[#top-n]
top _n_::
Generates the top *n* items from a sorted result. If your search has more than 1 measure, ThoughtSpot generates the top *n* items from the first measure in the search.
+
If you enter multiple measures in your search, ThoughtSpot sorts by the first measure. For example, if you search for `top 3 sales by product quantity purchased`, ThoughtSpot sorts by sales. If you change the search to sort by a different column, such as `top 3 sales by product sort by quantity purchased`, ThoughtSpot sorts by quantity purchased but preserves the top three ranked by sales.
+
If you search for "top _n_ by <column>", ThoughtSpot sorts by the column, then takes the top _n_ results. If you specify an attribute column, ThoughtSpot selects the results by reverse alphabetical order. We recommend using measure columns with the "top _n_ by" keyword.
+
Examples;;
+
----
top 10 sales rep revenue

top sales rep by count sales for average revenue > 10000

sales rep average revenue for each region top
----
