= Google Sheets Addon
:last_updated: 8/24/2022
:author: Naomi
:linkattrs:
:experimental:
:page-layout: default-seekwell
:description: SeekWell's Google Sheets Addon lets you and your team execute blocks directly from Google Sheets.

// More

NOTE: Before using the addon, make sure you are logged in to your browser with a single Google account. If you are logged in with multiple accounts (for example, your work and personal) there will be issues finding your {seekwell} account. If you're having issues, try using an "incognito" window.

== Introduction

{seekwell}'s Google Sheets Addon lets you and your team execute blocks directly from Google Sheets. Check it out link:https://gsuite.google.com/marketplace/app/seekwell_blocks/546600172375[here,window=_blank].

To get started, watch this demonstration, or follow the steps below:

video::3dUT7LXVh8M[youtube]

. Open Google Sheets and launch the {seekwell} add-on.

. Using the Search bar, search for the Block you'd like to execute. Under *Range*, enter the name of the desired Sheet to send your results. If the Sheet does not exist, {seekwell} will add it.

. To go back to your list of Blocks, select the *X* icon in the top right corner of the Add-on.

. Select the Block title to see it within link:https://app.seekwell.io/[{seekwell},window=_blank] and to make changes. After editing, return to the Google Sheets Add-on window and select *Refresh block*.

. To see the results of your edited block, select the name of the block within the Add-on, define the *Range*, and select the *Run* button.

== Working with parameters

video::ndzlcyWor4k[youtube]
