= Google Sheets
:last_updated: 8/22/2022
:author: Naomi
:linkattrs:
:experimental:
:page-layout: default-seekwell
:destination: Google Sheets
:description: Send data from SeekWell to Google Sheets.

// destination

== Send data from SQL to {destination}

[#prerequisite]
=== Prerequisites

Authorize the {destination} app link:https://seekwell.io/web_auth_sheets[here,window=_blank].

== Add {destination} as a destination

. After writing a SQL statement that pulls the data you want, select *Add destination* in the right sidebar and scroll down to select *{destination}*.

. Select a Spreadsheet, Sheet, and cell. If the Sheet does not exist, select *"" does not exist, add it?* +
{seekwell} will insert the new Sheet.

. Select *Run*.

. To set a schedule, select *Click to set Schedule* below *Repeat*.
+
video::4b13fe0c-7d1f-43b9-89b2-9b479f0e8c24.mp4[width=320, height=240]

== Appending data

You can also append results, instead of replacing the prior results, by checking off "Append". A few things to note:

* *You need to start your data in A1*. Use a formula if you need the data placed somewhere specific on another sheet (for example, put your daily data on `daily!A1` then reference `daily` in your `dashboard` sheet as a formula).

* You cannot have blank values in the first column.

* Checking the append option omits column names. If you need an easy way to get all the column names, just write without the Append option first and copy the column names.
+
video::append_to_sheet.mp4[width=320, height=240]
