= Getting started with {seekwell}
:last_updated: 8/26/22
:author: Naomi
:linkattrs:
:experimental:
:page-layout: default-seekwell
:description: You can write SQL and send the results to apps like Google Sheets, Slack, MS Teams, Hubspot, and more.

// Getting started

////
++++
<div style="position: relative; padding-bottom: 58.06451612903225%; height: 0;"><iframe src="https://www.loom.com/embed/2341af8796574626a671940302e8707d" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen style="position: absolute; top: 0; left: 0; width: 100%; height: 100%;"></iframe></div>
++++
////

Use {seekwell} to write SQL and send the results to apps like xref:google-sheets.adoc[Google Sheets], xref:microsoft-teams.adoc[MS Teams], xref:salesforce.adoc[Salesforce], xref:slack.adoc[Slack], and more. Blocks are the fundamental framework for working with {seekwell}. The four primary components of your block are the SQL that you write, the data source, the destination for your output, and the xref:parameters.adoc[parameter mapping].

////
Before you begin
////

== Blocks

Blocks can operate on the results of other blocks, so you can build complex processes to move data across databases and applications.

=== Create a Block

To create a block, follow these steps:

. Log in to link:https://app.seekwell.io/[{seekwell},window=_blank].

. Select the plus icon in the top-right of the screen and choose *New SQL*.

. Select *Untitled* and enter the title of your new Block.

=== Connect to a source

To connect to a new source, follow these steps:

. Open your Block.
. Under *Source* in the top right corner, select *Add new source*. If you have a previous connection, select the connection nickname under *Source* and scroll down to select *Add new source*.

. In the pop-up *New source* window, complete the following fields:
.. Flavor
.. Nickname
.. Account Name (exclusive to Snowflake connections)
.. Service Account Information in JSON (exclusive to BigQuery)
.. Host
.. Port
.. Username
.. Password
.. Warehouse (exclusive to Snowflake connections)
.. Database
.. Use SSL / Use SSH
+
NOTE: You must safelist the {seekwell} IP addresses (35.193.207.79 and 35.239.74.213) for the connection to work. For more information, see xref:safelisting-our-ip-address.adoc[].

. Select *Save*.

== Write your SQL statement

To input a SQL statement, follow these steps:

. Select *Write SQL here...* and enter your statement. Select the *Play* icon to run your query.

. In the section below the SQL statement, verify that your statement produces the desired results. Note that you can view your results in both chart and table form.

== Connect to a destination

To connect to a new destination, follow these steps:

. Under *Destination*, select *Add destination*. If you have previously selected destinations, select the destination name and scroll down to select *Add destination*.
 +
{seekwell} selects *Sheets* as the default destination. To send your results to a different destination, select *Sheets* and scroll down to select your new destination.

. Fill out the fields below your selected destination. For *Sheets*, fill out the following fields:
.. *Spreadsheet*: Select a spreadsheet or select *Create new Sheet*. If you do not see the desired spreadsheet destination, begin typing to search, or select *Refresh Sheets*.
.. *Sheet1*: Enter the page of the Spreadsheet to input your results. {seekwell} defaults to Sheet1.
.. *A1*: Enter the beginning cell to input your results. {seekwell} defaults to cell A1.
.. *Replace rows / Append rows*: If your selected Sheet has existing data, decide whether to replace rows with your results, or append your results.
.. *Include column names / Omit column names*: Decide whether to include or omit column names.

. Select *Save*.

. Select the *Play* icon to run your query and send the results to your chosen destination. The results appear in your destination within a few seconds.


== Set parameters [optional]

With parameters, you can inject data into your SQL statement. You can input plain text or  numbers, or inject data from Sheets or another block.

In this example, we demonstrate how to use parameters to add data to your block from Sheets. To set parameters for your block, follow these steps:

. Within your SQL statement, add a parameter.
+
[source]
----
select e.*
from dummy.events AS e
where 1=1
and e.email like '%{{email}}%'
limit 200
----

. As soon as you add a parameter to your SQL, the *Parameters* section appears in {seekwell}. Select *Sheets* as the *Type*.

. Select the Spreadsheet you want to grab the parameter value from and the *cell* link:https://developers.google.com/sheets/api/guides/concepts?utm_source=devtools#a1_notation[using A1 notation,window=_blank] (for example, `Sheet1!A1`). You can only use a single cell, except in the case of Postgres and Snowflake. If you need to reference multiple cells, use `and / or` statements.

. Run the query and results appear based on your parameters.


=== Related information

* xref:parameters.adoc[]
* xref:triggers.adoc[]
