= Sets (deprecated)
:last_updated: 8/23/2022
:author: Naomi
:linkattrs:
:experimental:
:page-layout: default-seekwell


// More

video::Dp76jQQpsIk[youtube]


Sets in {seekwell} allow you to create clean datasets for the rest of your team to use, and allow them to analyze data in your database without having to write code.

Let's walk through a demonstration of how to create a set, explore the set within {seekwell}, and send the results to an external business app.

== Create a {seekwell} Set

To create a Set within {seekwell}, follow these steps:

. Connect to your database. The *Source* dropdown displays all previously connected databases. If you do not see In this example, we connect to the demo database, `sw-replica`.

. Write your SQL query, for example:
+
[source]
----
select u.*
from dummy.users as u
where 1=1
----

. Test that you see the desired results by running your query.

. In the bottom right corner, select the *Edit set schema* icon, which looks like two curly brackets. {seekwell} automatically generates a schema for your SQL query.

. Using the *Edit set schema* window, you can add measures to your query, such as a `count` of paid users, by injecting a SQL attribute defining a `"sum(case when plan != 'basic' then 1 else 0 end)".

. Select *Run* to test your updated query schema displays the desired results.

== Explore sets in {seekwell}

To explore a set within {seekwell}, follow these steps:

. Type kbd:[`command`] / kbd:[`control`] + kbd:[`k`], then search for *Explore Sets*.

. Enter the name of your set in the Sets search bar.

. Search for the relevant measures to suit your business use case. In this example, to find the total number of plans, contrast by the number of paid plans, and group the results by week, you would search for: `DemoUsers.created_on_week` `DemoUsers.count` `DemoUsers.paid`.

. Type kbd:[`command`] + kbd:[`enter`], or select the *Run* icon to see your results. {seekwell} displays your results as a table by default. To see your results as a chart, select the *chart* icon.

. [Optional] Title the chart view of your search to save.

=== Send your results to an external app

To send the results of your exploration in Sets to an external app, follow these steps:

. Open the side-menu and select *Click to edit destination*.

. Fill in the details of your destination. For example, when sending to Google Sheets, you must enter the destination Spreadsheet, Sheet name, and cell number in A1 format.

. Run the query again. Your results appear in your destination app within seconds.
