= Tables
:last_updated: 8/26/2022
:author: Naomi
:linkattrs:
:experimental:
:page-layout: default-seekwell
:description: SeekWell tables let you easily update tables in your database.

// More

== Introduction

{seekwell} tables let you easily update tables in your database.

== Demo

video::G4TPy2oX3_k[youtube]

To edit tables in your database through {seekwell}, follow these steps:

. Type kbd:[`control`] / kbd:[`command`] + kbd:[`k`] and search for "Tables".

. On the page that appears, search for the title of the table you would like to update.

. Select the name of the table from the list.

. To edit any cell of the table, simply select it and begin to type. Pending changes appear above the table, to the right of the *Sync changes* button.

. To filter the table to more easily find the row(s) you need, select the *Filter* icon in the top right corner and select *+ Add filter*.
.. From the drop-down on the left, select the title of the column you want to filter on.
.. To select the filter condition, select *Is* and select a new operator from the list:
* Is
* Contains
* Does not contain
* Starts with
* Ends with
* Is null
* Is not null

.. Select *Value* and type in the value you want to filter for.

. To finalize your changes, select *Sync changes* in the top left corner. Your table automatically updates in your database.
