= ["GCP node overview"]
:last_updated: 11/18/2019
:permalink: /:collection/:path.html
:sidebar: mydoc_sidebar
:summary: Google Cloud Platform (GCP) can provide memory and CPU for your ThoughtSpot instance.

Your database capacity determines the number of instances you must have, and the instance network/storage requirements.
In addition, you can choose multiple virtual machines (VMs) based on your dataset size.

You must set up the appropriate Firewall Rules in your GCP environment for your ThoughtSpot deployment.
See the https://cloud.google.com/vpc/docs/firewalls[GCP Firewall Rules] article for configuration details.

You can find more information about appropriate Network ports for your ThoughtSpot deployment in the link:{{ site.baseurl}}/appliance/ports.html#[network ports reference].

== A little about GCP

GCP is a secure cloud services platform offered by Google.
Using ThoughtSpot in GCP allows you to easily add instances as your dataset grows.
You can do everything you'd normally want to do in a traditional data center with GCP.
It features an on-demand delivery of IT resources and applications through the Internet.
When you are connected to an instance, you can use it just like you use any other server.

Using GCP lets you develop and deploy applications faster since there is no need to manage hardware.
Therefore, it is easy to scale and manage computing capacity.

The ThoughtSpot image deploys on https://cloud.google.com/compute/docs/[Google Compute Engine], the GCP platform for creating and running VMs (_instances_) on Google Cloud infrastructure.
GCP and Google Compute Engine use https://cloud.google.com/iam/[Identity and Access Management (IAM)] roles to manage permissions to resources.
Google Compute engine instances and persistent disks are https://cloud.google.com/compute/docs/regions-zones/[zonal resources], and therefore must be in the same zone to work together.
