= Enable SSH access through Active Directory
:last_updated: 01-13-2020

You can enable Active Directory (AD) access on each ThoughtSpot node.

== Enable user access on a ThoughtSpot node through AD

In ThoughtSpot, you can enable Active Directory (AD) access on specified nodes of the cluster.
To enable AD access on the entire cluster, enable AD access on each node.
You must similarly configure all new nodes that you subsequently add to the cluster.

To enable system AD user access, issue the xref:tscli-command-ref.adoc#tscli-sssd-enable[tscli sssd enable] command:
[source]
----
tscli sssd enable --user <USER> --domain <DOMAIN>
----

Here, _`USER`_ is the user account you are enabling on the domain _`DOMAIN`_.

The system prompts for password credentials before completing the step.

NOTE: The user must have permission to join a computer or VM to the domain.

== Set sudo AD Group on a ThoughtSpot node

Just like enabling AD-based access on a node, you can enable `sudo` AD groups only on specific nodes.
To set AD group `sudo` access for the entire cluster, you must run the command on each node.
You must similarly configure all new nodes that you subsequently add to the cluster.

To enable `sudo` permissions for AD group, issue the xref:tscli-command-ref.adoc#tscli-sssd-set-sudo-group[tscli sssd set-sudo-group] command:
[source]
----
tscli sssd set-sudo-group <ACTIVE_DIRECTORY_GROUP_NAME>
----

== Clear sudo AD Group on a ThoughtSpot node

You may clear the `sudo` AD group only on the node where you run the command, not for the entire cluster.
To clear access for the entire cluster, you must run the command on each node.
You must similarly configure all new nodes that you subsequently add to the cluster.

To clear `sudo` permissions for the AD group, issue the xref:tscli-command-ref.adoc#tscli-sssd-clear-sudo-group[tscli sssd clear-sudo-group] command:
[source]
----
tscli sssd clear-sudo-group <ACTIVE_DIRECTORY_GROUP_NAME>
----

== Disable AD access on a ThoughtSpot node

You can disable AD access, individually on each node of the cluster.

To disable system AD user access, issue the xref:tscli-command-ref.adoc#tscli-sssd-disable[tscli sssd disable] command:
[source]
----
tscli sssd disable
----

NOTE: Running this command also removes the AD group from `sudo` list.

== Related Information

* The xref:tscli-command-ref.adoc#tscli-sssd[sssd command] in the `tscli` command reference
