= Introduction to administration
:last_updated: 12-28-2020

This guide covers all topics of special interest to application administrators.

This guide provides information for application administrators, or users with xref:logins.adoc[administrative access privileges].

Before addressing the major components of this guide, we recommend that you familiarize yourself with the general top-level xref:components.adoc[architecture] of the ThoughtSpot service.

Administrators are responsible for many facets of the ThoughtSpot service.
They are most frequently in charge of these common processes:

* xref:installation.adoc[Installation and setup of ThoughtSpot]
* xref:loading-intro.adoc[Loading and managing data]
* xref:groups-privileges.adoc[Managing users and groups]
* xref:security.adoc[Security]
* xref:sysadmin-overview.adoc[System administration]
* xref:choose-strategy.adoc[Backup and Restore]

Additionally, administrators are often involved in the following workflows:

* xref:data-modeling-intro.adoc[Data modeling]
* xref:worksheets.adoc[Using worksheets] to simplify search
* xref:query-on-query.adoc[Using views] for 'stacked' search; note that starting with Release 5.2, you can accomplish some aspects of search stacking by using the `IN` keyword; see xref:in-keyword-searches.adoc[Subquery search].
* xref:scheduled-pinboards.adoc[Managing scheduled jobs]
* xref:system-monitor.adoc[System monitoring]
* xref:troubleshooting-intro.adoc[Troubleshooting]
