= Packages installed with ThoughtSpot for Amazon Linux 2
:last_updated: 01/04/2020
:linkattrs:
:experimental:

View the packages necessary to deploy ThoughtSpot with Amazon Linux 2.

To successfully deploy ThoughtSpot in your organization, you must have the following packages on each node of your ThoughtSpot cluster: yum, python 3, and R.
When the Ansible playbook runs, it automatically installs them.

ThoughtSpot works with the latest version of each package; see the minimum supported version.

[#yum]
== Yum RPM packages

These are the required packages, and the minimum supported version.

include::partial$yum-rpm-packages.adoc[]

[#pip2]
== Python 2 packages

These are the required packages, and the minimum supported version.

include::partial$pip2-rpm-packages.adoc[]

[#pip3]
== Python 3 packages

These are the required packages, and the minimum supported version.

include::partial$pip3-rpm-packages.adoc[]

[#r]
== R packages

These are the required packages, and the minimum supported version.

include::partial$r-rpm-packages.adoc[]
