= ThoughtSpot deployment templates for Amazon Linux 2
:last_updated: 01/03/2021
:linkattrs:
:experimental:

Get the two primary tarball artifacts for configuring ThoughtSpot using Amazon Linux 2.


You must have the following artifacts to install or upgrade ThoughtSpot applications that run on Amazon Linux 2:

* The *Ansible tarball*, the *Terraform template*, the *Chef template*, and the *Puppet* template each contain a set of scripts for installing OS packages, dependencies, the ThoughtSpot CLI (tscli), and configuring your cluster (preparing the disks).
Choose *_one_* of these four templates, depending on which tool you have in your organization.
You can obtain one of these templates from your ThoughtSpot contact.
* The *Release tarball* contains the ThoughtSpot software binaries (`tar.gz`) of the release version you are installing or upgrading;
for example, ThoughtSpot Release 6.1.1.
You can obtain this file from the https://thoughtspot.egnyte.com/[ThoughtSpot secure file sharing system,window="_blank"].
We sent this information to you in our Welcome email.

== Next steps

Next, proceed to install:

* xref:al2-install-online.adoc[install ThoughtSpot in Amazon Linux 2 online clusters], where the hosts can connect to the public repositories to download the required packages
* xref:al2-install-offline.adoc[install ThoughtSpot in Amazon Linux 2 offline clusters], where the hosts cannot connect to the public repositories to download the required packages
