= Amazon Linux 2 installation prerequisites
:last_updated: 01/02/2021
:linkattrs:
:experimental:

Prepare the system and ThoughtSpot clusters for installation.

[options="interactive"]
.These are the general steps for installing ThoughtSpot on Amazon Linux 2:
* [ ] xref:set-up-hosts[1. Set up hosts for the ThoughtSpot cluster]
* [ ] xref:aws-ssm[2.(Optional) Set up AWS Systems Manager Agent]
* [ ] xref:partition-hosts[3. Partition the hosts]
* [ ] xref:enable-hosts[4. Enable the hosts to download Amazon Linux 2 packages]
* [ ] xref:enable-ansible[5. Enable an Ansible Control Server]
* [ ] xref:disable-selinux[6. Disable SELinux or run it in permissive mode]

[#set-up-hosts]
== Set up hosts for the ThoughtSpot cluster

Set up hosts for the ThoughtSpot cluster on Amazon Web Services.

. Refer to xref:aws-configuration-options.adoc[AWS configuration options] for the exact specification for the hosts:
 ** CPU
 ** memory
 ** disks
. Refer to xref:aws-launch-instance.adoc[Set up AWS resources for ThoughtSpot] to create and launch your AWS virtual machines.

[#aws-ssm]
== [Optional] Set up AWS Systems Manager Agent

If you plan to use the https://docs.aws.amazon.com/systems-manager/latest/userguide/ssm-agent.html[AWS SSM agent,window=“_blank”] as an alternative to SSH, create a new IAM role while creating VMs.
This IAM role must have an SSM policy to grant AWS SSM permission to perform actions on your instances.
Refer to https://docs.aws.amazon.com/systems-manager/latest/userguide/setup-instance-profile.html[Create an IAM instance profile for Systems Manager,window=“_blank”].

You must install the SSM agent on each node.
Refer to https://docs.aws.amazon.com/systems-manager/latest/userguide/sysman-manual-agent-install.html[Manually install SSM Agent on EC2 instances for Linux,window=“_blank”], if the SSM agent is not already on each node.

[#partition-hosts]
== Partition the hosts

Ensure that all ThoughtSpot hosts meet the following partition and sizing requirements.
All drives must be SSDs.

. At least 20 GB available on the root drive, for yum packages and system logs.
. At least 50 GB available for `/tmp`.
. At least 200 GB for ThoughtSpot installation, either on a secondary drive or as a separate partition on the root drive.
+
NOTE: This drive must be separate from the data drive(s).

[#enable-hosts]
== Enable the hosts to download Amazon Linux 2 packages

=== Repositories

[#yum-repository]
Yum repositories::
  You must enable the following Yum repositories in your cluster: `epel`, `nux-desktop`, `google-cloud-sdk`, and `azure-cli`.

[#python-repository]
Python repository::
  For Python, ensure that the machine is able to reach the `PyPI` repository located at https://pypi.python.org/[].

[#r-repository]
R repository::
  For R, ensure that the machine is able to reach the `CRAN` repository located at https://cran.rstudio.com/[].
  Make sure that you can download Amazon Linux 2 packages to all hosts, either from the xref:official-package-repository[official package repositories], or from a xref:mirror-repository[mirror repository] owned and managed by your organization
  If you cannot access the Amazon Linux 2 repositories, there is no mirror repository in your organization, or you are unable to access Yum, Python, or R repositories, please contact https://community.thoughtspot.com/customers/s/contactsupport[ThoughtSpot Support,window="_blank"].

[#official-package-repository]
Official package repositories::
  If the hosts of your ThoughtSpot cluster can access external repositories, either directly or through a proxy, your cluster is online.
  You can then proceed to download xref:yum-repository[Yum], xref:python-repository[Python], and xref:r-repository[R] package repositories.

[#mirror-repository]
Internal mirror repository::
  If the hosts of your ThoughtSpot cluster have access to an internal repository that mirrors the public repositories, copy the xref:yum-repository[Yum], xref:python-repository[Python], and xref:r-repository[R] package repositories to your hosts.

[#enable-ansible]
== Enable an Ansible Control Server

Configure an Ansible Control Server, on a separate host, to run the Ansible playbook that ThoughtSpot supplies.
You must install both `rsync` and Ansible on the Ansible Control Server host.

[#disable-selinux]
== Disable SELinux or run it in permissive mode

ThoughtSpot does not support policies that enforce SELinux.
We recommend that you disable SELinux, or run it in permissive mode.

== Next steps

Next, xref:al2-ts-artifacts.adoc[get ThoughtSpot artifacts].
