= Oracle connection reference
:last_updated: 07/6/2020

Learn about the fields used to create an Oracle connection with ThoughtSpot DataFlow.

Here is a list of the fields for an Oracle connection in ThoughtSpot DataFlow.
You need specific information to establish a seamless and secure connection.

== Connection properties

Connection name:: Name your connection.
+
Mandatory field. *Example:* + OracleConnection+++</dlentry>++++++<dlentry id="dataflow-oracle-conn-connection-type">+++Connection type:::: Choose the Oracle connection type. Mandatory field. *Example:* + Oracle+++</dlentry>++++++<dlentry id="dataflow-oracle-conn-host">+++Host:::: Specify the hostname or the IP address of the Oracle system Mandatory field. *Example:* + www.example.com+++</dlentry>++++++<dlentry id="dataflow-oracle-conn-port">+++Port:::: Specify the port associated to the Oracle system Mandatory field.
+
*Example:*
+
1234

User:: Specify the user id that will be used to connect to the Oracle system. This user should have necessary privileges to access the data in the databases.
+
Mandatory field.
+
*Example:*
+
userdi

Password:: Specify the password for the user.
+
Mandatory field.
+
*Example:*
+
pswrd234%!

Service name:: Service name is the TNS alias that you give when you remotely connect to your database and this Service name is recorded in Tnsnames.ora file on your clients and it can be the same as SID and you can also give it any other name you want.
+
Mandatory field.
+
*Example:*
+ idxdb03

Version:: Specify the Oracle version being connected to.
+
Optional field.
+
*Example:*
+
11.x
+
*Other notes:*
+
Advanced configuration

JDBC options:: Specify the options associated with the JDBC URL.
+
Optional field.
+
*Example:*
+
`jdbc:sqlserver://[serverName[\instanceName][:portNumber]]`
+
*Other notes:*
+ Advanced configuration

== Sync properties

Data extraction mode:: Specify the extraction type.
+
Mandatory field.
+
*Example:*
+
JDBC
+
*Valid Values:*
+
JDBC,OCI
+
*Default:*
+
JDBC

Column delimiter:: Specify the column delimiter character.
+
Mandatory field.
+
*Example:*
+
1
+
*Valid Values:*
+
Any printable ASCII character or decimal value for ASCII character
+
*Default:*
+
1

Null value:: Specifies the string literal that should indicate the null value in the extracted data. During the data load the column value matching this string will be loaded as null in the target.
+
Optional field.
+
*Example:*
+
NULL
+
*Valid Values:*
+
Any string literal
+
*Default:*
+
NULL

Enclosing character:: Specify if the text columns in the source data needs to be enclosed in quotes.
+
Optional field.
+
*Example:*
+
DOUBLE
+
*Valid Values:*
+
SINGLE, DOUBLE
+
*Default:*
+
DOUBLE
+
*Other notes:*
+
This is required if the text data has newline character or delimiter character.

Escape character:: Specify the escape character if using a text qualifier in the source data.
+
Optional field.
+
*Example:*
+
\"
+
*Valid Values:*
+
Any ASCII character
+
*Default:*
+
\"

Fetch size:: Specify the number of rows to be fetched at a time and processed in memory. If the value specified is zero then, all rows are extracted at once.
+
Mandatory field.
+
*Example:*
+
1000
+
*Valid Values:*
+
Any numeric value
+
*Default:*
+
1000

TS load options:: Specifies the parameters passed with the `tsload` command, in addition to the commands already included by the application. The format for these parameters is:
+
` --<param_1_name> <optional_param_1_value>`
+
` --<param_2_name> <optional_param_2_value>`
+
Optional field.
+
*Example:*
+
--max_ignored_rows 0
+
*Valid Values:*
+
--user "dbuser" --password "$DIWD" --target_database "ditest" --target_schema "falcon_schema"
+
*Default:*
+
--max_ignored_rows 0
