= Netezza connection reference
:last_updated: 07/6/2020

Learn about the fields used to create a Netezza connection with ThoughtSpot DataFlow.

Here is a list of the fields for a Netezza connection in ThoughtSpot DataFlow.
You need specific information to establish a seamless and secure connection.

== Connection properties

Connection name:: Name your connection.
+
Mandatory field.
+
*Example:*
+
NetezzaConnection

Connection type:: Choose the Netezza connection type.
+
Mandatory field.
+
*Example:*
+
Netezza

Host:: Specify the hostname or the IP address of the Netezza system.
+
Mandatory field.
+
*Example:*
+
www.example.com
+
Port:: Specify the port associated to the Netezza system.
+
Mandatory field.
+
*Example:*
+
1234

User:: Specify the user id that will be used to connect to the Netezza system. This user should have necessary privileges to access the data in the databases.
+
Mandatory field.
+
*Example:*
+
userdi

Password:: Specify the password for the User.
+
Mandatory field.
+
*Example:*
+
pswrd234%!

Version:: Specify the Netezza version being connected to.
+
Optional field.
+
*Example:*
+
7.x
+
*Other notes:*
+
Advanced Configuration

JDBC options:: Specify the options associated with the JDBC URL.
+
Optional field.
+
*Example:*
+
`jdbc:sqlserver://[serverName[\instanceName][:portNumber]]`
+
*Other notes:*
+
Advanced configuration

== Sync properties

Data extraction mode:: Specify the extraction type.
+
Mandatory field.
+
*Example:*
+
External table
+
*Valid Values:*
+
External table, JDBC
+
*Default:*
+
External Table

Column delimiter:: Specify the column delimiter character.
+
Mandatory field.
+
*Example:*
+
1
+
*Valid Values:*
+
Any printable ASCII character or decimal value for ASCII character
+
*Default:*
+
1

Enclosing character:: Specify if the text columns in the source data needs to be enclosed in quotes.
+
Optional field.
+
*Example:*
+
DOUBLE
+
*Valid Values:*
+
SINGLE, DOUBLE
+
*Default:*
+
DOUBLE
+
*Other notes:*
+
This is required if the text data has newline character or delimiter character.

Escape character:: Specify the escape character if using a text qualifier in the source data.
+
Optional field.
+
*Example:*
+
\"
+
*Valid Values:*
+
Any ASCII character
*Default:*
+
\"

Socket buffer size:: Specifies the chunk size at which to read the data from the source, expressed in bytes.
+
Optional field.
+
*Example:*
+
8
+
*Valid Values:*
+
Any numeric value
+
*Default:*
+
8

TS load options:: Specifies the parameters passed with the `tsload` command, in addition to the commands already included by the application. The format for these parameters is:
+
` --<param_1_name> <optional_param_1_value>`
+
` --<param_2_name> <optional_param_2_value>`
+
Optional field.
+
*Example:*
+
--max_ignored_rows 0
+
*Valid Values:*
+
--user "dbuser" --password "$DIWD" --target_database "ditest" --target_schema "falcon_schema"
+
*Default:*
+
--max_ignored_rows 0
