= Sync data through a MongoDB connection
:last_updated: 7/6/2020

After using ThoughtSpot DataFlow to establish a connection to a MongoDB database, you can create automatic data updates, to seamlessly refresh your data.

include::partial$sync-for-databases.adoc[]

. Specify the sync properties for MongoDB:
 ** xref:dataflow-mongodb-reference.adoc#dataflow-mongodb-sync-column-delimiter[Column delimiter]
 +
Specify the column delimiter character.
 ** xref:dataflow-mongodb-reference.adoc#dataflow-mongodb-sync-enclosing-character[Enclosing character]
 +
Specify if the text columns in the source data needs to be enclosed in quotes.
 ** xref:dataflow-mongodb-reference.adoc#dataflow-mongodb-sync-escape-character[Escape character]
 +
Specify the escape character if using a text qualifier in the source data.
 ** xref:dataflow-mongodb-reference.adoc#dataflow-mongodb-sync-ts-load-options[TS load options]
 +
Specify the parameters passed with the `tsload` command, in addition to the commands already included by the application.

+
See xref:dataflow-mongodb-reference.adoc#sync-properties[Sync properties] for details, defaults, and examples.
. Save your work by clicking *Save*.
+ Alternatively, click *Save and sync now* to save your work and sync data at the same time.
