= Add an Amazon Redshift database connection
:last_updated: 7/3/2020

You can add a connection to an Amazon Redshift database using ThoughtSpot DataFlow.

Follow these steps:

include::partial$add-database-connection.adoc[]

. After you select the Amazon Redshift *Connection type*, the rest of the connection properties appear.
 ** xref:dataflow-amazon-redshift-reference.adoc#dataflow-amazon-redshift-conn-connection-name[Connection name]
 +
Name your connection.
 ** xref:dataflow-amazon-redshift-reference.adoc#dataflow-amazon-redshift-conn-connection-type[Connection type]
 +
Choose the Amazon Redshsift connection type.
 ** xref:dataflow-amazon-redshift-reference.adoc#dataflow-amazon-redshift-conn-host[Host]
 +
Specify the hostname or the IP address of the Redshift system
 ** xref:dataflow-amazon-redshift-reference.adoc#dataflow-amazon-redshift-conn-port[Port]
 +
Specify the port associated to the Redshift system
 ** xref:dataflow-amazon-redshift-reference.adoc#dataflow-amazon-redshift-conn-user[User]
 +
Specify the user to connect to Amazon Redshift.
This user must have data access privileges.
 ** xref:dataflow-amazon-redshift-reference.adoc#dataflow-amazon-redshift-conn-password[Password]
 +
Specify the password for the User.
 ** xref:dataflow-amazon-redshift-reference.adoc#dataflow-amazon-redshift-conn-database[Database]
 +
Collection of information that is organized so that it can be easily accessed, managed and updated.
 ** xref:dataflow-amazon-redshift-reference.adoc#dataflow-amazon-redshift-conn-jdbc-options[JDBC options]
 +
Specify the options associated with the JDBC URL.

+
See xref:dataflow-amazon-redshift-reference.adoc#connection-properties[Connection properties] for details, defaults, and examples.
. Click *Create connection*.
