= Presto connection reference
:last_updated: 07/7/2020


Learn about the fields used to create a Presto connection with ThoughtSpot DataFlow.

Here is a list of the fields for a Presto connection in ThoughtSpot DataFlow.
You need specific information to establish a seamless and secure connection.

== Connection properties
+++<dlentry id="dataflow-presto-conn-connection-name">+++Connection name:::: Name your connection. Mandatory field. *Example:* + PrestoSQLConnection+++</dlentry>++++++<dlentry id="dataflow-presto-conn-connection-type">+++Connection type:::: Choose the Presto connection type. Mandatory field. *Example:* + Presto+++</dlentry>++++++<dlentry id="dataflow-presto-conn-host">+++Host:::: Specify the hostname or the IP address of the Presto system Mandatory field. *Example:* + www.example.com+++</dlentry>++++++<dlentry id="dataflow-presto-conn-port">+++Port:::: Specify the port associated to the Presto system Mandatory field. *Example:* + 1234+++</dlentry>++++++<dlentry id="dataflow-presto-conn-user-name">+++User name::::
Specify the user id that will be used to connect to the Presto system.
This user should have necessary privileges to access the data in the databases. Mandatory field. *Example:* + userdi+++</dlentry>++++++<dlentry id="dataflow-presto-conn-authentication-type">+++Authentication type::::
Specifies the type of security protocol to connect to the instance.
Based on the type of security select the authentication type and provide details. Mandatory field. *Example:* + SSL *Valid Values:* + No Auth, SSL, LDAP, KERBEROS *Default:* + No Auth+++</dlentry>++++++<dlentry id="dataflow-presto-conn-ssl-key-store-path">+++SSL key store path:::: Specify trust store path which is generated by server Optional field. *Example:* + trust store+++</dlentry>++++++<dlentry id="dataflow-presto-conn-ssl-key-store-password">+++SSL key store password:::: Specify password for key store which is generated by client which is created while generating key store file Optional field. *Example:* + password+++</dlentry>++++++<dlentry id="dataflow-presto-conn-ldap-password">+++Ldap password:::: Provide LDAP password to connect. Optional field. *Example:* + password+++</dlentry>++++++<dlentry id="dataflow-presto-conn-kerberos-remote-service-name">+++Kerberos remote service name:::: Hostname of the kerberos server, this is required to generate the krb.conf file Optional field. *Example:* + my_email@example.com+++</dlentry>++++++<dlentry id="dataflow-presto-conn-user-principal">+++User principal:::: To authenticate via a key-tab you must have supporting key-tab file which is generated by Kerberos Admin and also requires the user principal associated with Key-tab ( Configured while enabling Kerberos) Optional field. *Example:* + labuser@labdp.example.com+++</dlentry>++++++<dlentry id="dataflow-presto-conn-kerberos-config">+++Kerberos config:::: A Kerberos config explains the configuartion details used to connect to Kerberos authentication server. Optional field.name.example.com+++</dlentry>++++++<dlentry id="dataflow-presto-conn-user-keytab">+++User keytab:::: To authenticate via a key-tab you must have supporting key-tab file which is generated by Kerberos Admin and also requires the user principal associated with Key-tab ( Configured while enabling Kerberos) Optional field. *Example:* + /app/keytabs/labuser.keytab+++</dlentry>++++++<dlentry id="dataflow-presto-conn-catalog-name">+++Catalog name:::: Specify the catalog file name Mandatory field. *Example:* + direp *Other notes:* + Advanced Configuration+++</dlentry>++++++<dlentry id="dataflow-presto-conn-schema-name">+++Schema name:::: Specify the schema name of a database Mandatory field. *Example:* + dbrep *Other notes:* + Advanced Configuration+++</dlentry>++++++<dlentry id="dataflow-presto-conn-jdbc-options">+++JDBC options:::: Specify the options associated with the JDBC URL. Optional field. *Example:* + `jdbc:sqlserver://[serverName[\instanceName][:portNumber]]` *Other notes:* + Advanced configuration+++</dlentry>+++

== Sync properties
+++<dlentry id="dataflow-presto-sync-column-delimiter">+++Column delimiter:::: Specify the column delimiter character. Mandatory field. *Example:* + 1 *Valid Values:* + Any printable ASCII character or decimal value for ASCII character+++</dlentry>++++++<dlentry id="dataflow-presto-sync-null-value">+++Null value::::
Specifies the string literal that should indicate the null value in the extracted data.
During the data load the column value matching this string will be loaded as null in the target. Optional field. *Example:* + NULL *Valid Values:* + Any string literal+++</dlentry>++++++<dlentry id="dataflow-presto-sync-enclosing-character">+++Enclosing character:::: Specify if the text columns in the source data needs to be enclosed in quotes. Optional field. *Example:* + DOUBLE *Valid Values:* + SINGLE, DOUBLE *Other notes:* + This is required if the text data has newline character or delimiter character.+++</dlentry>++++++<dlentry id="dataflow-presto-sync-escape-character">+++Escape character:::: Specify the escape character if using a text qualifier in the source data. Optional field. *Example:* + \" *Valid Values:* + Any ASCII character+++</dlentry>++++++<dlentry id="dataflow-presto-sync-ts-load-options">+++TS load options::::
Specifies the parameters passed with the `tsload` command, in addition to the commands already included by the application.
The format for these parameters is: + ` --<param_1_name> <optional_param_1_value>` + ` --<param_2_name> <optional_param_2_value>` Optional field. *Example:* + --max_ignored_rows 0 *Valid Values:* + --user "dbuser" --password "$DIWD" --target_database "ditest" --target_schema "falcon_schema"+++</dlentry>+++
