= REST API connection reference
:last_updated: 11/25/2020


Learn about the fields used to create a REST API connection with ThoughtSpot DataFlow.

Here is a list of the fields for a REST API connection in ThoughtSpot DataFlow.
You need specific information to establish a seamless and secure connection.

== Connection properties
+++<dlentry id="dataflow-rest-api-conn-connection-name">+++Connection name:::: Name your connection. Mandatory field. *Example:* + RESTAPIConnection+++</dlentry>++++++<dlentry id="dataflow-rest-api-conn-connection-type">+++Connection type:::: Choose the REST API connection type. Mandatory field. *Example:* + REST API+++</dlentry>++++++<dlentry id="dataflow-rest-api-conn-authentication-type">+++Authentication type:::: Specify the type of authentication that is required to connect to the REST API service. Mandatory field. *Example:* + NONE *Valid Values:* + NONE, BASIC, or OAuth 2.0 *Default:* + NONE *Other notes:* +

* `NONE`: Credentials not required to connect to web service.
* `BASIC`: Must have Username and Password for authentication.
* `OAuth 2.0`: Must supply the access key/token to connect to the web service.+++</dlentry>++++++<dlentry id="dataflow-rest-api-conn-rest-api-base-url">+++REST API base URL:::: Specify the end point URL to access REST API web-service. Mandatory field.+++</dlentry>++++++<dlentry id="dataflow-rest-api-conn-user">+++User::::
Specify the user who connects to the Rest web service.
This user must have data access privileges.
Mandatory field.
+ For BASIC authentication type only. *Example:* + userid+++</dlentry>++++++<dlentry id="dataflow-rest-api-conn-password">+++Password:::: Specify the password for the User.
Mandatory field.
+ For BASIC authentication type only. *Example:* + pswrd234%!+++</dlentry>++++++<dlentry id="dataflow-rest-api-conn-obtain-access-token">+++Obtain access token:::: Select this option to use access key/token to connect to the REST API web-service
Optional field.
+ For OAuth 2.0 authentication type only.+++</dlentry>++++++<dlentry id="dataflow-rest-api-conn-access-token">+++Access token:::: Specify the access token to authenticate REST API.
Optional field.
+ For OAuth 2.0 authentication type only.+++</dlentry>++++++<dlentry id="dataflow-rest-api-conn-refresh-token">+++Refresh token:::: Specify the refresh token to authenticate REST API.
Optional field.
+ For OAuth 2.0 authentication type only.+++</dlentry>++++++<dlentry id="dataflow-rest-api-conn-oauth-client-id">+++OAuth client ID:::: Specify the OAuth client ID
Mandatory field.
+ Displayed only when "obtain access token" check-box is selected+++</dlentry>++++++<dlentry id="dataflow-rest-api-conn-mask-client-secret">+++Mask client secret:::: Specify the OAuth client secret
Mandatory field.
+ Displayed only when "obtain access token" check-box is selected+++</dlentry>++++++<dlentry id="dataflow-rest-api-conn-oauth-authorization-url">+++OAuth authorization URL:::: Specify the OAuth authorization URL
Mandatory field.
+ Displayed only when "obtain access token" check-box is selected+++</dlentry>++++++<dlentry id="dataflow-rest-api-conn-oauth-accesstoken-url">+++OAuth accesstoken URL:::: Specify the OAuth accesstoken URL
Mandatory field.
+ Displayed only when "obtain access token" check-box is selected+++</dlentry>++++++<dlentry id="dataflow-rest-api-conn-scope">+++Scope:::: Specify the number of users to access the account
Mandatory field.
+ Displayed only when "obtain access token" check-box is selected+++</dlentry>++++++<dlentry id="dataflow-rest-api-conn-callback-url">+++Callback URL:::: Secured domain URL of the repo which is used to register in REST API
Mandatory field.
+ Displayed only when "obtain access token" check-box is selected+++</dlentry>++++++<dlentry id="dataflow-rest-api-conn-rest-api-parameters">+++REST API parameters:::: When adding REST API parameters, click *Add*, and then specify the `Parameter name`, `Value`, and if the parameter is a `Header`. Optional field.+++</dlentry>+++

== Sync properties
+++<dlentry id="dataflow-rest-api-sync-column-delimiter">+++Column delimiter:::: Specify the column delimiter character. Mandatory field. *Example:* + 1 *Valid Values:* + Any printable ASCII character or decimal value for ASCII character *Default:* + 1+++</dlentry>++++++<dlentry id="dataflow-rest-api-sync-enclosing-character">+++Enclosing character:::: Specify if the text columns in the source data needs to be enclosed in quotes. Optional field. *Example:* + DOUBLE *Valid Values:* + SINGLE, DOUBLE *Default:* + DOUBLE *Other notes:* + This is required if the text data has newline character or delimiter character.+++</dlentry>++++++<dlentry id="dataflow-rest-api-sync-escape-character">+++Escape character::::
Specify this if the text qualifier is mentioned.
This should be the character which escapes the text qualifier character in the source data. Optional field. *Example:* + \" *Valid Values:* + Any ASCII character *Default:* + \"+++</dlentry>++++++<dlentry id="dataflow-rest-api-sync-null-value">+++Null value::::
Specifies the string literal that indicates the null value in the extracted data.
During the data load, the column value matching this string loads as null in the target. Optional field. *Example:* + NULL *Valid Values:* + Any string literal *Default:* + NULL+++</dlentry>++++++<dlentry id="dataflow-rest-api-sync-ts-load-options">+++TS load options::::
Specifies the parameters passed with the `tsload` command, in addition to the commands already included by the application.
The format for these parameters is: + ` --<param_1_name> <optional_param_1_value>` + ` --<param_2_name> <optional_param_2_value>` Optional field. *Example:* + `--max_ignored_rows 0` *Valid Values:* +  + ` --null_value ""` + ` --escape_character ""` + ` --max_ignored_rows 0` *Default:* + ` --max_ignored_rows 0`+++</dlentry>+++
