= Add a Splice Machine database connection
:last_updated: 7/7/2020

You can add a connection to a Splice Machine database using ThoughtSpot DataFlow.

Follow these steps:

include::partial$add-database-connection.adoc[]

. After you select the Splice Machine *Connection type*, the rest of the connection properties appear.
 ** xref:dataflow-splice-machine-reference.adoc#dataflow-splice-machine-conn-connection-name[Connection name]
 +
Name your connection.
 ** xref:dataflow-splice-machine-reference.adoc#dataflow-splice-machine-conn-connection-type[Connection type]
 +
Choose the Splice Machine connection type.
 ** xref:dataflow-splice-machine-reference.adoc#dataflow-splice-machine-conn-host[Host]
 +
Specify the hostname or the IP address of the Splice Machine system
 ** xref:dataflow-splice-machine-reference.adoc#dataflow-splice-machine-conn-port[Port]
 +
Specify the port associated with the Splice Machine system
 ** xref:dataflow-splice-machine-reference.adoc#dataflow-splice-machine-conn-user[User]
 +
Specify the user id that will be used to connect to the Splice Machine system. This user should have necessary privileges to access the data in the databases.
 ** xref:dataflow-splice-machine-reference.adoc#dataflow-splice-machine-conn-password[Password]
 +
Specify the password for the User
 ** xref:dataflow-splice-machine-reference.adoc#dataflow-splice-machine-conn-database[Database]
 +
Collection of information that is organized so that it can be easily accessed, managed and updated.
 ** xref:dataflow-splice-machine-reference.adoc#dataflow-splice-machine-conn-hadoop-version[Hadoop version]
 +
Specify the version of Hadoop you are using
 ** xref:dataflow-splice-machine-reference.adoc#dataflow-splice-machine-sync-hdfs-host[HDFS host]
 +
Specify the hostname or the IP address of the HDFS
 ** xref:dataflow-splice-machine-reference.adoc#dataflow-splice-machine-sync-hdfs-port[HDFS port]
 +
Specify the port associated to the HDFS
 ** xref:dataflow-splice-machine-reference.adoc#dataflow-splice-machine-sync-hdfs-temp-location[HDFS temp location]
 +
Specify the HDFS location for creating temp directory
 ** xref:dataflow-splice-machine-reference.adoc#dataflow-splice-machine-conn-jdbc-options[JDBC options]
 +

 Specify the options associated with the JDBC URL.

+
See xref:dataflow-splice-machine-reference.adoc#connection-properties[Connection properties] for details, defaults, and examples.
. Click *Create connection*.
