= Apache Parquet connection reference
:last_updated: 09/14/2020


Learn about the fields used to create an Apache Parquet connection with ThoughtSpot DataFlow.

Here is a list of the fields for an Apache Parquet connection in ThoughtSpot DataFlow.
You need specific information to establish a seamless and secure connection.

== Connection properties
+++<dlentry id="dataflow-apache-parquet-conn-connection-name">+++Connection name:::: Name your connection. Mandatory field. *Example:* + ApacheParquetConnection+++</dlentry>++++++<dlentry id="dataflow-apache-parquet-conn-connection-type">+++Connection type:::: Choose the Apache Parquet connection type. Mandatory field. *Example:* + Apache Parquet+++</dlentry>++++++<dlentry id="dataflow-apache-parquet-conn-file-location">+++File location:::: Specify the base location of the file on the server. Mandatory field. *Example:* + /home/admin/dataflow/data+++</dlentry>++++++<dlentry id="dataflow-apache-parquet-conn-files-on-remote-location">+++Files on remote location:::: Specify if the files on remote server. Mandatory field. *Default:* + No *Other notes:* + These are under Advanced configuration+++</dlentry>++++++<dlentry id="dataflow-apache-parquet-conn-protocol">+++Protocol:::: Select the required remote server connection
Mandatory field.
+ For remote location files only. *Example:* + FTP *Valid Values:* + FTP, SFTP *Default:* + FTP+++</dlentry>++++++<dlentry id="dataflow-apache-parquet-conn-authentication-type">+++Authentication type:::: Specify the authentication type for SFTP Protocol
Mandatory field.
+ For SFTP protocol only *Example:* + Password *Valid Values:* + Key, Password *Default:* + Password+++</dlentry>++++++<dlentry id="dataflow-apache-parquet-conn-host">+++Host:::: Specify the Hostname or the IP address of the remote server
Mandatory field.
+ For remote location files only. *Example:* + www.example.com+++</dlentry>++++++<dlentry id="dataflow-apache-parquet-conn-port">+++Port:::: Specify the Port to connect the remote server
Mandatory field.
+ For remote location files only. *Example:* + 1234+++</dlentry>++++++<dlentry id="dataflow-apache-parquet-conn-user">+++User::::
Specify the user to connect to remote server.
This user must have data access privileges.
Mandatory field.
+ For remote location files only. *Example:* + userdi+++</dlentry>++++++<dlentry id="dataflow-apache-parquet-conn-password">+++Password:::: Specify the password.
Optional field.
+ For remote location files only, when using password authentication. *Example:* + pswrd234%!+++</dlentry>++++++<dlentry id="dataflow-apache-parquet-conn-key-file">+++Key file:::: Specify the key file and its fully qualified path.
Mandatory field.
+ For remote location files only, when using key authentication. *Example:* + /app/key/sftp.key+++</dlentry>++++++<dlentry id="dataflow-apache-parquet-conn-passphrase-for-key">+++Passphrase for key:::: Specify the passphrase for the key file.
Optional field.
+ For remote location files only, when using key authentication. *Example:* + !hello *Other notes:* + Advanced configuration+++</dlentry>+++

== Sync properties
+++<dlentry id="dataflow-apache-parquet-sync-enclosing-character">+++Enclosing character:::: Specify if the text columns in the source data needs to be enclosed in quotes. Optional field. *Example:* + Single *Valid Values:* + Single, Double, Empty *Default:* + Empty+++</dlentry>++++++<dlentry id="dataflow-apache-parquet-sync-">+++Escape character::::
Specify escape characer if data uses text qualifier is mentioned.
This should be the character which escapes the text qualifier character in the source data. Optional field. *Example:* + \\ *Valid Values:* + Any ASCII character *Default:* + Empty+++</dlentry>++++++<dlentry id="dataflow-apache-parquet-sync-">+++Null value::::
Specifies the string literal indicates the null value for a column.
During the data load, the column value matching this string will be loaded as null in the target. Optional field. *Example:* + NULL *Valid Values:* + Any string literal *Default:* + NULL+++</dlentry>++++++<dlentry id="dataflow-apache-parquet-sync-">+++Date style:::: Specifies how to interpret the date format Optional field. *Example:* + YMD *Valid Values:* + `YMD`, `MDY`, `DMY`, `DMONY`, `MONDY`, `Y2MD`, `MDY2`, `DMY2`, `DMONY2`, and `MONDY2` *Default:* + `YMD` *Other notes:* + `MDY`: 2-digit month, 2-digit day, 4-digit year + `DMY`: 2-digit month, 2-digit day, 4-digit year + `DMONY`: 2-digit day, 3-character month name, 4-digit year + `MONDY`: 3-character month name, 2-digit day, 4-digit year + `Y2MD`: 2-digit year, 2-digit month, 2-digit day + `MDY2`: 2-digit month, 2-digit day, 2-digit year + `DMY2`: 2-digit day, 2-digit month, 2-digit year + `DMONY2`: 2-digit day, 3-character month name, 2-digit year + `MONDY2`: 3-character month name, 2-digit day, 2-digit year+++</dlentry>++++++<dlentry id="dataflow-apache-parquet-sync-">+++Date delimiter:::: Specifies the separator used in the date format. Optional field. *Example:* + - *Valid Values:* + Any printable ASCII character *Default:* + -+++</dlentry>++++++<dlentry id="dataflow-apache-parquet-sync-">+++Time style:::: Specifies the format of the time portion in the data. Optional field. *Example:* + 24HOUR *Valid Values:* + 12 Hour, 24 Hour *Default:* + 24HOUR+++</dlentry>++++++<dlentry id="dataflow-apache-parquet-sync-">+++Time delimiter:::: Specifies the character used as separate the time components. Optional field. *Example:* + : *Valid Values:* + Any printable ASCII character *Default:* + :+++</dlentry>++++++<dlentry id="dataflow-apache-parquet-sync-">+++Skip trailer rows:::: Skip trailer row while processing the data Optional field. *Example:* + 5 *Valid Values:* + Any numeric value *Default:* + 0+++</dlentry>++++++<dlentry id="dataflow-apache-parquet-sync-">+++Reader encoder:::: Specify the encoding format of the source system. Optional field. *Example:* + UFT-8 *Valid Values:* + ISO-8859-1, UTF-16, UTF-16BE, WINDOWS-1252 *Default:* + UFT-8+++</dlentry>++++++<dlentry id="dataflow-apache-parquet-sync-">+++TS load options::::
Specify additional parameters passed with the `tsload` command.
The format for these parameters is: + `--<param_1_name> <optional_param_1_value>` Optional field. *Example:* + `--max_ignored_rows 0` *Valid Values:* +  + ` --null_value ""` + ` --escape_character ""` + ` --max_ignored_rows 0` *Default:* + ` --max_ignored_rows 0`+++</dlentry>++++++<dlentry id="dataflow-apache-parquet-sync-boolean-representation">+++Boolean representation:::: Specifies the representation of data in the boolean field Optional field. *Example:* + true_false *Valid Values:* + true_false, T_F, 1_0, T_NULL *Default:* + true_false+++</dlentry>+++
