= Overview of data modeling settings
:last_updated: 11/15/2019


Learn about data modeling settings.

You can change data modeling settings in two ways, both of which change the model.
If you want to make a few small changes, you should xref:model-data-ui.adoc[make them in the ThoughtSpot application].
If you want to make many changes xref:edit-model-file.adoc[you should edit the modeling file].
Whether you are changing data modeling settings using the modeling file or the Web interface, the settings and their accepted values are the same.

== Modeling settings

The following index includes mutable data modeling settings that you can apply to columns, both tables and worksheets.

|===
| Setting&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; | Description

| xref:change-column-basics.adoc#change-the-column-name#[Column Name]
| Sets the name of the column to be used in searches.

| xref:change-column-basics.adoc#change-column-description[Description]
| Adds a text description of what the column contains.

| xref:datatypes.adoc[Data Type]
| *Read only.* Shows the column's data type.

| xref:change-column-basics.adoc#change-column-type[Column Type]
| Sets the type of column, either `ATTRIBUTE` or `MEASURE`.

| link:change-aggreg-additive.adoc[Additive]
| Controls the type of aggregations that will be available for a column.

| link:change-aggreg-additive.adoc[Aggregation]
| Sets the default aggregation type for a column.

| link:change-visibility-synonym.adoc[Hidden]
| Sets the visibility of a column.

| link:change-visibility-synonym.adoc[Synonyms]
| Adds synonyms that can be used in the search bar to refer to a column.

| link:spotiq-data-model-preferences.adoc[SpotIQ Preference]
| Excludes specified columns from SpotIQ analyses.
By Default, all columns are included in SpotIQ.

| link:change-index.adoc[Index Type]
| Sets the type of index that will be created for a column.

| link:model-geo-data.adoc[Geo Config]
| Enables a column to be used in GeoMap visualizations.

| link:change-index.adoc[Index Priority]
| Changes the priority of a column in search suggestions.

| link:set-format-pattern-numbers.adoc[Format Pattern]
| Specifies the format to use for numeric values or dates that show in the column.

| link:set-format-pattern-numbers.html#set-currency-type[Currency Type]
| Specifies the format of currencies in a column.

| link:attributable-dimension.adoc[Attribution Dimension]
| Only applies to tables that join over a xref:chasm-trap.adoc[Chasm Trap].
Designates whether the tables depend on this column for attribution.
You cannot change the attribution dimension in the modeling file.
You can only configure it on a table-by-table basis.

| xref:set-custom-calendar.adoc[Calendar Type]
| Specifies what type of calendar a date type column uses.
It can be Gregorian calendar (default), a fiscal calendar, or any custom calendar.

| link:set-entity-category.adoc[Entity Category]
| Specifies how to categorize the data in the column: person, place, time, and so on.

|===

== Data modeling best practices

As a best practice, make any data modeling settings in the table when you will be creating multiple worksheets that use that table.
This way, you won't have to make the same settings in each worksheet.
The settings will be inherited when you create worksheets that uses columns from the table.

If you have settings that only apply in the context of a particular worksheet, make those settings in the worksheet rather than in the underlying table(s).

Note that if you make your settings at the table level, and then create a worksheet that uses columns from the table, the settings are inherited from the table at the point in time that the worksheet is created.
If you then go back and change the settings at the table level, your changes will not be reflected in the worksheet.

If you want the worksheet to have the changes you made at the table level, you must drop those columns from the worksheet and re-add them.
Then save the worksheet.
At this point, the new settings will be used in the worksheet.
Note that any saved answers or pinboards based on the worksheet may display differently because of your changes.
For example, if you've changed the GeoMap setting from "None" to "Country", you will now see a map where before you might have seen a table.

== Related information

* xref:data-modeling-intro.adoc[Model the data for searching]
* xref:model-geo-data.adoc[Add a geographical data setting for a column]
