= Add a Google BigQuery database connection
:last_updated: 7/1/2020

You can add a connection to a Google BigQuery database using ThoughtSpot DataFlow.

Follow these steps:

include::partial$add-database-connection.adoc[]

. After you select the Google BigQuery *Connection type*, the rest of the connection properties appear.
+
Depending on your choice of authentication mechanism, you may use different properties.

 ** xref:dataflow-google-bigquery-reference.adoc#dataflow-google-bigquery-conn-project-id[Project id]
 +
The identification number given to particular project and its always unique.
 ** xref:dataflow-google-bigquery-reference.adoc#dataflow-google-bigquery-conn-authentication-type[Authentication type]
 +
It can be either Service Account or Access Tokens
 ** xref:dataflow-google-bigquery-reference.adoc#dataflow-google-bigquery-conn-service-account-key/access-token[Service account key/access Token]
 +
Provide the Service Account key when authentication type is selected as Service account and token when access token is selected as authentication type.
 ** xref:dataflow-google-bigquery-reference.adoc#dataflow-google-bigquery-conn-query-priority[Query priority]
 +
Specify the time duration to run the query and it can be either Interactive or Batch.
 ** xref:dataflow-google-bigquery-reference.adoc#dataflow-google-bigquery-conn-use-proxy[Use proxy]+
If required, to use a proxy, select the check box Use Proxy and provide the details
 ** xref:dataflow-google-bigquery-reference.adoc#dataflow-google-bigquery-conn-host[Host]
 +
Specify the hostname or the IP address of the BigQuery system For proxy authentication only.
 ** xref:dataflow-google-bigquery-reference.adoc#dataflow-google-bigquery-conn-port[Port]
 +
Specify the port associated to the BigQuery system For proxy authentication only.
 ** xref:dataflow-google-bigquery-reference.adoc#dataflow-google-bigquery-conn-protocol[Protocol]
 +
It can be either http or https For proxy authentication only.
 ** xref:dataflow-google-bigquery-reference.adoc#dataflow-google-bigquery-conn-jdbc-options[JDBC options]
 +
Specify the options associated with the JDBC URL.

+
See xref:dataflow-google-bigquery-reference.adoc#connection-properties[Connection properties] for details, defaults, and examples.

. Click *Create connection*.
