= Add an HDFS connection
:last_updated: 7/7/2020

You can add a connection to the HDFS file system using ThoughtSpot DataFlow.

Follow these steps:

include::partial$add-database-connection.adoc[]

. After you select the File *Connection type*, the rest of the connection properties appear.
+
Depending on your choice of authentication mechanism, you may use different properties.

 ** xref:dataflow-hdfs-reference.adoc#dataflow-hdfs-conn-connection-name[Connection name]
 +
Name your connection.
 ** xref:dataflow-hdfs-reference.adoc#dataflow-hdfs-conn-connection-type[Connection type]
 +
Choose the Google BigQuery connection type.
 ** xref:dataflow-hdfs-reference.adoc#dataflow-hdfs-conn-user[User]
 +
Specify the user to connect to HDFS file system. This user must have data access privileges.
For Hive security with simple, LDAP, and SSL authentication only.
 ** xref:dataflow-hdfs-reference.adoc#dataflow-hdfs-conn-hadoop-distribution-[Hadoop distribution]
 +
Provide the distribution of Hadoop being connected to + Mandatory field.
 ** xref:dataflow-hdfs-reference.adoc#dataflow-hdfs-conn-distribution-version[Distribution version]
 +
Provide the version of the Distribution chosen above + Mandatory field.
 ** xref:dataflow-hdfs-reference.adoc#dataflow-hdfs-conn-hadoop-conf-path[Hadoop conf path]
 +
By default, the system picks the Hadoop configuration files from the HDFS. To override, specify an alternate location.
Applies only when using configuration settings that are different from global Hadoop instance settings.
 ** xref:dataflow-hdfs-reference.adoc#dataflow-hdfs-conn-hdfs-ha-configured[HDFS HA configured]
 +
Enables High Availability for HDFS + Optional field.
 ** xref:dataflow-hdfs-reference.adoc#dataflow-hdfs-conn-hdfs-name-service[HDFS name service]
 +
The logical name of given to HDFS nameservice.
+
Mandatory field. For HDFS HA only.
 ** xref:dataflow-hdfs-reference.adoc#dataflow-hdfs-conn-hdfs-name-node-ids[HDFS name node IDs]
 +
Provides the list of NameNode IDs separted by comma and DataNodes use this property to determine all the NameNodes in the cluster.
XML property name is `dfs.ha.namenodes.dfs.nameservices`.
For HDFS HA only.
 ** xref:dataflow-hdfs-reference.adoc#dataflow-hdfs-conn-rpc-address-for-namenode1[RPC address for namenode1]
 +
To specify the fully-qualified RPC address for each listed NameNode and defined as `dfs.namenodes.rpc-address.dfs.nameservices.name_node_ID_1>`.
For HDFS HA only.
 ** xref:dataflow-hdfs-reference.adoc#dataflow-hdfs-conn-rpc-address-for-namenode2[RPC address for namenode2]
 +
To specify the fully-qualified RPC address for each listed NameNode and defined as `dfs.namenode.rpc-address.dfs.nameservices.name_node_ID_2`.
For HDFS HA only.
 ** xref:dataflow-hdfs-reference.adoc#dataflow-hdfs-conn-dfs-host[DFS host]
 +
Specify the DFS hostname or the IP address + Mandatory field.
For when _not_ using HDFS HA.
 ** xref:dataflow-hdfs-reference.adoc#dataflow-hdfs-conn-dfs-port[DFS port]
 +
Specify the associated DFS port + Mandatory field.
For when _not_ using HDFS HA.
 ** xref:dataflow-hdfs-reference.adoc#dataflow-hdfs-conn-default-hdfs-location[Default HDFS location]
 +
Specify the location for the default source/target location + Mandatory field.
 ** xref:dataflow-hdfs-reference.adoc#dataflow-hdfs-conn-temp-hdfs-location[Temp HDFS location]
 +
Specify the location for creating temp directory + Mandatory field.
 ** xref:dataflow-hdfs-reference.adoc#dataflow-hdfs-conn-hdfs-security-authentication[HDFS security authentication]
 +
Select the type of security being enabled + Mandatory field.
 ** xref:dataflow-hdfs-reference.adoc#dataflow-hdfs-conn-hadoop-rpc-protection[Hadoop RPC protection]
 +
Hadoop cluster administrators control the quality of protection using the configuration parameter hadoop.rpc.protection + Mandatory field.
For DFS security authentication with Kerberos only.
 ** xref:dataflow-hdfs-reference.adoc#dataflow-hdfs-conn-hive-principal[Hive principal]
 +
Principal for authenticating hive services + Mandatory field.
 ** xref:dataflow-hdfs-reference.adoc#dataflow-hdfs-conn-user-principal[User principal]
 +
To authenticate via a key-tab you must have supporting key-tab file which is generated by Kerberos Admin and also requires the user principal associated with Key-tab ( Configured while enabling Kerberos) + Mandatory field.
 ** xref:dataflow-hdfs-reference.adoc#dataflow-hdfs-conn-user-keytab[User keytab]
 +
To authenticate via a key-tab you must have supporting key-tab file which is generated by Kerberos Admin and also requires the user principal associated with Key-tab ( Configured while enabling Kerberos) + Mandatory field.
 ** xref:dataflow-hdfs-reference.adoc#dataflow-hdfs-conn-kdc-host[KDC host]
 +
Specify KDC Host Name where as KDC (Kerberos Key Distribution Center) is a service than runs on a domain controller server role (Configured from Kerbores configuration-/etc/krb5.conf ) + Mandatory field.
 ** xref:dataflow-hdfs-reference.adoc#dataflow-hdfs-conn-default-realm[Default realm]
 +
A Kerberos realm is the domain over which a Kerberos authentication server has the authority to authenticate a user, host or service (Configured from Kerbores configuration-/etc/krb5.conf ) + Mandatory field.

+
See xref:dataflow-hdfs-reference.adoc#connection-properties[Connection properties] for details, defaults, and examples.

. Click *Create connection*.
