= Presto connection reference
:last_updated: 07/7/2020

Learn about the fields used to create a Presto connection with ThoughtSpot DataFlow.

Here is a list of the fields for a Presto connection in ThoughtSpot DataFlow.
You need specific information to establish a seamless and secure connection.

== Connection properties

Connection name:: Name your connection.
+
Mandatory field.
+
*Example:*
+
PrestoSQLConnection

Connection type:: Choose the Presto connection type.
+
Mandatory field.
+*Example:*
+
Presto

Host:: Specify the hostname or the IP address of the Presto system.
+
Mandatory field.
+
*Example:*
+
www.example.com

Port:: Specify the port associated to the Presto system.
+
Mandatory field.
+
*Example:*
+
1234

User name:: Specify the user id that will be used to connect to the Presto system. This user should have necessary privileges to access the data in the databases.
+
Mandatory field. +
*Example:*
+
userdi

Authentication type:: Specifies the type of security protocol to connect to the instance. Based on the type of security select the authentication type and provide details.
+
Mandatory field.
+
*Example:*
+
SSL
+
*Valid Values:*
+
No Auth, SSL, LDAP, KERBEROS
+
*Default:*
+
No Auth

SSL key store path:: Specify trust store path which is generated by server.
+
Optional field.
+
*Example:*
+
trust store

SSL key store password:: Specify password for key store which is generated by client which is created while generating key store file.
+
Optional field.
*Example:*
+
password

Ldap password:: Provide LDAP password to connect.
+
Optional field.
+
*Example:*
+
password

Kerberos remote service name:: Hostname of the kerberos server, this is required to generate the krb.conf file.
+
Optional field.
+
*Example:*
+
my_email@example.com

User principal:: To authenticate via a key-tab you must have supporting key-tab file which is generated by Kerberos Admin and also requires the user principal associated with Key-tab (Configured while enabling Kerberos).
+
Optional field.
+
*Example:*
+
labuser@labdp.example.com

Kerberos config:: A Kerberos config explains the configuartion details used to connect to Kerberos authentication server.
+
Optional field.
+
*Example*
name.example.com

User keytab:: To authenticate via a key-tab you must have supporting key-tab file which is generated by Kerberos Admin and also requires the user principal associated with Key-tab (Configured while enabling Kerberos).
+
Optional field.
+
*Example:*
+
/app/keytabs/labuser.keytab

Catalog name:: Specify the catalog file name.
+
Mandatory field.
+
*Example:*
+
direp
+
*Other notes:*
+
Advanced Configuration

Schema name:: Specify the schema name of a database.
+
Mandatory field.
+
*Example:*
+
dbrep *Other notes:*
+
Advanced Configuration
+
JDBC options:: Specify the options associated with the JDBC URL.
+
Optional field.
+
*Example:*
+
`jdbc:sqlserver://[serverName[\instanceName][:portNumber]]`
+
*Other notes:*
+
Advanced configuration

== Sync properties
Column delimiter:: Specify the column delimiter character.
+
Mandatory field.
+
*Example:*
+
1
+
*Valid Values:*
+
Any printable ASCII character or decimal value for ASCII character

Null value:: Specifies the string literal that should indicate the null value in the extracted data. During the data load the column value matching this string will be loaded as null in the target.
+
Optional field. +
*Example:*
+
NULL
+
*Valid Values:*
+
Any string literal

Enclosing character:: Specify if the text columns in the source data needs to be enclosed in quotes.
+
Optional field.
+
*Example:*
+
DOUBLE
+
*Valid Values:*
+
SINGLE, DOUBLE
+
*Other notes:*
+
This is required if the text data has newline character or delimiter character.

Escape character:: Specify the escape character if using a text qualifier in the source data.
+
Optional field.
+
*Example:*
+
\"
+
*Valid Values:*
+
Any ASCII character

TS load options:: Specifies the parameters passed with the `tsload` command, in addition to the commands already included by the application. The format for these parameters is:
+
` --<param_1_name> <optional_param_1_value>`
+
` --<param_2_name> <optional_param_2_value>`
+
Optional field.
+
*Example:*
+
--max_ignored_rows 0
+
*Valid Values:*
+
--user "dbuser" --password "$DIWD" --target_database "ditest" --target_schema "falcon_schema"
