= Azure Synapse connection reference
:last_updated: 12/31/2020
:linkattrs:
:experimental:

Learn about the fields used to create an Azure Synapse connection with ThoughtSpot DataFlow.

Here is a list of the fields for an Azure Synapse connection in ThoughtSpot DataFlow.
You need specific information to establish a seamless and secure connection.

== Connection properties
+++<dlentry id="dataflow-azure-synapse-conn-connection-name">+++Connection name:::: Name your connection. Mandatory field. *Example:* + AzureSynapseConnection+++</dlentry>++++++<dlentry id="dataflow-azure-synapse-conn-connection-type">+++Connection type:::: Choose the Azure Synapse connection type. Mandatory field. *Example:* + Azure Synapse+++</dlentry>++++++<dlentry id="dataflow-azure-synapse-conn-host">+++Host:::: Specify the name of the server. Mandatory field. *Example:* + http://www.example.net/+++</dlentry>++++++<dlentry id="dataflow-azure-synapse-conn-port">+++Port:::: Specify the connection port for Azure Synapse. Mandatory field. *Example:* + 1234+++</dlentry>++++++<dlentry id="dataflow-azure-synapse-conn-user">+++User::::
Specify the user who connects to Azure Synapse.
This user must have data access privileges. Mandatory field. *Example:* + user1+++</dlentry>++++++<dlentry id="dataflow-azure-synapse-conn-password">+++Password:::: Specify the password. Mandatory field. *Example:* + pswrd234%!+++</dlentry>++++++<dlentry id="dataflow-azure-synapse-conn-jdbc-options">+++JDBC options:::: Specify JDBC URL for connecting to Azure Synapse, and the neccessary options. Optional field. *Example:* + jdbc:sqlserver://yourserver.database.windows.net:1234;database=mydatabase; *Other notes:* + Under *Advanced configuration*.+++</dlentry>++++++<dlentry id="dataflow-azure-synapse-conn-jdbc-options">+++JDBC options:::: Specify the options associated with the JDBC URL. Optional field. *Example:* + `jdbc:sqlserver://[serverName[\instanceName][:portNumber]]` *Other notes:* + Advanced configuration+++</dlentry>+++

== Sync properties
+++<dlentry id="dataflow-azure-synapse-sync-data-extraction-mode">+++Data extraction mode:::: Specify the extraction type. Mandatory field. *Example:* + BCP *Valid Values:* + JDBC, BCP *Default:* + JDBC+++</dlentry>++++++<dlentry id="dataflow-azure-synapse-sync-column-delimiter">+++Column delimiter:::: Specify the column delimiter character. Mandatory field. *Example:* + , (comma)
*Valid Values:* + Any character, (comma, semicolon) or a number.
If using a number, system uses its ASCII value as delimiter. *Default:* + , (comma)+++</dlentry>++++++<dlentry id="dataflow-azure-synapse-sync-null-value">+++Null value::::
Specify the string literal that represents NULL on the source.
When loading data, the system replaces this with NULL.
Optional field.
+ Available only when *Data extraction mode* is _BCP_. *Example:* + NULL *Valid Values:* + Any string literal *Default:* + NULL+++</dlentry>++++++<dlentry id="dataflow-azure-synapse-sync-enclosing-character">+++Enclosing character::::
Specify if text columns in the source data are enclosed in quotes;
if yes, single quotes or double quoates. Optional field. *Example:* + Double *Valid Values:* + Single, Double *Default:* + Double *Other notes:* + Required if text data uses newline character or delimiter character.+++</dlentry>++++++<dlentry id="dataflow-azure-synapse-sync-escape-character">+++Escape character:::: Specify the escape character if using a text qualifier in the source data. Optional field. *Example:* + \" *Valid Values:* + Any ASCII character *Default:* + \"+++</dlentry>++++++<dlentry id="dataflow-azure-synapse-sync-fetch-size">+++Fetch size::::
Specify the number of rows fetched into memory at the same time.
If the value is 0, system fetches all rows at the same time.
Mandatory field.
+ Available only when *Data extraction mode* is _JDBC_. *Example:* + 1000 *Valid Values:* + Any numeric value *Default:* + 1000+++</dlentry>++++++<dlentry id="dataflow-azure-synapse-sync-ts-load-options">+++TS load options::::
Specify additional parameters passed with the `tsload` command.
The format for these parameters is: + `--<param_1_name> <optional_param_1_value>` Optional field. *Example:* + `--max_ignored_rows 0` *Valid Values:* +  + ` --null_value ""` + ` --escape_character ""` + ` --max_ignored_rows 0` *Default:* + ` --max_ignored_rows 0`+++</dlentry>+++
