= Add a Netezza database connection
:last_updated: 7/6/2020

You can add a connection to a Netezza database using ThoughtSpot DataFlow.

Follow these steps:

include::partial$add-database-connection.adoc[]

. After you select the Netezza *Connection type*, the rest of the connection properties appear.
 ** xref:dataflow-netezza-reference.adoc#dataflow-netezza-conn-connection-name[Connection name]
 +
Name your connection.
 ** xref:dataflow-netezza-reference.adoc#dataflow-netezza-conn-connection-type[Connection type]
 +
Choose the Netezza connection type.
 ** xref:dataflow-netezza-reference.adoc#dataflow-netezza-conn-host[Host]
 +
Specify the hostname or the IP address of the Netezza system
 ** xref:dataflow-netezza-reference.adoc#dataflow-netezza-conn-port[Port]
 +
Specify the port associated to the Netezza system
 ** xref:dataflow-netezza-reference.adoc#dataflow-netezza-conn-user[User]
 +
Specify the user id that will be used to connect to the Netezza system. This user should have necessary privileges to access the data in the databases.
 ** xref:dataflow-netezza-reference.adoc#dataflow-netezza-conn-password[Password]
 +
Specify the password for the User
 ** xref:dataflow-netezza-reference.adoc#dataflow-netezza-conn-version[Version]
 +
Specify the Netezza version being connected to
 ** xref:dataflow-netezza-reference.adoc#dataflow-netezza-conn-jdbc-options[JDBC options]
 +
Specify the options associated with the JDBC URL.

+
See xref:dataflow-netezza-reference.adoc#connection-properties[Connection properties] for details, defaults, and examples.
. Click *Create connection*.
