= Cassandra connection reference
:last_updated: 07/03/2020

Learn about the fields used to create a Cassandra connection with ThoughtSpot DataFlow.

Here is a list of the fields for a Cassandra connection in ThoughtSpot DataFlow.
You need specific information to establish a seamless and secure connection.

== Connection properties

Connection name:: Name your connection.
+
Mandatory field.
+
*Example:* CassandraConnection

Connection type:: Choose the Cassandra connection type.
+
Mandatory field.
+
*Example:* Cassandra

Host:: Specify the hostname or the IP address of the Cassandra system.
+
Mandatory field.
+
*Example:* http://www.example.com/

Port:: Specify the port associated to the Cassandra system.
+
Mandatory field.
+
*Example:* 9042

User:: Specify the user to connect to Cassandra. This user must have data access privileges.
+
Mandatory field.
+
*Example:* userdi

Password:: Specify the password for the User.
+
Mandatory field.
+
*Example:* pswrd234%!

Authentication:: Specifies the type of security protocol to connect to the instance. Based on the type of security select the authentication type and provide details.
+
Mandatory field.
+
*Example:* Kerberos

*Valid Values:* None, SSL, LDAP, Kerberos

*Default:* None

Row scan depth:: The maximum number of rows to scan to look for the columns available in a table. Set this property to gain more control over how the provider applies data types to collections.
+
Optional field.
+
*Example:* -1

*Default:* 100

*Other notes:* Advanced Configuration

KDC host:: Specify KDC Host Name where as KDC (Kerberos Key Distribution Center) is a service than runs on a domain controller server role.
+
Mandatory field.
+
For Kerberos authentication only.
+
*Example:* my_email@example.com

User keytab:: To authenticate via a key-tab you must have supporting key-tab file which is generated by Kerberos Admin and also requires the user principal associated with Key-tab ( Configured while enabling Kerberos).
+
Mandatory field.
+
For Kerberos authentication only.
+
*Example:* /app/keytabs/labuser.keytab

Default realm:: A Kerberos realm is the domain over which a Kerberos authentication server has the authority to authenticate a user, host or service.
+
Mandatory field.
+
For Kerberos authentication only.
+
*Example:* name.example.com

Kerberos service KDC:: Specify the Kerberos KDC of the service.
+
Mandatory field.
+
For Kerberos authentication only.
+
*Example:* www.example.com

Kerberos service realm:: Specify the Kerberos realm of the service.
+
Mandatory field.
+
For Kerberos authentication only.
+
*Example:* EXAMPLE.COM

Kerberos SPN:: Specify the service principal name (SPN) for the Kerberos Domain Controller.
+
Mandatory field.
+
For Kerberos authentication only.
+
*Example:* cassandra/www.example.com@EXAMPLE.COM

LDAP user:: Specify the default LDAP user used to connect to and communicate with the server, it must be set if the LDAP server do not allow anonymous bind.
+
Mandatory field.
+
For LDAP authentication only.
+
*Example:* userdi

LDAP password:: Specify the password for the LDAP User.
+
Mandatory field.
+
For LDAP authentication only.
+
*Example:* pswrd234%!

LDAP server:: Specify the host name or IP address of the LDAP server.
+
Mandatory field.
+
For LDAP authentication only.
+
*Example:* my_email@example.com

LDAP port:: Specify the port number that is associated to the LDAP server.
+
Mandatory field.
+
For LDAP authentication only.
+
*Example:* 1234

Search filter:: Specify the search filter for looking up usernames in LDAP.
+
Mandatory field.
+
For LDAP authentication only.
+
*Example:* sAMAccountName=

*Default:* uid

Search base:: Specify the search base for the LDAP server, used to look up users.
+
Mandatory field.
+
For LDAP authentication only.
+
*Example:* DC=maxcrc,DC=com

Trust store path:: Specify the TLS/SSL client certificate store for SSL Client Authentication (2-way SSL).
+
Mandatory field.
+
For SSL authentication only.
+
*Example:* password

Certificate type:: Specify the subject of the TLS/SSL client certificate.
+
Mandatory field.
+
For SSL authentication only.
+
*Example:* JKSFILE

Certificate subject:: Specify the subject of the TLS/SSL client certificate.
+
Mandatory field.
+
For SSL authentication only.
+
*Example:* CN=www.example.com

*Default:* *

JDBC options:: Specify the options associated with the JDBC URL.
+
Optional field.
+
*Example:* `jdbc:sqlserver://[serverName[\instanceName][:portNumber]]`
+
*Other notes:* Advanced configuration

== Sync properties

Column delimiter:: Specify the column delimiter character.
+
Mandatory field.
+
*Example:* 1
+
*Valid values:* Any printable ASCII character or decimal value for ASCII character.
+
*Default:* 1

Enclosing character:: Specify if text columns in the source data are enclosed in quotes.
+
Optional field.
+
*Example:* DOUBLE
+
*Valid values:* SINGLE, DOUBLE
+
*Default:* DOUBLE
+
*Other notes:* Required if text data uses newline character or delimiter character.

Escape character:: Specify the escape character if using a text qualifier in the source data.
+
Optional field.
+
*Example:* \"
+
*Valid values:* Any ASCII character
+
*Default:* \"

TS load options:: Specifies the parameters passed with the `tsload` command, in addition to the commands already included by the application.
+
The format for these parameters is:
+
`--<param_1_name> <optional_param_1_value>`
+
`--<param_2_name> <optional_param_2_value>`
+
Optional field.
+
*Example:* --max_ignored_rows 0
+
*Valid values:* --null_value "" --escape_character "" --max_ignored_rows 0
+
*Default:* --max_ignored_rows 0
