= MongoDB connection reference
:last_updated: 07/6/2020


Learn about the fields used to create a MongoDB connection with ThoughtSpot DataFlow.

Here is a list of the fields for a MongoDB connection in ThoughtSpot DataFlow.
You need specific information to establish a seamless and secure connection.

== Connection properties
+++<dlentry id="dataflow-mongodb-conn-connection-name">+++Connection name:::: Name your connection. Mandatory field. *Example:* + MongoDBConnection+++</dlentry>++++++<dlentry id="dataflow-mongodb-conn-connection-type">+++Connection type:::: Choose the MongoDB connection type. Mandatory field. *Example:* + MongoDB+++</dlentry>++++++<dlentry id="dataflow-mongodb-conn-host-">+++Host:::: Specify the hostname or the IP address of the MongoDB system Mandatory field. *Example:* + www.example.com+++</dlentry>++++++<dlentry id="dataflow-mongodb-conn-port-">+++Port:::: Specify the port associated to the MongoDB system Mandatory field. *Example:* + 1234+++</dlentry>++++++<dlentry id="dataflow-mongodb-conn-user-">+++User::::
Specify the user id that will be used to connect to the MongoDB system.
This user should have necessary privileges to access the data in the databases. Mandatory field. *Example:* + userdi+++</dlentry>++++++<dlentry id="dataflow-mongodb-conn-password-">+++Password:::: Specify the password for the User Mandatory field. *Example:* + pswrd234%!+++</dlentry>++++++<dlentry id="dataflow-mongodb-conn-database-">+++Database:::: Collection of information that is organized so that it can be easily accessed, managed and updated Mandatory field. *Example:* + Test+++</dlentry>++++++<dlentry id="dataflow-mongodb-sync-flatten-arrays">+++Flatten arrays::::
The FlattenArrays property can be used to flatten the elements of nested arrays into columns of their own.
Set FlattenArrays to the number of elements you want to return from nested arrays. Optional field. *Example:* + 0 *Other notes:* + Advanced configuration+++</dlentry>++++++<dlentry id="dataflow-mongodb-sync-row-scan-depth">+++Row scan depth::::
The maximum number of rows to scan to look for the columns available in a table.
Set this property to gain more control over how the provider applies data types to collections. Optional field. *Example:* + -1 *Other notes:* + Advanced configuration+++</dlentry>++++++<dlentry id="dataflow-mongodb-conn-jdbc-options">+++JDBC options:::: Specify the options associated with the JDBC URL. Optional field. *Example:* + `jdbc:sqlserver://[serverName[\instanceName][:portNumber]]` *Other notes:* + Advanced configuration+++</dlentry>+++

== Sync properties
+++<dlentry id="dataflow-mongodb-sync-column-delimiter">+++Column delimiter:::: Specify the column delimiter character. Mandatory field. *Example:* + 1 *Valid Values:* + Any printable ASCII character or decimal value for ASCII character *Default:* + 1+++</dlentry>++++++<dlentry id="dataflow-mongodb-sync-enclosing-character">+++Enclosing character:::: Specify if the text columns in the source data needs to be enclosed in quotes. Optional field. *Example:* + DOUBLE *Valid Values:* + SINGLE, DOUBLE *Default:* + DOUBLE *Other notes:* + This is required if the text data has newline character or delimiter character.+++</dlentry>++++++<dlentry id="dataflow-mongodb-sync-escape-character">+++Escape character:::: Specify the escape character if using a text qualifier in the source data. Optional field. *Example:* + \" *Valid Values:* + Any ASCII character *Default:* + \"+++</dlentry>++++++<dlentry id="dataflow-mongodb-sync-ts-load-options">+++TS load options::::
Specifies the parameters passed with the `tsload` command, in addition to the commands already included by the application.
The format for these parameters is: + ` --<param_1_name> <optional_param_1_value>` + ` --<param_2_name> <optional_param_2_value>` Optional field. *Example:* + --max_ignored_rows 0 *Valid Values:* + --user "dbuser" --password "$DIWD" --target_database "ditest" --target_schema "falcon_schema" *Default:* + --max_ignored_rows 0+++</dlentry>+++
