= Add an Azure Synapse connection
:last_updated: 7/03/2020

You can add a connection to an Azure Synapse database using ThoughtSpot DataFlow.

To add a new connection to Azure Synapse, follow these steps:

include::partial$add-database-connection.adoc[]

. After you select the Azure Synapse *Connection type*, the rest of the connection properties appear.
 ** xref:dataflow-azure-synapse-reference.adoc#dataflow-azure-synapse-conn-connection-name[Connection name]
 +
Name your connection.
 ** xref:dataflow-azure-synapse-reference.adoc#dataflow-azure-synapse-conn-connection-type[Connection type]
 +
Choose the Azure Synapse connection type.
 ** xref:dataflow-azure-synapse-reference.adoc#dataflow-azure-synapse-conn-host[Host]
 +
Specify the name of the server.
 ** xref:dataflow-azure-synapse-reference.adoc#dataflow-azure-synapse-conn-port[Port]
 +
Specify the connection port for Azure Synapse.
 ** xref:dataflow-azure-synapse-reference.adoc#dataflow-azure-synapse-conn-user[User]
 +
Specify the user who connects to Azure Synapse.
This user must have data access privileges.
 ** xref:dataflow-azure-synapse-reference.adoc#dataflow-azure-synapse-conn-password[Password]
 +
Specify the password.
 ** xref:dataflow-azure-synapse-reference.adoc#dataflow-azure-synapse-conn-jdbc-options[JDBC options]
 +
Specify JDBC URL for connecting to Azure Synapse, and the neccessary options.
 ** xref:dataflow-azure-synapse-reference.adoc#dataflow-azure-synapse-conn-database[Database]
 +
Specify Database details like name, alias name, schema.
 ** xref:dataflow-azure-synapse-reference.adoc#dataflow-azure-synapse-conn-jdbc-options[JDBC options]
 +
Specify the options associated with the JDBC URL.

+
See xref:dataflow-azure-synapse-reference.adoc#connection-properties[Connection properties] for details, defaults, and examples.
. Click *Create connection*.
