= Sync data through a Hive connection
:last_updated: 7/6/2020

After using ThoughtSpot DataFlow to establish a connection to a Hive database, you can create automatic data updates, to seamlessly refresh your data.

include::partial$sync-for-databases.adoc[]

. Specify the sync properties for Hive:
 ** xref:dataflow-hive-reference.adoc#dataflow-hive-sync-data-extraction-mode[Data extraction mode]
 +
Specify the extraction type.
 ** xref:dataflow-hive-reference.adoc#dataflow-hive-sync-null-value[Null value]
 +
Specifies the string literal that should indicate the null value in the extracted data.
During the data load the column value matching this string will be loaded as null in the target.
For Hadoop Extract only.
 ** xref:dataflow-hive-reference.adoc#dataflow-hive-sync-enclosing-character[Enclosing character]
 +
Specify if the text columns in the source data needs to be enclosed in quotes.
 ** xref:dataflow-hive-reference.adoc#dataflow-hive-sync-escape-character[Escape character]
 +
Specify the escape character if using a text qualifier in the source data.
 ** xref:dataflow-hive-reference.adoc#dataflow-hive-sync-ts-load-options[TS load options]
 +
Specify the parameters passed with the `tsload` command, in addition to the commands already included by the application.

+
See xref:dataflow-hive.adoc#sync-properties[Sync properties] for details, defaults, and examples.
. Save your work by clicking *Save*.
+ Alternatively, click *Save and sync now* to save your work and sync data at the same time.
