= Google BigQuery connection reference
:last_updated: 07/03/2020

Learn about the fields used to create an Google BigQuery connection with ThoughtSpot DataFlow.

Here is a list of the fields for a Cassandra connection in ThoughtSpot DataFlow.
You need specific information to establish a seamless and secure connection.

== Connection properties

Project id:: The identification number given to particular project and its always unique.
+
Mandatory field.
+
*Example:* myproject-1234

Authentication type:: It can be either Service Account or Access Tokens
+
Mandatory field.
+
*Example:* Service Account
+
*Valid values:* Service Account, Access Token
+
*Default:* Service Account

Service account key/access Token:: Provide the Service Account key when authentication type is selected as Service account and token when access token is selected as authentication type.
+
Mandatory field.
+
*Example:* ABCDEFGH245HIJK

Query priority:: Specify the time duration to run the query and it can be either Interactive or Batch.
+
Optional field.
+
*Example:* BATCH
+
*Valid values:* INTERACTIVE, BATCH
+
*Default:* BATCH

Use proxy:: If required, to use a proxy, select the check box Use Proxy and provide the details.
+
Optional field.
+
*Other notes:* in *Advanced configuration*

Host:: Specify the hostname or the IP address of the BigQuery system.
+
Optional field.
+
For proxy authentication only.
+
*Example:* www.example.com

Port:: Specify the port associated to the BigQuery system.
+
Optional field.
+
For proxy authentication only.
+
*Example:* 1234

Protocol:: It can be either http or https.
+
Optional field.
+
For proxy authentication only.
+
*Example:* http
+
*Valid values:* http, https
+
*Default:* http

JDBC options:: Specify the options associated with the JDBC URL.
+
Optional field.
+
*Example:* `jdbc:sqlserver://[serverName[\instanceName][:portNumber]]`
+
*Other notes:* Advanced configuration

== Sync properties

Column delimiter:: Specify the column delimiter character.
+
Mandatory field.
+
*Example:* 1
+
*Valid values:* Any printable ASCII character, or the decimal value for an ASCII character.
+
*Default:* The delimiter specified in sync

Enclosing character:: Specify if the text columns in the source data needs to be enclosed in quotes.
+
Optional field.
+
*Example:* DOUBLE
+
*Valid values:* DOUBLE, SINGLE, NULL
+
*Default:* SINGLE
+
*Other notes:* Required if text data uses newline character or delimiter character.

Escape character:: Specify the escape character if using a text qualifier in the source data.
+
Optional field.
+
*Example:* \"
+
*Valid values:* \\, any ASCII character
+
*Default:* \"

Fetch size:: Specify the number of rows to fetch at one time, and process in memory. To fetch all rows, specify 0 rows.
+
Mandatory field.
+
*Example:* 1000
+
*Valid values:* 1000, 10, 100. 100000, any numeric value
+
*Default:* 10

Allow large resultset:: If enabled, allows query results that are larger in size.
+
Optional field.
+
*Example:* FALSE
+
*Valid values:* TRUE
+
*Default:* FALSE

TS load options:: Specifies the parameters passed with the tsload command, in addition to the commands already included by the application.
+
The format for these parameters is:
+
`--<param_1_name> <optional_param_1_value>`
+
`--<param_2_name> <optional_param_2_value>`
+
Optional field.
+
*Example:* --max_ignored_rows 0
+
*Valid values:* --null_value "" --escape_character "" --max_ignored_rows 0
+
*Default:* --max_ignored_rows 0
