= Amazon Redshift connection reference
:last_updated: 06/19/2020

Learn about the fields used to create an Amazon Redshift connection with ThoughtSpot DataFlow.

Here is a list of the fields for an Amazon Redshift connection in ThoughtSpot DataFlow.
You need specific information to establish a seamless and secure connection.

== Connection properties
Connection name:: Name your connection.
+
Mandatory field.
+
*Example:* AmazonRedshiftConnection

Connection type:: Choose the Amazon Redshift connection type.
+
Mandatory field.
+
*Example:* Amazon Redshift

Host:: Specify the hostname or IP address of the Redshift system.
+
Mandatory field.
+
*Example:* example.com

Port:: Specify the port associated with Amazon Redshift connections.
+
Mandatory field.
+
*Example:* 1234
+
*Port:* 5439

User:: Specify the user to connect to Amazon Redshift. This user must have data access privileges.
+
Mandatory field.
+
*Example:* userdi

Password:: Specify the password for the User.
+
Mandatory field.
+
*Example:* pswrd234%!

JDBC options:: Specify the options associated with the JDBC URL.
+
Optional field.
+
*Example:* `jdbc:sqlserver://[serverName[\instanceName][:portNumber]]`
+
*Other notes:* Advanced configuration

== Sync properties

Column delimiter:: Specify the column delimiter character.
+
Mandatory field.
+
*Example:* 1
+
*Valid values:* Any printable ASCII character or decimal value for ASCII character
+
*Default:* 1

Enclosing character:: Specify if the text columns in the source data needs to be enclosed in quotes.
+
Optional field.
+
*Example:* DOUBLE
+
*Valid values:* SINGLE, DOUBLE
+
*Default:* DOUBLE
+
*Other notes:* This is required if the text data has newline character or delimiter character.

Escape character:: Specify the escape character if using a text qualifier in the source data.
+
Optional field.
+
*Example:* \"
+
*Valid values:* Any ASCII character
+
*Default:* \"

Fetch size:: Specify the number of rows to be fetched at a time and processed in memory. If the value specified is zero then, all rows are extracted at once.
+
Mandatory field.
+
*Example:* 1000
+
*Valid values:* Any numeric value
+
*Default:* 1000

TS load options:: Specifies the parameters passed with the tsload command, in addition to the commands already included by the application.
+
The format for these parameters is:
+
`--<param_1_name> <optional_param_1_value>`
+
`--<param_2_name> <optional_param_2_value>`
+
Optional field.
+
*Example:* --max_ignored_rows 0
+
*Valid values:* --user "dbuser" --password "$DIWD" --target_database "ditest" --target_schema "falcon_schema"
+
*Default:* --max_ignored_rows 0
