= Add a Presto database connection
:last_updated: 7/7/2020

You can add a connection to a Presto database using ThoughtSpot DataFlow.

Follow these steps:

include::partial$add-database-connection.adoc[]

. After you select the Presto *Connection type*, the rest of the connection properties appear.
 ** xref:dataflow-presto-reference.adoc#dataflow-presto-conn-connection-name[Connection name]
 +
Name your connection.
 ** xref:dataflow-presto-reference.adoc#dataflow-presto-conn-connection-type[Connection type]
 +
Choose the Presto connection type.
 ** xref:dataflow-presto-reference.adoc#dataflow-presto-conn-host-[Host]
 +
Specify the hostname or the IP address of the Presto system
 ** xref:dataflow-presto-reference.adoc#dataflow-presto-conn-port-[Port]
 +
Specify the port associated with the Presto system
 ** xref:dataflow-presto-reference.adoc#dataflow-presto-conn-user-name[User name]
 +
Specify the user id that will be used to connect to the Presto system. This user must have necessary privileges to access the data in the databases.
 ** xref:dataflow-presto-reference.adoc#dataflow-presto-conn-authentication-type[Authentication type]
 +
Based on the security protocol you use to connect to the instance, select the authentication type and provide details.
 ** xref:dataflow-presto-reference.adoc#dataflow-presto-conn-ssl-key-store-path-[SSL key store path]
 +
Specify the trust store path, generated by the server
 ** xref:dataflow-presto-reference.adoc#dataflow-presto-conn-ssl-key-store-password[SSL key store password]
 +
Specify the password for the key store. The client generates this while generating the key store file
 ** xref:dataflow-presto-reference.adoc#dataflow-presto-sync-ldap-password[Ldap password]
 +
Provide LDAP password to connect.
 ** xref:dataflow-presto-reference.adoc#dataflow-presto-sync-kerberos-remote-service-name[Kerberos remote service name] + Hostname of the Kerberos server.
Required to generate the `krb.conf` file
 ** xref:dataflow-presto-reference.adoc#dataflow-presto-sync-user-principal[User principal]
 +
To authenticate via a key-tab, you need the user principal associated with the key-tab. You can configure this when enabling Kerberos.
 ** xref:dataflow-presto-reference.adoc#dataflow-presto-sync-kerberos-config[Kerberos config]
 +
A Kerberos config explains the configuartion details used to connect to Kerberos authentication server.
 ** xref:dataflow-presto-reference.adoc#dataflow-presto-sync-user-keytab[User keytab]
 +
To authenticate via a key-tab, you must have the supporting key-tab file that the Kerberos Admin generates.
 ** xref:dataflow-presto-reference.adoc#dataflow-presto-sync-catalog-name[Catalog name]
 +
Specify the catalog file name
 ** xref:dataflow-presto-reference.adoc#dataflow-presto-sync-schema-name[Schema name]
 +
Specify the schema name of a database
 ** xref:dataflow-presto-reference.adoc#dataflow-presto-conn-jdbc-options[JDBC options]
+ Specify the options associated with the JDBC URL.

+
See xref:dataflow-presto-reference.adoc#connection-properties[Connection properties] for details, defaults, and examples.
. Click *Create connection*.
