= Teradata connection reference
:last_updated: 07/7/2020


Learn about the fields used to create a Teradata connection with ThoughtSpot DataFlow.

Here is a list of the fields for a Teradata connection in ThoughtSpot DataFlow.
You need specific information to establish a seamless and secure connection.

== Connection properties
+++<dlentry id="dataflow-teradata-conn-connection-properties">+++Connection Properties:::: Name your connection. Mandatory field. *Example:* + TeradataConnection+++</dlentry>++++++<dlentry id="dataflow-teradata-conn-connection-type">+++Connection type:::: Choose the Teradata connection type. Mandatory field. *Example:* + Teradata+++</dlentry>++++++<dlentry id="dataflow-teradata-conn-host">+++Host:::: Specify the hostname or the IP address of the Teradata system Mandatory field. *Example:* + www.example.com+++</dlentry>++++++<dlentry id="dataflow-teradata-conn-port">+++Port:::: Specify the port associated to the Teradata system Mandatory field. *Example:* + 1234+++</dlentry>++++++<dlentry id="dataflow-teradata-conn-user">+++User::::
Specify the user id that will be used to connect to the Teradata system.
This user should have necessary privileges to access the data in the databases. Mandatory field. *Example:* + userdi+++</dlentry>++++++<dlentry id="dataflow-teradata-conn-password">+++Password:::: Specify the password for the User Mandatory field. *Example:* + pswrd234%!+++</dlentry>++++++<dlentry id="dataflow-teradata-conn-version">+++Version:::: Specify the version of Teradata you are using Optional field. *Example:* + 14.2 *Other notes:* + Advanced configuration+++</dlentry>++++++<dlentry id="dataflow-teradata-conn-jdbc-options">+++JDBC options:::: Specify the options associated with the JDBC URL. Optional field. *Example:* + `jdbc:sqlserver://[serverName[\instanceName][:portNumber]]` *Other notes:* + Advanced configuration+++</dlentry>+++

== Sync properties
+++<dlentry id="dataflow-teradata-sync-data-extraction-mode">+++Data extraction mode:::: Specify the extraction type. Mandatory field. *Example:* + JDBC *Valid Values:* + JDBC, TPT *Default:* + JDBC+++</dlentry>++++++<dlentry id="dataflow-teradata-sync-column-delimiter">+++Column delimiter:::: Specify the column delimiter character. Mandatory field. *Example:* + 1 *Valid Values:* + Any printable ASCII character or decimal value for ASCII character *Default:* + 1+++</dlentry>++++++<dlentry id="dataflow-teradata-sync-null-value">+++Null value::::
Specifies the string literal that indicates the null value in the extracted data.
During the data load, the column value matching this string loads as null in the target. Optional field. *Example:* + NULL *Valid Values:* + Any string literal *Default:* + NULL+++</dlentry>++++++<dlentry id="dataflow-teradata-sync-enclosing-character">+++Enclosing character:::: Specify if the text columns in the source data needs to be enclosed in quotes. Optional field. *Example:* + DOUBLE *Valid Values:* + SINGLE, DOUBLE *Default:* + DOUBLE *Other notes:* + This is required if the text data has newline character or delimiter character.+++</dlentry>++++++<dlentry id="dataflow-teradata-sync-escape-character">+++Escape character:::: Specify the escape character if using a text qualifier in the source data. Optional field. *Example:* + \" *Valid Values:* + Any ASCII character *Default:* + \"+++</dlentry>++++++<dlentry id="dataflow-teradata-sync-fetch-size">+++Fetch size::::
Specify the number of rows at a time to fetch and process in memory.
If you specify zero, the system extracts all rows at once. Mandatory field. *Example:* + 1000 *Valid Values:* + Any numeric value *Default:* + 1000+++</dlentry>++++++<dlentry id="dataflow-teradata-sync-ts-load-options">+++TS load options::::
Specifies the parameters passed with the `tsload` command, in addition to the commands already included by the application.
The format for these parameters is: + ` --<param_1_name> <optional_param_1_value>` + ` --<param_2_name> <optional_param_2_value>` Optional field. *Example:* + --max_ignored_rows 0 *Valid Values:* + --user "dbuser" --password "$DIWD" --target_database "ditest" --target_schema "falcon_schema" *Default:* + --max_ignored_rows 0+++</dlentry>+++
