= Sync data through Snowflake connection
:last_updated: 6/22/2020

After using ThoughtSpot DataFlow to establish a connection to a Snowflake database, you can create automatic data updates, to seamlessly refresh your data.

include::partial$sync-for-databases.adoc[]

. Specify the sync properties for Snowflake:
 ** xref:dataflow-snowflake-reference.adoc#dataflow-snowflake-sync-data-extraction-mode[Data extraction mode]
 +
Specify the extraction type.
 ** xref:dataflow-snowflake-reference.adoc#dataflow-snowflake-sync-column-delimiter[Column delimiter]
 +
Specify the column delimiter character.
 ** xref:dataflow-snowflake-reference.adoc#dataflow-snowflake-sync-enclosing-character[Enclosing character]
 +
Specify if text column data is in quotes, and if + Optional field.
 ** xref:dataflow-snowflake-reference.adoc#dataflow-snowflake-sync-escape-character[Escape character]
 +
Specify the escape character if using a text qualifier in the source data.
 ** xref:dataflow-snowflake-reference.adoc#dataflow-snowflake-sync-escape-unclosed-field[Escape unclosed field]
 +
Specify this if the text qualifier is mentioned. This should be the character which escapes the text qualifier character in the source data.
 ** xref:dataflow-snowflake-reference.adoc#dataflow-snowflake-sync-field-optionally-enclosed-by[Field optionally enclosed by]
 +
Specify if the text columns in the source data needs to be enclosed in quotes.
 ** xref:dataflow-snowflake-reference.adoc#dataflow-snowflake-sync-null-if[Null If]
 +
Specify the string literal that indicates NULL value in the extracted data. During data loading, column values that match this string loaded as NULL in the target.
 ** xref:dataflow-snowflake-reference.adoc#dataflow-snowflake-sync-stage-location[Stage location]
 +
Specify a temporary staging server Snowflake has to use while DataFlow extracts data.
 ** xref:dataflow-snowflake-reference.adoc#dataflow-snowflake-sync-max-file-size[Max file size]
 +
Specify the maximum size of each file in the stage location, in bytes.
 ** xref:dataflow-snowflake-reference.adoc#dataflow-snowflake-sync-parallel-threads[Parallel threads]
 +
Specify the number of parallel threads to unload data.
 ** xref:dataflow-snowflake-reference.adoc#dataflow-snowflake-sync-fetch-size[Fetch size]
 +
Specify the number of rows fetched into memory at the same time. If the value is 0, system fetches all rows at the same time.
 ** xref:dataflow-snowflake-reference.adoc#dataflow-snowflake-sync-ts-load-options[TS load options]
 +
Specify the parameters passed with the `tsload` command, in addition to the commands already included by the application.

+
See xref:dataflow-snowflake-reference.adoc#sync-properties[Sync properties] for details, defaults, and examples.
. Save your work by clicking *Save*.
+ Alternatively, click *Save and sync now* to save your work and sync data at the same time.
