= Denodo connection reference
:last_updated: 10/22/2020


Learn about the fields used to create a Denodo connection with ThoughtSpot DataFlow.

Here is a list of the fields for a Denodo connection in ThoughtSpot DataFlow.
You need specific information to establish a seamless and secure connection.

== Connection properties
+++<dlentry id="dataflow-denodo-conn-connection-name">+++Connection name:::: Name your connection. Mandatory field. *Example:* + DenodoConnection+++</dlentry>++++++<dlentry id="dataflow-denodo-conn-connection-type">+++Connection type:::: Choose the Denodo connection type. Mandatory field. *Example:* + Denodo+++</dlentry>++++++<dlentry id="dataflow-denodo-conn-host">+++Host:::: Specify the hostname or the IP address of the system. Mandatory field. *Example:* + www.example.com+++</dlentry>++++++<dlentry id="dataflow-denodo-conn-port">+++Port:::: Specify the port associated with the system. Mandatory field. *Example:* + 1234+++</dlentry>++++++<dlentry id="dataflow-denodo-conn-user">+++User::::
Specify the user who connects to the system.
This user must have data access privileges. Mandatory field. *Example:* + userid+++</dlentry>++++++<dlentry id="dataflow-denodo-conn-password">+++Password:::: Specify the password for the User. Mandatory field. *Example:* + pswrd234%!+++</dlentry>++++++<dlentry id="dataflow-denodo-conn-jdbc-options">+++JDBC options:::: Specify the options associated with the JDBC URL. Optional field. *Example:* + jdbc:sqlserver://[serverName[\instanceName][:portNumber]] *Other notes:* + Advanced configuration+++</dlentry>+++

== Sync properties
+++<dlentry id="dataflow-denodo-sync-column-delimiter">+++Column delimiter:::: Specify the column delimiter character. Mandatory field. *Example:* + 1 *Valid Values:* + Any printable ASCII character or decimal value for ASCII character *Default:* + 1+++</dlentry>++++++<dlentry id="dataflow-denodo-sync-enclosing-character">+++Enclosing character:::: Specify if the text columns in the source data needs to be enclosed in quotes. Optional field. *Example:* + DOUBLE *Valid Values:* + SINGLE, DOUBLE *Default:* + DOUBLE *Other notes:* + This is required if the text data has newline character or delimiter character.+++</dlentry>++++++<dlentry id="dataflow-denodo-sync-escape-character">+++Escape character::::
Specify this if the text qualifier is mentioned.
This should be the character which escapes the text qualifier character in the source data. Optional field. *Example:* + \" *Valid Values:* + Any ASCII character *Default:* + \"+++</dlentry>++++++<dlentry id="dataflow-denodo-sync-ts-load-options">+++TS load options::::
Specifies the parameters passed with the `tsload` command, in addition to the commands already included by the application.
The format for these parameters is: + ` --<param_1_name> <optional_param_1_value>` + ` --<param_2_name> <optional_param_2_value>` Optional field. *Example:* + `--max_ignored_rows 0` *Valid Values:* +  + ` --null_value ""` + ` --escape_character ""` + ` --max_ignored_rows 0` *Default:* + ` --max_ignored_rows 0`+++</dlentry>+++
