= Sync data through an SQL Server connection
:last_updated: 7/7/2020

After using ThoughtSpot DataFlow to establish a connection to an SQL Server database, you can create automatic data updates, to seamlessly refresh your data.

include::partial$sync-for-databases.adoc[]

. Specify the sync properties for SQL Server:
 ** xref:dataflow-sql-server-reference.adoc#dataflow-sql-server-sync-data-extraction-mode[Data extraction mode]
 +
Specify the extraction type.
 ** xref:dataflow-sql-server-reference.adoc#dataflow-sql-server-sync-column-delimiter[Column delimiter]
 +
Specify the column delimiter character.
 ** xref:dataflow-sql-server-reference.adoc#dataflow-sql-server-sync-null-value[Null value]
 +
Specifies the string literal that indicates the null value in the extracted data. During the data load, the column value matching this string loads as null in the target.
 ** xref:dataflow-sql-server-reference.adoc#dataflow-sql-server-sync-enclosing-character[Enclosing character]
 +
Specify if the text columns in the source data needs to be enclosed in quotes.
 ** xref:dataflow-sql-server-reference.adoc#dataflow-sql-server-sync-escape-character[Escape character]
 +
Specify the escape character if using a text qualifier in the source data.
 ** xref:dataflow-sql-server-reference.adoc#dataflow-sql-server-sync-ts-load-options[TS load options]
 +
Specify the parameters passed with the `tsload` command, in addition to the commands already included by the application.

+
See xref:dataflow-sql-server-reference.adoc#sync-properties[Sync properties] for details, defaults, and examples.
. Save your work by clicking *Save*.
+ Alternatively, click *Save and sync now* to save your work and sync data at the same time.
