= Azure Synapse connection reference
:last_updated: 06/19/2020

Learn about the fields used to create an Azure Synapse connection with ThoughtSpot DataFlow.

Here is a list of the fields for an Azure Synapse connection in ThoughtSpot DataFlow.
You need specific information to establish a seamless and secure connection.

== Connection properties

Connection name:: Name your connection.
+
Mandatory field.
+
*Example:* AzureSynapseConnection

Connection type:: Choose the Azure Synapse connection type.
+
Mandatory field.
+
*Example:* Azure Synapse

Host:: Specify the name of the server.
+
Mandatory field.
+
*Example:* http://www.example.net/

Port:: Specify the connection port for Azure Synapse.
+
Mandatory field.
+
*Example:* 1234

User:: Specify the user to connect to Azure Synapse. This user must have data access privileges.
+
Mandatory field.
+
*Example:* user1

Password:: Specify the password for the User.
+
Mandatory field.
+
*Example:* pswrd234%!

JDBC options:: Specify JDBC URL for connecting to Azure Synapse, and the necessary options.
+
Optional field.
+
*Example:* jdbc:sqlserver://yourserver.database.windows.net:1234;database=mydatabase;
+
*Other notes:* Under *Advanced configuration*.

JDBC options:: Specify the options associated with the JDBC URL.
+
Optional field.
+
*Example:* `jdbc:sqlserver://[serverName[\instanceName][:portNumber]]`
+
*Other notes:* Advanced configuration

== Sync properties

Data extraction mode:: Specify the column delimiter character.
+
Mandatory field.
+
*Example:* 1
+
*Valid values:* JDBC, BCP
+
*Default:* JDBC

Column delimiter:: Specify the column delimiter character.
+
Mandatory field.
+
*Example:* , (comma)
+
*Valid values:* Any character, (comma, semicolon) or a number. If using a number, system uses its ASCII value as delimiter.
+
*Default:* , (comma)

Null value:: Specify the string literal that represents NULL on the source. When loading data, the system replaces this with NULL.
+
Optional field.
+
Available only when *Data extraction* mode is BCP.
+
*Example:* NULL
+
*Valid values:* Any string literal
+
*Default:* NULL

Enclosing character:: Specify if text columns in the source data are enclosed in quotes; if yes, single quotes or double quotes.
+
Optional field.
+
*Example:* DOUBLE
+
*Valid values:* Single, Double
+
*Default:* DOUBLE
+
*Other notes:* Required if text data uses newline character or delimiter character.

Escape character:: Specify the escape character if using a text qualifier in the source data.
+
Optional field.
+
*Example:* \"
+
*Valid values:* Any ASCII character
+
*Default:* \"

Fetch size:: Specify the number of rows to be fetched at a time and processed in memory. If the value specified is zero then, all rows are extracted at once.
+
Mandatory field.
+
Available only when Data extraction mode is JDBC.
+
*Example:* 1000
+
*Valid values:* Any numeric value
+
*Default:* 1000

TS load options:: Specifies the parameters passed with the tsload command, in addition to the commands already included by the application.
+
The format for these parameters is:
+
`--<param_1_name> <optional_param_1_value>`
+
Optional field.
+
*Example:* --max_ignored_rows 0
+
*Valid values:* --null_value "" --escape_character "" --max_ignored_rows 0
+
*Default:* --max_ignored_rows 0
