= Sync data through a Netezza connection
:last_updated: 7/6/2020

After using ThoughtSpot DataFlow to establish a connection to a Netezza database, you can create automatic data updates, to seamlessly refresh your data.

include::partial$sync-for-databases.adoc[]

. Specify the sync properties for Netezza:
 ** xref:dataflow-netezza-reference.adoc#dataflow-netezza-sync-data-extraction-mode[Data extraction mode]
 +
Specify the extraction type.
 ** xref:dataflow-netezza-reference.adoc#dataflow-netezza-sync-column-delimiter[Column delimiter]
 +
Specify the column delimiter character.
 ** xref:dataflow-netezza-reference.adoc#dataflow-netezza-sync-enclosing-character[Enclosing character]
 +
Specify if the text columns in the source data needs to be enclosed in quotes.
 ** xref:dataflow-netezza-reference.adoc#dataflow-netezza-sync-escape-character[Escape character]
 +
Specify the escape character if using a text qualifier in the source data.
 ** xref:dataflow-netezza-reference.adoc#dataflow-netezza-sync-socket-buffer-size[Socket buffer size]
 +
Specifies the chunk size at which to read the data from the source, expressed in bytes + Optional field.
 ** xref:dataflow-netezza-reference.adoc#dataflow-netezza-sync-ts-load-options[TS load options]
 +
Specify the parameters passed with the `tsload` command, in addition to the commands already included by the application.

+
See xref:dataflow-netezza-reference.adoc#sync-properties[Sync properties] for details, defaults, and examples.
. Save your work by clicking *Save*.
+ Alternatively, click *Save and sync now* to save your work and sync data at the same time.
