= MySQL connection reference
:last_updated: 07/6/2020


Learn about the fields used to create a MySQL connection with ThoughtSpot DataFlow.

Here is a list of the fields for a MySQL connection in ThoughtSpot DataFlow.
You need specific information to establish a seamless and secure connection.

== Connection properties
+++<dlentry id="dataflow-mysql-conn-connection-name">+++Connection name:::: Name your connection. Mandatory field. *Example:* + MySQLConnection+++</dlentry>++++++<dlentry id="dataflow-mysql-conn-connection-type">+++Connection type:::: Choose the MySQL connection type. Mandatory field. *Example:* + MySQL+++</dlentry>++++++<dlentry id="dataflow-mysql-conn-host">+++Host:::: Specify the hostname or the IP address of the MySQL system Mandatory field. *Example:* + www.example.com+++</dlentry>++++++<dlentry id="dataflow-mysql-conn-port">+++Port:::: Specify the port associated to the MySQL system Mandatory field. *Example:* + 1234+++</dlentry>++++++<dlentry id="dataflow-mysql-conn-user">+++User::::
Specify the user id that will be used to connect to the MySQL system.
This user should have necessary privileges to access the data in the databases Mandatory field. *Example:* + userdi+++</dlentry>++++++<dlentry id="dataflow-mysql-conn-password">+++Password:::: Specify the password for the App User Mandatory field. *Example:* + pswrd234%!+++</dlentry>++++++<dlentry id="dataflow-mysql-conn-version">+++Version:::: Specify the MYSQL version being connected to. Optional field. *Example:* + 5.1x *Other notes:* + These are under Advanced configuration+++</dlentry>++++++<dlentry id="dataflow-mysql-conn-jdbc-options">+++JDBC options:::: Specify the options associated with the JDBC URL. Optional field. *Example:* + `jdbc:sqlserver://[serverName[\instanceName][:portNumber]]` *Other notes:* + Advanced configuration+++</dlentry>+++

== Sync properties
+++<dlentry id="dataflow-mysql-sync-column-delimiter">+++Column delimiter:::: Specify the column delimiter character. Mandatory field. *Example:* + 1 *Valid Values:* + Any printable ASCII character or decimal value for ASCII character *Default:* + The delimiter specified in sync+++</dlentry>++++++<dlentry id="dataflow-mysql-sync-enclosing-character">+++Enclosing character:::: Specify if the text columns in the source data needs to be enclosed in quotes. Optional field. *Example:* + DOUBLE *Valid Values:* + Single, Double *Default:* + DOUBLE *Other notes:* + This is required if the text data has newline character or delimiter character.+++</dlentry>++++++<dlentry id="dataflow-mysql-sync-escape-character">+++Escape character:::: Specify the escape character if using a text qualifier in the source data. Optional field. *Example:* + \" *Valid Values:* + Any ASCII character *Default:* + \"+++</dlentry>++++++<dlentry id="dataflow-mysql-sync-fetch-size">+++Fetch size::::
Specify the number of rows to be fetched at a time and processed in memory.
If the value specified is zero then, all rows are extracted at once. Mandatory field. *Example:* + 1000 *Valid Values:* + Any numeric value *Default:* + 1000+++</dlentry>++++++<dlentry id="dataflow-mysql-sync-ts-load-options">+++TS load options::::
Specifies the parameters passed with the `tsload` command, in addition to the commands already included by the application.
The format for these parameters is: + ` --<param_1_name> <optional_param_1_value>` + ` --<param_2_name> <optional_param_2_value>` Optional field. *Example:* + --max_ignored_rows 0 *Valid Values:* + --null_value "" --escape_character "" --max_ignored_rows 0 *Default:* + --max_ignored_rows 0+++</dlentry>+++
