= MariaDB connection reference
:last_updated: 07/6/2020

Learn about the fields used to create a MariaDB connection with ThoughtSpot DataFlow.

Here is a list of the fields for a MariaDB connection in ThoughtSpot DataFlow.
You need specific information to establish a seamless and secure connection.

== Connection properties
Connection name:: Name your connection.
+
Mandatory field.
+
*Example:*
+
MariaDBConnection
Connection type:: Choose the MariaDB connection type.
+
Mandatory field.
+
*Example:*
+
MariaDB

Host:: Specify the hostname or the IP address of the MariaDB system.
+
Mandatory field.
+
*Example:*
+
www.example.com

Port:: Specify the port associated to the MariaDB system.
+
Mandatory field.
+
*Example:*
+
1234

User:: Specify the user id that will be used to connect to the MariaDB system. This user should have necessary privileges to access the data in the databases.
+
Mandatory field.
*Example:*
+
userdi

Password:: Specify the password for the user.
+
Mandatory field.
+
*Example:*
+
pswrd234%!

Database version:: Specify the MariaDB version being connected to.
+
Optional field.
+
*Example:*
+
10.3
+
*Other notes:*
+
These are under Advanced configuration

JDBC options:: Specify the options associated with the JDBC URL.
+
Optional field.
+
*Example:*
+
`jdbc:sqlserver://[serverName[\instanceName][:portNumber]]`
+
*Other notes:*
+
Advanced configuration

== Sync properties
Column delimiter:: Specify the column delimiter character.
+
Mandatory field.
+
*Example:*
+
1
+
*Valid Values:*
+
Any printable ASCII character or decimal value for ASCII character
+
*Default:*
+
The delimiter specified in sync

Enclosing character:: Specify if the text columns in the source data needs to be enclosed in quotes.
+
Optional field.
+
*Example:*
+
DOUBLE
+
*Valid Values:*
+
Single, Double
+
*Default:*
+
DOUBLE
*Other notes:*
+
This is required if the text data has newline character or delimiter character.

Escape character:: Specify the escape character if using a text qualifier in the source data.
+
Optional field.
+
*Example:*
+
\"
+
*Valid Values:*
+
Any ASCII character
+
*Default:*
+
\"

Fetch size:: Specify the number of rows to be fetched at a time and processed in memory. If the value specified is zero then, all rows are extracted at once.
+
Mandatory field.
+
*Example:*
+
1000
+
*Valid Values:*
+
Any numeric value
+
*Default:*
+
1000

TS load options:: Specifies the parameters passed with the `tsload` command, in addition to the commands already included by the application. The format for these parameters is:
+
` --<param_1_name> <optional_param_1_value>`
+
` --<param_2_name> <optional_param_2_value>`
+
Optional field.
+
*Example:*
+
--max_ignored_rows 0
+
*Valid Values:*
+
--null_value "" --escape_character "" --max_ignored_rows 0
+
*Default:*
+
--max_ignored_rows 0
