= Delete a relationship
:last_updated: 02/01/2021
:linkattrs:
:experimental:

You can delete a relationship between tables through the ThoughtSpot application or TQL.

You must have either the xref:groups-privileges.adoc[*Can administer ThoughtSpot* or the *Can manage data* privilege] to delete a relationship.
If you're not an administrator, you also need edit permissions on the table, view, or worksheet.

If you created a relationship (join or link) between tables using the Web interface, you can also delete it from the Web interface.
But if the relationship was created using TQL, you must also use TQL to delete it.

xref:change-schema.adoc[To delete a relationship using TQL], use an `+ALTER TABLE...DROP CONSTRAINT...+` or `+ALTER TABLE...DROP RELATIONSHIP...+` statement.

To delete a relationship from the Web interface:

. Click *Data* on the top navigation bar.
. Click the name of the data source you from which you want to remove the relationship.
. Click *Joins*.
+
The list of existing joins appears.
+
In a worksheet, you must click *Joins within this worksheet* and choose *Joins from this worksheet*.

. Find the relationship you want to delete, and click the delete icon.
. Repeat these steps until all the joins you want to remove have been deleted.

== Related Information

* xref:constraints.adoc[Constraints]
