= Redshift connection reference
:last_updated: 01/24/2020

:redirect_from: /6.3.0/data-integrate/embrace/embrace-redshift-reference.html", "/6.3.0.CU1/data-integrate/embrace/embrace-redshift-reference.html

Learn about the fields used to create a Redshift connection using ThoughtSpot Embrace.

Here is a list of the fields of a Redshift connection in ThoughtSpot Embrace.
You need specific information to establish a seamless and secure connection.
All fields are required, except where noted.
+++<dlentry id="embrace-redshift-ref-connection-name">+++Connection name::::  Enter a new Redshift connection name.+++</dlentry>++++++<dlentry id="embrace-redshift-ref-connection-description">+++Connection description::::
Provide a short description of the connection.
_(Optional)_+++</dlentry>++++++<dlentry id="embrace-redshift-ref-host">+++Host::::  Enter the host name associated with the Redshift database.+++</dlentry>++++++<dlentry id="embrace-redshift-ref-port">+++Port::::  Enter the port number associated with the Redshift database.+++</dlentry>++++++<dlentry id="embrace-redshift-ref-user">+++User::::  Enter the Redshift account username.+++</dlentry>++++++<dlentry id="embrace-redshift-ref-password">+++Password::::  Enter the Redshift account password.+++</dlentry>++++++<dlentry id="embrace-redshift-ref-databse">+++Database::::  Specify the database associated with the account.+++</dlentry>+++
