= ThoughtSpot in Snowflake Partner Connect
:last_updated: 2/19/2020
:linkattrs:

Snowflake Partner Connect allows you to quickly and easily try out ThoughtSpot connected to Snowflake, using ThoughtSpot Embrace.

ThoughtSpot in Snowflake Partner Connect benefits:

* 30-day trial
* Easy to sign up
* Up and running in 5 minutes
* Trial data already loaded into Snowflake
* No data modeling required
* Gain first-hand experience of the power of ThoughtSpot search-driven insights

== Prerequisites

* A Snowflake account
+
If you don't have an account, you can sign up for a https://trial.snowflake.com/[free trial,window=_blank].

* Add the *try.thoughtspot.com* IP address to your list of allowed domains in your Snowflake account: `35.164.213.211`
* Read the xref:embrace-snowflake-best.adoc[best practices for Embrace with Snowflake].

== Sign up for the ThoughtSpot free trial in Snowflake Partner Connect

To sign up for the free trial, do the following:

. Log in to your Snowflake account.
. Click *Partner Connect*.
. Click *ThoughtSpot*.
The _Connect to ThoughtSpot_ window appears.
. Click *Connect*.
A ThoughtSpot account is created for you and an email titled _Activate Your ThoughtSpot Trial_ is sent to the email address associated with your Snowflake account.
This email contains activation instructions.
. Click *Activate*.
Your browser redirects to https://try.thoughtspot.com/[try.thoughtspot.com,window=_blank].
+
If you choose *Activate Later*, you can open the email and click *Start Trial Now* to navigate to try.thoughtspot.com.

. At try.thoughtspot.com, do the following:
 ** For *Username*, enter the email address associated with your Snowflake account.
 ** Enter your *Company Name*.
 ** Create a *Password*.
 ** Confirm the *Password*, by re-entering it.
 ** Check the checkbox for *I agree to Terms and Conditions*.
 ** Click *Sign in*.

+
Once you sign in, the ThoughtSpot home page appears.

== Using Embrace with Snowflake in the ThoughtSpot free trial

. From the ThoughtSpot home page, a _Connect to Snowflake_ guided tutorial appears at the bottom-right of the page.
You can play the video, which shows you the entire workflow of using Embrace to connect to Snowflake.
. Click *Next*, to be guided, step-by-step, through the process of connecting ThoughtSpot to Snowflake, selecting and searching a data source, changing a chart configuration, and more.
. Once you finish the tutorials, you are ready to try out your own searches, chart configurations, pinboard filters, and more.

== Related information

* xref:embrace-snowflake-tutorial.adoc[ThoughtSpot Tutorials for Snowflake Partner Connect]
* xref:embrace-intro.adoc[Embrace overview]
* xref:embrace-snowflake-add.adoc[Add a Snowflake connection]
* xref:embrace-snowflake-modify.adoc[Modify a Snowflake connection]
