= Synapse connection reference
:last_updated: 01/24/2020

:redirect_from: /6.3.0/data-integrate/embrace/embrace-synapse-reference.html", "/6.3.0.CU1/data-integrate/embrace/embrace-synapse-reference.html

Learn about the fields used to create a Synapse connection with ThoughtSpot Embrace.

Here is a list of the fields of a Synapse connection in ThoughtSpot Embrace.
You need specific information to establish a seamless and secure connection.
All fields are required, except where noted.
+++<dlentry id="embrace-synapse-ref-connection-name">+++Connection name::::  Enter a new Synapse connection name.+++</dlentry>++++++<dlentry id="embrace-synapse-ref-connection-description">+++Connection description::::
Provide a short description of the connection.
_(Optional)_+++</dlentry>++++++<dlentry id="embrace-synapse-ref-host">+++Host::::  Enter the host name associated with the Synapse database.+++</dlentry>++++++<dlentry id="embrace-synapse-ref-port">+++Port::::  Enter the port number associated with the Synapse database.+++</dlentry>++++++<dlentry id="embrace-synapse-ref-user">+++User::::  Enter the Synapse account username.+++</dlentry>++++++<dlentry id="embrace-synapse-ref-password">+++Password::::  Enter the Synapse account password.+++</dlentry>++++++<dlentry id="embrace-synapse-ref-database">+++Database::::  Specify the database associated with the account.+++</dlentry>+++
