= SAP HANA connection reference
:last_updated: 06/18/2020

:redirect_from: /6.3.0/data-integrate/embrace/embrace-hana-reference.html", "/6.3.0.CU1/data-integrate/embrace/embrace-hana-reference.html

Learn about the fields used to create an SAP HANA connection using ThoughtSpot Embrace.

Here is a list of the fields of an SAP HANA connection in ThoughtSpot Embrace.
You need specific information to establish a seamless and secure connection.
All fields are required, except where noted.
+++<dlentry id="embrace-HANA-ref-connection-name">+++Connection name::::  Enter a new SAP HANA connection name.+++</dlentry>++++++<dlentry id="embrace-HANA-ref-connection-description">+++Connection description::::
Provide a short description of the connection.
_(Optional)_+++</dlentry>++++++<dlentry id="embrace-HANA-ref-host-port">+++Host and port::::
Enter the host followed by a colon and the port number of the SAP HANA database.
+  + *Example*: If your host is `192.168.1.1`, and your port is `8080` you would enter `192.168.1.1:8080`.+++</dlentry>++++++<dlentry id="embrace-HANA-user-id">+++User::::  Enter the user associated with the SAP HANA database.+++</dlentry>++++++<dlentry id="embrace-HANA-password">+++Password::::  Enter the password associated with the user of the SAP HANA database.+++</dlentry>++++++<dlentry id="embrace-HANA-password">+++Database::::  Enter the database associated with the SAP HANA database.+++</dlentry>+++
