= Group API
:last_updated: 11/18/2019


The Group APIs enable you to set or remove a privilege to or from a group or multiple groups.

== Add a privilege

Use this API to add a `DATADOWNLOADING` or `USERDATAUPLOADING` privilege to the system default `ALL_GROUP` group.
All users in the system are always a part of the `ALL_GROUP` group.
By default, this group does not have either permission.

All the data sources which the `ALL_GROUP` group has permissions to are downloadable when `DATADOWNLOADING` is applied.

=== Resource URL

`post` /tspublic/v1/group/addprivilege

=== Request Parameters

`privilege`::
  Specifies a privilege type to add.
  Data type;; string
  Valid values;;
   * `DATADOWNLOADING` privilege
   * `USERDATAUPLOADING` privilege

`groupNames`::
  Specifies a group name where to add the privilege.
  Data type;; string
  Valid value;;
    * `ALL_GROUP` group.

=== Request Example

.cURL
----
curl -X POST --header 'Content-Type: application/x-www-form-urlencoded' --header 'Accept: application/json' --header 'X-Requested-By: ThoughtSpot' -d 'privilege=DATADOWNLOADING&groupNames=ALL_GROUP' 'https://<instance>/callosum/v1/tspublic/v1/group/addprivilege'
----

.Request URL
----
https://<instance>/callosum/v1/tspublic/v1/group/addprivilege
----

=== Response Example

----
Not applicable
204 - Success
----

== Remove a privilege

Use this API to delete a `DATADOWNLOADING` or `USERDATAUPLOADING` privilege from the system default ``ALL_GROUP``group.

=== Resource URL

`post` /tspublic/v1/group/removeprivilege

=== Request Parameters

`privilege`::
  Specifies a privilege type to delete.
  Data type;; string
  Valid values;;
    * `DATADOWNLOADING` privilege
    * `USERDATAUPLOADING` privilege.

`groupNames`::
  Specifies a group name from where to delete the privilege. 
  Data type;; string
  Valid value;;
    * `ALL_GROUP` group.

=== Request Example

.cURL
----
curl -X POST --header 'Content-Type: application/x-www-form-urlencoded' --header 'Accept: application/json' --header 'X-Requested-By: ThoughtSpot' -d 'privilege=USERDATAUPLOADING&groupNames=ALL_GROUP' 'https://<instance>/callosum/v1/tspublic/v1/group/removeprivilege'
----

.Request URL
----
https://<instance>/callosum/v1/tspublic/v1/group/removeprivilege
----

=== Response Example

----
Not applicable
204 - Success
----

////
## Error Codes

<table>
   <colgroup>
      <col style="width:20%" />
      <col style="width:60%" />
      <col style="width:20%" />
   </colgroup>
   <thead class="thead" style="text-align:left;">
      <tr>
         <th>Error Code</th>
         <th>Description</th>
         <th>HTTP Code</th>
      </tr>
   </thead>
   <tbody>
    <tr> <td><code>10003</code></td>  <td>Authentication token of type could not be authenticated by any configured realms.  Use valid realm that can authenticate these tokens.</td> <td><code>401</code></td></tr>

  </tbody>
</table>
////
