= Deploying on the SMC appliance
:last_updated: ["4/3/2020"]

Follow these steps to deploy ThoughtSpot on your Super Micro Computer (SMC) appliance.

[cols="5%,95%"]
|===
| &#10063;
| xref:prerequisites-smc.adoc[Step 1: Complete installation prerequisites]

| &#10063;
| xref:hardware-requirements-smc.adoc[Step 2: Review hardware requirements]

| &#10063;
| xref:connect-appliance-smc.adoc[Step 3: Connect your SMC appliance]

| &#10063;
| xref:configure-nodes-smc.adoc[Step 4: Configure nodes]

| &#10063;
| xref:smc-cluster-install.adoc[Step 5: Install cluster]
|===

This guide explains how to deploy ThoughtSpot on an SMC appliance, using ThoughtSpot's CentOS-based image.
You can also deploy ThoughtSpot on an SMC appliance using Red Hat Enterprise Linux (RHEL), allowing you to run ThoughtSpot on an RHEL 7.7 or 7.8 image that your organization manages internally.
To install ThoughtSpot using RHEL, refer to the xref:rhel.adoc[RHEL deployment guide].

== Related information

Use these references to aid you in successful installation and administration of ThoughtSpot.

* xref:nodesconfig-example.adoc[The nodes.config file]
* xref:parameters-nodesconfig.adoc[Parameters of the nodes.config file]
* xref:cluster-create.adoc[Using the tscli cluster create command]
* xref:parameters-cluster-create.adoc[Parameters of the cluster create command]
* xref:contact.adoc[Contact Support]
