= Introduction to administration
:last_updated: 09-23-2019

This guide covers all topics of special interest to application administrators.

This guide provides information for application administrators, or users with xref:logins.adoc[administrative access privileges].

Before addressing the major components of this guide, we recommend that you familiarize yourself with the general top-level xref:components.adoc[architecture] of the ThoughtSpot service.

Administrators are responsible for many facets of the ThoughtSpot service.
They are most frequently in charge of these common processes:

* xref:intro.adoc[Installation and setup of ThoughtSpot]
* xref:loading-intro.adoc[Loading and managing data]
* xref:about-users-groups.adoc[Managing users and groups]
* xref:about-security.adoc[Security]
* xref:sysadmin-overview.adoc[System administration]
* xref:choose-strategy.adoc[Backup and Restore]

Additionally, administrators are often involved in the following workflows:

* xref:about-data-modeling-intro.adoc[Data modeling]
* xref:about-worksheets.adoc[Using worksheets] to simplify search.
* xref:about-query-on-query.adoc[Using views] for 'stacked' search;
note that starting with Release 5.2, you can accomplish some aspects of search stacking by using the `IN` keyword (See xref:in-keyword-searches.adoc[in keyword searches]).
* xref:about-query-on-query.html[Enabling SearchIQ], ThoughtSpot's natural language search.
* xref:about-scheduled-pinboards.html[Managing scheduled jobs]
* xref:introduction.adoc[Monitoring system health]
* xref:troubleshooting-intro.adoc[Troubleshooting]
