= Prerequisites
:last_updated: 01/03/20201
:linkattrs:
:experimental:

Complete these prerequisites before installing your ThoughtSpot clusters on the SMC appliance.

[#installation-prerequisites]
== Installation Prerequisites

[options="interactive"]
.Ensure that you have the following items, information, and understanding of policies before you begin deploying ThoughtSpot on your SMC appliance:
* [ ] xref:connect-appliance-smc.adoc#haswell-port-location[1. Appliance Port Location], to locate data and IPMI ports.
* [ ] 2. Data center with proper environment controls, such as cooling.
* [ ] 3. AC power
* [ ] 4. 10GbE switch, with enabled IPv6 broadcast and multicast.
+
You must have one switch for each cluster, with one port for each node on the cluster.
* [ ] 5. 10GbE network cables, either direct attach copper (DAC) or fiber.
+
Refer to the xref:cable-networking.adoc[cable reference] for more information to decide between the two types.
* [ ] 6. 100Mbps or 1Gbps switch for IPMI, for Out of Band Management.
+
You must have one for each node in your cluster.
* [ ] 7. Cat5 network cables, for IPMI management port use.
+
You must have one for each node.
* [ ] 8. Rack space of 2U or 3.5 inches for each appliance, and a power strip.
* [ ] 9. VGA Monitor and USB keyboard
* [ ] 10. 10G connection: You need one SFP+ for each node for the switch side, and one SFP+ for each node for the appliance side.
* [ ] 11. Networking information: IP addresses for data & management NICs, for up to 2 DNS servers, up to 4 NTP servers and for the default gateway.
+
Ensure that you configure only two DNS servers. ThoughtSpot does not support configuration of three DNS servers.
+
You must know the timezone for your cluster. Typically, your timezone is where most of the people who will use the product are.
+
Download and fill out the ThoughtSpot xref:site-survey.pdf[site survey] so that you have a quick reference before beginning the install process. Ask your network administrator if you need help filling out the site survey.
* [ ] xref:ports.adoc[12. Review network ports], to determine the ports you need to have open for your cluster.

== Review hardware requirements

Next, xref:hardware-requirements-smc.adoc[review hardware requirements].
