= Prerequisites
:last_updated: 01/03/2021
:loinkattrs:
:experimental:

Complete these prerequisites to deploy ThoughtSpot on your Dell appliance.

== Installation prerequisites

[options="interactive"]
.Ensure that you have the following items, information, and understanding of policies before you begin installing your Dell 6420 appliance:
* [ ] 1. 10gbE switch with IPv6 broadcast and multicast enabled.
+
You must have one switch for each cluster, with one port for each node on the cluster.
* [ ] 2. Data center with proper environment controls, such as cooling.
* [ ] 3. AC power
* [ ] 4. 10G connection: You need one SFP+ for each node for the switch side.
+
Dell supplies SFP+'s for the appliance side.
* [ ] 5. 10GbE network cables, either direct attach copper (DAC) or fiber.
+
See the xref:cable-networking.adoc[cable reference] for more information to decide between the two types.
* [ ] 6. 100Mbps or 1Gbps switch for connection to the iDRAC (Out of Band Management) port.
+
You must have one for each node in your cluster.
* [ ] 7. Cat5 network cables, for iDRAC/ management port use.
+
You must have one for each node.
* [ ] 8. Rack space of 2U or 3.5 inches for each appliance, and a power strip.
* [ ] 9. VGA Monitor and USB keyboard
* [ ] 10. Networking information: IP addresses for data & management NICs, for up to 2 DNS servers, up to 4 NTP servers and for the default gateway.
+
Ensure that you only configure two DNS servers. ThoughtSpot does not support configuration of three DNS servers.
+
You also must know the timezone for your cluster. Typically, your timezone is the location of most of the people who use the product.

Download and fill out the ThoughtSpot xref:site-survey.pdf[site survey] so that you have a quick reference. Contact your network administrator if you need help filling out the site survey.

== Review hardware requirements

Next, xref:hardware-requirements-dell.adoc[review hardware requirements].
