= ThoughtSpot Support and Maintenance Guide
:last_updated: 01/26/2021
:linkattrs:
:experimental:

STATUS:: DRAFT

ThoughtSpot is committed to making customers successful in deploying and using ThoughtSpot, wherever they are
located. We provide 24x7 worldwide support and ongoing software updates to all our valued customers.

== Overview

ThoughtSpot technical assistance and software maintenance services for ThoughtSpot software as described herein. (“*Support*”) is made available by ThoughtSpot under the terms of this ThoughtSpot Support and Maintenance Program Guide (“*Guide*”).

This Guide makes use of the following defined terms: the agreement that grants rights to access and use the ThoughtSpot software and its incorporated or referenced order forms, purchase orders, addenda, and other documents are collectively the “*License Agreement*,” without regard to the name of the underlying agreement, nor how it refers to its parties or identifies ThoughtSpot’s software products; ThoughtSpot, Inc. or its applicable affiliate that entered into the License Agreement with Customer is “*ThoughtSpot*”; a distributor or reseller authorized by ThoughtSpot to sell licenses to ThoughtSpot software or Support to Customer is a “*Partner*”; an entity that has a current ThoughtSpot software license subject to a mutually signed License Agreement with ThoughtSpot or a ThoughtSpot Partner is the “*Customer*”; and ThoughtSpot’s online portal for support information and requests available at http://thoughtspot.com/support-request[ThoughtSpot Support,window="_blank"] (http://thoughtspot.com/support-request[http://thoughtspot.com/support-request,window="_blank"]) and its related and successor websites are collectively the “*Support Portal*.” Customer and ThoughtSpot are each referred to herein as a “party” and collectively as the “parties.” Capitalized terms used but not defined herein have the meaning ascribed to them in the License Agreement.

Support is available to Customer during the ThoughtSpot software license term as provided in the License Agreement between the parties. This Guide applies to Support purchased by Customer directly from ThoughtSpot or from any Partner. This Guide may be updated from time to time in ThoughtSpot’s sole discretion upon posting the new version to a link in the Support Portal.

This Guide describes the responsibilities of the parties regarding ThoughtSpot’s provision of Support. Please refer to instructions and documentation posted on the Support Portal for detailed information on Support procedures, including contact information, submission of tickets, roles, components used, alerting, request monitoring and escalations, file server access, and other procedural matters.

== Definitions

. “*Documentation*” means the then-current, published installation and operating instructions, user manuals, and help files made available by ThoughtSpot to Customer and intended for use in connection with the Software.
. “*Error*” means a reproducible failure of the Software to perform any material function set forth in the Documentation.
. “*Software*” means ThoughtSpot computer code licensed by ThoughtSpot to Customer under a License Agreement.
. “*Solution Data*” means aggregated and quantitative usage metrics and other data derived from Customer’s use of the Software. Solution Data excludes Customer Data.
. “*Technical Contact*” means a qualified individual designated by Customer for the purpose of receiving Support.
. “*Update*” means a patch or hotfix of an Upgrade that: (a) provides maintenance updates only, Error corrections, or bug fixes; or (b) introduces limited new functionality or enhancements. An example of a patch includes version 5.1.1, and an example of a hotfix includes version 5.1.1.1.
. “*Upgrade*” means a release of the Software that includes new functionality, extensions, features, or significant enhancements, as described in the Documentation as Major Releases (e.g., version 5.0), or Minor Releases (e.g., version 5.1).

== Scope of Support

Only Software that is properly registered, validly licensed, and unaltered is eligible for Support. Support does not include
implementation, configuration, customization, integration, or training services.

For all Software, ThoughtSpot will:

. provide Support during the license term for the current Upgrade of the Software and any Updates thereto, and
the immediate prior Upgrade and any Updates thereto;
. provide Support 24 hours a day, 7 days a week, including all holidays;
. answer questions from Customer regarding the operation of the Software primarily via ThoughtSpot’s Support Portal and secondarily via telephone and e-mail;
. use commercially reasonable efforts to correct any Errors reported by Customer and confirmed by ThoughtSpot in accordance with the priority level assigned to the Error in the ThoughtSpot Support Portal, including through the application of Updates and Upgrades;
. use commercially reasonable efforts to respond to each reported Error according to the Support Process section below. Responses may take the form of Updates and Upgrades, procedural solutions, correction of Documentation errors, or other remedial measures as ThoughtSpot may determine, in its sole discretion, to be appropriate; and
. provide Customer with any generally available Updates and Upgrades applicable to Customer’s licensed Software.

== Support Process

For each Error, Customer may assign in the ThoughtSpot ticketing system a priority level based on the relative impact an Error has on the use of the Software. ThoughtSpot may re-assign the priority level in its sole discretion. Priority levels and target initial response times for each priority level are described below.

[width="100%",cols="10%,75%,15%",options="header"]
|====================
| Priority | Description | Initial Response

| P0
| Production Software is unavailable; all users are blocked and
productivity halted.
| Within 1 hour

| P1
| Production Software is available; functionality or performance is
severely impaired.
| Within 2 hours

| P2
| Production Software is available and usable with partial, noncritical loss of functionality, or the production Software has an
occasional issue that Customer would like identified and
resolved. Requests for help on administrative tasks.
| Within 4 hours

| P3
| Cosmetic issues or request for general information about the
Software, Documentation, process or procedures.
| By next business day

|====================

== Exclusions

ThoughtSpot will have no Support obligations for any problems attributable to:

. use of the Software not in accordance with the Documentation or express written instructions provided by ThoughtSpot necessary to use the Software on devices (including specific configurations, hardware, and virtual infrastructure) that are not described in the Documentation;
. installation of the Software on hardware or virtual infrastructure failing to meet the requirements described in the Documentation;
. use of Software that is not the current Upgrade or the immediate prior Upgrade;
. modifications or alterations to the Software after its download made by a party other than ThoughtSpot or a ThoughtSpot Partner;
. configuration of the operating environment or data center, network latency, or causes beyond the reasonable control of ThoughtSpot; or
. third-party software not provided by ThoughtSpot.

== Maintenance

ThoughtSpot will make available to Customer generally available Updates and Upgrades to the Software no later than it makes the same available to ThoughtSpot’s similarly situated customers. ThoughtSpot has no obligation to create or provide any Updates or Upgrades. ThoughtSpot may, however, elect to provide Updates and Upgrades, including by uploading such directly to the Software, wherever provisioned. Additional features implemented in a new version may require purchase of an additional license to use the new features.

== Customer Responsibilities

ThoughtSpot’s Support obligations are conditioned upon Customer meeting the following obligations. Customer must:

. screen first-line technical inquiries and escalate to ThoughtSpot only those Errors that Customer’s Technical Contacts have been unable to resolve;
. designate a limited number of Technical Contacts to make Support requests. Technical Contacts must provide reasonable assistance to resolve Support issues, and to provide updates to ThoughtSpot using the Support Portal;
. install Upgrades to at least the immediate prior Upgrade;
. install any Updates, with ThoughtSpot assistance as needed, identified as “critical” by ThoughtSpot;
. ensure that proper licenses were obtained for all Software and adhere to the terms of the License Agreement, and grant ThoughtSpot reasonable access to the Software to verify Customer’s use;
. ensure that Customer has properly procured, installed, and maintained all equipment, communication interfaces, and other hardware necessary to operate the Software; and
. make available to ThoughtSpot accurate Customer system performance data, networking information and other materials reasonably required by ThoughtSpot solely as necessary to provide Support.

== Support Provisioning

. *Agreement*. This Guide constitutes the complete and exclusive agreement between Customer and ThoughtSpot relating to its subject matter and supersedes all prior oral and written agreements, understandings, representations, warranties, and communications regarding its subject matter. In the event of any conflict between the terms and conditions of this Guide and the License Agreement signed by Customer and ThoughtSpot, the License Agreement will govern to the extent of such conflict.
. *Purchasing Through Partners*. If Customer purchased Support from a Partner, Customer agrees that this Guide will apply to its receipt and use of Support, notwithstanding anything to the contrary in your License Agreement with the Partner. ThoughtSpot will not be liable for any contractual obligation made by the Partner or any other third party beyond those set forth in this Guide. Customer acknowledges that if ThoughtSpot does not receive payment for the Software or Support from its Partner, ThoughtSpot will have the right to suspend the Support until payment is received, without liability to you and you must look solely to the Partner for any damages or liability associated with such suspension.
. *Solution Data*. ThoughtSpot may collect, use, and disclose Solution Data to operate, support, improve and develop its Software and for industry analysis, benchmarking, marketing and other business purposes.
. *Termination*. Unless earlier terminated in accordance with the terms of the License Agreement, Support terminates upon expiration or termination of the License Agreement.
