= Release Schedule
:last_updated: 01/22/2021
:linkattrs:
:experimental:

STATUS:: DRAFT

== ThoughtSpot Release Schedule

We support each major release line of the ThoughtSpot for one year after it enters general availability (GA).

[width="100%","2,2,1,2,2,1",options="header"]
|====================
| Release line | Latest release | Status | GA date | Maintenance | EOL

| ThoughtSpot 7.x
| N/A
| Pending
| CL Feb 2021, SW Mar 2021
| TBD
| TBD

| ThoughtSpot 6.x
| 6.3
| Active
| November 7, 2019
| April 2021
| April 2022

| ThoughtSpot 5.x
| 5.3.2 CU3
| Maintenance
| November 14, 2018
| December 7, 2019
| December 2021
|====================

GA Date::
  The General Availability (GA) of a release line, such as ThoughtSpot 7.x, is the date we release the initial major version of the product.

  *ThoughtSpot 7.0 SW*;; GA date for our Software (On-Prem) offering is when we make it available for installation or upgrade.
  *ThoughtSpot 7.0 CL*;; GA date for our Cloud (SaaS) offering is when we announce the new release of our start upgrading our service clusters.

Status::
  The status of the release line.

  Active;; We are actively improving and supporting the new line, introducing new features and hardening the performance of the new functionality.
  Pending;; We are working on the initial first version in the release line; some clients in _Early Adopter_ program may experiment with pre-release versions of the product in their development environment.
  Maintenance;; When the release line is in maintenance mode; there are no improvements in functionality of features, only security updates.

Maintenance::
  After we release the new major version of the product, the *n-1* version line begins its maintenance period. For example, the GA of 7.0 precedes the beginning of maintenance for the 6.x release line. In this phase, only the most recent minor version receive critical security patch releases. A release line starts this phase 30 days after the next major release line goes GA.

End of Life (EOL)::
  This is the termination date for the maintenance window, when we completely stop support for the release line.

== Version policy

ThoughtSpot adheres to  semantic versioning rules. Each ThoughtSpot component has the following version signature: _major_._minor_._patch_.

Major::
  Major releases introduce substantial changes in features and functionality. They may also have advances that break backwards compatibility, and deprecate large groups of related features. Releases within the same major release line maintain feature compatibility and API compatibility.

Minor::
  Minor releases add new features, improvements and hardening to existing features, and fixes that maintain backwards compatibility.

Patch::
  Patch releases fix bugs and maintain backwards compatibility. We only patch the latest minor releases of a major release line.
+
Patch releases don't have a set schedule. Instead, we release patches for two reasons:
+
* Patches of customers who need an urgent correction to a feature
* Security patches

Prerelease::
  _*This is just a suggestion.*_
+
Major and minor releases may include prerelease versions, such as:
+
`_major_._minor_._patch_[-alpha._n_|-beta._n_|-rc._n_]`
//Prerelease versions will be tagged as next so that the npm client doesn’t prefer a prerelease over a stable version. Once a release candidate (rc) has been thoroughly tested, the stable release will be published.
//

== Roadmap

_*This is just a suggestion; we may not wish to include this section at all, or keep it at a very high level.*_

Refer to ThoughtSpot's external product roadmap _*insert link here*_ for the list of features in active development or planned for future major and minor releases.

These proposed features, their scope, and the release timeframes are estimates, not firm commitments. These milestones are intended for informational purposes only.
