= ThoughtSpot deployment templates for RHEL
:last_updated: 10/13/2020


Get the two primary tarball artifacts for configuring ThoughtSpot using RHEL.

You must have the following artifacts to install or upgrade ThoughtSpot applications that run on RHEL:

* The *Ansible tarball*, the *Terraform template*, the *Chef template*, and the *Puppet* template each contain a set of scripts for installing OS packages, dependencies, the ThoughtSpot CLI (tscli), and configuring your cluster (preparing the disks).
Choose *_one_* of these four templates, depending on which tool you have in your organization.
You can obtain these by requesting them from https://community.thoughtspot.com/customers/s/contactsupport[ThoughtSpot Support].
* The *Release tarball* contains the ThoughtSpot software binaries (`tar.gz`) of the release version you are installing or upgrading;
for example, ThoughtSpot Release 6.0.4.
You can obtain this file from the https://thoughtspot.egnyte.com/[ThoughtSpot secure file sharing system].
We sent this information to you in our Welcome email.
Contact ThoughtSpot Support if you experience difficulties accessing these files.
