= ThoughtSpot artifacts for RHEL
:last_updated: 10/13/2020

Get the two primary tarball artifacts for configuring ThoughtSpot using RHEL.

You must have the following artifacts to install or upgrade ThoughtSpot applications that run on RHEL:

* The *Ansible tarball* and the *Terraform template* each contain a set of scripts for installing OS packages, dependencies, the ThoughtSpot CLI (tscli), and configuring your cluster (preparing the disks).
Choose *_either_* the Ansible tarball or the Terraform template, depending on which tool you have in your organization.
Please join our RHEL Early Access program, and email us your link:mailto:early_access@thoughtspot.com?subject=RHEL%20Early%20Access%20Program%20Ansible%20File%20Request[Ansible] or link:mailto:early_access@thoughtspot.com?subject=RHEL%20Early%20Access%20Program%20Terraform%20File%20Request[Terraform request].
* The *Release tarball* contains the ThoughtSpot software binaries (`tar.gz`) of the release version you are installing or upgrading;
for example, ThoughtSpot Release 6.0.4.
You can obtain this file from the https://thoughtspot.egnyte.com/[ThoughtSpot secure file sharing system].
We sent this information to you in our Welcome email.
Contact ThoughtSpot Support if you experience difficulties accessing these files.
