= Set entity categories for SearchIQ
:last_updated: 09/23/2019

Entity categories help describe the column content, and assist SearchIQ in interpreting natural language queries.

NOTE: SearchIQ is in Beta.

* SearchIQ is only available in English.
* SerchIQ is in [.label.label-beta]#Beta#, and off by default;
to enable it, contact xref:contact.adoc[ThoughtSpot Support].
* You must have the *Can use experimental features* permission.

Entity categories specify how to categorize the data in the column, by entity type.
By default, `ENTITY TYPE` is not set.
Entity categories support xref:about-searchiq.adoc[SearchIQ] so that when you type a natural question, ThoughtSpot better knows how to interpret it.
For example, if you ask "who are the top performers?" ThoughtSpot will first choose columns set with `PERSON` from which to return answers.
If you ask "when was the movie Jurassic Park released?", columns set to `TIME` will be used to answer the "when" part of the question, and so forth.

// You can specify a per column entity category to help SearchIQ.

If you have access to tables and worksheets for data modeling purposes, you can specify entity categories for their columns.
This lets you designate that column as representing a person, place, or thing.
So then when a user asks "Which", "Who", or "Where", an appropriate response can more easily be found in the data.

If you're not sure how to change the data modeling settings, see the xref:data-modeling-settings.adoc[Overview of data modeling settings].

== About Entity Categories

These are the available Entity Categories:
[width="100%",options="header",cols="20%,80%"]
|===
| Category | Description

| PERSON
| Contains data that represents a person, relevant to questions about "who?"

| PLACE
| Contains data that represents a location, relevant to questions about "where?"

| TIME
| Contains data that represents a date or time, relevant to questions about "when?"

| PRODUCT
| Contains data that represents a product

| ZIP_CODE
| Contains zip code data, relevant to questions like "where?" or "what zip code?"

| LAT_LONG
| Contains data that represents geographical positioning, relevant to questions like "where?"

| COMPANY_ORG
| Contains data that represents a company or organization

| NUM_TYPES
| Contains numerical data
|===

== Set Entity Categories

To specify entity categories:

. Click *Data* in the top menu, and choose *Tables* or *Worksheets*.
. Click the name of your table or worksheet.
. On the *Columns* tab, find the COLUMN NAMES for which you want to specify entity categories, and scroll to the right to find `ENTITY CATEGORY`.
. Use the drop-down menu to set the `ENTITY CATEGORY` to the type you want.
. Click *SAVE CHANGES* in the upper right.

== Related information

* xref:about-searchiq.adoc[SearchIQ]
* xref:data-modeling-settings.adoc[Overview of data modeling settings]
