= Connection configuration
:last_updated: 02/11/2021
:linkattrs:
:experimental:

Lists the properties you can set for ODBC or JDBC connections

This section lists the properties you can set for ODBC or JDBC connections.

== Setting Properties for ODBC

Not all the parameters Simba accepts are supported by the ThoughtSpot ODBC clients, and ThoughtSpot has added some properties, which are listed separately here.
All configuration properties use the type String (text).

You can set these properties on Windows by using the xref:install-odbc-windows.adoc[ODBC Administrator] client.
For Linux, the properties are located in three files, depending on the property  type:

DSN::
  Location;; `odbc.ini` file

Driver::
  Location;; `odbsinst.ini` file

SimbaSetting Reader::
  Location;; `simbaclient.ini` file

== Setting Properties for JDBC

For JDBC, these properties are passed as key value pairs in the connect string.
For more information, see xref:use-jdbc-driver.adoc[Use the JDBC Driver].

== Properties Reference

The following tables summarize the configuration properties.

DATABASE::
  The default database for connecting.
  Type;; DSN or Driver

SCHEMA::
  The default schema to connect to.
  Type;; DSN or Driver

Description::
  A brief, human-readable description of the DSN. This describes the DSN to users who are deciding which DSN to use.
  Type;; DSN

Driver::
  In the driver configuration location, Driver should contain the path to the driver binary. In the DSN configuration location, Driver could contain the path to the driver binary, or it could contain the driver entry in the registry.
  Type;; DSN or Driver

IdleTimeout::
  The time to wait for a response from the server, in seconds. This property is optional, but SimbaClient will wait indefinitely for SimbaServer to respond to a request made to the server unless you specify a timeout period.
+
`IdleTimeout` specifies how many seconds that SimbaClient will wait before aborting the attempt and returning to the application with an error. This timeout corresponds to ODBC's `CONNECTION_TIMEOUT` property and is only used when more specific timeouts, such as `QUERY_TIMEOUT` or `LOGIN_TIMEOUT` aren't applicable.

  Type;; DSN

Locale::
  The connection locale. If this value is set, it overrides the driver-wide locale. For example, the driver-wide locale could be `en-US`. If the client would prefer `fr-CA`, it can set the connection locale to `fr-CA`.
+
Values are composed of a 2-letter language code (in lower case), and an optional 2-letter country code (in upper case). If the country code is specified, it must be separated from the language code by a hyphen (-).
  Type;; DSN

LoginTimeout::
  The timeout, in seconds, to wait for a response from the server when attempting to log in. A value of 0 means no timeout. The default value is 60.
  Type;; DSN

QueryTimeout::
  The timeout, in seconds, to wait for a response from the server during Prepare, Execute, and ExecuteDirect. A value of 0 means no timeout. The default value is 60.
  Type;; DSN

ServerList::
  A comma separated list of all servers (IP address and port number) to connect to. SimbaClient must be able to find SimbaServer on the network. This property enables server discovery. SimbaClient will try to make a network connection to the servers in the order specified until a connection is made.
  Type;; DSN

LogLevel::
  Controls the granularity of the messages and events that are logged.
+
With this keyword, you can control the amount of log output by controlling the kinds of events that are logged.
+
Type;; SimbaSetting Reader
Possible values;;
+
(case sensitive)
+
[horizontal]
`0` or `LOG_OFF`::: no logging
`1` or `LOG_FATAL`::: only log fatal errors
`2` or `LOG_ERROR`::: log all errors
`3` or `LOG_WARNING`::: log all errors and warnings
`4` or `LOG_INFO`::: log all errors, warnings, and informational messages
`5` or `LOG_DEBUG`::: log method entry, exit points, and parameter values for debugging
`6` or `LOG_TRACE`::: log all method entry points

LogPath::
  Specifies the directory where to create the log files. For example:
+
`LogPath=C:\Simba Technologies\Temp`
+
If this value is not set, the log files are written to the current working directory of the SimbaClient.
+
Type;; SimbaSetting Reader

LogFileSize::
  The size of each log file, in bytes. When the maximum size of the file is reached, the system creates a new file.
  Type;; SimbaSetting Reader
  Default value;; 20971520 bytes

LogFileCount::
  The number of log files to create. When the maximum number of log files has been created, the oldest file will be deleted and a new one created.
  Type;; SimbaSetting Reader
  Default value;; 50


username::
  Part of a user username/password combination. This combination should correspond to a ThoughtSpot application user with permissions appropriate to your ETL requirements.
+
Typically, this user is a user with data management or administrative privileges on the application.
+
Type;; UID

password::
  Part of a user username/password combination. This combination should correspond to a ThoughtSpot application user with permissions appropriate to your ETL requirements.
+
Typically, this user has data management or administrative privileges on the application.
+
Type;; Password
