= Set columns to exclude from SpotIQ analyses

You can specify columns to exclude from SpotIQ analyses.

xref:spotiq:whatisspotiq.adoc[SpotIQ] is a ThoughtSpot feature that provides users with insights about their data by automatically surfacing interesting characteristics (trends, correlations, outliers, and so on).

If you have access to tables, worksheets, and views for data modeling purposes, you can specify columns to exclude from SpotIQ analyses.
By default, all columns are _included_ in SpotIQ analyses.

== Exclude columns from SpotIQ analyses

To specify columns to exclude from SpotIQ analyses:

. Click *Data* in the top menu, and choose *Tables*,  *Worksheets*, or *xref:about-query-on-query.adoc[Views]*.
. Click the name of your data source.
. On the *Columns* tab, find the COLUMN NAMES you want to exclude from SpotIQ analyses, and scroll to the right to find `SPOTIQ PREFERENCE`.
. Use the drop-down menu to set the `SPOTIQ PREFERENCE` to *EXCLUDE* for each column you want to exclude.
. Click *SAVE CHANGES* in the upper right.

== Include columns in SpotIQ analyses

By default, all columns are included in SpotIQ analyses.

If you have previously set some columns to EXCLUDE and you want to re-set these to be included, do the following.

. Click *Data* in the top menu, and choose *Tables*, *Worksheets*, or *xref:about-query-on-query.adoc[Views]*.
. Click the name of your data source.
. On the *Columns* tab, find the COLUMN NAMES you want to set back to include in SpotIQ analyses, and scroll to the right to find `SPOTIQ PREFERENCE`.
. Use the drop-down menu to set the `SPOTIQ PREFERENCE` to *DEFAULT* for each column you want to include.
. Click *SAVE CHANGES* in the upper right.

== Related information

* xref:whatisspotiq.adoc[SpotIQ tutorial]
* xref:data-modeling-settings.adoc[Overview of data modeling settings]
