= July 2024 release notes
:last_updated: 3/23/2021
:experimental:
:linkattrs:
:page-layout: default-cloud
:page-aliases:
:description: ThoughtSpot Cloud 10.0.0.cl release notes

These new and enhanced features of ThoughtSpot Cloud were released in July 2024.

== ThoughtSpot Cloud 10.0.0.cl

[#10-0-0-cl-analyst]
=== For the Analyst

// Naomi. SCAL-201639
[#advanced-conditional]
Advanced conditional formatting [.badge.badge-early-access-relnotes]#Early Access#::
In addition to using conditional formatting to visually highlight a threshold in a measure (for example, `sales > 10000`), you can now use conditional formatting to compare a column's measures to another column.
// or to a parameter.
+
For example, if you search for `sales this year` compared to `sales last year`, you can highlight where sales this year were less than last year. You can set multiple conditional formatting rules to a single table. To enable this feature, contact your administrator.
+
For more information, see
xref:search-conditional-formatting.adoc#advanced-conditional-formatting[Advanced conditional formatting].
[#grouping-measures]
Grouping measures in pivot tables [.badge.badge-beta-whats-new]#Beta#::

ThoughtSpot now supports grouping measure in pivot tables. You can now move measures, and position them where you want in rows and columns. For more information, see xref:chart-pivot-table.adoc[Pivot tables].
// Mary. SCAL-181678. docs JIRA: SCAL-211771


// [#10-0-0-cl-business-user]
// === For the Business User

[#10-0-0-cl-data-engineer]
=== For the Data Engineer
[#version-control]
Version control for Liveboards and Answers::
Version control for Liveboards and Answers is now available to all users. Now teams of analysts can more easily collaborate on content development of Liveboards and Answers. You can enable version control on specific Liveboards and Answers. With version control enabled, every time you save the Liveboard or Answer, a new version is created and stored. You can browse the version history in ThoughtSpot and restore any saved versions whenever you need to. To enable this feature, contact your administrator. For more information, see
xref:liveboard.adoc#version-history[Liveboards] and xref:answers.adoc#version-history[Answers].

// doc jira: SCAL-213208

[#10-0-0-cl-it-ops]
=== For the IT/Ops Engineer
[#iam-v2]
IAM v2 migration::
ThoughtSpot is upgrading our Identity and Access Management (IAM) capabilities to provide a more secure login and authentication experience. This experience has been improved to ensure that you can upgrade to IAM v2 easily and with minimal downtime. For more information, see xref:okta-iam.adoc[Identity and Access Management V2].
// Mary. SCAL-191815. docs JIRA: SCAL-211956
[#org-deletion]
Org deletion::
You can now delete an Org without first manually deleting the data objects, connections, groups, and users within the Org. For more information, see xref:admin-console-orgs-page.adoc[Create, edit, and delete Orgs].
// Mary. SCAL-179795. docs JIRA: SCAL-201819

[#10-0-0-cl-developer]
=== For the Developer

ThoughtSpot Embedded:: For information about the new features and enhancements introduced in this release, refer to https://developers.thoughtspot.com/docs/?pageid=whats-new[ThoughtSpot Developer Documentation^].