= June 2025 release notes
:last_updated: 6/30/2025
:experimental:
:linkattrs:
:page-layout: default-cloud
:page-aliases:
:description: ThoughtSpot Cloud 10.9.0.cl release notes

These new and enhanced features of ThoughtSpot Cloud were released in May 2025.

== ThoughtSpot Cloud 10.10.0.cl

[#10-10-0-cl-business-user]
=== For the Business User

// Naomi – jira: SCAL-244702. docs jira: SCAL-258659
[#alerts-by]
Alerts by attribute:: Alerts by attribute are now available to all users and on by default. You can now set KPI alerts to trigger when a selected attribute changes. This can include changes in the value of the attribute, such as an increase in sales by percentage by state, or a scheduled alert to trigger on a weekly basis.
+
For example, if you wanted to create an alert for a KPI tracking sales of different phones by brand, you could choose the intended brands as attributes and set an alert to be notified when sales for those specific brands dropped by 5%.
+
For more information, see xref:monitor-alert-attributes.adoc[Create an alert by attributes].

[#10-10-0-cl-analyst]
=== For the Analyst

// Naomi. jira: SCAL-249991. docs jira: SCAL-260724.
[#feedback-and]
Feedback and learnability for Spotter Agent [.badge.badge-beta-relnotes]#Beta#::
When Spotter Agent is enabled, you can give feedback with additional details, and leave comments that are reviewed by your administrator. The feedback you give will appear in the Spotter Conversations Liveboard. To enable this feature, contact {support-url}. For more information, see xref:spotter-agent.adoc#feedback[Spotter Agent].

// Naomi. docs jiraL SCAL-258753
[#spotter-analytics]
Spotter analytics model changes:: We made the following changes to the TS: Spotter analytics data model, which is used by the Spotter Conversations Liveboard:
+
--
* Added the Hidden, User Feedback Labels, and User Feedback Comments columns
* Renamed the User Feedback column to User Feedback Rating
--
+
For more information, see xref:spotter-conversations-liveboard.adoc[Spotter Conversations Liveboard].


[#10-10-0-cl-data-engineer]
=== For the Data Engineer

// Naomi. jira: SCAL-221427. docs jira: SCAL-256366
[#progressive-model]
Progressive model filters [.badge.badge-beta-relnotes]#Beta#:: Previously, any filter defined at the Model or Worksheet level applied to every query based on that Model or Worksheet. Now, you can define which table a filter applies to in the Model or Worksheet TML. Once defined, the filter only applies to queries that include columns from that specific table.
+
For more information, see xref:tml-models.adoc#apply_on_tables[TML for Models].

// Naomi. jira: SCAL-214002. docs jira: SCAL-259366
[#monitor-application]
Monitor application of row-level security at database level:: When opening SQL comments in your database, you can now see whether RLS was applied to specific queries. In the SQL comments, you can check whether the value for `isRLSApplied` is true or false.


// Mary. jira: SCAL-245938. docs jira: SCAL-255650
[#spotter-conversations]
Spotter Conversations Liveboard available in all Orgs:: The Spotter Conversations Liveboard is now available by default in all Orgs. In the primary Org, only administrators have access by default.
In secondary Orgs, Org administrators can access this Liveboard, similar to other system objects.
+
For  more information, see xref:spotter-conversations-liveboard.adoc[Spotter Conversations Liveboard].

// Rani. docs jira: SCAL-258586
[#orgs-support]
Orgs support for ThoughtSpot plug-ins:: The Microsoft PowerPoint add-in and the Google Slides add-on now support Orgs in ThoughtSpot. Orgs functionality is enabled by default in the xref:thoughtspot-powerpoint.adoc[Microsoft PowerPoint add-in]. To enable Orgs in the xref:thoughtspot-slides.adoc[Google Slides add-on], please contact {support-url}.


// Mary. jira: SCAL-240367. docs jira: SCAL-238563
[#query-tags]
Query tags for Snowflake connections::
ThoughtSpot introduces support for query tags on Snowflake connections. You can now set up query tags on your Snowflake connection to allow you to filter on users, groups, or other ThoughtSpot variables when auditing the Snowflake query logs.
+
For more information, see xref:connections-snowflake-add.adoc[Add a Snowflake connection].


[#10-10-0-cl-developer]
=== For the Developer

ThoughtSpot Embedded:: For information about the new features and enhancements introduced in this release, refer to https://developers.thoughtspot.com/docs/?pageid=whats-new[ThoughtSpot Developer Documentation^].
