= February 2025 release notes
:last_updated: 3/23/2021
:experimental:
:linkattrs:
:page-layout: default-cloud
:page-aliases:
:description: ThoughtSpot Cloud 10.6.0.cl release notes

These new and enhanced features of ThoughtSpot Cloud were released in February 2025.

== ThoughtSpot Cloud 10.6.0.cl

[#10-6-0-cl-analyst]
=== For the Analyst

// Naomi. jira: SCAL-158897. docs jira: SCAL-238614
[#passthrough-filters-for-sets]
Passthrough filters for sets [.badge.badge-early-access-relnotes]#Early Access#:: You can now pass filters from a query into a set definition without needing to remake the set to include the filter. For example, if you create a query set defined as a list of SKUs that are ranked based on sales, where 1 through 10 are defined as Gold, 11 through 50 are defined as Silver, and the remainder are defined as Bronze, you can now add a filter such as Region. You can configure the set's filter behavior from the TML, instructing ThoughtSpot to exclude or include specific columns, or to accept all filters by default. To enable query sets, contact your administrator.
+
For more information, see
xref:query-sets.adoc#passthrough[Passthrough filters for query sets].

// Mary. jira: SCAL-194972. docs jira: SCAL-236113
[#advanced-condtional-formatting]
Advanced conditional formatting::
Advanced conditional formatting is now available to all users and on by default.
In addition to using conditional formatting to visually highlight a threshold in a measure (for example, `sales > 10000`), you can now use conditional formatting to compare a column's measures to another column. You can set multiple conditional formatting rules to a single table.

For more information, see xref:search-conditional-formatting.adoc#advanced-conditional-formatting[Advanced conditional formatting].


// Naomi. jira: SCAL-224932. docs jira: SCAL-240854
[#custom-comparison-point-for-kpi-charts]
Custom comparison point for KPI charts:: Custom comparison points for KPI charts are now on by default and available to all users. Previously, time-series KPI charts had limited options when comparing to past periods. For example, a weekly KPI could be compared against the previous week, the previous month's same week, the previous quarter's same week, or the previous year's same week. Now, you can set a custom point in data against which ThoughtSpot compares the most recent data point, any number of weeks ago. This feature is applicable to all KPIs including time keywords like `weekly`, `monthly`, or `quarterly`.  Your chosen comparison point persists for all viewers of the KPI. To enable this feature, contact your administrator.
+
For more information, see xref:chart-kpi.adoc#kpi-custom-comparison[KPI charts].

// Naomi. docs jira: SCAL-?
[#kpi-change-analysis]
KPI change analysis::
We made the following changes to change analysis for KPI charts:
+
--
* To open change analysis on a KPI chart, click the *Change analysis* button at the bottom of the chart.
* When opening change analysis on a KPI, users see a summary of all changes.
* KPI anomalies no longer appear as red points on the sparkline, they are labeled as out of the expected range of values.
To enable these changes, contact {support-url}.
--


// Naomi. jira: SCAL-196221. docs jira: SCAL-240309
[#group-aggregates-in-change-analysis]
Group aggregates in change analysis:: You can now run change analysis on queries that contain group aggregate expressions.
[#suggest-indexing-of-columns-for-spotter]
Suggest indexing of columns for Spotter::
In this release, we introduce *Optimize for Spotter*. It is an easier way of indexing the Worksheet and Model attribute columns required for accurate searches on specific column values in Spotter. After enabling Sage on a Worksheet or Model and clicking the *Optimize for Spotter* button, ThoughtSpot detects which columns are not indexed and allows you to index the ones you need for Spotter. For more information, see xref:spotter-worksheet-model.adoc#optimize-spotter[Optimize for Spotter].

// Mary. jira: SCAL-138848. docs jira: SCAL-238563
[#reorder-parameters-in-liveboards-and-answers]
Reorder parameters in Liveboards and Answers [.badge.badge-early-access-relnotes]#Early Access#::
You can now reorder the parameters in Liveboards and Answers, in the same way that you can reorder filters. When you edit a Liveboard or Answer to reorder the parameters and save your changes, the new order is reflected when anyone opens the Liveboard or Answer. To enable this feature, contact your administrator.
+
For more information, see xref:parameters-use.adoc[Reorder parameters in Liveboards and Answers].

[#improved-error-messaging-in-data-model-editor]
Improved error messaging in Data model editor::
The Data model editor has enhanced error messaging to help you understand and fix errors. Global errors, like a session expiring or an error when saving changes, are now displayed in a pop-up window. Local errors, associated with a specific tab, display a red dot on the tab and a banner under the tab after it is selected.
[#new-security-log-events-for-data-modeling]
New security log events for data modeling::
In this release, we've added new security log events for creating, updating, and deleting the following:

- Tables
- Imported tables
- SQL views
- Worksheets

You can access security logs from ThoughtSpot by pushing the logs to your SIEM server, or by pulling the logs using the Audit Logs API. For more information, see xref:audit-logs.adoc[Collect security logs].
[#custom-charts]
Custom charts::
Custom charts are now available to all users and on by default. Custom charts allow you to use charts created outside of ThoughtSpot, including from third-party chart libraries. For more information, see xref:chart-custom.adoc[Custom charts].

// Mary. jira: SCAL-224447. doc jira: SCAL-236449
[#pivot-table-charts]
Pivot table charts [.badge.badge-early-access-relnotes]#Early Access#::
ThoughtSpot introduces a brand new pivot table chart. The new pivot table charts have the following features:

* Faster load times with pagination.
* You can now expand and collapse all in pivot tables.
* We now support custom sort order.
* You can now adjust column widths.
* You can now slice with measures and attributes.
* You can now use values for more granular control in configurations.

+
To enable this feature, contact your administrator. For more information, see xref:chart-pivot-table.adoc#pivot-table-2-0[Pivot table charts].


[#10-6-0-cl-business-user]
=== For the Business User

// Naomi. jira: SCAL-226925. docs jira: SCAL-239972
[#spotter-in-slack]
Spotter in Slack [.badge.badge-beta-relnotes]#Beta#::
Where previously you could ask questions in natural language in Slack using the ThoughtSpot app, you can now use Spotter to conversationally search your data in Slack. Follow-up questions remain within the same thread, preserving context. Pin a Worksheet or Model to a channel to ensure quick access to data from that Worksheet or Model. To enable this feature, contact {support-url}.
+
NOTE: Spotter in Slack is not available for TSE and GCP clusters yet.
+
For more information, see xref:spotter-app-for-slack.adoc[Spotter in Slack].

// Mary. jira: SCAL-175792. docs jira: SCAL-238562
[#show-only-relevant-filters-and-parameters-on-liveboards]
Show only relevant filters and parameters on Liveboards [.badge.badge-early-access-relnotes]#Early Access#::
Filters and parameters that are not relevant to a tab are hidden by default when you open and view a Liveboard. You can choose to view all filters and parameters, including those that are not relevant to the tab, so that you can quickly create a new view or download the Liveboard without having to switch tabs and apply filters individually.
To enable this feature, contact your administrator.
+
For more information, see xref:liveboard-filters.adoc[Apply filters to specific visualizations or tabs].

// Naomi. jira: SCAL-222545. docs jira: SCAL-236119
[#gradient-based-conditional-formatting]
Gradient-based conditional formatting:: Gradient-based conditional formatting is now available to all users and on by default. You can now choose multiple colors to define a gradient in charts that support gradients -- geo heatmap, geo area, heatmap, and treemap charts. You can control the low, mid, and high values, and numerical value points to customize the gradient.
+
For more information, see xref:chart-color-change.adoc#charts-with-gradients[Change chart colors].

// Mary. jira: SCAL-218966. docs jira: SCAL-238611
[#query-set-bins]
Query set bins [.badge.badge-early-access-relnotes]#Early Access#::
ThoughtSpot users can now create bins for aggregate results in query sets. This feature allows you to create groups based on bins of specified sizes with minimum and maximum values. To enable this feature, contact your administrator.
+
For more information see, xref:query-sets.adoc[Query sets].

[#improved-sorting-filtering-and-export-of-answers-and-liveboards]
Improved sorting, filtering, and export of Answers and Liveboards in the new navigation and home page experience::
In this release, we provide new options for sorting and filtering Answers and Liveboards, as well as the option to export them to TML. These options are available in the home page, as well as the Liveboards and Answers pages of the Insights app in the new navigation and home page experience. The options include the following:
+
--
* Sorting Answer and Liveboard lists by "last modified"
* Filtering Liveboards and Answers by *All* or *Yours*
* Exporting selected Answers and Liveboards to TML
--
+
To confirm you are using the new navigation and home page, go to your user profile and make sure Navigation and Home page is set to *New experience*. For more information, see
xref:thoughtspot-one-homepage.adoc[Home page].

[#10-6-0-cl-data-engineer]
=== For the Data Engineer

// Naomi. jira: SCAL-226052. docs jira: SCAL-239382
[#spotter-conversations-liveboard]
Spotter Conversations Liveboard::
We’ve introduced the *Spotter Conversations Liveboard* to give you real-time visibility into user interactions with Spotter. With this Liveboard, administrators can:
+
--
* Gain insights into user engagement and adoption metrics for Spotter.
* Track query trends and understand user intent.
* Monitor follow-up actions, including query refinements and edits within conversations.
* Analyze feedback to identify training gaps and improve dataset coverage.
--
+
For more information, see xref:spotter-conversations-liveboard.adoc[Spotter Conversations Liveboard].

// Naomi. jira: SCAL-230405. docs jira: SCAL-239421
[#clickhouse-connection]
ClickHouse connection [.badge.badge-early-access-relnotes]#Early Access#:: You can now create connections from ThoughtSpot to ClickHouse. To enable this feature, contact your administrator. For more information, see
xref:connections-clickhouse.adoc[ClickHouse].

// Mark. jira: SCAL-222174. docs jira: SCAL-232768, SCAL-240422
// PM: Anant
Suggest indexing of columns for Spotter::
In this release, we introduce *Optimize for Spotter*. It is an easier way of indexing the Worksheet and Model attribute columns required for accurate searches on specific column values in Spotter. After enabling Sage on a Worksheet or Model and clicking the *Optimize for Spotter* button, ThoughtSpot detects which columns are not indexed and allows you to index the ones you need for Spotter. For more information, see xref:spotter-worksheet-model.adoc#optimize-spotter[Optimize for Spotter].


// Naomi. jira: SCAL-147895. docs jira: SCAL-240697
[#object-id]
User-defined ID in TML [.badge.badge-beta-relnotes]#Beta#:: Rather than using a system-generated GUID to identify individual objects in TML files, you can now manually set an object property (`obj_id`) with a uniqueness constraint on the Org level. This allows you to manage content across multiple Orgs without having to manually change the GUID of an object each time you move it between Orgs. To enable this feature, contact {support-url}.
+
For more information, see xref:tml.adoc#object-id[User-defined ID in TML].

[#10-6-0-cl-it-ops]
=== For the IT/Ops Engineer

// Naomi. jira: SCAL-212219. docs jira: SCAL-220587
[#search-data-mandatory-columns]
Search data mandatory columns [.badge.badge-beta-relnotes]#Beta#:: You can now use TML to define a list of associated columns that must be included in a search if a certain column is added. This allows you to make sure users do not remove necessary context from a search by removing a column. To enable this feature, contact {support-url}.
+
For more information, see xref:tml-worksheets.adoc#is_mandatory[Mandatory columns].

// Mary. jira: SCAL-84791. docs jira: SCAL-236084
[#multifactor-authentication-for-customers]
Multifactor authentication for customers using local authentication [.badge.badge-beta-relnotes]#Beta#::
ThoughtSpot now supports multifactor authentication (MFA) for customers using local authentication powered by Enhanced IAM with IAM v2. Use MFA to enable secure access to your ThoughtSpot instance for your local auth users by introducing an additional authentication factor configurable at the cluster level. We support Okta Verify, Google Authenticator, and Email-based time-based one-time passcode (TOTP) authentication with ThoughtSpot MFA.
+
For more information, see xref:authentication-local-mfa.adoc[Multifactor authentication for customers using local authentication].

// Mary. JIRA: SCAL-239506
[#thoughtspot-enterprise-org-enablement]
ThoughtSpot Enterprise Org enablement::
All ThoughtSpot Enterprise clusters will get enabled with Orgs by default starting with this release. Your environment remains a single-tenant environment until you create an Org. You can delete all the Orgs you created and use only the Primary Org if you want a single-tenant environment with Orgs enabled.
+
For more information, see xref:orgs-overview.adoc[Multi-tenancy with Orgs].

////
// Naomi. jira: SCAL-218237. docs jira: SCAL-239699
Learnability in conversation: feedback generation in follow-up questions:: You can now give feedback on AI-generated Answers in Spotter without interrupting your searching conversation. When marking an Answer incorrect, you can now edit the underlying search, save, and review the search query tokens making up the Answer. If you mark an Answer correct, you can review and save the underlying search query tokens so Spotter remembers your choices in the future for similar questions.
+
For more information, see xref:spotter-getting-started.adoc#learnability[Coach Spotter within a conversation].
////

// Mary. jira: SCAL-232495. docs jira: SCAL-232812
[#org-context-for-sharing-links]
Org context for sharing links::
ThoughtSpot's org context for sharing links is now available to all users and enabled by default. URLs in emails now include Org context so that users are taken directly to the correct Liveboard in the correct Org even if they belong to multiple Orgs. You can also move between different browser tabs that point to different Orgs. To enable this feature, contact your administrator.
+
For more information, see xref:orgs-overview.adoc[Org context for sharing links].

// Mary. jira: SCAL-216546. docs jira: SCAL-220685
[#import-and-export-users-and-groups-using-tml]
Import and export users and groups using TML [.badge.badge-early-access-relnotes]#Early Access#::
Import and export users, groups, roles, and privileges programmatically, using ThoughtSpot Modeling Language. Use this feature to migrate from one environment to another. This feature can be used so that user, group, and role configurations do not need to be recreated.
To enable this feature, contact your administrator.
+
For more information, see xref:admin-portal-users.adoc[Managing users], xref:admin-portal-groups.adoc[Managing groups], xref:rbac.adoc[Understand RBAC and privileges].



[#10-6-0-cl-developer]
=== For the Developer

ThoughtSpot Embedded:: For information about the new features and enhancements introduced in this release, refer to https://developers.thoughtspot.com/docs/?pageid=whats-new[ThoughtSpot Developer Documentation^].

// Mary. jira: SCAL-221647. docs jira: SCAL-238896
[#row-counts-connection-configuration]
Row counts connection configuration [.badge.badge-early-access-relnotes]#Early Access#::
ThoughtSpot now allows you to assign different configurations when creating a connection, to run row count stats and keep them separate from other process and user queries. Use this feature to help with auditing and tracking your cloud data warehouse usage by user and process. Optimize costs by assigning the right resources to the right process and users.
+
To enable this feature, contact your administrator.
