= March 2022 release notes
:last_updated: 3/23/2021
:experimental:
:linkattrs:
:page-layout: default-cloud
:page-aliases:
:description: ThoughtSpot Cloud 8.1.0.cl release notes

These new and enhanced features of ThoughtSpot Cloud were released in March 2022.

== ThoughtSpot Cloud 8.1.0.cl

// [#8-1-0-cl-analyst]
// === For the Analyst

////
removing cirrus features per ravi
[#spotapps]
ServiceNow SpotApp::
SpotApps are ThoughtSpot's new out-of-the-box solution templates built for specific use cases and data sources. They are built on Blocks, which are pre-built pieces of code that are easy to download and implement directly from the product. This release introduces the ServiceNow SpotApp and Analytics Blocks. Analytics Blocks include pre-built Worksheet, Answer, and Liveboard Blocks.
+
The ServiceNow SpotApp mimics the ServiceNow data model. After you connect to your ServiceNow data in your cloud data warehouse, ThoughtSpot maps that data to SpotApp columns, and creates pre-built but still customizable worksheets, answers, and Liveboards, based on your ServiceNow data.
+
This feature is in beta and off by default. It is part of the <<data-tab,Data tab redesign>>, which is also in beta and off by default. To enable SpotApps and the Data tab redesign, contact {support-url}.

SQL-based views::
This release introduces beta support for SQL-based views. Users can create views based on SQL queries, and use those views as data sources. This type of view has the same functionality as a view based on searching your data.
+
This feature is in beta and off by default. To enable it, contact {support-url}.

[#data-tab]
Data tab redesign::
This release redesigns the *Data* section of the product. To access this part of the product, select *Data* from the top navigation bar. The redesign introduces several new features, such as SQL-based views and SpotApps, and makes the UI more intuitive.
+
This feature is in beta and off by default. To enable it,  contact {support-url}.

////

[#8-1-0-cl-business-user]
=== For the Business User
[#reset]
Reset button for saved Answers::
The reset button allows you to reset a saved Answer to its last saved state after you edit it. This buttons appears to the right of the search bar in a saved Answer, next to the *undo* and *redo* buttons. Note that the reset button is only available for saved Answers.
+
The reset button is only available in the xref:answer-experience-new.adoc[new Answer experience].

[#chart-kpi-sparkline]
Sparkline visualization for KPI chart type::
When you search for a measure with a time-related keyword (for example, `Sales weekly`), you can now create sparkline visualizations of your data’s Key Performance Indicators (KPIs). For more information, see xref:chart-kpi.adoc#kpi-sparkline[Sparkline visualizations for time-series KPIs].

////
[#slack]
Slack integration::
You can now push insights from a saved answer or Liveboard visualization to your Slack workspace and deliver data directly to your Slack channels. For more information, see xref:push-data-to-slack.adoc[].
////

[#8-1-0-cl-data-engineer]
=== For the Data Engineer

////
removing cirrus features per ravi
[#connections-flow-data-portal]
New connection creation flow with data tab redesign::
If you have the new redesigned data tab enabled, you'll see the new Data Portal page. To start creating a connection, you click *Connections* and then click the connection type you want to create. Also with the new data tab enabled, you have the option to create a connection without selecting tables or columns. On the Data Portal page you can create a SQL-based view from a connection.
////

////
[#connections-redshift-oauth]
OAuth for Amazon Redshift::
Redshift connections now support OAuth. See xref:connections-redshift-oauth.adoc[Configure OAuth for a Redshift connection].
////

[#connections-azure-oauth]
OAuth for Microsoft Azure Synapse::
Synapse connections now support OAuth. See xref:connections-synapse-oauth.adoc[Configure OAuth for an Azure Synapse connection].

[#aws-region-japan]
New Japan cloud region::
ThoughtSpot Cloud is now available in Japan. See xref:ts-cloud-requirements-support.adoc[ThoughtSpot Cloud requirements and support].

[#8-1-0-cl-it-ops-engineer]
=== For the IT Ops Engineer

[#encryption-at-rest]
Encryption at rest::
ThoughtSpot provides advanced data encryption at rest (EAR) that allows for granular user and folder level controls for encrypting your persistent data. EAR is currently a beta feature. To enable EAR in your environment, contact {support-url}.

[#8-1-0-cl-developer]
=== For the Developer
For information about the new features and enhancements introduced in this release, refer to https://developers.thoughtspot.com/docs/?pageid=whats-new[ThoughtSpot Developer Documentation^].
