= April 2022 release notes
:last_updated: 3/23/2021
:experimental:
:linkattrs:
:page-layout: default-cloud
:page-aliases:
:description: ThoughtSpot Cloud 8.2.0.cl release notes

These new and enhanced features of ThoughtSpot Cloud were released in April 2022.

== ThoughtSpot Cloud 8.2.0.cl

[#8-2-0-cl-analyst]
=== For the Analyst

[#spotapps]
ServiceNow and Snowflake SpotApps [.badge.badge-beta-relnotes]#Beta#::
SpotApps are ThoughtSpot's new out-of-the-box solution templates built for specific use cases and data sources. They are built on Blocks, which are pre-built pieces of code that are easy to download and implement directly from the product. This release introduces the Analytics Blocks and the ServiceNow and Snowflake SpotApps. Analytics Blocks include pre-built Worksheet, Answer, and Liveboard Blocks.
+
The ServiceNow and Snowflake SpotApps mimic the ServiceNow and Snowflake data models. After you connect to your ServiceNow or Snowflake data in your cloud data warehouse, ThoughtSpot maps that data to SpotApp columns, and creates pre-built but still customizable Worksheets, Answers, and Liveboards, based on your ServiceNow data.
+
This feature is in beta and off by default. It is part of the <<data-tab,Data tab redesign>>, which is also in beta and off by default. To enable SpotApps and the Data tab redesign, contact {support-url}.
[#sql-views]
SQL-based views [.badge.badge-beta-relnotes]#Beta#::
This release introduces beta support for SQL-based views. Users can create views based on custom SQL queries, and use those views as data sources. This type of view has the same functionality as a view based on searching your data.
+
This feature is in beta and off by default. To enable it, contact {support-url}.

[#data-tab]
Data tab redesign [.badge.badge-beta-relnotes]#Beta#::

This release redesigns the *Data* section of the product. The new Data workspace is still in the same place in the product. To access it, select *Data* from the top navigation bar. The redesign introduces several new features, such as SQL-based views and SpotApps, and makes the UI more intuitive.
+
This feature is in beta and off by default. To enable it,  contact {support-url}.
[#pivot-table]
Pivot table scroll bar::
If your pivot table contains multiple measures with long names, the column header now has a horizontal scroll bar, so you can see all your measures without taking up  excessive space in the pivot table.
[#group-agg]
Group aggregate enhancement [.badge.badge-beta-relnotes]#Beta#::
When using a group aggregate formula in a Search, you can now view the results grouped at the level of detail specified in your aggregation formula.
+
For example, consider a query where you want to contrast total revenue per region between areas with above average revenue and below average revenue. Previously, queries of this type displayed individual areas with above or below average revenues in each region, but did not aggregate the results.
+
This enhancement also fixed an issue where queries including group aggregate formulas could not be visualized as charts.
+
This feature is in beta and off by default. To enable it, contact {support-url}.

[#8-2-0-cl-business-user]
=== For the Business User
[#html]
HTML in Answer titles and descriptions::
You can now use HTML 5 in titles and descriptions for Answers and visualizations within Liveboards. For example, you can add a clickable link to a word or phrase in a description, or italicize part of an Answer title.
+
This feature is only available for Answers and visualizations within Liveboards; it is not available for Liveboard titles and descriptions.
+
Refer to xref:chart-html.adoc[Customize titles and descriptions with HTML].
[#kpi]
Key Performance Indicator (KPI) chart type::

Support for attributes;;
You can now create KPI visualizations when you search for attributes, as well as measures. When you search for an attribute (for example, `product`), the KPI automatically displays the top result for that column. For more information, see xref:chart-kpi.adoc#kpi-attribute[KPI charts for attributes].
Conditional formatting;;
You can now add visual cues for KPIs or threshold metrics to easily show where you are falling short or exceeding targets. For more information on how to apply conditional formatting to your KPI, see xref:chart-kpi.adoc#kpi-conditional[KPI charts].
Support for Drill down, Show underlying data, and SpotIQ analyze;;
You can now right-click on the sparkline visual of any KPI chart to xref:search-drill-down.adoc[Drill down] to a finer-grained view of your data, xref:show-underlying-data.adoc[Show underlying data], or xref:spotiq-custom.adoc[run a custom SpotIQ analysis].

////
removing for now per vishal
Search suggestions [.badge.badge-beta-relnotes]#Beta#::
When you xref:search-answers.adoc[search across existing answers and Liveboards], ThoughtSpot now offers object suggestions based on objects you previously viewed or interacted with, not just popular objects. This allows you to quickly return to an object you were working on or looking at in a previous session.
+
This feature is in *Beta* and on only for select customers.
////

[#8-2-0-cl-data-engineer]
=== For the Data Engineer

[#connections-flow-data-portal]
New connection creation flow with data tab redesign::
If you have the new <<data-tab,redesigned data tab>> enabled, you can see the new Data workspace page from the *Data* tab in the top navigation bar. To start creating a connection, click *Connections*, then click the connection type you want to create. The new Data workspace allows you to create a connection without selecting tables or columns.

[#8-2-0-cl-developer]
=== For the Developer
For information about the new features and enhancements introduced in this release, refer to https://developers.thoughtspot.com/docs/?pageid=whats-new[ThoughtSpot Developer Documentation^].
