= May 2022 release notes
:last_updated: 3/23/2021
:experimental:
:linkattrs:
:page-layout: default-cloud
:page-aliases:
:description: ThoughtSpot Cloud 8.3.0.cl release notes

These new and enhanced features of ThoughtSpot Cloud were released in May 2022.

== ThoughtSpot Cloud 8.3.0.cl

[#8-3-0-cl-analyst]
=== For the Analyst
[#new-liveboard]
New Liveboard experience::
The xref:liveboard-experience-new.adoc[new Liveboard experience] is now available. It contains multiple new features and feature enhancements.
It is part of ThoughtSpot's move to a new stack.
To learn how to enable it, refer to xref:liveboard-experience-new.adoc[].
+
The new Liveboard experience contains the following new features:

include::partial$new-liveboard-experience-features.adoc[]

include::partial$new-liveboard-experience-deprecations.adoc[]
[#integration-dbt]
Integration with dbt [.badge.badge-beta-relnotes]#Beta#::
ThoughtSpot now offers an integration with dbt. You can provide your existing dbt models and automatically create Worksheets in ThoughtSpot that you can use to perform searches on your data.
+
This feature is in beta and off by default. It is part of the <<data-tab,Data tab redesign>>, which is also in beta and off by default. To enable dbt integration and the Data tab redesign, contact {support-url}.
[#jira]
Jira Issue Management SpotApp [.badge.badge-beta-relnotes]#Beta#::
This release introduces the Jira Issue Management SpotApp. ThoughtSpot maps your Jira data to SpotApp columns, and creates pre-built but still customizable Worksheets, Answers, and Liveboards, based on your data.
+
This feature is in beta and off by default. It is part of the <<data-tab,Data tab redesign>>, which is also in beta and off by default. To enable SpotApps and the Data tab redesign, contact {support-url}.
[#spotiq]
New SpotIQ experience::
The new SpotIQ experience is now available. The functionality remains the same, but we reorganized the UI to make it more intuitive. The new experience is on by default. You can manage your individual SpotIQ experience xref:user-profile.adoc[from your profile]. Note that the new SpotIQ experience is dependent on the xref:answer-experience-new.adoc[new Answer experience]; to use the new SpotIQ experience, you must first enable the new Answer experience. For more information, refer to xref:spotiq-custom.adoc[].

[#8-3-0-cl-business-user]
=== For the Business User
[#recently-viewed]
Recently viewed Liveboard and Answer suggestions::
When you xref:search-answers.adoc[search across existing Answers and Liveboards], ThoughtSpot now offers suggestions based on Liveboards and Answers you recently viewed or interacted with, not just popular objects. This allows you to quickly return to an object you were working on or looking at in a previous session.

// make sure this is going to be GA
[#open-search]
Open Search data in a new tab::
You can now open *Search data* in a new tab by right-clicking on the *Search data* option in the top navigation bar.
[#kpi]
KPI chart enhancements:: With this release, you can track Key Performance Indicators more easily, and tailor conditional formatting to suit your business use cases.
[#track-kpi]
Track KPI charts from your home page watchlist::
+
You can now add Key Performance Indicators to your xref:thoughtspot-one-homepage.adoc#quick-links[watchlist] and track them from your home page. To add a KPI chart to your watchlist, choose *Add metrics to your home page watchlist* and select the KPI chart from your recently viewed Liveboards.
[#conditional-formatting]
Conditional formatting for KPI attributes::
ThoughtSpot now supports conditional formatting for attribute-type KPI charts as well as measures.
[#monitor-key]
Monitor Key Performance Indicators::
ThoughtSpot now supports scheduled alerts for changes in Key Performance Indicators (KPIs) in your data. From the Monitor tab, you can view and manage all KPI alerts you create or subscribe to. For more information, see xref:monitor.adoc[Monitor Key Performance Indicators in your data].

[#8-3-0-cl-data-engineer]
=== For the Data Engineer
[#databricks]
OAuth for Databricks::
Databricks connections now support OAuth. See xref:connections-databricks-oauth.adoc[Configure OAuth for a Databricks connection].
[#oracle]
Oracle connections support Exadata and ADW::
In this release, the Oracle ADW connection is renamed to Oracle. Existing ADW connections continue to work. There are now two options: Cloud for ADW connections, and On Premise for Exadata or on-prem database connections. For details, see xref:connections-adw.adoc[Oracle].
[#dremio]
Dremio connector::
In the release, Dremio is a new connection type. For details, see xref:connections-dremio.adoc[Dremio]. Dremio supports OAuth. For details, see xref:connections-dremio-oauth.adoc[Configure OAuth for a Dremio connection].

[#8-3-0-cl-it-ops-engineer]
=== For the IT Ops Engineer

[#encryption-at-rest-ga]
Advanced encryption at rest::
xref:security-thoughtspot-lifecycle.adoc#advanced-data-ear[Advanced data encryption at rest] is now GA. ThoughtSpot provides advanced data encryption at rest (EAR) that allows for granular user and folder level controls for encrypting your persistent data.
+
To enable Advanced EAR in your environment, contact {support-url}.

[#8-3-0-cl-developer]
=== For the Developer
For information about the new features and enhancements introduced in this release, refer to https://developers.thoughtspot.com/docs/?pageid=whats-new[ThoughtSpot Developer Documentation^].
