= June 2022 release notes
:last_updated: 3/23/2021
:experimental:
:linkattrs:
:page-layout: default-cloud
:page-aliases:
:description: ThoughtSpot Cloud 8.4.0.cl release notes

These new and enhanced features of ThoughtSpot Cloud were released in June 2022.

== ThoughtSpot Cloud 8.4.0.cl

[#8-4-0-cl-analyst]
=== For the Analyst
[#liveboard-and]
Liveboard and Answer download footer::
This release introduces the ability for admins to specify a standard footer to add to all Liveboard and Answer downloads. Use this functionality to add a confidentiality disclaimer, for example.
+
This feature is part of the xref:answer-experience-new.adoc[new Answer experience] and the xref:liveboard-experience-new.adoc[new Liveboard experience]. The new Answer experience is on by default, and the new Liveboard experience is off by default in 8.4.0.cl. If you are using the classic experiences, you cannot set a standard download footer. If you are using only the new Answer experience, you can only set a standard download footer for Answers, *_not_* Liveboards.
+
For more information, refer to xref:search-spotiq-settings.adoc[].
[#spotapps]
SpotApps::
This release introduces several new SpotApps. ThoughtSpot maps your data from external applications, such as HubSpot, to SpotApp columns, and creates pre-built but still customizable Worksheets, Answers, and Liveboards, based on your data.
+
This release introduces the following new SpotApps:
+
--
* Okta
* Google Analytics
* HubSpot Marketing Email
* Snowflake Consumption Version 2
* Jira Sprint Management
--
+
The SpotApps feature is in beta and off by default. It is part of the <<data-tab,Data tab redesign>>, which is also in beta and off by default. To enable SpotApps and the Data tab redesign, contact {support-url}.

[#8-4-0-cl-business-user]
=== For the Business User
[#geomap-support]
Geo map support for France::

We now support more detailed geographic maps for France. You can now create maps based on postal codes, as well as region and city name. For more information, see xref:geomap-reference.adoc#france[Geo map reference].

[#8-4-0-cl-developer]
=== For the Developer
For information about the new features and enhancements introduced in this release, refer to https://developers.thoughtspot.com/docs/?pageid=whats-new[ThoughtSpot Developer Documentation^].
