= November 2022 release notes
:last_updated: 3/23/2021
:experimental:
:linkattrs:
:page-layout: default-cloud
:page-aliases:
:description: ThoughtSpot Cloud 8.9.0.cl release notes

These new and enhanced features of ThoughtSpot Cloud were released in November 2022.

== ThoughtSpot Cloud 8.9.0.cl

[#8-9-0-cl-analyst]
=== For the Analyst
[#custom-sizes]
Custom sizes for visualizations in Liveboards::
Custom tile sizes for visualizations within Liveboards are now generally available. In addition to the 5 predetermined visualization sizes, you can now customize your Liveboard visualizations to be any size. See xref:liveboard-layout-edit.adoc#size[Edit the layout of a Liveboard].
[#visualization-guid]
Visualization GUID support in TML files::
Liveboard ThoughtSpot Modeling Language (TML) files now contain distinct GUIDs for each visualization in the Liveboard by default. This ensures that the GUID for the visualization stays the same after you import or export it. See the xref:tml.adoc#viz_guid[TML viz_guid] parameter.
[#pinboard-to]
Pinboard to Liveboard change in TML::
ThoughtSpot changed the `pinboard` parameter in Liveboard TML files to `liveboard`, consistent with our rebrand of pinboards as Liveboards.
+
For more information, see xref:tml-liveboards.adoc#syntax-liveboards[Syntax of the Liveboard TML file].

////
[#spotapps-8-9]
SpotApps::

The following SpotApps are now available:
* xref:spotapps-google-ad-analysis.adoc[Google Ad Analysis]: Use this SpotApp to get invaluable insight into your Google Ads performance, from high-level usage to identifying popular campaigns.
* xref:spotapps-linkedin-ads.adoc[LinkedIn Ads]: Use this SpotApp to get invaluable insight into your LinkedIn Ads performance, from high-level usage to identifying popular projects.
* xref:spotapps-procurement-vulnerability.adoc[Procurement Vulnerability Analysis for SAP]: Use this SpotApp quickly identify where disruptions could occur in your global supply chain, reducing risk and building resilience.
////

[#8-9-0-cl-business-user]
=== For the Business User
[#thoughtspot-sync-sales]
ThoughtSpot Sync Salesforce connection [.badge.badge-beta-relnotes]#Beta#::

You can now sync data directly from an Answer or custom SQL view to Salesforce. Using ThoughtSpot Sync, you can push insights directly to Salesforce, notify your teams, and view data in context. ThoughtSpot Sync automatically establishes a secure pipeline to the destination app and thus eliminates the need for building custom connectors. For more information, see xref:sync-salesforce.adoc[Sync data to Salesforce]
[#discoverable-answers]
Discoverable Answers and Liveboards:: The discoverable Answers and Liveboards feature is now GA and on by default. You can now make content easily available to your team members. Use the *Make this [Answer | Liveboard] discoverable* checkbox that appears when you save or share an Answer or Liveboard to grant _view_ access to your teammates.
+
Select this checkbox to publish your content in the list of relevant results when a teammate uses the *Search Answers* feature, or deselect to keep your content private.
[#edit-your]
Edit your display name::
You can now edit your display name by clicking the profile icon in the upper-right corner of the screen. For more information, see xref:user-profile.adoc[Edit display name].

[#8-9-0-cl-data-engineer]
=== For the Data Engineer
[#tag-enhancements]
Tag enhancements::

This release includes the following updates to the xref:tags.adoc[tags] feature in the xref:data-workspace.adoc[]:
+
--
* Add tags to multiple objects at a time
* Administrators can create new tags from the *Edit tags* modal
--
+
For more information, see xref:tags.adoc#data-workspace-apply[Apply a tag] and xref:tags.adoc#data-workspace-create[Create a tag].
[#query-banding]
Query banding with Teradata connections::

With query banding, Teradata connections now support the trust SQL feature in Teradata. This provides additional permissions to a ThoughtSpot user for accessing specific tables in Teradata to execute queries. The user must be configured as an application proxy user in Teradata. Query banding also allows tracking of statistics for queries executed by a user. Refer to xref:connections-teradata-add.adoc[Add a Teradata connection].
[#sql-server]
SQL Server with Synapse connections::

In this release, ThoughtSpot officially certifies and provides support for Microsoft SQL Server used with Synapse connections. Refer to xref:connections-synapse-add.adoc[].

[#8-9-0-cl-it-ops-engineer]
=== For the IT/Ops Engineer

[#high-availability]
High Availability::
ThoughtSpot now supports High Availability through deployment spanning multiple Availability Zones. This ensures that the ThoughtSpot Cloud application experiences near-zero downtime in the case of AWS Availability Zone (AZ) failures. To learn how to enable High Availability in your environment, see xref:high-availability.adoc[].

[#8-9-0-cl-query-based-pricing]
Billable Query Stats Liveboard::

The new Billable Query Stats Liveboard allows administrators of customers who have signed up for a query-based usage subscription, to track the number of queries of their users. To view the Billable Query Stats Liveboard, go to *Liveboards* and select *Billable Query Stats Liveboard*. Query-based usage is part of consumption-based pricing. For more information, see xref:consumption-pricing-query-based.adoc[Query-based usage].


[#8-9-0-cl-developer]
=== For the Developer

For information about the new features and enhancements introduced in this release, refer to https://developers.thoughtspot.com/docs/?pageid=whats-new[ThoughtSpot Developer Documentation^].
