= August 2023 release notes
:last_updated: 3/23/2021
:experimental:
:linkattrs:
:page-layout: default-cloud
:page-aliases:
:description: ThoughtSpot Cloud 9.4.0.cl release notes

These new and enhanced features of ThoughtSpot Cloud were released in August 2023.

== ThoughtSpot Cloud 9.4.0.cl

[#9-4-0-cl-analyst]
=== For the Analyst
[#verified-liveboards]
Verified Liveboards [.badge.badge-beta-relnotes]#Beta#:: Admin-assigned verifiers can now mark Liveboards as verified. Users can now request these verifiers to review their Liveboards, and verify if the information displayed is trusted content. Verified Liveboards carry a tag that signifies that they have been audited for correctness. For more information, see xref:liveboard-verify.adoc[Verified Liveboards].
[#indexing-queries]
Indexing Queries Liveboard:: We introduced a Liveboard to answer the following questions: +

* How many indexing queries are made?
* What queries are failing and why?
* How long are the indexing queries taking?
* Which connections have the most failures so that the admin can easily identify them?
+
Admin users can access the Indexing Queries Liveboard from the admin tab, and use the results to improve indexing queries performance. For more information, see xref:indexing-queries-liveboard.adoc[Indexing Queries Liveboard].
[#custom-groups]
Custom groups [.badge.badge-beta-relnotes]#Beta#:: You can now create custom groups, which can be used to classify values in a list you can then reuse across multiple analyses. Custom groups are community objects which remain when you navigate away from the Search Data page and can be viewed by any user with view access to the underlying Worksheet. For more information, see xref:query-sets.adoc[Custom groups].
[#date-picker]
Date picker enhancement in Search [.badge.badge-early-access-relnotes]#Early Access#:: We added support for rolling, fixed, and custom date filters when creating an Answer or filtering a Liveboard. Previously, when adding a date filter to a Search, ThoughtSpot supported the conditions `ON (=)`, `ON OR AFTER (>=)`, `BEFORE (<)`, and `BETWEEN`. Now, you can additionally filter for `ON OR BEFORE (\<=)`, `NOT BETWEEN`, `ON LAST`, and `ON NEXT`. To try it out, click the filter icon next to the Date column in the left side menu, or click the date filter below the Answer or Liveboard title. This feature must be enabled by your administrator. For more information, see
xref:date-filter.adoc[Date filters for Answers and Liveboards].

[#geomap-chart]
Geomap chart enhancements:: ThoughtSpot now supports the following enhancements for geomap visualizations:

* We now provide geomap data for all countries. For a full list, see link:https://wiki.openstreetmap.org/wiki/List_of_territory_based_projects[Openstreetmap supported countries^].
* We now support multiple levels of subdivisions within a country, rather than just city and zip code.
//* Zip code data is now visualized as an area within a region, rather than a point on a map. You must select *Auto select* in the Geo config column of the source table or Worksheet to access this feature.
* We now support visualizations comparing subdivisions of multiple countries in a single visualization. For example, if a selected column contains data from cities in the United States and Mexico, all data would be displayed on a single visualization.
+
For more information, see
xref:chart-geo.adoc#enhancement[Geo chart enhancements].
[#responsive-liveboards]
Responsive Liveboards:: We have improved the responsiveness of Liveboards. For windows between 1024 pixels and 500 pixels, the Liveboard columns respond to re-sizing. For windows smaller than 500 pixels in width, a horizontal scroll bar appears.

////
Snowflake Query Profile SpotApp:: The Snowflake Query Profile SpotApp is now available. Use this SpotApp to analyze Snowflake query data to understand execution time better and pinpoint key areas for query optimization. For more information, see
xref:spotapps-snowflake-query.adoc[Snowflake Query Profile SpotApp].
////
[#table-column]
Table column case definition [.badge.badge-beta-relnotes]#Beta#::
We are introducing the ability to specify the case of a table column (for example, upper, lower, or mixed). Previously, SQL generated by ThoughtSpot was always wrapped in a LOWER function with no configuration options. Now, users will be able to define whether columns in tables are mixed case or lower case. To enable this feature, contact {support-url}.
[#worksheet-formula]
Worksheet formula indexing::
In this release, worksheet formulas can now be indexed by setting *Suggest values in search* to *Yes* for the formula.

[#9-4-0-cl-business-user]
=== For the Business User
[#notification-center]
Notification center:: You now receive in-app notifications when items are shared with them, or when other users request access to an Answer or Liveboard. To view these notifications, simply click on the user profile icon. For more information, see xref:web-notifications.adoc[Web notifications].
[#contextual-change]
Contextual change analysis:: Contextual change is now GA and on by default. You can now identify the key change drivers for changes in your metrics in a KPI chart. Select the percent change label or select any two data points on the KPI sparkline to view change analysis on your top 5 columns by usage-based ranking (UBR) and identify the reason behind the observed change. You can view the changes in other columns by clicking *Manage attributes* and selecting the desired column(s).
+
For more information, see
xref:spotiq-change.adoc#change-analysis-contextual[Contextual change analysis].
[#admin-controls]
Admin controls for new data panel experience::
ThoughtSpot admins now have more control for enabling the new data panel experience for users. As before, an admin can enable the new data panel experience by going to *Admin* > *Early Access features*, and enabling *Data Fluency*. Each user can selectively enable the new data panel experience by going to their user profile, and setting the *Answer data experience* to *New experience*. In this release, admins can now make the new answer data panel experience default for all users of a cluster, by going to *Admin* > *Search & SpotIQ* and setting the *Make new answer data panel experience default* to *Enabled*.
[#thoughtspot-for-connected]
ThoughtSpot for Connected Sheets plug-in:: ThoughtSpot Connected Sheets is an add-on that allows you to connect to a ThoughtSpot instance, pull data directly into a Google Sheet from trusted data sources connected to that instance (like Snowflake, Google BigQuery, DataBricks, and others), and use the tools in Google Sheets for ad-hoc analysis.
[#headline-creation]
Headline creation and pinning deprecation:: ThoughtSpot is deprecating the pin Headline to Liveboard feature. Beginning in the 9.4.0.cl Cloud release, users will no longer see the pin icon when they select table summaries. To visualize and pin single aggregated measures, attributes in string/date format, or time-series metrics with sparklines, we recommend creating xref:chart-kpi.adoc[KPI charts]. Existing Headlines pinned to Liveboards will not be affected in this release. For more information, see
link:https://community.thoughtspot.com/s/article/How-to-convert-Headlines-to-KPI-charts[How to convert Headlines to KPI charts^].
[#liveboard-tabs]
Liveboard tabs in Mobile:: We now display Liveboard tabs in the ThoughtSpot Mobile app. To create a Liveboard tab, you must access ThoughtSpot in a browser.
[#show-onboarding]
Show onboarding for new users following the share link:: When users are invited to ThoughtSpot via a Share link, they can now click the *Keep exploring* button to be directed to onboarding.
[#natural-language]
Natural language search improvements::
We made the following changes to the natural language search feature:

* Redesigned search results page. Filtering facets are now in the left panel.
* You can now interact with the Answers created by natural language search, including sorting values and drilling down.
* Title and descriptions are now pre-populated when you save an AI Answer.


[#9-4-0-cl-data-engineer]
=== For the Data Engineer
[#connections]
Connections:: You can now create connections from ThoughtSpot to the following connections:

* xref:connections-amazon-aurora-mysql.adoc[Amazon Aurora for MySQL]
* xref:connections-amazon-aurora-postgresql.adoc[Amazon Aurora for PostgreSQL]
* xref:connections-amazon-rds-mysql.adoc[Amazon RDS for MySQL]
* xref:connections-amazon-rds-postgresql.adoc[Amazon RDS for PostgreSQL]
[#connection-error]
Connection error messaging improvements:: If you run into an error while creating a connection, you can now click *View details* to see error details and add a comment for your administrator.
[#dbt]
dbt:: ThoughtSpot now supports dbt version 1.5.

[#9-4-0-cl-it-ops-engineer]
=== For the IT/Ops Engineer
[#new-london]
New London cloud region for AWS:: ThoughtSpot Cloud now supports the London region when you connect using AWS. See xref:ts-cloud-requirements-support.adoc[ThoughtSpot Cloud requirements and support].

[#9-4-0-cl-developer]
=== For the Developer
For information about the new features and enhancements introduced in this release, refer to https://developers.thoughtspot.com/docs/?pageid=whats-new[ThoughtSpot Developer Documentation^].
