= October 2023 release notes
:last_updated: 3/23/2021
:experimental:
:linkattrs:
:page-layout: default-cloud
:page-aliases:
:description: ThoughtSpot Cloud 9.6.0.cl release notes

These new and enhanced features of ThoughtSpot Cloud were released in October 2023.

== ThoughtSpot Cloud 9.6.0.cl

[#9-6-0-cl-analyst]
=== For the Analyst
[#embedding-in]
Embedding in note tiles [.badge.badge-early-access-relnotes]#Early Access#::
You can now embed interactive content such as videos, pdfs, or Figma files into Liveboards using the note tile format. To try it out, enter a Liveboard, select the edit icon, and select Add note from the top bar. You can then click the embed icon and enter the URL or iFrame code for your content. You can interact with the content embedded in a Liveboard like you would with a website. To enable this feature, contact {support-url}. For more information, see xref:liveboard-notes.adoc#embed[Embedding content with an iFrame].

// SCAL-174031
[#multi-date]
Multi-date bucketing:: Previously, when adding multiple date keywords to a Search, ThoughtSpot accepted the last entered date keyword as the bucket. For example, if you searched for `revenue` `monthly` `yearly`, ThoughtSpot would interpret `monthly` as `month of year`, rather than using the `monthly` bucket. +
Now, when you add multiple date keywords to a Search, ThoughtSpot preserves the date bucketing implied by the first date keyword. If you would like to change the default date bucket, you can use the *more options* menu for the column and select *Time Bucket* for more options. For more information, see xref:chart-table-change.adoc#multi-bucket[Multi-date bucketing].

[#9-6-0-cl-business-user]
=== For the Business User
[#change-analysis]
Change analysis: More insights [.badge.badge-beta-relnotes]#Beta#::
When running change analysis, you can now see additional insights. For example, ThoughtSpot will detect values that underwent the highest percentage change between the two data points defined in your analysis, and values whose share of the total changed the most. The additional insights appear below the main analysis in the change analysis pop-up window.
[#query-performance]
Query performance visibility [.badge.badge-beta-relnotes]#Beta#::
You can now see the state of query execution for any Liveboard visualization while it loads. If a visualization takes longer than three seconds to load, ThoughtSpot displays the current query execution status (executing query, waiting for connection, or processing query) to help users identify the reason for the delay.
[#hidden-columns]
Hidden columns in tables::
You can now hide a column from your table without removing it from your current Search. If you hide the column you’re using to sort results, the sorting order is unchanged. To try it out, create an Answer, open the *Edit chart configuration* icon, and drag the selected column to *Hidden Columns*.
[#commenting-on]
Commenting on Liveboards [.badge.badge-early-access-relnotes]#Early Access#::
You can now add or reply to comments, tag other users, or subscribe to comment threads directly on a Liveboard. Users can point out insights or reach out for clarification without leaving ThoughtSpot. To try it out, click the comment icon to the right of the edit icon, and select the data point you would like to comment on. This feature must be enabled by your administrator. For more information, see xref:liveboard-comment.adoc[Comment on a Liveboard].
[#natural-language]
Natural language narratives [.badge.badge-early-access-relnotes]#Early Access#:: Beginning in 9.6.0.cl, ThoughtSpot generates insight narratives in natural language to summarize the data analyzed in SpotIQ. The narratives are generated by LLM, and appear above the charts created by SpotIQ. This feature must be enabled by your administrator. For more information, see xref:spotiq-change.adoc#natural[Natural language narratives].
[#alation-metadata]
Alation metadata::
Alation metadata is now available to all users and on by default. Users can now see metadata information on tables and columns imported from Alation. This information appears when you click on the corresponding table or column in *Search data*. Once connected, metadata information is visible to all users. For more information, see xref:catalog-integration.adoc[Catalog integration].
[#verified-liveboards]
Verified Liveboards::
We made the following enhancements to verified Liveboards:

- When you request verification, you can now see the underlying data sources that will be shared with the verifier.
- The name of the Liveboard now appears in verification request emails.
- When editing an Answer on or pinning an Answer to a verified Liveboard, a warning banner appears indicating it may need to be verified again.

[#9-6-0-cl-slides]
[#thoughtspot-google-slides]
ThoughtSpot for Google Slides add-on::

ThoughtSpot Connected Slides is an add-on that allows you to insert charts and live data visualizations right into your Google Slides™ presentation. Just connect to ThoughtSpot, find a chart or visualization, and add it to your slide presentation. For details, see xref:thoughtspot-slides.adoc[ThoughtSpot Connected Slides].

[#9-6-0-cl-data-engineer]
=== For the Data Engineer
[#amazon-athena]
Amazon Athena connection::
You can now create connections from ThoughtSpot to Amazon Athena. For more information, see xref:connections-amazon-athena.adoc[Amazon Athena].
[#improved-error]
Improved error messaging for Liveboard visualizations:: Previously, ThoughtSpot displayed generic error messages for connection errors on Liveboards. Now, you can see the error message received from the underlying Cloud data warehouse.

[#9-6-0-cl-it-ops-engineer]
=== For the IT/Ops Engineer
[#alation-catalog]
Alation catalog integration::
Alation catalog integration is now available to all users and on by default. You can now import metadata information related to your tables and columns from Alation into ThoughtSpot. From the Data tab, you can set up a connection to Alation to import column descriptions, column verification status, table descriptions, and table verification status. For more information, see xref:catalog-integration.adoc[].
[#index-statistics]
Index Statistics Liveboard::
Admin users can now see indexing statistics for their cluster using the Index Statistics Liveboard. You can filter the results by connection, table, and column, and see the breakdown of indexed search tokens in the visualizations. This Liveboard helps you see how many search tokens you are using, and can help you diagnose indexing issues and errors.
For more information, see
xref:index-statistics-liveboard.adoc[Index Statistics Liveboard].
[#dbt-sync]
dbt sync::
In the past, ThoughtSpot generated a new Worksheet every time a user edited an existing dbt data model. Now, ThoughtSpot maintains a persistent connection with dbt and provides realtime updates. Users can update an object, update an object and create a new object, or simply create a new object.
For more information, see xref:dbt-integration.adoc[].
[#dbt-worksheet]
dbt Worksheet join rule::
Previously, when a Worksheet was created from a dbt model, the default worksheet join rule was "apply all joins". Now, "apply joins progressively" is the default. This means that when a Search is done on the Worksheet, joins are applied as each search term is added, rather than applying all joins to every Search.

[#9-6-0-cl-developer]
=== For the Developer

For information about the new features and enhancements introduced in this release, refer to https://developers.thoughtspot.com/docs/?pageid=whats-new[ThoughtSpot Developer Documentation^].
