= November 2023 release notes
:last_updated: 3/23/2021
:experimental:
:linkattrs:
:page-layout: default-cloud
:page-aliases:
:description: ThoughtSpot Cloud 9.7.0.cl release notes

These new and enhanced features of ThoughtSpot Cloud were released in November 2023.

== ThoughtSpot Cloud 9.7.0.cl

[#9-7-0-cl-analyst]
=== For the Analyst


//scal-66335
[#personalized-liveboard]
Personalized Liveboard views [.badge.badge-early-access-relnotes]#Early Access#:: Personalized views allow you to save your own set of values for filters and parameters in a Liveboard without editing the original Liveboard. You can change the values of the already present filters and parameters in a Liveboard to create a view, and save it for future use. The new Liveboard is a view of the master Liveboard, so any changes made to the master Liveboard flow  automatically to the filtered Liveboard view but not vice-versa. This includes changes made to pinned visualizations, tabs, filter chips, and re-ordering.

//scal-165262
[#embedding-in]
Embedding in note tiles:: Embedding in note tiles is now available to all users and is on by default. You can now embed interactive content such as videos, pdfs, or Figma files into Liveboards using the note tile format. To try it out, enter a Liveboard, select the edit icon, and select *Add note* from the top bar. You can then click the embed icon and enter the URL or iFrame code for your content. You can interact with the content embedded in a Liveboard like you would with a website. For more information, see xref:liveboard-notes.adoc#embed[Embedding content with iFrames].

//scal-139891
[#system-variables]
System Variables in Answer and Worksheet formulas:: Previously, ThoughtSpot supported the `ts_username` variable for use in row-level security formulas alone. Now, users can access the following string variables:
+
--
* `ts_orgname`
* `ts_email_domain`
--
+
`ts_orgname`, `ts_username`, and `ts_email_domain` variables are available to use in Answer and Worksheet formulas. These variables are helpful for data masking.

//scal-140692
[#request-access]
Request access to data source from filter:: When creating a filter on a Liveboard or Answer, you must have access to the underlying data source. Users can now request access to the underlying Worksheet through the filter modal on a Liveboard or Answer. For more information, see
xref:liveboard-filters.adoc#filter-request[Liveboard filters].


//scal-142071
////
ThoughtSpot Slack bot integration:: Get notified in Slack when Liveboards are updated. ThoughtSpot's Slack integration lets you preview Liveboard and Answer links directly in Slack.
////
//scal-161459
[#new-data]
New data panel:: The new data panel experience is available for all customers in this release, and is enabled by default. In this release, you can now filter data sources by how they are tagged.



[#9-7-0-cl-business-user]
=== For the Business User
////
//scal-151210
Redesigned home page [.badge.badge-early-access-relnotes]#Early Access#::
In this release,  we have a completely redesigned home page, where you can ask natural-language questions with Sage, view your watchlist, favorites, library of Answers and Liveboards, and more. With the new left-hand navigation, you can go directly to your Liveboards, Answers, SpotIQ Analysis, and Monitor Subscriptions. The _Search Data_ button has been renamed _Open Query Builder_ to more easily distinguish it from the Sage search bar.
+
This new home page experience is disabled by default. To enable it, open your user profile, and in the _Experience_ section, set the Navigation and Homepage to *New experience*.

// SCAL-175398
New persona-based navigation [.badge.badge-early-access-relnotes]#Early Access#:: In this release, we introduce a completely redesigned navigation experience organized by persona. The new app switcher allows business users, analysts, data engineers, IT Ops, and developers to work in separate contextual sections designed specifically for their needs. In addition, each app has left-hand navigation to create better consistency and ease of use for users switching between the different apps. When you switch to a different app, that app opens in a new browser tab. The redesigned home page is part of the new persona-based navigation, in this release.
+
This new navigation experience is disabled by default. To enable it, open your user profile, and in the _Experience_ section, set the Navigation and Homepage to *New experience*.

////
//scal-159818
////
ThoughtSpot Slack app [.badge.badge-beta-relnotes]#Beta#:: You can now ask ThoughtSpot questions using Slack. Install the ThoughtSpot Slack app, add it to a Slack channel, and you will be able to ask questions of your data sources in natural language. ThoughtSpot answers in chart format. For more information, see
xref:spotter-app-for-slack.adoc[ThoughtSpot Slack app].
////

//scal-158463
[#atlan]
Atlan [.badge.badge-beta-relnotes]#Beta#:: You can now see verification status and descriptions on tables and columns imported from Atlan. This information appears when you click on the corresponding table or column in *Search data*. Once connected, this information is visible to all users. This feature is in beta and off by default. To enable it, contact {support-url}. +
For more information, see
xref:catalog-integration-atlan.adoc[Atlan catalog integration].

//scal-159581, scal-102588, scal-95381, scal-154973, scal-142097, scal-102588, scal-158204
[#mobile-enhancements]
Mobile enhancements:: We made the following improvements to ThoughtSpot mobile:

* We simplified the sign in process for the ThoughtSpot mobile app. You can now enter your company email to receive an email with a magic link login, rather than entering the server URL.
* ThoughtSpot now supports IAMv2 login.
* You can now change your ThoughtSpot locale through the Mobile app. When your locale is updated, ThoughtSpot translates labels, date formats and number formats to match the default for your country and language.
* You can now use SpotIQ analysis to directly identify the key drivers for recent change in your KPIs in ThoughtSpot Mobile. KPI change analysis allows you to drill down into the causes of change in your KPIs and customize the insights generated by SpotIQ.
To access this feature, go to your KPI chart and select the caret icon to the right of the percent change label. The *Run change analysis* pop-up allows you to customize the columns ThoughtSpot analyzes. Note that ThoughtSpot runs change analysis between the two most recent data points defined by the KPI’s time bucket (for example, `daily` or `weekly`).
* We introduced improved deep linking to ThoughtSpot mobile. When you click a link you no longer need to choose whether you want to view the link in your default mobile browser or the ThoughtSpot app. The default behavior is to open the link in ThoughtSpot if it is supported.
* You can now receive ThoughtSpot mobile push notifications. Receive push notifications when a Liveboard or Answer is shared with you. Monitor scheduled and threshold alerts with push notifications.


[#9-7-0-cl-data-engineer]
=== For the Data Engineer

//scal-158463
[#atlan-data]
Atlan data catalog [.badge.badge-beta-relnotes]#Beta#:: You can now import metadata information related to your tables and columns from Atlan into ThoughtSpot. From the *Data* tab, you can set up a connection to Atlan to import column descriptions, column verification status, table descriptions, and table verification status. This information appears when you click on the corresponding table or column in *Search data*. Once connected, metadata information is visible to all users.
+
For more information, see
xref:catalog-integration-atlan.adoc[Atlan catalog integration].

//scal-158490
[#sap-hana]
SAP Hana Calculation view input parameters [.badge.badge-beta-relnotes]#Beta#:: Now, you can define a parameter to link to the parameter in SAP Hana using TML at the table level, and create a linked_parameter clause to ensure the parameter is displayed in all Answers created from the table. For more information, see
xref:tml-tables.adoc[TML for tables].


//scal-91104
[#key-pair]
Key Pair authentication for Snowflake:: We now support xref:connections-snowflake-add.adoc[Key Pair authentication for Snowflake].

//scal-136661
[#oauth-for]
OAuth for Databricks using Proof Key for Code Exchange (PKCE):: We now support xref:connections-databricks-add.adoc[OAuth with PKCE for Databricks].


[#9-7-0-cl-developer]
=== For the Developer

For information about the new features and enhancements introduced in this release, refer to https://developers.thoughtspot.com/docs/?pageid=whats-new[ThoughtSpot Developer Documentation^].
