= Publishing between Orgs
:last_updated: 5/7/2025
:linkattrs:
:experimental:
:page-layout: default-cloud-beta
:description: Publish objects between Orgs

Publishing allows tenant administrators to share objects across Orgs. Tenant administrators can publish objects, as read only, from a primary Org to target Orgs.  Administrators of the target Orgs can then share the objects to users within that Org. Liveboards, worksheets and answers can all be published.


[#conditions]
== Conditions
* Objects can only be published from a primary org to other Orgs.
* Only tenant administrators can publish and unpublish objects.
* Objects are published with read-only access in non-primary Orgs.
* Only tenant administrators can modify published objects in the primary Org.
* Org administrators have read access to published objects.
//* Published connections are not be visible in non-owner Orgs.

[#limitations]
== Limitations
* Cohort publishing is not supported.
* Spotter functionality is not supported on published WS.
* For the published tables, Sage Data Indexing will be disabled. This means no data value suggestions during search data and explore.
* On a published calendar the users will only be able to add/import custom calendars using the Import Existing method and the Create Calendar and Upload Calendar methods will not be supported.
* Custom calendars with different metadata across orgs will not be supported (i.e. month name etc.)
* Users will not be able to create cohorts on the published worksheets.
* Connection Remapping YAML will not be available.
* Only Tenant Admin / user with access to all the orgs where the object is present will be able to update a published object.
* CDWs supported: Snowflake, Redshift, Databricks, GBQ, (others can be added as per customer need)
* Git integration with published objects will not be supported.

