= Publishing between Orgs
:last_updated: 5/7/2025
:linkattrs:
:experimental:
:page-layout: default-cloud-beta
:description: Publish objects between Orgs

In a multi-tenant, org-enabled cluster administrators may want to make common, curated Liveboards and Answers available across multiple tenants or Orgs. Publishing allows tenant administrators to share read only objects across Orgs. Tenant administrators can publish objects, from a primary Org to target Orgs.  Administrators of the target Orgs can then share the objects to users within that Org. Liveboards, Models and Answers can all be published.

NOTE: Tenant administrators must have the *Can publish to orgs* privilege to publish obejects from a primary Org to another Org. For more information about privileges, see xref:rbac.adoc[].
//user and group privilege

To publish an object from a primary Org to other Orgs, complete the following steps:

. Log in to the primary Org as a tenant administrator.
. Go to




[#conditions]
== Conditions
* Objects can only be published from a primary Org to other Orgs.
* Objects are published with read-only access in the non-primary Orgs.
* Only tenant administrators can publish and unpublish objects.
* Only tenant administrators can modify published objects in the primary Org.
* Org administrators have read access to published objects.
//* Published connections are not be visible in non-owner Orgs.

[#limitations]
== Limitations
* Spotter functionality is not supported on published objects.
* For published tables, Sage Data Indexing is disabled.
* In a published calendar, users are only able to add or import custom calendars using *Import Existing*. *Create Calendar* and *Upload Calendar* are not supported.
* Custom calendars with different metadata across Orgs are not supported.
* Cohort publishing is not supported.
* Users can't create sets in the published Models.
* Connection remapping YAML is not available.
* Only tenant administrators with access to all the Orgs where the object exists can update a published object.
* Snowflake, Redshift, Databricks, GBQ, are supported.
* Git integration with published objects is not  supported.
//* Sage data indexing is not supported on published objects thus affecting the suggestions one gets to see in search data
