= Introduction to administration
:last_updated: 4/7/2021
:linkattrs:
:experimental:
:page-aliases: /admin/intro.adoc
:page-layout: default-cloud
:description: This guide covers all topics of special interest to application administrators.

This guide provides information for application administrators.

Before addressing the major components of this guide, we recommend that you familiarize yourself with the general top-level architecture of the ThoughtSpot service.

Administrators are responsible for many facets of the ThoughtSpot service.
They are most frequently in charge of these common processes:

//* link:{{ site.baseurl }}/admin/setup/intro.html[Installation and setup of ThoughtSpot]
//* link:{{ site.baseurl }}/admin/loading/loading-intro.html[Loading and managing data]
* xref:groups-privileges.adoc[Managing users and groups]
* xref:security.adoc[Security]

Additionally, administrators are often involved in the following workflows:

* xref:data-modeling.adoc[Data modeling]
* xref:worksheets.adoc[Using worksheets] to simplify search
* xref:views.adoc[Using views] for 'stacked' search;
note that starting with Release 5.2, you can accomplish some aspects of search stacking by using the `IN` keyword (See xref:search-subquery.adoc[]).
* xref:liveboard-schedule.adoc[Schedule liveboard jobs]
* xref:system-monitor.adoc[Monitoring system health]
* xref:troubleshooting.adoc[Troubleshooting]
