= Managing user logins and sessions
:last_updated: 11/10/2021
:linkattrs:
:experimental:
:page-aliases: /admin/users-groups/sign-in.adoc
:page-layout: default-cloud
:description: Learn how to manage user logins and sessions.

== User login

Users can log into ThoughtSpot in several ways: as users with xref:authentication-local.adoc[local ThoughtSpot accounts] and by using xref:authentication-integration.adoc[SAML].
Refer to xref:authentication.adoc[Authentication] for more information about ThoughtSpot's authentication options.
Administrators can configure their preferred authentication method from the *Admin Console*.

== User sessions

Depending on which version of ThoughtSpot Cloud you first deployed your cluster on, your users' experience with maximum session validity and idle session timeouts may differ.

=== Clusters deployed on November Cloud 2021 and later

When a user clicks *Remember me* on the login screen:

* *Idle session timeout*: If a user is not active for 14 days, ThoughtSpot logs the user out, and the user must enter their login credentials again.
* *Maximum session validity*: ThoughtSpot forces the user's session to expire after 14 days, even if they are active throughout that period.

When a user does not click *Remember me*:

* *Idle session timeout*: If a user is not active for 30 minutes, ThoughtSpot logs the user out, and the user must enter their login credentials again.
* *Maximum session validity*: No maximum session validity.

=== Clusters deployed on October Cloud 2021 and earlier

When a user clicks *Remember me* on the login screen:

* *Idle session timeout*: If a user is not active for 60 minutes, ThoughtSpot logs the user out, and the user must enter their login credentials again.
* *Maximum session validity*: ThoughtSpot forces the user's session to expire after 7 days, even if they are active throughout that period.

When a user does not click *Remember me*:

* *Idle session timeout*: If a user is not active for 30 minutes, ThoughtSpot logs the user out, and the user must enter their login credentials again.
* *Maximum session validity*: No maximum session validity.

To increase idle session timeouts or maximum session validity, https://community.thoughtspot.com/customers/s/contactsupport[contact ThoughtSpot Support].
