= Natural language search best practices
:author: Teresa
:last_updated: 5/17/23
:experimental:
:linkattrs:
:page-layout: default-cloud-private-preview
:description: Learn the best practices for using natural language to search for answers to your business questions.

ThoughtSpot Sage enables customers to ask business questions in natural language, and get AI-generated answers back in the search results page. This guide provides tips to help you get the best performance from the natural language search feature. For more information about natural language search, see xref:ai-answers.adoc[].

.[.badge.badge-private-preview]#Private Preview#
****
Natural language search is a private preview feature and is disabled by default. To enable it, contact {support-url}. Once enabled, your ThoughtSpot administrator can grant you access to this feature by assigning the *Can preview ThoughtSpot Sage* user privilege to your user group.
****

== Worksheet best practices
Follow these best practices when creating Worksheets to get the best natural language search accuracy:

* Worksheets should have 50 columns or fewer.
* Worksheets should have exactly one distinct use case.
* Avoid overlapping column names.
* Use underscores or spaces when naming columns.
* Use easily understandable names.
* Add synonyms by enabling the xref:data-modeling-visibility.adoc#automatic-synonyms[AI-generated Worksheet synonyms] feature, or xref:data-modeling-visibility.adoc#create-synonyms[create your own synonyms].
* Worksheets should have a maximum of two date columns.
* Worksheet values should be flattened lists or single items, not json.
* Adjust the xref:data-modeling-index.adoc#column-suggestion-priority[index priority] for your most popular columns, so ThoughtSpot prioritizes those columns when generating Answers.

== Search best practices
Follow these best practices when searching using natural language for the most accurate Answers:

* Don't use personal pronouns, such as "I," "My," "Mine." GPT can't understand them using the data we send it. Instead, use identifiers that exist in your data sources, such as names, email addresses, and so on.
* Don't ask "why" questions that require reasoning or text-based answers. For example, don't ask "Why did my sales go down in Q2?" These questions aren't currently supported.
* Don't ask descriptive questions about the data source. For example, don't ask "How many date columns does the Worksheet have?"
* Don't ask overly ambiguous questions. The more precise the question, the more likely you are to get an accurate answer. Use actual column names, if you know them.
* Don't ask questions that xref:search-data.adoc[] can't answer. ThoughtSpot must be able to express your question in search tokens. For example, don't ask common knowledge questions, or business questions that require text answers.