= Alerts code reference
:last_updated: 11/19/2019
:linkattrs:
:experimental:
:page-layout: default-cloud
:page-aliases: /reference/alerts-reference.adoc
:description: Learn about the alerts ThoughtSpot may generate.

This reference identifies the messages that can appear in the menu:System Health[Overview > Critical Alerts] and in the  *Alerts* dashboard.

== Informational alerts

{% for item in site.data.extract-alerts.alerts %} +   {% if item.type == "INFO" %}

=== {{item.id}}

*Msg*: `{{item.msg}}`

*Type*: {{item.type}}

{{item.description}}    {% endif %}  {% unless forloop.last %}  {% endunless %} {% endfor %}

== Errors

{% for item in site.data.extract-alerts.alerts %} +   {% if item.type == "ERROR" %}

=== {{item.id}}

*Msg*: `{{item.msg}}`

*Type*: {{item.type}}

{{item.description}}    {% endif %}  {% unless forloop.last %}  {% endunless %} {% endfor %}

== Warnings

{% for item in site.data.extract-alerts.alerts %} +   {% if item.type == "WARNING" %}

=== {{item.id}}

*Msg*: `{{item.msg}}`

*Type*: {{item.type}}

{{item.description}}    {% endif %}  {% unless forloop.last %}  {% endunless %} {% endfor %}

== Critical alerts

{% for item in site.data.extract-alerts.alerts %} +   {% if item.type == "CRITICAL" %}

=== {{item.id}}

*Msg*: `{{item.msg}}`

*Type*: {{item.type}}

{{item.description}}    {% endif %}  {% unless forloop.last %}  {% endunless %} {% endfor %}
