= Connect to Snowflake in Analyst Studio
:product: Analyst Studio
:author: Naomi
:page-last_updated: Sep 1, 2026
:experimental:
:linkattrs:
:description: Connect to Snowflake to start searching your data in Analyst Studio.
:jira: SCAL-315450

== Supported JDBC drivers and known issues

[options=”header”]
|===
| Driver | Driver Release Date | {product} Removal Date

| Snowflake v 3.20.0 | 10/30/2024

| (Recommended) Snowflake v 3.16.0 | 4/29/2024

| Snowflake v 3.13.29 | 3/17/2023

| Snowflake v 3.13.27 | 1/30/2023

| Snowflake v 3.13.14 | 1/21/2022

| Snowflake v 3.13.6 | 7/19/2021

| Snowflake v 3.13.1 | 3/1/2021
|===

The following are known issues with the current supported drivers.
{product} continues to advocate on our customers' behalf for vendors and open-source communities to resolve these issues.

[options=”header”]
|===
| Driver | Known Issue | Further Details

| All
| Date functions not displaying correctly
| Date functions like DATE_TRUNC do not work as expected due to {product}'s results formatter.
Workaround is to use a function to convert the date to string.

| Snowflake v 3.13.1
| Timestamps with timezone are not supported
a| {product} does not display timestamp values with the timezone.
Instead, convert all timestamps to one timezone for simplicity.
+++<pre>+++SELECT current_timestamp() AS Date, + cast(convert_timezone('US/Eastern', Date) AS datetime) EST_date;+++</pre>+++
|===

=== Connecting to {product} via password

. Log in to {product} and follow to steps to xref:analyst-studio-connecting-analyst-studio-to-your-database.adoc#direct-connect[connect a database to {product}].
. Select *Snowflake* from the list of databases.
. Select Authentication method: *Password* in the {product} connection form.
. Enter the Display name, Description (optional), Account URL/Host, Warehouse, Database name, Role (optional), Username, Password, and Preferred JDBC Driver. We recommend selecting Snowflake version 3.26.0 for JDBC Driver, but you can select any version from the dropdown.
. Click *Connect*.
You will land on a page that displays your database schema.

=== Connecting to {product} via key pair authentication

Please follow the link:https://docs.snowflake.com/en/user-guide/key-pair-auth#configuring-key-pair-authentication[Snowflake documentation,window=_blank] for configuring key pair authentication.

. Generate the private key.
There is the option to generate encrypted or unencrypted private keys.
Snowflake recommends encrypting with a passphrase to protect the private key.

. Generate the public key by referencing the private key and assign the public key to the Snowflake user that will be used to access {product}.

. Log in to {product} and follow to steps to xref:analyst-studio-connecting-analyst-studio-to-your-database.adoc#direct-connect[connect a database to {product}].

. Select *Snowflake* from the list of databases.

. Select Authentication method: *Key pair* in the {product} connection form.

. Enter the username of the assigned Snowflake user, upload the private key with a p8 file extension, and include the passphrase if the private key was encrypted.

. Click *Connect*.
You will land on a page that displays your database schema.

=== Connecting to {product} via OAuth

. Log in to {product} and follow to steps to xref:analyst-studio-connecting-analyst-studio-to-your-database.adoc#direct-connect[connect a database to {product}].

. Select *Snowflake* from the list of databases.

. Select Authentication method: *OAuth* in the {product} connection form.

. Enter the Display name, Description (optional), Account URL/Host, Warehouse, Database name, Role (optional), Snowflake Account Identifier, OAuth Client ID, OAuth Client Secret, and Preferred JDBC Driver. We recommend selecting Snowflake version 3.26.0 for JDBC Driver, but you can select any version from the dropdown.

. Click *Connect*.
You will be redirected to Snowflake to authorize access.

=== Connecting to {product} via OAuth with PKCE

. Log in to {product} and follow to steps to xref:analyst-studio-connecting-analyst-studio-to-your-database.adoc#direct-connect[connect a database to {product}].

. Select *Snowflake* from the list of databases.

. Select Authentication method: *OAuth with PKCE* in the {product} connection form.

. Enter the Display name, Description (optional), Account URL/Host, Warehouse, Database name, Role (optional), Snowflake Account Identifier, OAuth Client ID, OAuth Client Secret, and Preferred JDBC Driver. We recommend selecting Snowflake version 3.26.0 for JDBC Driver, but you can select any version from the dropdown.

. Click *Connect*.
You will be redirected to Snowflake to authorize access.
