= Integrations
:author: Naomi
:last_updated: 7/25/24
:experimental:
:page-layout: default-cloud
:linkattrs:
:description: Integrations.
:page-aliases: /analyst-studio/integrations.adoc
:product: Analyst Studio

Analyst Studio integrates with dbt, GitHub, Google Sheets, and more.

** xref:analyst-studio-dbt-data-freshness.adoc[dbt data freshness] +
{product}'s dbt integration allows users to view metadata about data freshness from dbt directly in {product} Reports.
** xref:analyst-studio-github.adoc[GitHub sync] +
An overview of {product}'s GitHub sync.
** xref:analyst-studio-google-sheets-integration.adoc[] +
An overview of {product}'s Google Sheets integration.
** xref:analyst-studio-dbt-semantic-layer.adoc[Semantic layer integrations] +
{product}’s integration with semantic layers extends metrics defined in dbt and Looker so business teams can leverage them for code-free exploration and reporting.
//** xref:studio-slack.adoc[Slack integration] +
//An overview of {product}'s Slack Integration sync.
** xref:analyst-studio-webhooks.adoc[Webhooks] +
An overview of webhooks and how to set them up in {product}.