= API reference
:categories: ["API"]
:categories_weight: 2
:date: 2024-02-27
:description: An overview of Analyst Studio API.
:experimental:
:page-layout: default-cloud
:page-aliases: /analyst-studio/api-reference.adoc
:ogdescription: An overview of Analyst Studio API.
:path: /articles/api-reference
:product: Analyst Studio
:jira: SCAL-219402

//+++<flag-icon>++++++</flag-icon>+++

== API tokens

API tokens allow you to connect to {product}'s API programmatically.
Use an API token instead of your email address and account password whenever you programmatically authenticate to {product} with link:https://developer.mozilla.org/en-US/docs/Web/HTTP/Authentication[basic authentication,window=_blank].

To call the API, you must first create an API access token.
Currently, {product} supports three types of access tokens -- Workspace API tokens, Member API tokens, and personal API tokens.
Starting in June 2023, you can only create Workspace API tokens, as this is the more secure and therefore recommended way to provide API access.
Admins can also enable the Member API tokens feature to allow all their members to create API tokens. Any personal tokens that were created prior to June 2023 can continue to be used to authenticate with the API; however, we will be fully deprecating personal API tokens on February 28, 2025.

The Workspace API tokens are meant to be used for programmatic management, such as archiving inactive Reports or deleting schedules for stale Reports across your Workspace.
These tokens mimic admin access to the Workspace and only admins will be able to create and manage them.

The Member API tokens are meant to be used by a single user for individual use cases, such as updating a specific Report or managing a Collection. These tokens mimic the individual user's access to the resources in the Workspace.

//See the full documentation for {product}'s API link:https://mode.com/developer/api-reference/introduction/[here,window=_blank].

[#generating-api-tokens]
=== Creating an API Access token

WARNING: Remember to store your API token and password securely. Do not expose the password on public sites, in client-side code, or in public code repositories.

==== Workspace tokens

Only admin users are able to create Workspace tokens. You can create as many API access tokens as you need. To create one, navigate to your **Workspace Settings > Features > API Keys > Workspace keys**. Click “Create API Key” and you will be prompted to add a display name and save the token.

==== Member tokens

To enable the Member API tokens feature, admins can navigate to your **Workspace Settings > Features > API Keys > Member keys**. Admins can see all the Member tokens created and revoke all or specific tokens on this tab. Users can then go to **Workspace Settings > Personal > My API Keys** to create their own API tokens.

The credentials are comprised of two parts:

. *Token*:  The public component of the credential.
Often referred to as the username or access key during authentication.
. *Secret*:  The private component of the credential.
Often referred to as the password or access secret during authentication.
This is only shown once when creating the token and must be saved somewhere secure before closing the modal.

*Limitations*:

* Workspace and Member API tokens cannot be used with the Clone endpoint for Report Runs or for creating new invites.
//link:https://mode.com/developer/api-reference/analytics/report-runs/#cloneReportRun[Clone endpoint for Report Runs,window=_blank] or for link:https://mode.com/developer/api-reference/management/invites/#createOrganizationInvite[creating new invites,window=_blank].
* Granular permissions are not currently supported with the Workspace API tokens;
they allow admin access to the Workspace for now.

For more information on generating and managing Workspace and Member API tokens, xref:analyst-studio-api-tokens.adoc[see here].

==== Personal tokens

IMPORTANT: You can continue to use personal API tokens with the API. However, you will not be able to generate new personal tokens. Personal token use will be deprecated on February 28, 2025.

When using personal API tokens, access to resources in the API directly matches your level of permissions in the {product} Workspace you're calling.
Before returning a response, {product} validates every API call against your permissions in that Workspace.

[#faqs]
=== FAQs

[discrete]
==== *Q: {product} API rate limiting*

As of today, our API rate limiting is approximately 40 requests every 10 seconds, or 4 requests per second per username.
We currently publish two headers:

* X-RateLimit-Limit, which shows the total number of requests allowed for that class of resources.
* X-RateLimit-Remaining, which shows how many requests until you'll be throttled.

[discrete]
==== *Q: How to check which Reports are scheduled and viewed*

*API method*

You can loop through every single Report in the workspace (the ones in public/private Collections, but not other members' personal Collections), and check each individual Report to see whether it's scheduled.
//See the API documentation on how to get all the Reports in your Workspace link:https://mode.com/developer/api-cookbook/management/get-all-reports/[here,window=_blank].

//From there, you can see the `view_count` property, which will allow you to see the view count for an individual Report.

*Discovery Database method*

You can also use the Discovery Database to obtain the same information from their reporting.
//The documentation for the Discovery Database can be found link:https://mode.com/developer/discovery-database/introduction/[here,window=_blank].
