= Answer experience
:last_updated: 4/1/2021
:linkattrs:
:experimental:
:page-layout: default-cloud
:page-aliases: /admin/ts-cloud/new-answer-experience.adoc, /admin/ts-cloud/answer-v2.adoc
:description: Learn about ThoughtSpot's new Answer experience, and how to enable it.

Learn about ThoughtSpot's Answer experience.

== Overview

The Answer experience contains multiple new features and feature enhancements.
It is part of ThoughtSpot's move to a new stack.
It is *_on_* by default for individual ThoughtSpot Cloud users.
The option to turn it on or off <<toggle-on-off,individually>> is also on by default.
To remove or enable this option, contact {support-url}.
If the new Answer experience is available in your environment, turn it on or off individually from your profile, in the *Experience manager* at the bottom of your profile.
The new Answer experience contains the following features:

include::partial$new-answer-experience-features.adoc[]

[#toggle-on-off]
== Turn the new Answer experience on or off individually

The new Answer experience is on by default. The option to turn it on or off individually is also on by default.
To remove or enable this option, contact {support-url}.
If this option is available in your environment, you can turn it on or off individually from your profile.

To turn the new Answer experience on or off, follow these steps:

. Navigate to your profile: select the *Profile* icon at the upper right of your screen, and select *Profile*.
. Next to *Experience*, at the bottom of your profile, select *Edit*.
. Select *New experience* or *Classic experience*.
. Select *Save*.

== Turn the new Answer experience on or off for the whole cluster

Manage the availability of the new Answer experience by contacting {support-url}.
ThoughtSpot Support can turn the new Answer experience on or off globally, and specify the default answer experience for all users.
For example, you can turn the new Answer experience on globally, but still have the classic experience as the default, allowing users to opt into the new experience.

[#limitations]
== Limitations

include::partial$new-answer-experience-deprecations.adoc[]
