= Collect security logs
:last_updated: 11/01/2022
:linkattrs:
:experimental:
:page-layout: default-cloud
:page-aliases: /admin/data-security/audit-logs.adoc
:description: Collect security audit logs to monitor user activity in ThoughtSpot and increase your system security.

ThoughtSpot Cloud provides security audit events related to account activities and user actions within ThoughtSpot.
These events can help your SOC team detect potential security threats or compromised user accounts in your organization.

== How to fetch security events

To fetch security events from ThoughtSpot, you can push the logs to your SIEM server, or pull the logs using the Audit Logs API.

=== Push to your SIEM server

ThoughtSpot’s human-readable and comprehensive events can be shipped to your SIEM application in near real-time. Security events remain within the system for 30 days.
To integrate with your SIEM or view these logs, contact {support-url}.

ThoughtSpot also supports log ingestion to the customer SIEM system. We support multiple output plugins which can be configured to push the security audit events to the configured destination SIEM server at an interval of every 5 seconds.

ThoughtSpot supports the following output plugin options:

- HTTP
- Splunk
- Azure Log Analytics
- Datadog

=== Pull via Audit Logs API

The ThoughtSpot log API service allows you to programmatically get security audit events from the ThoughtSpot system. To use this API, make sure you have admin user privileges.

For more information, see link:https://developers.thoughtspot.com/docs/?pageid=logs-api[Audit logs API,window=_blank].

== ThoughtSpot security events

ThoughtSpot security events include the following information:


* An event ID
* A unique description of the event (for example, "`A user account was created`")
* Timestamp (in UTC) yyyy/mm/dd:hh:mm:ss
* User ID of the person initiating the event
* public IP of the system from which the request originates
* Fields specific to the event (for example, name of the new account)

[#security-events]
== Security events

The possible events are:

* <<account-locked,ACCOUNT_LOCKED>>
* <<auth-token-created-successfully,AUTH_TOKEN_CREATED_SUCCESSFULLY>>
* <<create-answer,CREATE_ANSWER>>
//* <<create-connection,CREATE_CONNECTION>>
//* <<create-connection-attempted,CREATE_CONNECTION_ATTEMPTED>>
* <<create-pinboard,CREATE_PINBOARD>>
* <<create-rls-rule,CREATE_RLS_RULE>>
* <<create-tables,CREATE_TABLES>>
* <<csv-upload-finished,CSV_UPLOAD_FINISHED>>
* <<csv-upload-started,CSV_UPLOAD_STARTED>>
* <<data-upload-configured,DATA_UPLOAD_CONFIGURED>>
* <<delete-answers,DELETE_ANSWERS>>
//* <<delete-connection,DELETE_CONNECTION>>
//* <<delete-connection-attempted,DELETE_CONNECTION_ATTEMPTED>>
* <<delete-pinboards,DELETE_PINBOARDS>>
* <<delete-rls-rules,DELETE_RLS_RULES>>
//* <<edit-connection,EDIT_CONNECTION>>
//* <<edit-connection-attempted,EDIT_CONNECTION_ATTEMPTED>>
* <<failed-to-create-auth-token,FAILED_TO_CREATE_AUTH_TOKEN>>
* <<login-failed,LOGIN_FAILED>>
* <<login-successful,LOGIN_SUCCESSFUL>>
* <<logout-failed,LOGOUT_FAILED>>
* <<logout-successful,LOGOUT_SUCCESSFUL>>
* <<principals-in-group-update,PRINCIPALS_IN_GROUP_UPDATE>>
* <<privilege-changes,PRIVILEGE_CHANGES>>
* <<role-created,ROLE_CREATED>>
* <<role-deleted,ROLE_DELETED>>
* <<role-updated,ROLE_UPDATED>>
* <<roles-assigned,ROLES_ASSIGNED>>
* <<roles-imported,ROLES_IMPORTED>>
* <<roles-removed,ROLES_REMOVED>>
* <<share-objects,SHARE_OBJECTS>>
* <<update-answers,UPDATE_ANSWERS>>
* <<update-password,UPDATE_PASSWORD>>
* <<update-password-failed,UPDATE_PASSWORD_FAILED>>
* <<update-pinboards,UPDATE_PINBOARDS>>
* <<update-rls-rule,UPDATE_RLS_RULE>>
* <<user-activate,USER_ACTIVATE>>
* <<user-groups-created,USER_GROUPS_CREATED>>
* <<user-groups-deleted,USER_GROUPS_DELETED>>
* <<user-group-modified,USER_GROUP_MODIFIED>>
* <<users-created,USERS_CREATED>>
* <<users-deleted,USERS_DELETED>>
* <<users-modified,USERS_MODIFIED>>


// - [user-group-change](#user-group-change)


== Event descriptions

ThoughtSpot defines these events as follows:


[#account-locked]
ACCOUNT_LOCKED::
A local user fails to authenticate _x_ times in a row, locking the account.
Administrators can configure the number of authentication attempts before lockout within ThoughtSpot.
[#auth-token-created-successfully]
AUTH_TOKEN_CREATED_SUCCESSFULLY:: Auth token creation succeeds.
[#create-answer]
CREATE_ANSWER:: A user attempts to create a new Answer.
[#create-rls-rule]
[#create-pinboard]
CREATE_PINBOARD::  A user attempts to create a new Liveboard.
CREATE_RLS_RULE:: A user creates an RLS (row-level-security) rule on a table.
[#create-tables]
CREATE_TABLES::  A user attempts to create a new table.
[#csv-upload-finished]
CSV_UPLOAD_FINISHED:: CSV upload finishes.
[#csv-upload-started]
CSV_UPLOAD_STARTED:: CSV upload starts.
[#data-upload-configured]
DATA_UPLOAD_CONFIGURED:: Data upload configured for a connection.
[#delete-answers]
DELETE_ANSWERS:: A user attempts to delete an Answer.
[#delete-pinboards]
DELETE_PINBOARDS::  A user attempts to delete a Liveboard.
[#delete-rls-rules]
DELETE_RLS_RULES:: A user deletes an RLS rule on a table.
[#failed-to-create-auth-token]
FAILED_TO_CREATE_AUTH_TOKEN:: Auth token creation fails.
[#login-failed]
LOGIN_FAILED:: A user fails to log in due to an incorrect password, or IDP/ADP deny the authentication request.
[#login-successful]
LOGIN_SUCCESSFUL::  A local, IDP or AD user logs in to ThoughtSpot.
[#logout-failed]
LOGOUT_FAILED:: User logout failed.
[#logout-successful]
LOGOUT_SUCCESSFUL:: A user logs out from ThoughtSpot.
[#principals-in-group-update]
PRINCIPALS_IN_GROUP_UPDATE::  A user successfully or unsuccessfully attempts to add or remove users or groups from a group.
[#privilege-changes]
PRIVILEGE_CHANGES::  A user adds or removes one or several privileges from a group.
[#role-created]
ROLE_CREATED:: Role creation attempted.
[#role-deleted]
ROLE_DELETED:: Role deletion attempted.
[#role-updated]
ROLE_UPDATED:: Role update attempted.
[#roles-assigned]
ROLES_ASSIGNED:: Roles assignment to group attempted.
[#roles-imported]
ROLES_IMPORTED:: Roles import attempted.
[#roles-removed]
ROLES_REMOVED:: Removal of roles from group attempted.
[#share-objects]
SHARE_OBJECTS::  A user successfully or unsuccessfully attempts to share an object (Liveboard, Worksheet, Answer) with another user or group. The "discoverability" field indicates whether a shared object is discoverable to users of the same user group as the author who have access to the underlying data source.
[#update-answers]
UPDATE_ANSWERS:: A user attempts to modify an existing Answer.
[#update-password]
UPDATE_PASSWORD::  A user successfully or unsuccessfully attempts to change their password.
[#update-password-failed]
UPDATE_PASSWORD_FAILED:: A user fails to update their password.
[#update-pinboards]
UPDATE_PINBOARDS::  A user attempts to modify an existing Liveboard.
[#update-rls-rule]
UPDATE_RLS_RULE::  A user modifies an RLS rule on a table.
[#user-activate]
USER_ACTIVATE:: A user attempts to activate their account.
[#user-groups-created]
USER_GROUPS_CREATED:: A user creates a new group, either manually through the Admin Portal, or through the internal API.
[#user-groups-deleted]
USER_GROUPS_DELETED:: A user deletes a group, either manually through the Admin Portal, or through the internal API.
[#user-group-modified]
USER_GROUP_MODIFIED:: A user modifies the properties of a group, either in Admin Portal or over internal API.
(Properties include group name, display name, and sharing visibility.)


////
[#object-creation]
Object creation::
A user creates a new object (pinboard, worksheet, answer, etc.) in ThoughtSpot.

[#object-deletion]
Object deletion::
A user successfully or unsuccessfully attempts to delete an object (pinboard, worksheet, answer).

[#object-modification]
Object modification::
A user successfully or unsuccessfully attempts to change the properties of an object.</dd>
////

[#users-created]
USERS_CREATED::  A new user creates an account, either manually in the Admin Portal or through the internal API.
[#users-deleted]
USERS_DELETED::  A user account is deleted, either manually in the Admin Portal or through the internal API.
[#users-modified]
USERS_MODIFIED::  A user profile changes, either manually in the Admin Portal or over SAML sync.



////
[#user-group-change]
User group change::
A successful or unsuccessful attempt to change the user list to a group by adding or removing members.
////

== Free Trial events

The possible Free Trial events are:

* <<trial-user-create,TRIAL_USER_CREATE>>
* <<trial-user-delete,TRIAL_USER_DELETE>>
* <<trial-user-end,TRIAL_USER_END>>
* <<trial-user-expire,TRIAL_USER_EXPIRE>>
* <<trial-user-extend,TRIAL_USER_EXTEND>>
* <<user-invited,USER_INVITED>>

== Event descriptions

[#trial-user-create]
TRIAL_USER_CREATE:: A user successfully or unsuccessfully attempts to create a Free Trial account.
[#trial-user-delete]
TRIAL_USER_DELETE:: A user successfully or unsuccessfully attempts to delete a Free Trial account.
[#trial-user-end]
TRIAL_USER_END:: A user attempts to end their trial.
[#trial-user-expire]
TRIAL_USER_EXPIRE:: A Free Trial account expires.
[#trial-user-extend]
TRIAL_USER_EXTEND:: A user attempts to extend their trial.
[#user-invited]
USER_INVITED::  A user is invited to ThoughtSpot for a free trial.

== Team Edition events

The possible Team Edition events are:

* <<team-change-subscription,TEAM_CHANGE_SUBSCRIPTION>>
* <<teams-edition-user-delete,TEAM_EDITION_USER_DELETE>>
* <<teams-edition-user-expire,TEAM_EDITION_USER_EXPIRE>>
* <<user-change-subscription,USER_CHANGE_SUBSCRIPTION>>

== Event descriptions

[#team-change-subscription]
TEAM_CHANGE_SUBSCRIPTION:: The team subscription changes.
[#teams-edition-user-delete]
TEAMS_EDITION_USER_DELETE:: A Team Edition user successfully or unsuccessfully attempts to delete an account.
[#teams-edition-user-expire]
TEAM_EDITION_USER_EXPIRE:: A Team Edition user account expires.
[#user-change-subscription]
USER_CHANGE_SUBSCRIPTION:: A user attempts to change a subscription.

== Org events

The possible Orgs events are:

* <<org-access-granted-to-user,ORG_ACCESS_GRANTED_TO_USER>>
* <<org-creation-failed,ORG_CREATION_FAILED>>
* <<org-creation-successful,ORG_CREATION_SUCCESSFUL>>
* <<org-deletion-failed,ORG_DELETION_FAILED>>
* <<org-deletion-successful,ORG_DELETION_SUCCESSFUL>>
* <<org-switch-failed,ORG_SWITCH_FAILED>>
* <<org-switch-successful,ORG_SWITCH_SUCCESSFUL>>

== Event descriptions

[#org-access-granted-to-user]
ORG_ACCESS_GRANTED_TO_USER:: User added to an Org.
[#org-creation-failed]
ORG_CREATION_FAILED:: Org creation failed.
[#org-creation-successful]
ORG_CREATION_SUCCESSFUL:: Successfully created an Org.
[#org-deletion-failed]
ORG_DELETION_FAILED:: Org deletion failed.
[#org-deletion-successful]
ORG_DELETION_SUCCESSFUL:: Successfully deleted an Org.
[#org-switch-failed]
ORG_SWITCH_FAILED:: Failed to switch Org for user.
[#org-switch-successful]
ORG_SWITCH_SUCCESSFUL:: Successfully switched Org.




////
ThoughtSpot includes a number of management tools, monitoring applications, and automated processes to support system security. System security includes managing access and privileges, audit logs, security policies, and Linux OS installed package updates.

== Audit logs

There are several ways you can view audit log information in ThoughtSpot. You can see recent events in the Control Center or view more detailed audit logs using tscli. Administrators can view audit logs of configuration changes users have made to ThoughtSpot in these ways:

- Monitor events from the [Control Center]({{ site.baseurl }}/admin/system-monitor/monitor-pinboards.html#).
- Generate audit log reports through the `tscli` command.


You can access an audit log of cluster events through tscli. You can also access information on cluster updates, configurations, data loading and metadata events.

Use the `tscli event list` command to return an audit list of events from the cluster. The syntax is:

```
tscli event list
   [--include <all|config|notification>]
   [--since <hours,minutes,days>
   | --from <yyyymmdd-HH:MM>
   --to <yyyymmdd-HH:MM>]
   [--detail]
   [--summary_contains
   <'string1'| 'string2' ...>]
   [--detail_contains
   <'string1'| 'string2' ...>]
   [--attributes
   <key1='value1'|
   key2='value2' ...>]
```

Optional parameters are:

| Parameter | Description |
|---------------|---------------------|
| `--include` | Specifies the type of events to include, and can be `all`, `config`, or `notification`. |
| `--detail` | Returns the events in a detail format rather than a tabular summary, which is the default. |
| `--summary_contains <'string1' | 'string2' ...>` | Specifies a string to check for in the event summary. Enclose strings in single quotes, and separate multiple strings with &pipe;. Events that match all specified strings will be returned. |
| `--detail_contains <'string1'| 'string2' ...>` | Specifies a string to check for in the detail. Enclose strings in single quotes, and separate multiple strings with `|` (pipe symbol). Events that match all specified strings will be returned.|
| `--attributes <key1='value1' &pipe; key2='value2' ...>` | Specifies attributes to match as key=value pairs. Separate multiple attributes with `|` (pipe symbol). Events that match all specified key/value pairs will be returned. Put single quotes around the value(s). |

And a time window made up of either:

- `--since <hours,minutes,days>` is a time in the past for where the event audit begins, ending at the present time. Specify a human readable duration string, for example 4h (4 hours), 30m (30 minutes), 1d (1 day).

Or both:

- `--from <yyyymmdd-HH:MM>` is a timestamp for where to begin the event audit. It must be of the form: yyyymmdd-HH:MM.
- `--to <yyyymmdd-HH:MM>` is a timestamp for where to end the event audit. It must be of the form: yyyymmdd-HH:MM.

To get audit logs:

1. Sign in to the Linux shell using SSH.
2. Issue the `tscli event list` command, with the desired parameters, for example:

    ```
    $ tscli event list
       --include config
       --since 24 hours
    ```


== Security policies

Security policies are the principles and processes ThoughtSpot uses in development to ensure a product that conforms to security standards. Security policies ensure a secure product with each release. When a release is in development, each build is tested using Qualys Network Security and Vulnerability Management Suite. Issues and vulnerabilities are fixed proactively, based on the results.

The ThoughtSpot Engineering and ThoughtSpot Support teams are notified of Common Vulnerabilities and Exposures (CVEs), so they can patch OS packages proactively as well. You can view installed packages along with their version numbers at any time, in order to see if you require an update to ThoughtSpot.

Whenever a CVE is identified, and an OS package needs to be updated, the next patch release will include the patch or update. You can view installed Linux packages at any time, along with the version numbers of the installed packages.

## Third-party security software for security, governance, and monitoring of ThoughtSpot

You can install supported [third-party security and monitoring software]({{ site.baseurl}}/admin/data-security/about-secure-monitor-sw.html#) on a ThoughtSpot cluster.
////
