= Authentication
:last_updated: 11/10/21
:linkattrs:
:experimental:
:page-layout: default-cloud
:page-aliases: /admin/architecture/authentication.adoc
:description: ThoughtSpot provides either SAML or local ThoughtSpot accounts to authenticate users.

ThoughtSpot provides two ways to authenticate users: xref:authentication-integration.adoc[SAML] (Security Association Markup Language) and xref:authentication-local.adoc[ThoughtSpot local accounts].
ThoughtSpot recommends that you use SAML for authentication, since it is industry-standard and enables Single-Sign On (SSO) with your Identity Provider (IDP).

Starting in *Beta* in the 8.7.0.cl release, ThoughtSpot supports a new, industry-standard cloud authentication method through Okta. With this feature, called Identity and Access Management V2 (IAM V2), ThoughtSpot powers its internal authentication with Okta, which is the industry-leading authentication platform. The change to Okta is internal and has no impact on customers. Local and SAML authentication are still the 2 ways to authenticate users. After ThoughtSpot enables IAM V2 feature by default, all user authentication will automatically use the internal Okta service. This feature set involves several external improvements to authentication, including security enhancements. This feature is in *Beta* and off by default in 8.7.0.cl. To enable it, contact {support-url}. For more information, refer to xref:okta-iam.adoc[].

Use the following table to help you choose between local and SAML authentication.

[horizontal]
SAML::
* Use SAML for single sign-on authentication.
* Can redirect from ThoughtSpot to SAML logins.
* Recommended for portal integration.

ThoughtSpot::
* User created and managed in ThoughtSpot.
* xref:user-management.adoc#password[Password strength control]
* Only recommended when SAML is not an option.

////
keeping for now in case the above table looks as bad on the site as it does in the preview
+++<table>++++++<tr>++++++<th>+++xref:authentication-integration.adoc[SAML]+++</th>+++
    +++<th>+++xref:user-management.adoc[ThoughtSpot]+++</th>++++++</tr>+++
  +++<tr>++++++<td>++++++<ul>++++++<li>+++Use SAML for single sign-on authentication.+++</li>+++
    +++<li>+++Can redirect from ThoughtSpot to SAML logins.+++</li>+++
    +++<li>+++Recommended for portal integration.+++</li>++++++</ul>++++++</td>+++
    +++<td>++++++<ul>++++++<li>+++User created and managed in ThoughtSpot.+++</li>+++
    +++<li>+++xref:user-management.adoc#password[Password strength control]+++</li>+++
    +++<li>+++Only recommended when SAML is not an option.+++</li>++++++</ul>++++++</td>++++++</tr>++++++</table>+++
////

All users and groups must be known to ThoughtSpot.
If you are using SAML and don't create users in ThoughtSpot, a user is created when the user first logs in.
However, this user is assigned to the `All` group and can only see content available for all users.

Groups are the primary way that security is managed.
Groups are not automatically created.
You can create xref:group-management.adoc[groups] and xref:user-management.adoc[users] manually, or you must automate the assignment from a source system.
ThoughtSpot has public APIs that you can use to sync users and groups between source systems and your ThoughtSpot application.
