= Create answers in Setup
:last_updated: 12/14/2021
:linkattrs:
:experimental:
:page-layout: default-cloud
:page-aliases: /admin/ts-cloud/automated-answer-creation.adoc
:description: Use the auto-answer creation feature to experiment with creating an answer from a search.

Use the auto-answer creation feature to experiment with creating an answer from a search.

To simplify data modeling, ThoughtSpot supports automated answer creation during Setup, allowing you to create and save Search visualizations for future use.
When creating answers through Setup, you can view suggested answers for the measures, attributes and dates you select, and make changes to the auto-created answers before you save them.

== Create answers in Setup

To see suggested Search visualizations in Setup, follow these steps:

. Enter Setup by logging in for the first time, or by selecting *Profile* from the user icon at the top right of the screen and clicking *Revisit onboarding experience* under *Preferences*.
. Proceed to Step 1 of Analyst Setup by choosing the analyst data tile. +
*I want to: set up data connections, define relationships, and create worksheets to help my team search and analyze data*.
. Complete Step 1 of Setup, xref:connect-data.adoc[setting up your connection].
. Complete Step 2 of Setup, xref:worksheet-create-setup.adoc[Model data and create a worksheet].
Proceed to *Search and visualize*.
. The *Select columns from worksheet* interface appears.
Choose at least one measure and attribute from your data.
We recommend you select multiple columns to generate more possible answers.
+
NOTE: If your data contains date information, you must select a date column as well as measure and attribute columns in order to generate your answers.
. A list of your potential answers appears.
To view each answer as a chart, click the answer title.
. [Optional] Modify the selected answer by entering filters in the search bar and clicking *Go*.
To save a modified answer, select *Save*.
. Select *Go to setup checklist* from the top left corner of the screen to exit Setup.
To save all auto-created answers, choose *Save answers and exit* from the window that appears.
. To view the list of answers created from Setup, select *view answers* from the Setup tab, or select *Answers* from the navigation bar.

== Working with answers

+++<script src="https://fast.wistia.com/embed/medias/i8smdu5gws.jsonp" async></script><script src="https://fast.wistia.com/assets/external/E-v1.js" async></script><span class="wistia_embed wistia_async_i8smdu5gws popover=true popoverAnimateThumbnail=true popoverBorderColor=4E55FD popoverBorderWidth=2" style="display:inline-block;height:252px;position:relative;width:450px">&nbsp;</span>+++

*_Next steps:_* proceed to xref:liveboard-compose.adoc[Compose Liveboards from answers].
