= AI translation of Answers and Liveboards
:page-last_updated: Feb 3, 2026
:author: Naomi
:linkattrs:
:experimental:
:description: We now support locale-specific translations for all written text on saved Answers and Liveboards, apart from column names.
:jira: SCAL-285893, SCAL-292549, SCAL-300825

We now support locale-specific translations for all written text on saved Answers and Liveboards, apart from column names and filters. Translations are matched with the locale chosen in the user profile. Although AI translation is GA, it must be enabled by your administrator to work on your instance.

For ThoughtSpot Cloud:
When using Chrome, automatic translation uses its in-built link:https://developer.chrome.com/docs/ai/translator-api[Translator API]. On other browsers, translation occurs using the LLM chosen on the instance.

For ThoughtSpot Embedded:
Regardless of the browser used, the translation occurs using the LLM.


//Spotter must be enabled on your instance for auto-translation to work.

== Translate your content

To enable translation of your Liveboards and Answers, follow these steps:

. Click your user icon in the top right corner and select *Profile*.

. Click *Edit* for the *Preferences* section.

. Click the *System language* dropdown and select your desired locale. Click *Save*.

== Supported content

Translated content is supported for the following written content:

* Saved answers
** Title and description
** Downloaded Answers in PNG format
** Answers exported as PNG files using the link:https://developers.thoughtspot.com/docs/fetch-data-and-report-apis#_answer_report_api[Answer Report API]
* Liveboards
** Title and description
** Tab name
** Group title and description
** Visualizations title and description
** Note tiles
** Personalized view names
** Liveboards downloaded as PDFs
** Scheduled Liveboards in PDF format
** Liveboards exported as PDF or PNG files using the link:https://developers.thoughtspot.com/docs/fetch-data-and-report-apis#_liveboard_report_api[Liveboard Report API]

Translated content appears in the following areas:

* Answer page
* Liveboard page
* Download modal
* Schedule modal
* Liveboard Explore
* Liveboard information pop-up
* List pages such as Livebaord names, Answer names, and Liveboard names in schedules
//* Favorites
* Favorites, Trending, or Watchlist on the home page

For the following areas, translated content is not supported. By default, the content appears in the language it was saved in:

* Object search and search in list pages. Searched objects appear according to their saved names.
* Emails appear in English unless altered by an admin user.
* TML files remain in English.
* Titles generated for unsaved Answers are auto-generated based on column names.
* Edit mode appears in the saved language.
* Auto-translation is not supported for Spotter.
* The pin modal appears in the saved language.
* Monitor subscriptions and SpotIQ analyze in the list pages remain in the saved language.
* AI highlights are not supported.
* When you schedule a Liveboard and select a CSV or XLSX format, the downloaded content remains in the saved language.
* Liveboards downloaded as CSV or XLSX files remain in the saved language.
* Downloaded Answers remain in the saved language.
* Liveboards exported using the Liveboard Report API in CSV or XLSX format, or visualizations exported using the Answer Report API remain in the saved language.


== Enablement

Auto-translation can be enabled at either instance- or Org-level. By default, this feature is disabled. If enabled at instance level, it is automatically enabled for each individual Org. However, once enabled, Org admins can disable it for their Org. If this feature is disabled at instance level, Org admins are unable to enable the feature.

To enable this feature for your instance, navigate to the Admin panel and select *Home Page & App Experience*. Set *Auto-translate Liveboards and Answers* to *Enabled*.

== Limitations

* Chrome is only able to translate content from English to your chosen locale. If the content is in Japanese, and your locale is French, Chrome will not show the content in French; it will remain in Japanese. For other browsers, this limitation does not exist and ThoughtSpot can translate from any language to your locale.

* If there is an error in translation, ThoughtSpot shows only the original content.

* You cannot specify which Liveboard or Answer gets translated, as this is an instance-level setting.

