= AI translation of Answers and Liveboards
:last_updated: 11/24/25
:author: Naomi
:linkattrs:
:experimental:
:description: We now support locale-specific translations for all written text on saved Answers and Liveboards, apart from column names.
:page-layout: default-cloud-beta

We now support locale-specific translations for all written text on saved Answers and Liveboards, apart from column names and filters. This includes the following elements:

* Saved answers
** Title and description
* Liveboards
** Title and description
** Tab name
** Group title and description
** Visualizations title and description
** Note tiles
** Personalized view names


Translations are matched with the locale chosen in the user profile.

NOTE: Auto-translation is in beta. To enable this feature, contact {support-url}.

== Translate your content

To enable translation of your Liveboards and Answers, follow these steps:

. Click your user icon in the top right corner and select *Profile*.

. Click *Edit* for the *Preferences* section.

. Click the *System language* dropdown and select your desired locale. Click *Save*.

