= Create Answers in Setup
:page-last_updated: Sep 22, 2026
:linkattrs:
:experimental:
:page-aliases: /admin/ts-cloud/automated-answer-creation.adoc
:description: Use the auto-answer creation feature to experiment with creating an Answer from a search.

Use the auto-answer creation feature to experiment with creating an Answer from a search.

To simplify data modeling, ThoughtSpot supports automated Answer creation during Setup, allowing you to create and save Search visualizations for future use.
When creating Answers through Setup, you can view suggested Answers for the measures, attributes and dates you select, and make changes to the auto-created Answers before you save them.

== Create Answers in Setup

To see suggested Search visualizations in Setup, follow these steps:

. Enter Setup by logging in for the first time, or by choosing *Profile* from the user icon at the upper right of the screen and selecting *Revisit onboarding experience* under *Experience*.
. Proceed to Step 1 of Analyst Setup by choosing the analyst data tile. +
*I want to: set up data connections, define relationships, and create Models to help my team search and analyze data*.
. Complete Step 1 of Setup, xref:connect-data.adoc[setting up your connection].
. Complete Step 2 of Setup, xref:models.adoc[Model data].
Proceed to *Search and visualize*.
. The *Select columns from Model* interface appears.
Choose at least one measure and attribute from your data.
We recommend you select multiple columns to generate more possible Answers.
+
NOTE: If your data contains date information, you must select a date column as well as measure and attribute columns in order to generate your Answers.
. A list of your potential Answers appears.
To view each Answer as a chart, select the Answer title.
. [Optional] Modify the selected Answer by entering filters in the search bar and selecting *Go*.
To save a modified Answer, select *Save*.
. Select *Go to setup checklist* from the upper-left corner of the screen to exit Setup.
To save all auto-created Answers, choose *Save answers and exit* from the window that appears.
. To view the list of Answers created from Setup, select *view answers* from the Setup tab, or select *Answers* from the navigation bar.

== Working with Answers

++++
<br>
<div class="border">
<script src="https://fast.wistia.com/player.js" async></script><script src="https://fast.wistia.com/embed/ll235wgl8i.js" async type="module"></script><style>wistia-player[media-id='ll235wgl8i']:not(:defined) { background: center / contain no-repeat url('https://fast.wistia.com/embed/medias/ll235wgl8i/swatch'); display: block; filter: blur(5px); padding-top:56.25%; }</style> <wistia-player media-id="ll235wgl8i" aspect="1.7777777777777777"></wistia-player>
</div>
++++

*_Next steps:_* proceed to xref:liveboard.adoc[Compose Liveboards from Answers].
