= VitaraCharts for ThoughtSpot
:last_updated: 12/3/24
:linkattrs:
:experimental:
:author: Mark
:page-layout: default-cloud
:description: With custom charts, you can add your own custom charts to ThoughtSpot.
:jira: SCAL-233534

ThoughtSpot has partnered with Vitara to supercharge your data storytelling. With VitaraCharts for ThoughtSpot, you can access over 20 interactive charts which are fully integrated with ThoughtSpot.

== Benefits of VitaraCharts

Charts brings an advanced visualization library that extends ThoughtSpot’s capabilities to deliver an even richer, more dynamic visualization experience.

VitaraCharts for ThoughtSpot benefits include:

* *Seamless integration with native ThoughtSpot features*
+
You can pin charts from VitaraCharts on Liveboards, and use your favorite interactive features on these charts, including drill anywhere, filtering, explore, and more. ThoughtSpot makes it easy to go from high-level analytics to granular insights.

* *Advanced library of charts*
+
Adding 20+ customizable chart types on top of ThoughtSpot’s existing set, VitaraCharts has something for everyone, from new visualizations to pixel-perfect control over popular chart types.

* *Plug-and-play deployment*
+
Install and deploy visualizations on your ThoughtSpot instance within seconds. Once installed, all users receive instant access to charts within your instance.

* *Enterprise-grade security*
+
Your data never reaches VitaraCharts servers, and no data or configuration is written back to VitaraCharts servers. VitaraCharts servers are used by the ThoughtSpot platform only to fetch the charts developed by VitaraCharts.

* *Fully supported*
+
Software maintenance, upgrades, and expert technical support are all included with the VitaraCharts subscription.

For more information about the specific charts included and a demo video, go to https://www.vitaracharts.com/thoughtspot[VitaraCharts for ThoughtSpot^].

== Prerequisites for VitaraCharts

The custom charts feature must be enabled on your ThoughtSpot cluster. For more information, see xref:chart-custom.adoc[Custom charts].

== How to get VitaraCharts

You can try VitaraCharts before you purchase a subscription.

*Free trial*

. Sign up for a free 30-day free trial, at https://www.vitaracharts.com/thoughtspot[VitaraCharts for ThoughtSpot].
. Hema Pratap from VitaraCharts will contact you to schedule a demo.
. After the demo, VitaraCharts will send an email to you with links to the charts and the instructions on how to install them.
. Your ThoughtSpot administrator uses the instructions provided by Vitara to install the charts on your cluster.

*VitaraCharts subscription*

To purchase a subscription, contact hema@vitaracharts.com.

'''
> **Related information**
>
> * https://tsdocs.vitaracharts.com/[VitaraCharts for ThoughtSpot documentation^]