= Create charts
:last_updated: 2/24/2025
:linkattrs:
:experimental:
:page-layout: default-cloud
:description: Create your own charts in ThoughtSpot.
:jira: SCAL-242708

You can now create your own charts inside ThoughtSpot. If you're a developer, you can create new chart types by writing the code for them in the Chart Creator Playground. Using the chart library API, you create complex charts.

The Chart Creator Playground comprises four components:

- *The HTML editor*, where you can add the chart container structure the layout, and add additional elements like annotation.
- *The CSS editor*, where you create your chart’s look and feel by applying different styles using the the available class names in CSS.
- *The JavaScript editor*, where you can use the API to render complex charts. You can use multiple global variables.
- *The Chart preview*, where you can preview the chart based on the work you've done in the other components.

== HTML editor

. . .

== CSS editor

. . .

== JavaScript editor

The following APIs and data are available in the JavaScript editor:

* Muze library: contains the exhaustive API to create different kinds of charts, composing multiple layers in the same chart, cross-interaction in multiple canvases, and more.
* Data and DataModel: The data coming from a Sage search query is available in the editor. Muze also provides an in-memory data-manipulation component called DataModel which you can use to add filters, selection, group-by, and more, allowing you to structure the data to render very specific charts.
* Color palettes: The color that is used at the global level of the entire application is exposed in the editor, so that you can use it in your chart to match color and styles used in other chart types.

== Chart preview




