= Geo charts
:last_updated: 07/5/23
:linkattrs:
:experimental:
:page-layout: default-cloud
:page-aliases: /end-user/search/about-geo-charts.adoc
:description: Use geo area, geo bubble, and geo heatmap charts to visualize geographical data in ThoughtSpot.
:jira: SCAL-195134

Geo charts show data on a map by location.
There are three geo charts that let you visualize geographical data in ThoughtSpot: xref:chart-geo-area.adoc[geo area], xref:chart-geo-bubble.adoc[geo bubble], and xref:chart-geo-heatmap.adoc[geo heatmap] charts.
These geo charts can display six types of geographical data, depending on territory:

* Country
* State
* County
* Zip code
* Point (latitude/longitude)
* Other sub-nation regions (for international countries)

[#enhancement]
ThoughtSpot now supports maps for all countries. See the complete list in link:https://wiki.openstreetmap.org/wiki/List_of_territory_based_projects[Openstreetmap supported countries]. If you would like to use a custom map to visualize your data, see xref:geomaps-custom.adoc[].

Previously, ThoughtSpot supported the following geo chart capabilities:

* Visualize data at the country level for multiple countries in one chart.
* Visualize data at a higher level of detail (state, city, zip code) within one country at a time.

Now, ThoughtSpot supports the following capabilities:

* Visualizations comparing subdivisions of multiple countries in a single visualization. For example, if a selected column contains data from cities in the United States and Mexico, all data would be displayed on a single visualization.
* Visualizations displaying multiple levels of subdivisions within a country, rather than just city and zip code.
* Visualizations representing zip code as an area within a region, rather than a point on a map.

To improve the accuracy of your Search, we recommend appending the country name, or adding a reference to the country that the data is referring to. To append the country name, you can use a formula such as `concat (region, ', ' , country)`.

== Displayed geo data

Here is a table that shows which GeoType data can be displayed using which geo chart type.

|===
| GeoType | Data Type | Geo chart type | Notes

| Country
| VARCHAR
| Geo area (default), geo bubble, geo heatmap
| Can also be regions.

| County
| VARCHAR
| Geo area (default), geo bubble, geo heatmap
| Only for counties in the United States.

| Latitude (point)
| VARCHAR or DOUBLE
| Geo bubble (default), geo heatmap
| Must use both latitude and longitude columns.

| Longitude (point)
| VARCHAR or DOUBLE
| Geo bubble (default), geo heatmap
| Must use both latitude and longitude columns.

| State
| VARCHAR
| Geo area (default), geo bubble, geo heatmap
| Only for states in the United States.

| Zip code
| VARCHAR
| Geo bubble (default), geo heatmap
| Refer to the xref:geomap-reference.adoc[Geo map reference] to see which countries have supported zip codes.

| Other sub-nation regions
| VARCHAR
| Geo area (default), geo bubble, geo heatmap
| The display depends on the type of administrative region.
|===

For data to display in geo charts, your administrator must configure it as geographical data.
If you don't get an expected map visualization, contact your administrator so they can configure the system correctly.

See also:

* xref:chart-geo-area.adoc[]
* xref:chart-geo-bubble.adoc[]
* xref:chart-geo-heatmap.adoc[]

include::partial$geo-chart-map-type.adoc[]

== Limitations

Geo charts do *_NOT_* support conditional formatting.
