= ThoughtSpot Cloud infrastructure security
:last_updated: 11/05/2021
:linkattrs:
:experimental:
:page-layout: default-cloud
:page-aliases:
:description: Learn about ThoughtSpot Cloud's infrastructure security.
:jira: SCAL-178043

This article describes the various infrastructure and security controls available in ThoughtSpot Cloud. ThoughtSpot has achieved https://www.thoughtspot.com/press-releases/thoughtspot-modern-analytics-cloud-receives-iso-27001-certification[ISO 27001 certification^], and https://www.thoughtspot.com/press-releases/thoughtspot-receives-soc-2-type-2-attestation[SOC 2 Type II attestation^].

== Access log storage

ThoughtSpot Cloud access logs are generated on the customer instance and are copied to AWS S3 storage for centralized management. The logs are stored in a per-tenant S3 bucket and encrypted using a per-tenant encryption key. The logs are access-controlled to prevent unauthorized access. ThoughtSpot provides a logging capability in the platform that captures login and user actions.

== Access to the ThoughtSpot Cloud environment

Access to the ThoughtSpot Cloud environment is restricted to the Site Reliability Engineering (SRE) team members who support the cloud environment. The users have to be explicitly granted this access and are required to use multi-factor authentication to access the environment.

Each customer instance is separate from other customer tenants, and there is no network connectivity between tenants. Individual customer tenants are managed through the ThoughtSpot Cloud Control Plane. Network access is only allowed from the control plane to the customer tenant. The customer tenant cannot initiate any network connections back to the control plane.

== Cloud data warehouse credentials stored in the ThoughtSpot vault

Secrets in the ThoughtSpot vault have access control lists restricting the credentials to the individual instance. If a new instance is created in a customer tenant, it would not be able to access the secret unless the instance were added to the access list. The access list is controlled through our Terraform automation.

== Automated instance configurations

All other instance configurations are controlled through Infrastructure as Code (IAC) automation, including:

- Security groups
- Network configurations
- Instance creation
- Instance upgrades

== Firewall

All ThoughtSpot Cloud environments (Dev, QA, Prod) are completely isolated by firewall.
Authorized people access the environment through a secure data center in ThoughtSpot (across a VPN tunnel). Certificates are only valid for 20 minutes.

== VPC and EC2 instance

Completely dedicated and separate VPC and EC2 instance, including:

- Load balancer
- Gateways
- Dedicated backup

== Instance security services

There are security tools on the front end that allow inspection of traffic, including:

- Denial of service (DoS)
- Web application firewalls
- Intrusion detection systems

== Network access control and security group configuration

Network access control (NACL) credentials are stored in our directory as SSO is provided, by taking variables from Ping Identity and passing them through.

== Encryption in transit / encryption at rest

- All traffic encrypted using HTTPS / TLS 1.2.
* Customer browser to ThoughtSpot
* ThoughtSpot to cloud data warehouse
* ThoughtSpot to internal resources
- All credentials and keys encrypted in internal Secure Vault
- Encryption at rest (EAR): https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/EBSEncryption.html[Encrypted EBS with keys stored in AWS KMS^]
- Encrypted s3 bucket containing cluster backup. S3 bucket per tenant with per-tenant encryption key.



