= Connection reference for {connection}
:last_updated: 11/20/2023
:author: Naomi
:page-aliases:
:linkattrs:
:page-layout: default-cloud
:experimental:
:connection: Google Sheets
:description: Learn the specific information needed to establish a secure connection to Google Sheets.
:jira: SCAL-135769

You need specific information to establish a seamless and secure connection.
The following fields are required, except where noted.

Connection name:: Enter a name for your {connection} connection.
Connection description:: Provide a short description of the connection.
Google Sheet URL:: Enter the URL for the Google Sheet you want to connect to ThoughtSpot.


'''
> **Related information**
>
> * xref:connections-google-sheets-add.adoc[Add a {connection} connection]
> * xref:connections-google-sheets-edit.adoc[Edit a {connection} connection]
> * xref:connections-google-sheets-remap.adoc[Remap a {connection} connection]
> * xref:connections-google-sheets-delete-table.adoc[Delete a table from a {connection} connection]
> * xref:connections-google-sheets-delete-table-dependencies.adoc[Delete a table with dependent objects]
> * xref:connections-google-sheets-delete.adoc[Delete a {connection} connection]