= Connection reference for {connection}
:last_updated: 6/7/2022
:linkattrs:
:page-layout: default-cloud
:experimental:
:connection: Denodo
:description: Learn the specific information needed to establish a secure connection to Denodo.

You need specific information to establish a seamless and secure connection.
The following fields are required, except where noted.

[#connection-name]
Connection name::
Enter the name for the new connection.
[#connection-description]
Connection description::
_(Optional)_ Provide a short description of the connection.
[#host]
Host::
Enter the {connection} server host name. If you used an xref:connections-adw-private-link.adoc[AWS PrivateLink between your {connection} data warehouse and the ThoughtSpot Cloud tenant], use the PrivateLink Endpoint DNS name provided by {support-url}. For example, `vpce-12345a9c7e43959d-xxo2u2xx.vpce-svc-037b1f73d3de3a5b4.us-west-2.vpce.amazonaws.com`.
+
If the URL is in `https://<IP>:<PORT>` format, then only include the IP as host.
[#http-path]
Port::
{connection} server port.
[#user]
User::
Enter the user associated with the {connection} database.
[#password]
Password::
Enter the password of the user associated with the {connection} database.
[#database]
Database:: Specify the database of the {connection} account. _(Optional)_
[#project-id]
Project id::
_(Optional for Service Account only)_ Enter the project ID of the {connection} database.
[#oauth-client-id]
(OAuth only) OAuth Client ID::
Enter the OAuth client ID associated with the user of the {connection} database.
[#oauth-client-secret]
(OAuth only) OAuth Client Secret::
Enter the OAuth client secret associated with the user of the {connection} database.
[#auth-url]
(OAuth only) Auth Url::
Enter the Auth Url associated with the user of the {connection} database.
[#access-token-url]
(OAuth only) Access token Url::
Enter the Access token Url associated with the user of the {connection} database.

'''
> **Related information**
>
> * xref:connections-denodo-add.adoc[Add a {connection} connection]
> * xref:connections-denodo-edit.adoc[Edit a {connection} connection]
> * xref:connections-denodo-remap.adoc[Remap a {connection} connection]
> * xref:connections-denodo-delete-table.adoc[Delete a table from a {connection} connection]
> * xref:connections-denodo-delete-table-dependencies.adoc[Delete a table with dependent objects]
> * xref:connections-denodo-delete.adoc[Delete a {connection} connection]
> * xref:connections-denodo-private-link.adoc[]
> * xref:connections-denodo-oauth.adoc[Configure OAuth for a {connection} connection]
