= Best practices for connections with {connection}
:last_updated: 7/7/2021
:linkattrs:
:page-aliases: /admin/ts-cloud/ts-cloud-embrace-redshift-best.adoc
:experimental:
:page-layout: default-cloud
:description: You can connect to Redshift using ThoughtSpot Connections, and start searching your data. This article contains helpful pointers on data modeling.
:connection: Redshift

== Configuring your ThoughtSpot server

We recommend configuring the following settings when creating connections:

* Turn off '`Auto Indexing`', and manually set the Index Type on columns that would be helpful when searching.

https://community.thoughtspot.com/customers/s/contactsupport[Contact ThoughtSpot Support] to do this configuration.

== Optimizing query performance

User experience in ThoughtSpot Connections is strongly impacted by the performance of queries in the underlying database.
{connection} is a columnar MPP database built for analytic workloads, and proper tuning can have a significant impact on query performance.

You should always follow AWS best practices to optimize query performance.
For details, see https://docs.aws.amazon.com/redshift/latest/dg/c-optimizing-query-performance.html[Tuning query performance^] in Amazon's {connection} documentation.

== Workload management and monitoring

We recommend that you implement workload management (WLM) within {connection} to prioritize queries appropriately.
For more information, refer to the following links in Amazon's {connection} documentation:

* Implementation: https://docs.aws.amazon.com/redshift/latest/dg/cm-c-implementing-workload-management.html[Implementing workload management^]
* Workload and performance data: https://docs.aws.amazon.com/redshift/latest/dg/cm-c-wlm-query-monitoring-rules.html#cm-c-wlm-query-monitoring-metrics[System monitoring tables^]

== Concurrency scaling

ThoughtSpot may generate large numbers of concurrent queries.
{connection}'s concurrency scaling feature can be enabled to provide consistent query performance during periods of high activity.

For details, see https://docs.aws.amazon.com/redshift/latest/dg/concurrency-scaling.html[Working with concurrency scaling^] in Amazon's {connection} documentation.

== Data modeling

In {connection}, query performance can be improved significantly using Sort and Distribution keys on large tables.
Selecting an optimized compression type can also have a big impact on query performance.

These and other important topics are covered in https://docs.aws.amazon.com/redshift/latest/dg/c_designing-tables-best-practices.html[Amazon {connection} best practices for table design^] in Amazon's {connection} documentation.

== Materialized views

{connection} now supports materialized views, and it is recommended to create a materialized view and use it in place of any complex views or poor performing table joins.

For details, see https://docs.aws.amazon.com/redshift/latest/dg/materialized-view-overview.html[Creating materialized views in Amazon {connection}^] in Amazon's {connection} documentation.

== Defining joins between tables

To search more than one table at the same time in ThoughtSpot, you must define joins between these tables by specifying the columns that contain matching data across two tables.
These columns represent the '`primary key`' and '`foreign key`' of the join.
You can define them in either {connection} or ThoughtSpot.

For details on the syntax for defining primary and foreign keys in {connection}, see https://docs.aws.amazon.com/redshift/latest/dg/r_ALTER_TABLE.html[ALTER TABLE^] in Amazon's {connection} documentation.

For details on defining joins in ThoughtSpot, see xref:relationship-create.adoc[Join a table or view to another data source].

'''
> **Related information**
>
> * xref:connections-redshift-add.adoc[Add a {connection} connection]
> * xref:connections-redshift-edit.adoc[Edit a {connection} connection]
> * xref:connections-redshift-remap.adoc[Remap a {connection} connection]
> * xref:connections-redshift-external-tables.adoc[Query external tables from your {connection} connection]
> * xref:connections-redshift-delete-table.adoc[Delete a table from a {connection} connection]
> * xref:connections-redshift-delete-table-dependencies.adoc[Delete a table with dependent objects]
> * xref:connections-redshift-delete.adoc[Delete a {connection} connection]
> * xref:connections-redshift-oauth.adoc[Configure OAuth]
> * xref:connections-redshift-private-link.adoc[]
> * xref:connections-redshift-reference.adoc[Connection reference for {connection}]
> * xref:connections-query-tags.adoc#tag-redshift[ThoughtSpot query tags in Redshift]