= Enabling an AWS PrivateLink between ThoughtSpot Cloud and your {connection} data warehouse
:experimental:
:last_updated: 6/9/2022
:linkattrs:
:page-layout: default-cloud
:description: Learn how to deploy an AWS PrivateLink between your SAP HANA data warehouse and the ThoughtSpot Cloud tenant.
:connection: SAP HANA

Learn how to deploy an AWS PrivateLink between your {connection} data warehouse and the ThoughtSpot Cloud tenant.

NOTE: AWS PrivateLink is only available to Enterprise Edition users.

include::partial$private-link-intro.adoc[]

This article details how to enable a PrivateLink for *{connection}*;
to enable it for other data warehouses, refer to:

* xref:connections-redshift-private-link.adoc[Amazon Redshift PrivateLink]
* xref:connections-databricks-private-link.adoc[Databricks PrivateLink]
* xref:connections-denodo-private-link.adoc[Denodo PrivateLink]
* xref:connections-dremio-private-link.adoc[Dremio PrivateLink]
* xref:connections-adw-private-link.adoc[Oracle PrivateLink]
* xref:connections-postgresql-private-link.adoc[PostgreSQL PrivateLink]
* xref:connections-snowflake-private-link.adoc[Snowflake PrivateLink]
* xref:connections-sql-server-private-link.adoc[SQL Server PrivateLink]
* xref:connections-starburst-private-link.adoc[Starburst PrivateLink]
* xref:connections-teradata-private-link.adoc[Teradata PrivateLink]

include::partial$private-link-steps.adoc[]

[#embrace]
=== Configure Connections

xref:connections-hana.adoc[Configure Connections for {connection}], using the PrivateLink Endpoint DNS name from {support-url} for the *Host* field. For example, `vpce-12345a9c7e43959d-xxo2u2xx.vpce-svc-037b1f73d3de3a5b4.us-west-2.vpce.amazonaws.com`.

'''
> **Related information**
>
> * xref:connections-hana-add.adoc[Add a connection]
> * xref:connections-hana-edit.adoc[Edit a connection]
> * xref:connections-hana-remap.adoc[Remap a {connection} connection]
> * xref:connections-hana-delete-table.adoc[Delete a table from a {connection} connection]
> * xref:connections-hana-delete-table-dependencies.adoc[Delete a table with dependent objects]
> * xref:connections-hana-delete.adoc[Delete a {connection} connection]
> * xref:connections-hana-reference.adoc[{connection} connection reference]
> * xref:connections-query-tags.adoc#tag-saphana[ThoughtSpot query tags in SAP HANA]
> * xref:connections-hana-passthrough.adoc[]
