= Connection reference for {connection}
:last_updated: 5/11/2020
:page-aliases: /admin/ts-cloud/ts-cloud-embrace-starburst-connection-reference.adoc, /data-integrate/embrace/embrace-starburst-reference.adoc
:linkattrs:
:page-layout: default-cloud
:experimental:
:connection: Starburst

You need specific information to establish a seamless and secure connection.
The following fields are required, except where noted.

Connection name:: Enter a new {connection} connection name.
Connection description:: Provide a short description of the connection. _(Optional)_
Host::
Enter the host name or IP address.
+
Example;; `192.168.1.1`
Port:: Enter the port number associated with the {connection} database.
User:: Enter the {connection} account username.
Password:: Enter the {connection} account password. _(Optional)_
Database:: Specify the database associated with the account. _(Optional)_
OAuth Client ID:: Enter the client id of the OAuth application created in the identity provider.
OAuth client secret:: Enter the client secret of the OAuth application created in the identity provider.
Auth Url:: Enter the Auth URL associated with the OAuth app in your identity provider.
Access Token Url:: Enter the Access Token Url associated with the OAuth app in your identity provider.
