= Connection reference for {connection}
:last_updated: 1/25/2025
:page-aliases: /data-integrate/embrace/embrace-redshift-reference.adoc, /admin/ts-cloud/ts-cloud-embrace-redshift-connection-reference.adoc
:linkattrs:
:experimental:
:connection: Redshift

You need specific information to establish a seamless and secure connection.
The following fields are required, except where noted.

Connection name:: Enter a name for your {connection} connection.
Connection description:: Provide a short description of the connection.
Host:: Enter the host name associated with the database. If you used an xref:connections-redshift-private-link.adoc[AWS PrivateLink between your Redshift data warehouse and the ThoughtSpot Cloud tenant], use the PrivateLink Endpoint DNS name provided by {support-url}. For example, `vpce-12345a9c7e43959d-xxo2u2xx.vpce-svc-037b1f73d3de3a5b4.us-west-2.vpce.amazonaws.com`.
Port:: Enter the port number associated with the database.
User:: Enter the {connection} account username.
Password:: Enter the {connection} account password.
Database:: Specify the database associated with the account.
(IAM only) Dbuser:: Specify the db user associated with the account.
(IAM only) Access Key:: Specify the access key associated with the account.
(IAM only) Secret Key:: Specify the secret key associated with the account.
(OAuth only) OAuth Client ID:: Specify the OAuth client ID associated with the account.
(OAuth only) OAuth Client Secret:: Specify the OAuth client secret associated with the account.
(OAuth only) Auth Url:: Specify the Auth Url associated with the account.
(OAuth only) Access token Url:: Specify the Access token URL associated with the account.
(OAuth only) Role ARN:: Specify the role ARN associated with the account.
(OAuth only) DbGroups:: Specify the DbGroups associated with the account.
