= Enabling a Redshift-managed PrivateLink between ThoughtSpot Cloud and your {connection} data warehouse
:experimental:
:last_updated: 2/21/2024
:linkattrs:
:page-layout: default-cloud
:description: Learn how to deploy a Redshift-managed PrivateLink between your Redshift data warehouse and the ThoughtSpot Cloud tenant.
:connection: Redshift
:jira: SCAL-192459


Learn how to deploy a Redshift-managed PrivateLink, also known as Redshift-managed VPC endpoint, between your {connection} data warehouse and the ThoughtSpot Cloud tenant.


To deploy a Redshift-managed PrivateLink, you must work with {support-url} and follow the procedure in this article.

[#prerequisites]
== Prerequisites

* You must have a {connection} cluster
* The ThoughtSpot cluster must be in the same AWS region as your {connection} cluster
* For more prerequisites, see link:https://docs.aws.amazon.com/redshift/latest/mgmt/managing-cluster-cross-vpc.html#managing-cluster-cross-vpc-considerations[Considerations when using Redshift-managed VPC endpoints]

[#enable]
== Enable a Redshift-managed PrivateLink for {connection}

To deploy a Redshift-managed PrivateLink between your {connection} data warehouse and the ThoughtSpot Cloud tenant, follow these steps.


When configuring Redshift-managed PrivateLink, you must <<create,create>> a Support ticket requesting ThoughtSpot’s AWS account ID and AWS VPC ID, <<configure,configure>> your AWS account to allow ThoughtSpot access to your cluster, <<receive,receive>> the DNS endpoint for Connections from ThoughtSpot, and <<connect,connect>> to your cluster using the Endpoint DNS name.

[#create]
=== Step 1: Create a Support ticket

Create a Support ticket requesting ThoughtSpot’s AWS account ID and the AWS VPC ID for your cluster at {support-url}. Note that you need a Support Portal login to file a ticket. If you do not have one, contact your ThoughtSpot liaison.

[#configure]
=== Step 2: Configure your AWS account

To configure your AWS account to allow ThoughtSpot access, follow these steps: link:https://docs.aws.amazon.com/redshift/latest/mgmt/managing-cluster-cross-vpc.html#managing-cluster-cross-vpc-console[Granting access to a cluster].

Note that you only need to perform the steps to grant access to a cluster, not the ones described in "Creating a Redshift-managed VPC endpoint".

Once you have granted access to the ThoughtSpot AWS account, provide your AWS account ID and Redshift cluster identifier to {support-url}. You can use the same Support ticket filed in <<create,step 1>>.

[#receive]
=== Step 3: Receive the DNS endpoint

Using the same Support ticket, request the DNS endpoint for your cluster.

[#connect]
=== Step 4: Connect to your Redshift account in ThoughtSpot

Create a connection in your ThoughtSpot cluster to your Redshift account, entering the DNS endpoint in the "host" field. For more information, see xref:connections-redshift-add.adoc[Create a Redshift connection].


'''
> **Related information**
>
> * xref:connections-redshift-add.adoc[Add a {connection} connection]
> * xref:connections-redshift-edit.adoc[Edit a {connection} connection]
> * xref:connections-redshift-remap.adoc[Remap a {connection} connection]
> * xref:connections-redshift-external-tables.adoc[Query external tables from your {connection} connection]
> * xref:connections-redshift-delete-table.adoc[Delete a table from a {connection} connection]
> * xref:connections-redshift-delete-table-dependencies.adoc[Delete a table with dependent objects]
> * xref:connections-redshift-delete.adoc[Delete a {connection} connection]
> * xref:connections-redshift-best.adoc[Best Practices for {connection} connections]
> * xref:connections-redshift-reference.adoc[Connection reference for {connection}]
> * xref:connections-redshift-azure-ad-oauth.adoc[]
> * xref:connections-redshift-partner.adoc[Redshift Partner Connect overview]
> * xref:connections-query-tags.adoc#tag-redshift[ThoughtSpot query tags in Redshift]
> * xref:connections-redshift-passthrough.adoc[]
