= Delete a table with dependent objects from a {connection} connection
:last_updated: 11/05/2021
:linkattrs:
:experimental:
:page-layout: default-cloud
:connection: Denodo
:description: To delete a table with dependent objects from a Denodo connection, first delete the dependent objects.

If you attempt to delete a table with dependent objects, ThoughtSpot blocks the operation until you resolve the dependencies. See xref:connections-denodo-delete-table.adoc[].

include::partial$connection-delete-table-dependencies.adoc[]

'''
> **Related information**
>
> * xref:connections-denodo-add.adoc[Add a {connection} connection]
> * xref:connections-denodo-edit.adoc[Edit a {connection} connection]
> * xref:connections-denodo-remap.adoc[Remap a {connection} connection]
> * xref:connections-denodo-delete-table.adoc[Delete a table from a {connection} connection]
> * xref:connections-denodo-delete.adoc[Delete a {connection} connection]
> * xref:connections-denodo-private-link.adoc[]
> * xref:connections-denodo-oauth.adoc[Configure OAuth for a {connection} connection]
> * xref:connections-denodo-reference.adoc[Connection reference for {connection}]
> * xref:connections-denodo-passthrough.adoc[]