= Passthrough functions for {connection}
:last_updated: 4/7/2023
:linkattrs:
:experimental:
:page-layout: default-cloud
:page-aliases:
:connection: Teradata
:description: Passthrough functions allow you to send SQL expressions directly to {connection} without being interpreted by ThoughtSpot.

Passthrough functions allow you to send SQL expressions directly to {connection} without being interpreted by ThoughtSpot.
If you have custom database functions that ThoughtSpot doesn't support, you can use these new passthrough functions in the ThoughtSpot Formula Assistant to call your custom functions.

A passthrough function serves as a wrapper around the specific {connection} SQL function.
To use a specific {connection} SQL function, match the data type that the function returns with the Connections passthrough function that returns that data type.

For details on all supported passthrough functions, see xref:formula-reference.adoc#passthrough-functions[Connections passthrough functions].

For details on {connection} functions, see {connection}'s https://docs.teradata.com/r/Teradata-VantageTM-SQL-Functions-Expressions-and-Predicates/March-2019[SQL Reference^].

'''
> **Related information**
>
> * xref:connections-teradata-add.adoc[Add a {connection} connection]
> * xref:connections-teradata-edit.adoc[Edit a {connection} connection]
> * xref:connections-teradata-remap.adoc[Remap a {connection} connection]
> * xref:connections-teradata-delete-table.adoc[Delete a table from a {connection} connection]
> * xref:connections-teradata-delete-table-dependencies.adoc[Delete a table with dependent objects]
> * xref:connections-teradata-delete.adoc[Delete a {connection} connection]
> * xref:connections-teradata-private-link.adoc[]
> * xref:connections-teradata-reference.adoc[{connection} connection reference]