= Deactivate an {connection} connection
:page-last_updated: Mar 23, 2026
:author: Naomi
:linkattrs:
:experimental:
:connection: Azure Synapse
:jira: SCAL-279448
:description: You can now deactivate Connections directly within ThoughtSpot, suspending all activity on that Connection until it's re-enabled.

include::partial$connection-deactivate.adoc[]

'''
> **Related information**
>
> * xref:connections-synapse-add.adoc[]
> * xref:connections-synapse-edit.adoc[Edit an {connection} connection]
> * xref:connections-synapse-remap.adoc[Remap an {connection} connection]
> * xref:connections-synapse-delete-table.adoc[Delete a table from an {connection} connection]
> * xref:connections-synapse-delete-table-dependencies.adoc[Delete a table with dependent objects]
> * xref:connections-synapse-delete.adoc[Delete an {connection} connection]
> * xref:connections-synapse-oauth.adoc[Configure OAuth]
> * xref:connections-synapse-reference.adoc[Connection reference for {connection}]
> * xref:connections-query-tags.adoc#tag-synapse[ThoughtSpot query tags in Synapse]
> * xref:connections-synapse-passthrough.adoc[]