= Connection reference for {connection}
:last_updated: 9/21/2020
:page-aliases: /admin/ts-cloud/ts-cloud-embrace-synapse-connection-reference.adoc, /data-integrate/embrace/embrace-synapse-reference.adoc
:linkattrs:
:experimental:
:page-layout: default-cloud
:connection: Synapse

You need specific information to establish a seamless and secure connection.
The following fields are required.

Connection name:: Enter a new {connection} connection name.
Connection description:: Provide a short description of the connection. _(Optional)_
Host:: Enter the host name associated with the {connection} database.
Port:: Enter the port number associated with the {connection} database.
(Service Account only) User:: Enter the {connection} account username.
(Service Account only) Password:: Enter the {connection} account password.
Database:: Specify the database associated with the account.
(OAuth only) OAuth Client ID:: Specify the OAuth client ID associated with the account.
(OAuth only) OAuth Client Secret:: Specify the OAuth client secret associated with the account.
(OAuth only) Scope:: Enter this for your Synapse OAuth connection:
+
[source]
--
offline_access openid https://sql.azuresynapse.net/.default
--
+
Scope value is the same for all Synapse OAuth connections.
(OAuth only) Auth Url:: Specify the auth URL associated with the account.
(OAuth only) Access token Url:: Specify the access token URL associated with the account.
