= {connection} connection reference
:last_updated: 06/18/2020
:linkattrs:
:experimental:
:page-layout: default-cloud
:page-aliases: /admin/ts-cloud/ts-cloud-embrace-teradata-connection-reference.adoc, /7.0.0.mar.sw/data-integrate/embrace/embrace-teradata-reference.adoc
:description: Learn about the fields used to create a Teradata connection using ThoughtSpot Connections.
:connection: Teradata

Here is a list of the fields of a {connection} connection in ThoughtSpot Connections.
You need specific information to establish a seamless and secure connection.
All fields are required, except where noted.

Connection name:: Enter a new {connection} connection name.
Connection description:: Provide a short description of the connection. _(Optional)_
Host:: Enter the host associated with the {connection} database. If you used an xref:connections-adw-private-link.adoc[AWS PrivateLink between your {connection} data warehouse and the ThoughtSpot Cloud tenant], use the PrivateLink Endpoint DNS name provided by {support-url}. For example, `vpce-12345a9c7e43959d-xxo2u2xx.vpce-svc-037b1f73d3de3a5b4.us-west-2.vpce.amazonaws.com`.
User:: Enter the user account associated with the {connection} database.
Use application proxy user:: Select this if you want to use the Teradata query-banding feature with the user.
IMPORTANT: The user must be configured as an application proxy user in Teradata.
Password:: Enter the password associated with the user account of the {connection} database.
Database:: Enter the database name associated with the {connection} database. _(Optional)_

'''
> **Related information**
>
> * xref:connections-teradata-add.adoc[Add a {connection} connection]
> * xref:connections-teradata-edit.adoc[Edit a {connection} connection]
> * xref:connections-teradata-remap.adoc[Remap a {connection} connection]
> * xref:connections-teradata-delete-table.adoc[Delete a table from a {connection} connection]
> * xref:connections-teradata-delete-table-dependencies.adoc[Delete a table with dependent objects]
> * xref:connections-teradata-delete.adoc[Delete a {connection} connection]
> * xref:connections-teradata-private-link.adoc[]
> * xref:connections-teradata-passthrough.adoc[]