= Connection reference for {connection}
:last_updated: 5/11/2020
:page-aliases:
:linkattrs:
:page-layout: default-cloud
:experimental:
:connection: PostgreSQL
:description: Learn the specific information needed to establish a secure connection to PostgreSQL.

You need specific information to establish a seamless and secure connection.
The following fields are required, except where noted.

Connection name:: Enter a new {connection} connection name.
Connection description:: Provide a short description of the connection. _(Optional)_
Host::
Enter the host name or IP address.
+
Example;; `192.168.1.1`
Port:: Enter the port number associated with the {connection} database.
User:: Enter the {connection} account username.
Password:: Enter the {connection} account password. _(Optional)_
Database:: Specify the database associated with the account. _(Optional)_

'''
> **Related information**
>
> * xref:connections-postgresql-add.adoc[Add a {connection} connection]
> * xref:connections-postgresql-edit.adoc[Edit a {connection} connection]
> * xref:connections-postgresql-remap.adoc[Remap a {connection} connection]
> * xref:connections-postgresql-delete-table.adoc[Delete a table from a {connection} connection]
> * xref:connections-postgresql-delete-table-dependencies.adoc[Delete a table with dependent objects]
> * xref:connections-postgresql-delete.adoc[Delete a {connection} connection]
> * xref:connections-postgresql-private-link.adoc[]
