= Connection reference for {connection}
:last_updated: 6/7/2022
:linkattrs:
:page-layout: default-cloud
:page-aliases: /admin/ts-cloud/ts-cloud-embrace-databricks-connection-reference.adoc, /data-integrate/embrace/undefined/
:experimental:
:connection: Databricks
:description: Learn the specific information needed to establish a secure connection to Databricks.
:jira: SCAL-136661, SCAL-203358, SCAL-214983

You need specific information to establish a seamless and secure connection.
The following fields are required, except where noted.

If your {connection} is hosted on Microsoft Azure, see <<databricks-azure,{connection} on Microsoft Azure connection reference>>.

NOTE: Databricks-managed passwords will reach end of life on July 10, 2024. You will no longer be able to use Databricks-managed passwords to authenticate to Databricks, known as basic authentication, after July 10, 2024. You can log in using xref:connections-databricks-oauth.adoc[OAuth] or xref:connections-databricks-reference.adoc#service-account[Service Account].

Connection name:: Enter a new {connection} connection name.
Connection description:: Provide a short description of the connection. _(Optional)_
[#databricks-reference-host]
Host:: Enter the {connection} server host name without the protocol. You can find this in the connection details of your SQL warehouse. For more information, see link:https://docs.databricks.com/en/integrations/compute-details.html[Get connection details for a Databricks compute resource].
Example;; *example.cloud.databricks.com*
HTTP Path:: Enter the {connection} HTTP path. You can find this in the connection details of your SQL warehouse. For more information, see link:https://community.thoughtspot.com/customers/s/article/Where-is-the-http-path-for-my-Databricks-compute-resource[Where is the http path for my Databricks compute resource] or link:https://docs.databricks.com/en/integrations/compute-details.html[Get connection details for a Databricks compute resource].
Service account::
User::: Email address associated with your {connection} account. Username and password authentication is known as Databricks basic authentication; it is possible only when single sign-on is disabled.
+
When using a link:https://docs.databricks.com/en/integrations/jdbc/authentication.html#databricks-personal-access-token[Personal Access Token] as a password, enter the User as 'token'.
Password::: Specify the password of the {connection} account. You can also use your '`personal access token`' generated in {connection}. For more information, see link:https://docs.microsoft.com/en-us/azure/databricks/dev-tools/api/latest/authentication#--generate-a-personal-access-token[Generate a personal access token^].
link:https://docs.databricks.com/en/integrations/enable-disable-oauth.html#enable-custom-app-ui[OAuth]::
xref:connections-databricks-oauth.adoc[OAuth Client ID]::: Specify the OAuth client ID.
OAuth Client Secret::: Specify the OAuth client secret.
Scope::: Specify the scope.
Auth Url::: Specify the auth url.
Access token Url::: Specify the access token url.
Catalog:: Specify the catalog. _(Optional)_
Example;; sample_db

[#databricks-azure]
== {connection} on Microsoft Azure connection reference

Connection name:: Enter a new {connection} connection name.
Connection description:: Provide a short description of the connection. _(Optional)_
Host:: Enter the {connection} server hostname.  For more information, see https://docs.microsoft.com/en-us/azure/databricks/integrations/bi/jdbc-odbc-bi#get-server-hostname-port-http-path-and-jdbc-url[Get server hostname, port, HTTP path, and JDBC URL^].
Example;; *abc-1234567890123456.78.azuredatabricks.net*
HTTP Path:: Enter the Databricks HTTP path.  For more information, see https://docs.microsoft.com/en-us/azure/databricks/integrations/bi/jdbc-odbc-bi#get-server-hostname-port-http-path-and-jdbc-url[Get server hostname, port, HTTP path, and JDBC URL^].
Example;; *sql/protocolv1/o/1234567890123456/7890-123456-abc789*
[#service-account]
Service account::
User::: Enter your login email to your Azure account.
+
When using a link:https://docs.databricks.com/en/integrations/jdbc/authentication.html#databricks-personal-access-token[Personal Access Token] as a password, enter the User as 'Token'.
Password::: Enter your '`personal access token`' generated in {connection}.
This is not the password for your Azure account. For more information, see link:https://docs.microsoft.com/en-us/azure/databricks/dev-tools/api/latest/authentication#--generate-a-personal-access-token[Generate a personal access token^].
OAuth::
xref:connections-databricks-oauth.adoc[OAuth Client ID]::: Specify the OAuth client ID.
OAuth Client Secret::: Specify the OAuth client secret.
Scope::: Specify the scope.
Auth Url::: Specify the auth url.
Access token Url::: Specify the access token url.
Catalog:: Specify the catalog. _(Optional)_
Example;; sample_db

== Limitation
ThoughtSpot does not support link:https://docs.databricks.com/en/integrations/jdbc/authentication.html#oauth-machine-to-machine-m2m-authentication[OAuth machine-to-machine authentication], also known as Service Principal and OAuth authentication.

'''
> **Related information**
>
> * xref:connections-databricks-add.adoc[Add a {connection} connection]
> * xref:connections-databricks-edit.adoc[Edit a {connection} connection]
> * xref:connections-databricks-remap.adoc[Remap a {connection} connection]
> * xref:connections-databricks-delete-table.adoc[Delete a table from a {connection} connection]
> * xref:connections-databricks-delete-table-dependencies.adoc[Delete a table with dependent objects]
> * xref:connections-databricks-delete.adoc[Delete a {connection} connection]
> * xref:connections-databricks-oauth.adoc[Configure OAuth for a {connection} connection]
> * xref:connections-databricks-oauth-aad.adoc[]
> * xref:connections-databricks-private-link.adoc[]
> * xref:connections-databricks-passthrough.adoc[]
> * xref:connections-databricks-best.adoc[]