= Categorizing Connections
:last_updated: 10/31/2024
:author: Naomi
:experimental:
:linkattrs:
:page-layout: default-cloud-early-access
:description: Categorize Connections by type, rather than date added to ThoughtSpot.
:jira: SCAL-219033

By default, when you create a Connection, ThoughtSpot orders the connection tiles by date added to our platform. If you would rather see the Connections ordered by type, contact your administrator to enable the *Categorize connectors* feature from the Early Access panel.

When the *Categorize connectors* feature is enabled, the connection types are categorized into the following categories:

Cloud data platforms:: xref:connections-redshift.adoc[Amazon Redshift], xref:connections-synapse.adoc[Azure Synapse], xref:connections-databricks.adoc[Databricks], xref:connections-gbq.adoc[Google BigQuery], and xref:connections-snowflake.adoc[Snowflake].

Query engines:: xref:connections-amazon-athena.adoc[Amazon Athena], xref:connections-dremio.adoc[Dremio], xref:connections-presto.adoc[Presto], xref:connections-starburst.adoc[Starburst], and xref:connections-trino.adoc[Trino].

Databases:: xref:connections-amazon-aurora-mysql.adoc[Amazon Aurora MySQL], xref:connections-amazon-aurora-postgresql.adoc[Amazon Aurora PostgreSQL], xref:connections-amazon-rds-mysql.adoc[Amazon RDS MySQL], xref:connections-amazon-rds-postgresql.adoc[Amazon RDS PostgreSQL], xref:connections-denodo.adoc[Denodo], xref:connections-google-alloydb-postgresql.adoc[Google AlloyDB for PostgreSQL], xref:connections-google-cloud-sql-mysql.adoc[Google Cloud SQL for MySQL], xref:connections-google-cloud-sql-postgresql.adoc[Google Cloud SQL for PostgreSQL], xref:connections-google-cloud-sql-sql-server.adoc[Google Cloud SQL for SQL Server], xref:connections-mysql.adoc[MySQL], xref:connections-adw.adoc[Oracle], xref:connections-postgresql.adoc[PostgreSQL], xref:connections-hana.adoc[SAP HANA], xref:connections-singlestore.adoc[SingleStore], xref:connections-sql-server.adoc[SQL Server], and xref:connections-teradata.adoc[Teradata].

Others:: xref:connections-mode.adoc[Mode].