= Deactivate a {connection} connection
:page-last_updated: Mar 23, 2026
:author: Naomi
:linkattrs:
:page-layout: default-cloud
:experimental:
:connection: Databricks
:jira: SCAL-279448
:description: You can now deactivate Connections directly within ThoughtSpot, suspending all activity on that Connection until it's re-enabled.

include::partial$connection-deactivate.adoc[]


'''
> **Related information**
>
> * xref:connections-databricks-add.adoc[]
> * xref:connections-databricks-edit.adoc[Edit a {connection} connection]
> * xref:connections-databricks-csv-upload.adoc[]
> * xref:connections-databricks-remap.adoc[Remap a {connection} connection]
> * xref:connections-databricks-delete-table.adoc[Delete a table from a {connection} connection]
> * xref:connections-databricks-delete-table-dependencies.adoc[Delete a table with dependent objects]
> * xref:connections-databricks-delete.adoc[Delete a {connection} connection]
> * xref:connections-databricks-oauth.adoc[Configure OAuth for a {connection} connection]
> * xref:connections-databricks-oauth-aad.adoc[]
> * xref:connections-databricks-oauth-service.adoc[]
> * xref:connections-databricks-csv-upload-config.adoc[]
> * xref:connections-databricks-unity-catalog.adoc[]
> * xref:connections-databricks-private-link.adoc[]
> * xref:connections-databricks-reference.adoc[Connection reference for {connection}]
> * xref:connections-databricks-passthrough.adoc[]
> * xref:connections-databricks-best.adoc[]