= OpenVPN for Azure {connection} and Snowflake on Azure
:last_updated: 1/24/2022
:linkattrs:
:experimental:
:page-layout: default-cloud
:page-aliases: /admin/ts-cloud/openvpn-synapse.adoc
:description: Learn how to configure secure access from ThoughtSpot Cloud to your data in Azure Synapse or Snowflake on Azure, through your OpenVPN server.
:connection: Synapse

Learn how to configure secure access from ThoughtSpot Cloud to your data in Azure {connection} or Snowflake on Azure, through your OpenVPN server.

Make your data in Azure {connection} or Snowflake on Azure even more secure by connecting to your OpenVPN server.
This feature is also available for data in xref:connections-gbq-open-vpn.adoc[Google BigQuery].

NOTE: VPN is not supported for ThoughtSpot on GCP.

Your company may have a policy that prohibits exposing your cloud data to the internet.
In this case, you can set up a VPN connection between your ThoughtSpot Cloud cluster and your data warehouse, either Google BigQuery, Snowflake, or Azure {connection}.

ThoughtSpot supports the following 3 OpenVPN servers:

* https://openvpn.net/community-downloads/[OpenVPN Community Edition]
* https://docs.microsoft.com/en-us/azure/vpn-gateway/vpn-gateway-howto-openvpn-clients[Azure VPN]
* https://docs.aws.amazon.com/vpn/latest/clientvpn-admin/what-is.html[AWS Client VPN]

== Set up an OpenVPN connection

You must perform several preliminary steps before asking {support-url} to connect your OpenVPN server to your ThoughtSpot cluster(s).

. Set up an *OpenVPN server*, on OpenVPN Community Edition, Azure VPN, or AWS Client VPN.
. Create an *OpenVPN configuration file* in `.ovpn` form.
The configuration file must be _one_ file, in `.ovpn` form.
To generate your configuration file, refer to these articles:

* https://openvpn.net/community-resources/creating-configuration-files-for-server-and-clients/[OpenVPN Community Edition]
* https://docs.microsoft.com/en-us/azure/vpn-gateway/vpn-gateway-howto-openvpn-clients[Azure VPN]
* https://docs.aws.amazon.com/vpn/latest/clientvpn-admin/what-is.html[AWS Client VPN]

== Exchange OpenVPN and ThoughtSpot information with ThoughtSpot Support

. Send the OpenVPN configuration file to {support-url}.
. After ThoughtSpot configures the VPN on your ThoughtSpot Cloud cluster(s), ask them to send you the *private DNS name*.

== Connect your ThoughtSpot cluster(s) to your data warehouse

xref:connections-synapse.adoc[Configure Connections for {connection}] or xref:connections-snowflake.adoc[for Snowflake], using the private DNS name from {support-url}.
