= Connection reference for {connection}
:last_updated: 1/25/2025
:page-aliases: /data-integrate/embrace/embrace-redshift-reference.adoc, /admin/ts-cloud/ts-cloud-embrace-redshift-connection-reference.adoc
:linkattrs:
:experimental:
:connection: Redshift
:description: Learn the specific information needed to establish a secure connection to Amazon Redshift.
:jira: SCAL-203353

You need specific information to establish a seamless and secure connection.
The following fields are required, except where noted.

Connection name:: Enter a name for your {connection} connection.
Connection description:: Provide a short description of the connection.
Host:: Enter the host name associated with the database. If you used an xref:connections-redshift-private-link.adoc[AWS PrivateLink between your Redshift data warehouse and the ThoughtSpot Cloud tenant], use the PrivateLink Endpoint DNS name provided by {support-url}. For example, `vpce-12345a9c7e43959d-xxo2u2xx.vpce-svc-037b1f73d3de3a5b4.us-west-2.vpce.amazonaws.com`.
Port:: Enter the port number associated with the database.
User:: Enter the {connection} account username.
+
NOTE: This user must have at least *read* access to the *SVV_TABLE_INFO* table.
Password:: Enter the {connection} account password.
Database:: Specify the database associated with the account.
(IAM only) Dbuser:: Specify the db user associated with the account.
(IAM only) Access Key:: Specify the access key associated with the account.
(IAM only) Secret Key:: Specify the secret key associated with the account.
(OAuth only) OAuth Client ID:: Enter the OAuth client ID associated with the {connection} database.
(OAuth only) OAuth Client Secret::  Enter the OAuth client secret associated with the {connection} database.
(OAuth only) Scope:: Scope maps to a role in your Snowflake database.
+
For OAuth with Azure AD provider, it should be similar to `\https://<APPLICATION_ID_URI>/session:role:developer offline_access openid`.
For more information, see: xref:connections-redshift-azure-ad-oauth.adoc#step-8[part 1, step 8] in Configure Azure AD external OAuth for a {connection} connection.
(OAuth only) Auth Url:: ThoughtSpot performs an "Authorization Code" grant type flow to get the access token. Get the authorization endpoint for the respective identity provider from its console.
+
For Azure AD, it can be obtained from the Azure portal by navigating to Azure Active Directory resource. It should be similar to *\https://login.microsoftonline.com/<tenant_id>/oauth2/v2.0/authorize*.
(OAuth only) Access token Url:: (External OAuth) Enter the Access Token Url associated with your external identity provider.
+
For Azure AD, it can be obtained from the Azure portal by navigating to Azure Active Directory resource. It should be similar to *\https://login.microsoftonline.com/<tenant_id>/oauth2/v2.0/token*.


////
(OAuth only) OAuth Client ID:: Specify the OAuth client ID associated with the account.
(OAuth only) OAuth Client Secret:: Specify the OAuth client secret associated with the account.
(OAuth only) Auth Url:: Specify the Auth Url associated with the account.
(OAuth only) Access token Url:: Specify the Access token URL associated with the account.
(OAuth only) Role ARN:: Specify the role ARN associated with the account.
(OAuth only) DbGroups:: Specify the DbGroups associated with the account.
////

'''
> **Related information**
>
> * xref:connections-redshift-add.adoc[Add a {connection} connection]
> * xref:connections-redshift-edit.adoc[Edit a {connection} connection]
> * xref:connections-redshift-remap.adoc[Remap a {connection} connection]
> * xref:connections-redshift-external-tables.adoc[Query external tables from your {connection} connection]
> * xref:connections-redshift-delete-table.adoc[Delete a table from a {connection} connection]
> * xref:connections-redshift-delete-table-dependencies.adoc[Delete a table with dependent objects]
> * xref:connections-redshift-delete.adoc[Delete a {connection} connection]
> * xref:connections-redshift-best.adoc[Best practices for {connection} connections]
> * xref:connections-redshift-azure-ad-oauth.adoc[]
> * xref:connections-redshift-private-link.adoc[]
> * xref:connections-redshift-partner.adoc[Redshift Partner Connect overview]
> * xref:connections-query-tags.adoc#tag-redshift[ThoughtSpot query tags in Redshift]
> * xref:connections-redshift-passthrough.adoc[]