= Delete a {connection} connection
:last_updated: 6/7/2022
:linkattrs:
:experimental:
:page-layout: default-cloud
:page-aliases: /admin/ts-cloud/ts-cloud-embrace-databricks-delete-connection.adoc
:connection: Databricks
:description: Learn how to delete a Databricks connection.
:jira: SCAL-203358

include::partial$connection-delete.adoc[]

'''
> **Related information**
>
> * xref:connections-databricks-add.adoc[Add a {connection} connection]
> * xref:connections-databricks-edit.adoc[Edit a {connection} connection]
> * xref:connections-databricks-remap.adoc[Remap a {connection} connection]
> * xref:connections-databricks-delete-table.adoc[Delete a table from a {connection} connection]
> * xref:connections-databricks-delete-table-dependencies.adoc[Delete a table with dependent objects]
> * xref:connections-databricks-oauth.adoc[Configure OAuth for a {connection} connection]
> * xref:connections-databricks-oauth-aad.adoc[]
> * xref:connections-databricks-private-link.adoc[]
> * xref:connections-databricks-reference.adoc[Connection reference for {connection}]
> * xref:connections-databricks-passthrough.adoc[]
> * xref:connections-databricks-best.adoc[]