= Delete a table from a {connection} connection
:last_updated: 3/5/2024
:linkattrs:
:page-layout: default-cloud-early-access
:page-aliases:
:experimental:
:connection: Mode
:description: Learn how to delete a table from a Mode connection.
:jira: SCAL-176923, SCAL-201296

Whenever you try to remove a table in a connection, ThoughtSpot checks for dependencies and shows a list of dependent objects.
You can select the listed objects to delete them or remove the dependency.
Then you can remove the table.

NOTE: Mode connector is in Early Access and off by default. To enable it, contact your administrator.

To delete a table from a {connection} connection:

. Select *Data* in the top navigation bar.
. Open the *Connections* tab in the left navigation bar.
. Select the name of the connection that contains the table you want to delete.
. Find the table you want to delete in the list, and select the checkbox next to its name.
. Click *Delete*, and then select *Delete* again to confirm.
+
If you attempt to delete a table with dependent objects, the operation is blocked.
A _Cannot delete_ window appears, with a list of links to dependent objects.
See xref:connections-mode-delete-table-dependencies.adoc[Deleting a table with dependent objects].

See the xref:connections-mode-reference.adoc[Connection reference] for details of connection parameters.

'''
> **Related information**
>
> * xref:connections-mode-add.adoc[Add a connection]
> * xref:connections-mode-edit.adoc[Edit a connection]
> * xref:connections-mode-remap.adoc[Remap a {connection} connection]
> * xref:connections-mode-delete-table-dependencies.adoc[Delete a table with dependent objects]
> * xref:connections-mode-delete.adoc[Delete a {connection} connection]
> * xref:connections-mode-reference.adoc[{connection} connection reference]
> * xref:connections-mode-passthrough.adoc[]
