= Connection reference for Oracle
:last_updated: 08/09/2021
:experimental:
:linkattrs:
:page-partial:
:page-layout: default-cloud
:page-aliases: /data-integrate/embrace/embrace-adw-reference.adoc
:connection: Oracle

Learn about the fields used to connect to Oracle databases. You need specific information to establish a seamless and secure connection. All fields are required, except where noted.

[#connection-name]
Connection name::  Enter a new Oracle connection name.
[#connection-description]
Connection description::
Provide a short description of the connection.
_(Optional)_
[#host]
Host::  Enter the host of the Oracle database server.
[#port]
Port::  Enter the port of the Oracle database server.
[#instance-name]
Instance Name::  Enter the instance name Oracle database to connect. (Also known as SID).
[#user]
User::  Enter the Oracle account username.
[#password]
Password::  Enter the Oracle account password.
[#net-service-name]
Net Service Name:: Specify the net service name of the Oracle account.
+
Requires `tnsnames.ora` in the zip file uploaded through the Wallet file option.
[#wallet-file]
Wallet file:: Upload the wallet file containing your Oracle client credentials. If you do not have a wallet file, contact your Oracle administrator.
[#schema]
Schema:: Specify the schema associated with the database.
(_Optional_).
