= Query external tables from your {connection} connection
:last_updated: 8/3/2022
:linkattrs:
:experimental:
:page-layout: default-cloud
:connection: Redshift
:description: ThoughtSpot supports querying external tables stored in external data stores, such as Amazon S3 or Google Cloud Storage, via your cloud data warehouse.

include::partial$external-table-intro.adoc[]

[#supported-stores-formats]
== Supported data stores and file formats

ThoughtSpot supports any data stores or file formats that {connection} supports. Refer to the {connection}
documentation for more information: https://docs.aws.amazon.com/redshift/latest/dg/r_CREATE_EXTERNAL_TABLE.html[Create external table^].

== Querying your external tables

To query your external tables in ThoughtSpot, follow these steps:

. Ensure that {connection} supports your data store(s) and file format(s). Refer to <<supported-stores-formats,Supported data stores and file formats>>.

. Create the external table(s) in {connection}. For assistance, refer to the {connection} documentation.

. Create your {connection} connection, if you have not already done so. When selecting tables, select the external tables you want to query, as well as any other tables. Refer to xref:connections-redshift-add.adoc[].
+
NOTE: Ensure that your external tables are in the same database and schema as the database and schema specified in your {connection} connection.

. xref:search-data.adoc[Search] the data from your external table.

'''
> **Related information**
>
> * xref:connections-redshift-add.adoc[Add a {connection} connection]
> * xref:connections-redshift-edit.adoc[Edit a {connection} connection]
> * xref:connections-redshift-remap.adoc[Remap a {connection} connection]
> * xref:connections-redshift-delete-table.adoc[Delete a table from a {connection} connection]
> * xref:connections-redshift-delete-table-dependencies.adoc[Delete a table with dependent objects]
> * xref:connections-redshift-delete.adoc[Delete a {connection} connection]
> * xref:connections-redshift-best.adoc[Best Practices for {connection} connections]
> * xref:connections-redshift-private-link.adoc[]
> * xref:connections-redshift-reference.adoc[Connection reference for {connection}]
> * xref:connections-redshift-partner.adoc[Redshift Partner Connect overview]
> * xref:connections-query-tags.adoc#tag-redshift[ThoughtSpot query tags in Redshift]
> * xref:connections-redshift-passthrough.adoc[]