= {connection} connection reference
:last_updated: 01/31/2025
:linkattrs:
:page-partial:
:page-layout: default-cloud-early-access
:connection: ClickHouse
:description: Learn the specific information needed to establish a secure connection with your ClickHouse database.
:jira: SCAL-239421

You need very specific information to establish a seamless and secure connection with your {connection} database.

Here is a list of fields for {connection} connections.

You require all these fields, except the ones we marked _(Optional)_.

[#connection-name]
Connection name::
Enter the name for the new connection.
[#connection-description]
Connection description::
_(Optional)_ Provide a short description of the connection.
[#host]
Host::
Enter the {connection} server host name.
[#http-path]
Port::
{connection} server port.
[#user]
User::
Enter the user associated with the {connection} database.
[#password]
Password::
Enter the password of the user associated with the {connection} database.

'''
> **Related information**
>
> * xref:connections-clickhouse-add.adoc[]
> * xref:connections-clickhouse-edit.adoc[]
> * xref:connections-clickhouse-remap.adoc[]
> * xref:connections-clickhouse-delete-table.adoc[]
> * xref:connections-clickhouse-delete-table-dependencies.adoc[]
> * xref:connections-clickhouse-delete.adoc[]
