= Delete a table from a {connection} connection
:last_updated: 8/11/2020
:linkattrs:
:page-layout: default-cloud
:page-aliases: /admin/ts-cloud/ts-cloud-embrace-gbq-delete-table.adoc
:experimental:
:connection: BigQuery
:description: Learn how to delete a table from a BigQuery connection.

Whenever you try to remove a table in a connection, ThoughtSpot checks for dependencies and shows a list of dependent objects.
You can select the listed objects to delete them or remove the dependency.
Then you can remove the table.

To delete a table from a {connection} connection:

. Select *Data* in the top navigation bar.
. Open the *Connections* tab.
. Select the name of the connection that contains the table you want to delete.
. Find the table you want to delete in the list, and select the checkbox next to its name.
. Click *Delete*, and then select *Delete* again to confirm.

If you attempt to delete a table with dependent objects, the operation is blocked.
A _Cannot delete_ window appears, with a list of links to dependent objects.
See xref:connections-gbq-delete-table-dependencies.adoc[Delete a table with dependent objects].

See the xref:connections-gbq-reference.adoc[Connection reference] for details of connection parameters.

'''
> **Related information**
>
> * xref:connections-gbq-prerequisites.adoc[{connection} prerequisites]
> * xref:connections-gbq-add.adoc[Add a {connection} connection]
> * xref:connections-gbq-edit.adoc[Edit a {connection} connection]
> * xref:connections-gbq-remap.adoc[Remap a {connection} connection]
> * xref:connections-gbq-external-tables.adoc[Query external tables from your {connection} connection]
> * xref:connections-gbq-delete-table-dependencies.adoc[Delete a table with dependent objects]
> * xref:connections-gbq-delete.adoc[Delete a {connection} connection]
> * xref:connections-gbq-oauth.adoc[Configure OAuth for a {connection} connection]
> * xref:connections-gbq-reference.adoc[Connection reference for {connection}]