= Passthrough functions for Google {connection}
:last_updated: 2/2/2022
:linkattrs:
:experimental:
:page-layout: default-cloud
:page-aliases:
:connection: BigQuery
:description: Passthrough functions allow you to send SQL expressions directly to Google BigQuery without being interpreted by ThoughtSpot.

Passthrough functions allow you to send SQL expressions directly to Google {connection} without being interpreted by ThoughtSpot.
If you have custom database functions that ThoughtSpot doesn't support, you can use these new passthrough functions in the ThoughtSpot Formula Assistant to call your custom functions.

A passthrough function serves as a wrapper around the specific Google {connection} SQL function.
To use a specific Google {connection} SQL function, match the data type that the function returns with the Connections passthrough function that returns that data type.

For details on all supported passthrough functions, see xref:formula-reference.adoc#passthrough-functions[Connections passthrough functions].

For details on Google {connection} functions, see Google {connection}'s https://cloud.google.com/bigquery/docs/reference/standard-sql/lexical[SQL Reference^].

'''
> **Related information**
>
> * xref:connections-gbq-prerequisites.adoc[{connection} prerequisites]
> * xref:connections-gbq-ingress.adoc[]
> * xref:connections-gbq-add.adoc[Add a {connection} connection]
> * xref:connections-gbq-edit.adoc[Edit a {connection} connection]
> * xref:connections-gbq-remap.adoc[Remap a {connection} connection]
> * xref:connections-gbq-external-tables.adoc[Query external tables from your {connection} connection]
> * xref:connections-gbq-delete-table.adoc[Delete a table from a {connection} connection]
> * xref:connections-gbq-delete-table-dependencies.adoc[Delete a table with dependent objects]
> * xref:connections-gbq-delete.adoc[Delete a {connection} connection]
> * xref:connections-gbq-reference.adoc[Connection reference for {connection}]
> * xref:connections-query-tags.adoc#tag-gbq[ThoughtSpot query tags in Google BigQuery]
