= Enabling an AWS PrivateLink between ThoughtSpot Cloud and your {connection} data warehouse
:experimental:
:last_updated: 5/3/2023
:linkattrs:
:page-layout: default-cloud
:page-aliases: /admin/ts-cloud/private-link-redshift.adoc
:description: Learn how to deploy an AWS PrivateLink between your Redshift data warehouse and the ThoughtSpot Cloud tenant.
:connection: Redshift

Learn how to deploy an AWS PrivateLink between your {connection} data warehouse and the ThoughtSpot Cloud tenant.

NOTE: AWS PrivateLink is only available to Enterprise Edition users.

include::partial$private-link-intro.adoc[]

This article details how to enable a PrivateLink for *{connection}*;
to enable it for other data warehouses, refer to:

* xref:connections-databricks-private-link.adoc[Databricks PrivateLink]
* xref:connections-denodo-private-link.adoc[Denodo PrivateLink]
* xref:connections-dremio-private-link.adoc[Dremio PrivateLink]
* xref:connections-adw-private-link.adoc[Oracle PrivateLink]
* xref:connections-postgresql-private-link.adoc[PostgreSQL PrivateLink]
* xref:connections-hana-private-link.adoc[SAP HANA PrivateLink]
* xref:connections-snowflake-private-link.adoc[Snowflake PrivateLink]
* xref:connections-sql-server-private-link.adoc[SQL Server PrivateLink]
* xref:connections-starburst-private-link.adoc[Starburst PrivateLink]
* xref:connections-teradata-private-link.adoc[Teradata PrivateLink]

NOTE: You can enable a maximum of five PrivateLinks in your environment.

To deploy an AWS PrivateLink, you must work with {support-url} and follow the procedure in this article.

[#prerequisites]
== Prerequisites

* You must have a {connection} account
* The ThoughtSpot cluster must be in the same AWS region as your {connection} account
* You must obtain the ThoughtSpot AWS Account Amazon Resource Name (ARN) from {support-url}. This is required for step 6 of <<configure-aws,Configure the Endpoint Service>>. For example: `arn:aws:iam::999999999999:root`

== Enable an AWS PrivateLink for {connection}

To deploy an AWS PrivateLink between your {connection} data warehouse and the ThoughtSpot Cloud tenant, follow these steps.

. <<configure-aws,Configure the Endpoint Service in your AWS Console>>
. <<exchange-information,Exchange AWS and ThoughtSpot information with ThoughtSpot Support>>
. <<accept-request,Accept the PrivateLink Request>>
. <<embrace,Configure Connections>>

[#configure-aws]
=== Configure the Endpoint Service in your AWS Console

After completing the <<prerequisites,prerequisites>>, you must configure the Endpoint Service.

. Sign in to the AWS Console.
. Create a Network Load Balancer (NLB) routing TCP traffic on port 5439 to your {connection} database. Ensure that "Cross Zone Load Balancing" is enabled in the load balancer.
. Navigate to menu:AWS VPC Console[Endpoint Services > Create Endpoint Service].
. Select the {connection} NLB you created in step 2.
. Select *Require Acceptance for Endpoint*.
. Select menu:Endpoint Service[Whitelist principles > Add principles to whitelist].
Add the ThoughtSpot AWS Account Amazon Resource Name (ARN) that you obtained from {support-url} in the <<prerequisites,prerequisites>>.
. Select *Endpoint Service*.
. Write down the values for:

* *Service name*: for example, _com.amazonaws.vpce.us-west-2.vpce-svc-0123456789abcdef_
* *Availability zones*: for example, _us-west-2a (usw2-az1)_
+
You must provide the service name and availability zones to {support-url}.

[#exchange-information]
=== Exchange AWS and ThoughtSpot information with ThoughtSpot Support

. Send the *Service name* and *Availability zones* you gathered in step 8 of <<configure-aws,Configure the Endpoint Service in your AWS Console>> to {support-url}.
. After ThoughtSpot Support configures the AWS PrivateLink in ThoughtSpot, ask them to send you the PrivateLink Endpoint DNS name.

[#accept-request]
=== Accept the PrivateLink Request

. Navigate to menu:VPC[Endpoint Services].
. Select the Endpoint Service you created in <<configure-aws,Configure the Endpoint Service in your AWS Console>>.
. Select *Endpoint Connections*.
. Select the connection from the ThoughtSpot AWS Account.
Its status should be _Pending Acceptance_.
. Select menu:Actions[Accept endpoint connection request].

[#embrace]
=== Configure Connections

xref:connections-redshift.adoc[Configure Connections for {connection}], using the PrivateLink Endpoint DNS name from {support-url} for the *Host* field. For example, `vpce-12345a9c7e43959d-xxo2u2xx.vpce-svc-037b1f73d3de3a5b4.us-west-2.vpce.amazonaws.com`.


'''
> **Related information**
>
> * xref:connections-redshift-add.adoc[Add a {connection} connection]
> * xref:connections-redshift-edit.adoc[Edit a {connection} connection]
> * xref:connections-redshift-remap.adoc[Remap a {connection} connection]
> * xref:connections-redshift-external-tables.adoc[Query external tables from your {connection} connection]
> * xref:connections-redshift-delete-table.adoc[Delete a table from a {connection} connection]
> * xref:connections-redshift-delete-table-dependencies.adoc[Delete a table with dependent objects]
> * xref:connections-redshift-delete.adoc[Delete a {connection} connection]
> * xref:connections-redshift-best.adoc[Best Practices for {connection} connections]
> * xref:connections-redshift-reference.adoc[Connection reference for {connection}]
> * xref:connections-redshift-azure-ad-oauth.adoc[]
> * xref:connections-redshift-partner.adoc[Redshift Partner Connect overview]
> * xref:connections-query-tags.adoc#tag-redshift[ThoughtSpot query tags in Redshift]
> * xref:connections-redshift-passthrough.adoc[]
