= Query external tables from your {connection} connection
:last_updated: 8/3/2022
:linkattrs:
:experimental:
:page-layout: default-cloud
:connection: Snowflake
:description: After you create external tables in your Snowflake environment and connect to Snowflake, you can query them like any other table in your connection.

include::partial$external-table-intro.adoc[]

[#supported-stores-formats]
== Supported data stores and file formats

ThoughtSpot supports any data stores or file formats that {connection} supports. Refer to the {connection}
documentation for more information: https://docs.snowflake.com/en/user-guide/tables-external-intro.html[Introduction to External Tables^].

== Querying your external tables

To query your external tables in ThoughtSpot, follow these steps:

. Ensure that {connection} supports your data store(s) and file format(s). Refer to <<supported-stores-formats,Supported data stores and file formats>>.

. Create the external table(s) in {connection}. For assistance, refer to the {connection} documentation.

. Create your {connection} connection, if you have not already done so. When selecting tables, select the external tables you want to query, as well as any other tables. Refer to xref:connections-snowflake-add.adoc[].
+
NOTE: Ensure that your external tables are in the same database and schema as the database and schema specified in your {connection} connection.

. xref:search-data.adoc[Search] the data from your external table.

'''
> **Related information**
>
> * xref:connections-snowflake-add.adoc[Add a {connection} connection]
> * xref:connections-snowflake-edit.adoc[Edit a {connection} connection]
> * xref:connections-snowflake-remap.adoc[Remap a {connection} connection]
> * xref:connections-snowflake-delete-table.adoc[Delete a table from a {connection} connection]
> * xref:connections-snowflake-delete-table-dependencies.adoc[Delete a table with dependent objects]
> * xref:connections-snowflake-delete.adoc[Delete a {connection} connection]
> * xref:connections-snowflake-oauth.adoc[Configure OAuth]
> * xref:connections-snowflake-azure-ad-oauth.adoc[Configure Azure AD OAuth]
> * xref:connections-snowflake-best.adoc[Best practices for {connection} connections]
> * xref:connections-snowflake-private-link.adoc[]
> * xref:connections-snowflake-psc.adoc[]
> * xref:connections-snowflake-reference.adoc[Connection reference for {connection}]
> * xref:connections-query-tags.adoc#tag-snowflake[ThoughtSpot query tags in Snowflake]
> * xref:connections-snowflake-passthrough.adoc[]