= Connection reference for {connection}
:last_updated: 9/20/2023
:page-aliases:
:linkattrs:
:page-layout: default-cloud
:experimental:
:connection: Amazon Athena
:description: Learn the specific information needed to establish a secure connection to Amazon Athena.

You need specific information to establish a seamless and secure connection.
The following fields are required, except where noted.

Connection name:: Enter a new {connection} connection name.
Connection description:: Provide a short description of the connection. _(Optional)_
Region:: Provide the AWS region of the Athena instance you want to connect to.
Access key:: Specify the access key associated with the AWS account.
Secret key:: Specify the secret key associated with the AWS account.
S3 output location:: Specify the path of the Amazon S3 location where you want to store the query results.
Datasource:: Specify the Amazon Athena data source you want to connect to. _(Optional)_
Endpoint VPC:: If you are using a private link connection, specify the VPC endpoint. _(Optional)_

'''
> **Related information**
>
> * xref:connections-amazon-athena-add.adoc[Add an {connection} connection]
> * xref:connections-amazon-athena-edit.adoc[Edit an {connection} connection]
> * xref:connections-amazon-athena-remap.adoc[Remap an {connection} connection]
> * xref:connections-amazon-athena-delete-table.adoc[Delete a table from an {connection} connection]
> * xref:connections-amazon-athena-delete-table-dependencies.adoc[Delete a table with dependent objects]
> * xref:connections-amazon-athena-delete.adoc[Delete an {connection} connection]
> * xref:connections-amazon-athena-passthrough.adoc[]