////
:doctype: book

////include::7.1@software:ROOT:connections-snowflake-delete-table.adoc[]
////
= Delete a table from a {connection} connection
:last_updated: 8/11/2020
:experimental:
:linkattrs:
:page-layout: default-cloud
:page-partial:
:connection: Snowflake
:description: Learn how to delete a table from a Snowflake connection.

Whenever you try to remove a table in a connection, ThoughtSpot checks for dependencies and shows a list of dependent objects.
You can select the listed objects to delete them or remove the dependency.
Then you can remove the table.

To delete a table from a {connection} connection:

. Select *Data* in the top navigation bar.
. Open the *Connections* tab in the left navigation bar.
. Select the name of the connection that contains the table you want to delete.
. Find the table you want to delete in the list, and select the checkbox next to its name.
. Click *Delete*, and then select *Delete* again to confirm.

If you attempt to delete a table with dependent objects, the operation is blocked.
A _Cannot delete_ window appears, with a list of links to dependent objects.
See xref:connections-snowflake-delete-table-dependencies.adoc[Delete a table with dependent objects].

See the xref:connections-snowflake-reference.adoc[Connection reference] for details of connection parameters.

'''
> **Related information**
>
> * xref:connections-snowflake-add.adoc[Add a {connection} connection]
> * xref:connections-snowflake-edit.adoc[Edit a {connection} connection]
> * xref:connections-snowflake-remap.adoc[Remap a {connection} connection]
> * xref:connections-snowflake-external-tables.adoc[Query external tables from your {connection} connection]
> * xref:connections-snowflake-delete-table-dependencies.adoc[Delete a table with dependent objects]
> * xref:connections-snowflake-delete.adoc[Delete a {connection} connection]
> * xref:connections-snowflake-oauth.adoc[Configure OAuth]
> * xref:connections-snowflake-azure-ad-oauth.adoc[Configure Azure AD OAuth]
> * xref:connections-snowflake-best.adoc[Best practices for {connection} connections]
> * xref:connections-snowflake-private-link.adoc[]
> * xref:connections-snowflake-psc.adoc[]
> * xref:connections-snowflake-reference.adoc[Connection reference for {connection}]
> * xref:connections-query-tags.adoc#tag-snowflake[ThoughtSpot query tags in Snowflake]
> * xref:connections-snowflake-passthrough.adoc[]
////