= Deactivate an {connection} connection
:page-last_updated: Mar 23, 2026
:author: Naomi
:linkattrs:
:experimental:
:connection: Amazon RDS PostgreSQL
:jira: SCAL-279448
:description: You can now deactivate Connections directly within ThoughtSpot, suspending all activity on that Connection until it's re-enabled.

include::partial$connection-deactivate.adoc[]

'''
> **Related information**
>
> * xref:connections-amazon-rds-postgresql-add.adoc[]
> * xref:connections-amazon-rds-postgresql-edit.adoc[Edit an {connection} connection]
> * xref:connections-amazon-rds-postgresql-remap.adoc[Remap an {connection} connection]
> * xref:connections-amazon-rds-postgresql-delete-table.adoc[Delete a table from an {connection} connection]
> * xref:connections-amazon-rds-postgresql-delete-table-dependencies.adoc[Delete a table with dependent objects]
> * xref:connections-amazon-rds-postgresql-delete.adoc[Delete an {connection} connection]
> * xref:connections-amazon-rds-postgresql-private-link.adoc[Enable a PrivateLink]
> * xref:connections-amazon-rds-postgresql-reference.adoc[Connection reference for {connection}]
> * xref:connections-amazon-rds-postgresql-passthrough.adoc[]