= CSV upload to Answers
:last_updated: 8/28/2024
:linkattrs:
:page-layout: default-cloud-beta
:experimental:
:connection: Snowflake
:description: You can upload CSV data directly to an Answer, as long as the Answer was created based on data from a Snowflake connection.

You can now upload data related to your Search and append it directly to an Answer. This allows you to add data columns to an Answer without navigating away from your current analysis. To enable this feature, currently enabled only on Snowflake, contact {support-url}.

== Prerequisites

User role and permissions:: You must have the *can-upload-data* role. This role grants permission to upload CSV files.

Saved Answer requirements:: You must have access to a saved Answer that is built on a Worksheet. This Worksheet's underlying connection must support CSV uploads.

Answer and Worksheet sharing:: The saved Answer must be shared with the user who is uploading the CSV file. You should have *edit access* to both the saved Answer and the associated Worksheet to ensure you can manage and interact with the uploaded data.

Connection setup:: Only Snowflake connections are currently supported for CSV uploads.
You must have *write access* to the Snowflake connection where you intend to upload the CSV file. This access is necessary to create new tables within Snowflake.

CSV upload location:: The CSV file will be uploaded to the same Snowflake connection where the saved Answers are created.


== Upload data to an Answer


To append data from a CSV file to an Answer, follow these steps:

. Open an Answer created on a Snowflake connection. In the top left corner of the side panel, click *+Add* and select *Custom data*.

. The *Upload a CSV file* page appears. Click *Browse files* and select your CSV file, or drag and drop it into the field.

.. Choose whether column names are *defined in header* or *not defined*.
.. Choose the appropriate field separator: *comma*, *semicolon*, *pipe*, *space*, or *tab*.

. Click *Next*.

. The *Review and upload .CSV file* page appears.

. [Optional] Click the edit icon next to the CSV file name to update the name within ThoughtSpot.

. [Optional] Click the edit icon next to the column names to update the names within ThoughtSpot.

. [Optional] Click the data type below each column name to select a new type from the dropdown.

. Click *Next*.

. The *Link your .CSV file to the Answer* page appears.

. Under *Answer columns*, click *Choose a column* and select a column on which to join the CSV file.

. Under *CSV columns*, click *Choose a column*, and select the column to join with the Answer column.

. [Optional] Click *+ Add new columns* to add multiple join columns. Sample data from the joined columns appears at the bottom of the page.

. Click *Next*.

. The *Add columns from your .CSV file* page appears. Click the checkbox next to each column you want to add to your Search and click *Done*.

. Your Answer appears with the new columns grayed out in the side menu. Click the *X* in the search bar to clear the Search, and you can remake the Answer with the new columns included.
