= {connection} connection reference
:last_updated: 06/18/2020
:linkattrs:
:experimental:
:page-layout: default-cloud
:page-aliases: /7.0.0.mar.sw/data-integrate/embrace/embrace-hana-reference.adoc, /admin/ts-cloud/ts-cloud-embrace-hana-connection-reference.adoc
:description: Learn about the fields used to create an SAP HANA connection using ThoughtSpot Connections.
:connection: SAP HANA

You need specific information to establish a seamless and secure connection.
All fields are required, except where noted.

Connection name:: Enter a new {connection} connection name.
Connection description:: Provide a short description of the connection._(Optional)_
Host and port:: Enter the host followed by a colon and the port number of the {connection} database.
+
*Example*: If your host is `192.168.1.1`, and your port is `8080` you would enter `192.168.1.1:8080`.
+
If you used an xref:connections-adw-private-link.adoc[AWS PrivateLink between your {connection} data warehouse and the ThoughtSpot Cloud tenant], use the PrivateLink Endpoint DNS name provided by {support-url}. For example, `vpce-12345a9c7e43959d-xxo2u2xx.vpce-svc-037b1f73d3de3a5b4.us-west-2.vpce.amazonaws.com`.
User:: Enter the user associated with the {connection} database.
Password:: Enter the password associated with the user of the {connection} database.
Database:: Enter the database associated with the {connection} database.

'''
> **Related information**
>
> * xref:connections-hana-add.adoc[Add a connection]
> * xref:connections-hana-edit.adoc[Edit a connection]
> * xref:connections-hana-remap.adoc[Remap a {connection} connection]
> * xref:connections-hana-delete-table.adoc[Delete a table from a {connection} connection]
> * xref:connections-hana-delete-table-dependencies.adoc[Delete a table with dependent objects]
> * xref:connections-hana-delete.adoc[Delete a {connection} connection]
> * xref:connections-hana-private-link.adoc[]
> * xref:connections-query-tags.adoc#tag-saphana[ThoughtSpot query tags in SAP HANA]
> * xref:connections-hana-passthrough.adoc[]