= Delete a table from a {connection} connection
:last_updated: 8/11/2020
:linkattrs:
:page-layout: default-cloud
:page-aliases: /admin/ts-cloud/ts-cloud-embrace-redshift-delete-table.adoc
:experimental:
:connection: Redshift
:description: Learn how to delete a table from a Redshift connection.

Whenever you try to remove a table in a connection, ThoughtSpot checks for dependencies and shows a list of dependent objects.
You can select the listed objects to delete them or remove the dependency.
Then you can remove the table.

To delete a table from a {connection} connection:

. Select *Data* in the top navigation bar.
. Open the *Connections* tab in the left navigation bar.
. Select the name of the connection that contains the table you want to delete.

. Find the table you want to delete in the list, and select the checkbox next to its name.
. Click *Delete*, and then select *Delete* again to confirm.

If you attempt to delete a table with dependent objects, the operation is blocked.
A _Cannot delete_ window appears, with a list of links to dependent objects.
See xref:connections-redshift-delete-table-dependencies.adoc[Delete a table with dependent objects].

See the xref:connections-redshift-reference.adoc[Connection reference] for details of connection parameters.

'''
> **Related information**
>
> * xref:connections-redshift-add.adoc[Add a {connection} connection]
> * xref:connections-redshift-edit.adoc[Edit a {connection} connection]
> * xref:connections-redshift-remap.adoc[Remap a {connection} connection]
> * xref:connections-redshift-external-tables.adoc[Query external tables from your {connection} connection]
> * xref:connections-redshift-delete-table-dependencies.adoc[Delete a table with dependent objects]
> * xref:connections-redshift-delete.adoc[Delete a {connection} connection]
> * xref:connections-redshift-oauth.adoc[Configure OAuth]
> * xref:connections-redshift-best.adoc[Best Practices for {connection} connections]
> * xref:connections-redshift-private-link.adoc[]
> * xref:connections-redshift-reference.adoc[Connection reference for {connection}]
> * xref:connections-query-tags.adoc#tag-redshift[ThoughtSpot query tags in Redshift]