= Deactivate an {connection} connection
:page-last_updated: Mar 23, 2026
:author: Naomi
:linkattrs:
:experimental:
:page-layout: default-cloud
:connection: Amazon Redshift
:jira: SCAL-279448
:description: You can now deactivate Connections directly within ThoughtSpot, suspending all activity on that Connection until it's re-enabled.

include::partial$connection-deactivate.adoc[]

'''
> **Related information**
>
> * xref:connections-redshift-add.adoc[]
> * xref:connections-redshift-best.adoc[]
> * xref:connections-redshift-edit.adoc[Edit a {connection} connection]
> * xref:connections-redshift-remap.adoc[Remap a {connection} connection]
> * xref:connections-redshift-delete-table.adoc[Delete a table from a {connection} connection]
> * xref:connections-redshift-delete-table-dependencies.adoc[Delete a table with dependencies from a {connection} connection]
> * xref:connections-redshift-reference.adoc[{connection} connection reference]
> * xref:connections-redshift-delete.adoc[Delete a {connection} connection]
> * xref:connections-redshift-external-tables.adoc[]
> * xref:connections-redshift-private-link.adoc[]
> * xref:connections-redshift-partner.adoc[Redshift Partner Connect overview]
> * xref:connections-redshift-aws-idc-oauth.adoc[]
> * xref:connections-redshift-azure-ad-oauth.adoc[]
> * xref:connections-query-tags.adoc#tag-redshift[ThoughtSpot query tags in Redshift]
> * xref:connections-redshift-passthrough.adoc[]
// > * xref:connections-aws-secrets.adoc[Configure AWS Secrets Manager] //
// > * xref:data-load.adoc[Load and manage data]
> * xref:security.adoc[Data and object security]
