= Query external tables from your {connection} connection
:last_updated: 8/3/2022
:linkattrs:
:experimental:
:page-layout: default-cloud
:connection: Redshift

include::partial$external-table-intro.adoc[]

[#supported-stores-formats]
== Supported data stores and file formats

ThoughtSpot supports any data stores or file formats that {connection} supports. Refer to the {connection}
documentation for more information: https://docs.aws.amazon.com/redshift/latest/dg/r_CREATE_EXTERNAL_TABLE.html[Create external table^].

== Querying your external tables

To query your external tables in ThoughtSpot, follow these steps:

. Ensure that {connection} supports your data store(s) and file format(s). Refer to <<supported-stores-formats,Supported data stores and file formats>>.

. Create the external table(s) in {connection}. For assistance, refer to the {connection} documentation.

. Create your {connection} connection, if you have not already done so. When selecting tables, select the external tables you want to query, as well as any other tables. Refer to xref:connections-redshift-add.adoc[].
+
NOTE: Ensure that your external tables are in the same database and schema as the database and schema specified in your {connection} connection.

. xref:search-data.adoc[Search] the data from your external table.
