= Delete a table from an {connection} connection
:last_updated: 4/21/2023
:author: Naomi
:linkattrs:
:page-layout: default-cloud
:page-aliases:
:experimental:
:connection: Amazon RDS PostgreSQL
:description: Learn how to delete a table from an Amazon RDS PostgreSQL connection.

Whenever you try to remove a table in a connection, ThoughtSpot checks for dependencies and shows a list of dependent objects.
You can select the listed objects to delete them or remove the dependency.
Then you can remove the table.

To delete a table from an {connection} connection:

. Select *Data* in the top navigation bar.
. Open the *Connections* tab in the left navigation bar.
. Select the name of the connection that contains the table you want to delete.
. Find the table you want to delete in the list, and select the checkbox next to its name.
. Click *Delete*, and then select *Delete* again to confirm.

If you attempt to delete a table with dependent objects, the operation is blocked.
A _Cannot delete_ window appears, with a list of links to dependent objects.
See xref:connections-amazon-rds-postgresql-delete-table-dependencies.adoc[Delete a table with dependent objects].

See the xref:connections-amazon-rds-postgresql-reference.adoc[Connection reference] for details of connection parameters.

'''
> **Related information**
>
> * xref:connections-amazon-rds-postgresql-add.adoc[Add an {connection} connection]
> * xref:connections-amazon-rds-postgresql-edit.adoc[Edit an {connection} connection]
> * xref:connections-amazon-rds-postgresql-remap.adoc[Remap an {connection} connection]
> * xref:connections-amazon-rds-postgresql-delete-table-dependencies.adoc[Delete a table with dependent objects]
> * xref:connections-amazon-rds-postgresql-delete.adoc[Delete an {connection} connection]
> * xref:connections-amazon-rds-postgresql-private-link.adoc[Enable a PrivateLink]
> * xref:connections-amazon-rds-postgresql-reference.adoc[Connection reference for {connection}]
> * xref:connections-amazon-rds-postgresql-passthrough.adoc[]