= Enabling an AWS PrivateLink between ThoughtSpot Cloud and your {connection} data warehouse
:last_updated: 3/16/2021
:linkattrs:
:experimental:
:page-layout: default-cloud
:page-aliases: /admin/ts-cloud/private-link-snowflake.adoc
:description: Learn how to deploy an AWS PrivateLink between your Snowflake data warehouse and the ThoughtSpot Cloud tenant.
:connection: Snowflake

Your data's security is important.
To ensure a secure two-way data exchange between your cloud data warehouse and the ThoughtSpot Cloud tenant, you can use an AWS PrivateLink.
This option is currently available for your {connection} or Redshift data warehouse connections.
This article details how to enable a PrivateLink for {connection};
you can also enable it for xref:connections-redshift-private-link.adoc[Redshift].

NOTE: You can only enable one PrivateLink for each cluster.

To deploy an AWS PrivateLink, you must work with https://community.thoughtspot.com/customers/s/contactsupport[ThoughtSpot Support] and follow the procedure in this article.

[#prerequisites]
== Prerequisites

* You must have a {connection} account
* The ThoughtSpot cluster must be in the same AWS region as your {connection} account
* You must obtain the ThoughtSpot AWS Account ID from https://community.thoughtspot.com/customers/s/contactsupport[ThoughtSpot Support].
You may need a separate Account ID for staging or dev environments. This is required for step 1 of <<request-configuration,Request Snowflake PrivateLink configuration>>. For example: `999999999999`

== Enable an AWS PrivateLink for v

To deploy an AWS PrivateLink between your {connection} data warehouse and the ThoughtSpot Cloud tenant, follow these steps.

. <<request-configuration,Request {connection} PrivateLink configuration>>
. <<exchange-information,Exchange AWS and ThoughtSpot information with ThoughtSpot Support>>
. <<embrace,Configure Connections>>

[#request-configuration]
=== Request {connection} PrivateLink configuration

. Send a support request to {connection}, asking them to configure an AWS PrivateLink.
You must provide the following information:
 ** {connection} account URL
 ** ThoughtSpot AWS Account ID.
You obtained ThoughtSpot's AWS Account ID from https://community.thoughtspot.com/customers/s/contactsupport[ThoughtSpot Support] in the <<prerequisites,prerequisites>>.
You may need a separate Account ID for staging or dev environments.
. {connection} provides the following details with their response:
 ** VPC Endpoint Service Name
 ** Private DNS records required for {connection} clients

[#exchange-information]
=== Exchange AWS and ThoughtSpot information with ThoughtSpot Support

. Send the *account name* from the DNS records and the *Service name* to ThoughtSpot Support.
You gathered this information from {connection} in step 2 of <<request-configuration,Request {connection} PrivateLink configuration>>.
. After ThoughtSpot Support configures the AWS PrivateLink in ThoughtSpot, ask them to send you the PrivateLink {connection} account name.

[#embrace]
=== Configure Connections

xref:connections-snowflake.adoc[Configure Connections for {connection}], using the PrivateLink {connection} account name from ThoughtSpot Support for the *Account name* field. For example, `xyz99999.us-west-2.privatelink`.
