= Enabling a GCP Private Service Connect between ThoughtSpot Cloud and your {connection} data warehouse
:last_updated: 3/16/2021
:linkattrs:
:experimental:
:page-layout: default-cloud
:page-aliases:
:description: This guide explains how to set up Private Service Connect to enable connectivity between ThoughtSpot clusters and Snowflake within Google Cloud Platform.
:connection: Snowflake
:jira: SCAL-205490

This guide explains how to set up Private Service Connect (PSC) to enable secure and private connectivity between ThoughtSpot clusters and Snowflake within Google Cloud Platform (GCP). This setup ensures that data traffic between ThoughtSpot and Snowflake does not traverse the public internet, enhancing security and performance.

== Prerequisites

Before you begin the setup process, ensure the following conditions are met:

* Snowflake is active within your GCP project.
* Both the ThoughtSpot instance and Snowflake are located in the same GCP region.
* You must obtain the ThoughtSpot GCP Project ID from {support-url}.


== Configuration Process

To deploy a Private Service Connect between your Snowflake data warehouse and the ThoughtSpot Cloud tenant, follow these steps:

=== Step 1: Customer GCP Private Service Connect Configuration

* Follow steps 1 and 2 of the "Configuration Procedure" section in the link:https://docs.snowflake.com/en/user-guide/private-service-connect-google[Snowflake Documentation] to request PSC configuration in Snowflake.
* Save the output of the link:https://docs.snowflake.com/en/sql-reference/functions/system_get_privatelink_config[SYSTEM$GET_PRIVATELINK_CONFIG] function.

=== Step 2: Exchange information with ThoughtSpot

Send the output from the previous step to {support-url}. ThoughtSpot sends back the URL to use for Connection configuration.

=== Step 3: Connection Setup

Once the PSC is configured, xref:connections-snowflake-add.adoc[connect] your ThoughtSpot instance to your Snowflake account using the provided URL.

== Conclusion

Following this guide, you establish a secure, private connection between your ThoughtSpot cluster and Snowflake within GCP, leveraging Private Service Connect. For any further assistance or to report issues, please contact {support-url} to track and manage your request effectively.



'''
> **Related information**
>
> * xref:connections-snowflake-add.adoc[Add a {connection} connection]
> * xref:connections-snowflake-edit.adoc[Edit a {connection} connection]
> * xref:connections-snowflake-remap.adoc[Remap a {connection} connection]
> * xref:connections-snowflake-external-tables.adoc[Query external tables from your {connection} connection]
> * xref:connections-snowflake-delete-table.adoc[Delete a table from a {connection} connection]
> * xref:connections-snowflake-delete-table-dependencies.adoc[Delete a table with dependent objects]
> * xref:connections-snowflake-delete.adoc[Delete a {connection} connection]
> * xref:connections-snowflake-oauth.adoc[Configure OAuth]
> * xref:connections-snowflake-azure-ad-oauth.adoc[Configure Azure AD OAuth]
> * xref:connections-snowflake-best.adoc[Best practices for {connection} connections]
> * xref:connections-snowflake-reference.adoc[Connection reference for {connection}]
> * xref:connections-query-tags.adoc#tag-snowflake[ThoughtSpot query tags in Snowflake]
> * xref:connections-snowflake-passthrough.adoc[]