= Deactivate a {connection} connection
:page-last_updated: Mar 23, 2026
:author: Naomi
:linkattrs:
:experimental:
:connection: Amazon RDS MySQL
:jira: SCAL-279448
:description: You can now deactivate Connections directly within ThoughtSpot, suspending all activity on that Connection until it's re-enabled.

include::partial$connection-deactivate.adoc[]


'''
> **Related information**
>
> * xref:connections-amazon-rds-mysql-add.adoc[]
> * xref:connections-amazon-rds-mysql-edit.adoc[Edit an {connection} connection]
> * xref:connections-amazon-rds-mysql-remap.adoc[Remap an {connection} connection]
> * xref:connections-amazon-rds-mysql-delete-table.adoc[Delete a table from an {connection} connection]
> * xref:connections-amazon-rds-mysql-delete-table-dependencies.adoc[Delete a table with dependent objects]
> * xref:connections-amazon-rds-mysql-delete.adoc[Delete an {connection} connection]
> * xref:connections-amazon-rds-mysql-private-link.adoc[Enable a PrivateLink]
> * xref:connections-amazon-rds-mysql-reference.adoc[Connection reference for {connection}]
> * xref:connections-amazon-rds-mysql-passthrough.adoc[]