= Connection reference for {connection}
:last_updated: 11/13/2023
:page-aliases:
:linkattrs:
:page-layout: default-cloud
:experimental:
:connection: Looker
:page-aliases: connections-looker-ml-reference.adoc
:description: Learn the specific information needed to establish a secure connection to Looker Modeler.
:jira: SCAL-161198

You need specific information to establish a seamless and secure connection.
The following fields are required, except where noted.

Connection name:: Enter a new {connection} connection name.
Connection description:: Provide a short description of the connection. _(Optional)_
Host:: Enter the host name associated with the {connection} database, in the format of: `<looker_instance>/jdbc/`
+
_Example:_ https://sample-instance.dev.looker.com/jdbc/
Password:: Enter the password associated with the {connection} database.
User:: Enter the user name associated with the {connection} database.
Service account:: Enter the service account JSON key associated with the {connection} database. To generate the key, refer to xref:connections-gbq-prerequisites.adoc#service-account[Google {connection} prerequisites].
OAuth Client ID:: Enter the OAuth client ID associated with the {connection}.
Scope:: Enter the scope associated with the {connection} database.
Auth Url:: Enter the auth url associated with the {connection} database, in the format of: `<looker_instance>/auth`.
+
_Example:_ https://sample-instance.dev.looker.com/auth
Access token Url:: Enter the access token url associated with the {connection} database, in the format of `<looker_instance>/api/token`.
+
_Example:_ https://experiment-thoughtspot.dev.looker.com/api/token
Database:: *Leave this field blank*. Database name associated with the {connection} database.
'''
> **Related information**
>
> * xref:connections-looker-add.adoc[Add a {connection} connection]
> * xref:connections-looker-edit.adoc[Edit a {connection} connection]
> * xref:connections-looker-remap.adoc[Remap a {connection} connection]
> * xref:connections-looker-delete-table.adoc[Delete a table from a {connection} connection]
> * xref:connections-looker-delete-table-dependencies.adoc[Delete a table with dependent objects]
> * xref:connections-looker-delete.adoc[Delete a {connection} connection]
> * xref:connections-looker-passthrough.adoc[]