= {connection} connection reference
:last_updated: 03/5/2024
:linkattrs:
:experimental:
:page-layout: default-cloud-early-access
:page-aliases:
:description: Learn about the fields used to create a Mode connection using ThoughtSpot Connections.
:connection: Mode
:jira: SCAL-176923, SCAL-201296, SCAL-209201

You need specific information to establish a seamless and secure connection.
All fields are required, except where noted.

NOTE: Mode connector is in Early Access and off by default. To enable it, contact your administrator.

Connection name:: Enter a new {connection} connection name.
Connection description:: Provide a short description of the connection._(Optional)_
Host:: Enter `production-datawarehouse.mode.com`.
Port:: Enter `8444`.
User:: Enter the user associated with the {connection} database. This will be the API token you created in Mode.
Password:: Enter the password associated with the user of the {connection} database. This will be the secret you created in Mode.


'''
> **Related information**
>
> * xref:connections-mode-add.adoc[Add a connection]
> * xref:connections-mode-edit.adoc[Edit a connection]
> * xref:connections-mode-remap.adoc[Remap a {connection} connection]
> * xref:connections-mode-delete-table.adoc[Delete a table from a {connection} connection]
> * xref:connections-mode-delete-table-dependencies.adoc[Delete a table with dependent objects]
> * xref:connections-mode-delete.adoc[Delete a {connection} connection]
> * xref:connections-mode-passthrough.adoc[]
