= Delete a table from an {connection} connection
:last_updated: 1/20/2021
:linkattrs:
:experimental:
:page-layout: default-cloud
:page-aliases: /admin/ts-cloud/ts-cloud-embrace-adw-delete-table.adoc
:connection: Oracle
:description: Learn how to delete a table from an Oracle connection.


Whenever you try to remove a table in a connection, ThoughtSpot checks for dependencies and shows a list of dependent objects.
You can select the listed objects to delete them or remove the dependency.
Then you can remove the table.

To delete a table from an {connection} connection:

. Select *Data* in the top navigation bar.
. Open the *Connections* tab.
. Select the name of the connection that contains the table you want to delete.
. Find the table you want to delete in the list, and select the checkbox next to its name.
. Click *Delete*, and then select *Delete* again to confirm.

If you attempt to delete a table with dependent objects, the operation is blocked.
A _Cannot delete_ window appears, with a list of links to dependent objects.
See xref:connections-adw-delete-table-dependencies.adoc[Delete a table with dependent objects].

See the xref:connections-adw-reference.adoc[Connection reference] for details of connection parameters.

'''
> **Related information**
>
> * xref:connections-adw-add.adoc[]
> * xref:connections-adw-edit.adoc[]
> * xref:connections-adw-remap.adoc[]
> * xref:connections-adw-delete-table-dependencies.adoc[]
> * xref:connections-adw-reference.adoc[]
> * xref:connections-adw-delete.adoc[]
> * xref:connections-adw-private-link.adoc[]
> * xref:connections-adw-passthrough.adoc[]