= Delete a table from a {connection} connection
:last_updated: 4/21/2023
:author: Naomi
:linkattrs:
:page-aliases:
:experimental:
:connection: SingleStore
:description: Learn how to delete a table from a SingleStore connection.
:jira: SCAL-164909

Whenever you try to remove a table in a connection, ThoughtSpot checks for dependencies and shows a list of dependent objects.
You can select the listed objects to delete them or remove the dependency.
Then you can remove the table.

To delete a table from a {connection} connection:

. Select *Data* in the top navigation bar.
. Open the *Connections* tab in the left navigation bar.
. Select the name of the connection that contains the table you want to delete.
. Find the table you want to delete in the list, and select the checkbox next to its name.
. Click *Delete*, and then select *Delete* again to confirm.

If you attempt to delete a table with dependent objects, the operation is blocked.
A _Cannot delete_ window appears, with a list of links to dependent objects.
See xref:connections-singlestore-delete-table-dependencies.adoc[Delete a table with dependent objects].

See the xref:connections-singlestore-reference.adoc[Connection reference] for details of connection parameters.

'''
> **Related information**
>
> * xref:connections-singlestore-add.adoc[Add a {connection} connection]
> * xref:connections-singlestore-edit.adoc[Edit a {connection} connection]
> * xref:connections-singlestore-remap.adoc[Remap a {connection} connection]
> * xref:connections-singlestore-delete-table-dependencies.adoc[Delete a table with dependent objects]
> * xref:connections-singlestore-delete.adoc[Delete a {connection} connection]
> * xref:connections-singlestore-reference.adoc[Connection reference for {connection}]
> * xref:connections-singlestore-passthrough.adoc[]