= Connection reference for {connection}
:page-last_updated: 05/05/2026
:linkattrs:
:experimental:
:page-layout: default-cloud
:page-aliases:
:connection: Iomete
:description: Learn the specific information needed to establish a secure connection to your Iomete database.
:jira: SCAL-297520

You need specific information to establish a seamless and secure connection.
The following fields are required, except where noted.

Connection name:: Enter a new {connection} connection name.
Connection description:: Provide a short description of the connection. _(Optional)_
Host:: Enter the host associated with the {connection} database.
Port:: Enter the port information.
Compute Cluster:: Enter the Compute Cluster.
Data Plane:: Enter the Data Plane associated with the {connection} database. _(Optional)_
User:: Enter the user name associated with the {connection} database.
Password:: Enter the password.

'''
> **Related information**
>
> * xref:connections-iomete-add.adoc[Add an {connection} connection]
> * xref:connections-iomete-edit.adoc[Edit an {connection} connection]
> * xref:connections-iomete-remap.adoc[Remap an {connection} connection]
> * xref:connections-iomete-delete-table.adoc[Delete a table from an {connection} connection]
> * xref:connections-iomete-delete-table-dependencies.adoc[Delete a table with dependent objects]
> * xref:connections-iomete-delete.adoc[Delete an {connection} connection]
> * xref:connections-iomete-deactivate.adoc[]
