= Deactivate a {connection} connection
:page-last_updated: Mar 23, 2026
:author: Naomi
:linkattrs:
:page-layout: default-cloud
:experimental:
:connection: Google BigQuery
:jira: SCAL-279448
:description: You can now deactivate Connections directly within ThoughtSpot, suspending all activity on that Connection until it's re-enabled.

include::partial$connection-deactivate.adoc[]


'''
> **Related information**
>
> * xref:connections-gbq-add.adoc[]
> * xref:connections-gbq-prerequisites.adoc[{connection} prerequisites]
> * xref:connections-gbq-ingress.adoc[]
> * xref:connections-gbq-edit.adoc[Edit a {connection} connection]
> * xref:connections-gbq-remap.adoc[Remap a {connection} connection]
> * xref:connections-gbq-external-tables.adoc[Query external tables from your {connection} connection]
> * xref:connections-gbq-delete-table.adoc[Delete a table from a {connection} connection]
> * xref:connections-gbq-delete-table-dependencies.adoc[Delete a table with dependent objects]
> * xref:connections-gbq-delete.adoc[Delete a {connection} connection]
> * xref:connections-gbq-oauth.adoc[Configure OAuth for a {connection} connection]
> * xref:connections-gbq-reference.adoc[Connection reference for {connection}]
> * xref:connections-gbq-passthrough.adoc[]