= Delete a table from a {connection} connection
:last_updated: 9/21/2020
:linkattrs:
:page-layout: default-cloud
:page-aliases: /admin/ts-cloud/ts-cloud-embrace-synapse-delete-table.adoc
:experimental:
:connection: Synapse
:description: Learn how to delete a table from a Synapse connection.

Whenever you try to remove a table in a connection, ThoughtSpot checks for dependencies and shows a list of dependent objects.
You can select the listed objects to delete them or remove the dependency.
Then you can remove the table.

To delete a table from a {connection} connection:

. Select *Data* in the top navigation bar.
. Select the *Connections* tab.
. Select the name of the connection that contains the table you want to delete.
. Find the table you want to delete in the list, and select the checkbox next to its name.
. Click *Delete*, and then select *Delete* again to confirm.

If you attempt to delete a table with dependent objects, the operation is blocked.
A _Cannot delete_ window appears, with a list of links to dependent objects.
See xref:connections-synapse-delete-table-dependencies.adoc[Delete a table with dependent objects].

See the xref:connections-synapse-reference.adoc[Connection reference] for details of connection parameters.

'''
> **Related information**
>
> * xref:connections-synapse-add.adoc[Add a {connection} connection]
> * xref:connections-synapse-edit.adoc[Edit a {connection} connection]
> * xref:connections-synapse-remap.adoc[Remap a {connection} connection]
> * xref:connections-synapse-delete-table-dependencies.adoc[Delete a table with dependent objects]
> * xref:connections-synapse-delete.adoc[Delete a {connection} connection]
> * xref:connections-synapse-oauth.adoc[Configure OAuth]
> * xref:connections-synapse-reference.adoc[Connection reference for {connection}]
> * xref:connections-query-tags.adoc#tag-synapse[ThoughtSpot query tags in Synapse]
> * xref:connections-synapse-passthrough.adoc[]