= Column indexing with connections that use OAuth
:author: Naomi
:last_updated: 3/23/2023
:linkattrs:
:experimental:
:page-layout: default-cloud
:description: Learn how column indexing works with connections that use OAuth authentication.

== How column indexing works when using OAuth

When using OAuth-based connections to a database, the indexing jobs always run with the OAuth credentials supplied by the ThoughtSpot user who set up the connection. As such, for indexing to be successful, the user setting up the connection needs access to a database account that is able to access all of the data in the database used in the connection.

== When indexing jobs fail for connections that use OAuth

Column indexing jobs can fail when the user credentials used for creation of the connection expire, or if the credentials supplied do not have access to some/all of the data in the database.

For example, ThoughtSpot user `admin` sets up a connection with OAuth by signing in and entering the OAuth parameters to connect to the database. When they connect, they are prompted to sign in as an OAuth user account. In this case they sign in as the database account `user1`, who will use the connection. The database shows the data that `user1` has access to the database, and that any tables added will be indexed using the credentials of `user1`. At some point later, the token for `user1` expires and the indexing jobs start to fail.

== Resolving failed indexing jobs

To resolve failed indexing jobs for a connection with OAuth, do the following:

. The ThoughtSpot user who set up the connection (in this example: `admin`), edits the connection.
+
This prompts the other user to log in to the database using OAuth.
. The user logs in to the database again using their OAuth credentials (in this example: `user1`).
+
The credentials are saved and a new token is issued and used to run the indexing jobs. Indexing jobs will now run successfully.