= Deactivate a {connection} connection
:page-last_updated: Mar 23, 2026
:author: Naomi
:linkattrs:
:experimental:
:connection: Starburst
:jira: SCAL-279448
:description: You can now deactivate Connections directly within ThoughtSpot, suspending all activity on that Connection until it's re-enabled.

include::partial$connection-deactivate.adoc[]

'''
> **Related information**
>
> * xref:connections-starburst-add.adoc[]
> * xref:connections-starburst-edit.adoc[Edit a {connection} connection]
> * xref:connections-starburst-remap.adoc[Remap a {connection} connection]
> * xref:connections-starburst-delete-table.adoc[Delete a table from a {connection} connection]
> * xref:connections-starburst-delete-table-dependencies.adoc[Delete a table with dependent objects]
> * xref:connections-starburst-delete.adoc[Delete a {connection} connection]
> * xref:connections-starburst-oauth.adoc[Configure OAuth]
> * xref:connections-starburst-private-link.adoc[]
> * xref:connections-starburst-reference.adoc[Connection reference for {connection}]
> * xref:connections-starburst-passthrough.adoc[]