= Connection reference for {connection}
:last_updated: 4/19/2023
:page-aliases:
:linkattrs:
:page-layout: default-cloud
:experimental:
:connection: Amazon Aurora MySQL
:description: Learn the specific information needed to establish a secure connection to Amazon Aurora MySQL.

You need specific information to establish a seamless and secure connection.
The following fields are required, except where noted.

Connection name:: Enter a new {connection} connection name.
Connection description:: Provide a short description of the connection. _(Optional)_
Host::
Enter the host name or IP address.
+
Example;; `192.168.1.1`
Port:: Enter the port number associated with the {connection} database.
User:: Enter the {connection} account username.
Password:: Enter the {connection} account password. _(Optional)_
Database:: Specify the database associated with the account. _(Optional)_

'''
> **Related information**
>
> * xref:connections-amazon-aurora-mysql-add.adoc[Add an {connection} connection]
> * xref:connections-amazon-aurora-mysql-edit.adoc[Edit an {connection} connection]
> * xref:connections-amazon-aurora-mysql-remap.adoc[Remap an {connection} connection]
> * xref:connections-amazon-aurora-mysql-delete-table.adoc[Delete a table from an {connection} connection]
> * xref:connections-amazon-aurora-mysql-delete-table-dependencies.adoc[Delete a table with dependent objects]
> * xref:connections-amazon-aurora-mysql-delete.adoc[Delete an {connection} connection]
> * xref:connections-amazon-aurora-mysql-private-link.adoc[Enable a PrivateLink]
> * xref:connections-amazon-aurora-mysql-passthrough.adoc[]