= Deactivate a {connection} connection
:page-last_updated: Mar 23, 2026
:author: Naomi
:linkattrs:
:experimental:
:page-layout:
:connection: Denodo
:jira: SCAL-279448
:description: You can now deactivate Connections directly within ThoughtSpot, suspending all activity on that Connection until it's re-enabled.

include::partial$connection-deactivate.adoc[]


'''
> **Related information**
>
> * xref:connections-denodo-add.adoc[]
> * xref:connections-denodo-edit.adoc[Edit a {connection} connection]
> * xref:connections-denodo-remap.adoc[Remap a {connection} connection]
> * xref:connections-denodo-delete-table.adoc[Delete a table from a {connection} connection]
> * xref:connections-denodo-delete-table-dependencies.adoc[Delete a table with dependent objects]
> * xref:connections-denodo-delete.adoc[Delete a {connection} connection]
> * xref:connections-denodo-private-link.adoc[]
> * xref:connections-denodo-oauth.adoc[Configure OAuth for a {connection} connection]
> * xref:connections-denodo-reference.adoc[Connection reference for {connection}]
> * xref:connections-denodo-passthrough.adoc[]
