////
:doctype: book

////include::7.1@software:ROOT:connections-snowflake-delete-table.adoc[]
////
= Delete a table from a Snowflake connection
:last_updated: 8/11/2020
:experimental:
:linkattrs:
:page-layout: default-cloud
:page-partial:

Whenever you try to remove a table in a connection, ThoughtSpot checks for dependencies and shows a list of dependent objects.
You can click the listed objects to delete them or remove the dependency.
Then you can remove the table.

To delete a table from a Snowflake connection:

. Click *Data* in the top navigation bar.
. Click the *Connections* tab.
. Click the name of the connection that contains the table you want to delete.
. Find the table you want to delete in the list, and check the box next to its name.
. Click *Delete*, and then click *Delete* again to confirm.

If you attempt to delete a table with dependent objects, the operation is blocked.
A _Cannot delete_ window appears, with a list of links to dependent objects.
See xref:connections-snowflake-delete-table-dependencies.adoc[Delete a table with dependent objects].

See the xref:connections-snowflake-reference.adoc[Connection reference] for details of connection parameters.
////
