= Connection reference for Snowflake
:last_updated: 12/10/2020
:linkattrs:
:experimental:
:page-layout: default-cloud
:description: Learn about the fields used to create a Snowflake connection.
:page-aliases: /admin/ts-cloud/ts-cloud-embrace-snowflake-connection-reference.adoc, /data-integrate/embrace/embrace-snowflake-reference.adoc

Here is a list of the fields of a Snowflake connection.
You need specific information to establish a seamless and secure connection.
All fields are required, except where noted.
[#connection-name]
Connection name::  Enter a new Snowflake connection name.
[#connection-description]
Connection description::
Provide a short description of the connection.
_(Optional)_
[#account-name]
Account name::
Enter the account name associated with your Snowflake connection.
The account name is part of the URL that you use to access the Snowflake UI.
It is the portion of the URL before `snowflakecomputing.com`. +
*Example*: If your URL is `+https://abcd.xyz.efg.snowflakecomputing.com+`, your account name is `abcd.xyz.efg`.

Assume that the *account name* is _xy12345_.

[width="100%",cols="20%,40%,40%" options="header"]
|====================
|
Cloud platform  | Region | Full account name
| *AWS* | US East (N. Virginia) | xy12345.us-east-1
|  | US East (Ohio) | xy12345.us-east-2.aws
|  | US West (Oregon) | xy12345
|  | Canada (Central) | xy12345.ca-central-1.aws
|  | EU (Ireland) | xy12345.eu-west-1
|  | EU (Frankfurt) | xy12345.eu-central-1
|  | Asia Pacific (Singapore) | xy12345.ap-southeast-1
|  | Asia Pacific (Sydney) | xy12345.ap-sowtheast-2
| *GCP* *_- Preview_* | us-central1 (Iowa) | xy12345.us-central1.gcp
| *Azure* | East US 2 | xy12345.east-us-2.azure
|  | US Gov Virginia | xy12345.us-gov-virginia.azure
|  | Canada Central | xy12345.canada-central.azure
|  | West Europe | xy12345.west-europe.azure
|  | Australia East | 	xy12345.australia-east.azure
|====================

[#user]
User::  Enter the Snowflake account username.
[#password]
Password::  Enter the Snowflake account password.
[#role]
Role::  Specify the privilege of the user.
[#warehouse]
Warehouse::  Specify the warehouse associated with the connection.
[#database]
Database::
Specify the database associated with the account.
_(Optional)_
[#schema]
Schema::  Specify the schema associated with the database.
[#oauth]
OAuth:: Enter the OAuth client ID associated with the Snowflake database.
[#oauth-client-secret]
OAuth client secret:: Enter the OAuth client secret associated with the Snowflake database.
