= Query external tables from your {connection} connection
:last_updated: 8/3/2022
:linkattrs:
:experimental:
:page-layout: default-cloud
:connection: BigQuery
:description: Learn how to query external tables from your BigQuery connection.
:jira: SCAL-186507

include::partial$external-table-intro.adoc[]

[#supported-stores-formats]
== Supported data stores and file formats

ThoughtSpot supports any data stores or file formats that {connection} supports. Refer to the {connection}
documentation for more information: https://cloud.google.com/bigquery/docs/external-tables[External tables^].

== Querying your external tables

To query your external tables in ThoughtSpot, follow these steps:

. Ensure that {connection} supports your data store(s) and file format(s). Refer to <<supported-stores-formats,Supported data stores and file formats>>.

. Create the external table(s) in {connection}. For assistance, refer to the {connection} documentation.

. Create your {connection} connection, if you have not already done so. When selecting tables, select the external tables you want to query, as well as any other tables. Refer to xref:connections-gbq-add.adoc[].

. xref:search-data.adoc[Search] the data from your external table.

'''
> **Related information**
>
> * xref:connections-gbq-prerequisites.adoc[{connection} prerequisites]
> * xref:connections-gbq-ingress.adoc[]
> * xref:connections-gbq-add.adoc[Add a {connection} connection]
> * xref:connections-gbq-edit.adoc[Edit a {connection} connection]
> * xref:connections-gbq-remap.adoc[Remap a {connection} connection]
> * xref:connections-gbq-delete-table.adoc[Delete a table from a {connection} connection]
> * xref:connections-gbq-delete-table-dependencies.adoc[Delete a table with dependent objects]
> * xref:connections-gbq-delete.adoc[Delete a {connection} connection]
> * xref:connections-gbq-oauth.adoc[Configure OAuth for a {connection} connection]
> * xref:connections-gbq-reference.adoc[Connection reference for {connection}]
> * xref:connections-gbq-passthrough.adoc[]
//> * xref:connections-query-tags.adoc#tag-gbq[ThoughtSpot query tags in Google BigQuery]
