= Delete a table from a {connection} connection
:last_updated: 3/3/2023
:author: Naomi
:linkattrs:
:page-layout: default-cloud
:page-aliases:
:experimental:
:connection: Generic JDBC
:description: Learn how to delete a table from a Generic JDBC connection.

Whenever you try to remove a table in a connection, ThoughtSpot checks for dependencies and shows a list of dependent objects.
You can select the listed objects to delete them or remove the dependency.
Then you can remove the table.
Note that {connection} connections are behind a flag and off by default. To enable them, contact {support-url}.

To delete a table from a {connection} connection:

. Select *Data* in the top navigation bar.
. Open the *Connections* tab in the left navigation bar.
. Select the name of the connection that contains the table you want to delete.
. Find the table you want to delete in the list, and select the checkbox next to its name.
. Click *Delete*, and then select *Delete* again to confirm.

If you attempt to delete a table with dependent objects, the operation is blocked.
A _Cannot delete_ window appears, with a list of links to dependent objects.
See xref:connections-genericjdbc-delete-table-dependencies.adoc[Delete a table with dependent objects].

See the xref:connections-genericjdbc-reference.adoc[Connection reference] for details of connection parameters.

'''
> **Related information**
>
> * xref:connections-genericjdbc-add.adoc[Add a {connection} connection]
> * xref:connections-genericjdbc-edit.adoc[Edit a {connection} connection]
> * xref:connections-genericjdbc-remap.adoc[Remap a {connection} connection]
> * xref:connections-genericjdbc-delete-table-dependencies.adoc[Delete a table with dependent objects]
> * xref:connections-genericjdbc-delete.adoc[Delete a {connection} connection]
> * xref:connections-genericjdbc-reference.adoc[Connection reference for {connection}]