= Passthrough functions for Google {connection}
:last_updated: 2/2/2022
:linkattrs:
:experimental:
:page-layout: default-cloud
:page-aliases:
:connection: BigQuery

Passthrough functions allow you to send SQL expressions directly to Google {connection} without being interpreted by ThoughtSpot.
If you have custom database functions that ThoughtSpot doesn't support, you can use these new passthrough functions in the ThoughtSpot Formula Assistant to call your custom functions.

A passthrough function serves as a wrapper around the specific Google {connection} SQL function.
To use a specific Google {connection} SQL function, match the data type that the function returns with the Connections passthrough function that returns that data type.

For details on all supported passthrough functions, see xref:formula-reference.adoc#passthrough-functions[Connections passthrough functions].

For details on Google {connection} functions, see Google {connection}'s https://cloud.google.com/bigquery/docs/reference/standard-sql/lexical[SQL Reference^].
