= Connection reference for {connection}
:last_updated: 6/7/2022
:linkattrs:
:page-layout: default-cloud
:experimental:
:connection: Denodo

You need specific information to establish a seamless and secure connection.
The following fields are required, except where noted.

Connection name:: Enter a new {connection} connection name.
Connection description:: Provide a short description of the connection. _(Optional)_
Host:: Enter the {connection} server host name. If you used an xref:connections-adw-private-link.adoc[AWS PrivateLink between your {connection} data warehouse and the ThoughtSpot Cloud tenant], use the PrivateLink Endpoint DNS name provided by {support-url}. For example, `vpce-12345a9c7e43959d-xxo2u2xx.vpce-svc-037b1f73d3de3a5b4.us-west-2.vpce.amazonaws.com`.
Port:: Enter the {connection} port.
User:: Enter the user associated with your {connection} account.
Password:: Specify the password of the {connection} account.
Database:: Specify the database of the {connection} account. _(Optional)_