= About connections in ThoughtSpot Cloud
:last_updated: 11/05/2021
:linkattrs:
:experimental:
:page-aliases: /admin/ts-cloud/embrace.adoc
:page-layout: default-cloud
:description: Using Connections, you can perform live queries on external databases.

include::partial$liveboards-announcement.adoc[]

If your company stores source data externally in data warehouses, you can use ThoughtSpot Connections to directly query that data and use ThoughtSpot's analysis and visualization features.

On ThoughtSpot Cloud, you can connect to the following external databases:

* xref:connections-redshift.adoc[Amazon Redshift]
* xref:connections-synapse.adoc[Azure Synapse]
* xref:connections-databricks.adoc[Databricks]
* xref:connections-gbq.adoc[Google BigQuery]
* xref:connections-adw.adoc[Oracle ADW]
* xref:connections-hana.adoc[SAP HANA]
* xref:connections-snowflake.adoc[Snowflake]
* xref:connections-starburst.adoc[Starburst]
* xref:connections-teradata.adoc[Teradata]

== How it works

* Create a connection to the external database
* Choose from each table the columns that you want to explore in your live query.
* Primary key and foreign key relationships are imported along with the primary and foreign key tables.
* If there are any joins in the tables of your connection, Connections imports these joins.
* After your connection is complete, it becomes a *linked* data source in ThoughtSpot, so you can query the external database directly.
* It's also easy to apply transformations, and filter the data.

== Key benefits

* Set up and deploy ThoughtSpot faster by connecting directly to the external database.
* Eliminate the need to move data into ThoughtSpot for analysis.
* Centralize data management and governance in the external database.
* Save significant time and money by avoiding ETL pipelines.
* Connect to multiple external databases.
// - Custom calendar available with Snowflake.

== Limitations

IMPORTANT: Connections does not support joins across connections.

== Feature availability in Connections on ThoughtSpot Cloud

Here are the major features that are not currently available in Connections:

////
- Custom calendar is supported with Snowflake connections.
- Custom calendar is in beta for Redshift, Teradata, Starburst, Synapse, and SAP HANA connections, and are off by default. Contact ThoughtSpot to enable them.
////

* SpotIQ: Instant insights, Did you know?, Liveboard insights, Analyze
* Monitor
* Materialized views

== Function availability in Connections on ThoughtSpot Cloud

The following matrix compares the specific function support across the different databases of Connections in ThoughtSpot Cloud.
Functions not listed here have full support.

|===
| Function | Snowflake | Amazon +
Redshift | Google +
BigQuery | Azure +
Synapse | Oracle +
Autonomous Data Warehouse

| `SOUNDS_LIKE`
| &cross;
| &cross;
| &cross;
| &cross;
| &cross;

| `STRING_ MATCH_SCORE`
| &cross;
| &cross;
| &cross;
| &cross;
| &cross;

| `EDIT_DISTANCE_WITH_CAP`
| &cross;
| &cross;
| &cross;
| &cross;
| &cross;

| `APPROX_SET_CARDINALITY`
| &cross;
| &cross;
| &cross;
| &cross;
| &cross;

| `COUNT_NOT_NULL`
| &cross;
| &cross;
| &cross;
| &cross;
| &cross;

| `SPELLS_LIKE`
| &check;
| &cross;
| &cross;
| &cross;
| &cross;

| `EDIT_DISTANCE`
| &check;
| &cross;
| &cross;
| &cross;
| &cross;
|===

== Data type availability in Connections on ThoughtSpot Cloud

The following matrix captures the specific data type support limitations across the different databases of Connections.
Data types not listed here have full support.

|===
| Data Type +| Snowflake +| Amazon +
Redshift | Google +
BigQuery | Azure +
Synapse | Oracle +
Autonomous Data Warehouse

| `BINARY`
| &cross;
| &check;
| &check;
| &cross;
| &cross;

| `VARBINARY`
| &cross;
| &check;
| &check;
| &cross;
| &cross;

| `TIMESTAMPTZ`
| &check;
| &cross;
| &cross;
| &cross;
| &cross;

| `GEOMETRY`
| &check;
| &cross;
| &check;
| &check;
| &cross;
|===

== Additional specific exceptions

The following list captures the specific limitations across the different databases of Connections.
Databases not listed here have full support.

General: all databases::
Sample values;; Connections does not internationalize sample values in tables.
Delayed UI rendering;; For connections with a very large number of tables (on the order of 1000's of tables), UI rendering may take a very long time.
These connections may time out.
Deleting columns;; After specifying a connection, columns cannot be deleted from the table.
Editing a connection makes it possible to add additional columns, but not to remove them.

== Next steps

* *xref:connections-redshift-add.adoc[Add an Amazon Redshift connection]* +
 Create the connection between ThoughtSpot and tables in an external Amazon RedShift database.
* *xref:connections-synapse-add.adoc[Add an Azure Synapse connection]* +
 Create the connection between ThoughtSpot and tables in an external Azure Synapse database.
* *xref:connections-databricks-add.adoc[Add a Databricks connection]* +
Create the connection between ThoughtSpot and tables in an external Databricks database.
* *xref:connections-gbq-add.adoc[Add a Google BigQuery connection]* +
 Create the connection between ThoughtSpot and tables in an external Google BigQuery database.
* *xref:connections-adw-add.adoc[Add an Oracle Autonomous Data Warehouse connection]* +
 Create the connection between ThoughtSpot and tables in an external Oracle Autonomous Data Warehouse database.
* *xref:connections-hana-add.adoc[Add an SAP HANA connection]* +
 Create the connection between ThoughtSpot and tables in an external SAP HANA database.
* *xref:connections-snowflake-add.adoc[Add a Snowflake connection]* +
 Create the connection between ThoughtSpot and tables in an external Snowflake database.
* *xref:connections-starburst-add.adoc[Add a Starbust connection]* +
 Create the connection between ThoughtSpot and tables in an external Starburst database.
* *xref:connections-teradata-add.adoc[Add a Teradata connection]* +
 Create the connection between ThoughtSpot and tables in an external Teradata database.
