= Connection reference for Databricks
:last_updated: 6/7/2022
:linkattrs:
:page-layout: default-cloud
:page-aliases: /admin/ts-cloud/ts-cloud-embrace-databricks-connection-reference.adoc, /data-integrate/embrace/undefined/
:experimental:

You need specific information to establish a seamless and secure connection.
The following fields are required, except where noted.

If your Databricks is hosted on Microsoft Azure, see <<databricks-azure,Databricks on Microsoft Azure connection reference>>.

Connection name:: Enter a new Databricks connection name.
Connection description:: Provide a short description of the connection.
Host:: Enter the Databricks server host name without the protocol.  Example: *dbs.example.cloud.databricks.com*
HTTP Path:: Enter the Databricks HTTP path.
User:: Email address associated with your Databricks account.
Password:: Specify the password of the Databricks account.

[#databricks-azure]
== Databricks on Microsoft Azure connection reference

Connection name:: Enter a new Databricks connection name.
Connection description:: Provide a short description of the connection.
Host:: Enter the Databricks server hostname.  For more information, see https://docs.microsoft.com/en-us/azure/databricks/integrations/bi/jdbc-odbc-bi#get-server-hostname-port-http-path-and-jdbc-url[Get server hostname, port, HTTP path, and JDBC URL^].  Example: *abc-1234567890123456.78.azuredatabricks.net*
HTTP Path:: Enter the Databricks HTTP path.  For more information, see https://docs.microsoft.com/en-us/azure/databricks/integrations/bi/jdbc-odbc-bi#get-server-hostname-port-http-path-and-jdbc-url[Get server hostname, port, HTTP path, and JDBC URL^].  Example: *sql/protocolv1/o/1234567890123456/7890-123456-abc789*
User:: Enter your login email to your Azure account.
If this does not work, try "`token`".
Password:: Enter your '`personal access token`' generated in Databricks.
This is not the password for your Azure account.  For more information, see https://docs.microsoft.com/en-us/azure/databricks/dev-tools/api/latest/authentication#--generate-a-personal-access-token[Generate a personal access token^].
