= Connection reference for {connection}
:last_updated: 3/3/2023
:author: Naomi
:page-aliases:
:linkattrs:
:page-layout: default-cloud
:experimental:
:connection: Generic JDBC
:description: Learn the specific information needed to establish a secure connection to Generic JDBC.

You need specific information to establish a seamless and secure connection.
The following fields are required, except where noted.

Note that {connection} connections are behind a flag and off by default. To enable them, contact {support-url}.

Driver Class:: Provide the fully qualified class name for the driver. Refer to the documentation for the driver if needed.
Example;; com.mysql.jdbc.Driver
JDBC Driver JAR:: From the list of JAR files uploaded to the cluster, choose the file for the database you are creating with this connection. +
NOTE: To upload the JAR to the cluster, contact {support-url}.
JDBC URL::
Specify the URL in the format accepted by the driver. Refer to the driver documentation for details. +
Example;; jdbc:<database_provider>://<database_host>:<port>/
SQL Dialect:: Choose the SQL dialect compatible with your database.
Advanced configuration:: Use this option to specify any additional connection properties such as key-value pairs.


'''
> **Related information**
>
> * xref:connections-genericjdbc-add.adoc[Add a {connection} connection]
> * xref:connections-genericjdbc-edit.adoc[Edit a {connection} connection]
> * xref:connections-genericjdbc-remap.adoc[Remap a {connection} connection]
> * xref:connections-genericjdbc-delete-table.adoc[Delete a table from a {connection} connection]
> * xref:connections-genericjdbc-delete-table-dependencies.adoc[Delete a table with dependent objects]
> * xref:connections-genericjdbc-delete.adoc[Delete a {connection} connection]