= Connection reference for {connection}
:last_updated: 6/7/2022
:linkattrs:
:page-layout: default-cloud
:page-aliases: /admin/ts-cloud/ts-cloud-embrace-databricks-connection-reference.adoc, /data-integrate/embrace/undefined/
:experimental:
:connection: Databricks
:description: Learn the specific information needed to establish a secure connection to Databricks.

You need specific information to establish a seamless and secure connection.
The following fields are required, except where noted.

If your {connection} is hosted on Microsoft Azure, see <<databricks-azure,{connection} on Microsoft Azure connection reference>>.

Connection name:: Enter a new {connection} connection name.
Connection description:: Provide a short description of the connection. _(Optional)_
[#databricks-reference-host]
Host:: Enter the {connection} server host name without the protocol. You can find this in the connection details of your SQL warehouse.
Example;; *example.cloud.databricks.com*
HTTP Path:: Enter the {connection} HTTP path. You can find this in the connection details of your SQL warehouse.
(Service account only) User:: Email address associated with your {connection} account.
(Service account only) Password:: Specify the password of the {connection} account. You can also use your '`personal access token`' generated in {connection}. For more information, see https://docs.microsoft.com/en-us/azure/databricks/dev-tools/api/latest/authentication#--generate-a-personal-access-token[Generate a personal access token^].
(OAuth only) OAuth Client ID:: Specify the OAuth client ID.
(OAuth only) OAuth Client Secret:: Specify the OAuth client secret.
(OAuth only) Scope:: Specify the scope.
(OAuth only) Auth Url:: Specify the auth url.
(OAuth only) Access token Url:: Specify the access token url.
Catalog:: Specify the catalog. _(Optional)_
Example;; sample_db

[#databricks-azure]
== {connection} on Microsoft Azure connection reference

Connection name:: Enter a new {connection} connection name.
Connection description:: Provide a short description of the connection. _(Optional)_
Host:: Enter the {connection} server hostname.  For more information, see https://docs.microsoft.com/en-us/azure/databricks/integrations/bi/jdbc-odbc-bi#get-server-hostname-port-http-path-and-jdbc-url[Get server hostname, port, HTTP path, and JDBC URL^].
Example;; *abc-1234567890123456.78.azuredatabricks.net*
HTTP Path:: Enter the Databricks HTTP path.  For more information, see https://docs.microsoft.com/en-us/azure/databricks/integrations/bi/jdbc-odbc-bi#get-server-hostname-port-http-path-and-jdbc-url[Get server hostname, port, HTTP path, and JDBC URL^].
Example;; *sql/protocolv1/o/1234567890123456/7890-123456-abc789*
(Service account only) User:: Enter your login email to your Azure account.
If this does not work, try "`token`".
(Service account only) Password:: Enter your '`personal access token`' generated in {connection}.
This is not the password for your Azure account.  For more information, see https://docs.microsoft.com/en-us/azure/databricks/dev-tools/api/latest/authentication#--generate-a-personal-access-token[Generate a personal access token^].
(OAuth only) OAuth Client ID:: Specify the OAuth client ID.
(OAuth only) OAuth Client Secret:: Specify the OAuth client secret.
(OAuth only) Scope:: Specify the scope.
(OAuth only) Auth Url:: Specify the auth url.
(OAuth only) Access token Url:: Specify the access token url.
Catalog:: Specify the catalog. _(Optional)_
Example;; sample_db

'''
> **Related information**
>
> * xref:connections-databricks-add.adoc[Add a {connection} connection]
> * xref:connections-databricks-edit.adoc[Edit a {connection} connection]
> * xref:connections-databricks-remap.adoc[Remap a {connection} connection]
> * xref:connections-databricks-delete-table.adoc[Delete a table from a {connection} connection]
> * xref:connections-databricks-delete-table-dependencies.adoc[Delete a table with dependent objects]
> * xref:connections-databricks-delete.adoc[Delete a {connection} connection]
> * xref:connections-databricks-oauth.adoc[Configure OAuth for a {connection} connection]
> * xref:connections-databricks-private-link.adoc[]
> * xref:connections-databricks-passthrough.adoc[]