= Connection reference for {connection}
:last_updated: 9/21/2020
:linkattrs:
:experimental:
:page-layout: default-cloud
:page-aliases: /data-integrate/embrace/embrace-gbq-reference.adoc, /admin/ts-cloud/ts-cloud-embrace-gbq-connection-reference.adoc
:connection: BigQuery

You need specific information to establish a seamless and secure connection.
The following fields are required, except where noted.

Connection name:: Enter a new {connection} connection name.
Connection description:: Provide a short description of the connection. _(Optional)_
Project id:: Enter the project ID associated with the {connection} database.
Service account:: Enter the service account JSON key associated with the {connection} database. To generate the key, refer to xref:connections-gbq-prerequisites.adoc#service-account[Google {connection} prerequisites].
OAuth:: Enter the OAuth client ID associated with the {connection} database.
OAuth client secret:: Enter the OAuth client secret associated with the {connection} database.
