= Enabling an AWS PrivateLink between ThoughtSpot Cloud and your {connection} data warehouse
:experimental:
:last_updated: 6/9/22
:linkattrs:
:page-layout: default-cloud
:description: Learn how to deploy an AWS PrivateLink between your Databricks data warehouse and the ThoughtSpot Cloud tenant.
:connection: Databricks
:jira: SCAL-203358

Learn how to deploy an AWS PrivateLink between your {connection} data warehouse and the ThoughtSpot Cloud tenant.

NOTE: AWS PrivateLink is only available to Enterprise Edition users.


include::partial$private-link-intro.adoc[]

This article details how to enable a PrivateLink for *{connection}*;
to enable it for other data warehouses, refer to:

* xref:connections-redshift-private-link.adoc[Amazon Redshift PrivateLink]
* xref:connections-denodo-private-link.adoc[Denodo PrivateLink]
* xref:connections-dremio-private-link.adoc[Dremio PrivateLink]
* xref:connections-adw-private-link.adoc[Oracle PrivateLink]
* xref:connections-postgresql-private-link.adoc[PostgreSQL PrivateLink]
* xref:connections-hana-private-link.adoc[SAP HANA PrivateLink]
* xref:connections-snowflake-private-link.adoc[Snowflake PrivateLink]
* xref:connections-sql-server-private-link.adoc[SQL Server PrivateLink]
* xref:connections-starburst-private-link.adoc[Starburst PrivateLink]
* xref:connections-teradata-private-link.adoc[Teradata PrivateLink]

NOTE: You can enable a maximum of five PrivateLinks in your environment.

To deploy an AWS PrivateLink, you must work with {support-url} and follow the procedure in this article.

[#prerequisites]
== Prerequisites

* You must have a {connection} Enterprise account.
* The ThoughtSpot cluster must be in the same AWS region as your {connection} account.
* You must have {connection} Account Admin credentials.
+
NOTE: The {connection} Account admin is different from the Workspace Admin. The Account admin is able to sign in to https://accounts.cloud.databricks.com/[https://accounts.cloud.databricks.com/^].
* You must obtain the VPC Endpoint ID from {support-url}. This is required before you can complete <<register-endpoint,Step 1: Register the VPC Endpoint>>.

== Enable an AWS PrivateLink for {connection}

To deploy an AWS PrivateLink between your {connection} data warehouse and the ThoughtSpot Cloud tenant, follow these steps.

. <<register-endpoint,Register the VPC Endpoint with the {connection} Account API>>
. <<private-access,Create a private access settings configuration>>
. <<network-config,Create a new network configuration>>
. <<create-workspace,Create or update the Databricks workspace>>
. <<support,Contact ThoughtSpot Support>>
. <<embrace,Configure Connections>>

[#register-endpoint]
=== Step 1: Register the VPC Endpoint with the {connection} Account API

After completing the <<prerequisites,prerequisites>>, you must configure the register the VPC Endpoint. Follow these steps:

. Obtain the VPC Endpoint ID from {support-url}, if you did not do so in the <<prerequisites,prerequisites>>.
. Complete https://docs.databricks.com/administration-guide/cloud-configurations/aws/privatelink.html#step-3-register-your-vpc-endpoint-ids-with-the-account-api[Step 3: Register your VPC endpoint IDs with the Account API^] in the https://docs.databricks.com/administration-guide/cloud-configurations/aws/privatelink.html[Databricks AWS PrivateLink documentation^]. You need the VPC Endpoint ID from ThoughtSpot Support to complete this step.

[#private-access]
=== Step 2: Create a private access settings configuration

Complete https://docs.databricks.com/administration-guide/cloud-configurations/aws/privatelink.html#step-5-create-a-private-access-settings-configuration-using-the-databricks-account-api[Step 5: Create a private access settings configuration using the Databricks Account API^] in the https://docs.databricks.com/administration-guide/cloud-configurations/aws/privatelink.html[Databricks AWS PrivateLink documentation^].

[#network-config]
=== Step 3: Create a new network configuration

Complete https://docs.databricks.com/administration-guide/cloud-configurations/aws/privatelink.html#step-6-create-a-new-network-configuration-using-account-api[Step 6: Create a new network configuration using Account API^] in the https://docs.databricks.com/administration-guide/cloud-configurations/aws/privatelink.html[Databricks AWS PrivateLink documentation^].

[#create-workspace]
=== Step 4: Create or update the Databricks workspace

. Complete https://docs.databricks.com/administration-guide/cloud-configurations/aws/privatelink.html#step-7-create-or-update-a-workspace-with-privatelink-configurations-using-the-account-api[Step 7: Create or update a workspace with PrivateLink configurations using the Account API^] in the https://docs.databricks.com/administration-guide/cloud-configurations/aws/privatelink.html[Databricks AWS PrivateLink documentation^].

. Make a note of your *Databricks Workspace URL*. You must send it to {support-url} in the next step. This URL is in the format `https://xxx.cloud.databricks.com/`.

[#support]
=== Step 5: Contact ThoughtSpot Support
After you complete steps 1-4 in this document, contact {support-url}. They must finish the PrivateLink configuration.

Make sure you send ThoughtSpot Support your *Databricks Workspace URL*. This URL is in the format `https://xxx.cloud.databricks.com/`.

After {support-url} finishes the configuration, they will contact you, and you can move on to <<embrace,Step 6: Configure Connections>>.

[#embrace]
=== Step 6: Configure Connections

Create a xref:connections-databricks.adoc[{connection} connection]. Note that Databricks connections use the same xref:connections-databricks-reference.adoc#databricks-reference-host[host name] regardless of whether they are created through PrivateLink. When PrivateLink is configured, ThoughtSpot switches the internal DNS resolution for the hostname to point to the PrivateLink endpoint IP. For example, if your customer Databricks account is `\https://myaccount.cloud.databricks.com`, you would use the same name when configuring a connection that uses PrivateLink.


'''
> **Related information**
>
> * xref:connections-databricks-add.adoc[Add a {connection} connection]
> * xref:connections-databricks-edit.adoc[Edit a {connection} connection]
> * xref:connections-databricks-remap.adoc[Remap a {connection} connection]
> * xref:connections-databricks-delete-table.adoc[Delete a table from a {connection} connection]
> * xref:connections-databricks-delete-table-dependencies.adoc[Delete a table with dependent objects]
> * xref:connections-databricks-delete.adoc[Delete a {connection} connection]
> * xref:connections-databricks-oauth.adoc[Configure OAuth for a {connection} connection]
> * xref:connections-databricks-oauth-aad.adoc[]
> * xref:connections-databricks-reference.adoc[Connection reference for {connection}]
> * xref:connections-databricks-passthrough.adoc[]
> * xref:connections-databricks-best.adoc[]