= Consumption data storage
:last_updated: 11/05/2021
:linkattrs:
:experimental:
:page-aliases:
:page-layout: default-cloud
:description:

ThoughtSpot securely stores your consumption data. A dedicated Amazon S3 bucket is set up to store user activity CSV files temporarily. Then, the S3 data is uploaded to a searchable data store in Amazon Redshift. There is an S3 bucket prefix for your company and a unique key for your company to encrypt it. The encryption key is stored in AWS KMS.

As part of the pricing configuration, your cluster is configured with an access key to have access to the S3 bucket prefix unique to your cluster. ThoughtSpot deploys and maintains an Amazon Redshift database to load the consumption pricing data. With your cluster enabled for consumption pricing, you get access to your cluster’s consumption pricing data. A unique database user is created in Redshift and configured in your cluster as part of the pricing configuration. This creates a unique connection from your cluster to the ThoughtSpot manager consumption pricing database. You use this connection to view the consumption pricing-related reports for your ThoughtSpot cluster.
ts in a unique Embrace connection per customer cluster to the ThoughtSpot manager consumption pricing database (Redshift).
This is used to view the consumption pricing related reports in the customer's ThoughtSpot instance.