= Consumption-based pricing
:last_updated: 11/05/2021
:linkattrs:
:experimental:
:page-aliases: /admin/ts-cloud/consumption-pricing.adoc
:page-layout: default-cloud
:description: ThoughtSpot’s consumption-based pricing model lets you purchase a ThoughtSpot subscription based on your usage of the ThoughtSpot product.

ThoughtSpot’s consumption-based pricing model lets you purchase a ThoughtSpot subscription based on your usage of the ThoughtSpot product.

When you purchase ThoughtSpot using consumption-based pricing, ThoughtSpot bills you based on <<credits,credits>>.
The ThoughtSpot consumption pricing model is available for both ThoughtSpot Cloud and for Connections software deployment on your cloud platform.

For more information about pricing, refer to https://www.thoughtspot.com/pricing[ThoughtSpot pricing^].
Each cluster must have a discrete pricing model.

[#credits]
== Credits

You purchase and consume credits with the consumption-based pricing.
A credit is a unit of measure.
When members of your organization use ThoughtSpot, we measure either xref:consumption-pricing-query-based.adoc[query-based], or xref:consumption-pricing-time-based.adoc[time-based] usage. Both types of usage consume available credits. Each active ThoughtSpot user consumes credits.

User activities in ThoughtSpot that consume credits include:

- Performing a search
- Viewing or editing Liveboards or Answers
- Creating and editing Worksheets
- Making administrative changes, or changing setup configuration

'''
> *Related information*
>
> * xref:consumption-pricing-query-based.adoc[Query-based usage]
> * xref:consumption-pricing-time-based.adoc[Time-based usage]
> * xref:consumption-pricing-storage.adoc[Consumption data storage]