= Query-based usage
:last_updated: 11/05/2021
:linkattrs:
:experimental:
:page-aliases:
:page-layout: default-cloud
:description: Query-based usage measures the number of queries generated, based on a user’s activity. Usually, one credit is consumed for every query that is generated.


[.lead]
Query-based usage is measured by the number of queries generated, based on a user’s activity. In most cases, one credit is consumed for every query that is generated.

== What is a credit?

A credit is a unit of measure you use to pay for using ThoughtSpot to get insights from your data. Insights are created by executing queries to request information from a connected data warehouse.

=== Types of credits

- *Base credits*: credits included in the base subscription of each edition.
- *Flexible credits*: any additional credits that you would like to purchase to add to your subscription.

[#usage-minutes]
== Query-based pricing

To purchase query-based credits, you purchase a number of base-credit packages.  Each base-credit package is valid for one year and sets a subscription term of one year.  If you purchase multiple base-credit packages in an order form, the subscription term will be extended for that number of years.

== What is a query?

When a user requires information from an external data warehouse, system cache (data fetched previously or a result of recent calculation, and stored in the system), or descriptive/statistical metadata, the system triggers an event, called a query. Some functions, like a scheduled Liveboard, monitor, or SpotIQ, also trigger queries.

Various kinds of user actions or system functions generate one or more queries.

Examples of queries:

- A chart view from a search typically generates one query.
- Pivot tables and stacked charts generate multiple queries.
- A Liveboard view may generate multiple queries when loading multiple visualizations.

For information on user actions that generate queries, see xref:consumption-pricing-query-based-generate.adoc[User actions and queries].

'''
> *Related information*
>
> * xref:consumption-pricing.adoc[Consumption-based pricing]
> * xref:consumption-pricing-time-based.adoc[Time-based usage]
> * xref:consumption-pricing-storage.adoc[Consumption data storage]