= Consumption data storage
:last_updated: 11/05/2021
:linkattrs:
:experimental:
:page-aliases:
:page-layout: default-cloud
:description: ThoughtSpot securely stores your consumption data.

ThoughtSpot securely stores your consumption data. A dedicated Amazon S3 bucket is set up to store user activity CSV files temporarily. Then, the S3 data is uploaded to a searchable data store in Snowflake. There is an S3 bucket prefix for your company and a unique key for your company to encrypt it. The encryption key is stored in AWS KMS.

As part of the pricing configuration, your cluster is configured with an access key to have access to the S3 bucket prefix unique to your cluster. ThoughtSpot deploys and maintains a Snowflake database to load the consumption pricing data. With your cluster enabled for consumption pricing, you get access to your cluster’s consumption pricing data. A unique database user is created in Snowflake and configured in your cluster as part of the pricing configuration. This creates a unique connection from your cluster to the ThoughtSpot manager consumption pricing database. You use this connection to view the consumption pricing-related reports for your ThoughtSpot cluster.

'''
> *Related information*
>
> * xref:consumption-pricing.adoc[Consumption-based pricing]
> * xref:consumption-pricing-query-based.adoc[Query-based usage]
> * xref:consumption-pricing-time-based.adoc[Time-based usage]
