= Consumption-based pricing
:last_updated: 11/05/2021
:linkattrs:
:experimental:
:page-aliases: /admin/ts-cloud/consumption-pricing.adoc
:page-layout: default-cloud
:description: ThoughtSpot’s consumption-based licensing model lets you license ThoughtSpot based on usage of the ThoughtSpot product.

ThoughtSpot’s consumption-based licensing model lets you license ThoughtSpot based on your usage of the ThoughtSpot product.

When you purchase a consumption-based ThoughtSpot license, ThoughtSpot bills you based on <<credits,credits>>.
The ThoughtSpot consumption licensing model is available for both ThoughtSpot Cloud and for Connections software deployment on your cloud platform.

For more information about pricing, refer to https://www.thoughtspot.com/pricing[ThoughtSpot pricing^].
Each cluster must have a discrete pricing model.

[#credits]
== Credits

You purchase and consume credits with the consumption-based licenses.
A credit is a unit of measure.
When members of your organization use ThoughtSpot, we measure either xref:consumption-pricing-query-based.adoc[query-based], or xref:consumption-pricing-time-based.adoc[time-based] usage. Both types of usage consume available credits. Each active ThoughtSpot user consumes credits.

User activities in ThoughtSpot that consume credits include:

- Performing a search
- Viewing or editing Liveboards or answers
- Creating and editing worksheets
- Making administrative changes, or changing setup configuration
