= Load CSV files in Free Trial
:last_updated:
:linkattrs:
:experimental:
:page-layout: default-cloud
:description: The simplest way to load data is to upload a CSV file from the ThoughtSpot web interface.

In ThoughtSpot's free trial, you can upload your own data to perform live queries on it. You can xref:connections.adoc[connect to your cloud data warehouse], and you can upload 10 flat data files, or CSV files. The file size limit is 50 MB.

Your data should be in a CSV (comma separated values) file before you load it.
A CSV file is a text file made up of data fields separated by a delimiter and optionally enclosed with an enclosing character.

NOTE: This feature is exclusive to ThoughtSpot Free Trial.
Use Connections to access your data in ThoughtSpot Cloud.

== Add data files
Learn how to upload a CSV file. You can also edit that file later, or replace it with a different file. Note that you can only use 1 CSV file at a time.

include::partial$csv-upload.adoc[]

=== CSV file formatting

include::partial$csv-format.adoc[]
