= Custom actions
:last_updated: 2/25/2022
:linkattrs:
:experimental:
:page-aliases: /admin/ts-cloud/custom-actions.adoc
:page-layout: default-cloud
:description: You can add custom actions as menu options on visualizations, Liveboards, and saved Answers.

ThoughtSpot provides a set of standard actions in the primary menu bar, *More* menu, and the contextual menu that appears when a user right-clicks any value in an Answer or visualization.

ThoughtSpot supports adding custom actions to an Answer or visualization page. For example, you may want to create a custom action that allows pushing business insights from ThoughtSpot to an external app or a specific URL.

Similarly, if you have embedded ThoughtSpot in another app, you can add a custom action to trigger a callback event to the host application and initiate a response payload.

== Custom action creation

ThoughtSpot Developer Portal allows you to create, modify, and delete custom actions. Users with Developer or Administrator privilege can create the following types of actions:

URL actions::
A https://developers.thoughtspot.com/docs/?pageid=custom-action-url[URL action, window=_blank] allows you to send data from an Answer or visualization to a specific URL in a `POST` request.

////
App actions::
An https://developers.thoughtspot.com/docs/?pageid=app-actions[app action] allows you to push data to an external business app or workspace; for example, Slack.
////

Callback actions::
A https://developers.thoughtspot.com/docs/?pageid=custom-action-callback[callback action,window=_blank] triggers a callback event to the parent application and pushes the Answer or visualization data in a response payload. Callback actions are supported only on embedded instances and require a ThoughtSpot Embedded Edition license.

== Global and local actions

When creating a custom action, developers can configure it as a global or local action. They can also restrict custom action availability to specific user groups.

By default, a global action appears as a menu action in the *More* menu on all visualizations. Authorized users can edit the position of a global action on a visualization or saved Answer by using the edit icon in the *Custom actions* panel.

A local action is not assigned to any visualization or saved Answer by default. Authorized users can https://developers.thoughtspot.com/docs/?pageid=add-action-viz[add a local action, window=_blank] to a saved Answer, visualization, or Worksheet. If you https://developers.thoughtspot.com/docs/?pageid=add-action-worksheet[add a local action to a Worksheet, window=_blank], all new Answers built using that Worksheet display the action in the specified location.

For more information, see https://developers.thoughtspot.com/docs/?pageid=custom-action-intro[Custom actions in ThoughtSpot Developer Documentation,window=_blank].
