= Query sets
:last_updated: 6/4/24
:author: Naomi
:linkattrs:
:page-layout: default-cloud-early-access
:experimental:
:description: You can now create query sets, which can be used to classify values in a list you can then reuse across multiple analyses.
:jira:

You can create sets, which can be used to classify values in a list that you can then reuse across multiple analyses. Answer, formulas and parameters are generally available only when in use in an Answer, and must be remade if you navigate away from the Answer without saving. Sets are reusable across many answers with a single point of definition. A set is built from a Worksheet however it does not belong to the Worksheet. When a set is initially created it is only available to the creator. When a set is used in an Answer or Liveboard, and this Answer or Liveboard is shared with specific users or groups of users, the set is then available for use as a community object.

ThoughtSpot now supports query sets.

NOTE: Query sets are in early access and off by default. To enable this feature, contact {support-url}.


To create a query set, first define the business question you wish to answer.


For example, you may want to create a set to show the first sale date per customer.


To create a column showcasing this defined list of values, follow these steps:

. Navigate to the *Search Data* page by clicking the *Search data* button.

. Click *Add* and select *Query set*.

. Ensure you are searching on the correct Worksheet, and select the *Customer ID* column from the left side bar, or type the word into the Search bar. To see the quantity purchased by product, select *Min Transaction Date* and click the *Go* button or press *Enter*.

. Click *Next*.

. In the *Select name and description* window, complete the following fields:
.. Set name: Name your query set something meaningful.
.. Set description: Describe what this query set represents.
. Click *Next*.
. Under *Select a base column*, select a *Base column*. Select the column you are using as the base of your list of values. In this example, *Customer ID*.
. Under *Define groups for included query values*, select a column with the output groups. Each row in the base column will be assigned to an output group based on its value from this column.
. Under *Define groups for excluded query values*, select either *Hide excluded values* or *Group excluded values*. If you group excluded values, you can give the group a custom name.
. Click *Save*.



