= Custom actions
:last_updated: 8/18/2021
:linkattrs:
:experimental:
:page-aliases: /admin/ts-cloud/custom-actions.adoc
:page-layout: default-cloud
:description: You can add custom actions to an embedded instance and view them in the menu options on visualizations.

You can add custom actions to an embedded instance and view them in the menu options on visualizations.

You can insert custom buttons and menu actions into the ThoughtSpot's UI to push insights from ThoughtSpot to your app or trigger an event to an external application from your host application.
These custom actions allow your users to trigger actions on insights without leaving your application.

If your user account has the `Developer` privilege, you can create custom actions in the ThoughtSpot Developer portal.
Users with edit access to a worksheet or visualization can add a custom action as a primary button or menu action.

== Configure custom actions

ThoughtSpot Developer Portal allows you to create, modify, and delete custom actions.

Based on your application requirements, users with Developer privilege can create the following types of actions:

* https://developers.thoughtspot.com/docs/?pageid=custom-action-url[Action to send data to a specific URL endpoint].
* https://developers.thoughtspot.com/docs/?pageid=custom-action-callback[Action that triggers a callback action to your host application to send ThoughtSpot data as payload].

== Add custom action to visualizations

If your ThoughtSpot instance has custom actions configured, users with edit privileges to a worksheet or visualization can assign any available action to a visualization page.

For example, you can add a custom action to the contextual menu that appears when you right-click on a chart or table.
You can also add a custom action to all the new visualizations built from a specific worksheet.

For more information, see https://developers.thoughtspot.com/docs/?pageid=custom-action-intro[Custom actions in ThoughtSpot Developer Documentation].
