= Denodo connection reference
:last_updated: 09/10/2021
:experimental:
:linkattrs:
:page-aliases: /data-integrate/dataflow/dataflow-denodo-reference.adoc

Learn about the fields used to create a Denodo connection with ThoughtSpot DataFlow.

Here is a list of the fields for a Denodo connection in ThoughtSpot DataFlow.
You need specific information to establish a seamless and secure connection.

[#connection-properties]
== Connection properties
[#dataflow-denodo-conn-connection-name]
Connection name:: Name your connection. Mandatory field.
Example:;; DenodoConnection
[#dataflow-denodo-conn-connection-type]
Connection type:: Choose the Denodo connection type. Mandatory field.
Example:;; Denodo
[#dataflow-denodo-conn-host]
Host:: Specify the hostname or the IP address of the system. Mandatory field.
Example:;; www.example.com
[#dataflow-denodo-conn-port]
Port:: Specify the port associated with the system. Mandatory field.
Example:;; 1234
[#dataflow-denodo-conn-user]
User::
Specify the user who connects to the system.
This user must have data access privileges. Mandatory field.
Example:;; userid
[#dataflow-denodo-conn-password]
include::partial$dataflow/password.adoc[]

[#dataflow-denodo-conn-jdbc-options]
include::partial$dataflow/jdbc-options.adoc[]

[#sync-properties]
== Sync properties
[#dataflow-denodo-sync-column-delimiter]
Column delimiter:: Specify the column delimiter character. Mandatory field.
Example:;; 1
Valid Values:;; Any printable ASCII character or decimal value for ASCII character
Default:;; 1
[#dataflow-denodo-sync-enclosing-character]
Enclosing character:: Specify if the text columns in the source data needs to be enclosed in quotes. Optional field.
Example:;; DOUBLE
Valid Values:;; SINGLE, DOUBLE
Default:;; DOUBLE
Other notes:;; This is required if the text data has newline character or delimiter character.
[#dataflow-denodo-sync-escape-character]
Escape character::
Specify this if the text qualifier is mentioned.
This should be the character which escapes the text qualifier character in the source data. Optional field.
Example:;; \"
Valid Values:;; Any ASCII character
Default:;; \"
[#dataflow-denodo-sync-max-ignored-rows]
include::partial$dataflow/max-ignored-rows.adoc[]

[#dataflow-denodo-sync-ts-load-options]
include::partial$dataflow/ts-load-options.adoc[]
