= JDBC connection reference
:last_updated: 09/10/2021
:experimental:
:linkattrs:
:page-aliases: /data-integrate/dataflow/dataflow-jdbc-reference.adoc

Learn about the fields used to create a JDBC connection with ThoughtSpot DataFlow.

Here is a list of the fields for a jdbc connection in ThoughtSpot DataFlow.
You need specific information to establish a seamless and secure connection.

[#connection-properties]
== Connection properties
[#dataflow-jdbc-conn-connection-name]
Connection name:: Name your connection. Mandatory field.
Example:;; JDBCConnection
[#dataflow-jdbc-conn-connection-type]
Connection type:: Choose the JDBC connection type. Mandatory field.
Example:;; JDBC
[#dataflow-jdbc-conn-driver-name]
Driver name:: Specify the JDBC driver class for the database connection. Mandatory field.
[#dataflow-jdbc-conn-jdbc-url]
JDBC URL:: Specify the jdbc url for database connection. Mandatory field.
Example:;; jdbc:sqlserver://localhost:1234;databaseName=PUBS
[#dataflow-jdbc-conn-jdbc-driver-jar]
JDBC driver jar:: Upload the jdbc jar available in local system. Mandatory field.
[#dataflow-jdbc-conn-jdbc-options]
include::partial$dataflow/jdbc-options.adoc[]
[#dataflow-jdbc-conn-key]
Key:: Define the key parameter. Mandatory field.
[#dataflow-jdbc-conn-value]
Value:: Specify the value for key parameter. Mandatory field.
[#dataflow-jdbc-conn-encrypt]
Encrypt:: Encrypt the details for secured authentication.
Optional field. +
 Select the check-box to encrypt the details.
[#dataflow-jdbc-conn-schema-object-name-enclosing-character]
Schema object name enclosing character:: Specify the schema object name enclosing character. Optional field.
Default:;;
Other notes:;; Advanced configuration

[#sync-properties]
== Sync properties
[#dataflow-jdbc-sync-column-delimiter]
Column delimiter:: Specify the column delimiter character. Mandatory field.
Example:;; 1
Valid Values:;; Any printable ASCII character or decimal value for ASCII character
Default:;; 1
[#dataflow-jdbc-sync-enclosing-character]
Enclosing character:: Specify if the text columns in the source data needs to be enclosed in quotes. Optional field.
Example:;; DOUBLE
Valid Values:;; SINGLE, DOUBLE
Default:;; DOUBLE
Other notes:;; This is required if the text data has newline character or delimiter character.
[#dataflow-jdbc-sync-escape-character]
Escape character::
Specify this if the text qualifier is mentioned.
This should be the character which escapes the text qualifier character in the source data. Optional field.
Example:;; \"
Valid Values:;; Any ASCII character
Default:;; \"
[#dataflow-jdbc-sync-max-ignored-rows]
include::partial$dataflow/max-ignored-rows.adoc[]

[#dataflow-jdbc-sync-ts-load-options]
include::partial$dataflow/ts-load-options.adoc[]
