= Salesforce connection reference
:last_updated: 09/09/2021s
:experimental:
:linkattrs:
:page-aliases: /data-integrate/dataflow/dataflow-salesforce-reference.adoc

Learn about the fields used to create a Salesforce connection with ThoughtSpot DataFlow.

Here is a list of the fields for a Salesforce connection in ThoughtSpot DataFlow.
You need specific information to establish a seamless and secure connection.

[#connection-properties]
== Connection properties
[#dataflow-salesforce-conn-connection-name]
Connection name:: Name your connection. Mandatory field.
Example:;; SalesforceConnection
[#dataflow-salesforce-conn-connection-type]
Connection type:: Choose the Salesforce connection type. Mandatory field.
Example:;; Salesforce
[#dataflow-salesforce-conn-user]
User::
Specify the user id.
This user must have data access privileges. Mandatory field.
Example:;; userdi
[#dataflow-salesforce-conn-password]
include::partial$dataflow/password.adoc[]

[#dataflow-salesforce-conn-use-sandbox]
Use sandbox:: Specify if connecting to copy of a production environment. Optional field.
Example:;; Unchecked
Other notes:;; Advanced configuration.

[#dataflow-salesforce-conn-jdbc-options]
JDBC options:: Specify the options associated with the JDBC URL. Optional field.
Example:;; jdbc:sqlserver://[serverName[\instanceName][:portNumber]]
Other notes:;; Advanced configuration.

[#sync-properties]
== Sync properties
[#dataflow-salesforce-sync-column-delimiter]
Column delimiter:: Specify the column delimiter character. Mandatory field.
Example:;; 1
Valid Values:;; Any printable ASCII character or decimal value for ASCII character
Default:;; 1
[#dataflow-salesforce-sync-enclosing-character]
Enclosing character:: Specify if the text columns in the source data must be enclosed in quotes. Optional field.
Example:;; DOUBLE
Valid Values:;; SINGLE, DOUBLE
Default:;; DOUBLE
Other notes:;; This is required if the text data has newline character or delimiter character.
[#dataflow-salesforce-sync-escape-character]
Escape character:: Specify the escape character if using a text qualifier in the source data. Optional field.
Example:;; \"
Valid Values:;; Any ASCII character
Default:;; \"
[#dataflow-salesforce-sync-fetch-size]
Fetch size::
Specify the number of rows fetched into memory at the same time.
If the value is 0, system fetches all rows at the same time. Optional field.
Example:;; 1000
Valid Values:;; Any numeric value
Default:;; 1000
Other notes:;; Appears when Extraction Type is "JDBC".
[#dataflow-salesforce-sync-read-timeout]
Read Timeout:: Specify timeout time in milliseconds to read data from Salesforce. Optional field.
Example:;; 1800000
Valid Values:;; Any numeric value
Default:;; 1800000
[#dataflow-salesforce-sync-max-ignored-rows]
include::partial$dataflow/max-ignored-rows.adoc[]

[#dataflow-salesforce-sync-ts-load-options]
include::partial$dataflow/ts-load-options.adoc[]
