= Add an Exadata database connection
:last_updated: 3/22/2021
:page-aliases: /data-integrate/dataflow/dataflow-exadata-add.adoc
:linkattrs:
:experimental:

You can add a connection to an Exadata database using ThoughtSpot DataFlow.

Follow these steps:

include::partial$add-database-connection.adoc[]

. After you select the Exadata *Connection type*, the rest of the connection properties appear.
xref:dataflow-exadata-reference.adoc#dataflow-exadata-conn-connection-name[Connection name]::
Name your connection.
xref:dataflow-exadata-reference.adoc#dataflow-exadata-conn-connection-type[Connection type]::
Choose the Exadata connection type.
xref:dataflow-exadata-reference.adoc#dataflow-exadata-conn-host[Host]::
Specify the hostname or the IP address of the Exadata system
xref:dataflow-exadata-reference.adoc#dataflow-exadata-conn-port[Port]::
Specify the port associated to the Exadata system
xref:dataflow-exadata-reference.adoc#dataflow-exadata-conn-user[User]::
Specify the user id that will be used to connect to the Exadata system.
This user should have necessary privileges to access the data in the databases.
xref:dataflow-exadata-reference.adoc#dataflow-exadata-conn-password[Password]::
Specify the password for the User
xref:dataflow-exadata-reference.adoc#dataflow-exadata-conn-service-name[Service name]::
Service name is the TNS alias that you give when you remotely connect to your database and this Service name is recorded in Tnsnames.ora file on your clients and it can be the same as SID and you can also give it any other name you want
xref:dataflow-exadata-reference.adoc#dataflow-exadata-conn-version[Version]::
Specify the Exadata version being connected to
xref:dataflow-exadata-reference.adoc#dataflow-exadata-conn-jdbc-options[JDBC options]::
Specify the options associated with the JDBC URL.
+
See xref:dataflow-exadata-reference.adoc#connection-properties[Connection properties] for details, defaults, and examples.
. Click *Create connection*.

'''
> **Related information**
>
> * xref:dataflow-exadata-reference.adoc#connection-properties[DataFlow Exadata connection properties]
