= Teradata connection reference
:last_updated: 09/09/2021
:experimental:
:linkattrs:
:page-aliases: /data-integrate/dataflow/dataflow-teradata-reference.adoc

Learn about the fields used to create a Teradata connection with ThoughtSpot DataFlow.

Here is a list of the fields for a Teradata connection in ThoughtSpot DataFlow.
You need specific information to establish a seamless and secure connection.

[#connection-properties]
== Connection properties
[#dataflow-teradata-conn-connection-name]
Connection name:: Name your connection.
+
Mandatory field.
+
Example:;; TeradataConnection
[#dataflow-teradata-conn-connection-type]
Connection type:: Choose the Teradata connection type.
+
Mandatory field.
+
Example:;; Teradata
[#dataflow-teradata-conn-host]
Host:: Specify the hostname or the IP address of the Teradata system.
+
Mandatory field.
+
Example:;; www.example.com
[#dataflow-teradata-conn-port]
Port:: Specify the port associated to the Teradata system.
+
Mandatory field.
+
Example:;; 1234
[#dataflow-teradata-conn-authentication-type]
Authentication type:: Specifies the type of security protocol to connect to the instance. Based on the type of security select the authentication type and provide details. Mandatory field.
[#dataflow-teradata-conn-user]
User::
Specify the user id that will be used to connect to the Teradata system.
This user should have necessary privileges to access the data in the databases.
+
Mandatory field.
+
Example:;; userdi
[#dataflow-teradata-conn-password]
include::partial$dataflow/password.adoc[]
[#dataflow-teradata-conn-database]
Database:: Collection of information that is organized so that it can be easily accessed, managed, and updated. Optional field.
Example:;; Test

[#dataflow-teradata-conn-version]
Version:: Specify the version of Teradata you are using.
+
Optional field.
+
Example:;; 14.2
Other notes:;; Advanced configuration.
[#dataflow-teradata-conn-jdbc-options]
include::partial$dataflow/jdbc-options.adoc[]

[#sync-properties]
== Sync properties
[#dataflow-teradata-sync-data-extraction-mode]
Data extraction mode:: Specify the extraction type. Optional field.
xample:;; JDBC
Valid Values:;; JDBC, TPT
Default:;; JDBC
[#dataflow-teradata-sync-column-delimiter]
Column delimiter:: Specify the column delimiter character. Mandatory field.
Example:;; 1
Valid Values:;; Any printable ASCII character or decimal value for ASCII character
Default:;; 1
[#dataflow-teradata-sync-null-value]
Null value::
Specifies the string literal that indicates the null value in the extracted data.
During the data load, the column value matching this string loads as null in the target. Optional field.
Example:;; NULL
Valid Values:;; Any string literal
Default:;; NULL
[#dataflow-teradata-sync-enclosing-character]
Enclosing character:: Specify if the text columns in the source data needs to be enclosed in quotes. Optional field.
Example:;; DOUBLE
Valid Values:;; SINGLE, DOUBLE
Default:;; DOUBLE
Other notes:;; This is required if the text data has newline character or delimiter character.
[#dataflow-teradata-sync-escape-character]
Escape character:: Specify the escape character if using a text qualifier in the source data. Optional field.
Example:;; \"
Valid Values:;; Any ASCII character
Default:;; \"
[#dataflow-teradata-sync-fetch-size]
Fetch size::
Specify the number of rows at a time to fetch and process in memory.
If you specify zero, the system extracts all rows at once. Optional field.
Example:;; 1000
Valid Values:;; Any numeric value
Default:;; 1000
[#dataflow-teradata-sync-max-ignored-rows]
include::partial$dataflow/max-ignored-rows.adoc[]

[#dataflow-teradata-sync-ts-load-options]
include::partial$dataflow/ts-load-options.adoc[]
