= Date and time formats reference
:last_updated: 11/19/2019
:linkattrs:
:experimental:
:page-layout: default-cloud
:page-aliases: /reference/date-formats-for-loading.adoc
:description: ThoughtSpot supports several date and time formats.


This is a reference for the date and time contexts and formats you can use with ThoughtSpot.
You define data formats in specific contexts and, depending on the context, your choices in data formatting differ.
You must understand date  and time when you load data in CSV format.

NOTE: xref:csv-load-free-trial.adoc[CSV upload] is exclusive to ThoughtSpot Free Trial.
Use xref:connections.adoc[Connections] to access your data in ThoughtSpot Cloud.

Data loading formats do not change how data is displayed in tables and charts.

The context where you _can control_ date and time formats is data modeling.
Data modeling controls how data is displayed in search and their resulting answers.

== Data modeling formats for browser data upload

These date and time formats are supported in a CSV file when uploading through the browser.
You cannot specify the date format;
ThoughtSpot will pick the format that fits your data best:

include::partial$data-modeling-formats.adoc[]

== Data modeling formats

A user with administrative rights can configure data modeling for data on one or all files.
You can set number, date, and currency display formats.
These formats define how these value types display in tables and charts.
See the Admin Guide for more information about data modeling settings.
The following format strings are available for use:

include::partial$data-modeling-strings.adoc[]
