= Cassandra connection reference
:last_updated: 09/10/2021
:experimental:
:linkattrs:
:page-aliases: /data-integrate/dataflow/dataflow-cassandra-reference.adoc

Learn about the fields used to create a Cassandra connection with ThoughtSpot DataFlow.

Here is a list of the fields for a Cassandra connection in ThoughtSpot DataFlow.
You need specific information to establish a seamless and secure connection.

[#connection-properties]
== Connection properties
[#dataflow-cassandra-conn-connection-name]
Connection name:: Name your connection. Mandatory field.
Example:;; CassandraConnection
[#dataflow-cassandra-conn-connection-type]
Connection type:: Choose the Cassandra connection type. Mandatory field.
Example:;; Cassandra
[#dataflow-cassandra-conn-host]
Host:: Specify the hostname or the IP address of the Cassandra system. Mandatory field.
Example:;; www.example.com
[#dataflow-cassandra-conn-port]
Port:: Specify the port associated to the Cassandra system. Mandatory field.
Example:;; 1234
Default:;; 9042
[#dataflow-cassandra-conn-user]
User::
Specify the user to connect to Cassandra.
This user must have data access privileges. Mandatory field.
Example:;; userdi
[#dataflow-cassandra-conn-password]
include::partial$dataflow/password.adoc[]

[#dataflow-cassandra-conn-authentication]
Authentication::
Specifies the type of security protocol to connect to the instance.
Based on the type of security select the authentication type and provide details. Mandatory field.
Example:;; Kerberos
Valid Values:;; None, SSL, LDAP, Kerberos
Default:;; None
[#dataflow-cassandra-conn-row-scan-depth]
Row scan depth::
The maximum number of rows to scan to look for the columns available in a table.
Set this property to gain more control over how the provider applies data types to collections. Optional field.
Example:;; -1
Default:;; 100
Other notes:;; Advanced Configuration
[#dataflow-cassandra-conn-kdc-host]
KDC host:: Specify KDC Host Name where as KDC (Kerberos Key Distribution Center) is a service than runs on a domain controller server role.
Mandatory field. +
 For Kerberos authentication only.
 Example:;;
+
[source]
----
my_email@example.com
----
[#dataflow-cassandra-conn-user-keytab]
User keytab:: To authenticate via a key-tab you must have supporting key-tab file which is generated by Kerberos Admin and also requires the user principal associated with Key-tab (Configured while enabling Kerberos).
Mandatory field.
 For Kerberos authentication only.
 Example:;;
+
[source]
----
/app/keytabs/labuser.keytab
----
[#dataflow-cassandra-conn-default-realm]
Default realm:: A Kerberos realm is the domain over which a Kerberos authentication server has the authority to authenticate a user, host or service.
Mandatory field.
 For Kerberos authentication only.
Example:;;
+
[source]
----
name.example.com
----
[#dataflow-cassandra-conn-kerberos-service-kdc]
Kerberos service KDC:: Specify the Kerberos KDC of the service.
Mandatory field.
 For Kerberos authentication only.
Example:;;
+
[source]
----
www.example.com
----
[#dataflow-cassandra-conn-kerberos-service-realm]
Kerberos service realm:: Specify the Kerberos realm of the service.
Mandatory field. +
 For Kerberos authentication only.
 Example:;; EXAMPLE.COM
[#dataflow-cassandra-conn-kerberos-spn]
Kerberos SPN:: Specify the service principal name (SPN) for the Kerberos Domain Controller.
Mandatory field.
For Kerberos authentication only.
Example:;;
+
[source]
----
cassandra/www.example.com@EXAMPLE.COM
----
[#dataflow-cassandra-conn-ldap-user]
LDAP user:: Specify the default LDAP user used to connect to and communicate with the server, it must be set if the LDAP server do not allow anonymous bind.
Mandatory field.
For LDAP authentication only.
 Example:;; userdi
[#dataflow-cassandra-conn-ldap-password]
LDAP password:: Specify the password for the LDAP User.
Mandatory field. +
 For LDAP authentication only.
 Example:;; pswrd234%!
[#dataflow-cassandra-conn-ldap-server]
LDAP server:: Specify the host name or IP address of the LDAP server.
Mandatory field. +
 For LDAP authentication only.
 Example:;; my_email@example.com
[#dataflow-cassandra-conn-ldap-port]
LDAP port:: Specify the port number that is associated to the LDAP server.
Mandatory field.
 For LDAP authentication only.
 Example:;; 1234
[#dataflow-cassandra-conn-search-filter]
Search filter:: Specify the search filter for looking up usernames in LDAP.
Mandatory field.
 For LDAP authentication only.
 Example:;;
+
[source]
----
sAMAccountName=
----
 Default:;;
+
[source]
----
uid
----
[#dataflow-cassandra-conn-search-base]
Search base:: Specify the search base for the LDAP server, used to look up users.
Mandatory field. +
 For LDAP authentication only.
 Example:;;
+
[source]
----
DC=maxcrc,DC=com
----
[#dataflow-cassandra-conn-trust-store-path]
 Trust store path:: Specify the TLS/SSL client certificate store for SSL Client Authentication (2-way SSL).
Mandatory field. +
 For SSL authentication only.
 Example:;; trust store path
[#dataflow-cassandra-conn-trust-store-password]
Trust store password:: Specify the password for the TLS/SSL client certificate.
Mandatory field. +
 For SSL authentication only.
 Example:;; password
[#dataflow-cassandra-conn-certificate-type]
Certificate type:: Specify the type of key store containing the TLS/SSL client certificate.
Mandatory field. +
 For SSL authentication only.
 Example:;;
+
[source]
----
JKSFILE
----
[#dataflow-cassandra-conn-certificate-subject]
 Certificate subject:: Specify the subject of the TLS/SSL client certificate.
Mandatory field.
 For SSL authentication only.
 Example:;;
+
[source]
----
CN=www.example.com
----

[#dataflow-cassandra-conn-jdbc-options]
include::partial$dataflow/jdbc-options.adoc[]

[#sync-properties]
== Sync properties
[#dataflow-cassandra-sync-column-delimiter]
Column delimiter:: Specify the column delimiter character. Mandatory field.
Example:;; 1
Valid Values:;; Any printable ASCII character or decimal value for ASCII character.
Default:;; 1
[#dataflow-cassandra-sync-enclosing-character]
Enclosing character:: Specify if the text columns in the source data needs to be enclosed in quotes. Optional field.
Example:;;
+
[source]
----
DOUBLE
----
Valid Values:;;
+
[source]
----
SINGLE, DOUBLE
----
Default:;;
+
[source]
----
DOUBLE
----
Other notes:;; This is required if the text data has newline character or delimiter character.
[#dataflow-cassandra-sync-escape-character]
Escape character:: Specify the escape character if using a text qualifier in the source data. Optional field.
Example:;;
+
[source]
----
\"
----
Valid Values:;; Any ASCII character
Default:;;
+
[source]
----
\"
----
[#dataflow-cassandra-sync-max-ignored-rows]
include::partial$dataflow/max-ignored-rows.adoc[]

[#dataflow-cassandra-sync-ts-load-options]
include::partial$dataflow/ts-load-options.adoc[]
