= SAP Adaptive Server Enterprise connection reference
:last_updated: 07/7/2020
:experimental:
:linkattrs:
:page-aliases: /data-integrate/dataflow/dataflow-sap-adaptive-server-enterprise-reference.adoc

Learn about the fields used to create an SAP Adaptive Server Enterprise connection with ThoughtSpot DataFlow.

Here is a list of the fields for an SAP Adaptive Server Enterprise connection in ThoughtSpot DataFlow.
You need specific information to establish a seamless and secure connection.

[#connection-properties]
== Connection properties
[#dataflow-sap-adaptive-server-enterprise-conn-connection-name]
Connection name:: Name your connection. Mandatory field.
Example:;; SAPAdaptiveServerEnterpriseConnection
[#dataflow-sap-adaptive-server-enterprise-conn-connection-type]
Connection type:: Choose the SAP Adaptive Server Enterprise connection type. Mandatory field.
Example:;; SAP Adaptive Server Enterprise
[#dataflow-sap-adaptive-server-enterprise-conn-host]
Host:: Specify the hostname or the IP address of the Sybase system. Mandatory field.
Example:;; www.example.com
[#dataflow-sap-adaptive-server-enterprise-conn-port]
Port:: Specify the port associated to the Sybase system. Mandatory field.
Example:;; 1234
[#dataflow-sap-adaptive-server-enterprise-conn-user]
User::
Specify the user id that will be used to connect to the Sybase system.
This user needs the necessary privileges to access the data in the databases. Mandatory field.
Example:;; userdi
[#dataflow-sap-adaptive-server-enterprise-conn-password]
include::partial$dataflow/password.adoc[]

[#dataflow-sap-adaptive-server-enterprise-conn-version]
Version:: Specify the version of Sybase you are using. Optional field.
Example:;; 16.x
Other notes:;; Advanced configuration.
[#dataflow-sap-adaptive-server-enterprise-conn-jdbc-options]
include::partial$dataflow/jdbc-options.adoc[]

[#sync-properties]
== Sync properties
[#dataflow-sap-adaptive-server-enterprise-sync-column-delimiter]
Column delimiter:: Specify the column delimiter character. Mandatory field.
Example:;; 1
Valid Values:;; Any printable ASCII character or decimal value for ASCII character
Default:;; 1
[#dataflow-sap-adaptive-server-enterprise-sync-fetch-size]
Fetch size::
Specify the number of rows at a time to fetch and process in memory.
If you specify zero, the system extracts all rows at once. Optional field.
Example:;; 1000
Valid Values:;; Any numeric value
Default:;; 1000
[#dataflow-sap-adaptive-server-enterprise-sync-enclosing-character]
Enclosing character:: Specify if the text columns in the source data needs to be enclosed in quotes. Optional field.
Example:;; DOUBLE
Valid Values:;; SINGLE, DOUBLE
Default:;; DOUBLE
[#dataflow-sap-adaptive-server-enterprise-sync-escape-character]
Escape character:: Specify the escape character if using a text qualifier in the source data. Optional field.
Example:;; \"
Valid Values:;; Any ASCII character
Default:;; \"
[#dataflow-sap-adaptive-server-enterprise-sync-max-ignored-rows]
include::partial$dataflow/max-ignored-rows.adoc[]

[#dataflow-sap-adaptive-server-enterprise-sync-ts-load-options]
include::partial$dataflow/ts-load-options.adoc[]
