= Add a MemSQL database connection
:last_updated: 3/22/2021
:page-aliases: /data-integrate/dataflow/dataflow-memsql-add.adoc
:linkattrs:
:experimental:

You can add a connection to a MemSQL database using ThoughtSpot DataFlow.

Follow these steps:

include::partial$add-database-connection.adoc[]

. After you select the MemSQL *Connection type*, the rest of the connection properties appear.
xref:dataflow-memsql-reference.adoc#dataflow-memsql-conn-connection-name[Connection name]::
Name your connection.
+
xref:dataflow-memsql-reference.adoc#dataflow-memsql-conn-connection-type[Connection type]::
Choose the MemSQL connection type.
+
xref:dataflow-memsql-reference.adoc#dataflow-memsql-conn-platform-type[Platform type]::
Specify the environment to execute the connection.
+
xref:dataflow-memsql-reference.adoc#dataflow-memsql-conn-host-name[Host name]::
Specify the hostname or the IP address of the MemSQL system +
xref:dataflow-memsql-reference.adoc#dataflow-memsql-conn-port[Port]::
Specify the port associated to the MemSQL system
xref:dataflow-memsql-reference.adoc#dataflow-memsql-conn-user[User]::
Specify the user id that will be used to connect to the MemSQL system.
This user should have necessary privileges to access the data in the databases.
xref:dataflow-memsql-reference.adoc#dataflow-memsql-conn-password[Password]::
Specify the password for the User
xref:dataflow-memsql-reference.adoc#dataflow-memsql-conn-authentication-type[Authentication type]::
Specifies the type of security protocol to connect to the instance.
Based on the type of security select the authentication type and provide details.
xref:dataflow-memsql-reference.adoc#dataflow-memsql-conn-kdc-host[KDC Host]::
Specify KDC Host Name where as KDC (Kerberos Key Distribution Center) is a service than runs on a domain controller server role.
xref:dataflow-memsql-reference.adoc#dataflow-memsql-conn-default-realm[Default realm]::
A Kerberos realm is the domain over which a Kerberos authentication server has the authority to authenticate a user, host or service.
xref:dataflow-memsql-reference.adoc#dataflow-memsql-conn-keytab[Keytab]::
To authenticate via a key-tab you must have supporting key-tab file which is generated by Kerberos Admin and also requires the user principal associated with Key-tab ( Configured while enabling Kerberos)
xref:dataflow-memsql-reference.adoc#dataflow-memsql-conn-principle[Principle]::
To authenticate via a key-tab you must have supporting key-tab file which is generated by Kerberos Admin and also requires the user principal associated with Key-tab ( Configured while enabling Kerberos)
xref:dataflow-memsql-reference.adoc#dataflow-memsql-conn-ssl-encryption[SSL encryption]::
To ensure the data is encrypted use additional security feature such as SSL.
xref:dataflow-memsql-reference.adoc#dataflow-memsql-conn-trust-store[Trust store]::
Specify the TLS/SSL client certificate store for SSL Client Authentication (2-way SSL)
xref:dataflow-memsql-reference.adoc#dataflow-memsql-conn-trust-store-password[Trust store password]::
Specify the password for the TLS/SSL client certificate.
xref:dataflow-memsql-reference.adoc#dataflow-memsql-conn-jdbc-options[JDBC options]::
Specify the options associated with the JDBC URL.
+
See xref:dataflow-memsql-reference.adoc#connection-properties[Connection properties] for details, defaults, and examples.
. Click *Create connection*.

'''
> **Related information**
>
> * xref:dataflow-memsql-reference.adoc#connection-properties[DataFlow MemSQL connection properties]
