= MySQL connection reference
:last_updated: 09/9/2021
:experimental:
:linkattrs:
:page-aliases: /data-integrate/dataflow/dataflow-mysql-reference.adoc

Learn about the fields used to create a MySQL connection with ThoughtSpot DataFlow.

Here is a list of the fields for a MySQL connection in ThoughtSpot DataFlow.
You need specific information to establish a seamless and secure connection.

[#connection-properties]
== Connection properties
[#dataflow-mysql-conn-connection-name]
Connection name:: Name your connection. Mandatory field.
Example:;; MySQLConnection
[#dataflow-mysql-conn-connection-type]
Connection type:: Choose the MySQL connection type. Mandatory field.
Example:;; MySQL
[#dataflow-mysql-conn-host]
Host:: Specify the hostname or the IP address of the MySQL system. Mandatory field.
Example:;; www.example.com
[#dataflow-mysql-conn-port]
Port:: Specify the port associated to the MySQL system. Mandatory field.
Example:;; 1234
[#dataflow-mysql-conn-user]
User::
Specify the user id that will be used to connect to the MySQL system.
This user should have necessary privileges to access the data in the databases. Mandatory field.
Example:;; userdi
[#dataflow-mysql-conn-password]
include::partial$dataflow/password.adoc[]

////
[#dataflow-mysql-conn-version]
Version:: Specify the MYSQL version being connected to. Optional field.
Example:;; 5.1x
Other notes:;; These are under Advanced configuration.
////
[#dataflow-mysql-conn-jdbc-options]
include::partial$dataflow/jdbc-options.adoc[]

[#sync-properties]
== Sync properties
[#dataflow-mysql-sync-column-delimiter]
Column delimiter:: Specify the column delimiter character. Mandatory field.
Example:;; 1
Valid Values:;; Any printable ASCII character or decimal value for ASCII character
Default:;; The delimiter specified in sync
[#dataflow-mysql-sync-enclosing-character]
Enclosing character:: Specify if the text columns in the source data needs to be enclosed in quotes. Optional field.
Example:;; DOUBLE
Valid Values:;; Single, Double
Default:;; DOUBLE
Other notes:;; This is required if the text data has newline character or delimiter character.
[#dataflow-mysql-sync-escape-character]
Escape character:: Specify the escape character if using a text qualifier in the source data. Optional field.
Example:;; \"
Valid Values:;; Any ASCII character
Default:;; \"
[#dataflow-mysql-sync-fetch-size]
Fetch size::
Specify the number of rows to be fetched at a time and processed in memory.
If the value specified is zero then, all rows are extracted at once. Optional field.
Example:;; 1000
Valid Values:;; Any numeric value
Default:;; 1000
[#dataflow-mysql-sync-max-ignored-rows]
include::partial$dataflow/max-ignored-rows.adoc[]

[#dataflow-mysql-sync-ts-load-options]
include::partial$dataflow/ts-load-options.adoc[]
