= Add a Splunk connection
:last_updated: 3/22/2021
:linkattrs:
:experimental:
:page-aliases: /data-integrate/dataflow/dataflow-splunk-add.adoc

You can add a connection to a Splunk file system using ThoughtSpot DataFlow.

To add a new connection to Splunk, follow these steps:

include::partial$add-database-connection.adoc[]

. After you select the Splunk *Connection type*, the rest of the connection properties appear.
xref:dataflow-splunk-reference.adoc#dataflow-splunk-conn-connection-name[Connection name]::
Name your connection.
xref:dataflow-splunk-reference.adoc#dataflow-splunk-conn-connection-type[Connection type]::
Choose the Splunk connection type.
xref:dataflow-splunk-reference.adoc#dataflow-splunk-conn-server-name[Server name]::
Specify the hostname or the IP address of the Splunk system
xref:dataflow-splunk-reference.adoc#dataflow-splunk-conn-port[Port]::
Specify the port associated to the Splunk system
xref:dataflow-splunk-reference.adoc#dataflow-splunk-conn-user[User]::
Specify the user id that will be used to connect to the Splunk system.
This user should have necessary privileges to access the data in the databases.
xref:dataflow-splunk-reference.adoc#dataflow-splunk-conn-password[Password]::
Specify the password for the User
xref:dataflow-splunk-reference.adoc#dataflow-splunk-conn-jdbc-options[JDBC options]::
Specify the options associated with the JDBC URL.
+
See xref:dataflow-splunk-reference.adoc#connection-properties[Connection properties] for details, defaults, and examples.
. Click *Create connection*.

'''
> **Related information**
>
> * xref:dataflow-splunk-reference.adoc#connection-properties[DataFlow splunk connection properties]
