= Date filters for Answers and Liveboards
:last_updated: 5/24/2023
:linkattrs:
:experimental:
:page-layout: default-cloud
:author: Naomi
:description: ThoughtSpot now supports rolling time windows, as well as fixed date ranges for Search.

We have increased the possible range of dates you can use to filter your Answers and Liveboards. Previously, when adding a date using the filter from the side bar, users were limited to the following conditions: `On (=) <date>`, `On or after (>=) <date>`, `Before (<) <date>`, and `Between <date> and <date>`. Now, we support rolling time windows, as well as fixed date ranges.

For a complete list of the date options ThoughtSpot supports for Answers and Liveboards, see the following options:


. Rolling time windows. Note that in this context, s/m/h/D/W/M/Q/Y means seconds/minutes/hours/days/weeks/months/quarters/years.

* Yesterday
* Today
* Tomorrow
* This s/m/h/D/W/M/Q/Y
* Last s/m/h/D/W/M/Q/Y
* Next s/m/h/D/W/M/Q/Y
* Before this/last/next s/m/h/D/W/M/Q/Y
* After this/last/next s/m/h/D/W/M/Q/Y
* On or after this/last/next s/m/h/D/W/M/Q/Y
* On or before this/last/next s/m/h/D/W/M/Q/Y
* Week to date e.g. 05/15/2023 < 05/22/2023
* Month to date e.g. May
* Quarter to date e.g. 04/01/2023 < 05/22/2023
* Year to date e.g. 2023


. Specific calendar dates or date ranges.

* Is between
* Is not in between
* Is on
* Is not on
* Is after
* Is on or after
* Is before
* Is on or before
* In the month and year e.g. Jan 2020
* In the quarter and year e.g. Q1 2020
* In the year e.g. 2020



////
. All other time windows.

* Multiple conditions e.g. if a user enters “last 30 days next 1 week” or “date != 1 Jan date > 30 Dec”. This would include conditions like “Last/Next X m/h/D/W/M/Q/Y To Last/Next X s/m/h/D/W/M/Q/Y”.
* Is empty / Is not empty (i.e. = null / not null)
* Last X m/h/D/W/M/Q/Y for each Day/Week/Month/Quarter/Year e.g. last 2 days for each month
* Is one of / is not any of <multiple dates>
* X m/h/D/W/M/Q/Y ago e.g. 30 weeks ago
Choose a day of week (Saturdays, Sundays etc.), or a day of month (1st, 2nd, etc.) or a month of year (January, February, etc.) or quarter of year (Q1, Q2, etc.). Complete list:
** day of week
** day of month
** day of quarter
** day of year
** week of month
** week of quarter
** week of year
** month of quarter
** month of year
** quarter of year
* Specify minutes and hours e.g. events between 1 Jun 2021 4:00pm and 1 Jun 2021 5:00pm
////