= Embedding ThoughtSpot for Developers
:last_updated: 11/16/2023
:linkattrs:
:experimental:
:jira: SCAL-193994
:page-layout: default-cloud
:page-aliases: intro-embed.adoc, integration-overview.adoc, spotdev-portal.adoc, auth-overview.adoc, visual-embed-sdk.adoc, custom-actions.adoc, customization-rebranding.adoc, rest-api.adoc, runtime-filters.adoc
:description: Developer users embed ThoughtSpot content in their applications by using ThoughtSpot SDK and APIs.

ThoughtSpot offers a robust API framework with Visual Embed SDK and REST APIs to embed and customize ThoughtSpot components and automate deployments.
By embedding ThoughtSpot Analytics in your app, you can enrich your application experience with ThoughtSpot’s search and live analytics capabilities.


== Embed Licenses
ThoughtSpot provides various licensing schemes to embed ThoughtSpot features in your application. For more information, see the following pages:

* https://developers.thoughtspot.com/docs/get-started-tse[Embed Licenses, window=_blank]
* https://developers.thoughtspot.com/docs/license-feature-matrix[Feature Availability, window=_blank]


== Embedding Methods
Based on your embedding requirements and integration setup, you can use one of the following methods:

=== Embedding with Visual Embed SDK
The Visual Embed SDK provides a Javascript library to embed ThoughtSpot elements in your host application.The Visual Embed SDK is available for installation as a Node Package Manager (NPM) package.
You can use the Visual Embed SDK to embed the following components:

* Use the LiveboardEmbed component to embed a https://developers.thoughtspot.com/docs/embed-a-viz[single visualization, window=_blank] or a full https://developers.thoughtspot.com/docs/embed-liveboard[Liveboard, window=_blank] with multiple visualizations
* Use the AppEmbed library to embed https://developers.thoughtspot.com/docs/full-embed[full ThoughtSpot application, window=_blank] in your app
* Use the SageEmbed package to embed https://developers.thoughtspot.com/docs/embed-nls[Natural Language Search, window=_blank] interface
* Use the SearchEmbed package to embed the ThoughtSpot https://developers.thoughtspot.com/docs/getting-started?pageid=embed-search[Search page, window=_blank] with a pre-selected data source
* Use the SearchBarEmbed component to embed only the ThoughtSpot https://developers.thoughtspot.com/docs/embed-searchbar[Search bar, window=_blank] and data panel


==== Developer Playground
ThoughtSpot provides users with the access to the *Develop* page in the UI.
The ThoughtSpot Developer portal allows you to explore the SDK and APIs, preview code snippets, customize styles and UI elements, and view developer documentation.
You can also add custom actions and configure authentication and security settings for an embedded instance.

IMPORTANT: To access the *Develop* tab users require developer or administrator privileges.

==== Authentication
To authenticate and authorize embed users, you must also configure an authentication method in the SDK.
The following page lists the general recommendations for choosing an authentication method to authenticate embedded application users https://developers.thoughtspot.com/docs/embed-auth[Authentication].

==== Security Settings
To allow your application users to access the embedded content from web browsers, you must set your application as
a trusted host by https://developers.thoughtspot.com/docs/security-settings[adding your application domain and the URL endpoints to the CORS and CSP allowed list,window=_blank] in ThoughtSpot.

=== iFrame embedding without SDK
The Visual Embed SDK is the most convenient way to embed different types of ThoughtSpot content. However, if your portal or system does not have a way to use the Visual Embed SDK JavaScript library, you can embed ThoughtSpot components using an iFrame element.
For example, to embed a Liveboard or Visualization in portals such as Salesforce, SharePoint, Google Sites, or WordPress, you may want to use an iFrame element.
for more information, see the following page https://developers.thoughtspot.com/docs/embed-without-sdk[Embed without SDK,window=_blank].

To learn about the different embedding methods, see https://developers.thoughtspot.com/docs/embed-ts[Embedding Overview,window=_blank].

== REST APIs
ThoughtSpot https://developers.thoughtspot.com/docs/rest-apis[REST API,window=_blank] framework supports several resource collections and operations in two distinct versions. You can explore and access the API endpoints in both these versions:

* *REST API v1* is the legacy framework with several endpoints to create, edit, administer, and manage ThoughtSpot objects and data.
* *REST API v2.0* framework provides enhanced functionality compared to v1 and API experience with an interactive Playground.

The ThoughtSpot *Develop* page provides the REST API v1 and v2.0 Playgrounds to explore the API endpoints, and request and response workflows.

* https://try-everywhere.thoughtspot.cloud/v2/#/everywhere/api/rest/playgroundV1[REST API v1 Playground,window=_blank]

* https://developers.thoughtspot.com/docs/restV2-playground?apiResourceId=http%2Fgetting-started%2Fintroduction[REST API v2 Playground,window=_blank]

For a complete list of API endpoints and information about how to make an API call to these endpoints, see the following pages:

* https://developers.thoughtspot.com/docs/rest-api-getstarted[REST API v1 Getting Started,window=_blank]
* https://developers.thoughtspot.com/docs/rest-api-reference[REST API v1 Reference,window=_blank]
* https://developers.thoughtspot.com/docs/api-auth-session[REST API v1 Authentication,window=_blank]
* https://developers.thoughtspot.com/docs/rest-apiv2-getstarted[REST API v2 Getting Started,window=_blank]
*  https://developers.thoughtspot.com/docs/restV2-playground[REST API v2 Reference,window=_blank]
* https://developers.thoughtspot.com/docs/api-authv2[REST API v2.0 Authentication,window=_blank]

== Customizations

=== Custom Actions
ThoughtSpot supports adding https://developers.thoughtspot.com/docs/custom-action-intro[custom actions,window=_blank] to an Answer or visualization page. For example, you may want to create a custom action that
allows pushing business insights from ThoughtSpot to an external app or a specific URL. Similarly, if you have embedded ThoughtSpot in
another app, you can add a custom action to trigger a callback event to the host application and initiate a response payload.

=== Customize Style
ThoughtSpot allows you to https://developers.thoughtspot.com/docs/style-customization[customize the look and feel of embedded pages,window=_blank] and elements to match the UI style and design of the host application and branding guidelines of your organization.

* You can customize key UI components, such as your application logo, favicon, font style for charts and tables,
background color of the UI, background color of the top navigation panel, the color palette for your charts, page title, and footer text by either using the https://docs.thoughtspot.com/cloud/latest/style-customization[Style customization,window=_blank] menu
in the *Admin* tab or navigating to *Develop > Customizations > Styles*.

* https://developers.thoughtspot.com/docs/custom-css[Custom CSS,window=_blank] also allows developers to override the default styles and UI element specifications in their deployments. Custom CSS provides granular control over the UI appearance and allows you to modify design elements such as buttons, labels, text styles, and typography.

=== Customize Links
ThoughtSpot users receive system-generated links in email notifications, which allow them to access objects such as Liveboards, visualizations or saved answers.
To get more information on this, visit https://developers.thoughtspot.com/docs/customize-links[Customize links,window=_blank].

[#parameters]
== Runtime Overrides
https://developers.thoughtspot.com/docs/runtime-filters[Runtime filters,window=_blank] and https://developers.thoughtspot.com/docs/runtime-params[Parameter overrides,window=_blank] apply filters or Parameter values to a Liveboard or Answer by passing the filter or Parameter properties as query parameters in a Liveboard or visualization URL.
On embedded instances, you can use the Visual Embed SDK to apply filters to an embedded Liveboard or Answer, and update filters using events.

For information about the new features and enhancements introduced in this release, refer to https://developers.thoughtspot.com/docs/whats-new[ThoughtSpot Developer Documentation,window=_blank].

