= Developer
:last_updated: 11/23/2021
:linkattrs:
:experimental:
:page-partial:

NOTE: All documentation for embedding ThoughtSpot software features and components is now available in the ThoughtSpot UI. To view the documentation, go to the *Develop* tab and click **Guides**.

Developer users embed ThoughtSpot content in their application, web page, portal, or business solution by using ThoughtSpot SDK and APIs.

ThoughtSpot provides a Developer portal to application developers to explore the SDK and APIs and embedding workflows. Developers can also customize the look and feel of the embedded ThoughtSpot content and add additional functionality using custom actions.

For more information about embedding ThoughtSpot using Visual Embed SDK and REST APIs, visit the link:https://visual-embed-sdk-7-1-1.vercel.app/docs/[ThoughtSpot Everywhere documentation, window=_blank] site.

////
* link:https://developers.thoughtspot.com/docs/?pageid=embed-analytics[ThoughtSpot Everywhere for embedded analytics]
* link:https://developers.thoughtspot.com/docs/?pageid=integration-guidelines[ThoughtSpot integration guidelines]
* link:https://developers.thoughtspot.com/docs/?pageid=spotdev-portal[ThoughtSpot Developer Portal]
* link:https://developers.thoughtspot.com/docs/?pageid=auth-overview[Authentication and security]
* link:https://developers.thoughtspot.com/docs/?pageid=visual-embed-sdk[Visual Embed SDK]
* link:https://developers.thoughtspot.com/docs/?pageid=custom-action-intro[Custom action configuration]
* link:https://developers.thoughtspot.com/docs/?pageid=customization-intro[Customization and rebranding]
* link:https://developers.thoughtspot.com/docs/?pageid=rest-apis[REST APIs]
* link:https://developers.thoughtspot.com/docs/?pageid=rest-api-reference[REST API reference]
* link:https://developers.thoughtspot.com/docs/?pageid=runtime-filters[Runtime filters]
////



NOTE: To access ThoughtSpot Developer portal, you require developer privileges.

Mobile App::
Access your ThoughtSpot cluster to search answers and pinboards, and create pinboards.
+
See xref:mobile.adoc[].


////
from old user guide


* *xref:navigating-thoughtspot.adoc[Finding your way around]* +
 To make navigation easy, we organized ThoughtSpot into several sections.
You can see them on the menu bar.
* *xref:user-profile.adoc[About the user profile]* +
 The user icon lets you view your profile, or sign out of ThoughtSpot.
* *xref:privileges-end-user.adoc[Understanding privileges]* +
 Your privileges determine the things you can do.
ThoughtSpot sets privileges at the group level.
* *xref:tags.adoc[About tags]* +
 You can create tags to make it easier for people to find data sources and pinboards.

* xref:search.adoc[Use search]
* xref:answers.adoc[Work with Answers]
* xref:filters.adoc[Work with filters]
* xref:charts.adoc[Work with charts]
* xref:formulas.adoc[Work with formulas]
* xref:pinboards.adoc[Use pinboards]
* xref:answer-explorer.adoc[Answer Explorer]
* xref:r-thoughtspot.adoc[About R in ThoughtSpot]
* xref:spotiq.adoc[SpotIQ]
* xref:data-sources.adoc[Work with data]
* xref:help-center.adoc[]
////
