= Eco Mode
:page-last_updated: 5/4/2026
:author: Naomi
:page-layout:
:linkattrs:
:experimental:
:description: Eco Mode is a feature that detects periods of inactivity in a Cloud tenant and stops it to save compute cost if it is found to be continuously inactive.
:jira: SCAL-308679

Eco Mode is a feature that detects periods of inactivity in a Cloud tenant and stops it to save compute cost if it is found to be continuously inactive over an extended period of time. It is enabled for tenants provisioned with a NONPROD-EON SKU.
By default, Eco Mode tracks user activity on instances. If no user activity is detected for 120 minutes, the instance is considered idle and is stopped. To restart an idle instance, you must log in, and interact with a captcha.

== FAQ

How long does it take for an instance to load after it’s been stopped?:: After service is re-enabled, the instance takes about 3-12 minutes to restart.

What kind of instance activities would be considered valid to keep the instance awake?::
Instance wake-up happens due to user-initiated activities.

What happens to scheduled reports when the instance is inactive?::
Scheduled reports fail to send if the instance is inactive. Reports should be scheduled during active time windows.


My cluster is on an EON SKU and I need Eco Mode disabled. What do I do?::
Eco Mode cannot be disabled for clusters on the NONPROD-EON SKU without changing the SKU itself. Contact your ThoughtSpot account team or Customer Success Manager to discuss SKU changes.
