= Security in ThoughtSpot editions
:last_updated: 4/8/2025
:linkattrs:
:experimental:
:page-layout: default-cloud
:page-aliases:
:writer: Mary
:page-toclevels: -1
:description: This article provides information about the security in different ThoughtSpot editions.
:jira: SCAL-246983

This article provides information about the security features in each ThoughtSpot edition.

== Security controls by ThoughtSpot Analytics edition

[cols="20%,20%,20%,20%,20%" stripes="even"]
|===
.^|Control ^.^|Team or Essentials +++<br>+++ (multi-tenant) ^.^|Pro +++<br>+++ (multi-tenant) ^.^|Pro ^.^|Enterprise

|SOC Type 2 and ISO 27001 compliance
^.^|image:checkmark_black.svg[Yes,15]
^.^|image:checkmark_black.svg[Yes,15]
^.^|image:checkmark_black.svg[Yes,15]
^.^|image:checkmark_black.svg[Yes,15]

|Complete data isolation
^.^|image:checkmark_black.svg[Yes,15]
^.^|image:checkmark_black.svg[Yes,15]
^.^|image:checkmark_black.svg[Yes,15]
^.^|image:checkmark_black.svg[Yes,15]

|Disk data encryption at rest
^.^|image:checkmark_black.svg[Yes,15]
^.^|image:checkmark_black.svg[Yes,15]
^.^|image:checkmark_black.svg[Yes,15]
^.^|image:checkmark_black.svg[Yes,15]

|Data encryption in transit - TLS
^.^|image:checkmark_black.svg[Yes,15]
^.^|image:checkmark_black.svg[Yes,15]
^.^|image:checkmark_black.svg[Yes,15]
^.^|image:checkmark_black.svg[Yes,15]

|Row-level security
^.^|image:checkmark_black.svg[Yes,15]
^.^|image:checkmark_black.svg[Yes,15]
^.^|image:checkmark_black.svg[Yes,15]
^.^|image:checkmark_black.svg[Yes,15]

|System reporting and monitoring
^.^|
^.^|image:checkmark_black.svg[Yes,15]
^.^|image:checkmark_black.svg[Yes,15]
^.^|image:checkmark_black.svg[Yes,15]

|Single Sign-On via SAML
^.^|
^.^|image:checkmark_black.svg[Yes,15]
^.^|image:checkmark_black.svg[Yes,15]
^.^|image:checkmark_black.svg[Yes,15]

|Single Sign-On via OAuth and OIDC
^.^|
^.^|image:checkmark_black.svg[Yes,15]
^.^|image:checkmark_black.svg[Yes,15]
^.^|image:checkmark_black.svg[Yes,15]

|Custom URL
^.^|
^.^|
^.^|image:checkmark_black.svg[Yes,15]
^.^|image:checkmark_black.svg[Yes,15]

|Advanced data encryption at rest - file / folder / db
^.^|
^.^|
^.^|
^.^|image:checkmark_black.svg[Yes,15]

|Private link between ThoughtSpot and cloud data warehouses
^.^|
^.^|
^.^|
^.^|image:checkmark_black.svg[Yes,15]

|URL whitelabeling
^.^|
^.^|
^.^|
^.^|image:checkmark_black.svg[Yes,15]

|Virtual Private Network (VPN)
^.^|
^.^|
^.^|
^.^|image:checkmark_black.svg[Yes,15]
|===

== Security controls by ThoughtSpot Embedded edition

[cols="30%,10%,10%,10%" stripes="even"]
|===
.^|Control ^.^|Developer +++<br>+++ (multi-tenant) ^.^|Pro ^.^|Enterprise

|SOC Type 2 and ISO 27001 compliance
^.^|image:checkmark_black.svg[Yes,15]
^.^|image:checkmark_black.svg[Yes,15]
^.^|image:checkmark_black.svg[Yes,15]

|Complete data isolation
^.^|image:checkmark_black.svg[Yes,15]
^.^|image:checkmark_black.svg[Yes,15]
^.^|image:checkmark_black.svg[Yes,15]

|Disk data encryption at rest
^.^|image:checkmark_black.svg[Yes,15]
^.^|image:checkmark_black.svg[Yes,15]
^.^|image:checkmark_black.svg[Yes,15]

|Data encryption in transit - TLS
^.^|image:checkmark_black.svg[Yes,15]
^.^|image:checkmark_black.svg[Yes,15]
^.^|image:checkmark_black.svg[Yes,15]

|Row-level security
^.^|image:checkmark_black.svg[Yes,15]
^.^|image:checkmark_black.svg[Yes,15]
^.^|image:checkmark_black.svg[Yes,15]

|System reporting and monitoring
^.^|
^.^|image:checkmark_black.svg[Yes,15]
^.^|image:checkmark_black.svg[Yes,15]

|Single Sign-On via SAML
^.^|
^.^|image:checkmark_black.svg[Yes,15]
^.^|image:checkmark_black.svg[Yes,15]

|Single Sign-On via OAuth and OIDC
^.^|
^.^|image:checkmark_black.svg[Yes,15]
^.^|image:checkmark_black.svg[Yes,15]

|Custom URL
^.^|
^.^|image:checkmark_black.svg[Yes,15]
^.^|image:checkmark_black.svg[Yes,15]

|Advanced data encryption at rest - file / folder / db
^.^|
^.^|
^.^|image:checkmark_black.svg[Yes,15]

|Private link between ThoughtSpot and cloud data warehouses
^.^|
^.^|
^.^|image:checkmark_black.svg[Yes,15]

|URL whitelabeling
^.^|
^.^|
^.^|image:checkmark_black.svg[Yes,15]

|Virtual Private Network (VPN)
^.^|
^.^|
^.^|image:checkmark_black.svg[Yes,15]
|===