= ThoughtSpot Enterprise and Pro editions
:last_updated: 4/24/2024
:linkattrs:
:experimental:
:page-layout: default-cloud
:page-aliases:
:writer: Mary
:page-toclevels: -1
:description: This article provides information about the features supported in ThoughtSpot Enterprise and Pro editions.
:jira: SCAL-SCAL-214091

This article provides information about the features supported in ThoughtSpot Enterprise and Pro editions.

|===
| Capability | Enterprise edition | Pro edition

| Authentication: SAML SSO with IAM V2|Yes|Yes (only with IAM V2)|

VPN, Privatelink|Yes|No (Bridge connectivity GA 10.1.0.cl)|

Roles Based Access Control (RBAC)|Yes|Yes (default)|

Style & Chart Customization|Yes|Yes|

System Activities/Liveboards|Yes|Yes

a|Application Settings Admin panel:

* Search

* SpotIQ

* CSV Upload

* Early access features
|Yes|No

|Customizations with ThoughtSpot flags and URL allowlisting|Yes|No

|Security Settings (Develop tab)
|Yes|Yes

|Custom URL Support|Yes|No
|===

== Upcoming changes for new Pro Editions customers
* Early Access and Beta features are not supported for ThoughtSpot Pro edition customers.
* Custom URLs and custom domains are not currently supported for Pro edition customers.
* Customer specific allowlisting, URLs, and images are not supported for ThoughtSpot Pro edition customers.
* Customization with ThoughtSpot flags are not supported. Flags, if any, will only be applied during a weekly maintenance window.

////
Only cluster-level flag application is supported for multi-tenant clusters. These flags are applicable to all ThoughtSpot editions customers hosted on the multi-tenant cluster. Flags are applied only during a maintenance window.

Early Access/Beta features are not supported for ThoughtSpot editions customers.

Custom URLs are not supported for Pro edition customers. Only the URLs listed below are supported for customer clusters:

* TS Cloud URL for TSA Pro:
** <customername>.prod01-<na/eu/ap>.thoughtspot.cloud
* TS Cloud URL for TSE Pro:
** <customername>.tseprod01-<na/eu/ap>.thoughtspot.cloud

Customer specific allowlisting is not supported for ThoughtSpot editions customers.

COMs is not enabled for ThoughtSpot editions customers.
////
