= Administration in ThoughtSpot editions
:last_updated: 4/29/2025
:linkattrs:
:experimental:
:page-layout: default-cloud
:page-aliases:
:writer: Mark
:page-toclevels: -1
:description: This article provides information about the capabilities administrators have in each ThoughtSpot edition.
:jira: SCAL-179604, SCAL-205004 (remove build edition from TSE), SCAL-246983

This article provides information about the capabilities administrators have in each ThoughtSpot edition. For details on the specific features of the Team, Essentials, Pro, and Enterprise editions, see the https://www.thoughtspot.com/pricing[pricing page^] on ThoughtSpot.com. _Edition_ refers to the ThoughtSpot license your company has purchased.

== Administrator capabilities by edition

[cols="30%,10%,10%,10%,10%" stripes="even"]
|===
.^|Capability ^.^|Team ^.^|Essentials ^.^|Pro ^.^|Enterprise

|Org creation and management
^.^|
^.^|
^.^|
^.^|image:checkmark_black.svg[Yes,15]

|User management
^.^|{set:cellbgcolor:#FFFFF}image:checkmark_black.svg[Yes,15]
^.^|image:checkmark_black.svg[Yes,15]
^.^|image:checkmark_black.svg[Yes,15]
^.^|image:checkmark_black.svg[Yes,15]

|Group management
^.^|
^.^|image:checkmark_black.svg[Yes,15]
^.^|image:checkmark_black.svg[Yes,15]
^.^|image:checkmark_black.svg[Yes,15]

|Role management (RBAC)
^.^|
^.^|
^.^|image:checkmark_black.svg[Yes,15]
^.^|image:checkmark_black.svg[Yes,15]

|SAML authentication
^.^|
^.^|
^.^|image:checkmark_black.svg[Yes,15]
^.^|image:checkmark_black.svg[Yes,15]

|System Liveboards
^.^|image:checkmark_black.svg[Yes,15]
^.^|image:checkmark_black.svg[Yes,15]
^.^|image:checkmark_black.svg[Yes,15]
^.^|image:checkmark_black.svg[Yes,15]

|Developer privileges*
^.^|
^.^|
^.^|image:checkmark_black.svg[Yes,15] *#*
^.^|image:checkmark_black.svg[Yes,15]

|Style customization*
^.^|
^.^|
^.^|image:checkmark_black.svg[Yes,15]
^.^|image:checkmark_black.svg[Yes,15]
|===
+*+ _Requires license for ThoughtSpot Embedded or internal analytics add-on._

+#+ _Requires license for ThoughtSpot Embedded or internal analytics add-on. Not available for multi-tenant editions._



== Application settings by edition

The following table shows which application settings for each edition that an administrator can change, and the ones that are set globally by ThoughtSpot.

[cols="20%,20%,20%,20%,20%" stripes="even"]
|===
.^|Capability ^.^|Team and Essentials +++<br>+++ (multi-tenant) ^.^|Pro +++<br>+++ (multi-tenant) ^.^|Pro ^.^|Enterprise

|ThoughtSpot AI
^.^|
^.^|*
^.^|#
^.^|#

|Search & SpotIQ
^.^|
^.^|*
^.^|image:checkmark_black.svg[Yes,15]
^.^|image:checkmark_black.svg[Yes,15]

|Style customization
^.^|image:checkmark_black.svg[Yes,15]
^.^|image:checkmark_black.svg[Yes,15]
^.^|image:checkmark_black.svg[Yes,15]
^.^|image:checkmark_black.svg[Yes,15]

|Chart customization
^.^|image:checkmark_black.svg[Yes,15]
^.^|image:checkmark_black.svg[Yes,15]
^.^|image:checkmark_black.svg[Yes,15]
^.^|image:checkmark_black.svg[Yes,15]

|CSV upload
^.^|
^.^|
^.^|image:checkmark_black.svg[Yes,15]
^.^|image:checkmark_black.svg[Yes,15]

|Early access features
^.^|
^.^|
^.^|image:checkmark_black.svg[Yes,15]
^.^|image:checkmark_black.svg[Yes,15]

|Version Control
^.^|
^.^|
^.^|image:checkmark_black.svg[Yes,15]
^.^|image:checkmark_black.svg[Yes,15]

|Data modeling
^.^|
^.^|
^.^|image:checkmark_black.svg[Yes,15]
^.^|image:checkmark_black.svg[Yes,15]

|Administration
^.^|
^.^|*
^.^|image:checkmark_black.svg[Yes,15]
^.^|image:checkmark_black.svg[Yes,15]
|===

+*+ _Enabled and set globally by ThoughtSpot._

+#+ _Changeable by ThoughtSpot administrator if the customer has licensed ThoughtSpot on a query consumption plan, per-user plan, or if the Spotter add-on has been purchased._

== Application settings for Pro multi-tenant customers

Some of the application settings are established by ThoughtSpot for multi-tenant Essentials and Pro customers.  Below is a list of settings and how they are configured in your application.

=== ThoughtSpot AI (only available for Pro multi-tenant)

* AI Answers is enabled
* AI sample questions is enabled.
* AR Answers on Liveboards is enabled.
* AI synonyms is disabled.
* AI Worksheet description is disabled.
* AI narratives for SpotIQ is enabled.
* New Spotter is enabled.
* LLM of choice is OpenAI.
* AI search disabled on _all models_ in the data workspace. User must add AI search by model.

=== Search and SpotIQ

* All search and SpotIQ settings are enabled.
* KPI alerts are enabled.

=== Data Modeling

* You can create and edit models (Worksheets are excluded).
* You cannot create Worksheets using the UI during the period of deprecation.
* Joins tab in React is enabled.
* Importing Etags using TML is enabled.

=== CSV upload

* Disabled

=== Administration

* Hidden Org name for users of single Orgs is enabled.
* Org URL sharing is disabled.

== Other application differences for Pro multi-tenant and Essentials customers

* Customers of a multi-tenant solution must use the default domain name provided by ThoughtSpot.
* For VPN and AWS PrivateLink, customers must be on a single tenant version of ThoughtSpot. Multi-tenant Pro and Essentials editions are not supported.
* Customer-specific whitelisting is not supported.