= Administration in ThoughtSpot editions
:last_updated: 11/05/2021
:linkattrs:
:experimental:
:page-layout: default-cloud
:page-aliases:
:page-toclevels: -1
:description: This article provides information about the capabilities administrators have in each ThoughtSpot edition.
:jira: SCAL-179604

This article provides information about the capabilities administrators have in each ThoughtSpot edition. For details on the specific features of the Team, Essentials, Pro, and Enterprise editions, see the https://www.thoughtspot.com/pricing[pricing page^] on ThoughtSpot.com. _Edition_ refers to the ThoughtSpot license your company has purchased.

== Administrator capabilities by edition

[cols="30%,10%,10%,10%,10%" stripes="even"]
|===
.^|Capability ^.^|Team ^.^|Essentials ^.^|Pro ^.^|Enterprise

|Org creation and management
^.^|
^.^|
^.^|
^.^|image:checkmark_black.svg[Yes,15]

|User management
^.^|{set:cellbgcolor:#FFFFF}image:checkmark_black.svg[Yes,15]
^.^|image:checkmark_black.svg[Yes,15]
^.^|image:checkmark_black.svg[Yes,15]
^.^|image:checkmark_black.svg[Yes,15]

|Group management
^.^|
^.^|
^.^|image:checkmark_black.svg[Yes,15]
^.^|image:checkmark_black.svg[Yes,15]

|Role management (RBAC)
^.^|
^.^|
^.^|image:checkmark_black.svg[Yes,15]
^.^|image:checkmark_black.svg[Yes,15]

|SAML authentication
^.^|
^.^|
^.^|image:checkmark_black.svg[Yes,15]
^.^|image:checkmark_black.svg[Yes,15]

|System Liveboards
^.^|image:checkmark_black.svg[Yes,15]
^.^|image:checkmark_black.svg[Yes,15]
^.^|image:checkmark_black.svg[Yes,15]
^.^|image:checkmark_black.svg[Yes,15]

|Developer privileges*
^.^|
^.^|
^.^|image:checkmark_black.svg[Yes,15]
^.^|image:checkmark_black.svg[Yes,15]

|ThoughtSpot Sage preview
^.^|image:checkmark_black.svg[Yes,15]
^.^|image:checkmark_black.svg[Yes,15]
^.^|image:checkmark_black.svg[Yes,15]
^.^|image:checkmark_black.svg[Yes,15]

|Data management privileges
^.^|image:checkmark_black.svg[Yes,15]
^.^|image:checkmark_black.svg[Yes,15]
^.^|image:checkmark_black.svg[Yes,15]
^.^|image:checkmark_black.svg[Yes,15]

|SpotIQ privileges
^.^|
^.^|image:checkmark_black.svg[Yes,15]
^.^|image:checkmark_black.svg[Yes,15]
^.^|image:checkmark_black.svg[Yes,15]
|===

+*+ _Requires license for ThoughtSpot Everywhere or internal analytics add-on._

