= Type conversion functions
:last_updated: 11/15/2019
:linkattrs:
:experimental:
:page-layout: default-cloud
:page-aliases: /complex-search/conversion-formulas.adoc
:description: Learn about data type conversion functions.
:jira: SCAL-193283

Some formulas require the input to be of a particular data type.
If you find that you want to pass a value to the function, but it is of the wrong data type, you can convert it using a conversion formula.

The following are the conversion formulas:

include::partial$conversion-func.adoc[]

'''
> **Related information**
>
> * xref:formulas-cumulative.adoc[Cumulative functions]
> * xref:formulas-moving.adoc[Moving functions]
> * xref:formulas-aggregation-flexible.adoc[Flexible aggregation functions]
> * xref:formulas-aggregation-group.adoc[Grouping functions]
> * xref:formulas-aggregation-filtered.adoc[Filtered aggregation functions]
> * xref:aggregation-filters.adoc[Aggregate filters]
> * xref:formulas-date.adoc[Date functions]
> * xref:formulas-simple-operations.adoc[Percent calculations]
> * xref:formulas-logical-operations.adoc[Formula operators]
> * xref:formulas-nested.adoc[Nested formulas]
> * xref:formulas-chasm-trap.adoc[Formulas for chasm traps]