= About date formulas
:last_updated: 02/01/2021
:linkattrs:
:experimental:
:page-partial:
:page-aliases: /advanced-search/formulas/date-formulas.adoc

Learn about date formulas.

Date functions are useful when you want to compare data collected between two date periods.
Date formulas allow you to apply date related functions to your formulas.

== Date formulas

The date formulas include:

include::partial$date-func.adoc[]

== Calculate date formulas

Calculating date formulas is useful when you want to compare data from different date periods.
Here are some examples of using date formulas:

=== Example 1

The following example shows you how to create formulas that you can use to compare data from this week to last week.

* The formula for this week is: `week ( today () ) - week (date)`
* The formula for last week is: `diff_days ( week ( today () ) ) , week ( date ) )`

=== Example 2

The following example shows you how to calculate the percent increase from the last date period to this period in terms of revenue.

. Create the formula: `this week revenue = sum ( if ( this week ) then revenue else 0 )`
. Then create the formula: `last week revenue = sum ( if (last week ) then revenue else 0 )`
. Use xref:formulas-nested.adoc[nested formulas] to calculate the percent increase by creating a parent formula: `percent increase = ( ( this week revenue - last week revenue) / last week revenue ) * 100`

[#fiscal-and-gregorian-calendars]
== Fiscal and Gregorian calendars

For the following date formulas, you can further specify either `fiscal` or Gregorian `calendar` on which to base date calculations.
(If you do not specify a calendar type, the formula defaults to standard Gregorian, with the year starting in January.)

* `day_number_of_quarter`
* `day_number_of_year`
* `month_number`
* `month_number_of_quarter`
* `quarter_number`
* `start_of_quarter`
* `start_of_year`
* `week_number_of_quarter`
* `week_number_of_year`
* `year`

Your ThoughtSpot administrator and ThoughtSpot Support can xref:custom-calendar.adoc[set up a fiscal calendar year] to start on any month.
If the `fiscal` year is not explicitly configured in the system, `fiscal` defaults to January, the same as the Gregorian `calendar`.

For example, the formula `month_number_of_quarter (05/31/2014)` would return `2` based on the default Gregorian calendar, whereas the formula `month_number_of_quarter (05/31/2014, 'fiscal')` would return `1` if your administrator has configured the fiscal calendar to start in May.

'''
> **Related information**
>
> * xref:formula-reference.adoc#date-functions[Date functions] in the xref:formula-reference.adoc[Formula function reference]
> * xref:custom-calendar.adoc[Set up a fiscal calendar year]
