= Getting Started with ThoughtSpot Free Trial
:last_updated: 11/05/2021
:linkattrs:
:experimental:
:page-layout: default-cloud
:page-aliases: /release/ts-cloud-getting-started-free-trial.adoc
:description: Complete the following steps to get the most value from your data during the trial period.
:jira: SCAL-166161, SCAL-166160, SCAL-166159, SCAL-135769, SCAL-185089, SCAL-185892, SCAL-184808


Completing the following steps helps you and other users in your organization get the most value from your data during the trial period.
A little bit of time setting up ThoughtSpot has a big impact.

== Before you begin

Before you start, review these talks to identify your ideal use case.
The context helps you make account-related decisions and use ThoughtSpot effectively.

video::_HqB__xe3bo[youtube,title="ThoughtSpot Success Series: Defining a ThoughtSpot Use Case",width="375",height="210",frameborder="0",allow="accelerometer"]

video::W5dwAmLSwT0[youtube,title="ThoughtSpot Success Series: Use Case Prioritization",width="375",height="210",frameborder="0",allow="accelerometer"]


We highly recommend that you register for the free ThoughtSpot U course that covers the material in this section, https://training.thoughtspot.com/getting-started-with-thoughtspot-cloud[Getting Started with ThoughtSpot Analytics Cloud].

We also provide these instructions in link:{attachmentsdir}/ts-cloud-free-trial-get-started.pdf[PDF format].

== Step 1: Create a ThoughtSpot Community account

A ThoughtSpot Community account lets you ask questions in our product forums, explore best practices from other customers, sign up for events, and contact support.

https://community.thoughtspot.com/customers/s/login/SelfRegister[Create a Community account]

== Step 2: Activate your ThoughtSpot Cloud account

Check your inbox for a welcome email and click the link to access the free trial cluster.

Note that if you use Google sign-in, you do not need to activate your account.

Stay logged in to complete the rest of the setup.

Based on the URL of your trial environment, please whitelist accordingly:

* my1.thoughtspot.cloud: `34.199.33.15`
* my2.thoughtspot.cloud: `3.223.10.183`
* my3.thoughtspot.cloud: `52.203.101.217`
** team1.thoughtspot.cloud: `44.218.85.113`
** team2.thoughtspot.cloud: `52.20.14.188`
** team3.thoughtspot.cloud: `44.209.73.62`

=== Password requirements

When you start using the ThoughtSpot Free Trial, you see the ThoughtSpot password verification checklist.
Passwords must meet the following requirements:

* 8 or more characters.
* 1 uppercase letter, 1 lowercase letter, 1 number, and 1 special character.
* Pass a complexity and uniqueness test that checks for known patterns and simple words.
ThoughtSpot rejects passwords that are not complex enough.
For more information, see the https://github.com/dropbox/zxcvbn[Dropbox password library].
* No blocked words.
By default, the blocked words are: your username and any part of your display name.

== Step 3: Connect to your data source

Completing this step lets all users in your organization perform live queries.
Choose your cloud data warehouse type, and follow the connection instructions.

* xref:connections-amazon-athena.adoc[Amazon Athena]
* xref:connections-amazon-aurora-mysql.adoc[Amazon Aurora MySQL]
* xref:connections-amazon-aurora-postgresql.adoc[Amazon Aurora PostgreSQL]
* xref:connections-amazon-rds-mysql.adoc[Amazon RDS MySQL]
* xref:connections-amazon-rds-postgresql.adoc[Amazon RDS PostgreSQL]
* xref:connections-redshift.adoc[Amazon Redshift]
* xref:connections-synapse.adoc[Azure Synapse]
* xref:connections-databricks.adoc[Databricks]
* xref:connections-denodo.adoc[Denodo]
* xref:connections-dremio.adoc[Dremio]
* xref:connections-genericjdbc.adoc[Generic JDBC]
* xref:connections-gbq.adoc[Google BigQuery]
* xref:connections-mysql.adoc[MySQL]
* xref:connections-adw.adoc[Oracle]
* xref:connections-postgresql.adoc[PostgreSQL]
* xref:connections-presto.adoc[Presto]
* xref:connections-hana.adoc[SAP HANA]
* xref:connections-singlestore.adoc[SingleStore]
* xref:connections-snowflake.adoc[Snowflake]
* xref:connections-sql-server.adoc[SQL Server]
* xref:connections-starburst.adoc[Starburst]
* xref:connections-teradata.adoc[Teradata]
* xref:connections-trino.adoc[Trino]
* xref:getting-started-free-trial.adoc#upload-csv[Upload flat data file (CSV)]

== Step 4: Model your data for searches

ThoughtSpot automatically optimizes your data for search.
It models and configures most details.
However, we recommend that you adjust the modeling settings to align with your identified use cases, and improve the experience for other users.

* xref:data-modeling.adoc[Data modeling]
* xref:tables-join.adoc[Join tables]

== Step 5: Create a Worksheet

Worksheets make it easier for everyone in your organization to search data and create visualizations.
Use the following step-by-step instructions to create your first Worksheet.

* xref:worksheets.adoc[Create and use Worksheets]

== Step 6: Learn search essentials

After you finish creating Worksheets, you are ready to search.
Review the key concepts to get started, and how to help others in your organization become effective searchers.

* xref:search.adoc[Search overview]
* xref:keywords.adoc[Keyword reference]
* xref:charts.adoc[Understanding charts]
* xref:formulas.adoc[Understanding formulas in searches]

== Step 7: Invite users

When using Free Trial, you can invite up to 5 users. To invite another user, visit the *Admin* tab and click *+ Invite teammates* in the left menu. In the pop-up window, select your desired display name, and enter the emails of the teammates you want to invite and (optional) message to the invite email. Click *Send invite*.

== Step 8: Share a Liveboard

Liveboards are interactive collections of charts and tables.
Set up a shared Liveboard now, so everyone who joins your organization can access valuable information.

* xref:liveboard.adoc[Basic Liveboard usage]
* xref:share-liveboards.adoc[]

== Keep learning

* https://cloud-docs.thoughtspot.com[ThoughtSpot Cloud documentation]
* https://training.thoughtspot.com/getting-started-with-thoughtspot-cloud[Training: Getting started with ThoughtSpot Analytics Cloud]
* https://youtu.be/EYHa8Ck3tdw[ThoughtSpot Success Series]
* xref:support-handbook.adoc[ThoughtSpot Support Handbook] (link:{attachmentsdir}/support-handbook.pdf[PDF])

== Get connected

* https://www.youtube.com/thoughtspot[Visit YouTube channel]
* https://thoughtspotcs-officehours.youcanbook.me/[Schedule office hours]
* https://groups.thoughtspot.com/events/#/list[Join upcoming events]

== Add data files

include::partial$csv-upload.adoc[]
