= High-Risk Activity
:last_updated: 6/17/2022
:experimental:
:linkattrs:
:page-layout: default-cloud
:page-aliases: /release/high-risk.adoc

Customer understands that ThoughtSpot Cloud is intended for information searching and analytics, and must use ThoughtSpot Cloud within the intended business purposes described in the Documentation and not for any purpose that requires fail-safe processing performance, including stock trading, financial transaction processing such as credit card processing, business automation, electronic funds transfer, check clearing, management of hazardous facilities or applications for which failure could result in death, personal injury, or severe physical or environmental damage (“High Risk Activity”). ThoughtSpot, its licensors and suppliers expressly disclaim all warranties of fitness for any such use and Customer releases and holds ThoughtSpot, its licensors and suppliers harmless from liability arising out of use of ThoughtSpot Cloud for or in relation to any High Risk Activity.