= High Availability and resilience
:last_updated: 10/20/2022
:linkattrs:
:experimental:
:page-layout: default-cloud
:description: Learn how to enable High Availability, or multi-node clusters, with support across AWS Availability Zones.

High Availability (HA) ensures that the ThoughtSpot Cloud application experiences near-zero downtime in the case of AWS Availability Zone (AZ) failures. ThoughtSpot provides HA through deployment spanning multiple AZs. This ensures that, in the case of an AWS Availability Zone failure, ThoughtSpot continues to function.

[#user-impact]
== Impact on users

When one AWS Availability Zone fails, ThoughtSpot migrates all activity to the functioning Availability Zones. The ThoughtSpot application remains available and accessible during the entire AZ failure.

[#enable]
== Enable High Availability

Enabling High Availability requires the purchase of a new SKU. Contact your ThoughtSpot sales representative for information on how to purchase the HA SKU. After you purchase the HA SKU, you can contact {support-url} to enable High Availability in your environment.