= ThoughtSpot Cloud Documentation
:page-layout: home-branch-cloud
:page-last_updated: Jul 10, 2026
:experimental:

.Welcome to our new site!
[.announce-box-narrow]
--
We've redesigned the site with a new navigation structure, updated search features, and a fresh new look.

xref:doc-update.adoc[*Learn more*]
--

== Spotter agents

Automate key parts of your analytics workflow—from exploring and analyzing data to building visualizations and modeling your data. Each Spotter agent is built for a specific task, so you can move faster from question to insight without manual steps slowing you down.

[.card-gradient-box]
====
[.card-link-grid-4]
****
[.card-link]
--
image::Spot.svg[Icon,36,36]

xref:spotter.adoc[Spotter]

Discover insights from your data just by asking.
--

[.card-link]
--
image::Lumos.svg[Icon,36,36]
xref:spotter-model-create.adoc[SpotterModel]

Turn your raw data into models in minutes.
--

[.card-link]
--
image::Kaios.svg[Icon,36,36]

xref:spotter-viz.adoc[SpotterViz]

Plan your story and build a Liveboard automatically.
--

[.card-link-ext]
--
image::Camo.svg[Icon,36,36]

https://developers.thoughtspot.com/docs/SpotterCode[SpotterCode^]

Build with AI-assisted +
coding in your IDE.
--
****
====

== Quick links

[.card-link-grid]
****
[.card-link]
--
[.light-only]
image::megaphone_purp.svg[Icon,36,36]
[.dark-only]
image::megaphone-dark.svg[Icon,36,36]

xref:notes.adoc[What's new]

Learn about the latest features and enhancements.
--

[.card-link]
--
[.light-only]
image::settings.svg[Icon,36,36]
[.dark-only]
image::settings-dark.svg[Icon,36,36]

xref:administration.adoc[Administration]

Manage users, settings, and security for ThoughtSpot Cloud.
--

[.card-link]
--
[.light-only]
image::rocket.svg[Icon,36,36]
[.dark-only]
image::rocket-dark.svg[Icon,36,36]

xref:ts-cloud-getting-started.adoc[Deploying ThoughtSpot]

Learn how to set up ThoughtSpot Cloud for your organization.
--

[.card-link]
--
[.light-only]
image::compass.svg[Icon,32,32]
[.dark-only]
image::compass-dark.svg[Icon,32,32]

xref:user-onboarding-experience.adoc[Getting started for end users]

Learn how to get started with ThoughtSpot Cloud.
--

[.card-link-ext]
--
[.light-only]
image::embedded.svg[Icon,32,32]
[.dark-only]
image::embedded-dark.svg[Icon,32,32]

https://developers.thoughtspot.com/docs[Embedded^]

Embed AI-powered analytics into your own applications.
--

[.card-link]
--
[.light-only]
image::icon-insights-light.svg[Icon,32,32]
[.dark-only]
image::icon-insights-dark.svg[Icon,32,32]

xref:thoughtspot-homepage.adoc[Homepage and navigation]

Learn about ThoughtSpot's homepage and navigation.
--
// third row

[.card-link]
--
[.light-only]
image::layout-dashboard.svg[Icon,36,36]
[.dark-only]
image::layout-dashboard-dark.svg[Icon,36,36]

xref:liveboards.adoc[Liveboards]

Monitor your data with interactive, +
real-time dashboards.
--

[.card-link]
--
[.light-only]
image::semantic_layer.svg[Icon,36,36]
[.dark-only]
image::semantic_layer-dark.svg[Icon,36,36]

xref:semantic-layer.adoc[Spotter semantics]

Learn about our semantic layer for +
governed insights.
--

[.card-link]
--
[.light-only]
image::chart-spline.svg[Icon,36,36]
[.dark-only]
image::chart-spline-dark.svg[Icon,36,36]

xref:analyst-studio-getting-started.adoc[Analyst Studio]

Learn how to get started with +
Analyst Studio.
--
****

////
[.card-link-grid]
****
[.card-link]
--
image::spotteragent.svg[Icon,36,36]

xref:Spotter.adoc[Spotter]

Learn how to deploy, coach and use Spotter.
--

[.card-link]
--

image::spottermodel.svg[Icon,36,36]

xref:spotter-model-create.adoc[SpotterModel]

Turn raw data into models in minutes.
--

[.card-link]
--

image::spotterviz.svg[Icon,36,36]

xref:spotter-viz.adoc[SpotterViz]

Plan your story and build a Liveboard automatically.
--

[.card-link-ext]
--
image::spottercode.svg[Icon,36,36]

https://developers.thoughtspot.com/docs/SpotterCode[SpotterCode^]

AI-assisted coding right in your IDE.
--
////
