= Indexing Queries Liveboard
:last_updated: 6/28/23
:author: Naomi
:linkattrs:
:experimental:
:page-layout: default-cloud
:description: We introduced a Liveboard to help admin users improve query performance.

Use the Indexing Queries Liveboard to understand and improve indexing query performance.

You can use this Liveboard to answer the following questions:

* How many indexing queries are made?
* What queries are failing, and why?
* How long are the indexing queries taking?
* Which connections have the most failures so that the admin can easily identify and fix them?

To access this Liveboard, go to the *Liveboards* tab and search for *Indexing Queries*. Note that this Liveboard is only visible to admin users.

The visualizations on this Liveboard include the following:

* Filters
+
NOTE: Users can filter by connections and tables, and aggregate over the last `n` days.
* Total queries
* Failed queries
* Average query latency(s)
* Maximum query latency(s)
* Query count per connection
* Failed queries per connection
* Query latency
* Success rate over time
* Connections with failing queries
* Columns with highest query latency
