= Embedded analytics
:last_updated: 2/23/2022
:linkattrs:
:experimental:
:page-layout: default-cloud
:page-aliases: /admin/ts-cloud/intro-embed.adoc
:description: Use the Visual Embed SDK, REST APIs, and developer tools to embed search, visualizations, Liveboards, and the full ThoughtSpot experience.

ThoughtSpot provides a low-code embedded analytics platform for developers and product owners to build interactive data apps and integrate ThoughtSpot features directly into their apps, products, or services. Using ThoughtSpot Embedded, you can embed search-driven analytics, infuse insights into your application, and enrich your website, portal, or product with ThoughtSpot’s analytical capabilities.

With ThoughtSpot Embedded, you can use the Visual Embed SDK to programmatically embed search-driven analytics, Liveboards, visualizations, or the full ThoughtSpot experience in your app. ThoughtSpot also supports REST API services to allow its users to embed objects, query data, perform administrative operations, and automate deployments.

== Embedding methods

You can use one of the following methods to embed ThoughtSpot in your host application:

Visual Embed SDK::
The Visual Embed SDK provides Javascript-based embed packages and client libraries to embed and customize ThoughtSpot components in your web application. The SDK package includes separate libraries for embedding Search, Liveboard, full ThoughtSpot application, or a single visualization. To explore the Visual Embed APIs, navigate to the *Develop* tab and click *Visual Embed Playground*.
+
For more information, see xref:visual-embed-sdk.adoc[Visual Embed SDK].

REST APIs::

ThoughtSpot REST API v1 framework allows client applications to query data, add and modify ThoughtSpot objects programmatically, and perform administrative tasks.
+
The REST API v2.0 introduces new endpoints, improved request and response workflows, and an interactive Playground experience.
+
For more information, see xref:rest-api.adoc[REST APIs].

== ThoughtSpot Developer portal

ThoughtSpot users with developer and admin privileges can access the Developer portal by navigating to the *Develop* tab in the UI. The *Develop* tab consists of the following features:

* Developer Playground for Visual Embed SDK and REST APIs
* Customization features such as xref:customization-rebranding.adoc[Style customization], xref:custom-actions.adoc[Custom actions], and https://developers.thoughtspot.com/docs/?pageid=customize-links[system-generated link customization, window=_blank].
* Authentication and security settings for embedded ThoughtSpot instances
* Developer documentation

For more information, see xref:spotdev-portal.adoc[ThoughtSpot Developer Portal].

