= Embedded analytics with ThoughtSpot Everywhere
:last_updated: 2/23/2022
:linkattrs:
:experimental:
:page-layout: default-cloud
:page-aliases: /admin/ts-cloud/intro-embed.adoc
:description: Use the Visual Embed SDK, REST APIs, and  developer tools to embed search, visualizations, Liveboards, and the full ThoughtSpot experience.



ThoughtSpot Everywhere provides a low-code embedded analytics platform for developers and product owners to build interactive data apps and integrate ThoughtSpot features directly in their apps, products, or services. Using ThoughtSpot Everywhere, you can embed search-driven analytics, infuse insights into your application, and enrich your website, portal, or product with ThoughtSpot’s analytical capabilities.

With ThoughtSpot Everywhere, you can use the Visual Embed SDK to programmatically embed search-driven analytics, Liveboards, visualizations, or the full ThoughtSpot experience in your app. ThoughtSpot also supports REST API services to allow its users to embed objects, query data, perform administrative operations, and automate deployments.

== Embedding methods

You can use one of the following methods to embed ThoughtSpot in your host application:

Using Visual Embed SDK::
 Visual Embed SDK provides JavaScript libraries for embedding ThoughtSpot features such as the Search, Liveboards, visualizations, and the full application experience in your product or portal.
+
For more information, see xref:visual-embed-sdk.adoc[Visual Embed SDK].

Using REST APIs::
The ThoughtSpot REST API framework supports several resource collections and endpoints using which you can programmatically query data, manage objects, and administer users, groups, and sessions.
+
For more information, see xref:rest-api.adoc[REST APIs].

== ThoughtSpot Developer portal

ThoughtSpot users with developer and admin privileges can access the Developer portal by navigating to the *Develop* tab in the UI. The *Develop* tab consists of the following features:

* Visual Embed Playground
* REST API Playground [.badge.badge-update]#Beta#
* xref:customization-rebranding.adoc[Style customization]
* xref:custom-actions.adoc[Custom actions]
* Link format customization for embedded instances
* Authentication and security settings for embedded ThoughtSpot instances
* Developer Guides

For more information, see xref:spotdev-portal.adoc[ThoughtSpot Developer Portal].
For information about feature availability, see link:https://developers.thoughtspot.com/docs/?pageid=license-feature-matrix[Feature matrix and license types, window=_blank].

////
== UI customization and rebranding

If you have embedded the ThoughtSpot application in your host application, you can customize the look and feel of ThoughtSpot UI to match your organization's branding guidelines.

You can customize the ThoughtSpot application UI by using the style customization settings in the Developer portal.

For more information, see xref:customization-rebranding.adoc[Customization and rebranding].

== Custom actions

ThoughtSpot allows you to add custom actions to the embedded Liveboards and visualizations.

For example, you can add a button to the ThoughtSpot UI that will trigger a workflow in your parent application.

For more information, see xref:custom-actions.adoc[Custom action configuration].
////

== Get started with ThoughtSpot Everywhere

You can explore the APIs, evaluate embedding workflows, or obtain a license to get full access to ThoughtSpot Everywhere features.

* To explore embedding workflow, APIs, and SDK, visit the https://try-everywhere.thoughtspot.cloud/v2/#/everywhere[Developer Playground, window=_blank].
* To load your own data and evaluate the embedding workflows, sign up for a https://www.thoughtspot.com/trial?tsref=webtopnav[Free Trial, window=_blank].
* To get full access to ThoughtSpot Everywhere features, you can purchase the ThoughtSpot Everywhere Edition license.
For more information, see https://developers.thoughtspot.com/docs/?pageid=get-started-tse[Get started with ThoughtSpot, window=_blank].
