= Known issues
:keywords: known issues
:last_updated: 2/1/2023
:author: Mark Plummer
:experimental:
:page-layout: default-cloud
:linkattrs:

These are the known issues in this release of ThoughtSpot Cloud.

[#releases-9-6-x]
== 9.6.0.cl known issues

[cols="17%,39%,38%"]
|===
|Issue ID |Description|Symptoms, conditions, and workaround

|SCAL-182743
|Updates to runtime filters in a Liveboard do not appear in the downloaded Liveboard.
a|*Symptoms*:

Runtime filter updates do not appear in a downloaded Liveboard.

*Conditions*:

Update a runtime filter in a Liveboard and then download it.

*Workaround*:

None.

|SCAL-182610
|No fragments are shown when feedback is given to an AI-generated answer.
a|*Symptoms*:

No fragments are shown.

*Conditions*:

When feedback is given to an AI-generated answer when the Cloud instance is hosted on GCP.

*Workaround*:

None.

|SCAL-182316
|Errors in PDF exported from Liveboard.
a|*Symptoms*:

Extra page and distorted footer appear in exported PDF.

*Conditions*:

Exporting from a Liveboard.

*Workaround*:

None.

|SCAL-177835
|The group_aggregate function works differently with null values between ThoughtSpot Cloud and Software versions.
a|*Symptoms*:

Using an "if" statement in a formula to determine if a number is NULL generates a different result with ThoughtSpot Software compared to ThoughtSpot Cloud.

*Conditions*:

Using ThoughtSpot 9.5.0.cl.

*Workaround*:

None.

|SCAL-174571
|Configuration inconsistent in pivot tables.
a|*Symptoms*:

If you specify data fields below, the data is aggregated:

- Rows: B, E
- Measure: D
- Columns: A, C

However, if you move C to “Rows” section, the following error is displayed:

"This configuration is invalid for the current chart type."

Moreover, if you configure data fields the following way, empty cells are displayed:

- Rows: B, E
- Measure: D
- Columns: C, A

*Conditions*:

Using a pivot table.

*Workaround*:

None.

|SCAL-162316
|Menu options are displayed for broken visualizations.
a|*Symptoms*:

Visualization which doesn't load still shows menu options.

*Conditions*:

Visualization failed to load.

*Workaround*:

None.
|===
