= Known issues
:keywords: known issues
:last_updated: 7/15/2024
:author: Mark Plummer
:experimental:
:page-layout: default-cloud
:page-toclevels: -1
:linkattrs:
:jira: SCAL-206809 (9.12.0.cl), SCAL-210330 (9.12.5.cl), SCAL-214503 (10.0.0.cl),

These are the known issues in this release of ThoughtSpot Cloud.

[#releases-10-0-x]
== 10.0.0.cl known issues

[cols="17%,39%,38%"]
|===
|Issue ID |Description|Symptoms, conditions, and workaround

|SCAL-213767
|"Error encountered during analysis" due to "DB queries".
a|*Symptoms*:
SpotIQ Analyze request fails due to failure in DbQuery calls.


*Conditions*:
Using a hard-coded value as the timeout while making DbQueries from SpotIQ causes DbQuery to fail when there are many SpotIQ Analyze requests.

*Workaround*:
None.

|SCAL-196442
|Sorting issues with measure inside a pivot table [Charts item].
a|*Symptoms*:
Sorting a field which contains a measure only updates rows.

*Conditions*:
Sorting a pivot table using the search bar, or by updating sorting by a measure.

*Workaround*:
Sort the respective pivot table by rows or columns using the corresponding header.
|SCAL-214389
|Information center does not display in the selected language after the user changes the language.

a|*Symptoms*:
Information center is not translated immediately after user changes the language.

*Conditions*:
User changes the system language in their user profile.

*Workaround*:
User must manually refresh the page to apply the new language setting in the information center. This step ensures that the content is displayed in the newly selected language.
|SCAL-214993
|New Homepage experience does not load KPI watchlist charts when KPI is from a view.

a|*Symptoms*:
KPI charts fail to load in the right panel of the Watchlist in the homepage.

*Conditions*:
New homepage experience is enabled. Adding a KPI to the watchlist from a Liveboard Personalized View

*Workaround*:
None.
|===
