= Known issues
:keywords: known issues
:last_updated: 5/8/2024
:author: Mark Plummer
:experimental:
:page-layout: default-cloud
:page-toclevels: -1
:linkattrs:
:jira: SCAL-206809 (9.12.0.cl)

These are the known issues in this release of ThoughtSpot Cloud.

[#releases-9-12-x]
== 9.12.0.cl known issues

[cols="17%,39%,38%"]
|===
|Issue ID |Description|Symptoms, conditions, and workaround

|SCAL-205315
|Natural language search on Looker worksheet, with or without joins, does not work.
a|*Symptoms*:

Natural language search doesn't work on Looker worksheets.

*Conditions*:

Looker worksheet using Looker connection.

*Workaround*:

None.

|SCAL-204811
|User can't update datatype from `INT 64` to `DOUBLE`
a|*Symptoms*:

Unable to update datatype from INT64 to DOUBLE.
Even when data has decimals, it imports as INT64.

*Conditions*:

Trying to use a table that has columns with decimal values while creating custom SQL views using custom SQL.

*Workaround*:

None.
|SCAL-204463
|KPI alert failure.
a|*Symptoms*:

Alert and subscription emails are not sent.

*Conditions*:

KPI comparison with a single datapoint.

*Workaround*:

None.
|SCAL-203974
|Iterative change analysis causes the page to crash.
a|*Symptoms*:

Page crashes when doing iterative change analysis

*Conditions*:

Date columns in CCA modal (intermittent). No flags to be enabled. Selecting column with 'Time Bucket' as an axis menu option, and changing the date bucket.

*Workaround*:

None.
|SCAL-197408
|Tooltip does not appear in charts when forecasting is enabled.
a|*Symptoms*:

Tooltip does not appear.

*Conditions*:

Chart with forecasting feature enabled.

*Workaround*:

Contact support to disable the forecasting feature.
|===