= Known issues
:keywords: known issues
:last_updated: 1/16/2024
:author: Mark Plummer
:experimental:
:page-layout: default-cloud
:linkattrs:
:jira: SCAL-183017

These are the known issues in this release of ThoughtSpot Cloud.

[#releases-9-8-x]
== 9.8.0.cl known issues

[cols="17%,39%,38%"]
|===
|Issue ID |Description|Symptoms, conditions, and workaround

|SCAL-176744
|The Org admin can't see the count of Answers and Liveboards under the System Activities tab. However, the same information can be seen by primary Org admin.
a|*Symptoms*:

Total count of Answers and Liveboard under the *Admin* > *System activities* tab is displayed as 0 for the non-primary Org admin.

*Conditions*:

9.8.0.cl release.

*Workaround*:

The values are shown correctly for the primary Org admin.

|SCAL-186976
|Including the "Worksheet Name" and/or "Worksheet Description" when searching in the Product Usage worksheet causes bloated and incorrect results.
a|*Symptoms*:

- Bloated and/or incorrect results while analysing worksheets from Product Usage data
- Incorrect mapping of the table sub-type to the table name. Any such incorrect mapping of data can happen if the worksheet name/worksheet description columns are used.

*Conditions*:

Including the "Worksheet Name" and/or "Worksheet Description" when searching in the Product Usage worksheet. 9.8.0.cl release.

*Workaround*:

Do not use "Worksheet Name" and/or "Worksheet Description" columns in the Product Usage worksheet.
Instead use "Table Sub Type = 'worksheet' " filter if working with worksheets and "Table Name" to fetch the worksheet's name.

|SCAL-186191
|Including the "Worksheet Name" and/or "Worksheet Description" when searching in the Product Usage worksheet causes bloated and incorrect results.
a|*Symptoms*:

System becomes unresponsive due to running out of memory in the tomcat service.

*Conditions*:

Downloading a large CSV file. 9.8.0.cl release.

*Workaround*:

Workaround is to reduce the maxNumExportRows size to less value(default 1M), so that memory utilisation will be less. For assistance with this, contact {support-url}.

|SCAL-185567
|Liveboard is not available for a non-admin user, but it is available in a URL using the pinboard GUID.
a|*Symptoms*:

Liveboard is not available on the list page for the non-admin user, but it is accessible via URL using pinboard GUID.

*Conditions*:

Strict column-level security (CLS) enabled on the cluster. Non-admin user trying to view a Liveboard having a Liveboard filter on a column which the user does not have access to. 9.8.0.cl release.

*Workaround*:

None.

|SCAL-184586
|Cannot search a table associated with a problematic connection.
a|*Symptoms*:

User sees a 'connection not available' error, when searching on any table associated with a problematic connection due to connection leak.

*Conditions*:

Sync schedule exists and one the scheduled syncs failed. 9.8.0.cl release.

*Workaround*:

Remove the sync schedules.

|SCAL-180968
|Incorrect y-axis is plotted for a line chart when it is resized.
a|*Symptoms*:

- Some horizontal/vertical lines are visible for the line charts.
- The plotted min and max y-axis values don't align with the visible min and max data points.
- Line chart seems distorted/broken.

*Conditions*:

An answer with line-chart visualization.

*Workaround*:

- If the issue is observed in a Liveboard tile, modifying the tile size should help. Try modifying the tile size until the visualization looks as expected, and save the affected tile in that size.
- If the issue is observed on the Answers page and the browser window is either zoomed-in or zoomed-out, try changing it back to 100% zoom. If the browser window is resized, try resizing it to a more normal size.

|SCAL-187638
|Filters in Explore mode do not work
a|*Symptoms*:

Applying a new filter to a column that already has filters, removes the existing filters.

*Conditions*:

An answer with line-chart visualization.

*Workaround*:

Change filters using filter chips in the visualization's UI instead of using Explore.


|===