= Known issues
:keywords: known issues
:last_updated: 11/8/2022
:experimental:
:page-layout: default-cloud
:linkattrs:

These are the known issues in this release of ThoughtSpot Cloud.

[#releases-8-9-x]
== 8.9.0.cl known issues

[cols="17%,39%,38%"]
|===
|Issue ID |Description|Symptoms, conditions, and workaround

|SCAL-132991
|A red error banner appears on top of search with the first search with embedded ThoughtSpot.
a|*Symptoms*:

ThoughtSpot Everywhere customers see a red bar error at the top of the page where ThoughtSpot is embedded.

*Conditions*:

A red bar error appears at the top of the search page.

*Workaround*:

None, but functionality still works.

|SCAL-129691
|Error displayed on pinned headline tiles in Liveboards: “UniqueCount is not supported for the current query.”
a|*Symptoms*:

- If you try to edit the pinned visualization, the Edit page will show the entire Answer that the pinned headline came from. If the headline summary in the Answer page is displayed --, this is a good indication that the current aggregation selected is not compatible with the column that it is summarizing.

- This only happens with formula columns.

- Pinning the headline to a Liveboard is not locked in the UI; instead, the visualization tile will display the execution error message specified in the *Description* section for the issue when we attempt to retrieve the actual summary

*Conditions*:

- The headline is over a formula column that contains any of unique_count, unique_count_if, group_unique_count, approx_unique_count.

- The formula’s unique count portion uses columns that come from tables that are Embrace (non-Falcon, external data warehouse, etc.) tables.

- The selected headline aggregation for the formula (the headline visualization is at the bottom of the main Answer visualization) is Table Aggregate.

*Workaround*:

Set the selected headline aggregation to something other than Table Aggregate. Usually, TOTAL is a sufficient replacement for Table Aggregate and better matches customer use cases.

|SCAL-133971
|Unable to view Liveboard data using a Snowflake connection
a|*Symptoms*:

TBD

*Conditions*:

TBD

*Workaround*:

TBD

|SCAL-133405
|Importing a TML file causes a timeout error.
a|*Symptoms*:

TBD

*Conditions*:

TBD

*Workaround*:

TBD

|SCAL-133392
|Table TML cannot be edited in a Snowflake connection.
a|*Symptoms*:

TBD

*Conditions*:

TBD

*Workaround*:

TBD

|SCAL-133345
|Attempting to import a table causes an error.
a|*Symptoms*:

TBD

*Conditions*:

TBD

*Workaround*:

TBD

|SCAL-131419
|Some Answers in a Liveboard are not rendered, even if correct.
a|*Symptoms*:

TBD

*Conditions*:

TBD

*Workaround*:

TBD

|SCAL-131417
|Filters cannot be applied to a Liveboard after upgrade.
a|*Symptoms*:

TBD

*Conditions*:

TBD

*Workaround*:

TBD

|SCAL-126105
|Resizing a table column in a Liveboard causes the Liveboard to reload.
a|*Symptoms*:

TBD

*Conditions*:

TBD

*Workaround*:

TBD

|SCAL-125154
|When syncing user groups using the RLS sync user group, users are not added and the user groups are empty.
a|*Symptoms*:

TBD

*Conditions*:

TBD

*Workaround*:

TBD

|SCAL-121775
|After upgrade, a "Visualization data could not be retrieved. Invalid table/query set" error appears.
a|*Symptoms*:

TBD

*Conditions*:

TBD

*Workaround*:

TBD

|===
