= Known issues
:keywords: known issues
:last_updated: 8/21/2024
:author: Mark Plummer
:experimental:
:page-layout: default-cloud
:page-toclevels: -1
:linkattrs:
:jira: SCAL-206809 (9.12.0.cl), SCAL-210330 (9.12.5.cl), SCAL-214503 (10.0.0.cl), SCAL-216844 (10.1.0.cl)

These are the known issues in this release of ThoughtSpot Cloud.

[#releases-10-0-x]
== 10.1.0.cl known issues

[cols="17%,39%,38%"]
|===
|Issue ID |Description|Symptoms, conditions, and workaround

|SCAL-220290
|Filter chips overlap on a chart after clicking the downward-facing arrow to display all filters in Explore mode.
a|*Symptoms*:
Filter chips overlap on a chart.

*Conditions*:
Using Explore mode on a visualisation with more filters than can be displayed on one line and clicking the downward-facing arrow to display all filters.

*Workaround*:
Manually collapse the filter by clicking the upward-facing arrow.

|SCAL-178756
|Red banner error is displayed without any proper error message when the original verifier of the Liveboard is deleted from the system.
a|*Symptoms*:
Red banner displayed without error message.


*Conditions*:
When the requester or verifier of a Liveboard is deleted.

*Workaround*:
For a verified Liveboard,  there's no impact on functionality. The user can close the error banner.
For a pending request, and the requester is deleted, the user must contact {support-url} to delete the request.
|SCAL-220378
|When converting formulas from a Worksheet to a Model a "Current Operation not allowed" or "Invalid Yaml/Json Syntax" appears.
a|*Symptoms*:
A "Current Operation not allowed" or "Invalid Yaml/Json Syntax" appears.

*Conditions*:
When importing TML that was previously exported and contains formulas that contain the following:

* Double quotes used with hard-coded strings.
For example: concat ("order" + column_Name)
* Filters with null values.

*Workaround*:
Manually add back in the quotes to the TML and then import again.

|SCAL-217451
|'ThoughtSpot Cloud Answer Not Deletable'
a|*Symptoms*:
Unable to delete or update any unused formula.

*Conditions*:
Tables with specific columns exist with joins between them. An answer was generated using columns from these tables, including a formula that referred to a column in one of the tables. When later deleting the table containing that column, the attempt to remove the formula failed because it referenced a column that no longer exists.

*Workaround*:

. Make a copy of the answer, as all unused formulas will be permanently deleted.
. Export the TML of the answer using ‘Export Answer & Associated Objects (models, etc.)’.
. Delete the current answer.
. Import the answer TML zip file. All unused formulas will be removed from the answers.

|SCAL-220182
|Error creating a user in an Org when a user of the same name existed in a deleted Org.
a|*Symptoms*:
The following message appears: 'The user could not be created. User with this username already exists. Please choose a different username.'

*Conditions*:
IAMv2 and Orgs enabled cluster. Trying to create a user with same name as a user in a deleted Org.

*Workaround*:
Manually delete users before deleting the org or contact {support-url} if you are facing this issue for an already deleted Org.
|===
