= Known issues
:keywords: known issues
:last_updated: 2/1/2023
:author: Mark Plummer
:experimental:
:page-layout: default-cloud
:linkattrs:

// scal-176840

These are the known issues in this release of ThoughtSpot Cloud.

[#releases-9-5-x]
== 9.5.0.cl known issues

[cols="17%,39%,38%"]
|===
|Issue ID |Description|Symptoms, conditions, and workaround

|SCAL-164158
|Liveboards are slow to render.
a|*Symptoms*:

Liveboards render slowly.

*Conditions*:

TBD.

*Workaround*:

TBD.

|SCAL-163806
|Group aggregate and unique count in the same query do not work.
a|*Symptoms*:

Using a group aggregate grouping on a column with unique count in the same query does not work.

*Conditions*:

`enableGroupingByGroupAggregrates` feature enabled.

*Workaround*:

Disable the `enableGroupingByGroupAggregrates` feature.

|SCAL-161766
|Null formulas are not handled properly in TML.
a|*Symptoms*:

Migrating Answers and Liveboards from Software to Cloud fails.

*Conditions*:

Null formulas exist.

*Workaround*:

Remove null formulas.

|SCAL-172348
|_User_admin_ granular privilege is not being followed when user is created by ThoughtSpot public v1 APIs.
a|*Symptoms*:

_User_admin_ can't create, read, update, or delete users by using ThoughtSpot public v1 user APIs.

*Conditions*:

Role-based access control (RBAC) is enabled and customer is using ThoughtSpot public v1 APIs.

*Workaround*:

Perform the required operations using the _admin_ privilege or use ThoughtSpot Everywhere (TSE) v2 APIs with the _User_admin_ privilege.

| SCAL-175396
| PDF Exports in Visualization format does not allow note tiles to be downloaded.
| *Symptoms*:

Note tile will not be downloaded.

*Conditions*:

Note tile is added to a Liveboard.

*Workaround*:

Export the Liveboard in the Liveboard Format.
|===
