= Known issues
:keywords: known issues
:last_updated: 6/5/2024
:author: Mark Plummer
:experimental:
:page-layout: default-cloud
:page-toclevels: -1
:linkattrs:
:jira: SCAL-206809 (9.12.0.cl), SCAL-210330 (9.12.5.cl)

These are the known issues in this release of ThoughtSpot Cloud.

[#releases-9-12-x]
== 9.12.5.cl known issues

[cols="17%,39%,38%"]
|===
|Issue ID |Description|Symptoms, conditions, and workaround

|SCAL-196442
|Sorting issues with a measure inside a pivot table
a|*Symptoms*:

Only rows are updated accordingly when sorting by measure on a pivot table.

*Conditions*:

- When user sorts a pivot table using search bar
- When user updates sorting by the measure

*Workaround*:

None.

Only row-level sorting is used when applying default-sorting by measure on a pivot table.
|SCAL-206079
|"Generating AI synonyms" message appears when AI-generated synonyms feature is not enabled.
a|*Symptoms*:

"Generating AI synonyms" message appears.

*Conditions*:

Saving a Worksheet when AI-generated synonyms feature is *not* enabled.

*Workaround*:

None.
|SCAL-208599
|Updating fonts in *Admin* > *Style customization* page does not work.
a|*Symptoms*:

Updating fonts by selecting ones from the default list in *Admin* > *Style customization* page fails for non-primary Org Admin users.

*Conditions*:

Updating cluster-level fonts in a non-primary Org of a cluster.

*Workaround*:

Upload new fonts instead of choosing ones shown by default.
|===
