= Link parameters across Models in a Liveboard
:page-last_updated: 3/23/2026
:linkattrs:
:experimental:
:page-layout: default-cloud
:page-aliases:
:description: You can link parameters across Models in a Liveboard to reduce the effort required to individually set identical parameters for each Model.
:jira: SCAL-276233

You can link parameters of the same type across multiple Models used in a Liveboard. This reduces the repetitive effort needed to set identical parameters for each Model. Only parameters of the same data type can be linked. Example: Integer parameters can only be linked with other integer parameters. The link must be between *different* Models. Parameters from the same Model cannot be linked.

A link can have any number of parameters. It is not limited to two. If a parameter is linked as secondary to another parameter (which would be the primary), the secondary parameter chip will automatically be dropped from the Liveboard’s header.

NOTE: This is different from linked filters behavior where you must manually remove the chip before linking the filter.
