= ThoughtSpot mobile overview
:last_updated: 02/09/2022
:linkattrs:
:experimental:
:page-layout: default-cloud
:page-aliases: /admin/mobile/use-mobile.adoc
:description: ThoughtSpot mobile provides access to ThoughtSpot from your phone.



The ThoughtSpot mobile app allows you to discover insights in seconds from billions of rows of data, right from the palm of your hand.
You can access your ThoughtSpot cluster to search Answers and Liveboards.
You can also create Liveboards using existing Answers and use Liveboard filters.


== Who uses ThoughtSpot mobile
ThoughtSpot mobile can be used by anyone who wants to connect to their ThoughtSpot cluster from a mobile client.

== Use cases
Use ThoughtSpot mobile to access Answers and create or filter Liveboards.

== Latest updates

Version 2.8.1 supports more features that were previously available only through the ThoughtSpot web app, including:

* xref:mobile-kpi-change-analysis.adoc[KPI change analysis]
* xref:mobile-localization.adoc[Internationalization and localization]
* xref:mobile-push-notifications.adoc[ThoughtSpot mobile push notifications]
* xref:mobile-deep-linking.adoc[Deep linking]
* xref:mobile-drill-down.adoc[Drill down]


For details, see xref:notes-mobile.adoc[Mobile release notes].



'''
> **Related information**
>
> * xref:mobile-deploy.adoc[Deploy]
> * xref:mobile-install.adoc[Install and set up]
> * xref:mobile-faq.adoc[FAQ]
> * xref:notes-mobile.adoc[Release notes]