= Comparing ThoughtSpot mobile and web
:last_updated: 14/12/2023
:linkattrs:
:experimental:
:page-layout: default-cloud
:page-aliases:
:description: Comparing ThoughtSpot mobile and web.



The following section compares the features available in the ThoughtSpot mobile and web apps.

== Consumption features

[cols="20%,10%,10%" stripes="even", width="70%"]
|===
.^|Feature ^.^|Mobile ^.^|Web

|Answers
^.^|image:checkmark_black.svg[Yes,15]

^.^| image:checkmark_black.svg[Yes,15]
|Liveboards
^.^|image:checkmark_black.svg[Yes,15]

^.^|image:checkmark_black.svg[Yes,15]
|Tag favorite Answer/Liveboard
^.^|image:checkmark_black.svg[Yes,15]


^.^|image:checkmark_black.svg[Yes,15]
|Home Liveboard
^.^|image:checkmark_black.svg[Yes,15]

|
|Share
^.^|image:checkmark_black.svg[Yes,15]

^.^|image:checkmark_black.svg[Yes,15]

|Present Liveboard
|

^.^|image:checkmark_black.svg[Yes,15]
|Download as PDF
|

^.^|image:checkmark_black.svg[Yes,15]
|Schedule Liveboard
|
^.^|image:checkmark_black.svg[Yes,15]
|===
{empty} +

=== Liveboard features

[cols="20%,10%,10%" stripes="even", width="70%"]
|===
.^|Feature ^.^|Mobile ^.^|Web

|Tabs

^.^|image:checkmark_black.svg[Yes,15]
^.^|image:checkmark_black.svg[Yes,15]
|Note tiles
^.^|image:checkmark_black.svg[Yes,15]
^.^|image:checkmark_black.svg[Yes,15]

|Custom tile sizes

|
^.^|image:checkmark_black.svg[Yes,15]
|Filters
^.^|image:checkmark_black.svg[Yes,15]
^.^|image:checkmark_black.svg[Yes,15]

|Mandatory filters

^.^|image:checkmark_black.svg[Yes,15]
^.^|image:checkmark_black.svg[Yes,15]
|Parameters

|
^.^|image:checkmark_black.svg[Yes,15]
|===
{empty} +

=== Analysis features

[cols="20%,10%,10%" stripes="even", width="70%"]
|===
.^|Feature ^.^|Mobile ^.^|Web

|Drill down
^.^|image:checkmark_black.svg[Yes,15]
^.^|image:checkmark_black.svg[Yes,15]

|Apply filters
^.^|image:checkmark_black.svg[Yes,15]
^.^|image:checkmark_black.svg[Yes,15]

|Answer Explorer
|
^.^|image:checkmark_black.svg[Yes,15]

|SpotIQ
^.^|image:checkmark_black.svg[Yes,15]
^.^|image:checkmark_black.svg[Yes,15]

|Monitor KPI
^.^|image:checkmark_black.svg[Yes,15]
^.^|image:checkmark_black.svg[Yes,15]

|TS Sync
|
^.^|image:checkmark_black.svg[Yes,15]
|===
{empty} +

=== Creation features

[cols="20%,10%,10%" stripes="even", width="70%"]
|===
.^|Feature ^.^|Mobile ^.^|Web

|Search Data
|

^.^|image:checkmark_black.svg[Yes,15]
|Search Answers and Liveboards
^.^|image:checkmark_black.svg[Yes,15]
^.^|image:checkmark_black.svg[Yes,15]

|Create/edit Liveboard
|

^.^|image:checkmark_black.svg[Yes,15]
|Create/edit Answers
|

^.^|image:checkmark_black.svg[Yes,15]
|===
{empty} +

=== Miscellaneous features

[cols="20%,10%,10%" stripes="even", width="70%"]
|===
.^|Feature ^.^|Mobile ^.^|Web

|Localization

^.^|image:checkmark_black.svg[Yes,15]
^.^|image:checkmark_black.svg[Yes,15]
|Admin functions

|
^.^|image:checkmark_black.svg[Yes,15]
|===

== Important limitations
The ThoughtSpot mobile app has the following limitations:

* No support for pivot tables, geo maps, or sankey charts

* No support for sorting on Answers

