= ThoughtSpot mobile overview
:last_updated: 02/09/2022
:linkattrs:
:experimental:
:page-layout: default-cloud
:page-aliases: /admin/mobile/use-mobile.adoc
:description: ThoughtSpot mobile provides access to ThoughtSpot from your phone.



The ThoughtSpot mobile app allows you to discover insights in seconds from billions of rows of data, right from the palm of your hand.
You can access your ThoughtSpot cluster to search Answers and Liveboards.


== Who uses ThoughtSpot mobile
ThoughtSpot mobile can be used by anyone who wants to connect to their ThoughtSpot cluster from a mobile client.

== Use cases
Use ThoughtSpot mobile to access Answers and create or filter Liveboards.

== Latest updates

Version 2.9.0 supports more features that were previously available only through the ThoughtSpot web app, including:

* You can now view note tiles for Liveboards in the mobile app.
* Improved loading of priority information when opening Liveboards and Answers in ThoughtSpot mobile.


For details, see xref:notes-mobile.adoc[Mobile release notes].



'''
> **Related information**
>
> * xref:mobile-deploy.adoc[Deploy]
> * xref:mobile-install.adoc[Install and set up]
> * xref:mobile-faq.adoc[FAQ]
> * xref:notes-mobile.adoc[Release notes]