= Change the join rule or RLS setting for a Model
:last_updated: 5/22/2025
:linkattrs:
:experimental:
:page-layout: default-cloud-deprecated
:page-aliases: /admin/worksheets/change-inclusion-rule.adoc
:description: As long as you have permissions to edit a Worksheet, you can always go into it and set a different join or RLS rule.
:jira: SCAL-264258

If you find that the charts and tables built on a Model contain a large number of null values (which display as `+{blank}+` in the web browser), you can fix this by changing the xref:join-worksheet-edit.adoc#[internal joins] for the Model.

If you have the *Can administer ThoughtSpot* privilege or the *Can manage data* plus edit privilege on a Model, you can edit the Model and change its RLS or other key settings.

== Change/configure a Model

Before working through this procedure, make sure you are familiar with how the following affect data:

* xref:join-worksheet-edit.adoc#[internal Model joins]
* xref:model-progressive-joins.adoc#[Model join rule]
* xref:security-rls-implement.adoc#[row-level security (RLS)]

To configure these values for a Model:

. Select *Data* on the top navigation bar and then on *Models*.
. Select the name of the Model you want to edit from the list.
. Select the *Edit model* button in the upper-right side of the screen.
. The Data model editor opens, with the table view selected. Select *Settings*
. Configure the Model join rule and RLS setting as needed. Select *Apply joins progressively* or *Apply all joins*, and choose whether to *Disable row level security* for the Model.


. Select *Save changes* and *Exit data model*.

'''
> **Related information**
>
> * xref:model-formula.adoc[Create a formula in a Model]
> * xref:model-filter.adoc[Create a Model filter]
> * xref:model-progressive-joins.adoc[How the Model join rule works]
> * xref:join-add.adoc[Create a join relationship]
> * xref:join-worksheet-edit.adoc[Modify joins between Model tables]
> * xref:model-delete.adoc[Delete Models or tables]
> * xref:scriptability.adoc[Migrate or restore Models]
