= {version} Release Notes
:experimental:
:last_updated: 9/26/2025
:linkattrs:
:page-aliases: /release/notes.adoc
:page-layout: default-cloud
:description: These release notes include information about new and enhanced features.
:jira: SCAL-277691

ThoughtSpot Cloud {version} is now available.

These release notes include information about new and enhanced features.

For information about previous releases, see xref:release-history.adoc[Release history].

For information about features deprecated or removed in this and future releases see xref:deprecation.adoc[].

ThoughtSpot also provides weekly updates containing bug fixes and enhancements which are automatically deployed on customer instances. For details, see xref:notes-weekly.adoc[Weekly release notes].

////
[#new]
== New features and functionality

The latest release of ThoughtSpot Cloud contains several new and enhanced features.

[#10-13-0-cl-business-user]
=== For the Business User

<<<<<<< HEAD
=======



// Mary. jira: SCAL-260154. docs jira: SCAL-266444
// PM: Arpit. move to release notes only.
List page::
ThoughtSpot introduces improved list pages. List pages include improved sorting, filtering, tags and views. List pages also now remember selections for *All* and *Yours*, and allow you to see *Favorites* and *Verified* with one click.

// Mary – Jira: SCAL-268037. docs jira: SCAL-268038
// PM: Arpit.
Navigation and favorites [.badge.badge-early-access-relnotes]#Early Access#::
ThoughtSpot introduces navigation organized by persona. The new navigation allows business users, analysts, data engineers, administrators, and developers to work in separate contextual sections designed specifically for their needs. In addition, *Favorites* have been added to the left panel navigation *Insights* tab. To enable this feature, contact your administrator.
+
For more information, see xref:thoughtspot-homepage.adoc[New home page and persona-based navigation].

// Mark. jira: SCAL-239787. docs jira: SCAL-261671
// PM: Manan. add gif.


// Rani -- jira: SCAL-231687. docs jira: SCAL-231698
// PM: Aaghran
Forecasting::
Forecasting is now available to all users and on by default. You can use SpotIQ analysis to forecast future trends for your KPIs. ThoughtSpot uses machine learning models that learn from past trends, growth, and seasonality to project how the target metric will trend in the future.
+
This feature can be disabled from the *Search & SpotIQ* option under *Application Settings* on the *Admin settings* page.
+
For more information, see xref:spotiq-forecasting.adoc[Forecasting].

// Naomi – Jira: SCAL-266414. docs jira: SCAL-270357
// PM: Siddhant.
Emails for failed scheduled jobs [.badge.badge-early-access-relnotes]#Early Access#::

The creator of a scheduled job now gets an email alert if the job fails to send to any number of subscribers to the job. To enable this feature, contact {support-url}. For more information, see xref:liveboard-schedule.adoc[Schedule a Liveboard job].

>>>>>>> fd80c167c9 (SCAL-277691)
[#10-13-0-cl-analyst]
=== For the Analyst

[#10-12-0-cl-data-engineer]
=== For the Data Engineer


[#10-13-0-cl-developer]
=== For the Developer

ThoughtSpot Embedded:: For information about the new features and enhancements introduced in this release, refer to https://developers.thoughtspot.com/docs/?pageid=whats-new[ThoughtSpot Developer Documentation^].

[#10-13-0-cl-mobile]
=== For Mobile users

ThoughtSpot Mobile:: For information about the new features and enhancements introduced in the latest release, refer to https://docs.thoughtspot.com/mobile/latest[ThoughtSpot Mobile Documentation^].

