= Weekly release notes
:experimental:
:page-last_updated: Feb 23, 2026
:linkattrs:
:page-layout: default-cloud
:description: These weekly release notes include information about enhanced features and fixes which are released on a weekly basis.
:jira: SCAL-278217, SCAL-280996, SCAL-281927, SCAL-280886, SCAL-281156, SCAL-283473, SCAL-278723, SCAL-284023, SCAL-264083, SCAL-280423, SCAL-288834, SCAL-293915, SCAL-296024, SCAL-296606

++++
<style>
.badge-enhance-relnotes {
    display: inline-block;
    margin-top: -5px;
    margin-right: -8px;
    font-size: 13px;
    text-align: center;
    position: relative;
    padding: 4.5px 5px 3px;
    top: -1px;
    color: #0d652d;
    background-color: #bcf7d7;
    font-weight: 500;
    border-radius: 6px;
    width: 96px;
}

.badge-fix-relnotes {
    display: inline-block;
    margin-top: -5px;
    margin-right: -8px;
    font-size: 13px;
    text-align: center;
    position: relative;
    padding: 4.5px 5px 3px;
    top: -1px;
    color: #174ea6;
    background-color: #a9e8ff;
    font-weight: 500;
    border-radius: 6px;
    width: 96px;
}

.badge-early-access-relnotes {
    margin-top: -5px;
}

.doc table.tableblock, .doc table.tableblock>*>tr>* {
    border-bottom: 0px solid #e1e1e1 !important;
    margin-top: 0px;
}
</style>
++++

The following release notes cover weekly changes to the ThoughtSpot Cloud release. These enhancements and fixes are automatically deployed to customer instances. For the latest *monthly* release notes see the xref:notes.adoc[{version} release notes].

There are two types of weekly releases:

* *Patch releases*: which apply only to the {version} release.
** xref:notes-weekly-3.adoc[*Go to {version} patch release notes*]
* *MT releases*: which apply to multiple releases.
** xref:notes-weekly-2.adoc[*Go to MT release notes*]