= {version} Release Notes
:experimental:
:last_updated: 9/8/2025
:linkattrs:
:page-aliases: /release/notes.adoc
:page-layout: default-cloud
:description: These release notes include information about new and enhanced features.

ThoughtSpot Cloud {version} is now available.

These release notes include information about new and enhanced features.

For information about previous releases, see xref:release-history.adoc[Release history].

For information about features deprecated or removed in this and future releases see xref:deprecation.adoc[].


[#new]
== New features and functionality

The latest release of ThoughtSpot Cloud contains several new and enhanced features.

[#10-13-0-cl-business-user]
=== For the Business User

// Naomi – Jira: SCAL-266414. docs jira: SCAL-270357
// PM: Siddhant.
Emails for failed scheduled jobs [.badge.badge-early-access-relnotes]#Early Access#::

The creator of a scheduled job now gets an email alert if the job fails to send to any number of subscribers to the job. To enable this feature, contact your administrator. For more information, see xref:liveboard-schedule.adoc[Schedule a Liveboard job].


// Mary. jira: SCAL-260154. docs jira: SCAL-266444
// PM: Arpit. move to release notes only.
List page::
ThoughtSpot introduces improved list pages. List pages include improved sorting, filtering, tags and views. List pages also now remember selections for *All* and *Yours*, and allow you to see *Favorites* and *Verified* with one click.

// Mary – Jira: SCAL-268037. docs jira: SCAL-268038
// PM: Arpit.
Navigation and favorites [.badge.badge-early-access-relnotes]#Early Access#::
ThoughtSpot introduces navigation organized by persona. The new navigation allows business users, analysts, data engineers, administrators, and developers to work in separate contextual sections designed specifically for their needs. In addition, *Favorites* have been added to the left panel navigation *Insights* tab. To enable this feature, contact your administrator.
+
For more information, see xref:thoughtspot-homepage.adoc[New home page and persona-based navigation].


[#10-13-0-cl-analyst]
=== For the Analyst

// Naomi. docs jira: SCAL-272366
Number formatting for Japanese::

We have updated the abbreviations for large number formatting in Japanese. Our new format uses 千 for thousands, 百万 for millions, 十億 for billions, and 兆 for trillions.

[#10-12-0-cl-data-engineer]
=== For the Data Engineer

// Naomi – Jira: SCAL-249300, SCAL-267923 . docs jira: SCAL-267381
// PM: Anant. still beta. changes to functionality. who has permission. if not business user, move below the fold or to analyst section? is it the same person adding instructions from both places? add mp4.
Spotter natural language instructions [.badge.badge-beta-relnotes]#Beta#::

You can now add natural language instructions directly to a Model in the Data workspace. For example, you can instruct Spotter to specify the date filter as the last 30 days if the user does not provide a date keyword. You can edit instructions directly in a conversation by clicking the instructions icon in Spotter. You must have edit access to a Model or administrator privileges to view and edit instructions. Instructions on a Model are limited to 3000 characters. To enable this feature, contact {support-url}.
+
For more information, see xref:natural-language-instructions.adoc[Natural language instructions in Spotter].

// Naomi – Jira: SCAL-239719. docs jira: SCAL-270725
// PM: Damian. move below fold. waiting on info.
Column security rules [.badge.badge-early-access-relnotes]#Early Access#::

You can now set column security rules at the table level, and they will automatically be inherited to associated Models. Operational management is simplified as the cluster setting, Strict Object Mode, is not required. In addition, rules are only required for the secured columns rather than all columns in the table. For each column you select as restricted, you can define which group(s) can have access to the column. Users without access will not see the column in search results, or anywhere in the product. To enable this feature, contact your administrator.
+
For more information, see xref:security-data-object.adoc#csr[Column security rules].

// Naomi. jira: SCAL-234810. docs jira: SCAL-264385
// PM: Prayansh
ClickHouse AWS PrivateLink::

ThoughtSpot now supports AWS PrivateLink for ClickHouse connections. ThoughtSpot encrypts all your data by default. For an additional layer of security and network reliability, you can use an AWS PrivateLink. To enable ClickHouse connections, contact your administrator.
+
For more information, see xref:connections-clickhouse-private-link.adoc[Enabling an AWS PrivateLink between ThoughtSpot Cloud and your ClickHouse data warehouse].

// Naomi. jira: SCAL-262993. docs jira: SCAL-267256.
// PM: Prayansh
OAuth Client Credentials for Snowflake::

We now support OAuth Client Credentials authentication for Snowflake. For more information, see xref:connections-snowflake-add.adoc#client-credentials[Add a Snowflake connection].


// Mary -- jira: SCAL-174558. docs jira: SCAL-?
// PM: Damian.
Column sets::
Column sets are now available to all users and on by default. A column set is a custom group of values from a single column. You can create column sets, which can be used to classify values in a list that you can then reuse across multiple analyses. For example, you can use column sets to define regions with specific countries included or excluded. Column sets are community objects which remain when you navigate away from the Search Data page and can be used by any user with view access to the underlying Model. For more information, see xref:column-sets.adoc[Column sets].


// Mary – Jira: SCAL-89860. docs jira: SCAL-260787
// PM: Damian.
Enhanced row-level security (RLS) rule logic [.badge.badge-early-access-whats-new]#Early Access#::
ThoughtSpot introduces RLS rule logic to support using AND/OR operators with bracket notation. You can now define more precise and complex access control policies that accurately reflect your organization's security requirements without resorting to data modeling solutions with access control list tables. To enable this feature, contact your administrator. For more information, see xref:security-rls-concept.adoc[].

// Mary. Jira: SCAL-256617. Docs jira: SCAL-273350
//PM: Reshma
System Cross-domain Identity Management (SCIM) support::
SCIM is now available to all users and on by default. ThoughtSpot supports the use of SCIM to automate identity management and user provisioning across different identity management systems. Customers who use identity providers like Okta or Active Directory for identity management can now sync their user-management functions between their IdP and ThoughtSpot Cloud. Users are provisioned with their corresponding group and Org attributes when they authenticate via SSO (SAML). Users that are deactivated in their IDP are removed from ThoughtSpot as well. For more information, see xref:group-user-management-scim.adoc[Manage users and groups with SCIM].

[#10-13-0-cl-as]
=== For Analyst Studio users

// Naomi. docs jira: SCAL-275619

Notebook import::
You can now instantly import an existing Notebook for analysis. The new Import Notebook option allows you to upload any `.ipynb` file to start working immediately. For more information, see xref:analyst-studio-notebook.adoc#using-the-notebook[The Notebook].



[#10-13-0-cl-developer]
=== For the Developer

ThoughtSpot Embedded:: For information about the new features and enhancements introduced in this release, refer to https://developers.thoughtspot.com/docs/?pageid=whats-new[ThoughtSpot Developer Documentation^].

[#10-13-0-cl-mobile]
=== For Mobile users

ThoughtSpot Mobile:: For information about the new features and enhancements introduced in the latest release, refer to https://docs.thoughtspot.com/mobile/latest[ThoughtSpot Mobile Documentation^].

