= Weekly release notes
:page-last_updated: Feb 23, 2026
:linkattrs:
:experimental:
:page-layout: default-cloud
:description: These weekly release notes include information about enhanced features and fixes which are released on a weekly basis.
:jira: SCAL-278217, SCAL-280996, SCAL-281927, SCAL-280886, SCAL-281156, SCAL-283473, SCAL-278723, SCAL-284023, SCAL-264083, SCAL-280423, SCAL-288834, SCAL-293915, SCAL-296024, SCAL-296606

++++
<style>
.badge-enhance-relnotes {
    display: inline-block;
    margin-top: -5px;
    margin-right: -8px;
    font-size: 13px;
    text-align: center;
    position: relative;
    padding: 4.5px 5px 3px;
    top: -1px;
    color: #0d652d;
    background-color: #bcf7d7;
    font-weight: 500;
    border-radius: 6px;
    width: 96px;
}

.badge-fix-relnotes {
    display: inline-block;
    margin-top: -5px;
    margin-right: -8px;
    font-size: 13px;
    text-align: center;
    position: relative;
    padding: 4.5px 5px 3px;
    top: -1px;
    color: #174ea6;
    background-color: #a9e8ff;
    font-weight: 500;
    border-radius: 6px;
    width: 96px;
}

.badge-early-access-relnotes {
    margin-top: -5px;
}

.doc table.tableblock, .doc table.tableblock>*>tr>* {
    border-bottom: 0px solid #e1e1e1 !important;
    margin-top: 0px;
}
</style>
++++

The following release notes cover weekly changes to the ThoughtSpot Cloud release. These enhancements and fixes are automatically deployed to customer instances. For the latest monthly release notes see the xref:notes.adoc[{version} release notes].

There are two types of weekly releases:

* Patch releases: which apply only to the {version} release.
* MT releases: which apply to multiple release versions.

[tabs]
====
8.4.1.sw::
+
--
* German translation of the words "join", and "measure" are incorrect.
* Wrong join keys are displayed in tooltips shown in query visualizer.
* Drillng down in a Liveboard does not change the x-axis configuration.
* Legends which are removed from an answer are still shown for that answer in a Liveboard.
* Horizontal scroll bar does not appear in a Liveboard.
* DataFlow: Cannot create a sync with Parquet file.
* Fit-to-screen option does not work when a visualization is pinned to a Liveboard.
* Detail labels on visualizations disappear and sometimes start to re-appear when the page is reloaded.
* Filters on tables in a Snowflake connection do not work.
* Format of a metric is not maintained when pinned to a watchlist.
--
8.4.0.sw [LA]::
+
--
* When disableLoginRedirect is set to true, users incorrectly navigate to the license upload page.
* Authentication does not work in Incgonito mode of the Google Chrome browser.
* When the enableLocalization flag is set to false, ThoughtSpot incorrectly defaults to the language of the user's browser locale, instead of English.
* No tables display for a connection that uses the custom sql feature with a key/value pair set to "tracing/ALL" in the advanced config of the connection.
* Multiple data downloads occur when applying a filter in a table and trying to download the data in csv or xlsx format.
* DataFlow: When setting up table sync, user cannot move to the next screen after selecting the *Set up sync* button.
* An error appears when viewing a Liveboard which contains a visualization, though the same visualization displays normally outside of the Liveboard.
* Attempting to edit a column in a table in a Liveboard or selecting the column name to sort the data causes a message to appear indicating the user needs edit access, even when they already have it.
* Creating answers based on a worksheet causes a warning message to appear indicating data is still being indexed.
* Updating a cluster to use Instance Metadata Service Version 2, causes an error message indicating there is an exception retrieving the InstanceId.
* Using a formula that contains a unique count on a table with a chasm trap returns incorrect results.
* Exporting a pivot table in .xlsx format results in a file with missing headers.
--
====

[tabs]
====
MT release notes::
+
--
[#feb-23-2026]
February 23, 2026

Spotter
[cols="10%,90%", grid=none, frame=none]
|====================
|[.badge.badge-enhance-relnotes]#Enhancement#| Upgraded the default  LLM model for answer generation to Anthropic Claude Opus 4.5. It is served using Google Vertex AI in partnership with ThoughtSpot.||This improves the accuracy and consistency of Spotter-generated answers.
|====================

[#feb-16-2026]
February 16, 2026

Spotter
[cols="10%,90%", grid=none, frame=none]
|====================
|[.badge.badge-fix-relnotes]#Fix#| Spotter icon text overlaps the user query when opening Spotter in a Liveboard.
|====================

[cols="10%,90%", grid=none, frame=none]
|====================
|[.badge.badge-fix-relnotes]#Fix#|“Unknown failure” error in Spotter when asking questions in a Liveboard using specific filters. Chart axis configurations were not properly passed on to downstream services.||This issue is now fixed in 26.2.0.cl.
|====================

Models
[cols="10%,90%", grid=none, frame=none]
|====================
|[.badge.badge-fix-relnotes]#Fix#| Columns used in models are not indexed when Index Settings on the *Admin > Search & SpotIQ* page are set to _Index only columns used in Models_.| |Indexing now correctly triggers based on the indexing scope enabled.
|====================
--
Patch release notes::
+
--
TBD
--
====