= {version} Release Notes
:experimental:
:last_updated: 8/14/2025
:linkattrs:
:page-aliases: /release/notes.adoc
:page-layout: default-cloud
:description: These release notes include information about new and enhanced features.

ThoughtSpot Cloud {version} is now available.

These release notes include information about new and enhanced features.

For information about previous releases, see xref:release-history.adoc[Release history].

For information about features deprecated or removed in this and future releases see xref:deprecation.adoc[].

== Features removed in {version}

=== Worksheets

- Worksheets are removed in the 10.12.0.cl release.
- All previous Worksheets are now migrated to Models.
- For information about the Model migration process, see xref:worksheet-migration-after.adoc[After all Worksheets are converted to Models].
For more information about Models, see xref:models.adoc[Create Models].

[#new]
== New features and functionality

The latest release of ThoughtSpot Cloud contains several new and enhanced features.

[#10-12-0-cl-business-user]
=== For the Business User


[#10-12-0-cl-analyst]
=== For the Analyst


[#10-12-0-cl-data-engineer]
=== For the Data Engineer

[#10-12-0-cl-it-ops]
=== For the IT/Ops Engineer

[#10-12-0-cl-developer]
=== For the Developer

ThoughtSpot Embedded:: For information about the new features and enhancements introduced in this release, refer to https://developers.thoughtspot.com/docs/?pageid=whats-new[ThoughtSpot Developer Documentation^].

[#10-12-0-cl-mobile]
=== For Mobile users

ThoughtSpot Mobile:: For information about the new features and enhancements introduced in the latest release, refer to https://docs.thoughtspot.com/mobile/latest[ThoughtSpot Mobile Documentation^].

