= {version} Release Notes
:experimental:
:last_updated: 9/26/2025
:linkattrs:
:page-aliases: /release/notes.adoc
:page-layout: default-cloud
:description: These release notes include information about new and enhanced features.
:jira: SCAL-277691

ThoughtSpot Cloud {version} is now available.

These release notes include information about new and enhanced features.

For information about previous releases, see xref:release-history.adoc[Release history].

For information about features deprecated or removed in this and future releases see xref:deprecation.adoc[].

ThoughtSpot also provides weekly updates containing bug fixes and enhancements which are automatically deployed on customer instances. For details, see xref:notes-weekly.adoc[Weekly release notes].


[#new]
== New features and functionality

The latest release of ThoughtSpot Cloud contains several new and enhanced features.

[#10-15-0-cl-business-user]
=== For the Business User

New navigation and homepage::
ThoughtSpot is excited to announce that our brand-new navigation and homepage experience is now enabled by default for all users in the 10.15.0.cl release. This change *does not apply* to users of ThoughtSpot in an embedded environment.
+
Highlights of the new navigation and homepage

* *Enhanced navigation*: commonly accessed features are now in a left-side navigation menu, providing a more intuitive and consistent user experience across all product areas
* *Fewer clicks*: faster and easier to move between key areas, such as between Liveboards, or from a Model to searching data
* *Favorites and Liveboard schedule access*: now available with a single click from the homepage navigation menu, allowing you to quickly find your most important data
* *Modern homepage*: clean, contemporary, and customizable design
+
The classic navigation and homepage experience is no longer available. For more information, see xref:thoughtspot-homepage.adoc[].

New chart settings experience [.badge.badge-early-access-relnotes]#Early Access#::
The chart settings panel is completely redesigned with a more intuitive layout and easier access. To enable this feature, please contact your administrator. For more information, see
xref:charts-new.adoc[New chart settings experience].

// Naomi – jira: SCAL-271517, docs jira: SCAL-271518
// PM: Arpit
AI auto-translation for Liveboards and Answers [.badge.badge-beta-relnotes]#Beta#:: We now support locale-specific translations for all written text on saved Answers and Liveboards, apart from column names. Translations are matched with the locale chosen in the user profile. To enable this feature, contact {support-url}.
+
For more information, see xref:auto-translation.adoc[Translations of Answers and Liveboards].

[#10-15-0-cl-analyst]
=== For the Analyst
// Mark. jira: SCAL-256237. docs jira: SCAL-279677
// PM: Damian. add screenshot?
Make a copy in the Answer data panel::
You can now copy formulas, parameters and sets in the Answer data panel. This saves time and eliminates the errors that can be caused when copying and pasting.

// Naomi. jira: SCAL-212747. docs jira: SCAL-281207
// PM: Siddhant
PNG screenshots in scheduled emails [.badge.badge-early-access-relnotes]#Early Access#:: You can now view a snapshot of a Liveboard tab directly within your scheduled email, without opening the attachment or clicking a link to view it in ThoughtSpot. Currently only one tab's snapshot can be embedded in the email. To enable this feature, contact {support-url}.
+
For more information, see xref:liveboard-schedule.adoc[Schedule a Liveboard job].

[#10-15-0-cl-data-engineer]
=== For the Data Engineer

// Naomi. jira: SCAL-273103. docs jira: SCAL-273104
// PM: Anant
AI context for Models:: AI context for Models is now on by default. You can now add AI context to columns in any Model where you have `Can Edit` access. This context helps Spotter better interpret a column and its values, using this knowledge to differentiate between similar columns and answer your data questions more accurately. You can auto-generate this context automatically with a single click to get started.
+
Unlike Spotter context added to reference questions, which helps with similar queries, AI context for each column helps Spotter choose the correct columns and values for all queries.
+
For more information, see xref:spotter-ai-context.adoc[AI Context].

// Naomi – Jira: SCAL-271363, SCAL-272829. docs jira: SCAL-271364, SCAL-272830
// PM: Anant
Data model instructions:: Data model instructions are now on by default. You can now teach Spotter core concepts, default behaviors, and specific data nuances by adding natural language instructions directly to a data model. These standalone directives act as global rules for Spotter to follow. For example, you can create a rule that makes Spotter automatically apply a "last 30 days" date filter if a user's query doesn't specify a time frame. Access this option below the Spotter search bar or in the Instructions tab on the Model.
+
For more information, see
xref:natural-language-instructions.adoc[Natural language instructions in Spotter].

// Naomi. jira: SCAL-270846, docs jira: SCAL-270847
// PM: Prayansh
Personal Access Token (PAT) authentication for Snowflake:: We now support Personal Access Token authentication for Snowflake. For more information, see xref:connections-snowflake-add.adoc#pat[Add a Snowflake connection].

// Naomi. jira: SCAL-241438 docs jira: SCAL-275547
// PM: Prayansh
Databricks CSV upload:: You now have a quick and easy way to complete data loads of files that are not present in your cloud data warehouse. You can now upload a CSV file to your Databricks connection that can be joined to other tables in your connection. To use this feature, go to *Data* > *Utilities*, and click *Upload CSV*.

// Naomi. jira: SCAL-276011, docs jira: SCAL-276012
// PM: Sujay Narayana
Indexing queries default frequency change to weekly:: The default indexing frequency has been changed from daily to weekly. Administrators can change this frequency via the *Search and SpotIQ* settings.
+
For more information, see xref:search-spotiq-settings.adoc[Managing search and SpotIQ settings].

Create your own charts with Muze Studio [.badge.badge-early-access-relnotes]#Early Access#::
endif::[]

Utilize ThoughtSpot’s in-house charting library, Muze, to build custom charts on the fly. Developers can create new chart types by using the code builder. With over 50 advanced settings available across different chart types, you’ll have pixel-perfect control over every aspect of your visualizations - including data label sizes, colors, font styles, grid lines, tooltips, and more. To enable this feature, contact your administrator. For more information, see xref:chart-create.adoc[Creating charts with Muze Studio].

[#10-15-0-cl-developer]
=== For the Developer

ThoughtSpot Embedded:: For information about the new features and enhancements introduced in this release, refer to https://developers.thoughtspot.com/docs/?pageid=whats-new[ThoughtSpot Developer Documentation^].

[#10-15-0-cl-analyst-studio]
=== For Analyst Studio users

Analyst Studio:: For information about the new features and enhancements introduced in the latest release, refer to xref:analyst-studio-release.adoc[Analyst Studio release notes].

[#10-15-0-cl-mobile]
=== For Mobile users

ThoughtSpot Mobile:: For information about the new features and enhancements introduced in the latest release, refer to https://docs.thoughtspot.com/mobile/latest[ThoughtSpot Mobile Documentation^].

