= {version} Release Notes
:experimental:
:last_updated: 5/22/2025
:linkattrs:
:page-aliases: /release/notes.adoc
:page-layout: default-cloud
:description: These release notes include information about new and enhanced features.

ThoughtSpot Cloud {version} is now available.

These release notes include information about new and enhanced features.

For information about previous releases, see xref:release-history.adoc[Release history].
////
== Deprecated and removed features in {version}

=== Worksheets

- Worksheets are deprecated and will be removed in the 10.12.0.cl release.
- Beginning in the 10.10.0.cl release, the Worksheet editor will be disabled as part of the ongoing transition to Models. You will only be able to edit Worksheets through TML or by converting them to a Model.
+
ThoughtSpot recommends that you migrate your Worksheets to Models before the 10.12 release. For more information, see xref:worksheet-migration.adoc[Converting Worksheets to Models].

=== Sage and Ask Sage
- Sage and Ask Sage are deprecated in this release and will be removed in the 10.13.0.cl release.
+
Instead of using Sage and Ask Sage, we encourage to you use Spotter. For more information, see xref:spotter.adoc[Spotter].
+
You still have the option to use Sage, but you must contact your ThoughtSpot administrator to enable it.
+
For information about other features to be deprecated or removed, see xref:deprecation.adoc[Deprecated and removed features].
////
[#new]
== New features and functionality

The latest release of ThoughtSpot Cloud contains several new and enhanced features.

[#10-9-0-cl-business-user]
=== For the Business User

// Naomi. Jira: SCAL-243007. Docs jira: SCAL-256741
[#spotter-agent]
Spotter Agent [.badge.badge-early-access-relnotes]#Early Access#:: With Spotter Agent's powerful new capabilities, it’s easier than ever to explore your data and get answers that drive confident decisions.
+
Here’s what’s new:
+
--
* Understand your data instantly +
Ask Spotter what a dataset is about, explore available fields, and get clarity on how key metrics are defined -- perfect for boosting data literacy.
* Never run out of questions +
Not sure what to ask next? Spotter now suggests the next best questions based on your context, helping you dig deeper and explore smarter.
*  Know how answers are calculated +
Transparency matters. Spotter can now explain how it arrived at a specific answer, so you can trust and verify your insights.
--
+
For more information, see xref:spotter-best.adoc#spotter-agent[Spotter best practices] and xref:spotter-agent.adoc[Spotter Agent].

// Naomi. Jira: SCAL-232993. Docs jira: SCAL-254813
[#knowledge-cards]
Knowledge cards in Spotter:: You can now hover over query tokens in Spotter to see background information on measures, attributes, formulas, and filters. For more information, see xref:spotter-best.adoc#tokens[Spotter best practices].

// Naomi. jira: SCAL-243564. docs jira: SCAL-251986
[#spotter-worksheet]
Spotter Worksheet and Model optimization:: When you edit a Worksheet or Model that has Spotter enabled, you now see a Spotter optimization tab where you can click tiles to enable indexing, ensure date values are stored in the correct format, and optimize column types. You must have edit access to a Worksheet or Model to enable Spotter optimization. For more information, see xref:spotter-worksheet-model.adoc[].


// Naomi. Jira: SCAL-220576. Docs jira: SCAL-256740
[#spotter-quick]
Spotter quick edits:: You can now click tokens in a Spotter answer to edit them for clarity, such as specifying whether a measure should be classified as count or unique count, or changing the column being used as an attribute. For more information, see
xref:spotter-getting-started.adoc#quick-edits[Getting started with Spotter].


// Rani. docs jira: SCAL-245106
[#thoughtspot-for]
ThoughtSpot for Microsoft PowerPoint add-in:: *ThoughtSpot for PowerPoint* is an add-in that allows you to insert charts and data visualizations into your PowerPoint presentation. Just connect to your ThoughtSpot instance, find a chart or visualization, and add it to your PowerPoint presentation. For more information, see xref:thoughtspot-powerpoint.adoc[ThoughtSpot add-in for Microsoft PowerPoint].


// Naomi. Jira: SCAL-240219. Docs jira: SCAL-254885
[#date-phrase]
Date phrase keywords [.badge.badge-beta-relnotes]#Beta#:: Date phrase keywords now support grammatically correct combinations of date buckets—beyond simple options like yesterday or monthly. For example, you can now search for sales in the last week of each month with improved grammar in the following languages:
+
--
* xref:keywords-de-CH.adoc[Deutsch (Switzerland)]
* xref:keywords-fr-CA.adoc[Français (Canada)]
* xref:keywords-it-IT.adoc[Italiano]
* xref:keywords-es-MX.adoc[Español (Mexico)]
* xref:keywords-es-ES.adoc[Español (España)]
* xref:keywords-ru-RU.adoc[русский]
* xref:keywords-zh-CN.adoc[中文 (简体)]
* xref:keywords-ko-KR.adoc[한국어]
--
+
To enable this feature, contact {support-url}.

////
[#alert-across]
Alert across attributes [.badge.badge-early-access-relnotes]#Early Access#:: When clicking the ThoughtSpot link in an attribute alert email, you now see conditional formatting on the corresponding KPI in ThoughtSpot. To enable this feature, contact your administrator. For more information, see xref:monitor-alert-attributes.adoc[Create an alert by attributes].
////

// Naomi. Jira: SCAL-225179. Docs jira: SCAL-252338
[#ai-highlights]
AI Highlights:: AI Highlights are now available to all users. With AI Highlights, you get quick insights on how top metrics have changed in your Liveboard, dramatically reducing the time to derive insights from your KPIs. To enable this feature, contact your administrator. For more information, see
xref:liveboard-ai-highlights.adoc[AI Highlights].

// Naomi. Jira: SCAL-236927. Docs jira: SCAL-254997
[#ai-highlights-in]
AI Highlights in Liveboard scheduled email [.badge.badge-beta-relnotes]#Beta#:: When you create a Liveboard schedule, you can now receive AI Highlights in the scheduled email. For each KPI, the highlights define the top contributors for any change in the KPI value. To enable this feature, contact {support-url}.
For more information, see xref:liveboard-schedule.adoc#highlights[Schedule a Liveboard job].

// Mary. Jira: SCAL-244746. Docs jira: SCAL-253728
[#exclude-header]
Exclude header from XLS files::
ThoughtSpot now allows you to automate the removal of headers from XLSX files to allow you to optimize processing of your files. Once enabled, all XLSX files will have headers removed. To enable this feature contact {support-url}.
For more information, see xref:search-download.adoc[Download your search].


// Rani. Jira: SCAL-227807. Docs jira: SCAL-255514
[#monitor-alerts]
Monitor alerts time zone support::
ThoughtSpot now allows you to create and modify Monitor alerts in different time zones. When setting up an alert, you can specify the desired time zone (for example, "America/Los_Angeles") for when the alert should be sent. This removes the previous requirement to convert alert times to UTC, enabling more flexible and localized alert scheduling and delivery for users across various regions.


[#10-9-0-cl-analyst]
=== For the Analyst

// Naomi. Jira: SCAL-236459. Docs jira: SCAL-243235
[#last-value]
Last value in period and first value in period functions [.badge.badge-early-access-relnotes]#Early Access#:: We have added support for `last_value_in_period` and `first_value_in_period` functions. These functions are useful for semi-additive measures, measures that typically return a single value per time period rather than being additive across time. For example, if you want to find out the last value for full-time employee headcount for the current date, you can use the formula, `fxFTE = last_value_in_period(sum(full_time_employee), query_groups(), {date})`.  To enable this feature, contact your administrator.
+
For more information, see xref:semi-additive-measures-period.adoc[Last_value_in_period and first_value_in_period functions].

// Mary. Jira: SCAL-223592. Docs jira: SCAL-254630
[#pivot-table]
Pivot table summary calculation changes::
ThoughtSpot pivot table summary calculations by default, are calculated as separate SQL queries which allows you to define different aggregation rules. Changes reflect any changes to the table data caused by filters or joins in the summary queries.
+
For more information, see xref:chart-pivot-table.adoc[Customize pivot summaries].


// Mary. Jira: SCAL-227554. Docs jira: SCAL-247233
[#query-groups]
Query_groups optional grouping columns [.badge.badge-early-access-whats-new]#Early Access#::
ThoughtSpot introduces optional grouping columns in query_groups to ensure that only specified columns are included, if they are present in the query. A new syntax allows users to define an explicit optional list of grouping columns. Previously, you needed to manually exclude all other columns from the Model. To enable this feature, contact your administrator.
+
For more information, see xref:formulas-aggregation-flexible.adoc[Query_groups optional grouping columns].




[#10-9-0-cl-data-engineer]
=== For the Data Engineer

// Naomi. Jira: SCAL-230530. Docs jira: SCAL-254814
[#preview-data]
Preview data for chasm and fan trap Worksheets in Spotter [.badge.badge-beta-relnotes]#Beta#:: When you search on a Worksheet or Model containing a chasm or fan trap on Spotter, you can click the *Preview data* button to preview the underlying tables and columns. Click the names of tables in the left-hand menu to navigate between them. To enable this feature, contact {support-url}.
+
For more information, see xref:spotter-getting-started.adoc[Getting started with Spotter].

// Naomi. jira: SCAL-240159. docs jira: SCAL-254633
[#export-spotter]
Export Spotter coaching from Coach Spotter:: Filter, select and export specific reference questions or business terms across various data models directly from Coach Spotter.
+
For more information, see xref:migrate-feedback.adoc[Migrate Spotter feedback using TML].

// Naomi. add image? jira: SCAL-226972. docs jira: SCAL-238638, SCAL-241403
[#column-name]
Column name and description aliasing for localization [.badge.badge-beta-relnotes]#Beta#::
This feature provides the ability to define a column name or description alias in a Worksheet or Model which allows column names and descriptions to be displayed in a supported system language. When enabled, column names and descriptions in the Search Data and Answer interface display in the system language selected by the user in their ThoughtSpot user profile. To enable this feature, contact {support-url}.
+
For more information, see
xref:column-aliases.adoc[Column and description aliases for localization].


// Naomi. Jira: SCAL-221141. Docs jira: SCAL-251099
[#multiple-connection]
Multiple connection configuration for Google BigQuery [.badge.badge-early-access-relnotes]#Early Access#:: You can now create additional configurations for a Google BigQuery connection, rather than just the default configuration. With multiple connection configurations, you can configure separate Google BigQuery projects and/or authentications for specific ThoughtSpot users, groups, or processes, eliminating the need to duplicate connections.
+
For more information, see xref:connections-gbq-add.adoc#additional[Add a Google BigQuery connection].

// Naomi. Jira: SCAL-221141. Docs jira: SCAL-251099
[#google-bigquery]
Google BigQuery connection fields:: We have made the following changes to connection fields for Google BigQuery:
+
--
* The *Project* field has been renamed to *Billing Project*.
* We added the field *Additional Projects*.
--
+
For more information, see xref:connections-gbq-add.adoc[Add a BigQuery connection].

////
// Mary. Jira: SCAL-216227. Docs jira: SCAL-244158
// 5/28/25 - Sam Weick said to remove this because Mistral support is not GA yet.
[#choice-of]
Choice of LLM::
ThoughtSpot introduces support for the Snowflake Mistral LLM. Admin users can select from the supported LLMs to enable all ThoughtSpot AI features.
+
For more information, see xref:spotter-getting-started.adoc[Choose LLM for Spotter].
////

// Mary. jira: SCAL-233577. Docs jira: SCAL-254817
[#import-and]
Import and export column properties for bulk edit::
You can now make bulk edits to Model column properties by importing or exporting the Model as a CSV file from the Model editor.
+
For more information, see xref:models.adoc[Building your Model].

// Rani. Jira: SCAL-224360. Docs jira: SCAL-252796
[#product-usage]
AI and BI Stats [.badge.badge-beta-relnotes]#Beta#::
ThoughtSpot now has a new data model *AI and BI Stats* that allows customers to create Answers and Liveboards leveraging product usage data. This model systematically captures query performance metrics for every query executed against external databases. This enhancement aims to significantly improve the accuracy, reliability, and depth of insights delivered by system Liveboard reporting within ThoughtSpot.
+
For more information, see xref:data-workspace.adoc#aibistats[AI and BI Stats]
[#allow-export]
// Mary. Jira: SCAL-244799 Doc Jira:SCAL-244799
Allow export of high resolution Liveboard PNG file::
ThoughtSpot introduces the ability to export improved high resolution PNG images of Liveboards. Previously, PNG exports were PDF reports in a PNG format created by taking a rolling screenshot of the PDF report generated in a headless browser.

// Mary. Jira: SCAL-241617. Docs jira: SCAL-254770
Home page watchlist enhancements [.badge.badge-early-access-whats-new]#Early Access#::
ThoughtSpot introduces a redesigned and enhanced user interface to make adding KPIs to your watchlist easier. To enable this feature, contact your administrator.
+
For more information, see xref:thoughtspot-one-homepage.adoc[Track important KPIs enhancements].

[#allow-export]
// Mary. Jira: SCAL-244799 Doc Jira:SCAL-244799
Allow export of high resolution Liveboard PNG file::
ThoughtSpot introduces the ability to export improved high resolution PNG images of Liveboards. Previously, PNG exports were PDF reports in a PNG format created by taking a rolling screenshot of the PDF report generated in a headless browser.


[#10-9-0-cl-it-ops]
=== For the IT/Ops Engineer

// Mary. Jira: SCAL-84792. Docs jira: SCAL-253423
[#system-cross]
System Cross-domain Identity Management (SCIM) support [.badge.badge-beta-whats-new]#Beta#::
ThoughtSpot introduces SCIM support to automate identity management and user provisioning across different identity management systems. Customers who use identity providers like Okta or Active Directory for identity management can now sync their user-management functions between their IdP and ThoughtSpot Cloud. Users are provisioned with their corresponding group and Org attributes when they authenticate via SSO (SAML). Users that are deactivated in their IDP are removed from ThoughtSpot as well. To enable this feature, contact {support-url}.
+
For more information, see xref:group-user-management-scim.adoc[Manage users and groups with SCIM].

[#10-9-0-cl-developer]
=== For the Developer

ThoughtSpot Embedded:: For information about the new features and enhancements introduced in this release, refer to https://developers.thoughtspot.com/docs/?pageid=whats-new[ThoughtSpot Developer Documentation^].


