= {version} Release Notes
:experimental:
:last_updated: 5/22/2025
:linkattrs:
:page-aliases: /release/notes.adoc
:page-layout: default-cloud
:description: These release notes include information about new and enhanced features.

ThoughtSpot Cloud {version} is now available.

These release notes include information about new and enhanced features.

For information about previous releases, see xref:release-history.adoc[Release history].

////
== Deprecated and removed features in {version}

=== Worksheets

- Worksheets are deprecated and will be removed in the 10.12.0.cl release.
- Beginning in the 10.10.0.cl release, the Worksheet editor will be disabled as part of the ongoing transition to Models. You will only be able to edit Worksheets through TML or by converting them to a Model.
+
ThoughtSpot recommends that you migrate your Worksheets to Models before the 10.12 release. For more information, see xref:worksheet-migration.adoc[Converting Worksheets to Models].

=== Sage and Ask Sage
- Sage and Ask Sage are deprecated in this release and will be removed in the 10.13.0.cl release.
+
Instead of using Sage and Ask Sage, we encourage to you use Spotter. For more information, see xref:spotter.adoc[Spotter].
+
You still have the option to use Sage, but you must contact your ThoughtSpot administrator to enable it.

=== Liveboard note tile embedding

- Embedding content from an external site like youtube.com or loom.com in an iFrame of a Liveboard note tile is deprecated.
+
You can still embed this type of content in a Liveboard note tile, but you must whitelist the external sites. For more information, see xref:liveboard-notes.adoc[Liveboard note tiles].

+
For information about other features to be deprecated or removed, see xref:deprecation.adoc[Deprecated and removed features].
////


[#new]
== New features and functionality

The latest release of ThoughtSpot Cloud contains several new and enhanced features.

[#10-11-0-cl-business-user]
=== For the Business User

// Naomi. jira: SCAL-248151. docs jira: SCAL-259931
// PM: Aaghran

Why questions in Spotter [.badge.badge-early-access-relnotes]#Early Access#::
When you want to investigate further on a chart in Spotter, you can now ask direct questions like, "Why did my sales drop last month?" or "Why did sales drop in Q2?" Spotter identifies the key attributes and leverages the change analysis engine to provide a clear, natural language summary identifying the key drivers, supported by detailed visualizations. To enable this feature, contact your administrator.

// Mark. jira: SCAL-239787. docs jira: SCAL-261671
// PM: Manan. add gif.
Enhanced dynamic parameters in charts [.badge.badge-early-access-relnotes]#Early Access#::
You can now use any parameter from an axis or column name of a chart in the title or description of the Answer which contains that chart. A parameter used in the title or description always displays the value of the same parameter used in the chart itself. To enable this feature, contact your administrator.

// Mark. jira: SCAL-244789. docs jira: SCAL-261681
// PM: Dilip Pitchika.
Filtering a Liveboard for users with limited access to its Worksheets or Models [.badge.badge-early-access-relnotes]#Early Access#::
When viewing a Liveboard, you can now do the following:
+
--
* Filter columns from a Worksheet or Model you have access to.
* See parameters and filters from a Worksheet or Model that you don't have access to, but you can't re-order them.
* Select a hidden column used as a filter from a Worksheet or Model. It only shows the selected values, and you can't change them.
--
+
When editing a Liveboard, you can now do the following:
+
--
* Add, edit, and remove filters and parameters from a Worksheet or Model you have access to. You can't link filters to a Worksheet or Model that you don’t have access to.
--

// Mary. jira: SCAL-230770. docs jira: SCAL-258785.
// PM: Dilip Pitchika
Show only relevant filters and parameters on Liveboards::
This feature is now on by default and available to all users. Filters and parameters that are not relevant to a tab are hidden by default when you open and view a Liveboard. You can choose to view all filters and parameters, including those that are not relevant to the tab, so that you can quickly create a new View or download the Liveboard without needing to switch tabs and apply filters individually.
+
For more information, see
xref:liveboard-filters.adoc[Apply filters to specific visualizations or tabs].

// Rani. jira: SCAL-136817. docs jira: SCAL-256725
// PM: Rahul PJP.
Add KPI to the watchlist from Liveboards and Answers::
You can now add KPIs to your watchlist directly from the Liveboards or Answers page. Click the More menu icon in the upper-right corner of any Liveboard KPI or saved Answer, then select *Add to watchlist*. This allows you to track important KPIs without leaving the page you’re viewing.


// Mary. jira: SCAL-252924, SCAL-251870. docs jira: SCAL-?
// PM: Rahul PJP
KPI monitor alerts in Slack [.badge.badge-early-access-relnotes]#Early Access#::
Monitor alerts can send alert triggers directly to Slack to ensure better visibility and immediate action within your workflows. You can set up notifications to send to Slack when you create an alert.
To enable this feature, contact your administrator.



[#10-11-0-cl-analyst]
=== For the Analyst


// Naomi. jira: SCAL-248197. docs jira: SCAL-260111
// PM: Damian. edit image down, close measures and attributes.
Copy formulas and parameters in Search data::
You can now easily copy formulas and parameters in Search data. The copied object opens a pop-up window so you can easily edit and save as a new object.
+
For more information, see xref:formula-add.adoc#copy-formula[Copy a formula] and xref:parameters-create.adoc#copy-parameter[Copy a parameter].

// Mary. jira: SCAL-230636. docs jira: SCAL-238563
// PM: Arpit
Reorder parameters in Liveboards and Answers::
This feature is now enabled by default and available to all users. You can now edit a Liveboard or Answer to reorder the parameters along with filters and save your changes. The new order is reflected when anyone opens the Liveboard or Answer.
+
For more information, see xref:parameters-use.adoc[Reorder parameters in Liveboards and Answers].

[#10-11-0-cl-data-engineer]
=== For the Data Engineer

// Rani. jira: SCAL-224360. docs jira: SCAL-252796, SCAL-260476
// PM: Shreyash Sharma, Robert Davis
AI and BI System Liveboard::
ThoughtSpot introduces a new System Liveboard providing comprehensive visibility into query usage, user adoption, object usage, and query performance across your organization. You must have admin privileges to view this Liveboard.

// Naomi. jira: SCAL-246258. docs jira: SCAL-260476
// PM: Robert Davis, Shreyash Sharma.
Analyst Studio query tagging::
Analyst Studio queries now appear within the AI and BI System Liveboard, allowing you to easily track your consumption of queries and data set refreshes.

// [#10-11-0-cl-it-ops]
// === For the IT/Ops Engineer

[#10-11-0-cl-developer]
=== For the Developer

ThoughtSpot Embedded:: For information about the new features and enhancements introduced in this release, refer to https://developers.thoughtspot.com/docs/?pageid=whats-new[ThoughtSpot Developer Documentation^].
