= {version} Release Notes
:experimental:
:last_updated: 5/22/2025
:linkattrs:
:page-aliases: /release/notes.adoc
:page-layout: default-cloud
:description: These release notes include information about new and enhanced features.

ThoughtSpot Cloud {version} is now available.

These release notes include information about new and enhanced features.

For information about previous releases, see xref:release-history.adoc[Release history].

[#new]
== New features and functionality

The latest release of ThoughtSpot Cloud contains several new and enhanced features.

[#10-9-0-cl-business-user]
=== For the Business User

// Naomi. Jira: SCAL-243007. Docs jira: SCAL-?
Spotter Agent [.badge.badge-early-access-relnotes]#Early Access#:: With Spotter Agent's powerful new capabilities, it’s easier than ever to explore your data and get answers that drive confident decisions.
+
Here’s what’s new:
+
--
* Understand your data instantly +
Ask Spotter what a dataset is about, explore available fields, and get clarity on how key metrics are defined -- perfect for boosting data literacy.
* Never run out of questions +
Not sure what to ask next? Spotter now suggests the next best questions based on your context, helping you dig deeper and explore smarter.
*  Know how answers are calculated +
Transparency matters. Spotter can now explain how it arrived at a specific answer, so you can trust and verify your insights.
--
+
For more information, see xref:spotter-best.adoc#spotter-agent[Spotter best practices].

// Naomi. Jira: SCAL-232993. Docs jira: SCAL-254813
Knowledge cards in Spotter:: You can now hover over query tokens in Spotter to see background information on measures, attributes, formulas, and filters. For more information, see xref:spotter-best.adoc#tokens[Spotter best practices].

// Naomi. jira: SCAL-243564. docs jira: SCAL-251986
Spotter Worksheet and Model optimization:: When you edit a Worksheet or Model that has Spotter enabled, you now see a Spotter optimization tab where you can click tiles to enable indexing, ensure date values are stored in the correct format, and optimize column types. You must have edit access to a Worksheet or Model to enable Spotter optimization. For more information, see xref:spotter-worksheet-model.adoc[].

// Naomi. Jira: SCAL-220576. Docs jira: SCAL-?
Spotter quick edits [.badge.badge-beta-relnotes]#Beta#:: In certain cases, Spotter may show a warning in the answer tokens. If a data set contains multiple columns with similar names, or if it's unclear whether you want a count or a unique count of a measure, for example, Spotter may ask you to clarify its interpretation of your query. You can click the tile to see what Spotter found ambiguous about the query, and select the correct interpretation. For more information, see
xref:spotter-getting-started.adoc#quick-edits[Getting started with Spotter].

// Rani. docs jira: SCAL-245106
ThoughtSpot for Microsoft PowerPoint add-in:: *ThoughtSpot for PowerPoint* is an add-in that allows you to insert charts and data visualizations into your PowerPoint presentation. Just connect to your ThoughtSpot instance, find a chart or visualization, and add it to your PowerPoint presentation. For more information, see xref:thoughtspot-powerpoint.adoc[ThoughtSpot add-in for Microsoft PowerPoint].


// Naomi. Jira: SCAL-240219. Docs jira: SCAL-254885
Date phrase keywords [.badge.badge-beta-relnotes]#Beta#:: Date phrase keywords now support grammatically correct combinations of date buckets—beyond simple options like yesterday or monthly. For example, you can now search for sales in the last week of each month with improved grammar in the following languages:
+
--
* xref:keywords-de-CH.adoc[Deutsch (Switzerland)]
* xref:keywords-fr-CA.adoc[Français (Canada)]
* xref:keywords-it-IT.adoc[Italiano]
* xref:keywords-es-MX.adoc[Español (Mexico)]
* xref:keywords-es-ES.adoc[Español (España)]
* xref:keywords-ru-RU.adoc[русский]
* xref:keywords-zh-CN.adoc[中文 (简体)]
* xref:keywords-ko-KR.adoc[한국어]
--
+
To enable this feature, contact {support-url}.

Alert across attributes [.badge.badge-early-access-relnotes]#Early Access#:: When clicking the ThoughtSpot link in an attribute alert email, you now see conditional formatting on the corresponding KPI in ThoughtSpot. To enable this feature, contact your administrator. For more information, see xref:monitor-alert-attributes.adoc[Create an alert by attributes].

// Naomi. Jira: SCAL-225179. Docs jira: SCAL-252338
AI Highlights:: AI Highlights are now available to all users. With AI Highlights, you get quick insights on how top metrics have changed in your Liveboard, dramatically reducing the time to derive insights from your KPIs. To enable this feature, contact your administrator. For more information, see
xref:liveboard-ai-highlights.adoc[AI Highlights].

// Naomi. Jira: SCAL-236927. Docs jira: SCAL-254997
AI Highlights in Liveboard scheduled email [.badge.badge-beta-relnotes]#Beta#:: When you create a Liveboard schedule, you can now receive AI Highlights in the scheduled email. For each KPI, the highlights define the top contributors for any change in the KPI value. To enable this feature, contact {support-url}.
For more information, see xref:liveboard-schedule.adoc#highlights[Schedule a Liveboard job].



[#10-9-0-cl-analyst]
=== For the Analyst

// Naomi. Jira: SCAL-236459. Docs jira: SCAL-243235
Last value in period and first value in period functions [.badge.badge-early-access-relnotes]#Early Access#:: We have added support for `last_value_in_period` and `first_value_in_period` functions. These functions are useful for semi-additive measures, measures that typically return a single value per time period rather than being additive across time. For example, if you want to find out the last value for full-time employee headcount for the current date, you can use the formula, `fxFTE = last_value_in_period(sum(full_time_employee), query_groups(), {date})`.  To enable this feature, contact your administrator.
+
For more information, see xref:semi-additive-measures-period.adoc[Last_value_in_period and first_value_in_period functions].

[#10-9-0-cl-data-engineer]
=== For the Data Engineer

// Naomi. Jira: SCAL-230530. Docs jira: SCAL-254814
Preview data for chasm and fan trap Worksheets in Spotter [.badge.badge-beta-relnotes]#Beta#:: When you search on a Worksheet or Model containing a chasm or fan trap on Spotter, you can click the *Preview data* button to preview the underlying tables and columns. Click the names of tables in the left-hand menu to navigate between them. To enable this feature, contact {support-url}.
+
For more information, see xref:spotter-getting-started.adoc[Getting started with Spotter].

// Naomi. jira: SCAL-240159. docs jira: SCAL-254633
Export Spotter coaching from Coach Spotter:: Filter, select and export specific reference questions or business terms across various data models directly from Coach Spotter.
+
For more information, see xref:migrate-feedback.adoc[Migrate Spotter feedback using TML].

// Naomi. add image? jira: SCAL-226972. docs jira: SCAL-238638, SCAL-241403
Column name and description aliasing for localization [.badge.badge-beta-relnotes]#Beta#::
This feature provides the ability to define a column name or description alias in a Worksheet or Model which allows column names and descriptions to be displayed in a supported system language. When enabled, column names and descriptions in the Search Data and Answer interface display in the system language selected by the user in their ThoughtSpot user profile. To enable this feature, contact {support-url}.
+
For more information, see
xref:column-aliases.adoc[Column and description aliases for localization].


// Naomi. Jira: SCAL-221141. Docs jira: SCAL-251099
Multiple connection configuration for Google BigQuery [.badge.badge-early-access-relnotes]#Early Access#:: You can now create additional configurations for a Google BigQuery connection, rather than just the default configuration. With multiple connection configurations, you can configure separate Google BigQuery projects and/or authentications for specific ThoughtSpot users, groups, or processes, eliminating the need to duplicate connections.

// Naomi. Jira: SCAL-221141. Docs jira: SCAL-251099
Google BigQuery connection fields:: We have made the following changes to connection fields for Google BigQuery:
+
--
* The *Project* field has been renamed to *Billing Project*.
* We added the field *Additional Projects*.
--
+
For more information, see xref:connections-gbq-add.adoc[Add a BigQuery connection].


[#10-9-0-cl-it-ops]
=== For the IT/Ops Engineer

[#10-9-0-cl-developer]
=== For the Developer

ThoughtSpot Embedded:: For information about the new features and enhancements introduced in this release, refer to https://developers.thoughtspot.com/docs/?pageid=whats-new[ThoughtSpot Developer Documentation^].

== Deprecated and removed features

- Sage and Ask Sage are deprecated in this release and will be removed in the 10.13.0.cl release.
+
Instead of using Sage and Ask Sage, we encourage to you use Spotter. For more information, see xref:spotter.adoc[Spotter].
+
You still have the option to use Sage, but you must contact your ThoughtSpot administrator to enable it.
- Worksheets are deprecated and will be removed in the 10.12.0.cl release.
- Beginning in the 10.10.0.cl release, you will no longer be able to create Worksheets. Worksheets will still exist, but you will only be able to edit them through TML or by converting them to a Model.
+
ThoughtSpot recommends that you migrate your Worksheets to Models before the 10.12 release. For more information, see xref:worksheet-migration.adoc[Converting Worksheets to Models].
+
For information about other features to be deprecated or removed, see xref:deprecation.adoc[Deprecated and removed features].
