= {version} Release Notes
:experimental:
:last_updated: 9/26/2025
:linkattrs:
:page-aliases: /release/notes.adoc
:page-layout: default-cloud
:description: These release notes include information about new and enhanced features.
:jira: SCAL-277691

ThoughtSpot Cloud {version} is now available.

These release notes include information about new and enhanced features.

For information about previous releases, see xref:release-history.adoc[Release history].

For information about features deprecated or removed in this and future releases see xref:deprecation.adoc[].

ThoughtSpot also provides weekly updates containing bug fixes and enhancements which are automatically deployed on customer instances. For details, see xref:notes-weekly.adoc[Weekly release notes].


[#new]
== New features and functionality

The latest release of ThoughtSpot Cloud contains several new and enhanced features.

[#26-2-0-cl-business-user]
=== For the Business User

TBD

[#26-2-0-cl-analyst]
=== For the Analyst

TBD

[#26-2-0-cl-data-engineer]
=== For the Data Engineer

TBD


[#26-2-0-cl-developer]
=== For the Developer

ThoughtSpot Embedded:: For information about the new features and enhancements introduced in this release, refer to https://developers.thoughtspot.com/docs/?pageid=whats-new[ThoughtSpot Developer Documentation^].

[#26-2-0-cl-analyst-studio]
=== For Analyst Studio users

Analyst Studio:: For information about the new features and enhancements introduced in the latest release, refer to xref:analyst-studio-release.adoc[Analyst Studio release notes].

[#26-2-0-cl-mobile]
=== For Mobile users

ThoughtSpot Mobile:: For information about the new features and enhancements introduced in the latest release, refer to https://docs.thoughtspot.com/mobile/latest[ThoughtSpot Mobile Documentation^].

