= {version} Release Notes
:experimental:
:last_updated: 8/14/2025
:linkattrs:
:page-aliases: /release/notes.adoc
:page-layout: default-cloud
:description: These release notes include information about new and enhanced features.

ThoughtSpot Cloud {version} is now available.

These release notes include information about new and enhanced features.

For information about previous releases, see xref:release-history.adoc[Release history].

For information about features deprecated or removed in this and future releases see xref:deprecation.adoc[].

== Features removed in {version}

=== Worksheets

- Worksheets are removed.
- All previous Worksheets are now migrated to Models.
- For information about the Model migration process, see xref:worksheet-migration-after.adoc[After all Worksheets are converted to Models].
For more information about Models, see xref:models.adoc[Create Models].

[#new]
== New features and functionality

The latest release of ThoughtSpot Cloud contains several new and enhanced features.

[#10-12-0-cl-business-user]
=== For the Business User

// Naomi. jira: SCAL-249991. docs jira: SCAL-267398

Coach Spotter from conversation [.badge.badge-early-access-relnotes]#Early Access#:: You can now coach Spotter without leaving your conversation. Click *Add to coaching* below an Answer to teach Spotter how to answer similar questions in the future. To enable this feature, contact your administrator. For more information, see xref:spotter-coach-conversation.adoc[].

// Naomi. jira: SCAL-249300 docs jira: SCAL-267381, SCAL-267909
Spotter natural language instructions [.badge.badge-beta-relnotes]#Beta#:: You can now use natural language instructions to provide global feedback to Spotter that carries over to any query on the underlying data model. To provide natural language instructions, select the instructions icon in Spotter and type a directive about how Spotter is to interpret the question. For example, you can instruct Spotter to specify the date filter as the last 30 days if the user does not provide a date keyword. To enable this feature, contact {support-url}.
+
For more information, see xref:spotter-instructions.adoc[].

// Mary. Jira: SCAL-251909. docs jira: SCAL-264648
New navigation and favorites [.badge.badge-beta-relnotes]#Beta#:: ThoughtSpot introduces navigation organized by persona. The new navigation allows business users, analysts, data engineers, administrators, and developers to work in separate contextual sections designed specifically for their needs. In addition, *Favorites* have been added to the left panel navigation *Insights* tab. To enable this feature, contact {support-url}.
+
For more information, see xref:thoughtspot-homepage.adoc[].

[#10-12-0-cl-analyst]
=== For the Analyst

// Rani. jira: SCAL-248189. docs jira: SCAL-257624
Rerun queries in Search data::
This functionality allows users to execute the same search query again without needing to refresh the browser or modify the query, and update results with the latest data.
With this feature, users can simply click *Go* to rerun the query, which is useful for testing data model changes, formula updates, or database reloads.

// Naomi – jira: SCAL-240220. docs jira: SCAL-261716.
Change comparison for single-point KPIs [.badge.badge-beta-relnotes]#Beta#:: You can now make your single-point KPIs more powerful and actionable with the new aggregated KPI chart. You can see how your KPI has changed from the previous period even for queries like 'sales last 14 days' or 'sales last 2 months'. To enable this feature, contact {support-url}.
+
For more information, see xref:chart-kpi.adoc#cca-single[Change analysis for single-point KPIs].

// Mary – jira: SCAL-258886. docs jira: SCAL-266353
Custom sort order on Answers [.badge.badge-early-access-relnotes]#Early Access#:: You can now define and modify a custom sort order for attributes directly in an Answer. Sort order defined in the Answer overrides the sort order defined in the Model for that particular Answer. To enable this feature, contact your administrator.
+
For more information, see xref::answer-custom-sort.adoc[].

// Mary. jira: SCAL-246097. docs jira: SCAL-264000
Include or exclude cover and filter pages from a Liveboard PDF::
The option to exclude cover and filter pages from Liveboard PDFs is now available to all users and on by default. ThoughtSpot Liveboard PDFs include a cover page and filter pages that contain information about the filters applied. You can now use the *PDF Options* checkboxes to choose to include or exclude these page when downloading or scheduling a Liveboard PDF. Cover and filter pages can be excluded for a schedule or download by the user. An administrator can also set cover and filter pages to be included or excluded by default in *Admin settings* under *Downloads & Schedules*.
+
For more information, see xref:liveboard-download-pdf.adoc[Download a Liveboard as a PDF] and xref:schedule-liveboards.adoc[].

// Naomi. jira: SCAL-253863. docs jira: SCAL-267154
KPI alert emails:: KPI alert emails now display a visualization of your KPI, along with the change from the previous time bucket, and the threshold condition.

// Naomi. Jira: SCAL-246787. Docs jira: SCAL-267138
Query_groups optional grouping columns:: Optional grouping columns are now available to all users and on by default. ThoughtSpot supports optional grouping columns in query_groups to ensure that only specified columns are included, if they are present in the query. A new syntax allows users to define an explicit optional list of grouping columns. Previously, you needed to manually exclude all other columns from the Model.
+
For more information, see xref:formulas-aggregation-flexible.adoc[Query_groups optional grouping columns].

// Rani. Jira: SCAL-246727. Docs jira: SCAL-246727
Last value in period and first value in period functions::
`Last_value_in_period` and `first_value_in_period` functions are now available to all users and on by default. These functions are useful for semi-additive measures, measures that typically return a single value per time period rather than being additive across time. For example, if you want to find out the last value for full-time employee headcount for the current date, you can use the formula, `fxFTE = last_value_in_period(sum(full_time_employee), query_groups(), {date})`.
+
For more information, see xref:semi-additive-measures-period.adoc[Last_value_in_period and first_value_in_period functions].

[#10-12-0-cl-data-engineer]
=== For the Data Engineer

// Naomi – jira: SCAL-262748. docs jira: SCAL-264111, SCAL-264626
Spotter context in feedback [.badge.badge-beta-relnotes]#Beta#:: Rather than simply training Spotter Coach to recognize search tokens in reference questions, you can now add context, natural language explanations of why those tokens apply to that answer. For example, you could add an implicit rule to a sample reference question, clarifying that `sales` should only be calculated on completed transactions. Adding context to coaching improves accuracy and makes it easier to tailor Spotter to your data. To enable this feature, contact {support-url}.
+
For more information, see xref:spotter-context.adoc[].

// Naomi. jira:SCAL-252761, docs jira: SCAL-262558
Spotter Coach business terms::
You can now directly add business terms to Spotter Coach, rather than approving and editing terms from within a Spotter conversation. For more information, see xref:spotter-business-terms.adoc[].

// Rani – jira: SCAL-202857
TML utility [.badge.badge-early-access-relnotes]#Early Access#:: The *Import TML* and *Export TML* features under *Utilities* now have a new user interface. You can access these from the *Data workspace* > *Utilities* page.

// Rani. jira: SCAL-244854. docs jira: SCAL-264369
Bridge support for cloud data warehouses::
Bridge provides options to securely connect your data source with ThoughtSpot Cloud, as an alternative to PrivateLink, VPC Peering, or VPN tunnels. We expanded support for Bridge to include the following connectors:
+
--
* Azure Synapse
* ClickHouse
* Dremio
--
+
For more information, see xref:connections-bridge.adoc[Bridge connectivity for Cloud Data Warehouses and Databases].

// Naomi. jira: SCAL-193108. docs jira: SCAL-262244
Multiple configurations per connection:: In addition to xref:connections-snowflake-add.adoc#additional-configurations-create[Snowflake], we now support multiple configurations for xref:connections-databricks-add.adoc#additional-configurations-create[Databricks] and xref:connections-gbq-add.adoc#additional[Google BigQuery]. This feature allows you to allocate a separate configurations for different ThoughtSpot users, groups, or processes, eliminating the need to duplicate Liveboards and configure multiple connections, and helping you with cost tracking and governance. You can also use this for your system processes so that you can control and balance the computing load.

// Naomi. jira: SCAL-231120. docs jira: SCAL-268867
Add user-defined ID (object ID) in TML [.badge.badge-beta-relnotes]#Beta#:: You can now directly add or edit an object ID in the TML of an Answer, table, Model, Liveboard, or View. This user-defined object ID allows you to manage content across multiple Orgs without having to manually change the GUID of an object each time you move it between Orgs. To enable this feature, contact {support-url}.
+
For more information, see xref:tml.adoc#object-id[Object ID in TML files].


[#10-12-0-cl-developer]
=== For the Developer

ThoughtSpot Embedded:: For information about the new features and enhancements introduced in this release, refer to https://developers.thoughtspot.com/docs/?pageid=whats-new[ThoughtSpot Developer Documentation^].

[#10-12-0-cl-mobile]
=== For Mobile users

ThoughtSpot Mobile:: For information about the new features and enhancements introduced in the latest release, refer to https://docs.thoughtspot.com/mobile/latest[ThoughtSpot Mobile Documentation^].

