= {version} Release Notes
:experimental:
:last_updated: 9/8/2025
:linkattrs:
:page-aliases: /release/notes.adoc
:page-layout: default-cloud
:description: These release notes include information about new and enhanced features.

ThoughtSpot Cloud {version} is now available.

These release notes include information about new and enhanced features.

For information about previous releases, see xref:release-history.adoc[Release history].

For information about features deprecated or removed in this and future releases see xref:deprecation.adoc[].


[#new]
== New features and functionality

The latest release of ThoughtSpot Cloud contains several new and enhanced features.

[#10-13-0-cl-business-user]
=== For the Business User

// Naomi – Jira: SCAL-266414. docs jira: SCAL-270357
// PM: Siddhant.
Emails for failed scheduled jobs [.badge.badge-early-access-relnotes]#Early Access#::

The creator of a scheduled job now gets an email alert if the job fails to send to any number of subscribers to the job. To enable this feature, contact your administrator. For more information, see xref:liveboard-schedule.adoc[Schedule a Liveboard job].



[#10-13-0-cl-analyst]
=== For the Analyst

// Naomi. docs jira: SCAL-272366
Number formatting for Japanese::

We have updated the abbreviations for large number formatting in Japanese. Our new format uses 千 for thousands, 百万 for millions, 十億 for billions, and 兆 for trillions.

[#10-12-0-cl-data-engineer]
=== For the Data Engineer

// Naomi – Jira: SCAL-249300, SCAL-267923 . docs jira: SCAL-267381
// PM: Anant. still beta. changes to functionality. who has permission. if not business user, move below the fold or to analyst section? is it the same person adding instructions from both places? add mp4.
Spotter natural language instructions [.badge.badge-beta-relnotes]#Beta#::

You can now add natural language instructions directly to a Model in the Data workspace. For example, you can instruct Spotter to specify the date filter as the last 30 days if the user does not provide a date keyword. You can edit instructions directly in a conversation by clicking the instructions icon in Spotter. You must have edit access to a Model or administrator privileges to view and edit instructions. Instructions on a Model are limited to 3000 characters. To enable this feature, contact {support-url}.
+
For more information, see xref:natural-language-instructions.adoc[Natural language instructions in Spotter].

// Naomi – Jira: SCAL-239719. docs jira: SCAL-270725
// PM: Damian. move below fold. waiting on info.
Column security rules [.badge.badge-early-access-relnotes]#Early Access#::

You can now set column security rules at the table level, and they will automatically be inherited to associated Models. Operational management is simplified as the cluster setting, Strict Object Mode, is not required. In addition, rules are only required for the secured columns rather than all columns in the table. For each column you select as restricted, you can define which group(s) can have access to the column. Users without access will not see the column in search results, or anywhere in the product. To enable this feature, contact your administrator.

// Naomi. jira: SCAL-234810. docs jira: SCAL-264385
// PM: Prayansh
ClickHouse AWS PrivateLink::

ThoughtSpot now supports AWS PrivateLink for ClickHouse connections. ThoughtSpot encrypts all your data by default. For an additional layer of security and network reliability, you can use an AWS PrivateLink. To enable ClickHouse connections, contact your administrator.
+
For more information, see xref:connections-clickhouse-private-link.adoc[Enabling an AWS PrivateLink between ThoughtSpot Cloud and your ClickHouse data warehouse].

// Naomi. jira: SCAL-262993. docs jira: SCAL-267256.
// PM: Prayansh
OAuth Client Credentials for Snowflake::

We now support OAuth Client Credentials authentication for Snowflake. For more information, see xref:connections-snowflake-add.adoc#client-credentials[Add a Snowflake connection].

[#10-13-0-cl-developer]
=== For the Developer

ThoughtSpot Embedded:: For information about the new features and enhancements introduced in this release, refer to https://developers.thoughtspot.com/docs/?pageid=whats-new[ThoughtSpot Developer Documentation^].

[#10-13-0-cl-mobile]
=== For Mobile users

ThoughtSpot Mobile:: For information about the new features and enhancements introduced in the latest release, refer to https://docs.thoughtspot.com/mobile/latest[ThoughtSpot Mobile Documentation^].

