= {version} Release Notes
:experimental:
:last_updated: 5/22/2025
:linkattrs:
:page-aliases: /release/notes.adoc
:page-layout: default-cloud
:description: These release notes include information about new and enhanced features.

ThoughtSpot Cloud {version} is now available.

These release notes include information about new and enhanced features.

For information about previous releases, see xref:release-history.adoc[Release history].
////
== Deprecated and removed features in {version}

=== Worksheets

- Worksheets are deprecated and will be removed in the 10.12.0.cl release.
- Beginning in the 10.10.0.cl release, the Worksheet editor will be disabled as part of the ongoing transition to Models. You will only be able to edit Worksheets through TML or by converting them to a Model.
+
ThoughtSpot recommends that you migrate your Worksheets to Models before the 10.12 release. For more information, see xref:worksheet-migration.adoc[Converting Worksheets to Models].

=== Sage and Ask Sage
- Sage and Ask Sage are deprecated in this release and will be removed in the 10.13.0.cl release.
+
Instead of using Sage and Ask Sage, we encourage to you use Spotter. For more information, see xref:spotter.adoc[Spotter].
+
You still have the option to use Sage, but you must contact your ThoughtSpot administrator to enable it.

=== Liveboard note tile embedding

- Embedding content from an external site like youtube.com or loom.com in an iFrame of a Liveboard note tile is deprecated.
+
You can still embed this type of content in a Liveboard note tile, but you must whitelist the external sites. For more information, see xref:liveboard-notes.adoc[Liveboard note tiles].

+
For information about other features to be deprecated or removed, see xref:deprecation.adoc[Deprecated and removed features].
////
[#new]
== New features and functionality

The latest release of ThoughtSpot Cloud contains several new and enhanced features.

[#10-9-0-cl-business-user]
=== For the Business User

// Naomi – jira: SCAL-244702. docs jira: SCAL-258659
Alerts by attribute:: Alerts by attribute are now available to all users and on by default. You can now set KPI alerts to trigger when a selected attribute changes. This can include changes in the value of the attribute, such as an increase in sales by percentage by state, or a scheduled alert to trigger on a weekly basis.
+
For example, if you wanted to create an alert for a KPI tracking sales of different phones by brand, you could choose the intended brands as attributes and set an alert to be notified when sales for those specific brands dropped by 5%.
+
For more information, see xref:monitor-alert-attributes.adoc[Create an alert by attributes].

[#10-9-0-cl-analyst]
=== For the Analyst

// Naomi. jira: SCAL-249991. docs jira: SCAL-260724.
Feedback and learnability for Spotter Agent [.badge.badge-beta-relnotes]#Beta#::
When Spotter Agent is enabled, you can give feedback with additional details, and leave comments that are reviewed by your administrator. The feedback you give will appear in the Spotter Conversations Liveboard. To enable this feature, contact {support-url}. For more information, see xref:spotter-agent.adoc#feedback[Spotter Agent].

// Naomi. docs jiraL SCAL-258753
Spotter analytics model changes:: We made the following changes to the TS: Spotter analytics data model, which is used by the Spotter Conversations Liveboard:
+
--
* Added the Hidden, User Feedback Labels, and User Feedback Comments columns
* Renamed the User Feedback column to User Feedback Rating
--
+
For more information, see xref:spotter-conversations-liveboard.adoc[Spotter Conversations Liveboard].


[#10-9-0-cl-data-engineer]
=== For the Data Engineer

// Naomi. jira: SCAL-221427. docs jira: SCAL-256366
Progressive model filters [.badge.badge-beta-relnotes]#Beta#:: Previously, any filter defined at the Model or Worksheet level applied to every query based on that Model or Worksheet. Now, you can define which table a filter applies to in the Model or Worksheet TML. Once defined, the filter only applies to queries that include columns from that specific table.
+
For more information, see xref:tml-models.adoc#apply_on_tables[TML for Models] and xref:tml-worksheets.adoc#apply_on_tables[TML for Worksheets].

// Naomi. jira: SCAL-214002. docs jira: SCAL-259366
Monitor application of row-level security at database level:: When opening SQL comments in your database, you can now see whether RLS was applied to specific queries. In the SQL comments, you can check whether the value for `isRLSApplied` is true or false.


// Mary. jira: SCAL-245938. docs jira: SCAL-255650
Spotter Conversations Liveboard available in all Orgs:: The Spotter Conversations Liveboard is now available by default in all Orgs. In the primary Org, only administrators have access by default.
In secondary Orgs, Org administrators can access this Liveboard, similar to other system objects.
+
For  more information, see xref:spotter-conversations-liveboard.adoc[Spotter Conversations Liveboard].

// Rani. docs jira: SCAL-258586
Orgs support for ThoughtSpot plug-ins:: The Microsoft PowerPoint add-in and the Google Slides add-on now support Orgs in ThoughtSpot. Orgs functionality is enabled by default in the xref:thoughtspot-powerpoint.adoc[Microsoft PowerPoint add-in]. To enable Orgs in the xref:thoughtspot-slides.adoc[Google Slides add-on], please contact {support-url}.


// Mary. jira: SCAL-240367. docs jira: SCAL-238563
Query tags for Snowflake connections::
ThoughtSpot introduces support for query tags on Snowflake connections. You can now set up query tags on your Snowflake connection to allow you to filter on users, groups, or other ThoughtSpot variables when auditing the Snowflake query logs.
+
For more information, see xref:connections-snowflake-add.adoc[Add a Snowflake connection].



// [#10-9-0-cl-it-ops]
// === For the IT/Ops Engineer

[#10-9-0-cl-developer]
=== For the Developer

ThoughtSpot Embedded:: For information about the new features and enhancements introduced in this release, refer to https://developers.thoughtspot.com/docs/?pageid=whats-new[ThoughtSpot Developer Documentation^].
