= {version} Release Notes
:experimental:
:last_updated: 1/9/2026
:linkattrs:
:page-aliases: /release/notes.adoc
:page-layout: default-cloud
:description: These release notes include information about new and enhanced features.
:jira: SCAL-277691

*Last updated: {last_updated}*

*Recently updated or added information #highlighted# below.*

// ThoughtSpot Cloud {version} is now available.

These release notes include information about new and enhanced features.

For information about previous releases, see xref:release-history.adoc[Release history].

For information about features deprecated or removed in this and future releases see xref:deprecation.adoc[].

ThoughtSpot also provides weekly updates containing bug fixes and enhancements which are automatically deployed on customer instances. For details, see xref:notes-weekly.adoc[Weekly release notes].


[#new]
== New features and functionality

The latest release of ThoughtSpot Cloud contains several new and enhanced features.

[#26-2-0-cl-business-user]
=== For the Business User

// Naomi. docs jira: SCAL-287506
// PM: Aaghran
Spotter 3 [.badge.badge-early-access-relnotes]#Early Access#::
In the 26.2.0.cl release, ThoughtSpot introduces Spotter 3 — an AI agent that breaks down the barriers between your structured and unstructured data, and then plans, reasons, and executes complex analysis like a human analyst.
+
--
Key features:

* *Data-aware intelligence*: Now securely reads the specific results of your query to write accurate insights and answer follow-up questions with full context.
* *Data security*: Processes only the data needed to answer your question. Your data is sent to the LLM only to generate insights and is never stored or used for training.
* *Analyst-grade reasoning*: Creates a plan, validates assumptions, and self-corrects to provide you verifiable results.
* *Narrative insights*: Provides rich text summaries explaining why your data looks the way it does.
* *Automatic Model selection*: Identifies and queries across multiple data models at the same time and selects the most relevant data source(s) based on your question.
* *Integrate your tools into Spotter*: Integrate ThoughtSpot's powerful agentic analytics capabilities into your own custom AI agents using the ThoughtSpot MCP server.
--
+
Spotter 3 will be Early Access in 26.2.0.cl. To enable this feature, contact your administrator.

// Naomi. jira: SCAL-268901, SCAL-272871. docs jira: SCAL-268902, SCAL-272872
// PM: Alok
Spotter conversation history:: Spotter conversation history is now generally available (GA) and on by default. Spotter now saves your conversation history, preserving your past answers in the context of your searches. You can continue a previous conversation at any time. From the sidebar, you can visit, rename, or delete any conversation.

// Naomi – jira: SCAL-274260, docs jira: SCAL-285893
// PM: Arpit
AI auto-translation for Liveboards and Answers:: AI auto-translation is now generally available (GA) and on by default. We now support locale-specific translations for all written text on saved Answers and Liveboards, apart from column names. Translations are matched with the locale chosen in the user profile.
+
For more information, see xref:auto-translation.adoc[Translations of Answers and Liveboards].

[#26-2-0-cl-analyst]
=== For the Analyst

// Mary. jira: SCAL-252930. docs jira: SCAL-286583
// PM: Dilip Pitchika
Liveboard styling and grouping:: Liveboard styling and grouping options are now generally available (GA) and on by default. Styles can be applied to a Liveboard, a tile, or a group of tiles to improve readability, differentiate specific content, or apply organizational branding guidelines. You can group relevant content together within a Liveboard using grouping.
+
For more information, see xref:liveboard-grouping-styling.adoc[Liveboard grouping and Liveboard styling].

// Mark. jira: SCAL-264868. docs jira: SCAL-287513
// PM: Manan
New chart settings experience:: The new chart settings experience is now generally available (GA) and on by default. The chart settings panel is completely redesigned with a more intuitive layout and easier access. With over 50 advanced settings available across different chart types, you’ll have pixel-perfect control over every aspect of your visualizations - including data label sizes, colors, font styles, grid lines, tooltips, and more.
+
For more information, see
ifndef::pendo-links[]
xref:charts-new.adoc[New chart settings experience].

// Mark. jira: SCAL-285343. docs jira: SCAL-285344
// PM: Manan
New charts powered by Muze [.badge.badge-early-access-relnotes]#Early Access#:: This release significantly upgrades ThoughtSpot visualization capabilities by introducing nine new, powerful native charts — Line, Column, Bar, Area, Line Column, Line Stacked Column, Stacked Column, Stacked Bar, and Stacked Area.
+
These new charts unlock sophisticated visualizations like faceted, cross-tabbed, multivariate, and bullet charts. They also resolve previous limitations by allowing multiple columns in Line Column charts and slicing by color with multiple measures, while providing deeper granular control over configurations such as tooltips, data labels, and axes.
+
To enable this feature, contact your administrator.

// Mary. jira: SCAL-226098. docs jira: SCAL-287515
// PM: Manan
Pivot table enhancements:: The new pivot table chart is now available by default. This new chart has improvements in the following areas:
+
--
* Performance
** Faster interaction while expanding rows and columns
** Pagination
* Customization
** Custom sort order support
** Column widths
** Slicing with measures and attributes
** Measure names and values
* UX
** Tooltips
** Legends
** Zebra mode
** Decluttered header space
--

// Mary. jira: SCAL-255469. docs jira: SCAL-286958
// PM: Akshat
Share experience enhancement [.badge.badge-beta-relnotes]#Beta#:: ThoughtSpot introduces an improved sharing experience. When you share a Model with *Edit* access, it now automatically includes *View* access to all referenced tables and Views. This prevents you from encountering any potential access errors. To enable this feature, contact {support-url}.

[#26-2-0-cl-data-engineer]
=== For the Data Engineer

// Mary. jira: SCAL-276876. docs jira: SCAL-276877
// PM: Sejal
Publishing workflow [.badge.badge-early-access-relnotes]#Early Access#:: ThoughtSpot introduces publishing across Orgs. Publishing allows you to create an object in the Primary Org and publish it directly to target Orgs without generating duplicate copies. To enable this feature, contact your administrator.

// Mary. jira: SCAL-276880. docs jira: SCAL-276881
// PM: Sejal
Publishing with parameters [.badge.badge-early-access-relnotes]#Early Access#:: ThoughtSpot introduces publishing with parameters. Parameters are used to assign variables to certain properties and fields within objects such as Connections and Tables. Parameterization with variables allows you to reuse and propagate the same object across various Orgs and environments within a ThoughtSpot instance while maintaining a consistent data structure of objects across Orgs. To enable this feature, contact your administrator.

// Rani. jira: SCAL-272197. docs jira: SCAL-272198
// PM: Rudram
Customizable announcement banners:: Administrators can now display custom announcement banners at the top of the ThoughtSpot interface. These announcement banners will have scheduled start and end times, and the ability to target specific Orgs or all Orgs, as decided by the admin.

// Rani. jira: SCAL-278923
// PM: Reshma
Customize email template:: Administrators can now customize the branding, content, and visibility of components in notification emails. The following parameters of the ThoughtSpot email template can be customized:
+
--
* Style customization, including font and email color palette.
* Custom vocabulary for notification emails. This allows you to replace ThoughtSpot specific terms like “ThoughtSpot,” “Liveboard,” “Answer,” and "SpotIQ," with your product terminology.
* The company logo and the company contact details in the email footer.
* Visibility of various actions like *Modify alert*, *Unsubscribe*, and the mobile app nudge.
* Visibility of the *Privacy policy*, *Contact support*, and *Manage notification preferences* components in the email footer.
--

// Naomi. jira: SCAL-264774, SCAL-270662. docs jira: SCAL-264775
// PM: Damian
Suggestion settings [.badge.badge-early-access-relnotes]#Early Access#::
We have added the Suggestion Settings column to allow you to control data that shows in typeahead suggestions and column knowledge cards. Previously, on Models with row-level security defined, you would see suggested names of data in typeahead suggestions or in column knowledge cards that you could not access. For example, if you only had access to data in California, you could see that data for Texas existed, although you could not access the data. Set the Secure Suggestions column as *Secure Suggestions* to ensure users never see references to data they shouldn't be able to access. To enable this feature, contact your administrator.

// Mark. jira: SCAL-271228. docs jira: SCAL-271229
// PM: Manan, Anshul
Muze Studio:: Muze Studio is now generally available (GA) and on by default. You can create your own charts in ThoughtSpot using the Muze charting library. A developer can create new chart types by writing the code in the code builder. This release introduces a new console window which helps developers quickly identify and resolve issues with real-time feedback on their JavaScript code execution by providing errors and warnings generated during code execution.
+
For more information, see xref:chart-create.adoc[Creating charts with Muze Studio].

// Mark. jira: SCAL-276013. docs jira: SCAL-276014
// PM: Sejal, Siddarth
Indexing only columns used in your Models:: You can now choose to index all columns or only those used in your Models. Previously, you could only index all columns. This significantly reduces the number of queries sent to your cloud data warehouse and reduces memory usage. This option does not apply to SQL views, CSV tables, or datasets, which are always indexed. It is on by default, but your ThoughtSpot administrator can modify this setting.

// Mark. jira: SCAL-251670. docs jira: SCAL-283886
// PM: Damian
Custom calendar performance improvements::
In this release, we've made the following changes to improve customer calendar performance:
+
--
- Partition pruning using Common Table Expressions (CTEs), which allows databases to filter date columns early and scan less data, resulting in faster queries.
- Automatic approximate date filtering, which applies broad date filters to leverage partitioning and then narrows results, improving speed for common time-based queries.
--
+
These changes reduce query times and improve reliability for large, partitioned datasets with date-based analytics.

// Naomi. jira: SCAL-241441. docs jira: SCAL-278562
// PM: Prayansh
CSV upload support for Google BigQuery:: You now have a quick and easy way to complete data loads of files that are not present in your cloud data warehouse. You can now upload a CSV file to your Google BigQuery connection that can be joined to other tables in your connection. To use this feature, go to *Data* > *Utilities*, and click *Upload CSV*. To enable this feature, contact your administrator.
+
For more information, see xref:connections-gbq-csv-upload.adoc[Upload a CSV file to Google BigQuery].

// Naomi. jira: SCAL-279327. docs jira: SCAL-279328
// PM: Prayansh
Bridge support for Teradata:: You can now create a connection to Teradata using the Bridge connector.
+
For more information, see xref:connections-bridge.adoc[Bridge connectivity for Cloud Data Warehouses and Databases].

// Naomi. jira: SCAL-219728. docs jira: SCAL-220584
// PM: Damian
Date interval setting:: The date interval setting in TML is now generally available (GA) and on by default. You can set the default date bucket for a Model column at the instance level. The options are detailed, daily, weekly, monthly, quarterly, yearly, hourly, or no_bucket. Note that hourly is only available for datetime data.

// Naomi. jira: SCAL-261281. docs jira: SCAL-287514
// PM: Siddhant
Liveboards with column security rules [.badge.badge-early-access-relnotes]#Early Access#:: We have enhanced the behavior of Liveboards built with column security rules. If users with only partial access to a Liveboard's data access the Liveboard, they can see and interact with the Liveboard filters and visualizations built on accessible columns, but cannot edit visualizations built on Models or columns they cannot access.

// Mary. jira: SCAL-278931. docs jira: SCAL-278932
// PM: Sejal
UI for variables [.badge.badge-early-access-relnotes]#Early Access#:: ThoughtSpot introduces variables to allow you to substitute values for specific properties of an object and enable dynamic data propagation across Orgs in ThoughtSpot. To enable this feature, contact your administrator.

// Naomi. jira: SCAL-253971. docs jira: SCAL-286673
// PM: Damian
Aliasing dimension and fact tables in Models [.badge.badge-early-access-relnotes]#Early Access#:: Previously, table aliases were only supported for role-playing dimensions, or when a single physical dimension is referenced multiple times in a fact table, with each reference linking to a logically distinct role for the dimension. Now, we support table aliases for chasm trap models, and aliasing the primary fact table. Note that data security (row-level and column-level security) apply to the aliased table as well as the original table. We also now support progressive filters for table aliases.

[#26-2-0-cl-developer]
=== For the Developer

ThoughtSpot Embedded:: For information about the new features and enhancements introduced in this release, refer to https://developers.thoughtspot.com/docs/?pageid=whats-new[ThoughtSpot Developer Documentation^].

[#26-2-0-cl-analyst-studio]
=== For Analyst Studio users

Analyst Studio:: For information about the new features and enhancements introduced in the latest release, refer to xref:analyst-studio-release.adoc[Analyst Studio release notes].

[#26-2-0-cl-mobile]
=== For Mobile users

ThoughtSpot Mobile:: For information about the new features and enhancements introduced in the latest release, refer to https://docs.thoughtspot.com/mobile/latest[ThoughtSpot Mobile Documentation^].

