= Supported SQL commands for ODBC and JDBC
:last_updated: 02/04/2021
:linkattrs:
:page-aliases: /data-integrate/reference/odbc-commands.adoc
:experimental:

The ThoughtSpot connection drivers support a limited set of SQL commands.  The ODBC and JDBC drivers support a limited set of SQL commands.
When developing software that uses a ThoughtSpot ODBC driver, use this reference of supported commands.
This reference is intended for developers using other tools (ETL, and so on) to connect to ThoughtSpot through the ODBC or JDBC driver.

NOTE: ThoughtSpot displays `VARCHAR` fields using lower case, regardless of what the original case of the loaded data.

== Supported commands

ThoughtSpot supports these SQL commands for both ODBC and JDBC:

[#create-table]
CREATE TABLE::
  Creates a table with the specified column definitions and constraints.
The table is replicated on each node.
+
Example:;;
+
[source, sql]
----
CREATE TABLE country_dim (id_number int, country varchar, CONSTRAINT PRIMARY KEY (id_number));
----

[#create-database]
CREATE DATABASE::
  Creates a database.
+
Example:;;
+
[source, sql]
----
CREATE DATABASE "fruit_database";
----

[#create-schema]
CREATE SCHEMA::
  Creates a schema within the current database.
+
Example:;;
+
[source, sql]
----
CREATE SCHEMA "fruit_schema";
----

[#alter-table-column]
ALTER TABLE <table> ADD|DROP|RENAME COLUMN <column>::
  Alters a table to add, drop, or rename a column.
+
When you add a column to an existing table, you must provide a default value to use for existing rows.
+
Example:;;
+
[source, sql]
----
ALTER TABLE "cart" ADD COLUMN "nickname" varchar(255) DEFAULT 'no nickname';

ALTER TABLE "cart" DROP COLUMN "nickname";

ALTER TABLE "sales" ADD CONSTRAINT PRIMARY KEY ("PO_number");
----

[#alter-table-constraint]
ALTER TABLE <table> DROP CONSTRAINT PRIMARY KEY::
+
Drops the primary key from a table.
+
NOTE: If you add a new primary key, ThoughtSpot uses the same upsert behavior it does when adding any primary key.
This can result in deletion of your data, so make sure that you understand how the upsert changes your data before issuing this command.
+
Example:;;
+
[source, sql]
----
ALTER TABLE "sales" DROP CONSTRAINT PRIMARY KEY;

ALTER TABLE "sales" ADD CONSTRAINT PRIMARY KEY ("PO_number");
----

[#alter-table-drop]
ALTER TABLE <table> DROP [CONSTRAINT | RELATIONSHIP] <name>::
  Drops the named foreign key or relationship between two tables.
+
Example:;;
+
[source, sql]
----
ALTER TABLE "sales_fact" DROP CONSTRAINT "FK_PO_number";

ALTER TABLE "fruit_dim" DROP RELATIONSHIP "REL_dates";
----

[#alter-table-dimension-partition]
ALTER TABLE <table> [SET DIMENSION | SET FACT [PARTITION BY HASH [(<shards>)] [KEY(<column>)]]]::
  Changes the partitioning on a table by doing one of:
+
* re-sharding a sharded table
* changing a replicated table to a sharded table
* changing a sharded table to a replicated (unsharded) table
+
By default, ThoughtSpot does not shard dimension tables.
+
To change the partitioning on a table, or to change a dimension table to a sharded table, use `ALTER TABLE...SET FACT PARTITION BY HASH...;`
+
To make a sharded table into a dimension table (replicated on every node), use `ALTER TABLE...SET DIMENSION;`
command.
+
Example:;;
+
[source, sql]
----
ALTER TABLE "sales_fact" SET FACT PARTITION BY HASH (96) KEY ("PO_number");
ALTER TABLE "fruit_dim" SET DIMENSION;
----

[#alter-table-modify-column]
ALTER TABLE <table> MODIFY COLUMN <column> <new_data_type>;::
  Changes the data type of a column.
+
This can have implications on sharding and primary key behavior.
See xref:data-type-conversion.adoc#conversion-behavior[Data type conversion behavior].
+
Example:;;
+
[source, sql]
----
ALTER TABLE fact100 MODIFY COLUMN product_id int;
----

[#insert]
INSERT::
  Creates placeholders in the table to receive the data.
+
Example:;;
+
[source, sql]
----
INSERT INTO TABLE country_dim (?, ?);
----

[#delete]
DELETE FROM <table>::
  Deletes `ALL` rows from the specified table.
+
Use the `WHERE` clause to specify only certain rows to be deleted.
+
Example:;;
+
You could remove all data for sales before a certain date to free up space in ThoughtSpot.
+
[source, sql]
----
DELETE FROM country_dim;
----

[#select]
SELECT <cols_or_expression> FROM <table_list> [WHERE <predicates>] [GROUP BY <expressions>] [ORDER BY <expressions>]::
  Fetches the specified set of table data.
+
Example:;;
+
[source, sql]
----
SELECT id_number, country FROM country_dim WHERE id_number > 200;
----

[#truncate]
TRUNCATE TABLE <table>::
  Removes all data from a table, but preserves its metadata, including all GUIDs, relationships, and so on.
+
This can be used to force a new schema for a table without losing the metadata.
+
You must reload the data following a `TRUNCATE`, or all dependent objects (worksheets and pinboards) in ThoughtSpot become invalid.
+
Example:;;
+
[source, sql]
----
TRUNCATE TABLE "location";
----
CAUTION: This operation removes all existing data from the table.

[#drop-database]
DROP DATABASE <database>::
  Drops a database and all of its schemas and tables.
+
Example:;;
+
[source, sql]
----
DROP DATABASE "fruit_database";
----

[#drop-schema]
DROP SCHEMA <schema>::
  Drops a schema within the current database, and drops all of the tables in the schema.
+
Example:;;
+
[source, sql]
----
DROP SCHEMA "fruit_schema";
----

[#drop-table]
DROP TABLE <table>::
  Drops a table.
+
Example:;;
+
[source, sql]
----
DROP TABLE "location";
----

[#show-databases]
SHOW DATABASES::
+
Lists all available databases.
+
Example:;;
+
[source, sql]
----
SHOW DATABASES;
----

[#show-schemas]
SHOW SCHEMAS::
  Lists all schemas within the current database.
+
Example:;;
+
[source, sql]
----
SHOW SCHEMAS;
----

[#show-tables]
SHOW TABLES::
  Lists all tables within the current database by schema.
+
Example:;;
+
[source, sql]
----
SHOW TABLES;
----

[#show-table]
SHOW TABLE <table>::
  Lists all the columns for a table.
+
Example:;;
+
[source, sql]
----
SHOW TABLE "locations";
----

[#script-server]
SCRIPT SERVER::
  Generates the TQL schema for all tables in all databases on the server.
+
Example:;;
+
[source, sql]
----
SCRIPT SERVER;
----

[#script-database]
SCRIPT DATABASE <database>::
  Generates the TQL schema for all tables in a database.
+
Example:;;
+
[source, sql]
----
SCRIPT DATABASE "fruit_database";
----

[#script-table]
SCRIPT TABLE <table>::
  Generates the TQL schema for a specified table. Use the physical table name, not the logical table name from the ThoughtSpot UI.
Example:;;
+
[source, sql]
----
SCRIPT TABLE "physical-table-name";
----
