= Identity and Access Management (IAMv2)
:page-last_updated: September 15, 2026
:author: Mary, Rani
:linkattrs:
:experimental:
:description: Learn about IAMv2 and the pre-migration and post-migration steps required to migrate your ThoughtSpot cluster.
:jira: SCAL-252573, SCAL-322500, SCAL-337900

ThoughtSpot supports an industry-standard cloud authentication method through Okta. With this feature, ThoughtSpot powers its internal authentication with Okta, which is the industry-leading authentication platform. The change to Okta is internal and has no impact on customers. After ThoughtSpot enables this feature by default, all user authentication will automatically use the internal Okta service. This feature set involves several external improvements to authentication, including security enhancements.

ThoughtSpot is committed to continuously enhancing your security, administration and operations experience. We are upgrading our Identity and Access Management (IAM) capabilities to provide a more secure login and authentication experience.

Migration of all ThoughtSpot customers will be done in phases as part of the upgrade maintenance window. You can also request the upgrade by contacting {support-url}.

The following are some of the enhancements that come with this upgrade:

* Advanced password management policies that allow for greater security and flexibility.
* Enhanced enterprise-grade security compliance, and
advanced identity features supported with IAMv2.
* New features will only be supported with IAMv2.


The chart below outlines the differences between IAMv1 and IAMv2:
|===
|*Feature*|*IAMv1*|*IAMv2*
|Local user management|Yes|Yes|
SAML|Yes|Yes|
OpenID Connect (OIDC)|Yes|Yes|
Active Directory Sync|Yes|Yes|
SAML per Org|No|Yes|
OIDC per Org|No|Yes|
Org and Group mapping per user from identity provider (IDP)|No|Yes|
Multifactor authentication (MFA) support for local users |No|Yes
|===

== Migrate to IAMv2

To set up your ThoughtSpot environment for IAMv2, complete the following procedures.

* xref:iamv2-pre-migration.adoc[Before migrating to IAMv2]: Audit your usernames and allowlist the required URLs before your cluster is migrated.
* xref:iamv2-post-migration.adoc[After migrating to IAMv2]: Validate local and SAML account migration, and review the changes to expect after migration.

== Related information

Refer to the following articles for detailed information on new or changed ThoughtSpot functionality with IAMv2:

* xref:saml-okta.adoc[Managing authentication with SAML using IAMv2]: If the *SAML* section of the Admin Console is called *SAML integration*, your company is using IAMv2.
* xref:oidc-iamv2.adoc[Managing authentication with OIDC using IAMv2]: If the *OIDC* section of the Admin Console is called *OIDC integration*, your company is using IAMv2.
* xref:user-management-okta.adoc[Create, edit, or delete a user using IAMv2]: If the *Users* section of the Admin Console contains an *Account Activation* column, your company is using IAMv2.
* xref:user-account-activation-okta.adoc[Account activation using IAMv2]: If your activation email subject line is "Activate your ThoughtSpot account," your company is using IAMv2.

Refer to the following articles for detailed information on ThoughtSpot functionality if you do *_NOT_* have IAMv2 enabled. Note that there is no account activation required for local users on clusters that do not have IAMv2 enabled.

* xref:authentication-integration.adoc[]: If the *SAML* section of the Admin Console is called *Authentication: SAML*, your company is *_not_* using IAMv2.
* xref:user-management.adoc[]: If the *Users* section of the Admin Console does *_not_* contain an *Account Activation* column, your company is *_not_* using IAMv2.
