= Onboarding users
:experimental:
:last_updated: 11/05/2021
:linkattrs:
:page-layout: default-cloud
:page-aliases: /end-user/onboarding/intro-onboarding.adoc
:description: Guided onboarding simplifies the initial engagement that new users have with ThoughtSpot, and encourages adoption throughout your organization.
:jira: SCAL-51041


Onboarding enables users to master the key workflows of ThoughtSpot, and makes them productive and capable users in a very short time.

When you create a new user, we recommend that you add them to a user group immediately.
Configure that user group to use a specific data source, choose up to three initial Liveboards, and specify the text of the welcome email.

[#onboarding-prerequisites]
== Prerequisites for onboarding

* *Valid emails*  All users must have valid emails.
+
To include users in the onboarding process, each user profile must include a valid email address;
see xref:user-management.adoc#add-user[Create a user].
Contact {support-url} to whitelist email domains.

Before starting the onboarding process, an administrator must specify the configuration.

[#onboarding-process]
== Onboarding process

The key workflows that enable successful onboarding include the following:

. Create a new user group, or edit an existing user group to which new users belong:
 ** specify the group name and its display name
 ** set the sharing visibility to visible
 ** specify the Privileges
 ** test and customize the test welcome email.
See steps for xref:group-management.adoc#add-group[creating a user group] or xref:group-management.adoc#edit-group[editing a user group].
. Create a new user and assign them to the group you are using for onboarding.
See steps for xref:user-management.adoc#add-user[creating a new user].
You can also xref:group-management.adoc#change-users[add existing users to the group].
. When the new user signs in for the first time, the ThoughtSpot onboarding process starts automatically and guides them through a few basic scenarios of using the application.
See xref:user-onboarding-experience.adoc[User onboarding experience].
. *[Optional]* Any user can repeat their onboarding experience at any time.
Simply select *Profile* from user icon in the upper-right corner of the page.
Under *Experience*, select *Revisit onboarding experience*.
See xref:user-profile.adoc#onboarding[Revisit onboarding].



[#data-source-recommendation]
== Notes on data source recommendation

User groups in ThoughtSpot can be hierarchical, and each user can belong to multiple groups.
Because of this, the choice of the Recommended Data Source may be surprising, both to users and admins.

We determine the default data source for *each user* based on these criteria:

* Identify data sources associated with these Liveboards
* Rank the data sources on frequency of use
* Select the highest ranked data source

Admins can preview the onboarding flow for any given user.

'''
> **Related information**
>
> * xref:groups-privileges.adoc[Understand groups and privileges]
> * xref:group-management.adoc[Create, edit, or delete a group]
> * xref:user-management.adoc[Create, edit, or delete a user]
> * xref:user-management-okta.adoc[Create, edit, or delete a user using IAMv2]
> * xref:admin-sign-in.adoc[Manage user logins and sessions]
> * xref:user-sign-up.adoc[Allow users to sign up]
