= Understanding privileges
:last_updated: 5/28/2024
:linkattrs:
:experimental:
:page-layout: default-cloud
:page-aliases: /end-user/introduction/about-privileges-end-user.adoc
:description: The things you can do in ThoughtSpot are determined by the privileges you have. Privileges are granted through group membership.
:jira: SCAL-209169



If you are trying to do something in ThoughtSpot, and cannot access the screens to accomplish it, you may not have the correct privileges.
In this case, you should contact your administrator and explain what you want to accomplish.
Your administrator may be able to grant you additional privileges.

NOTE: Permissions to see and edit Answers and Liveboards are not affected by privileges.
They are given when these items are shared with you.

Here are the privileges that the administrator sets, and the capabilities they enable:

include::partial$privileges.adoc[]

The following table shows the intersection of user privilege and ability:
include::partial$security-matrix.adoc[]

'''
> **Related information**
>
> * xref:ts-cloud-requirements-support.adoc[Requirements and support]
> * xref:user-account-activation-okta.adoc[Activate your account using IAMv2]
> * xref:user-onboarding-experience.adoc[User onboarding experience]
> * xref:navigating-thoughtspot.adoc[Finding your way around]
> * xref:accessing.adoc[ThoughtSpot browser access]
> * xref:user-profile.adoc[Your user preferences]
> * xref:tags.adoc[Use tags to organize]
