= REST API reference
:last_updated: 09/14/2021
:linkattrs:
// :page-aliases: pinboard-data-api.adoc, metadata-api.adoc, session-api.adoc, user-api.adoc, group-api.adoc, materialization-api.adoc, search-data-api.adoc

:experimental:

ThoughtSpot REST APIs let you programmatically manage users, user sessions, group privileges, and metadata objects.

Authenticated ThoughtSpot users can access these API services on the Swagger UI page of your application instance. The URL for accessing the REST APIs is `\https://<your-thoughtspot-instance>/external/swagger`.

For an up-to-date list of API categories and associated resource endpoints, see https://developers.thoughtspot.com/docs/?pageid=rest-api-reference[REST API reference].

////
This reference details all the public ThoughtSpot APIs.
The descriptions are aimed to help you solve specific use cases, such as syncing users and groups, or fetching visualization headers.

The following public APIs are available:

xref:pinboard-data-api.adoc[Pinboard Data]::
  POST `/tspublic/v1/pinboarddata`;;
    Get the pinboard data from the ThoughtSpot system.

xref:metadata-api.adoc[Metadata]::
  GET `/tspublic/v1/metadata/listobjectheaders`;;
    List the metadata object headers in the repository.
  GET `/tspublic/v1/metadata/listvizheaders`;;
    Get the visualization headers from the ThoughtSpot system.

xref:session-api.adoc[Session]::
  POST `/tspublic/v1/session/login`;;
    Authenticate and login a user.
  POST `/tspublic/v1/session/logout`;;
    Logout a user out of an existing session.

xref:user-api.adoc[User]::
  POST `/tspublic/v1/user/transfer/ownership`;;
    Transfer ownership of all objects from one user to another.
  POST `/tspublic/v1/user/sync`;;
    Synchronize principal from your external system with ThoughtSpot system.
  POST `/tspublic/v1/user/updatepassword`;;
    Change the password of a user.
  GET `/tspublic/v1/user/list`;;
    Get all users, groups and their inter-dependencies.

xref:group-api.adoc[Group]::
  POST `/tspublic/v1/group/addprivilege`;;
    Add a privilege to a group.
  POST `/tspublic/v1/group/removeprivilege`;;
    Remove a privilege from a group.

xref:materialization-api.adoc[Materialization]::
  POST `/tspublic/v1/materialization/refreshview/`;;
    Re-execute the query and load data into the materialized view.

xref:search-data-api.adoc[Search Data]::
  POST `/tspublic/v1/searchdata`;;
    Search data from a specific data source in the ThoughtSpot system.

See xref:data-api.adoc[About the REST API] for information on how to call and use the REST APIs.
////
