= Push data to external apps
:last_updated: 2/24/2022
:linkattrs:
:experimental:
:page-aliases:
:page-noindex:
:page-layout: default-cloud
:description: You can send data to a third-party business application workspace such as Slack.

ThoughtSpot allows you to use custom actions to push data to an external app or URL. If a URL action is created on your instance, you can send insights from an answer or visualization to a specific URL in a `POST` request.

Starting with the 8.1.0.cl release, ThoughtSpot supports app actions that allow you to integrate your instance with business apps such as Slack. Using app actions, you can push insights directly to your app, notify your teams, and view data in context. With app actions, ThoughtSpot can automatically establish a secure pipeline to the destination app and thus eliminate the need for building custom connectors to external apps. You can quickly get started and push data to your workspace with a few simple steps.

[NOTE]
====
In the 8.1.0.cl release, ThoughtSpot supports app actions that push data to only Slack workspaces. For information about how to push data to a Slack workspace, see xref:push-data-to-slack.adoc[Push data to a Slack workspace].
====
