= Link tables using relationships
:last_updated: 1/6/2020
:linkattrs:
:experimental:
:page-layout: default-cloud
:page-aliases: /admin/data-modeling/about-relationships.adoc
:description: Learn how to link tables using relationships.

You can link tables by creating relationships between their columns.
Linked tables can be searched together or combined into a worksheet for easy searching.
Tables that have no relationship between their columns cannot be combined in a single search.

xref:relationship-create.adoc#[Create a relationship through the web interface.]

The two methods create the same kind of relationship.
When creating a relationship between two tables, the columns that form the link must have the same data type.
For example, you can build a relationship between two columns that use the `INT32` data type.

These relationships can be managed by going to the *Relationships* page when viewing data in the *Data Modeling* section in the ThoughtSpot application.
You can view, modify, or delete relationships in either place.

The relationships you create cannot form a circular relationship, or "cycle".
If you attempt to create a relationship that would complete a cycle, you will see a message stating that the relationship could not be added because it conflicts with another existing relationship.
