= ThoughtSpot releases
:page-last_updated: Sep 11, 2026
:experimental:
:author: Mark
:linkattrs:
:description: Learn about the different types of ThoughtSpot product releases.
:jira: SCAL-243763, SCAL-269211, SCAL-334174

ThoughtSpot is committed to continuously enhancing your experience by delivering the latest features, performance improvements, and security updates to our cloud platform. To achieve this, we perform regular upgrades to the ThoughtSpot Cloud environment. This article outlines our release process and what you can expect.

ThoughtSpot delivers the following releases of ThoughtSpot Cloud:

- Monthly upgrades
- Weekly patches

[#monthly-upgrades]
== Monthly upgrades
The ThoughtSpot Cloud environment is upgraded every month to the latest official release. Our release cycle is designed to be predictable and seamless, ensuring you always have access to the most current and robust version of our platform.
In addition to monthly feature releases, we may also deploy patches between scheduled upgrades to address any critical issues that may arise.

=== Upgrade scheduling and notifications
To ensure transparency and help you plan accordingly, we follow a structured communication process for all scheduled maintenance.

- *Advanced scheduling*: All production upgrades are scheduled in advance. A 7-day advance notice is provided for production systems, while non-production environments receive 3 days' notice. A minimum separation of two weeks will be maintained between the release schedule for non-production and production tenants.
- *After-business-hours scheduling*: To minimize disruption to business operations, maintenance windows are typically scheduled after standard business hours based on the region where the application is hosted (US, EMEA, APAC, or ANZ).
- *Email notifications*: For each scheduled upgrade, official email notifications are sent to designated customer contacts. These notifications are sent 7 days, 3 days, and 1 day prior to the maintenance window.
- *Contact information*: Email communications are sent to the contacts registered for your application in our system. To ensure the right people in your organization receive these important updates, please work with your customer success (CS) or sales engineering (SE) teams to ensure your contact informmation is current. Every tenant supports up to four registered email addresses. We strongly advise utilizing a corporate distribution list (for example, tasadmin@company.com) to guarantee all essential stakeholders are successfully reached by our system alerts.

=== Maintenance window

Each upgrade is performed within a predefined maintenance window, which will be clearly stated in the notification email. This scheduled window, typically 4 hours, is a comprehensive time frame that accounts for pre-upgrade preparations, the upgrade itself, and post-upgrade validations.

- *Service unavailability*: Please be aware that your ThoughtSpot Cloud application may not be accessible during the specified time window when the upgrade happens. A warning banner will appear 10 minutes before the system goes offline. Any changes saved prior to the system going offline will be preserved.
- *Minimal disruption*: We perform upgrades using a minimal downtime approach to ensure the process is as efficient as possible. We recommend planning your work to accommodate this scheduled maintenance. The current maintenance window can range between 40 and 70 mins. (Note: HA applications require a 150 minute maintenance window.)
- *Staying informed*: You can find information about the new features and enhancements included in the upgrade by consulting the release notes link in the notification email.

=== Exceptions and rescheduling

Our upgrade process is highly automated to ensure consistency and reliability; therefore, exceptions are generally discouraged. We believe that staying on the latest version provides the best and most secure experience.

However, we understand that critical business events may occasionally conflict with a scheduled maintenance window. If you have a valid business reason you may request to reschedule your upgrade. All such requests must be made by contacting {support-url} and creating a support case.

=== Cancellation or failure
In the event of a significant update failure, ThoughtSpot will postpone additional efforts until the following month's cycle to protect the platform. By prioritizing stability and reliability, we avoid risky reinstallation attempts within the current window, ensuring your environment remains consistent and secure.

[#weekly-patches]
== Weekly patches

In addition to our regular monthly releases, ThoughtSpot deploys weekly patches to enhance platform reliability and performance. These patches are focused on delivering critical updates and targeted bug fixes to ensure the continued stability and security of your environment.

=== Patching schedule and timing

To minimize business impact, our weekly patch deployment process is conducted during a standard maintenance window over the weekend.

- *Deployment window*: Patches are deployed in a staggered manner every weekend, on Saturdays and Sundays (Pacific Time).
- *Completion target*: The process is targeted for completion before the start of business hours on Monday across all global regions.

=== Service impact and downtime

The patching process is designed to be swift and efficient, with minimal disruption to your service. The expected interruption during a patch deployment is typically between 25 and 35 minutes.

=== Notifications

You will be informed of upcoming patch maintenance through in-app notifications and an email.

- *In-app banners*: A maintenance banner will be displayed within your ThoughtSpot application once a patch is scheduled.
- *Notification timing*: These banners are typically activated at least 48 hours before the scheduled weekend maintenance window.

=== Critical security patches

Please note that if a patch is designated as a critical security or break-fix update, it will be deployed across all customer environments without exception. This mandatory application ensures the security and integrity of the entire ThoughtSpot Cloud platform for all our customers.

