= ThoughtSpot Cloud release life cycle
:last_updated: 12/22/2022
:author: Mark Plummer
:linkattrs:
:experimental:
:page-layout: default-cloud
:description: The life cycle of ThoughtSpot Cloud releases.

ThoughtSpot Cloud features go through the following stages:

[#beta]
== Beta

Beta features are incomplete, may have bugs, and are subject to change before they reach General Availability (GA).
Beta features are enabled for select customers to provide early feedback to the product team prior to GA.
Beta features have minimal documentation which is also subject to change before GA.

****
Beta features are marked with [.badge.badge-update-note]#Beta# and are disabled by default.
You must contact {support-url} to enable them.
****

[#early-access]
== Early Access

Early Access features are complete, and available for customers to try before they reach GA, when they are enabled by default.
They are supported by ThoughtSpot and documentation is available.

****
Early Access features are marked with [.badge.badge-early-access]#Early Access# and are disabled by default.
You must contact your ThoughtSpot administrator or {support-url} to enable them.
****

For details on how to enable an Early Access feature, see xref:early-access-enable.adoc[].

[#private-preview]
== Private Preview

Private Preview features are complete, and available for select customers to try before they reach GA, when they are enabled by default. Private Preview features may have documentation which is subject to change before GA.

Once enabled, your ThoughtSpot administrator can grant access to Private Preview features for users in a group by assigning the *Can preview ThoughtSpot Sage* user privilege to the group. You do not need this privilege for the xref:data-modeling-visibility.adoc#automatic-synonyms[AI-generated Worksheet synonyms] feature.

****
Private Preview features are marked with [.badge.badge-private-preview]#Private Preview# and are disabled by default.
You must contact {support-url} to enable them.
****

== General Availability

General Availability (GA) features have new or enhanced functionality that are enabled by default for all customers.

== Deprecated

Deprecated features still exist in the product, for backward compatibility, but we plan to remove them in a later release.
Deprecated features do not receive ongoing support from ThoughtSpot.
For details, see xref:deprecation.adoc[Deprecated and removed features].

== Removed

Removed features no longer exist in the product.
When you upgrade to a newer release, any workflows that rely on a removed feature no longer work.
For details, see xref:deprecation.adoc[Deprecated and removed features].
