= About REST APIs
:last_updated: 2/24/2022
:linkattrs:
:experimental:
:page-layout: default-cloud
:page-aliases: /admin/ts-cloud/about-rest-apis.adoc
:description: ThoughtSpot REST APIs allow you to programmatically manage users and user sessions, query data, and import and export ThoughtSpot objects.



The ThoughtSpot REST API framework lets you create, access, edit, and manage objects and resources in the ThoughtSpot system programmatically.

ThoughtSpot REST API supports several resource collections and operations in two distinct versions:

* REST API v1
+
The legacy framework with several endpoints to create, edit, administer, and manage ThoughtSpot objects and data.

* REST API v2.0
+
The REST API v2.0 framework provides enhanced functionality and API experience with an interactive Playground.

For more information about the differences between these two REST API versions, see https://developers.thoughtspot.com/docs/?pageid=v1v2-comparison[REST API v1 and v2.0 comparison, window=_blank].

== REST API Playground

ThoughtSpot users with Developer or Administrator privileges can access the REST API v1 and v2.0 endpoints from the *Develop* tab. The portal provides a separate Playground for each REST API version and lets you explore the API endpoints, and request and response workflows.

* To try out the https://developers.thoughtspot.com/docs/?pageid=rest-api-v1[REST API v1 endpoints, window=_blank], click *REST Playground v1*. +
* To access the https://developers.thoughtspot.com/docs/?pageid=rest-api-v2[REST API v2 endpoints, window=_blank], click **REST Playground v2.0**.

== Get started

To know how to get started with REST APIs, see the following articles in __ThoughtSpot Developer Documentation__:

* https://developers.thoughtspot.com/docs/?pageid=rest-api-getstarted[Get started with REST API v1, window=_blank]
* https://developers.thoughtspot.com/docs/?pageid=rest-apiv2-getstarted[Get started with REST API v2.0, window=_blank]

==  API endpoints
For a complete list of API endpoints and information about how to make an API call to these endpoints, see the following reference pages:

* https://developers.thoughtspot.com/docs/?pageid=rest-api-reference[REST API v1 Reference, window=_blank]
* https://developers.thoughtspot.com/docs/?pageid=rest-apiv2-reference[REST API v2.0 Reference, window=_blank]