= About REST APIs
:last_updated: 2/24/2022
:linkattrs:
:experimental:
:page-layout: default-cloud
:page-aliases: /admin/ts-cloud/about-rest-apis.adoc
:description: ThoughtSpot REST APIs allow you to programmatically manage users and user sessions, query data, and import and export ThoughtSpot objects.

include::partial$liveboards-announcement.adoc[]

The ThoughtSpot REST API framework lets you programmatically create, access, edit, and manage objects and resources in the ThoughtSpot system.

== REST API v1 and v2

ThoughtSpot REST API supports several resource collections and request operations in two distinct versions:

* REST API v1
+
The legacy framework with several endpoints to create, edit, administer and manage ThoughtSpot objects and data.

* REST API V2
+
The REST API v2 [.badge.badge-update]#Beta# framework is a new developer-focused solution that provides additional functionality and an interactive Playground experience. The REST v2 framework also supports language-specific SDK and client libraries.

+
[NOTE]
====
The REST API v2 is a limited availability feature and is in Beta. To enable this feature on your instance, contact {support-url}.
====

For more information about the differences between these two REST API versions, see https://developers.thoughtspot.com/docs/?pageid=v1v2-comparison[REST API v1 and v2 comparison, window=_blank].


== REST API Playground

ThoughtSpot users with Developer or Administrator privileges can access the REST v1 and v2 endpoints in the Developer portal. If the REST API SDK and Playground^BETA^ feature is enabled on your cluster, you can see the *REST Playground v1* and **REST Playground v2** menu options under *REST API* in the *Develop* tab.

The portal provides a separate Playground for each version and lets you explore the API endpoints and make an API call.

* To try out the https://developers.thoughtspot.com/docs/?pageid=rest-api-v1[REST v1 APIs, window=_blank], click **REST Playground v1**.

* To access the https://developers.thoughtspot.com/docs/?pageid=rest-api-v2[REST v2 Playground], click **REST Playground v2**.

== Get started

To know how to get started with REST APIs, see the following articles in __ThoughtSpot Developer Documentation__:

* https://developers.thoughtspot.com/docs/?pageid=rest-api-getstarted[Get started with REST API v1, window=_blank]
* https://developers.thoughtspot.com/docs/?pageid=rest-apiv2-getstarted[Get started with REST API v2, window=_blank]

==  API endpoints
For a complete list of API endpoints and information about how to make an API call to these endpoints, see the following reference pages:

* https://developers.thoughtspot.com/docs/?pageid=rest-api-reference[REST API v1 Reference, window=_blank]
* https://developers.thoughtspot.com/docs/?pageid=rest-apiv2-reference[REST API v2 Reference, window=_blank]

////
Using REST APIs, your client application can perform the following operations:

* get Liveboard and visualization data from the ThoughtSpot application
* embed data from visualizations and Liveboards in a web page, portal, or application
* view metadata details for various types of ThoughtSpot objects
* construct a search query to get ThoughtSpot data
* manage ThoughtSpot user profiles and group privileges
* transfer ownership of objects from one user to another
* import, export, and validate scriptable files and automate deployments

== Resource endpoints

ThoughtSpot API components or resources are represented by the URI endpoints.
The URI endpoint contains the base URI and resource path to the objects that you want to query or manage.
The base URI of the API endpoints constitutes the following:

* The hostname or IP address of your ThoughtSpot application instance
* Port number
* Name of the ThoughtSpot API service
* The version number

For example, in the `https://<your-thoughtspot-hostname:port>/callosum/v1/tspublic/v1/session/login` URL:

* the base URI is `https://<your-thoughtspot-hostname:port>/callosum/v1`
* the resource path is `/tspublic/v1/session/login`

== HTTP request methods

ThoughtSpot REST APIs support Create, Read, Update and Delete (CRUD) operations and allow applications to use the standard HTTP verbs in API requests:

* *GET* to query information, such as getting a list of users, objects, or metadata headers
* *POST* to create, add, or exchange data
* *PUT* to update the parameters in resource representation
* *DELETE* to remove a specific data, association, or object

== Data format

The REST APIs allow you to send and receive data in JSON format.
To embed this data in your application, you can import or extract the data from the JSON file.
You can also use scriptable files in ThoughtSpot Modeling Language (TML) to represent objects in a reusable, editable, and easy-to-read format.
ThoughtSpot allows you to export, validate, and import these scriptable files.

== List of APIs

For a complete list of API endpoints and information about how to make an API request to these points, see https://developers.thoughtspot.com/docs/?pageid=rest-api-reference[REST API Reference].
////
