= Runtime filters
:last_updated: 2/25/2022
:linkattrs:
:experimental:
:page-layout: default-cloud
:page-aliases: /admin/ts-cloud/about-runtime-filters.adoc
:description: Use runtime filters to filter an embedded Answer or Liveboard.

Runtime filters apply filters to a Liveboard or Answer by passing the filter properties as query parameters in a Liveboard or visualization URL. You can also apply runtime filters in REST API requests when querying data from a Liveboard, Answer, or a visualization object. On embedded instances, you can use the Visual Embed SDK to apply filters to an embedded Liveboard or Answer, and update filters using events.

== Supported data types

You can use runtime filters on these data types:

* `VARCHAR`
* `BIGINT`
* `INT`
* `FLOAT`
* `DOUBLE`
* `BOOLEAN`
* `DATE`
* `DATE_TIME`
* `TIME`

For the `DATE` and `DATE_TIME` data types, you must provide the date and time values in the Epoch time format.
The Epoch time is also referred to as POSIX or Unix time.
Epoch time is an integer value representing the number of seconds elapsed since 1 JAN 1970 00:00:00 UTC.
You may have to convert time zones to calculate the appropriate timestamp.

For example, if you want to filter data for 2020-05-22, you can specify the date value in the Epoch time format as 1590192000, or use the following JavaScript method to calculate the timestamp:

----
new Date('2020-05-22').getTime() / 1000
----

== Runtime filter operators

This list contains all the filter operators you can use with runtime filters.

|===
| Operator | Description | Number of Values

| `EQ`
| equals
| 1

| `NE`
| does not equal
| 1

| `LT`
| less than
| 1

| `LE`
| less than or equal to
| 1

| `GT`
| greater than
| 1

| `GE`
| greater than or equal to
| 1

| `CONTAINS`
| contains
| 1

| `BEGINS_WITH`
| begins with
| 1

| `ENDS_WITH`
| ends with
| 1

| `BW_INC_MAX`
| between inclusive of the higher value
| 2

| `BW_INC_MIN`
| between inclusive of the lower value
| 2

| `BW_INC`
| between inclusive
| 2

| `BW`
| between non-inclusive
| 2

| `IN`
| is included in this list of values
| multiple
|===

== How to apply runtime filters

For information about how to apply runtime filters, see link:https://developers.thoughtspot.com/docs/?pageid=runtime-filters[Runtime filters, window=_blank].

[#limitations-of-runtime-filters]
== Limitations of runtime filters

Runtime filters do not work directly on top of tables. You must create a Worksheet if you want to use runtime filters.
This means that the Liveboard or visualization on which you apply a runtime filter must be created on top of a Worksheet.

* The DATE and DATE_TIME data type must be specified as EPOCH time (Unix or POSIX time) in runtime filters. +
* If the Worksheet was created from an Answer (it is an aggregated Worksheet), runtime filters will only work if the Answer was formed using a single Worksheet. If the Answer from which the Worksheet was created includes raw tables or joins multiple Worksheets, you won't be able to use runtime filters on it. This is because of the join path ambiguity that could result.
* Runtime filters do not allow you to apply HAVING in the URL parameters. +
* You cannot apply a runtime filter on a Liveboard or visualization built on tables whose schema includes a chasm trap.
