= ThoughtSpot Lightning Web Component (LWC) plugin for Salesforce
:author: Naomi
:page-last_updated: 09/05/2025
:linkattrs:
:experimental:

:description: This plugin allows you to seamlessly embed ThoughtSpot Liveboards and Spotter inside your Salesforce environment.
:jira: SCAL-271265, SCAL-280398

Use the ThoughtSpot LWC plugin to seamlessly embed ThoughtSpot Liveboards and Spotter inside your Salesforce environment. Using these embedded features, you can access interactive ThoughtSpot dashboards and AI-driven search for instant insights without leaving Salesforce. Spotter and the Liveboard work directly within Salesforce Accounts and other objects using the Lightning App Builder. You can configure your experience by choosing which Liveboards to display, and update URLs dynamically.

== Install the LWC package

To install the LWC package, follow these steps:

. Create a link:https://developer.salesforce.com/developer-legacy/signup[Salesforce Developer account].

. Install the link:https://login.salesforce.com/packaging/installPackage.apexp?p0=04tWU000000G5TZYA0[ThoughtSpot LWC package].

. Select the appropriate access level for your users, then click *Install*.

. Ensure your ThoughtSpot instance URL is allowlisted in Salesforce. Refer to the xref:salesforce-plugin-setup.adoc[Setup guide].

== Embed Liveboards and Spotter

video::HhUgtAA-G-M[youtube,title="ThoughtSpot - Salesforce LWC Demo",width="375",height="210"]

To get started on embedding Liveboards and Spotter into your Salesforce environment, follow these steps:

. Open the Salesforce App Launcher, and navigate to the *Sales* app.

. Go to the *Accounts* tab and select *All Accounts*.

. Create a new account or open an existing one.

. Click the gear icon ⚙️ and select *Edit Page* to enter the *Lightning App Builder*.

. Search for *ThoughtSpot* in the left side search bar. From the Custom-managed components section, drag and drop *ThoughtSpot Liveboard* and *ThoughtSpot Spotter* into sections marked *Add Component Here*.

. If you want to edit the Liveboard displayed on your page, click the Liveboard and update the *ThoughtSpot URL* and *Liveboard ID* in the options on the right side menu.
+
Note that you can find the new ThoughtSpot URL by navigating to your instance, accessing the home page and copying the URL. For the Liveboard ID, navigate to the desired Liveboard and copy the string in the URL after `/pinboard/`.

. Click *Save* to return to the Accounts page. You now see your embedded Liveboard and Spotter in the layout.

You can interact with an embedded Liveboard just as you would in Spotter, by applying filters, drilling down, and exploring. In your embedded Spotter plugin, you can ask questions in natural language and Spotter responds with insights with visual answers.

For further customization, reference link:https://developers.thoughtspot.com/docs/sf-integration[Salesforce and ThoughtSpot integration].
