= Release upgrade schedule
:last_updated: 4/30/2020
:linkattrs:
:experimental:
// :page-toclevels: -1
:page-layout: default-cloud
:description:  Current schedule for ThoughtSpot Cloud cluster upgrades
:jira: SCAL-175305

+++++
<style>
.doc .sidebarblock>.content>.title {
    font-weight: 500;
    text-align: left;
    margin-top: 10px;
}
</style>
+++++

ThoughtSpot Cloud releases are rolled out in a phased manner across the entire ThoughtSpot cloud environment. The initial release candidate is deployed on internal ThoughtSpot, and customer development (DEV) environments. Once the quality of the release candidate is confirmed, it is rolled out as generally available (GA) across all production (PROD) environments.

NOTE: Upgrade dates are subject to change without notice at ThoughtSpot’s discretion.

This is the targeted release schedule for upcoming ThoughtSpot Cloud upgrades:

// For RC we use Column E - G, and For GA we use Columns H - K in Cloud-Release Schedule (Active) Last Date of External Release Schedule google sheet:
// https://docs.google.com/spreadsheets/d/1jWDZngz4D8xSDXgYRpFmzMporz5HNF30sH-2SeBP8_g/edit#gid=1741858595&range=E2

[cols="20%,40%,40%"]
|===
|*Release*
|*Release candidate*

(DEV, Internal, non-PROD)|*General availability*

(PROD)

|9.7.0.cl
|October 20-26, 2023
|November 3-10, 2023

|9.8.0.cl
|October 25-November 7, 2023
|November 12-21, 2023

|9.9.0.cl
|November 15-23, 2023
|December 4-14, 2023

|*Customer email notifications*
|3 days prior to upgrade
|7 days prior to upgrade
|===

.Upgrade details
****
* Non-production environments include internal ThoughtSpot as well as partner, or customer dev clusters.
* Cluster upgrades are rolled out in a phased manner during the prescribed date range.
* All customers will be notified about the exact date and time window for the upgrade in an email notification as per the schedule in the table above.
* Customer documentation is published at the time of GA.
****



== Upgrade process
- New releases are deployed on a monthly cadence across all ThoughtSpot Cloud clusters.
- Customer development clusters are deployed with a release candidate that will allow us to validate release stability prior to deployment across the production environment.

== Upgrade times

Upgrades take place during off-business hours, at the following times:

- *APAC:* 10:00 AM Pacific Time (5:00 PM UTC)
- *ANZ:* 3:00 AM Pacific Time (10:00 AM UTC / 6:00 PM Singapore Time / 8:00 PM Atlantic Time / 10:00 PM New Zealand Time)
- *EMEA:* 3:00 PM Pacific Time (10:00 PM UTC)
- *US:* 8:00 PM Pacific Time (3:00 AM UTC)
////
