= Scheduled Liveboards
:last_updated: 2/08/2022
:linkattrs:
:page-layout: default-cloud
:experimental: /admin/manage-jobs/about-scheduled-pinboards.adoc
:description: On the Liveboard schedules page, found in Data > Utilities > View Liveboard schedules, you can create and manage scheduled Liveboards.

On the *Liveboard schedules* page, found in *Data > Utilities > View Liveboard schedules*, you can create and manage scheduled Liveboards.
With scheduled Liveboards, you can prepare for recurrent meetings and closely monitored metrics.

With scheduled Liveboard email updates, you can analyze your data offline and share Liveboards with your colleagues, including people who may not have a ThoughtSpot account.

Contact {support-url} if scheduled Liveboards is not enabled on your cluster.

== Scheduling Liveboards

Administrators and users with *can schedule for others* privilege can schedule and manage Liveboard jobs for other users and groups. Users must have at least view-only access to the Liveboards they share.

CAUTION: ThoughtSpot recommends that you remain conservative when deciding who has the *can schedule for others* privilege in your organization. There are  possible security implications when critical information can be shared outside your company.

== Row-level security

Scheduled Liveboards adhere to row-level security rules.
If the recipients are users in ThoughtSpot, they can only see data based on their own access to that Liveboard.
If the user does not have view-only or greater access to the Liveboard, they do not see any data in the email.
However, if the recipients are not ThoughtSpot users, then they have access to the dataset of the Liveboard based on the sender's permissions.

[#format]
== Format and layout of scheduled Liveboards

The Liveboard visualizations are attached to the scheduled email as either CSV or PDF files.
Saved configurations such as Liveboard filters are applied to the attachments.
Refer to the <<format-table,format types table>> to see how the Liveboard data is represented in each file format.

To specify the layout of the Liveboard in the email, select *Configure layout options*. For more details about the layout options, refer to xref:liveboard-download-pdf.adoc[].

[#format-table]
|===
| CSV | PDF

| The CSV file gets data only for table visualizations.
| The PDF file gets data for all visualizations.

a| The email has _n_ CSV attachments, where there are _n_ table visualizations in the Liveboard.
| The email has only one attachment file, which includes every visualization on its own page.

| Table visualizations have all data rows that they're supposed to have.
| Table visualizations include only the first 100 rows.

| In the case of a corrupted Liveboard: no email is sent.
An error message indicating failure to export data is visible on the Data > Utilities >  View Liveboard schedules page.
| In the case of a corrupted Liveboard: the PDF attachment has empty/error screenshots.

| In the case of a corrupted visualization: an email with the visualizations whose data can be exported is sent.
An error message indicating visualization export error is visible on the View Liveboard schedules page.
| In the case of a corrupted visualization: the PDF attachment has empty/error slots for the corrupted visualizations.
|===

The size of each email is limited to 25 MB, which matches most email services size limitations.

The total number of recipients for a scheduled Liveboard job cannot exceed the default of 1000.

'''
> **Related information**
>
> * For more information on creating a Liveboard job, see xref:liveboard-schedule.adoc[Schedule a Liveboard job].
