= Scheduled Liveboards management
:last_updated: 2/08/2022
:linkattrs:
:experimental:
:page-layout: default-cloud
:page-aliases: /admin/manage-jobs/scheduled-pinboards-management.adoc
:description: To view and manage Liveboard schedules, navigate to Data > Utilities > View Liveboard schedules.


Users who are not admins can only view Liveboard schedules they've created.
You can select specific jobs and choose to pause, resume, edit, or delete them.
You can have up to 50 scheduled jobs on your cluster at time.
Contact {support-url} if you'd like to increase this limit.

To view Liveboard schedules, navigate to menu:Data[Utilities > View Liveboard schedules].

== Bulk actions

Select the scheduled Liveboards and use the *Delete*, *Resume*, and *Pause* buttons to perform these bulk actions.
Deleting a Liveboard will also delete any schedules linked to it.

== Job statuses

Selecting the row of a job will open a detailed view of every generated update of that job.
You can see the start and end times of the job, as well as the status.
Selecting a job will show more information about the status updates.

== Liveboard links

Select the scheduled Liveboard name link to jump to an Edit schedule page, where you can edit the schedule configurations.

You can also select the Liveboard link provided in the scheduled Liveboard emails to jump to the Liveboard in ThoughtSpot.
In order to have the link direct you to the correct URL, you must first configure front end host and port access.
Contact {support-url} to configure these settings.
