= ThoughtSpot Lifecycle
:linkattrs:
:experimental:
:page-layout: default-cloud
:page-aliases: /admin/data-security/security-thoughtspot-lifecycle.adoc
:description: This topic covers security processes for the entire lifecycle of a ThoughtSpot deployment from development, release, upgrades, to software patching.
:last_updated: tbd
:jira: SCAL-181227

++++
<style>
.badge-aws {
    border-radius: 6px;
    background-color: #ff9900;
    display: inline-block;
    font-size: 13px;
    padding: 4.5px 5px 3px;
    font-style: normal;
}

.badge-gcp {
    border-radius: 6px;
    background-color: #34a853;
    display: inline-block;
    font-size: 13px;
    padding: 4.5px 5px 3px;
    font-style: normal;
}
</style>
++++


== Overview

At ThoughtSpot, we recognize that data is one of the most critical and valuable assets for any organization. As such, we prioritize managing our customers’ data security and privacy. To achieve this, we provide robust security features that manage network, application, and data security.

== Network Security
All communication between users and ThoughtSpot Cloud is encrypted using SSL for secure transmission of data. ThoughtSpot Cloud supports TLS 1.2 and higher. In addition, ThoughtSpot has many built-in security mechanisms to help prevent spoofing, hijacking, and SQL injection attacks, and it actively tests and responds to new threats with monthly updates.

=== Application Security
The ThoughtSpot Cloud environment is hosted in a multi-tenant configuration providing separation of users, data, and metadata across customers.

== Data security

=== Encryption at rest

ThoughtSpot provides standard Encryption at Rest (EAR) for storage encryption.
This includes centralized key management, key rotation, and key revocation.

[#advanced-data-ear]
==== Advanced data encryption at rest [.badge.badge-aws]#AWS-only#
ThoughtSpot provides advanced data encryption at rest (EAR) that allows for granular user and folder level controls for encrypting your persistent data. To enable Advanced EAR in your environment, contact {support-url}. Note that there is a lead time for enablement of Advanced EAR. {support-url} notifies you of the lead time when you open a request.
////
=== Secure Erase

Current erase guide: see https://thoughtspot.egnyte.com/dl/E1eYDyfotL/SOP-520-0007-00-User-Data-Removal.pdf_[Secure Erase Guide^].
////

=== ThoughtSpot Trust Center
https://www.thoughtspot.com/legal/trust
