= About row-level security (RLS)
:page-last_updated: 12/8/2025
:linkattrs:
:experimental:

:page-aliases: /admin/data-security/about-row-security.adoc
:description: Using row-level security (RLS), you can restrict data that appears in search results and Liveboards by group or user.
:jira: SCAL-230550, SCAL-264258, SCAL-286556, SCAL-286659, SCAL-292858


Row-level security (RLS) allows you to restrict access to table row data at group-level or user-level.
You do this by creating a _rule_ that associates a filter with a group.
When a group member searches, views an Answer, or otherwise works with data, ThoughtSpot evaluates the rules and prevents the display of the restricted data.
Users see only the data they are permitted to see.

NOTE: RLS is not applied to the string values defined in a custom sort order.

== How does RLS impact user interactions?

The security rules apply to objects shared with users individually or through groups they are a member of.
The rules restrict the visible data when users:

* view a table.
* view a Model derived from the table.
* search for data in the Model or table.
* view Answers from restricted data - either that they've created or that were shared with them.
* interact with Liveboards from restricted data - either that they've created or that were shared with them.

////
Search suggestions also fall under row-level security.
If a user would not have access to the row data, then values from the row do not appear in *Search* suggestions.

If RLS is applied to the cluster, and the creator of a Liveboard sets up default values in a Liveboard filter, the default values will be visible to everyone who has access to the Liveboard in the filter chip preview and in the tooltip. The data is filtered based on RLS, but the filter chip preview and tooltip do not follow RLS.
////

== Strict RLS

This is the default setting applied to clusters. This ensures that if an RLS rule is defined then this is always included in any query to the database. A query to the database refers to both a search to return results or a query initiated from a filter widget.

This setting can be disabled so that RLS rules are only included when the table that has the rule defined is included in the search results. This behavior may be desirable for very large datasets to improve performance. That is, the rule is applied to the fact table so that these results are secured. However, the RLS rule does not need to be included for dimensional tables.

See xref:advanced-commands.adoc[Cluster-level settings].

== Search Index and RLS

A search suggestion does not execute a query to the database. Rather, this is a value returned from the index stored by ThoughtSpot. These suggestions are displayed as Search typeahead suggestions, Liveboard Explore suggested tokens, and the Search Data column information card.

These suggestions respect RLS rules when the rule is defined explicitly on the table that the column is derived from. For example, assume the RLS rule is defined on the customer table. Then all search suggestions for the customer columns will have RLS applied. However, columns from the products table will not have the suggestions secured by this RLS rule.

As an analyst, you need to determine which tables require RLS to be applied to the suggestions. You then need to model the data in a way to ensure that the RLS rule can be defined on the table. If a data model includes multiple RLS rules, you may wish to consider disabling strict RLS.

video::dK5hOnPdwLA[youtube,title="ThoughtSpot Success Series: Row Level Security Design Patterns",width="375",height="210",frameborder="0",allow="accelerometer"]

If you are using passthrough security for a connection, search suggestions may not fall under row-level security.
When using passthrough security, ThoughtSpot builds the search index on the user who created the connection.
This user may have less restrictive row-level-security, or may be able to see all data.
Other users may be able to see search suggestions for columns or values they should not see.
They cannot run queries on these columns or values, however.

Search indexes are built based on the columns that have indexing enabled on them. When a valid row-level security rule is in place, then the index is created per the RLS rule, at group or user level, or at a combination of those levels. Because passthrough security may allow users to see search suggestions they should not have access to, if you are using passthrough security, ThoughtSpot recommends you xref:data-modeling-index.adoc#dont-index[turn off indexing] for sensitive columns.

[#respect]
== Respect join definitions

The following is an example SQL query result of a FULL OUTER JOIN between a sales table and a customer table.   These tables are joined on the CUSTOMER_ID field where CUSTOMER_ID_FACT is the many side of the join and CUSTOMER_ID_DIM is the one side of the join.

As per the following table:

C1 has a corresponding row on both tables.

C2 only has a record on the customer table. That is, this is a customer with no sales.

C5 only has a record on the fact table. That is, this is a customer that has been removed from the master customer dimension table.

[options="header"]
|===
| CUSTOMER_ID_FACT | CUSTOMER_ID_DIM

| C1 | C1

| C1 | C1

| C5 |

| | C2
|===

=== RLS rule definition

For this example the RLS rule will be defined based upon group membership. That is, the user must be a member of group with the same name as the CUSTOMER_ID field, where the valid values are: C1, C2, C5.

This rule could be defined in the following ways:

. Defined on the fact and reference the fact table.

. Defined on the fact and references the dimension table.

. Defined on the dimension.

Importantly, these definitions impact the final setup required for joins to be respected.

=== Right outer join → Return all customers, including those that have not made a sale

1. Defined on the fact and reference the fact table. This requires an additional OR condition to check for NULL customer_id values on the fact. That is, return all customers from the dimension.
+
`ts_groups = customer_id_fact or is_null(customer_id_fact)`

2. Defined on the fact and references the dimension table.
+
`ts_groups = customer_id_dim`

3. Defined on the dimension.
+
`ts_groups = customer_id_dim`

=== Left outer join → Return all transactions irrespective of if there is a matching row in the customer dimension table.

. Defined on the fact and reference the fact table.
+
`ts_groups = customer_id_fact`

. Defined on the fact and references the dimension table. This requires an additional OR condition to check for NULL customer_id values on the customer table.
+
`ts_groups = customer_id_dim or is_null(customer_id_dim)`

. Defined on the dimension. This requires an additional OR condition to check for NULL customer_id values on the customer table.
+
`ts_groups = customer_id_dim or is_null(customer_id_dim)`

=== Full outer join → Return all transactions and all customers.

No matter the RLS definition location, additional RLS rules are required to check for NULL customer IDs on both the fact and customer tables.

. Defined on the fact and reference the fact table.
+
`ts_groups = customer_id_fact or is_null(customer_id_fact) or is_null(customer_id_dim)`

. Defined on the fact and references the dimension table.
+
`ts_groups = customer_id_dim or is_null(customer_id_fact) or is_null(customer_id_dim)`

. Defined on the dimension.
+
`ts_groups = customer_id_dim or is_null(customer_id_fact) or is_null(customer_id_dim)`

[#reasons]
== Why use RLS?

RLS allows you to set up flexible rules that are self-maintaining.
An RLS configuration can handle thousands of groups.
There are several reasons you might want to use row-level security:

Hide sensitive data from groups who should not see it::
  In a report with customer details, hide potential customers (those who have not yet completed their purchase) from everyone except the sales group.
Filter tables to reduce their size, so that only the relevant data is visible::
  Reduce the number of rows that appear in a very large table of baseball players, so that players who are no longer active are not shown except to historians.
Enable creation of a single Liveboard or visualization, which can display different data depending on the group who is accessing it::
  Create one sales Liveboard that shows only the sales in the region of the person who views it. This effectively creates a personalized Liveboard, depending on the viewer's region.

'''
> **Related information**
>
> * To continue learning about RLS, see xref:security-rls-concept.adoc[How rule-based RLS works].
> * *Search* suggestions relies on compile indices to present suggestions to users from your data.
See xref:data-modeling-index.adoc#[Manage suggestion indexing] to learn how to configure suggestions.
> * xref:security-data-object.adoc[]
