= Share Models
:last_updated: 2/13/2020
:linkattrs:
:experimental:
:page-layout: default-cloud
:page-aliases: /admin/data-security/share-models.adoc
:description: You can share Models with users or with groups. Sharing a Model allows users to select it as a data source and search it.
:jira: SCAL-264258

When you share a Model, you give users or groups within your cluster access to the Model's data.
You share all of its columns.
Sharing a Model does not share the underlying tables.
If you want to share the underlying tables, see xref:share-source-tables.adoc#[Sharing tables and columns].

If you want to migrate the Model to another cluster, or otherwise export it, see xref:scriptability.adoc[Migrate or restore Models].

A Model can be shared by the owner of the Model, or by an administrator. If your organization is using xref:orgs-overview.adoc[multi-tenancy with Orgs], you can only share with other users in your specific Org.
Users can start searching a Model as soon as the Model is shared with them.

You can share a Model from the list of Models under *Models* <<share-datatab,on the *Data* tab>>, or from <<share-dataset,within the Model>>.

include::partial$share-data.adoc[]

'''
> **Related information**
>
> * xref:share-source-tables.adoc[Share tables and columns]
> * xref:share-views.adoc[Share views]
> * xref:share-liveboards.adoc[Share Liveboards]
> * xref:share-answers.adoc[Share Answers]
> * xref:share-revoke-access.adoc[Revoke access]
> * xref:security-data-object.adoc[]