= Overview of sharing
:last_updated: 6/04/2025
:linkattrs:
:experimental:
:page-layout: default-cloud
:page-aliases: /end-user/data-view/sharing-for-end-users.adoc
:description: Learn how to share Answers and Liveboards.
:jira: SCAL-257699, SCAL-264258




Whenever you are working in ThoughtSpot, you are in your own private environment until you share your work with others.
Sharing applies to searches, Liveboards, and data from xref:connections.adoc[Connections].
You share by selecting the *Share* button from within the object you want to share and specifying the users or groups with whom you want to share.
An email notification goes out to those users or groups when you select *Share*.

If your organization is using xref:orgs-overview.adoc[multi-tenancy with Orgs], you can only share with other users in your specific Org.

== What you can share

This is a list of objects a regular, non-administrator user can share.
Administrators have more granular control over data security.

You can share with groups and with individual people.
You can share different types of objects:

[width="100%",cols="20%,40%,40%"]
|===
| Object type | Description | Default security model

| Liveboards
| A Liveboard of saved search results.
| Anyone who can view a Liveboard can share it.
See xref:share-liveboards.adoc#[share a Liveboard].

| Answers
| The result of a single search.
| Anyone who can view an Answer can share it.
See xref:share-answers.adoc[share Answers].
|===

== Who can share and to whom

You do not have to be an administrator or the owner of an object to share saved Answers or Liveboards.
Any user can share them, based on the access levels the user has.

If you share *Can View* or *Can Edit* privileges for an object with other people, they can further share them with others.
This last point is important.
Like sharing a secret, sharing an object or your data can quickly spread in this way to people you do not intend it to.
So, if your data or work is sensitive to your business be thoughtful in how you share it.

Finally, you can revoke access to an object (table, Model, or Liveboard) that you have previously shared.
Unsharing an object is very similar to sharing it.

[#discoverable-liveboards-answers]
== Discoverability of Liveboards and Answers

If you mark an Answer or Liveboard as discoverable, it is "shared" with users in the groups to which you belong as long as they have access to the data source. With Liveboards, data source access is defined as having access to all the data sources used in the Liveboard. To have data source access, a user must have access to at least one of the data sources used for the visualizations in the Liveboard.

When a user who has data source access clicks a Liveboard or Answer they can see the actual details of the object in view mode.

If a user does not have access to the data source access, they will need to request access. For more information, see xref:share-request-access.adoc[Request access].


