= Sharing tables and columns
:last_updated: 11/05/2021
:linkattrs:
:experimental:
:page-layout: default-cloud
:page-aliases: /admin/data-security/share-source-tables.adoc
:description: As an administrator, you can share view or edit access to any table.




By default, tables are only visible to administrators.
Administrators and owners can share *Can View* or *Can Edit* privileges on tables with other users, who can further share them with others. If your organization is using xref:orgs-overview.adoc[multi-tenancy with Orgs], you can only share with other users in your specific Org.

When you share a table, you can share the entire table, or specific columns.
For column level security (CLS), share only specific columns. For more information about CLS, see xref:security-data-object.adoc[].

== Permissive or strict sharing

Use caution when sharing tables, because any objects created from that table will have dependencies on it and its underlying structure.
Objects created from tables can include Worksheets, views, Answers, and Liveboards.
This means that if a user wants to drop or modify a table, any object that depends upon it must be edited or removed first, to remove the dependency.

For this reason, it is a best practice to only grant the *Edit* permission on a table to a small number of users.
If you want to prevent shares from also revealing the columns regardless of where it appears (Worksheets, Answers, and Liveboards), you can ask {support-url} to enable a stricter behavior.

You can share a table or multiple tables <<share-datatab,from the *Data* tab>>, or share a single table <<share-dataset,from within the table>> that you want to share.

include::partial$share-data.adoc[]

'''
> **Related information**
>
> * xref:security-data-object.adoc[]
> * xref:share-worksheets.adoc[Share Worksheets]
> * xref:share-views.adoc[Share views]
> * xref:share-liveboards.adoc[Share Liveboards]
> * xref:share-answers.adoc[Share Answers]
> * xref:share-revoke-access.adoc[Revoke access]
