= Share views
:last_updated: 2/13/2020
:linkattrs:
:experimental:
:page-layout: default-cloud
:page-aliases: /admin/data-security/share-views.adoc
:description: You can share Views with users or with groups. Sharing a View allows users to select it as a data source and search it.

When you share a view, you share all of its data.
Sharing a view does not share the underlying tables.
If you want to share the underlying tables, see xref:share-source-tables.adoc#[Sharing tables and columns].
A view can be shared by the owner of the view, or by an administrator. If your organization is using xref:orgs-overview.adoc[multi-tenancy with Orgs], you can only share with other users in your specific Org.
Users can start searching a view as soon as the view is shared with them.

You can share a view from the list of views under *Views* <<share-datatab,on the *Data* tab>>, or from <<share-dataset,the view itself>>.

include::partial$share-data.adoc[]

'''
> **Related information**
>
> * xref:share-source-tables.adoc[Share tables and columns]
> * xref:share-worksheets.adoc[Share Worksheets]
> * xref:share-liveboards.adoc[Share Liveboards]
> * xref:share-answers.adoc[Share Answers]
> * xref:share-revoke-access.adoc[Revoke access]
> * xref:security-data-object.adoc[]
