= Share worksheets
:last_updated: 12/31/2020
:linkattrs:
:experimental:
:page-partial:

You can share worksheets with users or with groups.

Sharing a worksheet allows users to select it as a data source and search it.  When you share a worksheet, you give users or groups within your cluster access to the worksheet's data.
You share all of its columns.
Sharing a worksheet does not share the underlying tables.
If you want to share the underlying tables, see xref:share-source-tables.adoc[Sharing tables and columns].

If you want to migrate the worksheet to another cluster, or otherwise export it, see xref:scriptability.adoc[Migrate or restore objects].

A worksheet can be shared by the owner of the worksheet, or by an administrator.
Users can start searching a worksheet as soon as the worksheet is shared with them.

You can share a worksheet from the list of worksheets under *worksheets* <<share-datatab,on the *Data* tab>>, or from <<share-dataset,within the worksheet>>.

include::partial$share-data.adoc[]
