= Share Worksheets
:last_updated: 2/13/2020
:linkattrs:
:experimental:
:page-layout: default-cloud
:page-aliases: /admin/data-security/share-worksheets.adoc
:description: You can share Worksheets with users or with groups. Sharing a Worksheet allows users to select it as a data source and search it.

When you share a Worksheet, you give users or groups within your cluster access to the Worksheet's data.
You share all of its columns.
Sharing a Worksheet does not share the underlying tables.
If you want to share the underlying tables, see xref:share-source-tables.adoc#[Sharing tables and columns].

If you want to migrate the Worksheet to another cluster, or otherwise export it, see xref:scriptability.adoc[Migrate or restore Worksheets].

A Worksheet can be shared by the owner of the Worksheet, or by an administrator. If your organization is using xref:orgs-overview.adoc[multi-tenancy with Orgs], you can only share with other users in your specific Org.
Users can start searching a Worksheet as soon as the Worksheet is shared with them.

You can share a Worksheet from the list of Worksheets under *Worksheets* <<share-datatab,on the *Data* tab>>, or from <<share-dataset,within the Worksheet>>.

include::partial$share-data.adoc[]

'''
> **Related information**
>
> * xref:share-source-tables.adoc[Share tables and columns]
> * xref:share-views.adoc[Share views]
> * xref:share-liveboards.adoc[Share Liveboards]
> * xref:share-answers.adoc[Share Answers]
> * xref:share-revoke-access.adoc[Revoke access]