= OAuth sign-in for Liveboards
:page-layout: default-cloud-early-access
:last_updated: 11/12/2024
:author: Naomi
:linkattrs:
:experimental:
:description:
:jira: SCAL-219411
:page-aliases: enable-single-window-oauth.adoc, oauth-redirect.adoc
// don’t put in what’s new or release notes

Admin users can now control how users sign in to Connections authenticated using OAuth when the connection authentication has expired. Using the Automatic OAuth Sign-in Trigger option in the Early Access panel, admin users can set the *Sign in with OAuth* button to be automatically triggered in a Liveboard when the authentication of the underlying Connections expires. Using the OAuth Redirection Behavior option in the Early Access panel, admin users can ensure that the connection authentication flow opens in the current page, rather than a new tab.

== Automatic OAuth Sign-in Trigger

To enable the Automatic OAuth Sign-in Trigger feature, navigate to the Early Access feature page in the Admin tab and set *Automatic OAuth Sign-in Trigger* to *Enable*. Users will see the *Sign in with OAuth* button automatically trigger the sign-in process on Liveboards built on Connections authenticated with OAuth when the authentication expires.

== OAuth Redirection Behavior

To enable the OAuth Redirection behavior feature, navigate to the Early Access feature page in the Admin tab and set *OAuth Redirection Behavior* to *Enable*. Users will be able to log in to the Connection within the same tab as their Liveboard, and be directed to the Liveboard once the credentials are authenticated.
