= Integrate with Snowflake Semantic Views
:page-last_updated: 4/29/2026
:linkattrs:
:experimental:
-early-access
:author: Mary
:jira: SCAL-276952, SCAL-316441, SCAL-320368
:description: ThoughtSpot's Snowflake semantic views integration allows you to import your semantic layer into ThoughtSpot Models.

ThoughtSpot integrates with Snowflake Semantic Views, allowing you to leverage semantic models defined in Snowflake in ThoughtSpot. This enables centralized metric and business logic management in Snowflake, while providing a seamless analytics experience in ThoughtSpot, by leveraging Snowflake’s semantic layer. The integration is designed for flexibility, efficiency, and to improved data governance and discoverability.

The integration supports both direct connection to Snowflake and YAML file uploads for flexibility.

Administrators can manage and resync Semantic Views as needed to reflect changes made in Snowflake.

NOTE: The Snowflake Semantic Views is in Early Access. To enable this feature, contact {support-url}.

Features:

* Connect directly to Snowflake Semantic Views from ThoughtSpot.
* Import semantic models, including metrics, formulas, and column descriptions, into ThoughtSpot.
* Use imported semantic views as data models for building dashboards, SpotIQ queries, and analytics.
* Column-level metadata and documentation from Snowflake are automatically pulled into ThoughtSpot.


NOTE: This integration is separate from dbt integration; you can choose to use either or both, depending on your data modeling strategy.

== Prerequisites

Please confirm that the user has access to all underlying tables referenced by the semantic view.


== Integrating with Snowflake
. Define Semantic Views in Snowflake:
.. Create semantic views in Snowflake using their native tools.
.. Add business logic, metrics, and column descriptions as needed.
. Connect ThoughtSpot to Snowflake:
.. In ThoughtSpot, select Snowflake as your data source.
.. Choose the relevant database and select the semantic view you want to use.
.. ThoughtSpot will import the semantic view, including all defined metrics and metadata.
. Use in ThoughtSpot
.. The imported semantic view appears as a data model in ThoughtSpot.
.. Build dashboards, run queries, and use SpotIQ on top of the imported model.
.. All business logic and metrics defined in Snowflake are available for analytics in ThoughtSpot.

When a semantic view is imported, tables are imported into ThoughtSpot using the aliases defined in the semantic view. If a table already exists in the connection with a different name, it is automatically renamed to match the alias during the semantic view import.

== Limitations

If the semantic model has two or more tables, then the tables must have joins defined.

Snowflake window functions are not supported in ThoughtSpot.




