= Spotter Agent
:last_updated: 6/2/2025
:author: Naomi
:linkattrs:
:experimental:
:page-layout: default-cloud
:description: Spotter Agent is designed to interact with your questions naturally.
:jira: SCAL-256741


Spotter Agent is designed to interact with your questions naturally. Spotter Agent enhances the Spotter experience by helping you with the following:

* Answering data literacy questions
* Providing responses for questions not related to selected data model
* Providing suggestions on what questions to ask
* Providing details on how a metric is calculated
* Answering compound questions

== Limitations


* If Spotter Agent cannot access the answer data, it cannot summarise results in the conversation.
* Spotter Agent cannot change chart types.
* Although Spotter Agent cannot answer why questions, it will provide suggestions on how to further analyse your data.
* Spotter Agent currently does not support the ability to coach from a conversation.
* Coaching for non-data questions is not available, these questions are addressed based on metadata from the Worksheet or Model.
* Spotter Agent only works with Azure OpenAI models right now.
* Spotter Agent is optimized for the English language and may not be fully locale-aware.
* The following functionalities of spotter are not available in Spotter Agent in 10.9.0.cl:

** What’s changed: Spotter  usually shows the difference from the last answer above the answer, this will not be available once you switch to Spotter Agent.
** Spotter interpretations: Spotter Agent may not show the Spotter interpretations.
** Human-in-the-loop feedback: Spotter agent doesn't support human-in-the-loop feedback.