= Limitations
:page-last_updated: Sep 10, 2025
:author: Naomi
:linkattrs:
:experimental:
:page-layout: default-cloud
:description: Learn about Spotter’s limitations.
:jira: SCAL-271623, SCAL-273864, SCAL-287506

Spotter bases its answers on metadata, and does not directly handle the data it fetches. This limits certain capabilities of Spotter.

== #Spotter Classic limitations#

#Why questions:: Why questions such as “Why did my sales go down in Q2?” are not supported and should be avoided.#

#Data source questions:: Spotter Classic cannot answer descriptive questions about data sources, such as “How many columns does the worksheet have?”#

#Chart types:: You cannot change chart types by request. To access additional chart types, go to the Edit Answer option in the context menu.#

#Data model:: Spotter Classic cannot automatically identify which data model to use. You must select a data model to start asking questions.#

////
Summaries:: Currently, Spotter has trouble summarizing your data. In text responses, it will only respond with the metadata.

Chart understanding:: While Spotter can apply specific chart types when requested, it doesn't always understand which chart type you intended.

Irrelevant query handling:: When asked questions unrelated to the available data (for example, stock market data), Spotter responds with a null or an error mentioning that columns or data are not available. This error is more common if you are using the classic Spotter experience.

Sample questions control:: Today, you cannot control which sample questions will be visible below the Spotter search bar on the home page.

Data source selection:: Currently, you need to select the data source first before asking a question.

Internationalization:: Note that if you coach a question in Japanese, then ask the same question in French, Spotter will not be able to apply the coaching to the French language.

Instructions and training:: Coaching for non-data questions is not available; these questions are addressed based on metadata from the Model.
////

== #Spotter Agent limitations#

#Summaries:: Currently, Spotter Agent doesn’t have access to your data; hence, in text responses, it only responds with the metadata.#

#Chart understanding:: Spotter Agent understands standard visualizations such as bar chart, line chart, or donut chart. You can edit the answer from the context menu to change additional chart types and advanced chart settings.#

#Instructions and training:: Use natural language instructions to define business logic and data relationships. Controls for agent tonality, narrative style, granular chart formatting, and coaching for why analysis are not currently supported.#

#Data source selection:: Like Spotter Classic, Spotter Agent can’t automatically identify which data model to use; you need to select a data model to start asking questions.#

////
Note that Spotter Agent is only available if your instance uses the Azure OpenAI LLM.

The following functionalities of Spotter are not available in Spotter Agent in 10.13.0.cl:

* What’s changed: Spotter usually shows the difference from the last Answer above the latest Answer. This functionality is not available once you switch to Spotter Agent.
* Spotter interpretations: Spotter Agent may not show the Spotter interpretations.
* Human-in-the-loop feedback: Spotter Agent doesn’t support human-in-the-loop feedback.
* Locale awareness: Spotter Agent translates queries set in other locales to English, and presents its results in English.
////

== #Spotter 3 limitations#

#Chart understanding#:: #Spotter 3 understands standard visualizations such as bar chart, line chart, or donut chart. You can edit the answer from the context menu to change additional chart types and advanced chart settings.#

#Instructions and training:: Use natural language instructions to define business logic and data relationships. Controls for agent tonality, narrative style, granular chart formatting, and coaching for why analysis are not currently supported.#

