= ThoughtSpot Developer portal
:last_updated: 2/23/2022
:linkattrs:
:experimental:
:page-layout: default-cloud
:page-aliases: /admin/ts-cloud/spotdev-portal.adoc
:description: The ThoughtSpot Developer portal allows developer users to explore the embed APIs, preview code snippets, and view developer documentation.


The ThoughtSpot Developer portal allows you to explore the SDK and APIs, preview code snippets, customize styles and UI elements, and view developer documentation.

You can also add custom actions and configure authentication and security settings for an embedded instance.

== Access Develop tab

*If you have a ThoughtSpot user account*:

. Sign in to your ThoughtSpot application instance.
. Make sure your account has developer or administrator privileges.
+
For information about configuring a user group with developer privileges, see https://developers.thoughtspot.com/docs/?pageid=developer-access[ThoughtSpot Developer Documentation, window=_blank].

. Navigate to the *Develop* tab.

*If you do not have a ThoughtSpot user account*:

. Go to https://developers.thoughtspot.com/[developers.thoughtspot.com, window=_blank].
. On the header bar, click *Playground*.

NOTE: You can also register for a free trial and evaluate the SDK and APIs on a ThoughtSpot Free Trial instance.

== Find your way around

The *Develop* tab includes several sections to assist you through your embedding journey.

Home::
The *Home* page provides a pictorial view of the ThoughtSpot features that you can integrate with your applications.
The *Home* page also includes links to the *Developer Guides* and *Playground* to preview the code snippets.

Visual Embed SDK::
Includes the following menu items:
+
*Guide* +
Opens the Visual Embed documentation.
+
*Playground* +
Opens the Visual Embed Playground. You can explore the SDK and APIs available for embedding ThoughtSpot Search, Liveboard, visualization, or the full application experience, and view customization options.

REST API::
Includes the following menu items:

+
*Guide* +
Opens the REST API documentation.
+
*REST Playground v1* +
Opens the REST API v1 Explorer page. This page allows you to make REST API calls to the REST API v1 endpoints and view API responses.
+
*REST Playground v2.0* +
Opens the REST API v2.0 Playground, which allows you to view the v2.0 endpoints, make API calls, and explore the request and response workflows.

Customizations::
The Developer portal displays the following menu options under **Customizations**:

* *Custom actions* +
UI workflows to xref:custom-actions.adoc[create, edit and delete custom actions].
* *Styles* +
Customization controls to xref:customization-rebranding.adoc[rebrand the embedded ThoughtSpot UI elements, styles, and footer text].
* *Security Settings* +
xref:auth-overview.adoc[Security and authentication settings] for an embedded application instance.
* *Links settings* +
Configuration settings to https://developers.thoughtspot.com/docs/?pageid=customize-links[customize the format of system-generated links, window=_blank].

