= SpotApps
:last_updated: 6/13/2022
:experimental:
:linkattrs:
:page-layout: default-cloud
:description: SpotApps, ThoughtSpot's scriptable applications, are out-of-the-box solution templates built for specific use cases and data sources.



SpotApps are ThoughtSpot's out-of-the-box solution templates built for specific use cases and data sources, such as Snowflake Performance and Consumption, or Jira Issue Management. Starting in ThoughtSpot's 8.5.0.cl release, SpotApps do *_not_* refer to any set of multiple TML files. To learn about migrating custom sets of TML files, refer to xref:tml-import-export-multiple.adoc[Migrate multiple TML files].

SpotApps are built on xref:tml.adoc[ThoughtSpot Modeling Language (TML)] Blocks, which are pre-built pieces of code that are easy to download and implement directly from the product.

SpotApps use ThoughtSpot's solution for xref:scriptability.adoc[migrating data models (Worksheets, tables, and views) and content (Liveboards and Answers)] between different environments, such as development and production. You can optionally edit these ThoughtSpot objects during the migration process.

== Available SpotApps and Blocks
ThoughtSpot currently supports the following SpotApps, built on Analytics Blocks. Analytics Blocks can include pre-built Worksheet, Answer, and Liveboard Blocks, based on your application data in your cloud data warehouse.

xref:spotapps-databricks.adoc[Databricks Storage and Performance]::
Use this SpotApp to manage Databricks costs and investigate query performance.
xref:spotapps-dei.adoc[DEI Workforce Diversity]:: Use this SpotApp to get invaluable insight into your workforce diversity data from your HR application.
xref:spotapps-facebook.adoc[Facebook Ads]:: Use this SpotApp to measure ad performance across platforms to grow reach, engagement, & sales.
xref:spotapps-gbq.adoc[GBQ Performance and Consumption]::
Use this SpotApp to manage GBQ costs and consumption.
xref:spotapps-google-ad-analysis.adoc[Google Ad Analysis]:: Use this SpotApp to get invaluable insight into your Google Ads performance, from high-level usage to identifying popular campaigns.
xref:spotapps-google-analytics.adoc[Google Analytics]::
Use this SpotApp to analyze Google Analytics data about customer engagement with your website and any ads on the website.
xref:spotapps-hubspot.adoc[HubSpot Email Marketing]::
Use this SpotApp to identify the success of your HubSpot email campaigns.
xref:spotapps-jira-issue.adoc[Jira Issue Management]::
Use this SpotApp to track the number of Jira tickets submitted, and the efficiency of how they are resolved.
xref:spotapps-jira-sprint.adoc[Jira Sprint Management]::
Use this SpotApp to keep your Jira sprints on track with live insights into priorities, backlog, and progress.
xref:spotapps-linkedin-ads.adoc[LinkedIn Ads]:: Use this SpotApp to get invaluable insight into your LinkedIn Ads performance, from high-level usage to identifying popular projects.
xref:spotapps-okta.adoc[Okta Application Management]::
Use this SpotApp to understand any Okta login problems and application adoption within your company.
xref:spotapps-redshift.adoc[Redshift Performance and Consumption]::
Use this SpotApp to manage Redshift costs and investigate query performance.
xref:spotapps-salesforce.adoc[Salesforce Pipeline Analysis]::
Use this SpotApp to track how prospects progress closer to closed deals.
xref:spotapps-procurement-vulnerability.adoc[Procurement Vulnerability Analysis for SAP]:: Use this SpotApp to quickly identify where disruptions could occur in your global supply chain, reducing risk and building resilience.
xref:spotapps-servicenow.adoc[ServiceNow Incident Management]::
Use this SpotApp to track ServiceNow tickets and manage incidents.
xref:spotapps-snowflake.adoc[Snowflake Performance and Consumption]::
Use this SpotApp to manage Snowflake costs and investigate query performance.

SpotApps are built specifically for their application's out-of-the-box data model. To deploy a SpotApp successfully, you must ensure the data exists in your cloud data warehouse according to the required schema. Customizations can be handled with manual edits during the deployment and mapping process. For more information, refer to xref:spotapps-deploy.adoc[Deploying SpotApps].

[#prerequisites]
== Prerequisites to deploy SpotApps
To deploy any SpotApp, you must:

include::partial$spotapp-prereqs-general.adoc[]

== Deploying SpotApps
After you complete the <<prerequisites,prerequisites>>, you are ready to deploy SpotApps and begin leveraging their pre-built content.

Refer to the following articles, depending on the SpotApp you would like to deploy:

* xref:spotapps-databricks.adoc[Deploying the Databricks Storage and Performance SpotApp]
* xref:spotapps-dei.adoc[Deploying the DEI Workforce Diversity SpotApp]
* xref:spotapps-facebook.adoc[Deploying the Facebook Ads SpotApp]
* xref:spotapps-gbq.adoc[Deploying the GBQ Performance and Consumption SpotApp]
* xref:spotapps-google-ad-analysis.adoc[Deploying the Google Ad Analysis SpotApp]
* xref:spotapps-google-analytics.adoc[Deploying the Google Analytics SpotApp]
* xref:spotapps-hubspot.adoc[Deploying the HubSpot Email Marketing SpotApp]
* xref:spotapps-jira-issue.adoc[Deploying the Jira Issue Management SpotApp]
* xref:spotapps-jira-sprint.adoc[Deploying the Jira Sprint Management SpotApp]
* xref:spotapps-linkedin-ads.adoc[Deploying the LinkedIn Ads SpotApp]
* xref:spotapps-okta.adoc[Deploying the Okta Application Management SpotApp]
* xref:spotapps-redshift.adoc[Deploying the Redshift Performance and Consumption SpotApp]
* xref:spotapps-salesforce.adoc[Deploying the Salesforce Pipeline Analysis SpotApp]
* xref:spotapps-procurement-vulnerability.adoc[Deploying the Procurement Vulnerability Analysis for SAP SpotApp]
* xref:spotapps-servicenow.adoc[Deploying the ServiceNow Incident Management SpotApp]
* xref:spotapps-snowflake.adoc[Deploying the Snowflake Performance and Consumption SpotApp]
