= How Spotter uses your data
:last_updated: 9/10/25
:author: Naomi
:page-layout: default-cloud
:linkattrs:
:experimental:
:description: ThoughtSpot ensures that our use of AI prioritizes the security, privacy, and governance of your data.
:jira: SCAL-271626

ThoughtSpot ensures that our use of AI prioritizes the security, privacy, and governance of your data.

== Your data is not used for AI model training

A core principle of our AI implementation is that customer data is not used to train or improve the underlying AI models.

Our third-party LLMs, provided by Microsoft Azure and Google Cloud, do not use customer data to train their foundation models, a policy that ThoughtSpot adheres to. ThoughtSpot does not enable model training with customer data.

The statistical models used for SpotIQ forecasts are custom-fit for each specific request. They are not reused for other requests or improved based on any data they process.

== Your data is not stored by AI technologies

Customer data is not persisted by the AI technologies ThoughtSpot uses, it is deleted immediately after processing.

Azure OpenAI:: Data sent to these models is only held for the time necessary to process a user’s query. ThoughtSpot has been approved for “modified” abuse monitoring, meaning customer data is not persisted or logged.

Google Gemini:: Customer data is not persisted or logged during Google’s safety monitoring processes. Additionally, ThoughtSpot has disabled Google’s context caching feature to prevent data storage.

Audit logs:: While audit logs are maintained for services, they do not include any customer data, user prompts, or results.

== AI features are opt-in only

ThoughtSpot ensures that customers have complete control over the use of AI features.

All AI-powered features– including Spotter, SpotIQ, AI Highlights, and AI Assist– are disabled by default. You can choose to enable these features for specific Models or columns, ensuring that AI is only applied where you want it. This opt-in approach gives you the power to govern how and when AI interacts with your data.
