= How Spotter works in non-English languages
:page-last_updated: Oct 10, 2025
:author: Naomi
:page-layout: default-cloud
:linkattrs:
:experimental:
:description: Spotter is now available in any locale supported by ThoughtSpot.
:jira: SCAL-276583

Spotter now has the following capabilities in non-English languages:

Change chart type:: When you request a specific type of chart, such as line chart, in your locale language, Spotter accurately responds with that chart type.


Interpretation:: Spotter’s interpretation of your question (the paragraph above the answer chart) now reflects the language you used to ask your question.

Localized keywords:: The keyword tokens within the Spotter answer (such as “sort by” or “growth of”) are now localized according to the language selected in profile.

Reference questions and business terms:: You can now create reference questions and business terms in your locale language, and Spotter will apply that coaching to your
Conversations.

Note that if you coach a question in Japanese, then ask the same question in French, Spotter will not be able to apply the coaching to the French language.
