= Supported languages in Spotter
:page-last_updated: Oct 10, 2025
:author: Naomi
:page-layout:
:linkattrs:
:experimental:
:description: Spotter is now available in any locale supported by ThoughtSpot.
:jira: SCAL-276583

Spotter is now able to understand and reply in every language supported in ThoughtSpot. You can update your system language from the user profile. Note that if you begin interacting with Spotter in one language, then change your locale and use it again, your chat history remains in the original language.

== Change your system language

include::partial$set_locale.adoc[]

== Spotter language capabilities

Change chart type:: When you request a specific type of chart, such as line chart, in your locale language, Spotter accurately responds with that chart type.


Interpretation:: Spotter’s interpretation of your question (the paragraph above the answer chart) now reflects the language you used to ask your question.

Localized keywords:: The keyword tokens within the Spotter answer (such as “sort by” or “growth of”) are now localized according to the language selected in profile.

Reference questions and business terms:: You can now create reference questions and business terms in your locale language, and Spotter will apply that coaching to your
Conversations.

Note that if you coach a question in Japanese, then ask the same question in French, Spotter will not be able to apply the coaching to the French language.
