= Limitations
:last_updated: 9/10/25
:author: Naomi
:linkattrs:
:experimental:
:page-layout: default-cloud
:description: Learn about Spotter’s limitations.
:jira: SCAL-271623, SCAL-273864

Spotter bases its answers on metadata, and does not directly handle the data it fetches. This limits certain capabilities of Spotter.
 
Summaries:: Currently, Spotter has trouble summarizing your data. In text responses, it will only respond with the metadata.

Chart understanding:: While Spotter can apply specific chart types when requested, it doesn't always understand which chart type you intended.

Irrelevant query handling:: When asked questions unrelated to the available data (for example, stock market data), Spotter responds with a null or an error mentioning that columns or data are not available. This error is more common if you are using the classic Spotter experience.

Sample questions control:: Today, you cannot control which sample questions will be visible below the Spotter search bar on the home page.

Data source selection:: Currently, you need to select the data source first before asking a question.

Internationalization:: Note that if you coach a question in Japanese, then ask the same question in French, Spotter will not be able to apply the coaching to the French language.

Instructions and training:: Coaching for non-data questions is not available; these questions are addressed based on metadata from the Model.

== Spotter Agent limitations

Note that Spotter Agent is only available if your instance uses the Azure OpenAI LLM.

The following functionalities of Spotter are not available in Spotter Agent in 10.13.0.cl:

* What’s changed: Spotter usually shows the difference from the last Answer above the latest Answer. This functionality is not available once you switch to Spotter Agent.
* Spotter interpretations: Spotter Agent may not show the Spotter interpretations.
* Human-in-the-loop feedback: Spotter Agent doesn’t support human-in-the-loop feedback.
* Locale awareness: Spotter Agent translates queries set in other locales to English, and presents its results in English.
