= ThoughtSpot Developer portal
:last_updated: 11/05/2021
:linkattrs:
:experimental:
:page-layout: default-cloud
:page-aliases: /admin/ts-cloud/spotdev-portal.adoc
:description: The ThoughtSpot Developer portal allows developer users to explore the embed APIs, preview code snippets, and view developer documentation.

include::partial$liveboards-announcement.adoc[]

The ThoughtSpot Developer portal allows developer users to explore the embed APIs, preview code snippets, and view developer documentation.

The ThoughtSpot Developer portal allows you to explore ThoughtSpot SDK, APIs, and build your web applications with ThoughtSpot content.
The portal enables business application owners and developers to learn about ThoughtSpot APIs, and evaluate ThoughtSpot features that are available for integration.
The portal also allows authorized users to customize and rebrand the look and feel of the UI and add custom actions to an embedded visualization or Liveboard.

== Access Developer portal

You can access the developer portal from your ThoughtSpot application instance or the https://developers.thoughtspot.com/[ThoughtSpot Developers] website.

*If you have a ThoughtSpot user account*:

. Log in to your ThoughtSpot application instances.
. Make sure your user account has admin or developer privileges.
+
For more information on configuring a user group with developer privileges, see the https://developers.thoughtspot.com/docs/?pageid=developer-access[ThoughtSpot Developer Documentation].

. Navigate to the *Develop* tab.

*If you do not have a ThoughtSpot user account*:

. Go to https://developers.thoughtspot.com/[developers.thoughtspot.com].
. From the header bar, click *Playground*.
. Enter your name and email address.
. Click *Try Live Playground*.

NOTE: You can also register for a free trial and evaluate the SDK and APIs on the ThoughtSpot free trial cluster.

== Find your way around

The Developer portal includes several sections to assist you through your embedding journey.

*Home*  +
The *Home* page of the Developer portal provides a pictorial view of the ThoughtSpot features that you can integrate with your applications.
The homepage also includes links to the *Developer Guides* and  *Playground* to preview the code snippet.

*Guide* +
The *Guide* menu displays the _ThoughtSpot Embed Developer Documentation_.
The documentation portal provides step-by-step instructions on how to use the ThoughtSpot Visual Embed SDK and REST APIs to integrate ThoughtSpot features into your application.

*Playground* +
The *Playground* provides an API playground to explore the following ThoughtSpot features.

* Search
* Visualizations
* Liveboards
* Full application For more information about how to use the playground, see https://developers.thoughtspot.com/docs/?pageid=dev-playground[Developer Playground].

*Customizations* +
For ThoughtSpot users with administrator and developer privileges, the Developer portal displays the following customization menu items:

* *Styles* +
A set of customization controls to xref:customization-rebranding.adoc[rebrand the embedded ThoughtSpot content].
* *Actions* +
Configuration workflows to xref:custom-actions.adoc[create and manage custom actions] in the ThoughtSpot UI.
* *Settings* +
Security controls to xref:auth-overview.adoc[add CORS and CSP hosts and define authentication method] for an embedded ThoughtSpot instance.
* *Links* +
Configuration settings to https://developers.thoughtspot.com/docs/?pageid=customize-links[customize the format of system-generated links].
