= Understand coaching levels
:last_updated: 8/18/25
:author: Naomi
:linkattrs:
:page-layout: default-cloud
:experimental:
:jira:
:jira: SCAL-228500, SCAL-244132, SCAL-245651, SCAL-254069, SCAL-265156, SCAL-264258
:description: When you provide coaching to Spotter, this coaching can impact either just your own experience or the experience of all users interacting with that data.

When you provide coaching to Spotter, this coaching can impact either just your own experience or the experience of all users interacting with that data. We define these levels of coaching as user level and global level. Global-level coaching is used to refine answers for _all users_ querying that specific Model. It represents a verified, common understanding or definition that the organization wants Spotter to use universally for that dataset.

If you have Model editing access (that is, if you’re a Model editor or an admin user), the reference questions and business term coaching you create or approve are applied at the global level by default, as you are considered a primary coach for the system on that data.

== Who can provide what kind of feedback?

General business users (with view access):: When these users provide feedback, it defaults to user level. This allows them to flag issues or suggest improvements without deep technical knowledge of the data model or global definitions.

Primary coaches (edit or admin access):: When these users create reference questions, define business terms, or approve coaching, it is typically applied at the global level. This is because these roles are entrusted with shaping the common analytical understanding for this dataset.

== Permissions

The following table clarifies each permission level, the coaching a user can view, and the actions you can take.


[options="header"]
|===
| Permission level | What coaching can you see? | What actions can you take?


| `NO_ACCESS`: User does not have access to a data set. | User cannot see any coaching from this data set, including any coaching they submitted before losing access. | Not applicable. User cannot see the coaching.


| `TABLE_READ_PERMISSION`: User has read access to a data set. a| User can view their own coaching for this data set. +
User cannot see coaching provided by others for this data set. a| User can *fix the answer* and *delete* the coaching submitted by all the users on the dataset. +
If the access is changed to *Global*, users cannot change the coaching. +
Users cannot *change access* of any coaching submitted on the data set.


| `TABLE_MODIFY_PERMISSION`: User has edit access to a data set. | User can view coaching submitted by all the users on the data set. | User can *change access*, *fix the answer*, and *delete* the coaching submitted by all users on the data set.


| Administrator | User can view coaching submitted by all the users for all the data sets in the selected Org. | User can *change access*, *fix the answer*, and *delete* the coaching submitted by all the users for all the data sets in the selected Org.
|===


IMPORTANT: For an Org-enabled cluster, only the coaching from the selected Org is visible.

== Delete, fix, or promote coaching

Primary coaches (like analysts or Model editors) can manage coaching contributions from all users on the datasets they oversee. Through the “Coach Spotter” interface, they can:

* review feedback submitted by any user.
* delete irrelevant or incorrect coaching.
* fix/edit existing coaching to improve its accuracy or clarity.
* promote valuable user-level coaching to global level, so it benefits all users of that data set.

This ensures that while all users can contribute to refining Spotter, global standards are maintained by those with deeper data and business expertise.
