= SpotIQ preferences
:last_updated: 02/04/2021
:linkattrs:
:experimental:
:page-layout: default-cloud
:description: Change your SpotIQ basic preferences.

Change your SpotIQ basic preferences.
These parameters and threshold settings are a subset of those available on the  xref:spotiq-custom.adoc[SpotIQ Customize analysis] dialog.
If you set them here, the settings persist for all your SpotIQ analyses, including when you run custom analyses, unless you explicitly reset options for a custom analysis.

== Manage SpotIQ preferences
You can set default preferences for all your SpotIQ analyses.

To specify your SpotIQ preferences, follow these steps:

. Select *SpotIQ* from the top navigation bar. If you do not see that tab, you do not have SpotIQ privileges; contact your administrator.

. Select *Default preferences* in the upper-right corner of your screen. If you are on the classic experience, select the *Preferences* tab, under the top navigation bar.

. Specify email preferences. SpotIQ can email you if an analysis is successful or if it fails. SpotIQ can also attach the analysis Liveboard to the email as a pdf.

. Specify data preferences: SpotIQ can exclude null values or measure values of 0 from the analysis. It can also auto-tune the date boundaries.

. Specify parameters for analysis: You can specify the maximum p-value, minimum and maximum correlation coefficient, maximum correlation lag, and minimum relative difference.

. Select *Save*.

'''
> **Related information**
>
> * xref:spotiq-best.adoc[Best practices]
> * xref:monitor.adoc[Monitor KPI]
> * xref:spotiq-custom.adoc[Custom SpotIQ analysis]
> * xref:spotiq-change.adoc[SpotIQ change analysis]
> * xref:spotiq-feedback.adoc[Insight feedback]