= ThoughtSpot Developer portal
:last_updated: 2/23/2022
:linkattrs:
:experimental:
:page-layout: default-cloud
:page-aliases: /admin/ts-cloud/spotdev-portal.adoc
:description: The ThoughtSpot Developer portal allows developer users to explore the embed APIs, preview code snippets, and view developer documentation.



The ThoughtSpot Developer portal allows you to explore the SDK and APIs, preview code snippets, customize styles and UI elements, and view developer documentation.

You can also add custom actions and configure authentication and security settings for an embedded instance.

== Access Developer portal

You can access the developer portal from your ThoughtSpot application instance or the https://developers.thoughtspot.com/[ThoughtSpot Developers, window=_blank] website.

*If you have a ThoughtSpot user account*:

. Sign in to your ThoughtSpot application instance.
. Make sure your user account has admin or developer privileges.
+
For more information about configuring a user group with developer privileges, see the https://developers.thoughtspot.com/docs/?pageid=developer-access[ThoughtSpot Developer Documentation, window=_blank].

. Navigate to the *Develop* tab.

*If you do not have a ThoughtSpot user account*:

. Go to https://developers.thoughtspot.com/[developers.thoughtspot.com, window=_blank].
. From the header bar, select *Playground*.

NOTE: You can also register for a free trial and evaluate the SDK and APIs on a ThoughtSpot Free Trial instance.

== Find your way around

The Developer portal includes several sections to assist you through your embedding journey.

Home::
The *Home* page of the Developer portal provides a pictorial view of the ThoughtSpot features that you can integrate with your applications.
The homepage also includes links to the *Developer Guides* and  *Playground* to preview the code snippet.

Guide::
The *Guide* menu displays the _ThoughtSpot Developer Documentation_.
The documentation portal provides step-by-step instructions on how to use the ThoughtSpot Visual Embed SDK and REST APIs to integrate ThoughtSpot features into your application.
+
NOTE: If the **REST API Playground and SDK** [.badge.badge-update]#Beta# feature is enabled on your instance, the *Guide* menu will appear as a sub-menu option under *REST API* and **Visual Embed SDK**.
Playground::
The *Playground* provides an API playground to explore the following ThoughtSpot features.

* Search
* Visualizations
* Liveboards
* Full application For more information about how to use the playground, see https://developers.thoughtspot.com/docs/?pageid=dev-playground[Developer Playground, window=_blank].
+
NOTE: If the **REST API Playground and SDK** [.badge.badge-update]#Beta# feature is enabled on your instance, the **Develop** tab displays the *REST Playground v1* and *REST Playground v2* menu options. For more information about these menu options, see link:https://developers.thoughtspot.com/docs/?pageid=rest-apis[ThoughtSpot REST APIs, window=_blank].

Customizations::
The Developer portal displays the following menu options under **Customizations**:

* *Custom actions* +
UI workflows to xref:custom-actions.adoc[create, edit and delete custom actions].
* *Styles* +
Customization controls to xref:customization-rebranding.adoc[rebrand the embedded ThoughtSpot UI elements, styles, and footer text].
* *Security Settings* +
 xref:auth-overview.adoc[Security and authentication settings] for an embedded application instance.
* *Links settings* +
Configuration settings to https://developers.thoughtspot.com/docs/?pageid=customize-links[customize the format of system-generated links, window=_blank].
