= Integrating the Spotter and Spotter Agent experience in external apps
:page-last_updated: Oct 6, 2025
:author: Shashi, Mark
:linkattrs:
:experimental:
:page-aliases:
:description:
:jira:

== Embedding Spotter or Spotter Agent

Developers can embed the Spotter and Spotter Agent experience into their application using the ThoughtSpot Visual Embed SDK. The SDK provides client libraries to integrate ThoughtSpot’s conversational analytics and agentic capabilities in your app. It also provides customization controls to modify the embed view as per business requirements.

The embedded ThoughtSpot Spotter experience allows product leaders to quickly integrate agentic analytics experiences into their applications, workflows, and custom agents, enhancing user engagement and generating new revenue streams with a faster time-to-market. Spotter Embed offers a seamless, low-cost solution that frees up valuable developer resources, ensuring you can focus on core product innovation while providing your customers with the actionable insights they need.

For more information, see https://developers.thoughtspot.com/docs/embed-ai-search-analytics[ThoughtSpot Embedded documentation^].

== Extending Spotter skills to agents with MCP

ThoughtSpot Multi-Client Protocol (MCP) Server integration enables a protocol-based connector that allows external agents or AI clients to interact with ThoughtSpot’s analytics capabilities. The MCP Server provides a wrapper and orchestration layer for Spotter APIs and enables AI agents to send natural language questions, retrieve structured data or insights from ThoughtSpot, and programmatically create Liveboards.  For more information, see https://developers.thoughtspot.com/docs/mcp-integration[MCP server integration^].

== REST APIs

Spotter REST APIs provide programmatic access to Spotter conversation sessions and analytics.  REST API clients can send questions and receive structured answers, charts, or get relevant questions for a specific data model. For information about these APIs, see https://developers.thoughtspot.com/docs/spotter-api[Spotter AI API documentation^].
