= Spotter limitations
:page-last_updated: Jan 23, 2026
:author: Naomi
:linkattrs:
:experimental:
:page-layout: default-cloud
:description: Learn about Spotter’s limitations.
:jira: SCAL-271623, SCAL-273864, SCAL-287506

Spotter bases its answers on metadata, and does not directly handle the data it fetches. This limits certain capabilities of Spotter. The article describes the limitations of each version of Spotter.

== Spotter 3 limitations

Chart understanding:: Spotter 3 understands standard visualizations such as bar chart, line chart, or donut chart. You can edit the answer from the context menu to change additional chart types and advanced chart settings.

Instructions and training:: Use data model instructions to define business logic and data relationships. Controls for agent tonality, narrative style, granular chart formatting, and coaching for why analysis are not currently supported.

Parameters:: Spotter does not support parameters. Spotter only works with the formula replaced with the parameter value - it cannot change the parameter applied.

== Spotter Agent (Spotter 2) limitations

Summaries:: Currently, Spotter Agent doesn’t have access to your data; hence, in text responses, it only responds with the metadata.

Chart understanding:: Spotter Agent understands standard visualizations such as bar chart, line chart, or donut chart. You can edit the answer from the context menu to change additional chart types and advanced chart settings.

Instructions and training:: Use data model instructions to define business logic and data relationships. Controls for agent tonality, narrative style, granular chart formatting, and coaching for why analysis are not currently supported.

Data source selection:: Like Spotter Classic, Spotter Agent can’t automatically identify which data model to use; you need to select a data model to start asking questions.

Parameters:: Spotter does not support parameters. Spotter only works with the formula replaced with the parameter value - it cannot change the parameter applied.


== Spotter Classic (Spotter 1) limitations

Why questions:: Why questions such as “Why did my sales go down in Q2?” are not supported and should be avoided.

Data source questions:: Spotter Classic cannot answer descriptive questions about data sources, such as “How many columns does the worksheet have?”

Chart types:: You cannot change chart types by request. To access additional chart types, go to the Edit Answer option in the context menu.

Data model:: Spotter Classic cannot automatically identify which data model to use. You must select a data model to start asking questions.

Parameters:: Spotter does not support parameters. Spotter only works with the formula replaced with the parameter value - it cannot change the parameter applied.

