= Style customization
:last_updated: 9/28/2020
:linkattrs:
:experimental:
:page-layout: default-cloud
:page-aliases: /admin/ts-cloud/style-customization.adoc, admin-portal-style-customization.adoc
:description: Style Customization allows you to change the overall style of your ThoughtSpot interface.


Style customization allows you to change the overall style of your ThoughtSpot interface.

NOTE: If your organization uses xref:orgs-overview.adoc[multi-tenancy with Orgs], you can apply global style customizations on the *All Orgs* tab in *Admin settings* and this applies to all Orgs. An Org administrator can set style customizations for individual Orgs which will override the global settings.


include::partial$style-customization.adoc[]

'''
> **Related information**
>
> * xref:admin-console-orgs-page.adoc[]
> * xref:admin-portal-users-orgs.adoc[]
> * xref:admin-portal-groups-orgs.adoc[]
> * xref:authentication-local.adoc[]
> * xref:authentication-saml.adoc[]
> * xref:user-adoption.adoc[]
> * xref:performance-tracking.adoc[]
> * xref:search-spotiq-settings.adoc[]
> * xref:onboarding-email-settings.adoc[]
> * xref:scheduled-maintenance.adoc[]