= System worksheets and views
:last_updated: 02/17/2021
:linkattrs:
:experimental:
:page-partial:
:page-aliases: /admin/system-monitor/worksheets.adoc

Learn about the system worksheets that ThoughtSpot provides.

Most of the monitoring information in *System Health* comes from system worksheets and views which administrators can view, but not modify.
The underlying tables are protected system tables that cannot be accessed directly.
However, administrators can create new, custom monitoring reports from the worksheets and views.

== List the system worksheets and views

To list the system worksheets and views:

. Go to the *Data* tab.
. Choose *All* and *All types*.
. Enter `System User` in the search field.

== Summary of the worksheets

Credits Purchased::
Contains data on the number of credits for xref:consumption-pricing.adoc[consumption-based pricing] your cluster has, and their expiration date. Used for the xref:consumption-pricing.adoc#credit-usage-pinboard[Credit Usage Pinboard].
Credit Usage::
Tracks the credits for xref:consumption-pricing.adoc[consumption-based pricing] your cluster has consumed. Used for the xref:consumption-pricing.adoc#credit-usage-pinboard[Credit Usage Pinboard].
Product Usage::
Contains usage data for the product. Specifies what existing Worksheets, tables, and Views users search on and create objects from, and what those objects are. Specifies what actions users complete in the product. You can also use this Worksheet to view the underlying data sources for any objects, and any object’s dependents. Used for the xref:object-usage-pinboard.adoc[Object Usage pinboard].
TS: BI Server::
	Contains data related to the systems associated with underlying the ThoughtSpot BI server. This includes database latency, browser clients, size of responses, and more.
TS: Database::
  Contains information related to the database cache and queries run on the database. For example, you could use this worksheet to see data on the query errors returned by the database.
TS: Internal Capacity WS::
  Describes cluster memory capacity by node over time.
TS: Internal Table Wise Capacity WS::
  Describes memory capacity by node, table name, shard count, and CSV replication over time.
TS: Metrics::
  Contains metrics by cluster and host over time.
TS: Search::
  Contains data related to the number of searches (queries) run in the system. This contains information such as uptime, host, and timestamps.
TS: Service Resources::
  Contains data related to cluster nodes including page faults, memory usage, memory failures, and more.
TS: Table Info::
  Describes the named tables by timestamp, row count, row shards, and row size.
TS: Table Row Counts::
  Describes the named tables by timestamp and row count.
TS: Table Row Counts and Shards::
  Describes the named tables by timestamp, row count, row shards, and row size.
TS: Table Row Size::
  Describes the named tables by timestamp and row size.
TS: Table Shards::
  Describes the named tables by timestamp and shard count.
TS: Embrace Historical Row Fact::
Contains data related to row counts for external tables, or tables connected to through Embrace.
TS: Embrace Table Dimension::
Contains summary data for each external or Embrace table.
TS: Embrace Stats Worksheet::
Contains Embrace table- and query-level stats.
