= Introduction to monitoring
:last_updated: 11/05/2021
:linkattrs:
:experimental:
:page-layout: default-cloud
:page-aliases: /admin/system-monitor/introduction.adoc
:description: Learn how to monitor your system.
:jira: SCAL-264258


ThoughtSpot Cloud provides several out-of-the-box system monitoring Models, views, and Liveboards.
From these Models and views, you can create your own custom visualizations and Liveboards.
This page introduces these features and directs you towards more detailed information.

== Admin Console

From the Admin Console, you can view the xref:user-adoption.adoc[User Adoption] system Liveboard, and view upcoming xref:scheduled-maintenance.adoc[application maintenance].

Navigate to the Admin Console by selecting *Admin* from the top navigation bar.

== System Models, views, and Liveboards

Administrators can view existing system Liveboards, or create their own, custom boards that reflect system data in ways that are meaningful to specific departments or groups.
For more information, see the following documentation:

* xref:system-model.adoc[System Models and views]
* xref:system-liveboards.adoc[System Liveboards]
