= System worksheets and views
:last_updated: 11/05/2021
:linkattrs:
:experimental:
:page-layout: default-cloud
:page-aliases: /admin/system-monitor/worksheets.adoc
:description: Learn about the system worksheets and views that ThoughtSpot provides.

include::partial$liveboards-announcement.adoc[]

Most of the monitoring information in ThoughtSpot's system Liveboards comes from system worksheets and views that administrators can view, but not modify.
The underlying tables are protected system tables that you cannot access directly.
However, administrators can create new, custom monitoring reports from the worksheets and views.

== List the system worksheets and views

To list the system worksheets and views:

. Go to the *Data* tab.
. Choose *All* and *All types*.
. Enter `System User` in the search field.

== Description of system worksheets and views

Credits Purchased::
Contains data on the number of credits for xref:consumption-pricing.adoc[consumption-based pricing] your cluster has, and their expiration date. Used for the xref:consumption-pricing.adoc#credit-usage-pinboard[Credit Usage Liveboard].
Sample Retail - Apparel:: Contains sample retail data for xref:search-assist.adoc[Search Assist].
Credit Usage:: Tracks the credits for xref:consumption-pricing.adoc[consumption-based pricing] your cluster has consumed. Used for the xref:consumption-pricing.adoc#credit-usage-pinboard[Credit Usage Liveboard].
Discover Monitoring Data:: Contains data on how users are searching for existing answers and Liveboards. Contains information on what users are searching for, where users are successful and where they are not. Used for the xref:thoughtspot-one-query-intelligence-liveboard.adoc#[How Users are Searching Answers Liveboard].
Product Usage:: Contains usage data for the product. Specifies what existing Worksheets, tables, and Views users search on and create objects from, and what those objects are. Specifies what actions users complete in the product. You can also use this Worksheet to view the underlying data sources for any objects, and any object's dependents.
MetricsMonitoring:: Contains data on how users are searching for existing answers and Liveboards. Contains information on what users are searching for, where users are successful and where they are not, based on click count and position. Used for the xref:thoughtspot-one-query-intelligence-liveboard.adoc[How Users are Searching Answers Liveboard].
TS: BI Server:: Contains data related to the systems associated with underlying the
         ThoughtSpot BI server.  This includes database latency, browser clients, size
         of responses, and more.
TS: External Table Current Row Count::
Contains data related to the row count for external tables, or tables loaded through Connections.
TS: Rows of un-cached tables for each connection:: Contains data related to the sum of rows count for each un-cached table in a connection.
TS: External Table Stats WS::
Contains data related to the stats collected for external tables, or tables loaded through Connections.
TS: External Table Info:: Contains data related to external tables, or tables loaded through Connections.
TS: Daily Row Count External Table::
Contains Connections data, stored on a daily basis: the number of rows in your external database, and whether each external table is cached or not.
