= TML for tables
:page-last_updated: Jun 21, 2026
:author: Teresa Killmond
:linkattrs:
:experimental:

:page-aliases: /admin/scriptability/tsl-table.adoc, /admin/scriptability/tml-table.adoc, /admin/ts-cloud/tsl-table.adoc
:description: Use TML to modify tables in a flat-file format. Then, migrate the table to a different cluster, or restore it to the same cluster.
:object: tables
:jira: SCAL-158490, SCAL-186188, SCAL-231618, SCAL-220584, SCAL-264358, SCAL-276978

include::partial$tml-intro.adoc[]

[#syntax-tables]
include::partial$tml-syntax-table.adoc[]

[#table-parameters]
== TML parameters for {object}
These parameters and their definitions are specific to {object}; this list doesn't contain every parameter in every TML file. Similarly, the parameter definitions may vary from object to object, since the parameters may have different roles in different objects.

[width="100%",grid="none",options="header"]
|===
| a - e | f - j | n - t
a| <<aggregation,aggregation>>

<<calendar,calendar>>

<<column,column>>

<<column_type,column_type>>

<<columns,columns>>

<<connection,connection>>

<<currency_type,currency_type>>

<<custom_file_guid,custom_file_guid>>

<<data_type,data_type>>

<<db,db>>

<<db_column_name,db_column_name>>

<<db_column_properties,db_column_properties>>

<<db_table,db_table>>

<<default_date_bucket,default_date_bucket>>

<<default_value,default_value>>

<<description,description>>

<<destination,destination>>

<<expr,expr>>

a| <<format_pattern,format_pattern>>

<<fqn,fqn>>

<<geo_config,geo_config>>

<<geometryType,geometryType>>

<<guid,guid>>

<<id,id>>

<<index_priority,index_priority>>

<<index_type,index_type>>

<<is_additive,is_additive>>

<<is_attribution_dimension,is_attribution_dimension>>

<<is_hidden,is_hidden>>

<<is_one_to_one,is_one_to_one>>

<<is_spotter_enabled,is_spotter_enabled>>

<<join,join>>

<<join_path,join_path>>

<<joins,joins>>

<<joins_with,joins_with>>

a| <<name,name>>

<<on,on>>

<<parameters,parameters>>

<<properties,properties>>

<<rls_rules,rls_rules>>

<<rule,rule>>

<<rules,rules>>

<<sap_parameter_name,sap_parameter_name>>

<<schema,schema>>

<<source,source>>

<<spotiq_preference,spotiq_preference>>

<<spotter_config,spotter_config>>

<<synonyms,synonyms>>

<<table,table>>

<<table_paths,table_paths>>

<<tables,tables>>

<<type,type>>

<<accessible_groups,accessible_groups>>

<<column_security_rules,column_security_rules>>

|===

[#aggregation]
aggregation::
The default aggregation of the view column.
+
Aggregation options depend on the data type.
+
Possible values are `SUM`, `COUNT`, `AVERAGE`, `MAX`, `MIN`, `COUNT_DISTINCT`, `NONE`, `STD_DEVIATION`, and `VARIANCE`
+
Default: `SUM`.

[#accessible_groups]
accessible_groups::
Specifies the user groups that have access to a restricted column.
+
Contains a `group_name` list of one or more group names.
+
If `accessible_groups` is omitted for a column entry, the column is inaccessible to all user groups.

[#calendar]
calendar::
Specifies the calendar used by a date column.
+
Can be the Gregorian calendar (`default`), a fiscal calendar, or any custom calendar.
+
See xref:connections-cust-cal.adoc[Set up a custom calendar].

[#column]
column::
The id of the column(s) being filtered on.

[#column_security_rules]
column_security_rules::
Top-level container for the column security rules defined on a table.
+
Exported as a separate TML file when you export a table.
+
Contains a `table` reference and a `rules` list. Only columns that have security rules defined, or that are marked as protected, appear in the file.
+
See <<csr-tml,Column security rules TML>>.

[#column_type]
column_type::
The type of data the column represents.
+
Possible values: `MEASURE` or `ATTRIBUTE`

[#columns]
columns::
The columns in the table.

[#connection]
connection::
A way to identify the external data warehouse connection that the table or column resides in. To add tables or columns to an external connection, you must specify this parameter.

[#currency_type]
currency_type::
The source of the currency type.
+
One of:
+
`is_browser : true`;; infer the currency data from the locale of your browser
`column : <column_name>`;; extracts the currency information from a specified column
`iso_code : <valid_ISO_code>`;; applies currency based on the ISO code;
+
See https://www.iso.org/iso-4217-currency-codes.html[ISO 4217 Currency Codes^] and xref:data-modeling-patterns.adoc#set-currency-type[Set currency type] for more information.

[#custom_file_guid]
custom_file_guid::
The GUID for a custom map uploaded by an administrator.

[#data_type]
data_type::
The data type of the column.

[#db]
db::
The database that a table resides in.
Note that this is not the same as the data warehouse (Falcon, Amazon Redshift, or Snowflake, for example).

[#db_column_name]
db_column_name::
The name of the column in the database.
Note that this database is not the same as the data warehouse (Amazon Redshift, or Snowflake, for example).

[#db_column_properties]
db_column_properties::
The properties of the column in the database. Note that this database is not the same as the data warehouse (Amazon Redshift or Snowflake, for example).

[#db_table]
db_table::
The name of the table in the database.
Note that this database is not the same as the data warehouse (Falcon, Amazon Redshift, or Snowflake, for example).

[#default_date_bucket]
default_date_bucket:: The default date bucket for the column, options include daily, weekly, monthly, quarterly, yearly, hourly, and auto. Hourly is only available for datetime columns. When defined for a column, date bucket will always be included in a search containing that column. For example, if defined as "daily" for Revenue, searching for "revenue order date" will be interpreted as "revenue order date daily".

[#default_value]
default_value::
The default value of the parameter.
+
NOTE: Only applicable for tables imported from SAP Hana.

[#description]
description::
The text that describes an object: a `table`, a `join`, and so on.

[#destination]
destination::
The name of the destination table or view for a join.

[#expr]
expr::
The definition of the row-level security (RLS) rule. The syntax for variables in TML should be the same as the syntax of the variables in the rule on the table.

[#format_pattern]
format_pattern::
The format pattern string that controls the display of a number, date, or currency column.
+
See xref:data-modeling-patterns.adoc[Set number, date, and currency formats].

[#fqn]
fqn::
The table or connection's GUID.
You can find this string of letters and numbers at the end of the URL for that table or connection.
+
For example, in `\https://<company>.thoughtspot.com/#/data/tables/34226aaa-4bcf-4d6b-9045-24cb1e9437cb`, the GUID is `34226aaa-4bcf-4d6b-9045-24cb1e9437cb`.
+
Use this optional parameter to reduce ambiguity and identify a specific table, if you have multiple tables with the same name. When exporting a TML file, you have the option to *Export FQNs of referenced objects*, which ensures that the TML files you export contain FQNs for the underlying tables and connections. If you do not add the `fqn` parameter, and the connection or table you reference does not have a unique name, the file import fails.

[#geo_config]
geo_config::
Specifies the geographic information of a column. See xref:data-modeling-geo-data.adoc[Add a geographical data setting].
+
One of:
+
`latitude : true`;; for columns that specify the latitude
`longitude : true`;; for columns that specify the longitude
`country : true`;; for columns that specify the country
`region_name`;; for specifying a region in a country
+
Uses two paired parameters:

- `country: __<country_name>__`
- `region_name: __<region_name_in_UI>__`; can be State, Postal Code, District, and so on.

`custom_file_guid: <custom map GUID>`;; for columns that use a custom map. Must be followed by `geometryType`.
`geometryType: <custom_map_geometry_type>`;; for columns that use a custom map. Must be preceded by `custom_file_guid`. Accepts the following values: `POINT`, `LINE_STRING`, `LINEAR_RING`, `POLYGON`, `MULTI_POINT`, `MULTI_LINE_STRING`, `MULTI_POLYGON`, `GEOMETRY_COLLECTION`, `CIRCLE`

[#geometryType]
geometryType::
Specifies the geometry type of the *TopoJSON* file. Required for geographical configuration of Model or table columns that use a custom map. Accepts the following values: `POINT`, `LINE_STRING`, `LINEAR_RING`, `POLYGON`, `MULTI_POINT`, `MULTI_LINE_STRING`, `MULTI_POLYGON`, `GEOMETRY_COLLECTION`, `CIRCLE`

[#guid]
guid::
The GUID for the table. You can find this string of letters and numbers at the end of the URL for an object.

[#id]
id::
Specifies the id of an object, such as `table_paths`, `name`.

[#index_priority]
index_priority::
A value (1-10) that determines where to rank a column's name and values in the search suggestions
+
ThoughtSpot prioritizes columns with higher values.
+
See xref:data-modeling-index.adoc#column-suggestion-priority[Change a column's suggestion priority].

[#index_type]
index_type::
The indexing option of the table column.
+
Possible values: `DONT_INDEX`, `DEFAULT` (see xref:data-modeling-index.adoc#default-indexing[Understand the default indexing behavior]), `PREFIX_ONLY`, `PREFIX_AND_SUBSTRING`, and `PREFIX_AND_WORD_SUBSTRING`
+
Default: `DEFAULT`
+
See xref:data-modeling-index.adoc#override-system-default-column[Index Type Values].

[#is_additive]
is_additive::
Controls extended aggregate options for attribute columns.
+
For attribute columns that have a numeric data type (`FLOAT`, `DOUBLE`, or `INTEGER`) or a date data type (`DATE`, `DATETIME`, `TIMESTAMP`, or `TIME`)
+
Possible values: `true` or `false`.
+
Default: `true`.
+
See xref:data-modeling-aggreg-additive.adoc#make-attribute-additive[Making an ATTRIBUTE column ADDITIVE].

[#is_attribution_dimension]
is_attribution_dimension::
Controls if the column is an attribution dimension.
+
Used in managing chasm traps.
+
Possible values: `true` by default, `false` to designate a column as not producing meaningful attributions across a chasm trap
+
Default: `true`
+
See xref:data-modeling-attributable-dimension.adoc[Change the attribution dimension].

[#is_hidden]
is_hidden::
The visibility of the column.
+
Possible values: `true` to hide the column, `false` not to hide the column +
Default: `false`
+
See xref:data-modeling-visibility.adoc[].

[#is_one_to_one]
is_one_to_one::
Specifies the cardinality of the join. This is an optional parameter.
+
Possible values: `true`, `false`
+
Default: `false`

[#is_spotter_enabled]
is_spotter_enabled:: Defines whether Spotter is enabled on the table.  If Spotter is not enabled in your instance, this property is titled `is_sage_enabled`.

[#join]
join::
Specific join, used in defining higher-level objects, such as table paths.
+
Defined as `name` within `joins` definition

[#join_path]
join_path::
Specification of a composite join as a list of distinct `join` attributes.
+
These `join` attributes list relevant joins, previously defined in the `joins`, by name.
+
Default: `{}`

[#joins]
joins::
Contains a list of joins between the tables and views.
+
If you edit the joins in the Model or View TML file, you are only editing the joins for that specific Model or view. You are not editing the joins at the table level. To modify table-level joins, you must edit the source table's TML file.
+
Each join is identified by `name`, and the additional attributes of `source`, `destination`, `type`, and `is_one_to_one.`

[#joins_with]
joins_with::
Contains a list of external joins for which this table is the source. Each join is identified by `name` and optional `description`, and the additional attributes of `destination`, `type`, `on`, and `is_one_to_one`.

[#name]
name::
The name of an object.
Applies to `table`, `joins`, `connection`, and so on.

[#on]
on::
The join expression: the relationship definition, or the keys that your tables are joined on. For example, `[sale::Sale_Last Name] = [employee::Employee_Last Name] AND [sale::Sale_First Name] = [employee::Employee_First Name]`.
+
To alter a relationship definition, edit this parameter.

[#parameters]
parameters::
The parameter that corresponds to the input parameter in a Connection. Currently applicable only to tables imported from SAP Hana. For this field, you must fill in the name, data type, default value, and sap parameter name.

[#properties]
properties::
The list of properties of a table column.
+
Each column can have the following properties, depending on its definition: `column_type`, `aggregation`, `index_type`, `is_hidden`, `index_priority`, `synonyms`, `is_attribution_dimension`, `is_additive`, `calendar`, `format_pattern`, `currency_type`, `geo_config`, and `spotiq_preference`.

[#rls_rules]
rls_rules::
A container for the full definition of xref:security-rls-concept.adoc[row-level security] rules for the table.

[#rule]
rule::
A conditional formatting rule.

[#rules]
rules::
A container for the names and expressions of xref:security-rls-concept.adoc[row-level security] rules for the table.

[#spotter_config]
spotter_config:: A container for the is_spotter_enabled property. If Spotter is not enabled for your instance, this property is titled `sage_config`.

[#sap_parameter_name]
sap_parameter_name::
The name of the parameter from the SAP Hana calculated view.

[#schema]
schema::
The schema that the table is a part of.

[#source]
source::
Name of the source table or view for a join.

[#spotiq_preference]
spotiq_preference::
Specifies whether to include a column in SpotIQ analysis.
Specify `EXCLUDE`, or this property defaults to include the column in SpotIQ Analysis.
+
Refer to xref:spotiq-data-model-preferences.adoc[Set columns to exclude from SpotIQ analyses].

[#synonyms]
synonyms::
Alternate names for the column, used in search.
+
See xref:data-modeling-visibility.adoc[].

[#table]
table::
Top-level container for all object definitions within the table.

[#table_paths]
table_paths::
The list of table paths.
+
Each table path is identified by the `id`, and additional attributes of `table` and `join_path`.

[#tables]
tables::
List of tables used by the RLS rule.
+
Each table is identified by `name`.

[#type]
type::
The connection type.
+
Possible values: `Snowflake`, `Google BigQuery`, `Microsoft Azure`, or `Amazon Redshift`.

[#limitations]
== Limitations of working with TML files

There are certain limitations to the changes you can apply by editing {object} through TML.

* Columns can either have a new name, or a new expression.
You can't change both, unless migrating or updating the Model two times.
* It isn't possible to reverse the join direction in the TML script.
* You can only change logical tables using TML files.
You can't change the physical version of the table that exists in a database.
When you change the `column_name`, for example, the name changes in the application, but not in the physical table in the database.
* Joins only appear in the table TML file of the source table in a join, or the table on the Many side of a Many-to-One join.
You can only add and edit table joins from the TML file of the table on the Many side of the join.
You can't view or modify table-level joins from the destination table's TML file.
* You can't remove tables from a connection.
You can only add them.
* You can only delete table columns that have no dependents. If the table column has any dependents, ThoughtSpot returns an error when you try to import or validate the TML file. To delete a table column, you must first delete the dependents.
* When deleting columns, you only delete ThoughtSpot's record of the column. You don't delete the column in your external database.
* If there is an error in any row-level security (RLS) rule when importing a table, all RLS rules for the table are removed. ThoughtSpot warns you about this on import, and highlights the rule that is in an error state, so you can fix it or remove it.

// SOURCE: https://docs.google.com/document/d/12pdbKWDFUVpN94uW0IDgdIMMqSv7WKVIAqwY2JYT2Fo
[#csr-tml]
== Column security rules TML

Column security rules are exported as a separate TML file when you export a table. The file uses the `column_security_rules` key and contains only the columns that have security rules defined or that are marked as protected.

For information about setting up column security rules in the ThoughtSpot UI, see xref:security-data-object.adoc#csr[Column security rules].

=== TML syntax for column security rules

[source,yaml]
----
column_security_rules:
  table:
    name: <table_name>
    fqn: <table_guid>
  rules:
    - column_name: <column_name>                 # <1>
    - column_name: <column_name>                 # <2>
      accessible_groups:
        group_name:
          - <group_name>
          - <group_name>
----
<1> A column with no `accessible_groups` entry is inaccessible to all user groups.
<2> A column with an `accessible_groups` entry is accessible only to the listed groups.

==== Example

[source,yaml]
----
column_security_rules:
  table:
    name: PART
    fqn: d8f93c7b-8a12-4d1f-bfdc-1a2e3f4b5678
  rules:
    - column_name: P_NAME
    - column_name: salary
      accessible_groups:
        group_name:
          - HR Team
          - Finance
    - column_name: SSN
      accessible_groups:
        group_name:
          - HR Team
----

In this example:

* `P_NAME` is inaccessible to all user groups.
* `salary` is accessible to the *HR Team* and *Finance* groups only.
* `SSN` is accessible to the *HR Team* group only.

=== Export column security rules TML

Column security rules TML is exported automatically alongside the table TML when you export a table. To export, you must have:

* Modify access to the table and all its columns.
* Access to all user groups that are linked to column security rules on the table.

// TODO: verify with engineering — confirm whether CSR TML is included in the same ZIP as the table TML export, or requires a separate export action.

=== Import column security rules TML

To import column security rules TML, you must have:

* Modify permission on the table.
* Access to all user groups specified in the TML file.
* Access to all user groups already associated with column security rules on the table.

[NOTE]
====
If a user group specified in the TML file does not exist in ThoughtSpot, the import completes with a warning. The missing group is not applied.
====

=== Delete a column security rule

To delete a column security rule using TML, remove the relevant column entry from the `rules` list in the CSR TML file and re-import the file. This follows the same deletion pattern as other TML-based object deletions, such as deleting a column from a table TML.
