= TML for Spotter feedback
:last_updated: 4/11/25
:author: Naomi
:page-layout: default-cloud
:linkattrs:
:experimental:
:description: Use TML to modify feedback in a flat-file format. Then, migrate the feedback to a different Worksheet or Model.
:jira: SCAL-226681
:object: feedback

include::partial$tml-intro.adoc[]

[#syntax-feedback]
include::partial$tml-syntax-feedback.adoc[]




[#feedback-parameters]
== TML parameters for {object}

These parameters and their definitions are specific to {object}; this list doesn't contain every parameter in every TML file. Similarly, the parameter definitions may vary from object to object, since the parameters may have different roles in different objects.

[width="100%",grid="none",options="header"]
|===
| a - i |  n - y

a|
<<access,access>>
<<axis_config,axis_config>>
<<chart_type,chart_type>>
<<display_mode,display_mode>>
<<expression>>
<<feedback,feedback>>
<<feedback_phrase,feedback_phrase>>
<<formula_info,formula_info>>
<<guid,guid>>
<<id,id>>


a|
<<name,name>>
<<nls_feedback,nls_feedback>>
<<parent_question,parent_question>>
<<rating,rating>>
<<search_tokens,search_tokens>>
<<type,type>>
<<x,x>>
<<y,"y">>
|===

[#access]
access:: Defines the level of access of the feedback entry, either `GLOBAL` or `USER`.


[#axis_config]
axis_config:: Contains information about which columns map to which axes. Generated by the system when the feedback was originally created. Do not modify.

[#chart_type]
chart_type:: Generated by the system when the feedback was originally created. Do not modify.

[#display_mode]
display_mode:: Generated by the system when the feedback was originally created. Do not modify.

[#expression]
expression:: A string identifying the formula used in a feedback entry.

[#feedback]
feedback:: Marks the section containing the properties of the feedback. Contains the list of feedback entries created on the model.

[#feedback_phrase]
feedback_phrase:: The string denotes the natural language part of the feedback. For `REFERENCE_QUESTION`,  this is the same as 'parent_phrase'. For `BUSINESS_TERM`, this is the fragment of the 'parent_phrase' that was mapped to the search tokens.

[#formula_info]
formula_info:: A container for the name and expression of a formula used in feedback.

[#guid]
guid:: The GUID of the Worksheet or Model the feedback was created on.

[#id]
id:: Uniquely identifies each individual feedback entry. Note that this ID is temporary for this particular file and is only used to help report errors and warnings during file upload.

[#name]
name:: The name of the formula used in the feedback entry.

[#nls_feedback]
nls_feedback:: Parent container for the feedback entries in the TML file.

[#parent_question]
parent_question:: Indicates the parent query from which the `feedback_phrase` is derived, in the case of `BUSINESS_TERM` feedback.

[#rating]
rating:: Indicates whether the user Upvoted or Downvoted an AI-generated response.

[#search_tokens]
search_tokens:: Indicates the tokens for the feedback in TML form.


[#type]
type:: Identifies the type of feedback, whether `BUSINESS_TERM` or `REFERENCE_QUESTION`.

[#x]
x:: Denotes which column or search token is mapped on the x-axis.

[#y]
"y":: Denotes which column or search token is mapped on the y-axis.

'''
> **Related information**
>
> * xref:migrate-feedback.adoc[]