= TML for Sets
:last_updated: 8/7/2024
:author: Mary Scrim
:linkattrs:
:experimental:
:page-layout: default-cloud-beta
:description: Use TML to modify sets in a flat-file format. Then, migrate the sets to a different cluster, or restore it to the same cluster.
:object: Sets
:jira: SCAL-230555

include::partial$tml-intro.adoc[]

NOTE: TML export of sets is only available through the export of the parent object. If a set is used in an answer then exporting the answer with associated objects will export the set definition. This is a separate file.

A single set file or multiple set TML files can be imported using the TML import utility located in the *Data* tab.

Set owners and ThoughtSpot administrators can edit a set's TML definition in the *Search Data* panel.

NOTE: A set's owner property can only be edited by the ThoughtSpot administrator. Ownership can be changed in the TML using the optional *owner* TML property.


[#syntax-sets]
include::partial$tml-syntax-sets.adoc[]


[#set-parameters]
== TML parameters for {object}
These parameters and their definitions are specific to {object}; this list doesn't contain every parameter in every TML file. Similarly, the parameter definitions may vary from object to object, since the parameters may have different roles in different objects.

[width="100%",grid="none",options="header"]
|===
| a - d | e - o | p - v
a| <<aggregation,aggregation>>

<<anchor_column_id,anchor_column_id>>

<<answer,answer>>

<<answer_columns,answer_columns>>

<<bin_size,bin_size>>

<<bins,bins>>

//<<chart,chart>>

//<<chart_columns,chart_columns>>

<<client_state,client_state>>


<<cohort,cohort>>

<<cohort_grouping_type,cohort_grouping_type>>

<<cohort_type,cohort_type>>

<<column_id,column_id>>

<<column_type,column_type>>

<<combine_non_group_values,combine_non_group_values>>

<<combine_type,combine_type>>

<<conditions,conditions>>

<<config,config>>

<<custom_name,custom_name>>

<<data_type,data_type>>

<<description,description>>

<<display_mode,display_mode>>

a| <<expr,expr>>

<<formulas,formulas>>

<<fqn,fqn>>

<<group_excluded_query_values,group_excluded_query_values>>

<<groups,groups>>

<<guid,guid>>

<<headline_aggregation,headline_aggregation>>

<<hide_excluded_query_values,hide_excluded_query_values>>

<<id,id>>

//<<key,key>>

//<<locked,locked>>

<<maximum_value,maximum_value>>

<<minimum_value,minimum_value>>

<<name,name>>

<<null_output_value,null_output_value>>

<<operator,operator>>

<<ordered_column_ids,ordered_column_ids>>

//<<override_value,override_value>>

<<owner,owner>>

a|

//<<parameter_overrides,parameter_overrides>>

//<<parameter_values,parameter_values>>


<<return_column_id,return_column_id>>

<<search_query,search_query>>

//<<show_headline,show_headline>>

<<table,table>>

<<table_columns,table_columns>>

<<tables,tables>>

//<<type,type>>

//<<value,value>>

<<worksheet,worksheet>>

|===

[#aggregation]
aggregation::
The default aggregation of the output for a formula.
+
Aggregation options depend on the data type.
+
Possible values are `SUM`, `COUNT`, `AVERAGE`, `MAX`, `MIN`, `COUNT_DISTINCT`, `NONE`, `STD_DEVIATION`, and `VARIANCE`
+
Default: `SUM`.

[#anchor_column_id]
anchor_column_id::
Defines the identifier of the column that the set is associated with.

[#answer]
answer (query sets)::
Top-level container for all object definitions within an answer.

[#answer_columns]
answer_columns (query sets)::
A list of columns generated by the search query.

[#bin_size]
bin_size:: Size of bin.

[#bins]
bins:: Container for group configuration for bin-based column sets.

////
[#axis_configs]
axis_configs::
Specifies the columns for each axis on a chart.
+
If you are displaying a column chart with a line chart overlaying it, for example, you would need to specify more than one `axis_config`.
////
////
[#chart]
chart::
Contains configuration for the Answer, if it displays in chart format.
////
////
[#chart_columns]
chart_columns::
A list of columns in the chart.
////

[#client_state]
client_state (query sets)::
A JSON string with more advanced chart and table configuration.

[#cohort]
cohort::
A top-level container for all object definitions within a cohort.

[#cohort_grouping_type]
cohort_grouping_type::
Describes the type of grouping contained in a set.

[#cohort_type]
cohort_type::
Describes the type of set, either column or query set.

[#column_id]
column_id (query sets)::
Describes how the column appears in the query.
For example, if you sorted by `Quarter` in your search, from the `Commit Date` column, the `column_id` of the column is `Quarter(Commit Date)`.

[#column_type]
column_type (query sets)::
The type of data the output of the formula represents.
+
Possible values: `MEASURE` or `ATTRIBUTE`. The default depends on the <<data_type,data_type>>.
+
If the data type is `INT` or `BIGINT`, the formula output's `column_type` defaults to `Measure`.
+
If the data type is `BOOL`, `VARCHAR`, `DOUBLE`, `FLOAT`, `DATE`, `DATETIME`, or `TIME`, the formula output's `column_type` defaults to `Attribute`.

[#combine_non_group_values]
combine_non_group_values:: When set to true, combines all values which do not belong to any group.

[#combine_type]
combine_type:: Defines how multiple group conditions should be combined for group-based column sets. Options are ALL or ANY.


[#conditions]
conditions:: Conditions for each group for group-based column sets.

[#config]
config::
Container for all cohort configurations.

[#custom_name]
custom_name (query sets)::
Optional display name for a column.

[#data_type]
data_type (query sets)::
The data type of the formula output.
If the data type is `INT32` or `INT64`, the formula output's `column_type` defaults to `Measure`.
If the data type is `BOOL`, `VARCHAR`, `DOUBLE`, `FLOAT`, `DATE`, `DATETIME`, or `TIME`, the formula output's `column_type` defaults to `Attribute`.

[#description]
description::
The text that describes an Answer.

[#display_mode]
display_mode (query sets)::
Determines whether the answer displays as a chart or a table.
Specify either `CHART_MODE` or `TABLE_MODE`.

[#expr]
expr (query sets)::
The definition of the formula. This should be the same as the formula expression in the formula editor.

[#formulas]
formulas (query sets)::
The list of formulas in the Answer.
+
Each formula is identified by `name`, the `expr` (expression), and an optional `id` attribute.

[#fqn]
fqn::
The source table's GUID.
You can find this string of letters and numbers at the end of the URL for that table or connection.
+
For example, in `\https://<company>.thoughtspot.com/#/data/tables/34226aaa-4bcf-4d6b-9045-24cb1e9437cb`, the GUID is `34226aaa-4bcf-4d6b-9045-24cb1e9437cb`.
+
Use this optional parameter to reduce ambiguity and identify a specific table, if you have multiple tables with the same name. When exporting a TML file, you have the option to *Export FQNs of referenced objects*, which ensures that the TML files you export contain FQNs for the underlying tables and connections. If you do not add the `fqn` parameter, and the connection or table you reference does not have a unique name, the file import fails.

[#group_excluded_query_values]
group_excluded_query_values:: Name for combined group values which are not part of Query Set query.

[#groups]
groups:: Container for group configuration for group-based column sets.

[#guid]
guid::
The GUID for the Answer. You can find this string of letters and numbers at the end of the URL for an object.

[#headline_aggregation]
headline_aggregation (query sets)::
Specifies the type of aggregation the headline uses.
+
Can be `COUNT`, `COUNT_DISTINCT`, `SUM`, `MIN`, `MAX`, `AVERAGE`, or `TABLE_AGGR`.

[#hide_excluded_query_values]
hide_excluded_query_values:: Set to true to hide values which are not part of the Query Set query.

[#id]
id (query sets)::
Specifies the id of an object, such as `table` or `formula`.
+
For `answer_columns`, `id` refers to how the column appears in the query.
For example, if you sorted by `Quarter` in your search, from the `Commit Date` column, the `id` of the column is `Quarter(Commit Date)`. Refer to https://developers.thoughtspot.com/docs/?pageid=search-data-api[Components of a Search Query^] to understand syntax.
+
For formulas within answers, `id` refers to the display name of the formula. If you do not give your formula a name, it appears as 'Untitled Formula'.
+
//In the <<parameter_overrides,parameter_overrides>> section, `id` refers to the Parameter's GUID.

////
[#key]
key::
Name of the xref:parameters-create.adoc[Parameter] referenced in a formula in an Answer.
+
In the <<parameter_overrides,parameter_overrides>> section, `key` refers to the Parameter's GUID.
////

////
[#locked]
locked::
The 'automatically select my chart' option in the UI.
If set to `true`, the chart type does not change, even when you change the search query.
////

[#maximum_value]
maximum_value:: Maximum value for bin.

[#minimum_value]
minimum_value:: Minimum value for bin.

[#name]
name::
The name of an object.
Applies to `formula`, `answer`, `liveboard`, `table`, and so on.
+
For `answer_columns`, `name` refers to how the column appears in the query.
For example, if you sorted by `Quarter` in your search, from the `Commit Date` column, the `name` of the column is `Quarter(Commit Date)`.
Refer to https://developers.thoughtspot.com/docs/?pageid=search-data-api[Components of a Search Query^] to understand syntax.
+
In the `parameter_overrides` section for an Answer or Liveboard, `name` refers to the xref:parameters-create.adoc[Parameter] name.

[#null_output_value]
null_output_value:: Name for combined group values which are not part of any group in group-based sets.

[#operator]
operator:: Operator for group conditions for group-based column sets.

[#ordered_column_ids]
ordered_column_ids (query sets)::
A list of columns, in the order they appear in the table.

////
[#override_value]
override_value::
The value a Parameter is set to in an Answer, if different from the default value.
////

[#owner]
owner::
The owner of a column or query set.


////
[#parameter_overrides]
parameter_overrides::

Contains information on the value a Parameter is set to in an Answer, if different from its default value. If there is no `override_value` line, the Parameter is set to the default value.
////
////
[#parameter_values]
parameter_values::
Container for the xref:parameters-create.adoc[Parameters] in an Answer.
////
////
[#properties]
properties::
The list of the properties of the output for a formula within an Answer.
+
Each formula's output can have the following properties, depending on its definition: `column_type` and `aggregation`.
////

[#return_column_id]
return_column_id:: Return column forccolumn-based query sets.

[#search_query]
search_query (query sets)::
A string that represents the fully disambiguated search query.
Refer to https://developers.thoughtspot.com/docs/?pageid=search-data-api[Components of a Search Query^] to understand syntax.

////
[#show_headline]
show_headline::
Determines whether to show the headline for this column.
`true` shows the headline.
////

[#table]
table (query sets)::
Contains configuration for the answer, if it displays in table format.

[#table_columns]
table_columns (query sets)::
The columns in an Answer that is being displayed in table format.

[#tables]
tables (query sets)::
List of tables used by the Answer. Each table is identified by `name`.

////
[#type]
type::
Within the `chart` section of an Answer TML file, this is the chart type.
+
Possible values: `COLUMN`, `BAR`, `LINE`, `PIE`, `SCATTER`, `BUBBLE`, `STACKED_COLUMN`, `AREA`, `PARETO`, `COLUMN`, `GEO_AREA`, `GEO_BUBBLE`, `GEO_HEATMAP`, `GEO_EARTH_BAR`, `GEO_EARTH_AREA`, `GEO_EARTH_GRAPH`, `GEO_EARTH_BUBBLE`, `GEO_EARTH_HEATMAP`, `WATERFALL`, `TREEMAP`, `HEATMAP`, `STACKED_AREA`, `LINE_COLUMN`, `FUNNEL`, `LINE_STACKED_COLUMN`, `PIVOT_TABLE`, `SANKEY`, `GRID_TABLE`, `SPIDER_WEB`, `WHISKER_SCATTER`, `STACKED_BAR`, or `CANDLESTICK`.
////
////
[#value]
value::
The configured value of the Parameter referenced in a formula in the last saved state of the Answer.
////

[#worksheet]
worksheet:: Container for worksheet id and name to which the cohort belongs.

[#limitations]
== Limitations of working with TML files

There are certain limitations to the changes you can apply by editing {object} through TML.

* Formulas and columns can either have a new name, or a new expression.
You can't change both, unless migrating or updating the Worksheet two times.
* You can't create or export TML files for R- or Python-powered visualizations.
* You can't import manually compressed .zip files.
You can only import .zip files that you exported from ThoughtSpot: a custom set of TML files, an object and its associated data sources, or multiple objects of the same type that you exported from the object list page.
* You can't modify joins at the table level from the Worksheet, view, or Answer TML file.
You can only override the joins for that specific Worksheet, view, or Answer.
To modify table-level joins, you must edit the source table's TML file.
* Changing the filter order for Answers in the UI doesn't change the filter order in the TML file.