= ThoughtSpot Modeling Language
:last_updated: 11/05/2021
:linkattrs:
:experimental:
:page-layout: default-cloud
:page-aliases: /admin/ts-cloud/tml.adoc, /admin/ts-cloud/tsl.adoc, /admin/scriptability/tml.adoc
:description: Use TML to modify a ThoughtSpot object in a flat-file format. Then, migrate the object to a different cluster, or restore it to the same cluster.
:jira: SCAL-188027, SCAL-240697

Use TML to modify a ThoughtSpot object in a flat-file format. Then, migrate the object to a different cluster, or restore it to the same cluster.

To work with TML files for Worksheets, views, SQL views, tables, Answers, Liveboards, and Monitor alerts in ThoughtSpot, you can download these objects to a flat file in `.TML` format, modify it, and subsequently upload this file either to the same cluster, or to a different cluster.
To learn how to export, change, and update Worksheets, views, tables, Answers, and Liveboards, see xref:scriptability.adoc[Import and export TML files]. To learn how to migrate multiple TML files at a time, see xref:tml-import-export-multiple.adoc[].

In this section, you learn the syntax of the TML files for each object.
You also learn how to add and modify joins for Worksheets, views, SQL views, and tables.

See the following articles for the full syntax of each type of TML file:

* xref:tml-answers.adoc[TML for Answers]
* xref:tml-connections.adoc[TML for Connections]
* xref:tml-feedback.adoc[TML for feedback]
* xref:tml-joins.adoc[TML for joins]
* xref:tml-liveboards.adoc[TML for Liveboards]
* xref:tml-models.adoc[TML for Models]
* xref:tml-alerts.adoc[TML for Monitor alerts]
* xref:tml-sets.adoc[TML for Sets]
* xref:tml-sql-views.adoc[TML for SQL views]
* xref:tml-tables.adoc[TML for tables]
* xref:tml-views.adoc[TML for views]
* xref:tml-worksheets.adoc[TML for Worksheets]

[#object-id]
== Object ID in TML files [.badge.badge-beta]#Beta#

Rather than using a system-generated GUID to identify individual objects in TML files, you can now manually set an object property (`obj_id`) with a uniqueness constraint on the Org level. This allows you to manage content across multiple Orgs without having to manually change the GUID of an object each time you move it between Orgs. To enable this feature, contact {support-url}.

To use the `obj_id` property, open the object's TML file and add a line below the `guid` property. Choose a unique string to identify the object.

The resulting two lines at the top of the TML file should look like the below:

[subs=+macros]
....
guid: <answer_guid>
obj_id: <unique_string>
....

When you migrate an object between clusters, use the `obj_id` as the primary method of import.

[#fqn]
=== fqn

fqn refers to the source table's GUID. You can find this string of letters and numbers at the end of the URL for that table or connection.

For example, in `https://<company>.thoughtspot.com/#/data/tables/34226aaa-4bcf-4d6b-9045-24cb1e9437cb`, the GUID is `34226aaa-4bcf-4d6b-9045-24cb1e9437cb`.

Use this optional parameter to reduce ambiguity and identify a specific table, if you have multiple tables with the same name. When exporting a TML file, you have the option to *Export FQNs of referenced objects*, which ensures that the TML files you export contain FQNs for the underlying tables and connections. If you do not add the `fqn` parameter, and the connection or table you reference does not have a unique name, the file import fails.

== Limitations of working with TML files

There are certain limitations to the changes you can apply by editing a Worksheet, Answer, table, view, Liveboard, or xref:monitor.adoc[Monitor alert] through TML.

include::partial$scriptability-limitations.adoc[]
