= ThoughtSpot Modeling Language
:last_updated: 11/05/2021
:linkattrs:
:experimental:
:page-layout: default-cloud
:page-aliases: /admin/ts-cloud/tml.adoc, /admin/ts-cloud/tsl.adoc, /admin/scriptability/tml.adoc, /admin/scriptability/tsl-table.adoc, /admin/scriptability/tsl-pinboard.adoc, /admin/scriptability/tsl-answer.adoc, /admin/scriptability/tsl-view.adoc, /admin/worksheets/yaml-worksheet.adoc, /admin/scriptability/tml-table.adoc, /admin/scriptability/tml-pinboard.adoc, /admin/scriptability/tml-answer.adoc, /admin/scriptability/tml-view.adoc, /admin/worksheets/tml-worksheet.adoc, /admin/worksheets/tsl-worksheet.adoc, /admin/ts-cloud/tsl-table.adoc, /admin/ts-cloud/tsl-pinboard.adoc, /admin/ts-cloud/tsl-answer.adoc, /admin/ts-cloud/tsl-view.adoc, /admin/ts-cloud/yaml-worksheet.adoc, /admin/ts-cloud/tml-worksheet.adoc, /admin/ts-cloud/tsl-worksheet.adoc
:description: Use TML to modify a ThoughtSpot object in a flat-file format. Then, migrate the object to a different cluster, or restore it to the same cluster.



Use TML to modify a ThoughtSpot object in a flat-file format. Then, migrate the object to a different cluster, or restore it to the same cluster.

To work with TML files for <<syntax-worksheets,Worksheets>>, <<syntax-views,views>>, <<syntax-sql-views,SQL views>> <<syntax-tables,tables>>, <<syntax-answers,Answers>>, <<syntax-liveboards,Liveboards>>, and <<syntax-alerts,Monitor alerts>> (in beta and off by default in 9.0.0.cl) in ThoughtSpot, you can download these objects to a flat file in `.TML` format, modify it, and subsequently upload this file either to the same cluster, or to a different cluster.
To learn how to export, change, and update Worksheets, views, tables, Answers, and Liveboards, see xref:scriptability.adoc[Import and export TML files].

In this article, you learn the syntax of the TML files for each object.
You also learn how to <<syntax-joins,add and modify joins>> for Worksheets, views, SQL views, and tables.

NOTE: The syntax examples in this article contain every possible parameter in a TML file.
Some of these parameters are not in a TML file by default.
If you want to use them, you must add them yourself. +
For example, the `fqn` parameter is not present in the TML file by default, but you can add it to differentiate a table from another table with the same name.

[#syntax-worksheets]
include::partial$tml-syntax-worksheet.adoc[]

[#syntax-views]
include::partial$tml-syntax-view.adoc[]

[#syntax-sql-views]
include::partial$tml-syntax-sql-view.adoc[]

[#syntax-tables]
include::partial$tml-syntax-table.adoc[]

[#syntax-joins]
include::partial$tml-syntax-joins.adoc[]

[#syntax-answers]
include::partial$tml-syntax-answer.adoc[]

[#syntax-liveboards]
include::partial$tml-syntax-liveboard.adoc[]

[#syntax-alerts]
include::partial$tml-syntax-alert.adoc[]

[#tml-parameters]
include::partial$tml-parameters.adoc[]

== Limitations of working with TML files

There are certain limitations to the changes you can apply by editing a Worksheet, Answer, table, view, Liveboard, or xref:monitor.adoc[Monitor alert] through TML.

include::partial$scriptability-limitations.adoc[]
