= ThoughtSpot Modeling Language
:last_updated: 11/05/2021
:linkattrs:
:experimental:
:page-layout: default-cloud
:page-aliases: /admin/ts-cloud/tml.adoc, /admin/ts-cloud/tsl.adoc, /admin/scriptability/tml.adoc
:description: Use TML to modify a ThoughtSpot object in a flat-file format. Then, migrate the object to a different cluster, or restore it to the same cluster.

Use TML to modify a ThoughtSpot object in a flat-file format. Then, migrate the object to a different cluster, or restore it to the same cluster.

To work with TML files for Worksheets, views, SQL views, tables, Answers, Liveboards, and Monitor alerts in ThoughtSpot, you can download these objects to a flat file in `.TML` format, modify it, and subsequently upload this file either to the same cluster, or to a different cluster.
To learn how to export, change, and update Worksheets, views, tables, Answers, and Liveboards, see xref:scriptability.adoc[Import and export TML files]. To learn how to migrate multiple TML files at a time, see xref:tml-import-export-multiple.adoc[].

In this section, you learn the syntax of the TML files for each object.
You also learn how to add and modify joins for Worksheets, views, SQL views, and tables.

See the following articles for the full syntax of each type of TML file:

* xref:tml-answers.adoc[TML for Answers]
* xref:tml-connections.adoc[TML for Connections]
* xref:tml-joins.adoc[TML for joins]
* xref:tml-liveboards.adoc[TML for Liveboards]
* xref:tml-alerts.adoc[TML for Monitor alerts]
* xref:tml-sql-views.adoc[TML for SQL views]
* xref:tml-tables.adoc[TML for tables]
* xref:tml-views.adoc[TML for views]
* xref:tml-worksheets.adoc[TML for Worksheets]

== Limitations of working with TML files

There are certain limitations to the changes you can apply by editing a Worksheet, Answer, table, view, Liveboard, or xref:monitor.adoc[Monitor alert] through TML.

include::partial$scriptability-limitations.adoc[]
