= ThoughtSpot Cloud requirements and support
:last_updated: 11/05/2021
:linkattrs:
:experimental:
:page-layout: default-cloud
:page-aliases: /admin/ts-cloud/ts-cloud-requirements-support.adoc
:description: Information about features, and how to sign up.
:jira: SCAL-175184

[#aws]
== AWS Supported regions

ThoughtSpot Cloud on AWS is available in the following regions:

* US East (N.
Virginia)
* US West (Oregon)
* Sydney
* Ireland
* Frankfurt
* Singapore
* Japan
* London

[#gcp]
== GCP Supported regions

ThoughtSpot Cloud on GCP is available in the following region:

* US East (Virginia)
* EMEA (Frankfurt)
* APJC (Sydney)

== Requirements

* Outbound port 443 must be open.
* If you are going to use Snowflake with ThoughtSpot Cloud, and you have a network policy set in Snowflake, you must add the outbound IP address of your ThoughtSpot Cloud instance to the whitelist inside your Snowflake network policy.
Contact {support-url} for assistance.

== Supported features

ThoughtSpot Cloud supports the following connections:

include::partial$connections-list.adoc[]

== Unsupported features

ThoughtSpot Cloud does not support the following:

* Loading data using tsload
* Data cannot be migrated to another ThoughtSpot cluster, but you can migrate Liveboards, Answers, views, tables, and Worksheets.
+
For migration details, see xref:scriptability.adoc[Import and export TML files].

[#restrict_cluster_access_only_to_certain_ip_addresses]
== Restrict cluster access only to certain IP addresses [.badge.badge-aws]#AWS-only#

By default, frontend access to your ThoughtSpot Cloud cluster(s) is open to all source IPs.
You have the option to restrict access only to certain IP addresses.
To restrict access, gather the following information, and contact {support-url}:

* *Cluster name(s)*/ fqdn (fully-qualified domain name).
For example, `abcd.thoughtspot.cloud`
* *Source IP(s)* ( Public IP) in CIDR notation.
For example, `10.10.10.10/32`

Send this information to {support-url} and ask them to restrict cluster access to only the IP(s) you specified.

== How to sign up

To sign up for ThoughtSpot Cloud, talk to your ThoughtSpot contact.

include::partial$forgot-password.adoc[]

'''
> **Related information**
>
> * xref:user-account-activation-okta.adoc[Activate your account using IAMv2]
> * xref:user-onboarding-experience.adoc[User onboarding experience]
> * xref:navigating-thoughtspot.adoc[Finding your way around]
> * xref:accessing.adoc[ThoughtSpot browser access]
> * xref:user-profile.adoc[Your user preferences]
> * xref:tags.adoc[Use tags to organize]
> * xref:privileges-end-user.adoc[Privileges]
