= Activate your ThoughtSpot account using IAMv2
:last_updated: 7/8/2022
:linkattrs:
:experimental:
:page-layout: default-cloud
:description: Learn how to activate your ThoughtSpot account.



Before you can begin using ThoughtSpot, you must activate your ThoughtSpot account. When your ThoughtSpot administrator creates your user account, ThoughtSpot sends you an activation email.

[NOTE]
====
This article contains instructions for activating your ThoughtSpot account if your company uses Identity and Access Management V2 (IAMv2). IAMv2 is *_off_* by default. If your activation email subject line is "Activate your ThoughtSpot account," your company is using IAMv2. If you are using xref:orgs-overview.adoc[], we do not currently support using IAMv2.

If your welcome email subject line is "You have been invited to ThoughtSpot!", your company is *_not_* using IAMv2. There is no account activation requirement; your account is already active.
====

== Activate your account

To activate your ThoughtSpot account, follow these steps:

. Navigate to your activation email from ThoughtSpot. The subject line is *Activate Your ThoughtSpot account*.

. Select the activation link in the email.
+
If the link has expired, ask your ThoughtSpot administrator to send you a new activation email.

. The activation link takes you to a password creation modal for your ThoughtSpot account. Create a new password, and type it into the *Create password* and *Confirm password* text boxes.
Your password must meet the following requirements:

* The password must be 8 characters or more in length.
* The password must include at least 1 uppercase letter, 1 lowercase letter, 1 number, and 1 special character.
* The password must pass a complexity test based on an external library. This test ensures password complexity and uniqueness by checking for known patterns or words that are too simple. If the password is not complex enough, ThoughtSpot rejects it, even if it fulfills the other requirements. Refer to the https://github.com/dropbox/zxcvbn[Dropbox password library^] for more information.
* The password cannot use certain blocked words. By default, the blocked words are: your username, any part of your display name, and any blocked words your company configures. To add additional words to the blocklist, contact {support-url}.

. Select *Activate*.

. On the ThoughtSpot login page, enter your new password again.

. Select *Verify*.

. Your ThoughtSpot account is now active. You can close the tab, or begin the onboarding process, either xref:business-user-onboarding.adoc[business user] or xref:analyst-onboarding.adoc[analyst], depending on your role.

Note that whenever you navigate to the login page for ThoughtSpot, you will temporarily see the following URL: `identity.thoughtspot.com`. This is an expected part of the IAMv2 login experience.

include::partial$forgot-password.adoc[]

'''
> **Related information**
>
> * xref:ts-cloud-requirements-support.adoc[Requirements and support]
> * xref:user-onboarding-experience.adoc[User onboarding experience]
> * xref:navigating-thoughtspot.adoc[Finding your way around]
> * xref:accessing.adoc[ThoughtSpot browser access]
> * xref:user-profile.adoc[Your user preferences]
> * xref:tags.adoc[Use tags to organize]
> * xref:privileges-end-user.adoc[Privileges]