= Visual Embed SDK
:last_updated: 11/05/2021
:linkattrs:
:experimental:
:page-layout: default-cloud
:page-aliases: /admin/ts-cloud/visual-embed-sdk.adoc
:description: The Visual Embed SDK provides a JS library to embed search, visualizations, Liveboards, and the full app experience in an app, product, or web portal.

include::partial$liveboards-announcement.adoc[]

The Visual Embed SDK provides a Javascript library to embed ThoughtSpot elements in your host application.

You can use the Visual Embed SDK for the following purposes:

* Embed specific components of the ThoughtSpot application;
for example, search, Liveboards, and visualizations.
* Render full ThoughtSpot experience within the context of your host application.

== SDK installation

The Visual Embed SDK is available as a Node Package Manager (NPM) package.
You can access this package at https://www.npmjs.com/package/@thoughtspot/visual-embed-sdk.
Before installing the SDK, make sure you have installed the NPM.

== Visual Embed SDK APIs

The Visual Embed SDK includes the following embed modules:

* *SearchEmbed* +
Use the *SearchEmbed* component to https://developers.thoughtspot.com/docs/?pageid=search-embed[embed the ThoughtSpot search functionality] and retrieve search data from a specific data source or an existing saved answer.
* *PinboardEmbed* +
Use the *PinboardEmbed* component to https://developers.thoughtspot.com/docs/?pageid=embed-pinboard[embed a full Liveboard with multiple visualizations], or https://developers.thoughtspot.com/docs/?pageid=embed-a-viz[a specific visualization on a Liveboard].
* *AppEmbed* +
Use the *AppEmbed* component to embed the https://developers.thoughtspot.com/docs/?pageid=full-embed[full ThoughtSpot application] with or without the navigation bar.

== How to embed ThoughtSpot content

For information about embedding ThoughtSpot using Visual Embed SDK, see the https://developers.thoughtspot.com/docs/?pageid=visual-embed-sdk[Visual Embed SDK].
