= Visual Embed SDK
:last_updated: 2/24/2022
:linkattrs:
:experimental:
:page-layout: default-cloud
:page-aliases: /admin/ts-cloud/visual-embed-sdk.adoc
:description: The Visual Embed SDK provides a JS library to embed search, visualizations, Liveboards, and the full app experience in an app, product, or web portal.


The Visual Embed SDK provides a Javascript library to embed ThoughtSpot elements in your host application.

You can use the Visual Embed SDK for the following purposes:

* Embed specific components of the ThoughtSpot application; for example, the Search bar, Search page, Liveboards, and visualizations.
* Render the entire ThoughtSpot app within the context of your host application.

== SDK installation

The Visual Embed SDK is available as a Node Package Manager (NPM) package.
You can access this package at https://www.npmjs.com/package/@thoughtspot/visual-embed-sdk[https://www.npmjs.com/package/@thoughtspot/visual-embed-sdk^].

== Visual Embed SDK APIs

The Visual Embed SDK includes the following packages and JavaScript libraries:

SearchBarEmbed::
Use *SearchBarEmbed* to https://developers.thoughtspot.com/docs/?pageid=embed-searchbar[embed the ThoughtSpot Search bar, window=_blank] and get search results as raw data.
SearchEmbed::
Use *SearchEmbed* to https://developers.thoughtspot.com/docs/?pageid=search-embed[embed the ThoughtSpot Search functionality, window=_blank] and retrieve search data from a data source or saved Answer.
LiveboardEmbed::
Use *LiveboardEmbed* to https://developers.thoughtspot.com/docs/?pageid=embed-liveboard[embed a full Liveboard with multiple visualizations, window=_blank], or https://developers.thoughtspot.com/docs/?pageid=embed-a-viz[a specific visualization on a Liveboard, window=_blank].
AppEmbed::
Use *AppEmbed* to embed the https://developers.thoughtspot.com/docs/?pageid=full-embed[full ThoughtSpot application, window=_blank] with or without the navigation bar.

== How to embed ThoughtSpot content

For information about how to embed ThoughtSpot in your app, see https://developers.thoughtspot.com/docs/?pageid=visual-embed-sdk[Visual Embed SDK,window=_blank].

