= Web notifications
:author: Naomi
:last_updated: 6/14/23
:linkattrs:
:experimental:
:page-layout: default-cloud

Users can now receive in-app notifications when items are shared with them, or when other users request access to an Answer or Liveboard. To view these notifications, simply click on the user profile icon.

== How it works

When web notifications are enabled, you will see a notification in your notification queue when a user shares an Answer or Liveboard with you, or when a user requests access to an Answer or Liveboard you created. These notifications appear when you click your user profile icon. Clicking on a shared Answer or Liveboard notification will take you to that Answer or Liveboard. Clicking on an access requested notification takes you to the object and opens the "Share Answer or Liveboard" pop-up. You can then enter the name of the user who requested access in order to grant view access to the object.

== Enable or disable notifications

From your user profile, you can choose to enable or disable web and email notifications. By default, web and email notifications for shared objects and access requests are enabled. To disable web and email notifications, follow these steps:

. Click your user profile icon in the top right corner of the screen.

. Click *View my profile* to navigate to your profile.

. Scroll down to the *Notification preferences* section and click *Edit*.

. In the *Notification preference* page, you see the options *When Liveboards/answers are shared with you* and *When access is requested for Liveboards or answers*. Deselect the checkboxes next to the options you wish to disable. Note that you can choose to disable only web or email notifications, or both.
