= How the Worksheet join rule works
:last_updated: 11/18/2019
:linkattrs:
:experimental:
:page-layout: default-cloud
:page-aliases: /admin/worksheets/progressive-joins.adoc
:description: The Worksheet join rule specifies when to apply joins when searching on a Worksheet.

Use the Worksheet join rule to specify when to apply joins when a search is done on a Worksheet.
You can either apply joins progressively, as each search term is added (recommended), or apply all joins to every search.

== Understand progressive joins

Often, a Worksheet includes several dimension tables and a fact table.
With progressive joins, if your search only includes terms from the fact table, you can see all of the rows that satisfy your search.
But as you add terms from dimension tables, the total number of rows shown may be reduced, as the joins to each dimension table are applied.
It works like this:

* If you choose *Apply joins progressively (recommended for most cases)*, joins are only applied for tables whose columns are included in the search.
* If you choose *Apply all joins*, all possible joins are applied, regardless of which tables are included in the search.

When using *Apply joins progressively*, the number of rows in a search using the Worksheet depends on which tables are part of the search.
The Worksheet contains the results of a defined query in the form of a table.
So if a particular dimension table is left out of the search, its joins are not applied.

== Rule-based row-level security (RLS) with worksheets

With rule-based RLS, you need to protect every table that contains any sensitive data.
To do this, you can grant access by creating explicit row-level security rules on each of the underlying tables which contain data that row-level security should apply to.

When creating the row-level security rules for a table that's part of a Worksheet, you aren't limited to referencing only the columns in that table.
You can specify columns from other tables in the Worksheet as well, as long as the tables are joined to the table you're creating the rule on.
Then, when creating a Worksheet on top of them, the behavior is consistent regardless of the Worksheet join rule you choose.
Users will never be able to see data they should not, regardless of what their search contains.

Imagine you have a Worksheet that contains a `Sales` fact table, and `Customer` and `Product` dimensions that are joined on `Customer SSN` and `Product Code` columns.
In order to secure the `Sales` table, you can use `Customer Name` from the `Customer` column to create a row-level security rule.

== How joins are applied with chasm traps

When working with Worksheets and row-level security, you need to understand how joins are applied.
This is particularly important with chasm trap schemas.
For chasm trap schemas, if row-level security is only set on one of the tables, people could see data they should not see if the scope of their search does not include that table.
(this protects them from having people see the wrong things if they have chasm trap).

For chasm trap _worksheets_, progressive and non-progressive joins do not apply.
There is an entirely different methodology for how Worksheet joins on a chasm trap schema work with row-level security.
So you can safely ignore that setting.

'''
> **Related information**
>
> * xref:worksheet-edit.adoc[Edit a Worksheet]
> * xref:worksheet-formula.adoc[Create a formula in a Worksheet]
> * xref:worksheet-filter.adoc[Create a Worksheet filter]
> * xref:worksheet-inclusion.adoc[Create join rule or RLS for a Worksheet]
> * xref:join-add.adoc[Create a join relationship]
> * xref:join-worksheet-edit.adoc[Modify joins between Worksheet tables]
> * xref:worksheet-delete.adoc[Delete Worksheets or tables]
> * xref:scriptability.adoc[Migrate or restore Worksheets]
> * xref:tml-worksheets.adoc[Worksheet TML specification]
