= Edit or rename Worksheet
:last_updated: 11/18/2019
:linkattrs:
:experimental:
:page-layout: default-cloud
:page-aliases: /admin/worksheets/edit-worksheet.adoc
:description: Anyone with the proper permissions can edit a Worksheet.

If you created a Worksheet, or you have edit permissions on it, you can make changes such as adding sources and columns, adding or editing formulas, changing relationships, and changing column names.
You can also rename a Worksheet or change its description.

== Edit a Worksheet

To edit a Worksheet:

. Click *Data* on the top navigation bar.
. Click the name of the Worksheet you want to edit.
. Click the *Edit* button in the upper-right side of the screen.
. Make your changes to the Worksheet.
. Click *Save changes*.

== Rename a Worksheet or table

You can change a Worksheet or table name from the ThoughtSpot application.

To change the name of a Worksheet or table:

. Click *Data*, on the top navigation bar.
. Find the Worksheet or table you want to rename and click its name.
. Click the current name, and enter a new name.

'''
> **Related information**
>
> * xref:worksheet-inclusion.adoc[Change the join rule for a Worksheet]
> * xref:join-add.adoc[Add joins between a Worksheet and other data]
> * xref:join-worksheet-edit.adoc[Modify table joins within a Worksheet]
