[#admin-portal]
== Configure SAML using the Admin Console
You need admin privileges to enable SAML SSO authentication.

'''
> **ThoughtSpot Training**
>
> * For best results, we recommend that you take the following ThoughtSpot U course: https://training.thoughtspot.com/authentication-security/621450[Single Sign On (SSO)^].
> * See other training resources at https://training.thoughtspot.com/[ThoughtSpot U^].

'''

NOTE: If you configure authentication through SAML, you cannot also configure authentication through Active Directory.

1. Configure the ThoughtSpot application instance on your IDP server.

2. Log into your ThoughtSpot application instance.

3. From the top navigation bar, select the **Admin** tab.

4. Select **SAML** from the side navigation bar that appears.

5. Click the **Configure** button in the middle of the screen.

6. Fill in the parameters with the information you collected in the xref:prerequisites[Configuration prerequisites].

7. When the configuration is complete, download ThoughtSpot's metadata file, `spring_saml_metadata.xml`. This file contains the public key you need if you want to encrypt your SAML assertions. To download this file, navigate to `\https://<hostname-or-IP>/callosum/v1/saml/metadata`. The file automatically downloads.

NOTE: ThoughtSpot adds external users, or users that authenticate through SAML or Active Directory, to the *all* group by default. This group has no privileges. You must manually assign users to ThoughtSpot groups to give them privileges, such as *can upload user data*, or *can manage data*.

=== Configure the IDP

To enable the IdP to recognize your host application and ThoughtSpot as a valid service provider, you must configure the IdP with required attributes and metadata. This includes the `spring_saml_metadata.xml` file that you downloaded in step 7 of <<admin-portal,Configure SAML using the Admin Console>>.

ThoughtSpot supports SAML authentication with several identity and access management providers, such as https://developer.okta.com/docs/guides/build-sso-integration/saml2/before-you-begin/[Okta^], https://docs.microsoft.com/en-us/powerapps/maker/portals/configure/configure-saml2-settings-azure-ad[Azure Active Directory^], https://docs.pingidentity.com/bundle/pingfederate-102/page/ikb1564003000542.html[PingFederate^], https://docs.microsoft.com/en-us/powerapps/maker/portals/configure/configure-saml2-settings[Microsoft AD FS^], https://developers.onelogin.com/saml[Onelogin^] and so on. If you want to use one of these providers as your IdP, make sure you read the SAML configuration steps described in the Identity provider’s documentation site.

To determine if ThoughtSpot supports your preferred IdP, xref:support-contact.adoc[contact ThoughtSpot support].

Complete your configuration of the IdP using the IdP's SAML documentation. Upload or copy the contents of the `spring_saml_metadata.xml` to your IdP server. If you did not download the `spring_saml_metadata.xml` file, navigate to `\https://<your_ThoughtSpot_hostname-or-IP>/callosum/v1/saml/metadata`. The file automatically downloads.

Refer to <<saml-configure-2,Configure SAML 2.0>> for details on correct field mapping.

After you configure the IdP, open a Web browser and go to the ThoughtSpot login page. It should now show the Single Sign On option.

[#saml-configure-2]
=== Configure SAML 2.0

When configuring SAML 2.0, ensure that you map the SAML user attributes and subjects to appropriate fields. This allows the ThoughtSpot system to automatically pick up certain attributes and subjects, such as a user's email address, display name, and username.

For example,

Onelogin::
You must map the SAML user’s _username_ to the _NameId_ attribute.
Okta::
You must map the `username` to `userPrincipalName`.

You must also map the `email` address of the user to the `mail` attribute.
Optionally, map the display name you would like to use to the `displayName` subject.

Attributes and subjects appear in separate sections of your SAML assertion.

WARNING: Starting in ThoughtSpot version 6.3.1, the mail field is mandatory, and cannot be empty. If your organization cannot meet this requirement, contact xref:support-contact.adoc[ThoughtSpot Support] for help.

If your IdP does not allow you to import the IdP metadata XML file, you must map these values manually.
