:linkattrs:

You can contact ThoughtSpot by <<phone,phone>>, <<address,mail>>, <<email,email>>, by <<file-ticket,filing a support ticket>>, or by asking <<community,the ThoughtSpot community>>.

[#file-ticket]
== File a support ticket

If you encounter a technical issue, file a support ticket using the Support Portal ticket filing system at:

http://thoughtspot.com/support-request

Please provide as much detail as possible about your issue, to help us resolve it quickly.

You need a Support Portal login to file a ticket.
If you do not have one, contact your ThoughtSpot liaison.

[#community]
== Ask the ThoughtSpot community

Interact with the ThoughtSpot community to find useful content, ask and answer questions, exchange ideas and best practices, and collaborate with other customers, partners, and ThoughtSpot employees.
You can find the ThoughtSpot community at:

https://community.thoughtspot.com/s/

[#address]
== Address

ThoughtSpot, Inc.
1900 Camden Avenue
Suite 101
San Jose, CA 95124

[#phone]
== Phone numbers

|===
| Phone Number | Description

| 1-800-508-7008 ext 1
| ThoughtSpot Support.

| 1-800-508-7008
| Toll-free number for ThoughtSpot headquarters.
|===

[#email]
== Email

|===
| Reason for contacting us | Email

| Sales inquiries
| link:mailto:sales@thoughtspot.com[sales@thoughtspot.com]

| Other inquiries
| link:mailto:hello@thoughtspot.com[hello@thoughtspot.com]
|===
