[#prerequisites]
== Configuration prerequisites

Before you configure SAML, collect the following information:

[cols="5,~",grid=none,frame=none]
|===
| &#10063; | <<ts-service-address,ThoughtSpot service address>>
| &#10063; | <<ts-service-port,Service port>>
| &#10063; | <<ts-service-name,Unique service name>>
| &#10063; | <<skew-time,Skew time in seconds>>
| &#10063; | <<protocol,Protocol>>
| &#10063; | <<metadata-xml-file,IDP Metadata XML File>>
| &#10063; | <<auto-add,Automatically add SAML users to Thoughtspot>>
| &#10063; | <<ts-auth,Also use ThoughtSpot internal authentication>>
| &#10063; | <<max-auth,samlMaxAuthenticationAge>>
|===

[#ts-service-address]
=== ThoughtSpot service address
A fully qualified and resolvable domain name for the ThoughtSpot service. For example, *thoughtspot.thoughtspot-customer.com*. If you do not have the DNS name, you can use the front-end IP address. However, using the DNS name instead of the IP address is a best practice.

[#ts-service-port]
=== Service port
Enter `443` in this box. This is the port of the server where your ThoughtSpot instance is running.

[#ts-service-name]
=== Unique service name
The unique key used by your Identity Provider to identify the client. For example, *urn:thoughtspot:callosum:saml*. You may know this as the *Entity ID*.

[#skew-time]
=== Skew time in seconds
The allowed skew time, after which the authentication response is rejected and sent back from the IDP. *86400* is a popular choice. The default is *3600*.

[#protocol]
=== Protocol
The connection protocol for ThoughtSpot. For example, `https`.

[#metadata-xml-file]
=== IdP Metadata XML File
The absolute path to your Identity Provider’s metadata file. This file is provided by your IDP. You need this file so that the configuration persists over upgrades. It is a best practice to set it up on persistent/HA storage (NAS volumes) or in the same absolute path on all nodes in the cluster. For example, *idp-meta.xml*. If your IDP needs an Assertion Consumer Service URL to create the metadata file, use `https://<hostname_or_IP>:443/callosum/v1/saml/SSO`. Note that this URL is case-sensitive.

If your IdP does not allow you to import the IdP metadata XML file, you must map values between ThoughtSpot and your IDP manually. This allows the ThoughtSpot system to automatically pick up certain attributes, such as a user's email address and username. Map the username attribute value in your IDP (`userPrincipalName` in Okta, for example) to `NameId`, and map the `email` attribute value to `mail`.

For additional support with the attribute statements, refer to your IDP's SAML documentation. ThoughtSpot supports SAML authentication framework with popular Identity Providers such as https://developer.okta.com/docs/guides/build-sso-integration/saml2/before-you-begin/[Okta^], https://docs.microsoft.com/en-us/powerapps/maker/portals/configure/configure-saml2-settings-azure-ad[Azure Active Directory^], https://docs.pingidentity.com/bundle/pingfederate-102/page/ikb1564003000542.html[PingFederate^], https://docs.microsoft.com/en-us/powerapps/maker/portals/configure/configure-saml2-settings[Microsoft AD FS^], and https://developers.onelogin.com/saml[Onelogin^]. This is not an exhaustive list. To determine if ThoughtSpot supports your preferred IdP, talk to your ThoughtSpot contact.

[#auto-add]

=== Automatically add SAML users to Thoughtspot: (yes/no)
Choose whether or not to add SAML users to ThoughtSpot when they first authenticate. If you choose 'yes', then new users will be automatically created in ThoughtSpot upon first successful SSO login. If you choose 'no', then SAML users will not be added in ThoughtSpot upon first successful SSO login. Instead, you must xref:add-user.adoc[add users manually] or through xref:ldap-config-ad.adoc[Active Directory].


[#ts-auth]
=== Also use ThoughtSpot internal authentication: (y/n)

If 'y', then ThoughtSpot local/internal users (including local administrative users) will still be authenticated outside the scope of SSO.
