[#prerequisites]
== Configuration prerequisites

Before you configure SAML, collect the following information:

[cols="5,~",grid=none,frame=none]
|===
| &#10063; | <<ts-service-address,ThoughtSpot service address>>
| &#10063; | <<ts-service-port,Service port>>
| &#10063; | <<ts-service-name,Unique service name>>
| &#10063; | <<skew-time,Skew time in seconds>>
| &#10063; | <<protocol,Protocol>>
| &#10063; | <<metadata-xml-file,IDP Metadata XML File>>
| &#10063; | <<label,IDP label>>
| &#10063; | <<default,Do you want to make this IDP default?>>
| &#10063; | <<auto-add,Automatically add SAML users to Thoughtspot>>
| &#10063; | <<ts-auth,Also use ThoughtSpot internal authentication>>
| &#10063; | <<max-auth,samlMaxAuthenticationAge>>
|===

[#ts-service-address]
=== ThoughtSpot service address
A fully qualified and resolvable domain name for the ThoughtSpot service. For example, *thoughtspot.thoughtspot-customer.com*. If you do not have the DNS name, you can use the front-end IP address. However, using the DNS name instead of the IP address is a best practice.

[#ts-service-port]
=== Service port
Enter `443` in this box. This is the port of the server where your ThoughtSpot instance is running.

[#ts-service-name]
=== Unique service name
The unique key used by your Identity Provider(s) to identify the client. For example, _urn:thoughtspot:callosum:saml_, or _https://ssoappname.sso-provider.com/ab12c3de4_. This is also called the *SP Entity ID*.

[#skew-time]
=== Skew time in seconds
The allowed skew time, after which the authentication response is rejected and sent back from the IDP. *86400* is a popular choice. The default is *3600*.

[#protocol]
=== Protocol
The connection protocol for ThoughtSpot. For example, `https`.

[#label]
=== IDP label
*[TSCLI only. For multiple IDP only, with `--multi` flag]* Unique key to identify this IDP when using multiple identity providers. Cannot start with a period (`.`).

[#default]
=== Do you want to make this IDP default?
*[TSCLI only. For multiple IDP only, with `--multi` flag]* Specifies if this IDP should be the default. Type `y` to make this IDP the default, and `n` to make the next IDP you configure the default. When users log in to ThoughtSpot from the ThoughtSpot URL, the login screen takes them to the default IDP to log in. To use other, non-default IDPs that you configured with the `--multi` flag, users must log in to ThoughtSpot from the other IDP's login page.

[#metadata-xml-file]
=== IDP Metadata XML File
The absolute path to your Identity Providers' metadata file. This file is provided by your IDP(s). You need this file so that the configuration persists over upgrades. It is a best practice to set it up on persistent/HA storage (NAS volumes) or in the same absolute path on all nodes in the cluster. For example, *idp-meta.xml*. If your IDP(s) needs an Assertion Consumer Service URL to create the metadata file, use `\https://<hostname_or_IP>:443/callosum/v1/saml/SSO`. Note that this URL is case-sensitive.

If your IDP(s) does not allow you to import the IDP metadata XML file, you must map values between ThoughtSpot and your IDP manually. This allows the ThoughtSpot system to automatically pick up certain attributes and subjects, such as a user's email address, display name, and username. Map the username attribute value in your IDP(s) (`userPrincipalName` in Okta, for example) to `NameId`, map the `email` attribute value to `mail`, and optionally map the `display name` subject value to `displayName`. Attributes and subjects appear in separate sections of your SAML assertion. It is *mandatory* to fill out the mail field. If your company cannot meet this requirement, contact {support-url}.

For additional support with the attribute and subject statements, refer to your IDP's SAML documentation. ThoughtSpot supports SAML authentication framework with popular Identity Providers such as https://developer.okta.com/docs/guides/build-sso-integration/saml2/before-you-begin/[Okta^], https://docs.microsoft.com/en-us/powerapps/maker/portals/configure/configure-saml2-settings-azure-ad[Azure Active Directory^], https://docs.pingidentity.com/bundle/pingfederate-102/page/ikb1564003000542.html[PingFederate^], https://docs.microsoft.com/en-us/powerapps/maker/portals/configure/configure-saml2-settings[Microsoft AD FS^], and https://developers.onelogin.com/saml[Onelogin^]. This is not an exhaustive list. To determine if ThoughtSpot supports your preferred IDP, talk to your ThoughtSpot contact.

[#auto-add]
=== Automatically add SAML users to Thoughtspot: (yes/no)
Choose whether or not to add SAML users to ThoughtSpot when they first authenticate. If you choose 'yes', then new users will be automatically created in ThoughtSpot upon first successful SSO login. If you choose 'no', then SAML users will not be added in ThoughtSpot upon first successful SSO login. Instead, you must xref:user-management.adoc#add-user[add users manually] or through xref:ldap-config-ad.adoc[Active Directory].

[#ts-auth]
=== Also use ThoughtSpot internal authentication: (y/n)

If 'y', then ThoughtSpot local/internal users (including local administrative users) will still be authenticated outside the scope of SSO.

[#max-auth]
=== samlMaxAuthenticationAge (tscli configuration only)

By default, ThoughtSpot sets your `samlMaxAuthenticationAge` to 18114400 (seconds). If you experience an unauthorized error when logging in via SAML, your `AuthnInstant` value may be set to a different, older value. To resolve this issue, find your `AuthnInstant` value in the IDP login assertion. Set the `samlMaxAuthenticationAge` to a value older than that value.

This is only one reason why you may receive an unauthorized error when logging in via SAML; if updating your `samlMaxAuthenticationAge` value does not resolve this issue, contact {support-url}.

You can only configure this setting when configuring SAML xref:saml.adoc#saml-configure-tscli[using tscli].
