To use scripting before or after the sync, follow these steps:

. Open the *Advanced setup* interface by clicking the toggle to open.
. Choose the *Sync properties* tab.
. Scroll down to *Advanced configuration*, and click the toggle to expand.
. Specify the following information:
[#set-sync-file-trigger]
Wait for file::
Specify the fully-qualified name of the file (directory path and file name) that must be present before sync can start.
+
Timeout(in seconds)::
specify the maximum timeout for the file to get sync.

NOTE: ThoughtSpot deletes the file after the sync process completes.
[#set-sync-pre-script]
Pre-Sync TQL::
Add the TQL script that you want to run *before* syncing.
+
Optional field.
+
For example, to drop data that is over 1 year old, enter the following expression:
+
[source]
----
DELETE from FACT_TABLE Where DATE < DATEADD(TODAY(),-365).
----
+
To find the correct functions for the script, click *Expression editor*, use it to create a valid command (or several commands), and click *OK*.
[#set-sync-post-script]
Post-Sync TQL::
Add the TQL script that you want to run *after* syncing.
+
Optional field.
+
For example, to drop data that is over 1 year old, enter the following expression:
+
[source]
----
DELETE from FACT_TABLE Where DATE < DATEADD(TODAY(),-365).
----
+
To find the correct functions for the script, click *Expression editor*, use it to create a valid command (or several commands), and click *OK*.
[#rerun-on-failure]
Rerun on failure::
Select whether to rerun if there is a failure. +
Optional field. +
Specify the number of rerun attempts, and the wait time in seconds before a rerun. There is no limit on number of rerun attempts.
. Save your work by clicking *Save*.

Alternatively, click *Save and sync now* to save your work and sync data at the same time.
