== Syntax of the Worksheet TML file

The `TML` file for Scriptable Worksheets has a specific syntax.

See the xref:parameters[TML parameters] for details about the keywords used in this example.

You may not see each of these parameters in your own TML files, depending on whether each variable is explicitly defined.
For example, if you do not have any filters on your Worksheet, the `filters` parameter does not appear.
You can add that variable to the TML file to specify filters for your Worksheet.

Refer to <<syntax-joins,join syntax>> for more information on the functionality and syntax of Worksheet, View, and table joins in TML.

NOTE: If you edit the joins in the Worksheet TML file, you are only editing the joins for that specific Worksheet. You are not editing the joins at the table level. To modify table-level joins, you must edit the source table's TML file.

[subs=+macros]
....
<<guid,guid>>: <worksheet_guid>
<<worksheet,worksheet>>:
  name: <worksheet_name>
  <<description,description>>:
    This is a multi-line description of the worksheet
    Description line 2
  <<tables,tables>>:
  - <<name,name>>: <table_name_1>
    <<id,id>> : <optional_table_id>
    <<fqn,fqn>> : <optional_GUID_of_table_name>
  - <<name,name>>: <table_name_2>
  - <<name,name>>: <table_name_n>
  <<joins,joins>>:
  - <<name,name>>: <join_name_1>
    <<source,source>>: <source_table_name>
    <<destination,destination>>: <destination_table_name>
    <<type,type>>: [RIGHT_OUTER | LEFT_OUTER | INNER | OUTER]
    <<on,on>>: <join_expression_string>
    <<is_one_to_one,is_one_to_one>>: [ false | true ]
  - ...
  <<table_paths,table_paths>>:
  - <<id,id>>: <table_path_name_1>
    <<table,table>>: <table_name_1>
    <<join_path,join_path>>:
    - <<join,join>>:
      - <join_name_1>
  - <<id,id>>: <table_path_name_2>
    <<table,table>>: <table_name_2>
    <<join_path,join_path>>:
    - {}
  - <<id,id>>: <table_path_name_3>
    <<table,table>>: <table_name_3>
    <<join_path,join_path>>:
    - <<join,join>>:
      - <join_name_1>
    - <<join,join>>:
      - <join_name_2>
      - <join_name_3>
    - <<join,join>>:
      - <join_name_4>
      - <join_name_5>
      - <join_name_6>
  <<formulas,formulas>>:
  - <<name,name>>: <formula_name_1>
    <<expr,expr>>: <formula_definition_1>
    [id]: <optional_unique_identifier>
  - <<name,name>>: <formula_name_2>
    <<expr,expr>>: <formula_definition_2>
  - <<name,name>>: <formula_name_3>
    <<expr,expr>>: <formula_definition_3>
  <<filters,filters>>:
  - <<column,column>>: <filtered_column_name_1>
    <<oper,oper>>: <filter_operator>
    <<values,values>>: <filtered_values>
    - value 1
    - value 2
    - value n
  - <<column,column>>: <filtered_column_name_2>
  <<worksheet_columns,worksheet_columns>>:
  - <<name,name>>: <column_name_1>
    <<description,description>>: <optional_column_description>
    <<column_id,column_id>>: <column_id_1>
    <<properties,properties>>:
      <<column_type,column_type>>: [ MEASURE | ATTRIBUTE ]
      <<aggregation,aggregation>>: [ SUM | COUNT | AVERAGE | MAX | MIN |
                     COUNT_DISTINCT | NONE | STD_DEVIATION | VARIANCE]
      <<index_type,index_type>>: [ DONT_INDEX | DEFAULT | PREFIX_ONLY |
                    PREFIX_AND_SUBSTRING | PREFIX_AND_WORD_SUBSTRING ]
 	    <<index_priority,index_priority>>: <index_priority>
      <<synonyms,synonyms>> :
             <synonym_1>
             <synonym_2>
      <<is_attribution_dimension,is_attribution_dimension>> : [true | false]
      <<is_additive,is_additive>> : [ true | false ]
      <<calendar,calendar>> : [ default | calendar_name ]
      <<format_pattern,format_pattern>> : <format_pattern_string>
      <<currency_type,currency_type>> :
        is_browser : true
          OR
        column : <column_name>
          OR
        iso_code : <valid_ISO_code>
      <<is_hidden,is_hidden>>: [ true | false ]
      <<geo_config,geo_config>> :
        latitude : true
          OR
        longitude : true
          OR
        country : true
          OR
        region_name:
        - country : <name_supported_country>
        - region_name : <region_name_in_UI>
      <<spotiq_preference,spotiq_preference>>: <spotiq_preference_string>
      <<search_iq_preferred,search_iq_preferred>>: [ true | false ]
    <<name,name>>: <column_name_2>
    <<description,description>>: <column_description>
    <<column_id,column_id>>: <column_id_2>
    ...
  <<properties,properties>>:
    <<is_bypass_rls,is_bypass_rls>>: [ true | false ]
    <<join_progressive,join_progressive>>: [ true | false ]
  <<lesson_plans,lesson_plans>>
  - <<lesson_id,lesson_id>>: <lesson_id_number_1>
    <<lesson_plan_string,lesson_plan_string>> <lesson_plan_string_1>
  - <<lesson_id,lesson_id>>: <lesson_id_number_2>
    <<lesson_plan_string,lesson_plan_string>> <lesson_plan_string_2>
  - <<lesson_id,lesson_id>>: <lesson_id_number_n>
    <<lesson_plan_string,lesson_plan_string>> <lesson_plan_string_n>
....
