== Syntax of the Models TML file

The `TML` file for Models has a specific syntax.

See the <<worksheet-models,TML parameters for Models>> for details about the keywords used in this example.

See <<limitations,Limitations of working with TML files>> for more information about actions you can't perform using TML.

You may not see each of these parameters in your own TML files, depending on whether each variable is explicitly defined.
For example, if you do not have any filters on your Model, the `filters` parameter does not appear.
You can add that variable to the TML file to specify filters for your Model.

To reduce ambiguity, you may need to add the optional `fqn` parameter to your TML file when you reference source tables or connections. This is necessary if you have multiple connections or tables with the same name. If you do not add the `fqn` parameter, and the connection or table you reference does not have a unique name, the file import fails.

Refer to xref:tml-joins.adoc[TML for joins] for more information on the functionality and syntax of Model joins in TML.

NOTE: If you edit the joins in the Model TML file, you are only editing the joins for that specific Model. You are not editing the joins at the table level. To modify table-level joins, you must edit the source table's TML file.


[subs=+macros]
....
<<guid,guid>>: <model_guid>
<<model,model>>:
  name: <model_name>
  <<description,description>>:
    This is a multi-line description of the model
    Description line 2
  <<model_tables,model_tables>>:
  - <<name,name>>: <table_name_1>
    <<id,id>> : <optional_table_id>
    <<fqn,fqn>> : <optional_GUID_of_table_name>
    <<joins,joins>>:
    - <<with,with>>: Alias
      <<on,on>>: <join_expression_string>
      <<type,type>>: [RIGHT_OUTER | LEFT_OUTER | INNER | OUTER]
      <<cardinality, cardinality>>: [MANY_TO_ONE | ONE_TO_ONE | ONE_TO_MANY]
  - <<name,name>>: <table_name_2>
    <<alias,alias>>: Alias
  - <<name,name>>: <table_name_3>
    <<joins,joins>>:
    - <<with,with>>: <table_name_1>
      <<referencing_join,referencing_join>>: <join_expression_string>
  <<formulas,formulas>>:
  - <<name,name>>: <formula_name_1>
    <<expr,expr>>: <formula_definition_1>
    <<id,id>>: <optional_unique_identifier>
  - <<name,name>>: <formula_name_2>
    <<expr,expr>>: <formula_definition_2>
  - <<name,name>>: <formula_name_3>
    <<expr,expr>>: <formula_definition_3>
  <<filters,filters>>:
  - <<column,column>>: <filtered_column_name_1>
    <<oper,oper>>: <filter_operator>
    <<values,values>>: <filtered_values>
    - value 1
    - value 2
    - value n
  - <<column,column>>: <filtered_column_name_2>
  <<columns,columns>>:
  - <<name,name>>: <column_name_1>
    <<description,description>>: <optional_column_description>
    <<column_id,column_id>>: <table_path>::<column_id_1>
    <<properties,properties>>:
      <<column_type,column_type>>: [ MEASURE | ATTRIBUTE ]
      <<aggregation,aggregation>>: [ SUM | COUNT | AVERAGE | MAX | MIN |
                     COUNT_DISTINCT | NONE | STD_DEVIATION | VARIANCE]
      <<index_type,index_type>>: [ DONT_INDEX | DEFAULT | PREFIX_ONLY |
                    PREFIX_AND_SUBSTRING | PREFIX_AND_WORD_SUBSTRING ]
      <<index_priority,index_priority>>: <index_priority>
      <<synonyms,synonyms>> :
      - value 1
      - value 2
      - value n
      <<is_attribution_dimension,is_attribution_dimension>> : [true | false]
      <<is_additive,is_additive>> : [ true | false ]
      <<calendar,calendar>> : [ default | calendar_name ]
      <<format_pattern,format_pattern>> : <format_pattern_string>
      <<currency_type,currency_type>> :
        is_browser : true
          OR
        column : <column_name>
          OR
        iso_code : <valid_ISO_code>
      <<is_hidden,is_hidden>>: [ true | false ]
      <<geo_config,geo_config>>:
        latitude : true
          OR
        longitude : true
          OR
        country : true
          OR
        region_name:
        - country : <name_supported_country>
        - region_name : <region_name_in_UI>
          OR
        <<custom_file_guid,custom_file_guid>>: <custom_map_guid>
        <<geometryType,geometryType>>: <custom_map_geometry_type>
      <<spotiq_preference,spotiq_preference>>: <spotiq_preference_string>
    <<name,name>>: <column_name_2>
    <<description,description>>: <column_description>
    <<column_id,column_id>>: <table_path>::<column_id_2>
    ...
  <<properties,properties>>:
    <<is_bypass_rls,is_bypass_rls>>: [ true | false ]
    <<join_progressive,join_progressive>>: [ true | false ]
  <<lesson_plans,lesson_plans>>
  - <<lesson_id,lesson_id>>: <lesson_id_number_1>
    <<lesson_plan_string,lesson_plan_string>> <lesson_plan_string_1>
  - <<lesson_id,lesson_id>>: <lesson_id_number_2>
    <<lesson_plan_string,lesson_plan_string>> <lesson_plan_string_2>
  - <<lesson_id,lesson_id>>: <lesson_id_number_n>
    <<lesson_plan_string,lesson_plan_string>> <lesson_plan_string_n>
  <<parameters,parameters>>:
  - <<id,id>>: <parameter_1_id>
    <<name,name>>: <parameter_1_name>
    <<data_type,data_type>>: <parameter_1_data_type>
    <<default_value,default_value>>: <parameter_1_default_value>
    <<description,description>>: “parameter description”
    <<range_config,range_config>>:
      <<range_min,range_min>>: <parameter_1_range_minimum>
      <<range_max,range_max>>: <parameter_1_range_maximum>
      <<include_min,include_min>>: [true | false]
      <<include_max,include_max>>: [true | false]
  - <<id,id>>: <parameter_2_id>
    <<name,name>>: <parameter_2_name>
    <<data_type,data_type>>: <parameter_2_data_type>
    <<default_value,default_value>>: <parameter_1_default_value>
    <<list_config,list_config>>:
      <<list_choice,list_choice>>:
      - <<value,value>>: <list_value_1>
        <<display_name,display_name>>: <value_1_display_name>
      - <<value,value>>: <list_value_2>
        <<display_name,display_name>>: <value_2_display_name>
      - <<value,value>>: <list_value_n>
        <<display_name,display_name>>: <value_n_display_name>
        <<linked_parameters,linked_parameters>>: <table_name>::<parameter_name_in_ThoughtSpot>
  - <<id,id>>: <parameter_n_id>
    <<name,name>>: <parameter_n_name>
    <<data_type,data_type>>: <parameter_n_data_type>
    <<default_value,default_value>>: <parameter_n_default_value>
    <<range_config,range_config>>:
      <<range_min,range_min>>: <parameter_n_range_minimum>
      <<range_max,range_max>>: <parameter_n_range_maximum>
      <<include_min,include_min>>: [true | false]
      <<include_max,include_max>>: [true | false]
....



//   <<joins_with,joins_with>>:
//   - <<name,name>>: <join_name_1>
//     <<description,description>>: <optional_join_description_1>
//     <<destination,destination>>:
//       <<name,name>>: <destination_table_name_1>
//       <<fqn,fqn>>: <optional_table_guid_1>
//     <<on,on>>: <join_expression_string_1>
//     <<type,type>>: [RIGHT_OUTER | LEFT_OUTER | INNER | OUTER]
//     <<is_one_to_one,is_one_to_one>>: [ false | true ]
//     <<name,name>>: <join_name_2>
//     <<name,name>>: <join_name_n>