== Syntax of the Answer TML file

The `TML` file for Scriptable Answers has a specific syntax.

See the xref:parameters[TML parameters] for details about the keywords used in this example.

You may not see each of these parameters in your own TML files, depending on whether each variable is explicitly defined.
For example, if you did not define any conditional formatting, the `conditional_formatting` variable does not appear.
You can add that variable in the TML file to specify conditional formatting.

[subs=+macros]
....

<<guid,guid>>: <answer_guid>
<<answer,answer>>:
  <<name,name>>: <answer_name>
  <<description,description>>:
    This is a multi-line description of the answer
    Description line 2
  <<tables,tables>>:
  - <<id,id>>: <table_id>
    <<name,name>>: <table_name_1>
    <<fqn,fqn>>: <optional_GUID_of_table_name>
  <<formulas,formulas>>:
  - <<id,id>>: <formula_id_1>
    <<name,name>>: <formula_name_1>
    <<expr,expr>>: <formula_definition_1>
    <<properties,properties>>: <formula_properties_1>
      <<column_type,column_type>>: [ MEASURE | ATTRIBUTE ]
      <<data_type,data_type>>: [ BOOL | VARCHAR | DOUBLE | FLOAT | INT | BIGINT | DATE | DATETIME | TIMESTAMP | TIME ]
      <<aggregation,aggregation>>: [ SUM | COUNT | AVERAGE | MAX | MIN |
                     COUNT_DISTINCT | NONE | STD_DEVIATION | VARIANCE]
  - <<id,id>>: <formula_id_2>
    <<name,name>>: <formula_name_2>
    <<expr,expr>>: <formula_definition_2>
    <<properties,properties>>: <formula_properties_2>
  - <<id,id>>: <formula_id_3>
    <<name,name>>: <formula_name_3>
    <<expr,expr>>: <formula_definition_3>
    <<properties,properties>>: <formula_properties_3>
  <<search_query,search_query>>: <search_query_string>
  <<answer_columns,answer_columns>>:
  - <<id,id>>: <column_id_1>
    <<name,name>>: <column_name_1>
    <<custom_name,custom_name>>: <custom_name_1>
  - <<name,name>>: <column_name_2>
  <<table,table>>:
    <<table_columns,table_columns>>:
    - <<column_id,column_id>>: <column_id_1>
      <<conditional_formatting,conditional_formatting>>:
      - <<range,range>>:
        <<min,min>>: <conditional_formatting_minimum>
        <<max,max>>: <conditional_formatting_maximum>
      - <<rule,rule>>: <conditional_formatting_rule_1>
          <<range,range>>:
            <<min,min>>: <conditional_formatting_minimum>
            <<max,max>>: <conditional_formatting_maximum>
          <<color,color>>: <color_string>
          <<plotAsBand,plotAsBand>>: [ true | false ]
      - <<rule,rule>>: <conditional_formatting_rule_2>
      <<show_headline,show_headline>>: [ true | false ]
      <<headline_aggregation,headline_aggregation>>: <headline_aggregation_string>
    - <<column_id,column_id>>: <column_id_2>
    <<ordered_column_ids,ordered_column_ids>>:
    - <<column_id,column_id>>: <column_id_1>
    - <<column_id,column_id>>: <column_id_2>
    <<client_state,client_state>>: <client_state_string>
  <<chart,chart>>:
    <<type,type>>: <chart_type>
    <<chart_columns,chart_columns>>: <chart_column_1>
    - <<column_id,column_id>>: <column_id_1>
      <<conditional_formatting,conditional_formatting>>:
      - <<rule,rule>>: <conditional_formatting_rule_1>
          <<range,range>>:
            <<min,min>>: <conditional_formatting_minimum>
            <<max,max>>: <conditional_formatting_maximum>
          <<color,color>>: <color_string>
          <<plotAsBand,plotAsBand>>: [ true | false ]
      - <<rule,rule>>: <conditional_formatting_rule_2>
      <<show_headline,show_headline>>: [ true | false ]
      <<headline_aggregation,headline_aggregation>>: <headline_aggregation_string>
    - <<column_id,column_id>>: <column_id_2>
  <<ordered_column_ids,ordered_column_ids>>:
   - <<column_id,column_id>>: <column_id_1>
   - <<column_id,column_id>>: <column_id_2>
   <<client_state,client_state>>: <client_state_string>
  <<chart,chart>>:
   <<type,type>>: <chart_type>
   <<chart_columns,chart_columns>>: <chart_column_1>
   - <<column_id,column_id>>: <column_id_1>
    <<conditional_formatting,conditional_formatting>>:
    - <<rule,rule>>: <conditional_formatting_rule_1>
      <<range,range>>:
        <<min,min>>: <conditional_formatting_minimum>
        <<max,max>>: <conditional_formatting_maximum>
      <<color,color>>: <color_string>
      <<plotAsBand,plotAsBand>>: [ true | false ]
    - <<rule,rule>>: <conditional_formatting_rule_2>
  - <<column_id,column_id>>: <column_id_2>
    <<axis_configs,axis_configs>>: <axis_config_1>
    - x:
      - <<column_id,column_id>>: <column_id_x_axis>
    - y:
      - <<column_id,column_id>>: <column_id_y_axis>
      <<color,color>>:
      - <<column_id,column_id>>: <column_id_color>
    <<axis_configs,axis_configs>>: <axis_config_2>
    <<locked,locked>>: [ true | false ]
    <<client_state,client_state>>: <client_state_string>
  <<display_mode,display_mode>>: <display_mode_string>
....
