== Syntax of the View TML file

The `TML` file for Scriptable Views has a specific syntax.

See the xref:parameters[TML paramters] for details about the keywords used in this example.

You may not see each of these parameters in your own TML files, depending on whether each variable is explicitly defined.
For example, if you did not define any conditional formatting, the `conditional_formatting` variable does not appear.
You can add that variable in the TML file to specify conditional formatting.

NOTE: To reduce ambiguity, you may need to add the optional `fqn` parameter to your TML file when you reference source tables or connections. This is necessary if you have multiple connections or tables with the same name. If you do not add the `fqn` parameter, and the connection or table you reference does not have a unique name, the file import fails.

[subs=+macros]
....

<<view,view>> :
  <<name,name>> : <view_name>
  <<description,description>> :
    This is a multi-line description of the View.
    Description line 2
  <<tables,tables>> :
  - <<name,name>>: <table_name_1>
    <<id,id>> : <optional_table_id>
    <<fqn,fqn>> : <optional_GUID_of_table_name>
  - <<name,name>>: <table_name_2>
  - <<name,name>>: <table_name_n>
  <<joins,joins>> :
  - <<name,name>> : <join_name_1>
    <<source,source>> : <source_table_name>
    <<destination,destination>> : <destination_table_name>
    <<type,type>> : [RIGHT_OUTER | LEFT_OUTER | INNER | OUTER]
    <<on,on>> : <on_string>
    <<is_one_to_one,is_one_to_one>> : [ false | true ]
  <<table_paths,table_paths>> :
  - <<id,id>> : <table_path_name_1>
    <<table,table>> : <table_name_1>
    <<join_path,join_path>> :
    - <<join,join>>:
      - <join_name_1>
      - <join_name_n>
  - <<id,id>>: <table_path_name_2>
    <<table,table>>: <table_name_2>
    <<join_path,join_path>>:
    - <<join,join>>:
      - <join_name_2>
  - <<id,id>>: <table_path_name_n>
    <<table,table>>: <table_name_n>
    <<join_path,join_path>>:
    - <<join,join>>:
      - <join_name_n>
  <<formulas,formulas>> :
  - <<id,id>> : <formula_id_1>
    <<name,name>> : <formula_name_1>
    <<expr,expr>> : <formula_definition_1>
    <<properties,properties>> : <formula_properties_1>
      <<column_type,column_type>> : [ MEASURE | ATTRIBUTE ]
      <<data_type,data_type>> : [ BOOL | VARCHAR | DOUBLE | FLOAT | INT | BIGINT | DATE | DATETIME | TIMESTAMP | TIME ]
      <<aggregation,aggregation>> : [ SUM | COUNT | AVERAGE | MAX | MIN |
                         COUNT_DISTINCT | NONE | STD_DEVIATION | VARIANCE]
  - <<id,id>> : <formula_id_n>
    <<name,name>> : <formula_name_n>
    <<expr,expr>> : <formula_definition_n>
    <<properties,properties>> : <formula_properties_n>
  <<filters,filters>> :
  - column: <filtered_column_name_1>
    <<oper,oper>> : <filter_operator>
    <<values,values>> : <filtered_values>
    - value 1
    - value 2
  - <<column,column>> : <filtered_column_name_n>
  <<view_columns,view_columns>> :
  - <<name,name>> : <column_name_1>
    <<description,description>> : <optional_column_description>
    <<search_output_column,search_output_column>>: <query_column_name>
    <<column_id,column_id>> : <table_path>::<column_id_1>
    <<phrase,phrase>> : <phrase_string_1>
    <<properties,properties>> :
      <<column_type,column_type>> : [ MEASURE | ATTRIBUTE ]
      <<aggregation,aggregation>> : [ SUM | COUNT | AVERAGE | MAX | MIN |
                     COUNT_DISTINCT | NONE | STD_DEVIATION | VARIANCE]
      <<index_type,index_type>> : [ DONT_INDEX | DEFAULT | PREFIX_ONLY |
                    PREFIX_AND_SUBSTRING | PREFIX_AND_WORD_SUBSTRING ]
 	                  <<index_priority,index_priority>> : <index_priority>
      <<synonyms,synonyms>> :
             <synonym_1>
             <synonym_2>
      <<is_attribution_dimension,is_attribution_dimension>> : [true | false]
      <<is_additive,is_additive>> : [ true | false ]
      <<calendar,calendar>> : [ default | calendar_name ]
      <<format_pattern,format_pattern>> : <format_pattern_string>
      <<currency_type,currency_type>> :
        is_browser : true
          OR
        column : <column_name>
          OR
        iso_code : <valid_ISO_code>
      <<is_hidden,is_hidden>> : [ true | false ]
      <<geo_config,geo_config>> :
        latitude : true
          OR
        longitude : true
          OR
        country : true
          OR
        region_name:
        - country : <name_supported_country>
        - region_name : <region_name_in_UI>
      <<spotiq_preference,spotiq_preference>> : <spotiq_preference_string>
      <<search_iq_preferred,search_iq_preferred>> : [ true | false ]
    <<name,name>> : <column_name_2>
    <<description,description>> : <column_description>
    <<search_output_column,search_output_column>>: <query_column_name>
    <<column_id,column_id>> : <table_path>::<column_id_2>
    ...
  <<query,query>> : <query_string>
<<guid,guid>> : <view_guid>
....
