== Parameters of TML files


[width=“100%”,grid=“none”,options="header"]
|===
| a - e | f - o | p - w
a| <<aggregation,aggregation>>

<<answer,answer>>

<<answer_columns,answer_columns>>

<<axis_configs,axis_configs>>

<<calendar,calendar>>

<<chart,chart>>

<<chart_columns,chart_columns>>

<<client_state,client_state>>

<<color,color>>

<<column,column>>

<<columns,columns>>

<<column_id,column_id>>

<<column_type,column_type>>

<<conditional_formatting,conditional_formatting>>

<<connection,connection>>

<<currency_type,currency_type>>

<<custom_name,custom_name>>

<<data_type,data_type>>

<<db,db>>

<<db_column_name,db_column_name>>

<<db_table,db_table>>

<<description,description>>

<<destination,destination>>

<<display_mode,display_mode>>

<<display_headline_column,display_headline_column>>

<<expr,expr>>

a| <<filters,filters>>

<<format_pattern,format_pattern>>

<<formulas,formulas>>

<<fqn,fqn>>

<<geo_config,geo_config>>

<<guid,guid>>

<<headline_aggregation,headline_aggregation>>

<<id,id>>

<<identity,identity>>

<<index_priority,index_priority>>

<<index_type,index_type>>

<<is_additive,is_additive>>

<<is_attribution_dimension,is_attribution_dimension>>

<<is_bypass_rls,is_bypass_rls>>

<<is_hidden,is_hidden>>

<<is_one_to_one,is_one_to_one>>

<<join,join>>

<<join_path,join_path>>

<<join_progressive,join_progressive>>

<<joins,joins>>

<<layout,layout>>

<<locked,locked>>

<<max,max>>

<<min,min>>

<<name,name>>

<<on,on>>

<<oper,oper>>

<<ordered_column_ids,ordered_column_ids>>

a| <<phrase,phrase>>

<<pinboard,pinboard>>

<<properties,properties>>

<<plotAsBand,plotAsBand>>

<<range,range>>

<<rls_rules,rls_rules>>

<<rule,rule>>

<<rules,rules>>

<<schema,schema>>

<<search_query,search_query>>

<<show_headline,show_headline>>

<<size,size>>

<<source,source>>

<<spotiq_preference,spotiq_preference>>

<<synonyms,synonyms>>

<<table,table>>

<<table_columns,table_columns>>

<<table_paths,table_paths>>

<<tables,tables>>

<<type,type>>

<<values,values>>

<<view,view>>

<<view_columns,view_columns>>

<<visualizations,visualizations>>

<<visualization_id,visualization_id>>

<<worksheet,worksheet>>

<<worksheet_columns,worksheet_columns>>
|===

[#aggregation]
aggregation::
  The default aggregation of the Worksheet, View, or table column, or the aggregation of the output for a formula.
+
Aggregation options depend on the data type.
+
Possible values are `SUM`, `COUNT`, `AVERAGE`, `MAX`, `MIN`, `COUNT_DISTINCT`, `NONE`, `STD_DEVIATION`, and `VARIANCE`
+
Default: `SUM`.

[#answer]
answer::
  Top-level container for all object definitions within an Answer.

[#answer_columns]
answer_columns::
  A list of columns generated by the search query.

[#axis_configs]
axis_configs::
  Specifies the columns for each axis on a chart.
+
If you are displaying a column chart with a line chart overlaying it, for example, you would need to specify more than one `axis_config`.

[#calendar]
calendar::
  Specifies the calendar used by a date column.
+
Can be the Gregorian calendar (`default`), a fiscal calendar, or any custom calendar.
+
See xref:custom-calendar.adoc[Set up a custom calendar]

[#chart]
chart::
  Contains configuration for the Answer, if it displays in chart format.

[#chart_columns]
chart_columns::
  A list of columns in the chart.

[#client_state]
client_state::
  A JSON string with more advanced chart and table configuration.

[#color]
color::
  Color to use for conditional formatting or for the columns of an Answer in chart form, in the form of a HEX value.

[#column]
column::
  The id of the column(s) being filtered on. When a Pinboard contains xref:pinboard-filters-linked.adoc[linked filters], or filters that affect visualizations based on more than one Worksheet, the primary filter column appears first in the list of columns in the TML. The linked filter column appears after the primary filter column.

[#columns]
columns::
  The columns in the table.

[#column_id]
column_id::
  The `id` of the Worksheet or View column.
+
For Answers, `column_id` refers to how the column appears in the query.
For example, if you sorted by `Quarter` in your search, from the `Commit Date` column, the `column_id` of the column is `Quarter(Commit Date)`.

[#column_type]
column_type::
  The type of data the column represents.
For a formula, the `column_type` refers to the output of the formula.
+
Possible values: `MEASURE` or `ATTRIBUTE`
+
For Worksheets, the default is: `MEASURE`
+
For formulas, the default depends on the <<data_type,data_type>>.
+
If the data type is `INT` or `BIGINT`, the formula output's `column_type` defaults to `Measure`.
+
If the data type is `BOOL`, `VARCHAR`, `DOUBLE`, `FLOAT`, `DATE`, `DATETIME`, or `TIME`, the formula output's `column_type` defaults to `Attribute`

[#conditional_formatting]
conditional_formatting::
  Conditional formatting for the chart or table of an Answer.

[#connection]
connection::
  A way to identify the external data warehouse connection that the table resides in. To add tables or columns to an external connection, you must specify this parameter.

[#currency_type]
currency_type::
  The source of currency type.
+
One of:
+
  `is_browser : true`;; infer the currency data from the locale of your browser
  `column : <column_name>`;; extracts the currency information from a specified column
  `iso_code : <valid_ISO_code>`;; applies currency based on the ISO code;
+
See https://www.iso.org/iso-4217-currency-codes.html[ISO 4217 Currency Codes^] and xref:data-modeling-patterns.adoc#set-currency-type[Set currency type] for more information.

[#custom_name]
custom_name::
  Optional display name for a column.

[#data_type]
data_type::
  The data type of the formula output or column.
If the data type is `INT` or `BIGINT`, the formula output's `column_type` defaults to `Measure`.
If the data type is `BOOL`, `VARCHAR`, `DOUBLE`, `FLOAT`, `DATE`, `DATETIME`, or `TIME`, the formula output's `column_type` defaults to `Attribute`.
The possible data types are `Boolean`, `Text`, `Date`, `Datetime`, `Time`, `Numeric`, and `Decimal`.

[#db]
db::
  The database that a table resides in.
Note that this is not the same as the data warehouse (Falcon, Amazon Redshift, or Snowflake, for example).

[#db_column_name]
db_column_name::
  The name of the column in the database.
Note that this database is not the same as the data warehouse (Amazon Redshift, or Snowflake, for example).

[#db_column_properties]
db_column_properties::
  The properties of the column in the database. Note that this database is not the same as the data warehouse (Amazon Redshift or Snowflake, for example).

[#db_table]
db_table::
  The name of the table in the database.
Note that this database is not the same as the data warehouse (Falcon, Amazon Redshift, or Snowflake, for example).

[#description]
description::
  The text that describes an object: a `worksheet`, a `worksheet_column`, `answer`, `pinboard`, `view`, `view_column` and so on.

[#destination]
destination::
  The name of the destination table or View for a join.

[#display_mode]
display_mode::
  Determines whether the Answer displays as a chart or a table.
Specify either `CHART_MODE` or `TABLE_MODE`.

[#display_headline_column]
display_headline_column::
  If the visualization is a headline, this parameter specifies the column the headline comes from.

[#excluded_visualizations]
excluded_visualizations::
  A list of visualizations the Pinboard editor chose to exclude from the filter. Only appears when using xref:pinboard-filters-selective.adoc[selective filters].

[#expr]
expr::
  The definition of the formula or row level security (RLS) rule. For RLS rules, the syntax for variables in TML should be the same as the syntax of the variables in the rule on the table.

[#filters]
filters::
  Contains specifications for Pinboard, View, and Worksheet filters.

[#format_pattern]
format_pattern::
  The format pattern string that controls the display of a number, date, or currency column.
+
See xref:data-modeling-patterns.adoc[Set number, date, and currency formats]

[#formulas]
formulas::
  The list of formulas in the Worksheet, View, or Answer.
+
Each formula is identified by `name`, the `expr` (expression), and an optional `id` attribute.

[#fqn]
fqn::
  The table's GUID.
You can find this string of letters and numbers at the end of the URL for that table.
+
For example, in `\https://<company>.thoughtspot.com/#/data/tables/34226aaa-4bcf-4d6b-9045-24cb1e9437cb`, the GUID is `34226aaa-4bcf-4d6b-9045-24cb1e9437cb`.

[#geo_config]
geo_config::
  Specifies the geographic information of a column.
+
One of:
+
`latitude : true`;; for columns that specify the latitude
`longitude : true`;; for columns that specify the longitude
`country : true`;; for columns that specify the country
`region_name`;; for specifying a region in a country
+
Uses two paired parameters:

- `country: __<country_name>__`
- `region_name: __<region_name_in_UI>__`; can be State, Postal Code, District, and so on.

See xref:data-modeling-geo-data.adoc[Add a geographical data setting]

[#guid]
guid::
  The GUID for the Answer, Pinboard, SpotIQ result, Table, Worksheet, or View.
+
You can find this string of letters and numbers at the end of the URL for an object.

[#headline_aggregation]
headline_aggregation::
  Specifies the type of headline aggregation.
+
Can be `COUNT`, `COUNT_DISTINCT`, `SUM`, `MIN`, `MAX`, `AVERAGE`, or `TABLE_AGGR`.

[#id]
id::
  Specifies the id of an object, such as `table_paths`, `formula`.
+
For Answers, `id` refers to how the column appears in the query.
For example, if you sorted by `Quarter` in your search, from the `Commit Date` column, the `id` of the column is `Quarter(Commit Date)`.
+
Refer to xref:search-data-api.adoc#components[Components of a Search Query] to understand syntax.
+
For formulas within Answers, `id` refers to the display name of the formula.
+
If you do not give your formula a name, it appears as 'Untitled Formula'.

[#identity]
identity::
  Specifies the identity of a table, based on its `name`, `id`, and `fqn`.

[#index_priority]
index_priority::
  A value (1-10) that determines where to rank a column's name and values in the search suggestions
+
ThoughtSpot prioritizes columns with higher values.
+
See xref:data-modeling-index.adoc#column-suggestion-priority[Change a column's suggestion priority].

[#index_type]
index_type::
  The indexing option of the Worksheet, View, or table column.
+
Possible values: `DONT_INDEX`, `DEFAULT` (see xref:data-modeling-index.adoc#default-indexing[Understand the default indexing behavior]), `PREFIX_ONLY`, `PREFIX_AND_SUBSTRING`, and `PREFIX_AND_WORD_SUBSTRING`
+
Default: `DEFAULT`
+
See xref:data-modeling-index.adoc#overide-system-default-column[Index Type Values]

[#is_additive]
is_additive::
  Controls extended aggregate options for attribute columns
+
For attribute columns that have a numeric data type (`FLOAT`, `DOUBLE`, or `INTEGER`) or a date data type (`DATE`, `DATETIME`, `TIMESTAMP`, or `TIME`)
+
Possible values: `true` or `false`.
+
Default: `true`.
+
See xref:data-modeling-aggreg-additive.adoc#make-attribute-additive[Making an ATTRIBUTE column ADDITIVE].

[#is_attribution_dimension]
is_attribution_dimension::
  Controls if the column is an attribution dimension.
+
Used in managing chasm traps.
+
Possible values: `true` by default, `false` to designate a column as not producing meaningful attributions across a chasm trap
+
Default: `true`
+
See xref:data-modeling-attributable-dimension.adoc[Change the attribution dimension]

[#is_bypass_rls]
is_bypass_rls::
  Specifies if the worksheet supports bypass of Row-level security (RLS)
+
Possible values: `true` or `false`
+
Default: `false`
+
See xref:security-rls-concept.adoc#exempt-rls[Privileges that allow users to set, or be exempt from, RLS]

[#is_hidden]
is_hidden::
  The visibility of the column
+
Possible values: `true` to hide the column, `false` not to hide the column +
Default: `false`
+
See xref:data-modeling-visibility.adoc[]

[#is_one_to_one]
is_one_to_one::
  Specifies the cardinality of the join. This is an optional parameter.
+
Possible values: `true`, `false`
+
Default: `false`

////
[#is_primary_key]
is_primary_key::
  Determines if the table column is the primary key.
Can be `true` or `false`.

[#is_foreign_key]
is_foreign_key::
  Determines if the table column is the foreign key.
Can be `true` or `false`.
////

[#join]
join::
  Specific join, used in defining higher-level objects, such as table paths
+
Defined as `name` within `joins` definition

[#join_path]
join_path::
  Specification of a composite join as a list of distinct `join` attributes.
+
These `join` attributes list relevant joins, previously defined in the `joins`, by name.
+
Default: `{}`

[#join_progressive]
join_progressive::
  Specifies when to apply joins on a worksheet
+
Possible values: `true` when joins are applied only for tables whose columns are included in the search, and `false` for all possible joins
+
Default: `true`
+
See xref:worksheet-progressive-joins.adoc[How the worksheet join rule works]

[#joins]
joins::
  Contains a list of joins between the tables and Views.
+
If you edit the joins in the Worksheet or View TML file, you are only editing the joins for that specific Worksheet or View. You are not editing the joins at the table level. To modify table-level joins, you must edit the source table's TML file.
+
Each join is identified by `name`, and the additional attributes of `source`, `destination`, `type`, and `is_one_to_one.`

[#joins_with]
joins_with::
  Contains a list of external joins for which this table is the source. +
  Each join is identified by `name` and optional `description`, and the additional attributes of `destination`, `type`, `on`, and `is_one_to_one`.

[#layout]
layout::
  Specifies the Pinboard layout, in the order that a `visualization_id` is listed.

[#locked]
locked::
  The 'automatically select my chart' option in the UI.
If set to `true`, the chart type does not change, even when you add items to the query.

[#max]
max::
  Maximum value for conditional formatting.

[#min]
min::
  Minimum value for conditional formatting.

[#name]
name::
  The name of an object.
Applies to `worksheet`, `table`,`joins`, `formula`, `rls_rules`, `answer`, `pinboard`, `view`, `table`, `connection`, `destination`, and so on.
+
For Answers, `name` refers to how the column appears in the query.
For example, if you sorted by `Quarter` in your search, from the `Commit Date` column, the `name` of the column is `Quarter(Commit Date)`.
Refer to xref:search-data-api.adoc#components[Components of a Search Query] to understand syntax.

[#on]
on::
  The join expression: the relationship definition, or the keys that your tables are joined on. For example, `[sale::Sale_Last Name] = [employee::Employee_Last Name] AND [sale::Sale_First Name] = [employee::Employee_First Name]`. +
  You cannot directly edit a relationship definition. To alter a relationship definition, you must rename the join or create a new join.

[#oper]
oper::
  The operator of the Pinboard, View or Worksheet filter.
Accepted operators are `"in"`, `"not in"`, `"between"`, `=<`, `!=`, `+<=+`, `>=`, `>`, or `<`.

[#ordered_column_ids]
ordered_column_ids::
  A list of columns, in the order they appear in the table.

[#phrase]
phrase::
  Phrase associated with a View column.

[#pinboard]
pinboard::
  Top-level container for all object definitions within the Pinboard or SpotIQ result.

[#properties]
properties::
  The list of properties of a Worksheet, table, or View column, a Worksheet or View itself, or the properties of the output for a formula within an Answer, Worksheet, or View.
+
For Worksheets, Views, and tables, each column can have the following properties, depending on its definition: `column_type`, `aggregation`, `index_type`, `is_hidden`, `index_priority`, `synonyms`, `is_attribution_dimension`, `is_additive`, `calendar`, `format_pattern`, `currency_type`, `geo_config`, `spotiq_preference`, and `search_iq_preferred`.
+
Worksheets and Views themselves can have the following properties that affect query generation: `is_bypass_rls`, and `join_progressive`.
+
For Answers, each formula's output can have the following properties, depending on its definition: `column_type` and `aggregation`.

[#plotAsBand]
plotAsBand::
  Specifies whether to plot the chart conditional formatting like a band on the Visualization.
+
This is the 'fill chart' option in the UI.

[#range]
range::
  Range for the conditional formatting to apply to, with a specified `min` and `max`.

[#rls_rules]
rls_rules::
A container for the full definition of xref:security-rls-concept.adoc[row level security] rules for the table.

[#rule]
rule::
A conditional formatting rule.

[#rules]
rules::
A container for the names and expressions of xref:security-rls-concept.adoc[row level security] rules for the table.

[#schema]
schema::
  The schema that the table is a part of.

[#search_query]
search_query::
  A string that represents the fully disambiguated search query.
Refer to xref:search-data-api.adoc#components[Components of a Search Query] to understand syntax.

[#show_headline]
show_headline::
  Determines whether to show the headline for this column.
`true` shows the headline.

[#size]
size::
  The size of a visualization in a Pinboard.
The options are `EXTRA_SMALL`, `SMALL`, `MEDIUM`, `LARGE`, `LARGE_SMALL`, `MEDIUM_SMALL`, and `EXTRA_LARGE`.

[#source]
source::
  Name of the source table or View for a join.

[#spotiq_preference]
spotiq_preference::
  Specifies whether to include a column in SpotIQ analysis.
Specify `EXCLUDE`, or this property defaults to include the column in SpotIQ Analysis.
+
Refer to xref:spotiq-data-model-preferences.adoc[Set columns to exlude from SpotIQ analyses].

[#synonyms]
synonyms::
  Alternate names for the column, used in search
+
See xref:data-modeling-synonym.adoc[]

[#table]
table::
  Top-level container for all object definitions within the table.
+
Specific table, used in defining higher-level objects, such as table paths.
+
Defined as `name` within `tables` definition.
+
For Answers, this parameter contains configuration for the Answer, if it displays in table format.

[#table_columns]
table_columns::
  The columns in an Answer that is being displayed in table format.

[#table_paths]
table_paths::
  The list of table paths
+
Each table path is identified by the `id`, and additional attributes of `table` and `join_path`.

[#tables]
tables::
  List of tables used by the Worksheet, Answer, or table RLS rule.
+
Each table is identified by `name`.

[#type]
type::
  For Worksheets and Views, this is the join type. This is an optional parameter.
+
Possible values: `LEFT_OUTER` for left outer join, `RIGHT_OUTER` for right outer join, `INNER` for inner join, `OUTER` for full outer join.
+
Default: `INNER`
+
For tables, this is the connection type.
+
Possible values: `Snowflake`, `Google BigQuery`, `Microsoft Azure`, or `Amazon Redshift`.
+
Within the `chart` section of an Answer TML file, this is the chart type.
+
Possible values: `COLUMN`, `BAR`, `LINE`, `PIE`, `SCATTER`, `BUBBLE`, `STACKED_COLUMN`, `AREA`, `PARETO`, `COLUMN`, `GEO_AREA`, `GEO_BUBBLE`, `GEO_HEATMAP`, `GEO_EARTH_BAR`, `GEO_EARTH_AREA`, `GEO_EARTH_GRAPH`, `GEO_EARTH_BUBBLE`, `GEO_EARTH_HEATMAP`, `WATERFALL`, `TREEMAP`, `HEATMAP`, `STACKED_AREA`, `LINE_COLUMN`, `FUNNEL`, `LINE_STACKED_COLUMN`, `PIVOT_TABLE`, `SANKEY`, `GRID_TABLE`, `SPIDER_WEB`, `WHISKER_SCATTER`, `STACKED_BAR`, or `CANDLESTICK`.

[#values]
values::
  The values being filtered (excluded or included) in a Pinboard, View, or Worksheet.

[#view]
view::
  Top-level container for all object definitions within the View.

[#view_columns]
view_columns::
  The list of columns in the View.
+
Each column is identified by `name`, `description`, `column_id`, `phrase` and `properties`.

[#visualizations]
visualizations::
  The visualizations in a Pinboard: tables, charts, and headlines.

[#visualization_id]
visualization_id::
  The id of a visualization.
+
Used to specify the Pinboard's <<layout,layout>>.

[#worksheet]
worksheet::
  Top-level container for all object definitions within the worksheet

[#worksheet_columns]
worksheet_columns::
  The list of columns in the worksheet
+
Each worksheet is identified by `name`, `description`, `column_id`, and `properties`.
