== Syntax of the table TML file

The `TML` file for tables has a specific syntax.

See the <<table-parameters,TML parameters for tables>> for details about the keywords used in this example.

See <<limitations,Limitations of working with TML files>> for more information about actions you can't perform using TML.

You may not see each of these parameters in your own TML files, depending on whether each variable is explicitly defined.
For example, if you did not define any RLS rules, the `rls_rules` variable does not appear.
You can add that variable in the TML file to specify RLS rules.

Refer to xref:tml-joins.adoc[TML for joins] for more information on the functionality and syntax of table joins in TML.

NOTE: To reduce ambiguity, you may need to add the optional `fqn` parameter to your TML file when you reference source tables or connections. This is necessary if you have multiple connections or tables with the same name. If you do not add the `fqn` parameter, and the connection or table you reference does not have a unique name, the file import fails.

[subs=+macros]
....

<<guid,guid>>: <table_guid>
<<table,table>> :
  <<name,name>>: <table_name>
  <<description,description>>: <table_description>
  <<db,db>>: <database_name>
  <<schema,schema>>: <schema_name>
  <<db_table,db_table>>: <database_table_name>
  <<connection,connection>>:
    <<name,name>>: <connection_name>
    <<fqn,fqn>>: <optional_connection_GUID>
  <<columns,columns>>:
  - <<name,name>>: <column_name_1>
    <<db_column_name,db_column_name>>: <database_column_name>
    <<data_type,data_type>>: [ BOOL | VARCHAR | DOUBLE | FLOAT | INT32 | INT64 | DATE | TIME ]
    <<properties,properties>>:
      <<column_type,column_type>>: [ MEASURE | ATTRIBUTE ]
      <<aggregation,aggregation>>: [ SUM | COUNT | AVERAGE | MAX | MIN |
                     COUNT_DISTINCT | NONE | STD_DEVIATION | VARIANCE]
      <<index_type,index_type>>: [ DONT_INDEX | DEFAULT | PREFIX_ONLY |
                    PREFIX_AND_SUBSTRING | PREFIX_AND_WORD_SUBSTRING ]
      <<index_priority,index_priority>>: <index_priority>
      <<synonyms,synonyms>>:
             <synonym_1>
             <synonym_2>
      <<is_attribution_dimension,is_attribution_dimension>>: [true | false]
      <<is_additive,is_additive>>: [ true | false ]
      <<calendar,calendar>>: [ default | calendar_name ]
      <<format_pattern,format_pattern>>: <format_pattern_string>
      <<currency_type,currency_type>>:
        is_browser : true
          OR
        column : <column_name>
          OR
        iso_code : <valid_ISO_code>
      <<is_hidden,is_hidden>>: [ true | false ]
      <<geo_config,geo_config>>:
        latitude : true
          OR
        longitude : true
          OR
        country : true
          OR
        region_name:
        - country : <name_supported_country>
        - region_name : <region_name_in_UI>
          OR
        <<custom_file_guid,custom_file_guid>>: <custom_map_guid>
        <<geometryType,geometryType>>: <custom_map_geometry_type>
      <<spotiq_preference,spotiq_preference>>: <spotiq_preference_string>
    <<db_column_properties,db_column_properties>>:
      <<data_type,data_type>>: [ BOOL | VARCHAR | DOUBLE | FLOAT | INT32 | INT64 | DATE | TIME ]
  - <<name,name>>: <column_name_2>
  - <<name,name>>: <column_name_n>
  <<rls_rules,rls_rules>>:
    <<tables,tables>>:
    - <<name,name>>: <table_name_1>
      <<id,id>>: <optional_table_id>
      <<fqn,fqn>>: <optional_table_GUID>
    - <<name,name>>: <table_name_2>
    - <<name,name>>: <table_name_n>
    <<joins,joins>>:
    - <<name,name>>: <join_name_1>
      <<source,source>>: <source_table_name>
      <<destination,destination>>: <destination_table_name>
      <<type,type>>: [RIGHT_OUTER | LEFT_OUTER | INNER | OUTER]
      <<on,on>>: <join_expression_string>
      <<is_one_to_one,is_one_to_one>>: [ false | true ]
    <<table_paths,table_paths>>:
    - <<id,id>>: <table_path_name_1>
      <<table,table>>: <table_name_1>
      <<join_path,join_path>>:
      - <<join,join>>:
        - <join_name_1>
        - <join_name_n>
   - <<id,id>>: <table_path_name_2>
      <<table,table>>: <table_name_2>
      <<join_path,join_path>>:
      - <<join,join>>:
        - <join_name_2>
   - <<id,id>>: <table_path_name_n>
      <<table,table>>: <table_name_n>
      <<join_path,join_path>>:
      - <<join,join>>:
        - <join_name_n>
    <<rules,rules>>:
    - <<name,name>>: <rls_rule_name_1>
      <<expr,expr>>: <rls_rule_expression_1>
    - <<name,name>>: <rls_rule_name_2>
      <<expr,expr>>: <rls_rule_expression_2>
    - <<name,name>>: <rls_rule_name_n>
      <<expr,expr>>: <rls_rule_expression_n>
  <<joins_with,joins_with>>:
  - <<name,name>>: <join_name_1>
    <<description,description>>: <optional_join_description_1>
    <<destination,destination>>:
      <<name,name>>: <destination_table_name_1>
      <<fqn,fqn>>: <optional_table_guid_1>
    <<on,on>>: <join_expression_string_1>
    <<type,type>>: [RIGHT_OUTER | LEFT_OUTER | INNER | OUTER]
    <<is_one_to_one,is_one_to_one>>: [ false | true ]
  - <<name,name>>: <join_name_2>
  - <<name,name>>: <join_name_n>
....
