ifndef::pendo-links[]
April 2026 [label label-dep]#26.3.0.sw#
endif::[]
ifdef::pendo-links[]
[month-year-whats-new]#April 2026#
[label label-dep-whats-new]#26.3.0.sw#
endif::[]

ifndef::pendo-links[]
NOTE: Features marked as [.badge.badge-update-whats-new-beta-note]#Beta# are off by default. To enable them, contact {support-url}.
endif::[]

ifdef::pendo-links[]
NOTE: Features marked as [.badge.badge-update-whats-new-beta-note]#Beta# are off by default. To enable them, contact {support-url}.
endif::[]

[#primary-26-3-0-sw]

// Business User

ifndef::free-trial-feature[]
ifndef::pendo-links[]
[#26-3-0-kpi-chart]
[discrete]
=== KPI chart settings [.badge.badge-early-access]#Early Access#
endif::[]
ifdef::pendo-links[]
[#26-3-0-kpi-chart]
[discrete]
=== KPI chart settings [.badge.badge-early-access-whats-new]#Early Access#
endif::[]

// Naomi – jira: SCAL-265718. docs jira: SCAL-265719
// PM: Anshul Mehta

ThoughtSpot introduces more granular controls for KPI charts. You can now:

* Decide how missing dates are displayed (as gaps, ignored, or treated as 0).
* Specify whether to show or hide the current date, previous date, and previous value.

* Abbreviate previous month (PM) or previous quarter (PQ).

* Specify whether the measure’s increase or decrease is positive or negative.

To enable this feature, contact your administrator. For more information, see
ifndef::pendo-links[]
xref:chart-kpi.adoc#advanced[KPI charts].
endif::[]
ifdef::pendo-links[]
xref:chart-kpi.adoc#advanced[KPI charts,window=_blank].
endif::[]

endif::free-trial-feature[]

// Analyst



'''
[#secondary-26-3-0-sw]
[discrete]
=== _Other features and enhancements_

// Data engineer


[#26-3-0-sw-personal-access]
[discrete]
=== Personal Access Token (PAT) authentication for Snowflake
// Naomi. jira: SCAL-270846, docs jira: SCAL-270847
// PM: Prayansh
We now support Personal Access Token authentication for Snowflake. For more information, see
ifndef::pendo-links[]
xref:connections-snowflake-add.adoc#pat[Add a Snowflake connection].
endif::[]
ifdef::pendo-links[]
xref:connections-snowflake-add.adoc#pat[Add a Snowflake connection,window=_blank].
endif::[]


[#26-3-0-sw-oauth-client]
[discrete]
=== OAuth Client Credentials for Snowflake
// Naomi. jira: SCAL-262993. docs jira: SCAL-267256.
// PM: Prayansh
We now support OAuth Client Credentials authentication for Snowflake. For more information, see
ifndef::pendo-links[]
xref:connections-snowflake-add.adoc#client-credentials[Add a Snowflake connection] and xref:connections-snowflake-oauth-client.adoc[Snowflake OAuth with Client Credentials].
endif::[]
ifdef::pendo-links[]
xref:connections-snowflake-add.adoc#client-credentials[Add a Snowflake connection,window=_blank] and xref:connections-snowflake-oauth-client.adoc[Snowflake OAuth with Client Credentials,window=_blank].
endif::[]


[#26-3-0-sw-multiple-configurations]
[discrete]
=== Multiple configurations per connection
// Naomi. jira: SCAL-193108. docs jira: SCAL-262244
In addition to
ifndef::pendo-links[]
xref:connections-snowflake-add.adoc#additional-configurations-create[Snowflake],
endif::[]
ifdef::pendo-links[]
xref:connections-snowflake-add.adoc#additional-configurations-create[Snowflake,window=_blank],
endif::[]
we now support multiple configurations for
ifndef::pendo-links[]
xref:connections-databricks-add.adoc#additional-configurations-create[Databricks] and xref:connections-gbq-add.adoc#additional[Google BigQuery].
endif::[]
ifdef::pendo-links[]
xref:connections-databricks-add.adoc#additional-configurations-create[Databricks,window=_blank] and xref:connections-gbq-add.adoc#additional[Google BigQuery,window=_blank].
endif::[]
This feature allows you to allocate separate configurations for different ThoughtSpot users, groups, or processes, eliminating the need to duplicate Liveboards and configure multiple connections, and helping you with cost tracking and governance. You can also use this for your system processes so that you can control and balance the computing load.




ifndef::free-trial-feature[]
ifndef::pendo-links[]
[#26-3-0-sw-column-security]
[discrete]
=== Column security rules [.badge.badge-early-access]#Early Access#
endif::[]
ifdef::pendo-links[]
[#26-3-0-sw-column-security]
[discrete]
=== Column security rules [.badge.badge-early-access-whats-new]#Early Access#
endif::[]
// Naomi – Jira: SCAL-239719. docs jira: SCAL-270725
// PM: Damian.

You can now set column security rules at the table level, and they will automatically be inherited to associated Models. Operational management is simplified as the cluster setting, Strict Object Mode, is not required. In addition, rules are only required for the secured columns rather than all columns in the table. For each column you select as restricted, you can define which group(s) can have access to the column. Users without access will not see the column in search results, or anywhere in the product. To enable this feature, contact your administrator.

For more information, see
ifndef::pendo-links[]
xref:security-data-object.adoc#csr[Column security rules].
endif::[]
ifdef::pendo-links[]
xref:security-data-object.adoc#csr[Column security rules,window=_blank].
endif::[]

endif::free-trial-feature[]


ifndef::free-trial-feature[]
ifndef::pendo-links[]
[#26-3-0-sw-tenant-based]
[discrete]
=== Tenant-based column aliasing [.badge.badge-early-access]#Early Access#
endif::[]
ifdef::pendo-links[]
[#26-3-0-sw-tenant-based]
[discrete]
=== Tenant-based column aliasing [.badge.badge-early-access-whats-new]#Early Access#
endif::[]
// Naomi – Jira ID: SCAL-251015. docs jira: SCAL-273076
// PM: Damian.
Tenant-based column aliasing introduces the capability to define a column name or description based upon the user's membership in a ThoughtSpot Org or group. For example, Client 1 may refer to a column as Region, whilst Client 2 may refer to this as State. This feature is an extension of the language-based aliasing. Data analysts can define these aliases via CSV upload or with TML. This feature is particularly useful for embedded scenarios where the same underlying Model is leveraged across multiple clients.

For more information, see
ifndef::pendo-links[]
xref:column-aliases-tenant.adoc[Tenant-based column aliases].
endif::[]
ifdef::pendo-links[]
xref:column-aliases-tenant.adoc[Tenant-based column aliases,window=_blank].
endif::[]
endif::free-trial-feature[]

[#tse]
[discrete]
=== ThoughtSpot Embedded

Customers licensed to embed ThoughtSpot can use ThoughtSpot Embedded features and the Visual Embed SDK.

To enable ThoughtSpot Embedded on your cluster, contact {support-url}.

For new features and enhancements introduced in this release for ThoughtSpot Embedded, see https://developers.thoughtspot.com/docs/?pageid=whats-new[ThoughtSpot Developer Documentation^].
