ifndef::pendo-links[]
September 2025 [label label-dep]#10.10.0.sw#
endif::[]
ifdef::pendo-links[]
[month-year-whats-new]#September 2025#
[label label-dep-whats-new]#10.10.0.sw#
endif::[]

ifndef::pendo-links[]
NOTE: Features marked as [.badge.badge-update-whats-new-beta-note]#Beta# are off by default. To enable them, contact {support-url}.
endif::[]

ifdef::pendo-links[]
NOTE: Features marked as [.badge.badge-update-whats-new-beta-note]#Beta# are off by default. To enable them, contact {support-url}.
endif::[]

[#primary-10-1-0-sw]

// Business User

ifndef::free-trial-feature[]
ifndef::pendo-links[]
[#10-1-0-sw-redesign]
[discrete]
=== TBD
endif::[]
ifdef::pendo-links[]
[#10-1-0-sw-redesign]
[discrete]
=== TBD
endif::[]
// needs new gif. downplay slightly. homepage is being redesigned based on feedback, here's what's been done/ it's a work in progress. There's going to be a button added at the bottom to add feedback.
// Mark. doc jira: SCAL-151210

TBD

[#tse]
[discrete]
=== ThoughtSpot Embedded

Customers licensed to embed ThoughtSpot can use ThoughtSpot Embedded features and the Visual Embed SDK.

To enable ThoughtSpot Embedded on your cluster, contact {support-url}.

For new features and enhancements introduced in this release for ThoughtSpot Embedded, see https://developers.thoughtspot.com/docs/?pageid=whats-new[ThoughtSpot Developer Documentation^].
