ifndef::pendo-links[]
April 2026 [label label-dep]#26.3.0.sw#
endif::[]
ifdef::pendo-links[]
[month-year-whats-new]#April 2026#
[label label-dep-whats-new]#26.3.0.sw#
endif::[]

ifndef::pendo-links[]
NOTE: Features marked as [.badge.badge-update-whats-new-beta-note]#Beta# are off by default. To enable them, contact {support-url}.
endif::[]

ifdef::pendo-links[]
NOTE: Features marked as [.badge.badge-update-whats-new-beta-note]#Beta# are off by default. To enable them, contact {support-url}.
endif::[]

[#primary-26-3-0-sw]

// Business User

ifndef::free-trial-feature[]
ifndef::pendo-links[]
[#26-3-0-kpi-chart]
[discrete]
=== KPI chart settings [.badge.badge-early-access]#Early Access#
endif::[]
ifdef::pendo-links[]
[#26-3-0-kpi-chart]
[discrete]
=== KPI chart settings [.badge.badge-early-access-whats-new]#Early Access#
endif::[]

// Naomi – jira: SCAL-265718. docs jira: SCAL-265719
// PM: Anshul Mehta

ThoughtSpot introduces more granular controls for KPI charts. You can now:

* Decide how missing dates are displayed (as gaps, ignored, or treated as 0).
* Specify whether to show or hide the current date, previous date, and previous value.

* Abbreviate previous month (PM) or previous quarter (PQ).

* Specify whether the measure’s increase or decrease is positive or negative.

To enable this feature, contact your administrator. For more information, see
ifndef::pendo-links[]
xref:chart-kpi.adoc#advanced[Advanced KPI display options].
endif::[]
ifdef::pendo-links[]
xref:chart-kpi.adoc#advanced[Advanced KPI display options,window=_blank].
endif::[]

endif::free-trial-feature[]


[#26-3-0-sw-improved-chart]
[discrete]
=== Improved chart recommendations
// Mark. jira: SCAL-271016. docs jira: SCAL-271017
// PM: Manan/Anshul

Improved chart recommendations are now generally available (GA) and on by default. When you search, ThoughtSpot can automatically suggest a chart type based on your search query. The following capabilities are improved:

* When you submit a query for the first time, ThoughtSpot analyzes the data and automatically selects the most appropriate chart.
* If you modify an existing query by adding or removing fields, ThoughtSpot retains the existing chart type unless it is forced to change.
* When you drill down into data, ThoughtSpot maintains the current chart type whenever possible.

For more information, see
ifndef::pendo-links[]
xref:charts.adoc#chart-recs[Improved chart recommendations].
endif::[]
ifdef::pendo-links[]
xref:charts.adoc#chart-recs[Improved chart recommendations,window=_blank].
endif::[]

[#26-3-0-sw-dynamic]
[discrete]
=== Enhanced dynamic parameters in charts

// Mark. jira: SCAL-260580. docs jira: SCAL-269159
// PM: Manan? Vaibhav? Is this feature only used in titles?

Enhanced dynamic parameters are now generally available (GA) and on by default. You can use parameters across axis names, column names, answer titles and descriptions to change these elements dynamically based on the parameter value. A parameter used in the title or description always displays the value of the same parameter used in the chart itself.

For more information, see
ifndef::pendo-links[]
xref:charts.adoc#parameters[Parameters in axis and column names of charts and tables].
endif::[]
ifdef::pendo-links[]
xref:charts.adoc#parameters[Parameters in axis and column names of charts and tables,window=_blank].
endif::[]

+++
<div class="border">
<script src="https://fast.wistia.com/player.js" async></script><script src="https://fast.wistia.com/embed/ue13swsxbb.js" async type="module"></script><style>wistia-player[media-id='ue13swsxbb']:not(:defined) { background: center / contain no-repeat url('https://fast.wistia.com/embed/medias/ue13swsxbb/swatch'); display: block; filter: blur(5px); padding-top:59.38%; }</style> <wistia-player media-id="ue13swsxbb" aspect="1.6842105263157894"></wistia-player>
</div>
+++

[#26-3-0-sw-nav-homepage]
[discrete]
//Mary - SCAL-253882
=== New navigation and homepage
ThoughtSpot is excited to announce that our brand-new navigation and homepage experience is now generally available (GA). This change does not apply to users of ThoughtSpot in an embedded environment.

Highlights of the new navigation and homepage:

* Enhanced navigation: commonly accessed features are now in a left-side navigation menu, providing a more intuitive and consistent user experience across all product areas

* Fewer clicks: faster and easier to move between key areas, such as between Liveboards, or from a Model to searching data

* Favorites and Liveboard schedule access: now available with a single click from the homepage navigation menu, allowing you to quickly find your most important data

* Modern homepage: clean, contemporary, and customizable design

The classic navigation and homepage experience is no longer available. For more information, see xref:thoughtspot-homepage.adoc[New homepage and navigation].

[#26-3-0-sw-left-nav-admin]
[discrete]
// Mary - SCAL-286048
=== Admin settings in left navigation
ThoughtSpot introduces a new and improved user experience for Administration. Administration is now part of the left navigation panel.
For more information, see xref:thoughtspot-homepage.adoc[New homepage and navigation].

[#26-3-0-sw-style-group]
[discrete]
//Mary - SCAL-252930
=== Liveboard styling and grouping
Liveboard styling and grouping options are now generally available (GA). Styles can be applied to a Liveboard, a tile, or a group of tiles to improve readability, differentiate specific content, or apply organizational branding guidelines. You can group relevant content together within a Liveboard using grouping.
For more information, see xref:liveboard-grouping-styling.adoc[Liveboard grouping and Liveboard styling].

[#26-3-0-sw-filter-cover]
[discrete]
//Mary - SCAL-246097
=== Include or exclude cover and filter pages from a Liveboard PDF
The option to exclude cover and filter pages from Liveboard PDFs is now generally available (GA). ThoughtSpot Liveboard PDFs include a cover page and filter pages that contain information about the filters applied. You can now use the PDF Options checkboxes to choose to include or exclude these pages when downloading or scheduling a Liveboard PDF. Cover and filter pages can be excluded for a schedule or download by the user. An administrator can also set cover and filter pages to be included or excluded by default in Admin settings under Downloads & Schedules.
For more information, see xref:liveboard-download-pdf.adoc[Download a Liveboard as a PDF].

[#26-3-0-sw-relevant-filters-parameters-LB]
[discrete]
//Mary - SCAL-230770
=== Show only relevant filters and parameters on Liveboards
This feature is now generally available (GA). Filters and parameters that are not relevant to a tab are hidden by default when you open and view a Liveboard. You can choose to view all filters and parameters, including those that are not relevant to the tab, so that you can quickly create a new View or download the Liveboard without needing to switch tabs and apply filters individually.
For more information, see xref:liveboard-filters.adoc[Apply filters to specific visualizations or tabs].

[#26-3-0-sw-reorder-parameters-LB-Answers]
[discrete]
//Mary - SCAL-230636
=== Reorder parameters in Liveboards and Answers
This feature is now generally available (GA). You can now edit a Liveboard or Answer to reorder the parameters along with filters and save your changes. The new order is reflected when anyone opens the Liveboard or Answer.
For more information, see xref:parameters-use.adoc#reorder-parameters[Reorder parameters in Liveboards and Answers].

[#26-3-0-sw-pivot-table]
[discrete]
//Mary - SCAL-226098
=== Pivot table enhancements
The new pivot table chart is now generally available (GA). This new chart has improvements in the following areas:

* Performance
** Faster interaction while expanding rows and columns
** Pagination
* Customization
** Custom sort order support
** Column widths
** Slicing with measures and attributes
** Measure names and values
* UX
** Tooltips
** Legends
** Zebra mode
** Decluttered header space

+
For more information, see xref:chart-pivot-table.adoc#pivot-table-2-0[New Pivot Table charts].

[#26-3-0-sw-custom-sort]
[discrete]
//Mary - SCAL-261454
=== Custom Sort
Custom sorting on Answers is now generally available (GA). You can now define and modify a custom sort order for attributes directly in an Answer. Sort order defined in the Answer overrides the sort order defined in the Model for that particular Answer.
For more information, see xref:answer-custom-sort.adoc[Define or edit a custom sort order for an Answer].

[#26-3-0-sw-LB-download-schedule]
[discrete]
//Mary - SCAL-244743
=== Improved experience for Liveboard downloads and schedules [.badge.badge-early-access]#Early Access#
ThoughtSpot introduces an improved experience for Liveboard downloads and schedules:
When you select Download, you can now select CSV and XLSX in addition to PDF. When you select CSV or XLSX, you can choose which visualizations to download and a bulk download of the Liveboard data is triggered instead of a static image.
When you select Schedule, you can now select specific visualizations to include in the scheduled email attachment as CSV or XLSX files.
To enable this feature, contact your administrator. For more information, see xref:liveboard-download-pdf.adoc[Download a Liveboard and Schedule a Liveboard job].



// Analyst

ifndef::free-trial-feature[]
ifndef::pendo-links[]
[#26-3-0-sw-new-charts-powered]
[discrete]
=== New charts library [.badge.badge-early-access]#Early Access#
endif::[]
ifdef::pendo-links[]
[#26-3-0-sw-new-charts-powered]
[discrete]
=== New charts library [.badge.badge-early-access-whats-new]#Early Access#
endif::[]
// Mark. jira: SCAL-285343. docs jira: SCAL-285344
// PM: Manan
This release significantly upgrades ThoughtSpot visualization capabilities by introducing nine new, powerful native charts — Line, Column, Bar, Area, Line Column, Line Stacked Column, Stacked Column, Stacked Bar, and Stacked Area.

These new charts unlock sophisticated visualizations like faceted, cross-tabbed, multivariate, and bullet charts. They also resolve previous limitations by allowing multiple columns in Line Column charts and slicing by color with multiple measures, while providing deeper granular control over configurations such as tooltips, data labels, and axes.
To enable this feature, contact your administrator.

For more information, see
ifndef::pendo-links[]
xref:charts-library-new.adoc[ThoughtSpot's new charts].
endif::[]
ifdef::pendo-links[]
xref:charts-library-new.adoc[ThoughtSpot's new charts].
endif::[]

endif::free-trial-feature[]

[#26-2-0-cl-chart]
[discrete]
=== New chart settings experience

// Mark. jira: SCAL-264868. docs jira: SCAL-287513
// PM: Manan


The new chart settings experience is now generally available (GA) and on by default. The chart settings panel is completely redesigned with a more intuitive layout and easier access. With over 50 advanced settings available across different chart types, you’ll have pixel-perfect control over every aspect of your visualizations - including data label sizes, colors, font styles, grid lines, tooltips, and more.


For more information, see
ifndef::pendo-links[]
xref:charts-new.adoc[New chart settings experience].
endif::[]
ifdef::pendo-links[]
xref:charts-new.adoc[New chart settings experience,window=_blank].
endif::[]


+++
<div class="border">
<script src="https://fast.wistia.com/player.js" async></script><script src="https://fast.wistia.com/embed/a9cjw2v53d.js" async type="module"></script><style>wistia-player[media-id='a9cjw2v53d']:not(:defined) { background: center / contain no-repeat url('https://fast.wistia.com/embed/medias/a9cjw2v53d/swatch'); display: block; filter: blur(5px); padding-top:71.88%; }</style> <wistia-player media-id="a9cjw2v53d" aspect="1.391304347826087"></wistia-player>
</div>
+++




[#26-3-0-sw-sets]
[discrete]
//Mary - SCAL-174558
=== Column sets
Column sets are now generally available (GA). A column set is a custom group of values from a single column. You can create column sets, which can be used to classify values in a list that you can then reuse across multiple analyses. For example, you can use column sets to define regions with specific countries included or excluded. Column sets are community objects which remain when you navigate away from the Search Data page and can be used by any user with view access to the underlying Model. For more information, see xref:column-sets.adoc[Column sets].

=== Query sets
Query sets are now generally available (GA). You can create query sets, which can be used to classify values in a list that you can then reuse across multiple analyses. A query set is a custom group of values from a collection of objects in your database. Query sets are community objects which remain when you navigate away from the Search Data page and can be used by any user with view access to the underlying Worksheet. For more information, see xref:query-sets.adoc[Query sets].

[#26-3-0-sw-RLS-rule-logic]
[discrete]
//Mary - SCAL-89860
=== Enhanced row-level security (RLS) rule logic
RLS rule logic to support using AND/OR operators with bracket notation is now generally available (GA). You can now define more precise and complex access control policies that accurately reflect your organization’s security requirements without resorting to data modeling solutions with access control list tables. For more information, see xref:security-rls-concept.adoc[How rule-based RLS works].





'''
[#secondary-26-3-0-sw]
[discrete]
=== _Other features and enhancements_

// Data engineer


[#26-3-0-sw-personal-access]
[discrete]
=== Personal Access Token (PAT) authentication for Snowflake
// Naomi. jira: SCAL-270846, docs jira: SCAL-270847
// PM: Prayansh
We now support Personal Access Token authentication for Snowflake. For more information, see
ifndef::pendo-links[]
xref:connections-snowflake-add.adoc#pat[Add a Snowflake connection].
endif::[]
ifdef::pendo-links[]
xref:connections-snowflake-add.adoc#pat[Add a Snowflake connection,window=_blank].
endif::[]


[#26-3-0-sw-oauth-client]
[discrete]
=== OAuth Client Credentials for Snowflake
// Naomi. jira: SCAL-262993. docs jira: SCAL-267256.
// PM: Prayansh
We now support OAuth Client Credentials authentication for Snowflake. For more information, see
ifndef::pendo-links[]
xref:connections-snowflake-add.adoc#client-credentials[Add a Snowflake connection] and xref:connections-snowflake-oauth-client.adoc[Snowflake OAuth with Client Credentials].
endif::[]
ifdef::pendo-links[]
xref:connections-snowflake-add.adoc#client-credentials[Add a Snowflake connection,window=_blank] and xref:connections-snowflake-oauth-client.adoc[Snowflake OAuth with Client Credentials,window=_blank].
endif::[]


[#26-3-0-sw-multiple-configurations]
[discrete]
=== Multiple configurations per connection
// Naomi. jira: SCAL-193108. docs jira: SCAL-262244
In addition to
ifndef::pendo-links[]
xref:connections-snowflake-add.adoc#additional-configurations-create[Snowflake],
endif::[]
ifdef::pendo-links[]
xref:connections-snowflake-add.adoc#additional-configurations-create[Snowflake,window=_blank],
endif::[]
we now support multiple configurations for
ifndef::pendo-links[]
xref:connections-databricks-add.adoc#additional-configurations-create[Databricks] and xref:connections-gbq-add.adoc#additional[Google BigQuery].
endif::[]
ifdef::pendo-links[]
xref:connections-databricks-add.adoc#additional-configurations-create[Databricks,window=_blank] and xref:connections-gbq-add.adoc#additional[Google BigQuery,window=_blank].
endif::[]
This feature allows you to allocate separate configurations for different ThoughtSpot users, groups, or processes, eliminating the need to duplicate Liveboards and configure multiple connections, and helping you with cost tracking and governance. You can also use this for your system processes so that you can control and balance the computing load.


[#26-3-0-csv-upload]
[discrete]
=== CSV upload support for Google BigQuery

// Naomi. jira: SCAL-241441. docs jira: SCAL-278562
// PM: Prayansh
You now have a quick and easy way to complete data loads of files that are not present in your cloud data warehouse. You can now upload a CSV file to your Google BigQuery connection that can be joined to other tables in your connection. To use this feature, go to *Data* > *Utilities*, and click *Upload CSV*. To enable this feature, contact your administrator.

For more information, see
ifndef::pendo-links[]
xref:connections-gbq-csv-upload.adoc[Upload a CSV file to Google BigQuery].
endif::[]
ifdef::pendo-links[]
xref:connections-gbq-csv-upload.adoc[Upload a CSV file to Google BigQuery,window=_blank].
endif::[]

[#26-3-0-sw-databricks-csv]
[discrete]
=== Databricks CSV upload
// Naomi. jira: SCAL-241438 docs jira: SCAL-275547
// PM: Prayansh
You now have a quick and easy way to complete data loads of files that are not present in your cloud data warehouse. You can now upload a CSV file to your Databricks connection that can be joined to other tables in your connection. To use this feature, go to *Data* > *Utilities*, and click *Upload CSV*.

For more information, see
ifndef::pendo-links[]
xref:connections-databricks-csv-upload.adoc[Upload a CSV file to Databricks].
endif::[]
ifdef::pendo-links[]
xref:connections-databricks-csv-upload.adoc[Upload a CSV file to Databricks,window=_blank].
endif::[]





ifndef::free-trial-feature[]
ifndef::pendo-links[]
[#26-3-0-sw-column-security]
[discrete]
=== Column security rules [.badge.badge-early-access]#Early Access#
endif::[]
ifdef::pendo-links[]
[#26-3-0-sw-column-security]
[discrete]
=== Column security rules [.badge.badge-early-access-whats-new]#Early Access#
endif::[]
// Naomi – Jira: SCAL-239719. docs jira: SCAL-270725
// PM: Damian.

You can now set column security rules at the table level, and they will automatically be inherited to associated Models. Operational management is simplified as the cluster setting, Strict Object Mode, is not required. In addition, rules are only required for the secured columns rather than all columns in the table. For each column you select as restricted, you can define which group(s) can have access to the column. Users without access will not see the column in search results, or anywhere in the product. To enable this feature, contact your administrator.

For more information, see
ifndef::pendo-links[]
xref:security-data-object.adoc#csr[Column security rules].
endif::[]
ifdef::pendo-links[]
xref:security-data-object.adoc#csr[Column security rules,window=_blank].
endif::[]

endif::free-trial-feature[]

[#26-3-0-sw-muze-studio]
[discrete]
=== Muze Studio

// Mark. jira: SCAL-271228. docs jira: SCAL-271229
// PM: Manan, Anshul

Muze Studio is now generally available (GA) and on by default. You can create your own charts in ThoughtSpot using the Muze charting library. A developer can create new chart types by writing the code in the code builder. This release introduces a new console window which helps developers quickly identify and resolve issues with real-time feedback on their JavaScript code execution by providing errors and warnings generated during code execution.


For more information, see
ifndef::pendo-links[]
xref:chart-create.adoc[Creating charts with Muze Studio].
endif::[]
ifdef::pendo-links[]
xref:chart-create.adoc[Creating charts with Muze Studio,window=_blank].
endif::[]


ifndef::free-trial-feature[]
ifndef::pendo-links[]
[#26-3-0-sw-liveboards-with]
[discrete]
=== Liveboards with column security rules [.badge.badge-early-access]#Early Access#
endif::[]
ifdef::pendo-links[]
[#26-3-0-sw-liveboards-with]
[discrete]
=== Liveboards with column security rules [.badge.badge-early-access-whats-new]#Early Access#
endif::[]
// Naomi. jira: SCAL-261281. docs jira: SCAL-287514
// PM: Siddhant

We have enhanced the behavior of Liveboards built with column security rules. If users restricted by column security access the Liveboard, they can see and interact with the Liveboard filters and visualizations, but cannot edit the Liveboard as a whole. If such inaccessible columns are used as filters in the Liveboard, the Liveboard will no longer be blocked. Schedules now honor column security rules, and each recipient receives their own report based on their column security rule assignments.
+
For more information, see
ifndef::pendo-links[]
xref:security-data-object.adoc#csr-liveboard[Column security rules on Liveboards].
endif::[]
ifdef::pendo-links[]
xref:security-data-object.adoc#csr-liveboard[Column security rules on Liveboards,window=_blank].
endif::[]
endif::free-trial-feature[]



ifndef::free-trial-feature[]
ifndef::pendo-links[]
[#26-3-0-sw-tenant-based]
[discrete]
=== Tenant-based column aliasing [.badge.badge-early-access]#Early Access#
endif::[]
ifdef::pendo-links[]
[#26-3-0-sw-tenant-based]
[discrete]
=== Tenant-based column aliasing [.badge.badge-early-access-whats-new]#Early Access#
endif::[]
// Naomi – Jira ID: SCAL-251015. docs jira: SCAL-273076
// PM: Damian.
Tenant-based column aliasing introduces the capability to define a column name or description based upon the user's membership in a ThoughtSpot Org or group. For example, Client 1 may refer to a column as Region, whilst Client 2 may refer to this as State. This feature is an extension of the language-based aliasing. Data analysts can define these aliases via CSV upload or with TML. This feature is particularly useful for embedded scenarios where the same underlying Model is leveraged across multiple clients.

For more information, see
ifndef::pendo-links[]
xref:column-aliases-tenant.adoc[Tenant-based column aliases].
endif::[]
ifdef::pendo-links[]
xref:column-aliases-tenant.adoc[Tenant-based column aliases,window=_blank].
endif::[]
endif::free-trial-feature[]

[#tse]
[discrete]
=== ThoughtSpot Embedded

Customers licensed to embed ThoughtSpot can use ThoughtSpot Embedded features and the Visual Embed SDK.

To enable ThoughtSpot Embedded on your cluster, contact {support-url}.

For new features and enhancements introduced in this release for ThoughtSpot Embedded, see https://developers.thoughtspot.com/docs/?pageid=whats-new[ThoughtSpot Developer Documentation^].
