site:
  title: ThoughtSpot Cloud
  url: https://spotter-preview.netlify.app
  start_page: spotter::index.adoc
content:
  sources:
  # embedding empty credentials in the URL disables the Edit this Page link for any page created from this repository
  - url: git@github.com:thoughtspot/thoughtspot-docs.git
    # Cloud docs branches
    branches: ['1.0.0.cp']
    start_path: spotter/
urls:
  html_extension_style: drop
  latest_version_segment_strategy: redirect:to
  latest_version_segment: latest
ui:
  bundle:
    url: ui-bundle/ui2-bundle.zip
  supplemental_files:
  - path: .nojekyll
  - path: ui.yml
    contents: "static_files: [ .nojekyll ]"
    snapshot: true
asciidoc:
  attributes:
    page-company: ThoughtSpot
    tabs: tabs
    support-url: https://community.thoughtspot.com/customers/s/contactsupport[ThoughtSpot Support^]
    seekwell: SeekWell
    latest: 10.1.0.cl
    cl-subscription-agreement: https://www.thoughtspot.com/legal/thoughtspot-cloud-subscription-agreement[subscription agreement^]
  extensions:
    - '@asciidoctor/tabs'

output:
  clean: true
  dir: build
runtime:
  fetch: true
  log:
    level: error