site:
  title: Seekwell
  url: https://preview-seekwell.netlify.app/
  start_page: seekwell::index.adoc
content:
  sources:
  # embedding empty credentials in the URL disables the Edit this Page link for any page created from this repository
  - url: ./
    branches: HEAD
    start_paths:
      - seekwell/
ui:
  bundle:
    url: ui-bundle/ui2-bundle.zip
  supplemental_files:
  - path: .nojekyll
  - path: ui.yml
    contents: "static_files: [ .nojekyll ]"
    snapshot: true
asciidoc:
  attributes:
    software: true
    cloud: false
    tabs: tabs
    seekwell: SeekWell
    support-url: https://community.thoughtspot.com/customers/s/contactsupport[ThoughtSpot Support^]
  extensions:
    - "@djencks/asciidoctor-tabset-block"

output:
  clean: true
  dir: build/
