site:
  title: ThoughtSpot Cloud
  url: https://help-cloud-thoughtspot.netlify.app
  start_page: cloud::index_help.adoc
content:
  sources:
  # embedding empty credentials in the URL disables the Edit this Page link for any page created from this repository
  - url: ./
    branches: HEAD
    start_paths:
      - cloud/
urls:
  latest_version_segment_strategy: redirect:to
  latest_version_segment: latest
  html_extension_style: drop
ui:
  bundle:
    url: ui-bundle/help-ui-bundle.zip
  supplemental_files:
  - path: .nojekyll
  - path: ui.yml
    contents: "static_files: [ .nojekyll ]"
    snapshot: true
asciidoc:
  attributes:
    page-pagination: true # display links to previous/next pages at the bottom of the page
    software: true
    cloud: false
    tabs: tabs
    support-url: https://community.thoughtspot.com/customers/s/contactsupport[ThoughtSpot Support^]
    cl-subscription-agreement: https://www.thoughtspot.com/legal/thoughtspot-cloud-subscription-agreement[subscription agreement^]
  extensions:
    - "@djencks/asciidoctor-tabset-block"

output:
  clean: true
  dir: build
