site:
  title: ThoughtSpot Software
content:
  sources:
  # embedding empty credentials in the URL disables the Edit this Page link for any page created from this repository
  - url: ./
    branches: HEAD
    start_paths:
      - cloud/
ui:
  bundle:
    url: ui-bundle/ui2-bundle.zip
  supplemental_files:
  - path: .nojekyll
  - path: ui.yml
    contents: "static_files: [ .nojekyll ]"
    snapshot: true
asciidoc:
  attributes:
    software: true
    cloud: false
    tabs: tabs
    support-url: https://community.thoughtspot.com/customers/s/contactsupport[ThoughtSpot Support^]
    cl-subscription-agreement: https://www.thoughtspot.com/legal/thoughtspot-cloud-subscription-agreement[subscription agreement^]
  extensions:
    - "@djencks/asciidoctor-tabset-block"

output:
  clean: true
  dir: build/cloud
