site:
  title: ThoughtSpot Cloud
  url: https://ts-9-9-0-cl.vercel.app
content:
  sources:
  # embedding empty credentials in the URL disables the Edit this Page link for any page created from this repository
  - url: git@github.com:thoughtspot/thoughtspot-docs.git
    # Cloud docs branches
    branches: ['9.9.0.cl']
    start_path: cloud/
ui:
  bundle:
    url: ui-bundle/ui2-bundle.zip
  supplemental_files:
  - path: .nojekyll
  - path: ui.yml
    contents: "static_files: [ .nojekyll ]"
    snapshot: true
asciidoc:
  attributes:
    software: true
    cloud: false
    tabs: tabs
    support-url: https://community.thoughtspot.com/customers/s/contactsupport[ThoughtSpot Support^]
    seekwell: SeekWell
    cl-subscription-agreement: https://www.thoughtspot.com/legal/thoughtspot-cloud-subscription-agreement[subscription agreement^]
  extensions:
    - '@asciidoctor/tabs'

output:
  clean: true
  dir: build
