[build.environment]
CI = "true"
NODE_VERSION = "10"
NPM_CONFIG_OPTIONAL = "false"
ANTORA_CACHE_DIR = "node_modules/.cache/antora"

[build]
command = "node_modules/.bin/antora antora-playbook.yml --stacktrace"

[[redirects]]
  from = "https://beta-docs.thoughtspot.com/robots.txt"
  to = "https://beta-docs.thoughtspot.com/cloud/8.8.0.cl-beta/_attachments/robots.txt"
  status = 301
  force = true # COMMENT: ensure that we always redirect
