site:
  title: ThoughtSpot Documentation
  url: https://help-cloud-thoughtspot.netlify.app
  start_page: cloud::index.adoc
content:
  sources:
  # embedding empty credentials in the URL disables the Edit this Page link for any page created from this repository
  - url: ./
    branches: HEAD
    start_paths:
      - cloud/
urls:
  html_extension_style: drop
ui:
  bundle:
    # url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/master/raw/build/ui-bundle.zip?job=bundle-stable
    url: ui-bundle/help-ui-bundle.zip
  supplemental_files:
  - path: .nojekyll
  - path: ui.yml
    contents: "static_files: [ .nojekyll ]"
    snapshot: true
asciidoc:
  attributes:
    #software: true
    #cloud: false
    help:
    page-company: ThoughtSpot
    tabs: tabs
    support-url: https://community.thoughtspot.com/customers/s/contactsupport[ThoughtSpot Support^]
    seekwell: SeekWell
    cl-subscription-agreement: https://www.thoughtspot.com/legal/thoughtspot-cloud-subscription-agreement[subscription agreement^]
  extensions:
  - ./lib/asciidoctor-performance-patch.js
  - "@djencks/asciidoctor-tabset-block"
output:
  clean: true
  dir: build/
runtime:
  fetch: true
  log:
    level: error
