= ThoughtSpot {product} Documentation
:page-layout: home-branch-blank

++++
<style>
.home h2, .home h3, .home h4, .home h5, .home h6, .doc h1, .doc h2, .doc h3, .doc h4, .doc h5, .doc h6 {
    color: #444;
    font-weight: 500;
    font-family: Optimo-Plain,sans-serif;
    -webkit-hyphens: none;
    -ms-hyphens: none;
    hyphens: none;
    line-height: 1.3;
    margin: 1rem 0 0;
}

h2#_whats_new_in_thoughtspot_cloud {
    font-weight: 450;
    font-size: larger;
}

h3#_previous_releases_cloud {
    font-weight: 300;
    font-size: medium;
}

.dlist dt {
    font-style: normal !important;
}

b, dt, strong, th {
    font-weight: 500;
    font-size: .84444rem;
    line-height: 1.6;
}

.home .box-wide p {
    margin: medium;
    color: #444;
    font-size: .84444rem;
    line-height: 1.6;
}

.box-wide-columns {
    width: 82%;
    margin: 0 auto;
    padding-right: 25px;
}

td {
    font-size: 13px;
    padding: 10px;
}

.modal-inner {
    top: 20px !important;
    border-radius: 8px !important;
    max-width: 90% !important;
    max-height: 85% !important;
}

.mode-image {
    width: 80px !important;
    margin-top: -15px !important;
    margin-bottom: 1px !important;
}

@media only screen and (min-width: 1216px) {
    .box-button-columns {
        display: -webkit-box;
        display: -ms-flexbox;
        display: flex;
        -ms-flex-wrap: wrap;
        flex-wrap: wrap;
        /* margin: 0 auto; */
        margin-left: -18px !important;
        width: 100% !important;
    }
}

@media only screen and (min-width: 1024px) {
    .box-button-columns {
        display: -webkit-box;
        display: -ms-flexbox;
        display: flex;
        -ms-flex-wrap: wrap;
        flex-wrap: wrap;
        width: 100% !important;
    }
}
</style>
++++

++++
<!-- first row -->
<div class="box-button-columns">
    <div class="box-button"><a href="https://analyst-studio-preview.netlify.app/studio/latest/studio-get-started" class="panel-2">
      <span>
    <h2>
      Get Started
    </h2>
    </span>
    </a></div>
    <div class="box-button"><a href="https://analyst-studio-preview.netlify.app/studio/latest/studio-navigate-and-organize-content" class = "panel-2">
    <h2>
      Navigate and organize content
    </h2>
    </a></div>
  <div class="box-button"><a href="https://analyst-studio-preview.netlify.app/studio/latest/studio-connect-your-database" class="panel-2">
      <span>
    <h2>
      Connect your database
    </h2>
   </span>
    </a></div>
  <div class="box-button"><a href="https://analyst-studio-preview.netlify.app/studio/latest/studio-query-and-analyze-data" class="panel-2">
      <span>
    <h2>
      Query and analyze data
    </h2>
    </span>
    </a></div>
 </div>
<!-- second row -->
<div class="box-button-columns">
    <div class="box-button"><a href="https://analyst-studio-preview.netlify.app/studio/latest/studio-visualize-and-present-data" class="panel-2">
      <span>
    <h2>
      Visualize and present data
    </h2>
    </span>
    </a></div>
    <div class="box-button"><a href="https://analyst-studio-preview.netlify.app/studio/latest/studio-explore-and-share-data" class = "panel-2">
    <h2>
      Explore and share data
    </h2>
    </a></div>


  <div class="box-button"><a href="https://analyst-studio-preview.netlify.app/studio/latest/studio-integrations" class="panel-2">
      <span>
    <h2>
      Integrations
    </h2>
    </span>
    </a></div>
 </div>
<!-- third row -->
<div class="box-button-columns">
    <div class="box-button"><a href="https://analyst-studio-preview.netlify.app/studio/latest/studio-administration" class="panel-2">
      <span>
    <h2>
      Administration
    </h2>
    </span>
    </a></div>
    <div class="box-button"><a href = "https://analyst-studio-preview.netlify.app/studio/latest/studio-api" class = "panel-2">
    <h2>
      API
    </h2>
    </a></div>
  <div class="box-button"><a href="https://analyst-studio-preview.netlify.app/studio/latest/studio-faqs" class="panel-2">
      <span>
    <h2>
      FAQs
    </h2>
   </span>
    </a></div>
  <div class="box-button"><a href="https://analyst-studio-preview.netlify.app/studio/latest/studio-contact-us" class="panel-2">
      <span>
    <h2>
      Contact us
    </h2>
    </span>
    </a></div>
 </div>
++++

