= Contact Us
:categories: ["Contact us"]
:categories_weight: 1
:date: 2019-06-07
:description: How to get in touch with Analyst Studio
:ogdescription: How to get in touch with Analyst Studio
:path: /articles/contact-us
:product: Analyst Studio

Have a question that's not answered here, or looking for assistance with an analytics challenge?
{support-url} is available to help.

== Status page

We continuously monitor the status of our site and all related services.
In the event of a service interruption, an update will be posted on our link:https://status.modeanalytics.com/[status page].
If you are experiencing problems and do not see a notice posted, please let us know via Live Chat or contact {support-url}.

////
== Email

Contact our Customer Support team via email at link:mailto:support@mode.com[support@mode.com].
We review all emails and will respond as soon as possible!
////

== Live chat
//+++<flag-icon>++++++</flag-icon>+++

You can chat directly with our team of Customer Support Engineers and Analysts at any time during {product}'s business hours:

*Business Hours*: Monday-Friday, 5am to 6pm pacific (excluding major US holidays)

To access live chat anywhere in {product}:

. Click on the *?* circle in the upper right corner of the window.
. Click *Chat with us*.

During business hours, our Customer Support team aims to respond to questions submitted via live chat within an hour.
If you send us a message outside of our business hours, we'll respond as soon as possible the next business day.

TIP: Did you try to open live chat and got sent here instead? You may have a pop-up blocker enabled.
