= Overview of security features
:last_updated: 11/15/2019
:permalink: /:collection/:path.html
:sidebar: mydoc_sidebar

Learn about ThoughtSpot's security features.

There are several aspects of security, including access and permissions, data security and privacy, and security from an IT perspective.

* xref:audit-logs.adoc[System Security] refers to audit logs and security policies.
* xref:sharing-security-overview.adoc[Data Security] refers to which users can see which data in the ThoughtSpot application, and includes:
 ** xref:about-users-groups.adoc[Users and Groups]
 ** xref:about-users-groups.adoc#privileges-and-groups[Privileges]
 ** xref:share-source-tables.adoc[Table and columns sharing]
 ** xref:about-row-security.adoc[Row level security]
 ** xref:share-worksheets.adoc[Worksheet sharing]
 ** xref:share-pinboards.adoc[Pinboard sharing]
* Network Security refers to ports for external traffic and traffic within the cluster.
Some ports must remain open for handling network requests from outside the ThoughtSpot instance.
To see a list of network ports that must remain open to outside traffic, and for inter-cluster communication, review the information in xref:ports.adoc[Network ports].
