= Understanding views
:last_updated: 11/16/2020

If you want to perform a search on top of another search, try saving your search as a View. Then, you can use the saved View as a data source for a new search.

NOTE: Only users with the *Can administrate ThoughtSpot* or the *Can manage data* privilege can create Views and link them.

IMPORTANT: While you cannot apply row-level security (RLS) to a view, you can apply row-level security to the view's underlying table in order to restrict the data shown when searching on the view.

== Introduction to views

You may have noticed that when you do a search on a data source, ThoughtSpot is only able to aggregate one column by one other column.
Because of this, you may come across searches you can't do in one pass, because they are essentially nested queries.
But you can create the equivalent of nested queries using a View, which is an answer that you have saved for the purpose of building other searches on top of it.

You can use a View just like any other data source.
You can even link it to other sources by defining a relationship.
When you save an answer as a View, and then use it as a source in a new search, it is similar to doing a nested query in SQL, only much easier to create.

== View workflow

Suppose you created a search on the sales fact table that shows the top ten Sales Reps by revenue, for the first quarter.
Then you want to do some further investigation on that subset of data, such as ranking them by how much they discounted a specific product based on data from the orders fact table.
Unless you save your first answer as a View, and then search over that View, you cannot get your answers.

Here are the high-level steps for creating and using Views:

. Create the first search, and xref:create-aggregated-worksheet.adoc[save it as a View].
. xref:create-new-relationship.adoc[Create relationships] or xref:constraints.adoc[define joins] to connect your View with any other data source.
. Create a new search that includes your View and the other sources linked with it.
. We recommend that you xref:about-worksheets.adoc[create a new Worksheet] that includes all these data sources.
+
Creating a Worksheet makes it easier for people to search using your View and any related tables.

== Best practices for using views

* When creating Views, keep in mind the sizing recommendations for Worksheets, for the final Worksheet that you plan to use in modeling your data.
* To be able to join a View with a base table, your installation must be configured to allow this.
The View cannot have more than 5 tables, and the number of rows in the View cannot exceed 10 million rows.
* The order of the objects being linked (joined) matters, because joins are directional.
The table or View with the foreign key must be in the first (left) position.
The table or View with the primary key must be in the second (right) position.
* For best performance, Views should have 50 or fewer columns, and no more than 10 million rows.
If your View has more than 10 million rows, consider materializing it.
If your View has more than 40 million rows, consider sharding it.
* To improve performance, you can materialize the Views.
* You can use an ETL (extract, transform, load) processes to circumvent these limitations.

'''
> **Related information**
>
> * xref:more-example-scenarios.adoc[More view scenario examples]
> * xref:create-aggregated-worksheet.adoc[Save a search as a view]
> * xref:constraints.adoc[Constraints]
> * xref:materialized-views.adoc[Materialized views]
