= Manage and create snapshots
:last_updated: 7/28/2020
:linkattrs:
:experimental:

A snapshot is a point-in-time image of your running cluster. You can use a snapshot to restore the cluster to a specific point in time. Create and manage snapshots from the Admin Console.


[#manual-snapshot]
== About manual snapshots

You must <<admin-portal-create,create a snapshot>> before making any changes to your cluster's environment, loading a large amount of data, or changing the structure of a table.
ThoughtSpot supports up to 20 manual snapshots.
You must clear them to create new snapshots.
You can delete a snapshot <<admin-portal-delete,from the Admin Console>>.

ThughtSpot generates a snapshot in approximately 20 seconds, depending on the size of the cluster.
To restore from a snapshot, contact https://community.thoughtspot.com/customers/s/contactsupport[ThoughtSpot Support^].

NOTE: During an upgrade, all snapshots from the previous version of ThoughtSpot become manual snapshots.

include::partial$snapshot-manage.adoc[]
