= Set the relay host for SMTP (email)
:last_updated: 8/13/2020
:linkattrs:
:page-aliases: /admin/admin-portal/smtp-configure.adoc
:experimental:

ThoughtSpot uses emails to send critical notifications to ThoughtSpot Support. A relay host for SMTP traffic routes the alert and notification emails coming from ThoughtSpot through an SMTP email server.

'''
> **ThoughtSpot Training**
>
> * For best results with emails and alerts, we recommend the following ThoughtSpot U course: https://training.thoughtspot.com/emails-alerts[Email and Alert Setup^].
> * See other training resources at https://training.thoughtspot.com/[ThoughtSpot U^].

'''

include::partial$smtp-configure.adoc[]

== Configure an email to receive alerts

ThoughtSpot sends alerts to the email address specified during installation.
If you do not specify an email address, you do not receive any alerts.
To add an email to receive alerts, `ssh` into your cluster from the command line and issue the following command.

NOTE: Add the ThoughtSpot Support alert email, `prod-alerts@thoughtspot.com`, to allow xref:support-contact.adoc[ThoughtSpot Support] to receive alerts. xref:support-contact.adoc[ThoughtSpot Support] monitors these alerts to ensure your cluster's health.
Do not add this email to POC or demo environments.

 $ tscli monitoring set-config --email <prod-alerts@thoughtspot.com>,<your_email>

To send to multiple emails, provide a comma-separated list with no spaces.

== Verify the relay with an email

Check if the email settings are working properly by using this procedure.

. Log in to the Linux shell using SSH.
. Try sending an email to yourself by issuing:

 $ echo | mail -s Hello <your_email>

. If you receive the email at the address(es) you supplied, email is working correctly.
