= Configure SSL
:experimental:
:last_updated: 01/10/2021
:page-aliases: /admin/admin-portal/ssl-configure.adoc, /admin/setup/SSL-config.adoc
:linkattrs:

Secure socket layers (SSL) provide authentication and data security when sending data to and from ThoughtSpot.

You can use your own SSL certificate to secure ThoughtSpot HTTP(S) traffic.

'''
> **ThoughtSpot Training**
>
> * For best resutls with authentication and security, we recommend the following ThoughtSpot U course: https://training.thoughtspot.com/authentication-security/610523[Nginx SSL^].
> * See other training resources at https://training.thoughtspot.com/[ThoughtSpot U^].

'''

[#ssl-about]
== About SSL

To enable SSL for the ThoughtSpot web service, you must provide your organization's SSL certificate for the ThoughtSpot service URL.
If you do not have this certificate, you have the following options:

* Check with your IT department to see if they have an SSL certificate you can use.
* Obtain the certificate from an issuing authority.
* Use the default SSL certificate on the ThoughtSpot nodes.
* Disable SSL from the Admin Console: Under *SSL*, select menu:Configure[Disable] or menu:Edit[Disable].

ThoughtSpot supports a wide variety of SSL types.

[#ssl-ports]
== Required ports

To use the ThoughtSpot web service securely, ensure that TCP port 443 is open to accommodate incoming connections to ThoughtSpot nodes and clusters.

[#ssl-configure]
== Prerequisites

To add SSL and enable HTTPS in ThoughtSpot, you must generate the <<csr,Certificate Signing Request (CSR)>> and obtain the <<ssl-certificate-chain,SSL certificate chain>> and the <<key,private key>>.

[#csr]
=== Certificate Signing Request

When you generate a CSR, you handle sensitive data.
Therefore, ThoughtSpot recommends that its customers generate their own CSRs.

You can generate a CSR in several ways.
Most often, you generate a CSR and a new private key <<csr-new-private-key,at the same time>>.
If you already have a private key, <<csr-existing-private-key,use it to generate a CSR>>.

[#csr-new-private-key]
Follow these steps to generate a CSR and a private key.
You need a computer you can run Linux commands on, and a recent version of _openssl_.

. `ssh` into one of your ThoughtSpot nodes.
+
[source]
----
 ssh admin@<node_IP>
----

. Run the command to generate a CSR and private key pair:
+
[source]
----
 openssl req -new -newkey rsa:2048 -nodes -out csr.pem -keyout pk.key[-subj "/key1=value1/key2=value with space/
----
+
Note the following parameters:

 ** ThoughtSpot supports a 2048 or 4096 bit key.
 ** `subj`: a common subject.
Logically equivalent to the `-dname` property of _keytool_.
Alternatively, you can skip this flag, and `openssl` prompts you to enter this information interactively.
 ** Optionally, run `add-multivalue-rdn` to allow multiple values to be set for the same key.
 ** Run `man req` for more details.

[#csr-existing-private-key]
If you already have a private key, you can use it to generate a CSR.
Follow these steps to generate a CSR with an existing private key:

. `ssh` into one of your ThoughtSpot nodes.
+
[source]
----
 ssh admin@<node_IP>
----

. Run the command to generate a CSR and private key pair:
+
[source]
----
 openssl req -new -key <private_key_file> -nodes -out csr.pem[-subj "/key1=value1/key2=value with space/
----
+
Specify the existing private key file.
Refer to the parameters listed above.

[#ssl-certificate-chain]
=== SSL certificate chain

The SSL certificate chain must be in PEM format, which is an `X.509v3` file that contains ASCII (Base64) armored data, packed between `BEGIN` and `END` directives.
The certificate chain may contain a series of certificates, with the root certificate at the bottom and user-facing, while the ThoughtSpot-specific SSL certificate is at the top.

[#key]
=== Private key

The private key must also be in compatible PEM format.
It cannot be password-protected, or passphrase-protected.

NOTE: Do not use a passphrase when creating certificates with ThoughtSpot.

If you are prompted to specify a passphrase, first check if it exists by invoking the following command:
[source]
----
openssl rsa -check -in pk.key`
----

If the answer is 'yes', you must remove the passphrase first, and then proceed to use the private key with ThoughtSpot.

include::partial$ssl-configure.adoc[]

[#config-load-balancer]
=== Configuration string for load balancers

When enabling SSL support on a load balancer's server-side SSL client profile, make sure to add support for the following ciphers to ensure compatibility between the load balancer and ThoughtSpot.

The following ciphers are currently supported:
[source]
----
|   TLSv1.2:
|     ciphers:
|       TLS_DHE_RSA_WITH_AES_128_GCM_SHA256 - strong
|       TLS_DHE_RSA_WITH_AES_256_CBC_SHA - strong
|       TLS_DHE_RSA_WITH_AES_256_CBC_SHA256 - strong
|       TLS_DHE_RSA_WITH_AES_256_GCM_SHA384 - strong
|       TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256 - strong
|       TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA - strong
|       TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384 - strong
|       TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384 - strong
|     compressors:
|       NULL
|_  least strength: strong
----

The cipher string would be as follows:
[source]
----
EECDH+AESGCM:EDH+AESGCM:AES256+EECDH:AES256+EDH
----

You can retrieve these from the ThoughtSpot web server (not against the load balancer) by running the following command on any ThoughtSpot node:
[source]
----
nmap --script ssl-enum-ciphers -p 443 <ThoughtSpot_node_IP_address>
----

You must ensure that your load balancer supports these ciphers.
If your load balancer cannot support these ciphers, contact xref:support-contact.adoc[ThoughtSpot Support].

[#ssl-configure-test]
== Test the SSL certificate

To test if the certificate is installed correctly, see xref:admin-sign-in.adoc#tsadmin[Sign in to the ThoughtSpot application].
