= Admin Console for Orgs
:last_updated: 9/26/2022
:linkattrs:
:experimental:
:description: Learn how the Admin Console for multi-tenant environments can help you manage users, groups, security, authentication, and much more.

The Admin Console provides you with an intuitive, user-friendly interface to accomplish most of the necessary tasks for administering ThoughtSpot in a multi-tenant environment.

Navigate to the Admin Console by selecting *Admin* from the top navigation bar.

[NOTE]
====
This article is an overview for the Admin Console if your company uses the xref:orgs-overview.adoc[Orgs] feature for multi-tenancy in ThoughtSpot. This feature allows a ThoughtSpot instance to be logically partitioned into multiple tenant-specific environments called *Orgs*. With Orgs, each tenant’s data is isolated and protected with access control, and is invisible to the other tenants that share the same ThoughtSpot application instance. If you have an Org switcher to the left of the help icon in the top navigation bar, your company is using Orgs.

If you do not have an Org switcher between the help icon and the *Search answers and Liveboards* search box, your company is *_not_* using Orgs. Refer to xref:it-ops.adoc[].
====

== Cluster administrators and Org administrators

include::partial$org-admin.adoc[]

The Admin Console looks different, depending on whether you are a cluster administrator or an Org administrator.

When a cluster administrator is in the Primary Org, they can see two columns in the side navigation bar of the Admin Console: *All orgs* and *Primary org*.

The Org administrator can only see one column in the side navigation bar.

== Admin Console for cluster administrators
Cluster administrators can complete the following tasks in the Primary Org's Admin Console, under *All orgs*. Users can only manage these settings at a cluster level. These settings _cannot_ be managed separately for each Org.

*Manage Orgs*

* Create, edit, and delete Orgs. See xref:admin-console-orgs-page.adoc[Create, edit, and delete Orgs].

*Manage users*

* xref:admin-portal-users-orgs.adoc[Manage ThoughtSpot users:] Create, edit, or delete users. Add users to or remove users from Orgs.
+
You should only use the *All orgs > Users* section of the Admin Console to add users to multiple Orgs. Use the individual Org's *Admin Console > Users* section to add users to individual Orgs, and to add users to groups.

*Configure authentication*

* xref:authentication-local.adoc[Manage local authentication:] Enable or disable ThoughtSpot’s local authentication.

* xref:authentication-integration.adoc[Configure SAML authentication:] Integrate with SAML for single sign-on (SSO) authentication.

*Application settings: Search and SpotIQ settings, Onboarding and email settings*

* xref:search-spotiq-settings.adoc[Manage search and SpotIQ settings:] Enable, disable, and configure the following features: SpotIQ, column indexing, summaries, the new answer, SpotIQ, and Liveboard experiences, and the footer for downloaded answers and Liveboards.

* xref:onboarding-email-settings.adoc[Manage email and onboarding settings:] Customize welcome emails, scheduled emails, and the workflow that allows users to sign up for ThoughtSpot from the login page.

*Application and menu customization*

* xref:style-customization.adoc[Customize application style:] Change the overall style of your ThoughtSpot interface: logo, colors, fonts, and footer text.

*Monitor system*

* xref:user-adoption.adoc[View User Adoption Liveboard:] View and explore visualizations about how your ThoughtSpot users are interacting with ThoughtSpot, and how your user adoption is changing over time on the User Adoption Liveboard.

* xref:performance-tracking.adoc[View Performance Tracking Liveboard:] View and explore visualizations about your ThoughtSpot cluster’s performance on the Performance Tracking Liveboard.



== Admin Console for Org administrators
Org administrators can complete the following tasks in the Admin Console. These settings _can_ be managed separately for each Org.

* xref:admin-portal-users-orgs.adoc[Manage ThoughtSpot users:] Create, edit, or delete users in a specific Org. Add users to or remove users from groups in a specific Org.

* xref:admin-portal-groups-orgs.adoc[Manage ThoughtSpot groups:] Create, edit, or delete groups in a specific Org.
