= Packages installed with ThoughtSpot for Amazon Linux 2
:last_updated: 01/04/2020
:linkattrs:
:experimental:
:description: View the packages necessary to deploy ThoughtSpot with Amazon Linux 2.

View the packages necessary to deploy ThoughtSpot with Amazon Linux 2.

ThoughtSpot also uses the third-party software packages listed in xref:third-party.adoc[].

To successfully deploy ThoughtSpot in your organization, you must have the following packages on each node of your ThoughtSpot cluster: yum, python 3, and R. ThoughtSpot does not install the R packages if you define the xref:al2-install-online.adoc#skip_r[skip_r] flag in the Ansible playbook.
When the Ansible playbook runs, it automatically installs them.

[#yum]
[#pip3]
[#r]
[tabset]
====
Yum RPM packages;;
+
--
Download: link:{attachmentsdir}/yum-rpm-packages.csv[Yum RPM package list].

include::partial$packages/yum-rpm-packages.adoc[]
--
Python 3 packages;;
+
--
Download: link:{attachmentsdir}/pip3-rpm-packages.csv[Python3 RPM package list].
include::partial$packages/pip3-rpm-packages.adoc[]
--
R packages;;
+
ThoughtSpot does not install the R packages if you define the xref:al2-install-online.adoc#skip_r[skip_r] flag in the Ansible playbook.
+
--
Download: link:{attachmentsdir}/r-rpm-packages.csv[R RPM package list].
include::partial$packages/r-rpm-packages.adoc[]
--
====

'''
> **Related information**
>
> * xref:al2-prerequisites.adoc[Amazon Linux 2 prerequisites]
> * xref:al2-ts-artifacts.adoc[ThoughtSpot deployment artifacts for Amazon Linux 2]
> * xref:al2-install-online.adoc[Online Amazon Linux 2 install]
> * xref:al2-install-offline.adoc[Offline Amazon Linux 2 install]
> * xref:al2-upgrade.adoc[Amazon Linux 2 upgrade]
> * xref:al2-add-node.adoc[Adding new nodes to clusters in Amazon Linux 2]

