= Packages installed with ThoughtSpot for Amazon Linux 2
:last_updated: 6/11/2020

View the packages necessary to deploy ThoughtSpot with Amazon Linux 2.

To successfully deploy ThoughtSpot in your organization, you must have the following packages on each node of your ThoughtSpot cluster: yum, python 3, and R.
When the Ansible playbook runs, it automatically installs them.

ThoughtSpot works with the latest version of each package;
see the minimum supported version.
[#yum]
[#pip2]
[#pip3]
+++ <details><summary> +++
YUM RPM packages:
+++ </summary><div>
<table>
<tr><th>Yum Package</th script=""><th>Minimum version</th></tr>
<tr><td><code>aide</code></td><td>0.15.1-13.el7</td></tr>
<tr><td><code>alsa-lib</code></td><td>1.1.8-1.el7</td></tr>
<tr><td><code>amcheck_next95</code></td><td>1.5-1.rhel7</td></tr>
<tr><td><code>arp-scan</code></td><td>1.9.2-1.el7</td></tr>
<tr><td><code>atk</code></td><td>2.28.1-2.el7</td></tr>
<tr><td><code>atop</code></td><td>2.4.0-4.el7</td></tr>
<tr><td><code>azure-cli</code></td><td>2.7.0-1.el7</td></tr>
<tr><td><code>bash</code></td><td>4.2.46-34.el7</td></tr>
<tr><td><code>bind-utils</code></td><td>32:9.11.4-16.P2.el7_8.6</td></tr>
<tr><td><code>btrfs-progs</code></td><td>4.9.1-1.el7</td></tr>
<tr><td><code>chromium</code></td><td>81.0.4044.138-1.el7</td></tr>
<tr><td><code>cifs-utils</code></td><td>6.2-10.el7</td></tr>
<tr><td><code>cloud-init</code></td><td>18.5-6.el7</td></tr>
<tr><td><code>coreutils</code></td><td>8.22-24.el7</td></tr>
<tr><td><code>cryptsetup</code></td><td>2.0.3-6.el7</td></tr>
<tr><td><code>cups-libs</code></td><td>1:1.6.3-43.el7</td></tr>
<tr><td><code>curl</code></td><td>7.29.0-57.el7</td></tr>
<tr><td><code>cyrus-sasl-devel</code></td><td>2.1.26-23.el7</td></tr>
<tr><td><code>cyrus-sasl-plain</code></td><td>2.1.26-23.el7</td></tr>
<tr><td><code>cyrus-sasl</code></td><td>2.1.26-23.el7</td></tr>
<tr><td><code>dkms</code></td><td>2.8.1-4.20200214git5ca628c.el7</td></tr>
<tr><td><code>dmidecode</code></td><td>1:3.2-3.el7</td></tr>
<tr><td><code>dos2unix</code></td><td>6.0.3-7.el7</td></tr>
<tr><td><code>dracut</code></td><td>033-568.el7</td></tr>
<tr><td><code>dstat</code></td><td>0.7.2-12.el7</td></tr>
<tr><td><code>e2fsprogs</code></td><td>1.42.9-17.el7</td></tr>
<tr><td><code>ethtool</code></td><td>2:4.8-10.el7</td></tr>
<tr><td><code>exfat-utils</code></td><td>1.2.7-1.el7.nux</td></tr>
<tr><td><code>fio</code></td><td>3.7-1.el7</td></tr>
<tr><td><code>ftp</code></td><td>0.17-67.el7</td></tr>
<tr><td><code>fuse-exfat</code></td><td>1.2.7-1.el7.nux</td></tr>
<tr><td><code>gcc</code></td><td>4.8.5-39.el7</td></tr>
<tr><td><code>gcc</code></td><td>4.8.5-39.el7</td></tr>
<tr><td><code>GConf2</code></td><td>3.2.6-8.el7</td></tr>
<tr><td><code>gdb</code></td><td>7.6.1-119.el7</td></tr>
<tr><td><code>gdisk</code></td><td>0.8.10-3.el7</td></tr>
<tr><td><code>git</code></td><td>1.8.3.1-23.el7_8</td></tr>
<tr><td><code>glib2</code></td><td>2.56.1-5.el7</td></tr>
<tr><td><code>glibc-devel</code></td><td>2.17-307.el7.1</td></tr>
<tr><td><code>gnu-free-fonts-common</code></td><td>20120503-8.el7</td></tr>
<tr><td><code>google-cloud-sdk</code></td><td>295.0.0-1</td></tr>
<tr><td><code>graphviz</code></td><td>2.30.1-21.el7</td></tr>
<tr><td><code>grub2</code></td><td>1:2.02-0.81.el7</td></tr>
<tr><td><code>gtk3</code></td><td>3.22.30-5.el7</td></tr>
<tr><td><code>hdparm</code></td><td>9.43-5.el7</td></tr>
<tr><td><code>htop</code></td><td>2.2.0-3.el7</td></tr>
<tr><td><code>http-parser</code></td><td>2.7.1-8.el7_7.2</td></tr>
<tr><td><code>httpd-tools</code></td><td>2.4.6-93.el7</td></tr>
<tr><td><code>ipa-gothic-fonts</code></td><td>003.03-5.el7</td></tr>
<tr><td><code>iperf3</code></td><td>3.1.7-2.el7</td></tr>
<tr><td><code>ipmitool</code></td><td>1.8.18-9.el7_7</td></tr>
<tr><td><code>krb5-workstation</code></td><td>1.15.1-46.el7</td></tr>
<tr><td><code>ledmon</code></td><td>0.92-1.el7</td></tr>
<tr><td><code>libcap</code></td><td>2.22-11.el7</td></tr>
<tr><td><code>libcurl-devel</code></td><td>7.29.0-57.el7</td></tr>
<tr><td><code>libffi-devel</code></td><td>3.0.13-19.el7</td></tr>
<tr><td><code>libXcomposite</code></td><td>0.4.4-4.1.el7</td></tr>
<tr><td><code>libXcursor</code></td><td>1.1.15-1.el7</td></tr>
<tr><td><code>libXdamage</code></td><td>1.1.4-4.1.el7</td></tr>
<tr><td><code>libXext</code></td><td>1.3.3-3.el7</td></tr>
<tr><td><code>libXi</code></td><td>1.7.9-1.el7</td></tr>
<tr><td><code>libxml2-devel</code></td><td>2.9.1-6.el7.4</td></tr>
<tr><td><code>libXrandr</code></td><td>1.5.1-2.el7</td></tr>
<tr><td><code>libXScrnSaver</code></td><td>1.2.2-6.1.el7</td></tr>
<tr><td><code>libXtst</code></td><td>1.2.3-1.el7</td></tr>
<tr><td><code>lsof</code></td><td>4.87-6.el7</td></tr>
<tr><td><code>lsscsi</code></td><td>0.27-6.el7</td></tr>
<tr><td><code>lynx</code></td><td>2.8.8-0.3.dev15.el7</td></tr>
<tr><td><code>mailx</code></td><td>12.5-19.el7</td></tr>
<tr><td><code>mcelog</code></td><td>3:144-10.94d853b2ea81.el7</td></tr>
<tr><td><code>memtest86+</code></td><td>5.01-2.el7</td></tr>
<tr><td><code>mtr</code></td><td>2:0.85-7.el7</td></tr>
<tr><td><code>mutt</code></td><td>5:1.5.21-29.el7</td></tr>
<tr><td><code>nano</code></td><td>2.3.1-10.el7</td></tr>
<tr><td><code>net-tools</code></td><td>2.0-0.25.20131004git.el7</td></tr>
<tr><td><code>nfs-utils</code></td><td>1:1.3.0-0.66.el7</td></tr>
<tr><td><code>nmap</code></td><td>2:6.40-19.el7</td></tr>
<tr><td><code>ntfs-3g</code></td><td>2:2017.3.23-11.el7</td></tr>
<tr><td><code>ntfsprogs</code></td><td>2:2017.3.23-11.el7</td></tr>
<tr><td><code>ntp</code></td><td>4.2.6p5-29.el7</td></tr>
<tr><td><code>open-vm-tools</code></td><td>10.3.10-2.el7_8.1</td></tr>
<tr><td><code>openldap-clients</code></td><td>2.4.44-21.el7_6</td></tr>
<tr><td><code>openldap-clients</code></td><td>2.4.44-21.el7_6</td></tr>
<tr><td><code>openldap-devel</code></td><td>2.4.44-21.el7_6</td></tr>
<tr><td><code>openssh-clients</code></td><td>7.4p1-21.el7</td></tr>
<tr><td><code>openssh</code></td><td>7.4p1-21.el7</td></tr>
<tr><td><code>openssl-devel</code></td><td>1:1.0.2k-19.el7</td></tr>
<tr><td><code>openssl-devel</code></td><td>1:1.0.2k-19.el7</td></tr>
<tr><td><code>pango</code></td><td>1.42.4-4.el7_7</td></tr>
<tr><td><code>parted</code></td><td>3.1-32.el7</td></tr>
<tr><td><code>perf</code></td><td>3.10.0-1127.10.1.el7</td></tr>
<tr><td><code>pigz</code></td><td>2.3.4-1.el7</td></tr>
<tr><td><code>postfix</code></td><td>2:2.10.1-9.el7</td></tr>
<tr><td><code>postgresql95-contrib</code></td><td>9.5.22-1PGDG.rhel7</td></tr>
<tr><td><code>postgresql95-devel</code></td><td>9.5.22-1PGDG.rhel7</td></tr>
<tr><td><code>postgresql95-libs</code></td><td>9.5.22-1PGDG.rhel7</td></tr>
<tr><td><code>postgresql95-server</code></td><td>9.5.22-1PGDG.rhel7</td></tr>
<tr><td><code>psmisc</code></td><td>22.20-16.el7</td></tr>
<tr><td><code>pssh</code></td><td>2.3.1-7.el7.nux</td></tr>
<tr><td><code>pv</code></td><td>1.4.6-1.el7</td></tr>
<tr><td><code>pystache</code></td><td>0.5.3-2.el7</td></tr>
<tr><td><code>python-daemon</code></td><td>1.6-4.el7</td></tr>
<tr><td><code>python-devel</code></td><td>2.7.5-88.el7</td></tr>
<tr><td><code>python-psycopg2</code></td><td>2.7.5-1.rhel7</td></tr>
<tr><td><code>python2-cryptography</code></td><td>1.7.2-2.el7</td></tr>
<tr><td><code>python2-pip</code></td><td>8.1.2-12.el7</td></tr>
<tr><td><code>python2-pyasn1</code></td><td>0.1.9-7.el7</td></tr>
<tr><td><code>python3-devel</code></td><td>3.6.8-13.el7. Note that you cannot use python3 version 3.7.0 or later.</td></tr>
<tr><td><code>python3-rpm-macros</code></td><td>3-32.el7. Note that you cannot use python3 version 3.7.0 or later.</td></tr>
<tr><td><code>python3</code></td><td>3.6.8-13.el7. Note that you cannot use python3 version 3.7.0 or later.</td></tr>
<tr><td><code>R-devel</code></td><td>3.6.0-1.el7</td></tr>
<tr><td><code>R</code></td><td>3.6.0-1.el7</td></tr>
<tr><td><code>realmd</code></td><td>0.16.1-11.el7</td></tr>
<tr><td><code>redhat-lsb</code></td><td>4.1-27.el7</td></tr>
<tr><td><code>redis</code></td><td>3.2.12-2.el7</td></tr>
<tr><td><code>rsyslog</code></td><td>8.24.0-52.el7</td></tr>
<tr><td><code>samba-client</code></td><td>4.10.4-11.el7_8</td></tr>
<tr><td><code>samba-common-tools</code></td><td>4.10.4-11.el7_8</td></tr>
<tr><td><code>screen</code></td><td>4.1.0-0.25.20120314git3c2946.el7</td></tr>
<tr><td><code>sg3_utils</code></td><td>1:1.37-19.el7</td></tr>
<tr><td><code>smartmontools</code></td><td>1:7.0-2.el7</td></tr>
<tr><td><code>snappy-devel</code></td><td>1.1.0-3.el7</td></tr>
<tr><td><code>sssd</code></td><td>1.16.4-37.el7_8.3</td></tr>
<tr><td><code>strace</code></td><td>4.24-4.el7</td></tr>
<tr><td><code>strongswan</code></td><td>5.7.2-1.el7</td></tr>
<tr><td><code>sysstat</code></td><td>10.1.5-19.el7</td></tr>
<tr><td><code>systemd-networkd</code></td><td>219-73.el7_8.6</td></tr>
<tr><td><code>systemd-resolved</code></td><td>219-73.el7_8.6</td></tr>
<tr><td><code>systemd</code></td><td>219-73.el7_8.6</td></tr>
<tr><td><code>tcpdump</code></td><td>14:4.9.2-4.el7_7.1</td></tr>
<tr><td><code>telnet</code></td><td>1:0.17-65.el7_8</td></tr>
<tr><td><code>tinyproxy</code></td><td>1.8.3-2.el7</td></tr>
<tr><td><code>tmux</code></td><td>1.8-4.el7</td></tr>
<tr><td><code>traceroute</code></td><td>3:2.0.22-2.el7</td></tr>
<tr><td><code>unzip</code></td><td>6.0-21.el7</td></tr>
<tr><td><code>util-linux</code></td><td>2.23.2-63.el7</td></tr>
<tr><td><code>uuid</code></td><td>1.6.2-26.el7</td></tr>
<tr><td><code>veritysetup</code></td><td>2.0.3-6.el7</td></tr>
<tr><td><code>vim-common</code></td><td>2:7.4.629-6.el7</td></tr>
<tr><td><code>vim-enhanced</code></td><td>2:7.4.629-6.el7</td></tr>
<tr><td><code>vim-filesystem</code></td><td>2:7.4.629-6.el7</td></tr>
<tr><td><code>vim-minimal</code></td><td>2:7.4.629-6.el7</td></tr>
<tr><td><code>vnstat</code></td><td>1.15-2.el7</td></tr>
<tr><td><code>w3m</code></td><td>0.5.3-45.git20190105.el7</td></tr>
<tr><td><code>WALinuxAgent</code></td><td>2.0.18-1.el7</td></tr>
<tr><td><code>wget</code></td><td>1.14-18.el7_6.1</td></tr>
<tr><td><code>xfsprogs</code></td><td>4.5.0-20.el7</td></tr>
<tr><td><code>xorg-x11-font-utils</code></td><td>1:7.5-21.el7</td></tr>
<tr><td><code>xorg-x11-fonts-100dpi</code></td><td>7.5-9.el7</td></tr>
<tr><td><code>xorg-x11-fonts-75dpi</code></td><td>7.5-9.el7</td></tr>
<tr><td><code>xorg-x11-fonts-cyrillic</code></td><td>7.5-9.el7</td></tr>
<tr><td><code>xorg-x11-fonts-misc</code></td><td>7.5-9.el7</td></tr>
<tr><td><code>xorg-x11-fonts-Type1</code></td><td>7.5-9.el7</td></tr>
<tr><td><code>yum-plugin-versionlock</code></td><td>1.1.31-54.el7_8</td></tr>
<tr><td><code>zip</code></td><td>3.0-11.el7</td></tr>
<tr><td><code>zsh</code></td><td>5.0.2-34.el7_8.2</td></tr>
</table>
</div></details> +++
+++ <details><summary> +++
Python 2 packages:
+++ </summary><div>
<table>
<tr><th>Python 2 package</th><th>Version</th></tr>
<tr><td><code>setuptools</code></td><td>27.1.2</td></tr>
<tr><td><code>aws-cfn-bootstrap</code></td><td>1.4.post31</td></tr>
<tr><td><code>awscli</code></td><td>1.11.105</td></tr>
<tr><td><code>boto3</code></td><td>1.7.50</td></tr>
<tr><td><code>category-encoders</code></td><td>1.3.0</td></tr>
<tr><td><code>cffi</code></td><td>1.11.5</td></tr>
<tr><td><code>configobj</code></td><td>5.0.6</td></tr>
<tr><td><code>crypto</code></td><td>1.4.1</td></tr>
<tr><td><code>cryptography</code></td><td>2.3.1</td></tr>
<tr><td><code>openpyxl</code></td><td>2.6.3</td></tr>
<tr><td><code>csvkit</code></td><td>1.0.3</td></tr>
<tr><td><code>git+https://github.com/thoughtspot/Diamond.git</code></td></tr>
<tr><td><code>egnyte</code></td><td>0.5.3</td></tr>
<tr><td><code>enum34</code></td><td>1.1.6</td></tr>
<tr><td><code>eventlet</code></td><td>0.19.0</td></tr>
<tr><td><code>Flask</code></td><td>1.0.2</td></tr>
<tr><td><code>fping</code></td><td>0.0.1a2</td></tr>
<tr><td><code>greenlet</code></td><td>0.4.9</td></tr>
<tr><td><code>idna</code></td><td>2.5</td></tr>
<tr><td><code>influxdb</code></td><td>4.1.1</td></tr>
<tr><td><code>ipaddress</code></td><td>1.0.16</td></tr>
<tr><td><code>ipython</code></td><td>4.2.0</td></tr>
<tr><td><code>matplotlib</code></td><td>2.2.3</td></tr>
<tr><td><code>ndg-httpsclient</code></td><td>0.4.0</td></tr>
<tr><td><code>numpy</code></td><td>1.14.5</td></tr>
<tr><td><code>pandas</code></td><td>0.23.4</td></tr>
<tr><td><code>paramiko</code></td><td>2.4.1</td></tr>
<tr><td><code>pexpect</code></td><td>4.1.0</td></tr>
<tr><td><code>pika</code></td><td>0.10.0</td></tr>
<tr><td><code>psutil</code></td><td>4.2.0</td></tr>
<tr><td><code>psycopg2</code></td><td>2.7.1</td></tr>
<tr><td><code>pyasn1</code></td><td>0.4.1</td></tr>
<tr><td><code>pycparser</code></td><td>2.14</td></tr>
<tr><td><code>pycrypto</code></td><td>2.6.1</td></tr>
<tr><td><code>pydot</code></td><td>1.4.1</td></tr>
<tr><td><code>pyOpenSSL</code></td><td>17.1.0</td></tr>
<tr><td><code>python-gflags</code></td><td>3.0.5</td></tr>
<tr><td><code>python-ldap</code></td><td>2.4.25</td></tr>
<tr><td><code>pytz</code></td><td>2016.4</td></tr>
<tr><td><code>requests</code></td><td>2.17.0</td></tr>
<tr><td><code>rsa</code></td><td>3.4.2</td></tr>
<tr><td><code>scipy</code></td><td>1.0.0</td></tr>
<tr><td><code>six</code></td><td>1.10.0</td></tr>
<tr><td><code>scikit-learn</code></td><td>0.19.1</td></tr>
<tr><td><code>statsmodels</code></td><td>0.10.2</td></tr>
<tr><td><code>toml</code></td><td>0.10.0</td></tr>
<tr><td><code>xgboost</code></td><td>0.72.1</td></tr>
<tr><td><code>ansible</code></td><td>2.7.7</td></tr>
<tr><td><code>mock</code></td><td>3.0.5</td></tr>
<tr><td><code>kiwisolver</code></td><td>1.1.0</td></tr>
</table>
</div></details> +++
+++ <details><summary> +++
Python 3 packages:
+++ </summary><div>
<table>
<tr><th>Python 3 package</th><th>Version</th></tr>
<tr><td><code>agate-dbf</code></td><td>0.2.1</td></tr>
<tr><td><code>agate-excel</code></td><td>0.2.3</td></tr>
<tr><td><code>agate-sql</code></td><td>0.5.4</td></tr>
<tr><td><code>agate</code></td><td>1.6.1</td></tr>
<tr><td><code>ansible</code></td><td>2.8.5</td></tr>
<tr><td><code>asn1crypto</code></td><td>0.24.0</td></tr>
<tr><td><code>awscli</code></td><td>1.16.239</td></tr>
<tr><td><code>Babel</code></td><td>2.7.0</td></tr>
<tr><td><code>backcall</code></td><td>0.1.0</td></tr>
<tr><td><code>bcrypt</code></td><td>3.1.7</td></tr>
<tr><td><code>boto3</code></td><td>1.9.229</td></tr>
<tr><td><code>botocore</code></td><td>1.12.229</td></tr>
<tr><td><code>category-encoders</code></td><td>2.0.0</td></tr>
<tr><td><code>certifi</code></td><td>2019.9.11</td></tr>
<tr><td><code>cffi</code></td><td>1.12.3</td></tr>
<tr><td><code>chardet</code></td><td>3.0.4</td></tr>
<tr><td><code>Click</code></td><td>7.0</td></tr>
<tr><td><code>colorama</code></td><td>0.3.9</td></tr>
<tr><td><code>configobj</code></td><td>5.0.6</td></tr>
<tr><td><code>crypto</code></td><td>1.4.1</td></tr>
<tr><td><code>cryptography</code></td><td>2.7</td></tr>
<tr><td><code>csvkit</code></td><td>1.0.4</td></tr>
<tr><td><code>cycler</code></td><td>0.10.0</td></tr>
<tr><td><code>dbfread</code></td><td>2.0.7</td></tr>
<tr><td><code>decorator</code></td><td>4.4.0</td></tr>
<tr><td><code>dnspython</code></td><td>1.16.0</td></tr>
<tr><td><code>docutils</code></td><td>0.15.2</td></tr>
<tr><td><code>egnyte</code></td><td>0.5.3</td></tr>
<tr><td><code>enum34</code></td><td>1.1.6</td></tr>
<tr><td><code>et-xmlfile</code></td><td>1.0.1</td></tr>
<tr><td><code>eventlet</code></td><td>0.19.0</td></tr>
<tr><td><code>Flask</code></td><td>1.1.1</td></tr>
<tr><td><code>fping</code></td><td>0.0.1a2</td></tr>
<tr><td><code>future</code></td><td>0.17.1</td></tr>
<tr><td><code>greenlet</code></td><td>0.4.15</td></tr>
<tr><td><code>idna</code></td><td>2.8</td></tr>
<tr><td><code>influxdb</code></td><td>5.2.3</td></tr>
<tr><td><code>ipaddress</code></td><td>1.0.22</td></tr>
<tr><td><code>ipython-genutils</code></td><td>0.2.0</td></tr>
<tr><td><code>ipython</code></td><td>7.8.0</td></tr>
<tr><td><code>isodate</code></td><td>0.6.0</td></tr>
<tr><td><code>itsdangerous</code></td><td>1.1.0</td></tr>
<tr><td><code>jdcal</code></td><td>1.4.1</td></tr>
<tr><td><code>jedi</code></td><td>0.15.1</td></tr>
<tr><td><code>Jinja2</code></td><td>2.10.1</td></tr>
<tr><td><code>jmespath</code></td><td>0.9.4</td></tr>
<tr><td><code>joblib</code></td><td>0.13.2</td></tr>
<tr><td><code>kiwisolver</code></td><td>1.1.0</td></tr>
<tr><td><code>leather</code></td><td>0.3.3</td></tr>
<tr><td><code>MarkupSafe</code></td><td>1.1.1</td></tr>
<tr><td><code>matplotlib</code></td><td>3.1.1</td></tr>
<tr><td><code>monotonic</code></td><td>1.5</td></tr>
<tr><td><code>Naked</code></td><td>0.1.31</td></tr>
<tr><td><code>ndg-httpsclient</code></td><td>0.5.1</td></tr>
<tr><td><code>netaddr</code></td><td>0.7.19</td></tr>
<tr><td><code>numpy</code></td><td>1.17.2</td></tr>
<tr><td><code>openpyxl</code></td><td>2.6.3</td></tr>
<tr><td><code>pandas</code></td><td>0.25.1</td></tr>
<tr><td><code>paramiko</code></td><td>2.6.0</td></tr>
<tr><td><code>parsedatetime</code></td><td>2.4</td></tr>
<tr><td><code>parso</code></td><td>0.5.1</td></tr>
<tr><td><code>patsy</code></td><td>0.5.1</td></tr>
<tr><td><code>pexpect</code></td><td>4.7.0</td></tr>
<tr><td><code>pickleshare</code></td><td>0.7.5</td></tr>
<tr><td><code>pika</code></td><td>1.1.0</td></tr>
<tr><td><code>prompt-toolkit</code></td><td>2.0.9</td></tr>
<tr><td><code>psutil</code></td><td>5.6.3</td></tr>
<tr><td><code>psycopg2</code></td><td>2.8.3</td></tr>
<tr><td><code>ptyprocess</code></td><td>0.6.0</td></tr>
<tr><td><code>pyasn1-modules</code></td><td>0.2.6</td></tr>
<tr><td><code>pyasn1</code></td><td>0.4.7</td></tr>
<tr><td><code>pycparser</code></td><td>2.19</td></tr>
<tr><td><code>pycrypto</code></td><td>2.6.1</td></tr>
<tr><td><code>pydot</code></td><td>1.4.1</td></tr>
<tr><td><code>Pygments</code></td><td>2.4.2</td></tr>
<tr><td><code>PyNaCl</code></td><td>1.3.0</td></tr>
<tr><td><code>pyOpenSSL</code></td><td>19.0.0</td></tr>
<tr><td><code>pyparsing</code></td><td>2.4.2</td></tr>
<tr><td><code>python-dateutil</code></td><td>2.8.0</td></tr>
<tr><td><code>python-gflags</code></td><td>3.1.2</td></tr>
<tr><td><code>python-ldap</code></td><td>3.2.0</td></tr>
<tr><td><code>python-slugify</code></td><td>3.0.3</td></tr>
<tr><td><code>pytimeparse</code></td><td>1.1.8</td></tr>
<tr><td><code>pytz</code></td><td>2019.2</td></tr>
<tr><td><code>PyYAML</code></td><td>5.1.2</td></tr>
<tr><td><code>requests</code></td><td>2.22.0</td></tr>
<tr><td><code>rsa</code></td><td>3.4.2</td></tr>
<tr><td><code>s3transfer</code></td><td>0.2.1</td></tr>
<tr><td><code>scikit-learn</code></td><td>0.21.3</td></tr>
<tr><td><code>scipy</code></td><td>1.3.1</td></tr>
<tr><td><code>shellescape</code></td><td>3.4.1</td></tr>
<tr><td><code>six</code></td><td>1.12.0</td></tr>
<tr><td><code>SQLAlchemy</code></td><td>1.3.8</td></tr>
<tr><td><code>statsmodels</code></td><td>0.10.1</td></tr>
<tr><td><code>text-unidecode</code></td><td>1.2</td></tr>
<tr><td><code>toml</code></td><td>0.10.0</td></tr>
<tr><td><code>traitlets</code></td><td>4.3.2</td></tr>
<tr><td><code>urllib3</code></td><td>1.25.3</td></tr>
<tr><td><code>wcwidth</code></td><td>0.1.7</td></tr>
<tr><td><code>Werkzeug</code></td><td>0.15.6</td></tr>
<tr><td><code>xgboost</code></td><td>0.90</td></tr>
<tr><td><code>xlrd</code></td><td>1.2.0</td></tr>
</table>
</div></details> +++
+++ <details><summary> +++
R packages:
+++ </summary><div>
<table>
<tr><th>R package</th><th>Minimum version</th></tr>
<tr><td><code>broom</code></td><td>0.5.6</td></tr>
<tr><td><code>EnvStats</code></td><td>2.3.1</td></tr>
<tr><td><code>forecast</code></td><td>8.12</td></tr>
<tr><td><code>ggplot2</code></td><td>3.3.1</td></tr>
<tr><td><code>ggpubr</code></td><td>0.3.0</td></tr>
<tr><td><code>import</code></td><td>1.1.0</td></tr>
<tr><td><code>lubridate</code></td><td>1.7.9</td></tr>
<tr><td><code>magrittr</code></td><td>1.5</td></tr>
<tr><td><code>padr</code></td><td>0.5.2</td></tr>
<tr><td><code>timetk</code></td><td>2.0.0</td></tr>
<tr><td><code>tseries</code></td><td>0.10.47</td></tr>
<tr><td><code>Rserve</code></td><td>1.7.3.1</td></tr>
<tr><td><code>xts</code></td><td>0.12.0</td></tr>
</table>
</div></details> +++
