= ThoughtSpot deployment templates for Amazon Linux 2
:last_updated: 10/13/2020

Get the two primary tarball artifacts for configuring ThoughtSpot using Amazon Linux 2.

You must have the following artifacts to install or upgrade ThoughtSpot applications that run on Amazon Linux 2:

* The *Ansible tarball* and the *Terraform template* each contain a set of scripts for installing OS packages, dependencies, the ThoughtSpot CLI (tscli), and configuring your cluster (preparing the disks).
Choose *_either_* the Ansible tarball or the Terraform template, depending on which tool you have in your organization.
You can obtain this tarball from your ThoughtSpot contact.
* The *Release tarball* contains the ThoughtSpot software binaries (`tar.gz`) of the release version you are installing or upgrading;
for example, ThoughtSpot Release 6.1.1.
You can obtain this file from the https://thoughtspot.egnyte.com/[ThoughtSpot secure file sharing system].
We sent this information to you in our Welcome email.
Contact ThoughtSpot Support if you experience difficulties accessing these files.

== Next steps

Next, xref:al2-install-online.adoc[install ThoughtSpot in Amazon Linux 2 online clusters], where the hosts can connect to the public repositories to download the required packages, or xref:al2-install-offline.adoc[install ThoughtSpot in Amazon Linux 2 offline clusters], where the hosts cannot connect to the public repositories to download the required packages.
