= ThoughtSpot deployment artifacts for Amazon Linux 2
:last_updated: 8/13/2021

Get the two primary tarball artifacts for configuring ThoughtSpot using Amazon Linux 2.

include::partial$ts-artifacts-customer-os.adoc[]

== Next steps

Next, xref:al2-install-online.adoc[install ThoughtSpot in Amazon Linux 2 online clusters], where the hosts can connect to the public repositories to download the required packages, or xref:al2-install-offline.adoc[install ThoughtSpot in Amazon Linux 2 offline clusters], where the hosts cannot connect to the public repositories to download the required packages.

'''
> **Related information**
>
> * xref:al2-prerequisites.adoc[Amazon Linux 2 prerequisites]
> * xref:al2-install-online.adoc[Online Amazon Linux 2 install]
> * xref:al2-install-offline.adoc[Offline Amazon Linux 2 install]
> * xref:al2-upgrade.adoc[Amazon Linux 2 upgrade]
> * xref:al2-add-node.adoc[Adding new nodes to clusters in Amazon Linux 2]
> * xref:al2-packages.adoc[Packages installed with Amazon Linux 2]