= Packages installed with ThoughtSpot for Amazon Linux 2
:last_updated: 01/04/2020
:linkattrs:
:experimental:

View the packages necessary to deploy ThoughtSpot with Amazon Linux 2.

To successfully deploy ThoughtSpot in your organization, you must have the following packages on each node of your ThoughtSpot cluster: yum, python 3, and R.
When the Ansible playbook runs, it automatically installs them.

ThoughtSpot works with the latest version of each package; see the minimum supported version.

[#yum]
[#pip2]
[#pip3]
[#r]
[tabset]
====
Yum RPM packages;;
+
--
Download: link:{attachmentsdir}/yum-rpm-packages.csv[Yum RPM package list].

include::partial$packages/yum-rpm-packages.adoc[]
--
Python 2 packages;;
+
--
Download: link:{attachmentsdir}/pip2-rpm-packages.csv[Python RPM package list].

include::partial$packages/pip2-rpm-packages.adoc[]
--
Python 3 packages;;
+
--
Download: link:{attachmentsdir}/pip3-rpm-packages.csv[Python3 RPM package list].
include::partial$packages/pip3-rpm-packages.adoc[]
--
R packages;;
+
--
Download: link:{attachmentsdir}/r-rpm-packages.csv[R RPM package list].
include::partial$packages/r-rpm-packages.adoc[]
--
====