= Upgrading ThoughtSpot for Amazon Linux 2
:last_updated: 6/4/2020

Learn how to upgrade your Amazon Linux 2 installation of ThoughtSpot.

To upgrade your Amazon Linux 2 installation of ThoughtSpot, follow these steps:

. Back up your ThoughtSpot cluster.
. Pull the necessary security updates.
. Download the release tarball to each cluster (for online clusters) or to your organization's mirror repository (for offline clusters).
. For offline clusters, run the `run_offline.sh` script from the Ansible tarball.
. Run the `tscli cluster update` command.

'''
> **Related information**
>
> * xref:al2-prerequisites.adoc[Amazon Linux 2 prerequisites]
> * xref:al2-ts-artifacts.adoc[ThoughtSpot deployment artifacts for Amazon Linux 2]
> * xref:al2-install-online.adoc[Online Amazon Linux 2 install]
> * xref:al2-install-offline.adoc[Offline Amazon Linux 2 install]
> * xref:al2-add-node.adoc[Adding new nodes to clusters in Amazon Linux 2]
> * xref:al2-packages.adoc[Packages installed with Amazon Linux 2]