= Packages installed with ThoughtSpot for Amazon Linux 2
:last_updated: 01/04/2020
:linkattrs:
:experimental:

View the packages necessary to deploy ThoughtSpot with Amazon Linux 2.

To successfully deploy ThoughtSpot in your organization, you must have the following packages on each node of your ThoughtSpot cluster: yum, python 3, and R.
When the Ansible playbook runs, it automatically installs them.

ThoughtSpot works only with the specified version of each package.

[#yum]
[#pip2]
[#pip3]
[#r]
[tabset]
====
Yum RPM packages;;
+
--
Download: link:{attachmentsdir}/yum-rpm-packages.csv[Yum RPM package list].

include::partial$packages/yum-rpm-packages.adoc[]
--
Python 2 packages;;
+
--
Download: link:{attachmentsdir}/pip2-rpm-packages.csv[Python RPM package list].

include::partial$packages/pip2-rpm-packages.adoc[]
--
Python 3 packages;;
+
--
Download: link:{attachmentsdir}/pip3-rpm-packages.csv[Python3 RPM package list].
include::partial$packages/pip3-rpm-packages.adoc[]
--
R packages;;
+
--
Download: link:{attachmentsdir}/r-rpm-packages.csv[R RPM package list].
include::partial$packages/r-rpm-packages.adoc[]
--
====

'''
> **Related information**
>
> * xref:al2-prerequisites.adoc[Amazon Linux 2 prerequisites]
> * xref:al2-ts-artifacts.adoc[ThoughtSpot deployment artifacts for Amazon Linux 2]
> * xref:al2-install-online.adoc[Online Amazon Linux 2 install]
> * xref:al2-install-offline.adoc[Offline Amazon Linux 2 install]
> * xref:al2-upgrade.adoc[Amazon Linux 2 upgrade]
> * xref:al2-add-node.adoc[Adding new nodes to clusters in Amazon Linux 2]
