= Analyst
:last_updated: 7/19/2021
:linkattrs:
:experimental:

Your job is vital to your organization, and here is how you can get your users what they need:

xref:worksheets.adoc[]::
Create worksheets to make searching your data easier. Worksheets are flat tables created by joining columns from a set of one or more tables or imported datasets.

xref:search-assist.adoc[Search Assist]::
Enable users to learn how to use ThoughtSpot search by creating sample queries based on your own data.

xref:scriptability.adoc[Scriptability]::
Use SpotApps to export Worksheets, Pinboards, and Answers in a human-readable format.

xref:app-templates.adoc[SpotApps]::
Use SpotApps to create and migrate collections of related pinboards, answers, worksheets, views & tables.

xref:tml.adoc[ThoughtSpot Modeling Language]::
Modify a Worksheet, Pinboard, or Answer in a flat-file format.

xref:spotiq.adoc[SpotIQ]::
Use SpotIQ to gain AI-based insights into your data.

xref:pinboard-filters.adoc[]::
Pinboard filters allow you to apply the same filters to more than one related visualization. You can narrow the focus of your pinboard for specific purposes or audiences. You can create xref:pinboard-filters-linked.adoc[linked pinboard filters] or xref:pinboard-filters-selective.adoc[selective pinboard filters].

xref:chart-change.adoc[]::
You can adjust all aspects of ThoughtSpot charts to make them more useful for users: color, legends, axis, number format, and many more.

xref:formulas.adoc[Formulas]::
Add formulas to answers or worksheets, to perform mathematical functions, check for and replace null values, add if...then...else logic, and so on.

////
Getting started for Business users::
Get a quick overview of how ThoughtSpot can support you.
+
See xref:getting-started.adoc[].

Home page::
This is where you get direct access to exisiting Answers, Pinboards, and visualizations.

Pinboards and Answers::
Quick tips on how you can use and customize Pinboards and Charts.
+
See xref:charts.adoc[], xref:chart-types.adoc[], xref:chart-change.adoc[], and xref:pinboards.adoc[].

ThoughtSpot Search::
Explore our flagship Search functionality.
+
See xref:search.adoc[].
////
////
Search Assist::
See how ThoughtSpot Search Assist gives you insights into your own data.
////

xref:mobile.adoc[Mobile App]::
Access your ThoughtSpot cluster on the ThoughtSpot mobile app to search Answers and Pinboards, and create Pinboards.

////
from old user guide


* *xref:navigating-thoughtspot.adoc[Finding your way around]* +
 To make navigation easy, we organized ThoughtSpot into several sections.
You can see them on the menu bar.
* *xref:user-profile.adoc[About the user profile]* +
 The user icon lets you view your profile, or sign out of ThoughtSpot.
* *xref:privileges-end-user.adoc[Understanding privileges]* +
 Your privileges determine the things you can do.
ThoughtSpot sets privileges at the group level.
* *xref:tags.adoc[About tags]* +
 You can create tags to make it easier for people to find data sources and pinboards.

* xref:search.adoc[Use search]
* xref:answers.adoc[Work with Answers]
* xref:filters.adoc[Work with filters]
* xref:charts.adoc[Work with charts]
* xref:formulas.adoc[Work with formulas]
* xref:pinboards.adoc[Use pinboards]
* xref:answer-explorer.adoc[Answer Explorer]
* xref:r-thoughtspot.adoc[About R in ThoughtSpot]
* xref:spotiq.adoc[SpotIQ]
* xref:data-sources.adoc[Work with data]
* xref:help-center.adoc[]
////
