= New answer experience
:last_updated: 5/20/2022
:linkattrs:
:experimental:

== Overview

The new answer experience contains multiple new features and feature enhancements. It is part of ThoughtSpot's move to a new stack. It is on by default for individual users. The option to turn it on or off <<toggle-on-off,individually>> is also on by default. To remove or enable this option, contact {support-url}. If the new answer experience is available in your environment, turn it on or off individually from your profile, in the **Experience manager** at the bottom of your profile. The new answer experience contains the following features:

// REPLACE ABOVE LINE WITH To remove or enable this option, <<toggle-on-off-global,manage experiences in the Admin Console>> IF CHANGE IS MADE

[#new-features]
include::partial$new-answer-experience-features.adoc[]

[#toggle-on-off]
== Turn the new answer experience on or off individually
The new Answer experience is on by default. The option to turn it on or off individually is also on by default. To remove or enable this option, contact {support-url}. If this option is available in your environment, you can turn the new answer experience on or off individually from your profile.

To turn the new answer experience on or off, follow these steps:

. Navigate to your profile: select the **Profile** icon at the top right of your screen, and select **Profile**.

. Next to *Experience*, at the bottom of your profile, select *Edit*.

. Next to *Answers experience*, select **New experience**. To turn it off, select **Classic experience**.

. Select *Save*.

[#toggle-on-off-global]
== Turn the new answer experience on or off for the whole cluster
You can manage the availability of the new answer experience by xref:support-contact.adoc[contacting ThoughtSpot Support]. ThoughtSpot Support can turn the new answer experience on or off globally, and specify the default answer experience for all users. For example, you can turn the new answer experience on globally, but use the classic experience as the default.

////
with conf from arpit, remove above section and replace with this
[#toggle-on-off-global]
== Turn the new answer experience on or off for the whole cluster
You can manage the availability of the new answer experience xref:admin-portal-search-spotiq-settings.adoc#experience[from the Admin Console]. There, you can turn the new answer experience on or off globally, and specify the default answer experience for all users. For example, you can turn the new answer experience on globally, but use the classic experience as the default.
////

[#limitations]
== Limitations
include::partial$new-answer-experience-deprecations.adoc[]