= AWS configuration options
:last_updated: 12/31/2020
:linkattrs:
:experimental:

Your instances require specific configurations of memory, CPU, storage, and networking capacity. Our recommendations for instance types differ, depending on whether you are accessing your data by loading it into ThoughtSpot's <<in-memory,in-memory database>>, or if you are connecting to your data in a <<connections,cloud data warehouse>>.

ThoughtSpot can be deployed in your AWS environment by deploying compute (VM) instances in your Amazon VPC as well as an underlying persistent storage infrastructure.
Currently two configuration modes are supported by ThoughtSpot:

Mode 1: Compute VMs::
 EBS-only persistent storage
Mode 2: Compute VMs::
EBS and S3 persistent storage

The cost of infrastructure for deploying ThoughtSpot is cheaper when using S3.
However, there are differences in where data is loaded, as well as in the backup and restore procedures.
For assistance in choosing the best mode for your organization, contact your ThoughtSpot representative.
For more information on purchasing ThoughtSpot in AWS, see: https://www.thoughtspot.com/pricing[ThoughtSpot Pricing^].

All AWS VMs in a ThoughtSpot cluster must be in the same availability zone (and therefore, also in the same region).
ThoughtSpot does not support deploying VMs in the same cluster across availability zones.
For more information, see https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/Concepts.RegionsAndAvailabilityZones.html[Regions and Availability Zones^] in Amazon's AWS documentation.

[#ts-aws-instance-types]
== ThoughtSpot AWS instance types

The following sections contain the supported and recommended instance types for a ThoughtSpot AWS deployment.
When setting up your cluster in AWS, use the information here to select an instance type, configure the number of instances required for the storage you need, and add data volumes to your cluster. Our recommendations for instance types differ, depending on whether you are accessing your data by loading it into ThoughtSpot's <<in-memory,in-memory database>>, or if you are connecting to your data in a <<connections,cloud data warehouse>>.

When choosing an instance type, ensure that it uses Intel CPUs.

For example: If you were deploying a total cluster data size of 1 TB using the standard r5.16xlarge instance type, you would need 4 VM instances, because the instance type supports data capacity of 250 GB.
The data volumes on the EBS would need to be provision with 2x1 TB volumes per VM.

[#in-memory]
=== Instance types for in-memory data

[#vm-ebs-only-persistent-storage-in-memory]
==== VMs with EBS-only persistent storage

image::persistent-storage-ebs.svg[]

include::partial$aws-ebs-only-storage.adoc[]

[#vm-ebs-s3-persistent-storage-in-memory]
==== VMs with EBS and S3 persistent storage

image::persistent-storage-ebs-s3.svg[]

include::partial$aws-ebs-s3-storage.adoc[]

For most instances, the per VM recommended user data capacity is set at 50% of the available RAM on the instance.
However, in the case of our 16CPU/128GB RAM and 32CPU/256GB RAM instances, we support user data sizes below those numbers to budget for application overhead.

[#connections]
=== Instance types for cloud data warehouse connections

[#vm-ebs-only-persistent-storage-connections]
==== VMs with EBS-only persistent storage

include::partial$aws-ebs-only-storage-connections.adoc[]

[#vm-ebs-s3-persistent-storage-connections]
==== VMs with EBS and S3 persistent storage

include::partial$aws-ebs-s3-storage-connections.adoc[]

[#related]
'''
> **Related information**
>
> * https://aws.amazon.com/ec2/instance-types/[EC2 instance types^]
> * https://aws.amazon.com/ec2/pricing/[EC2 pricing^]
> * https://aws.amazon.com/ebs/pricing/[EBS pricing^]
> * http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/placement-groups.html[Placement groups^]
