= Configure ThoughtSpot nodes in AWS
:last_updated: 01/02/2021
:experimental:
:linkattrs:
:page-aliases: /appliance/aws/installing-aws.adoc

Prepare to install your ThoughtSpot cluster by configuring nodes.

'''
> **ThoughtSpot Training**
>
> * For best results when configuring ThoughtSpot nodes on AWS, we recommend that you take the following ThoughtSpot U course: https://training.thoughtspot.com/node-network-configuration/437249[Network Configuration^].
> * See other training resources at https://training.thoughtspot.com/[ThoughtSpot U^].

'''
Before you can install a ThoughtSpot cluster in AWS, you must configure your nodes.

[#installation-prerequisites]
== Installation Prerequisites

Ensure the successful creation of the virtual machines (VMs) before you install the ThoughtSpot cluster in AWS:

[cols="5,~",grid=none,frame=none]
|===
| &#10063; |  xref:aws-configuration-options.adoc[1. Review AWS configuration options] for detailed instance specs.
| &#10063; |  xref:aws-launch-instance.adoc[2. Set up AWS for ThoughtSpot] to create and launch your instance.
| &#10063; |  xref:ports.adoc[3. Review Network ports documentation] to view the required ports for successful operation of ThoughtSpot.
|===

[#configure-nodes]
== Configure Nodes

After creating the instance, you must configure the nodes.

Follow the steps in this checklist.

[cols="5,~",grid=none,frame=none]
|===
| &#10063; |  <<node-step-1,Step 1: Log in to your cluster>>
| &#10063; |  <<node-step-2,Step 2: Get a template for node configuration>>
| &#10063; |  <<node-step-3,Step 3: Prepare node configuration>>
| &#10063; |  <<node-step-4,Step 4: Configure the nodes>>
| &#10063; |  <<node-step-5,Step 5: Confirm node configuration>>
|===

[#node-step-1]
include::partial$configure-nodes-steps1through5.adoc[]

== Install ThoughtSpot software

Next, xref:aws-cluster-install.adoc[install your ThoughtSpot clusters].

include::partial$install-cluster-error-recovery.adoc[]

'''
> **Related information**
>
> * xref:nodesconfig-example.adoc[The nodes.config file]
> * xref:parameters-nodesconfig.adoc[Parameters of the nodes.config file]
> * xref:cluster-create.adoc[Using the tscli cluster create command]
> * xref:parameters-cluster-create.adoc[Parameters of the cluster create command]
> * Contact xref:support-contact.adoc[ThoughtSpot Support].
