= Set up ThoughtSpot in Azure
:last_updated: 8/6/2021
:linkattrs:
:experimental:
:description: After you determine your configuration options, you must set up your virtual machines using a ThoughtSpot image for Azure.

After you determine your configuration options, you must set up your virtual machines using a ThoughtSpot image for Azure.

== About the ThoughtSpot image

To provision ThoughtSpot in the Azure portal, access the ThoughtSpot Virtual Machine in the Azure Marketplace.

The ThoughtSpot Virtual Machine comes provisioned with the custom ThoughtSpot image to make hosting simple.
A virtual machine is a preconfigured template that provides the information required to launch an instance of ThoughtSpot.
It includes a root disk for the instance, which contains an operating system, application server, and other necessary software.

Check with your ThoughtSpot contact to learn about the latest version of the ThoughtSpot Virtual Machine.

Due to security restrictions, the ThoughtSpot Virtual Machine does not have default passwords for the administrator users.
When you are ready to obtain the password, contact {support-url}.

CAUTION: Starting on January 1, 2023, ThoughtSpot no longer supports deploymnent using CentOS. Full details are provided in xref:end-of-service-centos[CentOS end-of-life announcement]. You can still deploy ThoughtSpot on Azure using Red Hat Enterprise Linux (RHEL), allowing you to run ThoughtSpot on an RHEL 7.8, 7.9, 8.1, 8.2, 8.3, 8.4, 8.5, 8.6, 8.7, or 8.8 image that your organization manages internally. To install ThoughtSpot using RHEL, refer to the xref:rhel.adoc[RHEL and OEL deployment guide] after you launch your virtual machines.

