= Configure ThoughtSpot nodes in Azure
:last_updated: 01/02/2021
:linkattrs:
:page-aliases: /appliance/azure/installing-azure.adoc
:experimental:

Prepare to install your ThoughtSpot cluster by configuring nodes.

Before you can install a ThoughtSpot cluster in Azure, you must configure your nodes.

'''
> **ThoughtSpot Training**
>
> * For best results in configuring ThoughtSpot nodes on Azure, we recommend that you take the following ThoughtSpot U course:  https://training.thoughtspot.com/node-network-configuration/437249[Network Configuration^].
> * See other training resources at https://training.thoughtspot.com/[ThoughtSpot U^].

'''

[#installation-prerequisites]
== Installation Prerequisites

Ensure the successful creation of the virtual machines (VMs) before you install the ThoughtSpot cluster in Azure.

[cols="5,~",grid=none,frame=none]
|===
| &#10063; | xref:azure-configuration-options.adoc[1. Review Azure configuration options] for detailed instance specs.
| &#10063; | xref:azure-launch-instance.adoc[2. Set up Azure for ThoughtSpot] to create and launch your instance.
| &#10063; | xref:azure-launch-instance.adoc#prepare-for-startup[3. Prepare for starting up ThoughtSpot] to learn how to log into your VM with the private key, and change the admin password. You must change the admin password on first login, or you will not be able to log back into your VMs.
| &#10063; | xref:ports.adoc[Review network ports] to view the required ports for successful operation of ThoughtSpot.
|===

[#configure-nodes]
== Configure Nodes

After creating the instance, you must configure the nodes, one node at a time.

Follow the steps in this checklist to configure each node:

[cols="5,~",grid=none,frame=none]
|===

| &#10063; | <<node-step-1,Step 1: Log in to your cluster>>
| &#10063; | <<node-step-2,Step 2: Get a template for network configuration>>
| &#10063; | <<node-step-3,Step 3: Prepare node configuration>>
| &#10063; | <<node-step-4,Step 4: Configure the nodes>>
| &#10063; | <<node-step-5,Step 5: Confirm node configuration>>
|===

[#node-step-1]
=== Step 1: Log in to your cluster

Use Terminal on a Mac or a terminal emulator on Windows to log in to your cluster.
Log in using the new password you created for the _admin_ user in step two of xref:azure-launch-instance.adoc#prepare-for-startup[Prepare for starting up ThoughtSpot].

To log in to your cluster, run:

[source,bash]
----
$ ssh admin@<public_VM-IP>
----

[#node-step-2]
=== Step 2: Get a template for network configuration

Run the `tscli cluster get-config` command to get a template for network configuration for the new cluster.
Redirect it to the file `nodes.config`.

You can find more information on this process in the xref:nodesconfig-example.adoc[`nodes.config` file reference].

[source,bash]
----
$ tscli cluster get-config |& tee nodes.config
----

[#node-step-3]
=== Step 3: Prepare node configuration

CAUTION: _DNS server_ and _IP address_ values must be set in the Azure cloud backend.
It then populates them into the VM configuration.
If you specify different values during this step, it can create a temporary mismatch and lead to connectivity issues.

. Add your specific network information for the nodes in the `nodes.config` file, as demonstrated in the xref:nodesconfig-example.adoc#autodiscovery-of-one-node-example[autodiscovery of one node example].
To edit the file, run:.
+
[source,bash]
----
 $ vim nodes.config
----
+
NOTE: Some of the information in the `nodes.config` file may be pre-populated from earlier steps.
For example, if you specified an IP address while creating VMs, that IP address might already be present in your `nodes.config` file.

. Fill in the areas specified in xref:parameters-nodesconfig.adoc[Parameters of the nodes.config file] with your specific network information.
+
If you have additional nodes, complete each node within the nodes.config file in the same way.

Do not edit any part of the `nodes.config` file except the sections described in xref:parameters-nodesconfig.adoc[Parameters of the nodes.config file].
If you delete quotation marks, commas, or other parts of the code, it may cause setup to fail.

[#node-step-4]
=== Step 4: Configure the nodes

Configure the nodes in the `nodes.config` file using the `set-config` command.

. Disable the `firewalld` service by running `sudo systemctl stop firewalld` in your terminal.
The `firewalld` service is a Linux firewall that must be off for ThoughtSpot installation.
After the cluster installer reboots the nodes, `firewalld` automatically turns back on.
+
[source,bash]
----
$ sudo systemctl stop firewalld
----

. To make sure you temporarily disabled `firewalld`, run `sudo systemctl status firewalld`.
Your output should specify that `firewalld` is inactive.
It may look something like the following:
+
[source,bash]
----
$ sudo systemctl status firewalld
   ● firewalld.service - firewalld - dynamic firewall daemon
     Loaded: loaded (/usr/lib/systemd/system/firewalld.service; disabled;
         vendor preset: enabled)
     Active: inactive (dead)
----

. Run the configuration command: `$ cat nodes.config | tscli cluster set-config`.
+
If the command returns an error, refer to <<set-config-error-recovery,set-config error recovery>>.
+
After you run the node configuration command, your output appears similar to the following:
+
[source,bash]
----
$ cat nodes.config | tscli cluster set-config

 Connecting to local node-scout
 Setting up hostnames for all nodes
 Setting up networking interfaces on all nodes
 Setting up hosts file on all nodes
 Setting up NTP Servers
 Setting up Timezone
 Done setting up ThoughtSpot
----

[#node-step-5]
=== Step 5: Confirm node configuration

Use the `get-config` command to confirm node configuration.

Your output may look similar to the following:

[source,bash]
----
$ tscli cluster get-config

{
  "ClusterId": "",
  "ClusterName": "",
  "DataNetmask": "255.255.252.0",
  "DataGateway": "192.168.4.1",
  "IPMINetmask": "255.255.252.0",
  "IPMIGateway": "192.168.4.1",
  "Timezone": "America/Los_Angeles",
  "NTPServers": "0.centos.pool.ntp.org,1.centos.pool.ntp.org,2.centos.pool.ntp.org,3.centos.pool.ntp.org",
  "DNS": "192.168.2.200,8.8.8.8",
  "SearchDomains": "example.company.com",
  "Nodes": {
	"ac:1f:6b:8a:77:f6": {
  	"NodeId": "ac:1f:6b:8a:77:f6",
  	"Hostname": "Thoughtspot-server1",
  	"DataIface": {
    	"Name": "eth2",
    	"IPv4": "192.168.7.70"
  	},
  	"IPMI": {
    	"IPv4": "192.168.5.70"
  	}
	}
  }
}
----

== Install ThoughtSpot software

Next, xref:azure-cluster-install.adoc[install your ThoughtSpot clusters].

include::partial$install-cluster-error-recovery.adoc[]

'''
> **Related information**
>
> * xref:nodesconfig-example.adoc[The nodes.config file]
> * xref:parameters-nodesconfig.adoc[Parameters of the nodes.config file]
> * xref:cluster-create.adoc[Using the tscli cluster create command]
> * xref:parameters-cluster-create.adoc[Parameters of the cluster create command]
> * Contact https://community.thoughtspot.com/customers/s/contactsupport[ThoughtSpot Support^].
