= Azure configuration options
:last_updated: 02/01/2021
:linkattrs:
:experimental:

ThoughtSpot offers several Microsoft Azure instance types. Our recommendations for instance types differ, depending on whether you are accessing your data by loading it into ThoughtSpot's <<in-memory,in-memory database>>, or if you are connecting to your data in a <<connections,cloud data warehouse>>.

ThoughtSpot can be deployed in your Azure environment by deploying compute VM instances in your VNET, or Azure Virtual Network, and your underlying persistent storage infrastructure.
ThoughtSpot supports Premium SSD Managed Disks for persistent storage.
For more information, see https://azure.microsoft.com/en-us/pricing/details/managed-disks/[Managed Disks pricing^] in Microsoft's Azure documentation.

All Azure VMs (nodes) in a ThoughtSpot cluster must be in the same availability zone (and, therefore, also in the same region).
ThoughtSpot does not support deploying VMs( nodes) of the same cluster across availability zones.
For more information, see https://docs.microsoft.com/en-us/azure/availability-zones/az-overview[What are Availability Zones in Azure?^] in Microsoft's Azure documentation.

When choosing an instance type, ensure that it uses Intel CPUs.

== ThoughtSpot Azure instance types
Our recommendations for instance types differ, depending on if you are accessing your data by loading it into ThoughtSpot's <<in-memory,in-memory database>>, or if you are connecting to your data in a <<connections,cloud data warehouse>>.

[#in-memory]
=== Instance types for in-memory data
include::partial$azure-storage.adoc[]

For most instances, the per VM recommended user data capacity is set at 50% of the available RAM on the instance.
However, in the case of our 16CPU/128GB RAM and 32CPU/256GB RAM instances, we support user data sizes below those numbers to budget for application overhead.

[#connections]
=== Instance types for cloud data warehouse connections
include::partial$azure-storage-connections.adoc[]
