= Business User
:last_updated: 5/10/2022
:linkattrs:
:page-partial:
:experimental:
:description: Business users view data insights to inform and support critical business decisions.

Business users view data insights to inform and support critical business decisions.

Your job is vital to your organization, and using ThoughtSpot makes it easier.

include::partial$liveboards-announcement.adoc[]


Getting started for Business users::
Get a quick overview of how ThoughtSpot can support you.
+
See xref:getting-started.adoc[].

Home page::
This is where you get direct access to existing answers, Liveboards, and visualizations.

Liveboards and Answers::
Quick tips on how you can use and customize Liveboards and charts.
+
See xref:charts.adoc[], xref:chart-types.adoc[], xref:chart-change.adoc[], and xref:liveboards.adoc[].

ThoughtSpot Search::
Explore our flagship Search functionality.
+
See xref:search.adoc[].

////
Search Assist::
See how ThoughtSpot Search Assist gives you insights into your own data.
////

Mobile app::
Access your ThoughtSpot cluster to search answers and Liveboards, and create Liveboards.
+
See xref:mobile.adoc[].


////
from old user guide


* *xref:navigating-thoughtspot.adoc[Finding your way around]* +
 To make navigation easy, we organized ThoughtSpot into several sections.
You can see them on the menu bar.
* *xref:user-profile.adoc[About the user profile]* +
 The user icon lets you view your profile, or sign out of ThoughtSpot.
* *xref:privileges-end-user.adoc[Understanding privileges]* +
 Your privileges determine the things you can do.
ThoughtSpot sets privileges at the group level.
* *xref:tags.adoc[About tags]* +
 You can create tags to make it easier for people to find data sources and Liveboards.

* xref:search.adoc[Use search]
* xref:answers.adoc[Work with Answers]
* xref:filters.adoc[Work with filters]
* xref:charts.adoc[Work with charts]
* xref:formulas.adoc[Work with formulas]
* xref:liveboards.adoc[Use Liveboards]
* xref:answer-explorer.adoc[Answer Explorer]
* xref:r-thoughtspot.adoc[About R in ThoughtSpot]
* xref:spotiq.adoc[SpotIQ]
* xref:data-workspace.adoc[Data workspace]
* xref:help-center.adoc[]
////
