= Configure casing
:last_updated: 12/25/2020
:linkattrs:
:page-partial:
:experimental:

You can set the type of case sensitivity you would like to see reflected in the ThoughtSpot display.

The case sensitivity for source data strings is preserved in the display.
So, the visual display of results is identical to the case of the loaded input.

NOTE: The casing remains in lowercase in other parts of the application, when you ask a question or apply a filter. For string casing to work properly, you must disable title casing.

Remember that we specify string casings at the level of a column, not globally.
So data in the same data source may have different string casings if it comes from different columns.

Tables that are already compacted keep their lowercase format.
To get the desired string case for these tables, you must truncate all related tables and reload them.

To take advantage of case configuration, have https://community.thoughtspot.com/customers/s/contactsupport[ThoughtSpot Support^] enable this option on your cluster.
