= Aggregated KPI charts
:last_updated: 10/9/2024
:author: Naomi
:linkattrs:
:experimental:
:description: You can now create KPIs that display values as an aggregate over a period of time.
:jira: SCAL-227777


In general, time-series KPI charts display metrics as the most recent value (un-aggregated) defined in the date bucket. For example, a Sales Monthly KPI chart for a period of the last three months displays the value of *this month*, and compares it to the previous month to describe the percentage change. The sparkline graph shows a point value for each month over the last three months, and you can hover over each point to see the value.


If you change the filter on the Liveboard to which the KPI is pinned to display the last six months instead, the main value of the KPI chart does not change, because it still records the most recent value.


== Aggregated KPI charts


You can now choose to display KPI chart values as the aggregated result of all periods defined in the date bucket. For example, a Sales Monthly KPI for the last three months displays the value of all three months, aggregated. The sparkline graph still shows a point value for each month over the last three months, and you can hover over each point to see the value. The percentage change compares the aggregated results of the last three months to the aggregated sum of the previous three months. For example, a period of June through August would be compared with March through May.


If you change the filter on the Liveboard to which the KPI is pinned to display the last six months instead, the main value of the KPI chart now displays the aggregated result of the last six months.

NOTE: To turn on this feature, contact {support-url}.


