= Network connectivity issues

If network connectivity to and from ThoughtSpot is not working, try using these steps to find and correct the issue.

To troubleshoot network connectivity for ThoughtSpot:

. Make sure that the network cables are connected correctly.
. Check that the network cable is connecting the nodes to the network switch.
. Try replacing the cable with a cable from a known working system to rule out a bad cable or switch connectivity issues.
. Make sure the eth0 interface is connected to the network by issuing: `ethtool eth0` The port that's currently connected will have "link detected" in the last line of the output.
. If the networking settings have been reconfigured, reboot each of the nodes.

'''
> **Related information**
>
> * xref:get-logs.adoc[Get logs]
> * xref:upload-logs-egnyte.adoc[Upload logs to ThoughtSpot Support]
> * xref:set-timezone.adoc[Check the timezone]
> * xref:certificate-warning.adoc[Browser untrusted connection error]
> * xref:char-encoding.adoc[Characters not displaying correctly]
> * xref:clear-browser-cache.adoc[Clear the browser cache]
> * xref:formula-date-problem.adoc[Cannot open a saved answer that contains a formula]
> * xref:data-loading-too-slowly.adoc[Data loading too slowly]
> * xref:search-too-many-blanks.adoc[Search results contain too many blanks]