= Delete a table from a Snowflake connection
:last_updated: 08/27/2021
:linkattrs:
:experimental:
:page-partial:
:page-aliases: /7.1.0.aug.sw/data-integrate/embrace/snowflake-delete-table.adoc
:description: Learn how to delete a table from a Snowflake connection.

include::partial$connection-delete-table-intro.adoc[]

Follow these steps to delete an existing table from a Snowflake connection:

include::partial$connection-delete-table-initial-steps.adoc[]

include::partial$connection-delete-table-final-steps.adoc[]

'''
> **Related information**
>
> * xref:connections-snowflake-add.adoc[Add a connection]
> * xref:connections-snowflake-edit.adoc[]
> * xref:connections-snowflake-remap.adoc[]
> * xref:connections-snowflake-external-tables.adoc[]
> * xref:connections-snowflake-delete-table-dependencies.adoc[]
> * xref:connections-snowflake-delete.adoc[]
> * xref:connections-snowflake-oauth.adoc[]
> * xref:connections-snowflake-okta-oauth.adoc[]
> * xref:connections-snowflake-azure-ad-oauth.adoc[]
> * xref:connections-snowflake-best.adoc[Best practices]
> * xref:connections-snowflake-reference.adoc[Reference]
> * xref:connections-query-tags.adoc#tag-snowflake[ThoughtSpot query tags in Snowflake]
> * xref:connections-snowflake-partner.adoc[Partner Connect], with an accompanying xref:connections-snowflake-tutorial.adoc[Tutorial]