= Delete a table with dependencies from a Google {connection} connection
:last_updated: 08/27/2021
:linkattrs:
:experimental:
:page-partial:
:page-aliases: /7.1.0.aug.sw/data-integrate/embrace/gbq-delete-table-dependencies.adoc
:connection: BigQuery
:description: To delete a table with dependencies from a Google BigQuery connection, first delete the dependent objects.

If you attempt to delete a table with dependent objects, ThoughtSpot blocks the operation until you resolve the dependencies. See xref:connections-gbq-delete-table.adoc[].

include::partial$connection-delete-table-dependencies.adoc[]

'''
> **Related information**
>
> * xref:connections-gbq-prerequisites.adoc[]
> * xref:connections-gbq-ingress.adoc[]
> * xref:connections-gbq-add.adoc[Add a {connection} connection]
> * xref:connections-gbq-edit.adoc[Edit a {connection} connection]
> * xref:connections-gbq-remap.adoc[Remap a {connection} connection]
> * xref:connections-gbq-external-tables.adoc[]
> * xref:connections-gbq-delete-table.adoc[Delete a table from a {connection} connection]
> * xref:connections-gbq-delete-table-dependencies.adoc[Delete a table with dependencies from a {connection} connection]
> * xref:connections-gbq-reference.adoc[]
> * xref:connections-gbq-delete.adoc[Delete a {connection} connection]
//> * xref:connections-query-tags.adoc#tag-gbq[ThoughtSpot query tags in Google BigQuery]