= Query external tables from your {connection} connection
:last_updated: 9/22/2022
:linkattrs:
:experimental:
:connection: BigQuery
:description: ThoughtSpot supports querying external tables stored in external data stores, such as Amazon S3 or Google Cloud Storage, via your cloud data warehouse.

include::partial$external-table-intro.adoc[]

[#supported-stores-formats]
== Supported data stores and file formats

ThoughtSpot supports any data stores or file formats that {connection} supports. Refer to the {connection}
documentation for more information: https://cloud.google.com/bigquery/docs/external-tables[External tables^].

== Querying your external tables

To query your external tables in ThoughtSpot, follow these steps:

. Ensure that {connection} supports your data store(s) and file format(s). Refer to <<supported-stores-formats,Supported data stores and file formats>>.

. Create the external table(s) in {connection}. For assistance, refer to the {connection} documentation.

. Create your {connection} connection, if you have not already done so. When selecting tables, select the external tables you want to query, as well as any other tables. Refer to xref:connections-gbq-add.adoc[].
+
NOTE: Ensure that your external tables are in the same database and schema as the database and schema specified in your {connection} connection.

. xref:search.adoc[Search] the data from your external table.

'''
> **Related information**
>
> * xref:connections-gbq-prerequisites.adoc[]
> * xref:connections-gbq-ingress.adoc[]
> * xref:connections-gbq-add.adoc[Add a {connection} connection]
> * xref:connections-gbq-edit.adoc[Edit a {connection} connection]
> * xref:connections-gbq-remap.adoc[Remap a {connection} connection]
> * xref:connections-gbq-delete-table.adoc[Delete a table from a {connection} connection]
> * xref:connections-gbq-delete-table-dependencies.adoc[Delete a table with dependencies from a {connection} connection]
> * xref:connections-gbq-reference.adoc[]
> * xref:connections-gbq-delete.adoc[Delete a {connection} connection]
//> * xref:connections-query-tags.adoc#tag-gbq[ThoughtSpot query tags in Google BigQuery]