= Remap a Snowflake connection
:last_updated: 08/27/2021
:linkattrs:
:experimental:
:page-partial:
:page-aliases: /7.1.0.aug.sw/data-integrate/embrace/snowflake-remap.adoc


You can modify the parameters of your connection to the Snowflake database by changing the source mapping `tml` file. ThoughtSpot creates this file automatically, to record the details of the new or updated connections.

include::partial$liveboards-announcement.adoc[]


include::partial$connection-remapping-caution.adoc[]

To remap a Snowflake connection, follow these steps:

include::partial$connection-remapping-initial-steps.adoc[]

include::partial$connection-remapping-final-steps.adoc[]

'''
> **Related information**
>
> * xref:connections-snowflake-add.adoc[Add a Snowflake connection]
> * xref:connections-snowflake-edit.adoc[]
> * xref:connections-snowflake-external-tables.adoc[]
> * xref:connections-snowflake-delete-table.adoc[]
> * xref:connections-snowflake-delete-table-dependencies.adoc[]
> * xref:connections-snowflake-delete.adoc[]
> * xref:connections-snowflake-oauth.adoc[]
> * xref:connections-snowflake-azure-ad-oauth.adoc[]
> * xref:connections-snowflake-okta-oauth.adoc[]
> * xref:connections-snowflake-best.adoc[Best practices]
> * xref:connections-snowflake-reference.adoc[Reference]
> * xref:connections-query-tags.adoc#tag-snowflake[Snowflake query tags]
> * xref:connections-snowflake-partner.adoc[Partner Connect], with an accompanying xref:connections-snowflake-tutorial.adoc[Tutorial]
