= Redshift connection reference
:last_updated: 03/25/2021
:experimental:
:linkattrs:
:page-partial:
:page-aliases: /data-integrate/embrace/embrace-redshift-reference.adoc

Learn about the fields used to create a Redshift connection.

Here is a list of the fields of a Redshift connection.
You need specific information to establish a seamless and secure connection.
All fields are required, except where noted.
[#connection-name]
Connection name::  Enter a new Redshift connection name.
[#connection-description]
Connection description::
Provide a short description of the connection.
_(Optional)_
[#host]
Host::  Enter the host name associated with the Redshift database.
[#port]
Port::  Enter the port number associated with the Redshift database.
[#user]
User::  Enter the Redshift account username.
+
NOTE: This user must have at least *read* access to the *SVV_TABLE_INFO* table.
[#password]
Password::  Enter the Redshift account password.
[#databse]
Database::  Specify the database associated with the account.

'''
> **Related information**
>
> * xref:connections-redshift-add.adoc[]
> * xref:connections-redshift-edit.adoc[Edit an Amazon Redshift connection]
> * xref:connections-redshift-remap.adoc[Remap an Amazon Redshift connection]
> * xref:connections-redshift-delete-table.adoc[Delete a table from an Amazon Redshift connection]
> * xref:connections-redshift-delete-table-dependencies.adoc[Delete a table with dependencies from an Amazon Redshift connection]
> * xref:connections-redshift-delete.adoc[Delete an Amazon Redshift connection]
> * xref:connections-redshift-best.adoc[]
> * xref:connections-aws-secrets.adoc[Configure AWS Secrets Manager]