= Connection reference for {connection}
:last_updated: 10/25/2023
:author: Naomi
:page-aliases:
:linkattrs:
:experimental:
:connection: Google Cloud SQL for SQL Server
:description: Learn the specific information needed to establish a secure connection to Google Cloud SQL for SQL Server.
:jira: SCAL-166160

You need specific information to establish a seamless and secure connection.
The following fields are required, except where noted.

Connection name:: Enter a name for your {connection} connection.
Connection description:: Provide a short description of the connection.
Host:: Enter the host name associated with the database.
Port:: Enter the port number associated with the database.
User:: Enter the {connection} account username.
Example;; your.name@thoughtspot.com
Password:: Enter the {connection} account password.
Database:: Specify the database associated with the account.


'''
> **Related information**
>
> * xref:connections-google-cloud-sql-sql-server-add.adoc[Add a {connection} connection]
> * xref:connections-google-cloud-sql-sql-server-edit.adoc[Edit a {connection} connection]
> * xref:connections-google-cloud-sql-sql-server-remap.adoc[Remap a {connection} connection]
> * xref:connections-google-cloud-sql-sql-server-delete-table.adoc[Delete a table from a {connection} connection]
> * xref:connections-google-cloud-sql-sql-server-delete-table-dependencies.adoc[Delete a table with dependent objects]
> * xref:connections-google-cloud-sql-sql-server-delete.adoc[Delete a {connection} connection]