= BigQuery connection reference
:experimental:
:last_updated: 03/25/2021
:page-partial:
:page-aliases: /data-integrate/embrace/embrace-gbq-reference.adoc
:description: Learn the specific information needed to establish a secure connection to Google BigQuery.

Learn about the fields used to create a BigQuery connection.

Here is a list of the fields for a BigQuery connection from ThoughtSpot.
You need specific information to establish a seamless and secure connection.
All fields are required, except where noted.
[#connection-name]
Connection name:: Enter a new BigQuery connection name.
[#connection-description]
Connection description::
Provide a short description of the connection.
_(Optional)_
[#project-id]
Project id::  Enter the project ID associated with the BigQuery database.
[#service-account]
Service account::  Enter the service account JSON key associated with the BigQuery database. To generate the key, refer to xref:connections-gbq-prerequisites.adoc#service-account[Google BigQuery prerequisites].

'''
> **Related information**
>
> * xref:connections-gbq-prerequisites.adoc[]
> * xref:connections-gbq-ingress.adoc[]
> * xref:connections-gbq-add.adoc[Add a {connection} connection]
> * xref:connections-gbq-edit.adoc[Edit a {connection} connection]
> * xref:connections-gbq-remap.adoc[Remap a {connection} connection]
> * xref:connections-gbq-external-tables.adoc[]
> * xref:connections-gbq-delete-table.adoc[Delete a table from a {connection} connection]
> * xref:connections-gbq-delete-table-dependencies.adoc[Delete a table with dependencies from a {connection} connection]
> * xref:connections-gbq-delete.adoc[Delete a {connection} connection]
//> * xref:connections-query-tags.adoc#tag-gbq[ThoughtSpot query tags in Google BigQuery]