= Access levels and ingress rules for Google BigQuery
:author: Naomi
:last_updated: 3/20/23
:linkattrs:
:experimental:
:connection: Google BigQuery
:description: Learn how to allow ingress from ThoughtSpot instances to Google BigQuery with the minimum required privileges (minimal set of API Methods).

== Basic access level

Administrators define access policy, which is a container for link:https://cloud.google.com/access-context-manager/docs/overview[Access Context Manager^] resources like access levels and service perimeters. Access level defines tiers of who can access what, such as an access level called High_Level, which lets a small group of highly-privileged users to make requests. Service perimeters are created by VPC Service Controls, and protect resources and data that you specify. Those within the perimeter have access to the data contained within, but do not have access to unauthorized resources outside the perimeter. To create data exchange across perimeters, you need to use ingress and egress rules.

=== Create an access policy

To create an access policy, follow the steps described in link:https://cloud.google.com/access-context-manager/docs/create-access-policy#scoped-access-policy[Create an access policy^].

=== Example

The following is an example of an Access Level schema in JSON format.

[source]
----
{
  "name": AccessLevelName,
  "title": AccessLevelName,
  "description": Description,
  "basic": {
    "conditions": [
      {
        "ipSubnetworks": [
            {{ THOUGHTSPOT IP }}
        ]
      }
    ],
    "combiningFunction": AND
  }
}
----

For more information about the access level fields, see link:https://cloud.google.com/access-context-manager/docs/reference/rest/v1/accessPolicies.accessLevels#ConditionCombiningFunction[REST Resource, accessPolicies. accessLevels^].

== Ingress and egress rules

Ingress and egress rules are created to allow access to and from the resources and clients protected by service perimeters. Ingress rules refer to access by an API client from outside the service perimeter to resources within a service perimeter, while egress rules refer to access by an API client or resources from within the service perimeter to access resources outside a service perimeter. To grant ThoughtSpot access to data within a service perimeter, you will need to use an ingress rule.

=== Set ingress policies during perimeter creation

. In the Google Cloud console navigation menu, click *Security*, then select *VPC Service Controls*.
. Click *New perimeter*.
. In the left menu, click *Ingress policy*.
. Select *Add rule*.
. Designate the required *From attributes of the API client* and *To attributes of Google Cloud resources/services* that you want.
. Click *Create perimeter*.


=== Update ingress policies for a service perimeter

. In the Google Cloud console navigation menu, click *Security*, then select *VPC Service Controls*.
. Select an existing service perimeter.
. Click *Edit perimeter*.
. In the left menu, click *Ingress policy*.
. Designate the required *From attributes of the API client* and *To attributes of Google Cloud resources/services* that you want.
. Click *Save*.

=== Example

The following is an example of an ingress rule in .yaml format.

[source]
----
- ingressFrom:
    identityType: ANY_IDENTITY
    sources:
    - accessLevel:
  ingressTo:
    operations:
    - serviceName: bigquery.googleapis.com
      methodSelectors:
      - method: read permission 1
      - method: read permission 2
      - method: etc
    resources:
    - projects/{{ PROJECT_ID }}
// Project Id is a unique number that defines the project that you give ThoughtSpot access to.
----

For more information about ingress rule fields, see link:https://cloud.google.com/vpc-service-controls/docs/ingress-egress-rules?hl=en#ingress-rules-reference[Ingress rules reference^].


'''
> **Related information**
>
> * xref:connections-gbq-prerequisites.adoc[{connection} prerequisites]
> * xref:connections-gbq-add.adoc[Add a {connection} connection]
> * xref:connections-gbq-edit.adoc[Edit a {connection} connection]
> * xref:connections-gbq-remap.adoc[Remap a {connection} connection]
> * xref:connections-gbq-external-tables.adoc[Query external tables from your {connection} connection]
> * xref:connections-gbq-delete-table.adoc[Delete a table from a {connection} connection]
> * xref:connections-gbq-delete-table-dependencies.adoc[Delete a table with dependent objects]
> * xref:connections-gbq-delete.adoc[Delete a {connection} connection]
> * xref:connections-gbq-reference.adoc[Connection reference for {connection}]
//> * xref:connections-query-tags.adoc#tag-gbq[ThoughtSpot query tags in Google BigQuery]
