= Delete a Google {connection} connection
:last_updated: 08/27/2021
:linkattrs:
:experimental:
:page-partial:
:page-aliases: /7.1.0.aug.sw/data-integrate/embrace/gbq-delete-connection.adoc
:connection: BigQuery
:description: Learn how to delete a Google BigQuery connection.

include::partial$connection-delete.adoc[]

'''
> **Related information**
>
> * xref:connections-gbq-add.adoc[]
> * xref:connections-gbq-prerequisites.adoc[{connection} connection prerequisites]
> * xref:connections-gbq-ingress.adoc[]
> * xref:connections-gbq-edit.adoc[Modify a {connection} connection]
> * xref:connections-gbq-remap.adoc[Remap a {connection} connection]
> * xref:connections-gbq-external-tables.adoc[]
> * xref:connections-gbq-delete-table.adoc[Delete a table from a {connection} connection]
> * xref:connections-gbq-delete-table-dependencies.adoc[Delete a table with dependencies from a {connection} connection]
> * xref:connections-gbq-reference.adoc[{connection} connection reference]
//> * xref:connections-query-tags.adoc#tag-gbq[ThoughtSpot query tags in Google BigQuery]