= SAP HANA connection reference
:last_updated: 08/27/2021
:linkattrs:
:page-partial:
:page-aliases: /7.1.0.aug.sw/data-integrate/embrace/embrace-hana-reference.adoc

Learn about the fields used to create an SAP HANA connection.

Here is a list of the fields in an SAP HANA connection.
You need specific information to establish a seamless and secure connection.
All fields are required, except where noted.
[#connection-name]
Connection name::  Enter a new SAP HANA connection name.
[#connection-description]
Connection description::
Provide a short description of the connection.
_(Optional)_
[#host-port]
Host and port::
Enter the host followed by a colon and the port number of the SAP HANA database.
+
Example;; If your host is `192.168.1.1`, and your port is `8080` you would enter `192.168.1.1:8080`.
[#user-id]
User::  Enter the user associated with the SAP HANA database.
[#password]
Password::  Enter the password associated with the user of the SAP HANA database.
[#database]
Database::  Enter the database associated with the SAP HANA database.
