= Synapse connection reference
:last_updated: 03/25/2021
:linkattrs:
:page-partial:
:page-aliases: /data-integrate/embrace/embrace-synapse-reference.adoc
:connection: Synapse
:description: Learn about the fields used to create a Synapse connection in ThoughtSpot Software.

You need specific information to establish a seamless and secure connection.
The following fields are required.

Connection name:: Enter a new {connection} connection name.
Connection description:: Provide a short description of the connection. _(Optional)_
Host:: Enter the host name associated with the {connection} database.
Port:: Enter the port number associated with the {connection} database.
+
IMPORTANT: If you are using SQL Server, enter *1433*.
(Service Account only) User:: Enter the {connection} account username.
+
IMPORTANT: If you are using SQL Server, enter the login for your SQL Server database.
(Service Account only) Password:: Enter the {connection} account password.
Database:: Specify the database associated with the account.
(OAuth only) OAuth Client ID:: Specify the OAuth client ID associated with the account.
(OAuth only) OAuth Client Secret:: Specify the OAuth client secret associated with the account.
(OAuth only) Scope:: Enter this for your Synapse OAuth connection:
+
[source]
--
offline_access openid https://sql.azuresynapse.net/.default
--
+
Scope value is the same for all Synapse OAuth connections.
(OAuth only) Auth Url:: Specify the auth URL associated with the account.
(OAuth only) Access token Url:: Specify the access token URL associated with the account.

'''
> **Related information**
>
> * xref:connections-synapse-add.adoc[Add a connection]
> * xref:connections-synapse-edit.adoc[]
> * xref:connections-synapse-remap.adoc[]
> * xref:connections-synapse-delete-table.adoc[]
> * xref:connections-synapse-delete-table-dependencies.adoc[]
> * xref:connections-synapse-delete.adoc[]
> * xref:connections-synapse-oauth.adoc[]
> * xref:connections-query-tags.adoc#tag-synapse[Synapse query tags]