= Query external tables from your {connection} connection
:last_updated: 9/22/2022
:linkattrs:
:experimental:
:connection: Snowflake
:description: ThoughtSpot supports querying external tables stored in external data stores, such as Amazon S3 or Google Cloud Storage, via your cloud data warehouse.

include::partial$external-table-intro.adoc[]

[#supported-stores-formats]
== Supported data stores and file formats

ThoughtSpot supports any data stores or file formats that {connection} supports. Refer to the {connection}
documentation for more information: https://docs.snowflake.com/en/user-guide/tables-external-intro.html[Introduction to External Tables^].

== Querying your external tables

To query your external tables in ThoughtSpot, follow these steps:

. Ensure that {connection} supports your data store(s) and file format(s). Refer to <<supported-stores-formats,Supported data stores and file formats>>.

. Create the external table(s) in {connection}. For assistance, refer to the {connection} documentation.

. Create your {connection} connection, if you have not already done so. When selecting tables, select the external tables you want to query, as well as any other tables. Refer to xref:connections-snowflake-add.adoc[].
+
NOTE: Ensure that your external tables are in the same database and schema as the database and schema specified in your {connection} connection.

. xref:search.adoc[Search] the data from your external table.

'''
> **Related information**
>
> * xref:connections-snowflake-add.adoc[Add a connection]
> * xref:connections-snowflake-edit.adoc[]
> * xref:connections-snowflake-remap.adoc[]
> * xref:connections-snowflake-delete-table.adoc[]
> * xref:connections-snowflake-delete-table-dependencies.adoc[]
> * xref:connections-snowflake-delete.adoc[]
> * xref:connections-snowflake-oauth.adoc[]
> * xref:connections-snowflake-okta-oauth.adoc[]
> * xref:connections-snowflake-azure-ad-oauth.adoc[]
> * xref:connections-snowflake-best.adoc[Best practices]
> * xref:connections-snowflake-reference.adoc[Reference]
> * xref:connections-query-tags.adoc#tag-snowflake[ThoughtSpot query tags in Snowflake]
> * xref:connections-snowflake-partner.adoc[Partner Connect], with an accompanying xref:connections-snowflake-tutorial.adoc[Tutorial]