= Best practices for Redshift connections
:last_updated: 03/25/2021
:linkattrs:
:experimental:
:page-partial:
:page-aliases: /data-integrate/embrace/embrace-redshift-best.adoc

== Configuring your ThoughtSpot server

We recommend configuring the following settings when creating connections:

* Turn off '`Auto Indexing`', and manually set the Index Type on columns that would be helpful when searching.

xref:support-contact.adoc[Contact ThoughtSpot Support] to do this configuration.

== Optimizing query performance

User experience is strongly impacted by the performance of queries in the underlying database.
Redshift is a columnar MPP database built for analytic workloads, and proper tuning can have a significant impact on query performance.

You should always follow AWS best practices to optimize query performance.
For details, see https://docs.aws.amazon.com/redshift/latest/dg/c-optimizing-query-performance.html[Tuning query performance^] in Amazon's Redshift documentation.

== Workload management and monitoring

We recommend that you implement workload management (WLM) within Redshift to prioritize queries appropriately.
For more information, refer to the following links in Amazon's Redshift documentation:

* Implementation: https://docs.aws.amazon.com/redshift/latest/dg/cm-c-implementing-workload-management.html[Implementing workload management^]
* Workload and performance data: https://docs.aws.amazon.com/redshift/latest/dg/cm-c-wlm-query-monitoring-rules.html#cm-c-wlm-query-monitoring-metrics[System monitoring tables^]

== Concurrency scaling

ThoughtSpot may generate large numbers of concurrent queries.
Redshift's concurrency scaling feature can be enabled to provide consistent query performance during periods of high activity.

For details, see https://docs.aws.amazon.com/redshift/latest/dg/concurrency-scaling.html[Working with concurrency scaling^] in Amazon's Redshift documentation.

== Data modeling

In Redshift, query performance can be improved significantly using Sort and Distribution keys on large tables.
Selecting an optimized compression type can also have a big impact on query performance.

These and other important topics are covered in https://docs.aws.amazon.com/redshift/latest/dg/c_designing-tables-best-practices.html[Amazon Redshift best practices for table design^] in Amazon's Redshift documentation.

== Materialized views

Redshift now supports materialized views, and it is recommended to create a materialized view and use it in place of any complex views or poor performing table joins.

For details, see https://docs.aws.amazon.com/redshift/latest/dg/materialized-view-overview.html[Creating materialized views in Amazon Redshift^] in Amazon's Redshift documentation.

== Defining joins between tables

To search more than one table at the same time in ThoughtSpot, you must define joins between these tables by specifying the columns that contain matching data across two tables.
These columns represent the '`primary key`' and '`foreign key`' of the join.
You can define them in either Redshift or ThoughtSpot.

For details on the syntax for defining primary and foreign keys in Redshift, see https://docs.aws.amazon.com/redshift/latest/dg/r_ALTER_TABLE.html[ALTER TABLE^] in Amazon's Redshift documentation.

For details on defining joins in ThoughtSpot, see xref:relationship-create.adoc[Join a table or view to another data source].
