= Query external tables from your {connection} connection
:last_updated: 9/22/2022
:linkattrs:
:experimental:
:connection: BigQuery

include::partial$external-table-intro.adoc[]

[#supported-stores-formats]
== Supported data stores and file formats

ThoughtSpot supports any data stores or file formats that {connection} supports. Refer to the {connection}
documentation for more information: https://cloud.google.com/bigquery/docs/external-tables[External tables^].

== Querying your external tables

To query your external tables in ThoughtSpot, follow these steps:

. Ensure that {connection} supports your data store(s) and file format(s). Refer to <<supported-stores-formats,Supported data stores and file formats>>.

. Create the external table(s) in {connection}. For assistance, refer to the {connection} documentation.

. Create your {connection} connection, if you have not already done so. When selecting tables, select the external tables you want to query, as well as any other tables. Refer to xref:connections-gbq-add.adoc[].
+
NOTE: Ensure that your external tables are in the same database and schema as the database and schema specified in your {connection} connection.

. xref:search.adoc[Search] the data from your external table.

'''
> **Related information**
>
> * xref:connections-gbq-prerequisites.adoc[Prerequisites]
> * xref:connections-gbq-ingress.adoc[]
> * xref:connections-gbq-add.adoc[Add a Google BigQuery connection]
> * xref:connections-gbq-edit.adoc[]
> * xref:connections-gbq-remap.adoc[]
> * xref:connections-gbq-delete-table.adoc[]
> * xref:connections-gbq-delete-table-dependencies.adoc[]
> * xref:connections-gbq-delete.adoc[]
> * xref:connections-gbq-reference.adoc[Reference]
//> * xref:connections-query-tags.adoc#tag-gbq[Google BigQuery query tags]