= Teradata connection reference
:last_updated: 12/14/2022
:author: Mark Plummer
:experimental:
:linkattrs:
:page-partial:
:page-aliases: /data-integrate/embrace/embrace-teradata-reference.adoc
:description: Learn about the fields used to create a Teradata connection.

Learn about the fields used to create a Teradata connection.

Here is a list of the fields of a Teradata connection.
You need specific information to establish a seamless and secure connection.
All fields are required, except where noted.
[#connection-name]
Connection name::  Enter a new Teradata connection name.
[#connection-description]
Connection description::
Provide a short description of the connection.
_(Optional)_
[#host-id]
Host::  Enter the host associated with the Teradata database.
[#user-id]
User::  Enter the user account associated with the Teradata database.
[#user-application-proxy-user]
Use application proxy user::  Select this if you want to use the Teradata query-banding feature with the user.
+
IMPORTANT: The user must be configured as an application proxy user in Teradata.
[#password]
Password::  Enter the password associated with the user account of the Teradata database.
[#database]
Database::
Enter the database name associated with the Teradata database.
_(Optional)_

'''
> **Related information**
>
> * xref:connections-teradata-add.adoc[Add a Teradata connection]
> * xref:connections-teradata-edit.adoc[]
> * xref:connections-teradata-remap.adoc[]
> * xref:connections-teradata-delete-table.adoc[]
> * xref:connections-teradata-delete-table-dependencies.adoc[]
> * xref:connections-teradata-delete.adoc[]

