= Delete a table with dependencies from an Amazon Redshift connection
:last_updated: 08/27/2021
:linkattrs:
:experimental:
:page-partial:
:page-aliases: /7.1.0.aug.sw/data-integrate/embrace/redshift-delete-table-dependencies.adoc

If you attempt to delete a table with dependent objects, ThoughtSpot blocks the operation until you resolve the dependencies. See xref:connections-redshift-delete-table.adoc[].

include::partial$connection-delete-table-dependencies.adoc[]

'''
> **Related information**
>
> * xref:connections-redshift-add.adoc[Add an Amazon Redshift connection]
> * xref:connections-redshift-edit.adoc[]
> * xref:connections-redshift-remap.adoc[]
> * xref:connections-redshift-delete-table.adoc[]
> * xref:connections-redshift-delete.adoc[]
> * xref:connections-redshift-oauth.adoc[Configure OAuth]
> * xref:connections-redshift-best.adoc[Best practices]
> * xref:connections-aws-secrets.adoc[AWS Secrets Manager]
> * xref:connections-redshift-reference.adoc[Reference]
> * xref:connections-query-tags.adoc#tag-redshift[Redshift query tags]
