= Passthrough functions for Connections
:last_updated: 08/10/2021
:experimental:
:linkattrs:
:page-partial:
:page-aliases: /data-integrate/embrace/embrace-snowflake-passthrough.adoc, /data-integrate/embrace/embrace-gbq-passthrough.adoc, connections-snowflake-passthrough.adoc, connections-gbq-passthrough.adoc
:description: Passthrough functions allow you to send SQL expressions directly to a supported cloud data warehouse, without them being interpreted by ThoughtSpot.


Passthrough functions allow you to send SQL expressions directly to a supported cloud data warehouse, without them being interpreted by ThoughtSpot. Use the passthrough functions in the ThoughtSpot Formula Assistant to call any custom database functions you implemented for your business.

A passthrough function serves as a wrapper around the specific SQL function in the cloud data warehouse. You must ensure that the return data type you use with the passthrough function matches the return type of the cloud data warehouse's SQL function.

For details on all supported passthrough functions, see xref:formula-reference.adoc#passthrough-functions[Passthrough functions].

'''
> **Related information**
>
> * https://docs.aws.amazon.com/redshift/latest/dg/cm_chap_SQLCommandRef.html[Amazon Redshift SQL reference^]
> * https://docs.microsoft.com/en-us/sql/t-sql/functions/functions?view=sql-server-ver15[Microsoft Azure Synapse SQL functions^]
> * https://docs.databricks.com/sql/language-manual/index.html[SQL reference for Databricks SQL^]
> * https://cloud.google.com/bigquery/docs/reference/standard-sql/lexical[Google BigQuery SQL Reference^]
> * https://help.sap.com/viewer/7c78579ce9b14a669c1f3295b0d8ca16/Cloud/en-US/0861a5d054e2464da4f5b50e5a96628e.html[SAP HANA SQL Reference^]
> * https://docs.snowflake.com/en/sql-reference-functions.html[Snowflake’s SQL Function Reference^]
> * https://docs.starburst.io/latest/sql.html[Starburst SQL statement syntax^]
> * https://docs.teradata.com/r/Teradata-Database-Introduction/June-2017/SQL[Teradata SQL^]
