= Delete a table with dependencies from a Snowflake connection
:last_updated: 08/27/2021
:linkattrs:
:experimental:
:page-partial:
:page-aliases: /7.1.0.aug.sw/data-integrate/embrace/snowflake-delete-table-dependencies.adoc

If you attempt to delete a table with dependent objects, ThoughtSpot blocks the operation until you resolve the dependencies. See xref:connections-snowflake-delete-table.adoc[].

include::partial$connection-delete-table-dependencies.adoc[]

'''
> **Related information**
>
> * xref:connections-snowflake-add.adoc[Add a connection]
> * xref:connections-snowflake-edit.adoc[]
> * xref:connections-snowflake-remap.adoc[]
> * xref:connections-snowflake-delete-table.adoc[]
> * xref:connections-snowflake-delete.adoc[]
> * xref:connections-snowflake-oauth.adoc[]
> * xref:connections-snowflake-azure-ad-oauth.adoc[]
> * xref:connections-snowflake-best.adoc[Best practices]
> * xref:connections-snowflake-reference.adoc[Reference]
> * xref:connections-snowflake-partner.adoc[Partner Connect], with an accompanying xref:connections-snowflake-tutorial.adoc[Tutorial]
> * xref:connections-query-tags.adoc#tag-snowflake[Snowflake query tags]