= ThoughtSpot in Snowflake Partner Connect
:last_updated: 05/10/2022
:linkattrs:
:experimental:
:page-partial:
:page-aliases: /data-integrate/embrace/embrace-snowflake-partner.adoc
:description: With Snowflake Partner Connect, you get a free trial of ThoughtSpot Cloud on Snowflake connections.


With Snowflake Partner Connect, you get a free trial of ThoughtSpot Cloud on Snowflake connections.

Snowflake Partner Connect allows you to quickly and easily try out ThoughtSpot connected to Snowflake.

ThoughtSpot in Snowflake Partner Connect benefits:

* 30-day trial
* Easy to sign up
* Up and running in 5 minutes
* Trial data already loaded into Snowflake
* No data modeling required
* Gain first-hand experience of the power of ThoughtSpot search-driven insights

== Prerequisites

* A Snowflake account
+
If you don't have an account, you can sign up for a https://trial.snowflake.com/[free trial^].

* Add the *try.thoughtspot.com* IP address to your list of allowed domains in your Snowflake account: `35.164.213.211`
* Read the xref:connections-snowflake-best.adoc[].

== Sign up for the ThoughtSpot free trial in Snowflake Partner Connect

To sign up for the free trial, do the following:

. Sign in to your Snowflake account.
. Select *Partner Connect*.
. Select *ThoughtSpot*.
The _Connect to ThoughtSpot_ window appears.
. Select *Connect*.
A ThoughtSpot account is created for you and an email titled _Activate Your ThoughtSpot Trial_ is sent to the email address associated with your Snowflake account.
This email contains activation instructions.
. Select *Activate*.
Your browser redirects to https://try.thoughtspot.com/[try.thoughtspot.com^].
+
If you choose *Activate Later*, you can open the email and select *Start Trial Now* to navigate to try.thoughtspot.com.

. At try.thoughtspot.com, do the following:
 ** For *Username*, enter the email address associated with your Snowflake account.
 ** Enter your *Company Name*.
 ** Create a *Password*.
 ** Confirm the *Password*, by re-entering it.
 ** Check the checkbox for *I agree to Terms and Conditions*.
 ** Select *Sign in*.

+
After you sign in, the ThoughtSpot home page appears.

== Using Snowflake connections in the ThoughtSpot free trial

. From the ThoughtSpot home page, a _Connect to Snowflake_ guided tutorial appears at the lower right of the page.
You can play the video, which shows you the entire workflow of connecting to Snowflake.
. Select *Next*, to be guided, step-by-step, through the process of connecting ThoughtSpot to Snowflake, selecting and searching a data source, changing a chart configuration, and more.
. After you finish the tutorials, you are ready to try out your own searches, chart configurations, Liveboard filters, and more.

'''
> **Related information**
>
> * xref:connections-snowflake-tutorial.adoc[]
> * xref:connections-snowflake-add.adoc[Add a connection]
> * xref:connections-snowflake-edit.adoc[]
> * xref:connections-snowflake-remap.adoc[]
> * xref:connections-snowflake-external-tables.adoc[]
> * xref:connections-snowflake-delete-table.adoc[]
> * xref:connections-snowflake-delete-table-dependencies.adoc[]
> * xref:connections-snowflake-delete.adoc[]
> * xref:connections-snowflake-oauth.adoc[]
> * xref:connections-snowflake-okta-oauth.adoc[]
> * xref:connections-snowflake-azure-ad-oauth.adoc[]
> * xref:connections-snowflake-best.adoc[Best practices]
> * xref:connections-snowflake-reference.adoc[Reference]
> * xref:connections-query-tags.adoc#tag-snowflake[ThoughtSpot query tags in Snowflake]