= Starburst connection reference
:last_updated: 08/24/2021
:linkattrs:
:page-partial:
:connection: Starburst
:description: Learn the specific information needed to establish a secure connection to Starburst.

You need specific information to establish a seamless and secure connection.
The following fields are required, except where noted.

[#connection-name]
Connection name:: Enter a new {connection} connection name.
[#connection-description]
Connection description:: Provide a short description of the connection. _(Optional)_
[#host]
Host::
Enter the host name or IP address.
+
Example;; `192.168.1.1`
[#port]
Port:: Enter the port number associated with the {connection} database.
[#user-id]
User:: Enter the {connection} account username.
[#password]
Password:: Enter the {connection} account password. _(Optional)_ Note that SSL must be enabled for password authentication. To enable SSL, enter "SSL=true" under Advanced Configuration.
[#database]
Database:: Specify the database associated with the account. _(Optional)_
[#oauth-client-id]
OAuth Client ID:: Enter the client id of the OAuth application created in the identity provider.
[#oauth-client-secret]
OAuth client secret:: Enter the client secret of the OAuth application created in the identity provider.
[#auth-url]
Auth Url:: Enter the Auth URL associated with the OAuth app in your identity provider.
[#access-token-url]
Access Token Url:: Enter the Access Token Url associated with the OAuth app in your identity provider.

'''
> **Related information**
>
> * xref:connections-starburst-add.adoc[]
> * xref:connections-starburst-edit.adoc[]
> * xref:connections-starburst-remap.adoc[]
> * xref:connections-starburst-delete-table.adoc[]
> * xref:connections-starburst-delete-table-dependencies.adoc[]
> * xref:connections-starburst-delete.adoc[]
> * xref:connections-starburst-oauth.adoc[]
> * xref:connections-starburst-azure-ad-oauth.adoc[]
