= Connection reference for Redshift
:last_updated: 1/25/2025
:page-aliases: /data-integrate/embrace/embrace-redshift-reference.adoc, /admin/ts-cloud/ts-cloud-embrace-redshift-connection-reference.adoc
:linkattrs:
:experimental:
:description: Learn the specific information needed to establish a secure connection to Amazon Redshift.

You need specific information to establish a seamless and secure connection.
The following fields are required, except where noted.

Connection name:: Enter a name for your Redshift connection.
Connection description:: Provide a short description of the connection.
Host:: Enter the host name associated with the database.
Port:: Enter the port number associated with the database.
User:: Enter the Redshift account username.
+
NOTE: This user must have at least *read* access to the *SVV_TABLE_INFO* table.
Password:: Enter the Redshift account password.
Database:: Specify the database associated with the account.
(IAM only) Dbuser:: Specify the db user associated with the account.
(IAM only) Access Key:: Specify the access key associated with the account.
(IAM only) Secret Key:: Specify the secret key associated with the account.
(OAuth only) OAuth Client ID:: Specify the OAuth client ID associated with the account.
(OAuth only) OAuth Client Secret:: Specify the OAuth client secret associated with the account.
(OAuth only) Auth Url:: Specify the Auth Url associated with the account.
(OAuth only) Access token Url:: Specify the Access token URL associated with the account.
(OAuth only) Role ARN:: Specify the role ARN associated with the account.
(OAuth only) DbGroups:: Specify the DbGroups associated with the account.

'''
> **Related information**
>
> * xref:connections-redshift-add.adoc[Add a connection]
> * xref:connections-redshift-edit.adoc[]
> * xref:connections-redshift-remap.adoc[]
> * xref:connections-redshift-external-tables.adoc[]
> * xref:connections-redshift-delete-table.adoc[]
> * xref:connections-redshift-delete-table-dependencies.adoc[]
> * xref:connections-redshift-delete.adoc[]
> * xref:connections-redshift-oauth.adoc[Configure OAuth]
> * xref:connections-redshift-best.adoc[Best practices]
> * xref:connections-query-tags.adoc#tag-redshift[Redshift query tags]
> * xref:connections-aws-secrets.adoc[AWS Secrets Manager]
