= {connection} connection reference
:last_updated: 08/20/2021
:linkattrs:
:page-partial:
:connection: Dremio
:description: Learn the specific information needed to establish a secure connection to your Dremio database.

You need very specific information to establish a seamless and secure connection with your {connection} database.

Here is a list of fields for {connection} connections.

You require all these fields, except the ones we marked _(Optional)_.

[#connection-name]
Connection name::
Enter the name for the new connection.
[#connection-description]
Connection description::
_(Optional)_ Provide a short description of the connection.
[#host]
Host::
Enter the {connection} server host name.
[#http-path]
Port::
{connection} server port.
[#user]
User::
Enter the user associated with the {connection} database.
[#password]
Password::
Enter the password of the user associated with the {connection} database.
[#project-id]
Project id::
_(Optional for {connection} Cloud with Service Account only)_ Enter the project ID of the {connection} database.
[#Schema]
Schema::
_(Optional)_ Enter the schema of the {connection} database.
[#oauth-client-id]
(OAuth only) OAuth Client ID::
Enter the OAuth client ID associated with the user of the {connection} database.
[#oauth-client-secret]
(OAuth only) OAuth Client Secret::
Enter the OAuth client secret associated with the user of the {connection} database.
[#auth-url]
(OAuth only) Auth Url::
Enter the Auth Url associated with the user of the {connection} database.
[#access-token-url]
(OAuth only) Access token Url::
Enter the Access token Url associated with the user of the {connection} database.

'''
> **Related information**
>
> * xref:connections-dremio-add.adoc[]
> * xref:connections-dremio-edit.adoc[]
> * xref:connections-dremio-remap.adoc[]
> * xref:connections-dremio-delete-table.adoc[]
> * xref:connections-dremio-delete-table-dependencies.adoc[]
> * xref:connections-dremio-reference.adoc[]
> * xref:connections-dremio-oauth.adoc[]
> * xref:connections-dremio-delete.adoc[]
