= Remap an Amazon Redshift connection
:last_updated: 08/27/2021
:linkattrs:
:experimental:
:page-partial:
:page-aliases: /7.1.0.aug.sw/data-integrate/embrace/redshift-remap.adoc
:description: Learn how to remap an Amazon Redshift connection.


You can modify the parameters of your connection to the Amazon Redshift database by changing the source mapping `tml` file. ThoughtSpot creates this file automatically, to record the details of the new or updated connections.

include::partial$connection-remapping-caution.adoc[]

To remap an Amazon Redshift connection, follow these steps:

include::partial$connection-remapping-initial-steps.adoc[]

include::partial$connection-remapping-final-steps.adoc[]

'''
> **Related information**
>
> * xref:connections-redshift-add.adoc[Add a connection]
> * xref:connections-redshift-edit.adoc[]
> * xref:connections-redshift-external-tables.adoc[]
> * xref:connections-redshift-delete-table.adoc[]
> * xref:connections-redshift-delete-table-dependencies.adoc[]
> * xref:connections-redshift-delete.adoc[]
> * xref:connections-redshift-oauth.adoc[Configure OAuth]
> * xref:connections-redshift-best.adoc[Best practices]
> * xref:connections-aws-secrets.adoc[AWS Secrets Manager]
> * xref:connections-redshift-reference.adoc[Reference]
> * xref:connections-query-tags.adoc#tag-redshift[Redshift query tags]