= Delete a Snowflake connection
:last_updated: 08/27/2021
:linkattrs:
:experimental:
:page-partial:
:page-aliases: /7.1.0.aug.sw/data-integrate/embrace/snowflake-delete-connection.adoc
:connection: Snowflake

include::partial$liveboards-announcement.adoc[]

include::partial$connection-delete.adoc[]

'''
> **Related information**
>
> * xref:connections-snowflake-add.adoc[Add a Snowflake connection]
> * xref:connections-snowflake-edit.adoc[]
> * xref:connections-snowflake-remap.adoc[]
> * xref:connections-snowflake-external-tables.adoc[]
> * xref:connections-snowflake-delete-table.adoc[]
> * xref:connections-snowflake-delete-table-dependencies.adoc[]
> * xref:connections-snowflake-oauth.adoc[]
> * xref:connections-snowflake-azure-ad-oauth.adoc[]
> * xref:connections-snowflake-okta-oauth.adoc[]
> * xref:connections-snowflake-best.adoc[Best practices]
> * xref:connections-snowflake-reference.adoc[Reference]
> * xref:connections-query-tags.adoc#tag-snowflake[Snowflake query tags]
> * xref:connections-snowflake-partner.adoc[Partner Connect], with an accompanying xref:connections-snowflake-tutorial.adoc[Tutorial]