= Edit an Amazon Redshift connection
:last_updated: 08/27/2021
:linkattrs:
:experimental:
:page-partial:
:page-aliases: /7.1.0.aug.sw/data-integrate/embrace/redshift-edit.adoc
:description: You can edit an Amazon Redshift connection to add tables and columns.

You can edit an Amazon Redshift connection to add tables and columns.

Follow these steps to edit an existing Amazon Redshift connection:

include::partial$connection-edit-initial-steps.adoc[]

include::partial$connection-edit-final-steps.adoc[]

'''
> **Related information**
>
> * xref:connections-redshift-add.adoc[Add a connection]
> * xref:connections-redshift-remap.adoc[]
> * xref:connections-redshift-external-tables.adoc[]
> * xref:connections-redshift-delete-table.adoc[]
> * xref:connections-redshift-delete-table-dependencies.adoc[]
> * xref:connections-redshift-delete.adoc[]
> * xref:connections-redshift-oauth.adoc[Configure OAuth]
> * xref:connections-redshift-best.adoc[Best practices]
> * xref:connections-aws-secrets.adoc[AWS Secrets Manager]
> * xref:connections-redshift-reference.adoc[Reference]
> * xref:connections-query-tags.adoc#tag-redshift[Redshift query tags]