= Query-based subscription and rollover
:last_updated: 11/05/2021
:linkattrs:
:experimental:
:page-aliases:
:description:

The following information defines a subscription term and how query-based consumption credits roll over.

== Subscription term

The subscription term in an order form is the number of years for which base credit packages were purchased.

.Examples
****
- A purchase of one Base-Credit package creates a one-year subscription term.

- A purchase of three Base-Credit packages creates a three-year subscription term.
****

Flexible Credits can be used at any time during the subscription term *after* the Base Credits for the year they were purchased are consumed.

== Rollover of credits

=== Base Credits

Unused Base Credits expire in successive 12-month intervals, beginning with signature to a corresponding order form. They do not roll over.

=== Flexible Credits

Unused Flexible Credits roll over each year within the subscription term in effect*.

Flexible Credits are valid to use throughout the subscription term for which they were purchased. In addition, a portion of flexible credits can be rolled over to a renewal subscription term as described in the following table.

==== Rollover of Flexible Credits
[cols="20%,20%,20%,40%",frame=ends,grid=rows]
|===
|Subscription term |Rollover within subscription term |New subscription term |Rollover at time of new subscription term

|1 year
|N/A
|1 year or multi-year
|Up to 30% of prior contract’s unused Flexible Credits as long as renewal amount >= preceding subscription term.

|Multi-year
|100%
|Multi-year
|Up to 15% of prior contract’s unused Flexible Credits as long as renewal amount >= preceding subscription term.
|===

NOTE: Unused Flexible Credits rolled over from the preceding subscription term expire 12 months after the start date of a new subscription term.
