= Consumption-based pricing
:last_updated: 04/09/2021
:linkattrs:
:page-partial:
:page-aliases: /appliance/consumption-pricing.adoc
:experimental:
:description: ThoughtSpot’s consumption-based pricing model lets you purchase a ThoughtSpot subscription based on your organization's use of the ThoughtSpot product.

ThoughtSpot’s consumption-based pricing model lets you purchase a ThoughtSpot subscription based on your organization's utilization of the ThoughtSpot product. When you purchase ThoughtSpot using consumption-based pricing, ThoughtSpot bills you based on xref:credits[credits]. The ThoughtSpot consumption pricing model is available
both for Connections software deployment on your cloud platform, and ThoughtSpot Cloud.

For more information about pricing, refer to https://www.thoughtspot.com/pricing[ThoughtSpot pricing^].
Each cluster must have a discrete pricing model.

[#credits]
== Credits

You purchase and consume credits with the consumption-based licenses.
A credit is a unit of measure.
When members of your organization use ThoughtSpot, we measure either xref:consumption-pricing-query-based.adoc[query-based], or xref:consumption-pricing-time-based.adoc[time-based] usage. Both types of usage consume available credits. Each active ThoughtSpot user consumes credits.

User activities in ThoughtSpot that consume credits include:

- Performing a search
- Viewing or editing pinboards or answers
- Creating and editing worksheets
- Making administrative changes, or changing setup configuration

[#rights-obligations]
== Using the ThoughtSpot consumption pricing model

We originally introduced the consumption-based pricing model in our ThoughtSpot Cloud offering. You can now use the consumption pricing model when you deploy ThoughtSpot Software in your own cloud environment, and use connections to your data.

You must allow ThoughtSpot to gather usage information from your cluster environment daily. We use a secure TLS-encrypted SSL connection to gather this information, and use it solely for the purpose of measuring credit consumption.

Additionally, you must allow ThoughtSpot to serve usage information to you, for full visibility and accurate reporting of in-product usage and credit consumption. To accomplish this, ThoughtSpot creates a JDBC connection to your cluster, and uses TLS-encrypted SSL transport protocol to serve this data. This usage information is secure and isolated inside our cloud environment.

The following points outline the necessary prerequisites to pricing and using ThoughtSpot based on consumption level.

Supported deployments::
The ThoughtSpot consumption pricing model is available for both https://cloud-docs.thoughtspot.com/[ThoughtSpot Cloud^], and for ThoughtSpot Software deployments that use xref:connections.adoc[] to connect to data.
+
Consumption pricing *does not apply* to ThoughtSpot Software deployments that use the ThoughtSpot Falcon database, where you import/maintain data using xref:dataflow.adoc[DataFlow] or another ETL tool.

Supported releases::
In the 6.3.1 SW release, ThoughtSpot consumption pricing is available only on single-node clusters.
+
Starting with the 6.3.1CU1 release, ThoughtSpot makes consumption pricing available for all multi-node deployments.

Mandatory ports::
ThoughtSpot requires organizations that subscribe to usage-based pricing to open the following ports. Failure to open these ports prevents you from using the consumption-based license.
Port 443;; The outbound port to the IP address that we provide at the time of licensing; we use this to collect usage data.
Port 5439;; The outbound port from the IP address that we provide at the time of licensing; we use this to send you credit consumption data.

'''
> **Related information**
>
> * xref:consumption-pricing-query-based.adoc[Query-based usage]
> * xref:consumption-pricing-query-based-generate.adoc[User actions and queries]
> * xref:consumption-pricing-query-based-subscription.adoc[Subscription and rollover]
> * xref:consumption-pricing-time-based.adoc[Time-based usage]
> * xref:consumption-pricing-storage.adoc[Consumption data storage]
