= Upgrading ThoughtSpot on your own OS to a new release
:last_updated: 5/30/2023
:author: Teresa Killmond
:linkattrs:
:experimental:
:description: Learn how to upgrade your Amazon Linux 2, RHEL, or OEL installation of ThoughtSpot.

Learn how to upgrade your RHEL, OEL, or Al2 installation of ThoughtSpot.

To upgrade your installation of ThoughtSpot, follow these steps:

. Back up your ThoughtSpot cluster.
. Pull the necessary security updates.
. Download the release tarball to each cluster (for online clusters) or to your organization's mirror repository (for offline clusters).
. For offline clusters only, run the `run_offline.sh` script from the ansible tarball.
. Run the `tscli cluster update` command.

'''
> **Related information**
>
> * xref:customer-os.adoc[]
> * xref:customer-os-prerequisites.adoc[]
> * xref:customer-os-artifacts.adoc[]
> * xref:customer-os-untar.adoc[]
> * xref:customer-os-offline-script.adoc[]
> * xref:customer-os-ansible-configure.adoc[]
> * xref:customer-os-install.adoc[]
> * xref:customer-os-add-node.adoc[]
> * xref:customer-os-packages.adoc[Packages installed with ThoughtSpot running on your own OS]