= Packages installed with ThoughtSpot running on your own OS
:author: Teresa Killmond
:last_updated: 5/10/2023
:linkattrs:
:experimental:
:description: To successfully deploy ThoughtSpot, you must have the following packages on each node of your ThoughtSpot cluster: yum, python 3, and R.

To successfully deploy ThoughtSpot in your organization, you must have the following packages on each node of your ThoughtSpot cluster: <<yum,yum>>, <<pip,python 3>>, and <<r,R>>. ThoughtSpot does not install the R packages if you define the xref:customer-os-ansible-configure.adoc#skip_r[skip_r] flag in the ansible playbook.
When the ansible playbook runs, it automatically installs the packages.

ThoughtSpot also uses the third-party software packages listed in xref:third-party.adoc[].

NOTE: If your organization requires that privilege escalation take place through an external tool that integrates with ansible, you must install the packages yourself. The ansible playbook does not install them. Refer to xref:rhel-install-ansible.adoc[].

ThoughtSpot works with the latest version of each package.

[#yum]
[#pip]
[#r]
[tabset]
====
Yum RPM packages for RHEL 7.8 and 7.9, OEL 7.9, and Amazon Linux 2;;
+
--
Download: link:{attachmentsdir}/yum-rpm-packages-rhel.csv[Yum RPM package list for RHEL 7.8 and 7.9 and OEL 7.9].

include::partial$/packages/yum-rpm-packages-rhel.adoc[]
--
Yum RPM packages for RHEL 8.1 - 8.7;;
+
--
Download: link:{attachmentsdir}/yum-rpm-packages-rhel-8.csv[Yum RPM package list for RHEL 8.1 - 8.7].

include::partial$/packages/yum-rpm-packages-rhel-8.adoc[]
--
Python 3 packages;;
+
--
Download: link:{attachmentsdir}/pip-rpm-packages.csv[Python RPM package list].

include::partial$/packages/pip-rpm-packages.adoc[]
--
R packages;;
+
ThoughtSpot does not install the R packages if you define the xref:customer-os-ansible-configure.adoc#skip_r[skip_r] flag in the ansible playbook.
+
--
Download: link:{attachmentsdir}/r-rpm-packages-rhel.csv[R RPM package list].

include::partial$/packages/r-rpm-packages-rhel.adoc[]
--
====

'''
> **Related information**
>
> * xref:customer-os.adoc[]
> * xref:customer-os-prerequisites.adoc[]
> * xref:customer-os-artifacts.adoc[]
> * xref:customer-os-untar.adoc[]
> * xref:customer-os-offline-script.adoc[]
> * xref:customer-os-ansible-configure.adoc[]
> * xref:customer-os-install.adoc[]
> * xref:customer-os-upgrade.adoc[Upgrading ThoughtSpot on your own OS to a new release]
> * xref:customer-os-add-node.adoc[]
