= Contents of the ansible tarball for deployment on your own OS
:last_updated: 5/10/2023
:linkattrs:
:author: Teresa Killmond
:experimental:
:description: Untar the ansible tarball for deployment of ThoughtSpot on your own OS, and see the contents.

Before you can install the ThoughtSpot application on the hosts, you must untar the ansible tarball on your local machine. To download the ansible tarball, refer to xref:customer-os-artifacts.adoc[]. The ansible tarball contains the following files and directories:

`ansible_pkgs`:: *[Offline tarball only]* This contains the yum packages required for installing ansible. If you run ansible on a different node and want to exclude these packages in the ansible playbook, add the `--skip_ansible` flag when you xref:customer-os-offline-script.adoc[run the offline script].

`hosts.sample`::
This is the ansible inventory file for host configuration.

`prod_image`::
This directory contains the ThoughtSpot tools and `tscli`, the ThoughtSpot CLI binary.

python3_pkgs:: *[Offline tarball only]* This contains all the xref:customer-os-packages.adoc[python 3 packages].

`README.md`::
This file contains basic information about the ansible tarball.

`r_pkgs`:: *[Offline tarball only]* This contains all the xref:customer-os-packages.adoc[R packages].

`rpm_gpg`::
This directory contains the https://access.redhat.com/documentation/en-us/red_hat_network/5.0.0/html/client_configuration_guide/ch-gpg-keys[GPG keys^] that authenticate the public repository.

`toolchain`::
This contains the tools that are necessary to compile the instructions you define in the ansible Playbook, the source code, into executables that can run on your device. The toolchain includes a compiler, a linker, and run-time libraries.

`ts-customize.yml`:: This runs as the last step in the preparation process. You can use it to include deployment-specific customizations, such as enabling or disabling a corporate proxy, configuring extra SSH keys, installing extra services, and so on. By default, this script does nothing.

`ts-new.yaml`::
The ansible playbook for new installations.

`ts-update.yaml`::
The ansible playbook for updates.

`ts.yaml`:: The main yaml file that calls the other yaml files.

`yum_pkgs`:: *[Offline tarball only]* This contains all the xref:customer-os-packages.adoc[yum packages] required for installing and running ThoughtSpot.

`yum.repos.d`::
This directory contains information about the yum repository used by the cluster.

== Next steps
For an _offline_ deployment, you must run the `run_offline.sh` script. See xref:customer-os-offline-script.adoc[].

For an _online_ deployment, skip to xref:customer-os-ansible-configure.adoc[Configure and run the ansible playbook].

'''
> **Related information**
>
> * xref:customer-os.adoc[]
> * xref:customer-os-prerequisites.adoc[]
> * xref:customer-os-artifacts.adoc[]
> * xref:customer-os-offline-script.adoc[]
> * xref:customer-os-ansible-configure.adoc[]
> * xref:customer-os-install.adoc[]
> * xref:customer-os-upgrade.adoc[Upgrading ThoughtSpot on your own OS to a new release]
> * xref:customer-os-add-node.adoc[]
> * xref:customer-os-packages.adoc[Packages installed with ThoughtSpot running on your own OS]
