= Data integration
:last_updated: 01/20/2021
:linkattrs:
:page-aliases: /data-integrate/introduction/introduction-data-integration.adoc
:experimental:
:description: This guide explains how to integrate ThoughtSpot with other data sources for loading data.
:jira: SCAL-229854 (simba jdbc/odbc removal)

This guide explains how to integrate ThoughtSpot with other data sources for loading data.

== Methods for loading data

There are multiple ways to load data into ThoughtSpot, depending on your goals and where the data is located.
Always consider your requirements for recurring loads when planning how best to bring the data into ThoughtSpot.

Here are the options, with information on where to find the documentation for each method:

ThoughtSpot Loader (tsload)::
  ThoughtSpot Loader is a command line tool to load CSV files into an existing database schema in ThoughtSpot. This is the fastest way to load extremely large amounts of data, and it can be run in parallel. You can also use this method to script recurring loads.
DataFlow::
With DataFlow, you can move data into ThoughtSpot’s in-memory Falcon database from most databases.
