= Azure Synapse connection reference
:last_updated: 09/10/2021
:linkattrs:
:experimental:
:page-aliases: /data-integrate/dataflow/dataflow-azure-synapse-reference.adoc

Learn about the fields used to create an Azure Synapse connection with ThoughtSpot DataFlow.

Here is a list of the fields for an Azure Synapse connection in ThoughtSpot DataFlow.
You need specific information to establish a seamless and secure connection.

[#connection-properties]
== Connection properties
[#dataflow-azure-synapse-conn-connection-name]
Connection name:: Name your connection. Mandatory field.
Example:;; AzureSynapseConnection
[#dataflow-azure-synapse-conn-connection-type]
Connection type:: Choose the Azure Synapse connection type. Mandatory field.
Example:;; Azure Synapse
[#dataflow-azure-synapse-conn-host]
Host:: Specify the name of the server. Mandatory field.
Example:;; http://www.example.net/
[#dataflow-azure-synapse-conn-port]
Port:: Specify the connection port for Azure Synapse. Mandatory field.
Example:;; 1234
[#dataflow-azure-synapse-conn-user]
User::
Specify the user who connects to Azure Synapse.
This user must have data access privileges. Mandatory field.
Example:;; user1
[#dataflow-azure-synapse-conn-password]
include::partial$dataflow/password.adoc[]

[#dataflow-azure-synapse-conn-jdbc-options]
include::partial$dataflow/jdbc-options.adoc[]
[#dataflow-azure-synapse-conn-database]
Database:: Specify Database details like name, alias name, schema. Mandatory field.
Example:;; di_src

[#sync-properties]
== Sync properties
[#dataflow-azure-synapse-sync-data-extraction-mode]
Data extraction mode:: Specify the extraction type. Optional field.
Example:;; BCP
Valid Values:;; JDBC, BCP
Default:;; JDBC
[#dataflow-azure-synapse-sync-column-delimiter]
Column delimiter:: Specify the column delimiter character. Mandatory field.
Example:;; , (comma)
Valid Values:;; Any character, (comma, semicolon) or a number.
If using a number, system uses its ASCII value as delimiter.
Default:;; , (comma)
[#dataflow-azure-synapse-sync-null-value]
Null value::
Specify the string literal that represents NULL on the source.
When loading data, the system replaces this with NULL.
Optional field. +
Available only when *Data extraction mode* is _BCP_.
Example:;; NULL
Valid Values:;; Any string literal
Default:;; NULL
[#dataflow-azure-synapse-sync-enclosing-character]
Enclosing character::
Specify if text columns in the source data are enclosed in quotes;
if yes, single quotes or double quotes. Optional field.
Example:;; Double
Valid Values:;; Single, Double
Default:;; Double
Other notes:;; Required if text data uses newline character or delimiter character.
[#dataflow-azure-synapse-sync-escape-character]
Escape character:: Specify the escape character if using a text qualifier in the source data. Optional field.
Example:;; \"
Valid Values:;; Any ASCII character
Default:;; \"
[#dataflow-azure-synapse-sync-fetch-size]
Fetch size::
Specify the number of rows fetched into memory at the same time.
If the value is 0, system fetches all rows at the same time.
Optional field. +
 Available only when *Data extraction mode* is _JDBC_.
 Example:;; 1000
 Valid Values:;; Any numeric value
 Default:;; 1000
[#dataflow-azure-synapse-sync-max-ignored-rows]
include::partial$dataflow/max-ignored-rows.adoc[]

[#dataflow-azure-synapse-sync-ts-load-options]
include::partial$dataflow/ts-load-options.adoc[]
