= SAP HANA DataFlow connection reference
:last_updated: 07/7/2020

Learn about the fields used to create an SAP HANA Server Enterprise connection with ThoughtSpot DataFlow.

Here is a list of the fields for an SAP HANA connection in ThoughtSpot DataFlow.
You need specific information to establish a seamless and secure connection.

[#connection-properties]
== Connection properties

[#dataflow-sap-hana-conn-connection-name]
Connection name:: Name your connection.
+
Mandatory field.
+
*Example:*
+
SAPHANAConnection

[#dataflow-sap-hana-conn-connection-type]
Connection type:: Choose the SAP HANA connection type.
+
Mandatory field.
+
*Example:*
+
SAP HANA

[#dataflow-sap-hana-conn-host]
Host:: Specify the hostname or the IP address of the SAP HANA system.
+
Mandatory field.
+
*Example:*
+
www.example.com

[#dataflow-sap-hana-conn-port]
Port:: Specify the port associated with the SAP HANA system.
+
Mandatory field.
+
*Example:*
+
1234

[#dataflow-sap-hana-conn-user]
User:: Specify the user id that will be used to connect to the SAP HANA system. This user should have necessary privileges to access the data in the databases.
+
Mandatory field.
+
*Example:*
+
userdi

[#dataflow-sap-hana-conn-password]
Password:: Specify the password for the user.
+
Mandatory field.
+
*Example:*
+
pswrd234%!

[#dataflow-sap-hana-conn-database]
Database:: Collection of information that is organized so that it can be easily accessed, managed and updated.
+
Mandatory field.
+
*Example:*
+
SYSTEMDB

[#dataflow-sap-hana-conn-jdbc-options]
JDBC options:: Specify the options associated with the JDBC URL.
+
Optional field.
+
*Example:*
+
`jdbc:sqlserver://[serverName[\instanceName][:portNumber]]`
+
*Other notes:*
+
Advanced configuration

[#sync-properties]
== Sync properties

[#dataflow-sap-hana-sync-column-delimiter]
Column delimiter:: Specify the delimiter to use as the column delimiter for the extracted data.
+
Mandatory field.
+
*Example:*
+
1
+
*Valid Values:*
+
Any printable ASCII character or decimal value for ASCII character
+
*Default:*
+
1

[#dataflow-sap-hana-sync-enclosing-character]
Enclosing character:: Specify if the text columns in the source data needs to be enclosed in quotes.
+
Optional field.
+
*Example:*
+
DOUBLE
+
*Valid Values:*
+
SINGLE, DOUBLE
+
*Default:*
+
DOUBLE
+
*Other notes:*
+
This is required if the text data has newline character or delimiter character.

[#dataflow-sap-hana-sync-escape-character]
Escape character:: Specify the escape character if using a text qualifier in the source data.
+
Optional field.
+
*Example:*
+
\"
+
*Valid Values:*
+
Any ASCII character
+
*Default:*
+ \"

[#dataflow-sap-hana-sync-fetch-size]
Fetch size:: Specify the number of rows at a time to fetch and process in memory. If you specify zero, the system extracts all rows at once.
+
Mandatory field.
+
*Example:*
+
1000
+
*Valid Values:*
+
Any numeric value
+
*Default:*
+
1000

[#dataflow-sap-hana-sync-ts-load-options]
TS load options:: Specifies the parameters passed with the `tsload` command, in addition to the commands already included by the application. The format for these parameters is:
+
`--<param_1_name> <optional_param_1_value>`
+
`--<param_2_name> <optional_param_2_value>`
+
Optional field.
+
*Example:*
+
--max_ignored_rows 0
+
*Valid Values:*
+
--user "dbuser" --password "$DIWD" --target_database "ditest" --target_schema "falcon_schema"
+
*Default:*
+
--max_ignored_rows 0

'''
> **Related information**
>
> * xref:dataflow-sap-hana-add.adoc[Add a connection]
> * xref:dataflow-sap-hana-sync.adoc[Sync data]
