= Define a synonym
:last_updated: 02/01/2021
:linkattrs:
:experimental:
:page-aliases: /admin/data-modeling/change-visibility-synonym.adoc

Make a column easier to find by assigning to it a synonym.This is helpful, for example, when different departments refer to the data using different terminology.

When users search a data source, they might try typing different words to try to retrieve a particular column.
This could be due to different groups in your organization using different terms for the same data.
Or maybe your users just intuitively use different words when searching for that item.
Using synonyms allows them to access the data even if the term they choose isn't the same as the actual column name.

You can set column synonyms for columns in tables, user imported data, and worksheets.
The returned table or chart uses the _actual column name_, but the search bar reflects the term the user typed in (the synonym).

To create a synonym for a column:

. Find the column for which you want to add synonyms.
. Select its *Synonyms*.
. Enter a comma-separated list of the synonyms.
+
If a synonym is more than one word, enclose it in double quotes.
If you are using the Web interface, you would type:
+
----
 profit,"gross profit"
----
+
If you are using the model file, the list of synonyms must be enclosed in  square brackets:
+
----
 [profit, "gross profit"]
----

. Save your changes.

'''
> **Related information**
>
> * xref:data-modeling.adoc[]
> * xref:data-modeling-visibility.adoc[]
> * xref:data-modeling-column-basics.adoc[Set column name, description, and type]
> * xref:data-modeling-aggreg-additive.adoc[Set additive and aggregate values]
> * xref:spotiq-data-model-preferences.adoc[]
> * xref:data-modeling-index.adoc[Manage suggestion indexing]
> * xref:data-modeling-geo-data.adoc[Add a geographical data setting]
> * xref:data-modeling-patterns.adoc[Set number, date, currency formats]
> * xref:data-modeling-attributable-dimension.adoc[Change the attribution dimension setting]

