= MemSQL connection reference
:last_updated: 09/10/2021
:page-aliases: /data-integrate/dataflow/dataflow-memsql-reference.adoc
:experimental:
:linkattrs:

Learn about the fields used to create a MemSQL connection with ThoughtSpot DataFlow.

Here is a list of the fields for a MemSQL connection in ThoughtSpot DataFlow.
You need specific information to establish a seamless and secure connection.

[#connection-properties]
== Connection properties
[#dataflow-memsql-conn-connection-name]
Connection name:: Name your connection. Mandatory field.
Example:;;  MemSQLConnection
[#dataflow-memsql-conn-connection-type]
Connection type:: Choose the MemSQL connection type. Mandatory field.
Example:;; MemSQL
[#dataflow-memsql-conn-platform-type]
Platform type:: Specify the environment to execute the connection. Mandatory field.
Example:;; On Premise
Valid Values:;; On Premise, Managed Service
Default:;; Managed Service
[#dataflow-memsql-conn-host-name]
Host name:: Specify the hostname or the IP address of the MemSQL system Mandatory field.
Example:;;  www.example.com
[#dataflow-memsql-conn-port]
Port:: Specify the port associated to the MemSQL system Mandatory field.
Example:;; 1234
[#dataflow-memsql-conn-user]
User:: Specify the user id that will be used to connect to the MemSQL system.This user should have necessary privileges to access the data in the databases. Mandatory field.
Example:;; userdi
[#dataflow-memsql-conn-password]
Password:: Specify the password for the User Mandatory field.
Example:;; pswrd234%!
[#dataflow-memsql-conn-authentication-type]
Authentication type::
Specifies the type of security protocol to connect to the instance.
Based on the type of security select the authentication type and provide details.
Mandatory field.
+
For On Premise Platform Type only.

Example:;; Password authentication
Valid Values:;; Password authentication, Kerberos
Default:;; Password authentication
[#dataflow-memsql-conn-kdc-host]
KDC Host:: Specify KDC Host Name where as KDC (Kerberos Key Distribution Center) is a service than runs on a domain controller server role.
Mandatory field.
+
For Kerberos authentication only.

Example:;; my_email@example.com
[#dataflow-memsql-conn-default-realm]
Default realm:: A Kerberos realm is the domain over which a Kerberos authentication server has the authority to authenticate a user, host or service.
Mandatory field.
+
For Kerberos authentication only.
+
Example:;; realm1.example.com
[#dataflow-memsql-conn-keytab]
Keytab:: To authenticate via a key-tab you must have supporting key-tab file which is generated by Kerberos Admin and also requires the user principal associated with Key-tab ( Configured while enabling Kerberos)
Mandatory field.
+
For Kerberos authentication only.

Example:;; /app/keytabs/labuser.keytab
[#dataflow-memsql-conn-principle]
Principle:: To authenticate via a key-tab you must have supporting key-tab file which is generated by Kerberos Admin and also requires the user principal associated with Key-tab ( Configured while enabling Kerberos)
Mandatory field.
+
For Kerberos authentication only.

Example:;; labuser@labdp.example.com
[#dataflow-memsql-conn-ssl-encryption]
SSL encryption:: To ensure the data is encrypted use additional security feature such as SSL.
Optional field.
+
For On Premise Platform Type only.
+
[#dataflow-memsql-conn-trust-store]
Trust store:: Specify the TLS/SSL client certificate store for SSL Client Authentication (2-way SSL)
Mandatory field.
+
For SSL authentication only.
+
Example:;;  trust store path
[#dataflow-memsql-conn-trust-store-password]
Trust store password:: Specify the password for the TLS/SSL client certificate.
Mandatory field.
+
For SSL authentication only.

Example:;; password

[#dataflow-memsql-conn-jdbc-options]
include::partial$dataflow/jdbc-options.adoc[]

[#sync-properties]
== Sync properties
[#dataflow-memsql-sync-column-delimiter]
Column delimiter:::: Specify the column delimiter character. Mandatory field.
Example:;; 1
Valid Values:;; Any printable ASCII character or decimal value for ASCII character
Default:;; The delimiter specified in sync
[#dataflow-memsql-conn-escape-character]
Escape character:: Specify this if the text qualifier is mentioned. This should be the character which escapes the text qualifier character in the source data. Optional field.
Example:;; "
Valid Values:;; Any ASCII character
Default:;; "
[#dataflow-memsql-conn-enclosing-character]
Enclosing character:: Specify if the text columns in the source data needs to be enclosed in quotes. Optional field.
Example:;; DOUBLE
Valid Values:;; SINGLE, DOUBLE
Default:;; DOUBLE
Other notes:;; This is required if the text data has newline character or delimiter character.
[#dataflow-memsql-conn-max-ignored-rows]
include::partial$dataflow/max-ignored-rows.adoc[]

[#dataflow-memsql-conn-ts-load-options]
TS load options:: Specifies the parameters passed with the `tsload` command, in addition to the commands already included by the application.The format for these parameters is:
+
`--<param_1_name> <optional_param_1_value>`
+
`--<param_2_name> <optional_param_2_value>`
Optional field.

Example:;; --max_ignored_rows 0
Valid Values:;; --null_value +
 --escape_character +
  --max_ignored_rows 0
Default:;; --max_ignored_rows 0


> **Related information**
>
> * xref:dataflow-tips.adoc[Dataflow tips]
