= Sync data through Splunk connection
:last_updated: 3/22/2021
:experimental:
:linkattrs:
:page-aliases: /data-integrate/dataflow/dataflow-splunk-sync.adoc

After using ThoughtSpot DataFlow to establish a connection to a Splunk file system, you can create automatic data updates, to seamlessly refresh your data.

include::partial$sync-for-file-systems.adoc[]

. Specify the sync properties for files:
xref:dataflow-splunk-reference.adoc#dataflow-splunk-sync-column-delimiter[Column delimiter]::
Specify the column delimiter character.
xref:dataflow-splunk-reference.adoc#dataflow-splunk-sync-escape-character[Escape character]::
Specify this if the text qualifier is mentioned.
This should be the character which escapes the text qualifier character in the source data.
xref:dataflow-splunk-reference.adoc#dataflow-splunk-sync-enclosing-character[Enclosing character]::
Specify if the text columns in the source data needs to be enclosed in quotes.
xref:dataflow-splunk-reference.adoc#dataflow-splunk-sync-max-ignored-rows[Max ignored rows]::
Abort the transaction after encountering 'n' ignored rows
xref:dataflow-splunk-reference.adoc#dataflow-splunk-sync-ts-load-options[TS load options]::
Specify the parameters passed with the `tsload` command, in addition to the commands already included by the application.
+
See xref:dataflow-splunk-reference.adoc#sync-properties[Sync properties] for details, defaults, and examples.
. Save your work by clicking *Save*.
+
Alternatively, click *Save and sync now* to save your work and sync data at the same time.

'''
> **Related information**
>
> * xref:dataflow-splunk-reference.adoc#sync-properties[DataFlow splunk sync properties]
