= Sync data through an Exadata connection
:last_updated: 9/10/2021
:page-aliases: /data-integrate/dataflow/dataflow-exadata-sync.adoc
:experimental:
:linkattrs:

After using ThoughtSpot DataFlow to establish a connection to an Exadata database, you can create automatic data updates, to seamlessly refresh your data.

include::partial$sync-for-databases.adoc[]

. Specify the sync properties for Exadata:
xref:dataflow-exadata-reference.adoc#dataflow-exadata-sync-data-extraction-mode[Data extraction mode]::
Specify the extraction type.
xref:dataflow-exadata-reference.adoc#dataflow-exadata-sync-column-delimiter[Column delimiter]::
Specify the column delimiter character.
xref:dataflow-exadata-reference.adoc#dataflow-exadata-sync-null-value[Null Value]::
Specifies the string literal that should indicate the null value in the extracted data.
During the data load the column value matching this string will be loaded as null in the target.
xref:dataflow-exadata-reference.adoc#dataflow-exadata-sync-escape-character[Escape character]::
Specify this if the text qualifier is mentioned.
This should be the character which escapes the text qualifier character in the source data.
xref:dataflow-exadata-reference.adoc#dataflow-exadata-sync-enclosing-character[Enclosing character]::
Specify if the text columns in the source data needs to be enclosed in quotes.
xref:dataflow-exadata-reference.adoc#dataflow-exadata-sync-max-ignored-rows[Max ignored rows]::
Abort the transaction after encountering 'n' ignored rows
xref:dataflow-exadata-reference.adoc#dataflow-exadata-sync-fetch-size[Fetch size]::
Specify the number of rows to be fetched at a time and processed in memory.
If the value specified is zero then, all rows are extracted at once.
////
xref:dataflow-exadata-reference.adoc#dataflow-exadata-sync-file-type[File Type]::
Specify type of the file
xref:dataflow-exadata-reference.adoc#dataflow-exadata-sync-lf-string[LF String]::
Specifies if the data has new line characters or not, so that these new line characters can be identified separately.
xref:dataflow-exadata-reference.adoc#dataflow-exadata-sync-compression[Compression]::
Specify this if the file is compressed
xref:dataflow-exadata-reference.adoc#dataflow-exadata-sync-encryption[Encryption]::
Specify if the data needs to be encrypted
xref:dataflow-exadata-reference.adoc#dataflow-exadata-sync-date-style[Date Style]::
Specifies how to interpret the date format
xref:dataflow-exadata-reference.adoc#dataflow-exadata-sync-date-delimiter[Date Delimiter]::
Specifies the separator used in the date format.
xref:dataflow-exadata-reference.adoc#dataflow-exadata-sync-time-style[Time Style]::
Specifies the format of the time portion in the data.
xref:dataflow-exadata-reference.adoc#dataflow-exadata-sync-time-delimiter[Time Delimiter]::
Specifies the character used as separate the time components.
////
xref:dataflow-exadata-reference.adoc#dataflow-exadata-sync-tsload-options[TS load options]:: Specifies the parameters passed with the `tsload` command, in addition to the commands already included by the application.
+
The format for these parameters is:
+
[source]
----
--<param_1_name> <optional_param_1_value>
--<param_2_name> <optional_param_2_value>
----
+
See xref:dataflow-exadata-reference.adoc#sync-properties[Sync properties] for details, defaults, and examples.
. Save your work by clicking *Save*.
+
Alternatively, click *Save and sync now* to save your work and sync data at the same time.

'''
> **Related information**
>
> * xref:dataflow-exadata-reference.adoc#sync-properties[DataFlow Exadata sync properties]
