= Snowflake connection reference for DataFlow
:last_updated: 09/09/2021
:experimental:
:linkattrs:
:page-aliases: /data-integrate/dataflow/dataflow-snowflake-reference.adoc

Learn about the fields used to create a Snowflake connection with ThoughtSpot DataFlow.

Here is a list of the fields for a Snowflake connection in ThoughtSpot DataFlow.
You need specific information to establish a seamless and secure connection.

[#connection-properties]
== Connection properties
[#dataflow-snowflake-conn-connection-name]
Connection Properties:: Name your connection. Mandatory field.
Example:;; SnowflakeConnection
[#dataflow-snowflake-conn-connection-type]
Connection type:: Choose the Snowflake connection type. Mandatory field.
Example:;; Snowflake
[#dataflow-snowflake-conn-user]
User::
Specify the user to connect to Snowflake.
This user must have data access privileges to the databases. Mandatory field.
Example:;; user1
[#dataflow-snowflake-conn-password]
include::partial$dataflow/password.adoc[]

[#dataflow-snowflake-conn-account]
Account:: Specify the account to connect to the Snowflake database. Mandatory field.
Example:;; example_account
[#dataflow-snowflake-conn-role]
Role:: Specify the role that defines the set of privileges assigned to a user or a user group. Mandatory field.
Example:;; Developer
Valid Values:;; Developer, Operator, Business Analyst, Public, Scheduler Read, Scheduler Write, Scheduler Execute
Default:;; Public
[#dataflow-snowflake-conn-jdbc-options]
include::partial$dataflow/jdbc-options.adoc[]
[#dataflow-snowflake-conn-warehouse]
Warehouse:: Choose the warehouse of databases. Mandatory field.
Example:;; demo_wh
[#dataflow-snowflake-conn-keep-connection-alive]
Keep connection alive::
Specify if system must force the user to log in again after a period of inactivity. +
 &bull;
When `TRUE`, Snowflake keeps the session active indefinitely, even if there is no user activity. +
 &bull;
When set to `FALSE` user must log in after four hours of inactivity. Optional field.
Example:;; TRUE
Valid Values:;; TRUE, FALSE
Default:;; TRUE
Other notes:;; Advanced configuration.

[#sync-properties]
== Sync properties
[#dataflow-snowflake-sync-data-extraction-mode]
Data extraction mode:: Specify the extraction type. Optional field.
Example:;; JDBC
Valid Values:;; JDBC, Bulk export
Default:;; Bulk export
[#dataflow-snowflake-sync-column-delimiter]
Column delimiter:: Specify the column delimiter character. Mandatory field.
Example:;; 1
Valid Values:;; Any printable ASCII character or decimal value for ASCII character
Default:;; 1
[#dataflow-snowflake-sync-enclosing-character]
Enclosing character:: Specify if text column in the data source needs to be enclosed in quotes. Optional field.
Example:;; DOUBLE
Valid Values:;; SINGLE, DOUBLE
Default:;; DOUBLE
Other notes:;; Required when text data contains a newline character or delimiter character.
[#dataflow-snowflake-sync-escape-character]
Escape character:: Specify the escape character if using a text qualifier in the source data. Optional field.
Example:;; \"
Valid Values:;; Any ASCII character
Default:;; \"
[#dataflow-snowflake-sync-escape-unclosed-field]
Escape unclosed field::
Specify this if the text qualifier is mentioned.
This should be the character which escapes the text qualifier character in the source data. Optional field.
Example:;; NONE
Valid Values:;; NONE
Default:;; NONE
[#dataflow-snowflake-sync-field-optionally-enclosed-by]
Field optionally enclosed by:: Specify if the text columns in the source data needs to be enclosed in quotes. Optional field.
Example:;; DOUBLE
Valid Values:;; None, Double
Default:;; DOUBLE
[#dataflow-snowflake-sync-null-if]
Null If::
Specify the string literal that indicates NULL value in the extracted data.
During data loading, column values that match this string loaded as NULL in the target. Optional field.
Example:;; NULL
Valid Values:;; NULL
Default:;; NULL
[#dataflow-snowflake-sync-stage-location]
Stage location:: Specify a temporary staging server Snowflake has to use while DataFlow extracts data. Mandatory field.
Example:;; /tmp
Valid Values:;; /tmp
Default:;; /tmp
[#dataflow-snowflake-sync-max-file-size]
Max file size:: Specify the maximum size of each file in the stage location, in bytes. Mandatory field.
Example:;; 16000000
Valid Values:;; Any numeric value
Default:;; 16000000
[#dataflow-snowflake-sync-parallel-threads]
Parallel threads:: Specify the number of parallel threads to unload data. Mandatory field.
Example:;; 4
Valid Values:;; Any numeric value
Default:;; 4
[#dataflow-snowflake-sync-fetch-size]
Fetch size::
Specify the number of rows fetched into memory at the same time.
If the value is 0, system fetches all rows at the same time. Optional field.
Example:;; 1000
Valid Values:;; Any numeric value
Default:;; 1000
[#dataflow-snowflake-sync-max-ignored-rows]
include::partial$dataflow/max-ignored-rows.adoc[]

[#dataflow-snowflake-sync-ts-load-options]
include::partial$dataflow/ts-load-options.adoc[]
