= Dremio connection reference
:last_updated: 9/9/2021
:experimental:
:linkattrs:
:page-aliases: /data-integrate/dataflow/dataflow-dremio-reference.adoc

Learn about the fields used to create a Dremio connection with ThoughtSpot DataFlow.

Here is a list of the fields for a Dremio connection in ThoughtSpot DataFlow.
You need specific information to establish a seamless and secure connection.

[#connection-properties]
== Connection properties

[#dataflow-dremio-conn-connection-name]
Connection name::
Name your connection.
+
Mandatory field.

Example;;
DremioConnection

[#dataflow-dremio-conn-connection-type]
Connection type::
Choose the Dremio connection type.
+
Mandatory field.

Example;;
Dremio

[#dataflow-dremio-conn-host]
Host::
Specify the hostname or the IP address of the Dremio system
+
Mandatory field.

Example;;
www.example.com

[#dataflow-dremio-conn-port]
Port::
Specify the port associated to the Dremio system
+
Mandatory field.

Example;;
1234
Default;;
31010

[#dataflow-dremio-conn-user]
User::
Specify the user to connect to Dremio. This user must have data access privileges.
+
Mandatory field.

Example;;
userdi

[#dataflow-dremio-conn-password]
Password::
Specify the password for the User.
+
Mandatory field.

Example;;
pswrd234%!

[#dataflow-dremio-conn-jdbc-options]
JDBC options::
Specify the options associated with the JDBC URL.
+
Optional field.

Example;;
+
----
jdbc:sqlserver://[serverName[\instanceName][:portNumber]]`
----
Note;;
Advanced configuration

[#sync-properties]
== Sync properties

[#dataflow-dremio-sync-column-delimiter]
Column delimiter::
Specify the column delimiter character.
+
Mandatory field.
Example;;
1
Valid values;;
Any printable ASCII character or the decimal value for ASCII character
Default;;
1

[#dataflow-dremio-sync-enclosing-character]
Enclosing character::
Specify when the text columns in the source data must be enclosed in quotes.
+
Optional field.

Example;;
DOUBLE

Valid values;;
SINGLE, DOUBLE

Default;;
DOUBLE

Note;;
Required when the text data contains newline or delimiter characters.

[#dataflow-dremio-sync-escape-character]
Escape character::
Specify this if the text qualifier is mentioned. This should be the character which escapes the text qualifier character in the source data.
+
Optional field.

Example;;
\""
Valid values;;
Any ASCII character
Default;;
\""

[#dataflow-dremio-sync-sync-properties]
Sync Properties::
Optional field.

[#dataflow-dremio-sync-fetch-size]
Fetch size::
Specify the number of rows to fetch at one time, and process in memory.
+
If the value specified is `0`, then DataFlow extracts all rows at the same time.
+
Optional field.

Example;;
`1000`
Valid values;;
Any numeric value
Default;;
`1000`

[#dataflow-dremio-sync-max-ignored-rows]
include::partial$dataflow/max-ignored-rows.adoc[]

[#dataflow-dremio-sync-ts-load-options]
TS load options::
Specifies the parameters passed with the `tsload` command, in addition to the commands already included by the application.
+
The format for these parameters is:
+
----
--<param_1_name><optonal_param_1_value>
--<param_2_name><optonal_param_21_value>
----
+
Optional field.

Example;;
+
----
--max_ignored_rows 0
----
Valid values;;
+
----
--null_value """"
--escape_character """"
--max_ignored_rows 0
----
Default;;
+
----
--max_ignored_rows 0
----
