= Google Cloud Storage connection reference
:last_updated: 9/10/2021
:experimental:
:linkattrs:
:page-aliases: /data-integrate/dataflow/dataflow-google-cloud-storage-reference.adoc

Learn about the fields used to create an Google Cloud Storage connection with ThoughtSpot DataFlow.

Here is a list of the fields for a Google Cloud Storage connection in ThoughtSpot DataFlow.
You need specific information to establish a seamless and secure connection.

[#connection-properties]
== Connection properties
[#dataflow-google-cloud-storage-conn-connection-name]
Connection name:: Name your connection. Mandatory field.
Example:;; GoogleCloudStorageConnection
[#dataflow-google-cloud-storage-conn-connection-type]
Connection type:: Choose the Google Cloud storage connection type. Mandatory field.
Example:;; Google Cloud storage
[#dataflow-google-cloud-storage-conn-project-id]
Project ID:: The identification number given to particular project and its always unique. Mandatory field.
Example:;; myproject-1234
[#dataflow-google-cloud-storage-conn-authentication-type-]
Authentication type:: It can be either Service Account or Access Tokens. Mandatory field.
Example:;; Service Account
Valid Values:;; Service Account, Access Token
Default:;; Service Account
[#dataflow-google-cloud-storage-conn-service-account-key-or-access-token]
Service account key or access token:: Provide the Service Account key when authentication type is selected as Service account and token when access token is selected as authentication type. Mandatory field.
Example:;; ABCDEFGH245HIJK
[#dataflow-google-cloud-storage-conn-bucket-]
Bucket:: To specify GCS bucket name. Mandatory field.
Example:;; bucket
////
[#dataflow-google-cloud-storage-conn-file-location-]
File location:: Specify directory of source on agent location. Mandatory field.
////
[#dataflow-google-cloud-storage-conn-use-proxy]
Use proxy:: If required, to use a proxy, select the check box Use Proxy and provide the details. Optional field.
Other notes:;; These are under Advanced configuration.
[#dataflow-google-cloud-storage-conn-host]
Host:: Specify the hostname or the IP address of the GCS system. Mandatory field.
Example:;; www.example.com
[#dataflow-google-cloud-storage-conn-port]
Port:: Specify the port associated to the GCS system. Mandatory field.
Example:;; 1234
[#dataflow-google-cloud-storage-conn-protocol]
Protocol:: It can be either http or https. Mandatory field.
Example:;; http
Valid Values:;; http, https
Default:;; http

[#sync-properties]
== Sync properties
[#dataflow-google-cloud-storage-sync-file-name]
File name:: Specify name of the file. Mandatory field.
Example:;; PRODUCT.csv
Valid Values:;; Any string literal
Default:;; The name of the file used to create sync
Other notes:;; To specify wildcard pattern use '*' character in the file name
[#dataflow-google-cloud-storage-sync-enable-archive-on-success]
Enable archive on success:: Specify if file needs to be archived once it is succeeded. Optional field.
Example:;; No
Valid Values:;; Yes, No
Default:;; No
[#dataflow-google-cloud-storage-sync-delete-file-on-success]
Delete file on success:: Specify if file needs to be deleted after execution is successful. Optional field.
Example:;; No
Valid Values:;; Yes, No
Default:;; No
[#dataflow-google-cloud-storage-sync-column-delimiter]
Column delimiter:: Specify the column delimiter character. Mandatory field.
Example:;; ,
Valid Values:;; Any printable ASCII character or decimal value for ASCII character
Default:;; The delimiter specified in sync
[#dataflow-google-cloud-storage-sync-skip-header-rows]
Skip header rows:: Skip the number of header rows specified while loading the data. Optional field.
Example:;; 5
Valid Values:;; Any numeric value
Default:;; 0
[#dataflow-google-cloud-storage-sync-compression]
Compression:: Specify this if the file is compressed and what kind of compressed file it is. Mandatory field.
Example:;; gzip
Valid Values:;; None, gzip
Default:;; None
[#dataflow-google-cloud-storage-sync-row-delimiter]
Row delimiter:: Specifies the character to be used to indicate the end of the row in the extracted data. Optional field.
Example:;; \\n
Valid Values:;; Any printable ASCII character
Default:;; \\n (new line character)
[#dataflow-google-cloud-storage-sync-enclosing-character]
Enclosing character:: Specify if the text columns in the source data is enclosed in quotes. Optional field.
Example:;; Single
Valid Values:;; Single, Double, Empty
Default:;; Empty
[#dataflow-google-cloud-storage-sync-escape-character]
Escape character:: Specify the escape character if using a text qualifier in the source data. Optional field.
Example:;; \\
Valid Values:;; Any ASCII character
Default:;; Empty
[#dataflow-google-cloud-storage-sync-null-value]
Null value::
Specifies the string literal indicates the null value for a column.
During the data load, the column value matching this string will be loaded as null in the target. Optional field.
Example:;; NULL
Valid Values:;; Any string literal
Default:;; NULL
[#dataflow-google-cloud-storage-sync-date-style]
Date style:: Specifies how to interpret the date format. Optional field.
Example:;; YMD
Valid Values:;; `YMD`, `MDY`, `DMY`, `DMONY`, `MONDY`, `Y2MD`, `MDY2`, `DMY2`, `DMONY2`, and `MONDY2`
Default:;; `YMD`
Other notes:;; `MDY`: 2-digit month, 2-digit day, 4-digit year +
 `DMY`: 2-digit month, 2-digit day, 4-digit year +
`DMONY`: 2-digit day, 3-character month name, 4-digit year +
`MONDY`: 3-character month name, 2-digit day, 4-digit year +
`Y2MD`: 2-digit year, 2-digit month, 2-digit day +
`MDY2`: 2-digit month, 2-digit day, 2-digit year +
`DMY2`: 2-digit day, 2-digit month, 2-digit year +
`DMONY2`: 2-digit day, 3-character month name, 2-digit year +
`MONDY2`: 3-character month name, 2-digit day, 2-digit year
[#dataflow-google-cloud-storage-sync-date-delimiter]
Date delimiter:: Specifies the separator used in the date format. Optional field.
Example:;; -
Valid Values:;; Any printable ASCII character
Default:;; -
[#dataflow-google-cloud-storage-sync-time-style]
Time style:: Specifies the format of the time portion in the data. Optional field.
Example:;; 24 hour
Valid Values:;; 12 Hour, 24 Hour
Default:;; 24 Hour
[#dataflow-google-cloud-storage-sync-time-delimiter]
Time delimiter:: Specifies the character used as separate the time components. Optional field.
Example:;; :
Valid Values:;; Any printable ASCII character
Default:;; :
[#dataflow-google-cloud-storage-sync-decimal-delimiter]
Decimal delimiter:: Specify the decimal delimiter for float/double/numeric data types. Optional field.
Example:;; .
Valid Values:;; (.), (,), EMPTY
Default:;; EMPTY
[#dataflow-google-cloud-storage-sync-skip-trailer-rows]
Skip trailer rows:: Skip the number of trailer rows specified while loading the data. Optional field.
Example:;; 5
Valid Values:;; Any numeric value
Default:;; 0
[#dataflow-google-cloud-storage-sync-ts-load-options]
include::partial$dataflow/ts-load-options.adoc[]
[#dataflow-google-cloud-storage-sync-boolean-representation]
   Boolean representation:: Specifies the representation of data in the boolean field. Optional field.
   Example:;; true_false
   Valid Values:;; true_false, T_F, 1_0, T_NULL
   Default:;; true_false
