= Splunk connection reference
:last_updated: 06/19/2020
:experimental:
:linkattrs:
:page-aliases: /data-integrate/dataflow/dataflow-splunk-reference.adoc

Learn about the fields used to create a splunk connection with ThoughtSpot DataFlow.

Here is a list of the fields for a Splunk connection in ThoughtSpot DataFlow.
You need specific information to establish a seamless and secure connection.

[#connection-properties]
== Connection properties
[#dataflow-splunk-conn-connection-name]
Connection name:: Name your connection. Mandatory field.
Example:;; SplunkConnection
[#dataflow-splunk-conn-connection-type]
Connection type:: Choose the Splunk connection type. Mandatory field.
Example:;; Splunk
[#dataflow-splunk-conn-server-name]
Server name:: Specify the hostname or the IP address of the Splunk system Mandatory field.
Example:;; www.example.com
[#dataflow-splunk-conn-port]
Port:: Specify the port associated to the Splunk system Mandatory field.
Example:;; 1234
[#dataflow-splunk-conn-user]
User:: Specify the user id that will be used to connect to the Splunk system.This user should have necessary privileges to access the data in the databases. Mandatory field.
Example:;; userdi
[#dataflow-splunk-conn-password]
Password:: Specify the password for the User Mandatory field.
Example:;; pswrd234%!
[#dataflow-splunk-conn-jdbc-options]
JDBC options:: Specify the options associated with the JDBC URL. Optional field.
Example:;; `jdbc:sqlserver://[serverName[\instanceName][:portNumber]]`
Other notes:;; Advanced configuration

[#sync-properties]
== Sync properties
[#dataflow-splunk-sync-column-delimiter]
Column delimiter:: Specify the column delimiter character. Mandatory field.
Example:;; 1
Valid Values:;; Any printable ASCII character or decimal value for ASCII character
Default:;; The delimiter specified in sync
[#dataflow-splunk-sync-escape-character]
Escape character:: Specify this if the text qualifier is mentioned. This should be the character which escapes the text qualifier character in the source data. Optional field.
Example:;; "
Valid Values:;; Any ASCII character
Default:;; "
[#dataflow-splunk-sync-enclosing-character]
Enclosing character:: Specify if the text columns in the source data needs to be enclosed in quotes. Optional field.
Example:;; DOUBLE
Valid Values:;; SINGLE, DOUBLE
Default:;; DOUBLE
Other notes:;; This is required if the text data has newline character or delimiter character.
[#dataflow-splunk-sync-max-ignored-rows]
include::partial$dataflow/max-ignored-rows.adoc[]

[#dataflow-splunk-sync-ts-load-options]
TS load options:: Specifies the parameters passed with the `tsload` command, in addition to the commands already included by the application.
The format for these parameters is:
+
`--<param_1_name> <optional_param_1_value>`
+
`--<param_2_name> <optional_param_2_value>` Optional field.

Example:;; --max_ignored_rows 0
Valid Values:;; --null_value "" --escape_character "" --max_ignored_rows 0
Default:;; --max_ignored_rows 0

Reference:;; xref:tsload-api-flags.adoc[]

> **Related information**
>
> * xref:dataflow-tips.adoc[Dataflow tips]
