= Greenplum connection reference
:last_updated: 09/10/2021
:page-aliases: /data-integrate/dataflow/dataflow-greenplum-reference.adoc
:experimental:
:linkattrs:

Learn about the fields used to create a Greenplum connection with ThoughtSpot DataFlow.

Here is a list of the fields for a Greenplum connection in ThoughtSpot DataFlow.
You need specific information to establish a seamless and secure connection.

[#connection-properties]
== Connection properties
[#dataflow-greenplum-conn-connection-name]
Connection name:: Name your connection. Mandatory field.
Example:;; GreenplumConnection
[#dataflow-greenplum-conn-connection-type]
Connection type:: Choose the Greenplum connection type. Mandatory field.
Example:;; Greenplum
[#dataflow-greenplum-conn-host]
Host:: Specify the hostname or the IP address of the Greenplum system Mandatory field.
Example:;; www.example.com
[#dataflow-greenplum-conn-port]
Port:: Specify the port associated to the Greenplum system Mandatory field.
Example:;; 1234
[#dataflow-greenplum-conn-user]
User:: Specify the user id that will be used to connect to the Greenplum system.This user should have necessary privileges to access the data in the databases. Mandatory field.
Example:;;  userdi
[#dataflow-greenplum-conn-password]
Password:::: Specify the password for the User Mandatory field.
Example:;;  pswrd234%!
[#dataflow-greenplum-conn-database]
Database:: Collection of information that is organized so that it can be easily accessed, managed and updated. Mandatory field.
Example:;;  ditform
[#dataflow-greenplum-conn-version]
Version:: Specify the Greenplum version being connected to Optional field.
Example:;; 4.x
Other notes:;; Advanced configuration
[#dataflow-greenplum-conn-jdbc-options]
JDBC options:: Specify the options associated with the JDBC URL. Optional field.
Example:;; jdbc:sqlserver://[serverName[\instanceName][:portNumber]]
Other notes:;; Advanced configuration

[#sync-properties]
== Sync properties
[#dataflow-greenplum-sync-data-extraction-mode]
Data extraction mode:: Specify the extraction type. Optional field.
Example:;; JDBC
Valid Values:;; JDBC, Greenplum External Table
Default:;; JDBC
[#dataflow-greenplum-sync-column-delimiter]
Column delimiter:: Specify the column delimiter character. Mandatory field.
Example:;; 1
Valid Values:;; Any printable ASCII character or decimal value for ASCII character
Default:;; 1
[#dataflow-greenplum-sync-null-value]
Null Value:: Specifies the string literal that should indicate the null value in the extracted data.During the data load the column value matching this string will be loaded as null in the target. Optional field.
Example:;; NULL
Valid Values:;; Any string literal
Default:;; NULL
Other notes:;; Specific only to Greenplum External Table data extraction mode
[#dataflow-greenplum-sync-escape-character]
Escape character:: Specify this if the text qualifier is mentioned.This should be the character which escapes the text qualifier character in the source data. Optional field.
Example:;; "
Valid Values:;; Any ASCII character
Default:;; "
[#dataflow-greenplum-sync-enclosing-character]
Enclosing character:: Specify if the text columns in the source data needs to be enclosed in quotes. Optional field.
Example:;; DOUBLE
Valid Values:;; SINGLE, DOUBLE
Default:;; DOUBLE
Other notes:;; This is required if the text data has newline character or delimiter character
[#dataflow-greenplum-sync-max-ignored-rows]
include::partial$dataflow/max-ignored-rows.adoc[]

[#dataflow-greenplum-sync-ts-load-options]
TS load options:: Specifies the parameters passed with the `tsload` command, in addition to the commands already included by the application. The format for these parameters is:
+
`--<param_1_name> <optional_param_1_value>`
+
`--<param_2_name> <optional_param_2_value>`
Optional field.

Example:;; --max_ignored_rows 0
Valid Values:;; --user "dbuser" --password "$DIWD" --target_database "ditest" --target_schema "falcon_schema"
Default:;; --max_ignored_rows 0

Reference:;; xref:tsload-api-flags.adoc[]

> **Related information**
>
> * xref:dataflow-tips.adoc[Dataflow tips]
