= Data REST APIs
:last_updated: 08/24/2021
:experimental:
:linkattrs:
:page-title: About REST APIs
:page-pageid: rest-apis
:page-description: You can use the ThoughtSpot REST APIs to programmatically manage users, user sessions, group privileges, and metadata objects.

ThoughtSpot REST APIs let you programmatically create, access, and manage ThoughtSpot objects and resources. Using REST APIs, your client application can perform the following operations:

* get pinboard and visualization data from the ThoughtSpot application
* embed data from visualizations and pinboards in a web page, portal, or application
* view metadata details for various types of ThoughtSpot objects
* construct a search query to get ThoughtSpot data
* manage ThoughtSpot user profiles and group privileges
* transfer ownership of objects from one user to another
* import, export, and validate scriptable files and automate deployments

== Resource endpoints
ThoughtSpot API components or resources are represented by the URI endpoints. The URI endpoint contains the base URI and resource path to the objects that you want to query or manage.
The base URI of the API endpoints constitutes the following:

* The hostname or IP address of your ThoughtSpot application instance
* Port number
* Name of the ThoughtSpot API service
* The version number

For example, in the `\https://<your-thoughtspot-hostname:port>/callosum/v1/tspublic/v1/session/login` URL

* the base URI is `\https://<your-thoughtspot-hostname:port>/callosum/v1`
* the resource path is `/tspublic/v1/session/login`

== HTTP request methods

ThoughtSpot REST APIs support Create, Read, Update and Delete (CRUD) operations and allow applications to use the standard HTTP verbs in API requests:

* **GET** to query information, such as getting a list of users, objects, or metadata headers
* **POST** to create, add, or exchange data
* **PUT** to update the parameters in resource representation
* **DELETE** to remove a specific data, association, or object

== Data format

The REST APIs allow you to send and receive data in JSON format. To embed this data in your application, you can import or extract the data from the JSON file. You can also use scriptable files in ThoughtSpot Modeling Language (TML) to represent objects in a reusable, editable, and easy-to-read format. ThoughtSpot allows you to export, validate, and import these scriptable files.

'''
> **Related information**
>
> * https://docs.thoughtspot.com/visual-embed-sdk/7.1/en/?pageid=rest-api-getstarted[Get started with REST APIs, window=_blank]
> * https://docs.thoughtspot.com/visual-embed-sdk/7.1/en/?pageid=rest-api-reference[REST API Reference, window=_blank]

////
[#authentication]
== Authentication

Before you can use the Data REST API, you must authenticate to ThoughtSpot using SAML with the xref:js-api.adoc[JavaScript API].

== Cross Domain Verification

You can enable cross-domain verification when using the Data REST API.
This protects your data, so that another website cannot use a URL to get data from ThoughtSpot.
The procedure for xref:js-api-enable.adoc[enabling the JavaScript API] includes information on how to enable this.

== Data REST API capabilities

Use a POST method to access the URL, which calls the REST API.
The data is returned as a JSON string.
When using this method, you must extract the data from the JSON file and render it on your Web page, portal, or application.

You can use the REST API to do things like:

* Generate dynamic picklists on your Web page.
* Display a single value.
* Retrieve the data to populate a visualization drawn by your own renderer.
* Pull data directly from ThoughtSpot

Remember that the data you retrieve from ThoughtSpot is live data, so whenever the Web page is rendered, the current value(s) will be shown.

== Direct Search-to-Embed API

The xref:data-api-search.adoc[Direct Search-to-Embed API] enables searching directly from an external application or web page to pull data from ThoughtSpot.
This feature was introduced in ThoughtSpot 5.0.
When using it, you can access data stored in ThoughtSpot directly.
You do not have to save a search result to a pinboard and then reference it using the visualization's URL.

== Public API reference

You can find more information on our public APIs in the xref:public-api-reference.adoc[Reference guide].

'''
> **Related information**
>
> * xref:public-api-reference.adoc[API Reference guide]
> * xref:data-api-search.adoc[Direct Search-to-Embed API]
////
