= IBM Db2 connection reference
:last_updated: 09/10/2021
:experimental:
:linkattrs:
:page-aliases: /data-integrate/dataflow/dataflow-ibm-db2-reference.adoc

Learn about the fields used to create an IBM Db2 connection with ThoughtSpot DataFlow.

Here is a list of the fields for an IBM Db2 connection in ThoughtSpot DataFlow.
You need specific information to establish a seamless and secure connection.

[#connection-properties]
== Connection properties
[#dataflow-ibm-db2-conn-connection-name]
Connection name:: Name your connection. Mandatory field.
Example:;; IBMDb2Connection
[#dataflow-ibm-db2-conn-connection-type]
Connection type:: Choose the IBM Db2 connection type. Mandatory field.
Example:;; IBM Db2
[#dataflow-ibm-db2-conn-platform]
Platform::
An environment in which a data point is executed.
Specify LUW, iSeries, or Mainframe. Mandatory field.
Example:;; platform
[#dataflow-ibm-db2-conn-host]
Host:: Specify the hostname or the IP address of the Db2 system. Mandatory field.
Example:;; example.plaform.com
[#dataflow-ibm-db2-conn-port]
Port:: Specify the port associated to the Db2 system. Mandatory field.
Example:;; 1234
[#dataflow-ibm-db2-conn-user]
User::
Specify the user to connect to IBM Db2.
This user must have data access privileges. Mandatory field.
Example:;; userdi
[#dataflow-ibm-db2-conn-password]
include::partial$dataflow/password.adoc[]

[#dataflow-ibm-db2-conn-database]
Database:: Collection of information that is organized so that it can be easily accessed, managed and updated. Mandatory field.
Example:;; database
[#dataflow-ibm-db2-conn-database-alias]
Database alias:: Specify database alias for easy identification. Mandatory field.
Example:;; database_alias
Other notes:;; These are under Advanced configuration.
[#dataflow-ibm-db2-sync-version]
Version:: Specify the Db2 version being connected to. Optional field.
Example:;; 10.x
Other notes:;; These are under Advanced configuration.
[#dataflow-ibm-db2-sync-code-page]
Code page::
A standardized code in which characters are represented for computer storage and transmission by the numbers 0 through 127.
Select either ASCII or EBCDIC. Optional field.
Example:;; ASCII
[#dataflow-ibm-db2-conn-jdbc-options]
include::partial$dataflow/jdbc-options.adoc[]

[#sync-properties]
== Sync properties
[#dataflow-ibm-db2-sync-data-extraction-mode]
Data extraction mode:: Specify the extraction type. Optional field.
Example:;; Db2 EXPORT
Valid Values:;; JDBC,Db2 EXPORT
Default:;; JDBC
[#dataflow-ibm-db2-sync-column-delimiter]
Column delimiter:: Specify the column delimiter character. Mandatory field.
Example:;; 1
Valid Values:;; Any printable ASCII character or decimal value for ASCII character
Default:;; The delimiter specified in sync
[#dataflow-ibm-db2-sync-null-value]
Null value::
Specifies the string literal that should indicate the null value in the extracted data.
During the data load the column value matching this string will be loaded as null in the target. Optional field.
Example:;; NULL
Valid Values:;; Any string literal
Default:;; NULL
Other notes:;; Specific only to Db2 EXPORT Utility
[#dataflow-ibm-db2-sync-enclosing-character]
Enclosing character:: Specify if the text columns in the source data needs to be enclosed in quotes. Optional field.
Example:;; DOUBLE
Valid Values:;; Single, Double
Default:;; DOUBLE
Other notes:;; This is required if the text data has newline character or delimiter character.
[#dataflow-ibm-db2-sync-escape-character]
Escape character:: Specify the escape character if using a text qualifier in the source data. Optional field.
Example:;; \"
Valid Values:;; Any ASCII character
Default:;; \"
[#dataflow-ibm-db2-sync-fetch-size]
Fetch size::
Specify the number of rows to be fetched at a time and processed in memory.
If the value specified is zero then, all rows are extracted at once. Optional field.
Example:;; 1000
Valid Values:;; Any numeric value
Default:;; 1000
Other notes:;; Appears when Extraction Type is "JDBC".
[#dataflow-ibm-db2-sync-max-ignored-rows]
include::partial$dataflow/max-ignored-rows.adoc[]

[#dataflow-ibm-db2-sync-ts-load-options]
include::partial$dataflow/ts-load-options.adoc[]
