= Vertica connection reference
:last_updated: 9/10/2021
:experimental:
:linkattrs:
:page-aliases: /data-integrate/dataflow/dataflow-vertica-reference.adoc

Learn about the fields used to create a Vertica connection with ThoughtSpot DataFlow.

Here is a list of the fields for a Vertica connection in ThoughtSpot DataFlow.
You need specific information to establish a seamless and secure connection.

[#connection-properties]
== Connection properties

[#dataflow-vertica-conn-connection-name]
Connection name::
Name your connection.
+
Mandatory field.

Example;;
VerticaConnection

[#dataflow-vertica-conn-connection-type]
Connection type::
Choose the Vertica connection type.
+
Mandatory field.

Example;;
Vertica

[#dataflow-vertica-conn-host-name]
Host name::
Specify the hostname or the IP address of the Vertica system
+
Mandatory field.

Example;;
www.example.com

[#dataflow-vertica-conn-port]
Port::
Specify the port associated to the Vertica system
+
Mandatory field.

Example;;
1234
Default;;
5433

[#dataflow-vertica-conn-user]
User::
Specify the user id that will be used to connect to the Vertica system. This user should have necessary privileges to access the data in the databases.
+
Mandatory field.

Example;;
userdi

[#dataflow-vertica-conn-password]
Password::
Specify the password for the User
+
Mandatory field.

Example;;
pswrd234%!

[#dataflow-vertica-conn-database]
Database::
Collection of information that is organized so that it can be easily accessed, managed, and updated.
+
Mandatory field.

Example;;
database

[#dataflow-vertica-conn-ssl-encryption]
SSL encryption::
To ensure the data is encrypted use additional security feature such as SSL.
+
Optional field.

[#dataflow-vertica-conn-trust-store]
Trust store::
Specify the TLS/SSL client certificate store for SSL Client Authentication (2-way SSL)
+
Mandatory field.

Example;;
trust store path

[#dataflow-vertica-conn-trust-store-password]
Trust store password::
Specify the password for the TLS/SSL client certificate.
+
Mandatory field.

Example;;
password

[#sync-properties]
== Sync properties

[#dataflow-vertica-sync-column-delimiter]
Column delimiter::
Specify the column delimiter character.
+
Mandatory field.

Example;;
1
Valid values;;
Any printable ASCII character, or the decimal value for an ASCII character
Default;;
The delimiter specified in sync

[#dataflow-vertica-sync-escape-character]
Escape character::
Specify the escape character if using a text qualifier in the source data.
+
Optional field.

Example;;
""
Valid values;;
Any ASCII character
Default;;
""

[#dataflow-vertica-sync-enclosing-character]
Enclosing character::
Specify if the text columns in the source data must be in quotes, and the quote types.
+
Optional field.

Example;;
`DOUBLE`
Valid values;;
Single, Double
Default;;
`DOUBLE`

[#dataflow-vertica-sync-ts-load-options]
TS load options::
Specifies the parameters passed with the `tsload` command, in addition to the commands already included by the application.
+
The format for these parameters is:
+
----
--<param_1_name><optonal_param_1_value>
--<param_2_name><optonal_param_21_value>
----
+
Optional field.

Example;;
+
----
--max_ignored_rows 0
----
Valid values;;
+
----
--null_value """"
--escape_character """"
--max_ignored_rows 0
----
Default;;
+
----
--max_ignored_rows 0
----

[#dataflow-vertica-sync-max-ignored-rows]
include::partial$dataflow/max-ignored-rows.adoc[]

[#dataflow-vertica-sync-fetch-size]
Fetch size::
Specify the number of rows to fetch at one time, and process in memory.
+
If the value specified is `0`, then DataFlow extracts all rows at the same time.
+
Optional field.

Example;;
`1000`
Valid values;;
Any numeric value
Default;;
`1000`

[#dataflow-vertica-sync-jdbc-options]
JDBC options::
Specify the options associated with the JDBC URL.
+
Optional field.

Example;;
+
----
jdbc:sqlserver://[serverName[instanceName][:portNumber]]
----
