= PostgreSQL connection reference
:last_updated: 07/6/2020
:experimental:
:linkattrs:
:page-aliases: /data-integrate/dataflow/dataflow-postgresql-reference.adoc

Learn about the fields used to create a PostgreSQL connection with ThoughtSpot DataFlow.

Here is a list of the fields for a PostgreSQL connection in ThoughtSpot DataFlow.
You need specific information to establish a seamless and secure connection.

[#connection-properties]
== Connection properties
[#dataflow-postgresql-conn-connection-name]
Connection name:: Name your connection. Mandatory field.
Example:;; PostgreSQLConnection
[#dataflow-postgresql-conn-connection-type]
Connection type:: Choose the PostgreSQL connection type. Mandatory field.
Example:;; PostgreSQL
[#dataflow-postgresql-conn-host]
Host:: Specify the hostname or the IP address of the PostgreSQL system. Mandatory field.
Example:;; www.example.com
[#dataflow-postgresql-conn-port]
Port:: Specify the port associated to the PostgreSQL system. Mandatory field.
Example:;; 1234
[#dataflow-postgresql-conn-user]
User::
Specify the user id that will be used to connect to the PostgreSQL system.
This user should have necessary privileges to access the data in the databases. Mandatory field.
Example:;; userdi
[#dataflow-postgresql-conn-password]
include::partial$dataflow/password.adoc[]

[#dataflow-postgresql-conn-database]
Database:: Collection of information that is organized so that it can be easily accessed, managed and updated. Mandatory field.
Example:;; ditform
////
[#dataflow-postgresql-conn-version]
Version:: Specify the PostgreSQL version being connected to. Optional field.
Example:;; 9.x
Other notes:;; Advanced configuration
////
[#dataflow-postgresql-conn-jdbc-options]
include::partial$dataflow/jdbc-options.adoc[]

[#sync-properties]
== Sync properties
[#dataflow-postgresql-sync-data-extraction-mode]
Data extraction mode:: Specify the extraction type. Optional field.
Example:;; JDBC
Valid Values:;; JDBC,PSQL
Default:;; JDBC
[#dataflow-postgresql-sync-column-delimiter]
Column delimiter:: Specify the column delimiter character. Mandatory field.
Example:;; 1
Valid Values:;; Any printable ASCII character or decimal value for ASCII character
Default:;; 1
[#dataflow-postgresql-sync-null-value]
Null value::
Specifies the string literal that should indicate the null value in the extracted data.
During the data load the column value matching this string will be loaded as null in the target. Optional field.
Example:;; NULL
Valid Values:;; Any string literal
Default:;; NULL
[#dataflow-postgresql-sync-enclosing-character]
Enclosing character:: Specify if the text columns in the source data needs to be enclosed in quotes. Optional field.
Example:;; DOUBLE
Valid Values:;; SINGLE, DOUBLE
Default:;; DOUBLE
Other notes:;; This is required if the text data has newline character or delimiter character.
[#dataflow-postgresql-sync-escape-character]
Escape character:: Specify the escape character if using a text qualifier in the source data. Optional field.
Example:;; \"
Valid Values:;; Any ASCII character
Default:;; \"
[#dataflow-postgresql-sync-max-ignored-rows]
include::partial$dataflow/max-ignored-rows.adoc[]

[#dataflow-postgresql-sync-ts-load-options]
include::partial$dataflow/ts-load-options.adoc[]
