= Amazon Redshift connection reference
:last_updated: 06/19/2020
:experimental:
:linkattrs:
:page-aliases: /data-integrate/dataflow/dataflow-amazon-redshift-reference.adoc

Learn about the fields used to create an Amazon Redshift connection with ThoughtSpot DataFlow.

Here is a list of the fields for an Amazon Redshift connection in ThoughtSpot DataFlow.
You need specific information to establish a seamless and secure connection.

[#connection-properties]
== Connection properties
[#dataflow-amazon-redshift-conn-connection-name]
Connection name:: Name your connection. Mandatory field.
Example:;; AmazonRedshiftConnection
[#dataflow-amazon-redshift-conn-connection-type]
Connection type:: Choose the Amazon Redshift connection type. Mandatory field.
Example:;; Amazon Redshift
[#dataflow-amazon-redshift-conn-host]
Host:: Specify the hostname or the IP address of the Redshift system. Mandatory field.
Example:;; example.com
[#dataflow-amazon-redshift-conn-port]
Port:: Specify the port associated to the Redshift system Mandatory field.
Example:;; 1234
Default:;; 5439
[#dataflow-amazon-redshift-conn-user]
User::
Specify the user to connect to Amazon Redshift.
This user must have data access privileges. Mandatory field.
Example:;; userdi
[#dataflow-amazon-redshift-conn-password]
include::partial$dataflow/password.adoc[]

[#dataflow-amazon-redshift-conn-database]
Database:: Collection of information that is organized so that it can be easily accessed, managed and updated. Mandatory field.
Example:;; database
[#dataflow-amazon-redshift-conn-jdbc-options]
include::partial$dataflow/jdbc-options.adoc[]

[#sync-properties]
== Sync properties
[#dataflow-amazon-redshift-sync-column-delimiter]
Column delimiter:: Specify the column delimiter character. Mandatory field.
Example:;; 1
Valid Values:;; Any printable ASCII character or decimal value for ASCII character
Default:;; 1
[#dataflow-amazon-redshift-sync-enclosing-character]
Enclosing character:: Specify if the text columns in the source data needs to be enclosed in quotes. Optional field.
Example:;; DOUBLE
Valid Values:;; SINGLE, DOUBLE
Default:;; DOUBLE
Other notes:;; This is required if the text data has newline character or delimiter character.
[#dataflow-amazon-redshift-sync-escape-character]
Escape character:: Specify the escape character if using a text qualifier in the source data. Optional field.
Example:;; \"
Valid Values:;; Any ASCII character
Default:;; \"
[#dataflow-amazon-redshift-sync-fetch-size]
Fetch size::
Specify the number of rows to be fetched at a time and processed in memory.
If the value specified is zero then, all rows are extracted at once. Mandatory field.
Example:;; 1000
Valid Values:;; Any numeric value
Default:;; 1000
[#dataflow-amazon-redshift-sync-ts-load-options]
include::partial$dataflow/ts-load-options.adoc[]
