= Google Sheets connection reference
:last_updated: 9/9/2021
:experimental:
:linkattrs:
:page-aliases: /data-integrate/dataflow/dataflow-google-sheets-reference.adoc

Learn about the fields used to create a Google Sheets connection with ThoughtSpot DataFlow.

Here is a list of the fields for a Google Sheets connection in ThoughtSpot DataFlow.
You need specific information to establish a seamless and secure connection.

[#connection-properties]
== Connection properties

[#dataflow-google-sheets-conn-connection-name]
Connection name::
Name your connection.
+
Mandatory field.

Example;;
GoogleSheetsConnection

[#dataflow-google-sheets-conn-connection-type]
Connection type::
Choose the Google Sheets connection type.
+
Mandatory field.

Example;;
Google Sheets

[#dataflow-google-sheets-conn-access-token]
Access token::
Specify the access token to authenticate Google Sheets.
+
Mandatory field.

[#dataflow-google-sheets-conn-refresh-token]
Refresh token::
Specify the refresh token to authenticate Google Sheets.
+
Optional field.

[#dataflow-google-sheets-conn-obtain-access-token]
Obtain access token::
Select this option to use access key/token to connect to the Google Sheets web-service
+
Optional field.

[#dataflow-google-sheets-conn-oauth-client-id]
OAuth client ID::
Specify the OAuth client ID
+
Mandatory field.

Note;;
Only when you select the "obtain access token" option

[#dataflow-google-sheets-conn-oauth-client-secret]
OAuth client secret::
Specify the OAuth client secret
+
Mandatory field.

Note;;
Only when you select the "obtain access token" option

[#dataflow-google-sheets-conn-callback-url]
Callback URL::
Secured domain URL of the repo used to register in Google Sheets
+
Mandatory field.

Note;;
Only when you select the "obtain access token" option

[#dataflow-google-sheets-conn-scope]
Scope::
Specify the number of users to access the account
+
Mandatory field.

Note;;
Only when you select the "obtain access token" option


[#sync-properties]
== Sync properties

[#dataflow-google-sheets-sync-column-delimiter]
Column delimiter::
Specify the column delimiter character.
+
Mandatory field.

Example;;
1
Valid values;;
Any printable ASCII character, or the decimal value for an ASCII character
Default;;
The delimiter specified in sync

[#dataflow-google-sheets-sync-enclosing-character]
Enclosing character::
Specify if the text columns in the source data must be in quotes, and the quote types.
+
Optional field.

Example;;
`DOUBLE`
Valid values;;
Single, Double
Default;;
`DOUBLE`
Note;;
This is required if the text data has newline character or delimiter character.

[#dataflow-google-sheets-sync-escape-character]
Escape character::
Specify the escape character if using a text qualifier in the source data.
+
Optional field.

Example;;
""
Valid values;;
Any ASCII character
Default;;
""

[#dataflow-google-sheets-sync-fetch-size]
Fetch size::
Specify the number of rows to fetch at one time, and process in memory.
+
If the value specified is `0`, then DataFlow extracts all rows at the same time.
+
Optional field.

Example;;
`1000`
Valid values;;
Any numeric value
Default;;
`1000`

[#dataflow-google-sheets-sync-max-ignored-rows]
include::partial$dataflow/max-ignored-rows.adoc[]

[#dataflow-google-sheets-sync-ts-load-options]
TS load options::
Specifies the parameters passed with the `tsload` command, in addition to the commands already included by the application.
+
The format for these parameters is:
+
----
--<param_1_name><optonal_param_1_value>
--<param_2_name><optonal_param_2_value>
----
+
Optional field.

Example;;
+
----
--max_ignored_rows 0
----
Valid values;;
+
----
--null_value """"
--escape_character """"
--max_ignored_rows 0
----
Default;;
+
----
--max_ignored_rows 0
----

[#dataflow-google-sheets-sync-jdbc-options]
JDBC options::
Specify the options associated with the JDBC URL.
+
Optional field.

Example;;
+
----
jdbc:sqlserver://[serverName[instanceName][:portNumber]]
----
Note;;
Advanced configuration
