= Hive connection reference
:last_updated: 09/10/2021
:experimental:
:linkattrs:
:page-aliases: /data-integrate/dataflow/dataflow-hive-reference.adoc

Learn about the fields used to create a Hive connection with ThoughtSpot DataFlow.

Here is a list of the fields for a Hive connection in ThoughtSpot DataFlow.
You need specific information to establish a seamless and secure connection.

[#connection-properties]
== Connection properties
[#dataflow-hive-conn-connection-name]
Connection name:: Name your connection. Mandatory field.
Example:;; HiveConnection
[#dataflow-hive-conn-connection-type]
Connection type:: Choose the Hive connection type. Mandatory field.
Example:;; Hive
[#dataflow-hive-conn-hiveserver2-ha-configured]
HiveServer2 HA configured:: Specify this option if using HiveServer2 High Availability. Mandatory field.
[#dataflow-hive-conn-hiveserver2-zookeeper-namespace]
HiveServer2 zookeeper namespace::
Specify zookeeper namespace as hiveserver2.
This is the default value.
Mandatory field. +
 Only when using Hiveserver2 HA.
 Example:;; hiveserver2
 Other notes:;; If value is different then, the value can be found from hive-site.xml against the property `hive.server2.zookeeper.namespace`.
[#dataflow-hive-conn-host]
Host:: Specify the hostname or the IP address of the Hadoop system.
Mandatory field. +
 Only when _not_ using Hiveserver2 HA.
Example:;; myEmail@example.com
[#dataflow-hive-conn-port]
Port:: Specify the port.
Mandatory field. +
 Only when _not_ using Hiveserver2 HA.
 Example:;; 1234
[#dataflow-hive-conn-hive-security-authentication]
Hive security authentication::
Specifies the type of security protocol to connect to the instance.
Based on the type of security select the authentication type and provide details. Mandatory field.
Example:;; Kerberos
Valid Values:;; Simple, Kerberos, LDAP, SSL, Kerberos & SSL, LDAP & SSL
Default:;; Simple
Other notes:;; The authentication type setup for the instance can be found from hive-site.xml against the property `hive.server2.authentication`.
[#dataflow-hive-conn-user]
User::
Specify the user to connect to Hive.
This user must have data access privileges.
Mandatory field. +
 For simple, LDAP, and Simple authentication only.
 Example:;; userdi
 Default:;; simple
[#dataflow-hive-conn-password]
Password:: Specify the password for the User.
+
Optional field.
+
Example:;; _pswrd234%!_
+
Note:;; For simple, LDAP authentication only.

[#dataflow-hive-conn-trust-store]
Trust store:: Specify the trust store name for authentication.
Mandatory field. +
 For SSL and Kerberos & SSL authentication only.
 Example:;; trust store
 Default:;; SSL
[#dataflow-hive-conn-trust-store-password]
Trust store password:: Specify the password for the trust store.
Mandatory field. +
 For SSL and Kerberos & SSL authentication only.
 Example:;; password
 Default:;; SSL
[#dataflow-hive-conn-hive-transport-mode]
Hive transport mode::
Applicable only for hive process engine.
This specifies the network protocol used for communicating between hive nodes. Mandatory field.
Example:;; binary
Valid Values:;; Binary, HTTP
Default:;; binary
Other notes:;; The Hive transport mode can be identified from hive-site.xml against the property hive.server2.transport.mode.
[#dataflow-hive-conn-http-path]
HTTP path:: This is specified as an option when http transport mode is selected.
Mandatory field. +
 For HTTP transport mode only.
 Example:;; cliservice
 Valid Values:;; cliservice
 Default:;; cliservice
 Other notes:;; The HTTP Path value can be identified from `hive-site.xml` against the property `hive.server2.thrift.http.path`.
[#dataflow-hive-conn-hadoop-distribution]
Hadoop distribution:: Provide the distribution of Hadoop being connected to. Optional field.
Example:;; Hortonworks
Valid Values:;; CDH, Hortonworks, EMR
Default:;; CDH
[#dataflow-hive-conn-distribution-version]
Distribution version:: Provide the version of the Distribution chosen above. Optional field.
Example:;; 2.6.5
Valid Values:;; Any Numeric value
Default:;; 6.3.x
[#dataflow-hive-conn-hadoop-conf-path]
Hadoop conf path::
By default, the system picks the Hadoop configuration files from the HDFS.
To override, specify an alternate location.
Applies only when using configuration settings that are different from global Hadoop instance settings. Optional field.
Example:;; $DI_HOME/app/path
Other notes:;; An instance where this could be needed is, if the hdfs is encrypted and the location of key files and password decrypt the files is available in the hadoop config files.
[#dataflow-hive-conn-dfs-ha-configured]
DFS HA configured:: Specify if using High Availability for DFS.
Optional field. +
 For Hadoop Extract only.
 Example:;; Checked
[#dataflow-hive-conn-dfs-name-service]
 DFS name service:: Specify the logical name of the HDFS nameservice.
Optional field. +
 For DFS HA and Hadoop Extract only.
 Example:;; lahdfs
 Other notes:;; It is available in hdfs-site.xml and defined as dfs.nameservices
[#dataflow-hive-conn-dfs-name-node-ids]
DFS name node IDs::
Specify a comma-separated list of NameNode IDs.
System uses this property to determine all NameNodes in the cluster.
XML property name is `dfs.ha.namenodes.dfs.nameservices`.
Optional field. +
 For DFS HA and Hadoop Extract only.
 Example:;; nn1, nn2
[#dataflow-hive-conn-rpc-address-for-namenode1]
RPC address for namenode1::
Specify the fully-qualified RPC address for each listed NameNode.
Defined as `dfs.namenode.rpc-address.dfs.nameservices.name node ID 1`.
Optional field. +
 For DFS HA and Hadoop Extract only.
 Example:;; lclabh.example.com:5678
[#dataflow-hive-conn-rpc-address-for-namenode2]
RPC address for namenode2::
Specify the fully-qualified RPC address for each listed NameNode.
Define as `dfs.namenode.rpc-address.dfs.nameservices.name node ID 2`.
Optional field. +
 For DFS HA and Hadoop Extract only. Example:;; lvclabh.example.com:9876
[#dataflow-hive-conn-dfs-host]
DFS host:: Specify the DFS hostname or the IP address.
Optional field. +
 For Hadoop Extract only, when _not_ using DFS HA.
 Example:;; myemail@example.com
[#dataflow-hive-conn-dfs-port]
DFS port:: Specify the associated DFS port.
Optional field. +
 For Hadoop Extract only, when _not_ using DFS HA.
 Example:;; 1234
[#dataflow-hive-conn-default-dfs-location]
Default DFS location:: Specify the location for the default source/target location.
Optional field. +
 For Hadoop Extract only.
 Example:;; /tmp
[#dataflow-hive-conn-temp-dfs-location]
 Temp DFS location:: Specify the location for creating temp directory. +
Optional field. +
 For Hadoop Extract only.
 Example:;; /tmp
[#dataflow-hive-conn-dfs-security-authentication]
DFS security authentication:: Select the type of security being enabled. +
Optional field. +
 For Hadoop Extract only.
 Example:;; Kerberos
 Valid Values:;; Simple, Kerberos
 Default:;; simple
[#dataflow-hive-conn-hadoop-rpc-protection]
Hadoop RPC protection:: Hadoop cluster administrators control the quality of protection using the configuration parameter `hadoop.rpc.protection`.
Optional field. +
 When using Kerberos DFS security authentication _and_ Hadoop Extract.
 Example:;; none
 Valid Values:;; None, authentication, integrity, privacy
 Default:;; authentication
 Other notes:;; It is available in core-site.xml.
[#dataflow-hive-conn-hive-principal]
 Hive principal:: Principal for authenticating hive services. Optional field.
 Example:;; hive/host@lab.example.com
 Other notes:;; It is available in hive-site.xml
[#dataflow-hive-conn-user-principal]
User principal:: To authenticate via a key-tab you must have supporting key-tab file which is generated by Kerberos Admin and also requires the user principal associated with Key-tab (Configured while enabling Kerberos). +
Optional field.
Example:;; labuser@labdp.example.com
[#dataflow-hive-conn-user-keytab]
User keytab:: To authenticate via a key-tab you must have supporting key-tab file which is generated by Kerberos Admin and also requires the user principal associated with Key-tab (Configured while enabling Kerberos). +
Optional field.
Example:;; /app/keytabs/labuser.keytab
[#dataflow-hive-conn-kdc-host]
KDC host:: Specify KDC Host Name where as KDC (Kerberos Key Distribution Center) is a service than runs on a domain controller server role (Configured from Kerberos configuration-/etc/krb5.conf). Optional field.
Example:;; example.example.com
[#dataflow-hive-conn-default-realm]
Default realm:: A Kerberos realm is the domain over which a Kerberos authentication server has the authority to authenticate a user, host or service (Configured from Kerberos configuration-/etc/krb5.conf). Optional field.
Example:;; labhdp.example.com
[#dataflow-hive-conn-queue-name]
Queue name:: Specify the queue name followed by a coma separated form in yarn.scheduler.capacity.root.queues.
Optional field. +
 For Hadoop Extract only.
 Example:;; default
 Other notes:;; It is available in capacity-scheduler.xml
[#dataflow-hive-conn-yarn-web-ui-port]
YARN web UI port:: Yarn Providing web UI for yarn RM and by default 8088 in use.
Optional field. +
 For Hadoop Extract only.
 Example:;; 8088
[#dataflow-hive-conn-zookeeper-quorum-host]
Zookeeper quorum host:: Specify the value of hadoop.registry.zk.quorum from yarn-site.xml.
Optional field. +
 Only when _not_ using Hiveserver2 HA.
  Example:;; lvclhdp1.example.com:21,lvclabhdp12.example.com:81,lvclabhdp12.example.com:2093
[#dataflow-hive-conn-yarn-timeline-webapp-host]
Yarn timeline webapp host:: Specify the ip address of yarn timeline service web application. Optional field.
Example:;; 8188
[#dataflow-hive-conn-yarn-timeline-webapp-port]
Yarn timeline webapp port:: Specify the port associated with the yarn timeline service web application. Optional field.
Example:;; 8190
[#dataflow-hive-conn-yarn-timeline-webapp-version]
Yarn timeline webapp version:: Specify the version associated with the yarn timeline service web application. Optional field.
Example:;; v1
[#dataflow-hive-conn-jdbc-options]
include::partial$dataflow/jdbc-options.adoc[]

[#sync-properties]
== Sync properties
[#dataflow-hive-sync-data-extraction-mode]
Data extraction mode:: Specify the extraction type. Optional field.
Example:;; Hadoop Extract
Valid Values:;; Hadoop Extract, JDBC
Default:;; Hadoop Extract
[#dataflow-hive-sync-column-delimiter]
Column delimiter:: Specify the column delimiter character. Mandatory field.
Example:;; , (comma)
Valid Values:;; Any character, (comma, semicolon) or a number.
If using a number, system uses its ASCII value as delimiter.
Default:;; , (comma)
[#dataflow-hive-sync-null-value]
Null value::
Specifies the string literal that should indicate the null value in the extracted data.
During the data load the column value matching this string will be loaded as null in the target.
Optional field. +
 For Hadoop Extract only.
 Example:;; NULL
 Valid Values:;; NULL
 Default:;; NULL
[#dataflow-hive-sync-enclosing-character]
Enclosing character:: Specify if the text columns in the source data needs to be enclosed in quotes. Optional field.
Example:;; DOUBLE
Valid Values:;; SINGLE, DOUBLE
Default:;; DOUBLE
[#dataflow-hive-sync-escape-character]
Escape character:: Specify the escape character if using a text qualifier in the source data. Mandatory field.
Example:;; \"
Valid Values:;; \\, Any ASCII character
Default:;; \"
[#dataflow-hive-sync-max-ignored-rows]
include::partial$dataflow/max-ignored-rows.adoc[]

[#dataflow-hive-sync-ts-load-options]
include::partial$dataflow/ts-load-options.adoc[]
