= SAS connection reference
:last_updated: 09/10/2021
:experimental:
:linkattrs:
:page-aliases: /data-integrate/dataflow/dataflow-sas-reference.adoc


Learn about the fields used to create a SAS connection with ThoughtSpot DataFlow.

Here is a list of the fields for a SAS connection in ThoughtSpot DataFlow.
You need specific information to establish a seamless and secure connection.

[#connection-properties]
== Connection properties
[#dataflow-sas-conn-connection-name]
Connection name:: Name your connection. Mandatory field.
Example:;; SASConnection
[#dataflow-sas-conn-connection-type]
Connection type:: Choose the SAS connection type. Mandatory field.
Example:;; SAS
[#dataflow-sas-conn-host]
Host:: Specify the hostname or the IP address of the system. Mandatory field.
Example:;; www.example.com
[#dataflow-sas-conn-port]
Port:: Specify the port associated with the system. Mandatory field.
Example:;; 1234
[#dataflow-sas-conn-user]
User::
Specify the user who connects to the system.
This user must have data access privileges. Mandatory field.
Example:;; userid
[#dataflow-sas-conn-password]
include::partial$dataflow/password.adoc[]

[#dataflow-sas-conn-server-type]
Server type:: Specify the type of server to connect. Optional field.
Example:;; SASIOM
Valid Values:;; SHARENET, SASIOM
Default:;; SASIOM
Other notes:;; If SASIOM is selected then by default the Version value is 9.2 and if SHARENET is selected then by default the Version value is 9.4.
[#dataflow-sas-conn-ref-name]
Ref name:: Specify the reference name given to recognize the server. Mandatory field.
Example:;; Test
[#dataflow-sas-conn-path]
Path:: Specify the path which is generated by server. Mandatory field.
Example:;; default
[#dataflow-sas-conn-version]
Version:: Specify the SAS version being connected to. Optional field.
Example:;; 9.2
Valid Values:;; 9.2, 9.4, 9.44, or 9.45
Other notes:;; Advanced configuration.

[#sync-properties]
== Sync properties
[#dataflow-sas-sync-column-delimiter]
Column delimiter:: Specify the column delimiter character. Mandatory field.
Example:;; 1
Valid Values:;; Any printable ASCII character or decimal value for ASCII character
Default:;; 1
[#dataflow-sas-sync-enclosing-character]
Enclosing character:: Specify if the text columns in the source data needs to be enclosed in quotes. Optional field.
Example:;; DOUBLE
Valid Values:;; SINGLE, DOUBLE
Default:;; DOUBLE
Other notes:;; This is required if the text data has newline character or delimiter character.
[#dataflow-sas-sync-escape-character]
Escape character::
Specify this if the text qualifier is mentioned.
This should be the character which escapes the text qualifier character in the source data. Optional field.
Example:;; \"
Valid Values:;; Any ASCII character
Default:;; \"
[#dataflow-sas-sync-parallel-thread-limit]
Parallel thread limit:: Specify the number of parallel threads to unload data.
Example:;; 4
Valid Values:;; Any numeric value
Default:;; 4
[#dataflow-sas-sync-max-ignored-rows]
include::partial$dataflow/max-ignored-rows.adoc[]

[#dataflow-sas-sync-ts-load-options]
include::partial$dataflow/ts-load-options.adoc[]
