= SQL Server connection reference
:last_updated: 09/09/2021
:experimental:
:linkattrs:
:page-aliases: /data-integrate/dataflow/dataflow-sql-server-reference.adoc


Learn about the fields used to create an SQL Server connection with ThoughtSpot DataFlow.

Here is a list of the fields for an SQL Server connection in ThoughtSpot DataFlow.
You need specific information to establish a seamless and secure connection.

[#connection-properties]
== Connection properties

[#dataflow-sql-server-conn-connection-name]
Connection name::
  Name your connection. Mandatory field.
  Example;; SQLServerConnection

[#dataflow-sql-server-conn-connection-type]
Connection type:: Choose the SQL Server connection type. Mandatory field.
Example:;; SQL Server

[#dataflow-sql-server-conn-sql-server-type]
SQL server type:: Specify the SQL server type, either On-premise, Azure SQL database, or SQL server on Cloud VM. Mandatory field.
Default:;; On-premise

[#dataflow-sql-server-conn-host]
Host:: Specify the hostname or the IP address of the SQL Server system. Mandatory field.
Example:;; www.example.com
[#dataflow-sql-server-conn-instance]
Instance:: Specify an instance with all SQL Server databases run by a single SQL Server service. This option appears when SQL server type is "On-premise" or "SQL Server on Cloud VM". To access, select the box next to *Named instance*. When selected, *Instance* replaces the *Port* option.
[#dataflow-sql-server-conn-port]
Port:: Specify the port associated with the SQL Server system. This option appears when SQL server type is "Azure SQL database", or when the *Named instance* option is not selected. Mandatory field.
Example:;; 1234
[#dataflow-sql-server-conn-user]
User::
Specify the user id that will be used to connect to the SQL Server system.
This user should have necessary privileges to access the data in the databases. Mandatory field.
Example:;; userdi
[#dataflow-sql-server-conn-password]
include::partial$dataflow/password.adoc[]
////
[#dataflow-sql-server-conn-instance]
Instance:: Specify an instance with all SQL Server databases run by a single SQL Server service. Optional field.
Example:;; diazsql
Other notes:;; Advanced configuration.
[#dataflow-sql-server-conn-version]
Version:: Specify the SQL Server version being connected to. Optional field.
Example:;; 2016
Other notes:;; Advanced configuration.
////
[#dataflow-sql-server-conn-azure-ad-user]
Azure AD User:: This option appears when you select "Azure SQL database" in *SQL server type*. Select the checkbox next to *Azure AD User* to provide Azure Active Directory authentication details.
[#dataflow-sql-server-conn-jdbc-options]
include::partial$dataflow/jdbc-options.adoc[]

[#sync-properties]
== Sync properties
[#dataflow-sql-server-sync-data-extraction-mode]
Data extraction mode:: Specify the extraction type. Optional field.
Example:;; JDBC
Valid Values:;; JDBC, BCP
Default:;; JDBC
[#dataflow-sql-server-sync-column-delimiter]
Column delimiter:: Specify the column delimiter character. Mandatory field.
Example:;; 1
Valid Values:;; Any printable ASCII character or decimal value for ASCII character
Default:;; 1
[#dataflow-sql-server-sync-null-value]
Null value::
Specifies the string literal that indicates the null value in the extracted data.
During the data load, the column value matching this string loads as null in the target. Optional field.
Example:;; NULL
Valid Values:;; Any string literal
Default:;; NULL
[#dataflow-sql-server-sync-enclosing-character]
Enclosing character:: Specify if the text columns in the source data needs to be enclosed in quotes. Optional field.
Example:;; DOUBLE
Valid Values:;; SINGLE, DOUBLE
Default:;; DOUBLE
Other notes:;; This is required if the text data has newline character or delimiter character.
[#dataflow-sql-server-sync-escape-character]
Escape character:: Specify the escape character if using a text qualifier in the source data. Optional field.
Example:;; \"
Valid Values:;; Any ASCII character
Default:;; \"
[#dataflow-sql-server-sync-max-ignored-rows]
include::partial$dataflow/max-ignored-rows.adoc[]

[#dataflow-sql-server-sync-ts-load-options]
include::partial$dataflow/ts-load-options.adoc[]
