= MongoDB connection reference
:last_updated: 09/10/2021
:experimental:
:linkattrs:
:page-aliases: /data-integrate/dataflow/dataflow-mongodb-reference.adoc

Learn about the fields used to create a MongoDB connection with ThoughtSpot DataFlow.

Here is a list of the fields for a MongoDB connection in ThoughtSpot DataFlow.
You need specific information to establish a seamless and secure connection.

[#connection-properties]
== Connection properties
[#dataflow-mongodb-conn-connection-name]
Connection name:: Name your connection. Mandatory field.
Example:;; MongoDBConnection
[#dataflow-mongodb-conn-connection-type]
Connection type:: Choose the MongoDB connection type. Mandatory field.
Example:;; MongoDB
[#dataflow-mongodb-conn-host-]
Host:: Specify the hostname or the IP address of the MongoDB system. Mandatory field.
Example:;; www.example.com
[#dataflow-mongodb-conn-port-]
Port:: Specify the port associated to the MongoDB system. Mandatory field.
Example:;; 1234
[#dataflow-mongodb-conn-user-]
User::
Specify the user id that will be used to connect to the MongoDB system.
This user should have necessary privileges to access the data in the databases. Mandatory field.
Example:;; userdi
[#dataflow-mongodb-conn-password-]
Password:: Specify the password for the User. Mandatory field.
Example:;; pswrd234%!
[#dataflow-mongodb-conn-database-]
Database:: Collection of information that is organized so that it can be easily accessed, managed and updated. Mandatory field.
Example:;; Test
////
[#dataflow-mongodb-sync-flatten-arrays]
Flatten arrays::
The FlattenArrays property can be used to flatten the elements of nested arrays into columns of their own.
Set FlattenArrays to the number of elements you want to return from nested arrays. Optional field.
Example:;; 0
Other notes:;; Advanced configuration
////
[#dataflow-mongodb-sync-row-scan-depth]
Row scan depth::
The maximum number of rows to scan to look for the columns available in a table.
Set this property to gain more control over how the provider applies data types to collections. Optional field.
Example:;; -1
Other notes:;; Advanced configuration
[#dataflow-mongodb-conn-jdbc-options]
include::partial$dataflow/jdbc-options.adoc[]

[#sync-properties]
== Sync properties
[#dataflow-mongodb-sync-column-delimiter]
Column delimiter:: Specify the column delimiter character. Mandatory field.
Example:;; 1
Valid Values:;; Any printable ASCII character or decimal value for ASCII character
Default:;; 1
[#dataflow-mongodb-sync-enclosing-character]
Enclosing character:: Specify if the text columns in the source data needs to be enclosed in quotes. Optional field.
Example:;; DOUBLE
Valid Values:;; SINGLE, DOUBLE
Default:;; DOUBLE
Other notes:;; This is required if the text data has newline character or delimiter character.
[#dataflow-mongodb-sync-escape-character]
Escape character:: Specify the escape character if using a text qualifier in the source data. Optional field.
Example:;; \"
Valid Values:;; Any ASCII character
Default:;; \"
[#dataflow-mongodb-sync-max-ignored-rows]
include::partial$dataflow/max-ignored-rows.adoc[]

[#dataflow-mongodb-sync-ts-load-options]
include::partial$dataflow/ts-load-options.adoc[]
