= Amazon Aurora connection reference
:last_updated: 07/16/2020
:experimental:
:linkattrs:
:page-aliases: /data-integrate/dataflow/dataflow-amazon-aurora-reference.adoc

Learn about the fields used to create an Amazon Aurora connection with ThoughtSpot DataFlow.

Here is a list of the fields for an Amazon Aurora connection in ThoughtSpot DataFlow.
You need specific information to establish a seamless and secure connection.

[#connection-properties]
== Connection properties
[#dataflow-amazon-aurora-conn-connection-name]
Connection name:: Name your connection.
+
Mandatory field.
+
Example:;;
 AmazonAuroraConnection
[#dataflow-amazon-aurora-conn-connection-type]
 Connection type:: Choose the Amazon Aurora connection type.
+
Mandatory field.
+
Example:;; Amazon Aurora
[#dataflow-amazon-aurora-conn-host]
Host:: Specify the hostname or IP address of the Aurora system.
+
Mandatory field.
+
Example:;; example.com
[#dataflow-amazon-aurora-conn-port]
Port:: Specify the port associated with Amazon Aurora connections.
+
Mandatory field.
+
Example:;; 1234
[#dataflow-amazon-aurora-conn-user]
User::
Specify the user to connect to Amazon Aurora.
This user must have data access privileges.
+
Mandatory field.
+
Example:;; userdi
[#dataflow-amazon-aurora-conn-password]
include::partial$dataflow/password.adoc[]

[#dataflow-amazon-aurora-conn-jdbc-options]
include::partial$dataflow/jdbc-options.adoc[]

[#sync-properties]
== Sync properties
[#dataflow-amazon-aurora-sync-column-delimiter]
Column delimiter:: Specify the column delimiter character.
+
Mandatory field.
+
Example:;; 1
Valid Values:;;
Any printable ASCII character or decimal value for ASCII character.
Default:;; The delimiter specified in sync
[#dataflow-amazon-aurora-sync-enclosing-character]
Enclosing character:: Specify if the text columns in the source data needs to be enclosed in quotes.
+
Optional field.
+
Example:;; DOUBLE
Valid Values:;; Single, Double
Default:;; DOUBLE
Other notes;; This is required if the text data has newline character or delimiter character.
[#dataflow-amazon-aurora-sync-escape-character]
Escape character:: Specify the escape character if using a text qualifier in the source data.
+
Optional field.
+
Example:;; \"
Valid Values:;; Any ASCII character.
Default:;; \"
[#dataflow-amazon-aurora-sync-fetch-size]
Fetch size::
Specify the number of rows to be fetched at a time and processed in memory.
If the value specified is zero then, all rows are extracted at once.
+
Mandatory field.
+
Example:;; 1000
Valid Values:;; Any numeric value.
Default:;; 1000
[#dataflow-amazon-aurora-sync-ts-load-options]
include::partial$dataflow/ts-load-options.adoc[]
