= Exadata connection reference
:last_updated: 09/10/2021
:page-aliases: /data-integrate/dataflow/dataflow-exadata-reference.adoc
:experimental:
:linkattrs:

Learn about the fields used to create an Exadata connection with ThoughtSpot DataFlow.
Here is a list of the fields for an Exadata connection in ThoughtSpot DataFlow.
You need specific information to establish a seamless and secure connection.

[#connection-properties]
== Connection properties
[#dataflow-exadata-conn-connection-name]
Connection name:: Name your connection. Mandatory field.
Example:;; ExadataConnection
[#dataflow-exadata-conn-connection-type]
Connection type:: Choose the Exadata connection type. Mandatory field.
Example:;; Exadata
[#dataflow-exadata-conn-host]
Host:: Specify the hostname or the IP address of the Exadata system Mandatory field.
Example:;; www.example.com
[#dataflow-exadata-conn-port]
Port::
Specify the port associated to the Exadata system Mandatory field.
Example:;; 1234
[#dataflow-exadata-conn-user]
User::
Specify the user id that will be used to connect to the Exadata system. This user should have necessary privileges to access the data in the databases. Mandatory field.
Example:;;  userdi
[#dataflow-exadata-conn-password]
Password::
Specify the password for the User Mandatory field.
Example:;;  pswrd234%!
[#dataflow-exadata-conn-service-name]
Service name::
Service name is the TNS alias that you give when you remotely connect to your database and this Service name is recorded in Tnsnames.ora file on your clients and it can be the same as SID and you can also give it any other name you want Mandatory field.
Example:;; idxdb03
[#dataflow-exadata-conn-version]
Version::
Specify the Exadata version being connected to Optional field.
Example:;; 11.x
Other notes:;; Advanced configuration
[#dataflow-exadata-conn-jdbc-options]
JDBC options::
Specify the options associated with the JDBC URL. Optional field.
Example:;; ``jdbc:sqlserver://[serverName[\instanceName][:portNumber]] ``
Other notes:;; Advanced configuration

[#sync-properties]
== Sync properties
[#dataflow-exadata-sync-data-extraction-mode]
Data extraction mode:: Specify the extraction type. Optional field.
Example:;; JDBC
Valid Values:;; JDBC, OCI
Default:;; JDBC
[#dataflow-exadata-sync-column-delimiter]
Column delimiter:: Specify the column delimiter character. Mandatory field.
Example:;; 1
Valid Values:;; Any printable ASCII character or decimal value for ASCII character
Default:;; 1
[#dataflow-exadata-sync-null-value]
Null Value:: Specifies the string literal that should indicate the null value in the extracted data. During the data load the column value matching this string will be loaded as null in the target. Optional field.
Example:;; NULL
Valid Values:;; Any string literal
Default:;; NULL
Other notes:;; Specific only to OCI data extraction mode
[#dataflow-exadata-sync-escape-character]
Escape character::
Specify this if the text qualifier is mentioned.
This should be the character which escapes the text qualifier character in the source data. Optional field.
Example:;; "
Valid Values:;; Any ASCII character
Default:;; "
[#dataflow-exadata-sync-enclosing-character]
Enclosing character:: Specify if the text columns in the source data needs to be enclosed in quotes. Optional field.
Example:;; DOUBLE
Valid Values:;; SINGLE, DOUBLE
Default:;; DOUBLE
Other notes:;; This is required if the text data has newline character or delimiter character.
[#dataflow-exadata-sync-max-ignored-rows]
include::partial$dataflow/max-ignored-rows.adoc[]

[#dataflow-exadata-sync-fetch-size]
Fetch size:: Specify the number of rows to be fetched at a time and processed in memory.If the value specified is zero then, all rows are extracted at once. Optional field.
Example:;; 1000
Valid Values:;; Any numeric value
Default:;; 1000
////
[#dataflow-exadata-sync-file-type]
File Type:: Specify type of the file Optional field.
Default:;; Delimiter
[#dataflow-exadata-sync-lf-string]
LF String:: Specifies if the data has new line characters or not, so that these new line characters can be identified separately. Optional field.
Example:;; OFF
Valid Values:;; OFF, ON
Default:;; OFF
[#dataflow-exadata-sync-compression]
Compression:: Specify this if the file is compressed Optional field.
Example:;;  NO
Valid Values:;; NO, YES
Default:;; NO
[#dataflow-exadata-sync-encryption]
Encryption:: Specify if the data needs to be encrypted Optional field.
Example:;; NO
Valid Values:;; NO, YES
Default:;; NO

[#dataflow-exadata-sync-date-style]
Date Style:: Specifies how to interpret the date format Optional field.
Example:;; YMD
Valid Values:;; `YMD`, `MDY`, `DMY`, `DMONY`, `MONDY`, `Y2MD`, `MDY2`, `DMY2`, `DMONY2`, and `MONDY2`
Default:;; `YMD`
Other notes:;; `MDY`: 2-digit month, 2-digit day, 4-digit year
+
`DMY`: 2-digit month, 2-digit day, 4-digit year
+
`DMONY`: 2-digit day, 3-character month name, 4-digit year
+
`MONDY`: 3-character month name, 2-digit day, 4-digit year
+
`Y2MD`: 2-digit year, 2-digit month, 2-digit day
+
`MDY2`: 2-digit month, 2-digit day, 2-digit year
+
`DMY2`: 2-digit day, 2-digit month, 2-digit year
+
`DMONY2`: 2-digit day, 3-character month name, 2-digit year
+
`MONDY2`: 3-character month name, 2-digit day, 2-digit year
+
[#dataflow-exadata-sync-date-delimiter]
Date Delimiter:: Specifies the separator used in the date format. Optional field.
Example:;; -
Valid Values:;; Any printable ASCII character
Default:;; -
[#dataflow-exadata-sync-time-style]
Time Style:: Specifies the format of the time portion in the data. Optional field.
Example:;; 24 hour
Valid Values:;; 12 Hour, 24 Hour
Default:;; 24 Hour
[#dataflow-exadata-sync-time-delimiter]
Time Delimiter:: Specifies the character used as separate the time components. Optional field.
Example:;; :
Valid Values:;; Any printable ASCII character
Default:;; :
////

[#dataflow-exadata-sync-tsload-options]
TS load options:: Specifies the parameters passed with the `tsload` command, in addition to the commands already included by the application. The format for these parameters is:
+
`--<param_1_name> <optional_param_1_value>`
+
`--<param_2_name> <optional_param_2_value>`
+
Optional field.

Example:;; --max_ignored_rows 0
Valid Values:;; --user "dbuser" --password "$DIWD" --target_database "ditest" --target_schema "falcon_schema"
Default:;; --max_ignored_rows 0

Reference:;; xref:tsload-api-flags.adoc[]

== Related Information

xref:dataflow-tips.adoc[Dataflow tips]
