= Oracle connection reference
:last_updated: 09/08/2021
:experimental:
:linkattrs:
:page-aliases: /data-integrate/dataflow/dataflow-oracle-reference.adoc

Learn about the fields used to create an Oracle connection with ThoughtSpot DataFlow.

Here is a list of the fields for an Oracle connection in ThoughtSpot DataFlow.
You need specific information to establish a seamless and secure connection.

[#connection-properties]
== Connection properties
[#dataflow-oracle-conn-connection-name]
Connection name:: Name your connection. Mandatory field.
Example:;; OracleConnection
[#dataflow-oracle-conn-connection-type]
Connection type:: Choose the Oracle connection type. Mandatory field.
Example:;; Oracle
[#dataflow-oracle-conn-host]
Host:: Specify the hostname or the IP address of the Oracle system. Mandatory field.
Example:;; www.example.com
[#dataflow-oracle-conn-port]
Port:: Specify the port associated to the Oracle system. Mandatory field.
Example:;; 1234
[#dataflow-oracle-conn-user]
User::
Specify the user id that will be used to connect to the Oracle system.
This user should have necessary privileges to access the data in the databases. Mandatory field.
Example:;; userdi
[#dataflow-oracle-conn-password]
include::partial$dataflow/password.adoc[]

[#dataflow-oracle-conn-service-name]
Service name:: Service name is the TNS alias that you give when you remotely connect to your database. This Service name is recorded in Tnsnames.ora file on your clients. It can be the same as SID and you can also give it any other name you want. Mandatory field.
Example:;; idxdb03
[#dataflow-oracle-conn-ad-user]
AD user:: Enable this option to use single sign-on and multi-factor authentication to avoid security breach.
////
[#dataflow-oracle-conn-version]
Version:: Specify the Oracle version being connected to. Optional field.
Example:;; 11.x
Other notes:;; Advanced configuration.
////
[#dataflow-oracle-conn-jdbc-options]
include::partial$dataflow/jdbc-options.adoc[]

[#sync-properties]
== Sync properties
[#dataflow-oracle-sync-data-extraction-mode]
Data extraction mode:: Specify the extraction type. Optional field.
Example:;; JDBC
Valid Values:;; JDBC,OCI
Default:;; JDBC
[#dataflow-oracle-sync-column-delimiter]
Column delimiter:: Specify the column delimiter character. Mandatory field.
Example:;; 1
Valid Values:;; Any printable ASCII character or decimal value for ASCII character
Default:;; 1
[#dataflow-oracle-sync-null-value]
Null value::
Specifies the string literal that should indicate the null value in the extracted data.
During the data load the column value matching this string will be loaded as null in the target. Optional field.
Example:;; NULL
Valid Values:;; Any string literal
Default:;; NULL
[#dataflow-oracle-sync-enclosing-character]
Enclosing character:: Specify if the text columns in the source data needs to be enclosed in quotes. Optional field.
Example:;; DOUBLE
Valid Values:;; SINGLE, DOUBLE
Default:;; DOUBLE
Other notes:;; This is required if the text data has newline character or delimiter character.
[#dataflow-oracle-sync-escape-character]
Escape character:: Specify the escape character if using a text qualifier in the source data. Optional field.
Example:;; \"
Valid Values:;; Any ASCII character
Default:;; \"
[#dataflow-oracle-sync-fetch-size]
Fetch size::
Specify the number of rows to be fetched at a time and processed in memory.
If the value specified is zero then, all rows are extracted at once. Optional field.
Example:;; 1000
Valid Values:;; Any numeric value
Default:;; 1000
[#dataflow-oracle-sync-max-ignored-rows]
include::partial$dataflow/max-ignored-rows.adoc[]

[#dataflow-oracle-sync-ts-load-options]
include::partial$dataflow/ts-load-options.adoc[]
