= Azure Blob Storage connection reference
:last_updated: 09/10/2021
:experimental:
:linkattrs:
:page-aliases: /data-integrate/dataflow/dataflow-azure-blob-storage-reference.adoc


Learn about the fields used to create an Azure Blob Storage connection with ThoughtSpot DataFlow.

Here is a list of the fields for an Azure Blob Storage connection in ThoughtSpot DataFlow.
You need specific information to establish a seamless and secure connection.

[#connection-properties]
== Connection properties
[#dataflow-azure-blob-storage-conn-connection-name]
Connection name:: Name your connection. Mandatory field.
Example:;; AzureBlobAStorageConnection
[#dataflow-azure-blob-storage-conn-connection-type]
Connection type:: Choose the Azure Blob Storage connection type. Mandatory field.
Example:;; Azure Blob Storage
[#dataflow-azure-blob-storage-conn-storage-type]
Storage type:: Choose the Storage type: _Azure Blob Storage_ (default) or _Data Lake GEN2 Storage_. Mandatory field.
[#dataflow-azure-blob-storage-conn-account]
Account:: Azure Storage has an address that includes our unique account name which is a combination of the account name and the Azure Storage blob endpoint forms the base address for the objects in your storage account. Mandatory field.
Example:;; userdi
[#dataflow-azure-blob-storage-conn-authentication-type]
Authentication type:: This supports two types of authentication methods:
Azure account key:;; Choose to authenticate based on access keys and other parameters to produce an encrypted signature string that is passed on the request in the Authorization header.
Shared access signatures (SAS):;; Choose to grant fine-grained access to resources in your storage account with specified permissions and over a specified time interval. Mandatory field.
Example:;; Azure account key
Valid Values:;; Azure account key +
Shared access signature
[#dataflow-azure-blob-storage-conn-key]
Key:: The 512-bit access key generated while creating storage account. Mandatory field.
Example:;; ABCDEFGH245HIJK
[#dataflow-azure-blob-storage-conn-folder]
Folder:: Give the storage folder details. Mandatory field.
Availability:;; Displayed only when "Authentication type" is Datalake GEN2 Storage.
Example:;; difolder
[#dataflow-azure-blob-storage-conn-container]
Container:: Give container details that organizes a set of blobs, like a directory in a file system. Mandatory field.
Example:;; container

[#sync-properties]
== Sync properties
[#dataflow-azure-blob-storage-sync-file-name]
File name:: Specify name of the file. +
Mandatory field.
Example:;; testfile.csv
Valid Values:;; Any string literal
Default:;; The name of the file used to create sync.
Other notes:;; To specify wildcard pattern use `*` character in the file name
[#dataflow-azure-blob-storage-sync-column-delimiter]
Column delimiter:: Specifies the delimiter between the columns in the source file. +
Mandatory field.
Example:;; ,
Valid Values:;; Any printable ASCII character or decimal value for ASCII character
Default:;; The delimiter specified in sync
[#dataflow-azure-blob-storage-sync-enable-archive-on-success]
Enable archive on success:: Specify if file needs to be archived once it is succeeded. Optional field.
Example:;; No
Valid Values:;; Yes, No
Default:;; No
[#dataflow-azure-blob-storage-sync-delete-on-success]
Delete on success:: Specify if file needs to be deleted after execution is successful. Optional field.
Example:;; No
Valid Values:;; Yes, No
Default:;; No
[#dataflow-azure-blob-storage-sync-compression]
Compression:: Specify this if the file is compressed and what kind of compressed file it is. Mandatory field.
Example:;; gzip
Valid Values:;; None, gzip
Default:;; None
[#dataflow-azure-blob-storage-sync-enclosing-character]
Enclosing character:: Specify if the text columns in the source data is enclosed in quotes. Optional field.
Example:;; Single
Valid Values:;; Single, Double, Empty
Default:;; Empty
[#dataflow-azure-blob-storage-sync-escape-character]
Escape character:: Specify the escape character if using a text qualifier in the source data. Optional field.
Example:;; \\
Valid Values:;; Any ASCII character
Default:;; Empty
[#dataflow-azure-blob-storage-sync-null-value]
Null value::
Specifies the string literal indicates the null value for a column.
During the data load, the column value matching this string will be loaded as null in the target. Optional field.
Example:;; NULL
Valid Values:;; Any string literal
Default:;; NULL
[#dataflow-azure-blob-storage-sync-date-style]
Date style:: Specifies how to interpret the date format. Optional field.
Example:;; YMD
Valid Values:;; `YMD`, `MDY`, `DMY`, `DMONY`, `MONDY`, `Y2MD`, `MDY2`, `DMY2`, `DMONY2`, and `MONDY2`
Default:;; `YMD`
Other notes:;; `MDY`: 2-digit month, 2-digit day, 4-digit year +
`DMY`: 2-digit month, 2-digit day, 4-digit year +
`DMONY`: 2-digit day, 3-character month name, 4-digit year +
`MONDY`: 3-character month name, 2-digit day, 4-digit year +
`Y2MD`: 2-digit year, 2-digit month, 2-digit day +
`MDY2`: 2-digit month, 2-digit day, 2-digit year +
`DMY2`: 2-digit day, 2-digit month, 2-digit year +
`DMONY2`: 2-digit day, 3-character month name, 2-digit year +
`MONDY2`: 3-character month name, 2-digit day, 2-digit year
[#dataflow-azure-blob-storage-sync-date-delimiter]
Date delimiter:: Specifies the separator used in the date format. Optional field.
Example:;; -
Valid Values:;; Any printable ASCII character
Default:;; -
[#dataflow-azure-blob-storage-sync-time-style]
Time style:: Specifies the format of the time portion in the data. Optional field.
Example:;; 24HOUR
Valid Values:;; 12HOUR, 24 HOUR
Default:;; 24HOUR
[#dataflow-azure-blob-storage-sync-time-delimiter]
Time delimiter:: Specifies the character used as separate the time components. Optional field.
Example:;; :
Valid Values:;; Any printable ASCII character
Default:;; :
[#dataflow-azure-blob-storage-sync-skip-trailer-rows]
Skip trailer rows:: Skip the number of trailer rows specified while loading the data. Optional field.
Example:;; 5
Valid Values:;; Any numeric value
Default:;; 0
[#dataflow-azure-blob-storage-sync-ts-load-options]
include::partial$dataflow/ts-load-options.adoc[]
[#dataflow-azure-blob-storage-sync-boolean-representation]
Boolean representation:: Specifies the representation of data in the boolean field. Optional field.
Example:;; true_false
Valid Values:;; true_false, T_F, 1_0, T_NULL
Default:;; true_false
