= Netezza connection reference
:last_updated: 09/10/2021
:experimental:
:linkattrs:
:page-aliases: /data-integrate/dataflow/dataflow-netezza-reference.adoc

Learn about the fields used to create a Netezza connection with ThoughtSpot DataFlow.

Here is a list of the fields for a Netezza connection in ThoughtSpot DataFlow.
You need specific information to establish a seamless and secure connection.

[#connection-properties]
== Connection properties
[#dataflow-netezza-conn-connection-name]
Connection name:: Name your connection. Mandatory field.
Example:;; NetezzaConnection
[#dataflow-netezza-conn-connection-type]
Connection type:: Choose the Netezza connection type. Mandatory field.
Example:;; Netezza
[#dataflow-netezza-conn-host]
Host:: Specify the hostname or the IP address of the Netezza system. Mandatory field.
Example:;; www.example.com
[#dataflow-netezza-conn-port]
Port:: Specify the port associated to the Netezza system. Mandatory field.
Example:;; 1234
[#dataflow-netezza-conn-user]
User::
Specify the user id that will be used to connect to the Netezza system.
This user should have necessary privileges to access the data in the databases. Mandatory field.
Example:;; userdi
[#dataflow-netezza-conn-password]
include::partial$dataflow/password.adoc[]

////
[#dataflow-netezza-conn-version]
Version:: Specify the Netezza version being connected to. Optional field.
Example:;; 7.x
Other notes:;; Advanced Configuration.
////
[#dataflow-netezza-conn-jdbc-options]
include::partial$dataflow/jdbc-options.adoc[]

[#sync-properties]
== Sync properties
[#dataflow-netezza-sync-data-extraction-mode]
Data extraction mode:: Specify the extraction type. Optional field.
Example:;; External table
Valid Values:;; External table, JDBC
Default:;; External Table
[#dataflow-netezza-sync-column-delimiter]
Column delimiter:: Specify the column delimiter character. Mandatory field.
Example:;; 1
Valid Values:;; Any printable ASCII character or decimal value for ASCII character
Default:;; 1
[#dataflow-netezza-sync-enclosing-character]
Enclosing character:: Specify if the text columns in the source data needs to be enclosed in quotes. Optional field.
Example:;; DOUBLE
Valid Values:;; SINGLE, DOUBLE
Default:;; DOUBLE
Other notes:;; This is required if the text data has newline character or delimiter character.
[#dataflow-netezza-sync-escape-character]
Escape character:: Specify the escape character if using a text qualifier in the source data. Optional field.
Example:;; \"
Valid Values:;; Any ASCII character
Default:;; \"
[#dataflow-netezza-sync-socket-buffer-size]
Socket buffer size:: Specifies the chunk size at which to read the data from the source, expressed in bytes. Optional field.
Example:;; 8
Valid Values:;; Any numeric value
Default:;; 8
[#dataflow-netezza-sync-max-ignored-rows]
include::partial$dataflow/max-ignored-rows.adoc[]

[#dataflow-netezza-sync-ts-load-options]
include::partial$dataflow/ts-load-options.adoc[]
