= Hide a column
:last_updated: 02/01/2021
:linkattrs:
:experimental:
:page-aliases: 

You can hide columns from users in ThoughtSpot without dropping them from the database. It is common to hide a column when its data contains identifier columns that are used to join tables, but which do not have any meaning to users.

As the number of columns in the dataset increases, the search experience requires more effort.
Users have to navigate through larger numbers of columns to choose the correct one.
There might also be some columns in the dataset that you don't want to expose to the users.

When you hide a worksheet, table, or view column, you only hide it from users without *edit* privileges on the object. Administrators and users with edit privileges on the object can still see and interact with the hidden column. Users without edit privileges for the object cannot see or interact with the hidden column.

To hide a column, change the *HIDDEN* (UI)/*Hide* (model file) setting. By default, all columns in a data source appear in ThoughtSpot. To hide these columns, set the *HIDDEN* setting to `YES`.

. Find the *HIDDEN* (UI)/*Hide* (model file) setting for a column.
. Set its value to `YES`.
. Save your changes.
