= Sync data through a Dremio connection
:last_updated: 9/13/2021
:experimental:
:linkattrs:
:page-aliases: /data-integrate/dataflow/dataflow-dremio-sync.adoc

After using ThoughtSpot DataFlow to establish a connection to a Dremio database, you can create automatic data updates, to seamlessly refresh your data.

include::partial$sync-for-databases.adoc[]

. Specify the sync properties for Denodo:
+
See xref:dataflow-dremio-reference.adoc#sync-properties[Sync properties] for details, defaults, and examples.
+
xref:dataflow-dremio-reference.adoc#dataflow-dremio-sync-column-delimiter[Column delimiter]::
Specify the column delimiter character.
xref:dataflow-dremio-reference.adoc#dataflow-dremio-sync-enclosing-character[Enclosing character]::
Specify when the text columns in the source data must be enclosed in quotes.

xref:dataflow-dremio-reference.adoc#dataflow-dremio-sync-escape-character[Escape character]::
Specify this if the text qualifier is mentioned. This should be the character which escapes the text qualifier character in the source data.

xref:dataflow-dremio-reference.adoc#dataflow-dremio-sync-fetch-size[Fetch size]::
Specify the number of rows to fetch at one time, and process in memory.

xref:dataflow-dremio-reference.adoc#dataflow-dremio-sync-max-ignored-rows[Max ignored rows]::
Abort the transaction after encountering 'n' ignored rows.

xref:dataflow-dremio-reference.adoc#dataflow-dremio-sync-ts-load-options[TS load options]::
Specifies the parameters passed with the `tsload` command, in addition to the commands already included by the application.
+
The format for these parameters is:
+
----
--<param_1_name><optonal_param_1_value>
--<param_2_name><optonal_param_21_value>
----

. Save your work by clicking *Save*.
+
Alternatively, click *Save and sync now* to save your work and sync data at the same time.
