= Sync data through Flat files connection using DataFlow
:last_updated: 7/7/2020

After using ThoughtSpot DataFlow to establish a connection to a flat files, either local or remote, you can create automatic data updates, to seamlessly refresh your data.

include::partial$sync-for-file-systems.adoc[]

. Specify the sync properties for files:
 ** xref:dataflow-files-reference.adoc#dataflow-files-sync-file-name[File name]
 +
Specify name of the file.
 ** xref:dataflow-files-reference.adoc#dataflow-files-sync-column-delimiter[Column delimiter]
 +
Specify the column delimiter character.
 ** xref:dataflow-files-reference.adoc#dataflow-files-sync-enable-archive-on-success[Enable archive on success]
 +
Specify if system is to archive file after successful sync.
 ** xref:dataflow-files-reference.adoc#dataflow-files-sync-delete-file-on-success[Delete file on success]
 +
Specify if system to delete file after successful sync.
 ** xref:dataflow-files-reference.adoc#dataflow-files-sync-compression[Compression]
 +
Specify if file uses compression, and compression type.
 ** xref:dataflow-files-reference.adoc#dataflow-files-sync-skip-header-rows[Skip header rows]
 +
Specify the number of header rows to skip when loading data.
 ** xref:dataflow-files-reference.adoc#dataflow-files-sync-enclosing-character[Enclosing character]
 +
Specify if the text columns in the source data needs to be enclosed in quotes.
 ** xref:dataflow-files-reference.adoc#dataflow-files-sync-escape-character[Escape character]
 +
Specify the escape character if using a text qualifier in the source data.
 ** xref:dataflow-files-reference.adoc#dataflow-files-sync-null-value[Null value]
 +
Specifies the string literal indicates the null value for a column. During the data load, the column value matching this string will be loaded as null in the target.
 ** xref:dataflow-files-reference.adoc#dataflow-files-sync-date-style[Date style]
 +
Specifies how to interpret the date format.
** xref:dataflow-files-reference.adoc#dataflow-files-sync-date-delimiter[Date delimiter]
+
Specifies the separator used in the date format.
** xref:dataflow-files-reference.adoc#dataflow-files-sync-time-style[Time style]
+
Specifies the format of the time portion in the data.
** xref:dataflow-files-reference.adoc#dataflow-files-sync-time-delimiter[Time delimiter]
+
Specifies the character used to separate the time components.
** xref:dataflow-files-reference.adoc#dataflow-files-sync-statistics[Statistics]
+
Specify if the file source count needs to be displayed in Monitor statistics.
** xref:dataflow-files-reference.adoc#dataflow-files-sync-skip-trailer-rows[Skip trailer rows]
+
Skip trailer row while processing the data.
** xref:dataflow-files-reference.adoc#dataflow-files-sync-reader-encoder[Reader encoder]
+
Specify the encoding format of the source system.
** xref:dataflow-files-reference.adoc#dataflow-files-sync-tsload-options[TS load options]
+
Specifies the parameters passed with the `tsload` command, in addition to the commands already included by the application. The format for these parameters is:
+
`--<param_1_name> <optional_param_1_value>`
+
`--<param_2_name> <optional_param_2_value>`
+
Optional field.
 ** xref:dataflow-files-reference.adoc#dataflow-files-sync-boolean-representation[Boolean representation]
 +
Specifies the representation of data in the boolean field.

+
See xref:dataflow-files-reference.adoc#sync-properties[Sync properties] for details, defaults, and examples.
. Save your work by clicking *Save*.
+ Alternatively, click *Save and sync now* to save your work and sync data at the same time.

'''
> **Related information**
>
> * xref:dataflow-files-add.adoc[Add a connection]
> * xref:dataflow-files-reference.adoc[Reference]