= ThoughtSpot software deployment
:last_updated: 9/22/2021
:linkattrs:
:experimental:
:description: You can install ThoughtSpot Software on a cloud provider, VMware, or on a hardware appliance.

You can install ThoughtSpot Software on a cloud provider or VMware.

NOTE: ThoughtSpot has stopped selling and renewing hardware appliance contracts. See xref:end-of-service-centos.adoc#hardware-impact[CentOS end-of-life announcement] for more information, and alternative deployment options.

All ThoughtSpot nodes need to be on the same platform and same subnet with no connectivity blocked between any two nodes.
You can have multiple clusters on multiple platforms, but you cannot host one cluster on multiple platforms.

This guide instructs you on how to prepare each of the following:

* xref:customer-os.adoc[Deploying ThoughtSpot on your own OS (RHEL, OEL, or AL2)]
* xref:hardware-appliance.adoc[Hardware appliance]
* xref:aws-configuration-options.adoc[Amazon Web Services (AWS) EC2]
* xref:azure-configuration-options.adoc[Microsoft Azure]
* xref:gcp-configuration-options.adoc[Google Cloud Platform (GCP)]
* xref:vmware.adoc[VMware]

After you configure your nodes, you can contact {support-url}.

[#encryption]
== Data encryption at rest

ThoughtSpot has validated that the following scenarios work with ThoughSpot on-premise deployments:

* https://cpl.thalesgroup.com/encryption/vormetric-data-security-platform[Vormetric^] Transparent Encryption on RHEL 7 deployments
* https://cpl.thalesgroup.com/resources/encryption/protectfile-file-encryption-product-brief[ProtectFile^] encryption on ThoughtSpot-provided CentOS deployments

[NOTE]
====
* You must provide your own transparent encryption software at file or folder level. Contact your software vendor of choice for support.
* ThoughtSpot does not make recommendations of specific software applications, nor do we directly support or provide configuration recommendations for third-party encryption software.
====
