= Deprecation announcements
:last_updated: 09/15/2021
:linkattrs:
:experimental:
:description: In this article, we give you advance notice of features we are discontinuing in future releases.


ThoughtSpot sometimes deprecates and then removes existing features, replacing them with new and more effective means to use our products.
In this article, we give you advance notice of features we are discontinuing in future releases.

Please https://community.thoughtspot.com/customers/s/contactsupport[contact^] your Customer Success or SRE team for clarification.

ThoughtSpot _deprecates_ some existing features, and then _removes_ them. These terms mean two different things.

Deprecated::
A deprecated feature still exists in the product, for backward compatibility, but there is a plan to remove it in a later release. Deprecated features do not receive ongoing support from ThoughtSpot.
+
We recommend that you stop using deprecated features as soon as possible, and change your workflows to use the new, improved functionality instead.

Removed::
A removed feature no longer exists in the product. When you upgrade to a newer release, any workflows that rely on a removed feature no longer work.

[#deprecated-9-0-0-sw]
== Deprecated in 9.0.0.sw

The 9.0.0.sw release of ThoughtSpot Software, targeted for February 2023 (LA) and April 2023 (GA), will drop support for the following feature:

Pin Headlines:: ThoughtSpot will deprecate the pin Headline to Liveboard feature. Beginning in the 9.0.0.sw Software release, users will no longer see the pin icon when they select table summaries. To visualize and pin single aggregated measures, attributes in string/date format, or time-series metrics with sparklines, we recommend creating xref:chart-kpi.adoc[KPI charts]. Existing Headlines pinned to Liveboards will not be affected in this release.

[#removed-9-0-0-sw]
== Removed in 9.0.0.sw

The 9.0.0.sw release of ThoughtSpot Software, targeted for February 2023 (LA), and April 2023 (GA), will *remove* the Instant Search functionality. Instead, searching in ThoughtSpot will use the xref:search-bar.adoc#search-on-enter[Search on Enter] functionality.

In Instant Search, the system triggers a query every time you add an item to the search bar. When you use Search on Enter, the system only triggers a query when you select the *Go* button. Search on Enter avoids unnecessary query cost and ensures that users are in full control of when to trigger a query.

[#deprecated-8-8-0-sw]
== Deprecated in 8.8.0.sw
The 8.8.0.sw release of ThoughtSpot Software, targeted for October 2022, will *deprecate* the following features. ThoughtSpot will drop support for these features in a later release.

=== New Liveboard experience deprecations

include::partial$new-liveboard-experience-deprecations.adoc[]

[#removed-8-4-0-sw]
== Removed in 8.4.0.sw [LA]
Liveboard follow::
In 7.2.1 and earlier, there are two different ways for a user to ask ThoughtSpot to email them a Liveboard PDF on a specified schedule.
Users can follow the Liveboard, or xref:liveboard-schedule.adoc[schedule a Liveboard job].
+
In 8.4.0.sw [LA] and later releases, ThoughtSpot will combine these features into a single action called "Schedule." The *Follow* option will not be available.
This change will allow any user to schedule their own Liveboard emails.
To send Liveboard emails to other users, you still need the xref:privileges-end-user.adoc#schedule-liveboards[*Can schedule for others* permission].
+
ThoughtSpot will migrate any existing Liveboard follows to Liveboard schedules.
If you followed a Liveboard in releases earlier than 8.4.0.sw [LA], you will see it in the list of Liveboard schedules for that Liveboard as _Migrated from follow (your display name)_.

[#deprecated-8-4-0-sw]
== Deprecated in 8.4.0.sw [LA]
The 8.4.0.sw [LA] release of ThoughtSpot Software, targeted for May 2022 (LA) and August 2022 (GA), will *deprecate* the following features. ThoughtSpot will drop support for these features in a later release.

=== New answer experience deprecations

include::partial$new-answer-experience-deprecations.adoc[]

[#removed-7-2-1]
== Removed in 7.2.1
The 7.2.1 release of ThoughtSpot Software, targeted for April 2022 (GA), will drop support for *Self-Service Upgrade (SSU)*. This feature allowed customers to upgrade their environment to a new ThoughtSpot release themselves, from the UI.

Additionally, the 7.2.1 release will drop support for the *Available Updates* section of the *Upgrade* page in the Admin Console. The *Available Updates* section contained information about available releases customers could upgrade to.

*Self-Service Upgrade* and *Available Updates* both appeared on the *Upgrade* page in the Admin Console. This page will not be available, starting in release 7.2.1.

As an alternative, contact {support-url} to upgrade your Software environment when necessary, or consider ThoughtSpot's Software as a Service offering, https://cloud-docs.thoughtspot.com[ThoughtSpot Cloud^], which upgrades to the latest Cloud release automatically.

[#removed-7-1-1]
== Removed in 7.1.1

The 7.1.1 release of ThoughtSpot Software, targeted for November 2021 (GA), will drop support for the following feature.

Ask an Expert::
This feature allowed users to ask a designated expert on a particular data source for help when they run into an issue with an answer or search they created on that data source. Starting in 7.0.1, users can learn about specific data sources in a different way, by completing xref:search-assist.adoc[Search Assist] sample queries on their own data sources.

[#remove-7-1]
== Removed in 7.1

The 7.1 release of ThoughtSpot Software, targeted for July 2021 (LA) and Oct 2021 (GA), will drop support for the following features.

Instant Insights::
Prior to 7.1, the Instant Insights feature worked only in on-prem deployments that use our internal database, Falcon. Connections and cloud deployments never supported Instant Insights.
+
Prior to 7.1, Instant Insights appeared in four (4) areas of our product:
+
--
- Home Page: Did you know
- Search: under the answer
- Liveboard: Liveboard Insights at the top of the Liveboard
- Worksheet and Table: the Spotiq Insights tab
--

Learn how to use ThoughtSpot Liveboard::
This Liveboard contained search replays created in the system. The Replay Search feature is also removed in 7.1. Customers currently use *Replay search* and the *Learn how to use ThoughtSpot Liveboard* to learn how to use ThoughtSpot's search on data. As an alternative, starting in 7.0.1, use xref:search-assist.adoc[Search Assist] to learn how to use ThoughtSpot search on xref:search-assist-coach.adoc[your company's data].

Replay search::
This feature allowed you to replay the search used to create an answer. As an alternative, starting in 7.0.1, use xref:search-assist.adoc[Search Assist] to learn how to use ThoughtSpot search on xref:search-assist-coach.adoc[your company's data].

Custom actions::
Starting in the 7.1.0 software release, embed customers can no longer use custom actions created in the *Action customization* section of the Admin Console, or create new custom actions in the Admin Console.
+
Instead, starting in the 8.4.0.sw [LA] release, if you are embedding through https://developers.thoughtspot.com/[ThoughtSpot Everywhere^], you can create new custom actions in the Develop tab. Refer to https://developers.thoughtspot.com/docs/?pageid=customize-actions#_custom_actions_page[Custom actions overview^].

[#remove-7-0]
== Removed in 7.0

SearchIQ::
The 7.0 release of ThoughtSpot Software, targeted for March 2021 (LA) and June 2021 (GA), will drop support for  *SearchIQ*. This feature was always in Beta, and was never deployed on production environments.
+
As we move to ThoughtSpot Cloud, we incorporate and further enrich the affordances of SearchIQ in Ask Answers features, and in an enhanced experience with our Home page.

SpotIQ Monitor Headlines::
The 7.0 release of ThoughtSpot Software, targeted for March 2021 (LA) and June 2021 (GA) will drop support for SpotIQ Headline Monitoring. This feature has been in Beta and was never deployed on production environments.
