= Developer
:last_updated: 7/20/2021
:linkattrs:
:experimental:

Developer users embed ThoughtSpot content in their applications by using ThoughtSpot SDK and APIs.

ThoughtSpot provides a Developer portal to external users to embed ThoughtSpot content in their application, web page, portal, or business solution. Browse through the following topics to get started with embedding ThoughtSpot:

* xref:embedding-overview.adoc[Embedding]
//- ThoughtSpot Integration guidelines
//- ThoughtSpot Developer portal
//- Security settings for embedding
* xref:js-api.adoc[Use the JavaScript API]
* xref:saml-integration.adoc[SAML]
** xref:saml.adoc[Configure SAML]
** xref:saml-configure-siteminder.adoc[Configure CA SiteMinder]
** xref:active-directory-federated-services.adoc[Configure Active Directory Federated Services]
* xref:data-api.adoc[Data REST API]
** xref:data-api-calling.adoc[Calling the REST API]
** xref:data-api-pagination.adoc[REST API pagination]
** xref:data-api-get.adoc[Use the Data REST API to get data]
** xref:data-api-search.adoc[Use the Embedded Search API]
** xref:data-api-push.adoc[Use the Data Push API]
* xref:embedding.adoc[Embed ThoughtSpot]
** xref:embed-viz.adoc[Embed Pinboard or visualization]
** xref:js-api-enable.adoc[Authentication flow with embed]
** xref:embed-full.adoc[Full application embedding]
** xref:trusted-authentication.adoc[Configure trusted authentication]
* xref:runtime-filters.adoc[Runtime Filters]
** xref:runtime-filter-apply.adoc[Apply a Runtime Filter]
** xref:runtime-filter-operators.adoc[Runtime Filter Operators]
//* Visual Embed SDK
* xref:customization.adoc[Style customization for embedded content]
** xref:customize-logo.adoc[Upload application logos]
** xref:customize-fonts.adoc[Set chart and table visualization fonts]
** xref:customize-background.adoc[Choose a background color]
** xref:customize-color-palettes.adoc[Select chart color palettes]
** xref:customize-footer-text.adoc[Change the footer text]
** xref:admin-portal-customize-actions-menu.adoc[Customize Answer actions]




NOTE: To access ThoughtSpot Developer portal, you require developer privileges.

////
As an Admin, you have a vital role to manage user and group access, local authentication, and integration with SAML.
These are the Admin tasks that you have to complete to make ThoughtSpot available for everyone in your organization. We take care of the rest.

Manage users
Manage groups
Manage local authentication
Managing authentication with SAML
Style customization
Help customization
View scheduled maintenance
View user activity
Monitor app performance
In-app acceptance of ThoughtSpot's use agreement
Manage search and SpotIQ settings
Manage email and onboarding settings
////

////
Your role is to establish connections to data. Here is how you can connect to all your data.
The following list provides information about connecting to your data in supported data warehouses.


Direct Connections with Embrace::
Snowflake
Overview
Add connection
Edit connection
Remap connection
Delete a table
Delete a table with object dependencies
Delete connection
Best practices
Connection reference
 Amazon Redshift
Overview
Add connection
Edit connection
Remap connection
Delete a table
Delete a table with object dependencies
Delete connection
Connection reference
 Google BigQuery
Overview
Add connection
Edit connection
Remap connection
Delete a table
Delete a table with object dependencies
Delete connection
Connection reference
 Azure Synapse
Overview
Add connection
Edit connection
Remap connection
Delete a table
Delete a table with object dependencies
Delete connection
Connection reference
 Oracle ADW
Overview
Add connection
Edit connection
Remap connection
Delete a table
Delete a table with object dependencies
Delete connection
Connection reference
 Starburst
Overview
Add connection
Edit connection
Remap connection
Delete a table
Delete a table with object dependencies
Delete connection
Connection reference
 Databricks
Overview
Add connection
Edit connection
Remap connection
Delete a table
Delete a table with object dependencies
Delete connection
Connection reference

Getting data into Falcon with DataFlow::
DataFlow information
////

////
Search Assist::
See how ThoughtSpot Search gives you insights into your own data.

Onboarding for Analysts::
Get a comprehensive look at how to create modern and dynamic dashboards for your organization.

Scriptability::
Use SpotApps to export Worksheets, Pinboards, and Answers in a human-readable format.

SpotApp Templates::
Use SpotApp templates to gain insights into your Salesforce, accounts receivable, or procurement instances.

ThoughtSpot Modeling Language::
Modify a Worksheet, Pinboard, or Answer in a flat-file format.
////
////
Getting started for Business users::
Get a quick overview of how ThoughtSpot can support you.
+
See xref:getting-started.adoc[].

Home page::
This is where you get direct access to exisiting Answers, Pinboards, and visualizations.

Pinboards and Answers::
Quick tips on how you can use and customize Pinboards and Charts.
+
See xref:charts.adoc[], xref:chart-types.adoc[], xref:chart-change.adoc[], and xref:pinboards.adoc[].

ThoughtSpot Search::
Explore our flagship Search functionality.
+
See xref:search.adoc[].
////
////
Search Assist::
See how ThoughtSpot Search Assist gives you insights into your own data.
////

Mobile App::
Access your ThoughtSpot cluster to search Answers and Pinboards, and create Pinboards.
+
See xref:mobile.adoc[].


////
from old user guide


* *xref:navigating-thoughtspot.adoc[Finding your way around]* +
 To make navigation easy, we organized ThoughtSpot into several sections.
You can see them on the menu bar.
* *xref:user-profile.adoc[About the user profile]* +
 The user icon lets you view your profile, or sign out of ThoughtSpot.
* *xref:privileges-end-user.adoc[Understanding privileges]* +
 Your privileges determine the things you can do.
ThoughtSpot sets privileges at the group level.
* *xref:tags.adoc[About tags]* +
 You can create tags to make it easier for people to find data sources and pinboards.

* xref:search.adoc[Use search]
* xref:answers.adoc[Work with Answers]
* xref:filters.adoc[Work with filters]
* xref:charts.adoc[Work with charts]
* xref:formulas.adoc[Work with formulas]
* xref:pinboards.adoc[Use pinboards]
* xref:answer-explorer.adoc[Answer Explorer]
* xref:r-thoughtspot.adoc[About R in ThoughtSpot]
* xref:spotiq.adoc[SpotIQ]
* xref:data-sources.adoc[Work with data]
* xref:help-center.adoc[]
////
