= About disaster recovery
:last_updated: 02/02/2021
:linkattrs:
:experimental:

ThoughtSpot's disaster recovery prevents data loss if there is a hardware or software failure.

Disaster recovery is the ability to recover from a hardware or software failure or a catastrophic event.
ThoughtSpot protects you from data loss in the event of a hardware or software failure or a catastrophic event.

ThoughtSpot takes snapshots of itself automatically at periodic intervals.
These can be pulled out as backups at intervals or manually as needed.
See the ThoughtSpot Administrator Guide for details on backups, snapshots and restore operations.

The information here addresses disaster recovery specifically.
These are some potential types of failure, listed in increasing order of severity:

xref:disk-failure.adoc[Disk failure]::
ThoughtSpot uses replication of stored data. When a disk faila, ThoughtSpot continues to operate.

xref:node-failure.adoc[Node failure]::
ThoughtSpot uses replication of stored data. When a node fails, ThoughtSpot continues to operate.
+
See also xref:ha-resilience.adoc[High Availability and resilience].

xref:cluster-replacement.adoc[Cluster replacement]::
Using a mirrored system architecture, you can replace faulty clusters. This approach enables you to rapidly recover an entire system without data loss.
+
ThoughtSpot supports recovery from disk or node failure within each appliance.
+
You can also architect your system to support loss of an entire appliance, which is the highest level of disaster recovery.
