= Embed ThoughtSpot
:last_updated: 05/24/2022
:linkattrs:
:experimental:
:page-aliases:
:page-description: ThoughtSpot supports several embedding options to embed ThoughtSpot in your web application or portal.


ThoughtSpot supports embedding Search, Liveboard, visualizations, and the full ThoughtSpot experience in a web application, product, or portal.

NOTE: Starting from the 8.4.0-sw release (Limited Availability), customers licensed to embed ThoughtSpot can use ThoughtSpot Embedded features and Visual Embed SDK. +
To enable ThoughtSpot Embedded on your cluster, contact {support-url}.

== Supported embedding methods

Based on your embedding requirements and integration setup, you can use one of the following embedding methods:

* link:https://developers.thoughtspot.com/docs/?pageid=visual-embed-sdk[Embed using Visual Embed SDK, window=_blank] (Recommended)
* link:https://developers.thoughtspot.com/docs/?pageid=embed-without-sdk[iFrame embedding without SDK, window=_blank]
* xref:embedding-overview.adoc[Legacy embedding method with app.min.js]

To determine the method that best fits your embedding requirement, refer to the link:https://visual-embed-sdk-8-4.vercel.app/docs/?pageid=embed-ts[Feature details and recommendations, window=_blank].

== ThoughtSpot Embedded

ThoughtSpot Embedded provides a low-code embedded analytics platform for developers and product owners to build interactive data apps and incorporate ThoughtSpot functions and services directly into their apps, products, or services.

It offers several features to enhance your embedding experience:

* Visual Embed SDK for quick and easy embedding
* A developer portal with interactive developer Playgrounds, customization controls and security settings for the embedded view, and Developer Guides.
* REST API framework to programmatically create and manage objects, data, and automate deployments

For more information, see link:https://developers.thoughtspot.com/docs/?pageid=embed-analytics[ThoughtSpot Developer documentation, window=_blank].

== Legacy embedding method

For information about the legacy embedding method, see the following pages:

* xref:embedding-overview.adoc[Introduction to embedding]
* xref:embedding.adoc[Embed ThoughtSpot]
* xref:embed-viz.adoc[Embedded charts and Liveboards]
* xref:embed-full.adoc[Full application embedding]
* xref:data-api.adoc[Data REST API]
* xref:runtime-filters.adoc[Runtime filters]
* xref:customize-logo.adoc[Style customization]
* xref:public-api-reference.adoc[REST API reference]

== REST APIs

ThoughtSpot also provides data REST APIs using which you can embed an answer, Liveboard, or a specific visualization from a Liveboard. You can use these APIs with or without the SDK to embed ThoughtSpot content in your app.

For more information, see link:https://developers.thoughtspot.com/docs/?pageid=embed-data-restapi[Embed using REST APIs, window=_blank].
