= Introduction to embedding
:last_updated: 05/10/2022
:linkattrs:
:experimental:
:description: This article lists the features and capabilities of the legacy embedding method available with ThoughtSpot Extended Enterprise Edition.
:page-aliases: /app-integrate/introduction/introduction.adoc


This article lists the features and capabilities of the legacy embedding method available with ThoughtSpot Extended Enterprise Edition.

ThoughtSpot Extended Enterprise Edition includes these capabilities:

* xref:embed-full.adoc[Full application embedding]
* xref:embed-viz.adoc[Embedded charts and Liveboards]
* xref:data-api.adoc[REST API]
* xref:runtime-filters.adoc[Runtime filters]

NOTE: ThoughtSpot Extended Enterprise Edition license is available until ThoughtSpot Software release 7.x only. +
Starting from the 8.4.0-sw release (Limited Availability), customers licensed to embed ThoughtSpot can use ThoughtSpot Embedded features and Visual Embed SDK. +
To enable ThoughtSpot Embedded on your cluster, contact {support-url}.

== Rights and obligations

When you buy ThoughtSpot Extended Enterprise, the following rights and obligations apply:

. External users may only access those elements that are exposed through ThoughtSpot public APIs.
These include search, search results and data visualizations, saved Liveboards and answers, and SpotIQ.
. External users may not be granted Administrator privileges such as the ability to create and modify users and groups.
. External users are not permitted to copy or download the ThoughtSpot software.
. You may not include external users in a group that has access to these privileges:
** Can administer ThoughtSpot
** Can administer and bypass RLS
. The license for Extended Enterprise does not enable you to act as an MSP (Managed Service Provider).
This means that you must not offer managed services to third parties that are based on the ThoughtSpot software.
. As a company offering access to ThoughtSpot Extended Enterprise to external users, you are responsible for your own data policy and for complying with local laws and regulations concerning data privacy, such as GDPR and HIPAA.
. If you are using either *_Application Embedding_* or *_Embedded Search_*, an NPS (Net Promoter Score) survey will be offered to your external users.
You may not disable this survey.
+
If you are using either the *_Visualization Embedding_* or *_Liveboard Embedding_* in your application, it is okay to disable the NPS survey.
. Deployments of ThoughtSpot Extended Enterprise must conform to https://brand.thoughtspot.com/d/Vtg4Zg2mqTbE/brand-guidelines[logo restrictions].
+
These are the branding elements you can change in ThoughtSpot Extended Enterprise:

** xref:customize-logo.adoc[Logos & Favicon]
** xref:customize-color-palettes.adoc[Color Palettes]
** xref:customize-background.adoc[Background Color]
** xref:customize-fonts.adoc[Chart and Table Fonts]
** xref:customize-footer-text.adoc[Footer Text]

. You may not remove the _Powered by ThoughtSpot_ logo that appears at the lower right of the embedded application when using ThoughtSpot full application embed, or when embedding a Liveboard.
It is okay to remove the logo if you are embedding a single visualization.

'''
> **Related information**
>
> Here are the main topics for Embedding with Extended Enterprise:
>
> * xref:js-api-enable.adoc[Authentication flow with embed]
> * xref:saml-integration.adoc[About SAML]
> * xref:trusted-authentication.adoc[Configure trusted authentication]
> * xref:customize-logo.adoc[Style Customization]
> * xref:public-api-reference.adoc[REST API Reference]
