= Connection reference for Oracle ADW
:last_updated: 08/09/2021
:experimental:
:linkattrs:
:page-aliases: /data-integrate/embrace/embrace-adw-reference.adoc

Learn about the fields used to create an ADW connection using ThoughtSpot Embrace. You need specific information to establish a seamless and secure connection. All fields are required, except where noted.

[#embrace-adw-ref-connection-name]
Connection name::  Enter a new ADW connection name.
[#embrace-adw-ref-connection-description]
Connection description::
Provide a short description of the connection.
_(Optional)_
[#embrace-adw-ref-user]
User::  Enter the ADW account username.
[#embrace-adw-ref-password]
Password::  Enter the ADW account password.
[#embrace-adw-ref-net-service-name]
Net Service Name:: Specify the net service name of the ADW account.
[#embrace-adw-ref-wallet-file]
Wallet file:: Upload the wallet file containing your Oracle client credentials. If you do not have a wallet file, contact your Autonomous Database administrator.
[#embrace-adw-ref-schema]
Schema:: Specify the schema associated with the database.
_Optional field_.

'''
> **Related information**
>
> * xref:embrace-adw-add.adoc[]
> * xref:embrace-adw-modify.adoc[Modify an ADW connection]
