= BigQuery connection reference
:experimental:
:last_updated: 03/25/2021
:page-aliases: /data-integrate/embrace/embrace-gbq-reference.adoc

Learn about the fields used to create a BigQuery connection using ThoughtSpot Embrace.

Here is a list of the fields of a BigQuery connection in ThoughtSpot Embrace.
You need specific information to establish a seamless and secure connection.
All fields are required, except where noted.
[#embrace-gbq-ref-connection-name]
Connection name:: Enter a new BigQuery connection name.
[#embrace-gbq-ref-connection-description]
Connection description::
Provide a short description of the connection.
_(Optional)_
[#embrace-gbq-ref-project-id]
Project id::  Enter the project ID associated with the BigQuery database.
[#embrace-gbq-ref-service-account]
Service account::  Enter the service account JSON key associated with the BigQuery database. To generate the key, refer to xref:embrace-gbq-prerequisites.adoc#service-account[Google BigQuery prerequisites].

'''
> **Related information**
>
> * xref:embrace-gbq-prerequisites.adoc[]
> * xref:embrace-gbq-add.adoc[]
> * xref:embrace-gbq-modify.adoc[]