= Snowflake connection reference
:last_updated: 03/26/2021
:experimental:
:linkattrs:
:page-aliases: /data-integrate/embrace/embrace-snowflake-reference.adoc

Learn about the fields used to create a Snowflake connection with ThoughtSpot Embrace.

Here is a list of the fields of a Snowflake connection in ThoughtSpot Embrace.
You need specific information to establish a seamless and secure connection.
All fields are required, except where noted.
[#embrace-snowlake-ref-connection-name]
Connection name::  Enter a new Snowflake connection name.
[#embrace-snowlake-ref-connection-description]
Connection description::
Provide a short description of the connection.
_(Optional)_
[#embrace-snowlake-ref-account-name]
Account name::
Enter the account name associated with your Snowflake connection.
The account name is part of the URL that you use to access the Snowflake UI.
It is the portion of the URL before `snowflakecomputing.com`. +
*Example*: If your URL is `+https://abcd.xyz.efg.snowflakecomputing.com+`, your account name is `abcd.xyz.efg`.
[#embrace-snowlake-ref-user]
User::  Enter the Snowflake account username.
[#embrace-snowlake-ref-password]
Password::  Enter the Snowflake account password.
[#embrace-snowlake-ref-role]
Role::  Specify the privilege of the user.
[#embrace-snowlake-ref-warehouse]
Warehouse::  Specify the warehouse associated with the connection.
[#embrace-snowlake-ref-database]
Database::
Specify the database associated with the account.
_(Optional)_
[#embrace-snowflake-ref-oauth]
OAuth:: Enter the OAuth client ID associated with the Snowflake database.
[#embrace-snowflake-ref-oauth-client-secret]
OAuth client secret:: Enter the OAuth client secret associated with the Snowflake database.

'''
> **Related information**
>
> * xref:embrace-snowflake-add.adoc[Add a connection]
> * xref:embrace-snowflake-modify.adoc[Modify a Snowflake connection]
> * xref:embrace-snowflake-best.adoc[]
> * xref:embrace-snowflake-partner.adoc[Partner Connect], with an accompanying xref:embrace-snowflake-tutorial.adoc[Tutorial]