= Teradata connection reference
:last_updated: 06/18/2020
:permalink: /:collection/:path.html
:sidebar: mydoc_sidebar
:summary: Learn about the fields used to create a Teradata connection using ThoughtSpot Embrace.

Here is a list of the fields of a Teradata connection in ThoughtSpot Embrace.
You need specific information to establish a seamless and secure connection.
All fields are required, except where noted.
[#embrace-teradata-ref-connection-name]
Connection name::  Enter a new Teradata connection name.
[#embrace-teradata-ref-connection-description]
Connection description::
Provide a short description of the connection.
_(Optional)_
[#embrace-teradata-ref-host-id]
Host::  Enter the host associated with the Teradata database.
[#embrace-teradata-ref-user-id]
User::  Enter the user account associated with the Teradata database.
[#embrace-teradata-password]
Password::  Enter the password associated with the user account of the Teradata database.
[#embrace-teradata-ref-database]
Database::
Enter the database name associated with the Teradata database.
_(Optional)_

'''
> **Related information**
>
> * xref:embrace-teradata-add.adoc[]
> * xref:embrace-teradata-modify.adoc[]
