= Synapse connection reference
:last_updated: 03/25/2021
:page-aliases: /data-integrate/embrace/embrace-synapse-reference.adoc

Learn about the fields used to create a Synapse connection with ThoughtSpot Embrace.

Here is a list of the fields of a Synapse connection in ThoughtSpot Embrace.
You need specific information to establish a seamless and secure connection.
All fields are required, except where noted.
[#embrace-synapse-ref-connection-name]
Connection name::  Enter a new Synapse connection name.
[#embrace-synapse-ref-connection-description]
Connection description::
Provide a short description of the connection.
_(Optional)_
[#embrace-synapse-ref-host]
Host::  Enter the host name associated with the Synapse database.
[#embrace-synapse-ref-port]
Port::  Enter the port number associated with the Synapse database.
[#embrace-synapse-ref-user]
User::  Enter the Synapse account username.
[#embrace-synapse-ref-password]
Password::  Enter the Synapse account password.
[#embrace-synapse-ref-database]
Database::  Specify the database associated with the account.

'''
> **Related information**
>
> * xref:embrace-synapse-add.adoc[Add a connection]
> * xref:embrace-synapse-modify.adoc[Modify a connection]
