= Snowflake connection reference
:last_updated: 01/24/2020

Learn about the fields used to create a Snowflake connection with ThoughtSpot Embrace.

Here is a list of the fields of a Snowflake connection in ThoughtSpot Embrace.
You need specific information to establish a seamless and secure connection.
All fields are required, except where noted.

Connection name:: Enter a new Snowflake connection name. Mandatory field.
Connection description:: Provide a short description of the connection. Optional field.
Account name:: Enter the account name associated with your Snowflake connection.
The account name is part of the URL that you use to access the Snowflake UI.
It is the portion of the URL before `snowflakecomputing.com`.
+
*Example*: If your URL is `+https://abcd.xyz.efg.snowflakecomputing.com+`, your account name is `abcd.xyz.efg`.
+
Mandatory field.
User:: Enter the Snowflake account username. Mandatory field.
Password:: Enter the Snowflake account password. Mandatory field.
Role:: Specify the privilege of the user. Mandatory field.
Warehouse:: Specify the warehouse associated with the connection. Optional field.
Database:: Specify the database associated with the account. Optional field.
Schema:: Specify the schema associated with the database. Optional field.

'''
> **Related information**
>
> * xref:embrace-snowflake-add.adoc[]
> * xref:embrace-snowflake-modify.adoc[]
> * xref:embrace-snowflake-best.adoc[]
> * xref:embrace-snowflake-partner.adoc[]
> * xref:embrace-snowflake-tutorial.adoc[]