= Redshift connection reference
:last_updated: 03/25/2021
:experimental:
:linkattrs:
:page-aliases: /data-integrate/embrace/embrace-redshift-reference.adoc

Learn about the fields used to create a Redshift connection using ThoughtSpot Embrace.

Here is a list of the fields of a Redshift connection in ThoughtSpot Embrace.
You need specific information to establish a seamless and secure connection.
All fields are required, except where noted.
[#embrace-redshift-ref-connection-name]
Connection name::  Enter a new Redshift connection name.
[#embrace-redshift-ref-connection-description]
Connection description::
Provide a short description of the connection.
_(Optional)_
[#embrace-redshift-ref-host]
Host::  Enter the host name associated with the Redshift database.
[#embrace-redshift-ref-port]
Port::  Enter the port number associated with the Redshift database.
[#embrace-redshift-ref-user]
User::  Enter the Redshift account username.
+
NOTE: This user must have at least *read* access to the *SVV_TABLE_INFO* table.
[#embrace-redshift-ref-password]
Password::  Enter the Redshift account password.
[#embrace-redshift-ref-databse]
Database::  Specify the database associated with the account.

'''
> **Related information**
>
> * xref:embrace-redshift-add.adoc[]
> * xref:embrace-redshift-modify.adoc[]
> * xref:embrace-redshift-best.adoc[]