= CentOS end-of-life announcement
:last_updated: 10/14/2022
:linkattrs:
:experimental:
:description: End-of-life information about CentOS-based ThoughtSpot software and hardware deployments.

This page provides the end-of-sale (EOS), and end-of-service-life (EOSL) announcement for ThoughtSpot support for CentOS 7 Linux.

ThoughtSpot ships an xref:security-thoughtspot-lifecycle.adoc[embedded CentOS 7 Linux] with software and hardware deployments. Because https://endoflife.date/centos[RedHat plans to EOL CentOS^], ThoughtSpot will EOL our CentOS-based deployments.

If you are using a CentOS-based software or hardware deployment, you must migrate using one of our supported options to continue to receive support from ThoughtSpot.

== Key dates

[cols="30%,70%"]
|===
|Date |Event

|January 1, 2023
|End-of-sale (EOS) for new CentOS-based embedded Linux deployments

|March 3, 2023
|End-of-renewal (EOR) for ThoughtSpot-supplied hardware appliances

|December 31, 2023
|End-of-service-life (EOSL) for CentOS-based software and hardware deployments
|===

== Migration options

ThoughtSpot supports the following migration paths:

* ThoughtSpot Cloud SaaS
* One of the following bring-your-own-Linux (BYOL) variants: xref:customer-os.adoc[RedHat Enterprise Linux (RHEL), Oracle Enterprise Linux (OEL), or Amazon Linux 2 (AL2)]

+
IMPORTANT: These BYOL variants are not supplied/embedded by ThoughtSpot. You must manage the deployment of the OS yourself.

=== Migration to ThoughtSpot Cloud SaaS

ThoughtSpot can provide https://www.thoughtspot.com/professional-services[Professional Services^] to help you migrate to ThoughtSpot Cloud SaaS. Please contact your ThoughtSpot Sales or Customer Success representative to understand professional services options for migrating to ThoughtSpot Cloud SaaS.

=== Migration to Bring-Your-Own-Linux (BYOL)

Please note that you will need to manage the deployment of the Linux operating system yourself using the instructions provided here:

* xref:customer-os.adoc[RedHat Enterprise Linux (RHEL), Oracle Enterprise Linux (OEL), or Amazon Linux 2 (AL2)]

Once the Linux installation is complete, ThoughtSpot Support can assist you with the migration of the ThoughtSpot application to the new operating system. To migrate to BYOL, please open a case with {support-url}.

[#hardware-impact]
=== Impact to ThoughtSpot hardware appliances

If you are using a ThoughtSpot-supplied hardware appliance:

. Existing hardware appliance customers who have an active service contract, will continue to receive support for their hardware and ThoughtSpot application software throughout the remainder of their contract.
. After Dec 31st 2023, the CentOS Operating System will no longer be supported by ThoughtSpot, on the hardware appliance. Supported customers should take one of the following actions BEFORE Jan, 2024. The options below are listed in order of preference:

.. Migrate to ThoughtSpot Cloud SaaS.
.. Migrate to customer-owned VPC in the cloud (e.g., AWS, Azure, GCP).
.. Migrate to customer-owned VMware on the hardware appliance.
.. Install RHEL 8 on the hardware appliances and restore ThoughtSpot from existing deployment (See below).
. Hardware appliance contracts will not be renewable after March 3, 2023.
. Once the hardware appliance contracts expire, all hardware must be returned according to the contract policy.

=== Install RHEL on hardware appliance

ThoughtSpot will provide customers with RHEL installation requirements. It is the customer's responsibility to license, install, and support RHEL on the hardware appliance. Once the installation is completed and requirements are verified by the {support-url} team, ThoughtSpot will help install, configure, and restore the ThoughtSpot backup from the CentOS-based ThoughtSpot deployment.
