= ThoughtSpot Software end of life
:last_updated: 8/18/2025
:linkattrs:
:experimental:
:description: The timelines of when ThoughtSpot Software will go end-of-life.
:jira: SCAL-265277

After careful consideration, ThoughtSpot has made the decision to discontinue ThoughtSpot Software, with sustaining support beginning on October 1, 2025 and the product reaching its end of life and end of support on July 1, 2027.

== What this means for you

We understand that ThoughtSpot Software (including ThoughtSpot Embrace (also referred to as Connections), Flex, and Falcon) plays a role in your operations, and we're committed to making this transition as smooth as possible.  We value your trust in us and want to assure you that our priority is to minimize disruption and provide the guidance you need. Here's what you can expect:

=== Full support period

From now until July 1, 2027 or the end of your current order-form term (whichever comes first), you'll continue to receive our complete support, including technical assistance, bug fixes, and security updates.

=== Data Access
You retain full ownership of your data throughout this process. We recommend exporting your data well before the end-of-life date to ensure a seamless transition.

If you have any questions or concerns, please don't hesitate to contact your account manager or {support-url}.