= Formula function reference
:last_updated: 03/22/2021
:linkattrs:
:experimental:
:page-partial:

Learn the operators and functions you can use to create formulas in ThoughtSpot.

ThoughtSpot allows you to create derived columns in worksheets using formulas.
You create these columns by building formulas using the *Formula Assistant*.
An individual formula consists of _n_ combinations of operators and functions.

This reference lists the various operators and functions you can use to create formulas.

[#aggregate-functions]
== Aggregate functions (group aggregate)

Use the following functions to aggregate data.

include::partial$aggregate.adoc[]

[#conversion-functions]
== Conversion functions

Use these functions to convert data from one data type into another data type.

ThoughtSpot does not support _date_ data type conversion.

include::partial$conversion-func.adoc[]

[#date-functions]
== Date functions

include::partial$date-func.adoc[]

[#mixed-functions]
== Mixed functions

These functions can be used with text and numeric data types.

include::partial$mixed-func.adoc[]

[#number-functions]
== Number functions

include::partial$number-func.adoc[]

[#operators]
== Operators

include::partial$operators.adoc[]

[#text-functions]
== Text functions

include::partial$text-func.adoc[]

[#variable-functions]
== Variables

These variables can be used in your expressions.

include::partial$func-variables.adoc[]

[#passthrough-functions]
== Connection passthrough functions

NOTE: ThoughtSpot provides passthrough SQL functions support only for connections in Snowflake.

include::partial$sql-passthrough.adoc[]
