= Install ThoughtSpot clusters in GCP
:last_updated: 01/02/2021
:linkattrs:
:experimental:

Learn how to install ThoughtSpot clusters in GCP.

'''
> **ThoughtSpot Training**
>
> * For best results with GCP cluster installation, we recommend the following ThoughtSpot U course: https://training.thoughtspot.com/create-upgrade-patch-a-thoughtspot-cluster/430642[Create a Cluster^].
> * See other training resources at https://training.thoughtspot.com/[ThoughtSpot U^].

'''

== Prerequisites

Before you can install your ThoughtSpot clusters in GCP, complete these prerequisites:

[cols="5,~",grid=none,frame=none]
|===
| &#10063; | xref:gcp-configuration-options.adoc[1. Review GCP configuration options] for detailed instance specs.
| &#10063; | xref:gcp-launch-instance.adoc[2. Set up ThoughtSpot in GCP] to create and launch your instance.
| &#10063; | xref:ports.adoc[3. Review Network ports] to view the required ports for successful operation of ThoughtSpot.
| &#10063; | xref:gcp-installing.adoc[4. Configure ThoughtSpot nodes in GCP] to configure your nodes.
|===

[#cluster-install]
== Install ThoughtSpot Software

Install the cluster using the ThoughtSpot software release bundle.
The estimated installation time is one hour.

Follow the steps in this checklist:

[cols="5,~",grid=none,frame=none]
|===
| &#10063; | <<cluster-step-1,Step 1: Run the installer>>
| &#10063; | <<cluster-step-2,Step 2: Check cluster health>>
| &#10063; | <<cluster-step-3,Step 3: Finalize installation>>
|===

Refer to your welcome letter from ThoughtSpot to find the link to download the release bundle.
If you do not have a link, open a support ticket with https://community.thoughtspot.com/customers/s/contactsupport[ThoughtSpot Support^] to request access to the release bundle.

[#cluster-step-1]
=== Step 1: Run the installer

. Copy the downloaded release bundle to `/export/sdc1/TS_TASKS/install` using the following command:
+
[source,bash]
----
$ scp <release-number>.tar.gz admin@<hostname>:/export/sdc1/TS_TASKS/install/<file-name>
----
+
Note the following parameters of the `scp` command:

`release-number`::
  is the release number of your ThoughtSpot instance, such as 5.3, 6.0, and so on.
`hostname`::
  is your specific hostname.
`file-name`::
  is the name of the tarball file on your local computer.

+
NOTE: You can use another secure copy method, if you prefer a method other than the `scp` command.

. Alternatively, use `tscli fileserver download-release` to download the release bundle.
+
You must xref:tscli-command-ref.adoc#tscli-fileserver[configure the fileserver] by running `tscli fileserver configure` before you can download the release.
+
[source,bash]
----
 $ tscli fileserver download-release <release-number> --user <username> --out <release-location>
----
+
Note the following parameters of this command:

`release-number`::
  is the release number of your ThoughtSpot instance, such as 5.3, 5.3.1, 6.0, and so on.
`username`::
  is the username for the fileserver that you set up earlier, when configuring the fileserver.
`release-location`::
  is the location path of the release bundle on your local machine. For example, `/export/sdc1/TS_TASKS/install/6.0.tar.gz`.

. Verify the checksum to ensure you have the correct release.
+
Run `md5sum -c <release-number>.tar.gz.MD5checksum`.
+
[source,bash]
----
$ md5sum -c <release-number>.tar.gz.MD5checksum
----
+
Your output says `ok` if you have the correct release.

. Launch a https://linux.die.net/man/1/screen[screen^] session.
Use screen to ensure that your installation does not stop if you lose network connectivity.
+
[source,bash]
----
$ screen -S DEPLOYMENT
----

. Take a machine snapshot prior to the release deployment, as a best practice.

. Create the cluster.
+
Run `tscli cluster create` to create the cluster.
+
If you are using a gcs bucket for object storage, include the flag `--enable_cloud_storage=gcs`.
+
[source,bash]
----
$ tscli cluster create <release-number>.tar.gz --enable_cloud_storage=gcs
----

include::partial$cluster-steps1through3.adoc[]

== Lean configuration

*For use with thin provisioning only:* If you have a xref:deploying-cloud.adoc#small-medium[small or medium instance type], with less than 100GB of data, you must use advanced lean configuration before loading any data into ThoughtSpot.
After installing the cluster, configure advanced lean mode.

To configure advanced lean mode, do the following:

. SSH as admin into your ThoughtSpot cluster, using the following syntax:
+
[source,bash]
----
ssh admin@<cluster-ip-address or hostname>
----
. Run the advanced lean mode configuration using the following syntax:
+
[source,bash]
----
tscli config-mode lean [-h] --type {small,medium,default}
----
+
Examples:
+
Configure the instance for "small" data size::
+
[source,bash]
----
size, run: `tscli config-mode lean [-h] --type small
----
Configure the instance for "medium" data size::
+
[source,bash]
----
tscli config-mode lean [-h] --type medium
----

+
NOTE: If you decide later you want to disable advanced lean mode, use `default`.

'''
> **Related information**
>
> * xref:nodesconfig-example.adoc[The nodes.config file]
> * xref:parameters-nodesconfig.adoc[Parameters of the nodes.config file]
> * xref:cluster-create.adoc[Using the tscli cluster create command]
> * xref:parameters-cluster-create.adoc[Parameters of the cluster create command]
> * https://community.thoughtspot.com/customers/s/contactsupport[ThoughtSpot Support^].
