= Configure ThoughtSpot nodes in GCP
:last_updated: 01/02/2021
:linkattrs:
:page-aliases: /appliance/gcp/installing-gcp.adoc
:experimental:

Prepare to install your ThoughtSpot cluster by configuring nodes.

Before you can install a ThoughtSpot cluster in GCP, you must configure your nodes.

'''
> **ThoughtSpot Training**
>
> * For best results in setting up ThoughtSpot nodes in GCP, we recommend that you take the following ThoughtSpot U course: https://training.thoughtspot.com/node-network-configuration/437249[Network Configuration^].
> * See other training resources at https://training.thoughtspot.com/[ThoughtSpot U^].

'''

[#installation-prerequisites]
== Installation Prerequisites


Ensure the successful creation of the virtual machines (VMs) before you install the ThoughtSpot cluster in GCP:

[cols="5,~",grid=none,frame=none]
|===
| &#10063; | xref:gcp-configuration-options.adoc[1. Review GCP configuration options] for detailed instance specs.
| &#10063; |xref:ports.adoc[2. Review network ports] to view the required ports for successful operation of ThoughtSpot.
| &#10063; |xref:gcp-launch-instance.adoc[3. Set up GCP for ThoughtSpot] to create and launch your instance.
|===

[#configure-nodes]
== Configure Nodes

After creating the instance, you must configure the nodes.

[cols="5,~",grid=none,frame=none]
|===
| &#10063; | <<node-step-1,Step 1: Log in to your cluster>>
| &#10063; | <<node-step-2,Step 2: Get a template for network configuration>>
| &#10063; | <<node-step-3,Step 3: Prepare node configuration>>
| &#10063; | <<node-step-4,Step 4: Configure the nodes>>
| &#10063; | <<node-step-5,Step 5: Confirm node configuration>>
|===

include::partial$configure-nodes-steps1through5.adoc[]

== Install ThoughtSpot software

Next, xref:gcp-cluster-install.adoc[install your ThoughtSpot clusters].

include::partial$install-cluster-error-recovery.adoc[]

'''
> **Related information**
>
> * xref:nodesconfig-example.adoc[The nodes.config file]
> * xref:parameters-nodesconfig.adoc[Parameters of the nodes.config file]
> * xref:cluster-create.adoc[Using the tscli cluster create command]
> * xref:parameters-cluster-create.adoc[Parameters of the cluster create command]
> * Contact https://community.thoughtspot.com/customers/s/contactsupport[ThoughtSpot Support^].
