= Group API
:last_updated: 11/18/2019
:experimental:
:linkattrs:

The Group APIs enable you to set or remove a privilege to or from a group or multiple groups.

== Add a privilege

Use this API to add a `DATADOWNLOADING` or `USERDATAUPLOADING` privilege to the system default `ALL_GROUP` group.
All users in the system are always a part of the `ALL_GROUP` group.
By default, this group does not have either permission.

All the data sources which the `ALL_GROUP` group has permissions to are downloadable when `DATADOWNLOADING` is applied.

=== Resource URL

[source]
----
`post` /tspublic/v1/group/addprivilege
----

=== Request Parameters

`privilege`::
  Specifies a privilege type to add.
  Data type;; string
  Valid values;;
   * `DATADOWNLOADING` privilege
   * `USERDATAUPLOADING` privilege

`groupNames`::
  Specifies a group name where to add the privilege.
  Data type;; string
  Valid value;;
    * `ALL_GROUP` group.

=== Request Example

.cURL

[source]
----
curl -X POST --header 'Content-Type: application/x-www-form-urlencoded' --header 'Accept: application/json' --header 'X-Requested-By: ThoughtSpot' -d 'privilege=DATADOWNLOADING&groupNames=ALL_GROUP' 'https://<instance>/callosum/v1/tspublic/v1/group/addprivilege'
----

.Request URL

[source]
----
https://<instance>/callosum/v1/tspublic/v1/group/addprivilege
----

=== Response Example

----
Not applicable
204 - Success
----

== Remove a privilege

Use this API to delete a `DATADOWNLOADING` or `USERDATAUPLOADING` privilege from the system default ``ALL_GROUP``group.

=== Resource URL

[source]
----
`post` /tspublic/v1/group/removeprivilege
----

=== Request Parameters

`privilege`::
  Specifies a privilege type to delete.
  Data type;; string
  Valid values;;
    * `DATADOWNLOADING` privilege
    * `USERDATAUPLOADING` privilege.

`groupNames`::
  Specifies a group name from where to delete the privilege.
  Data type;; string
  Valid value;;
    * `ALL_GROUP` group.

=== Request Example

.cURL

[source]
----
curl -X POST --header 'Content-Type: application/x-www-form-urlencoded' --header 'Accept: application/json' --header 'X-Requested-By: ThoughtSpot' -d 'privilege=USERDATAUPLOADING&groupNames=ALL_GROUP' 'https://<instance>/callosum/v1/tspublic/v1/group/removeprivilege'
----

.Request URL

[source]
----
https://<instance>/callosum/v1/tspublic/v1/group/removeprivilege
----

=== Response Example

----
Not applicable
204 - Success
----
