= Configure internal authentication
:last_updated: 3/4/2020
:page-aliases: /admin/setup/internal-auth.adoc
:experimental:
:linkattrs:

Many organizations don’t use LDAP or active directory for user authentication. In other scenarios, some users are not in LDAP and are created only in ThoughtSpot. In such cases, you can choose to authenticate users against ThoughtSpot internal authentication.


Many organizations don't use LDAP or active directory for user authentication.
In other scenarios, some users are not in LDAP and are created only in ThoughtSpot.
In such cases, you can choose to authenticate users against ThoughtSpot internal authentication.

NOTE: Before a user logs into ThoughtSpot, that user must exist in ThoughtSpot.
This is independent of the authentication mechanism.

== Enable internal authentication with the admin console

include::partial$authentication-local.adoc[]

If you have been using ThoughtSpot with users you created manually, and you now want to transition to LDAP, contact https://community.thoughtspot.com/customers/s/contactsupport[ThoughtSpot Support^].
They can assist you in migrating existing users to their LDAP equivalents.
