= Introduction to data integration
:last_updated: tbd

This guide explains how to integrate ThoughtSpot with other data sources for loading data.
It also includes information on installing and using the ThoughtSpot clients (ODBC, JDBC, and more).

== ThoughtSpot clients

ThoughtSpot provides certified clients to help you load data easily from your ETL tool or another database.
These include ODBC and JDBC drivers.

You can obtain the ThoughtSpot client downloads from the Help Center.
Always use the version of the ThoughtSpot clients that corresponds with the version of ThoughtSpot that you are running.
When upgrading, make sure to upgrade your clients as well.

IMPORTANT: The ETL tool must add a data transformation step if the source column data type does not exactly match the target's, ThoughtSpot's, column data type.
The driver does not do any implicit conversions.

== Methods for loading data

There are several ways to load data into ThoughtSpot, depending on your goals and where the data is located.
Always consider your requirements for recurring loads when planning how best to bring the data into ThoughtSpot.

Here are the options, with information on where to find the documentation for each method:

[width="100%",options="header",cols="30%,70%"]
|===
| Method | Description
| ThoughtSpot Loader (tsload) | ThoughtSpot Loader is a command line tool to load CSV files into an existing database schema in ThoughtSpot. This is the fastest way to load extremely large amounts of data, and it can be run in parallel. You can also use this method to script recurring loads. See the ThoughtSpot Administrator Guide for details.
| User Data Import | Users can upload a spreadsheet through the web interface with User Data Import. This is useful for giving everyone easy access to loading small amounts of their own data. See the ThoughtSpot Administrator Guide for details.
a| xref:about-odbc.adoc[ODBC] | ThoughtSpot provides an ODBC (Open Database Connectivity) driver to enable transferring data from your ETL tool into ThoughtSpot.
a| xref:about-jdbc-driver.adoc[JDBC] | You can use the ODBC driver to connect to SSIS and import data into ThoughtSpot. Basic instructions are included in this guide.

a| xref:set-up-the-jdbc-driver-for-pentaho.adoc[Connect to Pentaho] | You can use the JDBC driver to connect to Pentaho and import data into ThoughtSpot. Basic instructions are included in this guide.
|===

== Where to go next

* *xref:jdbc-odbc-prereqs.adoc[Server-side prerequisites for using JDBC/ODBC to import data]*
+
You must follow setup prerequisites for importing data using JDBC/ODBC.
* *xref:about-odbc.adoc[About the ODBC Driver]*
+
You can use the ThoughtSpot ODBC driver to bring data into ThoughtSpot from your ETL tool or database.
* *xref:about-jdbc-driver.adoc[About the JDBC Driver]*
+
Java Database Connectivity (JDBC) is a Java standard API that allows applications to interact with databases in a standard manner.
ThoughtSpot has JDBC support through a JDBC driver that we provide.
