= Introduction to the User Guide
:last_updated: 11/15/2019

This ThoughtSpot User Guide contains information on navigating and searching data with ThoughtSpot. It assists you with starting new searches, managing your pinboards, and troubleshooting.

ThoughtSpot enables you to view and analyze your data through a search-based user interface.
You can create your searches quickly and easily, just by typing them into a search bar, like you do when using an Internet search engine.
ThoughtSpot makes it easy to see your data, get your questions answered, create interactive graphs, and customize pinboards.
You don't need to understand how ThoughtSpot stores information, attend days of training, or know SQL to do these things.
Collaboration and security features make it easy to protect sensitive data, and safely share information with others.

ThoughtSpot gives administrators the ability to modify data properties to meet business needs.
Administrators can specify search synonyms for common terms, boost the importance of a column in search results, or format how the data appears.
So, if you are not getting the answers you expect when using ThoughtSpot, check with your ThoughtSpot administrator to see if some settings can be changed.

* *xref:about-navigating-thoughtspot.adoc[Finding your way around]* +
To make navigation easy, we organized ThoughtSpot into several sections.
You can see them on the menu bar.
* *xref:about-user.adoc[About the user profile]* +
The user icon lets you view your profile, or sign out of ThoughtSpot.
* *xref:about-privileges-end-user.adoc[Understanding privileges]* +
 Your privileges determine the things you can do.
ThoughtSpot sets privileges at the group level.
* *xref:stickers.adoc[About stickers]* +
 You can create stickers to make it easier for people to find data sources and pinboards.
