= IT and Ops
:last_updated: 7/20/2021
:linkattrs:
:page-partial:
:experimental:

As an Admin, you have a vital role to manage the ThoughtSpot application, including managing users, authentication, deployment, and so on.
These are the Admin tasks that you have to complete to make ThoughtSpot available for everyone in your organization.

xref:admin-portal-users.adoc[Manage users]::
Before people can log in and use ThoughtSpot, you need to create a username, a password, and a membership in one or more groups for them. Use the Admin Console to easily create and manage your users.
xref:admin-portal-groups.adoc[Manage groups]::
Before people can log in and use ThoughtSpot, you need to create a membership in one or more groups for them, with the correct privileges. Use the Admin Console to easily create and manage your user groups.
xref:admin-portal-authentication-local.adoc[Manage local authentication]::
ThoughtSpot supports internal authentication.
xref:admin-portal-authentication-active-directory.adoc[Manage authentication through Active Directory]::
ThoughtSpot supports user authentication through Active Directory.
xref:admin-portal-authentication-saml.adoc[Manage authentication through SAML]::
ThoughtSpot supports user authentication through SAML.
xref:ldap-sync-users-groups.adoc[Sync users and groups from LDAP]::
Use this procedure to synchronize your ThoughtSpot system with an LDAP server through Active Directory.
xref:deployment-sw.adoc[Software deployment]::
Learn how to install ThoughtSpot Software on a cloud provider, VMware, or on a hardware appliance.
xref:admin-portal-style-customization.adoc[Style customization]::
Customize the ThoughtSpot application style.
xref:admin-portal-customize-help.adoc[Help customization]::
Customize the ThoughtSpot help menu.
//* View scheduled maintenance
//* View user activity
xref:admin-portal-system-cluster-pinboard.adoc[View cluster information]::
View system information about your cluster.
xref:admin-portal-system-alerts-pinboard.adoc[View alert information]::
View system alerts.
xref:performance-tracking.adoc[Monitor app performance]::
The Performance Tracking pinboard contains essential information about your ThoughtSpot cluster’s performance. Use this pinboard to understand query latency, user traffic, how users are interacting with ThoughtSpot, most frequently loaded tables, and so on.
xref:admin-portal-user-adoption-pinboard.adoc[View user adoption information]::
View the User Adoption pinboard to learn how your users are interacting with ThoughtSpot.
xref:use-agreement.adoc[In-app acceptance of ThoughtSpot's use agreement]::
Accept ThoughtSpot's use agreement from within the application.
xref:deployment-sw.adoc[Deploy software]::
Learn how to install ThoughtSpot Software on a cloud provider, VMware, or on a hardware appliance.
xref:troubleshooting.adoc[Troubleshooting]::
Learn the basics of troubleshooting for ThoughtSpot.
xref:security.adoc[Security]::
Learn how to implement security features.
//* Manage search and SpotIQ settings
//* Manage email and onboarding settings


////
Your role is to establish connections to data. Here is how you can connect to all your data.
The following list provides information about connecting to your data in supported data warehouses.

Direct Connections::
Snowflake
Overview
Add connection
Edit connection
Remap connection
Delete a table
Delete a table with object dependencies
Delete connection
Best practices
Connection reference
 Amazon Redshift
Overview
Add connection
Edit connection
Remap connection
Delete a table
Delete a table with object dependencies
Delete connection
Connection reference
 Google BigQuery
Overview
Add connection
Edit connection
Remap connection
Delete a table
Delete a table with object dependencies
Delete connection
Connection reference
 Azure Synapse
Overview
Add connection
Edit connection
Remap connection
Delete a table
Delete a table with object dependencies
Delete connection
Connection reference
 Oracle ADW
Overview
Add connection
Edit connection
Remap connection
Delete a table
Delete a table with object dependencies
Delete connection
Connection reference
 Starburst
Overview
Add connection
Edit connection
Remap connection
Delete a table
Delete a table with object dependencies
Delete connection
Connection reference
 Databricks
Overview
Add connection
Edit connection
Remap connection
Delete a table
Delete a table with object dependencies
Delete connection
Connection reference

Getting data into Falcon with DataFlow::
DataFlow information
////

////
Search Assist::
See how ThoughtSpot Search gives you insights into your own data.

Onboarding for Analysts::
Get a comprehensive look at how to create modern and dynamic dashboards for your organization.

Scriptability::
Use SpotApps to export Worksheets, Pinboards, and Answers in a human-readable format.

SpotApp Templates::
Use SpotApp templates to gain insights into your Salesforce, accounts receivable, or procurement instances.

ThoughtSpot Modeling Language::
Modify a Worksheet, Pinboard, or Answer in a flat-file format.
////
////
Getting started for Business users::
Get a quick overview of how ThoughtSpot can support you.
+
See xref:getting-started.adoc[].

Home page::
This is where you get direct access to exisiting Answers, Pinboards, and visualizations.

Pinboards and Answers::
Quick tips on how you can use and customize Pinboards and Charts.
+
See xref:charts.adoc[], xref:chart-types.adoc[], xref:chart-change.adoc[], and xref:pinboards.adoc[].

ThoughtSpot Search::
Explore our flagship Search functionality.
+
See xref:search.adoc[].
////
////
Search Assist::
See how ThoughtSpot Search Assist gives you insights into your own data.
////

xref:mobile.adoc[Mobile app]::
Access your ThoughtSpot cluster on the ThoughtSpot mobile app to view and create Answers and Pinboards.

////
from old user guide


* *xref:navigating-thoughtspot.adoc[Finding your way around]* +
 To make navigation easy, we organized ThoughtSpot into several sections.
You can see them on the menu bar.
* *xref:user-profile.adoc[About the user profile]* +
 The user icon lets you view your profile, or sign out of ThoughtSpot.
* *xref:privileges-end-user.adoc[Understanding privileges]* +
 Your privileges determine the things you can do.
ThoughtSpot sets privileges at the group level.
* *xref:tags.adoc[About tags]* +
 You can create tags to make it easier for people to find data sources and pinboards.

* xref:search.adoc[Use search]
* xref:answers.adoc[Work with Answers]
* xref:filters.adoc[Work with filters]
* xref:charts.adoc[Work with charts]
* xref:formulas.adoc[Work with formulas]
* xref:pinboards.adoc[Use pinboards]
* xref:answer-explorer.adoc[Answer Explorer]
* xref:r-thoughtspot.adoc[About R in ThoughtSpot]
* xref:spotiq.adoc[SpotIQ]
* xref:data-sources.adoc[Work with data]
* xref:help-center.adoc[]
////
