= Enable JDBC Logs

Configure logging parameter strings.

To enable logging for JDBC, add the logging parameters to the connect string.
Logs are stored on ThoughtSpot.
Before enabling JDBC logging, you need:

* The level of logging you want to capture.
* The path on the ThoughtSpot server where the logs will be written.
Make sure the directory has the correct permissions so that the "admin" Linux user can write logs to it.

To enable JDBC logging:

. When forming the connect string for JDBC, add these two parameter, separated by "&":
+
For example:
+
----
 jdbc:simba://192.168.2.248:12345;SERVERS=192.168.2.249:12345,
 192.168.2.247:12345;Database=test;Schema=falcon_default_schema;**LogLevel=3;LogPath=/usr/local/scaligent/logs**
----
+
The `LogLevel` is the level of logging to capture (0-6).
The `LogPath` is  the fully qualified path where logs will be written on ThoughtSpot.

. Run the JDBC code that uses the connection you modified.
. Check the `LogPath` directory for logs generated by JDBC.
