= Enable JDBC logs
:last-upddated: 06/23/20021
:experimental:
:page-aliases: data-integrate::troubleshooting:JDBC-logging.adoc
:linkattrs:

Configure logging parameter strings.

To enable logging for JDBC, add the logging parameters to the connect string.
Logs are stored on ThoughtSpot.
Before enabling JDBC logging, you need:

* The level of logging you want to capture.
* The path on the ThoughtSpot server where the logs will be written.
Make sure the directory has the correct permissions so that the "admin" Linux user can write logs to it.

To enable JDBC logging, follow these steps:

. When forming the connect string for JDBC, add these two parameters, separated by "&":
+
For example:
+
[source]
----
jdbc:simba://192.168.2.248:12345;SERVERS=192.168.2.249:12345,
  192.168.2.247:12345;Database=test;
  Schema=falcon_default_schema;**LogLevel=3;
  LogPath=/usr/local/scaligent/logs**
----
+
`LogLevel`:: The level of logging to capture (0-6).
`LogPath`:: The fully-qualified path for writing ThoughtSpot logs.

. Run the JDBC code that uses the connection you modified.
. Check the `LogPath` directory for logs generated by JDBC.

'''
> **Related information**
>
> * xref:odbc-enable-log.adoc[Enable ODBC logs]
> * xref:schema-not-found.adoc[Schema not found error with ODBC]
> * xref:throughput.adoc[How to improve throughput]
> * xref:windows-odbc-tracing.adoc[ODBC tracing on Windows]
> * xref:odbc-jdbc-sql.adoc[SQL commands in ODBC and JDBC]
> * xref:odbc-jdbc-configuration.adoc[Connection configuration for ODBC and JDBC]