= Join a worksheet to another data source
:last_updated: 08/12/2021
:linkattrs:
:experimental:
:page-partial:
:page-aliases: /admin/worksheets/add-joins.adoc

Joining a Worksheet to a table or View creates a relationship that allows them to be searched together.
Choose a column to join on that both data sources contain (for example,
employee ID or product key).
This process creates a xref:constraints.adoc[generic join] between the Worksheet and the table or View on the column you specify.

NOTE: Defining a generic relationship in the UI rather than using a primary key/ foreign key join through TQL has no impact on performance.
However, when creating relationships in the UI, you must ensure that you create it in the right direction: many to one.
To create many-to-many joins, or to create joins using >, <, >=, or \<=, use TQL.

See this matrix for information about which joins you can create, and what permissions these joins require.

include::partial$joins-matrix.adoc[]


You must have either the *Can administer ThoughtSpot* privilege or the *Can manage data* privilege to create a join relationship.
If you're not an administrator, you also need edit permissions on the table, View, or Worksheet.

When creating a join between the columns in two data sources, the columns being linked must have the same data type, with the same meaning.
That is, they must represent the same data.

include::partial$joins-create-worksheet.adoc[]

. Repeat these steps to create all joins.

After creating the join, you may change its name and description by clicking the edit icon.
If you want to change the data source or column being joined, you must delete the join and create a new one.

'''
> **Related information**
>
> * xref:constraints.adoc[Constraints]
> * xref:relationship-create.adoc#join-type[Possible join types]
> * xref:relationship-create.adoc#join-cardinality[Join cardinality]
