= Known issues
:keywords: known issues
:last_updated: 10/6/2022
:experimental:
:page-layout:
:linkattrs:
:jira: SCAL-192798

These are the known issues in this release of ThoughtSpot Software.

[#releases-9-0-x]
== 9.0.1.sw known issues

[cols="17%,39%,38%"]
|===
|Issue ID |Description|Symptoms, conditions, and workaround

|SCAL-154579
|Clicking the *Utilities* tab in a Worksheet redirects the user to the Home page.
a|*Symptoms*:

User taken to the Home page of the ThoughtSpot application.

*Conditions*:

In a Worksheet, click the *Utilities* tab.

*Workaround*:

None

|SCAL-183487
|Newer versions of iptables use error messages not handled neatly by oreo.
a|*Symptoms*:

Service push fails during cluster installation, node reboot, or cluster start.  Error message viewed in `/export/logs/oreo/oreo_main.INFO` is similar to the following:

- `[ Run Firewall command sudo iptables -t filter -S CLUSTER ] failed; Failed: exit_code=1, error=iptables: Incompatible`

*Conditions*:

Cluster is running on customer-provided RHEL or OEL version 8.9.

*Workaround*:

Either of the following workarounds can be used:

- Run `sudo iptables -t filter -N CLUSTER` while the failure is being seen. You may need to run it multiple times. You should do this on each node of the cluster.
- Downgrade iptables yum package to version 1.8.4 (`sudo yum remove iptables`; `sudo yum install iptables-1.8.4`).

|SCAL-187943
|postgresql11 public repository removed by The PostgreSQL Global Development Group
a|*Symptoms*:

Attempts to run yum commands fail. Upgrade or installation of ThoughtSpot in an online manner fails due to yum command failure.  Error looks similar to:

- `One of the configured repositories failed (PostgreSQL 11 for RHEL/CentOS 7 - x86_64)`, and `yum doesn't have enough cached data to continue.`
+
or

- `failure: repodata/repomd.xml from pgdg11: [Errno 256] No more mirrors to try.
\https://download.postgresql.org/pub/repos/yum/11/redhat/rhel-7-x86_64/repodata/repomd.xml: [Errno 14] HTTPS Error 404 - Not Found`

*Conditions*:

ThoughtSpot installed on one of the following customer-provided operating systems:

- RHEL7
- RHEL8
- OEL7
- OEL8
- AL2.

ThoughtSpot version is later than 6.3.1.CU4.

*Workaround*:

None

|===


== 9.0.0.sw known issues

None.


[#releases-8-7-x]
== 8.8.0.sw known issues

[cols="17%,39%,38%"]
|===
|Issue ID |Description|Symptoms, conditions, and workaround

|SCAL-129737
|Headline summary is truncated despite the number of decimals.
a|*Symptoms*:

Headline with decimal digits is rounded off, causing a loss of accuracy.

*Conditions*:

Headline value is `DOUBLE` type.

*Workaround*:

None

|SCAL-129691
|“UniqueCount is not supported for the current query” error on pinned-headline tiles in a Liveboard.
a|*Symptoms*:

- When editing a pinned visualization, the Edit page shows the entire answer that the pinned headline came from. If the headline summary in the answer page is showing **--**, the selected aggregation is not compatible with the column that it is summarizing.
- Pinning the headline to a Liveboard is not a locked action from the UI. When attempting to retrieve the actual summary, the visualization tile displays the execution error message specified in the *Description* section for this issue instead.

*Conditions*:

- The headline is over a formula column that contains any of the following: `unique_count`, `unique_count_if`, `group_unique_count`, `approx_unique_count`.
- The formula’s unique count portion uses columns that come from tables of a connection to a cloud data warehouse.
- The selected headline aggregation for the formula (the headline visualization at the bottom of the main answer visualization) is Table Aggregate.

*Workaround*:

Set the selected headline aggregation to something other than Table Aggregate. Usually, **TOTAL** is a sufficient replacement for Table Aggregate and better matches customer use cases.

|===
