= Known issues
:keywords: known issues
:last_updated: 4/23/2025
:experimental:
:page-layout:
:linkattrs:
:description: These are the known issues in recent ThoughtSpot Software releases.
:jira: SCAL-232281

These are the known issues in these releases of ThoughtSpot Software.

[#releases-10-1-x]

== 10.1.0.sw.cu1 known issues

[cols="17%,39%,38%"]
|===
|Issue ID |Description|Symptoms, conditions, and workaround

|SCAL-249562
|Classic homepage displays `0` _Views_ by default for Liveboards and Answers.
a|*Symptoms*:

The _Views_ column on the homepage displays the number `0` by default for Liveboards and Answers.


*Conditions*:

The Navigation and Homepage is set to _Classic experience_ in the user's profile.

*Workaround*:

None.
|===

== 10.1.0.sw known issues

[cols="17%,39%,38%"]
|===
|Issue ID |Description|Symptoms, conditions, and workaround

|SCAL-249562
|Filter chips overlap on a chart after clicking the downward-facing arrow to display all filters in Explore mode.
a|*Symptoms*:

Filter chips overlap on a chart.


*Conditions*:

Using Explore mode on a visualisation with more filters than can be displayed on one line and clicking the downward-facing arrow to display all filters.

*Workaround*:

Manually collapse the filter by clicking the upward-facing arrow.

|SCAL-178756
|Red banner error is displayed without any proper error message when the original verifier of the Liveboard is deleted from the system.
a|*Symptoms*:

Red banner displayed without error message.


*Conditions*:

When the requester or verifier of a Liveboard is deleted.

*Workaround*:

For a verified Liveboard, there’s no impact on functionality and you can close the error banner. For a pending request, when the requester has been deleted, contact {support-url} to delete the request.

|SCAL-217451
|ThoughtSpot Cloud Answer cannot be deleted.
a|*Symptoms*:

Unable to delete or update any unused formula.


*Conditions*:

Tables with specific columns exist with joins between them. An Answer is generated using columns from these tables, including a formula that refers to a column in one of the tables. When later deleting the table containing that column, the attempt to remove the formula fails because it references a column that no longer exists.

*Workaround*:

. Make a copy of the Answer, because all unused formulas will be permanently deleted.
. Export the TML of the Answer using ‘Export Answer & Associated Objects (models, etc.)’.
. Delete the current Answer.
. Import the Answer TML zip file. All unused formulas will be removed from the Answers.
|===