= Search actions within a Liveboard
:last_updated: 5/10/2022
:experimental:
:linkattrs:
:page-partial:
:page-aliases: /end-user/pinboards/about-showing-underlying-data-from-within-a-pinboard.adoc, pinboard-search.adoc
:description: Learn about searching within a Liveboard.

You can perform many of the same search actions on individual visualizations within a Liveboard as you can within a search.
You can interact directly with a visualization of a Liveboard to perform ad hoc searches or edit it.

include::partial$liveboard-experience-new-announcement.adoc[]


To directly edit a visualization, follow these steps:

. Select the *Edit* button at the upper right of the Liveboard. If this button is grayed out, you do not have edit privileges for the Liveboard. To resolve this, contact your administrator or the creator of the Liveboard.

. You are now in edit mode for the visualization, where you can xref:search-choose-data-source.adoc[view and change sources], xref:search-bar.adoc[search different columns], xref:chart-table-change.adoc[change the view], xref:views.adoc[save the answer as a worksheet], xref:formulas.adoc[add a formula], and xref:chart-change.adoc[change the chart].
