= Load CSV files with the UI
:last_updated: 08/12/2021
:linkattrs:
:experimental:
:page-aliases: /admin/loading/load-from-web-browser.adoc, /end-user/data-view/generate-flat-file.adoc

The simplest way to load data is to upload a CSV or Excel file from the ThoughtSpot Web interface.

include::partial$web-load-intro.adoc[]

== Formatting the CSV

Your ETL (extract, transform, load) process will typically generate CSV files.
You can also create a CSV file from a Microsoft Excel spreadsheet by opening the spreadsheet in Excel, choosing *Save As* and selecting CSV.

include::partial$csv-format.adoc[]

If you are loading a fact table that joins to dimension tables, you must load the fact table first, and then the dimension tables.
The joining key must be a single column of unique values in the dimension table.
`NULL` values in the fact table cannot be joined.

== Create a CSV file

include::partial$csv-create.adoc[]

For general information about CSV files and the rules for creating them, see the Wikipedia article on http://en.wikipedia.org/wiki/Comma-separated_values[Comma-separated values].

== Load the CSV File

include::partial$csv-load.adoc[]

== Append to an existing table

include::partial$csv-append.adoc[]

== Troubleshoot uploads

Boolean data must use `TRUE`/`FALSE` values. Other values such as `Y`/`N` are not supported.
