= Materialization API
:last_updated: 01/20/2021
:linkattrs:
:experimental:

The materialization API allows you to synchronize a view's data with the latest data.

This API enables you to refresh a materialized view to synchronize its data with the latest data load to the underlying tables.
You may want to invoke this API in the following scenarios:

* When the status of a materialized view is `Stale` (out of sync) due to an incremental data load,
* When the status of a materialized view is `Error` due to an error that occurred.

Note that if your materialized view refreshes on a schedule, you cannot use the materialization API to refresh it a second time during the same refresh window.

NOTE: To refresh a materialized view, you must have the xref:groups-privileges.adoc#list-of-privileges[*Can administer ThoughtSpot* privilege].

== Resource URL

[source]
----
`post` /tspublic/v1/materialization/refreshview/\{id}
----

== Request Parameters

`id`::
  ID of the metadata object
  Data type;; string

== Request Example

.cURL

[source]
----
curl -X POST --header 'Content-Type: */*' --header 'Accept: application/json' --header 'X-Requested-By: ThoughtSpot' 'https://<instance>/callosum/v1/tspublic/v1/materialization/refreshview/e27f3c1c-a9cd-4996-9029-097449cd6f60'
----

.Request URL

[source]
----
https://<instance>/callosum/v1/tspublic/v1/materialization/refreshview/e27f3c1c-a9cd-4996-9029-097449cd6f60
----

== Response Example

----
Not applicable
204 - Refresh submitted
----
