= Deploy mobile app
:last_updated: 12/31/2020
:linkattrs:
:experimental:
:page-partial:
:page-aliases: /admin/mobile/deploy-mobile.adoc

You can deploy the ThoughtSpot mobile app through the iOS app store, or your MDM or MAM platform.

Deploying the ThoughtSpot mobile app to your users allows them to access their data and make decisions remotely from their mobile device.
For more information about features in the mobile app, refer to xref:mobile.adoc[ThoughtSpot mobile overview].

== Deployment options

There are two options for your users to download the ThoughtSpot mobile app:

* App Store for iOS or Google Play for Android
* Your MDM platform

=== App Store for iOS or Google Play for Android

The ThoughtSpot app is available from the App Store and Google Play.
Your users can download it directly from there.

=== Mobile device or app management platform

There are two ways to provide the ThoughtSpot app to your users with your MDM platform:

==== Option 1 [Recommended]: Provide a link to the App Store or Google Play.

Almost all of the platforms allow you to link to the ThoughtSpot app in either app store.
With this option, your users download it directly and automatically receive the latest updates, when they are available.

To add a link to the ThoughtSpot app on your management platform, refer to the following platform-specific information:

* https://docs.vmware.com/en/VMware-Workspace-ONE-UEM/1811/VMware-Workspace-ONE-UEM-Mobile-Application-Management/GUID-AWT-CONFIG-PUBLIC-APPS-WS1.html[Workspace ONE (AirWatch)^]
* http://mi.extendedhelp.mobileiron.com/53/all/en/desktop/App_Catalog.htm[MobileIron^] (Scroll to "`Adding an app from a public store`")
* https://docs.citrix.com/en-us/xenmobile/xenmobile-service/apps.html#add-a-public-app-store-app[XenMobile^]
* https://docs.microsoft.com/en-us/intune/store-apps-ios[Intune^]
* https://documentation.meraki.com/SM/Apps_and_Software/Deploying_Store_Apps_for_iOS%2F%2FmacOS_and_Android[Cisco Meraki^]

==== Option 2: Provide a custom application package file.

You can upload custom .ipa (iOS) and .apk (Android) files of the ThoughtSpot app to your management platform.

===== Before you begin

* Your company must have an Apple/Android developer enterprise account.
* Contact https://community.thoughtspot.com/customers/s/contactsupport[ThoughtSpot Support^] to get the ThoughtSpot `.ipa/.apk` file.

To upload the ThoughtSpot .ipa/.apk file to your management platform, refer to the following platform-specific information:

* https://docs.vmware.com/en/VMware-Workspace-ONE-UEM/1811/VMware-Workspace-ONE-UEM-Mobile-Application-Management/GUID-AWT-CONFIG-INTERNAL-APPS-LOCAL.html#GUID-AWT-CONFIG-INTERNAL-APPS-LOCAL[Workspace ONE (AirWatch)^]
* http://mi.extendedhelp.mobileiron.com/53/all/en/desktop/App_Catalog.htm[MobileIron^] (Scroll to "`Adding an In-house app`")
* https://docs.citrix.com/en-us/citrix-endpoint-management/apps.html#add-an-enterprise-app[XenMobile^]
* https://docs.microsoft.com/en-us/intune/lob-apps-ios[Intune^]
* https://documentation.meraki.com/SM/Apps_and_Software/Installing_Custom_Apps_on_iOS_and_Android_Devices[Cisco Meraki^]

==== AppConfig support

The ThoughtSpot mobile app conforms to the industry standard AppConfig community and version 1.1 of the app supports the following keys.
You can add these *keys* while deploying through your MDM platform.


ServerUrls:: Displays a list of servers for users to choose from during sign-in.
+
Separate the servers using commas.

  Format::: https://thoughtspot.example.com[^],
https://thoughtspot.finance-example.com[^]
HomePinboardHelpText:: Customize the home pinboard setup help text using this key.
  Format::: Send an email to admin@example.com if you are having difficulties when setting up your home pinboard.

[#try-the-mobile-app]
== Try the mobile app

If you want to try the mobile app before you deploy it to ThoughtSpot users in your company, do the following:

. Install and set up the app, following the steps in xref:mobile-install.adoc[Install and set up the mobile app].
. Use the following credentials to connect to ThoughtSpot's testing environment and try out the app:
+
*Server URL*: https://try.thoughtspot.com
+
*User ID*: mobile_beta@thoughtspot.com
+
*Password*: mobile

Have questions?
Feel free to contact https://community.thoughtspot.com/customers/s/contactsupport[ThoughtSpot Support^].
