= Configure NAS for backup storage
:last_updated: 11/30/20
:experimental:
:page-aliases: /admin/admin-portal/nas-mount-configure.adoc
:linkattrs:

You can use network attached storage to support backup/restore and data loading.

'''
> **ThoughtSpot Training**
>
> * For best results when configuring NAS for backups, we recommend that you take the following ThoughtSpot U course: https://training.thoughtspot.com/nas-mount[NAS Mount^].
> * See other training resources at https://training.thoughtspot.com/[ThoughtSpot U^].

'''

include::partial$mount-nas.adoc[]

You can mount NAS through the xref:admin-portal.adoc[Admin Console], or <<mount-nas-tscli,using tscli>>.

include::partial$nas-mount-configure.adoc[]

[#mount-nas-tscli]
== Mount NAS using tscli

To mount a NAS file system using the tscli, follow these steps:

. Log in to the Linux shell using SSH.
. Mount the directory to the file system by issuing the appropriate command:
 ** Example for an NFS (Network File System) directory:
+
[source,bash]
----
tscli nas mount-nfs --server storageservername.file.yourdomain.net
   --path_on_server <path>  /tsdev-backup --mount_point /export/BACKUPS/
   --options vers=<version>,sec=<security scheme>,<OPTIONS>
----
+
NOTE: Other command-line options are available to forward to the command (default: `noexec`).

 ** Example for a CIFS (Common Internet File System) directory.
Use `1001` for the `uid` and `gid`, as in the example:
+
[source,bash]
----
tscli nas mount-cifs --server storageservername.file.yourdomain.net
  --path_on_server /tsdev-backup --mount_point /export/BACKUPS/
  --username 'avtprdweutspotdev' --uid 1001 --gid 1001 --options 'vers=3.0'
----
+
NOTE: Other command-line options are available to forward to the `mount.cifs` command (default: `noexec`).
. Use the mounted file system by referring to its mount point.
. When you are finished with it, you can optionally unmount the NAS file system:
+
[source,bash]
----
 tscli nas unmount --dir <directory>
----
