= 10.1.0.sw Release Notes
:experimental:
:last_updated: 11/15/24
:linkattrs:
:page-aliases: /release/notes.adoc
:description: These release notes include information about new and enhanced features.
:jira: SCAL-251725, SCAL-264748

++++
<style>
.badge-update-whats-new-beta {
  font-style: normal !important;
  top: -0.03rem !important;
}

</style>
++++

ThoughtSpot version 10.1.0.sw.cu1 is now available.

These release notes include information about new and enhanced features.

To see our feature deprecation plans, please see xref:deprecation.adoc[].

For a complete list of known issues in this release, see xref:known.adoc#releases-10-1-x[Known issues].

* <<upgrade-paths,Supported Upgrade Paths>>

[#new-10-1-0-cu1]
== 10.1.0.sw.cu1 New Features and Functionality

// Mark – SCAL-216879.
Manage tags for Answers and Liveboards::
You can now manage all your Answer and Liveboard tags from one convenient window. Just click the *Manage tags* button at the top of your list of Liveboards or Answers, then create, edit, and delete tags. To delete and edit tags you must have administrator privileges or the _can manage tags_ role if RBAC is enabled.
+
For more information, see
xref:tags.adoc[Use tags to organize].

// Mark – SCAL-216879.
Org Name filter added to system Liveboards::
The Org Name filter has been added to the following system Liveboards:

- User Adoption
- Object Usage
- Credit Usage
- Performance Tracking
- Embrace Pinboard

[#new-10-1-0]
== 10.1.0.sw New Features and Functionality

IMPORTANT: Beginning in the 10.1.0.sw release, you will no longer be able to use the "classic experience" for Liveboards, Answers, and SpotIQ. The "new experience" from the previous release is now the only option and is on by default.

.User interface changes
****
The following changes to the ThoughtSpot UI are introduced in this release:

- Edit TML has been moved from the Answer/Liveboard list view to the *Data* > *Utilities* page.
- You cannot delete or rename pre-created tags in either the original UI or the new UI.
- The "classic experience" for the Liveboard list and the Answers list view is removed.  The "new experience" from the previous release is now the only option and is on by default for these list pages.
+
For more information, see xref:scriptability.adoc[Import and export TML files] and xref:tags.adoc[Use tags to organize].
****

[#analyst-10-1-0-sw]
=== For the Analyst

// Naomi – SCAL-181312. documentation JIRA scal-201645.
Remember personalized columns in change analysis::
Personalized columns are now available to all users and on by default. Users with edit permissions on a Liveboard can set their preferred attribute columns through the change analysis window and select *Apply to all users* to keep those selections for any subsequent change analysis calculations on that Liveboard. Individual users can still override these preferences for their own calculations. +
For more information, see
xref:spotiq-change.adoc#remember-personalized[Remember personalized columns].

// Naomi -- scal-201040
Renaming columns::
You can now rename columns in an Answer and see the new name reflected on the table header, tooltips, legend, and chart configuration menu. Changes made to an Answer are not reflected in the underlying Worksheet. For more information, see xref:chart-column-axis-rename.adoc#column-rename[Rename a table column].

Language updates::
// Naomi. epic: SCAL-181448. doc: SCAL-199383 (approved). epic: SCAL-159833. doc: SCAL-208059 (approved)
// PM: Aashna
ThoughtSpot now supports xref:keywords-ko-KR.adoc[Korean], and we've also added synonyms for date and time based keywords in xref:keywords-de-DE.adoc[German] and xref:keywords-fr-FR.adoc[French] for a more accurate experience.

Custom charts [.badge.badge-beta-relnotes]#Beta#::
You can now use custom charts created outside of ThoughtSpot, including third-party chart libraries. To enable this feature, contact {support-url}. For more information, see xref:chart-custom.adoc[Custom charts].

Models [.badge.badge-early-access-relnotes]#Early Access#::
Introducing Models. Models are an easier way of creating what previously were called Worksheets. You can create Models from the *Data* tab, just like Worksheets. You can still create and use Worksheets, but ThoughtSpot plans to deprecate and remove Worksheets in a future release. For more information, see xref:models.adoc[Models].

[#business-user-10-1-0-sw]
=== For the Business User

Redesigned home page [.badge.badge-early-access-relnotes]#Early Access#::
// Mark. doc jira: SCAL-151210
In this release, you can try our redesigned and customizable home page, where you can view your watchlist, favorites, library of Answers and Liveboards, and more. With the new left-hand navigation, you can go directly to your Liveboards, Answers, and SpotIQ Analysis.
+
This new home page experience is disabled by default. Contact your ThoughtSpot administrator to enable this feature for your cluster. After that, open your user profile, and in the _Experience_ section, set the _Navigation and Homepage_ to *New experience*. Note that this setting also enables persona-based navigation. For more information, see xref:thoughtspot-homepage.adoc[].

New persona-based navigation [.badge.badge-early-access-relnotes]#Early Access#::
// Mark. Doc jira: SCAL-175398
In this release, you can try our completely redesigned navigation experience organized by persona. The new app switcher allows business users, analysts, data engineers, administrators, and developers to work in separate contextual sections designed specifically for their needs. In addition, each app has left-hand navigation to create better consistency and ease of use for users switching between the different apps.
+
This new navigation experience is disabled by default. Contact your ThoughtSpot administrator to enable this feature for your cluster. After that, open your user profile, and in the _Experience_ section, set the _Navigation and Homepage_ to *New experience*. Note that this setting also enables the redesigned home page. For more information, see xref:thoughtspot-homepage.adoc[].

// Naomi -- scal-201035
Null and missing values in charts::
You can now choose how null and missing values appear in line, column, and bar charts in ThoughtSpot. Null and missing values appear as bars of 1 pixel width on bar and column charts. You can choose whether to display null date values as zero values, line breaks, or an average of proximate values on a line chart. Rather than showing a sharp decline to zero every time there is null or missing data on your line chart, you can see the missing values represented as line breaks or averages of the closest values instead. For more information, see
xref:chart-null-missing.adoc[Null and missing values in charts].

// Naomi – JIRA SCAL-214756
Semi-additive measures with first and last values:: Semi-additive measures with first and last values are now available to all users and on by default. A semi-additive measure, also known as snapshot data, is a measure that is usually aggregated for all attributes except for date and time. For certain measures, like inventory, you want to know what the value was at the beginning or end of a period. In that case, you can use the `last_value` function to find the inventory at the end of a month, rather than aggregating all values over the month. Similarly, you can use the `first_value` function to find out your stock at the beginning of a month.
+
For more information, see
xref:semi-additive-measures.adoc[Semi-additive measures with `first_value` and `last_value` functions] and xref:semi-additive-modeling.adoc[Modeling data for semi-additive measures].

// Naomi -- JIRA SCAL-201298
Keywords "of" and "percentage of":: The "of" and "percentage of" keywords are now on by default and available to all users. You can use the "of" and "percentage of" keywords to answer questions related to mix, contribution, share of, percentage, and total ratios. These keywords help answer questions such as, "What is the share of a certain store’s sales as a percentage of the regional whole?" To try out this feature, enter a search phrase in the search bar containing the keyword, such as `sales percentage of store region`, and press *Go*.
+
For more information, see xref:formulas-keywords.adoc[Keywords: Of and Percentage of].

Drill down in change analysis::
// Naomi – SCAL-180942. doc: SCAL-205576 (approved)
// PM: Vikas, Rahul PJP
Drill down in change analysis is now on by default and available to all users. You can now drill down on specific columns in change analysis, in order to identify change drivers within your data. For example, if you run an analysis on sales monthly and find out that the 'jacket' item type changed the most, you can easily drill down on jacket sales and identify which region contributed the most to the change in sales. For more information, see xref:spotiq-change.adoc#iterative[Iterative change analysis].


// Naomi. SCAL-178764. docs JIRA SCAL-204357. release notes only.
Error message improvements:: We have improved the error messages for CSV upload and custom calendar.

[#data-engineer-10-1-0-sw]
=== For the Data Engineer

// Mark -- Jira: SCAL-196890

Version control for Liveboards and Answers::
Version control for Liveboards and Answers is available to all users. Now teams of analysts can more easily collaborate on content development of Liveboards and Answers. You can enable version control on specific Liveboards and Answers. With version control enabled, every time you save the Liveboard or Answer, a new version is created and stored. You can browse the version history in ThoughtSpot and restore any saved versions whenever you need to. To enable this feature, contact your administrator. For more information, see xref:liveboards.adoc#version-history[Liveboards] and xref:answers.adoc#version-history[Answers].

// Naomi. jira: SCAL-264748
Node.js version::
We now support Node version 22.13.1 in 10.1.0.sw.cu1. Note that customers in operating systems AL2 and CENTOS remain on Node 18 as Node 22 is not compatible.

// Naomi -- SCAL-164290, SCAL-201306
Ts_Groups system variable::
ThoughtSpot now supports the `ts_groups` system variable in Answer and Worksheet formulas. You can use the `ts_groups` variable for data masking, or deciding whether to display the value of a column to a user based on their group membership. For more information, see xref:data-masking.adoc[].

// Naomi - JIRA: SCAL-209029. Confirm if we support OAuth for Starburst in Software
OAuth for Starburst using Proof Key for Code Exchange (PKCE):: We now support xref:connections-starburst-add.adoc[OAuth with PKCE for Starburst].

// Naomi – SCAL-191462, documentation jira scal-196178
Snowflake secondary role configuration for External OAuth::
ThoughtSpot now supports secondary role configuration when you create a Snowflake connection using External OAuth. When you set secondary roles to `ALL`, you can access all tables that any single role has access to and combine them in a single SQL query without having to switch roles.
+
For more information on primary and secondary roles, see link:https://docs.snowflake.com/en/user-guide/security-access-control-overview#enforcement-model-with-primary-role-and-secondary-roles[Enforcement model with primary role and secondary roles^] and xref:connections-snowflake-add.adoc#secondary[Add a Snowflake connection].

// Naomi – SCAL-148626. documentation jira SCAL-202207 (approved). SCAL-132544. documentation jira SCAL-202209 (approved)
Connection TML::
You can now use the table TML file to make changes to connection details like remapping columns and changing data type, rather than using the connection.yaml file. This allows you to make small changes to a Connection without the need to resolve all possible errors first. You can also edit or export the Connection TML file from the Data workspace.  For more information, see xref:tml-connections.adoc[TML for connections].

// Naomi -- SCAL-126451. documentation JIRA SCAL-201301
Sharing dbt connections::
You can now select a dbt connection and click *Share* to share the connection with other users or groups. By default, the underlying Cloud data warehouse connection is shared. Note that you need *Can manage data* privileges to access and share dbt connections.
For more information, see
xref:dbt-integration.adoc#share[Share a dbt connection].

// Naomi -- SCAL-126453, SCAL-201305
dbt connections join enhancement::
When creating a Worksheet from a dbt connection, ThoughtSpot joins the tables based on the relationships defined in the underlying .yml schema file. Now, joins between the tables will be created local to the Worksheet instead of creating a global join between the tables.

// Naomi -- SCAL-180960. documentation JIRA SCAL-201304.
dbt error message handling::
ThoughtSpot displays dbt error messages that clearly describe whether the error originated in dbt or in ThoughtSpot, where the error was encountered, and what steps users should take to resolve the issue. For a list of the error messages ThoughtSpot supports, see
xref:dbt-integration.adoc#error[dbt error messages].


// Naomi -- scal-169614, documentation JIRA scal-201047
dbt version 1.7:: ThoughtSpot now supports dbt version 1.7.

// Mark - SCAL-205579

Answer data panel enhancements::
Now in the new Answer data panel, you can filter as you hover on a column, _By category_ grouping by default, and display the information panel when you click a column.

// Mark -- Jira: SCAL-196890

Enabling GIT integration for version control of Liveboards and Answers::
Administrators can now enable version control of Liveboards and Answers. You enable version control for your ThoughtSpot Org by connecting it to a Github repository. Once enabled for the Org, version control can be enabled individually for any Liveboard or Answer. Each time a user saves changes, a new version of the Liveboard or Answer is created and stored in your Github repository. Users can easily browse and restore an older version from the Liveboard or Answer itself. For more information, see xref:git-version-control.adoc[Version control for Liveboards and Answers].

// Mark -- Jira: SCAL-136317

Multiple configurations for Snowflake connections [.badge.badge-early-access-relnotes]#Early Access#::
You can now create multiple configurations for each Snowflake connection. This allows you to allocate a separate Snowflake warehouse for different ThoughtSpot users or groups, eliminating the need to duplicate Liveboards and configure multiple Snowflake connections and helping you with cost tracking and chargeback. You can also use this for your search indexing so that you can control and balance the computing load. In addition, this allows you to easily test a set of Liveboards against different environments (dev, qa, prod), and configure different databases for multi-tenancy / multi-org deployments. For more information, see xref:connections-snowflake-add.adoc#additional-configurations-create[additional configurations for your Snowflake connection].

[#it-ops-engineer-10-1-0-sw]
=== For the IT Ops Engineer


[#developer-10-1-0-sw]
=== For the Developer

Customers licensed to embed ThoughtSpot can use ThoughtSpot Embedded features and Visual Embed SDK.

To enable ThoughtSpot Embedded on your cluster, contact {support-url}.

For information about ThoughtSpot Embedded, refer to  link:https://developers.thoughtspot.com/docs[ThoughtSpot Embedded Documentation, window=_blank].

[#upgrade-paths]
== Supported Upgrade Paths

If you are running one of the following versions, you can upgrade to the 10.1.0.sw release directly:

* 9.8.0.sw to 10.1.0.sw
* 9.5.0.sw to 10.1.0.sw

This includes any hotfixes or customer patches on these branches.

If you are running a different version, you must do a multiple pass upgrade.

First, upgrade to version 9.8.0.sw or 9.5.0.sw, and then to the 10.1.0.sw release.

NOTE: To successfully upgrade your ThoughtSpot cluster, all user profiles must include a valid email address. Without valid email addresses, the upgrade is blocked.
