= {version} Release Notes
:experimental:
:last_updated: Jun 21, 2026
:linkattrs:
:page-aliases: /release/notes.adoc
:description: These release notes include information about new and enhanced features.
:jira: SCAL-251725, SCAL-264748, SCAL-318156

++++
<style>
.badge-update-whats-new-beta {
  font-style: normal !important;
  top: -0.03rem !important;
}

</style>
++++

ThoughtSpot version {version} is now available.

These release notes include information about new and enhanced features.

To see our feature deprecation plans, please see xref:deprecation.adoc[].

* <<upgrade-paths,Supported Upgrade Paths>>

[#new-26-9-0-sw]
== {version} New Features and Functionality

[#analyst-26-9-0-sw]
=== For the Analyst

TBD

[#business-user-26-9-0-sw]
=== For the Business User

TBD

[#data-engineer-26-9-0-sw]
=== For the Data Engineer

TBD


[#developer-26-3-0-sw]
=== For the Developer

Customers licensed to embed ThoughtSpot can use ThoughtSpot Embedded features and Visual Embed SDK.

To enable ThoughtSpot Embedded on your cluster, contact {support-url}.

For information about ThoughtSpot Embedded, refer to  link:https://developers.thoughtspot.com/docs[ThoughtSpot Embedded Documentation, window=_blank].

[#upgrade-paths]
== Supported Upgrade Paths

If you are running one of the following versions, you can upgrade to the {version} release:

* 26.3.0.sw to {version}
* 10.1.0.sw (or earlier) to 26.3.0.sw, then 26.3.0.sw to {version}

This includes any hotfixes or customer patches on these branches.

If you are running a different version, you must do a multiple pass upgrade.

NOTE: To successfully upgrade your ThoughtSpot cluster, all user profiles must include a valid email address. Without valid email addresses, the upgrade is blocked.
