= 7.2 Release Notes
:experimental:
:last_updated: 3/31/2022
:linkattrs:
:page-aliases: /release/notes.adoc
:description: These release notes include information about ThoughtSpot's new and enhanced features.

ThoughtSpot version 7.2.1.CU1 is now available.

For a complete list of issues that we fixed in the 7.2.1.CU1 release, see xref:fixed.adoc#releases-7-2-x[Fixed issues].

These release notes include information about new and enhanced features.

To see our feature deprecation plans, please see xref:deprecation.adoc[].

* <<new-7-2-1,7.2.1 New Features and Functionality>>
* <<new-7-2,7.2 New Features and Functionality>>
* <<upgrade-paths,Supported Upgrade Paths>>

[#new-7-2-1]
== 7.2.1 New Features and Functionality

* <<data-engineer-7-2-1,For the Data Engineer>>
* <<it-ops-engineer-7-2-1,For the IT Ops Engineer>>

[#data-engineer-7-2-1]
=== For the Data Engineer

[#synapse-oauth]
OAuth for Microsoft Azure Synapse::
Synapse connections now support OAuth. See xref:connections-synapse-oauth.adoc[Configure OAuth for an Azure Synapse connection].

[#synapse-sql-server]
SQL Server with Synapse connections::
In this release, ThoughtSpot officially certifies and provides support for Microsoft SQL Server used with Synapse connections. Refer to xref:connections-synapse-add.adoc[Add a Synapse connection].

[#oracle]
Oracle connections support Exadata and ADW::
In this release, the Oracle ADW connection is renamed to Oracle. Existing ADW connections continue to work. There are now two options: *Cloud* for ADW connections, and *On Premise* for Exadata or on-prem database connections. For details, see xref:connections-adw.adoc[Oracle].

[#dremio]
Dremio connector::
In this release, Dremio is a new connection type. For details, see xref:connections-dremio.adoc[Dremio].
Dremio supports OAuth. For details, see xref:connections-dremio-oauth.adoc[Configure OAuth for a Dremio connection]

[#it-ops-engineer-7-2-1]
=== For the IT Ops Engineer

Support for Python versions 3.6, 3.7, and 3.9::
ThoughtSpot supports use of the following versions of Python 3 for deployment:
* Python 3.6: ThoughtSpot-managed CentOS for AWS, GCP, VMware, Azure, SMC, and Dell; customer-managed xref:rhel.adoc[RedHat Enterprise Linux (RHEL)]; customer-managed xref:rhel.adoc[Oracle Enterprise Linux (OEL)]; customer-managed xref:al2.adoc[Amazon Linux 2]
* Python 3.7: customer-managed Amazon Linux 2
* Python 3.9: ThoughtSpot-managed CentOS for AWS, GCP, and Azure; customer-managed xref:rhel.adoc[RedHat Enterprise Linux (RHEL)]; customer-managed xref:al2.adoc[Amazon Linux 2]

[#new-7-2]
== 7.2 New Features and Functionality

* <<analyst-7-2,For the Analyst>>
* <<business-user-7-2,For the Business User>>
* <<data-engineer-7-2,For the Data Engineer>>
* <<it-ops-engineer-7-2,For the IT Ops Engineer>>
* <<developer-7-2,For the Developer>>

[#analyst-7-2]
=== For the Analyst
[#scriptability]
Improved import workflow for TML files:: The new import workflow for xref:scriptability.adoc[importing and exporting TML files] identifies errors, suggests solutions, and allows you to resolve these errors as part of the import workflow.
It also has a cleaner, more intuitive UI, with separate sections for different object types.

[#proximity-search]
Proximity search for Connections::
ThoughtSpot now supports proximity searches, find entities related to each other by location, for data from xref:connections.adoc[].

[#business-user-7-2]
=== For the Business User

[#profile-ui]
UI improvement for user profile::
This release improves the UI and user experience of the xref:user-profile.adoc[user profile].

[#geomaps]
Geo map support::
New Zealand;; We added support for regional councils, cities and districts, and postcodes, for New Zealand.
Denmark;; We added support for regions, municipalities, and postal codes, for Denmark.
+
See xref:geomap-reference.adoc[Geo Map Reference].

[#data-engineer-7-2]
=== For the Data Engineer

[#dataflow]
DataFlow:: We added support for the following database: xref:dataflow-impala.adoc[Impala].

Presto query engines:;; In addition to the Presto query engine, you can now use Starburst and Trino query engines when you create your Presto DataFlow connection. See xref:dataflow-presto-reference.adoc#dataflow-presto-conn-query-engine[Presto connection reference] for further details.


[#connections-azure-ad-oauth]
Azure AD OAuth for Snowflake connections::
Snowflake connections now support Azure AD OAuth. For configuration details, see xref:connections-snowflake-azure-ad-oauth.adoc[Configure Azure AD OAuth for Snowflake].

[#connections-azure-ad-oauth]
OAuth for Redshift connections::
Redshift connections now support OAuth. For configuration details, see xref:connections-redshift-oauth.adoc[Configure OAuth for Redshift].


[#it-ops-engineer-7-2]
=== For the IT Ops Engineer

[#rhel]
RHEL 8 support::
ThoughtSpot now supports installation on RHEL 8.1, 8.2, 8.3, 8.4, and 8.5. Refer to the xref:rhel.adoc[RHEL deployment guide].

SAML assertion validity::
ThoughtSpot now supports 2 methods to increase the duration of validity for your xref:saml.adoc#saml-assertion[SAML assertion]: the `SessionNotOnOrAfter` attribute and the `maxAuthenticationAge` parameter. You can ask ThoughtSpot to disable either one of these checks. If you use both, and either check fails, ThoughtSpot does not authenticate the user. Some IDPs do not support use of `SessionNotOnOrAfter`. If your IDP does not support use of `SessionNotOnOrAfter`, remove that attribute from your IDP assertion and ask {support-url} to enable `maxAuthenticationAge`.

////
Manage answer experience::
This release allows administrators to control the answer experience for their users. In 7.2, the xref:answer-experience-new.adoc[new answer experience] is available but off by default. Individual users can turn it on from their profile. Administrators can now manage the availability of the new answer experience by contacting {support-url}. ThoughtSpot Support can turn the new answer experience on or off globally, and specify the default answer experience for all users. For example, you can turn the new answer experience on globally and have the new experience as the default, instead of the classic experience.
+
To manage the availability of the new answer experience, contact {support-url}.
////

[#developer-7-2]
=== For the Developer

Customers embedding ThoughtSpot in software releases should continue embedding ThoughtSpot using xref:embedding-overview.adoc[legacy embedding tools], which remain supported in 7.x software releases. Upgrading an environment with an existing embedded solution leveraging the legacy embedded technology to SW v.7.x is supported and seamless from an embedding standpoint.

////
ThoughtSpot Everywhere::
For information about the new features and enhancements introduced in this release, refer to the documentation embedded in your ThoughtSpot environment under the *Develop* tab.
////

[#upgrade-paths]
== Supported Upgrade Paths

If you are running one of the following versions, you can upgrade to the 7.2.1.x release directly:

* 7.0.x to 7.2.1.x
* 7.1.x to 7.2.1.x

This includes any hotfixes or customer patches on these branches.

If you are running a different version, you must do a multiple pass upgrade.

First, upgrade to version 7.0.x or 7.1.x, and then to the 7.2.1.x release.

NOTE: To successfully upgrade your ThoughtSpot cluster, all user profiles must include a valid email address. Without valid email addresses, the upgrade is blocked.
