= 26.3.0.sw Release Notes
:experimental:
:last_updated: 9/22/25
:linkattrs:
:page-aliases: /release/notes.adoc
:description: These release notes include information about new and enhanced features.
:jira: SCAL-251725, SCAL-264748

++++
<style>
.badge-update-whats-new-beta {
  font-style: normal !important;
  top: -0.03rem !important;
}

</style>
++++

ThoughtSpot version 26.3.0.sw is now available.

These release notes include information about new and enhanced features.

To see our feature deprecation plans, please see xref:deprecation.adoc[].

* <<upgrade-paths,Supported Upgrade Paths>>

[#new-26-3-0-sw]
== 26.3.0.sw New Features and Functionality

[#analyst-26-3-0-sw]
=== For the Analyst

// Writer – SCALs (epic and doc).



[#business-user-26-3-0-sw]
=== For the Business User

// Naomi – jira: SCAL-265718. docs jira: SCAL-265719
// PM: Anshul Mehta
[#kpi-chart]
KPI chart settings [.badge.badge-early-access-relnotes]#Early Access#::
ThoughtSpot introduces more granular controls for KPI charts. You can now:
+
--
* Decide how missing dates are displayed (as gaps, ignored, or treated as 0).
* Specify whether to show or hide the current date, previous date, and previous value.

* Abbreviate previous month (PM) or previous quarter (PQ).

* Specify whether the measure’s increase or decrease is positive or negative.
--
+
To enable this feature, contact your administrator. For more information, see
xref:chart-kpi.adoc#advanced[KPI charts].




[#data-engineer-26-3-0-sw]
=== For the Data Engineer

// Naomi – Jira: SCAL-239719. docs jira: SCAL-270725
// PM: Damian.
[#column-security]
Column security rules [.badge.badge-early-access-relnotes]#Early Access#::

You can now set column security rules at the table level, and they will automatically be inherited to associated Models. Operational management is simplified as the cluster setting, Strict Object Mode, is not required. In addition, rules are only required for the secured columns rather than all columns in the table. For each column you select as restricted, you can define which group(s) can have access to the column. Users without access will not see the column in search results, or anywhere in the product. To enable this feature, contact your administrator.
+
For more information, see xref:security-data-object.adoc#csr[Column security rules].

// Naomi. jira: SCAL-261281. docs jira: SCAL-287514
// PM: Siddhant

[#liveboards-with]
Liveboards with column security rules [.badge.badge-early-access-relnotes]#Early Access#:: We have enhanced the behavior of Liveboards built with column security rules. If users restricted by column security access the Liveboard, they can see and interact with the Liveboard filters and visualizations, but cannot edit the Liveboard as a whole. If such inaccessible columns are used as filters in the Liveboard, the Liveboard will no longer be blocked. Schedules now honor column security rules, and each recipient receives their own report based on their column security rule assignments.
+
For more information, see xref:security-data-object.adoc#csr-liveboard[Column security rules on Liveboards].




// Naomi – Jira ID: SCAL-251015. docs jira: SCAL-273076
// PM: Damian.
[#tenant-based]
Tenant-based column aliasing [.badge.badge-early-access-relnotes]#Early Access#::
Tenant-based column aliasing introduces the capability to define a column name or description based upon the user's membership in a ThoughtSpot Org or group. For example, Client 1 may refer to a column as Region, whilst Client 2 may refer to this as State. This feature is an extension of the language-based aliasing. Data analysts can define these aliases via CSV upload or with TML. This feature is particularly useful for embedded scenarios where the same underlying Model is leveraged across multiple clients.
+
For more information, see xref:column-aliases-tenant.adoc[Tenant-based column aliases].

// Naomi. jira: SCAL-241441. docs jira: SCAL-278562
// PM: Prayansh
[#csv-upload]
CSV upload support for Google BigQuery:: You now have a quick and easy way to complete data loads of files that are not present in your cloud data warehouse. You can now upload a CSV file to your Google BigQuery connection that can be joined to other tables in your connection. To use this feature, go to *Data* > *Utilities*, and click *Upload CSV*. To enable this feature, contact your administrator.
+
For more information, see xref:connections-gbq-csv-upload.adoc[Upload a CSV file to Google BigQuery].

// Naomi. jira: SCAL-241438 docs jira: SCAL-275547
// PM: Prayansh
[#databricks-csv]
Databricks CSV upload:: You now have a quick and easy way to complete data loads of files that are not present in your cloud data warehouse. You can now upload a CSV file to your Databricks connection that can be joined to other tables in your connection. To use this feature, go to *Data* > *Utilities*, and click *Upload CSV*.
+
For more information, see xref:connections-databricks-csv-upload.adoc[].

// Naomi. jira: SCAL-270846, docs jira: SCAL-270847
// PM: Prayansh
[#personal-access]
Personal Access Token (PAT) authentication for Snowflake:: We now support Personal Access Token authentication for Snowflake. For more information, see xref:connections-snowflake-add.adoc#pat[Add a Snowflake connection].

// Naomi. jira: SCAL-262993. docs jira: SCAL-267256.
// PM: Prayansh
[#oauth-client]
OAuth Client Credentials for Snowflake::

We now support OAuth Client Credentials authentication for Snowflake. For more information, see xref:connections-snowflake-add.adoc#client-credentials[Add a Snowflake connection] and xref:connections-snowflake-oauth-client.adoc[Snowflake OAuth with Client Credentials].

// Naomi. jira: SCAL-193108. docs jira: SCAL-262244
[#multiple-configurations]
Multiple configurations per connection:: In addition to xref:connections-snowflake-add.adoc#additional-configurations-create[Snowflake], we now support multiple configurations for xref:connections-databricks-add.adoc#additional-configurations-create[Databricks] and xref:connections-gbq-add.adoc#additional[Google BigQuery]. This feature allows you to allocate separate configurations for different ThoughtSpot users, groups, or processes, eliminating the need to duplicate Liveboards and configure multiple connections, and helping you with cost tracking and governance. You can also use this for your system processes so that you can control and balance the computing load.




[#it-ops-engineer-10-1-0-sw]
=== For the IT Ops Engineer

// Writer – SCALs (epic and doc).


[#developer-26-3-0-sw]
=== For the Developer

Customers licensed to embed ThoughtSpot can use ThoughtSpot Embedded features and Visual Embed SDK.

To enable ThoughtSpot Embedded on your cluster, contact {support-url}.

For information about ThoughtSpot Embedded, refer to  link:https://developers.thoughtspot.com/docs[ThoughtSpot Embedded Documentation, window=_blank].

[#upgrade-paths]
== Supported Upgrade Paths

If you are running one of the following versions, you can upgrade to the 26.3.0.sw release directly:

* 10.10.0.sw to 26.3.0.sw
* 10.1.0.sw to 26.3.0.sw

This includes any hotfixes or customer patches on these branches.

If you are running a different version, you must do a multiple pass upgrade.

First, upgrade to version 10.10.0.sw or 10.1.0.sw, and then to the 26.3.0.sw release.

NOTE: To successfully upgrade your ThoughtSpot cluster, all user profiles must include a valid email address. Without valid email addresses, the upgrade is blocked.
