= 10.10.0.sw Release Notes
:experimental:
:last_updated: 8/11/25
:linkattrs:
:page-aliases: /release/notes.adoc
:description: These release notes include information about new and enhanced features.
:jira: SCAL-251725, SCAL-264748

++++
<style>
.badge-update-whats-new-beta {
  font-style: normal !important;
  top: -0.03rem !important;
}

</style>
++++

ThoughtSpot version 10.10.0.sw is now available.

These release notes include information about new and enhanced features.

To see our feature deprecation plans, please see xref:deprecation.adoc[].

* <<upgrade-paths,Supported Upgrade Paths>>

[#new-10-10-0-cu1]
== 10.10.0.sw New Features and Functionality

// Writer – SCALs (epic and doc).
TBD::
TBD
+
For more information, see
TBD

[#analyst-10-10-0-sw]
=== For the Analyst

// Writer – SCALs (epic and doc).
TBD::
TBD
For more information, see
TBD.

[#business-user-10-10-0-sw]
=== For the Business User

TBD::
// Writer – SCALs (epic and doc).
TBD.
For more information, see TBD.

[#data-engineer-10-10-0-sw]
=== For the Data Engineer

// Writer – SCALs (epic and doc).

TBD::
TBD. For more information, see TBD.

[#it-ops-engineer-10-1-0-sw]
=== For the IT Ops Engineer

// Writer – SCALs (epic and doc).

TBD::
TBD. For more information, see TBD.

[#developer-10-1-0-sw]
=== For the Developer

Customers licensed to embed ThoughtSpot can use ThoughtSpot Embedded features and Visual Embed SDK.

To enable ThoughtSpot Embedded on your cluster, contact {support-url}.

For information about ThoughtSpot Embedded, refer to  link:https://developers.thoughtspot.com/docs[ThoughtSpot Embedded Documentation, window=_blank].

[#upgrade-paths]
== Supported Upgrade Paths

If you are running one of the following versions, you can upgrade to the 10.10.0.sw release directly:

* 10.1.0.sw to 10.10.0.sw
* 9.8.0.sw to 10.10.0.sw

This includes any hotfixes or customer patches on these branches.

If you are running a different version, you must do a multiple pass upgrade.

First, upgrade to version 10.1.0.sw or 9.8.0.sw, and then to the 10.10.0.sw release.

NOTE: To successfully upgrade your ThoughtSpot cluster, all user profiles must include a valid email address. Without valid email addresses, the upgrade is blocked.
