= 26.3.0.sw Release Notes
:experimental:
:last_updated: April 17, 2026
:linkattrs:
:page-aliases: /release/notes.adoc
:description: These release notes include information about new and enhanced features.
:jira: SCAL-251725, SCAL-264748

++++
<style>
.badge-update-whats-new-beta {
  font-style: normal !important;
  top: -0.03rem !important;
}

</style>
++++

ThoughtSpot version 26.3.0.sw is now available.

These release notes include information about new and enhanced features.

To see our feature deprecation plans, please see xref:deprecation.adoc[].

* <<upgrade-paths,Supported Upgrade Paths>>

[#new-26-3-0-sw]
== 26.3.0.sw New Features and Functionality

[#analyst-26-3-0-sw]
=== For the Analyst

// Mark. jira: SCAL-285343. docs jira: SCAL-285344
// PM: Manan
[#new-charts-powered]
New charts library [.badge.badge-early-access-relnotes]#Early Access#:: This release significantly upgrades ThoughtSpot visualization capabilities by introducing nine new, powerful native charts — Line, Column, Bar, Area, Line Column, Line Stacked Column, Stacked Column, Stacked Bar, and Stacked Area.
+
These new charts unlock sophisticated visualizations like faceted, cross-tabbed, multivariate, and bullet charts. They also resolve previous limitations by allowing multiple columns in Line Column charts and slicing by color with multiple measures, while providing deeper granular control over configurations such as tooltips, data labels, and axes.
To enable this feature, contact your administrator.
+
For more information, see xref:charts-library-new.adoc[ThoughtSpot's new charts].

// Mark. jira: SCAL-264868. docs jira: SCAL-287513
// PM: Manan
[#chart]
New chart settings experience::
The new chart settings experience is now generally available (GA) and on by default. The chart settings panel is completely redesigned with a more intuitive layout and easier access. With over 50 advanced settings available across different chart types, you’ll have pixel-perfect control over every aspect of your visualizations - including data label sizes, colors, font styles, grid lines, tooltips, and more.
+
For more information, see
xref:charts-new.adoc[New chart settings experience].

// Mary - SCAL-286048
[#left-nav-admin]
Admin settings in left navigation::
ThoughtSpot introduces a new and improved user experience for Administration. Administration is now part of the left navigation panel.
For more information, see xref:thoughtspot-homepage.adoc[New homepage and navigation].

//Mary - SCAL-174558
[#sets]
Column sets::
Column sets are now available to all users and on by default. A column set is a custom group of values from a single column. You can create column sets, which can be used to classify values in a list that you can then reuse across multiple analyses. For example, you can use column sets to define regions with specific countries included or excluded. Column sets are community objects which remain when you navigate away from the Search Data page and can be used by any user with view access to the underlying Model. For more information, see
xref:column-sets.adoc[Column sets].

// Mary - SCAL-174558
[#query]
Query sets::
Query sets are now available to all users and on by default. You can create query sets, which can be used to classify values in a list that you can then reuse across multiple analyses. A query set is a custom group of values from a collection of objects in your database. Query sets are community objects which remain when you navigate away from the Search Data page and can be used by any user with view access to the underlying Worksheet. For more information, see xref:query-sets.adoc[Query sets].

//Mary - SCAL-89860
[#RLS-rule-logic]
Enhanced row-level security (RLS) rule logic::
ThoughtSpot introduces RLS rule logic to support using AND/OR operators with bracket notation. You can now define more precise and complex access control policies that accurately reflect your organization’s security requirements without resorting to data modeling solutions with access control list tables. For more information, see xref:security-rls-concept.adoc[How rule-based RLS works].

// Rani. jira: SCAL-248189. docs jira: SCAL-257624
//Damian
[#rerun-queries]
Rerun queries in Search data::
This functionality allows users to execute the same search query again without needing to refresh the browser or modify the query, and update results with the latest data.
With this feature, users can simply click *Go* to rerun the query, which is useful for testing data model changes, formula updates, or database reloads.
+
For more information, see xref:search.adoc[Rerun your search query].

// Rani. Jira: SCAL-246727. Docs jira: SCAL-246727
//PM: Christina Yu
[#last-value]
Last value in period and first value in period functions::
`Last_value_in_period` and `first_value_in_period` functions are now available to all users and on by default. These functions are useful for semi-additive measures, measures that typically return a single value per time period rather than being additive across time. For example, if you want to find out the last value for full-time employee headcount for the current date, you can use the formula, `fxFTE = last_value_in_period(sum(full_time_employee), query_groups(), {date})`.
+
For more information, see xref:semi-additive-measures-period.adoc[Last_value_in_period and first_value_in_period functions].


//Mary - SCAL-174558
//PM Damian
[#26-3-0-sw-sets]
Column sets::
Column sets are now generally available (GA). A column set is a custom group of values from a single column. You can create column sets, which can be used to classify values in a list that you can then reuse across multiple analyses. For example, you can use column sets to define regions with specific countries included or excluded. Column sets are community objects which remain when you navigate away from the Search Data page and can be used by any user with view access to the underlying Model.
+
For more information, see xref:column-sets.adoc[Column sets].

//Mary - SCAL-174558
//PM Damian
Query sets::
Query sets are now generally available (GA). You can create query sets, which can be used to classify values in a list that you can then reuse across multiple analyses. A query set is a custom group of values from a collection of objects in your database. Query sets are community objects which remain when you navigate away from the Search Data page and can be used by any user with view access to the underlying Worksheet.
+
For more information, see xref:query-sets.adoc[Query sets].

//Mary - SCAL-89860
//PM Damian
[#RLS-rule-logic]
Enhanced row-level security (RLS) rule logic::
RLS rule logic to support using AND/OR operators with bracket notation is now generally available (GA). You can now define more precise and complex access control policies that accurately reflect your organization’s security requirements without resorting to data modeling solutions with access control list tables.
+
For more information, see xref:security-rls-concept.adoc[How rule-based RLS works].




[#business-user-26-3-0-sw]
=== For the Business User


//Mary - SCAL-253882
//PM Arpit
[#nav-homepage]::
New navigation and homepage
ThoughtSpot is excited to announce that our brand-new navigation and homepage experience is now generally available (GA). This change does not apply to users of ThoughtSpot in an embedded environment.

Highlights of the new navigation and homepage:

* Enhanced navigation: commonly accessed features are now in a left-side navigation menu, providing a more intuitive and consistent user experience across all product areas

* Fewer clicks: faster and easier to move between key areas, such as between Liveboards, or from a Model to searching data

* Favorites and Liveboard schedule access: now available with a single click from the homepage navigation menu, allowing you to quickly find your most important data

* Modern homepage: clean, contemporary, and customizable design

The classic navigation and homepage experience is no longer available. For more information, see xref:thoughtspot-homepage.adoc[New homepage and navigation].

// Mary - SCAL-286048
//PM Arpit
[#left-nav-admin]
Admin settings in left navigation::
ThoughtSpot introduces a new and improved user experience for Administration. Administration is now part of the left navigation panel.
For more information, see xref:thoughtspot-homepage.adoc[New homepage and navigation].


// Naomi – jira: SCAL-265718. docs jira: SCAL-265719
// PM: Anshul Mehta
[#kpi-chart]
KPI chart settings [.badge.badge-early-access-relnotes]#Early Access#::
ThoughtSpot introduces more granular controls for KPI charts. You can now:
+
--
* Decide how missing dates are displayed (as gaps, ignored, or treated as 0).
* Specify whether to show or hide the current date, previous date, and previous value.

* Abbreviate previous month (PM) or previous quarter (PQ).

* Specify whether the measure’s increase or decrease is positive or negative.
--
+
To enable this feature, contact your administrator. For more information, see
xref:chart-kpi.adoc#advanced[Advanced KPI display options].

// Mark. jira: SCAL-271016. docs jira: SCAL-271017
// PM: Manan/Anshul
[#improved-chart]
Improved chart recommendations::

Improved chart recommendations are now generally available (GA) and on by default. When you search, ThoughtSpot can automatically suggest a chart type based on your search query. The following capabilities are improved:

* When you submit a query for the first time, ThoughtSpot analyzes the data and automatically selects the most appropriate chart.
* If you modify an existing query by adding or removing fields, ThoughtSpot retains the existing chart type unless it is forced to change.
* When you drill down into data, ThoughtSpot maintains the current chart type whenever possible.
+
For more information, see
xref:charts.adoc#chart-recs[Improved chart recommendations].

// Mark. jira: SCAL-260580. docs jira: SCAL-269159
// PM: Manan? Vaibhav? Is this feature only used in titles?
[#dynamic]
Enhanced dynamic parameters in charts::
Enhanced dynamic parameters are now generally available (GA) and on by default. You can use parameters across axis names, column names, answer titles and descriptions to change these elements dynamically based on the parameter value. A parameter used in the title or description always displays the value of the same parameter used in the chart itself.
+
For more information, see
xref:charts.adoc#parameters[Dynamic parameters in charts and Answers].

//Mary - SCAL-253882
[#nav-homepage]
New navigation and homepage::
ThoughtSpot is excited to announce that our brand-new navigation and homepage experience is now enabled by default for all users. This change does not apply to users of ThoughtSpot in an embedded environment.
+
Highlights of the new navigation and homepage:
+
--
* Enhanced navigation: commonly accessed features are now in a left-side navigation menu, providing a more intuitive and consistent user experience across all product areas

//Mary - SCAL-252930
// PM Siddhant
[#style-group]
Liveboard styling and grouping::
Liveboard styling and grouping options are now generally available (GA). Styles can be applied to a Liveboard, a tile, or a group of tiles to improve readability, differentiate specific content, or apply organizational branding guidelines. You can group relevant content together within a Liveboard using grouping.
+
For more information, see xref:liveboard-grouping-styling.adoc[Liveboard grouping and Liveboard styling].

//Mary - SCAL-246097
// PM Siddhant
[#filter-cover]
Include or exclude cover and filter pages from a Liveboard PDF::
The option to exclude cover and filter pages from Liveboard PDFs is now generally available (GA). ThoughtSpot Liveboard PDFs include a cover page and filter pages that contain information about the filters applied. You can now use the PDF Options checkboxes to choose to include or exclude these pages when downloading or scheduling a Liveboard PDF. Cover and filter pages can be excluded for a schedule or download by the user. An administrator can also set cover and filter pages to be included or excluded by default in Admin settings under Downloads & Schedules.
+
For more information, see xref:liveboard-download-pdf.adoc[Download a Liveboard as a PDF].

//Mary - SCAL-230770
//PM Dillip
[#relevant-filters-parameters-LB]
Show only relevant filters and parameters on Liveboards::
This feature is now on generally available (GA). Filters and parameters that are not relevant to a tab are hidden by default when you open and view a Liveboard. You can choose to view all filters and parameters, including those that are not relevant to the tab, so that you can quickly create a new View or download the Liveboard without needing to switch tabs and apply filters individually.
+
For more information, see xref:liveboard-filters.adoc[Apply filters to specific visualizations or tabs].


//Mary - SCAL-230636
//PM Arpit
[#reorder-parameters-LB-Answers]
Reorder parameters in Liveboards and Answers::
This feature is now generally available (GA). You can now edit a Liveboard or Answer to reorder the parameters along with filters and save your changes. The new order is reflected when anyone opens the Liveboard or Answer.
+
For more information, see xref:parameters-use.adoc#reorder-parameters[Reorder parameters in Liveboards and Answers].


//Mary - SCAL-226098
//PM Manan
[#26-3-0-sw-pivot-table]
Pivot table enhancements::
The new pivot table chart is now generally available (GA). This new chart has improvements in the following areas:

* Performance
** Faster interaction while expanding rows and columns
** Pagination
* Customization
** Custom sort order support
** Column widths
** Slicing with measures and attributes
** Measure names and values
* UX
** Tooltips
** Legends
** Zebra mode
** Decluttered header space

+
For more information, see xref:chart-pivot-table.adoc#pivot-table-2-0[New Pivot Table charts].

//Mary - SCAL-261454
//PM Mannan
[#custom-sort]
Custom Sort::
Custom sorting on Answers is now generally available (GA). You can now define and modify a custom sort order for attributes directly in an Answer. Sort order defined in the Answer overrides the sort order defined in the Model for that particular Answer.
+
For more information, see xref:answer-custom-sort.adoc[Define or edit a custom sort order for an Answer].

//Mary - SCAL-244743
//PM Siddhant
[#LB-download-schedule]
Improved experience for Liveboard downloads and schedules[.badge.badge-early-access-relnotes]#Early Access#::
ThoughtSpot introduces an improved experience for Liveboard downloads and schedules:
When you select Download, you can now select CSV and XLSX in addition to PDF. When you select CSV or XLSX, you can choose which visualizations to download and a bulk download of the Liveboard data is triggered instead of a static image.
When you select Schedule, you can now select specific visualizations to include in the scheduled email attachment as CSV or XLSX files.
To enable this feature, contact your administrator.
+
For more information, see xref:liveboard-download-pdf.adoc[Download a Liveboard and Schedule a Liveboard job].




* Favorites and Liveboard schedule access: now available with a single click from the homepage navigation menu, allowing you to quickly find your most important data

* Modern homepage: clean, contemporary, and customizable design
--
+
The classic navigation and homepage experience is no longer available. For more information, see xref:thoughtspot-homepage.adoc[New homepage and navigation].

//Mary - SCAL-252930
[#group]
Liveboard styling and grouping::
Liveboard styling and grouping options are now generally available (GA) and on by default. Styles can be applied to a Liveboard, a tile, or a group of tiles to improve readability, differentiate specific content, or apply organizational branding guidelines. You can group relevant content together within a Liveboard using grouping.
For more information, see
xref:liveboard-grouping-styling.adoc[Liveboard grouping and Liveboard styling].

//Mary - SCAL-246097
[#filter-cover]
Include or exclude cover and filter pages from a Liveboard PDF::
The option to exclude cover and filter pages from Liveboard PDFs is now on by default. ThoughtSpot Liveboard PDFs include a cover page and filter pages that contain information about the filters applied. You can now use the PDF Options checkboxes to choose to include or exclude these pages when downloading or scheduling a Liveboard PDF. Cover and filter pages can be excluded for a schedule or download by the user. An administrator can also set cover and filter pages to be included or excluded by default in Admin settings under Downloads & Schedules.
For more information, see
xref:liveboard-download-pdf.adoc[Download a Liveboard as a PDF].

//Mary - SCAL-230770
[#relevant-filters-parameters-LB]
Show only relevant filters and parameters on Liveboards::
This feature is now on by default and available to all users. Filters and parameters that are not relevant to a tab are hidden by default when you open and view a Liveboard. You can choose to view all filters and parameters, including those that are not relevant to the tab, so that you can quickly create a new View or download the Liveboard without needing to switch tabs and apply filters individually.
For more information, see
xref:liveboard-filters.adoc[Apply filters to specific visualizations or tabs].

//Mary - SCAL-230636
[#reorder-parameters-LB-Answers]
Reorder parameters in Liveboards and Answers::
This feature is now enabled by default and available to all users. You can now edit a Liveboard or Answer to reorder the parameters along with filters and save your changes. The new order is reflected when anyone opens the Liveboard or Answer.
For more information, see
xref:parameters-use.adoc#reorder-parameters[Reorder parameters in Liveboards and Answers].

//Mary - SCAL-226098
[#pivot-table]
Pivot table enhancements::
The new pivot table chart is now available by default. This new chart has improvements in the following areas:
+
--
* Performance
** Faster interaction while expanding rows and columns
** Pagination
* Customization
** Custom sort order support
** Column widths
** Slicing with measures and attributes
** Measure names and values
* UX
** Tooltips
** Legends
** Zebra mode
** Decluttered header space
--
+
For more information, see
xref:chart-pivot-table.adoc#pivot-table-2-0[New pivot table charts].

//Mary - SCAL-261454
[#custom-sort]
Custom sort::
Custom sorting on Answers is now on by default and available to all users. You can now define and modify a custom sort order for attributes directly in an Answer. Sort order defined in the Answer overrides the sort order defined in the Model for that particular Answer.
For more information, see
xref:answer-custom-sort.adoc[Define or edit a custom sort order for an Answer].

//Mary - SCAL-244743
[#LB-download-schedule]
Improved experience for Liveboard downloads and schedules::
ThoughtSpot introduces an improved experience for Liveboard downloads and schedules:
When you select Download, you can now select CSV and XLSX in addition to PDF. When you select CSV or XLSX, you can choose which visualizations to download and a bulk download of the Liveboard data is triggered instead of a static image.
When you select Schedule, you can now select specific visualizations to include in the scheduled email attachment as CSV or XLSX files.
To enable this feature, contact your administrator. For more information, see
xref:liveboard-download-pdf.adoc[Download a Liveboard] and xref:liveboard-schedule.adoc[Schedule a Liveboard job].


[#data-engineer-26-3-0-sw]
=== For the Data Engineer

// Mark. jira: SCAL-271228. docs jira: SCAL-271229
// PM: Manan, Anshul
[#muze-studio]
Muze Studio::
Muze Studio is now generally available (GA) and on by default. You can create your own charts in ThoughtSpot using the Muze charting library. A developer can create new chart types by writing the code in the code builder. This release introduces a new console window which helps developers quickly identify and resolve issues with real-time feedback on their JavaScript code execution by providing errors and warnings generated during code execution.
+
For more information, see
xref:chart-create.adoc[Creating charts with Muze Studio].

// Naomi – Jira: SCAL-239719. docs jira: SCAL-270725
// PM: Damian.
[#column-security]
Column security rules [.badge.badge-early-access-relnotes]#Early Access#::

You can now set column security rules at the table level, and they will automatically be inherited to associated Models. Operational management is simplified as the cluster setting, Strict Object Mode, is not required. In addition, rules are only required for the secured columns rather than all columns in the table. For each column you select as restricted, you can define which group(s) can have access to the column. Users without access will not see the column in search results, or anywhere in the product. To enable this feature, contact your administrator.
+
For more information, see xref:security-data-object.adoc#csr[Column security rules].



// Naomi. jira: SCAL-261281. docs jira: SCAL-287514
// PM: Siddhant

[#liveboards-with]
Liveboards with column security rules [.badge.badge-early-access-relnotes]#Early Access#:: We have enhanced the behavior of Liveboards built with column security rules. If users restricted by column security access the Liveboard, they can see and interact with the Liveboard filters and visualizations, but cannot edit the Liveboard as a whole. If such inaccessible columns are used as filters in the Liveboard, the Liveboard will no longer be blocked. Schedules now honor column security rules, and each recipient receives their own report based on their column security rule assignments.
+
For more information, see xref:security-data-object.adoc#csr-liveboard[Column security rules on Liveboards].

// Rani – jira: SCAL-202857
//PM: Akshat Shah
[#tml-utility]
TML utility [.badge.badge-early-access-relnotes]#Early Access#:: The *Import TML* can now also be done asynchronously from the new TML utility. This allows users to trigger TML imports directly from the UI, which are processed as asynchronous jobs in the backend. You can enable this feature from the *Data modelling* option under *Application Settings* on the *Admin settings* page. Once enabled, you can access the new UI from the *Data workspace* > *Utilities* page.
+
For more information, see xref:scriptability.adoc#async-import[Async import TML utility].

// Naomi. jira: SCAL-219728. docs jira: SCAL-220584
// PM: Damian
[#date-interval]
Date interval setting:: The date interval setting in TML is now generally available (GA) and on by default. You can set the default date bucket for a Model column at the instance level. The options are detailed, daily, weekly, monthly, quarterly, yearly, hourly, or no_bucket. Note that hourly is only available for datetime data.
+
For more information, see
xref:tml-models.adoc#date-bucket-default[Default date bucket].


// Rani. jira: SCAL-233681. docs jira: SCAL-242416
// PM: Damian
[#rls-support]
RLS support for integer comparison for ts_groups::
ThoughtSpot introduces a new system variable `ts_groups_int` for integer comparison in the row-level security configuration. This allows you to create RLS rules where an integer column is compared directly to the integer group IDs a user belongs to.
+
For more information, see
xref:security-rls-concept.adoc[How rule-based RLS works].

// Rani. jira: SCAL-263003. docs jira: SCAL-271538
// PM: Prayansh
[#connection-tml]
Connection TML import for OAuth without validation::
ThoughtSpot now supports importing OAuth connections through TML without validation. This feature allows users to import an OAuth connection via TML without performing validation during the import process.
+
For more information, see xref:tml-connections.adoc[TML for connections].

// Naomi. jira: SCAL-231120. docs jira: SCAL-268867
[#add-user]
Add user-defined ID (object ID) in TML:: You can now directly add or edit an object ID in the TML of an Answer, table, Model, Liveboard, or View. This user-defined object ID allows you to manage content across multiple Orgs without having to manually change the GUID of an object each time you move it between Orgs. To enable this feature, contact {support-url}.
+
For more information, see xref:tml.adoc#object-id[Object ID in TML files].


// Naomi – Jira ID: SCAL-251015. docs jira: SCAL-273076
// PM: Damian.
[#tenant-based]
Tenant-based column aliasing [.badge.badge-early-access-relnotes]#Early Access#::
Tenant-based column aliasing introduces the capability to define a column name or description based upon the user's membership in a ThoughtSpot Org or group. For example, Client 1 may refer to a column as Region, whilst Client 2 may refer to this as State. This feature is an extension of the language-based aliasing. Data analysts can define these aliases via CSV upload or with TML. This feature is particularly useful for embedded scenarios where the same underlying Model is leveraged across multiple clients.
+
For more information, see xref:column-aliases-tenant.adoc[Tenant-based column aliasing].

// Naomi. jira: SCAL-241441. docs jira: SCAL-278562
// PM: Prayansh
[#csv-upload]
CSV upload support for Google BigQuery:: You now have a quick and easy way to complete data loads of files that are not present in your cloud data warehouse. You can now upload a CSV file to your Google BigQuery connection that can be joined to other tables in your connection. To use this feature, go to *Data* > *Utilities*, and click *Upload CSV*. To enable this feature, contact your administrator.
+
For more information, see xref:connections-gbq-csv-upload.adoc[Upload a CSV file in your Google BigQuery connection].

// Naomi. jira: SCAL-241438 docs jira: SCAL-275547
// PM: Prayansh
[#databricks-csv]
Databricks CSV upload:: You now have a quick and easy way to complete data loads of files that are not present in your cloud data warehouse. You can now upload a CSV file to your Databricks connection that can be joined to other tables in your connection. To use this feature, go to *Data* > *Utilities*, and click *Upload CSV*.
+
For more information, see xref:connections-databricks-csv-upload.adoc[].

// Naomi. jira: SCAL-270846, docs jira: SCAL-270847
// PM: Prayansh
[#personal-access]
Personal Access Token (PAT) authentication for Snowflake:: We now support Personal Access Token authentication for Snowflake. For more information, see xref:connections-snowflake-add.adoc#pat[Personal Access Token authentication].

// Naomi. jira: SCAL-262993. docs jira: SCAL-267256.
// PM: Prayansh
[#oauth-client]
OAuth Client Credentials for Snowflake::

We now support OAuth Client Credentials authentication for Snowflake. For more information, see xref:connections-snowflake-add.adoc#client-credentials[OAuth Client Credentials] and xref:connections-snowflake-oauth-client.adoc[Configure OAuth with Client Credentials for a Snowflake connection].

// Naomi. jira: SCAL-193108. docs jira: SCAL-262244
[#multiple-configurations]
Multiple configurations per connection:: In addition to xref:connections-snowflake-add.adoc#additional-configurations-create[Snowflake], we now support multiple configurations for xref:connections-databricks-add.adoc#additional-configurations-create[Databricks] and xref:connections-gbq-add.adoc#additional[Google BigQuery]. This feature allows you to allocate separate configurations for different ThoughtSpot users, groups, or processes, eliminating the need to duplicate Liveboards and configure multiple connections, and helping you with cost tracking and governance. You can also use this for your system processes so that you can control and balance the computing load.



////
[#it-ops-engineer-10-1-0-sw]
=== For the IT Ops Engineer
////
// Writer – SCALs (epic and doc).


[#developer-26-3-0-sw]
=== For the Developer

Customers licensed to embed ThoughtSpot can use ThoughtSpot Embedded features and Visual Embed SDK.

To enable ThoughtSpot Embedded on your cluster, contact {support-url}.

For information about ThoughtSpot Embedded, refer to  link:https://developers.thoughtspot.com/docs[ThoughtSpot Embedded Documentation, window=_blank].

[#upgrade-paths]
== Supported Upgrade Paths

If you are running one of the following versions, you can upgrade to the 26.3.0.sw release directly:

* 10.10.0.sw to 26.3.0.sw
* 10.1.0.sw to 26.3.0.sw

This includes any hotfixes or customer patches on these branches.

If you are running a different version, you must do a multiple pass upgrade.

First, upgrade to version 10.10.0.sw or 10.1.0.sw, and then to the 26.3.0.sw release.

NOTE: To successfully upgrade your ThoughtSpot cluster, all user profiles must include a valid email address. Without valid email addresses, the upgrade is blocked.
