= 7.1 Release Notes
:experimental:
:last_updated: 9/9/2021
:linkattrs:
:page-aliases: /release/notes.adoc, /7.0/release/notes.adoc, /7.0.0.CU1/release/notes.adoc, /7.0.1/release/notes.adoc, /7.0.0.mar.sw/release/notes.adoc


ThoughtSpot version 7.1 is now available as a limited availability release.

These release notes include information about new and enhanced features.

To see our feature deprecation plans, please see xref:deprecation.adoc[].

For a complete list of issues that we fixed in this release, see xref:fixed.adoc#releases-7-1-x[Fixed issues].

* <<new-7-1,7.1 New Features and Functionality>>
* <<upgrade-paths,Supported Upgrade Paths>>

NOTE: Self-service upgrade is not supported for upgrade to version 7.1.

[#new-7-1]
== 7.1 New Features and Functionality

For a complete list of issues that we fixed in this release, see xref:fixed.adoc#releases-7-1-x[Fixed issues].

Here are the most significant new features and improvements in the 7.1 Software Release:

* <<analyst-7-1,For the Analyst>>
* <<business-user-7-1,For the Business User>>
* <<data-engineer-7-1,For the Data Engineer>>
* <<it-ops-engineer-7-1,For the IT Ops Engineer>>

NOTE: All documentation for software embedding is now available only on the https://docs.thoughtspot.com/visual-embed-sdk/7.1/en/[ThoughtSpot Everywhere documentation^] site.

[#analyst-7-1]
=== For the Analyst

Scriptability::

+
- *TML for tables with row-level security*: ThoughtSpot now supports the migration and editing of tables with xref:security-rls-concept.adoc[row level security (RLS)] using xref:tml.adoc#syntax-tables[TML].
- *Scriptable worksheets with Search Assist Coach lessons*: You can now use TML to import, export, and update Worksheets with xref:search-assist-coach.adoc[] lessons. See xref:tml.adoc#syntax-worksheets[Syntax of the worksheet TML file].

Query filters::
Aggregate formulas now support in-line query filters. See xref:formulas-aggregation-flexible.adoc#query-filters[Query filters].

[#business-user-7-1]
=== For the Business User

[#deprecation]
Deprecations::
ThoughtSpot is dropping support for the following feature in the 7.1 release. This feature is *_not_* available in the 7.1 release:
+
- Instant Insights
+
Refer to xref:deprecation.adoc[Deprecation Announcements] for more information.

[#data-engineer-7-1]
=== For the Data Engineer

[#connections]
Connections:: ThoughtSpot has renamed Embrace to Connections. To access your connections, navigate to the *Data* tab and click *Connections*. For more information, see xref:connections.adoc[].
Databricks;; Connections now supports Databricks. For more information, see xref:connections-databricks.adoc[].
Starburst;; Connections now supports Starburst. For more information, see xref:connections-starburst.adoc[].

[#dataflow]
DataFlow::
We added support for the following databases: xref:dataflow-dremio.adoc[Dremio], xref:dataflow-google-sheets.adoc[Google Sheets], and xref:dataflow-vertica.adoc[Vertica].
+
DataFlow now automatically selects the options based on source file format, but you can overwrite it. For details, see xref:dataflow-files.adoc[Files].
When connecting to remote files, DataFlow now supports the XML and Avro file formats.

DataFlow Single Sign-On;; DataFlow now supports Single Sign-On (SSO). You can configure the Single Sign-On settings based on the SSO service used in your organization. Once configured, the user login authentication in ThoughtSpot and ThoughtSpot DataFlow is routed through the SSO service, and you do not need to maintain separate user credentials for ThoughtSpot DataFlow. See xref:dataflow-user-management-sso.adoc[] for details.
Case-sensitive table names;; DataFlow now supports case-sensitive table names. You can now create multiple syncs using different tables with the same name from the same connection and the same database.
Sync mode advanced settings;; For all DataFlow connections, the Sync mode available in the Sync properties tab now defaults to *Append*.
////
SQL Server type;; When setting up a SQL Server connection, you can now select one of three SQL server types: On-premise, Azure SQL database, and SQL Server on Cloud VM. For *On-Premise* and *SQL Server on Cloud VM*, select *Named Instance* to include the *Instance* field. For *Azure SQL Database*, select the *Azure AD User* checkbox to provide authentication details. See xref:dataflow-sql-server-reference.adoc[].
////
Salesforce drivers;; In this release, the Salesforce cdata JDBC jar in `agent/lib/jars/salesforce/xx/jdbc/cdata.jdbc.salesforce.jar` upgraded with the latest drivers.
//ThoughtSpot added new properties `BulkPageSize=2000` and `UseBulkAPI=true` in the JDBC URL.
Cassandra drivers;; The Cassandra JDBC jar in `agent/lib/jars/cassandra/3.x Jar: cdata.jdbc.cassandra.jar` location upgraded with the latest drivers.

Truncate table;; We removed this functionality because it is no longer necessary.

User management;; We removed user management from DataFlow; this function is now integrated with ThoughtSpot user management.

[#it-ops-engineer-7-1]
=== For the IT Ops Engineer

[#search-spotiq]
Manage advanced search and SpotIQ settings::
You can now manage advanced search and SpotIQ settings from the Admin Console. You can configure column indexing and enable or disable SpotIQ Analyze and column summaries. Refer to xref:admin-portal-search-spotiq-settings.adoc[Manage search and SpotIQ settings].

[#email-onboarding]
Manage email and onboarding settings::
You can manage certain advanced settings for your organization from the Admin Console. You can customize welcome emails, scheduled emails, and the workflow that allows users to sign up for ThoughtSpot from the login page. Refer to xref:admin-portal-onboarding-email-settings.adoc[Manage email and onboarding settings].

[#new-admin-privileges]
New admin privileges [.label.label-beta]#Beta#::
This release introduces new administrator privileges that separate the abilities of the administrator into 4 specific privileges. For example, you can allow certain users to create and manage users, while not allowing them to manage SAML integration or other advanced settings. These new administrator privileges do not provide access to all data in ThoughtSpot, unlike the *Can administer ThoughtSpot* privilege. Users with the new privileges can only see data that others share with them. The *Can administer ThoughtSpot* privilege, which encompasses all 4 new administrator privileges, still appears as an option by default. To remove it, xref:support-contact.adoc[contact ThoughtSpot Support]. The 4 new privileges are:
+
- *Can manage users*: Can create, delete, and edit users.
- *Can manage privileges*: Can create, delete, and edit groups. This includes the group's name, sharing visibility, and privileges.
- *Can operate application*: Can configure local and SAML authentication. Can manage application settings: search, SpotIQ, and onboarding advanced settings, style and help customization. Can view scheduled maintenance.
- *Can see system information*: Can view all default admin data, including system worksheets and pinboards.
+
This feature is in [.label.label-beta]#Beta# and off by default. To enable it, xref:support-contact.adoc[contact ThoughtSpot Support].

[#rhel]
RHEL ease of installation::
You can now configure a specific admin username for the user who sets up the nodes when deploying on RHEL. Previously, you had to use the default `admin` username, the `1081` uid, and the `1081` gid.
+
Refer to xref:rhel-install-online.adoc[] and xref:rhel-install-offline.adoc[].

[#saml-attribute]
SAML configuration::
When configuring SAML authentication for ThoughtSpot, you can now optionally map the display name subject value in the IDP metadata file to `displayName`. This ensures that your users' display names in SAML match their display names in ThoughtSpot. For more information, refer to xref:saml.adoc[].

[#ui-improvement]
UI improvement for Admin Console::
This release improves the UI and user experience of the xref:admin-portal-nas-mount-configure.adoc[NAS mount], xref:admin-portal-reverse-ssh-tunnel.adoc[Reverse SSH tunnel], xref:admin-portal-smtp-configure.adoc[SMTP], xref:admin-portal-snapshot-manage.adoc[Snapshot], xref:admin-portal-available-update.adoc[Upgrade], xref:admin-portal-scheduled-maintenance.adoc[Scheduled maintenance], and xref:admin-portal-ssl-configure.adoc[SSL] sections of the Admin Console.

[#product-usage-worksheet]
Product Usage worksheet::
This release introduces a new default worksheet for monitoring product usage. The Product Usage worksheet contains data on the following topics:
- Specifies what existing worksheets, tables, and views users search on and create objects from, and what those objects are
- Lists what actions users complete in the product
- Lists the underlying data sources for any object
- Lists any object's dependents

You can search on this worksheet, or create pinboards based on it, to monitor your users' interaction with the product. To access this worksheet, search for Product Usage worksheet from the Data tab, or add it as a source while searching data.

This worksheet is the underlying source for the xref:object-usage-pinboard.adoc[Object Usage pinboard].

[#upgrade-paths]
== Supported Upgrade Paths

If you are running one of the following versions, you can upgrade to the 7.1 release directly:

* 6.3.x to 7.1
* 7.0.x to 7.1

This includes any hotfixes or customer patches on these branches.

If you are running a different version, you must do a multiple pass upgrade.
First, upgrade to version 6.3.x, or 7.0.x, and then to the 7.1 release.

NOTE: To successfully upgrade your ThoughtSpot cluster, all user profiles must include a valid email address. Without valid email addresses, the upgrade is blocked.
