= 26.3.0.sw Release Notes
:experimental:
:last_updated: April 17, 2026
:linkattrs:
:page-aliases: /release/notes.adoc
:description: These release notes include information about new and enhanced features.
:jira: SCAL-251725, SCAL-264748

++++
<style>
.badge-update-whats-new-beta {
  font-style: normal !important;
  top: -0.03rem !important;
}

</style>
++++

ThoughtSpot version 26.3.0.sw is now available.

These release notes include information about new and enhanced features.

To see our feature deprecation plans, please see xref:deprecation.adoc[].

* <<upgrade-paths,Supported Upgrade Paths>>

[#new-26-3-0-sw]
== 26.3.0.sw New Features and Functionality

[#analyst-26-3-0-sw]
=== For the Analyst

// Mark. jira: SCAL-285343. docs jira: SCAL-285344
// PM: Manan
[#new-charts-powered]
New charts library [.badge.badge-early-access-relnotes]#Early Access#:: This release significantly upgrades ThoughtSpot visualization capabilities by introducing nine new, powerful native charts — Line, Column, Bar, Area, Line Column, Line Stacked Column, Stacked Column, Stacked Bar, and Stacked Area.
+
These new charts unlock sophisticated visualizations like faceted, cross-tabbed, multivariate, and bullet charts. They also resolve previous limitations by allowing multiple columns in Line Column charts and slicing by color with multiple measures, while providing deeper granular control over configurations such as tooltips, data labels, and axes.
To enable this feature, contact your administrator.
+
For more information, see xref:charts-library-new.adoc[ThoughtSpot's new charts].

// Mark. jira: SCAL-264868. docs jira: SCAL-287513
// PM: Manan
[#26-2-0-cl-chart]
New chart settings experience::
The new chart settings experience is now generally available (GA) and on by default. The chart settings panel is completely redesigned with a more intuitive layout and easier access. With over 50 advanced settings available across different chart types, you’ll have pixel-perfect control over every aspect of your visualizations - including data label sizes, colors, font styles, grid lines, tooltips, and more.
+
For more information, see
xref:charts-new.adoc[New chart settings experience].




// Rani. jira: SCAL-248189. docs jira: SCAL-257624
//Damian
[#rerun-queries]
Rerun queries in Search data::
This functionality allows users to execute the same search query again without needing to refresh the browser or modify the query, and update results with the latest data.
With this feature, users can simply click *Go* to rerun the query, which is useful for testing data model changes, formula updates, or database reloads.

For more information, see xref:search.adoc[Rerun your search query].

// Rani. Jira: SCAL-246727. Docs jira: SCAL-246727
//PM: Christina Yu
[#last-value]
Last value in period and first value in period functions::
`Last_value_in_period` and `first_value_in_period` functions are now available to all users and on by default. These functions are useful for semi-additive measures, measures that typically return a single value per time period rather than being additive across time. For example, if you want to find out the last value for full-time employee headcount for the current date, you can use the formula, `fxFTE = last_value_in_period(sum(full_time_employee), query_groups(), {date})`.
+
For more information, see xref:semi-additive-measures-period.adoc[Last_value_in_period and first_value_in_period functions].





[#business-user-26-3-0-sw]
=== For the Business User

// Naomi – jira: SCAL-265718. docs jira: SCAL-265719
// PM: Anshul Mehta
[#kpi-chart]
KPI chart settings [.badge.badge-early-access-relnotes]#Early Access#::
ThoughtSpot introduces more granular controls for KPI charts. You can now:
+
--
* Decide how missing dates are displayed (as gaps, ignored, or treated as 0).
* Specify whether to show or hide the current date, previous date, and previous value.

* Abbreviate previous month (PM) or previous quarter (PQ).

* Specify whether the measure’s increase or decrease is positive or negative.
--
+
To enable this feature, contact your administrator. For more information, see
xref:chart-kpi.adoc#advanced[KPI charts].

// Mark. jira: SCAL-271016. docs jira: SCAL-271017
// PM: Manan/Anshul
[#improved-chart]
Improved chart recommendations::

Improved chart recommendations are now generally available (GA) and on by default. When you search, ThoughtSpot can automatically suggest a chart type based on your search query. The following capabilities are improved:

* When you submit a query for the first time, ThoughtSpot analyzes the data and automatically selects the most appropriate chart.
* If you modify an existing query by adding or removing fields, ThoughtSpot retains the existing chart type unless it is forced to change.
* When you drill down into data, ThoughtSpot maintains the current chart type whenever possible.
+
For more information, see
xref:charts.adoc#chart-recs[Improved chart recommendations].

// Mark. jira: SCAL-260580. docs jira: SCAL-269159
// PM: Manan? Vaibhav? Is this feature only used in titles?
[#26-3-0-cl-dynamic]
Enhanced dynamic parameters in charts::
Enhanced dynamic parameters are now generally available (GA) and on by default. You can use parameters across axis names, column names, answer titles and descriptions to change these elements dynamically based on the parameter value. A parameter used in the title or description always displays the value of the same parameter used in the chart itself.
+
For more information, see
xref:charts.adoc#parameters[Parameters in axis and column names of charts and tables].




[#data-engineer-26-3-0-sw]
=== For the Data Engineer

// Naomi – Jira: SCAL-239719. docs jira: SCAL-270725
// PM: Damian.
[#column-security]
Column security rules [.badge.badge-early-access-relnotes]#Early Access#::

You can now set column security rules at the table level, and they will automatically be inherited to associated Models. Operational management is simplified as the cluster setting, Strict Object Mode, is not required. In addition, rules are only required for the secured columns rather than all columns in the table. For each column you select as restricted, you can define which group(s) can have access to the column. Users without access will not see the column in search results, or anywhere in the product. To enable this feature, contact your administrator.
+
For more information, see xref:security-data-object.adoc#csr[Column security rules].

// Mark. jira: SCAL-271228. docs jira: SCAL-271229
// PM: Manan, Anshul
[#26-2-0-cl-muze-studio]
Muze Studio::
Muze Studio is now generally available (GA) and on by default. You can create your own charts in ThoughtSpot using the Muze charting library. A developer can create new chart types by writing the code in the code builder. This release introduces a new console window which helps developers quickly identify and resolve issues with real-time feedback on their JavaScript code execution by providing errors and warnings generated during code execution.
+
For more information, see
xref:chart-create.adoc[Creating charts with Muze Studio].

// Naomi. jira: SCAL-261281. docs jira: SCAL-287514
// PM: Siddhant

[#liveboards-with]
Liveboards with column security rules [.badge.badge-early-access-relnotes]#Early Access#:: We have enhanced the behavior of Liveboards built with column security rules. If users restricted by column security access the Liveboard, they can see and interact with the Liveboard filters and visualizations, but cannot edit the Liveboard as a whole. If such inaccessible columns are used as filters in the Liveboard, the Liveboard will no longer be blocked. Schedules now honor column security rules, and each recipient receives their own report based on their column security rule assignments.
+
For more information, see xref:security-data-object.adoc#csr-liveboard[Column security rules on Liveboards].

// Rani – jira: SCAL-202857
//PM: Akshat Shah
[#tml-utility]
TML utility [.badge.badge-early-access-relnotes]#Early Access#:: The *Import TML* can now also be done asynchronously from the new TML utility. This allows users to trigger TML imports directly from the UI, which are processed as asynchronous jobs in the backend. You can enable this feature from the *Data modelling* option under *Application Settings* on the *Admin settings* page. Once enabled, you can access the new UI from the *Data workspace* > *Utilities* page.
+
For more information, see xref:scriptability.adoc#async-import[Async import TML utility]

// Rani. jira: SCAL-233681. docs jira: SCAL-242416
// PM: Damian
[#rls-support]
RLS support for integer comparison for ts_groups::
ThoughtSpot introduces a new system variable `ts_groups_int` for integer comparison in the row-level security configuration. This allows you to create RLS rules where an integer column is compared directly to the integer group IDs a user belongs to.
+
For more information, see
xref:security-rls-concept.adoc[Row-level security].

// Rani. jira: SCAL-263003. docs jira: SCAL-271538
// PM: Prayansh
[#connection-tml]
Connection TML import for OAuth without validation::
ThoughtSpot now supports importing OAuth connections through TML without validation. This feature allows users to import an OAuth connection via TML without performing validation during the import process.
+
For more information, see xref:tml-connections.adoc[TML for connections].

// Naomi. jira: SCAL-231120. docs jira: SCAL-268867
[#add-user]
Add user-defined ID (object ID) in TML:: You can now directly add or edit an object ID in the TML of an Answer, table, Model, Liveboard, or View. This user-defined object ID allows you to manage content across multiple Orgs without having to manually change the GUID of an object each time you move it between Orgs. To enable this feature, contact {support-url}.
+
For more information, see xref:tml.adoc#object-id[Object ID in TML files].


// Naomi – Jira ID: SCAL-251015. docs jira: SCAL-273076
// PM: Damian.
[#tenant-based]
Tenant-based column aliasing [.badge.badge-early-access-relnotes]#Early Access#::
Tenant-based column aliasing introduces the capability to define a column name or description based upon the user's membership in a ThoughtSpot Org or group. For example, Client 1 may refer to a column as Region, whilst Client 2 may refer to this as State. This feature is an extension of the language-based aliasing. Data analysts can define these aliases via CSV upload or with TML. This feature is particularly useful for embedded scenarios where the same underlying Model is leveraged across multiple clients.
+
For more information, see xref:column-aliases-tenant.adoc[Tenant-based column aliases].

// Naomi. jira: SCAL-241441. docs jira: SCAL-278562
// PM: Prayansh
[#csv-upload]
CSV upload support for Google BigQuery:: You now have a quick and easy way to complete data loads of files that are not present in your cloud data warehouse. You can now upload a CSV file to your Google BigQuery connection that can be joined to other tables in your connection. To use this feature, go to *Data* > *Utilities*, and click *Upload CSV*. To enable this feature, contact your administrator.
+
For more information, see xref:connections-gbq-csv-upload.adoc[Upload a CSV file to Google BigQuery].

// Naomi. jira: SCAL-241438 docs jira: SCAL-275547
// PM: Prayansh
[#databricks-csv]
Databricks CSV upload:: You now have a quick and easy way to complete data loads of files that are not present in your cloud data warehouse. You can now upload a CSV file to your Databricks connection that can be joined to other tables in your connection. To use this feature, go to *Data* > *Utilities*, and click *Upload CSV*.
+
For more information, see xref:connections-databricks-csv-upload.adoc[].

// Naomi. jira: SCAL-270846, docs jira: SCAL-270847
// PM: Prayansh
[#personal-access]
Personal Access Token (PAT) authentication for Snowflake:: We now support Personal Access Token authentication for Snowflake. For more information, see xref:connections-snowflake-add.adoc#pat[Add a Snowflake connection].

// Naomi. jira: SCAL-262993. docs jira: SCAL-267256.
// PM: Prayansh
[#oauth-client]
OAuth Client Credentials for Snowflake::

We now support OAuth Client Credentials authentication for Snowflake. For more information, see xref:connections-snowflake-add.adoc#client-credentials[Add a Snowflake connection] and xref:connections-snowflake-oauth-client.adoc[Snowflake OAuth with Client Credentials].

// Naomi. jira: SCAL-193108. docs jira: SCAL-262244
[#multiple-configurations]
Multiple configurations per connection:: In addition to xref:connections-snowflake-add.adoc#additional-configurations-create[Snowflake], we now support multiple configurations for xref:connections-databricks-add.adoc#additional-configurations-create[Databricks] and xref:connections-gbq-add.adoc#additional[Google BigQuery]. This feature allows you to allocate separate configurations for different ThoughtSpot users, groups, or processes, eliminating the need to duplicate Liveboards and configure multiple connections, and helping you with cost tracking and governance. You can also use this for your system processes so that you can control and balance the computing load.




[#it-ops-engineer-10-1-0-sw]
=== For the IT Ops Engineer

// Writer – SCALs (epic and doc).


[#developer-26-3-0-sw]
=== For the Developer

Customers licensed to embed ThoughtSpot can use ThoughtSpot Embedded features and Visual Embed SDK.

To enable ThoughtSpot Embedded on your cluster, contact {support-url}.

For information about ThoughtSpot Embedded, refer to  link:https://developers.thoughtspot.com/docs[ThoughtSpot Embedded Documentation, window=_blank].

[#upgrade-paths]
== Supported Upgrade Paths

If you are running one of the following versions, you can upgrade to the 26.3.0.sw release directly:

* 10.10.0.sw to 26.3.0.sw
* 10.1.0.sw to 26.3.0.sw

This includes any hotfixes or customer patches on these branches.

If you are running a different version, you must do a multiple pass upgrade.

First, upgrade to version 10.10.0.sw or 10.1.0.sw, and then to the 26.3.0.sw release.

NOTE: To successfully upgrade your ThoughtSpot cluster, all user profiles must include a valid email address. Without valid email addresses, the upgrade is blocked.
