= Orgs administration
:last_updated: 9/23/2022
:linkattrs:
:experimental:
:description: Learn how to administer your Orgs-enabled, multi-tenant ThoughtSpot instance.



include::partial$org-intro.adoc[]

This article is an overview of the administrative tasks required of the administrators of an Orgs-enabled ThoughtSpot cluster.

WARNING: After you enable the Orgs feature on a cluster, you can’t turn off the ability to create Orgs. However, your environment remains a single-tenant environment until you create an Org. You can also delete all the Orgs you created, and just use the Primary Org, if you would like a single-tenant environment with Orgs enabled.

== Cluster administrators and Org administrators

include::partial$org-admin.adoc[]

include::partial$org-create-manage.adoc[]

include::partial$all-org-scope.adoc[]

[#users-groups]
== Manage users and groups

include::partial$org-users-groups.adoc[]

=== Add users to Orgs
The cluster administrator can add a user to multiple Orgs at a time as the cluster administrator, or add a user to one specific Org as that Org’s administrator.

To add a user to multiple Orgs at a time, you must be in the Primary Org, in the *All orgs > Users* section of the Admin Console.

You should only use the *All orgs > Users* section of the Admin Console to add users to multiple Orgs. Use the individual Org's *Admin Console > Users* section to add users to individual Orgs, and to add users to groups.

For more information about creating users, see xref:user-management-orgs.adoc[Create, edit, or delete a user in a multi-tenant environment].

NOTE: Usernames must be unique across the cluster, not just the Org.

=== Remove users from Orgs
You can remove a user from multiple Orgs at a time as the cluster administrator, or remove a user from one specific Org as that Org’s administrator.

To remove a user from multiple Orgs at a time, the cluster administrator must be in the Primary Org, in the *All orgs > Users* section of the Admin Console.

For more information about deleting users, see xref:user-management-orgs.adoc[Create, edit, or delete a user in a multi-tenant environment].

=== Manage groups in Orgs
You can only add, modify, and delete groups at the individual Org level. You cannot add, modify, or delete  groups for multiple Orgs at a time.

For more information about managing groups, see xref:group-management-orgs.adoc[Create, edit, or delete a group in a multi-tenant environment].

NOTE: Group names must be unique across the cluster, not just the Org.

[#authentication]
== User authentication

You manage user authentication at the *All orgs* level of the Admin Console. You cannot manage or configure SAML or local user authentication to work in different ways for different Orgs in the same cluster.

For more information about SAML and local user authentication, refer to xref:authentication-integration.adoc[Managing authentication with SAML] and xref:authentication-local.adoc[Managing local authentication].

NOTE: ThoughtSpot does not support xref:oidc-configure.adoc[OpenID Connect] integration for authentication in an Orgs environment.

== Application settings

You manage application settings, such as search and SpotIQ settings, email and onboarding settings, and style customization, at the *All orgs* level of the Admin Console. You cannot configure these features to work in different ways for different Orgs in the same cluster.

For more information about application settings, refer to xref:search-spotiq-settings.adoc[Managing search and SpotIQ settings], xref:onboarding-email-settings.adoc[Managing email and onboarding settings], and xref:style-customization.adoc[Style customization].

== View and analyze user, performance and billing information

You can view and analyze system Liveboards about user adoption, app performance, and credit usage at the *All orgs* level of the Admin Console. These Liveboards are applicable to the entire cluster, but you can filter them by Org to view data specific to each Org.

For more information about these system Liveboards, refer to xref:user-adoption.adoc[User Adoption Liveboard], xref:performance-tracking.adoc[Performance Tracking Liveboard], and xref:consumption-pricing-time-based.adoc#credit-usage-pinboard[Credit Usage Liveboard].

== View status of and sign the ThoughtSpot user agreement
You sign the ThoughtSpot user agreement for the entire cluster. You do not need to sign it for each Org. You can sign the revised user agreement or view the currently signed  user agreement for your cluster from the *All Orgs > Terms*  section of the Admin Console.


'''
> **Related information**
>
> * xref:user-management-orgs.adoc[]
> * xref:group-management-orgs.adoc[]
> * xref:admin-console-orgs.adoc[]