= Network ports
:last_updated: 8/26/2020
:page-aliases: /admin/setup/firewall-ports.adoc, /appliance/firewall-ports.adoc
:experimental:
:linkattrs:


For regular operations and for debugging, there are some ports you must keep open to network traffic from end users.
Another, larger list of ports must be kept open for network traffic between the nodes in the cluster.

NOTE: This article summarizes the list of ports, both required and optional, for regular operations of ThoughtSpot. Optional ports appear at the end of each list.

include::partial$ports/end-user.adoc[]

include::partial$ports/admin.adoc[]

include::partial$ports/cluster-access.adoc[]

include::partial$ports/ipmi.adoc[]

include::partial$ports/intracluster.adoc[]

'''
> **Related information**
>
> * xref:cable-networking.adoc[Cable reference]
> * xref:nodesconfig-example.adoc[The nodes.config file]
> * xref:parameters-nodesconfig.adoc[Parameters of the nodes.config file]
> * xref:cluster-create.adoc[Using the tscli cluster create command]
> * xref:parameters-cluster-create.adoc[Parameters of the tscli cluster create command]