= Upgrade your Python version
:last_updated: 4/26/2022
:linkattrs:
:experimental:
:description: If you are on ThoughtSpot-managed CentOS hosted on AWS, Azure, or GCP, your ThoughtSpot cluster comes with Python 3.9 by default.

If you are on ThoughtSpot-managed CentOS hosted on AWS, Azure, or GCP, your ThoughtSpot cluster comes with Python 3.9 by default. You do *_not_* need to upgrade your Python version; ThoughtSpot does not support any Python version other than Python 3.9 for ThoughtSpot-managed CentOS clusters hosted on AWS, Azure, or GCP that are on 8.4.1.sw.

If you are on customer-managed RHEL or customer-managed OEL, or ThoughtSpot-managed CentOS hosted on VMware, SMC, or Dell, Python 3.6 is still the default version. If you are on customer-managed Amazon Linux 2, Python 3.7 is still the default version. If you are on customer-managed RHEL or Amazon Linux 2, you can upgrade to Python 3.9.

[#supported-versions]
== Supported Python versions
ThoughtSpot supports use of the following versions of Python 3 for deployment. Python 3.7 is the current default version for customer-managed Amazon Linux 2. Python 3.9 is the default version for ThoughtSpot-managed CentOS hosted on AWS, Azure, and GCP. Python 3.6 is the default version for customer-managed RHEL, customer-managed OEL, and ThoughtSpot-managed CentOS hosted on VMware, SMC, and Dell.

* Python 3.6: ThoughtSpot-managed CentOS for AWS, GCP, VMware, Azure, SMC, and Dell; customer-managed xref:rhel.adoc[RedHat Enterprise Linux (RHEL)]; customer-managed xref:rhel.adoc[Oracle Enterprise Linux (OEL)]; customer-managed xref:al2.adoc[Amazon Linux 2]
* Python 3.7: customer-managed Amazon Linux 2
* Python 3.9: ThoughtSpot-managed CentOS for AWS, GCP, and Azure; customer-managed xref:rhel.adoc[RedHat Enterprise Linux (RHEL)]; customer-managed xref:al2.adoc[Amazon Linux 2]

== Upgrade your Python version
After you create the cluster, upgrade your Python version to Python 3.9.

To upgrade your Python version, follow these steps:

. `ssh` into a node as an admin user.
+
----
ssh admin@<node-IP>
----

. Run the following command to stop your cluster:
+
----
tscli cluster stop
----

. Ensure that the version of Python you want to use is <<supported-versions,ThoughtSpot-certified>> for your deployment type. ThoughtSpot does *_NOT_* certify Python 3.9 for customer-managed OEL or ThoughtSpot-managed CentOS for VMware, SMC, or Dell.
. Install Python version 3.9.
. Navigate to the correct location to run the command:
+
----
cd /usr/local/scaligent/release/
----
. Run the following command on all nodes, at `/usr/local/scaligent/release/` for each node:
+
----
PATH=/usr/pgsql-11/bin:$PATH pip3 install -r production/prod_image/current/pip_packages/requirements_no_versions.txt --upgrade
----
. Run the following command to start your cluster again:
+
----
tscli cluster start
----
