= Delete a relationship
:last_updated: 02/01/2021
:linkattrs:
:experimental:
:page-partial:
:page-aliases: /admin/data-modeling/delete-relationship.adoc
:description: Learn to delete a relationship (join or link) using the web interface or TQL.

You must have either the xref:groups-privileges.adoc[*Can administer ThoughtSpot* or the *Can manage data* privilege] to delete a relationship.
If you're not an administrator, you also need edit permissions on the table, view, or worksheet.

If you created a relationship (join or link) between tables using the web interface, you can also delete it from the web interface.
But if the relationship was created using TQL, you must also use TQL to delete it.

xref:schema-change.adoc[To delete a relationship using TQL], use an `+ALTER TABLE...DROP CONSTRAINT...+` or `+ALTER TABLE...DROP RELATIONSHIP...+` statement.

To delete a relationship from the web interface:

. Select *Data* on the top navigation bar.
. Select the name of the data source you from which you want to remove the relationship.
. Select *Joins*.
+
The list of existing joins appears.
+
In a worksheet, you must select *Joins within this worksheet* and choose *Joins from this worksheet*.

. Find the relationship you want to delete, and select the delete icon. The *Confirm delete* window appears.
+
If the join has dependents, a different window appears, warning you that deleting this join makes the dependent objects stop working until you recreate the join later. However, ThoughtSpot doesn't delete the dependent objects. You can use this functionality to xref:relationship-create.adoc#change-cardinality[reverse the join cardinality] or otherwise edit a join without deleting its dependents.
. Repeat these steps until all the joins you want to remove have been deleted.

'''
> **Related information**
>
> * xref:constraints.adoc[Constraints]
