= Packages installed with ThoughtSpot for RHEL and OEL
:last_updated: 8/6/2021
:linkattrs:
:experimental:

To successfully deploy ThoughtSpot in your organization, you must have the following packages on each node of your ThoughtSpot cluster: <<yum,yum>>, <<pip,python 3>>, and <<r,R>>.
When the Ansible playbook runs, it automatically installs them.

ThoughtSpot works with the latest version of each package;
see the minimum supported version.

[#yum]
[#pip]
[#r]
[tabset]
====
Yum RPM packages for 7.1;;
+
--
Download: link:{attachmentsdir}/yum-rpm-packages-rhel-71.csv[Yum RPM package list].

include::partial$/packages/yum-rpm-packages-rhel-71.adoc[]
--
Yum RPM packages for 7.1.1;;
+
--
Download: link:{attachmentsdir}/yum-rpm-packages-rhel.csv[Yum RPM package list].

include::partial$/packages/yum-rpm-packages-rhel.adoc[]
--
Python 3 packages for 7.1;;
+
--
Download: link:{attachmentsdir}/pip-rpm-packages-71.csv[Python RPM package list].

include::partial$/packages/pip-rpm-packages-71.adoc[]
--
Python 3 packages for 7.1.1;;
+
--
Download: link:{attachmentsdir}/pip-rpm-packages.csv[Python RPM package list].

include::partial$/packages/pip-rpm-packages.adoc[]
--
R packages for 7.1;;
+
--
Download: link:{attachmentsdir}/r-rpm-packages-rhel-71.csv[R RPM package list].

include::partial$/packages/r-rpm-packages-rhel-71.adoc[]
--
R packages for 7.1.1;;
+
--
Download: link:{attachmentsdir}/r-rpm-packages-rhel.csv[R RPM package list].

include::partial$/packages/r-rpm-packages-rhel.adoc[]
--
====
