= RHEL deployment overview
:last_updated: 7/22/2020

Run ThoughtSpot on your own internally managed RedHat Enterprise Linux (RHEL) 7.7 or 7.8 image.

Starting with Release 6.0.4, you have the flexibility to run ThoughtSpot on an RHEL image that your organization manages internally. This enables your organization to manage the OS and perform SysAdmin tasks.

In Release 6.0.5, ThoughtSpot runs on RHEL 7.7 or RHEL 7.8.

ThoughtSpot certifies RHEL on the following platforms:

* Bare metal deployments on the two ThoughtSpot-certified hardware appliances: xref:installing-dell.adoc[DELL] and xref:installing-the-smc.adoc[SMC]
* Cloud deployments: xref:configuration-options-aws.adoc[Amazon Web Services (AWS) EC2], xref:configuration-options-azure.adoc[Microsoft Azure], and xref:configuration-options-gcp.adoc[Google Cloud Platform (GCP)]
* xref:vmware-intro.adoc[VMware]

Follow these steps to deploy ThoughtSpot through RHEL:

[cols="5%,95%"]
|===
| &#10063;
| xref:rhel-prerequisites.adoc[Complete installation prerequisites]

| &#10063;
| xref:rhel-ts-artifacts.adoc[Get ThoughtSpot artifacts]

| &#10063;
| xref:rhel-install-online.adoc[Install ThoughtSpot in RHEL online clusters], or

xref:rhel-install-offline.adoc[Install ThoughtSpot in RHEL offline clusters]
|===

Additionally, learn how you can:

* xref:rhel-upgrade.adoc[Upgrade ThoughtSpot for RHEL to a new release]
* xref:rhel-add-node.adoc[Add a new node to an existing ThoughtSpot cluster in RHEL]

Finally, to see what additional 3rd-party RPM packages your ThoughtSpot installation includes by default, see xref:rhel-packages.adoc[Packages installed with ThoughtSpot for RHEL].
