= ThoughtSpot deployment artifacts for RHEL and OEL
:last_updated: 8/6/2021
:experimental:
:page-aliases: /appliance/rhel/rhel-ts-artifacts.adoc
:linkattrs:

Get the two primary tarball artifacts for configuring ThoughtSpot using RHEL.

include::partial$ts-artifacts-customer-os.adoc[]

== Next steps

Next, proceed to install:

* xref:rhel-install-online.adoc[install ThoughtSpot in RHEL online clusters], where the hosts can connect to the public repositories to download the required packages
* xref:rhel-install-offline.adoc[install ThoughtSpot in RHEL offline clusters], where the hosts cannot connect to the public repositories to download the required packages

'''
> **Related information**
>
> * xref:rhel-prerequisites.adoc[RHEL and OEL prerequisites]
> * xref:rhel-install-online.adoc[Online RHEL and OEL install]
> * xref:rhel-install-offline.adoc[Offline RHEL and OEL install]
> * xref:rhel-upgrade.adoc[RHEL and OEL upgrade]
> * xref:rhel-add-node.adoc[Add new nodes to clusters on RHEL or OEL]
> * xref:rhel-packages.adoc[Packages installed with RHEL and OEL]