= Delete ThoughtSpot clusters using ansible on clusters that use RHEL
:last_updated: 12/8/2022
:author: Teresa Killmond
:linkattrs:
:experimental:
:description: Delete ThoughtSpot clusters using ansible on RHEL clusters.

If your organization requires that privilege escalation take place through an external tool that integrates with ansible, follow the steps in this article to delete your cluster.

Before deleting the cluster, ensure that the xref:rhel-install-ansible.adoc#system-settings[system settings] are correctly configured.

== Upgrading the cluster

. Rename *cluster_hosts.sample* to *cluster_hosts.yaml*.
. Update the ansible vars in *cluster_hosts.yaml* with your own specific values. See <<ansible-vars,Sample ansible vars>>.
. Run the ansible-playbook. This upgrades the cluster. Run the following command on any cluster node:
+
[source,bash]
----
ansible-playbook -i cluster_hosts.yaml cluster_delete.yaml
----
+
If privilege escalation requires a password, add the `-K` option to the `ansible-playbook` command.
. If there is a failure at any point, fix the failure and rerun the `ansible-playbook` command. Bypass the completed steps using the `--start-at-task` option, specifying the task at which to start.

[#ansible-vars]
=== Sample ansible vars

This is the definition of the *cluster_hosts.sample* file that is present in your ansible tarball. You must replace anything in this file within `<>` with your own specific information.

[source,bash]
----
all:
  hosts:
    # List of IPs of the nodes in the cluster>
    <node_ip1>:
    <node_ip2>:
  vars:
    ssh_user: <ts_service_user>
    ansible_ssh_user: <ts_service_user>
    username: <ts_service_user>
    groupname: <ts_service_group>
    env: {}
    ssh_private_key: <Private key  for ssh>
    keep_release: False  # Set to true if you do not want to delete the release.
    keep_dr_mirror: False
    DATA_DRIVE_SCRIPT: "/usr/local/scaligent/release/build-out/production/install/select_data_drives_tool.par"
----

'''
> **Related information**
>
> * xref:rhel-install-ansible.adoc[Creating a cluster]
> * xref:rhel-restore-ansible.adoc[Restoring a cluster]
> * xref:rhel-start-stop-ansible.adoc#start[Starting a cluster]
> * xref:rhel-start-stop-ansible.adoc#stop[Stopping a cluster]
> * xref:rhel-upgrade-ansible.adoc[Upgrading a cluster]
> * xref:rhel-add-node-ansible.adoc[Adding a node to a cluster]
