= Restore ThoughtSpot using ansible on clusters that use RHEL
:last_updated: 12/8/2022
:author: Teresa Killmond
:linkattrs:
:experimental:
:description: Restore ThoughtSpot using ansible on RHEL clusters.

If your organization requires that privilege escalation take place through an external tool that integrates with ansible, follow the steps in this article to restore your cluster.

Before restoring the cluster, ensure that the xref:rhel-install-ansible.adoc#system-settings[system settings] are correctly configured.

== Restore the cluster

. Rename *cluster_create_hosts.sample* to *cluster_create_hosts.yaml*.
. Update the ansible vars in *cluster_create_hosts.yaml* with your own specific values. See <<ansible-vars,Sample ansible vars>>.
. Run the ansible-playbook. This restores the cluster. Run the following command on any cluster node:
+
[source,bash]
----
ansible-playbook -i cluster_create_hosts.yaml ts-cluster-create-full-flow.yaml
----
+
If privilege escalation requires a password, add the `-K` option to the `ansible-playbook` command.
. If there is a failure at any point, fix the failure and rerun the `ansible-playbook` command. Bypass the completed steps using the `--start-at-task` option, specifying the task at which to start.

[#ansible-vars]
=== Sample ansible vars

This is the definition of the *cluster_create_hosts.sample* file that is present in your ansible tarball. You must replace anything in this file within `<>` with your own specific information.

[source,bash]
----
all:
  hosts:
    # List of IPs of the nodes in the cluster>
    <node_ip1>:
    <node_ip2>:
  vars:
    ssh_user: <ts_service_user>
    username: <ts_service_user>
    groupname: <ts_service_group>
    env: {}
    ssh_private_key: <Private key for ssh>
    cluster_id: <Cluster ID. Provided by ThoughtSpot.>
    cluster_name: <Cluster name>
    backupdir: <location of backup>
    ramdisk_size: 50619136k
   operation: RESTORE
    # ThoughtSpot variables. Do not modify.
    release_location: /export/releases/root/
    installer_spec_path: /usr/local/scaligent/install/install_config
    pgversion: 11
    layout_file: /tmp/hadoop_config.json
    no_sudo: 1
    minimal_sudo_install: 1
    offline: 1
    skip_r: 1
    skip_local_user_creation: 1
----

'''
> **Related information**
>
> * xref:rhel-install-ansible.adoc[Creating a cluster]
> * xref:rhel-start-stop-ansible.adoc#start[Starting a cluster]
> * xref:rhel-start-stop-ansible.adoc#stop[Stopping a cluster]
> * xref:rhel-upgrade-ansible.adoc[Upgrading a cluster]
> * xref:rhel-add-node-ansible.adoc[Adding a node to a cluster]
> * xref:rhel-delete-ansible.adoc[Deleting a cluster]