= Upgrading ThoughtSpot for RHEL
:last_updated: 11/16/2020
:experimental:
:linkattrs:

To upgrade your RHEL installation of ThoughtSpot, follow these steps:

[cols="5,~",grid=none,frame=none]
|===
| &#10063; | Step 1. Back up your ThoughtSpot cluster.
| &#10063; | Step 2. Pull the necessary security updates.
| &#10063; | Step 3. Download the release tarball to each cluster (for online clusters) or to your organization's mirror repository (for offline clusters).
| &#10063; | Step 4. For offline clusters, run the `run_offline.sh` script from the Ansible tarball.
| &#10063; | Step 5. Run the `tscli cluster update` command.
|===

'''
> **Related information**
>
> * xref:rhel-prerequisites.adoc[RHEL prerequisites]
> * xref:rhel-ts-artifacts.adoc[ThoughtSpot deployment artifacts for RHEL]
> * xref:rhel-install-online.adoc[Online RHEL install]
> * xref:rhel-install-offline.adoc[Offline RHEL install]
> * xref:rhel-add-node.adoc[Add new nodes to clusters on RHEL]
> * xref:rhel-packages.adoc[Packages installed with RHEL]