= Start or stop ThoughtSpot using ansible on clusters that use RHEL
:last_updated: 12/8/2022
:author: Teresa Killmond
:linkattrs:
:experimental:
:description: Start or stop ThoughtSpot using ansible on RHEL clusters.

If your organization requires that privilege escalation take place through an external tool that integrates with ansible, follow the steps in this article to start or stop your cluster.

Before starting or stopping the cluster, ensure that the xref:rhel-install-ansible.adoc#system-settings[system settings] are correctly configured.

[#start]
== Start the cluster

. Rename *cluster_hosts.sample* to *cluster_hosts.yaml*.
. Update the ansible vars in *cluster_hosts.yaml* with your own specific values. See <<ansible-vars-start,Sample ansible vars>>.
. Run the ansible-playbook. This starts the cluster. Run the following command on any cluster node:
+
[source,bash]
----
ansible-playbook -i cluster_hosts.yaml cluster_start.yaml
----
+
If privilege escalation requires a password, add the `-K` option to the `ansible-playbook` command.
. If there is a failure at any point, fix the failure and rerun the `ansible-playbook` command. Bypass the completed steps using the `--start-at-task` option, specifying the task at which to start.

[#ansible-vars-start]
=== Sample ansible vars

This is the definition of the *cluster_hosts.sample* file that is present in your ansible tarball. You must replace anything in this file within `<>` with your own specific information.

[source,bash]
----
all:
  hosts:
    # List of IPs of the nodes in the cluster>
    <node_ip1>:
    <node_ip2>:
  vars:
    ssh_user: <ts_service_user>
    ansible_ssh_user: <ts_service_user>
    username: <ts_service_user>
    groupname: <ts_service_group>
    env: {}
    ssh_private_key: <Private key for ssh>

----

[#stop]
== Stop the cluster

. Rename *cluster_hosts.sample* to *cluster_hosts.yaml*.
. Update the ansible vars in *cluster_create_hosts.yaml* with your own specific values. See <<ansible-vars-stop,Sample ansible vars>>.
. Run the ansible-playbook. This stops the cluster. Run the following command on any cluster node:
+
[source,bash]
----
ansible-playbook -i cluster_hosts.yaml cluster_stop.yaml
----
+
If privilege escalation requires a password, add the `-K` option to the `ansible-playbook` command.
. If there is a failure at any point, fix the failure and rerun the `ansible-playbook` command. Bypass the completed steps using the `--start-at-task` option, specifying the task at which to start.

[#ansible-vars-stop]
=== Sample ansible vars

This is the definition of the *cluster_hosts.sample* file that is present in your ansible tarball. You must replace anything in this file within `<>` with your own specific information.

[source,bash]
----
all:
  hosts:
    # List of IPs of the nodes in the cluster>
    <node_ip1>:
    <node_ip2>:
  vars:
    ssh_user: <ts_service_user>
    ansible_ssh_user: <ts_service_user>
    username: <ts_service_user>
    groupname: <ts_service_group>
    env: {}
    ssh_private_key: <Private key for ssh>
----

'''
> **Related information**
>
> * xref:rhel-install-ansible.adoc[Creating a cluster]
> * xref:rhel-restore-ansible.adoc[Restoring a cluster]
> * xref:rhel-upgrade-ansible.adoc[Upgrading a cluster]
> * xref:rhel-add-node-ansible.adoc[Adding a node to a cluster]
> * xref:rhel-delete-ansible.adoc[Deleting a cluster]
