= Packages installed with ThoughtSpot for RHEL and OEL
:last_updated: 8/6/2021
:linkattrs:
:experimental:
:description: To successfully deploy ThoughtSpot, you must have the following packages on each node of your ThoughtSpot cluster: yum, python 3, and R.

To successfully deploy ThoughtSpot in your organization, you must have the following packages on each node of your ThoughtSpot cluster: <<yum,yum>>, <<pip,python 3>>, and <<r,R>>. ThoughtSpot does not install the R packages if you define the xref:rhel-install-online.adoc#skip_r[skip_r] flag in the Ansible playbook.
When the Ansible playbook runs, it automatically installs them.

ThoughtSpot also uses the third-party software packages listed in xref:third-party.adoc[].

NOTE: If your organization requires that privilege escalation take place through an external tool that integrates with Ansible, you must install the packages yourself. The Ansible playbook does not install them. Refer to xref:rhel-install-ansible.adoc[].

[#yum]
[#pip]
[#r]
[tabset]
====
Yum RPM packages for RHEL 7.8 and 7.9 and OEL 7.9;;
+
--
Download: link:{attachmentsdir}/yum-rpm-packages-rhel.csv[Yum RPM package list for RHEL 7.8 and 7.9 and OEL 7.9].

include::partial$/packages/yum-rpm-packages-rhel.adoc[]
--
Yum RPM packages for RHEL 8.1 - 8.7;;
+
--
Download: link:{attachmentsdir}/yum-rpm-packages-rhel-8.csv[Yum RPM package list for RHEL 8.1 - 8.7].

include::partial$/packages/yum-rpm-packages-rhel-8.adoc[]
--
Python 3 packages;;
+
--
Download: link:{attachmentsdir}/pip-rpm-packages.csv[Python RPM package list].

include::partial$/packages/pip-rpm-packages.adoc[]
--
R packages;;
+
ThoughtSpot does not install the R packages if you define the xref:rhel-install-online.adoc#skip_r[skip_r] flag in the Ansible playbook.
+
--
Download: link:{attachmentsdir}/r-rpm-packages-rhel.csv[R RPM package list].

include::partial$/packages/r-rpm-packages-rhel.adoc[]
--
====

'''
> **Related information**
>
> * xref:rhel-prerequisites.adoc[RHEL and OEL prerequisites]
> * xref:rhel-ts-artifacts.adoc[ThoughtSpot deployment artifacts for RHEL and OEL]
> * xref:rhel-install-online.adoc[Online RHEL and OEL install]
> * xref:rhel-install-offline.adoc[Offline RHEL and OEL install]
> * xref:rhel-upgrade.adoc[RHEL and OEL upgrade]
> * xref:rhel-add-node.adoc[Add new nodes to clusters on RHEL or OEL]
> * xref:rhel-ansible.adoc[]