= RHEL and OEL installation prerequisites
:last_updated: 2/18/2022
:linkattrs:
:page-aliases: /appliance/rhel/rhel-prerequisites.adoc
:experimenal:

Prepare the system and ThoughtSpot clusters for installation:

[cols="5,~",grid=none,frame=none]
|===
| &#10063; | xref:set-up-hosts[1. Set up hosts for the ThoughtSpot cluster]
| &#10063; | xref:partition-hosts[2. Partition the hosts]
| &#10063; | xref:install-rhel[3. Install RHEL version 7.8, 7.9, 8.1, 8.2, 8.3, 8.4, or 8.5 or OEL version 7.9 on all hosts]
| &#10063; | xref:linux-kernel-version[4. Ensure that your Linux kernel is correct]
| &#10063; | xref:enable-hosts[5. Enable the hosts to download RHEL or OEL packages]
| &#10063; | xref:tmp-permission[6. Ensure tmp has permission 777 or 1777]
| &#10063; | xref:cgroups[7. Ensure that you are using Linux cgroupsV1]
| &#10063; | xref:proc[8. Ensure /proc mount point flags are compatible]
| &#10063; | xref:etc-sudoers[9. Remove Defaults requiretty from /etc/sudoers]
| &#10063; | xref:selinux[(RHEL 8 only) 10. Remove the selinux policy for rsync]
| &#10063; | xref:enable-ansible[ (Optional) Enable an Ansible Control Server]
|===

[#set-up-hosts]
== Set up hosts for the ThoughtSpot cluster

Set up hosts for the ThoughtSpot cluster on your chosen platform.
Please refer to the relevant deployment sections in our documentation for the exact specification for the hosts: CPU, memory, and disks.

* [*_RHEL 7 only_*] ThoughtSpot-certified hardware appliance manufactured by xref:dell.adoc[DELL]
* [*_RHEL 7 only_*] ThoughtSpot-certified hardware appliance manufactured by xref:smc.adoc[SMC]
* [*_RHEL 7 or 8 or OEL_*] xref:aws-configuration-options.adoc[Amazon Web Services (AWS) EC2]
* [*_RHEL 7 or OEL_*] xref:gcp-configuration-options.adoc[Google Cloud Platform (GCP)]
* [*_RHEL 7 only_*] xref:azure-configuration-options.adoc[Microsoft Azure]
* [*_RHEL 7 or 8 or OEL_*] xref:vmware.adoc[VMware]

[#partition-hosts]
== Partition the hosts

Ensure that all ThoughtSpot hosts meet the following partition and sizing requirements.
All drives must be SSDs.

Do not partition the data drives. ThoughtSpot partitions the data drives during installation. For information about data drive specifications, refer to the intro articles for each platform linked in the <<set-up-hosts,set up hosts>> section of this article.


[cols="15,85",options="header"]
|===
| Path | Required free space

| /
| 20 GB. This is the root drive.

| /tmp
| 50 GB

| /export
| 200 GB, on a separate filesystem
|===


NOTE: For ThoughtSpot-certified hardware platforms, xref:dell.adoc[Dell] and xref:smc.adoc[Super Micro Computer], you must use a secondary drive rather than a partition, because the root drive has a limit of 200 GB. This drive must be separate from the data drive(s).

[#install-rhel]
== Install RHEL or OEL on hosts

ThoughtSpot is certified with RHEL versions 7.8, 7.9, 8.1, 8.2, 8.3, 8.4, and 8.5;
we *do not* support other versions of RHEL, including 7.7 and 8.
ThoughtSpot is certified with OEL version 7.9. Install RHEL version 7.8, 7.9, 8.1, 8.2, 8.3, 8.4, or 8.5, or OEL version 7.9.

On RHEL version 7.8, ensure that your <<#linux-kernel-version,linux kernel version>> is 3.10.0-1127.19.1 or higher. On all other supported RHEL versions, use the default linux kernel. On OEL version 7.9, ensure that you are using the Red Hat Compatible Kernel (RHCK), not the default Unbreakable Enterprise Kernel (UEK). If you are using the UEK, contact {support-url} to switch to the RHCK.

NOTE: For RHEL deployments on online clusters, the Ansible playbook upgrades the OS to the latest supported version of RHEL. The Ansible playbook does *not* upgrade the OS when installing offline.

[#linux-kernel-version]
=== Linux kernel version

For RHEL version 7.8, your Linux kernel *_must_* be on version 3.10.0-1127.19.1 or higher.
RHEL 7.8 used to come with a Linux kernel of version 3.10.x, which has a bug that causes nodes to reboot unexpectedly.
The default Linux kernel version for RHEL 7.8 is now 3.10.0-1127.19.1.
However, you may have an older RHEL 7.8, with a Linux kernel of version 3.10.x.
You must upgrade to 3.10.0-1127.19.1 or higher.
If you have trouble upgrading your Linux kernel to version 3.10.0-1127.19.1 or higher, contact {support-url}.
This is a requirement for *all* platforms: hardware appliance, cloud, and VMware.

If you are using any other supported RHEL version, use the default Linux kernel.

On OEL version 7.9, ensure that you are using the Red Hat Compatible Kernel (RHCK), not the default Unbreakable Enterprise Kernel (UEK). If you are using the UEK, contact {support-url} to switch to the RHCK.

WARNING: If you are running RHEL 7.8, and your Linux kernel version is not 3.10.0-1127.19.1 or higher, you may run into unexpected node reboots and possible loss of data.

[#enable-hosts]
== Enable the hosts to download RHEL or OEL packages

*Repositories*

[#yum-repository]
Yum repositories for RHEL 7::
You must enable the following Yum repositories in your cluster: +
`epel`, `pgdg11`, `rhel`, `rhel-optional`, `rhel-extras`.

Yum repositories for RHEL 8::
You must enable the following Yum repositories in your cluster: +
`epel`, `pgdg11`, `baseos`, `codeready`, `appstream`.

Yum repositories for OEL::
  You must enable the following Yum repositories in your cluster: +
  `epel`, `pgdg95`, `pgdg11`, `ol7_optional_latest`, `oracle-linux-ol7`.

[#python-repository]
Python repository::
  For Python, ensure the machine is able to reach the `PyPI` repository located at https://pypi.python.org/.

[#r-repository]
R repository::
  For R, ensure the machine is able to reach the `CRAN` repository located at https://cran.rstudio.com/.

Make sure that you can download RHEL or OEL packages to all hosts, either from the xref:official-repositories[official package repositories], or from a xref:mirror-repositories[mirror repository] owned and managed by your organization.

If you cannot access the RHEL or OEL repositories, there is no mirror repository in your organization, or you are unable to access Yum, Python, or R repositories, contact {support-url}.

[#official-repositories]
*Official package repositories*

If the hosts of your ThoughtSpot cluster can access external repositories, either directly or through a proxy, your cluster is online.
You can then proceed to download xref:yum-repository[Yum], xref:python-repository[Python], and xref:r-repository[R] package repositories.

[#mirror-repositories]
*Internal mirror repository*

If the hosts of your ThoughtSpot cluster have access to an internal repository that mirrors the public repositories, copy the xref:yum-repository[Yum], xref:python-repository[Python], and xref:r-repository[R] package repositories to your hosts.

[#tmp-permission]
== Ensure tmp has permission 777 or 1777

The `/tmp` directory must have either the `777` or `1777` permission. `1777` is the `777` permission but with the sticky bit set. If you mount the `/tmp` directory as a separate partition, it must NOT have the `noexec` flag set.

[#cgroups]
== Ensure that you are using Linux cgroupsV1

You must use Linux control groups v1 (`cgroupsV1`). `cgroupsV1` is the default on both RHEL 7 and RHEL 8. ThoughtSpot does not support use of Linux control groups v2 (`cgroupsV2`).

[#proc]
== Ensure /proc mount point flags are compatible

You cannot mount the /proc mount point with the `hidepid` flag. You must mount it without that flag.

[#etc-sudoers]
== Remove Defaults requiretty from /etc/sudoers

The `/etc/sudoers` file must not have the `Defaults requiretty` line. This line can cause cluster creation to fail.

[#selinux]
== [RHEL 8 only] Remove the selinux policy for rsync

Remove the selinux policy for rsync on each node. This is *only* necessary if you are using RHEL 8.1 - 8.5. You do not need to do this step if you are using RHEL 7.9 or 7.9, or OEL 7.9.

Run the following command on each ThoughtSpot node:

----
semanage permissive -a rsync_t
----

[#enable-ansible]
== [Optional] Enable an Ansible Control Server

Optionally configure an Ansible Control Server, on a separate host, to run the Ansible playbook that ThoughtSpot supplies.
You must install both `rsync` and Ansible on the Ansible Control Server host.

'''
> **Related information**
>
> * xref:rhel-ts-artifacts.adoc[ThoughtSpot deployment artifacts for RHEL and OEL]
> * xref:rhel-install-online.adoc[Online RHEL and OEL install]
> * xref:rhel-install-offline.adoc[Offline RHEL and OEL install]
> * xref:rhel-upgrade.adoc[RHEL and OEL upgrade]
> * xref:rhel-add-node.adoc[Add new nodes to clusters on RHEL or OEL]
> * xref:rhel-packages.adoc[Packages installed with RHEL and OEL]