= Packages installed with ThoughtSpot for RHEL and OEL
:last_updated: 8/6/2021
:linkattrs:
:experimental:

To successfully deploy ThoughtSpot in your organization, you must have the following packages on each node of your ThoughtSpot cluster: <<yum,yum>>, <<pip,python 3>>, and <<r,R>>.
When the Ansible playbook runs, it automatically installs them.

ThoughtSpot works only with the specified version of each package.

[#yum]
[#pip]
[#r]
[tabset]
====
Yum RPM packages;;
+
--
Download: link:{attachmentsdir}/yum-rpm-packages-rhel.csv[Yum RPM package list].

include::partial$/packages/yum-rpm-packages-rhel.adoc[]
--
Python 3 packages;;
+
--
Download: link:{attachmentsdir}/pip-rpm-packages.csv[Python RPM package list].

include::partial$/packages/pip-rpm-packages.adoc[]
--
R packages;;
+
--
Download: link:{attachmentsdir}/r-rpm-packages-rhel.csv[R RPM package list].

include::partial$/packages/r-rpm-packages-rhel.adoc[]
--
====

'''
> **Related information**
>
> * xref:rhel-prerequisites.adoc[RHEL and OEL prerequisites]
> * xref:rhel-ts-artifacts.adoc[ThoughtSpot deployment artifacts for RHEL and OEL]
> * xref:rhel-install-online.adoc[Online RHEL and OEL install]
> * xref:rhel-install-offline.adoc[Offline RHEL and OEL install]
> * xref:rhel-upgrade.adoc[RHEL and OEL upgrade]
> * xref:rhel-add-node.adoc[Add new nodes to clusters on RHEL or OEL]
