= Configure CA SiteMinder
:last_updated: 12/30/2020
:experimental:
:linkattrs:

CA SiteMinder can be used as an Identity Provider for single sign on to ThoughtSpot.

Before configuring CA SiteMinder, you must xref:saml.adoc[configure SAML in ThoughtSpot].
Use this procedure to set up CA SiteMinder for use with ThoughtSpot:

. Configure the Local Identity Provider Entity as follows:
+
[horizontal]
Entity Location:: Local
Entity Type:: SAML2 IDP
Entity ID:: Any (Relevant ID)
Entity Name:: Any (Relevant name)
Description:: Any (Relevant description)
Base URL:: `https://<FWS_FQDN>`, using fully qualified domain name serving SiteMinder services
Signing Private Key Alias:: Select the correct private key alias or import one if not done already
Signed Authentication Requests Required:: No
Supported NameID format:: Optional

. Create the Remote SP Entity, either through a metadata import or manually.
To configure the Remote SP entity manually, select *Create Entity*.
Create ThoughtSpot as a Remote Entity with following details:
+
[horizontal]
Entity Location:: Remote
New Entity Type:: SAML2 SP
Entity ID:: Your cluster
Entity Name:: Any (relevant name)
Description:: Any (relevant description)
Assertion Consumer Service URL:: (Relevant URL)
Verification Certificate Alias:: Select the correct certificate to verify the signature in incoming requests
Supported NameID Format:: Optional

. Proceed to configure the Federation Partnership between CA SiteMinder (the IDP) and ThoughtSpot (the Remote SP) in CA SiteMinder.
Log in to CA SiteMinder.
. Navigate to *Federation* > *Partnership Federation > Create Partnership* (*SAML 2 IDP > SP*).
. Click *Configure Partnership* and fill in the following values:
+
[horizontal]
Add Partnership Name:: Any (relevant name)
Description:: Any (relevant description)
Local IDP ID:: Select Local IDP ID
Remote SP ID:: Select Remote SP ID
Base URL:: Will be pre-populated
Skew Time:: Any per environment requirement
User Directories and Search Order:: Select required Directories in required search order

. Click *Configure Assertion* and fill in the following values:
+
[horizontal]
Name ID Format:: Optional
Name ID Type:: User Attribute
Value:: The name of the user attribute, containing the email address or user identifier, such as 'mail'.

. Click *Configure SSO and SLO* and fill in the following values:
+
[horizontal]
Add Authentication URL:: This should be the URL that is protected by SiteMinder
SSO Binding:: Select SSO Binding supported by the SP, typically the HTTP-Post
Audience:: (Relevant audience)
Transaction Allowed:: Optional
Assertion Consumer Service URL:: Populated using the information from the SP entity

. Continue to *Partnership Activation*, and select *Activate*.
