= Scheduled maintenance
:last_updated: 2/18/2022
:linkattrs:
:experimental:
:description: From the Admin Console, you can view any scheduled maintenance for the ThoughtSpot application.

Your ThoughtSpot Cloud application may require periodic maintenance.
You can always view upcoming scheduled maintenance from the Admin Console.

You can also ask your ThoughtSpot contact to add you to a list of email addresses that receive an alert about upcoming maintenance. The cluster administrator is automatically on this list, and you can add up to 3 more email addresses.

To view maintenance alerts from the ThoughtSpot application, navigate to the Admin Console by selecting the *Admin* tab from the top navigation bar.

If your organization uses xref:orgs-overview.adoc[multi-tenancy with Orgs], ensure that you are in the correct Org. Use the *Org switcher* in the top navigation bar, to the left of the help icon. Switch to the Org that you would like to view scheduled maintenance for. If you are in the Primary Org, switch to the *Primary Org* section of the side navigation bar in the Admin Console. You cannot view scheduled maintenance for all Orgs at the same time.

Select *Scheduled maintenance* from the side navigation bar that appears.

Before any planned maintenance, users see a yellow warning bar, letting them know about upcoming downtime for the application.

When ThoughtSpot is under maintenance, you are not able to use the application.

'''
> **Related information**
>
> * xref:admin-console-orgs-page.adoc[]
> * xref:admin-portal-users-orgs.adoc[]
> * xref:admin-portal-groups-orgs.adoc[]
> * xref:authentication-local.adoc[]
> * xref:saml.adoc[]
> * xref:user-adoption.adoc[]
> * xref:performance-tracking.adoc[]
> * xref:search-spotiq-settings.adoc[]
> * xref:onboarding-email-settings.adoc[]
> * xref:style-customization.adoc[]
