= Other search actions
:last_updated: 11/15/2019

Learn about advanced search options.

There are other search actions you can perform by interacting directly with your Answer.
These actions can be performed in an ad hoc way, or you can pin your Answer to a Pinboard to save your configurations.

* *xref:change-the-view.adoc[Change view options]*
+
You can change the view of your Answer so it appears as a table or a chart. Sorting your search allows you to order your Answer, making it easier to read. You can change the date bucketing on tables and charts for columns with date values.
* *xref:show-underlying-data.adoc[Show underlying data]*
+
Viewing the underlying data of your Answer gives you an un-aggregated view of the underlying data.
* *xref:drill-down.adoc[Drill down]*
+
Drilling down allows you to see more information about the columns used within your search.
* *xref:change-the-view.adoc#exclude-and-include-row-values[Exclude and include row values]*
+
You can include or exclude row values from your Answer.
* *xref:apply-conditional-formatting.adoc[Apply conditional formatting]*
+
You can apply conditional formatting to tables or charts to highlight values in the data.
This makes values over, under, or within a particular threshold stand out.
* *xref:work-with-answers.adoc[Work with saved Answers]*
+
You can make a copy of an Answer if you would like to make edits without changing the original Answer.
* *xref:download-your-search.adoc[Download your search]*
+
You can download your search as either a table or chart.
* *xref:replay-search.adoc[Replay search]*
+
You can instantly generate a step-by-step replay showing the creation of a table or chart.
