= Security
:last_updated: 06/21/2021
:linkattrs:
:experimental:
:description: Learn about ThoughtSpot's security features.

Learn about ThoughtSpot's security features.

include::partial$liveboards-announcement.adoc[]


There are several aspects of security, including access and permissions, data security and privacy, and security from an IT perspective.

* xref:system-security.adoc[System Security] refers to audit logs and security policies.
* xref:data-security.adoc[Data Security] refers to which users can see which data in the ThoughtSpot application, and includes:
 ** xref:groups-privileges.adoc[Users and Groups]
 ** xref:groups-privileges.adoc#privileges-and-groups[Privileges]
 ** xref:share-source-tables.adoc[Table and columns sharing]
 ** xref:security-rls.adoc[Row level security]
 ** xref:share-worksheets.adoc[Worksheet sharing]
 ** xref:share-liveboards.adoc[Liveboard sharing]
* Network Security refers to ports for external traffic and traffic within the cluster.
Some ports must remain open for handling network requests from outside the ThoughtSpot instance.
To see a list of network ports that must remain open to outside traffic, and for inter-cluster communication, review the information in xref:ports.adoc[Network ports].
