= Set up monitoring
:linkattrs:

Setting up monitoring is a one time operation.

To configure monitoring of your cluster, set up the frequency of heartbeat and monitoring reports and an email address to receive them:

. Log in to the Linux shell using SSH.
. Issue the `tscli` command to set up monitoring:
+
----
 tscli monitoring set-config
    --email <email>
    --heartbeat_interval <heartbeat_interval>
    --report_interval <report_interval>
----
+
The parameters are:

 ** `--email <email>` is a comma separated list (no spaces) of email addresses where the cluster will send monitoring information.
 ** `--heartbeat_interval <heartbeat_interval>` is the heartbeat email generation interval in seconds.
Must be greater than 0.
 ** `--report_interval <report_interval>` sets the cluster report email generation interval in seconds.
Must be greater than 0.

. To view your settings and verify that they have been applied, issue:
+
----
 tscli monitoring show-config
----
+
You should see information like:
+
----
 Monitoring Configuration:

   Alert Email: dev-alerts@thoughtspot.com

   Heartbeat Interval: 900 sec

   Report Interval: 21600 sec
----

. After the heartbeat interval has passed, check your email to verify that emails are being delivered.
. If you don't receive any emails, xref:set-up-relay-host.adoc#verify-email[verify that email is working].

== Additional resources

As you develop your expertise in monitoring, we recommend the following ThoughtSpot U course:
- https://training.thoughtspot.com/emails-alerts[Email and Alert Setup]

See other training resources at https://training.thoughtspot.com[ThoughtSpot U].
