= About installation and upgrades
:last_updated: 3/4/2020

As administrator, you are responsible for setting up and configuring ThoughtSpot. This guide explains how. It will also assist you in troubleshooting some common problems, finding additional resources, and contacting ThoughtSpot.

Your ThoughtSpot application software is already installed for you in a ThoughtSpot appliance.
This is true for both physical and virtual appliances.

The ThoughtSpot software is updated by ThoughtSpot Support.
ThoughtSpot Support will contact you to schedule an update when one becomes available.

As administrator, you are responsible for setting up and configuring ThoughtSpot.
This guide helps you with these tasks, and also assists in troubleshooting some common problems and finding additional resources.

[#display-current-config]
== Display your current configuration

To perform the setup and configuration, you must first learn how to xref:logins.adoc[gain administrative access].

. Log in to the ThoughtSpot cluster as the `admin` user.
. Use the `tscli feature` subcommand to display your current configuration.
+
----
 $ tscli feature get-all-config
 +---------------------------------+----------+---------------+
 |              NAME               |  STATUS  | CONFIGURATION |
 +---------------------------------+----------+---------------+
 | Firewall                        | Disabled |               |
 | Saml                            | Disabled |               |
 | Ldap                            | Disabled |               |
 | CustomBranding                  | Disabled |               |
 | CustomBrandingFontCustomization | Disabled |               |
 | DataConnect                     | Disabled |               |
 | RLS                             | Enabled  |               |
 | Callhome                        | Enabled  |               |
 | SSHTunnel                       | Enabled  |               |
 | Fileserver                      | Disabled |               |
 +---------------------------------+----------+---------------+
----

[#related]
'''
> **Related information**
>
> The following tasks are also available:
>
> * xref:set-your-thoughtspot-locale.adoc[Set your locale]
> * xref:test-network.adoc[Test connectivity between nodes]
> * xref:set-custom-calendar.adoc[Set up a fiscal calendar year]
> * xref:about-LDAP.adoc[Integrate LDAP]
> * xref:set-up-monitoring.adoc[Set up monitoring]
> * xref:work-with-ts-support.adoc[Configure support services]
> * xref:firewall-ports.adoc[Network ports]
> * xref:about-load-balancer-configuration.adoc[Configure load balancing and proxies]
> * xref:customize-style.adoc[Customize look and feel]
