= Sharing information in ThoughtSpot
:last_updated: 02/01/2021
:linkattrs:
:experimental:
:page-partial:
:page-aliases: /end-user/data-view/sharing-for-end-users.adoc
:description: Learn how to share answers and Liveboards.


Learn how to share answers and Liveboards.

Whenever you are working in ThoughtSpot, you are in your own private environment until you share your work with others.
Sharing applies to searches, Liveboards, and any data you upload.
You share by selecting the *Share* button from within the object you want to share and specifying the users or groups with whom you want to share.
An email notification goes out to those users or groups when you select *Share*.

== What you can share

This is a list of objects a regular, non-administrator user can share.
Administrators have more granular control over data security.

You can share with groups and with individual people.
You can share several different types of objects:

[cols="20,25,~",option="header"]
|===
| Object type | Description | Default security model

| Uploaded data
| Data you upload using a Web browser.
| Only the user who uploaded the data (and any user with administrator privileges) has access to it by default.
They can share a table (or selected columns) with other people or groups.
See xref:share-user-imported-data.adoc[Share uploaded data].

| Liveboards
| A Liveboard of saved search results.
| By default, only the user who created the object (and any user with administrator privileges) has access to it. After the creator or an admin shares it, anyone who can view a Liveboard can share it.
See xref:share-liveboards.adoc[share a Liveboard].

| Answers
| The result of a single search.
| By default, only the user who created the object (and any user with administrator privileges) has access to it. After the creator or an admin shares it, anyone who can view an answer can share it.
See xref:share-answers.adoc[share answers].
|===

== Who can share and to whom

You do not have to be an administrator or the owner of an object to share saved answers or Liveboards.
Any user can share them, based on the access levels the user has.

If you upload a spreadsheet, you can share *Can View* or *Can Edit* privileges with other people, who can further share them with others.
This last point is important.
Like sharing a secret, sharing an object or your data can quickly spread in ths way to people you do not intend it to.
So, if your data or work is sensitive to your business be thoughtful in how you share it.

Finally, you can revoke access to an object (table, worksheet, or Liveboard) that you have previously shared.
Unsharing an object is very similar to sharing it.

'''
> **Related information**
>
> * xref:share-liveboards.adoc[Share a Liveboard]
> * xref:share-answers.adoc[Share answers]
> * xref:share-user-imported-data.adoc[Share uploaded data]
> * xref:share-request-access.adoc[Request object access]
> * xref:share-revoke-access.adoc[Revoke access (unshare)]
