= Configure ThoughtSpot nodes on the SMC appliance
:last_updated: 01/02/2021
:linkattrs:
:experimental:
:page-aliases: /appliance/hardware/configure-nodes-smc.adoc

Configure your nodes before you can install your cluster(s).

'''
> **ThoughtSpot Training**
>
> * For best results when configuring ThoughtSpot on a SMC appliance, we recommend that you take the following ThoughtSpot U course: https://training.thoughtspot.com/node-network-configuration/437249[Network Configuration^].
> * See other training resources at https://training.thoughtspot.com/[ThoughtSpot U^].

'''
After you connect the appliance, configure the nodes in your Mac or Windows terminal emulator.

Follow the steps in this checklist.

[cols="5,~",grid=none,frame=none]
|===
| &#10063; | <<node-step-1,Step 1: SSH into your cluster>>
| &#10063; | <<node-step-2,Step 2: Change to the `install` directory>>
| &#10063; | <<node-step-3,Step 3: Get a template for node configuration>>
| &#10063; | <<node-step-4,Step 4: Prepare node configuration>>
| &#10063; | <<node-step-5,Step 5: Configure the nodes>>
| &#10063; | <<node-step-6,Step 6: Confirm node configuration>>
|===

If you completed ThoughtSpot's link:{attachmentsdir}/site-survey.pdf[site survey] form and returned it to https://community.thoughtspot.com/customers/s/contactsupport[ThoughtSpot Support^] before ThoughtSpot shipped the appliance, the appliance may be pre-configured for your network environment and ready to install and connect to your network.

If the network configuration was not pre-set, then this step must be done as part of the installation process.

Follow these steps to determine the configuration status of your appliance.

. SSH into your cluster.
Run `ssh admin@<nodeIP>`.
+
Replace `nodeIP` with your specific network information.
+
[source,bash]
----
 $ ssh admin@<nodeIP>
----

. Run `tscli cluster status`.
+
[source,bash]
----
 $ tscli cluster status
----

. If the output shows READY, and looks like the xref:smc-cluster-install.adoc#install-step-2[cluster status output] in the next article, your appliance is configured.
. Skip to xref:smc-cluster-install.adoc#install-step-3[Finalize installation].

If your status is not READY, continue with the installation process outlined below.

[#node-step-1]
== Step 1: SSH into your cluster

SSH into your cluster with admin credentials.

. Run the command `ssh admin@<cluster-IP>` or `ssh admin@<hostname>` on the command line.
+
Replace `clusterIP` or `hostname` with your specific network information.
+
----
 $ ssh admin@<nodeIP>
----

. Enter your admin password when prompted.
+
Ask your network administrator if you don't know the password.

[#node-step-2]
== Step 2: Change to the `install` directory

In your terminal, change directory to `/home/admin/install` by running the command `cd /home/admin/install`.
If your `/install` subdirectory does not exist, you may have to use the `/home/admin` directory.

 $ cd /home/admin/install

[#node-step-3]
== Step 3: Get a template for network configuration

Run the `tscli cluster get-config` command to get a template for network configuration.
Redirect it to the file `nodes.config`.
You can find more information on this process in the xref:nodesconfig-example.adoc[nodes.config file reference].

 $ tscli cluster get-config |& tee nodes.config

[#node-step-4]
== Step 4: Prepare node configuration

. Add your specific network information for the nodes in the `nodes.config` file, as demonstrated in the xref:nodesconfig-example.adoc#autodiscovery-of-one-node-example[autodiscovery of one node example].
Run `vim nodes.config` to edit the file.
+
----
 $ vim nodes.config
----
+
NOTE: Some of the information in the `nodes.config` file may be pre-populated from earlier steps.
For example, if you specified an IP address while creating VMs, that IP address might already be present in your `nodes.config` file.

. Fill in the areas specified in xref:parameters-nodesconfig.adoc[Parameters of the nodes.config file] with your specific network information.
+
If you have additional nodes, complete each node within the nodes.config file in the same way.
+
Edit only the parts of the nodes.config file that are explicitly discussed in xref:parameters-nodesconfig.adoc[Parameters of `nodes.config`].
If you delete quotation marks, commas, or other parts of the code, it may cause setup to fail.

. Update the file `/etc/hosts` with all the node IP addresses and hostnames for the other VMs that will be part of the ThoughtSpot cluster.

[#node-step-5]
== Step 5: Configure the nodes

Configure the nodes in the `nodes.config` file using the `set-config` command.

Run `$ cat nodes.config | tscli cluster set-config` in your terminal.

If the command returns an error, refer to xref:smc-cluster-install.adoc#set-config-error-recovery[set-config error recovery].

[source,bash]
----
$ cat nodes.config | tscli cluster set-config

Connecting to local node-scout
Setting up hostnames for all nodes
Setting up networking interfaces on all nodes
Setting up hosts file on all nodes
Setting up IPMI configuration
Setting up NTP Servers
Setting up Timezone
Done setting up ThoughtSpot
----

[#node-step-6]
== Step 6: Confirm node configuration

Use the `get-config` command to confirm node configuration.
Your output may look similar to the following:

[source,bash]
----
$ tscli cluster get-config

{
  "ClusterId": "",
  "ClusterName": "",
  "DataNetmask": "255.255.252.0",
  "DataGateway": "192.168.4.1",
  "IPMINetmask": "255.255.252.0",
  "IPMIGateway": "192.168.4.1",
  "Timezone": "America/Los_Angeles",
  "NTPServers": "0.centos.pool.ntp.org,1.centos.pool.ntp.org,2.centos.pool.ntp.org,3.centos.pool.ntp.org",
  "DNS": "192.168.2.200,8.8.8.8",
  "SearchDomains": "example.company.com",
  "Nodes": {
	"ac:1f:6b:8a:77:f6": {
  	"NodeId": "ac:1f:6b:8a:77:f6",
  	"Hostname": "Thoughtspot-server1",
  	"DataIface": {
    	"Name": "eth2",
    	"IPv4": "192.168.7.70"
  	},
  	"IPMI": {
    	"IPv4": "192.168.5.70"
  	}
	}
  }
}
----

== Install the cluster

Next, xref:smc-cluster-install.adoc[install your cluster.]
