= Deploying on the SMC appliance
:last_updated: 8/6/2021
:linkattrs:
:experimental:
:page-aliases: /appliance/hardware/smc-cluster-install.adoc

Follow these steps to deploy ThoughtSpot on your Super Micro Computer (SMC) appliance:

[cols="5,~",grid=none,frame=none]
|===
| &#10063; | xref:smc-prerequisites.adoc[Step 1: Complete installation prerequisites]
| &#10063; | xref:smc-hardware-requirements.adoc[Step 2: Review hardware requirements]
| &#10063; | xref:smc-connect-appliance.adoc[Step 3: Connect your SMC appliance]
| &#10063; | xref:smc-configure-nodes.adoc[Step 4: Configure nodes]
| &#10063; | xref:smc-cluster-install.adoc[Step 5: Install cluster]
|===

This guide explains how to deploy ThoughtSpot on an SMC appliance, using ThoughtSpot's CentOS-based image.
You can also deploy ThoughtSpot on an SMC appliance using Red Hat Enterprise Linux (RHEL), allowing you to run ThoughtSpot on an RHEL 7.8 or 7.9 image that your organization manages internally.
To install ThoughtSpot using RHEL, refer to the xref:rhel.adoc[RHEL and OEL deployment guide].

'''
> **Related information**
>
> * xref:nodesconfig-example.adoc[The nodes.config file]
> * xref:parameters-nodesconfig.adoc[Parameters of the nodes.config file]
> * xref:cluster-create.adoc[Using the tscli cluster create command]
> * xref:parameters-cluster-create.adoc[Parameters of the cluster create command]
> * Contact https://community.thoughtspot.com/customers/s/contactsupport[ThoughtSpot Support^].
