= System monitoring
:last_updated: 12/28/2020
:experimental:
:linkattrs:
:description: System monitoring tools in ThoughtSpot include several Liveboards in the Admin Console and system logs.


System monitoring tools in ThoughtSpot include several Liveboards in the Admin Console and system logs. Additionally, ThoughtSpot provides several worksheets and out-of-the-box system monitoring Liveboards. From these worksheets, you can create your own custom visualizations and Liveboards. This section introduces these features and directs you towards more detailed information.

include::partial$liveboards-announcement.adoc[]


== System worksheets and Liveboards

The ThoughtSpot application includes an *Admin Console* center, where you can easily view Liveboards that monitor usage, alerts, events and general cluster health. Navigate to the *Admin Console* by selecting *Admin* from the top navigation bar.

Only users with administrative privileges can view the *Admin Console*. However, administrative users can present the information in the *Admin Console* to others.

Administrators can also create their own, custom Liveboards that reflect system data in ways that are meaningful to specific departments or groups.

For more information on system worksheets and Liveboards, refer to the following articles:

* xref:admin-portal-system-information-liveboard.adoc[System information and usage Liveboard]
* xref:admin-portal-table-status-liveboard.adoc[Data board]
* xref:cluster-manager.adoc[Cluster Manager board]
* xref:system-alerts-events.adoc[Alerts and Events board]
* xref:system-worksheet.adoc[System Worksheets]
* xref:system-liveboards.adoc[System Liveboards]
* xref:falcon-monitor.adoc[Falcon monitoring Liveboards]
* xref:admin-portal-performance-tracking.adoc[Performance Tracking Liveboard]

Much of the data presented by these boards is also available through tscli commands see xref:tscli-command-ref.adoc[tscli Command Reference].

== Log files
Many of the administration commands output logging information to log files. The logs get written into the fixed directory `/export/logs/`, with a sub-directory for each subsystem. The individual log directories follow:

* `/export/logs/orion`
* `/export/logs/oreo`
* `/export/logs/hadoop`
* `/export/logs/zookeeper`

You can also view [additional topics that also touch on log files throughout the documentation.

== System monitoring notifications

You can configure ThoughtSpot to send emails to addresses you specify with monitoring reports and a cluster heartbeat. Follow these steps to xref:monitoring-setup.adoc[Set up monitoring].
