= System Liveboards
:last_updated: 08/20/2021
:linkattrs:
:experimental:
:page-partial:
:description: ThoughtSpot provides several Liveboards that help with system monitoring.
:page-aliases: /admin/system-monitor/monitor-pinboards.adoc, system-pinboards.adoc
:jira: SCAL-71323

ThoughtSpot provides several Liveboards that help with system monitoring.

There are several system monitoring Liveboards in ThoughtSpot that provide answers for system status and resource usage questions.
The information in these Liveboards are updated hourly from internal data sources that collect monitoring statistics.

Only users with the *can administer ThoughtSpot* privilege can view the monitoring Liveboards by default.
They are based on worksheets, which administrators can view, but not modify.
However, you can create new monitoring Liveboards from the worksheets.

Users with admin privileges can share the system Liveboards with other users who do not have admin privileges. However, be aware that you may be sharing sensitive user-level information such as the names of objects that a user accessed, pricing information, and so on.

== View system Liveboards

To view these system Liveboards:

. Go to the *Liveboards* tab.
. Choose *All*.
. Search for the Liveboard you would like to view.
You can also view the *System Cluster Liveboard*, the *System Alert Liveboard*, *TS Stats: Table Status*, *TS Stats: System Information and Usage* and the *User Adoption Liveboard* from the Admin Console. You can also view the *Connections Liveboard* from *Data > Usage Statistics*.

== Summary of system Liveboards

TS Stats: Alert Detail::
  Combines alerts, notification events, and configuration events boards.

TS Stats: Cluster Detail::
  Contains cluster details, logs, snapshots, and latency data.

TS Stats: System Information and Usage::
  Replicates the *Admin > System Health > Overview* page. Available in the Admin Console, under *System information*.

TS Stats: Latency Visualizations::
  Latency on servers and impression counts. This data comes from the xref:ts-bi-server.adoc[TS: BI Server worksheet].

TS Stats: Table Status::
  Replicates the *Data* board. Available in the Admin Console, under *Table status*.

Connections Liveboard:: Contains information on your connections: monthly and daily row count, query count, and query performance. Available from *Data > Usage statistics*.

User Adoption::
      Contains information on how your ThoughtSpot users are interacting with ThoughtSpot, and how your user adoption is changing over time. Refer to xref:admin-portal-user-adoption-liveboard.adoc[User Adoption Liveboard].

Object usage::
  	Contains information on how your ThoughtSpot users are interacting with ThoughtSpot objects such as worksheets, tables, and views. Refer to xref:object-usage-liveboard.adoc[Object Usage Liveboard].

Performance Tracking::
  Contains information on how your ThoughtSpot cluster is performing. Refer to xref:admin-portal-performance-tracking.adoc[Performance Tracking Liveboard].

== About deprecated system Liveboards

The deprecated system Liveboards (`TS status: Usage - Deprecated` and `TS StaTS: Queries -- Deprecated`) are there to support older installations.

New installations should not use or rely on deprecated Liveboards.

Older installations that use these Liveboards should start using the new Liveboards and remove any dependencies.
