= TML for Answers
:last_updated: 5/19/2023
:author: Teresa Killmond
:linkattrs:
:experimental:
:page-aliases: /admin/scriptability/tsl-answer.adoc, /admin/scriptability/tml-answer.adoc, /admin/ts-cloud/tsl-answer.adoc
:description: Use TML to modify Answers in a flat-file format. Then, migrate the Answer to a different cluster, or restore it to the same cluster.
:object: Answers

include::partial$tml-intro.adoc[]

[#syntax-answers]
include::partial$tml-syntax-answer.adoc[]

[#answer-parameters]
== TML parameters for {object}
These parameters and their definitions are specific to {object}; this list doesn't contain every parameter in every TML file. Similarly, the parameter definitions may vary from object to object, since the parameters may have different roles in different objects.

[width=“100%”,grid=“none”,options="header"]
|===
| a - c | d - l | n - t
a| <<aggregation,aggregation>>
<<answer,answer>>

<<answer_columns,answer_columns>>

<<axis_configs,axis_configs>>

<<chart,chart>>

<<chart_columns,chart_columns>>

<<client_state,client_state>>

<<column_id,column_id>>

<<column_type,column_type>>

<<custom_name,custom_name>>

a| <<data_type,data_type>>

<<description,description>>

<<display_mode,display_mode>>

<<expr,expr>>

<<formulas,formulas>>

<<fqn,fqn>>

<<guid,guid>>

<<headline_aggregation,headline_aggregation>>

<<id,id>>

<<locked,locked>>

a| <<name,name>>

<<ordered_column_ids,ordered_column_ids>>

<<override_value,override_value>>

<<properties,properties>>

<<search_query,search_query>>

<<show_headline,show_headline>>

<<table,table>>

<<table_columns,table_columns>>

<<tables,tables>>

<<type,type>>
|===

[#aggregation]
aggregation::
The default aggregation of the output for a formula.
+
Aggregation options depend on the data type.
+
Possible values are `SUM`, `COUNT`, `AVERAGE`, `MAX`, `MIN`, `COUNT_DISTINCT`, `NONE`, `STD_DEVIATION`, and `VARIANCE`
+
Default: `SUM`.

[#answer]
answer::
Top-level container for all object definitions within an answer.

[#answer_columns]
answer_columns::
A list of columns generated by the search query.

[#axis_configs]
axis_configs::
Specifies the columns for each axis on a chart.
+
If you are displaying a column chart with a line chart overlaying it, for example, you would need to specify more than one `axis_config`.

[#chart]
chart::
Contains configuration for the Answer, if it displays in chart format.

[#chart_columns]
chart_columns::
A list of columns in the chart.

[#client_state]
client_state::
A JSON string with more advanced chart and table configuration.

[#column_id]
column_id::
Describes how the column appears in the query.
For example, if you sorted by `Quarter` in your search, from the `Commit Date` column, the `column_id` of the column is `Quarter(Commit Date)`.

[#column_type]
column_type::
The type of data the output of the formula represents.
+
Possible values: `MEASURE` or `ATTRIBUTE`. The default depends on the <<data_type,data_type>>.
+
If the data type is `INT` or `BIGINT`, the formula output's `column_type` defaults to `Measure`.
+
If the data type is `BOOL`, `VARCHAR`, `DOUBLE`, `FLOAT`, `DATE`, `DATETIME`, or `TIME`, the formula output's `column_type` defaults to `Attribute`.

[#custom_name]
custom_name::
Optional display name for a column.

[#data_type]
data_type::
The data type of the formula output.
If the data type is `INT32` or `INT64`, the formula output's `column_type` defaults to `Measure`.
If the data type is `BOOL`, `VARCHAR`, `DOUBLE`, `FLOAT`, `DATE`, `DATETIME`, or `TIME`, the formula output's `column_type` defaults to `Attribute`.

[#description]
description::
The text that describes an Answer.

[#display_mode]
display_mode::
Determines whether the answer displays as a chart or a table.
Specify either `CHART_MODE` or `TABLE_MODE`.

[#expr]
expr::
The definition of the formula. This should be the same as the formula expression in the formula editor.

[#formulas]
formulas::
The list of formulas in the Answer.
+
Each formula is identified by `name`, the `expr` (expression), and an optional `id` attribute.

[#fqn]
fqn::
The source table's GUID.
You can find this string of letters and numbers at the end of the URL for that table or connection.
+
For example, in `\https://<company>.thoughtspot.com/#/data/tables/34226aaa-4bcf-4d6b-9045-24cb1e9437cb`, the GUID is `34226aaa-4bcf-4d6b-9045-24cb1e9437cb`.
+
Use this optional parameter to reduce ambiguity and identify a specific table, if you have multiple tables with the same name. When exporting a TML file, you have the option to *Export FQNs of referenced objects*, which ensures that the TML files you export contain FQNs for the underlying tables and connections. If you do not add the `fqn` parameter, and the connection or table you reference does not have a unique name, the file import fails.

[#guid]
guid::
The GUID for the Answer. You can find this string of letters and numbers at the end of the URL for an object.

[#headline_aggregation]
headline_aggregation::
Specifies the type of aggregation the headline uses.
+
Can be `COUNT`, `COUNT_DISTINCT`, `SUM`, `MIN`, `MAX`, `AVERAGE`, or `TABLE_AGGR`.

[#id]
id::
Specifies the id of an object, such as `table` or `formula`.
+
For `answer_columns`, `id` refers to how the column appears in the query.
For example, if you sorted by `Quarter` in your search, from the `Commit Date` column, the `id` of the column is `Quarter(Commit Date)`. Refer to https://developers.thoughtspot.com/docs/?pageid=search-data-api[Components of a Search Query^] to understand syntax.
+
For formulas within answers, `id` refers to the display name of the formula. If you do not give your formula a name, it appears as 'Untitled Formula'.

[#locked]
locked::
The 'automatically select my chart' option in the UI.
If set to `true`, the chart type does not change, even when you change the search query.

[#name]
name::
The name of an object.
Applies to `formula`, `answer`, `liveboard`, `table`, and so on.
+
For `answer_columns`, `name` refers to how the column appears in the query.
For example, if you sorted by `Quarter` in your search, from the `Commit Date` column, the `name` of the column is `Quarter(Commit Date)`.
Refer to https://developers.thoughtspot.com/docs/?pageid=search-data-api[Components of a Search Query^] to understand syntax.

[#ordered_column_ids]
ordered_column_ids::
A list of columns, in the order they appear in the table.

[#properties]
properties::
The list of the properties of the output for a formula within an Answer.
+
Each formula's output can have the following properties, depending on its definition: `column_type` and `aggregation`.

[#search_query]
search_query::
A string that represents the fully disambiguated search query.
Refer to https://developers.thoughtspot.com/docs/?pageid=search-data-api[Components of a Search Query^] to understand syntax.

[#show_headline]
show_headline::
Determines whether to show the headline for this column.
`true` shows the headline.

[#table]
table::
Contains configuration for the answer, if it displays in table format.

[#table_columns]
table_columns::
The columns in an Answer that is being displayed in table format.

[#tables]
tables::
List of tables used by the Answer. Each table is identified by `name`.

[#type]
type::
Within the `chart` section of an Answer TML file, this is the chart type.
+
Possible values: `COLUMN`, `BAR`, `LINE`, `PIE`, `SCATTER`, `BUBBLE`, `STACKED_COLUMN`, `AREA`, `PARETO`, `COLUMN`, `GEO_AREA`, `GEO_BUBBLE`, `GEO_HEATMAP`, `GEO_EARTH_BAR`, `GEO_EARTH_AREA`, `GEO_EARTH_GRAPH`, `GEO_EARTH_BUBBLE`, `GEO_EARTH_HEATMAP`, `WATERFALL`, `TREEMAP`, `HEATMAP`, `STACKED_AREA`, `LINE_COLUMN`, `FUNNEL`, `LINE_STACKED_COLUMN`, `PIVOT_TABLE`, `SANKEY`, `GRID_TABLE`, `SPIDER_WEB`, `WHISKER_SCATTER`, `STACKED_BAR`, or `CANDLESTICK`.

[#limitations]
== Limitations of working with TML files

There are certain limitations to the changes you can apply by editing {object} through TML.

* Formulas and columns can either have a new name, or a new expression.
You can't change both, unless migrating or updating the Worksheet two times.
* You can't create or export TML files for R- or Python-powered visualizations.
* You can't import manually compressed .zip files.
You can only import .zip files that you exported from ThoughtSpot: a custom set of TML files, an object and its associated data sources, or multiple objects of the same type that you exported from the object list page.
* You can't modify joins at the table level from the Worksheet, view, or Answer TML file.
You can only override the joins for that specific Worksheet, view, or Answer.
To modify table-level joins, you must edit the source table's TML file.
* Changing the filter order for Answers in the UI doesn't change the filter order in the TML file.
