= Migrate multiple TML files
:experimental:
:last_updated: 8/19/2022
:linkattrs:
:page-aliases: /admin/ts-cloud/tml-import-export-multiple.adoc, /admin/scriptability/app-templates.adoc, /app-templates.adoc


You can migrate collections of Liveboards, answers, worksheets, views, and tables packaged together as a zip file.
You can do this by xref:scriptability.adoc[importing and exporting TML files], ThoughtSpot's solution for migrating data models (worksheets, tables, and views) and content (Liveboards and answers) between different environments, such as development and production.
You can optionally edit these ThoughtSpot objects during the migration process.

include::partial$liveboards-announcement.adoc[]


[#export-multiple]
== Export related TML files

You can export your own custom zip file of related ThoughtSpot Modeling Language (TML) files from the *Utilities* page.
Additionally, when you export more than one object of the same type at a time, or when you export an object and its dependents, ThoughtSpot exports it as a zip file.

To export your own custom TML file collections, follow these steps.

. Navigate to the *Utilities* page: *Data > Utilities*.
. In the *Import/Export TML* tile, select *Export TML*.
. In the *Export* interface, select the Liveboards, answers, views, tables, and worksheets that you would like to include in your zip file of related TML files.
For example, for a Marketing zip file, you might choose a Marketing worksheet, a Campaigns worksheet, a Pipeline Liveboard, and a few answers your Chief Marketing Officer created.

. Click *Export _n_ objects*.
. The *Choose what to Export* modal appears.
Choose whether to export only the selected objects, or the selected objects and their associated objects (their underlying data sources: worksheets, tables, and views).
. Click *Export*.
. Open the downloaded `TML` zip file.
The zip file contains a document called the `Manifest` file, which defines the objects you exported, their underlying data sources, and any export errors.

See xref:scriptability.adoc[] for more information on exporting and importing objects.

== Import related TML files

You can import your own custom zip file of related TML files from the *Utilities* page.

. Navigate to the *Utilities* page: *Data > Utilities*.
. In the *Import/Export TML* tile, select *Import TML*.
. In the *Import* interface, click *Select .zip or .tml files to upload*.
. In your file system, find and select the .zip file.
. Unselect any files in the `.zip` file you do not want to upload.
. If you constructed the file correctly, the *Import* interface displays a _Ready for import_ message for each TML file, and shows you which objects are validated.
. When all your files are ready for import, you can now determine how to import the objects.
The `GUID` parameter in an object's TML file allows ThoughtSpot to recognize pre-existing GUIDs, and determine if you are updating an existing object, or creating a new one.
If you are updating an existing object, the system asks if you would like to create a new object, or update the existing one.
. If there are errors in any of the objects you are importing, the *Status* column says *Cannot import* for that object.
Next to *Cannot import*, you can *View Errors* to see the errors, and a suggested resolution.
. Resolve any errors by selecting the *Edit* button for the object with errors.
This opens the xref:scriptability.adoc#tml-editor[TML editor].
Within the editor, resolve the errors using the method suggested under *View Errors* in the Import workflow.
. After you resolve the errors, click *Validate*, and then *Save*.
Exit the TML editor.
. Select the objects you want to import.
ThoughtSpot automatically selects objects with no errors, but does not select objects with errors, even after you resolve them.
You must select those objects yourself.
. Click *Import _n_ selected*.
. The *Import Status* screen displays the status of the objects you imported.
You can open the object(s) that you imported, or click *Exit* to return to the main object page.

== Limitations

You cannot import manually compressed .zip files. You can only import .zip files that you exported from ThoughtSpot: a custom set of TML files, an object and its associated data sources, or multiple objects of the same type that you exported from the object list page.
