= TML for SQL views
:last_updated: 5/19/2023
:author: Teresa Killmond
:linkattrs:
:experimental:
:description: Use TML to modify SQL views in a flat-file format. Then, migrate the view to a different cluster, or restore it to the same cluster.
:object: SQL views

include::partial$tml-intro.adoc[]

[#syntax-sql-views]
include::partial$tml-syntax-sql-view.adoc[]

[#sql-view-parameters]
== TML parameters for {object}
These parameters and their definitions are specific to {object}; this list doesn't contain every parameter in every TML file. Similarly, the parameter definitions may vary from object to object, since the parameters may have different roles in different objects.

[width=“100%”,grid=“none”,options="header"]
|===
| a - f | g - n | o - t
a| <<aggregation,aggregation>>

<<calendar,calendar>>

<<column_type,column_type>>

<<connection,connection>>

<<currency_type,currency_type>>

<<description,description>>

<<destination,destination>>

<<format_pattern,format_pattern>>

<<fqn,fqn>>

a| <<geo_config,geo_config>>

<<guid,guid>>

<<index_priority,index_priority>>

<<index_type,index_type>>

<<is_additive,is_additive>>

<<is_attribution_dimension,is_attribution_dimension>>

<<is_hidden,is_hidden>>

<<is_one_to_one,is_one_to_one>>

<<joins_with,joins_with>>

<<name,name>>

a| <<on,on>>

<<properties,properties>>

<<spotiq_preference,spotiq_preference>>

<<sql_output_column,sql_output_column>>

<<sql_query,sql_query>>

<<sql_view,sql_view>>

<<sql_view_columns,sql_view_columns>>

<<synonyms,synonyms>>

<<type,type>>

|===

[#aggregation]
aggregation::
The default aggregation of the SQL view column.
+
Aggregation options depend on the data type.
+
Possible values are `SUM`, `COUNT`, `AVERAGE`, `MAX`, `MIN`, `COUNT_DISTINCT`, `NONE`, `STD_DEVIATION`, and `VARIANCE`
+
Default: `SUM`.

[#calendar]
calendar::
Specifies the calendar used by a date column.
+
Can be the Gregorian calendar (`default`), a fiscal calendar, or any custom calendar.
+
See xref:connections-cust-cal.adoc[Set up a custom calendar].

[#column_type]
column_type::
The type of data the column represents.
+
Possible values: `MEASURE` or `ATTRIBUTE`

[#connection]
connection::
A way to identify the external data warehouse connection that the SQL view uses. To add tables or columns to an external connection, you must specify this parameter.

[#currency_type]
currency_type::
The source of the currency type.
+
One of:
+
`is_browser : true`;; infer the currency data from the locale of your browser
`column : <column_name>`;; extracts the currency information from a specified column
`iso_code : <valid_ISO_code>`;; applies currency based on the ISO code;
+
See https://www.iso.org/iso-4217-currency-codes.html[ISO 4217 Currency Codes^] and xref:data-modeling-patterns.adoc#set-currency-type[Set currency type] for more information.

[#description]
description::
The text that describes an object: a `sql_view`, `sql_view_column` and so on.

[#destination]
destination::
The name of the destination table or view for a join.

[#format_pattern]
format_pattern::
The format pattern string that controls the display of a number, date, or currency column.
+
See xref:data-modeling-patterns.adoc[Set number, date, and currency formats].

[#fqn]
fqn::
The table or connection's GUID.
You can find this string of letters and numbers at the end of the URL for that table or connection.
+
For example, in `\https://<company>.thoughtspot.com/#/data/tables/34226aaa-4bcf-4d6b-9045-24cb1e9437cb`, the GUID is `34226aaa-4bcf-4d6b-9045-24cb1e9437cb`.
+
Use this optional parameter to reduce ambiguity and identify a specific table, if you have multiple tables with the same name. When exporting a TML file, you have the option to *Export FQNs of referenced objects*, which ensures that the TML files you export contain FQNs for the underlying tables and connections. If you do not add the `fqn` parameter, and the connection or table you reference does not have a unique name, the file import fails.

[#geo_config]
geo_config::
Specifies the geographic information of a column. See xref:data-modeling-geo-data.adoc[Add a geographical data setting]
+
One of:
+
`latitude : true`;; for columns that specify the latitude
`longitude : true`;; for columns that specify the longitude
`country : true`;; for columns that specify the country
`region_name`;; for specifying a region in a country
+
Uses two paired parameters:

- `country: __<country_name>__`
- `region_name: __<region_name_in_UI>__`; can be State, Postal Code, District, and so on.
[#guid]
guid::
The GUID for the SQL view.
+
You can find this string of letters and numbers at the end of the URL for an object.
[#index_priority]
index_priority::
A value (1-10) that determines where to rank a column's name and values in the search suggestions
+
ThoughtSpot prioritizes columns with higher values.
+
See xref:data-modeling-index.adoc#column-suggestion-priority[Change a column's suggestion priority].

[#index_type]
index_type::
The indexing option of the SQL view column.
+
Possible values: `DONT_INDEX`, `DEFAULT` (see xref:data-modeling-index.adoc#default-indexing[Understand the default indexing behavior]), `PREFIX_ONLY`, `PREFIX_AND_SUBSTRING`, and `PREFIX_AND_WORD_SUBSTRING`
+
Default: `DEFAULT`
+
See xref:data-modeling-index.adoc#override-system-default-column[Index Type Values].

[#is_additive]
is_additive::
Controls extended aggregate options for attribute columns.
+
For attribute columns that have a numeric data type (`FLOAT`, `DOUBLE`, or `INTEGER`) or a date data type (`DATE`, `DATETIME`, `TIMESTAMP`, or `TIME`)
+
Possible values: `true` or `false`.
+
Default: `true`.
+
See xref:data-modeling-aggreg-additive.adoc#make-attribute-additive[Making an ATTRIBUTE column ADDITIVE].

[#is_attribution_dimension]
is_attribution_dimension::
Controls if the column is an attribution dimension.
+
Used in managing chasm traps.
+
Possible values: `true` by default, `false` to designate a column as not producing meaningful attributions across a chasm trap.
+
Default: `true`
+
See xref:data-modeling-attributable-dimension.adoc[Change the attribution dimension].

[#is_hidden]
is_hidden::
The visibility of the column.
+
Possible values: `true` to hide the column, `false` not to hide the column +
Default: `false`
+
See xref:data-modeling-visibility.adoc[].

[#is_one_to_one]
is_one_to_one::
Specifies the cardinality of the join. This is an optional parameter.
+
Possible values: `true`, `false`
+
Default: `false`

[#joins_with]
joins_with::
Contains a list of external joins for which this SQL view is the source. +
Each join is identified by `name` and optional `description`, and the additional attributes of `destination`, `type`, `on`, and `is_one_to_one`.

[#name]
name::
The name of an object.
Applies to `joins`, `SQL view`, and so on.

[#on]
on::
The join expression: the relationship definition, or the keys that your tables are joined on. For example, `[sale::Sale_Last Name] = [employee::Employee_Last Name] AND [sale::Sale_First Name] = [employee::Employee_First Name]`.
+
To alter a relationship definition, edit this parameter.

[#properties]
properties::
The list of properties of a SQL view column.
+
Each column can have the following properties, depending on its definition: `column_type`, `aggregation`, `index_type`, `is_hidden`, `index_priority`, `synonyms`, `is_attribution_dimension`, `is_additive`, `calendar`, `format_pattern`, `currency_type`, `geo_config`, and `spotiq_preference`.

[#spotiq_preference]
spotiq_preference::
Specifies whether to include a column in SpotIQ analysis.
Specify `EXCLUDE`, or this property defaults to include the column in SpotIQ Analysis.
+
Refer to xref:spotiq-data-model-preferences.adoc[Set columns to exclude from SpotIQ analyses].

[#sql_output_column]
sql_output_column::
Name of the SQL's output column as per the select clause in the view's SQL query.

[#sql_query]
sql_query::
A string that represents the SQL query used to create the SQL view.

[#sql_view]
sql_view::
Top-level container for all object definitions within the SQL view.

[#sql_view_columns]
sql_view_columns::
The list of columns in the SQL view.
+
Each column is identified by `name`, `description`, and `properties`.

[#synonyms]
synonyms::
Alternate names for the column, used in search.
+
See xref:data-modeling-visibility.adoc[].

[#type]
type::
This is the join type. This is an optional parameter.
+
Possible values: `LEFT_OUTER` for left outer join, `RIGHT_OUTER` for right outer join, `INNER` for inner join, `OUTER` for full outer join.
+
Default: `INNER`

[#limitations]
== Limitations of working with TML files

There are certain limitations to the changes you can apply by editing {object} through TML.

* It isn't possible to reverse the join direction in the TML script.
* You can't import manually compressed .zip files.
You can only import .zip files that you exported from ThoughtSpot: a custom set of TML files, an object and its associated data sources, or multiple objects of the same type that you exported from the object list page.