= ThoughtSpot Modeling Language
:last_updated: 08/06/2021
:linkattrs:
:experimental:
:page-partial:
:description: Use ThoughtSpot Modeling Language to modify a worksheet, view, table, Liveboard, SpotIQ result, or answer in a flat-file format.
:page-aliases: /admin/scriptability/tsl.adoc, /admin/ts-cloud/tml.adoc, /admin/ts-cloud/tsl.adoc, /admin/worksheets/yaml-worksheet.adoc, /admin/scriptability/tsl-pinboard.adoc, /admin/scriptability/tsl-answer.adoc, /admin/scriptability/tsl-view.adoc, /admin/scriptability/tml.adoc


Use ThoughtSpot Modeling Language to modify a worksheet, view, table, Liveboard, SpotIQ result, or answer in a flat-file format. Then you can migrate the object to a different cluster, or restore it to the same cluster.

To work with TML files for <<syntax-worksheets,worksheets>>, <<syntax-views,views>>, <<syntax-sql-views,SQL views>>, <<syntax-tables,tables>>, <<syntax-answers,answers>>, <<syntax-liveboards,SpotIQ results>>, and <<syntax-liveboards,Liveboards>> in ThoughtSpot, you can download these objects to a flat file in `.TML` format, modify it, and subsequently upload this file either to the same cluster, or to a different cluster.
To learn how to export, change, and update worksheets, views, tables, answers, SpotIQ results, and Liveboards, see xref:scriptability.adoc[Import and export TML files].

In this article, you learn the syntax of the TML files for each object. You also learn how to <<syntax-joins,add and modify joins>> for worksheets, views, SQL views, and tables.

NOTE: The syntax examples in this article contain every possible parameter in a TML file. Some of these parameters are not in a TML file by default. If you want to use them, you must add them yourself. For example, the <<fqn,fqn>> parameter is not present in the TML file by default, but you can add it to differentiate a table from another table with the same name.

[#syntax-worksheets]
include::partial$tml-syntax-worksheet.adoc[]

[#syntax-views]
include::partial$tml-syntax-view.adoc[]

[#syntax-sql-views]
include::partial$tml-syntax-sql-view.adoc[]

[#syntax-tables]
include::partial$tml-syntax-table.adoc[]

[#syntax-joins]
include::partial$tml-syntax-joins.adoc[]

[#syntax-answers]
include::partial$tml-syntax-answer.adoc[]

[#syntax-liveboards]
include::partial$tml-syntax-liveboard.adoc[]

[#tml-parameters]
include::partial$tml-parameters.adoc[]

== Limitations of working with TML files

There are certain limitations to the changes you can apply by editing a worksheet, answer, table, view, Liveboard, or SpotIQ result through TML.

[#limitations]
include::partial$scriptability-limitations.adoc[]
