= Network connectivity issues
:last_updated: 11/18/2019
:experimental:
:linkattrs:
:page-aliases: /admin/troubleshooting/check-connectivity.adoc

If network connectivity to and from ThoughtSpot is not working, try using these steps to find and correct the issue.

To troubleshoot network connectivity for ThoughtSpot:

. Make sure that the network cables are connected correctly.
. Check that the network cable is connecting the nodes to the network switch.
. Try replacing the cable with a cable from a known working system to rule out a bad cable or switch connectivity issues.
. Make sure the eth0 interface is connected to the network by issuing: `ethtool eth0` The port that's currently connected will have "link detected" in the last line of the output.
. If the networking settings have been reconfigured, reboot each of the nodes.

'''
> **Related information**
>
> * xref:troubleshooting-logs.adoc[Get logs]
> * xref:troubleshooting-logs-share.adoc[Upload logs to ThoughtSpot Support]
> * xref:troubleshooting-timezone.adoc[Check the timezone]
> * xref:troubleshooting-certificate.adoc[Browser untrusted connection error]
> * xref:troubleshooting-char-encoding.adoc[Characters not displaying correctly]
> * xref:troubleshooting-browser-cache.adoc[Clear the browser cache]
> * xref:troubleshooting-formulas.adoc[Cannot open a saved answer that contains a formula]
> * xref:troubleshooting-load.adoc[Data loading too slowly]
> * xref:troubleshooting-blanks.adoc[Search results contain too many blanks]