= Troubleshooting
:last_updated: 01/10/2021
:experimental:
:linkattrs:
:page-partial:
:description: Learn the basics of troubleshooting for ThoughtSpot.
:page-aliases: /admin/troubleshooting/troubleshooting-intro.adoc

Learn the basics of troubleshooting for ThoughtSpot.

The information here provides very basic troubleshooting.

* *xref:troubleshooting-logs.adoc[Get your configuration and logs]*
+
For troubleshooting on specific incidents or cluster problems, getting a log bundle can help.

* *xref:troubleshooting-logs-share.adoc[Upload logs to ThoughtSpot Support]*


* *xref:troubleshooting-generate-har-file.adoc[]* +
When you log a support ticket that references unexpected behavior in the web user interface, {support-url} often asks for a HAR file from the browser. The HAR file captures details about what's happening in the UI when the error occurs, including network requests happening in the browser. Learn how to generate a HAR file.

* *xref:troubleshooting-connectivity.adoc[Network connectivity issues]*
+
If network connectivity to and from ThoughtSpot isn't working, try using these steps to find and correct the issue.

* *xref:troubleshooting-timezone.adoc[Check the timezone]*
+
ThoughtSpot comes configured with the timezone where it is to be installed.

* *xref:troubleshooting-certificate.adoc[Browser untrusted connection error]*
+
If you aren't using an SSL certificate for authentication, users will see an untrusted connection error in their browser when accessing ThoughtSpot.
+
The error looks slightly different depending on the web browser being used.
* *xref:troubleshooting-char-encoding.adoc[Characters not displaying correctly]* +
Your CSV files are more likely to load smoothly if they are encoded with UTF-8.
+
If you're having problems with some characters rendering incorrectly, you can convert the files to UTF-8 encoding before loading the data.
* *xref:troubleshooting-browser-cache.adoc[Clear the browser cache]*
+
You might occasionally see unexpected behavior that is due to the web browser caching information from ThoughtSpot.
+
In this case, clearing the browser cache and reloading the page should resolve the problem.

* *xref:troubleshooting-formulas.adoc[Cannot open a saved answer that contains a formula]*

* *xref:troubleshooting-load.adoc[Data loading too slowly]*
+
Some tables may take an unusually long time to load due to a high data version issue. This issue normally arises when ThoughtSpot completes an upgrade or the system is recovering after a crash.

* *xref:troubleshooting-blanks.adoc[Search results contain too many blanks]*
+
If you find that your search results contain too many blanks when your data source is a worksheet, there is a simple adjustment you can make to fix this.

For more detailed troubleshooting, contact {support-url}.
