= About troubleshooting
:last_updated: 11/18/2019

Learn the basics of troubleshooting for ThoughtSpot.

The information here provides very basic troubleshooting.

* *xref:get-logs.adoc[Get your configuration and logs]*
+
For troubleshooting on specific incidents or cluster problems, getting a log bundle can help.
* *xref:upload-logs-egnyte.adoc[Upload logs to ThoughtSpot Support]*
* *xref:check-connectivity.adoc[Network connectivity issues]*
+
If network connectivity to and from ThoughtSpot is not working, try using these steps to find and correct the issue.
* *xref:set-timezone.adoc[Check the timezone]*
+
ThoughtSpot comes configured with the timezone where it is to be installed.
* *xref:certificate-warning.adoc[Browser untrusted connection error]*
+
If you are not using a SSL certificate for authentication, users will see an untrusted connection error in their browser when accessing ThoughtSpot.
The error looks slightly different depending upon the Web browser being used.
* *xref:char-encoding.adoc[Characters not displaying correctly]*
+
Your CSV files are more likely to load smoothly if they are encoded with UTF-8.
If you're having problems with some characters rendering incorrectly, you can convert the files to UTF-8 encoding before loading the data.
* *xref:clear-browser-cache.adoc[Clear the browser cache]*
+
You might occasionally see unexpected behavior that is due to the Web browser caching information from ThoughtSpot.
In this case, clearing the browser cache and reloading the page should resolve the problem.
* *xref:formula-date-problem.adoc[Cannot open a saved answer that contains a formula]*
* *xref:data-loading-too-slowly.adoc[Data loading too slowly]*
+
Some tables may take an unusually long time to load due to a high data version issue.
This issue normally arises when ThoughtSpot completes an upgrade or the system is recovering after a crash.
* *xref:search-too-many-blanks.adoc[Search results contain too many blanks]*
+
If you find that your search results contain too many blanks when your data source is a worksheet, there is a simple adjustment you can make to fix this.

For more detailed troubleshooting, xref:contact.adoc[Contact ThoughtSpot].
