= tscli command reference
:last_updated: 12/25/2020
:linkattrs:

The ThoughtSpot command line interface, or tscli, is an administration interface for the cluster. Use `tscli` to take snapshots (backups) of data, to apply updates, to stop and to start services, and to view information about the system. This reference defines each subcommand.

The command returns `0` code on success, and a non-zero exit code on failure.
The `tscli` command logs errors to the `stderr` directory.

[#tscli-command-how-to]
== How to use the tscli command

The `tscli` command has the following syntax:

....

tscli [-h]
      [--helpfull]
      [--verbose]
      [--noautoconfig]
      [--autoconfig]
      [--yes]
      [--cluster ]
      [--zoo ]
      {access,alert,ansible,backup,backup-policy,calendar,callhome,cassandra,cluster,command,dr-mirror,etl,event,feature,fileserver,firewall,hdfs,ipsec,ldap,logs,map-tiles,monitoring,nas,node,notification,onboarding,patch,rpackage,saml,scheduled-pinboards,set,smtp,snapshot,snapshot-policy,socialproof,ssl,sssd,storage,support,tokenauthentication}
....

The `tscli` command has several subcommands, such as `alert`, `backup`, and so on.

Issue subcommands using the following format:

----
tscli [subcommand]
----

Subcommands have their own additional options and actions, such as `tscli backup create` or `tscli backup delete`.

Each subcommand may have several options.
When a subcommand option is of the form `tscli subcommand --flag FLAG`, it requires a specific input from the user.
For example, the command `tscli access list --type TYPE`, where you want a list of pinboards, takes the form `tscli access list type pinboard`.

To view help for a subcommand, type `-h` after the subcommand option:

----
tscli [subcommand] -h
----

[#tscli-optional-flags]
== tscli optional flags

There are several optional flags that are common to each `tscli` subcommand.

[#tscli--help]
=== help

----
-h, --help
----

Shows help for a command.
This flag lists the specified command's subcommands and their definitions.

[#tscli--helpfull]
=== helpfull

----
--helpfull HELPFUll
----

This flag shows help for all supported commands.

[#tscli--verbose]
=== verbose

----
--verbose
----

Turns verbose logging on for the console.
By default, logs are written to both the console and log files, with the log files containing the highest verbosity log messages. The default is `false`.

[#tscli--noautoconfig]
=== noautoconfig

----
--noautoconfig
----

Prompts y/n response for each question within a command, instead of assuming `yes`. The default is `True`.

[#tscli--autoconfig]
=== autoconfig

----
--autoconfig
----

Automatically configures properties of the cluster whenever possible.
User may still be prompted for certain inputs. The default is `False`.

[#tscli--yes]
=== yes

----
--yes
----

Automatically configures properties of the cluster when possible.
User may still be prompted for certain inputs. The default is `False`.

[#tscli--cluster]
=== cluster

----
--cluster CLUSTER
----

Name of the cluster.
Used when a cluster is not automatically detected. The default is `False`.

[#tscli--zoo]
=== zoo

----
--zoo ZOO
----

List of Zookeeper servers, comma-separated. Used when a cluster is not detected automatically.

[#tscli-subcommands]
== tscli subcommands

This section lists each subcommand and its syntax.

[#tscli-access]
=== access

----
tscli access [-h] {list}
----

This subcommand has the following option:

tscli access list::
  Lists objects by last access time, with the following parameters:
  --type TYPE;; Type of object, either answer or pinboard.
  --limit	LIMIT;;  The number of objects to fetch. The default is 30.
  --offset OFFSET;;  Offset to use when skipping objects for batched results. The default is 0.
  --ascending;;  Sorts the answers by access time ascending. The default is `True`.

[#tscli-alert]
=== alert

----
tscli alert [-h] {count,info,list,off,on,refresh,silence,status,unsilence}
----

This subcommand has the following options:

tscli alert count::
  Lists counts of generated alerts by type.
tscli alert info::
  Lists all alerts. Add `--silenced` to list only silenced alerts, `--active` to list only active alerts, or `--detailed` to get detailed alert information.
tscli alert list::
  Lists the generated alerts, with these parameters:
  --limit LIMIT;;  Specifies the number of recent alerts to display.
  --since SINCE;;  Lists all alerts raised since a specified time period, in the form of a human-readable duration string, such as 4h (4 hours) or 4m (4 minutes).
tscli alert off::
  Disables all alerts from the cluster in the cluster's timezone.
tscli alert on::
  Enables alerts from the cluster.
tscli alert refresh::
  Refreshes alert metadata on the cluster.
tscli alert silence --name NAME::
  Silences the alert with `NAME`, such as `DISK_ERROR`. Silenced alerts are still recorded in postgres, but emails are not sent out.
tscli alert status::
  Shows the status of cluster alerts.
tscli alert unsilence --name NAME::
  Unsilences the alert with `NAME`, such as `DISK_ERROR`.

[#tscli-ansible]
=== ansible

----
tscli ansible [-h] {checkout,commit} [--local]
----

This subcommand has the following options:

tscli ansible checkout --host HOST::
  Checks out Ansible playbook with the target `HOST` that is running the `ts_ansible` service.
tscli ansible commit --host HOST::
  Commits Ansible playbooks with the target `HOST` that is running the `ts_ansible service`. Use this subcommand to install and configure third-party software on the ThoughtSpot cluster. For details, see these articles:
  * xref:about-secure-monitor-sw.adoc[About third party security and monitoring software]
  * xref:install-secure-monitor-sw.adoc[Installing third party security and monitoring software]

[#tscli-backup]
=== backup

----
tscli backup [-h] {create,delete,ls}
----

This subcommand has the following options:

tscli backup create [-h] [--mode {full,light,dataless}] [--type {full,incremental}] [--base BASE] [--storage_type {local,nas,cloud}] [--remote] [--no-orion-master] name out::
  Pulls a snapshot and saves it as a backup. You must specify the snapshot name, `name`, and also the backup directory, `out`. The command has the following optional parameters:
  --mode {full,light,dataless};; Mode of backups. The default is `full`.
  --type;; Type of backup. Only `STANDALONE` is supported.
  --base BASE;; Based snapshot name for incremental backup. Because `incremental` is not implemented, neither is this option. There is no default setting.
  --storage_type {local,nas,cloud};;  Storage type of output directory. The default setting is `local`.
  --remote;; Takes backup through Orion. The default setting is `True`.
  --no-orion-master;; Determines whether Orion is available during backup. The default is `False`.
  --bucket_name BUCKET_NAME;; The name of the s3/gcs bucket to create the backup. The platform depends on the storage type of the cluster. You must specify `--storage_type` as `cloud`.
  --staging_dir STAGING_DIR;; Used for staging hdfs data in cloud based backups. No effect in non-cloud based backups. You must specify `--storage_type` as `cloud`.

tscli backup delete ID::
  Deletes the backup with the specified ID.
tscli backup ls::
  Lists all periodic backups taken by the system. This command only shows periodic backups, not manual backups.

[#tscli-backup-policy]
=== backup-policy

----
tscli backup-policy [-h] {create,delete,disable,enable,ls,show,status,update}
----

Manages the backup policy.

This subcommand has the following options:

tscli backup-policy create::
  Prompts an editor for you to edit the parameters of a new periodic backup policy, with the following parameters:
  name;; Specify a name for your backup.
  mode {full,light,dataless};; The backup mode. A `FULL` backup is required for restoring a cluster. The default is `full.`
  type;; The backup type. Only `STANDALONE` is supported.
  directory;; The location on the disk to place the backup. You specify an existing directory path as `home/admin/folder`. The `folder` cannot already exist. ThoughtSpot creates the folder when it runs a backup.
  storage_type {NAS,local,S3};; The type of storage you are using. `NAS` storage is recommended for `FULL` backups.
  --config CONFIG;; Specifies the text format of the periodic backup policy config.

tscli backup-policy delete NAME::
  Deletes the backup policy `name`.

tscli backup-policy disable NAME::
  Disables the policy `name`.

tscli backup-policy enable NAME::
  Enables the policy `name`.

tscli backup-policy ls::
  Lists backup policies.

tscli backup-policy show NAME::
  Shows the backup policy `name`

tscli backup-policy status NAME::
  Shows the status of the backup policy `name`.

tscli backup-policy update NAME::
  Prompts an editor for you to edit the backup policy `name`, with the following parameter:
  --config CONFIG;; Specifies the text format of the periodic backup policy config.

[#tscli-calendar]
=== calendar

----
tscli calendar [-h] {create,delete,disable,enable,generate,get,list,update}
----

This subcommand has the following options:

tscli calendar create::
  Creates a new custom calendar, with the following parameters:
  --file_path FILE_PATH;; Path to the CSV file holding custom calendar data.
  --name NAME;; Custom calendar name.
  --separator SEPARATOR;; The separator used in the CSV file. The default is the comma, `,`.
  --no-header-row;; Flag to indicate that the CSV file has no header row. The default is `True`.
  --username USERNAME;; The admin username for ThoughtSpot login.

tscli calendar delete::
  Deletes a custom calendar table from the system, with the following parameters:
  --name NAME;; Deletes the custom calendar _NAME_.
  --username USERNAME;; The admin username for ThoughtSpot login.

tscli calendar disable::
  Disables custom calendar on the cluster.

tscli calendar enable::
  Enables custom calendar on the cluster.

tscli calendar generate::
  Creates a custom calendar table based on given specifications, with the following parameters:
  --name NAME;; A name for the new custom calendar CSV file.
  --start_date START_DATE;; The start date for the custom calendar, in the form `mm/dd/yyyy`.
  --end_date END_DATE;; The end date for the custom calendar, in the form `mm/dd/yyyy`.
  --calendar_type {MONTH_OFFSET,4-4-5,4-5-4,5-4-4};; The type of custom calendar. The default is `MONTH_OFFSET`.
  --month_offset {January,February,March,April,May,June,July,August,September,October,November,December};; The month offset that starts the year, if the calendar is the `MONTH_OFFSET` type. The default is `January`.
  --start_day_of_week DAY_OF_WEEK;; The day for starting the week. The default is `Sunday`.
  --quarter_name_prefix QUARTER_NAME_PREFIX;; The string for the prefix to the quarter.
  --year_name_prefix YEAR_NAME_PREFIX;; The string for the prefix to the year.
  --username USERNAME;; The admin username for ThoughtSpot login.

tscli calendar get::
  Procures data of a custom calendar as a CSV file, with the following parameters:
  --name NAME;; Procures data of custom calendar `NAME`.
  --username USERNAME;; Admin username for ThoughtSpot login.

tscli calendar list::  Procures a list of custom calendars present in the cluster, with the following parameter:
  --username USERNAME;;  Admin username for ThoughtSpot login.

tscli calendar update::  Updates a custom calendar table in the system, with the following parameters:
  --file_path FILE_PATH;; Path to the CSV file holding custom calendar data.
  --name NAME;; Custom calendar name.
  --separator SEPARATOR;; The separator used in the CSV file. The default is comma, `,`.
  --no-header-row;; Flag to indicate that the CSV file has no header row. The default is `True`.
  --username USERNAME;; The admin username for ThoughtSpot login.

[#tscli-callhome]
=== callhome

Provides usage statistics to ThoughtSpot by sending them from the cluster to a secure S3 bucket that ThoughtSpot owns.

----
tscli callhome [-h] {disable,enable,generate-bundle}
----

This subcommand has the following options:

tscli callhome enable --customer_name CUSTOMER_NAME::
  Enables the callhome feature. This feature is enabled by default.
  --customer_name CUSTOMER_NAME;; The parameter `customer_name` takes the form `Shared/CUSTOMER_NAME/stats`.
tscli callhome disable::
  Turns off the callhome feature.
tscli callhome generate-bundle [--d D] [--since SINCE]::
  Generates the callhome stats `*.tar` file, with the following parameters:
  --d D;; Destination folder for the `*.tar` file. There is no default setting.
  --since SINCE;; Grabs `callhome` data from the specified time window, in the past. This should be a human-readable duration string, such as `4h` (4 hours), `30m` (30 minutes), `1d` (1 day). This option generates a `*.tar` file of the cluster metrics and writes it to the specified directory. Here, `SINCE` is how many days back the file must start. There is no default setting

[#tscli-cassandra]
=== cassandra

----
tscli cassandra [-h] {backup,restore}
----

Backs up cassandra.

This subcommand has the following options:

tscli cassandra backup::
  Takes a backup of cassandra, with the following parameters:
  --keyspaces KEYSPACES;; Comma-separated list of keyspaces to back up.
  backup_dir BACKUP_DIR;; The path to the backup directory.
tscli cassandra restore::
  Restores cassandra from a backup, with the following parameter:
  --backup_dir BACKUP_DIR;; The path to the backup directory.

[#tscli-cluster]
=== cluster

----
tscli cluster [-h] {abort-update,bucket-migrate,bucket-name,check,create,download-release,get-config,list-available-releases,list-downloaded-releases,load,restore,resume-update,set-config,set-min-resource-spec,setup-release-host,setup-release-host-key,show-resource-spec,start,status,stop,update,update-hadoop}
----

This subcommand has the following options:

tscli cluster abort-update::
  Aborts an ongoing cluster update, if safe.
tscli cluster bucket-migrate::
  Migrates the cluster to use another S3/GCS bucket, also migrating the data from the current s3 bucket to the new bucket. This command has the following optional parameter:
  --name NAME;; Name of the new bucket.
tscli cluster bucket-name::
  Returns the name of the s3 bucket associated with the cluster, if there is one.
tscli cluster check [--path PATH] [--includes INCLUDES] [--retry RETRY] [--localhost] [--disable-events]::
  Checks the status of all nodes in the cluster, with the following parameters:
  --path PATH;; Specifies the working directory of the diagnostic tool. The default is `/usr/local/scaligent/release`.
  --includes INCLUDES;; Specifies the comma-separated component(s) to be included in the check. The default is `all`.
  --retry RETRY;; The maximum number of retry times if the node is unreachable. The default is `10`.
  --localhost;; Runs cluster checks only on localhost. The default is `False`.
  --disable-events;; Disables raising configuration events. The default is `False`.

tscli cluster create release::
  Creates a new cluster from the release file specified by adding the release number. Used by ThoughtSpot Support when installing a new cluster. For example, `tscli cluster create 6.3.1.tar.gz`. This command has the following parameters:
  --disable_rotate_keys;; Disables cluster rotate key configuration. The default is `False`.
  --enable_cloud_storage {s3a,gcs};; Determines whether to enable Cloud Storage setup, and which storage format to use.
  heterogeneous;; Should be set for heterogeneous clusters. The default is `False`.

tscli cluster download-release release::
  Downloads the specified release to the Hadoop Distributed File Sytem (HDFS) for a subsequent upgrade.

tscli cluster get-config::
  Gets current cluster network and time configuration. Prints JSON configuration to `stdout`. If the system cannot be connected to all interfaces, the command returns an error but continues to function. This command has the following parameters:
  --local;; Gets the config for the local host only. The default is `False`.
  --nodes NODES;; A comma-separated list of specified nodes.

tscli cluster list-available-releases::
  Lists the available releases to update to on the cluster.

tscli cluster list-downloaded-releases::
  Lists the releases downloaded to the cluster.

tscli cluster load backupdir::
  Loads the state from a specified backup directory onto an existing cluster. This command has the following parameters:
  --reuse_cluster CLUSTER;; Add this parameter to reuse the cluster service configs, instead of restoring from the backup directory.
  --cloud_data_dir CLOUD_DATA_DIR;; Add this parameter to specify the cloud path to the restore.

tscli cluster restore --release RELEASE backupdir::
  Restores a cluster on the specified release number using the backup in the specified directory, `backupdir`. If you are restoring from a data-less backup, you must supply the release tarball for the corresponding software release. This command has the following parameters:
  --disable_rotate_keys;; Disables cluster rotate key configurations. The default is `False`.
  --enable_cloud_storage {s3a,gcs};; Determines whether to enable Cloud Storage setup. For example, run `tscli cluster restore --enable_cloud_storage s3a` to enable AWS S3 object storage.
  --heterogeneous;; Must be set for heterogeneous clusters. The default is `False`.

tscli cluster resume-update::
  Resumes in-progress updates, with the following parameter:
  --ignore_if_unhealthy;; Comma-separated list of node IPs on which upgrade is not attempted if they are found to be unhealthy. If a node outside of this list is found unhealthy, the upgrade is aborted.

tscli cluster set-config::
  Sets cluster network and time configuration. Takes JSON configuration from `stdin`. This subcommand has the following parameters:
  --ipv4-only;; Only use ipv4 for node communication. Requires passing ipMap in config unless no-network-change is also specified. The default is `False`.
  --no-network-change;; This flag ensures that a change made with set-config does not update network settings. The default is `False`.
  --allow_network_gateway_mismatch;; Allows a network and gateway mismatch. The default is `False`.

tscli cluster set-min-resource-spec::
  Sets the minimum resource configuration of the cluster, with the following parameter:
  --file FILE;; Specified script with overrides. The default is `False`.

tscli cluster setup-release-host HOST::
  Sets up the release host for Self Service Upgrade, with the specified `HOST`.

tscli cluster setup-release-host-key::
  Sets up the release host api key for Self Service Upgrade.

tscli cluster show-resource-spec::
  Prints default or min.

tscli cluster start::
  Starts the cluster.

tscli cluster status::
  Gives the status of the cluster, including release number, date last updated, number of nodes, pending tables time, and services status. This subcommand has the following parameters:
  --mode {basic,service,table,full,reinstall-os};; Specifies the kind of status message you want.
  --tail::  Prints the details of creation and update progress. The default is `False`.
  --no-orion;; Runs checks not related to orion. The default is `False`.
  --includes INCLUDES;; The name of the service, either falcon or sage.

tscli cluster stop::
  Pauses the cluster, but does not stop storage services.

tscli cluster update::
  Updates an existing cluster on a specified release, with the following parameters:
  --release_version;; Looks for 'release' in the downloaded tarballs and if found, updates to that tarball. The default is `False`.
  --dry_run_only;; Runs only the pre-update checks. The default is `False`.
  --wait_for_falcon_sage;; Waits for Falcon and Sage to be in a serving state before marking an update as complete. The default is `False`.
  --create_snapshot_before_update;; Creates a snapshot automatically before starting an update. The default is `False`.
  --generate_compare_scoreboard;; Generates pre-update and post-update scoreboards and compares them. The default is `False`.
  --update_orion_only;; Only updates orion.
  --ignore_if_unhealthy;; A comma-separated list of node IPs on which upgrade is not attempted in case they are found to be unhealthy. If a node outside of this list is found unhealthy, the upgrade is aborted.

tscli cluster update-hadoop::
  Updates Hadoop/Zookeeper on the cluster.

[#tscli-command]
=== command

----
tscli command [-h] {run}
----

Runs the specified command, `COMMAND`, on all nodes.

This subcommand has the following option:

tscli command run COMMAND::
  This subcommand has the following parameters:
  --nodes NODES;; Space-separated IPs of nodes where to run the command. The default setting is `all`.
  --dest_dir DEST_DIR;; Directory to save the files that contain the output from each node. This is a mandatory parameter.
  --copyfirst COPYFIRST;; Command to copy the executable to required nodes first. The default setting is `False`.
  --timeout TIMEOUT;; Timeout waiting for the command to finish. The default setting is `60`.

[#tscli-dr-mirror]
=== dr-mirror

----
tscli dr-mirror [-h] {start,status,stop}
----

This subcommand has the following options:

tscli dr-mirror start::
  Starts a mirror cluster which will continuously recover from a primary cluster, with the following parameters:
  directory;; Directory where backups of primary cluster can be found
  nodes;; Comma-separated list of IP addresses of nodes in the mirror cluster.
  cluster_name;; The name of the mirror cluster.
  cluster_id;; The ID of the mirror cluster.
  --email EMAIL;; Optional alert email setting. The default is `later`.

tscli dr-mirror status::
  Checks whether the current cluster is running in mirror mode.

tscli dr-mirror stop::
  Stops mirroring on the local cluster.

[#tscili-etl]
=== etl

----
tscli etl [-h] {change-password,disable-lw,download-agent,enable-lw,show-lw}
----

This subcommand has the following options:

tscli etl change-password::
  Changes the Informatica Cloud account password used by ThoughtSpot Data Connect, with the following parameters:
  --admin_username ADMIN_USERNAME;; Specifies the Administrator username for ThoughtSpot.
  --username USERNAME;; Specifies the username for Informatica Cloud.
  --max_wait MAX_WAIT;; The maximum time in seconds to wait for the Data Connect agent to start.
  --isIICS;; This flag identifies whether Informatica is in IICS or ICS mode. By default, Informatica is in ICS mode.

tscli etl disable-lw::
  Disables ThoughtSpot Data Connect.

tscli etl download-agent::
  Downloads the ThoughtSpot Data Connect agent to the cluster, with the following parameters:
  --push_to_all;; Pushes the downloaded installer to all nodes. The default is `False`.
  --proxy_host PROXY_HOST;; Specify your proxy server host for network access.
  --proxy_port PROXY_PORT;; Specify your proxy server port.
  --proxy_username PROXY_USERNAME;; Specify your proxy server username.
  --isIICS;; This flag identifies whether Informatica is in IICS or ICS mode. By default, Informatica is in ICS mode. The default is `False`.

tscli etl enable-lw::
  Enables Data Connect. Contact ThoughtSpot Support for assistance in setting this up. This subcommand has the following parameters:
  --username USERNAME;; Username for Informatica Cloud.
  --thoughtspot_url THOUGHTSPOT_URL;; URL to reach ThoughtSpot.
  --admin_username ADMIN_USERNAME;; Admin username for ThoughtSpot.
  --groupname GROUPNAME;; Name of the secure agent group to use.
  --org_id ORG_ID;; Specifies the Informatica `id` of the company.
  --pin_to PIN_TO;; Specifies the IP address to pin to. If you specify an IP to pin to, that node becomes sticky to the Informatica agent, and will always be used. Defaults to the public IP address of the localhost where this command was run.
  --proxy_host PROXY_HOST;; Proxy server host for network access.
  --proxy_port PROXY_PORT;; Proxy server port.
  --proxy_username PROXY_USERNAME;; Proxy server username.
  --max_wait MAX_WAIT;; Maximum time in seconds to wait for Data Connect agent to start.
  --isIICS;; This flag identifies whether Informatica is in IICS or ICS mode. By default, Informatica is in ICS mode. The default is `False`.

tscli etl show-lw::
  Shows the status of ThoughtSpot Data Connect. It also returns the Informatica username and OrgId.

[#tscli-event]
=== event

----
tscli event [-h] {list}
----

This subcommand and its options manage event notifications. This subcommand has the following option:

tscli event list [-h] [--include INCLUDE] [--since SINCE] [--from FROM] [--to TO] [--limit LIMIT] [--detail] [--summary_contains SUMMARY_CONTAINS] [--detail_contains DETAIL_CONTAINS] [--attributes ATTRIBUTES]::
  The `event list ` subcommand accepts these optional flags:
  --include INCLUDE;; Options are all, config, and notification. The default is `config`.
  --since SINCE;; Grabs events from the specified time window. Should be a human readable duration string, such as `4h` (4 hours), `30m` (30 minutes), or `1d` (1 day).
  --from FROM;; Specifies the starting point for the time window to grab events from. Must be of the form `yyyymmdd-HH:MM`.
  --to TO;; Specifies the ending point for the time window to grab events from. Must be of the form: `yyyymmdd-HH:MM`.
  --limit LIMIT;; Maximum number of events to fetch. The default setting is `0`.
  --detail;; Prints events in detail format. This is not tabular. Default is a tabular summary. The default setting is `False`.
  --summary_contains SUMMARY_CONTAINS;; Summary of the event will be checked for this string. Multiple strings to check for can be specified by separating them with `|` (pipe). The event is returned if it `matches ALL`. Put single quotes around the param value to prevent undesired glob expansion.
  --detail_contains DETAIL_CONTAINS;; Details of the event will be checked for this string. Multiple strings to check for can be specified by separating them with `|` (pipe). The event is returned if it `matches ALL`. Put single quotes around the param value to prevent undesired glob expansion.
  --attributes ATTRIBUTES;; Specify attributes to match as `key=value`. Multiple strings to check for can be specified by separating them with `|` (pipe). The event is returned if it `matches ALL`. Put single quotes around the param value to prevent undesired glob expansion.

[#tscli-feature]
=== feature

----
tscli feature [-h] {get-all-config}
----

This subcommand has the following option:

tscli feature get-all-config::
  Gets the configured features in a cluster. The command returns a list of features, such as custom branding, Data Connect, and callhome, and informs the requester if they are enabled or disabled. This subcommand has the following parameter:
  --proto;; Shows the output as a serialized proto. The default is `False`.

[#tscli-fileserver]
=== fileserver

----
tscli fileserver [-h] {configure,download-release,purge-config,show-config,upload}
----

This subcommand has the following options:

tscli fileserver configure [-h] --user USER [--password PASSWORD]::
  Configures the secure file server username and password for file upload/download, and the call home feature. You only have to issue this command one time, to set up the connection to the secure file server. Reissue this command if the password changes. The parameter `PASSWORD` is optional. If a password is not specified, the system prompts the user to enter it.

tscli fileserver download-release [-h] [--user USER] [--password PASSWORD] [--url URL] [--md5 MD5] [--out OUT] release::
  Downloads the specified release file, including its checksum, and verifies the integrity of release bundle. You must specify the exact release number, such as `6.3.1`. Before using this command for the first time, you must set up the file server connection using `tscli fileserver configure`.  You can then work with a member of the ThoughtSpot Support team because a privileged `user` and a corresponding `password` must be specified to download releases.  This command has the following parameters:
  --user USER;; The fileserver username.
  --password PASSWORD;; The fileserver password.
  --url URL;; Url from where the release needs to be downloaded.
  --md5 MD5;; Md5 of the release tarball, if known.
  --out OUT;; File name of the tar ball.

tscli fileserver purge-config::
  Removes the file server configuration.

tscli fileserver show-config::
  Shows the file server configuration.

tscli fileserver upload [-h] [--user USER] [--password PASSWORD] --file_name FILE_NAME --server_dir_path SERVER_DIR_PATH::
  Uploads the specified file to the specified directory on the secure file server. You may optionally specify the `user` and `password` to bypass the credentials specified when configuring the file server connection with `tscli fileserver configure`. Before using this command for the first time, you must set up the file server connection using `tscli fileserver configure`. This command uses the following flags:
  --user USER;; Username of the fileserver.
  --password PASSWORD;; Password of the fileserver. This is required and the command prompts you for it if you do not supply it.
  --file_name FILE_NAME;; Local file to upload.
  --server_dir_path SERVER_DIR_PATH;; Directory path on fileserver. The `SERVER_DIR_PATH` parameter specifies the directory for file upload. It is based on customer name, and takes the form `/Shared/support/customer_name`.

[#tscli-firewall]
=== firewall

----
tscli firewall [-h] {close-ports,disable,enable,open-ports,status}
----

This subcommand has the following options:

tscli firewall close-ports --ports PORTS::
  Closes specified ports through firewall on all nodes. Accepts a comma-separated list of ports. Only closes ports that were previously opened using `open-ports`, and ignores ports that were not opened with `open-port`, or closed ports. Some essential ports are always kept open, such as `ssh`; they are not affected by this command or by `open-ports`.

tscli firewall disable::
  Disables firewall.

tscli firewall enable::
  Enables firewall.

tscli firewall open-ports --ports PORTS::
  Opens specified ports through a firewall on all nodes. Accepts a comma-separated list of ports. Ignores open ports. Some essential ports are always kept open, such as `ssh`; they are not affected by this command or by `close-ports`.

tscli firewall status::
  Shows whether firewall is currently enabled or disabled.

[#tscli-hdfs]
=== hdfs

----
tscli hdfs [-h] {leave-safemode}
----

This subcommand has the following option:

tscli hdfs leave-safemode::
  Command to get HDFS `namenodes` out of `safemode`, with the following parameter:
  --timeout TIMEOUT;; Specifies timeout when waiting for the command to finish. The default is `5`.

[#tscli-ipsec]
=== ipsec

----
tscli ipsec [-h] {disable,enable,status}
----

This subcommand has the following options:

tscli ipsec disable::
  Disables IPSec.

tscli ipsec enable::
  Enables IPSec.

tscli ipsec status::
  Shows IPSec status on all nodes.

[#tscli-ldap]
=== ldap

----
tscli ldap [-h] {add-cert,configure,purge-configuration}
----

This subcommand has the following options:

tscli ldap add-cert name cert_file::
  Adds an SSL certificate for LDAP. Use only if LDAP has already been configured without SSL, when you are adding SSL. Use `name` to supply an alias for the certificate you are installing. Use `cert-file` to specify the certificate file.

tscli ldap configure::
  Configures LDAP using an interactive script.

tscli ldap purge-configuration::
  Purges (removes) any existing LDAP configuration.

[#tscli-logs]
=== logs

----
tscli logs [-h] {collect,runcmd}
----

Manages the logging behavior.

This subcommand has the following options:

tscli logs collect [-h] [--include INCLUDE] [--exclude EXCLUDE] [--since SINCE] [--from FROM] [--to TO] [--out OUT] [--maxsize MAXSIZE] [--sizeonly] [--nodes NODES]::
  Extracts logs from the cluster. Does not include any logs that were dropped because of log rotation. This subcommand has the following parameters:
  --include INCLUDE;; Specifies a comma-separated list of logs to include. Each entry is either a "selector" or a glob for matching files. Selectors must be among: `all`, `orion`, `system`, `ts`. Anything starting with `/` is assumed to be a glob pattern, and it is interpreted through `find(1)`. Other entries are ignored. Put single quotes around the param value to prevent undesired glob expansion. The default is `all`.
  --exclude EXCLUDE;; Comma separated list of logs to exclude. Applies to the list selected by `--include`. Params are interpreted just like in `--include`.
  --since SINCE;; Grabs logs from the specified time window in the past. Should be a human-readable duration string, such as `4h` (4 hours), `30m` (30 minutes), `1d` (1 day).
  --from FROM;; Timestamp where collection begins; must be of the form `yyyymmdd-HH:MM`.
  --to TO;; Timestamp where collection ends; must be of the form `yyyymmdd-HH:MM`.
  --out OUT;; Tarball path for writing logs from each node. The default setting is `/tmp/logs.tar.gz`.
  --maxsize MAXSIZE;; Only fetch logs if size is smaller than this value. Can be specified in megabytes or gigabytes, such as `100MB`, `10GB`.
  --sizeonly;; Do not collect logs. Just report the size. The default setting is `False`.
  --nodes NODES;; Comma separated list of nodes from where to collect logs. Skip this to use all nodes.

tscli logs runcmd [-h] --cmd CMD [--include INCLUDE] [--exclude EXCLUDE] [--since SINCE] [--from FROM] [--to TO] [--outfile OUTFILE] [--outdir OUTDIR] [--cmd_infmt CMD_INFMT] [--cmd_outfmt CMD_OUTFMT] [--nodes NODES]::
  Runs a Unix command on logs in the cluster matching the given constraints. Results are reported as text dumped to standard out, the specified output file, or as tarballs dumped into the specified directory. Accepts these optional flags:
  --cmd CMD;; Unix-Command to run on the selected logs. Use single quotes to escape spaces and other common characters. Note the language used to specify CMDSTR has the following rules:

    * A logfile and its corresponding result file can be referred to by the keywords `SRCFILE` and `DSTFILE`. For example, `cp SRCFILE DSTFILE`.
    * Without any reference to `DSTFILE` in CMDSTR, `DSTFILE` will be appended to CMDSTR for output redirection. For example, `du -sch SRCFILE` gets auto-translated to `du -sch SRCFILE > DSTFILE`.
    * Without any reference to `SRCFILE`, the contents of the log are streamed to CMDSTR by pipe. For example, `tail -n100 | grep ERROR` gets auto-translated to `cat SRCFILE | tail -n100 |     grep ERROR > DSTFILE`.
  --include INCLUDE;; Comma-separated list of logs to include. Each entry is either a "selector" or a glob for matching files. Selectors must be one of `all`, `orion`, `system`, or `ts`. Anything that starts with `/` (forward slash) is assumed to be a glob pattern and interpreted through `find(1)`. Other entries are ignored. Use single quotes around the parameter value to prevent undesired glob expansion. The default setting is `all`.
  --exclude EXCLUDE;; Comma separated list of logs to exclude. Applies to the list selected by `--include`. Parameters are interpreted just like in `--include`.
  --since SINCE;; Grabs logs from the specified time window in the past. Should be a human-readable duration string, such as `4h` (4 hours), `30m` (30 minutes), or `1d` (1 day).
  --from FROM;; Timestamp where collection begins; must be of the form `yyyymmdd-HH:MM`.
  --to TO;; Timestamp where collection ends; must be of the form `yyyymmdd-HH:MM`.
  --outfile OUTFILE;; File path for printing all results. By default printed to `stdout`.
  --outdir OUTDIR;; Directory path for writing results with original directory structure from each node. Used as an alternative to printing output to `outfile/stdout`.
  --cmd_infmt CMD_INFMT;; Specify if the input file should be compressed or uncompressed before running `CMD`. Use `C` for compressed, and `U` for uncompressed. Don't use this flag if `CMD` works on both.
  --cmd_outfmt CMD_OUTFMT;; Specify if `OUTFILE` generated by `CMD` should be compressed or uncompressed. Use `C` for compressed, and `U` for uncompressed. Don't use this flag if output file is of the same format as the input file.
  --nodes NODES;; Comma-separated list of nodes to run command on. Skip this to use all nodes.

[#tscli-tiles]
=== map-tiles

----
tscli map-tiles [-h] {disable,enable,status}
----

This subcommand has the following options:

tscli map-tiles enable [-h] [--online] [--offline] [--tar TAR] [--md5 MD5]::
  Enables ThoughtSpot's map tiles. Used when constructing geo map charts. If you don't have internet access, you must download the map tiles tar and md5 files, and append the following to the `tscli` command:
  --online;; Downloads `maptiles` tar from internet. The default setting is `True`.
  --offline;; Specifies that you are using `maptiles` tar from a local disk. The default setting is `False`.
  --tar TAR;; Specified tar file for map-tiles.
  --md5 MD5;;  Specified md5 file for map-tiles.

tscli map-tiles disable::
  Disables map-tiles functionality.

tscli map-tiles status::
  Checks whether map-tiles are enabled, with the following parameter:
  --md5 MD5;; Specified md5 checksum for validation.

[#tscli-monitoring]
=== monitoring

----
tscli monitoring [-h] {set-config,show-config}
----

This subcommand has the following options:

tscli monitoring set-config [-h] [--email EMAIL] [--clear_email] [--heartbeat_interval HEARTBEAT_INTERVAL] [--heartbeat_disable]::
  Sets the monitoring configuration. The `monitoring` subcommand accepts the following optional flags:
  --email EMAIL;; Comma separated list (no spaces) of email addresses where the cluster sends monitoring information.
  --clear_email;; Disables monitoring emails by clearing email configuration. The default is `False`.
  --heartbeat_interval HEARTBEAT_INTERVAL;; Specify a heartbeat email generation interval in seconds. The interval should be greater than 0.
  --heartbeat_disable;; Disables heartbeat email generation. The default is `False`.

tscli monitoring show-config::
  Shows the monitoring configuration.

[#tscli-nas]
=== nas

----
tscli nas [-h] {ls,mount-cifs,mount-nfs,unmount}
----

This subcommand has the following options:

tscli nas ls [-h]::
  Lists mounts managed by NAS mounter service.

tscli nas mount-cifs [-h] --server SERVER [--path_on_server PATH_ON_SERVER] --mount_point MOUNT_POINT--username USERNAME --password PASSWORD [--uid UID] [--gid GID] [--options OPTIONS]::
  Mounts a CIFS device on all nodes. Accepts the following optional flags:
  --server SERVER;; IP address or DNS name of CIFS service. For example, `10.20.30.40`.
  --path_on_server PATH_ON_SERVER;; Filesystem path on the CIFS source server to mount NAS. For example, `/a`. The default setting is `/` (forward slash).
  --mount_point MOUNT_POINT;; Directory on all cluster nodes where the NFS filesystem should be mounted on the target. If this directory does not exist, the command creates it. If this directory already exists, the command uses it for mounting. For example, `/mnt/external`.
  --username USERNAME;; Username to connect to the CIFS filesystem.
  --password PASSWORD;; CIFS password for `--username`.
  --uid UID;; The _UID_ that owns all files or directories on the mounted filesystem when the server does not provide ownership information. See `man mount.cifs` for more details. The default setting is `1001`.
  --gid GID;; The `GID` that owns all files or directories on the mounted filesystem when the server does not provide ownership information. See `man mount.cifs` for more details. The default is `1001`.
  --options OPTIONS;; Other command-line options to forward to the `mount.cifs` command. The default setting is `noexec`.

tscli nas mount-nfs [-h] [--server SERVER] [--path_on_server PATH_ON_SERVER] [--mount_point MOUNT_POINT] [--options OPTIONS] [--protocol {nfs,nfs4}]::
  Mounts the NFS filesystem on all nodes. Accepts the following optional flags:
  --server SERVER;; IP address or DNS name of NFS service. For example, `10.20.30.40`.
  --path_on_server PATH_ON_SERVER;; Filesystem path on the NFS source server. For example, `/a/b/c/d`. The default setting is `/`.
  --mount_point MOUNT_POINT;; Directory on all cluster nodes of the target system. If this directory does not exist, the command creates it. If this directory already exists, the command uses it for mounting. For example, `/mnt/external`.
  --options OPTIONS;; Command-line options to mount. The default setting is `noexec`.
  --protocol PROTO;; Protocol to use for mounting, either `nfs` or `nfs4`. The default is `nfs`.

tscli nas unmount [-h] --dir DIR::
  Unmounts all devices from the specified directory, `DIR`. This command returns an error if nothing is currently mounted on this directory through `tscli nas mount`.

[#tscli-node]
=== node

----
tscli node [-h] {check,ls,status}
----

This subcommand has the following options:

tscli node check [-h] [--select { reinstall-preflight}] [--secondary SECONDARY]::
  Runs checks per node. Accepts the following flags:
  --select { reinstall-preflight};; Specifies the type of node check. The default setting is `reinstall-preflight`.
  --secondary SECONDARY;; Secondary drive for `reinstall-preflight`. The default setting is `sdd`.

tscli node ls [-h] [--type {all,healthy,not-healthy}]::
  Lists all nodes in the cluster, with the following parameter:
  --type {all,healthy,not-healthy};; Filters by node state. The default setting is `all`.

tscli node status::
  Get Node status for the operation specified by mode, with the following parameters:
  --mode { reinstall-os};; Mode for running node status.
  --tail;; Prints the details of create and update progress. The default is `False`.

[#tscli-notification]
=== notification

----
tscli notification [-h] {set-apns-config}
----

This subcommand has the following option:

tscli notification set-apns-config::
  Sets APNS configuration.

[#tscli-onboarding]
=== onboarding

----
tscli onboarding [-h] {configure,purge-configuration}
----

Onboarding helps application administrators to bulk update user information.
In particular, it configures various in-app email options.

This subcommand has the following options:

tscli onboarding --help::
  Prints help for the onboarding configuration.

tscli onboarding configure::
  Configures the onboarding through a series of steps. Asks the user to provide information necessary for onboarding-related functionality, such as:

. Company name
. Product name
. Should welcome emails be enabled?
 ** Send welcome emails to new users
 ** Support email
 ** Custom message to include in emails
 ** URL of the ThoughtSpot instance
 ** URL of the ThoughtSpot documentation

 tscli onboarding purge-configuration::
   This command removes all previous onboarding configuration.

[#tscli-patch]
=== patch

----
tscli patch [-h] {abort-apply,apply,ls,resume-apply,resume-rollback,rollback,status}
----

This subcommand has the following options:

tscli patch abort-apply::
  Aborts an ongoing patch-apply, if safe.

tscli patch apply [-h] [release]::
  Applies the patch on an existing cluster, with the specified `release`. Accepts the following flag:
  --skip-check;;  When set, skips all pre-apply checks. The default is `False`.

tscli patch ls [-h]  [--applied] [--rolled_back] [--service SERVICE] [--md5 MD5] [--history]::
  Lists the patches currently applied. Accepts the following flags:
  --applied;; Shows only the patches applied since the last full release. The default setting is `False`.
  --rolled_back;; Shows only the patches rolled back since the last full release. The default setting is `False`.
  --service SERVICE;; Shows patches filtered by service.
  --md5 MD5;; Shows the details of the patch specified.
  --history;; Shows the history of all patches applied/rollback releases. The default setting is `False`.

tscli patch resume-apply [-h]::
  Resumes patch apply.

tscli patch resume-rollback [-h]::
  Resumes patch roll-back.

tscli patch rollback md5 [-h]::
  Rolls back a specified patch from an existing cluster with the following parameters:
  md5;; Specifies the md5 of the patch to be rolled back.
  --skip_check;; When set, skips all pre-apply checks while rolling back. The default is `False`.

tscli patch status::
  Shows the progress of patch operation.

[#tscli-rpackage]
=== rpackage

----
tscli rpackage [-h] {add,delete,list}
----

Manages R packages available to SpotIQ.

This subcommand has the following options:

tscli rpackage add [-h] [--repo REPO] [--timeout TIMEOUT] [--dest_dir DEST_DIR] [--nodes NODES] package_name::
  Command to add an R package, `package_name`, to the cluster. Accepts the following flags:
  --repo REPO;; Specifies the URL of a specific source repository of packages, to download them. The default is `http://cran.rstudio.com/`.
  --timeout  REPO;; Timeout waiting for the R package to install. The default is `60`.
  --dest_dir REPO;; Directory where output of this command will be placed.
  --nodes NODES;; Space-separated list of IPs for nodes to run the command on. The default setting is `all`.

tscli rpackage delete [-h] [--timeout TIMEOUT] [--dest_dir DEST_DIR] [--nodes NODES] package_name::
  Command to delete an installed R package from the cluster. Accepts the following flags:
  --timeout REPO;; Timeout waiting for the R package to be removed. The default is 60.
  --dest_dir REPO;; Directory where the output of this command should be saved.
  --nodes NODES;; Space-separated list of node IPs on which to run the command. The default setting is `all`.

tscli rpackage list [-h] [--detailed]::
  List all R packages installed on the cluster, with the following parameter:
  --detailed::  Command to get install information as well as package names. The default is `False`.

[#tscli-saml]
=== saml

----
tscli saml [-h] {configure,purge-configuration}
----

This subcommand has the following options:

tscli saml configure [-h]::
  Configures SAML.

tscli saml purge-configuration::
  Purges any existing SAML configuration.

To see a list of prerequisites, refer to xref:configure-SAML-with-tscli.adoc[Configure SAML].

[#tscli-scheduled-pinboards]
=== scheduled-pinboards

----
tscli scheduled-pinboards [-h] {disable,enable}
----

This subcommand has the following options:

tscli scheduled-pinboards disable::
  Disables scheduled pinboards for the cluster.

tscli scheduled-pinboards enable [-h]::
  Enables scheduled Pinboards, which are disabled in prod clusters by default.

NOTE: When you enable scheduled Pinboards, you should also configure a list of intended email domains.
Contact xref:contact.adoc[ThoughtSpot Support]  for help on how to configure this list.

[#tscli-set]
=== set

----
tscli set [-h] {heterogeneous}
----

This subcommand has the following option:

tscli set heterogeneous::
  Sets or unsets a cluster as heterogeneous, with the following parameters:
  --set;; Marks the cluster heterogeneous. The default is `True`.
  --unset;; Marks the cluster homogeneous. The default is `False`.

[#tscli-smtp]
=== smtp

----
tscli smtp [-h] {remove-mailfromname,remove-mailname,remove-relayhost,remove-saslcredentials,reset-canonical-mapping,set-canonical-mapping,set-mailfromname,set-mailname,set-relayhost,set-saslcredentials,show-canonical-mapping,show-mailfromname,show-mailname,show-relayhost}
----

This subcommand has the following options:

tscli smtp remove-mailfromname::
  Removes current cluster mail from name. It is the first half of the email address, the part before the @ sign. In _example@company.com_, it is _example_.

tscli smtp remove-mailname::
  Removes current cluster mail name. It is the second half of the email address, the part after the @ sign. In _example@company.com_, it is _company_.

tscli smtp remove-relayhost::
  Removes current cluster relay host.

tscli smtp remove-saslcredentials::
  Clears SASL credentials and disables SMTP AUTH.

tscli smtp reset-canonical-mapping::
  Deletes the current postmap mapping.

tscli smtp set-canonical-mapping [-h] new_key new_value::
  Sets a new Postmap mapping. You must specify the `new_key` and the `new_value`.

tscli smtp set-mailfromname mailfromname::
  Sets the name from where email alerts are sent for the cluster. It is the first half of the email address, the part before the @ sign. In _example@company.com_, it is _example_.

+tscli smtp set-mailname mailname::
  Sets the domain from where email alerts are sent for the cluster. It is the second half of the email address, the part after the @ sign. In _example@company.com_, it is _company_.

tscli smtp set-relayhost [-h] [--force FORCE] relayhost::
  Sets the specified `relayhost` for SMTP (email) sent from the cluster. Accepts the following flag:
  --force FORCE;; Set even if relay host is not accessible. The default setting is `False`.

  * On ThoughtSpot release 6.1.1 or later, and on release 6.0.5, you can specify a custom port to connect to the relay host. If you do not specify a port, the system uses the default recommended port, port 25. Use a custom port if port 25 is blocked in your environment.
  * To use the default port, run the setup command normally: `$ tscli smtp set-relayhost IP_address`. To use a custom port instead of port 25, run the setup command, specifying the port you want to use: `$ tscli smtp set-relayhost IP_address:custom_port`.
  * If you are on 6.1 rather than 6.1.1, or an a version earlier than 6.0.5, contact xref:contact.adoc[ThoughtSpot Support] to help you set up a custom port.

tscli smtp set-saslcredentials::
  Sets SASL credentials and enables SMTP AUTH.

tscli smtp show-canonical-mapping::
  Shows the current postmap mapping.

tscli smtp show-mailfromname::
  Shows the mailname, from which email alerts are sent, for the cluster.

tscli smtp show-mailname::
  Shows the mailname, from which email alerts are sent, for the cluster.

tscli smtp show-relayhost::
  Shows the relay host for SMTP (email) sent from the cluster. If the relay host is not configured, the command returns `NOT FOUND`.

[#tscli-snapshot]
=== snapshot

----
tscli snapshot [-h] {backup,create,delete,ls,pin,restore,unpin,update-ttl,validate}
----

To learn more about snapshots and backups, see xref:choose-strategy.adoc[Understand the backup strategies].

This subcommand has the following options:

tscli snapshot backup [-h] [--mode {full,light,dataless}] [--type {full,incremental}] [--base BASE] [--storage_type {local,nas}] [--remote] [--no-orion-master] name out::
  Pulls snapshot out as a backup. This command has two required elements: `name` and `out`. The rest of the flags are optional:
  name;; Name of snapshot to pull out as a backup. To list all snapshots, run `tscli snapshot ls`.
  out;; Directory where backup will be written. The directory must not already exist.
  --mode {full,light,dataless};; Mode of backups. The default is `full`.
  --type {full,incremental};; Type of backup. Incremental backup is not implemented. The default setting is `full`.
  --base BASE;; Based snapshot name for incremental backup. Incremental backup is not implemented yet.
  storage_type {local,nas};; Storage type of output directory. The default is `local`.
  --remote;; Takes backup through orion master. The default is `False`.
  --no-orion-master;; Specifies whether orion master is available during backup. The default is `False`.
  --bucket_name BUCKET_NAME;; The name of the s3/gcs bucket to create the backup. The platform depends on the storage type of the cluster. You must specify `--storage_type` as `cloud`.
  --staging_dir STAGING_DIR;; Used for staging hdfs data in cloud based backups. No effect in non-cloud based backups. You must specify `--storage_type` as `cloud`.

tscli snapshot create [-h] name reason ttl::
  Creates a new snapshot with the specified `name` and `reason`. This command does not accept `.` (periods). It does accept `-` (dashes or hyphens). The `ttl` parameter is the number of days after which this snapshot is automatically deleted. A value of `-1` disables automatic deletion.

tscli snapshot delete [-h] name::
  Deletes the named snapshot.

tscli snapshot ls [-h]::
  Lists available snapshots.

tscli snapshot pin [-h] name::
  Pins a snapshot with the specified _name_ so it cannot be deleted or garbage collected.

tscli snapshot restore [-h] [--allow_release_change] [--only_service_state] name::
  Restores cluster to the specified snapshot _name_. Accepts the following flags:
  --allow_release_change;; Allows restoration to a snapshot at a different release. The default is `False`.
  --only_service_state;; Restores only the service state. The default is `False`.

tscli snapshot unpin [-h] name::
  Unpins the specified snapshot _name_ so it can be deleted or garbage-collected.

tscli snapshot update-ttl [-h] [--disable DISABLE] name ttl::
  Updates manual snapshot garbage collection policy. Accepts the following flags:
  name;; Specifies which snapshot to update.
  ttl;; This is the "time-to-live" value. Use a positive value to increase `ttl`. Use negative values to decrease it.
  --disable DISABLE;; Disables manual snapshot garbage collection. Setting this value to `True` overrides any `ttl` value. The default is `False`.

tscli snapshot validate::
  Validates a specified snapshot _name_ to ensure it is not corrupt.

[#tscli-snapshot-policy]
=== snapshot-policy

----
tscli snapshot-policy [-h] {disable,enable,show,update}
----

This subcommand has the following options:

tscli snapshot-policy disable [-h]::
  Disables a specified snapshot policy.

tscli snapshot-policy enable -h::
  Enables a specified snapshot policy.

tscli snapshot-policy show [-h]::
  Shows snapshot policy.

tscli snapshot-policy update [-h] [--config CONFIG]::
  Updates periodic snapshot config, with the following parameter:
  --config CONFIG;; Text format of periodic backup policy config.

[#tscli-socialproof]
=== socialproof

----
tscli socialproof [-h] {disable,enable}
----

This subcommand has the following options:

tscli socialproof disable::
  Disables socialproof.

tscli socialproof enable::
  Enables socialproof.

[#tscli-ssl]
=== ssl

----
tscli ssl [-h] {add-cert,add-valid-hosts,clear-min-tls-version,off,on,remove-valid-hosts,rm-cert,set-alert-days,set-min-tls-version,status,tls-status}
----

This subcommand manages the SSL configuration.

To use SSL, the following ports must be open:

* 443
* 80

Refer to xref:SSL-config.adoc[Configure SSL] for more information.

This subcommand has the following options:

tscli ssl add-cert [-h] key certificate valid_hosts::
  Adds a specified SSL certificate and key pair. Requires a comma-separated host list. Nginx will reject if the hosts are not valid. This command has the following optional flag:
  --force;; Forces setting of key and certification without validation. The default is `False`.

tscli ssl add-valid-hosts [-h] VALID_HOSTS::
  Enables host validation for the specified host(s). Helps improve security. This feature is for all customers that have or are planning to enable SSL. Multiple hosts must be separated by a comma (,).

  * To ensure that the valid host is *cluster1.corp.example.com*, run the command `tscli ssl add-valid-hosts cluster1.corp.example.com`.
  * To allow all hosts that have the suffix *corp.example.com*, run the command `tscli ssl add-valid-hosts *.corp.example.com`. Use the wild card within the hostname.
  * To allow multiple valid hosts, such as both **.corp.example.com* and *cluster1*, run the command `tscli ssl add-valid-hosts *.corp.thoughtspot.com,cluster1`.

tscli ssl clear-min-tls-version [-h]::
  Clears any customizations for the minimum TLS version to support.

tscli ssl off::
  Disables SSL. Disabling SSL will stop users from seeing a security warning when accessing ThoughtSpot from a browser if there is no SSL certificate installed.

tscli ssl on [-h]::
  If SSL is enabled and there is no certificate, users see a security warning when accessing ThoughtSpot from a browser. To bypass this warning, users must click *Advanced* and then *Proceed*.

tscli ssl remove-valid-hosts::
  Turns off validation of hosts.

tscli ssl rm-cert::
  Removes the existing SSL certificate, if any. Reverts to default self-signed certificate.

tscli ssl set-alert-days days::
  Sets alert threshold for a specifed number of days to check before SSL certificate expires. The default is `30 days`.

tscli ssl set-min-tls-version {1.0,1.1,1.2}::
  Sets a specified minimum supported TLS version. Sets the minimum SSL version to be supported by the ThoughtSpot application. You must ensure that client browsers are enabled for this version or newer.

tscli ssl status::
  Shows whether SSL authentication is enabled or disabled.

tscli ssl tls-status::
  Prints the status of TLS support.

[#tscli-sssd]
=== sssd

----
tscli sssd {clear-sudo-group,disable,disable-openldap,enable,enable-openldap,set-sudo-group}
----

This subcommand uses system security services daemon (SSSD), and has the following options:

[#tscli-sssd-clear-sudo-group]
tscli sssd clear-sudo-group ACTIVE_DIRECTORY_GROUP_NAME::
  Clears a specified AD sudo group so that they no longer have `sudo` permissions.

[#tscli-sssd-disable]
tscli sssd disable::
  Disables Active Directory access. Leaves identity domain and removes AD sudo group.

[#tscli-sssd-disable-openldap]
tscli sssd disable-openldap::
  Disables OpenLDAP integration.

NOTE: If you mapped your OpenLDAP admin user to ThoughtSpot's local admin user through the Ansible playbook while deploying ThoughtSpot on RHEL, do not run this command. If you ran `tscli sssd enable-openldap` and also mapped your OpenLDAP admin user to ThoughtSpot's local admin user through the Ansible playbook, contact xref:contact.adoc[ThoughtSpot Support].

[#tscli-sssd-enable]
tscli sssd enable --user USER --domain DOMAIN::
  Enables system Active Directory (AD) user access on a single node. Prompts for password credentials. The user must have permission to join a computer or VM to the domain. This subcommand has the following parameters:
  --user USER;; You must specify the user to receive access.
  --domain DOMAIN::  You must specify the domain.

[#tscli-sssd-enable-openldap]
tscli sssd enable-openldap::
  Connects to your OpenLDAP server and allows users to SSH into your ThoughtSpot cluster with their LDAP credentials, without using the fully qualified domain name.

NOTE: If you mapped your OpenLDAP admin user to ThoughtSpot's local admin user through the Ansible playbook while deploying ThoughtSpot on RHEL, do not run this command.

This subcommand has the following parameters:
  --server_base_dn SERVER_BASE_DN;; Specify the LDAP server base distinguished name, in the form _dc=<optional_subdomain>,dc=<domain>,dc=<top-level-domain>_, such as _dc=thoughtspot,dc=com_.
  --server_uri SERVER_URI;; Specify the LDAP server uniform resource identifier, in the form _ldap://<ldap_server_IP>_.

[#tscli-sssd-set-sudo-group]
tscli sssd set-sudo-group ACTIVE_DIRECTORY_GROUP_NAME::
  Allows `sudo` permissions for a specified AD group. For more about setting up Active Directory access, see xref:active-directory-based-access.adoc[Enable Active Directory based access].

[#tscli-storage]
=== storage

----
tscli storage [-h] {gc,df}
----

This subcommand has the following options:
tscli storage gc [-h] [--log_age LOG_AGE] [--force] [--localhost_only]::  Garbage collects unused storage.

Before issuing this command, you must stop the cluster using `tscli     cluster stop`.

After garbage collection finishes, you can restart the cluster with `tscli cluster start`.

This command frees space in the following directories:

 /tmp
     /usr/local/scaligent/logs/
     /export/logs/orion
     /export/logs/oreo
     /export/logs/hadoop
     /export/logs/zookeeper
     cores

The `storage gc` subcommand accepts these optional flags:

  --log_age LOG_AGE;; Deletes logs older than a specified number of hours. Use a non-zero value, because zero deletes all temporary files, including the ones that are closed temporarily while passing from one component to the next. The default setting is `4`.
  --force;; Forces deletion of all logs and temporary files regardless of age. Only run this command on a stopped cluster. To stop a cluster, run `tscli cluster stop`. The default setting is `False`.
  --localhost_only;; Only removes the logs on the local host. If not specified, the command acts on the entire cluster.

tscli storage df [--mode disk|hdfs]::
  Checks the disk usage on the relevant mounts. Returns output similar to the Linux system command `df -h directory`.

[#tscli-support]
=== support

----
tscli support [-h]
   {bundle, restart-remote, rm-admin-email, rm-admin-phone, rm-feedback-email,
    set-admin-email, set-admin-phone, set-debug-ui-password, set-feedback-email,
    set-remote, show-admin-email, show-admin-phone, show-feedback-email,
    show-remote, start-remote, stop-remote}
----

This subcommand has the following options:

tscli support bundle [-h] [--include INCLUDE] [--exclude EXCLUDE] [--list_selectors] [--since SINCE] [--from FROM] [--to TO] [--out OUT] [--nodes NODES]::
  This subcommand specifies the support bundle. It uses the following flags:
  --include INCLUDE;; Comma-separated list of selectors to include. Each entry is either a "selector" or a glob for matching files. To see the list of valid selectors, run this command with `--list_selectors`. You may also specify `all` to get all selectors and logs, and `basic` to get only the basic selectors. Selectors can be used for logs collection: `all`, `orion`, `system`, `ts`, or the name of a service. Anything that starts with `/` (forward slash) is assumed to be a glob pattern, and is interpreted through `find(1)`. Other entries are ignored. Use single quotes around the parameter value to prevent undesired glob expansion. Use `all` to collect all selectors and all logs. The default setting is `all_but_logs`.
  --exclude EXCLUDE;; Comma-separated list of selectors to exclude. Applies to the list selected by `--include`. Parameters are interpreted in the same manner as in `--include`. Use the special keyword `logs` to exclude logs collection altogether. There is no default setting.
  --list_selectors;; Lists the selectors available for `--include` and `--exclude`, and then exits. The default setting is `False`.
  --since SINCE;; Grabs logs from the specified time window. Should be a human-readable duration string, such as `4h` (4 hours), `30m` (30 minutes), `1d` (1 day). There is no default setting.
  --from FROM;; Timestamp when collection begins. Must be of the form: `yyyymmdd-HH:MM`. There is no default setting.
  --to TO;; Timestamp when collection ends. Must be of the form: `yyyymmdd-HH:MM`. There is no default setting.
  --out OUT;; Tarball path for dumping the support bundle. The default setting is `/tmp/support_bundle.tar.gz`.
  --nodes NODES;; Comma-separated list of nodes from which the system collects logs. Skip this to use all nodes. There is no default setting.

tscli support restart-remote::
  Restarts remote support.

tscli support rm-admin-email::
  Removes the email address for contacting the customer administrator. Replaces it with the default ThoughtSpot Support email address.

tscli support rm-feedback-email::
  Removes the email address for product feedback. Replaces it with the default ThoughtSpot Support email address.

tscli support rm-admin-phone::
  Removes the phone number for contacting the customer administrator. Replaces it with the default ThoughtSpot Support phone number.

tscli support set-admin-email email::
  Sets the specified email address for contacting the customer administrator.

tscli support set-feedback-email email::
  Sets the specified email address for sending feedback.

tscli support set-admin-phone phone_number::
  Sets the specified phone number for contacting the customer administrator. Specify a phone number using any value, such as `+1 800-508-7008 Ext. 1`.

tscli support set-remote [-h] [--addr ADDR] [--user USER]::
  Configures the cluster for remote support through SSH tunneling, where _`ADDR`_ is the support address, such as `tunnel.thoughtspot.com`, and _`USER`_ is the support username.

tscli support show-admin-email::
  Shows the email address for the customer administrator, if set.

tscli support show-feedback-email::
  Shows the email address for product feedback, if set.

tscli support show-admin-phone::
  Shows the phone number for the customer administrator, if set.

tscli support show-remote::
  Prints the status and configuration of remote support.

tscli support start-remote::
  Starts remote support.

tscli support stop-remote::
  Stops remote support.

[#tscli-tokenauthentication]
=== tokenauthentication

----
tscli tokenauthentication [-h] {disable,enable}
----

This subcommand has the following options:

tscli tokenauthentication enable::
  Configures token-based login.

tscli tokenauthentication disable::
  Purges existing token-based login configuration.
