= Users
:last_updated: 02/11/2021
:linkattrs:
:page-aliases: /end-user/introduction/introduction.adoc
:experimental:

////
This ThoughtSpot User Guide contains information on navigating and searching data with ThoughtSpot. It assists you with starting new searches, managing your pinboards, and troubleshooting.
////
ThoughtSpot enables you to view and analyze your data through a search-based user interface.
You can create your searches quickly and easily, just by typing them into a search bar, like you do when using an Internet search engine.
ThoughtSpot makes it easy to see your data, get your questions answered, create interactive graphs, and customize pinboards.
You don't need to understand how ThoughtSpot stores information, attend days of training, or know SQL to do these things.
Collaboration and security features make it easy to protect sensitive data, and safely share information with others.

ThoughtSpot gives administrators the ability to modify data properties to meet business needs.
Administrators can specify search synonyms for common terms, boost the importance of a column in search results, or format how the data appears.
So, if you are not getting the answers you expect when using ThoughtSpot, check with your ThoughtSpot administrator to see if some settings can be changed.

Depending on the size and structure of your organization, you may have colleagues who interact with ThoughtSpot in very specific fashion according to the following roles, or a hybrid of these roles:

xref:business-user.adoc[]::

xref:analyst.adoc[]::

xref:data-engineer.adoc[]::

xref:it-ops.adoc[]::

xref:developer.adoc[]::
