= User onboarding experience
:last_updated: 10/07/2019
:experimental:
:page-partial:
:linkattrs:
:description: ThoughtSpot's onboarding is quick and intuitive; you can learn to use the application very quickly and efficiently.


ThoughtSpot's onboarding is quick and intuitive; you can learn to use the application very quickly and efficiently.

When you begin using ThoughtSpot, the onboarding process starts automatically and guides you through a few basic scenarios.

Usually, you receive an email welcoming you to the onboarding process at ThoughtSpot.

To repeat user onboarding, see xref:user-profile.adoc#onboarding[Revisit onboarding].

[#onboarding-user]
== How onboarding works for the user

Your onboarding experience begins when you log in for the first time.

. *Get Started*
+
The initial welcome screen provides an overview of the onboarding process, and offers a quick video.
+
Watch the video, and select *Continue*.
+
Alternatively, you can select *Exit to homepage* at the upper-right corner of the screen, and end the onboarding process.
+
This option appears at this and every subsequent step.
. *Recommended data source*
+
This screen introduces the primary data source for onboarding. The administrator selects this source before you begin.
+
Select *Continue*.
. *Select a Liveboard*
+
Consider which of the initial Liveboards to explore first, and select it.
. *View your insights*
+
Examine the Liveboard you selected, and learn what insights it provides.
+
Select *Follow* to receive periodic emails about this Liveboard.

== Repeating the onboarding process

*_[Optional]_*
Any user can repeat their onboarding experience at any time.
Simply select *Profile* from the user icon on the upper-right corner of the page, and under *Experience*, click *Revisit Onboarding*.
See xref:user-profile.adoc#onboarding[Revisit onboarding].

If you are a new user and you did not experience onboarding, please contact your administrator and request that they configure it for you and other new users.

You can always get additional help.
As you start to use ThoughtSpot, we recommend that you review the xref:getting-started.adoc[].
