= Install ThoughtSpot clusters in VMware
:last_updated: 01/01/2021
:linkattrs:
:experimental:

Learn how to install ThoughtSpot clusters in VMware.

'''
> **ThoughtSpot Training**
>
> * For best results in setting up ThoughtSpot clusterss in VMware, we recommend that you take the following ThoughtSpot U course: * https://training.thoughtspot.com/create-upgrade-patch-a-thoughtspot-cluster/430642[Create a Cluster^].
> * See other training resources at https://training.thoughtspot.com/[ThoughtSpot U^].

'''

== Prerequisites

Before you can install your ThoughtSpot clusters in VMware, complete these prerequisites.

. *Download the OVA* Download the https://thoughtspot.egnyte.com/dl/LPOSJr8Cdd[Open Virtualization Appliance^] (OVA) file.
. *Download the md5* Download the https://thoughtspot.egnyte.com/dl/MaovnPnHqF[md5^], which you can use later to ensure the OVA file is on the correct version, and not corrupted.
. *Review configuration overview* Refer to xref:vmware.adoc[VMware configuration overview] for detailed instance specs.
. *Create the instance* Refer to xref:vmware-setup.adoc[Set up VMware for ThoughtSpot] to create and launch your instance.
. *Review required ports* Refer to xref:ports.adoc[Network ports] to view the required ports for successful operation of ThoughtSpot.
. *Configure nodes* Refer to xref:vmware-installing.adoc[Configure ThoughtSpot nodes in VMware] to configure your nodes.

[#cluster-install]
== Install ThoughtSpot Software

Install the cluster using the ThoughtSpot software release bundle.
The estimated installation time is one hour.

Follow the steps in this checklist:

[cols="5,~",grid=none,frame=none]
|===
| &#10063; | <<cluster-step-1,1. Run the installer>>
| &#10063; | <<cluster-step-2,2. Check cluster health>>
| &#10063; | <<cluster-step-3,3. Finalize installation>>
|===

Refer to your welcome letter from ThoughtSpot to find the link to download the release bundle.
If you do not have a link, open a support ticket with https://community.thoughtspot.com/customers/s/contactsupport[ThoughtSpot Support^] to request access to the release bundle.

[#cluster-step-1]
=== Step 1: Run the installer

. Copy the downloaded release bundle to `/export/sdb1/TS_TASKS/install` using the following command:
+
[source,bash]
----
$ scp <release-number>.tar.gz admin@<hostname>:/export/sdb1/TS_TASKS/install/<file-name>
----
+
The `scp` command uses the following parameters:

`release-number`::
  is the release number of your ThoughtSpot instance, such as 5.3, 6.0, and so on.
`hostname`::
  is your specific hostname.
`file-name`::
 is the name of the tarball file on your local computer.

+
NOTE: You can use another secure copy method, if you prefer a method other than the `scp` command.

. Alternatively, use `tscli fileserver download-release` to download the release bundle.
+
You must xref:tscli-command-ref.adoc#tscli-fileserver[configure the fileserver] by running `tscli fileserver configure` before you can download the release.
+
[source,bash]
----
 $ tscli fileserver download-release <release-number> --user <username> --out <release-location>
----
+
The command has the following parameters:

`release-number`::
  is the release number of your ThoughtSpot instance, such as 5.3, 5.3.1, 6.0, and so on.
`username`::
  is the username for the fileserver that you set up earlier, when configuring the fileserver.
`release-location`::
  is the location path of the release bundle on your local machine. For example, `/export/sdb1/TS_TASKS/install/6.0.tar.gz`.

. Verify the checksum to ensure you have the correct release.
+
Run `md5sum -c <release-number>.tar.gz.MD5checksum`.
+
[source,bash]
----
$ md5sum -c <release-number>.tar.gz.MD5checksum
----
+
Your output says `ok` if you have the correct release.

. Launch a https://linux.die.net/man/1/screen[screen^] session.
Use screen to ensure that your installation does not stop if you lose network connectivity.
+
[source,bash]

----
$ screen -S DEPLOYMENT
----

. Take a machine snapshot prior to the release deployment, as a best practice.

. Create the cluster.
+
Run `tscli cluster create` to create the cluster.
+
[source,bash]
----
$ tscli cluster create <release-number>.tar.gz
----

include::partial$cluster-steps1through3.adoc[]

== Lean configuration

*For use with thin provisioning only:* If you have a xref:deploying-cloud.adoc#small-medium[small or medium instance type], with less than 100GB of data, advanced lean configuration is required before loading any data into ThoughtSpot.
After installing the cluster, contact https://community.thoughtspot.com/customers/s/contactsupport[ThoughtSpot Support^] for assistance with this configuration.

'''
> **Related information**
>
> * xref:nodesconfig-example.adoc[The nodes.config file]
> * xref:parameters-nodesconfig.adoc[Parameters of the nodes.config file]
> * xref:cluster-create.adoc[Using the tscli cluster create command]
> * xref:parameters-cluster-create.adoc[Parameters of the `cluster create` command]
> * xref:deployment-sw.adoc[Deployment Overview]
> * Contact https://community.thoughtspot.com/customers/s/contactsupport[ThoughtSpot Support^].
