= Configure ThoughtSpot nodes in VMware
:last_updated: 01/03/2021
:linkattrs:
:page-aliases: /appliance/vmware/installing-vmware.adoc
:experimental:

Prepare to install your ThoughtSpot cluster by configuring nodes.

Before you can install a ThoughtSpot cluster in VMware, you must configure your nodes.

'''
> **ThoughtSpot Training**
>
> * For best results when configuring ThoughtSpot nodes on VMware, we recommend that you take the following ThoughtSpot U course: https://training.thoughtspot.com/node-network-configuration/437249[Network Configuration^].
> * See other training resources at https://training.thoughtspot.com/[ThoughtSpot U^].

'''


[#installation-prerequisites]
== Installation Prerequisites

Ensure the successful creation of the virtual machines (VMs) before you install the ThoughtSpot cluster in VMware.

[cols="5,~",grid=none,frame=none]
|===
| &#10063; | *Download the OVA* Download the https://thoughtspot.egnyte.com/dl/LPOSJr8Cdd[Open Virtualization Appliance^] (OVA) file.
| &#10063; | *Download the md5* Download the https://thoughtspot.egnyte.com/dl/MaovnPnHqF[md5^], which you can use later to ensure the OVA file is on the correct version, and not corrupted.
| &#10063; | *Review configuration overview* Refer to xref:vmware.adoc[VMware configuration overview] for detailed instance specs.
| &#10063; | *Create the instance* Refer to xref:vmware-setup.adoc[Set up VMware for ThoughtSpot] to create and launch your instance.
| &#10063; | *Review required ports* Refer to xref:ports.adoc[Network ports] to view the required ports for successful operation of ThoughtSpot.
|===

[#configure-nodes]
== Configure Nodes

After creating the instance, you must configure the nodes.

Follow the steps in this checklist:

[cols="5,~",grid=none,frame=none]
|===
| &#10063; | <<node-step-1,Step 1: Log in to your cluster>>
| &#10063; | <<node-step-2,Step 2: Get a template for network configuration>>
| &#10063; | <<node-step-3,Step 3: Prepare node configuration>>
| &#10063; | <<node-step-4,Step 4: Configure the nodes>>
| &#10063; | <<node-step-5,Step 5: Confirm node configuration>>
|===

include::partial$configure-nodes-steps1through5.adoc[]

== Install ThoughtSpot software

Next, xref:vmware-cluster-install.adoc[install your ThoughtSpot clusters].

include::partial$install-cluster-error-recovery.adoc[]

'''
> **Related information**
>
> * xref:nodesconfig-example.adoc[the nodes.config file]
> * xref:parameters-nodesconfig.adoc[Parameters of the nodes.config file]
> * xref:cluster-create.adoc[Using the tscli cluster create command]
> * xref:parameters-cluster-create.adoc[Parameters of the `cluster create` command]
> * Contact xref:support-contact.adoc[ThoughtSpot Support].
