== All Org scope

On a multi-tenant ThoughtSpot instance, all operations are run in the Org context that the user is currently in. If a cluster administrator wants to perform a CRUD operation or apply a configuration change to all Orgs, they must be in the Primary Org, in the *All orgs* section of the Admin Console.

For example, to add a user to multiple Orgs, the administrator must be in the Primary Org, in the *All orgs > Users* section of the Admin Console. If the administrator is in *Org 1*, for example, the *Users* section of the Admin console does not have the option to add users to Orgs, only to groups. You should only use the *All orgs > Users* section of the Admin Console to add users to multiple Orgs. Use the individual Org's *Admin Console > Users* section to add users to individual Orgs, and to add users to groups.

=== Cluster-level configurations

The following features can only be configured or viewed on a cluster level, for all Orgs. You cannot configure these features to work in different ways for different Orgs in the same cluster. Therefore, the cluster administrator must perform the configuration or other management of the following features:

* Adding users to multiple Orgs at a time
* Identity and Access Management: local and SAML user authentication
* Style customization
* User adoption Liveboard
* Performance tracking Liveboard
* Billing information: Credit Usage Liveboard
* Developer functionality and features, including custom actions.
//See <DEV DOCS LINK>
* Custom calendar
* Search and SpotIQ settings
* Email and onboarding settings