If you encounter a technical issue, you can contact ThoughtSpot Support from within the ThoughtSpot application, if in-app support is enabled. If it is not enabled, you can go to our support portal.

== In-app support

If in-app support is enabled, it can be accessed from the help menu by clicking the *Contact support* tile, where you will find information on how to use the application and solutions to common problems. You can find more details about in-app support in the xref:support-handbook.adoc[].


[#file-ticket]
== Support portal

If you encounter a technical issue, you can go to our support portal:

http://thoughtspot.com/support-request

To access our support portal, you need an account in ThoughtSpot Community.
If you do not have one, you can sign up at the above URL.


In our support portal, use our chatbot to describe your technical issue. Please provide as much detail as possible, so we can try to help you resolve it without creating a support case.

If needed, you can create a support case using the chatbot.

