[#upload-csv]
=== Upload a flat data file (CSV)

To upload a CSV file, follow these steps:

. Select *Data* in the top navigation bar.

. Select *Utilities* in the side navigation bar.

. Select *Upload CSV*.
+
Alternatively, navigate to step one of Setup, and select *upload CSV*.
. Upload the CSV file using one of these options:
** Click *Browse your files* and select the file.
** Drag and drop the file into the drop area.

. Answer the question *Are the column names already defined in the file header?*
+
Specify one of the following:

Comma:: (,), example: `Jacket,Winter 2021,yellow,600`

Semicolon:: (;), example: `Jacket;Winter 2021;yellow;600`

Pipe:: (|), example: `Jacket|Winter 2021|yellow|600`

Space:: ( ), example: `Jacket "Winter 2021" yellow 600`

Tab:: ( ), example: `Jacket Winter 2021 yellow 600`

. Select *Next.*
. If column names are missing, select the column header to add column names that describe the attributes or measures in the columns.
+
You can also change existing names to a simpler or more human-readable format.
. Select *Next*.
. Review the automatically-generated data types for each column, and make necessary changes.
+
These are the possible data types:
+
True/False::  Boolean, Yes, no.
Integer::  Smaller integers represented by 32 bits.
Large Integer:: Larger integers represented by 64 bits.
Decimal::  Floating point or Decimal.
Text::  Character or text.
Date::  Simple date, not including the time component.
Date_Time::  The date and time.
Time:: Only the time, not including the date component.
. Select *Upload*.

NOTE: Users have an upload limit of 10 CSV files each.

=== Replace or append new data to a CSV file

To replace your uploaded CSV file or append new data to it, follow these steps:

. Select *Data* in the top navigation bar.

. Select your current CSV file in the list of data sources.

. Select *Replace CSV* in the upper-right corner of your screen.

. Answer the question *Are the column names already defined in the file header?*
. Answer the question *Do you want to append to the existing data or overwrite it?*
+
To add this data to your existing CSV file, choose *Append*. To create a new CSV file, choose *Overwrite*.
. Answer the question *How are fields separated?*
. Select *Next*.
. Preview your data and select *Upload*.
