[#forgot-password]
== Forgotten password
If you forget your password, you can request a password reset from the ThoughtSpot login page. Follow these steps:

. On the ThoughtSpot login page, select *Forgot password?*

. The *Forgot Password?* modal appears. Type your username in the *Username* text box.

. Select *Request reset link*.

. ThoughtSpot sends a password reset email to the email address associated with your ThoughtSpot account. The email subject line is *Account password reset*.

. Select *Reset password*. The link takes you to an interface where you can reset your password.
+
Your password must meet the following requirements:

* The password must be 8 characters or more in length.
* The password must include at least 1 uppercase letter, 1 lowercase letter, 1 number, and 1 special character.
* The password must pass a complexity test based on an external library. This test ensures password complexity and uniqueness by checking for known patterns or words that are too simple. If the password is not complex enough, ThoughtSpot rejects it, even if it fulfills the other requirements. Refer to the https://github.com/dropbox/zxcvbn[Dropbox password library^] for more information.
* The password cannot use certain blocked words. By default, the blocked words are: your username, any part of your display name, and any blocked words your company configures. To add additional words to the blocklist, contact {support-url}.