== Possible joins
[#join-worksheet]
Origin: Worksheet::
Destination:;; Tables uploaded through the UI
Necessary permissions:;; *Can edit* permission on source worksheet
[#join-view]
Origin: View::
Destination:;; other views, materialized views, tables imported through the UI, tables uploaded from backend (tsload) or through DataFlow
Necessary permissions:;; *Can edit* permission on source view
[#join-materialized-view]
Origin: Materialized View::
Destination:;; Views, other materialized views, tables imported through the UI, and tables uploaded from backend (tsload) or through DataFlow
Necessary permissions:;; *Can edit* permission on source materialized view
+
NOTE: For tables loaded from backend, it is best practice to create the join through ThoughtSpot UI, rather than using TQL.

[#join-imported-table]
Origin: Imported table (UI)::
Destination:;; Worksheets, views, materialized views, tables imported through the UI, tables uploaded from backend (tsload) or through DataFlow
Necessary permissions:;; *Can edit* permission on source table

[#join-tsload-table]
Origin: Table uploaded from backend (tsload) or through DataFlow::
Destination:;; Views, materialized views, tables imported through the UI, tables uploaded from backend (tsload) or through DataFlow
Necessary permissions:;; *Can edit* permission on source table
+
NOTE: For joins from tables uploaded through tsload to materialized views and other tables uploaded through tsload, it is best practice to create the join through ThoughtSpot UI, rather than using TQL.

[#join-table-embrace]
Origin: Table uploaded through Connections::
Destination:;; other tables uploaded through Connection, views on top of tables uploaded through Connections
Necessary permissions:;; *Can edit* permission on source table, and *can manage data* permission
+
NOTE: The join must be created between two tables or a table and a view from the same connection.

[#join-view-embrace]
Origin: View on top of a table uploaded through Connections::
Destination:;; Tables uploaded through Connections, other views on top of tables uploaded through Connections
Necessary permissions:;; *Can edit* permission on source view
+
NOTE: The join must be created between two views or a table and a view from the same connection.
