The latest release of ThoughtSpot Cloud contains several new and enhanced features.

* <<8-6-0-cl-first,For the First User>>
* <<8-6-0-cl-analyst,For the Analyst>>
* <<8-6-0-cl-business-user,For the Business User>>
* <<8-6-0-cl-data-engineer,For the Data Engineer>>
* <<8-6-0-cl-it-ops-engineer,For the It Ops Engineer>>
* <<8-6-0-cl-developer,For the Developer>>

[#8-6-0-cl-first]
=== For the First User

Getting started with ThoughtSpot Cloud::
The first user on the account has to complete a series of steps before other people can start using ThoughtSpot with your organization's data.
For these instructions, see xref:ts-cloud-getting-started.adoc[Getting Started with ThoughtSpot Cloud].

[#8-6-0-cl-analyst]
=== For the Analyst

New Liveboard experience::
The xref:liveboard-experience-new.adoc[new Liveboard experience] is now GA and on by default. It contains multiple new features and feature enhancements.
It is part of ThoughtSpot's move to a new stack.
To learn how to manage its enablement, refer to xref:liveboard-experience-new.adoc[].
+
The new Liveboard experience contains the following new features:

include::partial$new-liveboard-experience-features.adoc[]

include::partial$new-liveboard-experience-deprecations.adoc[]

TML import improvements::
You can now import xref:tml.adoc[TML] files that contain certain errors. During the import process, ThoughtSpot removes the part of the object that contains errors, and allows you to import the rest of the object. These errors include the following:
+
--
* Some Liveboard visualizations contain errors, but the overall Liveboard is valid: ThoughtSpot removes the visualizations that contain errors and imports the Liveboard.
* Some Liveboard filters contain errors, but the overall Liveboard is valid: ThoughtSpot removes the filters that contain errors and imports the Liveboard.
* Destination tables for some joins in a table do not exist, but the overall table is valid: ThoughtSpot removes the joins that do not have destination tables and imports the table.
--
+
Refer to xref:scriptability.adoc#migrate-object[Migrate an object].


[#8-6-0-cl-business-user]
=== For the Business User


Delete objects from home page:: You can now delete answers and Liveboards directly from the list on the home page, as well as from the *Answers* and *Liveboards* tabs. To delete an answer or Liveboard from the home page, scroll down the list or search tags and author name to select the object name. After selecting the checkbox to the left of the object name, click the *Delete* button that appears. +
//Note: you will see a warning when you delete an object with dependents.


Data panel multi-word search:: In the data panel search bar, you can now search text and a list of columns separated by one of the following delimiters: comma (*,*), period (*.*), backslash (*\*), dash (*-*), underscore (*_*), or space. If all of your search words find a match with column name words then it is considered as a match.

Choose sources limitation::
You can no longer select more than 100 data sources to search on when searching data. This maximum of 100 sources improves performance and limits timeouts due to the selection of too many sources.

[#8-6-0-cl-data-engineer]
=== For the Data Engineer

[#dbt-improvements]
Integration with dbt improvements::
This release includes the following improvements to the dbt integration:
* Integration with dbt for Databricks connections
* Import of multiple folders at a time
* Import of a single table within a folder
* Support for joins across multiple folders

[#connections-denodo]
Denodo for Connections::
Denodo is now supported as a connection. See xref:connections-denodo.adoc[Denodo].

[#tags]
Edit tags from the Data workspace::
You can now edit tags for tables, worksheets, views, and SQL views from the Data workspace home page. Refer to xref:tags.adoc#data-workspace[Use tags to organize].

[#8-6-0-cl-it-ops-engineer]
=== For the IT Ops Engineer

[#private-link]
AWS PrivateLink between ThoughtSpot Cloud and your Denodo data warehouse::
ThoughtSpot now supports AWS PrivateLink for Denodo connections. ThoughtSpot encrypts all your data by default. For an additional layer of security and network reliability, you can use an AWS PrivateLink.
+
See xref:connections-denodo-private-link.adoc[Enabling an AWS PrivateLink between ThoughtSpot Cloud and your Denodo data warehouse].

[#8-6-0-cl-developer]
=== For the Developer

ThoughtSpot Everywhere:: For information about the new features and enhancements introduced in this release, refer to https://developers.thoughtspot.com/docs/?pageid=whats-new[ThoughtSpot Developer Documentation^].
