The latest release of ThoughtSpot Cloud contains several new and enhanced features.

* <<10-3-0-cl-first,For the First User>>
* <<10-3-0-cl-analyst,For the Analyst>>
* <<10-3-0-cl-business-user,For the Business User>>
* <<10-3-0-cl-data-engineer,For the Data Engineer>>
* <<10-3-0-cl-developer,For the Developer>>

[#10-3-0-cl-first]
=== For the First User

Getting started with ThoughtSpot Cloud::
The first user on the account has to complete a series of steps before other people can start using ThoughtSpot with your organization's data.
For these instructions, see xref:ts-cloud-getting-started.adoc[Getting Started with ThoughtSpot Cloud].

[#10-3-0-cl-analyst]
=== For the Analyst

// Naomi. jira: SCAL-211323. docs jira: SCAL-225087
Analyst Studio [.badge.badge-beta-relnotes]#Beta#:: ThoughtSpot introduces Analyst Studio, where you can write SQL queries to create reusable Datasets. You can set schedules to refresh Datasets, or publish them to the Data workspace, where you can join multiple Datasets to query as a whole.
+
For more information, see
xref:analyst-studio-getting-started.adoc[Analyst Studio].

// Mary. jira: SCAL-160492. docs jira: SCAL-223961
// PM: Arpit.
Liveboard schedule available to all users [.badge.badge-early-access-relnotes]#Early Access#::

ThoughtSpot introduces access to Liveboard schedules on the home page. Users can now see all Liveboard schedules that they are subscribed to in a new section on the home page. From this page, you can edit Liveboard schedules that you created. Administrators can edit the Liveboard schedule for all schedules from this page.
+
For more information, see xref:thoughtspot-homepage.adoc[New home page and persona-based navigation].



[#10-3-0-cl-business-user]
=== For the Business User

// Naomi. jira: SCAL-210305. docs jira: SCAL-221925
Natural language search and object search:: Natural language search and object search are now separated. To search for an AI-generated answer using natural language, enter your question in the search bar marked *Ask a business question in natural language*  on the home page. To search for related Answers and Liveboards, enter your question in the search bar marked *Find existing Answers and Liveboards* in the top navigation bar.
+
For information on the changes in ThoughtSpot Embedded, see https://developers.thoughtspot.com/docs/full-app-customize#_search_experience[Search experience^] in the ThoughtSpot developer documentation.
+
For any questions or concerns, contact {support-url}.

////
// Naomi. jira: SCAL-212737. docs jira: SCAL-226578
Compact Liveboard header [.badge.badge-early-access-relnotes]#Early Access#:: We have streamlined the design of Liveboard headers to ensure maximum visibility of Liveboard visualizations no matter the size of the screen. To enable this feature, contact your administrator.
////

// Naomi. docs jira: SCAL-220633.
Portuguese (Brazil) keywords::
We have updated the Portuguese date keyword synonyms. For more information, see
xref:keywords-pt-BR.adoc[Português (Brasil) Keyword reference].

// Naomi. docs jira: SCAL-220682
Keywords known issue:: When entering keywords in the search bar, you may see different keywords reflected in the filter chips of the resulting chart (for example, `última hora` and `último 1 hora`). Accuracy of the search result is not affected.

// Mary. jira: SCAL-199338. docs jira: SCAL-224679
Create an alert from the Watchlist on the home page [.badge.badge-early-access-relnotes]#Early Access#:: You can now create alerts directly from the *Watchlist* on the home page.
+
For more information, see xref:thoughtspot-one-homepage.adoc[Home page] and xref:monitor.adoc[Monitor Key Performance Indicators in your data].

Manage tags for Answers and Liveboards::

You can now manage all your Answer and Liveboard tags from one convenient window. Just click the *Manage tags* button at the top of your list of Liveboards or Answers, then create, edit, and delete tags. To delete and edit tags you must have administrator privileges or the *can manage tags* role if RBAC is enabled. For more information, see
xref:tags.adoc[Use tags to organize].

[#10-3-0-cl-data-engineer]
=== For the Data Engineer

// Naomi. jira: SCAL-207602. docs jira: SCAL-219033
Categorization for Connections [.badge.badge-early-access-relnotes]#Early Access#:: You can now choose to sort Connections by type rather than order added to ThoughtSpot. To enable this feature, contact your administrator. For more information, see
xref:connectors-categorization.adoc[Categorizing Connections].

// Naomi. jira: SCAL-212191. docs jira: SCAL-227574
Sage Coach enhancements::
Filters improvement:::
Filters for Worksheets, feedback providers, and editors have been refined to display only relevant values when managing feedback. For example, only Worksheets with existing feedback entries will appear in the filter options, rather than showing all Worksheets in the system.
This enhancement improves the filtering process, making it more efficient and user-friendly.

// Mary. jira: SCAL-210151.
// Monitor the application of row-level security::

//You can now track whether or not row-level security is applied to queries. Risk and compliance analysts can track the volume of queries with row-level security applied versus those without. A row-level security tag is included in the sql query. This provides the ability to determine the number of queries that have included row-level security via the underlying database.
//+
//Each query log contains a comment as follows:
//+
//----
//isRLSApplied: true/false.
//----


// Mary. jira: SCAL-212742. docs jira: SCAL-223959
Allow only ThoughtSpot users and groups to be added to schedules::

ThoughtSpot schedules can be configured to prevent new and existing schedules from being sent to external emails. To enable this feature, contact {support-url}.
+
For more information, see xref:liveboard-schedule.adoc[Schedule a Liveboard job]


[#10-3-0-cl-it-ops]
=== For the IT/Ops Engineer

Option to set new navigation and homepage experience as default [.badge.badge-early-access-relnotes]#Early Access#::
// Mark. jira: SCAL-223658. docs jira: SCAL-226711
// PM: Mohil
Administrators now have the ability to set the new navigation and homepage experience as the default UI for all users of the cluster, if it is enabled for the cluster. To enable this feature, go to the *Admin > Early access features* page and enable _New Experience (Default UI)_. For more information, see
xref:early-access-enable.adoc[Enable Early Access features].
// Mary. JIRA: SCAL-202402. docs JIRA: SCAL-212285
Org-specific URLs [.badge.badge-early-access-relnotes]#Early Access#::

ThoughtSpot introduces Org-specific URLs. URLs in emails now include Org context so that users are taken directly to the correct Liveboard in the correct Org even if they belong to multiple Orgs.
You can also move between different browser tabs that point to different Orgs.

////
// Mary. JIRA: SCAL-197810. docs JIRA: SCAL-216615
Local authentication support with IAMv2 [.badge.badge-early-access-relnotes]#Early Access#::

ThoughtSpot allows customers to enable or disable local authentication at the Org and cluster levels. To enable local authentication at the cluster level, administrators require the *Can manage authentication* privilege. To enable local authentication at the Org level, contact {support-url}.
+
NOTE: Org level settings override cluster level settings.
+
For more information, see xref:authentication-local.adoc[Managing local authentication].
////

Enhanced Identity and Access Management (IAMv2) enablement::
Enhanced Identity and Access Management (aka IAMv2) is being enabled for customers as part of maintenance windows for all ThoughtSpot Enterprise customers.
+
Some of the improvements for customers include:

* Security compliance benefits.
* Support for advanced functionality with SAML, OIDC per Org, and Org and Group mapping.
* Increased speed of deployment for advanced identity features into ThoughtSpot Cloud.
* Improved password policy management with increased flexibility and features.
+
NOTE: Upcoming enhancements will include multi-factor authentication (MFA) for locally authenticated users.

+
Ensure you are ready for migration by reviewing and following the steps in the documentation so that there is no login disruption for your users after migration. For more information, see xref:okta-iam.adoc[Identity and Access Management V2]. Accept in-product notifications for IAM updates. Please contact {support-url} if you have any questions.


[#10-3-0-cl-developer]
=== For the Developer

ThoughtSpot Embedded:: For information about the new features and enhancements introduced in this release, refer to https://developers.thoughtspot.com/docs/?pageid=whats-new[ThoughtSpot Developer Documentation^].

Selective User Access::
Provide selective access to ThoughtSpot pages through both the ThoughtSpot Cluster URL and the embedded context of your host app. For details, see: https://developers.thoughtspot.com/docs/selective-user-access#selective-access[Selectively assign access^].
