The latest release of ThoughtSpot Cloud contains several new and enhanced features.

* <<10-7-0-cl-first,For the First User>>
* <<10-7-0-cl-analyst,For the Analyst>>
* <<10-7-0-cl-business-user,For the Business User>>
* <<10-7-0-cl-data-engineer,For the Data Engineer>>
* <<10-7-0-cl-developer,For the Developer>>

[#10-7-0-cl-first]
=== For the First User

Getting started with ThoughtSpot Cloud::
The first user on the account has to complete a series of steps before other people can start using ThoughtSpot with your organization's data.
For these instructions, see xref:ts-cloud-getting-started.adoc[Getting Started with ThoughtSpot Cloud].

[#10-7-0-cl-analyst]
=== For the Analyst



[#10-7-0-cl-business-user]
=== For the Business User

// Naomi – jira: SCAL-215657. docs jira: SCAL-243597
Alerts by attribute [.badge.badge-early-access-relnotes]#Early Access#::
You can now set KPI alerts to trigger at changes to a selected attribute. This can include changes in the value of the attribute, such as an increase in sales by percentage by state, or a scheduled alert to trigger on a weekly basis. For example, if you wanted to create an alert for a KPI tracking sales of different phones by brand, you could choose the intended brands as attributes and set an alert to be notified when sales for those specific brands dropped by 5%.
+
For more information, see xref:monitor-alert-attributes.adoc[Alerts by attribute].

// Naomi. jira: SCAL-233663. docs jira: SCAL-239444
Bilingual keywords for Japanese::
ThoughtSpot now supports bilingual keywords for the Japanese locale. When your system language is set as Japanese, you can now enter keywords in either English or Japanese while searching.

[#10-7-0-cl-data-engineer]
=== For the Data Engineer

// Mark – jira: SCAL-233945. docs jira: SCAL-242708.
Create your own charts with Muze Studio [.badge.badge-beta-relnotes]#Beta#:: You can now create your own charts in ThoughtSpot using Muze Studio. A developer can create new chart types by writing the code for them in the code builder. To enable this feature, contact your ThoughtSpot administrator.
+
For more information, see
xref:chart-create.adoc[Creating charts with Muze Studio].

// Naomi. jira: SCAL-226981. docs jira: SCAL-243429
OAuth for Denodo using Proof Key for Code Exchange (PKCE):: We now support OAuth with PKCE for Denodo. For more information, see
xref:connections-denodo-add.adoc[Add a Denodo connection].

// Naomi. jira: SCAL-206474. docs jira: SCAL-235082
Bridge support for SQL Server, SAP HANA, and Oracle::
Bridge provides options to securely connect your data source with ThoughtSpot Cloud, as an alternative to PrivateLink, VPC Peering, or VPN tunnels. We added support for Bridge for the following connectors:
+
--
* Oracle
* SAP HANA
* SQL Server
--
+
For more information, see xref:connections-bridge.adoc[Bridge connectivity for Cloud Data Warehouses and Databases].

// Naomi. jira: SCAL-234949. docs jira: SCAL-?
Query tagging in Query Stats Worksheet::
ThoughtSpot now distinguishes between regular query consumption and Spotter queries within the Query Stats Worksheet.

// Naomi. jira: SCAL-218237. docs jira: SCAL-239699
Learnability in conversation: feedback generation in follow-up questions::
You can now give feedback on AI-generated Answers in Spotter without interrupting your searching conversation. When marking an Answer incorrect, you can now edit the underlying search, save, and review the search query tokens making up the Answer. If you mark an Answer correct, you can review and save the underlying search query tokens so Spotter remembers your choices in the future for similar questions.
+
For more information, see xref:spotter-getting-started.adoc#learnability[Coach Spotter within a conversation].

[#10-7-0-cl-it-ops]
=== For the IT/Ops Engineer

[#10-7-0-cl-developer]
=== For the Developer

ThoughtSpot Embedded:: For information about the new features and enhancements introduced in this release, refer to https://developers.thoughtspot.com/docs/?pageid=whats-new[ThoughtSpot Developer Documentation^].
