The latest release of ThoughtSpot Cloud contains several new and enhanced features.

* <<10-8-0-cl-first,For the First User>>
* <<10-8-0-cl-business-user,For the Business User>>
* <<10-8-0-cl-analyst,For the Analyst>>
* <<10-8-0-cl-data-engineer,For the Data Engineer>>
* <<10-8-0-cl-developer,For the Developer>>

[#10-8-0-cl-first]
=== For the First User

Getting started with ThoughtSpot Cloud::
The first user on the account has to complete a series of steps before other people can start using ThoughtSpot with your organization's data.
For these instructions, see xref:ts-cloud-getting-started.adoc[Getting Started with ThoughtSpot Cloud].

[#10-8-0-cl-business-user]
=== For the Business User

Spotter features::
// Naomi. jira: SCAL-226925. docs jira: SCAL-239972.
Spotter in Slack [.badge.badge-beta-relnotes]#Beta#:::
You can now use Spotter to conversationally search your data in Slack. Follow-up questions remain within the same thread, preserving context. Pin a Worksheet or Model to a channel to ensure quick access to data from that Worksheet or Model. Spotter in Slack replaces the ThoughtSpot app in Slack. To enable this feature, contact {support-url}.
+
--
NOTE: Spotter in Slack is not available for GCP and ThoughtSpot Embedded clusters yet.
--
+
For more information, see
xref:spotdev.adoc[Spotter in Slack].
// Naomi. jira: SCAL-240915, SCAL-233735. docs jira: SCAL-?
Spotter in MS Teams [.badge.badge-early-access-relnotes]#Early Access#::: You can now use Spotter to conversationally search your data in MS Teams. Follow-up questions remain within the same thread, preserving context. Pin a Worksheet or Model to a channel to ensure quick access to data from that Worksheet or Model. To enable this feature, contact your administrator.
+
For more information, see xref:spotter-ms-teams.adoc[].
// Naomi. jira: SCAL-218237. docs jira: SCAL-239699
Learnability in conversation: feedback generation in follow-up questions [.badge.badge-beta-relnotes]#Beta#:::
You can now give feedback on AI-generated Answers in Spotter without interrupting your searching conversation. When marking an Answer incorrect, you can now edit the underlying search, save, and review the search query tokens making up the Answer. If you mark an Answer correct, you can review and save the underlying search query tokens so Spotter remembers your choices in the future for similar questions.
+
For more information, see
xref:spotter-getting-started.adoc#learnability[Coach Spotter within a conversation].
// Naomi. jira: SCAL-214785. docs jira: SCAL-?
Natural language conversations with Spotter:::
Now, Spotter’s capabilities have expanded to include natural language responses, allowing Spotter to gather information about your business questions before translating answers into visualizations.
+
You can ask Spotter to suggest questions during the conversation.
Spotter can also answer 'why' questions.
Spotter can take in broad topical questions, break them into smaller questions, and then generate multiple answers to answer your question.
+
For more information, see
xref:spotter-best.adoc[Spotter best practices], xref:spotter-change-analysis.adoc[Spotter change analysis], and xref:spotter-deep-analysis.adoc[Spotter deep analysis].
// Mary – jira: SCAL-233271. docs jira:?
Spotter shortcuts [.badge.badge-early-access-relnotes]#Early Access#::: ThoughtSpot introduces shortcuts that allow users to select from existing verified data constructs, including columns, filter values, and search data keywords. These shortcuts allow users to mix natural language and deterministic inputs when using Spotter.
+
To enable this feature, contact {support-url}.
// Naomi - jira: SCAL-233562, SCAL-232993. docs jira: SCAL-244415
Hover over Spotter tokens::: You can now hover over Spotter tokens to gain more information about the attributes, measures, formulas, and filters used in each Answer.
+
--
Attributes:::: Spotter displays a description in natural language, and lists sample values. Select *More details* to view column statistics (such as how many unique values exist), data type, and source.
Measures:::: Spotter displays a description in natural language. Select *More details* to view column statistics (such as minimum and maximum values), data type, and source.
Formulas:::: Spotter displays the formula used.
Filters:::: Spotter displays an explanation of the filter in natural language and a mention of which value is being filtered.
--
+
For more information, see
xref:spotter-best.adoc#tokens[Spotter query tokens].

//Mary. Jira: SCAL-226919. doc jira: SCAL-239109
Spotter on mobile::: ThoughtSpot introduces Spotter, our new AI-powered, unified conversational search experience on mobile.
+
For more information about Spotter on ThoughtSpot mobile, see the link:https://docs.thoughtspot.com/mobile/latest/[ThoughtSpot mobile documentation site,window=_blank].

// Naomi. jira: SCAL-211323, SCAL-220341. docs jira: SCAL-225087
Analyst Studio:: ThoughtSpot introduces Analyst Studio, where you can write SQL queries to create reusable Datasets. You can set schedules to refresh Datasets, or publish them to the Data workspace, where you can join multiple Datasets to query as a whole.
ThoughtSpot's enhanced identity and access management (IAMv2) allows users with the *Can manage/access analyst studio* privilege to navigate to Analyst Studio seamlessly from the Data workspace.
+
For more information, see
ifndef::pendo-links[]
xref:analyst-studio-getting-started.adoc[Analyst Studio].
[#10-8-0-cl-analyst]
=== For the Analyst

// Mary. jira: SCAL-224447. doc jira: SCAL-236449
Pivot table charts [.badge.badge-early-access-relnotes]#Early Access#:: ThoughtSpot introduces a brand new pivot table chart. The new pivot table charts have the following features:
+
--
* Faster load times with pagination.
//* You can now expand and collapse all in pivot tables.
* We now support custom sort order.
* You can now adjust column widths.
* You can now slice with measures and attributes.
* You can now use values for more granular control in configurations.
--
+
To enable this feature, contact your administrator.
+
For more information, see
xref:chart-pivot-table.adoc#pivot-table-2-0[Pivot table charts].

// Mary. jira: SCAL-194093. docs jira: SCAL-226615
Query set groups [.badge.badge-early-access-relnotes]#Early Access#:: ThoughtSpot users can now define groups for included query values using conditions in query sets. Conditions allow you to create groups using operators, to specify the parameters of the group.
+
For example, you could create a query set that list each customer, their sales dollar amount, and then add a formula that ranks the amount in descending order. You could then add groups to define Gold, Silver, and Bronze levels where Gold is ranked 1-10, Silver 11-50, and Bronze every other value.
+
To enable this feature, contact your administrator. For more information, see
xref:query-sets.adoc[Query sets].

// Mary -- SCAL-150356
Custom sets [.badge.badge-early-access-relnotes]#Early Access#::
You can create custom sets, which can be used to classify values in a list that you can then reuse across multiple analyses. A column set is a custom group of values from a single column. For example, you can use custom sets to define regions with specific countries included or excluded. Custom sets are community objects which remain when you navigate away from the Search Data page and can be used by any user with view access to the underlying Worksheet or Model. To enable this feature, contact {support-url}.
+
For more information, see
xref:column-sets.adoc[Custom sets].


[#10-8-0-cl-data-engineer]
=== For the Data Engineer

// Naomi. jira: SCAL-226052. docs jira: SCAL-239382
Spotter Conversations Liveboard:: We’ve introduced the *Spotter Conversations Liveboard* to give you real-time visibility into user interactions with Spotter. With this Liveboard, administrators can:
+
--
* Gain insights into user engagement and adoption metrics for Spotter.
* Track query trends and understand user intent.
* Monitor follow-up actions, including query refinements and edits within conversations.
* Analyze feedback to identify training gaps and improve dataset coverage.
--
+
For more information, see
xref:spotter-conversations-liveboard.adoc[Spotter Conversations Liveboard].

// Naomi. jira: SCAL-226972. doc jira: SCAL-241403
Column name localization and aliasing [.badge.badge-early-access-relnotes]#Early Access#:: If you have edit privileges to Worksheets or Models, you can now create column name aliases, linked to the system language you selected in your user profile. This allows you to search for column names in your system language, instead of typing the columns in English and the keywords in your system language. You can also set column descriptions in other languages to be displayed according to the locale you choose.
+
For more information, see
xref:column-aliases.adoc[Column aliases and localization].

// Mark – jira: SCAL-233945. docs jira: SCAL-242708.
Create your own charts with Muze Studio [.badge.badge-beta-relnotes]#Beta#:: You can now create your own charts in ThoughtSpot using Muze Studio. A developer can create new chart types by writing the code for them in the code builder. Other users can then use these charts to visualize their data. To enable this feature, contact {support-url}.
+
For more information, see
xref:chart-create.adoc[Create charts].

// Naomi. jira: SCAL-230405. docs jira: SCAL-239421
ClickHouse connection [.badge.badge-early-access-relnotes]#Early Access#:: You can now create connections from ThoughtSpot to ClickHouse. To enable this feature, contact your administrator. For more information, see
xref:connections-clickhouse.adoc[ClickHouse].

// Naomi. jira: SCAL-225380. SCAL-216227 doc jira: SCAL-227908
Gemini and Mistral LLM integration with Spotter [.badge.badge-beta-relnotes]#Beta#:: You can now choose the LLM to power your Spotter experience. Your options are Azure OpenAI, Google Gemini, or Mistral. For more information, see
xref:spotter-getting-started.adoc[Getting started with Spotter].

// Naomi. jira: SCAL-206474. docs jira: SCAL-?
Bridge support for SQL Server, SAP HANA, and Oracle:: Bridge provides options to securely connect your data source with ThoughtSpot Cloud, as an alternative to PrivateLink, VPC Peering, or VPN tunnels. We added support for Bridge for the following connectors:
+
--
* Oracle
* SAP HANA
* SQL Server
--
+
For more information, see
xref:connections-bridge.adoc[Bridge connectivity for Cloud Data Warehouses and Databases].


[#10-8-0-cl-developer]
=== For the Developer

ThoughtSpot Embedded:: For information about the new features and enhancements introduced in this release, refer to https://developers.thoughtspot.com/docs/?pageid=whats-new[ThoughtSpot Developer Documentation^].

