The latest release of ThoughtSpot Cloud contains several new and enhanced features.

* <<9-7-0-cl-first,For the First User>>
* <<9-7-0-cl-analyst,For the Analyst>>
* <<9-7-0-cl-business-user,For the Business User>>
* <<9-7-0-cl-data-engineer,For the Data Engineer>>
* <<9-7-0-cl-developer,For the Developer>>

[#9-7-0-cl-first]
=== For the First User

Getting started with ThoughtSpot Cloud::
The first user on the account has to complete a series of steps before other people can start using ThoughtSpot with your organization's data.
For these instructions, see xref:ts-cloud-getting-started.adoc[Getting Started with ThoughtSpot Cloud].

[#9-7-0-cl-analyst]
=== For the Analyst


//scal-66335
Personalized Liveboard views [.badge.badge-early-access-relnotes]#Early Access#:: Personalized views allow you to save your own set of values for filters and parameters in a Liveboard without editing the original Liveboard. You can change the values of the already present filters and parameters in a Liveboard to create a view, and save it for future use. The new Liveboard is a view of the master Liveboard, so any changes made to the master Liveboard flow  automatically to the filtered Liveboard view but not vice-versa. This includes changes made to pinned visualizations, tabs, filter chips, and re-ordering.

//scal-165262
Embedding in note tiles:: Embedding in note tiles is now available to all users and is on by default. You can now embed interactive content such as videos, pdfs, or Figma files into Liveboards using the note tile format. To try it out, enter a Liveboard, select the edit icon, and select *Add note* from the top bar. You can then click the embed icon and enter the URL or iFrame code for your content. You can interact with the content embedded in a Liveboard like you would with a website. For more information, see xref:liveboard-notes.adoc#embed[Embedding content with iFrames].

//scal-139891
System Variables in Answer and Worksheet formulas:: Previously, ThoughtSpot supported the `ts_username` variable for use in row-level security formulas alone. Now, users can access the following string variables:
+
--
* `ts_orgname`
* `ts_email_domain`
--
+
`ts_orgname`, `ts_username`, and `ts_email_domain` variables are available to use in Answer and Worksheet formulas. These variables are helpful for data masking.

//scal-140692
Request access to data source from filter:: When creating a filter on a Liveboard or Answer, you must have access to the underlying data source. Users can now request access to the underlying Worksheet through the filter modal on a Liveboard or Answer. For more information, see
xref:liveboard-filters.adoc#filter-request[Liveboard filters].


//scal-161459
[#9-7-0-cl-business-user]
=== For the Business User

New data panel with tag-based filtering::
The new data panel experience is available for all customers in this release, and is enabled by default. In this release, you can now filter data sources by how they are tagged.
+
For more information, see xref:search-start.adoc[Start a new search].

//scal-158463
Atlan [.badge.badge-beta-relnotes]#Beta#:: You can now see verification status and descriptions on tables and columns imported from Atlan. This information appears when you click on the corresponding table or column in *Search data*. Once connected, this information is visible to all users. This feature is in beta and off by default. To enable it, contact {support-url}. +
For more information, see
xref:catalog-integration-atlan.adoc[Atlan catalog integration].

//scal-159581, scal-95381, scal-158204
Mobile enhancements:: We made the following improvements to ThoughtSpot mobile:

* We simplified the log in process for the ThoughtSpot mobile app. You can now enter your company email to receive an email with a magic link login, rather than entering the server URL.
* You can now change your ThoughtSpot locale through the Mobile app. When your locale is updated, ThoughtSpot translates labels, date formats and number formats to match the default for your country and language.
* You can now use SpotIQ analysis to directly identify the key drivers for recent change in your KPIs in ThoughtSpot Mobile. KPI change analysis allows you to drill down into the causes of change in your KPIs and customize the insights generated by SpotIQ.


[#9-7-0-cl-data-engineer]
=== For the Data Engineer

//scal-158463
Atlan data catalog [.badge.badge-beta-relnotes]#Beta#:: You can now import metadata information related to your tables and columns from Atlan into ThoughtSpot. From the *Data* tab, you can set up a connection to Atlan to import column descriptions, column verification status, table descriptions, and table verification status. This information appears when you click on the corresponding table or column in *Search data*. Once connected, metadata information is visible to all users.
+
For more information, see
xref:catalog-integration-atlan.adoc[Atlan catalog integration].

//scal-158490
SAP Hana Calculation view input parameters [.badge.badge-beta-relnotes]#Beta#:: Now, you can define a parameter to link to the parameter in SAP Hana using TML at the table level, and create a linked_parameter clause to ensure the parameter is displayed in all Answers created from the table. For more information, see
xref:tml-tables.adoc[TML for tables] and xref:tml-worksheets.adoc[TML for Worksheets].


//scal-91104
Key Pair authentication for Snowflake:: We now support xref:connections-snowflake-add.adoc[Key Pair authentication for Snowflake].

//scal-136661
OAuth for Databricks using Proof Key for Code Exchange (PKCE):: We now support xref:connections-databricks-add.adoc[OAuth with PKCE for Databricks].


[#9-7-0-cl-developer]
=== For the Developer

ThoughtSpot Everywhere:: For information about the new features and enhancements introduced in this release, refer to https://developers.thoughtspot.com/docs/?pageid=whats-new[ThoughtSpot Developer Documentation^].
