The latest release of ThoughtSpot Cloud contains several new and enhanced features.

* <<8-7-0-cl-first,For the First User>>
* <<8-7-0-cl-analyst,For the Analyst>>
* <<8-7-0-cl-business-user,For the Business User>>
* <<8-7-0-cl-data-engineer,For the Data Engineer>>
* <<8-7-0-cl-it-ops-engineer,For the IT Ops Engineer>>
* <<8-7-0-cl-developer,For the Developer>>

[#8-7-0-cl-first]
=== For the First User

Getting started with ThoughtSpot Cloud::
The first user on the account has to complete a series of steps before other people can start using ThoughtSpot with your organization's data.
For these instructions, see xref:ts-cloud-getting-started.adoc[Getting Started with ThoughtSpot Cloud].

[#8-7-0-cl-analyst]
=== For the Analyst

Customizable colors for heatmap and treemap charts::
You can now customize the colors used for heatmap and treemap charts. Prior to this release, the only available heatmap color was teal in various shades, and the only available treemap color was green in various shades. Now you can choose any color in your color palette. For more information, see xref:chart-heatmap.adoc[] and xref:chart-treemap.adoc[].

Liveboard tabs::
ThoughtSpot now supports separating Liveboards into multiple tabs. This allows you to group specific visualizations together within a Liveboard. For example, you may have a *Sales* Liveboard that contains top-level KPIs and more detailed charts. You can create a tab for the top-level KPIs for executives to view, and a tab for the more detailed charts that managers need to monitor. For more information, refer to xref:liveboard-tabs.adoc[Liveboard tabs].

[#8-7-0-cl-business-user]
=== For the Business User

Threshold-based alerts::
Threshold-based alerts are now GA and on by default. You can now use the Monitor feature to receive alerts when your KPI satisfies a given threshold condition. For example, create a condition to receive an alert when your Sales KPI becomes `greater than 200,000`, or when your KPI for Sales weekly `increases by 2%`.
For more information, see xref:monitor.adoc#threshold-based-alert[Create a threshold-based alert].

ThoughtSpot Sync:: You can now sync data directly from an answer or custom SQL view to an external business app like xref:sync-sheets.adoc[Google Sheets], xref:sync-slack.adoc[Slack], or xref:sync-ms-teams.adoc[Microsoft Teams]. Using ThoughtSpot Sync, you can push insights directly to your app, notify your teams, and view data in context. ThoughtSpot Sync automatically establishes a secure pipeline to the destination app and thus eliminates the need for building custom connectors to external apps. For more information, see xref:thoughtspot-sync.adoc[Sync data from ThoughtSpot to external apps].

////
Support for OR in contains operator::
ThoughtSpot now offers the option to `OR` multiple `contains` clauses for the same attribute in a search, instead of combining them with `AND`, which is the default. For example, with the optional new `OR` behavior, `country name contains 'a' country name contains 'b'` returns results such as `Azerbaijan`, `Bahrain`, `North America`, and `Canada`. With the default `AND` behavior, that search returns `Azerbaijan` and `Bahrain`, but *_not_* `North America` or `Canada`.
+
To enable this feature, contact {support-url}.
////

Support for multiple contains, begins_with, and ends_with phrases in versus queries::
ThoughtSpot now supports multiple `contains`, `begins_with`, and `ends_with` phrases in `vs` queries. For example, you can now have a versus query such as `state name begins_with 'a' state name begins_with 'c' vs state name begins_with 'd'`.
+
For more information, refer to the xref:keywords.adoc#vs[Keyword reference].

Geo charts enhancements::
This release includes several enhancements to all geo charts:
+
--
* Improved map quality: This includes faster map loading, better clarity, and more granular details down to the street level when you zoom in. This applies to background maps (the parts of the map with no data) as well.
* A new *map type* option that allows you to customize the display of the parts of the geo chart map that do not contain data. The new map type options are Light, Dark, Outdoors, Streets, Satellite, and Satellite Streets. The default is Light.

--
See xref:chart-geo.adoc[].

[#8-7-0-cl-data-engineer]
=== For the Data Engineer

Denodo OAuth::
Denodo connections now support OAuth. For details, see xref:connections-denodo-oauth.adoc[Configure OAuth for a Denodo connection].

Snowflake Oauth improvements::
This release brings improvements in how ThoughtSpot handles user tokens for Snowflake connections configured with Snowflake OAuth. If a user's refresh token becomes invalid, the administrator or author of the connection can now run the Invalidate Tokens command to allow the user to re-authenticate and regain access to the insights provided by the connection, and the connection itself. Also, in this release the _Role_ field has been added to the Snowflake OAuth connection details page, allowing a role to be added when the connection is created and changed when a connection is edited. See xref:connections-snowflake-edit.adoc#invalidate-tokens[Invalidating refresh tokens of a Snowflake connection].

Snowflake CSV upload [.badge.badge-beta-relnotes]#Beta#:: Now you have a quick and easy way to complete one-time data loads of small files that are not present in your cloud data warehouse. You can now upload a CSV file to the database of your Snowflake connection that can be joined to other tables or worksheets in your connection. Once your administrator enables this feature, go to *Data* > *Utilities*, and click *Upload CSV*.
ifndef::pendo-links[]
See xref:connections-snowflake-csv-upload-config.adoc[Configure CSV upload for your Snowflake connection], and xref:connections-snowflake-csv-upload.adoc[Upload a CSV file in your Snowflake connection].


[#8-7-0-cl-it-ops-engineer]
=== For the IT/Ops Engineer

[#8-7-0-cl-query-based-pricing]
Query Stats Liveboard::

The new Query Stats Liveboard allows administrators of customers who have signed up for a query-based usage subscription, to track the number of queries of their users. To view the Query Stats Liveboard, go to *Liveboards* and select *Query Stats Liveboard*. Query-based usage is part of consumption-based pricing. For more information, see xref:consumption-pricing-query-based.adoc[Query-based usage].

[#okta]
Identity and Access Management V2 [.badge.badge-beta-relnotes]#Beta#::

In this release, ThoughtSpot switched to a new, industry-standard cloud authentication method through Okta. ThoughtSpot now powers its internal authentication with Okta, which is the industry-leading authentication platform. This change is internal and has no impact on customers. After we enable this feature by default, all user authentication will automatically use the internal Okta service.
+
This switch involves several external improvements to authentication, including security enhancements:
+
--
* Ability to map IDP attributes from the ThoughtSpot Admin Console (username, email, and display name).
* Account activation monitoring from the Users section of the Admin Console: if a user still needs to activate their account, administrators can see that information in the Users section and re-send their activation email.
* Only Okta interacts with your IDP. Your ThoughtSpot cluster does not directly interact with your IDP.
* Local users create their own password during activation. Administrators do not create the password prior to activation.
--
+
For more information, refer to xref:okta-iam.adoc[Identity and Access Management V2].
+
This feature is in beta and off by default. To enable Okta authentication, contact {support-url}.

[#8-7-0-cl-developer]
=== For the Developer

ThoughtSpot Everywhere:: For information about the new features and enhancements introduced in this release, refer to https://developers.thoughtspot.com/docs/?pageid=whats-new[ThoughtSpot Developer Documentation^].
