The latest release of ThoughtSpot Cloud contains several new and enhanced features.

* <<10-2-0-cl-first,For the First User>>
* <<10-2-0-cl-analyst,For the Analyst>>
* <<10-2-0-cl-business-user,For the Business User>>
* <<10-2-0-cl-data-engineer,For the Data Engineer>>
* <<10-2-0-cl-developer,For the Developer>>

[#10-2-0-cl-first]
=== For the First User

Getting started with ThoughtSpot Cloud::
The first user on the account has to complete a series of steps before other people can start using ThoughtSpot with your organization's data.
For these instructions, see xref:ts-cloud-getting-started.adoc[Getting Started with ThoughtSpot Cloud].

[#10-2-0-cl-analyst]
=== For the Analyst

Data augmentation [.badge.badge-beta-relnotes]#Beta#:: You can now upload data related to your Search and append it directly to an Answer. This allows you to add data columns to an Answer without navigating away from your current analysis. To enable this feature, contact {support-url}.
+
NOTE: Data augmentation is only available for Answers built on data uploaded to Snowflake connections.

[#10-2-0-cl-business-user]
=== For the Business User


[#10-2-0-cl-data-engineer]
=== For the Data Engineer

Categorization for Connections [.badge.badge-early-access-relnotes]#Early Access#:: You can now choose to sort Connections by type rather than order added to ThoughtSpot. To enable this feature, contact your administrator.


[#10-2-0-cl-it-ops]
=== For the IT/Ops Engineer

[#10-1-0-cl-developer]
=== For the Developer

ThoughtSpot Embedded:: For information about the new features and enhancements introduced in this release, refer to https://developers.thoughtspot.com/docs/?pageid=whats-new[ThoughtSpot Developer Documentation^].
