The latest release of ThoughtSpot Cloud contains several new and enhanced features.

* <<8-10-0-cl-first,For the First User>>
* <<8-10-0-cl-analyst,For the Analyst>>
* <<8-10-0-cl-business-user,For the Business User>>
* <<8-10-0-cl-data-engineer,For the Data Engineer>>
* <<8-10-0-cl-it-ops-engineer,For the IT Ops Engineer>>
* <<8-10-0-cl-developer,For the Developer>>

[#8-10-0-cl-first]
=== For the First User

Getting started with ThoughtSpot Cloud::
The first user on the account has to complete a series of steps before other people can start using ThoughtSpot with your organization's data.
For these instructions, see xref:ts-cloud-getting-started.adoc[Getting Started with ThoughtSpot Cloud].

[#8-10-0-cl-analyst]
=== For the Analyst

Admins can manage all Monitor alerts::

Admins will be able to view, edit or delete alerts even if they are not the creator or subscriber of those alerts. For more information, see xref:monitor.adoc[Permissions].

SpotApps::

The DEI Workforce Diversity SpotApp is now available. Get invaluable insight into your workforce diversity data from your HR application. See xref:spotapps-dei.adoc[DEI Workforce Diversity SpotApp].

[#8-10-0-cl-business-user]
=== For the Business User

ThoughtSpot Sync Salesforce connection::

ThoughtSpot Sync Salesforce connection is now GA and on by default. You can now sync data directly from an Answer or custom SQL view to Salesforce. Using ThoughtSpot Sync, you can push insights directly to Salesforce, notify your teams, and view data in context. ThoughtSpot Sync automatically establishes a secure pipeline to the destination app and thus eliminates the need for building custom connectors. For more information, see xref:sync-salesforce.adoc[Sync data to Salesforce].

Schedule ThoughtSpot Sync::
ThoughtSpot Sync schedules are now GA and on by default. When creating a sync from ThoughtSpot to an external business app (Google Sheets, Microsoft Teams, Slack), you can now schedule the sync to repeat on an hourly, daily, weekly, or monthly basis. To try it out, create a sync and select *Schedule your sync*. For more information, see xref:thoughtspot-sync.adoc#pipelines[ThoughtSpot Sync].

Delete tables from ThoughtSpot::
Previously, when deleting tables from Connections, ThoughtSpot did not delete the table’s metadata completely. Starting in 8.10.0.cl, tables deleted through the ThoughtSpot UI disappear completely from your cluster.

// [#8-10-0-cl-data-engineer]
// === For the Data Engineer

[#8-10-0-cl-it-ops-engineer]
=== For the IT/Ops Engineer


Multiple AWS PrivateLinks::

ThoughtSpot now supports multiple AWS PrivateLinks in your environment, using any combination of the cloud data warehouses that ThoughtSpot supports for PrivateLink. If you have data in multiple cloud data warehouses that needs an additional layer of security and network reliability, you can set up an AWS PrivateLink between each CDW, for a maximum of five PrivateLinks.
+
For more information, see xref:connections-private-link-intro.adoc[].

Multi-tenancy with Orgs::

This release introduces ThoughtSpot’s multi-tenancy feature, which allows a ThoughtSpot cloud instance to be logically partitioned into multiple tenant-specific environments called *Orgs*.
+
This feature is off by default. To enable it, contact {support-url}. For more information, see xref:orgs-overview.adoc[Multi-tenancy with Orgs].

Object Usage Liveboard::
Use the Object Usage Liveboard to easily track how specific objects (Liveboards, Answers, Worksheets, or tables) are trending over time. Our new visualizations allow you to understand adoption on the object-level, and filter on a specific user or users to see usage on the user-level.

[#8-10-0-cl-developer]
=== For the Developer

ThoughtSpot Everywhere:: For information about the new features and enhancements introduced in this release, refer to https://developers.thoughtspot.com/docs/?pageid=whats-new[ThoughtSpot Developer Documentation^].
