The latest release of ThoughtSpot Cloud contains several new and enhanced features.

* <<9-12-5-cl-first,For the First User>>
* <<9-12-5-cl-analyst,For the Analyst>>
* <<9-12-5-cl-business-user,For the Business User>>
* <<9-12-5-cl-data-engineer,For the Data Engineer>>
* <<9-12-5-cl-developer,For the Developer>>

[#9-12-5-cl-first]
=== For the First User

Getting started with ThoughtSpot Cloud::
The first user on the account has to complete a series of steps before other people can start using ThoughtSpot with your organization's data.
For these instructions, see xref:ts-cloud-getting-started.adoc[Getting Started with ThoughtSpot Cloud].

[#9-12-5-cl-analyst]
=== For the Analyst

Note tile enhancements::
ThoughtSpot introduces the ability to customize note tiles. You can now customize the appearance of note tiles. You can also edit hyperlinks and iFrames that previously had to be deleted and replaced to make changes. Images within note tiles are now responsive to screen size. For more information, see xref:liveboard-notes.adoc[Liveboard note tiles].
// Mary. epic: SCAL-142949. doc: SCAL-205501. include less words about what you can do and add a gif.
// PM: Arpit

Query sets [.badge.badge-early-access-relnotes]#Early Access#::
You can create query sets, which can be used to classify values in a list that you can then reuse across multiple analyses. A query set is a custom group of values from a collection of objects in your database.
Query sets are community objects which remain when you navigate away from the *Search Data* page and can be used by any user with view access to the underlying Worksheet. To enable this feature, contact {support-url}. For more information, see xref:custom-groups.adoc[].
// Mary. epic: SCAL-164083. doc: SCAL-203599.
// PM: Damian

Custom charts [.badge.badge-beta-relnotes]#Beta#::
You can now use custom charts created outside of ThoughtSpot, including third-party chart libraries. To enable this feature, contact {support-url}. For more information, see xref:chart-byoc.adoc[Custom charts].
// Mark -- SCAL-202002, doc jira: SCAL-179003

// Naomi. jira: SCAL-181350. docs jira: SCAL-223848
Alation authentication::
You can now connect to Alation using token-based authentication as well as service account authentication. For more information, see xref:catalog-integration.adoc[Alation catalog integration].

Sage Coach enhancements::
// Naomi. epic: SCAL-194540. doc: SCAL-209711
// PM: Alok, Anant
We made the following changes to Sage Coach:


* Only users with Worksheet editing rights can promote feedback to the global access level so that it applies user queries on the Worksheet.
* Once feedback is promoted to global access level, users without worksheet editing access cannot take any actions on it. For more information on the changes in the permission model, refer to
xref:sage-coach.adoc#permissions[Sage Coach permissions].
* When a Worksheet column is modified, such as a column name change, the changes are reflected in Sage Coach feedback. When a column is deleted, any feedback using that column is also removed. While saving a changed Worksheet, you have the option to review the impacted feedback, ensuring accurate updates upon confirmation.
* You can now edit query fragment text before submitting feedback. Additionally, you can edit the natural language query terms along with the Answer tokens through the Sage Coach flow.

Save table layouts in models::
ThoughtSpot introduces the ability to save table layouts in the schema viewer. Table location and size are now maintained and saved in the schema viewer. For more information, see xref:models.adoc[Building your model].
// Mary. epic: SCAL-180590. doc: SCAL-202068.
// PM: Samridh

Language updates::
// Naomi. epic: SCAL-181448. doc: SCAL-199383 (approved). epic: SCAL-159833. doc: SCAL-208059 (approved)
// PM: Aashna
ThoughtSpot now supports xref:keywords-ko-KR.adoc[Korean] and we've also added synonyms for date and time based keywords in xref:keywords-de-DE.adoc[German] and xref:keywords-fr-FR.adoc[French] for a more accurate experience.

[#9-12-5-cl-business-user]
=== For the Business User

Redesigned home page [.badge.badge-early-access-relnotes]#Early Access#::
// Mark. doc jira: SCAL-151210
In this release, you can try our redesigned and customizable home page, where you can ask natural-language questions with Sage, view your watchlist, favorites, library of Answers and Liveboards, and more. With the new left-hand navigation, you can go directly to your Liveboards, Answers, SpotIQ Analysis, and Monitor Subscriptions.
+
This new home page experience is disabled by default. Contact your ThoughtSpot administrator to enable this feature for your cluster. After that, open your user profile, and in the _Experience_ section, set the _Navigation and Homepage_ to *New experience*. Note that this setting also enables persona-based navigation. For more information, see xref:thoughtspot-homepage.adoc[].

New persona-based navigation [.badge.badge-early-access-relnotes]#Early Access#::
// Mark. Doc jira: SCAL-175398
In this release, you can try our completely redesigned navigation experience organized by persona. The new app switcher allows business users, analysts, data engineers, administrators, and developers to work in separate contextual sections designed specifically for their needs. In addition, each app has left-hand navigation to create better consistency and ease of use for users switching between the different apps.
+
This new navigation experience is disabled by default. Contact your ThoughtSpot administrator to enable this feature for your cluster. After that, open your user profile, and in the _Experience_ section, set the _Navigation and Homepage_ to *New experience*. Note that this setting also enables the redesigned home page. For more information, see xref:thoughtspot-homepage.adoc[].

Drill down in change analysis::
// Naomi – SCAL-180942. doc: SCAL-205576 (approved)
// PM: Vikas
Drill down in change analysis is now on by default and available to all users. You can now drill down on specific columns in change analysis, in order to identify change drivers within your data. For example, if you run an analysis on sales monthly and find out that the 'jacket' item type changed the most, you can easily drill down on jacket sales and identify which region contributed the most to the change in sales. For more information, see xref:spotiq-change.adoc#iterative[Interative change analysis].

Forecasting [.badge.badge-early-access-relnotes]#Early Access#::
// Naomi. epic: SCAL-188788. doc: SCAL-205575 (approved)
// add gif?
// PM: Vikas
You can now use SpotIQ analysis to forecast future trends for your KPIs. ThoughtSpot uses machine learning models that learn from past trends, growth, and seasonality to project how the target metric will trend in the future. To enable this feature, contact your administrator. For more information, see xref:spotiq-forecasting.adoc[].

[#9-12-5-cl-data-engineer]
=== For the Data Engineer

Rules to sort TML::
ThoughtSpot introduces a consistent sort order when exporting the TML of an object (table, SQL view, Liveboard, etc.). This ensures that unnecessary differences don’t show up between TML files when the objects haven't really changed, and makes it easier to compare TML files.
// Mary. epic: SCAL-133208. doc: SCAL-199958.
//does this need to be in the what's new? sounds like a fix, not a feature. - awaiting confirmation from Samridh
//https://docs.thoughtspot.com/cloud/latest/tml-liveboards
// PM: Samridh


Role-based access control [.badge.badge-early-access]#Early Access#::
Role-based access control (RBAC) is now available to all users. RBAC allows for more granular access privileges. Use RBAC to apply privileges customized for your organizational needs.

NOTE: Once you enable RBAC it cannot be disabled.

To enable RBAC, contact {support-url}.




[#9-12-5-cl-developer]
=== For the Developer

ThoughtSpot Embedded:: For information about the new features and enhancements introduced in this release, refer to https://developers.thoughtspot.com/docs/?pageid=whats-new[ThoughtSpot Developer Documentation^].
