The latest release of ThoughtSpot Cloud contains several new and enhanced features.

* <<9-8-0-cl-first,For the First User>>
* <<9-8-0-cl-analyst,For the Analyst>>
* <<9-8-0-cl-business-user,For the Business User>>
* <<9-8-0-cl-data-engineer,For the Data Engineer>>
* <<9-8-0-cl-developer,For the Developer>>

[#9-8-0-cl-first]
=== For the First User

Getting started with ThoughtSpot Cloud::
The first user on the account has to complete a series of steps before other people can start using ThoughtSpot with your organization's data.
For these instructions, see xref:ts-cloud-getting-started.adoc[Getting Started with ThoughtSpot Cloud].

[#9-8-0-cl-analyst]
=== For the Analyst

// SCAL-158474
Database as a destination for Answer sync:: Using ThoughtSpot Sync you can now sync data directly from an Answer or a custom SQL view, to your Snowflake or Redshift cloud data warehouse.

//  SCAL-158473
Enhancements for TS Sync::
ThoughtSpot Sync allows you to connect and share complete Liveboards using Microsoft Teams and Slack. Previously, only Answers could be shared.


//SCAL-154204

Sage Coach feedback review::
You can now review user feedback from the Data workspace, and determine whether it should apply to only that user’s queries, or to the entire cluster. Use the *Query Feedback* modal to review feedback given to individual natural language queries, and use the *Query Term Feedback* modal to review the translation of individual natural language terms to search tokens.
For more information, see
xref:sage-coach.adoc[Sage Coach].

//  SCAL-156895
Custom Sorting [.badge.badge-early-access]#Early Access#::
ThoughtSpot introduces custom sorting of attributes to sort all chart types in a way that helps users to consume charts more efficiently. You can now sort on any attribute in a chart, using the custom sort column. Enter the attributes in order to set up a custom sort order. To enable this feature, contact your administrator.


[#9-8-0-cl-business-user]
=== For the Business User

IMPORTANT: The *Null and missing values in charts* feature has been postponed until the 9.10.0.cl release. Administrators may notice the ability to enable it as an early access feature, but the feature is disabled in this release so that we can make sure it performs up to our standards of quality in the 9.10.0.cl release. We apologize for the inconvenience.


// SCAL-154204
Give feedback to AI-generated Answers:: When giving feedback to AI-generated Answers in Sage, you now tell ThoughtSpot what search tokens to use to signify certain key terms. For example, when you search for "best performing products this year", ThoughtSpot responds with the top five products sorted by sum of sales. You can correct top five to top ten by clicking the thumbs-down icon and editing the Answer. ThoughtSpot then stores that feedback, and admin users and Worksheet owners can decide to apply the feedback globally, so that every time someone searches for "best" products, they receive the top ten results.
For more information, see xref:ai-answers.adoc#sage-coach[Give feedback to AI-generated Answers].


// SCAL-127727
Contextual alert creation on KPI charts [.badge.badge-early-access-relnotes]#Early Access#:: ThoughtSpot now preserves the filters you use on a KPI when you create a Monitor alert. Users with view access to the underlying Liveboard can now receive alert emails for filtered KPIs without saving the filters on the Liveboard. For more information, see xref:monitor.adoc[Monitor alerts].

// SCAL-172513
Change analysis: More insights:: Change analysis _More insights_ are now available to all customers and are enabled by default. For example, ThoughtSpot finds values that underwent the highest percentage change between the two data points defined in your analysis, and values whose share of the total changed the most. The insights appear below the main analysis in the change analysis pop-up window. Note that insights do not appear for measures of type `count` and `ratios`. For more information, see xref:spotiq-change.adoc#additional[Change analysis].

// SCAL-89341
Anomaly insights with Monitor alerts for time-series KPI [.badge.badge-early-access-relnotes]#Early Access#:: When you receive an email alert about a threshold or scheduled alert, ThoughtSpot now surfaces any anomalies found in your KPI. You can see the expected range of values, and click a link to view your KPI in the original Liveboard. For more information, see
xref:monitor.adoc#early-access[Monitor].

// SCAL-177812
KPI scheduled watchlist alert:: When you add a KPI to your homepage watchlist, ThoughtSpot automatically creates a scheduled alert. You receive emails with updates to the KPI on a periodic basis. You can edit all scheduled alerts from the *Monitor* tab. For more information, see
xref:thoughtspot-one-homepage.adoc#monitor[Track important KPIs].

////
// SCAL-159818
ThoughtSpot for Slack::
You can now ask ThoughtSpot questions using Slack. Install the ThoughtSpot Slack app, add it to a Slack channel, and you can ask questions of your data sources in natural language. ThoughtSpot answers in chart format. For more information, see xref:spotdev.adoc[ThoughtSpot Slack app].
////

//SCAL-163617
Personalized views::
Personalized views are now available to all users and on by default. Personalized views allow you to save your own set of values for filters and parameters in a Liveboard without editing the original Liveboard. You can change the values of the already present filters and parameters in a Liveboard and save the view for future use. Any changes made to the master Liveboard are carried over to the view, including changes made to pinned visualizations, tabs, filter chips, and re-ordering. Changes made to the view are not pushed to the master Liveboard. This eliminates the need to make multiple copies of a Liveboard with your preferred filter values, that can fall out of sync with the original.

// SCAL-169279
Atlan:: Atlan is now available to all customers and is on by default. You can now see verification status and descriptions on tables and columns imported from Atlan. This information appears when you click on the corresponding table or column in *Search data*. Once connected, this information is visible to all users. For more information, see xref:catalog-integration-atlan.adoc[Atlan catalog integration].

// SCAL-204112
Webhooks for KPI monitor alerts:: Webhooks for Monitor are now available to all users and on by default. You can create webhooks to initiate workflows in third-party applications based on KPI changes, or send KPI alert notifications to custom channels. For example, if you are monitoring a "current inventory" KPI for an inventory management use case, you can build a workflow to trigger an order placement in a third-party app when your current inventory drops below a particular threshold value. For more information, see xref:monitor-webhooks.adoc[].


// scal-162075
Donut charts:: We have renamed the pie chart as donut chart. For more information, see xref:chart-donut.adoc[Donut charts].

// scal-187051
Update to Liveboard PDFs:: We have removed the ability to add footer text and the existing admin footer set at the cluster for Liveboard PDFs. This resolves the issue of misaligned footers in exported PDFs from Liveboards. This applies to Liveboard PDFs only. For more information, see xref:liveboard-download-pdf.adoc[Download a Liveboard as a PDF].
[#9-8-0-cl-data-engineer]
=== For the Data Engineer

//SCAL-138688
Custom calendar enabled by default::
In this release, custom calendar is enabled by default for all connections, except for the following which don’t support custom calendar:

- Dremio
- Denodo

For details, see xref:connections-cust-cal.adoc[Custom calendar overview].

// SCAL-166161, SCAL-166160, SCAL-166159, SCAL-164909
Connections::
The following connections are now available to all customers and are on by default:

* xref:connections-google-alloydb-postgresql.adoc[Google AlloyDB for PostgreSQL]
* xref:connections-google-cloud-sql-postgresql.adoc[Google Cloud SQL for PostgreSQL]
* xref:connections-google-cloud-sql-sql-server.adoc[Google Cloud SQL for SQL Server]
* xref:connections-singlestore.adoc[SingleStore]

// SCAL-192459
Redshift-managed PrivateLink:: You can now create Redshift Connections using Redshift-managed PrivateLink, as well as AWS PrivateLink. For more information, see xref:connections-redshift-managed-private-link.adoc[].

// SCAL-169279
Atlan catalog integration:: You can now import metadata information related to your tables and columns from Atlan into ThoughtSpot. From the Data tab, you can set up a connection to Atlan to import column descriptions, column verification status, table descriptions, and table verification status. For more information, see xref:catalog-integration-atlan.adoc[Atlan catalog integration].

// SCAL-183256
Data Catalog for GCP::
ThoughtSpot does not support Data Catalog for GCP Cloud. Support for Data Catalog will be added in 9.12.0.cl.

// SCAL-132886
dbt public API::
You can now use the dbt public API to perform the following tasks:

* Create a dbt connection
* Delete a dbt connection
* Search a list of dbt connections
* Update a dbt connection
* Run dbt Sync
* Update dbt Sync

//For more information, see xref:dbt-integration.adoc#public-api[dbt public API].

// SCAL-160062
OAuth connection improvements:: If you do not have a valid OAuth access token, you can now directly navigate to the OAuth authorization screen when performing one of the following actions on a connection shared with you:

** View sample data
** Create a custom SQL view
** Edit the connection
** Upload a CSV file (Snowflake connections only)

// Naomi-- scal-187049

Snowflake account name restrictions::
In accordance with link:https://community.snowflake.com/s/article/Behaviour-Change-Release-information-associated-with-Snowflake-JDBC-driver-version-3-13-25#:~:text=This%20change%20was%20made%20to,my_account.snowflakecomputing.com[Snowflake's recent JDBC update], ThoughtSpot does not support Snowflake account names that contain underscores for connections that use Private Link. For more information on how to adjust your account name behavior to avoid this restriction, see xref:connections-snowflake-private-link.adoc#account-name[Snowflake Private Link].

////
// SCAL-134057. moved to 9.12
Support for deletion of Orgs::
You can now delete an Org without first removing all users, connections and objects.
////

// scal-187722
Org name limitations:: When an Org name is created, it becomes a subdomain of the cluster URL. As a DNS subdomain, an Org name cannot contain a space (' ') as a character. When used as a subdomain, any spaces in the Org name will be replaced with hyphens ('-').


// scal-164805
Disable SQL passthrough functions::
Admin users can now ban passthrough functions for all connections on their cluster, to prevent SQL injection attacks. This option is available under the *Search & SpotIQ* section of the *Admin* tab.





[#9-8-0-cl-developer]
=== For the Developer

ThoughtSpot Everywhere:: For information about the new features and enhancements introduced in this release, refer to https://developers.thoughtspot.com/docs/?pageid=whats-new[ThoughtSpot Developer Documentation^].
