The latest release of ThoughtSpot Cloud contains several new and enhanced features.

* <<9-5-0-cl-first,For the First User>>
* <<9-5-0-cl-analyst,For the Analyst>>
* <<9-5-0-cl-business-user,For the Business User>>
* <<9-5-0-cl-data-engineer,For the Data Engineer>>
* <<9-5-0-cl-it-ops-engineer,For the IT Ops Engineer>>
* <<9-5-0-cl-developer,For the Developer>>

[#9-5-0-cl-first]
=== For the First User

Getting started with ThoughtSpot Cloud::
The first user on the account has to complete a series of steps before other people can start using ThoughtSpot with your organization's data.
For these instructions, see xref:ts-cloud-getting-started.adoc[Getting Started with ThoughtSpot Cloud].

[#9-5-0-cl-analyst]
=== For the Analyst


Improved multi-tab PDF export from Liveboards:: Previously, you couldn’t export a liveboard with more than 40 visualizations, even if they were across multiple tabs. Starting in this release, you can now export a Liveboard with more than 40 visualizations, as long a single tab has no more than 40 visualizations.

Verified Liveboards:: Admin-assigned verifiers can now mark Liveboards as verified. Users can now request these verifiers to review their Liveboards, and verify if the information displayed is trusted content. Verified Liveboards carry a tag that signifies that they have been audited for correctness. For more information, see xref:liveboard-verify.adoc[Verified Liveboards].

Rename filters on a Liveboard:: You can now edit the display name of filters on Liveboards to better represent your data. To try it out, click the *Edit* icon on a Liveboard, click the filter you want to rename, select *Filter options*.

Custom groups [.badge.badge-beta-relnotes]#Beta#:: You can now create custom groups, which can be used to classify values in a list you can then reuse across multiple analyses. Custom groups are community objects which remain when you navigate away from the Search Data page and can be viewed by any user with view access to the underlying Worksheet. For more information, see xref:custom-groups.adoc[Custom groups].

Alation data catalog integration [.badge.badge-beta-relnotes]#Beta#:: You can now import metadata information related to your tables and columns from Alation into ThoughtSpot. From the *Data* tab, you can set up a connection to Alation to import column descriptions, column verification status, table descriptions, and table verification status. This information appears when you click on the corresponding table or column in *Search data*. Once connected, metadata information is visible to all users.
For more information, see
xref:catalog-integration.adoc[Catalog integration].

Date picker enhancement in Search:: We added support for rolling, fixed, and custom date filters when creating an Answer or filtering a Liveboard. Previously, when adding a date filter to a Search, ThoughtSpot supported the conditions `ON (=)`, `ON OR AFTER (>=)`, `BEFORE (<)`, and `BETWEEN`. Now, you can additionally filter for `ON OR BEFORE (\<=)`, `NOT BETWEEN`, `ON LAST`, and `ON NEXT`. To try it out, click the filter icon next to the Date column in the left side menu, or click the date filter below the Answer or Liveboard title. For more information, see
xref:date-filter.adoc[Date filters for Answers and Liveboards].

Monitor alerts in ThoughtSpot notifications:: You can now see notifications for threshold and anomaly alerts in the ThoughtSpot notification service, rather than receiving emails.


Single value selection for attribute filters:: When creating a Liveboard, you can now designate attribute filters as single-select, in addition to multi-select. For example, you could choose to make a Country filter single-select, so users would only see data related to one country at a time.


Geomap chart enhancements:: ThoughtSpot now supports the following enhancements for geomap visualizations:

* We now provide geomap data for all countries. For a full list, see link:https://wiki.openstreetmap.org/wiki/List_of_territory_based_projects[Openstreetmap supported countries].
* We now support multiple levels of subdivisions within a country, rather than just city and zip code.
// * Zip code data is now visualized as an area within a region, rather than a point on a map. You must select *Auto select* in the Geo config column of the source table or Worksheet to access this feature.
* We now support visualizations comparing subdivisions of multiple countries in a single visualization. For example, if a selected column contains data from cities in the United States and Mexico, all data would be displayed on a single visualization.
+
To enable these features, the *Geo config* property in the underlying Worksheet must be set to *Auto select*. All Worksheets created after 9.4.0.cl GA classify geographical data as *Auto select* by default.
+
For more information, see
xref:chart-geo.adoc#enhancement[Geo chart enhancements].

Responsive Liveboards:: We have improved the responsiveness of Liveboards. For windows between 1024 pixels and 500 pixels, the Liveboard columns respond to re-sizing. For windows smaller than 500 pixels in width, a horizontal scroll bar appears.

Chart display enhancements:: When you create bar and column charts and slice by color, ThoughtSpot automatically enables gridlines to make the chart easier to read. You can choose to disable gridlines under the chart configuration menu.

ServiceNow Incident Management (Snowflake Connector for ServiceNow):: In this release, there is a new ServiceNow Incident Management SpotApp which allows you to use your ServiceNow data stored in Snowflake. If you use the ServiceNow Snowflake connector to move your data from ServiceNow to Snowflake, use this SpotApp to track the number of tickets submitted, and understand the efficiency of how those tickets are resolved.
+
For more information, see
xref:spotapps-servicenow.adoc[ServiceNow Incident Management SpotApps].


[#9-5-0-cl-business-user]
=== For the Business User

Natural language search enhancements:: We made the following enhancements to natural language search:

* The following keywords are now supported in natural language search: "vs", "growth of", and "trend".

* Title and descriptions are now automatically created when you save an AI Answer.

* ThoughtSpot now stores feedback in order to correctly answer related questions. For example, if you correct the column used in an Answer about annual recurring revenue for 2023, ThoughtSpot uses the correct column in Answers about annual recurring revenue for 2022 and 2021.

Pivot table enhancements:: We made the following enhancements to pivot table charts:

- When you download an xlsx version of a pivot table, the measure values are displayed as numbers instead of the general format.
- When you download an xlsx version of a pivot table, row and column labels are shown as separate cells rather than as a column-separated list.
- You can no longer add conditional formatting to a pivot table in heatmap mode.
- Naming of subtotals and grand totals are now consistent in the chart and chart configuration dropdown.
- We now support hyperlinks in pivot tables.
- You can now choose to show or hide row and column summaries and subtotals, from the chart configuration menu. When summaries and subtotals are enabled, you can choose to display them at the top or bottom of the pivot table.


Admin controls for new data panel experience::
ThoughtSpot admins now have more control for enabling the new data panel experience for users. As before, an admin can enable the new data panel experience by going to *Admin* > *Early Access features*, and enabling *Data Fluency*. Each user can selectively enable the new data panel experience by going to their user profile, and setting the *Answer data experience* to *New experience*. In this release, admins can now make the new answer data panel experience default for all users of a cluster, by going to *Admin* > *Search & SpotIQ* and setting the *Make new answer data panel experience default* to *Enabled*.

Headline creation and pinning deprecation:: ThoughtSpot is deprecating the pin Headline to Liveboard feature. Beginning in the 9.4.0.cl Cloud release, users will no longer see the pin icon when they select table summaries. To visualize and pin single aggregated measures, attributes in string/date format, or time-series metrics with sparklines, we recommend creating xref:chart-kpi.adoc[KPI charts]. Existing Headlines pinned to Liveboards will not be affected in this release. For more information, see
link:https://community.thoughtspot.com/s/article/How-to-convert-Headlines-to-KPI-charts[How to convert Headlines to KPI charts].


Webhooks for KPI monitor alerts [.badge.badge-beta-relnotes]#Beta#:: You can create webhooks to initiate workflows in third-party applications based on KPI changes, or send KPI alert notifications to custom channels. For example, if you are monitoring a "current inventory" KPI for an inventory management use case, you can build a workflow to trigger an order placement in a third-party app when your current inventory drops below a particular threshold value. Webhooks for Monitor is in beta and off by default. To enable it, contact {support-url}.

Editing in-use parameters:: When using a parameter in a Search, Answer, or Liveboard, you can now change the allowed values type (for example, from *List* to *Range*). You can also add or delete values from a list parameter while it's in use, or increase or decrease the minimum and maximum values in a range parameter. We do not support changing the data type of the parameter (for example, from `INT` to `DATE`). For more information, see xref:parameters-create.adoc[Create parameters].

Mobile enhancements:: We made the following enhancements to ThoughtSpot Mobile:

* We extended the length of mobile sessions on ThoughtSpot Cloud. If a user visits the mobile app at least once every two weeks, they will no longer be logged out.

* We introduced a Watchlist tab on Mobile to make it easier for users to follow important metrics.

* We simplified the log in process for the ThoughtSpot mobile app. You can now enter your company email to receive an email with a magic link login, rather than entering the server URL.


Introduction of roles and more granular access privileges [.badge.badge-private-preview]#Private Preview#::

ThoughtSpot introduces role-based access control (RBAC) to allow for more granular access privileges. Use roles to apply privileges customized for your organizational needs.
+
ThoughtSpot includes some standard roles to help existing customers transition to RBAC. To enable RBAC, contact {support-url}.
See
xref:rbac.adoc[Understand RBAC and privileges].

ThoughtSpot for Connected Sheets add-on:: ThoughtSpot Connected Sheets is an add-on that allows you to connect to a ThoughtSpot instance, pull data directly into a Google Sheet from trusted data sources connected to that instance (like Snowflake, Google BigQuery, DataBricks, and others), and use the tools in Google Sheets for ad-hoc analysis.
+
For more information, see
xref:thoughtspot-sheets.adoc#sheets-connected[ThoughtSpot Connected Sheets].

[#9-5-0-cl-data-engineer]
=== For the Data Engineer

SingleStore connection [.badge.badge-early-access-relnotes]#Early Access#:: You can now create connections from ThoughtSpot to SingleStore.
For details, see xref:connections-singlestore.adoc[Connect to SingleStore].


Redshift OAuth with Azure AD IDP:: Redshift now supports external OAuth through Microsoft Azure AD. See xref:connections-redshift-azure-ad-oauth.adoc[Configure Azure AD external OAuth for a Redshift connection].

[#9-5-0-cl-it-ops-engineer]
=== For the IT/Ops Engineer

[#9-5-0-cl-developer]
=== For the Developer

ThoughtSpot Everywhere:: For information about the new features and enhancements introduced in this release, refer to https://developers.thoughtspot.com/docs/?pageid=whats-new[ThoughtSpot Developer Documentation^].
