The latest release of ThoughtSpot Cloud contains several new and enhanced features.

* <<10-8-0-cl-first,For the First User>>
* <<10-8-0-cl-business-user,For the Business User>>
* <<10-8-0-cl-analyst,For the Analyst>>
* <<10-8-0-cl-data-engineer,For the Data Engineer>>
* <<10-8-0-cl-developer,For the Developer>>

[#10-8-0-cl-first]
=== For the First User

Getting started with ThoughtSpot Cloud::
The first user on the account has to complete a series of steps before other people can start using ThoughtSpot with your organization's data.
For these instructions, see xref:ts-cloud-getting-started.adoc[Getting Started with ThoughtSpot Cloud].

[#10-8-0-cl-business-user]
=== For the Business User

Spotter features::
// Naomi. jira: SCAL-226925. docs jira: SCAL-239972.
Spotter in Slack [.badge.badge-beta-relnotes]#Beta#:::
You can now use Spotter to conversationally search your data in Slack. Follow-up questions remain within the same thread, preserving context. Pin a Worksheet or Model to a channel to ensure quick access to data from that Worksheet or Model. Spotter in Slack replaces the ThoughtSpot app in Slack. To enable this feature, contact {support-url}.
+
--
NOTE: Spotter in Slack is not available for GCP and ThoughtSpot Embedded clusters yet.
--
+
For more information, see
xref:spotdev.adoc[Spotter in Slack].
// Naomi. jira: SCAL-240915, SCAL-233735. docs jira: SCAL-244744
Spotter in Microsoft Teams [.badge.badge-beta-relnotes]#Beta#::: You can now use Spotter to conversationally search your data in Microsoft Teams by chatting directly with the Spotter app in a direct message. Use the *Reset* command to start a new conversation. To enable this feature, contact your administrator.
+
--
NOTE: Spotter in Microsoft Teams is not available for GCP and ThoughtSpot Embedded clusters yet.
--
+
For more information, see xref:spotter-ms-teams.adoc[].
// Naomi. jira: SCAL-218237. docs jira: SCAL-239699
Learnability in conversation: feedback generation in follow-up questions:::
You can now give feedback on AI-generated Answers in Spotter without interrupting your searching conversation. When marking an Answer incorrect, you can now edit the underlying search, save, and review the search query tokens making up the Answer. If you mark an Answer correct, you can review and save the underlying search query tokens so Spotter remembers your choices in the future for similar questions.
+
For more information, see
xref:spotter-getting-started.adoc#learnability[Coach Spotter within a conversation].
// Naomi. jira: SCAL-214785. docs jira: SCAL-244489, SCAL-244634, SCAL-244636
Agentic skills in Spotter:::
Now, Spotter’s capabilities have expanded to include natural language responses, allowing Spotter to gather information about your business questions before translating answers into visualizations.
+
You can ask Spotter questions about the data model, or ask Spotter to query the warehouse and get data. For more information, see xref:spotter-data-insights.adoc[Spotter data insights].
+
Spotter can also answer 'why' questions.
For more information, see
xref:spotter-change-analysis.adoc[Spotter change analysis].
+
Spotter can take in broad topical questions, break them into smaller questions, and then generate multiple answers to answer your question.
For more information, see
xref:spotter-deep-analysis.adoc[Spotter deep analysis].
// Mary – jira: SCAL-233271. docs jira:SCAL-245110
Spotter shortcuts [.badge.badge-early-access-relnotes]#Early Access#::: ThoughtSpot introduces Spotter shortcuts that allow you to select from existing verified data constructs, including columns, filter values, and search data keywords. These shortcuts allow you to mix natural language and deterministic inputs when using Spotter. To enable this feature, contact {support-url}.
+
For more information, see xref:spotter-getting-started.adoc#spotter-shortcuts[Spotter shortcuts].
// Mark – jira: SCAL-230530. docs jira: SCAL-245105
Spotter preview data enhancement::: The *Preview data* feature in Spotter now supports complex models with multiple join paths, including chasm and fan traps.
For more information, see
xref:spotter-getting-started.adoc#spotter-preview-data[Getting started with Spotter].
// Naomi - jira: SCAL-233562, SCAL-232993. docs jira: SCAL-244415
Hover over Spotter tokens::: You can now hover over Spotter tokens to gain more information about the attributes, measures, formulas, and filters used in each Answer.
+
--
Attributes:::: Spotter displays a description in natural language, and lists sample values. Select *More details* to view column statistics (such as how many unique values exist), data type, and source.
Measures:::: Spotter displays a description in natural language. Select *More details* to view column statistics (such as minimum and maximum values), data type, and source.
Formulas:::: Spotter displays the formula used.
Filters:::: Spotter displays an explanation of the filter in natural language and a mention of which value is being filtered.
--
+
For more information, see
xref:spotter-best.adoc#tokens[Spotter query tokens].

//Mary. Jira: SCAL-226919. doc jira: SCAL-239109
Spotter on mobile::: ThoughtSpot introduces Spotter, our new AI-powered, unified conversational search experience on mobile.
+
For more information about Spotter on ThoughtSpot mobile, see the link:https://docs.thoughtspot.com/mobile/latest/mobile-ask-sage[ThoughtSpot mobile documentation site,window=_blank].

// Naomi. jira: SCAL-211323, SCAL-220341. docs jira: SCAL-225087
Analyst Studio:: ThoughtSpot introduces Analyst Studio, the collaborative creator space where data teams can come together to transform raw data into actionable insights. Analyst Studio provides a complete, integrated experience that blends SQL, Python, R, and visual analysis.
+
Key highlights of Analyst Studio:
+
--
Datasets::: Analyst Studio introduces an “extract” solution called Datasets, enabling the creation of periodic data snapshots with controlled refresh schedules.

AI-assisted SQL Editor::: The built-in SQL editor within Analyst Studio offers a powerful, AI-assisted  environment for directly manipulating and transforming data.

Python and R Notebooks::: Analyst Studio includes Python and R notebooks, providing the ability to perform advanced statistical modeling - all within a single platform.
--
+
For more information, see
ifndef::pendo-links[]
xref:analyst-studio-getting-started.adoc[Analyst Studio].


// Mary. JIRA: DAP-1452. Doc JIRA: SCAL-244155
Audit logs for Analyst Studio [.badge.badge-beta-relnotes]#Beta#::
Analyst Studio audit logs provide visibility into critical events within your workspace, enabling you to monitor activities and ensure compliance. You can review audit log to:

* Track changes to user roles and memberships.
* Monitor modifications to groups, collections, and connections.
* Review access and permissions changes.

+
For more information, see xref:analyst-studio-audit-logs.adoc[Audit logs for Analyst Studio].


// Mary. JIRA: SCAL-231999 & SCAL-231927 Doc JIRA: SCAL-244641 & SCAL-244642
Liveboard styling and grouping [.badge.badge-beta-relnotes]#Beta#::
ThoughtSpot introduces new styling and grouping options for Liveboards. Styles can be applied to a Liveboard, a tile, or a group of tiles to improve readability, differentiate specific content, or apply organizational branding guidelines.
+
For more information, see xref:liveboards.adoc#liveboard-grouping[Liveboard grouping and Liveboard styling].



[#10-8-0-cl-analyst]
=== For the Analyst

// Mary. jira: SCAL-224447. doc jira: SCAL-236449
Pivot table charts [.badge.badge-early-access-relnotes]#Early Access#:: ThoughtSpot introduces a brand new pivot table chart. The new pivot table charts have the following features:
+
--
* Faster load times with pagination.
//* You can now expand and collapse all in pivot tables.
* We now support custom sort order.
* You can now adjust column widths.
* You can now slice with measures and attributes.
* You can now use values for more granular control in configurations.
--
+
To enable this feature, contact your administrator.
+
For more information, see
xref:chart-pivot-table.adoc#pivot-table-2-0[Pivot table charts].

// Mary. jira: SCAL-194093. docs jira: SCAL-226615
Query set groups [.badge.badge-early-access-relnotes]#Early Access#:: ThoughtSpot's Query sets includes a graphical user interface or 'smart rules' to define grouping conditions. Conditions allow you to create groups using operators, to specify the parameters of the group.
+
For example, you could create a query set that list each customer, their sales dollar amount, and then add a formula that ranks the amount in descending order. You could then add groups to define Gold, Silver, and Bronze levels where Gold is ranked 1-10, Silver 11-50, and Bronze every other value.
+
To enable this feature, contact your administrator. For more information, see
xref:query-sets.adoc[Query sets].

// Mary -- SCAL-150356
Column sets [.badge.badge-early-access-relnotes]#Early Access#::
You can create column sets, which can be used to classify values in a list that you can then reuse across multiple analyses. A column set is a custom group of values from a single column. For example, you can use column sets to define regions with specific countries included or excluded. Column sets are community objects which remain when you navigate away from the Search Data page and can be used by any user with view access to the underlying Worksheet or Model. To enable this feature, contact {support-url}.
+
For more information, see
xref:column-sets.adoc[Column sets].

// Naomi. jira: SCAL-226052. docs jira: SCAL-239382
Spotter Conversations Liveboard:: We’ve introduced the *Spotter Conversations Liveboard* to give you real-time visibility into user interactions with Spotter. With this Liveboard, administrators can:
+
--
* Gain insights into user engagement and adoption metrics for Spotter.
* Track query trends and understand user intent.
* Monitor follow-up actions, including query refinements and edits within conversations.
* Analyze feedback to identify training gaps and improve dataset coverage.
--
+
For more information, see
xref:spotter-conversations-liveboard.adoc[Spotter Conversations Liveboard].

[#10-8-0-cl-data-engineer]
=== For the Data Engineer



// Naomi. jira: SCAL-226972. doc jira: SCAL-241403
Column name localization and aliasing [.badge.badge-beta-relnotes]#Beta#:: Models support the ability to define column name and description aliases based upon the selected system language. This allows for a single Model definition to persist across multiple languages, rather than the need to build separate Models for each language. The alias name and description are displayed across the platform based upon the user's selected system language.
+
For more information, see
xref:column-aliases.adoc[Column aliases and localization].

// Mark – jira: SCAL-233945. docs jira: SCAL-242708.
Create your own charts with Muze Studio [.badge.badge-beta-relnotes]#Beta#:: You can now create your own charts in ThoughtSpot using Muze Studio. A developer can create new chart types by writing the code for them in the code builder. To enable this feature, contact your ThoughtSpot administrator.
+
For more information, see
xref:chart-create.adoc[Creating charts with Muze Studio].

// Naomi. jira: SCAL-230405. docs jira: SCAL-239421
ClickHouse connection [.badge.badge-early-access-relnotes]#Early Access#:: You can now create connections from ThoughtSpot to ClickHouse. To enable this feature, contact your administrator. For more information, see
xref:connections-clickhouse.adoc[ClickHouse].

// Naomi. jira: SCAL-225380. SCAL-216227 doc jira: SCAL-227908
Gemini and Mistral LLM integration with Spotter [.badge.badge-beta-relnotes]#Beta#:: You can now choose the LLM to power your Spotter experience. Your options are Azure OpenAI, Google Gemini, or Mistral. For more information, see
xref:spotter-getting-started.adoc#llm-spotter[Choose LLM for Spotter].

// Naomi. jira: SCAL-206474. docs jira: SCAL-235082
Bridge support for SQL Server, SAP HANA, and Oracle:: Bridge provides options to securely connect your data source with ThoughtSpot Cloud, as an alternative to PrivateLink, VPC Peering, or VPN tunnels. We added support for Bridge for the following connectors:
+
--
* Oracle
* SAP HANA
* SQL Server
--
+
For more information, see
xref:connections-bridge.adoc[Bridge connectivity for Cloud Data Warehouses and Databases].


[#10-8-0-cl-developer]
=== For the Developer

ThoughtSpot Embedded:: For information about the new features and enhancements introduced in this release, refer to https://developers.thoughtspot.com/docs/?pageid=whats-new[ThoughtSpot Developer Documentation^].

