The latest release of ThoughtSpot Cloud contains several new and enhanced features.

* <<8-2-0-cl-first,For the First User>>
* <<8-2-0-cl-analyst,For the Analyst>>
* <<8-2-0-cl-business-user,For the Business User>>
* <<8-2-0-cl-data-engineer,For the Data Engineer>>
* <<8-2-0-cl-it-ops-engineer,For the IT Ops Engineer>>
* <<8-2-0-cl-developer,For the Developer>>

[#8-2-0-cl-first]
=== For the First User

Getting started with ThoughtSpot Cloud::
The first user on the account has to complete a series of steps before other people can start using ThoughtSpot with your organization's data.
For these instructions, see xref:ts-cloud-getting-started.adoc[Getting Started with ThoughtSpot Cloud].

[#8-2-0-cl-analyst]
=== For the Analyst

[#spotapps]
ServiceNow and Snowflake SpotApps [.badge.badge-update]#Beta#::
SpotApps are ThoughtSpot's new out-of-the-box solution templates built for specific use cases and data sources. They are built on Blocks, which are pre-built pieces of code that are easy to download and implement directly from the product. This release introduces the Analytics Blocks and the ServiceNow and Snowflake SpotApps. Analytics Blocks include pre-built Worksheet, Answer, and Liveboard Blocks.
+
The ServiceNow and Snowflake SpotApps mimic the ServiceNow and Snowflake data models. After you connect to your ServiceNow or Snowflake data in your cloud data warehouse, ThoughtSpot maps that data to SpotApp columns, and creates pre-built but still customizable worksheets, answers, and Liveboards, based on your ServiceNow data.
+
This feature is in beta and off by default. It is part of the <<data-tab,Data tab redesign>>, which is also in beta and off by default. To enable SpotApps and the Data tab redesign, contact {support-url}.

SQL-based views [.badge.badge-update]#Beta#::
This release introduces beta support for SQL-based views. Users can create views based on custom SQL queries, and use those views as data sources. This type of view has the same functionality as a view based on searching your data.
+
This feature is in beta and off by default. To enable it, contact {support-url}.

[#data-tab]
Data tab redesign [.badge.badge-update]#Beta#::
This release redesigns the *Data* section of the product. The new Data Workspace is still in the same place in the product. To access it, select *Data* from the top navigation bar. The redesign introduces several new features, such as SQL-based views and SpotApps, and makes the UI more intuitive.
+
This feature is in beta and off by default. To enable it,  contact {support-url}.

Pivot table scroll bar::
If your pivot table contains more than 2 measures, the column header now has a horizontal scroll bar, so you can see all your measures without taking up  excessive space in the pivot table.

Group aggregate enhancement::
When using a group aggregate formula in a Search, you can now view the results grouped at the level of detail specified in your aggregation formula.
+
For example, consider a query where you want to contrast total revenue per region between areas with above average revenue and below average revenue. Previously, queries of this type displayed individual areas with above or below average revenues in each region, but did not aggregate the results.
+
This enhancement also fixed an issue where queries including group aggregate formulas could not be visualized as charts.
+
This feature is in beta and off by default. To enable it, contact {support-url}.

[#8-2-0-cl-business-user]
=== For the Business User

HTML in answer titles and descriptions::
You can now use HTML 5 in titles and descriptions for answers and visualizations within Liveboards. For example, you can add a clickable link to a word or phrase in a description, or italicize part of an answer title.
+
This feature is only available for answers and visualizations within Liveboards; it is not available for Liveboard titles and descriptions.
+
Refer to xref:chart-html.adoc[Customize titles and descriptions with HTML].

Key Performance Indicator (KPI) chart type::

Support for attributes;;
You can now create KPI visualizations when you search for attributes, as well as measures. When you search for an attribute (for example, `product`), the KPI automatically displays the top result for that column. For more information, see xref:chart-kpi.adoc#kpi-attribute[KPI charts for attributes].
Conditional formatting;;
You can now add visual cues for KPIs or threshold metrics to easily show where you are falling short or exceeding targets. For more information on how to apply conditional formatting to your KPI, see xref:chart-kpi.adoc#kpi-conditional[KPI charts].
Support for Drill down, Show underlying data, and SpotIQ analyze;;
You can now right-click on the sparkline visual of any KPI chart to xref:search-drill-down.adoc[Drill down] to a finer-grained view of your data, xref:show-underlying-data.adoc[Show underlying data], or xref:spotiq-custom.adoc[run a custom SpotIQ analysis].

////
removing for now per vishal
Search suggestions [.badge.badge-update]#Beta#::
When you xref:search-answers.adoc[search across existing answers and Liveboards], ThoughtSpot now offers object suggestions based on objects you previously viewed or interacted with, not just popular objects. This allows you to quickly return to an object you were working on or looking at in a previous session.
+
This feature is in *Beta* and on only for select customers.
////

[#8-2-0-cl-data-engineer]
=== For the Data Engineer

[#connections-flow-data-portal]
New connection creation flow with data tab redesign::
If you have the new <<data-tab,redesigned data tab>> enabled, you can see the new Data Workspace page from the *Data* tab in the top navigation bar. To start creating a connection, click *Connections*, then click the connection type you want to create. The new Data Workspace allows you to create a connection without selecting tables or columns.

[#8-2-0-cl-it-ops-engineer]
=== For the IT Ops Engineer

[#okta]
Okta authentication [.badge.badge-update]#Beta#::

In this release, ThoughtSpot switched to a new, industry-standard cloud authentication method through Okta. ThoughtSpot now powers its internal authentication with Okta, which is the industry-leading authentication platform. This change is internal and has no impact on customers. After we enable this feature by default, all user authentication will automatically use the internal Okta service.
+
This new Okta authentication feature is in *Beta*, and off by default. To enable it, https://community.thoughtspot.com/customers/s/contactsupport[contact ThoughtSpot Support^].
+
This switch involves several external improvements to authentication, including security enhancements:

* Ability to map IDP attributes from the ThoughtSpot Admin Console (username, email, and display name)
* Account activation monitoring from the Users section of the Admin Console: if a user still needs to activate their account, you can see that information in the Users section and re-send their activation email
* Only Okta interacts with your IDP. Your ThoughtSpot cluster does not directly interact with your IDP.
* Local users create their own password during activation. Administrators do not create the password prior to activation.

[#8-2-0-cl-developer]
=== For the Developer

ThoughtSpot Everywhere:: For information about the new features and enhancements introduced in this release, refer to https://developers.thoughtspot.com/docs/?pageid=whats-new[ThoughtSpot Developer Documentation^].
