The latest release of ThoughtSpot Cloud contains several new and enhanced features.

* <<10-1-0-cl-first,For the First User>>
* <<10-1-0-cl-analyst,For the Analyst>>
* <<10-1-0-cl-business-user,For the Business User>>
* <<10-1-0-cl-data-engineer,For the Data Engineer>>
* <<10-1-0-cl-developer,For the Developer>>

[#10-1-0-cl-first]
=== For the First User

Getting started with ThoughtSpot Cloud::
The first user on the account has to complete a series of steps before other people can start using ThoughtSpot with your organization's data.
For these instructions, see xref:ts-cloud-getting-started.adoc[Getting Started with ThoughtSpot Cloud].

[#10-1-0-cl-analyst]
=== For the Analyst

// Mary – Jira: SCAL-158900. docs JIRA: SCAL-212555
Import and export sets using TML [.badge.badge-beta-relnotes]#Beta#:: You can now use TML to import and export column sets and query sets in ThoughtSpot. For more information, see xref:tml-sets.adoc[TML for Sets].



[#10-1-0-cl-business-user]
=== For the Business User

// Naomi – JIRA: SCAL-207062
Anomaly-based alerts [.badge.badge-early-access-relnotes]#Early Access#:: You can now receive alerts when data of KPIs you are subscribed to fall outside the predicted value range.
When creating an alert, you can specify the time and frequency at which ThoughtSpot checks the KPI’s data against the values predicted by ML models trained on the data. For example, you can create an alert for a `sales weekly` KPI, and specify that ThoughtSpot compare the values every Monday at 5 PM. You may also add individual subscribers to the alert. If the KPI's data falls outside the predicted range, ThoughtSpot sends an alert to your email and, if applicable, your subscribers' emails.
+
For more information, see xref:monitor.adoc#create_an_anomaly_alert[Create an anomaly alert].

// Naomi -- JIRA SCAL-201298
Keywords "of" and "percentage of":: The "of" and "percentage of" keywords are now on by default and available to all users. You can use the "of" and "percentage of" keywords to answer questions related to mix, contribution, share of, percentage, and total ratios. These keywords help answer questions such as, "What is the share of a certain store’s sales as a percentage of the regional whole?" To try out this feature, enter a search phrase in the search bar containing the keyword, such as `sales percentage of store region`, and press *Go*.
+
For more information, see xref:formulas-keywords.adoc[Keywords: Of and Percentage of].

// Naomi -- JIRA: SCAL-218932
Sort and filter fragment and query feedback:: You can now sort and filter columns in the Sage Coach fragment and query feedback pages. You can also search for specific values for `worksheet`, `feedback provider`, and `edited by` to further narrow your selection.

// Naomi – JIRA SCAL-214756
Semi-additive measures with first and last values:: Semi-additive measures with first and last values are now available to all users and on by default. A semi-additive measure, also known as snapshot data, is a measure that is usually aggregated for all attributes except for date and time. For certain measures, like inventory, you want to know what the value was at the beginning or end of a period. In that case, you can use the `last_value` function to find the inventory at the end of a month, rather than aggregating all values over the month. Similarly, you can use the `first_value` function to find out your stock at the beginning of a month.
+
For more information, see
xref:semi-additive-measures.adoc[Semi-additive measures with `first_value` and `last_value` functions] and xref:semi-additive-modeling.adoc[Modeling data for semi-additive measures].

[#10-1-0-cl-data-engineer]
=== For the Data Engineer

// Naomi - JIRA: SCAL-209029
OAuth for Starburst using Proof Key for Code Exchange (PKCE):: We now support xref:connections-starburst-add.adoc[OAuth with PKCE for Starburst].

// Naomi - JIRA: SCAL-212095
Bridge connectivity for Cloud Data Warehouses (CDWs) and Databases::
Bridge provides options to securely connect your data source with the ThoughtSpot Cloud, as an alternative to PrivateLink, VPC Peering or VPN tunnels. We support Bridge for the following Connectors:
+
--
* Amazon Athena
* Amazon Redshift
* Databricks
* Google BigQuery
* PostgreSQL
* Snowflake
* Starburst
* Trino
--
+
For more information, see
xref:connections-bridge.adoc[Bridge connectivity for Cloud Data Warehouses and Databases].

[#10-1-0-cl-it-ops]
=== For the IT/Ops Engineer

// Mary. JIRA: SCAL-197810. docs JIRA: SCAL-216615
// PM: Aashica - Awaiting Doc JIRA and access to PRD and release status

Local authentication support with IAMv2 [.badge.badge-early-access-relnotes]#Early Access#::
ThoughtSpot allows customers to enable or disable local authentication at the Org and cluster levels. To enable local authentication at the cluster level, administrators require the *Can manage authentication* privilege. To enable local authentication at the Org level, contact {support-url}.
+
NOTE: Org level settings override cluster level settings.
+
For more information, see xref:authentication-local.adoc[Managing local authentication].

// Mary. JIRA: SCAL-202402. docs JIRA: SCAL-212285
// PM: Aashica - Awaiting more info from Aashica
Org-specific URLs [.badge.badge-beta-relnotes]#Beta#::
ThoughtSpot introduces Org-specific URLs. URLs in emails now include Org context so that users are taken directly to the correct Liveboard in the correct Org even if they belong to multiple Orgs.
You can also move between different browser tabs that point to different Orgs.
+
For more information, see xref:orgs-overview.adoc[Multi-tenancy with Orgs].

[#10-1-0-cl-developer]
=== For the Developer

ThoughtSpot Embedded:: For information about the new features and enhancements introduced in this release, refer to https://developers.thoughtspot.com/docs/?pageid=whats-new[ThoughtSpot Developer Documentation^].
