The latest release of ThoughtSpot Cloud contains several new and enhanced features.

* <<november-cloud-2021-first,For the First user>>
* <<november-cloud-2021-analyst,For the Analyst>>
* <<november-cloud-2021-business-user,For the Business User>>
* <<november-cloud-2021-data-engineer,For the Data Engineer>>
* <<november-cloud-2021-it-ops-engineer,For the IT Ops Engineer>>
* <<november-cloud-2021-developer,For the Developer>>

[#november-cloud-2021-first]
=== For the First User
Getting started with ThoughtSpot Cloud::
The first user on the account has to complete a series of steps before other people can start using ThoughtSpot with your organization's data.
For these instructions, see xref:ts-cloud-getting-started.adoc[Getting Started with ThoughtSpot Cloud].

[#november-cloud-2021-analyst]
=== For the Analyst


////
removing these features for now per alok. may add back in

[#spotapps]
ServiceNow SpotApp +++<span class="label label-beta">+++Beta+++</span>+++::
SpotApps are ThoughtSpot's new out-of-the-box solution templates built for specific use cases and data sources. They are built on Blocks, which are pre-built pieces of code that are easy to download and implement directly from the product. This release introduces the ServiceNow SpotApp and Analytics Blocks. Analytics Blocks include pre-built Worksheet, Answer, and Liveboard Blocks. +
The ServiceNow SpotApp mimics the ServiceNow data model. After you connect to your ServiceNow data in your cloud data warehouse, ThoughtSpot maps that data to SpotApp columns, and creates pre-built but still customizable worksheets, answers, and Liveboards, based on your ServiceNow data. +
Refer to xref:app-templates.adoc[SpotApps]. +
This feature is in beta and off by default. It is part of the <<data-tab,Data tab redesign>> beta. To enable SpotApps and the Data tab redesign, link:https://community.thoughtspot.com/customers/s/contactsupport[contact ThoughtSpot Support].



SQL-based views +++<span class="label label-beta">+++Beta+++</span>+++::
This release introduces beta support for SQL-based views. Users can create views based on SQL queries, and use those views as data sources. This type of view has the same functionality as a view based on searching your data. +
This feature is in beta and off by default. To enable it, link:https://community.thoughtspot.com/customers/s/contactsupport[contact ThoughtSpot Support].


[#data-tab]
Data tab redesign +++<span class="label label-beta">+++Beta+++</span>+++::
This release redesigns the *Data* section of the product. To access this part of the product, select *Data* from the top navigation bar. The redesign introduces several new features, such as SQL-based views and SpotApps, and makes the UI more intuitive. +
This feature is in beta and off by default. To enable it,  link:https://community.thoughtspot.com/customers/s/contactsupport[contact ThoughtSpot Support].
////

[#date-interval-functions]
Date interval functions::
In this release, we introduced new functions for computing time intervals between two dates. In addition to the existing xref:formula-reference.adoc#diff_days[diff_days] and xref:formula-reference.adoc#diff_time[diff_time] functions, you can now use `diff_years`, `diff_quarters`, `diff_months`, `diff_weeks`, `diff_hours`, and `diff_minutes` to calculate time intervals at these additional granularities.
+
If your organization uses a xref:connections-cust-cal.adoc[custom calendar], which can specify a new starting date of a year, starting dates of quarters, a starting day of the month, and a starting day of the week, use the optional custom calendar argument with these functions to calculate the difference between the two dates.




[#auto-answer]
Automated answer creation in Setup::
We simplified the steps to create Search visualizations during Setup.
Now, you can select measures, attributes and date columns and immediately view suggested answers and visualizations.
For more information, see xref:automated-answer-creation.adoc[Create answers in Setup].

[#november-cloud-2021-business-user]
=== For the Business User

[#liveboard-announcement]
Starting in December 2021, ThoughtSpot refers to Liveboards instead of pinboards.
With Liveboards, you can have an interactive experience and get granular insights through live queries on cloud data, tailored for you.
You can use Liveboards to iterate, explore, and drill into more insights, and tell a continuously evolving data story. +
ThoughtSpot plans to support for several releases, and then retire, internal processes and external methods that use the older naming convention.

[#session-validity]
User session timeout and validity::
ThoughtSpot increased the duration of *idle session timeouts* and the *maximum session validity*, when you click *Remember me* on the login screen.
There is no change to the duration when you do not click *Remember me*.

* Idle session timeout: If a user is not active for 14 days, ThoughtSpot logs the user out, and the user must enter their login credentials again.
* Maximum session validity: ThoughtSpot forces the user's session to expire after 14 days, even if they are active throughout that period.

This change *_only_* affects new clusters created on the November Cloud release and later.
Clusters created on the October Cloud release and earlier have the old experience, even after they update to the November Cloud release.
In the old experience, the *idle session timeout* is 60 minutes with *Remember me*, and 30 minutes without it.
The old *maximum session validity* is 7 days with *Remember me*, and not available without it.

To increase idle session timeouts or maximum session validity for clusters created on the October Cloud release and earlier, https://community.thoughtspot.com/customers/s/contactsupport[contact ThoughtSpot Support^].

[#search-suggestions]
Search suggestions::
Search suggestions are now GA.
When you xref:search-answers.adoc[search across existing answers and Liveboards], ThoughtSpot now offers search suggestions in the search bar, based on your past searches and popular searches in your environment, in addition to object suggestions.
For example, if you type `Sal` in the search bar, it might now result in search suggestions like *Sales* and *Sales this year*, in addition to object suggestions like an existing Liveboard called *Sales in the east last year*.
+
ThoughtSpot provides search suggestions before you begin typing, but not object suggestions.

[#november-cloud-2021-data-engineer]
=== For the Data Engineer
[#connections-snowflake-azure-ad-oauth]
Azure AD external OAuth for Snowflake::
Snowflake now supports external OAuth through Microsoft Azure AD.
See xref:connections-snowflake-azure-ad-oauth.adoc[Configure Azure AD external OAuth for a Snowflake connection].

////
removing for now per alok
[#connections-flow-data-portal]
New connection creation flow with data tab redesign::
If you have the new redesigned data tab enabled, you'll see the new Data Portal page. To start creating a connection, you click *Connections* and then click the connection type you want to create. Also with the new data tab enabled, you have the option to create a connection without selecting tables or columns. On the Data Portal page you can create a SQL-based view from a connection.
////

[#november-cloud-2021-it-ops-engineer]
=== For the IT Ops Engineer
[#saml]
SAML assertion validity::
ThoughtSpot now supports 2 methods to increase the duration of validity for your xref:authentication-integration.adoc#saml-assertion[SAML assertion]: the `SessionNotOnOrAfter` attribute and the `maxAuthenticationAge` parameter.
You can ask ThoughtSpot to disable either one of these checks. If you use both, and either check fails, ThoughtSpot does not authenticate the user. Some IDPs do not support use of `SessionNotOnOrAfter`.
If your IDP does not support use of `SessionNotOnOrAfter`, remove that attribute from your IDP assertion and https://community.thoughtspot.com/customers/s/contactsupport[ask ThoughtSpot Support^] to enable `maxAuthenticationAge`.

[#multiple-idp]
Multiple Identity Providers for SAML login::
You can now configure SAML SSO login for more than one Identity Provider (IDP).
You may have multiple groups of users who need to log into ThoughtSpot but are managed by separate IDPs.
To configure this, https://community.thoughtspot.com/customers/s/contactsupport[contact ThoughtSpot Support^].

[#vpn]
OpenVPN support for Google BigQuery and Azure Synapse connections::
ThoughtSpot now supports secure access from ThoughtSpot Cloud to your data in Google BigQuery and Azure Synapse, through your OpenVPN server.
ThoughtSpot supports the following OpenVPN server implementations:

* https://openvpn.net/community-downloads/[OpenVPN Community Edition^]
* https://docs.microsoft.com/en-us/azure/vpn-gateway/vpn-gateway-howto-openvpn-clients[Azure VPN^]
* https://docs.aws.amazon.com/vpn/latest/clientvpn-admin/what-is.html[AWS Client VPN^]

To learn how to configure a VPN connection for your Google BigQuery or Azure Synapse connection, refer to xref:connections-gbq-open-vpn.adoc[OpenVPN for Google BigQuery] and xref:connections-synapse-open-vpn.adoc[OpenVPN for Azure Synapse].

[#november-cloud-2021-developer]
=== For the Developer

ThoughtSpot Everywhere:: For information about the new features and enhancements introduced in this release, refer to https://developers.thoughtspot.com/docs/?pageid=whats-new[ThoughtSpot Developer Documentation^].
