+++<span class="label label-dep">8.2.0.cl</span>+++ April 2022
[#8-2-0-cl-first]
=== For the First User

[#8-2-0-cl-getting-started]
Getting started with ThoughtSpot Cloud::
The first user on the account has to complete a series of steps before other people can start using ThoughtSpot with your organization's data.

[#8-2-0-cl-business-user]
=== For the Business User

[#8-2-0-cl-kpi]
Key Performance Indicator (KPI) chart type::
In this release, we made further improvements to KPIs.

[#8-2-0-cl-kpi-attributes]
Support for attributes::: You can now create KPI visualizations when you search for attributes, as well as measures. When you search for an attribute (for example, `product`), the KPI automatically displays the top result for that column.
[#8-2-0-cl-kpi-conditional-formatting]
Conditional formatting::: Conditional formatting enables you to add visual cues for KPIs or threshold metrics, to easily show where your measurements are falling short or exceeding targets.

[#8-2-0-cl-html-titles-descriptions]
HTML in answer titles and descriptions::
Within Liveboards, you can now use HTML code directly on answer and visualization titles and descriptions. For example, you can add a clickable link to a word or phrase in a description, or italicize part of an answer title.
+
Note that you cannot use this for the title and description of Liveboards, only for the answers and visualizations inside Liveboards.

[#8-2-0-cl-analyst]
=== For the Analyst

[#8-2-0-cl-spotapps]
ServiceNow and Snowflake SpotApps** [.badge.badge-update]#Beta#**::
ThoughtSpot built new solution templates, SpotApps, for specific use cases and data sources. We deliver them to you as Blocks, pre-built pieces of code that you can easily download and implement directly from our product.
+
This release introduces the Analytics Blocks and the ServiceNow and Snowflake SpotApps. Analytics Blocks include pre-built Worksheet, Answer, and Liveboard Blocks.
+
The ServiceNow and Snowflake SpotApps mimic the ServiceNow and Snowflake data models. After connecting to your ServiceNow or Snowflake data in your cloud data warehouse, ThoughtSpot maps the data to SpotApp columns, and creates functional and  customizable worksheets, answers, and Liveboards.
+
This feature is in beta, and off by default. It is part of the <<8-2-0-cl-data-tab,Data tab redesign>>, which is also in beta and off by default. To enable SpotApps and the Data tab redesign, contact {support-url}.

[#8-2-0-cl-sql-based-views]
SQL-based views **[.badge.badge-update]#Beta#**::
This release introduces beta support for SQL-based views. You can create views based on custom SQL queries, and then use them as data sources.
+
This feature is in beta and off by default. To enable it, contact {support-url}.

[#8-2-0-cl-data-tab]
Data tab redesign **[.badge.badge-update]#Beta#**::
This release introduces a new optimized design for the *Data*-management interface of ThoughtSpot. To access it, select *Data* from the top navigation bar. The redesign adds several new features, such as SQL-based views and SpotApps, and a more intuitive UI.
+
This feature is in beta and off by default. To enable it, contact {support-url}.

[#8-2-0-cl-data-engineer]
=== For the Data Engineer

[#8-2-0-cl-connections-redshift-aws-secrets-manager]
AWS Secrets Manager for Redshift connection passwords::
Amazon Redshift connections now support AWS Secrets Manager for clusters deployed on an AWS EC2 instance. You no longer have to enter a password when you create a new Redshift connection.
+
This feature is disabled by default. To enable it, contact {support-url}.

[#8-2-0-cl-connections-flow-data-portal]
New approach to creating connections, with Data tab redesign::
With the new <<8-2-0-cl-data-tab,redesigned data tab>>, the new Data Workspace interface on the *Data* tab allows you to create a connection. Simply click *Connections* and select the connection type: Snowflake, Amazon Redshift, and so on. With the new Data Workspace, you can quickly create a connection without first selecting target tables and columns.

[#8-2-0-cl-it-ops-engineer]
=== For the IT Ops Engineer

[#8-2-0-cl-okta]
Okta authentication **[.badge.badge-update]#Beta#**::

In this release, ThoughtSpot adopts the industry-standard cloud authentication through Okta. This change is internal, and has no impact on customers. When enabled, all user authentication automatically switches to the internal Okta service.
+
This new Okta authentication feature is in beta and off by default. To enable it, contact {support-url}.
+
Okta authetication introduces several external improvements and security enhancements:

* Okta maps your IDP attributes from the ThoughtSpot *Admin Console* (username, email, and display name).
* Monitor account activation on the *Admin Console > Users* section; if a user did not activate their account, that information is visible, and you can re-send their activation email.
* Only Okta, not your ThoughtSpot cluster, interacts with your IDP
* Local users create their own passwords during account activation; administrators do not have to create passwords for them..

[#8-2-0-cl-developer]
=== For the Developer

ThoughtSpot Everywhere:: For information about the new features and enhancements introduced in this release, refer to https://developers.thoughtspot.com/docs/?pageid=whats-new[ThoughtSpot Developer Documentation^].
