The latest release of ThoughtSpot Cloud contains several new and enhanced features.

* <<8-8-0-cl-first,For the First User>>
* <<8-8-0-cl-analyst,For the Analyst>>
* <<8-8-0-cl-business-user,For the Business User>>
* <<8-8-0-cl-data-engineer,For the Data Engineer>>
* <<8-8-0-cl-it-ops-engineer,For the IT Ops Engineer>>
* <<8-8-0-cl-developer,For the Developer>>

[#8-8-0-cl-first]
=== For the First User

Getting started with ThoughtSpot Cloud::
The first user on the account has to complete a series of steps before other people can start using ThoughtSpot with your organization's data.
For these instructions, see xref:ts-cloud-getting-started.adoc[Getting Started with ThoughtSpot Cloud].

[#8-8-0-cl-analyst]
=== For the Analyst

Custom sizes for visualizations in Liveboards [.badge.badge-beta-relnotes]#Beta#::
This release introduces custom tile sizes for visualizations within Liveboards. In addition to the 5 predetermined visualization sizes, you can now customize your Liveboard visualizations to be any size. See xref:liveboard-layout-edit.adoc#size[Edit the layout of a Liveboard].
+
This feature is in *Beta* and off by default. To enable it, contact {support-url}.

Formula function search bar::
The formula editor assistant now contains a search bar for formula functions. Use it to search for specific functions to include in your formula. Refer to xref:formula-add.adoc[].

year_name function::
The new `year_name` formula function returns the year in string format for a given date. This improves the behavior of formulas involving years when using a custom calendar with year values that are not in integer format. Refer to xref:formula-reference.adoc#year_name[Formula function reference].

Headline summaries for discontinuous group aggregate formulas::
We changed the default behavior for table aggregation summaries when the search contains a formulas that contain both a conditional clause (`if... then... else`) and a group_aggregate expression. When a user searches with a formula containing both a conditional clause and a group_aggregate expression, then ThoughtSpot detects the aggregation type on the first non-constant output clause and uses it in the headline summary. In this context, a non-constant output clause means any base column reference (for example, `Revenue`), or formula (for example, `sum(revenue)`).
+
For example, in the formula `group_aggregate(sum(if (Color = 'blue') then 0 else group_unique_count(Discount)))`, the headline summary would use `COUNT_DISTINCT`, since the first non-constant output clause within the `if... then... else` clause is `group_unique_count` and has an aggregation type of `COUNT_DISTINCT`.

[#spotapps-8-9]
SpotApps::

The following SpotApps are now available:
* xref:spotapps-facebook.adoc[Facebook Ads]: Use this SpotApp to measure ad performance across platforms to grow reach, engagement, & sales.
* xref:spotapps-salesforce.adoc[Salesforce Pipeline Analysis]: Use this SpotApp to track how prospects progress closer to closed deals.

[#8-8-0-cl-business-user]
=== For the Business User

Schedule ThoughtSpot Sync [.badge.badge-beta-relnotes]#Beta#::
When creating a sync from ThoughtSpot to an external business app (Google Sheets, Microsoft Teams, Slack), you can now schedule the sync to repeat on an hourly, daily, weekly, or monthly basis. To try it out, create a sync and select *Schedule your sync*. For more information, see xref:thoughtspot-sync.adoc#pipelines[ThoughtSpot Sync].

Explain change for KPI charts [.badge.badge-beta-relnotes]#Beta#::
You can now use SpotIQ analysis to directly identify the key drivers for recent change in your KPIs. KPI change analysis allows you to drill down into the causes of change in your KPIs and customize the insights generated by SpotIQ.
+
To access this feature, go to your KPI chart and select the caret icon to the right of the percent change label. The *Run change analysis* pop-up allows you to customize the columns ThoughtSpot analyzes. Note that ThoughtSpot runs change analysis between the two most recent data points defined by the KPI’s time bucket (for example, `daily` or `weekly`).
+
For more information on change analysis,
see xref:spotiq-change.adoc[Comparative analysis].


Apply tags from the Home page::
You can now apply and edit tags on Liveboards and answers directly from the Home page, as well as from the *Answers* and *Liveboards* tabs. To try it out, select the checkbox next to the name(s) of the answer(s) or Liveboard(s) you would like to tag and click the *Apply tags* button that appears. For more information, see xref:thoughtspot-one-homepage.adoc#object-tag[Home page].

Show underlying data improvements::
We have made the following improvements to the *Show underlying data* feature:

* When you right-click a table and select *Show underlying data*, ThoughtSpot displays only the visualized columns.
* You can now open the *Show underlying data* pop-up and click *Edit columns* to add or remove columns from your query.
* When you open the *Edit columns* pop-up, you can now search for column names using the search bar.
* The *Show underlying data* pop-up no longer disables columns by default. To disable columns from your query, click *Edit columns* and deselect the column name(s).

Improvements to German keywords::
This release improves the translated German keywords. See xref:keywords-de-DE.adoc[].

[#8-8-0-cl-data-engineer]
=== For the Data Engineer

[#snowflake-oauth-improvements]
Snowflake OAuth improvements::
This release brings improvements in how ThoughtSpot handles user tokens for Snowflake connections configured with Snowflake OAuth. If a user’s refresh token becomes invalid, the administrator or author of the connection can now run the Invalidate Tokens command to allow the user to re-authenticate and regain access to the insights provided by the connection, and the connection itself. Also, in this release the Role field has been added to the Snowflake OAuth connection details page, allowing a role to be added when the connection is created and changed when a connection is edited. See xref:connections-snowflake-edit.adoc#invalidate-tokens[Invalidating refresh tokens of a Snowflake connection].

[#snowflake-okta-oauth]
Snowflake Okta OAuth::
You can now use Okta as your authorization server for external OAuth. For details, see xref:connections-snowflake-okta-oauth.adoc[Configure Okta OAuth for a Snowflake connection].

[#starburst-azure-ad-oauth]
Starburst Azure AD OAuth::
You can now use Azure AD as your authorization server for external OAuth. For details, see xref:connections-starburst-oauth.adoc[Configure Azure AD OAuth for a Starburst connection].

[#new-connections]
New connections::
This release adds the following new connections:

- xref:connections-presto.adoc[Presto]
- xref:connections-trino.adoc[Trino]
- xref:connections-denodo.adoc[Denodo], which supports OAuth. See xref:connections-denodo-oauth.adoc[Denodo OAuth].

[#join-deletion]
Delete joins that have dependents::
You can now delete a join from the ThoughtSpot UI even if the join has dependents. Deleting the join does not delete the dependents. This allows you to delete a join and create it again in the other direction, without invalidating or deleting any dependent objects.
+
Refer to xref:relationship-delete.adoc[].

[#dbt-improvements]
Integration with dbt for Amazon Redshift and Google BigQuery::
This release supports integration with dbt for the following 2 new cloud data warehouses:
+
--
* Amazon Redshift
* Google BigQuery
--
+
Refer to xref:dbt-integration.adoc[].


[#8-8-0-cl-it-ops-engineer]
=== For the IT/Ops Engineer

[#ipsec-vpn]
IPSec VPN support for cloud data warehouse connections::
ThoughtSpot now supports secure access from ThoughtSpot Cloud to your data in ThoughtSpot's supported cloud data warehouses, through your IPSec VPN server.
+
To learn how to configure an IPSec VPN connection for your cloud data warehouse connection, refer to xref:connections-ipsec-vpn.adoc[].

[#okta]
Identity and Access Management V2::

Identity and Access Management V2 (IAMv2) is now GA. It is *_off_* by default. With IAMv2, ThoughtSpot switched to a new, industry-standard cloud authentication method through Okta. ThoughtSpot now powers its internal authentication with Okta, which is the industry-leading authentication platform. This change is internal and has no impact on customers. After we enable this feature by default, all user authentication will automatically use the internal Okta service.
+
This switch involves several external improvements to authentication, including security enhancements:
+
--
* Ability to map IDP attributes from the ThoughtSpot Admin Console (username, email, and display name).
* Account activation monitoring from the Users section of the Admin Console: if a user still needs to activate their account, administrators can see that information in the Users section and re-send their activation email.
* Only Okta interacts with your IDP. Your ThoughtSpot cluster does not directly interact with your IDP.
* Local users create their own password during activation. Administrators do not create the password prior to activation.
--
+
For more information, refer to xref:okta-iam.adoc[Identity and Access Management V2].

[#ts-eula-v2]
License agreement::
We made the following changes to the ThoughtSpot license agreement signing process:
+
--
* First-time admin users see a checkbox to agree to ThoughtSpot's terms and conditions upon login.
* Admin users on updated clusters see a banner to sign ThoughtSpot's terms and conditions within 30 days. You can sign the agreement by clicking *Accept* on the banner, or from *Admin > Legal*.
* If an admin user does not accept the ThoughtSpot terms and conditions within a 30-day period, cluster access is suspended for all users.
--
+
For more information, see link:https://www.thoughtspot.com/legal/thoughtspot-cloud-subscription-agreement[ThoughtSpot Cloud Subscription Agreement^].


[#8-8-0-cl-developer]
=== For the Developer

ThoughtSpot Everywhere:: For information about the new features and enhancements introduced in this release, refer to https://developers.thoughtspot.com/docs/?pageid=whats-new[ThoughtSpot Developer Documentation^].
