The latest release of ThoughtSpot Cloud contains several new and enhanced features.

* <<8-4-0-cl-first,For the First User>>
* <<8-4-0-cl-analyst,For the Analyst>>
* <<8-4-0-cl-business-user,For the Business User>>
* <<8-4-0-cl-developer,For the Developer>>

[#8-4-0-cl-first]
=== For the First User

Getting started with ThoughtSpot Cloud::
The first user on the account has to complete a series of steps before other people can start using ThoughtSpot with your organization's data.
For these instructions, see xref:ts-cloud-getting-started.adoc[Getting Started with ThoughtSpot Cloud].

[#8-4-0-cl-analyst]
=== For the Analyst

Liveboard and answer download footer::
This release introduces the ability for admins to specify a standard footer to add to all Liveboard and answer downloads. Use this functionality to add a confidentiality disclaimer, for example.
+
This feature is part of the xref:answer-experience-new.adoc[new answer experience] and the xref:liveboard-experience-new.adoc[new Liveboard experience]. The new answer experience is on by default, and the new Liveboard experience is off by default. If you are using the classic experiences, you cannot set a standard download footer. If you are using only the new answer experience, you can only set a standard download footer for answers, *_not_* Liveboards.
+
For more information, refer to xref:search-spotiq-settings.adoc[].

Conditional and number formatting for downloaded tables::
When you download a table in XLSX format, the downloaded table now shows the same conditional and number formatting as the table in ThoughtSpot. Refer to xref:search-download.adoc#table-formatting[Download your search].

SpotApps::
This release introduces several new SpotApps. ThoughtSpot maps your data from external applications, such as HubSpot, to SpotApp columns, and creates pre-built but still customizable worksheets, answers, and Liveboards, based on your data.
+
This release introduces the following new SpotApps:
+
--
* Okta
* Google Analytics
* HubSpot Marketing Email
* Snowflake Consumption Version 2
* Jira Sprint Management
--
+
The SpotApps feature is in beta and off by default. It is part of the <<data-tab,Data tab redesign>>, which is also in beta and off by default. To enable SpotApps and the Data tab redesign, contact {support-url}.


[#8-4-0-cl-business-user]
=== For the Business User

Geo map support for France::

// Naomi

We now support more detailed geographic maps for France. You can now create maps based on postal codes, as well as region and city name. For more information, see xref:geomap-reference.adoc#france[Geo map reference].

[#8-4-0-cl-developer]
=== For the Developer

ThoughtSpot Everywhere:: For information about the new features and enhancements introduced in this release, refer to https://developers.thoughtspot.com/docs/?pageid=whats-new[ThoughtSpot Developer Documentation^].
