


ThoughtSpot mobile 2.8.1  is now available.
These release notes include information about new features, fixed issues from the previous releases, and any known issues.

[#2-8-1-new]
== 2.8.1 New Features and Functionality

* Support for SpotIQ analysis to directly identify the key drivers for recent change in your KPIs.
* Support for IAMv2 login on ThoughtSpot Mobile.
* Introductions of ThoughtSpot mobile push notifications.


[#2-8-new]
== 2.8 New Features and Functionality

* Improved deep linking to ThoughtSpot Mobile.
* Internationalization and localization of ThoughtSpot Mobile.


[#2-7-new]
== 2.7 New Features and Functionality

* New login experience.
* Revamped User Interface.
* Support for push notification.
* Bug fixes.

[#2-6-new]
== 2.6 New Features and Functionality

* Support for Watchlist. You can now keep an eye on all of your favorite KPIs in one place.
* Support for tabs on Liveboards.
* New experience for Liveboards.
* Support for KPI charts on Liveboards.
* Bug fixes.

[#2-5-new]
== 2.5 New Features and Functionality

We have moved Liveboards to the new Answer experience on mobile in this release. This change also includes showing KPI charts on Liveboards and bug fixes.

[#2-4-new]
== 2.4 New Features and Functionality

* Provided support for trust certificates signed by user-added CAs.
* Check out the new Answer experience on ThoughtSpot Mobile. For more information on the new Answer experience, see xref:answer-experience-new.adoc[].
* KPI charts are now supported on the Answer page.
+
NOTE: KPI charts are not available on Liveboards at this time.

[#2-0-new]
== 2.0 New Features and Functionality

Version 2.0 supports more features that were previously available only through the ThoughtSpot web app, including:

* Deep linking
* Drill down

=== Deep linking

You can now share a link to objects in ThoughtSpot and a user can open the link in the mobile app or the web.
If a user has the mobile app, the link will open directly in the mobile app.
If they don't have the mobile app, the are presented with the option to download it or to view it on the web.
For details, see xref:mobile.adoc#[ThoughtSpot Mobile overview].

=== Drill down

You can now select data point(s) and drill down for more detailed information.
You can also trace the drill path back and reset it to the initial state.
For details, see xref:mobile.adoc#[ThoughtSpot Mobile overview].

[#1-5-new]
== 1.5 New Features and Functionality

* Support for ThoughtSpot 6.0 features including improved number formatting for data labels on the chart marks (bars, bubbles, lines) and axes.
* Grouping of axes, and axis renaming.
* Improved performance.

NOTE: If upgrading your cluster to ThoughtSpot 6.2, all mobile users *MUST* update their ThoughtSpot app to 1.5.
If they do not, they will not be able to sign in.

[#1-4-new]
== 1.4 New Features and Functionality

* Improved network status messaging to keep you better informed on your device's connection to the internet and/or VPN.
* You can now read the entire description on the visualization details page which originally displayed only one line.

[#1-4-fixed]
== 1.4 Fixed Issues

The following issues are fixed in the 1.4 release:

* The app crashes when applying filters on a Liveboard that has an empty date or measure filter.

[#1-3-new]
== 1.3 New Features and Functionality

* All-new design
* New Android app (for Android 6.0 or later)

[#1-2-new]
== 1.2 New Features and Functionality

* R charts are now supported.
* Data labels are now available on the iPad version for enhanced chart viewing.
* Quick support.
If you have any issues, you can now share debug logs with the ThoughtSpot mobile team, from the profile page.

[#1-2-fixed]
== 1.2 Fixed Issues

The following issues are fixed in the 1.2 release:

* Users can interact with "View Only" filters on Liveboards.
* Year data labels are off by one year when custom calendar settings are used.

[#1-1-2-new]
== 1.1.2 New Features and Functionality

* Auto-redirect Single Sign-On (SSO) for clusters with SSO enabled.

[#1-1-2-fixed]
== 1.1.2 Fixed Issues

The following issues are fixed in the 1.1.2 release:

* Dates appear as invalid on visualizations.
* Last updated time is sometimes one day later than it actually is.
* The home Liveboard refreshes randomly and does not follow the 30 minutes background to foreground logic.
* The "`Excluded`" filters applied in the ThoughtSpot web user interface appear in the "`Included`" list in the Mobile app.
* Cached data disappears even before new data loads.
* Clickable area for the close button on the Filters page is too small.
* "`Login with SSO`" on iPad is misaligned.
* Cascading filters do not work.
* Dates overlap on the x-axis when custom calendar is used.
