The multi-tenancy feature logically partitions a ThoughtSpot cloud instance into multiple tenant-specific environments called *Orgs*. With Orgs, each tenant’s data is isolated and protected with access control, and is invisible to the other tenants that share the same ThoughtSpot application instance.

If the Orgs feature is enabled on your instance, your cluster administrator can create an Org for each tenant account, configure groups and users, and control access to data objects. Each Org serves as an independent container with its own set of users and data, and provides the same user experience as that of a regular ThoughtSpot instance.

[NOTE]
====
The Orgs feature requires either the ThoughtSpot Enterprise Edition or the ThoughtSpot Embedded Enterprise Edition. See https://www.thoughtspot.com/pricing[ThoughtSpot pricing and editions^].

If you have either of these editions, contact {support-url} to enable Orgs. The Orgs feature is off by default. To learn about multi-tenancy using groups instead of Orgs, refer to https://developers.thoughtspot.com/docs/multitenancy-without-orgs[Multi-tenancy with groups^].
====