NOTE: You can enable a maximum of five PrivateLinks in your environment.

To deploy an AWS PrivateLink, you must work with {support-url} and follow the procedure in this article.

[#prerequisites]
== Prerequisites

* The {connection} data warehouse is running inside your AWS account.
* The ThoughtSpot cluster must be in the same AWS region as your {connection} account.
* You must obtain the ThoughtSpot AWS Account Amazon Resource Name (ARN) from {support-url}. This is required for step 7 of <<configure-aws,Configure the Endpoint Service>>. For example: `arn:aws:iam::999999999999:root`

== Enable an AWS PrivateLink for {connection}

To deploy an AWS PrivateLink between your {connection} data warehouse and the ThoughtSpot Cloud tenant, follow these steps.

. <<configure-aws,Configure the VPC Endpoint Service in your AWS Console>>
. <<exchange-information,Exchange AWS and ThoughtSpot information with ThoughtSpot Support>>
. <<accept-request,Accept the PrivateLink Request>>
. <<embrace,Configure Connections>>

[#configure-aws]
=== Configure the Endpoint Service in your AWS Console

After completing the <<prerequisites,prerequisites>>, you must configure the Endpoint Service.

. Sign in to the AWS Console.
. Create a Network Load Balancer (NLB) routing TCP traffic to your {connection} database.
. Note the number of the port you used to route the TCP traffic. You must provide {support-url} with this information later.
. Navigate to menu:AWS VPC Console[Endpoint Services > Create Endpoint Service].
. Select the NLB you created in step 2.
. *_Optionally_*, you can select *Require Acceptance for Endpoint*.
. Select menu:Endpoint Service[Whitelist principles > Add principles to whitelist].
Add the ThoughtSpot AWS Account Amazon Resource Name (ARN) that you obtained from {support-url} in the <<prerequisites,prerequisites>>.
. Select *Endpoint Service*.
. Write down the values for:

* *Service name*: for example, _com.amazonaws.vpce.us-west-2.vpce-svc-0123456789abcdef_
* *Port number*: for example, _5439_
* *Availability zones and availability zone IDs*: for example, _us-west-2a (usw2-az1)_
+
You must provide the service name, port number, availability zones, and availability zone IDs to {support-url}.

[#exchange-information]
=== Exchange AWS and ThoughtSpot information with ThoughtSpot Support

. Send the *Service name*, *Port number*, *Availability zones*, and *Availability zone IDs* you gathered in step 9 of <<configure-aws,Configure the Endpoint Service in your AWS Console>> to {support-url}.
. After ThoughtSpot Support configures the AWS PrivateLink in ThoughtSpot, ask them to send you the PrivateLink Endpoint DNS name.

[#accept-request]
=== Accept the PrivateLink Request

. Navigate to menu:VPC[Endpoint Services].
. Select the Endpoint Service you created in <<configure-aws,Configure the Endpoint Service in your AWS Console>>.
. Select *Endpoint Connections*.
. Select the connection from the ThoughtSpot AWS Account.
Its status should be _Pending Acceptance_.
. Select menu:Actions[Accept endpoint connection request].
