[#migrate]
== Migrate SpotApps
You can easily migrate a SpotApp you configured from one cluster to another using xref:scriptability.adoc[TML files]. To migrate a SpotApp you already configured, follow these steps:

. Navigate to *Data > SpotApps*.
. Select the SpotApp you would like to migrate.
. On the *Analytics Blocks* page, select *Download TML zip file* in the right middle of your screen.
. Navigate to the cluster you would like to add this SpotApp to.
. xref:connections.adoc[Connect] to the data that the SpotApp requires, if you have not already.
. In the cluster you would like to add this SpotApp to, navigate to *Data > Utilities*.
. In the *Import/Export TML* tile, select *Import TML*.
. In the *Import* interface, click *Select .zip or .tml files to upload*.
. In your file system, find and select the .zip file.
. Deselect any files in the `.zip` file you do not want to upload.
. If you constructed the file correctly, the *Import* interface displays a _Ready for import_ message for each TML file, and shows you which objects are validated.
. If any of the files show errors, you may need to check that the names of the columns and column values in the SpotApp files are the same as the names in your cloud data warehouse. Then, edit the TML file to use the names in your cloud data warehouse.
. Select *Import _n_ selected*.
. The *Import Status* screen displays the status of the objects you imported.
You can open the object(s) that you imported, or select *Exit* to return to the main object page.
