[#deploy]
== Deploy the SpotApp
After you complete the prerequisites for the SpotApp that you would like to deploy, you are ready to deploy the SpotApp and begin leveraging its pre-built content.

=== Prerequisites
Complete the prerequisites for the SpotApp you would like to deploy:

* xref:spotapps-databricks.adoc#prerequisites[Databricks Storage and Performance prerequisites]
* xref:spotapps-dei.adoc#prerequisites[DEI Workforce Diversity prerequisites]
* xref:spotapps-facebook.adoc#prerequisites[Facebook Ads prerequisites]
* xref:spotapps-gbq.adoc#prerequisites[GBQ Performance and Consumption prerequisites]
* xref:spotapps-google-ad-analysis.adoc#prerequisites[Google Ad Analysis prerequisites]
* xref:spotapps-google-analytics.adoc#prerequisites[Google Analytics prerequisites]
* xref:spotapps-hubspot.adoc#prerequisites[HubSpot Email Marketing prerequisites]
* xref:spotapps-jira-issue.adoc#prerequisites[Jira Issue Management prerequisites]
* xref:spotapps-jira-sprint.adoc#prerequisites[Jira Sprint Management prerequisites]
* xref:spotapps-linkedin-ads.adoc#prerequisites[LinkedIn Ads prerequisites]
* xref:spotapps-okta.adoc#prerequisites[Okta Application Management prerequisites]
* xref:spotapps-procurement-vulnerability.adoc#prerequisites[Procurement Vulnerability Analysis for SAP prerequisites]
* xref:spotapps-redshift.adoc#prerequisites[Redshift Performance and Consumption prerequisites]
* xref:spotapps-salesforce.adoc#prerequisites[Salesforce Pipeline Analysis prerequisites]
* xref:spotapps-servicenow.adoc#prerequisites[ServiceNow Incident Management prerequisites]
* xref:spotapps-snowflake.adoc#prerequisites[Snowflake Performance and Consumption prerequisites]

=== Deploy

To deploy the SpotApp, follow these steps:

. Navigate to *Data > SpotApps*.

. Select the SpotApp you would like to deploy.

. Select *Analytics Blocks*.

. To set up your Analytics Blocks, select *Configure*.

. Set up a connection to your data warehouse. Note that the connection name for each new SpotApp must be unique. To learn how to set up a connection, refer to xref:connections.adoc[Connections], and use the connection credentials that you collected in the <<prerequisites,prerequisites>>.
+
Note that you do not have to select any tables or columns while setting up the connection. You can select them later by editing the connection.

. After you create the connection, ThoughtSpot automatically maps databases, schemas, and tables from your cloud data warehouse to database, schema, and table names in the SpotApp. If ThoughtSpot cannot map any of the SpotApp databases, schemas, tables, a warning symbol appears next to the unmapped user object(s). To choose an object in your cloud data warehouse that matches the name of the object in the SpotApp, use the drop-down in the *User database*, *User schema*, or *User table* column.
+
For example, you might call a *problem* table something else, like *issues*. You can map your *issues* table to the *problem* table in the SpotApp.
+
Tables with asterisks next to their names are required. Other tables are optional.

. Select *Next*.

. Next, ThoughtSpot auto-maps columns from your cloud data warehouse to column names in the SpotApp. If ThoughtSpot cannot map any of the SpotApp columns, a warning symbol appears next to the unmapped user column(s). To choose a column in your cloud data warehouse that matches the name of the column in the SpotApp, use the drop-down in the *User column* column.
+
Columns with asterisks next to their names are required. Other columns are optional.
+
Select *Finish*.

. ThoughtSpot generates the objects in your SpotApp. This may take a few moments. When the generation is complete, a message appears at the bottom of your screen: `Analytics block for the SpotApp installed successfully`.

. After you configure the Analytics Block, ThoughtSpot returns you to the main *Analytics Block* page, where you can see a list of the objects ThoughtSpot created for your SpotApp. You can also see them in the list on the *Data* home page, and on the *Liveboards* page.
