To use scripting before or after the sync, follow these steps:

. Open the *Advanced setup* interface by clicking the toggle to open.
. Choose the *Sync properties* tab.
. Scroll down to *Advanced configuration*, and click the toggle to expand.
. Specify the following information:
[#set-sync-file-trigger]
Wait for file::
Specify the fully-qualified name of the file (directory path and file name) that must be present before sync can start.
+
NOTE: ThoughtSpot deletes the file after the sync process completes.
[#set-sync-pre-script]
Pre-script::
Add the script that you want to run *before* syncing.
+
Optional field.
+
Example:;;
*Drop data that is over 1 year old*; to find the correct functions for the script, click *Expression editor*, use it to create a valid command (or several commands), and click *OK*.
+
[source]
----
DELETE from FACT_TABLE Where DATE < ADD_DAYS(TODAY(),-365)
----
[#set-sync-post-script]
Post-script::
Add the script that you want to run *after* syncing.
+
Optional field.
+
Example:;;
*Drop data that is over 1 year old*; to find the correct functions for the script, click *Expression editor*, use it to create a valid command (or several commands), and click *OK*.
+
[source]
----
DELETE from FACT_TABLE Where DATE < ADD_DAYS(TODAY(),-365)
----

. Save your work by clicking *Save*.
+
Alternatively, click *Save and sync now* to save your work and sync data at the same time.
