The syntax and functionality of joins in the table TML file differs from the syntax and functionality for Worksheet and View TML files.

When you edit the information in the <<joins_syntax,joins>> section of the TML for a Worksheet or view, you override the table join(s) from the table the Worksheet or view comes from. However, you only override the join(s) for the specific Worksheet or view you are editing, *not* for the source table.

When you edit the information in the <<joins_with_syntax,joins_with>> section of the TML for a table, Worksheet, view, or SQL view, you edit the join information for the source object, the destination object, and any dependents, such as Worksheets and views. Note that you can only edit joins for which the object is the source.

See the <<join-parameters,TML parameters for joins>> for details about the keywords used in these examples.

See <<limitations,Limitations of working with TML files>> for more information about actions you can't perform using TML.

== Syntax for joins a Worksheet or view is built on

For the joins a Worksheets or view is built on, the join syntax is the following. The <<joins_syntax,joins>> section defines the joins that the Worksheet or view was built on, and the <<joins_with_syntax,joins_with>> section defines the joins from that Worksheet, view, or SQL view to another object. Note that SQL views and tables do not have the <<joins_syntax,joins>> section, but they may have the <<joins_with_syntax,joins_with>> section.

[#joins_syntax]

=== joins syntax

[subs=+macros]
....
<<joins,joins>>:
- <<name,name>>: <join_name_1>
  <<source,source>>: <source_table_name>
  <<destination,destination>>: <destination_table_name>
  <<type,type>>: [RIGHT_OUTER | LEFT_OUTER | INNER | OUTER]
  <<on,on>>: <join_expression_string>
  <<is_one_to_one,is_one_to_one>>: [ false | true ]
<<table_paths,table_paths>>:
- <<id,id>>: <table_path_name_1>
  <<table,table>>: <table_name_1>
  <<join_path,join_path>>:
  - <<join,join>>
    - <join_name_1>
    - <join_name_2>
....

[#joins_with_syntax]
=== joins_with syntax
[subs=+macros]
....
<<joins_with,joins_with>>:
- <<name,name>>: <join_name_1>
  <<description,description>>: <optional_join_description_1>
  <<destination,destination>>:
    <<name,name>>: <destination_table_name_1>
    <<fqn,fqn>>: <optional_table_guid_1>
  <<on,on>>: <join_expression_string_1>
  <<type,type>>: [RIGHT_OUTER | LEFT_OUTER | INNER | OUTER]
  <<is_one_to_one,is_one_to_one>>: [ false | true ]
  <<name,name>>: <join_name_2>
  <<name,name>>: <join_name_n>
....

=== Functionality and limitations of the joins section

You can accomplish the following tasks:

- Add new joins at the Worksheet, view, or SQL view level
- Modify existing joins at the Worksheet, view, or SQL view level
- Delete existing joins at the Worksheet, view, or SQL view level

You have the following limitation:

- You cannot modify joins at the table level from the Worksheet, view, or SQL view TML file. You can only override the joins for that specific Worksheet, view, or SQL view.

== Syntax for joins from a table, Worksheet, view, or SQL view to another object

To reduce ambiguity, you may need to add the optional `fqn` parameter to your TML file when you reference source tables or connections. This is necessary if you have multiple connections or tables with the same name. If you do not add the `fqn` parameter, and the connection or table you reference does not have a unique name, the file import fails.

The <<joins_with_syntax,joins_with>> section defines the joins from the data source to another object. It may appear in tables, Worksheets, views, and SQL views.

[subs=+macros]
....
<<joins_with,joins_with>>:
- <<name,name>>: <join_name_1>
  <<description,description>>: <optional_join_description_1>
  <<destination,destination>>:
    <<name,name>>: <destination_table_name_1>
    <<fqn,fqn>>: <optional_table_guid_1>
  <<on,on>>: <join_expression_string_1>
  <<type,type>>: [RIGHT_OUTER | LEFT_OUTER | INNER | OUTER]
  <<is_one_to_one,is_one_to_one>>: [ false | true ]
  <<name,name>>: <join_name_2>
  <<name,name>>: <join_name_n>
....

[#table-join-functionality]
=== Functionality and limitations of the joins_with section

You can accomplish the following tasks:

- Add new joins at the table level. Joins only appear in the table TML file of the source table in a join, or the table on the Many side of a Many-to-One join. You can only add and edit table joins from the TML file of the table on the Many side of the join.
- Create range joins at the table level, such as `Table1.date = Table2.date AND Table1.date > Table2.start_date AND Table1.date < Table2.end_date`.
+
Note that you must have an 'equals' clause before you can have a 'greater than/less than' clause. `Table1.date = Table2.date AND Table1.date > Table2.start_date AND Table1.date < Table2.end_date` is valid, but `Table1.date < Table2.end_date` is not.
+
Joins only appear in the table TML file of the source table in a join, or the table on the Many side of a Many-to-One join. You can only add and edit table joins from the TML file of the table on the Many side of the join.
+
*Generic/ range join example*:
+
----
name: LO to Date Range Join
    destination:
    name: DATE
    "on": "(([LINEORDER::Order Date] = [DATE::Datekey]) AND ([LINEORDER::Commit Date] < [DATE::Datekey]))"
    type: INNER
----

- Edit existing joins by changing the name of the join and modifying it to your specifications. Changing the name of the join creates a new join; you must then delete the old join. Joins only appear in the table TML file of the source table in a join, or the table on the Many side of a Many-to-One join. You can only add and edit table joins from the TML file of the table on the Many side of the join.

You have the following limitations:

- Renaming a join creates a new join with that name and does not delete the old join with the original name.
- When creating generic or range joins, you must have an 'equals' clause before you can have a 'greater than/less than' clause. `Table1.date = Table2.date AND Table1.date > Table2.start_date AND Table1.date < Table2.end_date` is valid, but `Table1.date < Table2.end_date` is not.

== Generic joins

The functionality for generic joins in TML files allows the following elements:

- Constants: int, double, bool, date, and string
- Comparison operators: `=`, `!=`, `<`, `>`, `\<=`, and `>=`
- Columns
- Boolean operators: `AND` and `NOT`. TML does *_not_* support use of `OR` in generic joins.
