== Syntax of the SQL view TML file

The `TML` file for SQL views has a specific syntax.

See the xref:parameters[TML parameters] for details about the keywords used in this example.

You may not see each of these parameters in your own TML files, depending on whether each variable is explicitly defined.
For example, the `fqn` parameter is not present in any TML file by default, but you can add it to differentiate a table from another table with the same name.

To reduce ambiguity, you may need to add the optional `fqn` parameter to your TML file when you reference source tables or connections. This is necessary if you have multiple connections or tables with the same name. If you do not add the `fqn` parameter, and the connection or table you reference does not have a unique name, the file import fails.

Refer to <<syntax-joins,join syntax>> for more information on the functionality and syntax of Worksheet, view, SQL view, and table joins in TML.

NOTE: If you edit the joins in the SQL view TML file, you are only editing the joins for that specific SQL view. You are not editing the joins at the table level. To modify table-level joins, you must edit the source table's TML file.

[subs=+macros]
....
<<guid,guid>>: <sql_view_guid>
<<sql_view,sql_view>>:
  <<name,name>>: <view_name>
  <<description,description>>:
    This is a multi-line description of the View.
    Description line 2
  <<connection,connection>>:
    <<name,name>>: <connection_name>
    <<fqn,fqn>>: <optional_connection_GUID>
  <<sql_query,sql_query>>: <sql_query_string>
  <<sql_view_columns,sql_view_columns>>:
  - <<name,name>>: <column_name_1>
    <<description,description>>: <optional_column_description>
    <<sql_output_column,sql_output_column>>: <sql_query_column_name>
    <<properties,properties>>:
      <<column_type,column_type>>: [ MEASURE | ATTRIBUTE ]
      <<aggregation,aggregation>>: [ SUM | COUNT | AVERAGE | MAX | MIN |
                     COUNT_DISTINCT | NONE | STD_DEVIATION | VARIANCE]
      <<index_type,index_type>>: [ DONT_INDEX | DEFAULT | PREFIX_ONLY |
                    PREFIX_AND_SUBSTRING | PREFIX_AND_WORD_SUBSTRING ]
 	    <<index_priority,index_priority>>: <index_priority>
      <<synonyms,synonyms>> :
             <synonym_1>
             <synonym_2>
      <<is_attribution_dimension,is_attribution_dimension>> : [true | false]
      <<is_additive,is_additive>> : [ true | false ]
      <<calendar,calendar>> : [ default | calendar_name ]
      <<format_pattern,format_pattern>> : <format_pattern_string>
      <<currency_type,currency_type>> :
        is_browser : true
          OR
        column : <column_name>
          OR
        iso_code : <valid_ISO_code>
      <<is_hidden,is_hidden>> : [ true | false ]
      <<geo_config,geo_config>> :
        latitude : true
          OR
        longitude : true
          OR
        country : true
          OR
        region_name:
        - country : <name_supported_country>
        - region_name : <region_name_in_UI>
      <<spotiq_preference,spotiq_preference>> : <spotiq_preference_string>
  - <<name,name>> : <column_name_2>
    <<description,description>> : <column_description_2>
    <<sql_output_column,sql_output_column>>: <sql_query_column_name_2>
    <<properties,properties>>:
    ...
  - <<name,name>> : <column_name_n>
    <<description,description>> : <column_description_n>
    <<sql_output_column,sql_output_column>>: <sql_query_column_name_n>
    <<properties,properties>>:
    ...
  <<joins_with,joins_with>>:
  - <<name,name>>: <join_name_1>
    <<description,description>>: <optional_join_description_1>
    <<destination,destination>>:
      <<name,name>>: <destination_table_name_1>
      <<fqn,fqn>>: <optional_table_guid_1>
    <<on,on>>: <join_expression_string_1>
    <<type,type>>: [RIGHT_OUTER | LEFT_OUTER | INNER | OUTER]
    <<is_one_to_one,is_one_to_one>>: [ false | true ]
  - <<name,name>>: <join_name_2>
  - <<name,name>>: <join_name_n>
....
