== Syntax of the Monitor alert TML file

The `TML` file for Monitor alerts has a specific syntax. The `Alerts.tml` file only appears when you export an Answer or Liveboard and its associated objects.

The `Alerts.tml` file defines the KPI Monitor alerts associated with the object. If you have administrator privileges, you see every alert for the object. Otherwise, you see only the alerts you created.

See the <<alert-parameters,TML parameters for Monitor alerts>> for details about the keywords used in this example.

See <<limitations,Limitations of working with TML files>> for more information about actions you can't perform using TML.

You may not see each of these parameters in your own TML files, depending on whether each variable is explicitly defined.
For example, for scheduled alerts, the `condition` parameter does not appear. The `condition` parameter only appears for threshold alerts.
You can add that section to the TML file to change a Monitor alert to a threshold alert.

To reduce ambiguity, you may need to add the optional `fqn` parameter to your TML file when you reference source tables. This is necessary if you have multiple tables with the same name. If you do not add the `fqn` parameter, and the table you reference does not have a unique name, the file import fails.

NOTE: We rebranded Pinboards to Liveboards. However, some of the parameters in the alerts.tml file still use Pinboard, not Liveboard. Ensure that you use the correct syntax.

[subs=+macros]
....

<<monitor_alert,monitor_alert>>:
- <<guid,guid>>: <alert_1_guid>
  <<name,name>>: <alert_1_name>
  <<frequency_spec,frequency_spec>>:
    <<cron,cron>>:
      <<second,second>>: <alert_1_time_seconds>>
      <<minute,minute>>: <alert_1_time_minutes>>
      <<hour,hour>>: <alert_1_time_hours>>
      <<day_of_month,day_of_month>>: <alert_1_day_of_month>>
      <<month,month>>: <alert_1_month>>
      <<day_of_week,day_of_week>>: <alert_1_day_of_week>>
    <<time_zone,time_zone>>: <alert_1_timezone>
    <<start_time,start_time>>: <alert_1_start_time>
    <<end_time,end_time>>: <alert_1_end_time>
    <<frequency_granularity,frequency_granularity>>: <alert_1_frequency>
  <<creator,creator>>:
    <<username,username>>: <alert_1_creator_username>
    <<user_email,user_email>>: <alert_1_creator_email>
  <<condition,condition>>:
    <<simple_condition,simple_condition>>:
      <<comparator,comparator>>: <alert_1_condition_operator>>
      <<threshold,threshold>>:
        <<value,value>>: <alert_1_threshold_value>
  <<metric_id,metric_id>>:
    <<answer_id,answer_id>>: <alert_1_answer_id>
    OR
    <<pinboard_viz_id,pinboard_viz_id>>:
      <<pinboard_id,pinboard_id>>: <alert_1_liveboard_guid>
      <<viz_id,viz_id>>: <alert_1_vizualization_guid>
    <<personalised_view_id,personalised_view_id>>: <alert_1_personalised_view_id>
  <<subscribed_user,subscribed_user>>:
  - <<username,username>>: <alert_1_subscribed_user_1_username>
  - <<user_email,user_email>>: <alert_1_subscribed_user_1_email>
  - <<username,username>>: <alert_1_subscribed_user_2_username>
  - <<user_email,user_email>>: <alert_1_subscribed_user_2_email>
<<personalised_view_info,personalised_view_info>>:
    <<tables,tables>>:
      - <<id,id>>: <optiona_table_id>
        <<name,name>>: <table_name_1>
        <<fqn,fqn>>: <optional_GUID_of_table_name>
    <<filters,filters>>:
      - <<column,column>>:
         - <table_name>::<column_name>
        <<oper,oper>>: <filter_operator>
        <<values,values>>: <filtered_values>
        - value 1
        - value 2
        - value n
        <<is_mandatory,is_mandatory>>: [ false | true ]
        <<is_single_value,is_single_value>>: [ false | true ]
        <<display_name, display_name>>: ""
      - <<column, column>>:
        - <table_name>::<column_name>
        <<is_mandatory,is_mandatory>>: [ false | true ]
        <<date_filter,date_filter>>:
          <<type,type>>: EXACT_DATE_RANGE
          <<oper,oper>>: between
          <<date_range,date_range>>:
            <<start_date,start_date>>: <start_date>
            <<end_date,end_date>>: <end_date>
        <<display_name,display_name>>: ""
- <<guid,guid>>: <alert_2_guid>
  <<name,name>>: <alert_2_name>
  <<frequency_spec,frequency_spec>>:
    <<cron,cron>>:
      <<second,second>>: <alert_2_time_seconds>>
      <<minute,minute>>: <alert_2_time_minutes>>
      <<hour,hour>>: <alert_2_time_hours>>
      <<day_of_month,day_of_month>>: <alert_2_day_of_month>>
      <<month,month>>: <alert_2_month>>
      <<day_of_week,day_of_week>>: <alert_2_day_of_week>>
    <<time_zone,time_zone>>: <alert_2_timezone>
    <<start_time,start_time>>: <alert_2_start_time>
    <<end_time,end_time>>: <alert_2_end_time>
    <<frequency_granularity,frequency_granularity>>: <alert_2_frequency>
  <<creator,creator>>:
    <<username,username>>: <alert_2_creator_username>
    <<user_email,user_email>>: <alert_2_creator_email>
  <<condition,condition>>:
    <<percentage_change_condition,percentage_change_condition>>:
      <<comparator,comparator>>: <alert_2_condition_operator>>
      <<threshold,threshold>>:
        <<value,value>>: <alert_2_threshold_value>
 <<metric_id,metric_id>>:
    <<answer_id,answer_id>>: <alert_2_answer_id>
    OR
    <<pinboard_viz_id,pinboard_viz_id>>:
      <<pinboard_id,pinboard_id>>: <alert_1_liveboard_guid>
      <<viz_id,viz_id>>: <alert_1_vizualization_guid>
  <<subscribed_user,subscribed_user>>:
  - <<username,username>>: <alert_1_subscribed_user_username>
  - <<user_email,user_email>>: <alert_1_subscribed_user_email>
....
