[#date-bucket]
== Date bucket settings for {object} [.badge.badge-beta]#Beta#

ThoughtSpot allows you to restrict how date columns are searched on Models and Worksheets. Contact {support-url} to enable the following features:

Strict date column:: When enabled, TIMESTAMP keywords (such as `hourly`) and menu items (filters such as `last ten minutes`) will be removed from DATE columns. Note that DateTime and Time columns are unaffected by this feature, and will continue to support sub-daily granular keywords and filters.
+
These keyword and filter restrictions apply both in the search bar and in filter models via the left panel menu or chart and table views.

<<default_date_bucket,Default date bucket>>:: When enabled, you can specify the default date bucket for Date and DateTime columns. The default date bucket options are the following: Hourly, Daily, Weekly, Monthly, Quarterly, and Yearly. Note that the Hourly option is only available for DateTime columns.
+
Once the default_date_bucket property is set for a date column, that bucket is used for default aggregation. For example, `revenue order date` would be the same as `revenue order date daily`.

<<is_time_bucket_restricted,Time bucket restricted>>:: When defined as "true" for a column, only the defined default time bucket is shown in the bucketing menu. For time bucket restriction to be enabled, `default_date_bucket` must be set.
+
Once `is_time_bucket_restricted` is set for a date column, only the default date bucket will be used for aggregation. For example, assuming that the default_date_bucket is defined as weekly, `revenue order date` would be the same as `revenue order date weekly`. However, `revenue order date daily` would no longer be recognized.

Disable future keywords:: When enabled, date filter keywords referring to the future, such as `next` and `tomorrow`, will not be suggested or recognized by the search bar. Those keywords will also be hidden from date filter dialogue windows.

Hide rolling filter:: When enabled, hides the rolling date filter section in the filter editor and disallows applying rolling filters from the editor.
