== Syntax of the Monitor alert TML file

The `TML` file for Monitor alerts has a specific syntax. The `Alerts.tml` file only appears when you export an Answer or Liveboard and its associated objects.

.[.badge.badge-beta]#Beta#
****
TML for Monitor alerts is in Beta and off by default. To enable it, contact {support-url}. For more about Beta features, see xref:release-lifecycle.adoc#beta[ThoughtSpot Cloud release life cycle].
****

The `Alerts.tml` file defines the KPI Monitor alerts associated with the object. If you have administrator privileges, you see every alert for the object. Otherwise, you see only the alerts you created.

See the xref:tml-parameters[TML parameters] for details about the keywords used in this example.

You may not see each of these parameters in your own TML files, depending on whether each variable is explicitly defined.
For example, for scheduled alerts, the `condition` parameter does not appear. The `condition` parameter only appears for threshold alerts.
You can add that section to the TML file to change a Monitor alert to a threshold alert.

NOTE: We rebranded Pinboards to Liveboards. However, some of the parameters in the alerts.tml file still use Pinboard, not Liveboard. Ensure that you use the correct syntax.

[subs=+macros]
....

<<monitor_alert,monitor_alert>>:
- <<guid,guid>>: <alert_1_guid>
  <<name,name>>: <alert_1_name>
  <<frequency_spec,frequency_spec>>:
    <<cron,cron>>:
      <<second,second>>: <alert_1_time_seconds>>
      <<minute,minute>>: <alert_1_time_minutes>>
      <<hour,hour>>: <alert_1_time_hours>>
      <<day_of_month,day_of_month>>: <alert_1_day_of_month>>
      <<month,month>>: <alert_1_month>>
      <<day_of_week,day_of_week>>: <alert_1_day_of_week>>
    <<time_zone,time_zone>>: <alert_1_timezone>
    <<start_time,start_time>>: <alert_1_start_time>
    <<end_time,end_time>>: <alert_1_end_time>
    <<frequency_granularity,frequency_granularity>>: <alert_1_frequency>
  <<creator,creator>>:
    <<username,username>>: <alert_1_creator_username>
    <<user_email,user_email>>: <alert_1_creator_email>
  <<condition,condition>>:
    <<simple_condition,simple_condition>>:
      <<comparator,comparator>>: <alert_1_condition_operator>>
      <<threshold,threshold>>:
        <<value,value>>: <alert_1_threshold_value>
  <<metric_id,metric_id>>:
    <<answer_id,answer_id>>: <alert_1_answer_id>
    OR
    <<pinboard_viz_id,pinboard_viz_id>>:
      <<pinboard_id,pinboard_id>>: <alert_1_liveboard_guid>
      <<viz_id,viz_id>>: <alert_1_vizualization_guid>
  <<subscribed_user,subscribed_user>>:
  - <<username,username>>: <alert_1_subscribed_user_1_username>
  - <<user_email,user_email>>: <alert_1_subscribed_user_1_email>
  - <<username,username>>: <alert_1_subscribed_user_2_username>
  - <<user_email,user_email>>: <alert_1_subscribed_user_2_email>
- <<guid,guid>>: <alert_2_guid>
  <<name,name>>: <alert_2_name>
  <<frequency_spec,frequency_spec>>:
    <<cron,cron>>:
      <<second,second>>: <alert_2_time_seconds>>
      <<minute,minute>>: <alert_2_time_minutes>>
      <<hour,hour>>: <alert_2_time_hours>>
      <<day_of_month,day_of_month>>: <alert_2_day_of_month>>
      <<month,month>>: <alert_2_month>>
      <<day_of_week,day_of_week>>: <alert_2_day_of_week>>
    <<time_zone,time_zone>>: <alert_2_timezone>
    <<start_time,start_time>>: <alert_2_start_time>
    <<end_time,end_time>>: <alert_2_end_time>
    <<frequency_granularity,frequency_granularity>>: <alert_2_frequency>
  <<creator,creator>>:
    <<username,username>>: <alert_2_creator_username>
    <<user_email,user_email>>: <alert_2_creator_email>
  <<condition,condition>>:
    <<percentage_change_condition,percentage_change_condition>>:
      <<comparator,comparator>>: <alert_2_condition_operator>>
      <<threshold,threshold>>:
        <<value,value>>: <alert_2_threshold_value>
 <<metric_id,metric_id>>:
    <<answer_id,answer_id>>: <alert_2_answer_id>
    OR
    <<pinboard_viz_id,pinboard_viz_id>>:
      <<pinboard_id,pinboard_id>>: <alert_1_liveboard_guid>
      <<viz_id,viz_id>>: <alert_1_vizualization_guid>
  <<subscribed_user,subscribed_user>>:
  - <<username,username>>: <alert_1_subscribed_user_username>
  - <<user_email,user_email>>: <alert_1_subscribed_user_email>
....
