ifndef::pendo-links[]
November 2025 [label label-dep]#10.14.0.cl#
endif::[]
ifdef::pendo-links[]
[month-year-whats-new]#November 2025#
[label label-dep-whats-new]#10.14.0.cl#
endif::[]

ifndef::free-trial-feature[]
NOTE: Features marked as [.badge.badge-update-note]#Beta# are off by default. To enable them, contact {support-url}.
endif::free-trial-feature[]

[#primary-10-14-0-cl]


// Business User

[#10-14-0-cl-conv]
[discrete]
=== Conversation history in Spotter

// Naomi. jira: SCAL-251490, SCAL-268901. docs jira: SCAL-265461, SCAL-268902.
// PM: Alok/Anant/ Mayur Selukar. marked 10.13.0.cl still, or not marked Release Ready. waiting to hear if you need a privilege to use it or if the data will be updated.

Spotter now saves your conversation history, preserving your past answers in the context of your searches.

[#10-14-0-cl-stop]
[discrete]
=== Stop Answer in Spotter

// Naomi. jira: SCAL-257617. docs jira: SCAL-268083
// PM: Alok. marked Commit

When you click the Send button to ask a question in Spotter, the button transforms into a Stop button as the answer generates. You can click the Stop button at any time before the answer finishes loading, if you decide your question was incomplete or might generate an incorrect response. Once you click the button, you can edit your input and click Send to generate a new answer.

ifndef::free-trial-feature[]
ifndef::pendo-links[]
[#10-14-0-cl-model]
[discrete]
=== AI context for Models [.badge.badge-beta]#Beta#
endif::[]
ifdef::pendo-links[]
[#10-14-0-cl-model]
[discrete]
=== AI context for Models [.badge.badge-beta-whats-new]#Beta#
endif::[]

// Naomi. jira: SCAL-269830. docs jira: SCAL-?
// PM: Anant

In addition to AI synonyms, you can now generate AI context for the columns in any Model you have edit access for. This context helps Spotter understand how to apply the columns to answer your data questions. Unlike the context you add to reference questions, which only apply to that question in particular, AI context in Models applies to any query based on the Model.

endif::free-trial-feature[]



[#10-14-0-cl-sort]
[discrete]
=== Custom sorting on answer page

// Mary. jira: SCAL-261454. docs jira: SCAL-275188
// PM: Manan

[#10-14-0-cl-byok]
[discrete]
=== COMS BYOK

// Mary. jira: SCAL-269862. docs jira: SCAL-269863
// PM: ?



// Analyst

[#10-14-0-cl-training]
[discrete]
=== Spotter coaching access

// Naomi. jira: SCAL-234908. docs jira: SCAL-267410, SCAL-268946
// PM: Anant. waiting on info



[#10-14-0-cl-follow]
[discrete]
=== Spotter coaching access follow-up

// Naomi. jira: SCAL-272576. docs jira: SCAL-272578
// PM: Anant. marked Commit. waiting on info.

[#10-14-0-cl-coaching]
[discrete]
=== Spotter context in coaching

// Naomi. jira: SCAL-264453. docs jira: SCAL-264454
// PM: Anant.

Rather than simply training Spotter Coach to recognize search tokens in reference questions, you can now add context, natural language explanations of why those tokens apply to that answer. For example, you could add an implicit rule to a sample reference question, clarifying that `sales` should only be calculated on completed transactions. Adding context to coaching improves accuracy and makes it easier to tailor Spotter to your data.

////
For more information, see
ifndef::pendo-links[]
xref:spotter-context.adoc[Context in Spotter].
endif::[]
ifdef::pendo-links[]
xref:spotter-context.adoc[Context in Spotter,window=_blank].
endif::[]
////
+++
<div class="border">
<script src="https://fast.wistia.com/player.js" async></script><script src="https://fast.wistia.com/embed/u1c1k36t0t.js" async type="module"></script><style>wistia-player[media-id='u1c1k36t0t']:not(:defined) { background: center / contain no-repeat url('https://fast.wistia.com/embed/medias/u1c1k36t0t/swatch'); display: block; filter: blur(5px); padding-top:62.92%; }</style> <wistia-player media-id="u1c1k36t0t" aspect="1.5894039735099337"></wistia-player>
</div>
+++

ifndef::free-trial-feature[]
ifndef::pendo-links[]
[#10-13-0-cl-instructions]
[discrete]
=== Spotter natural language instructions [.badge.badge-early-access]#Early Access#
endif::[]
ifdef::pendo-links[]
[#10-13-0-cl-instructions]
[discrete]
=== Spotter natural language instructions [.badge.badge-early-access-whats-new]#Early Access#
endif::[]

// Naomi – Jira: SCAL-267923. docs jira: SCAL-267924
// PM: Anant. who has permission. if not business user, move below the fold or to analyst section? is it the same person adding instructions from both places? add mp4.

You can now add natural language instructions directly to a Model in the Data workspace. For example, you can instruct Spotter to specify the date filter as the last 30 days if the user does not provide a date keyword. You can edit instructions directly in a conversation by clicking the instructions icon in Spotter. You must have edit access to a Model or administrator privileges to view and edit instructions. Instructions on a Model are limited to 3000 characters. To enable this feature, contact your administrator.

////
For more information, see
ifndef::pendo-links[]
xref:natural-language-instructions.adoc[Natural language instructions in Spotter].
endif::[]
ifdef::pendo-links[]
xref:natural-language-instructions.adoc[Natural language instructions in Spotter,window=_blank].
endif::[]
////

+++
<div class="border">
<script src="https://fast.wistia.com/player.js" async></script><script src="https://fast.wistia.com/embed/lpuh7ovr3o.js" async type="module"></script><style>wistia-player[media-id='lpuh7ovr3o']:not(:defined) { background: center / contain no-repeat url('https://fast.wistia.com/embed/medias/lpuh7ovr3o/swatch'); display: block; filter: blur(5px); padding-top:58.13%; }</style> <wistia-player media-id="lpuh7ovr3o" aspect="1.7204301075268817"></wistia-player>
</div>
+++


endif::free-trial-feature[]

[#10-14-0-cl-progressive]
[discrete]
=== Progressive Model filters

// Mary. jira: SCAL-255873. docs jira: SCAL-273001
// PM: Damian

ifndef::free-trial-feature[]
ifndef::pendo-links[]
[#10-14-0-cl-modeling]
[discrete]
=== Data modeling column alias UDF [.badge.badge-early-access]#Early Access#
endif::[]
ifdef::pendo-links[]
[#10-14-0-cl-modeling]
[discrete]
=== Data modeling column alias UDF [.badge.badge-early-access-whats-new]#Early Access#
endif::[]

// Naomi – Jira ID: SCAL-243256. docs jira: SCAL-?
// PM: Damian. waiting on info.


endif::free-trial-feature[]


ifndef::free-trial-feature[]
ifndef::pendo-links[]
[#10-14-0-cl-udf]
[discrete]
=== Column alias UDF [.badge.badge-early-access]#Early Access#
endif::[]
ifdef::pendo-links[]
[#10-14-0-cl-udf]
[discrete]
=== Column alias UDF [.badge.badge-early-access-whats-new]#Early Access#
endif::[]

// Naomi – Jira ID: SCAL-251015. docs jira: SCAL-273076
// PM: Damian. waiting on info.


endif::free-trial-feature[]


[#secondary-10-14-0-cl]
[discrete]
=== _Other features and enhancements_

// Data Engineer

[#10-14-0-cl-rls]
[discrete]
=== Sage indexing for Spotter filter values

// Naomi. jira: SCAL-264774. docs jira: SCAL-264775
// PM: Damian. marked 10.15.0.cl and Commit. waiting on info.

[#10-14-0-cl-sample]
[discrete]
=== Row-level security secure suggestions
// Naomi. jira: SCAL-262132. docs jira: SCAL-?
// PM: Damian. marked Commit

If you have Strict RLS enabled for your instance and apply RLS to a column on a Model, ThoughtSpot now displays only data the user has access to in sample values in Answers and Spotter preview data. Users will still be able to see suggested values in Search, so we recommend you set any column with values you don't want suggested as DONT_INDEX.


[#10-14-0-cl-atlas]
[discrete]
=== Atlas data inclusion in System Liveboard

// Rani. jira: SCAL-263794. docs jira: SCAL-272820
// PM: Shreyash?

[#10-14-0-cl-filter]
[discrete]
=== Decouple mechanism of fetching filter values in explore workflow from sage indexing

// Mary. jira: SCAL-268528. docs jira: SCAL-268530
// PM: Damian

ifndef::free-trial-feature[]
ifndef::pendo-links[]
[#10-14-0-cl-querygen]
[discrete]
=== Support for formula variables in querygen [.badge.badge-beta]#Beta#
endif::[]
ifdef::pendo-links[]
[#10-14-0-cl-querygen]
[discrete]
=== Support for formula variables in querygen [.badge.badge-beta-whats-new]#Beta#
endif::[]
// Naomi. jira: SCAL-257924. docs jira: SCAL-268027
// PM: Damian. waiting on info.

endif::free-trial-feature[]

ifndef::free-trial-feature[]
ifndef::pendo-links[]
[#10-14-0-cl-autocomplete]
[discrete]
=== Support for formula variables in autocomplete and sage metadata [.badge.badge-beta]#Beta#
endif::[]
ifdef::pendo-links[]
[#10-14-0-cl-autocomplete]
[discrete]
=== Support for formula variables in autocomplete and sage metadata [.badge.badge-beta-whats-new]#Beta#
endif::[]
// Naomi. jira: SCAL-257918. docs jira: SCAL-?
// PM: Damian. waiting on info.

endif::free-trial-feature[]



ifndef::free-trial-feature[]
ifndef::pendo-links[]
[#10-14-0-cl-variable]
[discrete]
=== Implement formula variable type in template variables [.badge.badge-beta]#Beta#
endif::[]
ifdef::pendo-links[]
[#10-14-0-cl-variable]
[discrete]
=== Implement formula variable type in template variables [.badge.badge-beta-whats-new]#Beta#
endif::[]
// Mary. jira: SCAL-209917. docs jira: SCAL-?
// PM: Damian

endif::free-trial-feature[]


// Developer

ifndef::free-trial-feature[]
[discrete]
=== For the Developer

For new features and enhancements introduced in this release of ThoughtSpot Embedded, see https://developers.thoughtspot.com/docs/?pageid=whats-new[ThoughtSpot Developer Documentation^].
endif::free-trial-feature[]