ifndef::pendo-links[]
June 2025 [label label-dep]#10.10.0.cl#
endif::[]
ifdef::pendo-links[]
[month-year-whats-new]#June 2025#
[label label-dep-whats-new]#10.10.0.cl#
endif::[]

ifndef::free-trial-feature[]
NOTE: Features marked as [.badge.badge-update-note]#Beta# are off by default. To enable them, contact {support-url}. These features are not available for Free Trial.
endif::free-trial-feature[]

[#primary-10-10-0-cl]


// Business User

[#10-10-0-cl-spotter]
[discrete]
=== Alerts by attribute

// Naomi – jira: SCAL-244702. docs jira: SCAL-258659
// PM: Rahul PJP

Alerts by attribute are now available to all users and on by default. You can now set KPI alerts to trigger when a selected attribute changes. This can include changes in the value of the attribute, such as an increase in sales by percentage by state, or a scheduled alert to trigger on a weekly basis.

For example, if you wanted to create an alert for a KPI tracking sales of different phones by brand, you could choose the intended brands as attributes and set an alert to be notified when sales for those specific brands dropped by 5%.

////
For more information, see
ifndef::pendo-links[]
xref:monitor-alert-attributes.adoc[Create an alert by attributes].
endif::[]
ifdef::pendo-links[]
xref:monitor-alert-attributes.adoc[Create an alert by attributes,window=_blank].
endif::[]
////
+++
<div class="border">
<video autoplay loop muted controls width="100%" controlsList="nodownload">
<source src="https://docs.thoughtspot.com/cloud/10.9.0.cl/_images/attribute-alert.mp4" type="video/mp4">
</video>
</div>
+++


// [#10-10-0-cl-nav]
// [discrete]
// === Navigation v3

// Mark. jira: SCAL-251909. docs jira: SCAL-?
// PM: Arpit - 5/31/25: Arpit said to not document it because it is moving to the 10.11 release.

// Analyst



'''
[#secondary-10-10-0-cl]
[discrete]
=== _Other features and enhancements_

// Data Engineer

ifndef::free-trial-feature[]
ifndef::pendo-links[]
[#10-10-0-cl-progressive]
[discrete]
=== Progressive model filters [.badge.badge-beta]#Beta#
endif::[]
ifdef::pendo-links[]
[#10-10-0-cl-progressive]
[discrete]
=== Progressive model filters [.badge.badge-beta-whats-new]#Beta#
endif::[]

// Naomi. jira: SCAL-221427. docs jira: SCAL-256366
// PM: Damian, Samridh. check if beta or EA.

Previously, any filter defined at the Model or Worksheet level applied to every query based on that Model or Worksheet. Now, you can define which table a filter applies to in the Model or Worksheet TML. Once defined, the filter only applies to queries that include columns from that specific table.

endif::free-trial-feature[]

[#10-10-0-cl-rls]
[discrete]
=== Monitor application of row-level security at database level

// Naomi. jira: SCAL-214002. docs jira: SCAL-?
// PM: Damian. reach out to Damian for image.

When opening SQL comments in your database, you can now see whether RLS was applied to specific queries. In the SQL comments, you can check whether the value for `isRLSApplied` is true or false.

[#10-10-0-cl-liveboard]
[discrete]
=== Make Spotter Liveboard available in all Orgs
The Spotter Conversations Liveboard is now available by default in all Orgs. In the primary Org, only administrators have access by default.
In secondary Orgs, Org administrators can access this Liveboard, similar to other system objects.
// Mary. jira: SCAL-245938. docs jira: SCAL-255650
// PM: Anant

[#10-10-0-cl-query]
[discrete]
=== Query tags for Snowflake

// Mary. jira: SCAL-240367. docs jira: SCAL-?
// PM: Prayansh - awaiting details from PM

[#10-10-0-cl-coms]
[discrete]
=== Email customization

// Rani. jira: SCAL-237254. docs jira: SCAL-256234
// PM: Mohil, Reshma


// Developer

ifndef::free-trial-feature[]
[discrete]
=== For the Developer

For new features and enhancements introduced in this release of ThoughtSpot Embedded, see https://developers.thoughtspot.com/docs/?pageid=whats-new[ThoughtSpot Developer Documentation^].
endif::free-trial-feature[]

////
[discrete]
=== Deprecated and removed features
Sage and Ask Sage are deprecated in this release and will be removed in a future release.

Instead of using Sage and Ask Sage, we encourage to you use Spotter. For more information, see xref:spotter.adoc[Spotter].

You still have the option to use Sage, but you must contact your ThoughtSpot administrator to enable it.

For information about other features to be deprecated or removed, see
ifndef::pendo-links[]
xref:deprecation.adoc[Deprecated and removed features].
endif::[]
ifdef::pendo-links[]
xref:deprecation.adoc[Deprecated and removed features,window=_blank].
endif::[]
////