= ["Introduction to Embedding"]
:last_updated: 11/18/2019
:permalink: /:collection/:path.html
:sidebar: mydoc_sidebar
:summary: You can embed ThoughtSpot in an external application, website, or portal.

ThoughtSpot Extended Enterprise Edition lets you give people outside of your company access to some ThoughtSpot capabilities within the context of an external application, website, or portal.
We call these people "`external users`".
For example, you could give external users access to data, search, search results, data visualizations, and/or pinboards.

External users cannot be granted administrative privileges or receive technical support from ThoughtSpot.
All first-line support must be handled through your company or organization.

ThoughtSpot Extended Enterprise Edition includes these capabilities:

* link:{{ site.baseurl }}/app-integrate/embedding-viz/about-full-embed.html[Full Application Embedding]
* link:{{ site.baseurl }}/app-integrate/embedding-viz/embed-a-viz.html[Embedded Charts and Pinboards]
* link:{{ site.baseurl }}/app-integrate/data-api/about-data-api.html[Data REST API]
* link:{{ site.baseurl }}/app-integrate/runtime-filters/about-runtime-filters.html[Runtime Filters]
* link:{{ site.baseurl }}/app-integrate/reference/metadata-api.html[Metadata API]

== Rights and Obligations

When you buy ThoughtSpot Extended Enterprise, the following rights and obligations apply:

. External users may only access those elements that are exposed through ThoughtSpot public APIs.
These include search, search results and data visualizations, saved Pinboards and Answers, SearchIQ [.label.label-beta]#Beta#, and SpotIQ.
. External users may not be granted Administrator privileges such as the ability to create and modify users and groups.
. External users are not permitted to copy or download the ThoughtSpot software.
. You may not include external users in a group that has access to these privileges:
 ** Can administer ThoughtSpot
 ** Can administer and bypass RLS
. The license for Extended Enterprise does not enable you to act as an MSP (Managed Service Provider).
This means that you must not offer managed services to third parties that are based on the ThoughtSpot software.
. As a company offering access to ThoughtSpot Extended Enterprise to external users, you are responsible for your own data policy and for complying with local laws and regulations concerning data privacy, such as GDPR and HIPAA.
. If you are using either *_Application Embedding_* or *_Embedded Search_*, an NPS (Net Promoter Score) survey will be offered to your external users.
You may not disable this survey.
+ If you are using either the *_Visualization Embedding_* or *_Pinboard Embedding_* in your application, it is okay to disable the NPS survey.
. Deployments of ThoughtSpot Extended Enterprise must conform to https://brand.thoughtspot.com/d/Vtg4Zg2mqTbE/brand-guidelines[logo restrictions].
+
These are the branding elements you can change in ThoughtSpot Extended Enterprise:

 ** link:{{ site.baseurl }}/app-integrate/custom-branding/upload-application-logos.html[Logos & Favicon]
 ** link:{{ site.baseurl }}/app-integrate/custom-branding/select-chart-color-palettes.html[Color Palettes]
 ** link:{{ site.baseurl }}/app-integrate/custom-branding/choose-background-color.html[Background Color]
 ** link:{{ site.baseurl }}/app-integrate/custom-branding/set-chart-and-table-visualization-fonts.html[Chart and Table Fonts]
 ** link:{{ site.baseurl }}/app-integrate/custom-branding/change-the-footer-text.html[Footer Text]

. You may not remove the _Powered by ThoughtSpot_ logo that appears at the bottom right of the embedded application when using ThoughtSpot full application embed, or when embedding a pinboard.
It is okay to remove the logo if you are embedding a single visualization.

== Section Contents

Here are the main topics for Embedding with Extended Enterprise:

* link:{{ site.baseurl }}/app-integrate/introduction/login-console.html[Log in to the Linux shell using SSH]
* link:{{ site.baseurl }}/app-integrate/introduction/logins.html[Login credentials]
* link:{{ site.baseurl }}/app-integrate/JSAPI/about-JS-API.html[Using the JavaScript API]
* link:{{ site.baseurl }}/app-integrate/SAML/about-SAML-integrations.html[SAML]
* link:{{ site.baseurl }}/app-integrate/data-api/about-data-api.html[Data REST API]
* link:{{ site.baseurl }}/app-integrate/embedding-viz/about-embedding-viz.html[Embed ThoughtSpot]
* link:{{ site.baseurl }}/app-integrate/runtime-filters/about-runtime-filters.html[Runtime Filters]
* link:{{ site.baseurl }}/app-integrate/custom-branding/perform-style-customization.html[Style Customization]
* link:{{ site.baseurl }}/app-integrate/reference/public-api-reference.html[API Reference]
