= Add {destination} as a Destination
:last_updated: 7/7/2022
:author: Naomi
:linkattrs:
:experimental:
:page-layout: default-seekwell
:description:
:destination: Google Sheets

== Prerequisites

* Authorize the destination app (link)

== Send data from Seekwell to {destination}

To send data from Seekwell, follow these steps:

. Enter a SQL query that pulls the data you want.

. Select "Destination" in the right sidebar.

. Select "Sheets" from the drop-down that appears.

.. Select "Spreadsheet", and scroll down to select your destination spreadsheet.

.. [optional] Select "Sheet1" and scroll down to choose your destination page in the spreadsheet, or search by typing the name of the destination page. To add a new sheet to an existing spreadsheet, select "Add it", and enter a name.


=== Append data to a {destination} spreadsheet from Seekwell

By default, Seekwell replaces existing data in the destination with the results of your query. To append data rather than replacing, select "Replace rows" and select "Append rows" from the drop-down.

NOTE: * You need to start your data in A1. Use a formula if you need the data placed somewhere specific on another sheet (e.g. put your daily data on daily!A1 then reference daily in your dashboard sheet as a formula).
* You can't have blank values in the first column.

//* Checking the append option omits column names. If you need an easy way to get all the column names, just write it without the Append option first and copy the column names.



=== Include or omit column names

By default, Seekwell omits column names when you choose to append data to an existing spreadsheet. To include column names when appending data, first write your query without selecting the Append option, and copy-paste the column names to your spreadsheet. Then, select Append to send your data to Google Sheets.
