Immediately after creating a new connection, the connection detail page appears.

When you schedule you create a sync, you have the following scheduling options:

* Hourly
* Daily(default)
* Weekly
* Monthly
* Does not repeat

After you specify the sync schedule, click *Save and sync now*.
This action saves the schedule, and starts the data sync immediately.

Alternatively, if you click *Save*, the system saves the schedule, but does not sync the data.
This gives you the opportunity to fine-tune the column mapping between external data sources and tables inside ThoughtSpot, such as naming, visibility, data type conversion, conditions, and so on.
The first sync starts on the specified schedule.

=== Hourly sync
+++<dlentry id="schedule-hourly-repeat">+++Repeat::::
Select *hourly*.
+ Mandatory field.+++</dlentry>++++++<dlentry id="schedule-hourly-starts">+++Starts::::
Accept the defaults, or set your own starting date and time for syncing.
+ Note that the timezone is in UTC+00:00.
+ Mandatory fields.+++</dlentry>++++++<dlentry id="schedule-hourly-hour">+++Run the task every X hour(s)::::
Select the frequency of the sync.
+ The valid range is from 1 (default) to 12 hours.
+ Mandatory field.+++</dlentry>++++++<dlentry id="schedule-hourly-alert-notifications">+++Alert notifications::::  Specify when to notify of the sync status: +

* Failures (default)
* Success and Failures
* Never+++</dlentry>+++

=== Daily sync
+++<dlentry id="schedule-daily-repeat">+++Repeat::::
Select *daily*.
+ Mandatory field.+++</dlentry>++++++<dlentry id="schedule-daily-starts">+++Starts::::
Accept the defaults, or set your own starting date and time for syncing.
+ Note that the timezone is in UTC+00:00.
+ Mandatory fields.+++</dlentry>++++++<dlentry id="schedule-daily-alert-notifications">+++Alert notifications::::  Specify when to notify of the sync status: +

* Failures (default)
* Success and Failures
* Never+++</dlentry>+++

=== Weekly sync
+++<dlentry id="schedule-weekly-repeat">+++Repeat::::
Select *weekly*.
+ Mandatory field.+++</dlentry>++++++<dlentry id="schedule-weekly-starts">+++Starts::::
Accept the defaults, or set your own starting date and time for syncing.
+ Note that the timezone is in UTC+00:00.
+ Mandatory fields.+++</dlentry>++++++<dlentry id="schedule-weekly-days">+++Days of the week::::
Select the days of the week when you want to sync.
+ For example, you may select only _Monday_, or only _Monday_ through _Friday_.
+ Mandatory field.+++</dlentry>++++++<dlentry id="schedule-weekly-alert-notifications">+++Alert notifications::::  Specify when to notify of the sync status: +

* Failures (default)
* Success and Failures
* Never+++</dlentry>+++

=== Monthly sync
+++<dlentry id="schedule-monthly-repeat">+++Repeat::::
Select *monthly*.
+ Mandatory field.+++</dlentry>++++++<dlentry id="schedule-monthly-starts">+++Starts::::
Accept the defaults, or set your own starting date and time for syncing.
+ Note that the timezone is in UTC+00:00.
+ Mandatory fields.+++</dlentry>++++++<dlentry id="schedule-monthly-days">+++Day of the Month::::
Select the days of the month when you want to sync.
+ Mandatory field.
+ There are two basic approaches: +
+++<dlentry>+++Cardinal day::::
Click the *Day* selector, and choose by date of the month from drop down menu.
+ For example, select `15` to run sync on 15th of each month.+++</dlentry>++++++<dlentry>+++Ordinal day::::
Click the *The* selector.
Then choose one of _First_(default), _Second_, _Third_, _Fourth_, or _Last_.
Then choose one of the days of the week, _Sunday_ through _Saturday_.+++</dlentry>++++++</dlentry>++++++<dlentry id="schedule-weekly-alert-notifications">+++Alert notifications::::  Specify when to notify of the sync status: +

* Failures (default)
* Success and Failures
* Never+++</dlentry>+++

=== Does not repeat
+++<dlentry id="schedule-no-repeat">+++Repeat::::
Select *Does not repeat*.
+ Mandatory field.+++</dlentry>++++++<dlentry id="schedule-no-repeat-alert-notifications">+++Alert notifications::::  Specify when to notify of the sync status: +

* Failures (default)
* Success and Failures
* Never+++</dlentry>+++
