== Syntax of the Pinboard and SpotIQ result TML file

The `TML` file for Scriptable Pinboards has a specific syntax.

[NOTE]
====
* SpotIQ results are in the form of Pinboards.
* Use the Pinboard TML syntax to edit a SpotIQ TML file.
====

See the xref:parameters[TML paramters] for details about the keywords used in this example.

You may not see each of these parameters in your own TML files, depending on whether each variable is explicitly defined.
For example, if you do not have any filters on your Pinboard, the `filters` parameter does not appear.
You can add that variable to the TML file to specify filters for your Pinboard.

....

pinboard:
  name: <pinboard_name>
  description:
    This is a multi-line description of the pinboard
    Description line 2
  visualizations:
  - answer:
    This section includes all the Answer specification for a visualization, from name to display_mode, in the Answer syntax section above.
    id: <viz_id_1>
  - answer:
    This section includes all the Answer specification for a second visualization. In this case, the visualization is a headline.
    id: <viz_id_2>
    display_headline_column: <headline_column>
  filters:
  - column: <filtered_column_name_1>
    oper: <filter_operator>
    values: <filtered_values>
    - value 1
    - value 2
  - column: <filtered_column_name_2>
  layout:
    tiles:
    - visualization_id: <visualization_id_1>
      size: <viz_id_1_size>
    - visualization_id: <visualization_id_2>
guid: <pinboard_guid>
....
