= ThoughtSpot Mobile Documentation
:page-layout: home-branch-mobile

++++
<style>
.doc-home .sidebarblock {
  background: #f1f1f1;
  border-radius: 0.75rem;
  border: 1px solid #4444;
  padding: 0.75rem 1.5rem;
  margin-top: 20px;
  margin-bottom: 20px;
  width: 96%;
}

.title {
  font-weight: 500;
  text-align: left;
  margin-top: 5px;
}

#preamble+.sect1, .doc .sect1+.sect1 {
  margin-top: 1rem;
  margin-left: 10px;
}

.sect1 {
  margin-left: 10px;
}

.sidebarblock .title img {
  margin-bottom: -12px;
  margin-right: 5px;
}

span.image {
    vertical-align: text-bottom;
}

img {
    max-width: 95%;
    margin-top: 10px;
    margin-bottom: 10px;
}

.home .columns .box li img.inline {
    margin-top: 0;
}

ul li img {
    margin-bottom: -10px;
}

.home h1, .home h2, .home h3 {
    line-height: 1.2;
    margin: 0;
    color: #444;
    margin-top: 2.5rem;
}

.doc-home .columns .box {
    padding-right: 8px;
}

/* remove drop shadows from persona boxes */
.home .columns .box {
    -webkit-box-shadow: 0 0px 0px rgba(0,0,0,0) !important;
    box-shadow: 0 0px 0px rgba(0,0,0,0) !important;
}

.image:not(.left):not(.right)>img {
    margin-top: -0.2em;
    margin-bottom: -10px;
}

.image>img, .doc .imageblock img {
    display: inline-block;
    height: auto;
    max-width: 100%;
    vertical-align: middle;
}

/*slide what's new section left to align with preamble */
.sect1 {
    margin-left: 0px !important;
}

/* slide what's new up slightly to be closer to persona boxes */
h2#_whats_new_in_thoughtspot_cloud {
    margin-top: 10px !important;
}

</style>
++++

ThoughtSpot Mobile allows you to discover insights in seconds from billions of rows of data, right from the palm of your hand. You can access your ThoughtSpot cluster to search Answers and Liveboards.


== Who uses ThoughtSpot Mobile
ThoughtSpot Mobile can be used by anyone who wants to connect to their ThoughtSpot cluster from a mobile client.

////
== Use cases
Use ThoughtSpot Mobile to access Answers and create or filter Liveboards.
////

== Latest updates

ThoughtSpot Mobile Version 3.3.0 supports more features that were previously available only through the ThoughtSpot web app, including:

* You can now view and switch between Orgs in ThoughtSpot Mobile.

For details, see xref:mobile-orgs.adoc[Mobile ThoughtSpot Mobile and Orgs].



'''
> **Related information**
>
> * xref:mobile-deploy.adoc[Deploy]
> * xref:mobile-install.adoc[Install and set up]
> * xref:mobile-faq.adoc[FAQ]
> * xref:notes-mobile.adoc[Release notes]