= Mobile FAQ
:last_updated: 6/6/2024
:linkattrs:
:experimental:
:page-aliases: /admin/mobile/faq-mobile.adoc
:description: These are a few frequently asked questions about ThoughtSpot Mobile.



== Caching data

You may wonder where does the mobile device store the cached data and login credentials.

The ThoughtSpot app stores two kinds of data:

* *Authentication data*
+
*Android*: Authentication data for Android is stored in an encrypted format in SharedPreferences that is only accessible to the ThoughtSpot App.
The key used to encrypt this data is stored in the Android default keystore system.
For more information, refer to Google's Android documentation on https://developer.android.com/training/data-storage/shared-preferences[SharedPreferences^].
+
*iOS*: Authentication data for iOS is stored in an encrypted database, called a keychain.
For more information, refer to Apple's documentation on https://developer.apple.com/documentation/security/keychain_services[Keychain Services^].

NOTE: You cannot access the data saved by ThoughtSpot Mobile from any other app.

== Deleting data saved on the mobile device, and restricting sharing

You may choose to deploy the ThoughtSpot app using management platforms like Airwatch, Mobile Iron, Microsoft Intune, and others.
They give you the flexibility to delete the mobile device's data and stop functionality like copy and paste, and screenshots.

'''
> **Related information**
>
> * xref:mobile-deploy.adoc[Deploy]
> * xref:mobile-install.adoc[Install and set up]
> * xref:notes-mobile.adoc[Release notes]