= ThoughtSpot Mobile Liveboards
:last_updated: 6/26/2024
:linkattrs:
:experimental:
:page-aliases:
:description: ThoughtSpot Mobile Liveboards.

Liveboards are the ThoughtSpot term for a dashboard. They group and manage related search result visuals.

What are Liveboards::
Liveboards act like live dashboards. They are collections of your related Answers, in the form of charts and tables, and your headline metrics.
Liveboard authors can pin charts and tables to any Liveboard that they create or edit. Liveboards can be shared with view privileges to mobile users.

You can view Liveboards created in the ThoughtSpot web app in ThoughtSpot Mobile. For more information about creating a Liveboard in the ThoughtSpot web app, see link:https://docs.thoughtspot.com/cloud/latest/liveboard[Create a Liveboard].

NOTE: ThoughtSpot Mobile users can view but not edit Liveboards in ThoughtSpot Mobile.

//insert screen cap


////
If user can't create the Liveboard in ThoughtSpot Mobile, let's mention that to create a Liveboard, they must create it in the ThoughtSpot web app, and link them to the appropriate article in the TSA docs.
////

