= ThoughtSpot Mobile overview
:last_updated: 6/6/2024
:linkattrs:
:experimental:
:page-aliases: /admin/mobile/use-mobile.adoc
:description: ThoughtSpot Mobile provides access to ThoughtSpot from your phone.



ThoughtSpot Mobile allows you to discover insights in seconds from billions of rows of data, right from the palm of your hand. You can access your ThoughtSpot cluster to search Answers and Liveboards.


== Who uses ThoughtSpot Mobile
ThoughtSpot Mobile can be used by anyone who wants to connect to their ThoughtSpot cluster from a mobile client.

////
== Use cases
Use ThoughtSpot Mobile to access Answers and create or filter Liveboards.
////

== Latest updates

ThoughtSpot Mobile Version 3.0.0 supports more features that were previously available only through the ThoughtSpot web app, including:

* You can now use ThoughtSpot Sage on ThoughtSpot Mobile version 3.0.0. You can ask a single natural language question on any AI enabled data source to get instant AI generated answers. You can ask by typing the question or use voice commands. You can save and share answers to facilitate collaboration.

For details, see xref:notes-mobile.adoc[Mobile release notes].



'''
> **Related information**
>
> * xref:mobile-deploy.adoc[Deploy]
> * xref:mobile-install.adoc[Install and set up]
> * xref:mobile-faq.adoc[FAQ]
> * xref:notes-mobile.adoc[Release notes]