= AgentSpot administration
:last_updated: 4/28/2026
:linkattrs:
:experimental:
:page-layout: default-agentspot-no-index
:page-aliases:
:description: Learn how to administer AgentSpot

This guide provides the essential steps for an administrator to set up AgentSpot for your team.

== Setting up AgentSpot

To set up AgentSpot, you must:

* *Add users*: For details, see <<#managing-users,Managing users>>.

* *Add connectors*: For details, see <<#managing-connectors,Managing connectors>>.

[#managing-users]
== Managing users
To add users to AgentSpot, you must do the following in your ThoughtSpot instance:

* Create a role with AgentSpot privileges.
* Add your role to a group.
* Add users to your group, as needed.

There are two primary AgentSpot privileges you can assign to a role:

[cols="1,3"]
|===
| Privilege | Description

| *Can manage AgentSpot* | Full administrative access to manage connectors, agents, and organization-wide settings
| *Can use AgentSpot* | Access to AgentSpot to use shared agents
|===

IMPORTANT: Users only appear in AgentSpot after they have been assigned a role containing one of these privileges.

=== Accessing your ThoughtSpot instance

Access your ThoughtSpot instance from AgentSpot by doing the following:

. Log in to AgentSpot.
. Click your user profile icon in the upper right, and select *Launch ThoughtSpot*.
. In ThoughtSpot, go to the *Admin Settings* tab.

=== Creating a role with AgentSpot privileges

To create a role with AgentSpot privileges, do the following:

. Under the *Admin Settings* tab, click *Roles*.
. Click *Create role*.
. In the _Create role_ window, enter a Role name and description.
. Click *AgentSpot Control*.
. Select one or more AgentSpot privileges for your role.
. Click *Review selection*.
. Review the role name, description, and admin controls.
. When you are ready to save your role, click *Save*.
. Create additional roles as needed.

=== Adding your role to a group

You can add your role to an existing group or a new group.

==== To add your role to an existing group, do the following:

. Under the Admin Settings tab, click *Groups*.
. Click the More menu associated with the group and select *Edit*.
. In the _Roles_ section, select the checkbox for the role(s) you want to add and click *Review selection*.
. Review the roles you added.
. When you are ready to save your group, click *Save*.

==== To add your role to new group, do the following:

. Under the Admin Settings tab, click Groups.
. Click *Create group*.
. In the _Create group_ window, do the following:
.. Enter a display name, group name, and description.
.. Specify if you want to allow others to share objects with the group.
.. Under _Select roles_, choose the AgentSpot privileges you want to add to the group.
.. Click *Review selection*.
.. Review the Roles you added.
.. When you are ready to save your group, click *Save*.

=== Adding users to a group

You can add users to an existing group or a new group.

==== To add a user to an existing group, do the following:

. Under the Admin Settings tab, click *Users*.
. Click the More menu associated with the user and select *Edit*.
. In the _Edit user_ window, select the group(s) you want to add the user to and click *Save*.

==== To add a user to a new group, do the following:

. Under the Admin Settings tab, click *Users*.
. Click *Add user*.
. In the _Add user_ window, do the following:
.. Enter a Usernam and a Display name.
.. Specify if you want to allow others to share objects with the user.
.. Under _Select Groups_, choose the group(s) you want to add to the user to.
.. Click *Add*.

== Admin Settings

In the Admin Settings page you can view and manage the AgentSpot workspace. It is organized into the following sections:

* *Connectors*: Allows you to manage connectors to different applications. See <<#managing-connectors,Managing connectors>>.
* *Usage*: Allows you to see the overall usage of AgentSpot. See <<#usage, Monitoring usage>>.
* *Users*: Allows you to see details about AgentSpot users. See <<#users, Monitoring users>>.
* *Settings*: Coming soon (based on the UI). See <<#settings, Setttings>>.

[#managing-connectors]
=== Managing connectors
Connectors allow AgentSpot to interact with external applications like Jira, Slack, and Clay.

As an administrator, you have the authority to:

* **Activate/Deactivate:** Enable or disable specific connectors for the entire organization (e.g., turning off Slack write-access if desired).
* **Test and share:** You can activate a connector for yourself to test its functionality before "publishing" or sharing it with the rest of the organization.

In the *Admin Settings* > *Connctors* page, you can see the list of Available Connectors. Once you add a connector, it appears in the list of Already Added connectors near the top of the page.

IMPORTANT: To add a connector, you must know the URL of the MCP server for that connector.

==== Available connectors
AgentSpot ships with native connectors for popular applications.

To add an available connector, do the following:

. Find the connector in the list of _Available Connectors_.
. In the box for the connector you want to add, click *Add*.
. In the _Custom Connector_ window, do the following:
.. (optional) Change the Connector Name if you want to.
.. Enter the Connector URL for the connector's MCP server.
.. (Optional) For *Transport Type*, select either of the following:
... Streamable HTTP (Recommended)
... Server-Sent Events (SSE)
.. (Optional) Enter a *Description*.
.. (Optional) Enter a *Logo URL*.
.. (Optional) Choose an *Authentication* method.
.. Click *Add Connector*.

==== Custom connectors
If a required application is not in the list of available connectors, you can add a custom connector using **MCP (Model Context Protocol) servers**. Simply provide the URL for the MCP server and complete the setup to enable any compatible tool.

To add a custom connector in AgentSpot, do the following:

. Log in to AgentSpot.
. Click the gear icon in the upper right, to open the _Admin Settings_ page.
. Under the _Connectors_ tab, click *+Custom Connector*.
. In the _Custom Connector_ window, do the following:
.. Enter a *Connector Name*.
.. Enter a *Connector URL*.
.. (Optional) For *Transport Type*, select either of the following:
... Streamable HTTP (Recommended)
... Server-Sent Events (SSE)
.. (Optional) Enter a *Description*.
.. (Optional) Enter a *Logo URL*.
.. (Optional) Choose an *Authentication* method.
.. Click *Add Connector*.

==== User authentication and security
Connectors do not require any setup for authentication because they follow the form of authentication that the user already uses to connect with the application.

When an admin enables a connector (e.g., Jira), each user must log in with their individual credentials. AgentSpot respects all existing permissions within the target app; users will only see data and perform actions they are already authorized to access.

[#usage]
=== Monitoring usage
The _Usage_ page provides high-level analytics to help you track the ROI and adoption of AgentSpot.

You can monitor the following:

* Total active users
* Number of conversations
* Connector usage frequency

[#users]
=== Monitoring users
The _Users_ page allows you to view detailed information about users and groups who use AgentSpot.

It provides the following information:

* *Users*
** *Role*: Member or Admin
** *Level*: Basic, Standard, or Power
** *Sessions*: Number of total sessions
** *Messages*: Total number of messages
** *Agents*: Total number of agents
** *Memories*: Total number of memories
** *Last Active*: Last time user was active
* *Groups*

[#settings]
=== Settings

UI says "Coming soon"


== Agent and workflow governance
Administrators have visibility over all agents and workflows created within the organization.

* **Visibility:** Admins can see every agent created, regardless of who the owner is.
* **Business continuity:** If a user leaves the company, an administrator can step in to manage, edit, or reassign the agents and workflows they created.

== Managing agents

As an administrator, you have access to all agents and workflows created within your organization:

* Once agents are created, you can share them with the appropriate teams so they are visible in their dashboard.
* If a user leaves the company, an administrator can step in to manage, edit, or reassign the agents and workflows they created.

=== View agents in your organization

To see all agents in your organization do the following:

. From the AgentSpot homepage, under _My Team_, click *View ALL*.
. Click *From My Org*.

=== Share an agent in your organization

To share an agent in your organization, do the following:

. From the AgentSpot homepage, click the agent you want to share.
. In the upper-right corner of the agent window, click *Share agent*.
. In the Share window, do the following:
.. In the *Add people or groups* field, find the people or group(s) to share with.
.. In the *Ready to share* field, confirm the people or group(s) to share with.
... For each person or group added, using the menu on the right to specify whether they *Can use* or *Can edit* the agent.
.. In the *People and groups with access* field, confirm the people and groups who already access and make changes, if needed.
.. Click *Done*.
+
The agent you shared will now appear the Agents dashboard for the people and groups you shared it with.
