name: Handle Fork PR Sync

on:
  pull_request_target:
    types: [closed]

jobs:
  trigger-sync:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Sync Workflow
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            await github.rest.repos.createDispatchEvent({
              owner: context.repo.owner,
              repo: context.repo.repo,
              event_type: 'sync-public-mirror',
              client_payload: {
                branch: context.payload.pull_request.base.ref,
                pr_number: context.payload.pull_request.number
              }
            });
